### ISSUE TITLE
视频缓冲问题

### ISSUE THREAD

**Issue by xiaohaibin** [CarGuo/GSYVideoPlayer#10]
视频缓冲时，如果触碰了播放界面，加载动画就停止了

**Comment by CarGuo** [comment]
哪个版本的？

**Comment by CarGuo** [comment]
我大致上看到了～

**Comment by CarGuo** [comment]
大致上看到了，下个版本我处理下，谢谢提醒~

**Comment by CarGuo** [comment]
1.3.5已经提交，如果可以请close~谢谢啦！

**Comment by xiaohaibin** [comment]
恩，谢谢，另外，我发现播放全屏播放视频时，视频没有充满屏幕，屏幕两边还有间隙，如果能够支持沉浸式最好了，我之前研究过一段时间vitamio的视频播放框架，最近才接触这个。

**Comment by CarGuo** [comment]
哪两边有间隙？上下还是左右？方便发个视频链接看看嘛？沉浸式其实播放的activity支持了应该就是了，有进去全屏和退出全屏接口，可以在这里做额外的操作！

**Comment by xiaohaibin** [comment]
恩，刚刚看到是有的，谢谢
