### ISSUE TITLE
大小屏不同布局设置全屏按钮，全屏时要闪退

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#1002]
是要做什么操作么，直接设置，全屏时，找不到图片资源

**Comment by CarGuo** [comment]
不是很理解，有log没，建议参考demo LandLayoutVideo

**Comment by i2863CookieZJ** [comment]
@CarGuo `video.setEnlargeImageRes(R.drawable.qy_video_to_fullscreen_selector);
        video.setShrinkImageRes(R.drawable.qy_video_to_normal_selector);
        video.setUp("http://vod.136.i2863.com/b8bd7e372b1440439a0818bd7a815403.mp4", false, "jhaahj");`
这是demo LandLayoutVideo 这样设置就会闪退，是否不能这样直接设置的

**Comment by CarGuo** [comment]
你可以參考 DanmkuVideoActivity

或者在LandLayoutVideo中重载
``


    @Override
    public int getEnlargeImageRes() {
            return R.drawable.custom_enlarge;
    }

    @Override
    public int getShrinkImageRes() {
        return R.drawable.custom_shrink;
    }
```

**Comment by i2863CookieZJ** [comment]
ok

**Comment by i2863CookieZJ** [comment]
重载依然出错

**Comment by i2863CookieZJ** [comment]
![error](https://user-images.githubusercontent.com/23622439/38595388-103227be-3d7e-11e8-8ec8-31e542b58cef.png)

**Comment by CarGuo** [comment]
你这个看起来不是播放器的问题，你可以更新下demo，我在LandLayoutVideo中重载后正常使用

**Comment by i2863CookieZJ** [comment]
我知道了，能使用的直接的图片，但是使用selecoter的drawable  我本来想加个点击效果的

**Comment by CarGuo** [comment]
都是imgeview控件设置图片而且，不支持的应该是drawable有问题

**Comment by i2863CookieZJ** [comment]
ok，是drawable的问题，感谢
