### ISSUE TITLE
问题机型 华为荣耀8 android7.0  先开启网易云音乐后台播放音乐 再打开 demo中detailplayer  进行全屏小屏切换 con全屏切换到小屏时 出现视频声音和后台音乐一起播放

### ISSUE THREAD

**Issue by RookieTree** [CarGuo/GSYVideoPlayer#1003]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by RookieTree** [comment]
问题机型 华为荣耀8 android7.0  先开启网易云音乐后台播放音乐 再打开 demo中detailplayer  进行全屏小屏切换 con全屏切换到小屏时 出现视频声音和后台音乐一起播放

**Comment by CarGuo** [comment]
收到问题
