### ISSUE TITLE
demo的视频播放不了？

### ISSUE THREAD

**Issue by slimvan** [CarGuo/GSYVideoPlayer#1004]
04-11 12:47:09.697 30513-30562/com.example.gsyvideoplayer W/System.err: java.lang.IllegalStateException
04-11 12:47:09.699 30513-30562/com.example.gsyvideoplayer W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer._prepareAsync(Native Method)
04-11 12:47:09.700 30513-30562/com.example.gsyvideoplayer W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.prepareAsync(IjkMediaPlayer.java:515)
04-11 12:47:09.700 30513-30562/com.example.gsyvideoplayer W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:515)
04-11 12:47:09.701 30513-30562/com.example.gsyvideoplayer W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$300(GSYVideoBaseManager.java:44)
04-11 12:47:09.701 30513-30562/com.example.gsyvideoplayer W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:469)
04-11 12:47:09.701 30513-30562/com.example.gsyvideoplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
04-11 12:47:09.701 30513-30562/com.example.gsyvideoplayer W/System.err:     at android.os.Looper.loop(Looper.java:203)
04-11 12:47:09.701 30513-30562/com.example.gsyvideoplayer W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

设备是魅族Pro6、华为P9 都播放不了 第一次使用 是我姿势不对吗？

**Comment by CarGuo** [comment]
哪个页面哪个视频，有可能链接过期了之类的

**Comment by slimvan** [comment]
所有页面的都是...我在源码中把链接拷贝到浏览器中是可以播放的   logcat报错信息在上面，我点击播放按钮的时候会打印上面的错误。

**Comment by CarGuo** [comment]
明白了，因为昨天在修改下个发布4.1.2的时候，出现存在一些问题，你再更新下demo就可以了。
或者修改gsyVideoPlayer 模块下的gradle依赖从   api project(':gsyVideoPlayer-java') 为 api "com.shuyu:gsyVideoPlayer-java:$gsyVideoVersion"

**Comment by slimvan** [comment]
嗯 现在没问题了 回答很效率~ 点赞~
