### ISSUE TITLE
大佬，请问为什么导入你的架包会出现如下error:Program type already present: android.support.v4.app.FragmentTransitionCompat21$1	

### ISSUE THREAD

**Issue by ChiShengCan** [CarGuo/GSYVideoPlayer#1006]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by lkkz** [comment]
我也遇到了
