### ISSUE TITLE
关于弹幕

### ISSUE THREAD

**Issue by Average77** [CarGuo/GSYVideoPlayer#1010]
## 问题描述：

弹幕用网络请求的 数据后，小屏没事儿，进入全屏会出现mParser为空。如果在cloneParams方法中st.mParser=sf.mParser写上这个后，全屏的时候就会出现弹幕一闪一闪的，还会提前消失，然后走好几遍。

## Demo中的复现步骤

demo中用raw中的数据并无此情况。

```

**Comment by CarGuo** [comment]
这里的区别应该就是数据源不同，出现这种情况个人觉得应该是对于大小屏之间，数据源应该是唯一的，只是渲染层切换，demo弹幕比较粗糙，需要看下在切换的时候，传递重构的支持渲染层，而数据源不变

**Comment by Average77** [comment]
我如果加载raw中的数据流，是没问题的，换成网络请求的，就算代码放在同样的地方，进入全屏也会出现一闪一闪的情况。猫大人的意思是，切换全屏的时候，数据源也变了是吗？ @CarGuo

**Comment by CarGuo** [comment]
首先，demo中是每次创建都会构建一个 private void initDanmaku()  -> mParser，所以你需要从外部设置一个 mParser进来，然后cloneParams的时候传递，而不是在内部创建。这样prepare的时候你的弹幕数据源就不会被重构了。

**Comment by Average77** [comment]
猫大人，我放到activity 创建 mParser也不行诶，还是闪，直接用raw的也不行了。 @CarGuo

**Comment by Average77** [comment]
猫大人，我放到activity 创建 mParser也不行诶，还是闪，直接用raw的也不行了。 @CarGuo

**Comment by CarGuo** [comment]
一闪一闪的情况是怎么样的？光文字有点抽象

**Comment by Average77** [comment]
有几种情况，有时候是     弹幕的字会突然速度加快，我设置的弹幕条数比较少，只有四五条，当这四五条都走出屏幕的时候，后两三条会再出现，然后再走一遍，最后一条会在左上角走好几遍。
还有的时候是   弹幕的字一闪一闪的，就是一下子有一下子没有，很快，看起来就像是一闪一闪的。
还有的情况是  像是有两个，在下面还有一个，两层距离很近，下面的那层颜色比较浅 @CarGuo

**Comment by Average77** [comment]
raw里获取的数据，就算cloneParams里不写st.mParser=sf.mParser;   mParser也不为空，但是网络请求的，就不行诶。

**Comment by Average77** [comment]
我发现第一次全屏的时候会闪，如果进去全屏，然后按返回键回到小屏，再进全屏，就没事儿了。猫大人，你知道这是为什么吗？ @CarGuo

**Comment by CarGuo** [comment]
如果你方便提供流和代码我调试看看咯

**Comment by Average77** [comment]
好哒好哒，谢谢猫大人，我到公司了发您，万分感谢

**Comment by Average77** [comment]
[https://github.com/Average77/test2](url)   猫大人，我传到github上了。 @CarGuo

**Comment by Average77** [comment]
DanmakuVideoPlayer 里面，如果放到initDanmaku 里面请求，是第一次闪，然后进入小屏，滑到最开始，然后再进大屏，不闪。如果用这个方法setDanmuData，外部调用的话，是怎么都闪

**Comment by Average77** [comment]
为什么mParser=  createParser(mContext.getResources().openRawResource(R.raw.comments));这样写不需要在cloneParams方法里传递，但是网络请求的就需要cloneParams传递呢？我发现就是cloneParams里传递的话，就会闪 @CarGuo

**Comment by CarGuo** [comment]
我简单的在刚刚提交的danmku分支上修改了demo，不过你给的链接弹幕太少，看不出来，你可以看看

**Comment by Average77** [comment]
好了，QAQ，太感谢了，猫大人棒棒哒~ヾ(✿ﾟ▽ﾟ)ノ

**Comment by kyriej** [comment]
@老哥，大小屏切换时，置顶置底弹幕位置错乱，有解决方案没

**Comment by androidwzl** [comment]
可以说一下解决思路和方法么，我目前也有这种情况。全屏弹幕不显示，如果在cloneParams方法中st.mParser=sf.mParser写上这个后，全屏的时候就会出现弹幕一闪一闪的，还会提前消失，然后走好几遍。

**Comment by guojilong** [comment]
@Average77  hello 方便说下怎么解决的么，目前也遇到这个问题，横屏之后，弹幕会多出一些，并且会闪烁

**Comment by guojilong** [comment]
@CarGuo 我目前也遇到这个问题了，可以说下解决思路么
