### ISSUE TITLE
Https不能播放

### ISSUE THREAD

**Issue by whj33** [CarGuo/GSYVideoPlayer#1013]
请问一下我在Demo中运行https的源是可以播放的，但是集成到项目里却报这个

 Protocol not found

请问大概是什么问题呢 @CarGuo

**Comment by CarGuo** [comment]
demo不复现的问题···我也很难定位☹

**Comment by whj33** [comment]
请问，支持https的话除了so库还有其他需要配置的吗

**Comment by whj33** [comment]
我测试了几个链接，都是以Https开头的    就是播放不出来，然后我直接重新拼接了一遍，直接去掉S  以Http开头  发现也能播放   真是奇怪呢

**Comment by whj33** [comment]
请问大神   按常理来说是不可以播放的啊   为什么去掉S还能播放啊  0- 0

**Comment by CarGuo** [comment]
这个就要看服务器是否强制只能https播放了。至于这个现象，你需要确定你本地或者其他依赖，是否依赖了或者使用了ijk的so，ijk默认的so是不支持https的
