### ISSUE TITLE
怎么样才能播放RTMP格式的流呢

### ISSUE THREAD

**Issue by Li-Yuwei** [CarGuo/GSYVideoPlayer#1014]
我在demo里直接改的播放地址 remp://...  这样的不能播放

**Comment by CarGuo** [comment]
修改so的依赖为ex_so，屏蔽其他so

**Comment by Born-alone** [comment]
可以直接播放rtmp的流呀 直接换成rtmp的地址就行

**Comment by Li-Yuwei** [comment]
还是不能播，，，

**Comment by CarGuo** [comment]
使用ex so可以支持rtmp，如果不行再配置tcp，可见问题详解，再不行就看视频编码和连接协议是否兼容
