### ISSUE TITLE
Demo横竖屏切换区别！

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#1015]
现在有一个问题  就是在横屏状态下自动播放下一个视频时有声音无画面  竖屏的时候自动播放下一个是正常的
我是参考Demo中 DetailPlayer页面 实现的功能  我试着在Demo 中 DetailPlayer 页面播放完成的回调中播放下一个视频资源 发现出现的问题跟我项目出现的问题是一样的 
![_20180413184659](https://user-images.githubusercontent.com/25575326/38730980-3ffec276-3f4b-11e8-9dbf-e482dd533b46.png)

想请问一下 DetailPlayer 页面 与 DetailListPlayer页面实现自动播放下一视频有什么区别？

**Comment by CarGuo** [comment]
detaillist的用的是内置的ListGSYVideoPlayer

**Comment by Born-alone** [comment]
我看那个内置的ListGSYVideoPlayer里面也没有什么区别呀 只不过用的是setUp方法




| |
18600886046
邮箱：18600886046@163.com
|

签名由 网易邮箱大师 定制

在2018年04月14日 15:24，Shuyu Guo 写道：

detaillist的用的是内置的ListGSYVideoPlayer

**Comment by CarGuo** [comment]
ListGSYVideoPlayer 内部做了切换下一集的处理，比如在全屏和非全屏的切换同步

**Comment by Born-alone** [comment]
请问能告知具体是体现在哪些方法嘛？

**Comment by CarGuo** [comment]
你看源码不就知道了么？ListGSYVideoPlayer的重载方法并不多
