### ISSUE TITLE
希望能添加支持 wmv的格式

### ISSUE THREAD

**Issue by wang869755676** [CarGuo/GSYVideoPlayer#1018]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
自己编译下so，替换即可，编辑方法首页有
