### ISSUE TITLE
全屏时按实体返回键会直接退出activity

### ISSUE THREAD

**Issue by qq798863415** [CarGuo/GSYVideoPlayer#1019]
全屏时按实体返回键会直接退出activity，想要退出全屏该怎么办？还有全屏时视频超出了屏幕。

**Comment by CarGuo** [comment]
demo中哪里复现

**Comment by qq798863415** [comment]
我继承StandardGSYVideoPlayer写了一个自己的player

**Comment by CarGuo** [comment]
直接退出activity应该是你没有对Activity的的返回键监听上做处理，参考demo就好了

**Comment by qq798863415** [comment]
onbackpressed吗？我这样写了还是不行
@Override
    public void onBackPressed() {

        if (orientationUtils != null) {
            orientationUtils.backToProtVideo();
        }

        if (StandardGSYVideoPlayer.backFromWindowFull(this)) {
            return;
        }
        super.onBackPressed();
    }

**Comment by CarGuo** [comment]
你参考demo吧，demo是正常的
