### ISSUE TITLE
双击事件与单击事件冲突

### ISSUE THREAD

**Issue by a1018875550** [CarGuo/GSYVideoPlayer#1020]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

双击事件与单击事件冲突

## 问题机型/系统：

所有机型

## Demo中的复现步骤

双击播放页面

**Comment by CarGuo** [comment]
现象是？

**Comment by a1018875550** [comment]
双击本来只应该是暂停或者播放视频，现在双击 top bottom view 显示与影藏并发了

**Comment by CarGuo** [comment]
推荐你继承后处理，内部方法目前也都是protect

**Comment by CarGuo** [comment]
已修复，下版本更新处理
