### ISSUE TITLE
无法播放sd卡下视频

### ISSUE THREAD

**Issue by wangxp423** [CarGuo/GSYVideoPlayer#1021]
设置url为本地的
String url3 = Environment.getExternalStorageDirectory().getPath().concat("/test-xiaoye.mp4");
无法播放，本地MP4,rm文件格式都无法播放，
我想知道这个跟编译.so文件有关吗？
机型是红米手机 系统6.0.1

日志如下：
04-17 16:39:32.407 12096-12158/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_create_from_android()
04-17 16:39:32.408 12096-12158/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque(0x20063e)
    ijkmp_set_inject_opaque()=void
    ijkmp_set_ijkio_inject_opaque(0x20063e)
04-17 16:39:32.413 12096-12158/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
    ijkmp_android_set_mediacodec_select_callback()
    ffpipeline_set_mediacodec_select_callback
    ijkmp_android_set_mediacodec_select_callback()=void
04-17 16:39:32.414 12096-12158/com.example.gsyvideoplayer W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.shuyu.gsyvideoplayer.player.IJKPlayerManager.initVideoPlayer(IJKPlayerManager.java:71)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:504)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$300(GSYVideoBaseManager.java:44)
04-17 16:39:32.415 12096-12158/com.example.gsyvideoplayer W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:469)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by CarGuo** [comment]
rm现在的so是播放不了

首先确定是否文件是否存在，通过file判断下，然后看看设置中demo是否有读写sd卡的权限，因为demo中没做动态权限获取，最后看mp4的视频编码和音频编码

**Comment by wangxp423** [comment]
我在跑ijkplayer的时候，最开始运行异常，异常的地方是下面第一行
        IjkMediaPlayer.loadLibrariesOnce(null);
        IjkMediaPlayer.native_profileBegin("libijkplayer.so");
后来加入.os文件以后能运行了。但是我在看你的demo的时候，发现你并没有调用这两个方法，但是你编译.so文件了。而我在看另一个github上的项目的时候，
他直接是：
compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'
compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.8'
这样通过使用IjkMediaPlayer 配合 TextureView也能播放在线视频，一般是.mp4.. 但是https的貌似不行，rm格式的也不行。
这个时候是不是需要配合.so文件就可以了？ 因为我是windows系统。所以编译有点没法，暂时没有编译过。所以对于.so文件有一些疑问。
这里的编译.so文件主要是用来支持编解码的是吗？对于不同格式的音视频文件，在编译的时候有配置方法是吗？
因为目前发现网上关于音视频方面的资料不是很多，还请指教。

**Comment by CarGuo** [comment]
ijk是在加载类的时候，默认就会去初始化加载so，demo中的so是通过远程依赖实现的。

gsy修改编译的so加入了https的支持，然后带ex_so的so增加了rtsp，rtmp，concat等支持

默认的ijk so是不支持https

so文件是，ijk基于ffmpeg修改的到的，通过配置文件制定需要支持的格式，支持格式越多so越大

**Comment by rosuH** [comment]
@CarGuo 你好，我也遇到了类似报错，无法播放视频的情况。

---
Logcat：

```shell
09-11 21:30:37.457 14890-14909/me.rosuh.videofilecheckdemo W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
09-11 21:30:37.458 14890-14909/me.rosuh.videofilecheckdemo W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:592)
09-11 21:30:37.459 14890-14909/me.rosuh.videofilecheckdemo W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:556)
        at android.os.Handler.dispatchMessage(Handler.java:106)
09-11 21:30:37.460 14890-14909/me.rosuh.videofilecheckdemo W/System.err:     at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)

```

## 环境

1. 机型：华为荣耀畅玩7 DUA-AL00
2. 系统：EMUI 8.0.0 base on Android 8.1.0
3. 视频存放在内置存储或 SD 卡都不能播放

## 视频格式

```shell
General
Count                                    : 332
Count of stream of this kind             : 1
Kind of stream                           : General
Kind of stream                           : General
Stream identifier                        : 0
Count of video streams                   : 1
Count of audio streams                   : 1
Video_Format_List                        : AVC
Video_Format_WithHint_List               : AVC
Codecs Video                             : AVC
Audio_Format_List                        : AAC LC
Audio_Format_WithHint_List               : AAC LC
Audio codecs                             : AAC LC
Complete name                            : Desktop/hiv00000.mp4
Folder name                              : Desktop
File name                                : hiv00000.mp4
File name                                : hiv00000
File extension                           : mp4
Format                                   : MPEG-PS
Format                                   : MPEG-PS
Format/Extensions usually used           : mpeg mpg m2p vob vro pss evo
Commercial name                          : MPEG-PS
Internet media type                      : video/MP2P
File size                                : 268435456
File size                                : 256 MiB
File size                                : 256 MiB
File size                                : 256 MiB
File size                                : 256 MiB
File size                                : 256.0 MiB
Duration                                 : 44063645
Duration                                 : 12 h 14 min
Duration                                 : 12 h 14 min 23 s 645 ms
Duration                                 : 12 h 14 min
Duration                                 : 12:14:23.645
Duration                                 : 12:14:23.645
Overall bit rate mode                    : VBR
Overall bit rate mode                    : Variable
Overall bit rate                         : 48736
Overall bit rate                         : 48.7 kb/s
File last modification date              : UTC 2018-09-11 01:32:57
File last modification date (local)      : 2018-09-11 09:32:57
FileExtension_Invalid                    : mpeg mpg m2p vob vro pss evo

Video
Count                                    : 347
Count of stream of this kind             : 1
Kind of stream                           : Video
Kind of stream                           : Video
Stream identifier                        : 0
StreamOrder                              : 0
FirstPacketOrder                         : 0
ID                                       : 224
ID                                       : 224 (0xE0)
Format                                   : AVC
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format/Url                               : http://developers.videolan.org/x264.html
Commercial name                          : AVC
Format profile                           : Main@L4.2
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 1
Format settings, ReFrames                : 1 frame
Internet media type                      : video/H264
Duration                                 : 44063645
Duration                                 : 12 h 14 min
Duration                                 : 12 h 14 min 23 s 645 ms
Duration                                 : 12 h 14 min
Duration                                 : 12:14:23.645
Duration                                 : 12:14:23.645
Width                                    : 1920
Width                                    : 1 920 pixels
Height                                   : 1080
Height                                   : 1 080 pixels
Stored_Height                            : 1088
Sampled_Width                            : 1920
Sampled_Height                           : 1080
Pixel aspect ratio                       : 1.000
Display aspect ratio                     : 1.778
Display aspect ratio                     : 16:9
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Chroma subsampling                       : 4:2:0
Bit depth                                : 8
Bit depth                                : 8 bits
Scan type                                : Progressive
Scan type                                : Progressive
Delay                                    : 184989.484
Delay                                    : 3 min 4 s
Delay                                    : 3 min 4 s 989 ms
Delay                                    : 3 min 4 s
Delay                                    : 00:03:04.989
Delay, origin                            : Container
Delay, origin                            : Container
Color range                              : Full
colour_description_present               : Yes
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
Count                                    : 277
Count of stream of this kind             : 1
Kind of stream                           : Audio
Kind of stream                           : Audio
Stream identifier                        : 0
StreamOrder                              : 1
FirstPacketOrder                         : 1
ID                                       : 192
ID                                       : 192 (0xC0)
Format                                   : AAC
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Commercial name                          : AAC
Format version                           : Version 4
Format_AdditionalFeatures                : LC
Muxing mode                              : ADTS
Codec ID                                 : 2
Duration                                 : 44063644
Duration                                 : 12 h 14 min
Duration                                 : 12 h 14 min 23 s 644 ms
Duration                                 : 12 h 14 min
Duration                                 : 12:14:23.644
Duration                                 : 12:14:23.644
Bit rate mode                            : VBR
Bit rate mode                            : Variable
Channel(s)                               : 1
Channel(s)                               : 1 channel
Channel positions                        : Front: C
Channel positions                        : 1/0/0
Channel layout                           : C
Samples per frame                        : 1024
Sampling rate                            : 16000
Sampling rate                            : 16.0 kHz
Samples count                            : 705018304
Frame rate                               : 15.625
Frame rate                               : 15.625 FPS (1024 SPF)
Compression mode                         : Lossy
Compression mode                         : Lossy
Delay                                    : 184992.000
Delay                                    : 3 min 4 s
Delay                                    : 3 min 4 s 992 ms
Delay                                    : 3 min 4 s
Delay                                    : 00:03:04.992
Delay, origin                            : Container
Delay, origin                            : Container
Delay relative to video                  : 3
Delay relative to video                  : 3 ms
Delay relative to video                  : 3 ms
Delay relative to video                  : 3 ms
Delay relative to video                  : 00:00:00.003
```

---

因为没有什么头绪，所以麻烦给一点思路，谢谢~

**Comment by rosuH** [comment]
在 一加3T上测试了，也无法播放。是视频格式的问题吗？

**Comment by CarGuo** [comment]
@rosuH 1、试试用ex_so依赖。2、或者切换到exoplayer内核试试。

**Comment by rosuH** [comment]
@CarGuo 报了另一个错误：

> 09-12 09:42:20.409 17124-17185/me.rosuh.videofilecheckdemo E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:927)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:849)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:780)
09-12 09:42:20.415 17124-17141/me.rosuh.videofilecheckdemo E/EventLogger: playerFailed [0.94]
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:349)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:927)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:849)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:780)

我之前单独使用 EXOPlayer 时候就是报这个错误。

---
使用  README 中的方法切换到 exoplayer 内核

```xml
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation('com.shuyu:gsyVideoPlayer-java:6.0.0-beta') {
        exclude group: 'com.android.support'
    }
    implementation ('com.shuyu:GSYVideoPlayer-exo2:6.0.0-beta'){
        exclude group: 'com.android.support'
    }
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```

```java
File file = new File(Environment.getExternalStorageDirectory() + "/hiv00001.mp4");
Log.i(TAG, "onCreate: file is exist =====>>>> " + file.exists());
PlayerFactory.setPlayManager(new Exo2PlayerManager());
player.setUp(Environment.getExternalStorageDirectory() + "/hiv00001.mp4", false, "ss");

```

---

感谢回复~

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(new Exo2PlayerManager()); 去掉

然后依赖改为 

```
 implementation('com.shuyu:gsyVideoPlayer-java:6.0.0-beta') {
        exclude group: 'com.android.support'
}
implementation ('com.shuyu:gsyVideoPlayer-ex_so:6.0.0-beta'){
        exclude group: 'com.android.support'
}

```

试试，如果还不行说明so不支持这类格式

**Comment by rosuH** [comment]
@CarGuo 
去掉或者使用`IJKPlayerManager`，都会报楼主的错误：

> 09-12 10:04:54.028 18766-18787/me.rosuh.videofilecheckdemo W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
09-12 10:04:54.029 18766-18787/me.rosuh.videofilecheckdemo W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:592)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:556)
09-12 10:04:54.030 18766-18787/me.rosuh.videofilecheckdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by rosuH** [comment]
@CarGuo Demo 下无法复现(･д･｀o)

---
感谢回复~

**Comment by happyHou** [comment]
我也遇到这个问题，后来解决了，本地路径如果是字符串scheme为空是必然。使用com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView#setUp(java.lang.String, boolean, java.io.File, java.lang.String)中的方法cacheWithPlay：true,cachePath:本地路径用File包装一下。
