### ISSUE TITLE
一个广告的小问题，还请大神看一下

### ISSUE THREAD

**Issue by Angelvzp** [CarGuo/GSYVideoPlayer#1022]
## 问题描述：
在DetailADPlayer2中发生了这样的问题！

## Demo中的复现步骤

Demo中的DetailADPlayer2中
public class DetailADPlayer2 extends GSYBaseADActivityDetail<NormalGSYVider, GSYADVideoPlayer> 中把NormalGSYVider换成SampleVideo,并按示例去修改xml和代码，点击切换清晰度的时候，切换成功后又开始重新从广告开始播，我写了一个方法，把切换后isNeedAdOnStart()变成了false不出现广告了，但是播放后就有问题了

**Comment by CarGuo** [comment]
这个你可以看下源码GSYBaseADActivityDetail，你切换清晰度之后，主播放器应该再出发了一遍onPrepared，这时候又会再出发一次 startAdPlay()，所以你可以重载onPrepared去做一些状态判断

**Comment by Angelvzp** [comment]
嗯嗯，已经好了，谢谢大神
