### ISSUE TITLE
startWindowFullscreen 出现下表越界异常。

### ISSUE THREAD

**Issue by canglen** [CarGuo/GSYVideoPlayer#1023]
使用的 GSYSampleADVideoPlayer 
然后代码是
detailPlayer 的demo 拷贝过来
url 就是demo的url
String url = "http://video.7k.cn/app_video/20171202/6c8cf3ea/v.m3u8.mp4";
但是当点击 全屏按钮的时候 出现下标越界，
点进去查看后是 父类 ListGSYVideoPlayer 的
 public GSYBaseVideoPlayer startWindowFullscreen(Context context, boolean actionBar, boolean statusBar) 方法的这一行
 GSYVideoModel gsyVideoModel = mUriList.get(mPlayPosition);
报错

吧GSYSampleADVideoPlayer  替换为StandardGSYVideoPlayer 之后 依然出现下标越界异常。
报错代码还是上面那一句。
还忘有遇到过这个问题的大佬帮忙解决一下。
布局为 
` 
<android.support.design.widget.CoordinatorLayout >

   <android.support.design.widget.AppBarLayout>

      <android.support.design.widget.CollapsingToolbarLayout>

          <LinearLayout>

              <com.shuyu.gsyvideoplayer.video.GSYSampleADVideoPlayer/>

         </LinearLayout>

         <android.support.v7.widget.Toolbar/>

      </android.support.design.widget.CollapsingToolbarLayout>

          <android.support.design.widget.TabLayout/>

    </android.support.design.widget.AppBarLayout>

    <android.support.v4.widget.NestedScrollView>

         <android.support.v4.view.ViewPager/>

    </android.support.v4.widget.NestedScrollView>

</android.support.design.widget.CoordinatorLayout>
`

**Comment by CarGuo** [comment]
demo怎么复现

**Comment by canglen** [comment]
把布局里面的 
com.shuyu.gsyvideoplayer.video.GSYSampleADVideoPlayer
更换为
com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
后问题解决。
只是在滑动的时候好像不是太顺畅。。
