### ISSUE TITLE
startWindowFullscreen开启全屏的方法中super.startWindowFullscreen(context, actionBar, statusBar);返回的null

### ISSUE THREAD

**Issue by KafukaChen** [CarGuo/GSYVideoPlayer#1024]
自定义播放器UI集成StandardGSYVideoPlayer后，
在开启全屏时重写的startWindowFullscreen（Context context, boolean actionBar, boolean statusBar）方法
但是偶尔会出现父类返回的对象为null的情况，super.startWindowFullscreen(context, actionBar, statusBar)返回null。打断点进入GSYBaseVideoPlayer后发现，该类的startWindowFullscreen方法中
hadNewConstructor == true；548行的 gsyVideoPlayer = constructor.newInstance(getActivityContext(), true);报错，捕获的错误类型是java.long.reflect.InvocationTargetException.
这个问题有时出现有时没有，确保未更改响应代码

总结下就是GSYBaseVideoPlayer中startWindowFullscreen方法的try catch捕获到java.long.reflect.InvocationTargetException.

**Comment by CarGuo** [comment]
你是继承了StandardGSYVideoPlayer，有没重载
```
这个构造方法
 public XXXX(Context context, Boolean fullFlag) 
```

**Comment by KafukaChen** [comment]
重载了，方法名报灰，应该是没使用到

**Comment by KafukaChen** [comment]
问题偶然的，不能确定是改了哪里，发生两次。。还有这个构造
public XXXX(Context context, Boolean fullFlag) 
不重载的话，因为我全屏切换时返回的两套不同的layout，不重载的的话不管是否全屏都只会加载同一个layout，就是非全屏的layout。
博主还有一个问题，就是我在
 @Override
    public int getLayoutId() {
        if (mIfCurrentIsFullscreen) {
            //全屏布局
            return R.layout.layout_video_time_flow_full;
        }
        //列表布局
        return R.layout.layout_video_time_flow_list;
    }
中返回的两套布局，底部的进度条bottom_progressbar设置了相同的样式，但是非全屏的进度条不起作用，只显示背景不显示加载进度，全屏的就有用，demo中也复现不了。。。。

**Comment by CarGuo** [comment]
public XXXX(Context context, Boolean fullFlag) 这是必须重载才会返回两套布局是没问题的。

至于demo复现不了，我也定位不了啊
