### ISSUE TITLE
集成问题

### ISSUE THREAD

**Issue by xuzhaolezi** [CarGuo/GSYVideoPlayer#1025]
## 问题描述
直接将java代码复制到项目中，  在app-libs下放入ijkplayer的armeabi-v7a，在app的build.gradle中添加compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'，运行到手机时报
 NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.getChildCount()'，
at gsyvideoplayer.render.view.GSYTextureView.addTextureView(GSYTextureView.java:269)

还有就是报
UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xzl.joke-2/base.apk", zip file "/data/app/com.xzl.
但是我只有一个armeabi-v7a啊。
## 问题机型/系统：

真机  华为JMM-AL00  7.0

**Comment by CarGuo** [comment]
textureViewContainer 是空，什么导致的你可以找找。
至于loader UnsatisfiedLinkError，可以试试添加ndk过滤
