### ISSUE TITLE
默认设置横屏，全屏后取消全屏，设置为竖屏了

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#1028]
问题代码：(如果有)

![tim 20180419104359](https://user-images.githubusercontent.com/13781886/38968562-97fab800-43be-11e8-83d1-8319f4b33bf4.png)

## 问题
默认设置横屏，全屏后取消全屏，设置为竖屏了

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/effect/BitmapIconEffect.java     demo参考DetailFilterActivity

```
     /*Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher);
        mGSYVideoGLViewCustomRender = new GSYVideoGLViewCustomRender();
        mCustomBitmapIconEffect = new BitmapIconEffect(bitmap, dp2px(50), dp2px(50), 0.6f);
        mGSYVideoGLViewCustomRender.setBitmapEffect(mCustomBitmapIconEffect);
        detailPlayer.setCustomGLRenderer(mGSYVideoGLViewCustomRender);
        detailPlayer.setGLRenderMode(GSYVideoGLView.MODE_RENDER_SIZE);*/
```

**Comment by CarGuo** [comment]
你是通过哪个页面实现的，如果不需要竖屏的时候，都不需要用到orientationUtils
