### ISSUE TITLE
请问播放时怎么添加水印，看了好久没看到文档介绍的相关api

### ISSUE THREAD

**Issue by Saturdaycong** [CarGuo/GSYVideoPlayer#1029]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/effect/BitmapIconEffect.java demo参考DetailFilterActivity

     /*Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher);
        mGSYVideoGLViewCustomRender = new GSYVideoGLViewCustomRender();
        mCustomBitmapIconEffect = new BitmapIconEffect(bitmap, dp2px(50), dp2px(50), 0.6f);
        mGSYVideoGLViewCustomRender.setBitmapEffect(mCustomBitmapIconEffect);
        detailPlayer.setCustomGLRenderer(mGSYVideoGLViewCustomRender);
        detailPlayer.setGLRenderMode(GSYVideoGLView.MODE_RENDER_SIZE);*/

**Comment by Saturdaycong** [comment]
好的谢谢，我试试

**Comment by CarGuo** [comment]
DetailFilterActivity
