### ISSUE TITLE
全屏退出之后 再切换新的视频源 setup失败

### ISSUE THREAD

**Issue by junchenChow** [CarGuo/GSYVideoPlayer#103]
我看了下代码 setup 方法里面这个`if (isCurrentMediaListener() &&(System.currentTimeMillis() - CLICK_QUIT_FULLSCREEN_TIME) < FULL_SCREEN_NORMAL_DELAY)return false;` 导致的 。
这个if 用来干嘛的看不懂， FULL_SCREEN_NORMAL_DELAY 写死的2000L又是何解。
这样的判断，假如我有一个视频列表，我播放第一个视频，然后点击全屏再退出全屏，这个时候，如果切换视频播放地址播放新的视频，如果时间在2秒以内，我setup就是不成功的，这样就导致，我切换视频无效。

**Comment by CarGuo** [comment]
如果是列表播放，请参考列表播放的播放器，有一个LIST的，因为默认是一个播放完了释放播放，这时候在没有释放完成之前，你设置什么都是没用的，列表播放器是在结束中拦截释放。
