### ISSUE TITLE
 请问如何仅使用ExoPlayer，并且不需要包含ijkplayer的依赖

### ISSUE THREAD

**Issue by AricGuo** [CarGuo/GSYVideoPlayer#1030]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
只依赖java代码，然后参考demo 实现 自定义  Manager 和 playerManager （已经实现的EXO2PlayerManager）
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/manager/CustomManager.java 

ps，exoplayer最好搭配surfaceview模式GSYVideoType.setRenderType(GSYVideoType.SUFRACE);，至于如果嫌弃java层带有ijk代码，可以在远程依赖的时候exclude掉
