### ISSUE TITLE
播放一段网络视频会请求好几次，为什么？

### ISSUE THREAD

**Issue by NFLeo** [CarGuo/GSYVideoPlayer#1034]
## 问题描述：
抓包发现 播放一段网络视频会请求好几次，为什么？

**Comment by CarGuo** [comment]
什么意思？播放什么协议的视频？

**Comment by NFLeo** [comment]
拿你demo里面的视频放到AS 查看网络监测，发现同一个视频会有好几段请求，别的视频也是一样

**Comment by NFLeo** [comment]
关于视频的播放信息参数可以回调出来嘛，比如说域名解析花了多久，连接服务器花了多久这些。因为在调短视频秒开，线上的视频比测试服慢很多

**Comment by CarGuo** [comment]
目前不支持
