### ISSUE TITLE
后台播放一段时间后断开

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#104]
后台播放到percent 59 就断了。
播放url：“http://cdn-media.jingzong.org/mp4/02/02-041/02-041-0001.mp4”
播放m3u8， 几分钟就断开了
m3u8 url："http://hls.ciguang.tv/hdtv/video.m3u8"

[后台播放log.txt](https://github.com/CarGuo/GSYVideoPlayer/files/844253/log.txt)

**Comment by CarGuo** [comment]
缓存关闭了的情况下么？

**Comment by Wangct23** [comment]
是的, 緩存關閉了.
