### ISSUE TITLE
请问为什么我第三种依赖也播放不了rtsp

### ISSUE THREAD

**Issue by GirlFriendNotFind** [CarGuo/GSYVideoPlayer#1041]
![1](https://user-images.githubusercontent.com/33824120/39236905-9c1996ca-48ac-11e8-86b8-1566c3def247.png)
![2](https://user-images.githubusercontent.com/33824120/39236900-9834483e-48ac-11e8-88fe-cc9c87fa09f8.png)
![3](https://user-images.githubusercontent.com/33824120/39236928-aefecde6-48ac-11e8-83be-65d94c76a68d.png)
![4](https://user-images.githubusercontent.com/33824120/39236943-b71902a8-48ac-11e8-95ea-5d0ad35b4853.png)
![5](https://user-images.githubusercontent.com/33824120/39236946-b9df8b92-48ac-11e8-8a26-d87066bd4961.png)
![6](https://user-images.githubusercontent.com/33824120/39236951-bbd9117a-48ac-11e8-9fe6-b3072e53bb7e.png)
![7](https://user-images.githubusercontent.com/33824120/39236957-bde702d8-48ac-11e8-9b53-a62b5d8d39c7.png)
![8](https://user-images.githubusercontent.com/33824120/39236963-c0c88c38-48ac-11e8-9993-3caeea21c501.png)

不知道哪些是关键日志

**Comment by CarGuo** [comment]
参考问题集锦，设置tcp连接试试

**Comment by GirlFriendNotFind** [comment]
![9](https://user-images.githubusercontent.com/33824120/39281606-18bfe6f8-4938-11e8-8bab-913412935502.png)
![10](https://user-images.githubusercontent.com/33824120/39281609-1b60e858-4938-11e8-8264-4e8176cb9a22.png)
![11](https://user-images.githubusercontent.com/33824120/39281610-1ce1cc2e-4938-11e8-9428-3d0c8d950ba9.png)
已经设置过的了~~

**Comment by CarGuo** [comment]
![](https://user-images.githubusercontent.com/10770362/39284455-f195b28e-4945-11e8-9ef7-9d642ecb9c23.png)

**Comment by GirlFriendNotFind** [comment]
啊，也就是设置没有生效吗，那个api应该是全局的设置啊，，，，，我再看看

**Comment by GirlFriendNotFind** [comment]
这，，，好吧，本来用vlc的但是vlc分屏播放不好搞

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/QUESTION.md - > 17、rtsp连接有问题
