### ISSUE TITLE
No such file perf_event.h when compile ffmpeg

### ISSUE THREAD

**Issue by kimnamcham** [CarGuo/GSYVideoPlayer#1042]
When i compile ffmpeg, i have some problem. Here is log compile:

n file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/avassert.h:31,
                 from libavfilter/aeval.c:26:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
 # include <linux/perf_event.h>
                               ^
compilation terminated.
make: *** [libavfilter/aeval.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/avassert.h:31,
                 from libavfilter/af_aecho.c:21:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
 # include <linux/perf_event.h>
                               ^
compilation terminated.
In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/opt.h:31,
                 from libavfilter/af_acrusher.c:21:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
 # include <linux/perf_event.h>
                               ^
compilation terminated.
In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/opt.h:31,
                 from libavfilter/af_aemphasis.c:21:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
 # include <linux/perf_event.h>
ake: *** [libavfilter/af_aecho.o] Error 1
[K                               ^
compilation terminated.
In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/audio_fifo.h:30,
                 from libavfilter/af_afftfilt.c:21:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
 # include <linux/perf_event.h>
                               ^
compilation terminated.
In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/audio_fifo.h:30,
                 from libavfilter/af_afade.c:26:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/opt.h:31,
                 from libavfilter/af_adelay.c:22:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
 # include <linux/perf_event.h>
                               ^
make: In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from libavfilter/avfilter.h:41,
                 from libavfilter/audio.h:25,
                 from libavfilter/af_acopy.c:19:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
 *** [libavfilter/af_acrusher.o] Error 1# include <linux/perf_event.h>

How can i resolve this?

**Comment by CarGuo** [comment]
try this: https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite.sh 
compile-ijk.sh clear   compile-ffmpeg.sh clear   compile-openssl.sh clear first

**Comment by kimnamcham** [comment]
@CarGuo Thanks, i will try it

**Comment by RajivKulkarni707** [comment]
Hi, this is Rajiv.
I  still have the same issue.
All steps from README.sh work first time.
But, if I modify config.sh ( so that I can enable RTSP ) and then try to do all these steps, I get the same error as follows :->
==========================

In file included from ./libavutil/internal.h:42:0,
                 from ./libavutil/common.h:467,
                 from ./libavutil/avutil.h:296,
                 from ./libavutil/avassert.h:31,
                 from libavfilter/aeval.c:26:
./libavutil/timer.h:38:31: fatal error: linux/perf_event.h: No such file or directory
 # include <linux/perf_event.h>
                               ^
compilation terminated.
make: *** [libavfilter/aeval.o] Error 1

=========================================
Thanks in advance.

Rajiv Kulkarni

**Comment by CarGuo** [comment]
android-ndk-r13b

**Comment by RajivKulkarni707** [comment]
Thanks CarGuo, I am able to compile!

Still do not know how to enable "RTSP" .

My url is "rtsp://192.168.1.12:8080/h264.sdp"

When I select "IjkMediaPlayer", and run the url, I get following error:->

**E/IJKMEDIA: rtsp://192.168.1.12:8080/h264.sdp: Protocol not found**

Any help appreciated.

Thanks

Rajiv Kulkarni

**Comment by CarGuo** [comment]
Like ：https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh

or try

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'

implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.3'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.3'
