### ISSUE TITLE
GsyVideoView  更换后，setplayPosition 无效

### ISSUE THREAD

**Issue by zzp880303** [CarGuo/GSYVideoPlayer#1043]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
我们在做全屏功能，需要用到两个gsyVideoView,需要记录播放位置，切换全屏/非全屏时使用；
GsyVideoView  更换后，setplayPosition 无效

## 问题机型/系统：
泰捷盒子

## Demo中的复现步骤

全屏非全屏切换时，更换GSYVideoView ,然后设置setplayPosition  ,每次都是从头开始播放

问题代码：(如果有)
 
## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
demo中怎么复现？？？？
