### ISSUE TITLE
如何在全屏模式下切换横竖屏

### ISSUE THREAD

**Issue by KafukaChen** [CarGuo/GSYVideoPlayer#1044]
我发现Demo里的列表视频都是在列表播放时点击全屏直接旋转到横屏模式，无法借鉴啊。。。
我的需求是列表中的视频没有全屏按钮，点击 封面/播放按钮/播放中视频 都直接进全屏，所以我这时候只能用startWindowFullscreen（）方法，然后进去的就是竖着的全屏，然后点击全屏键需要横竖屏切换，不知道咋整啊，望楼主指点指点

**Comment by KafukaChen** [comment]
简单来说就是从列表中进入全屏后，全屏中如何横竖屏切换

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/wiki/基础Player-API

```
  public boolean isLockLand()

    /**
     * 一全屏就锁屏横屏，默认false竖屏，可配合setRotateViewAuto使用
     */
    public void setLockLand(boolean lockLand)
```

**Comment by KafukaChen** [comment]
嗯 我用的.setLockLand(false)              //全屏默认横屏
                .setRotateViewAuto(true)       //是否开启自动旋转
不行，因为我要一进来竖着全屏，我这么设置的，全屏之后点击全屏就退出全屏了，如果设置两个true则全屏后点击全屏按钮无反应

**Comment by CarGuo** [comment]
这样的需求就需要继承后，实现自定义逻辑
