### ISSUE TITLE
请问，如何实现自动播放？

### ISSUE THREAD

**Issue by yitongUp** [CarGuo/GSYVideoPlayer#1046]
## 问题描述：

我想已进入界面就自动进行播放。我找到了这个方法clickStartIcon。但是我没有找到合适的调用地方。写在init方法里会报url为空。。。也没有别的入口了呀。。。
我是参照StandardGSYVideoPlayer的类写的。

**Comment by CarGuo** [comment]
startplayLogic

**Comment by yitongUp** [comment]
3Q。这个方法得是player对象调用。

**Comment by a1677156127** [comment]
> startplayLogic

哥 我想问下 目前竖屏 进去 默认调用这个可以播放  播放完自动切换下一集也ok 标题也能刷新 ，然后 我切换横屏进去 调用同样的方法 他不自动播放了，title 也不变 ，目前观察到的 剧集倒是切换了 本地log有输出
