### ISSUE TITLE
出现内存泄漏奔溃

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#1048]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！
进度条定时器发生内存泄漏
## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```
![aa](https://user-images.githubusercontent.com/18607571/39391478-87b3c300-4ad6-11e8-9f86-5fa33c9cd1e0.jpg)

xxxxxxx

```

**Comment by CarGuo** [comment]
这是内存溢出，你可以试试设置关闭暂停时的mShowPauseCover图片显示为false
