### ISSUE TITLE
请问应该如何设置标准播放器StandardGSYVideoPlayer 竖屏全屏？

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1049]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by xi5528336** [comment]
以及在进行ViewPager+Fragments 进行滑动自动播放操作时， 由于代码中含有 如果有其他播放器在运行，则onPause  有没有办法就是每滑动一次都能自动播放，不会onPause。

**Comment by CarGuo** [comment]
不是很理解

**Comment by w787959** [comment]
StandardGSYVideoPlayer的宽高怎么才能跟视频保持一致呢？

**Comment by xi5528336** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
