### ISSUE TITLE
setListener为什么没作用

### ISSUE THREAD

**Issue by zhiyou007** [CarGuo/GSYVideoPlayer#1054]
## 问题描述：

setListener为什么没作用

## 问题机型/系统：

问题代码：(如果有)
     代码里的日志打印都没有打印出来，视频缓冲info的监听也没作用
     GSYVideoManager.instance().setListener(new GSYMediaPlayerListener(){
            @Override
            public void onPrepared() {
                Log.i("xxxx","onPrepared");
            }

            @Override
            public void onAutoCompletion() {

            }

            @Override
            public void onCompletion() {

            }

            @Override
            public void onBufferingUpdate(int percent) {
                Log.i("xxx","onBufferingUpdate:"+percent);Log.i("wzm","onBufferingUpdate:"+percent);
            }

            @Override
            public void onSeekComplete() {

            }

            @Override
            public void onError(int what, int extra) {

            }

            @Override
            public void onInfo(int what, int extra) {
                Log.i("xxxx","onInfo:"+what);
            }

            @Override
            public void onVideoSizeChanged() {

            }

            @Override
            public void onBackFullscreen() {

            }

            @Override
            public void onVideoPause() {

            }

            @Override
            public void onVideoResume() {

            }

            @Override
            public void onVideoResume(boolean seek) {

            }
        });

videoPlayer.getGSYVideoManager().setLastListener，这个方法也试过

**Comment by CarGuo** [comment]
这个本来就不是这么用的，如果你需要坚挺，设置videocallback

**Comment by jksfood** [comment]
public void onPlayError(String url, Object... objects)
objects打印出来的是
[Ljava.lang.Object;@f54aa91
能都打印出具体的错误信息？
