### ISSUE TITLE
大佬，有办法取消掉外部媒体监听导致的视频暂停播放吗？

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1055]
问题：最近在做ViewPager+Fragment 下滑播放视频的项目，ViewPager add了多个播放器Fragment。然后 因为ViewPager+Fragment有烦人的预加载，导致视频无法播放，有什么解决的办法吗？

**Comment by CarGuo** [comment]
不是很理解，但是如果是你描述的场景，可以试试setUpLazy
或者是给你的fragment坐懒加载

**Comment by xi5528336** [comment]
好的，多谢大佬，如果有ViewPager+Fragment的播放代码就更好了，哈哈

**Comment by xi5528336** [comment]
额 能请问一下setUpLazy的网络请求头的作用吗？第一次接触视频这方面的

**Comment by CarGuo** [comment]
GSYVideoOptionBuilder应该有setMapHeadData
