### ISSUE TITLE
GSY怎么播放SD卡视频,我权限加了,加载图片有了,无法播放

### ISSUE THREAD

**Issue by chigang** [CarGuo/GSYVideoPlayer#1056]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by chigang** [comment]
好了解决了,"file:///" +SDPATH+ "/Download/w.mp4",但是不明白为什么必须这种格式,这这种SDPATH+ "/Download/w.mp4"播放不了

**Comment by CarGuo** [comment]
uri必须事file才识别为本地

**Comment by chigang** [comment]
@CarGuo 支持rtp么

**Comment by CarGuo** [comment]
rtsp支持一些，不是全支持，使用的时候记得参考问题集锦设置为tcp连接模式

**Comment by chigang** [comment]
@CarGuo 好的,谢谢
