### ISSUE TITLE
假如底层播放器我想用ExoPlayer， 需要显示调用吗？

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#106]
如题， 希望能尽量详细地介绍一下操作方法。
谢谢啦。

**Comment by CarGuo** [comment]
GsyViedeoManager有setVideoType

**Comment by Wangct23** [comment]
GSYVideoManager.instance().setVideoType(this, IJKEXOPLAYER);

**Comment by Wangct23** [comment]
已解決, 謝謝.
