### ISSUE TITLE
打开视频播放后，退出播放再去点击别的界面，发现界面的图片加载不出来,版本号：2.1.1

### ISSUE THREAD

**Issue by tiefeiniu** [CarGuo/GSYVideoPlayer#1060]
播放视频后，去点击别的界面，这个界面的图片加载不出来，打印是有图片url的，但是加载不出图片，只加载出没有网络的图片，用的是glide，如果不播放视频，先点击这个界面，图片就正常显示。楼主，这个什么原因呢，红米5 plu

**Comment by CarGuo** [comment]
可以在demo 复现么

**Comment by tiefeiniu** [comment]
我在demo引入了需要加载图片的界面，先打开视频，然后在点击需要加载图片的界面，是可以显示出来，但需要等10秒多，刚开始先显示无网络图片；如果不先打开视频，直接打开这个界面，一进来图片就加载出来了，但我的项目里如果先打开视频，图片怎么都加载不出来

**Comment by tiefeiniu** [comment]
我视频是继承GSYBaseActivityDetail，demo里测试是在MainActivity里添加一个button，点击打开新的界面（即加载图片的界面）

**Comment by tiefeiniu** [comment]
楼主，我刚发现我项目里先打开视频，再打开需要加载图片的界面，图片也是可以显示出来的，但是需要等10多秒后，跟demo里一样的

**Comment by CarGuo** [comment]
@tiefeiniu 我在InputUrlDetailActivity做了个简单的测试，没复现问题，你可以看看刚刚更新的demo
