### ISSUE TITLE
您好,问个亮度调节的问题

### ISSUE THREAD

**Issue by findvoid** [CarGuo/GSYVideoPlayer#1061]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

手势调节亮度后,再用系统亮度调节没有效果

## 问题机型/系统：

例如 真机 坚果pro Android7.1.1

## Demo中的复现步骤

Demo中的打开VIDEO会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by findvoid** [comment]
可以設置跟隨系統一起調節麼

**Comment by CarGuo** [comment]
目前看来不行
