### ISSUE TITLE
播放hevc编码的h.265视频(ios11录制)，视频播放时长变为两倍。

### ISSUE THREAD

**Issue by g19980115** [CarGuo/GSYVideoPlayer#1064]
## 问题描述：

播放该视频，实际时长为13秒，但是可播放到26秒。声音正常播放，视频跟不上声音。

## 问题机型/系统：

真机 一加5 Android8.0.0

## 视频链接
（忽略这个mp4的后缀，实际是mov）
[http://qiniu.carmmi.com/image/132451525666042.mp4](http://qiniu.carmmi.com/image/132451525666042.mp4)

**Comment by g19980115** [comment]
不同手机延长的手机不一样，但是用videoview播放都是正常的。

**Comment by CarGuo** [comment]
我记得ijk是通过ffpmeg的音频时序同步的， 所以估计是源的音频时序问题，和系统mediacodec播放不同，目前看来两种方案，要不就修改源的生成逻辑，要不修改为exoplayer2 + surfaceview模式
```
GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
```

**Comment by g19980115** [comment]
好吧
