### ISSUE TITLE
无缝切换视频，会出现类似播放DVD时出现的卡屏，声音“咔咔”的，不同的是这里只响一下

### ISSUE THREAD

**Issue by zung** [CarGuo/GSYVideoPlayer#1066]
## 问题描述：

无缝切换我按照SmartPickVideo写了，我把一个完整视频分成6段，并且帧没有重叠的，可以完美实现无缝切换，根本看不出来是分割的视频片段，和完整视频一模一样。
但是，切换时的音效怎么取消掉，我没找到。

## 问题机型/系统：

真机 Pixel 2 Android8.0

## PS
最后我想问，无缝切换的原理是什么，能简单说下吗？

**Comment by zung** [comment]
就是在切换视频时，会发出一声类似SoundPool发出的声音，而且切换不同的视频，音效声音也不一样，就响一下，如：“咔”、“嘀”这样的。
        我用的视频片断是由一个完整视频分割的，放在了raw下面，一共6个视频片断，每个10秒，没有重叠帧

**Comment by zung** [comment]
### 我重复测试了几次，不是音效，是切换时偶尔有一个声音发出，有的两个视频之间会出现，有的不会出现，还有时候第一次出现，就像过去播放DVD卡屏一样，对，就是那种声音。

**Comment by zung** [comment]
### 解决了！！
我利用ffmpeg首先把原来的完整视频源只抽取视频（无声音），然后再分割几个片段，这样就没有那个卡顿的声音了。
### PS
作者的这个封装的很不错，很好用！

**Comment by Djangoogle** [comment]
> ## 问题描述：
> 无缝切换我按照SmartPickVideo写了，我把一个完整视频分成6段，并且帧没有重叠的，可以完美实现无缝切换，根本看不出来是分割的视频片段，和完整视频一模一样。
> 但是，切换时的音效怎么取消掉，我没找到。
> 
> ## 问题机型/系统：
> 真机 Pixel 2 Android8.0
> 
> ## PS
> 最后我想问，无缝切换的原理是什么，能简单说下吗？

哥能贴一下你改过的代码吗？我这里切换还是有黑屏啊。
