### ISSUE TITLE
播放本地视频滑动快进问题

### ISSUE THREAD

**Issue by jianlin00000** [CarGuo/GSYVideoPlayer#1067]
## 问题描述：

播放本地视频（网上下的电影MP4格式）的过程中（使用demo中的SampleVideo），在屏幕上进行手势滑动控制进度出现没有中间进度的情况（往后划瞬间到结束位置，往前划瞬间到开始位置），播放网络视频的时候不会

## 问题机型/系统：

真机 朵唯平板

**Comment by CarGuo** [comment]
首先是否同个视频，其次可以尝试问题集锦中的精准seek配置

**Comment by jianlin00000** [comment]
试了不同的视频都一样，在application中添加了精准seek配置也还是一样

**Comment by jianlin00000** [comment]
在华为荣耀8上面试了也是一样，一划onProgressChanged(SeekBar seekBar, int progress, boolean fromUser)中的progress就到了100，fromUser为false

**Comment by jianlin00000** [comment]
解决了，是因为我对DisplayMetrics设置了一下参数，导致 mScreenWidth = getActivityContext().getResources().getDisplayMetrics().widthPixels;mScreenHeight = getActivityContext().getResources().getDisplayMetrics().heightPixels;这连个值为0导致的，叨扰郭神了
