### ISSUE TITLE
如何实现直接切换横屏或者竖屏

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1069]
我做法是宽大于高,就直接显示竖屏,反之就横屏
具体应该切换横竖屏怎么怎么实现
if( videoDetail.getWidth()>videoDetail.getHeight()){
                    //直接横屏
                    orientationUtils.resolveByClick();
                    videoplayer.startWindowFullscreen(getContext(),false,false);
                }else {
                  //直接竖屏
                }

**Comment by CarGuo** [comment]
类似的需求，demo已经实现，近期下个版本更新发布

**Comment by CarGuo** [comment]
4.1.3 fix
