### ISSUE TITLE
通过在线url的方式播放mpg格式的视频，只能观看没有声音

### ISSUE THREAD

**Issue by AlawnXu** [CarGuo/GSYVideoPlayer#1072]
通过在线url的方式播放mpg格式的视频，只能观看没有声音，是因为不支持h265吗？
而且在播放mpg视频之后，会导致页面文字乱码。

**Comment by CarGuo** [comment]
依赖ex so 依赖试试

**Comment by AlawnXu** [comment]
怎么确定音频编码？

**Comment by AlawnXu** [comment]
![image](https://user-images.githubusercontent.com/5283399/39859637-0eafb298-546d-11e8-9c84-fe88f505ef10.png)

**Comment by AlawnXu** [comment]
请问是这样依赖么？

**Comment by AlawnXu** [comment]
视频太大了一时下载不来，文件格式是.mpg,音频编码应该确定是h265

**Comment by CarGuo** [comment]
可以在输出的log里看看，h265是视频编码

**Comment by AlawnXu** [comment]
![image](https://user-images.githubusercontent.com/5283399/39860652-a7f353ee-5470-11e8-903b-fd5b7ad080f4.png)

**Comment by CarGuo** [comment]
不是这个log，你找找和h265输出相近位置的log

**Comment by AlawnXu** [comment]
没看见h265，通过什么关键字查询？

**Comment by AlawnXu** [comment]
有个log显示“ Option ijkiomanager not found.”

**Comment by CarGuo** [comment]
这个没关系，没找到说明这个不对，清下log，然后播放，然后把所有log复制成一个文件，压缩上传上来试试

**Comment by AlawnXu** [comment]
[log.txt](https://github.com/CarGuo/GSYVideoPlayer/files/1991078/log.txt)

**Comment by CarGuo** [comment]
音频编码是ac3，目前的so并没有支持

**Comment by AlawnXu** [comment]
那要重新编译一个吗？

**Comment by CarGuo** [comment]
如果需要支持这种格式的话，需要重新编译so，然后只依赖java层就可以了。编译的话首页有教程，脚本可以用根目录的.sh文件

**Comment by AlawnXu** [comment]
https://www.jianshu.com/p/bd289e25d272
是这个链接中选择编译吗？.sh还需要修改吗？

**Comment by CarGuo** [comment]
是的， sh需要加上ac3的音频支持

**Comment by AlawnXu** [comment]
暂时不支持电视遥控器控制播放器快进、快退、全屏、加减声音等操作吗？

**Comment by AlawnXu** [comment]
![image](https://user-images.githubusercontent.com/5283399/40063070-14ff7e14-588f-11e8-896e-cdb814e70743.png)
我试了一下这里的方式，没编译通过！你能帮忙编译一个支持ac3的版本吗？多谢啊！
