### ISSUE TITLE
两个Activity都要有播放页面，退出第二个activity不能调用relaseallVideos，可否释放单独的video啊？

### ISSUE THREAD

**Issue by yanglichuan** [CarGuo/GSYVideoPlayer#1076]
两个Activity都要有播放页面，退出第二个activity不能调用relaseallVideos，可否释放单独的video啊？

**Comment by CarGuo** [comment]
问题是默认情况下，播放内核其实只有一个，所以你只要是否了第二个Activity下的video，一定会release内核的。等于是你回到第一个activity，需要调用播放器恢复原本状态。 或者你使用demo中的多个播放内核的方式，不过开启播放内核多了的话会很占用内存
