### ISSUE TITLE
默认横屏的状态下，home键或者锁屏键操作有问题

### ISSUE THREAD

**Issue by yitongUp** [CarGuo/GSYVideoPlayer#1077]
我项目中的需求是视频默认横屏的。首次进入，点击返回键退出登录，正常操作没有问题。但是如果点击了home键或者锁屏键。再返回到视频页的时候。点击返回键，视频会从横屏转为竖屏。且标题栏会显示。

## 问题机型/系统：

华为p8

问题代码：(如果有)
我的代码如下：
OnCreat中
        //外部辅助的旋转，帮助全屏
        orientationUtils = new OrientationUtils(this, mVpVideo);
        orientationUtils.setEnable(false);

        mVpVideo.setIsTouchWiget(true);
        //关闭自动旋转
        mVpVideo.setRotateViewAuto(false);
        mVpVideo.setLockLand(false);
        mVpVideo.setShowFullAnimation(false);
        mVpVideo.setDismissControlTime(10 * 1000);

        GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);

        mVpVideo.setVideoAllCallBack(new GSYSampleCallBack() {
            @Override
            public void onPrepared(String url, Object... objects) {
                Log.e(TAG,"onPrepared");
                super.onPrepared(url, objects);
                //开始播放了才能旋转和全屏
                orientationUtils.setEnable(true);
                //直接横屏
                orientationUtils.resolveByClick();

                //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                mVpVideo.startWindowFullscreen(VideoActivity.this, true, true);

                isPlay = true;
            }
           @Override
            public void onQuitFullscreen(String url, Object... objects) {
                super.onQuitFullscreen(url, objects);
                if (orientationUtils != null) {
                    orientationUtils.backToProtVideo();
                }
            }

            @Override
            public void onPlayError(String url, Object... objects) {
                super.onPlayError(url, objects);
                Log.e(TAG,"onPlayError");
            }
        });

@Override
    protected void onResume() {
        SysLogService.insertSysLog(TAG,"VideoActivity onResume");
        getCurPlay().onVideoResume();
        super.onResume();
        isPause = false;
        if (isPlay){
            mVpVideo.startPlayLogic();
        }
    }

    @Override
    protected void onPause() {
        SysLogService.insertSysLog(TAG,"VideoActivity onPause");
        getCurPlay().onVideoPause();
        super.onPause();
        isPause = true;
    }

**Comment by CarGuo** [comment]
mVpVideo.setLockLand(true);

试试
