### ISSUE TITLE
建议在项目中build一个debug apk出来

### ISSUE THREAD

**Issue by FynnJason** [CarGuo/GSYVideoPlayer#1078]
想运行看一些功能具体是什么效果，无奈要下载项目自己跑一遍，所以作者大哥可以把项目打包出一个debug的apk

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/releases/download/v4.1.0/app-release.apk 这里有4.1.0的版本，虽然不是最新的
