### ISSUE TITLE
请问项目中全屏的时候是怎么做到在播放器上面的控件也能挡起来的？

### ISSUE THREAD

**Issue by Average77** [CarGuo/GSYVideoPlayer#1079]
如题

**Comment by CarGuo** [comment]
播放器上面的控件也能挡起来的？？？你是说你在播放器上面也放了东西是吧····，那你直接返回你的布局啊。https://github.com/CarGuo/GSYVideoPlayer/blob/master/GSYVIDEO_PLAYER_PROJECT_INFO.md

**Comment by Average77** [comment]
<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="200dp">
    <com.xingyuyou.xingyuyou.views.DanmakuVideoPlayer
        android:id="@+id/detail_player"
        android:layout_width="match_parent"
        android:layout_height="200dp" />
    <RelativeLayout
        android:id="@+id/ad_frame_root"
        android:layout_alignParentBottom="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">


        <RelativeLayout
            android:id="@+id/ad_video_frame"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />

        <TextView
            android:id="@+id/ad_frame_cancel"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="关闭"
            android:layout_alignParentRight="true"
            android:background="@color/black"
            android:textSize="14sp"
            android:textColor="@color/white"/>
    </RelativeLayout>
</RelativeLayout> 
是这样，然后全屏的时候ad_frame_root 就看不到了 @CarGuo

**Comment by Average77** [comment]
<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="200dp">
    <com.xingyuyou.xingyuyou.views.DanmakuVideoPlayer
        android:id="@+id/detail_player"
        android:layout_width="match_parent"
        android:layout_height="200dp" />

    <RelativeLayout
        android:id="@+id/ad_frame_root"
        android:layout_alignParentBottom="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">


        <RelativeLayout
            android:id="@+id/ad_video_frame"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />

        <TextView
            android:id="@+id/ad_frame_cancel"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="关闭"
            android:layout_alignParentRight="true"
            android:background="@color/black"
            android:textSize="14sp"
            android:textColor="@color/white"/>
    </RelativeLayout>
</RelativeLayout>

被吞了点

**Comment by CarGuo** [comment]
你应该把需要的布局加进去做成自定义布局，在继承的getLayoutId返回

**Comment by Average77** [comment]
明白了
