### ISSUE TITLE
全屏情况下 触摸快进/触摸音量/亮度  返回之后不隐藏

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1080]
联动detail Demo中
我一直触摸滑动按住,让Dialog显示  播放结束后 点击返回键之后(触摸滑动按住没有松手)   进度条没有隐藏

**Comment by CarGuo** [comment]
滑动冲突问题，已经在demo中更新

**Comment by darkrevier** [comment]
@CarGuo 我更新你的代码 ,但是仍然会显示(音量图标,亮度,进度条)

**Comment by darkrevier** [comment]
点击退出全屏键

**Comment by CarGuo** [comment]
再更新下，刚没理解到这个点

**Comment by darkrevier** [comment]
@CarGuo 可以了

**Comment by lichun19930209** [comment]
@PureDark 这个问题请问是怎么解决的呢？目前我也遇到这个问题呢。能否帮忙解答下？谢谢，感恩

**Comment by lichun19930209** [comment]
@CarGuo  个问题请问是怎么解决的呢？目前我也遇到这个问题呢。能否帮忙解答下？谢谢，感恩

**Comment by millerzhu** [comment]
> @CarGuo 个问题请问是怎么解决的呢？目前我也遇到这个问题呢。能否帮忙解答下？谢谢，感恩
我的是重写下面这个方法 里面 dismissVolumeDialog();解决的。
    @Override
    protected void changeUiToCompleteShow() {
        dismissVolumeDialog();
        super.changeUiToCompleteShow();
