### ISSUE TITLE
从全屏模式退出后原先Activity的样式为什么会改变？？

### ISSUE THREAD

**Issue by chailijun** [CarGuo/GSYVideoPlayer#1081]
## 问题描述：

DetailListPlayer页面将activity的主题设置成全屏样式。
旋转手机进入全屏播放，然后退出全屏播放，原先activity全屏样式却变成了带有状态栏的样式

## 问题机型/系统：

真机 Redmi Note4 Android6.0

## Demo中的复现步骤
# 1.修改Demo中application的主题AppTheme，修改成如下：
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorPrimaryDark</item>

        <item name="android:windowFullscreen">true</item>
        <item name="android:windowContentOverlay">@null</item>
    </style>

# 2.运行Demo，点击Demo首页Button “DETAIL列表模式，切换下一集”进入DetailListPlayer页面
# 3.播放视频并且进入全屏播放，然后再退出全屏播放。
# 4.此时DetailListPlayer的主题变成带有状态栏了>_<，怎么去掉这个状态栏啊？？？

**Comment by CarGuo** [comment]
全屏方法设置actionbar为false

**Comment by chailijun** [comment]
### 已解决，在Activity中重写onWindowFocusChanged方法
    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        if (hasFocus && Build.VERSION.SDK_INT >= 19) {
            View decorView = getWindow().getDecorView();
            decorView.setSystemUiVisibility(
                    View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                            | View.SYSTEM_UI_FLAG_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
        }
    }
