### ISSUE TITLE
GSYVideoPlayer 支持的高清模式有哪些。

### ISSUE THREAD

**Issue by zhongwen1** [CarGuo/GSYVideoPlayer#1084]
## 问题描述：GSYVideoPlayer 支持的高清模式有哪些。

如果视频编码是H.264 音频编码是AAC 视频容器是mp4 或m3u8 这两种视频容器能达到高清效果。

希望楼主解答下,谢谢。

**Comment by zhongwen1** [comment]
如果视频编码是H.264 音频编码是AAC 视频容器是m3u8 GSYVideoPlayer能播放吗？

**Comment by CarGuo** [comment]
可以播放
