### ISSUE TITLE
MultiSampleVideo 播放一段时间之后停止

### ISSUE THREAD

**Issue by qiaoshouliang** [CarGuo/GSYVideoPlayer#1086]
（

## 问题描述：

使用MultiSampleVideo播放rtsp视频流时，过10分钟左右，视频停止播放

## 问题机型/系统：

魅族，华为等多个机型都有这个问题

## Demo中的复现步骤

ListMultiNormalAdapter的视频播放地址为rtsp的视频直播地址，或者M3u8(http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8)，播放四个视频，过一段时间之后，四个视频都停止播放

**Comment by CarGuo** [comment]
rtsp可能断了，是配置了option的tcp连接吗

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/QUESTION.md  - > 17、rtsp连接有问题

**Comment by Android-Boys** [comment]
表示也遇到了这个问题。
