### ISSUE TITLE
视频卡顿

### ISSUE THREAD

**Issue by CleverSJX** [CarGuo/GSYVideoPlayer#1090]
## 视频播放卡顿
视频是下载到本地播放的 没有网络因素影响 
我是在安卓电视上运行的APP 播放的
把视屏拷贝到U盘中用电视直接播放 视频不卡正常播放
这是我拍摄的卡顿效果视频 http://s.swao.cn/o_1c4gs92iap4812kj10ehko261q7.mp4
这是视频的地址http://s.swao.cn/o_1c4gm8o1nniu1had13bk1t0l1rq64m.mov
 http://s.swao.cn/o_1cb9e0749eit58h1u6d1sir1jrj6e.mp4

**Comment by CarGuo** [comment]
你可以试试问题集锦中的丢帧，调一个合适帧率试试···

**Comment by CleverSJX** [comment]
我在问题集锦没有找到关于卡顿丢帧的处理。

**Comment by CarGuo** [comment]
framedrop 根据你测试视频的帧数，调整一个值

**Comment by CleverSJX** [comment]
http://s.swao.cn/o_1cdhf0vavui21ev915mg79m1r2v7.png  这是视频信息的截图 我看25帧也不高啊 是那个1分50秒 135M的视频的信息

**Comment by CleverSJX** [comment]
视频码率9800多 是这个高吧   用framedrop 是降低额这个吗

**Comment by CarGuo** [comment]
码率的话只能开启硬解码试试了

**Comment by CleverSJX** [comment]
android:hardwareAccelerated="true"  硬件加速一直开的
