### ISSUE TITLE
这里面的方法还是不走，视频只是再转圈等待

### ISSUE THREAD

**Issue by wanglinfu** [CarGuo/GSYVideoPlayer#1093]
normalGSYVideoPlayer.setVideoAllCallBack(new GSYSampleCallBack(){
           @Override
            public void onPlayError(String url, Object... objects) {
//                super.onPlayError(url, objects);
                Log.i("tag" , "onPlayError" + url + "objects:" + objects[1]);
                Toast.makeText(DanmkuVideoActivity.this , "视频播放失败请重试" , Toast.LENGTH_SHORT).show();
                finish();
            }

}

**Comment by CarGuo** [comment]
看log，断点，看看流程都触发了什么
