### ISSUE TITLE
请问本地下载好的视频怎么播放不了，支持吗

### ISSUE THREAD

**Issue by guiyanbing** [CarGuo/GSYVideoPlayer#1094]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by guiyanbing** [comment]
我在手机打开下载好的视频可以播放

**Comment by CarGuo** [comment]
直接播放啊···首先项目跑起来的时候应该会申请读取sd卡权限，带file:///的路径打开即可

**Comment by chailijun** [comment]
好吧，在本地视频路径前面加上“file:///”就ok了
