### ISSUE TITLE
能否帮忙编译一个支持ac3音频编码的so版本呢？

### ISSUE THREAD

**Issue by AlawnXu** [CarGuo/GSYVideoPlayer#1098]
能否帮忙编译一个支持ac3音频编码的so版本呢？多谢啊！

**Comment by CarGuo** [comment]
这个还是得靠自己，兄弟

**Comment by AlawnXu** [comment]
改module-lite-hevc.sh里面的配置，反注释acs3的配置吗？
![image](https://user-images.githubusercontent.com/5283399/40152573-4d1ab802-59b8-11e8-85d2-062b00fa1d3a.png)

编译前选择以下这个配置？
![image](https://user-images.githubusercontent.com/5283399/40152513-15eb5b02-59b8-11e8-924c-cb39cbd149d6.png)

**Comment by AlawnXu** [comment]
GSYVideoPlayer依赖4.1.3的，IJKPlayer用master分支的代码没有问题的吧？

**Comment by CarGuo** [comment]
可以，0.8.8的ijk

**Comment by AlawnXu** [comment]
我改了配置编译了支持了acs3，但是播放的时候会卡帧，播放器中间的进度会跳动，声音一卡一卡的

**Comment by CarGuo** [comment]
因为ijk的时序同步是用音频为基准的，感觉应该是音频解码出来有问题

**Comment by AlawnXu** [comment]
有没有解决方法呢？😓

**Comment by AlawnXu** [comment]
![image](https://user-images.githubusercontent.com/5283399/40225314-49014da4-5abb-11e8-935f-cfccb8496bc5.png)
1、怎么关闭硬解码？2、Activity要配置什么？

**Comment by AlawnXu** [comment]
我重新编译了so，支持了acs3，但是播放的时候依旧是卡顿，无法观看视频，视频卡帧，声音也是 一卡一卡的。以下是我的播放链接，能否帮忙看看是不是片源问题？还是ijkplayer本身就不支持这种格式？
http://112.45.113.75/88888888/16/20180427/268457850/268457850.ts

**Comment by CarGuo** [comment]
最新版本的切换到exoplayer模式试试 GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);
