### ISSUE TITLE
如何添加字幕..

### ISSUE THREAD

**Issue by androidmh** [CarGuo/GSYVideoPlayer#1100]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
目前来看不支持内嵌在库中，你可以考虑在上层嵌入一层字幕层，下个版本不出意外应该会优化exo相关的，exo带了meger source 接口可以合并字幕和流
