### ISSUE TITLE
请问能播放本地ts格式的吗？

### ISSUE THREAD

**Issue by FynnJason** [CarGuo/GSYVideoPlayer#1101]
想下载m3u8中的ts，通过连续读取ts文件来实现完整视频的播放。

**Comment by CarGuo** [comment]
首先，你可以做一个本地的m3u8，不过需要配置白名单，详见问题集锦。 protocol_whitelist ，加上你需要支持的协议
或者你下载ts后，拼接成concat也可以，不过需要白名单和ex so依赖。
