### ISSUE TITLE
进度条跳动问题

### ISSUE THREAD

**Issue by Basakerone** [CarGuo/GSYVideoPlayer#1102]
## 问题描述：
替换demo PlayActivity  中视频地址为:http://p4qwant9x.bkt.clouddn.com/pc_1521113116117.mp4第一次
拖动进度条没有跳动，但是时间在继续计时，第二次拖动的时候进度条就明显跳动。
## 问题机型/系统：
真机 小米MAX Android7.0  
模拟器 夜神
![test](https://user-images.githubusercontent.com/17926247/40115177-253711e4-5942-11e8-921f-c18f314828a7.gif)

**Comment by Basakerone** [comment]
用过，没效果。貌似用ijk去播放，用demo的视频不会，用一些其他编码的视频就会出现这样的问题。切换到exo2就行了，感谢回复！

**Comment by wangyikai1234567** [comment]
大佬你好，请问现在进度条闪动问题有什么好的办法处理么？
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
我添加这个并没有太大的作用，而且视频在暂停状态时，滑动进度条无法回到00:00点，播放之后才会回到
