### ISSUE TITLE
IJKPlayer、EXOPlayer、系统播放器切换？

### ISSUE THREAD

**Issue by FynnJason** [CarGuo/GSYVideoPlayer#1103]
GSYVideoManager.instance().setVideoType(this, 4);  
请问是不是调用这句话，就切换到系统播放器完成了？但是运行后没什么变化呀

**Comment by CarGuo** [comment]
是这样切换，你需要什么变化？？？

**Comment by FynnJason** [comment]
在源码中看到，不是太明白 (最好配合GSYVideoType.SUFRACE) 是什么意思？

GSYVideoManager.instance().setVideoType(this, 4);
StandardGSYVideoPlayer player = findViewById(R.id.player);
String url = "http://fuli.zuida-youku-le.com/20170507/xDeZkLgu/index.m3u8";
player.setUp(url, false, "标题");

完整如上，请问是这个样子的吗？

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setVideoType(this, 4); 属于全局的，在Application中配置就好

**Comment by hhuas** [comment]
GSYVideoManager.instance().setVideoType(this, 4);
这个方法没了，用什么方法替换啊

**Comment by CarGuo** [comment]
@hhuas PlayerFactory.setPlayManager
