### ISSUE TITLE
列表播放，关闭全屏动画,退出全屏时，会闪一下才恢复列表播放

### ISSUE THREAD

**Issue by laiforever3** [CarGuo/GSYVideoPlayer#1104]
## 问题描述：

关闭全屏动画，从全屏回到列表播放时，效果是先旋转回竖屏，会闪一下再恢复到原先到列表播放。
这个闪一下很影响体验

## 问题机型/系统：

例如 真机 mate9 Android8.0

## Demo中的复现步骤
在 RecyclerItemNormalHolder中。

.setShowFullAnimation(false)

**Comment by CarGuo** [comment]
我这边在demo中的RecyclerViewActivity没复现
