### ISSUE TITLE
IJKPlayer，ExoPlayer，系统播放器有何不同？

### ISSUE THREAD

**Issue by FynnJason** [CarGuo/GSYVideoPlayer#1105]
比较好奇这个，大佬能简单解释一下吗？

**Comment by CarGuo** [comment]
系统播放器就是系统的MediaPlayer，内部用的是mediacodec解码，可定制程度较低。
ExoPlayer是谷歌订制话，使用低版本api，暴露更多接口和可定制化的播放器，内部也是用mediacodec相关。
ijkplayer的内核是脱离android的FFmpeg编译出的so
