### ISSUE TITLE
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.sample-1/lib/arm/libijksdl.so"

### ISSUE THREAD

**Issue by yuexiaodong1** [CarGuo/GSYVideoPlayer#1107]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

程序使用代码安装， targetSdkVersion 26时都是正常的，发包时都降低到22，到播放视频时就崩溃。

## 问题机型/系统：
Device Manufacturer: alps
Device Model       : A11-F-64-QN
Android Version    : 7.0
Android SDK        : 24

## Demo中的复现步骤

使用程序代码安装一切正常，发布版本的包就播放崩溃，播放的本地文件，

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.sample-1/lib/arm/libijksdl.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
	at java.lang.System.loadLibrary(System.java:1530)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.a(Unknown Source)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(Unknown Source)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(Unknown Source)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source)
	at com.shuyu.gsyvideoplayer.c.b.a(Unknown Source)
	at com.shuyu.gsyvideoplayer.c.a(Unknown Source)
	at com.shuyu.gsyvideoplayer.c.a(Unknown Source)
	at com.shuyu.gsyvideoplayer.c$a.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by CarGuo** [comment]
配置ndk过滤，参考demo gradle

**Comment by yuexiaodong1** [comment]
所有的都配置过，唯一没有的就是混淆了

**Comment by CarGuo** [comment]
你开启了混淆了？

**Comment by yuexiaodong1** [comment]
刚刚看了，主工程开 混淆了，我在库工程里面把混淆添加进去，还是报这个问题，混淆都关闭就是好的

**Comment by yuexiaodong1** [comment]
#Gson
-keepattributes Signature
-keepattributes *Annotation*
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }
-keep class com.google.gson.examples.android.model.** { *; }
-keep class com.google.gson.* { *;}
-dontwarn com.google.gson.**

#xutils
-keep class * extends java.lang.annotation.Annotation { *; }
#butterknife
-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}
#glide
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
#okhttp
-dontwarn okhttp3.**
-keep class okhttp3.**{*;}

#okio
-dontwarn okio.**
-keep class okio.**{*;}

#播放器GSYVideoPlayer
-keep class com.shuyu.gsyvideoplayer.video.** { *; }
-dontwarn com.shuyu.gsyvideoplayer.video.**
-keep class com.shuyu.gsyvideoplayer.video.base.** { *; }
-dontwarn com.shuyu.gsyvideoplayer.video.base.**
-keep class com.shuyu.gsyvideoplayer.utils.** { *; }
-dontwarn com.shuyu.gsyvideoplayer.utils.**
-keep class tv.danmaku.ijk.** { *; }
-dontwarn tv.danmaku.ijk.**

-keep public class * extends android.view.View{
    *** get*();
    void set*(***);
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}



#-------------------------3.与js互相调用的类------------------------

-keep class com.ol.patrolproject.Presenter.interactor.** { *; }

#-------------------------4.反射相关的类和方法----------------------


#-------------------------5.基本不用动区域--------------------------
#指定代码的压缩级别
-optimizationpasses 5

#不去忽略非公共的库类
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers

# 是否使用大小写混合
-dontusemixedcaseclassnames

#预校验
-dontpreverify

#混淆时是否记录日志
-verbose

#忽略警告，避免打包时某些警告出现
-ignorewarning

# 混淆时所采用的算法
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*

#保护注解
-keepattributes *Annotation*

#记录生成的日志数据,gradle build时在本项目根目录输出
#apk 包内所有 class 的内部结构
-dump class_files.txt
#未混淆的类和成员
-printseeds seeds.txt
#列出从 apk 中删除的代码
-printusage unused.txt
#混淆前后的映射
-printmapping mapping.txt


#-----------------------------6.默认保留区-----------------------

# 保持哪些类不被混淆
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Appliction
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class * extends android.view.View
-keep public class com.android.vending.licensing.ILicensingService


# 对于带有回调函数的onXXEvent、**On*Listener的，不能被混淆
-keepclassmembers class * {
    void *(**On*Event);
    void *(**On*Listener);
}


#如果有引用v4、v7包可以添加下面这行
-keep public class * extends android.support.*


# 保留继承的
#-keep public class * extends android.support.v4.**
#-keep public class * extends android.support.v7.**
#-keep public class * extends android.support.annotation.**

# 保留R下面的资源
-keep class **.R$* {*;}

# 保留我们自定义控件（继承自View）不被混淆
-keep public class * extends android.view.View{
    *** get*();
    void set*(***);
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}



-keepclassmembers class * implements java.io.Serializable {

            static final long serialVersionUID;
            private static final java.io.ObjectStreamField[] serialPersistentFields;
            !static !transient <fields>;
            !private <fields>;
            !private <methods>;
            private void writeObject(java.io.ObjectOutputStream);
            private void readObject(java.io.ObjectInputStream);
            java.lang.Object writeReplace();
            java.lang.Object readResolve();
}

# 保持 native 方法不被混淆

-keepclasseswithmembernames class * {
    native <methods>;
}
# 保持自定义控件类不被混淆

-keepclasseswithmembernames class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembernames class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}


# 保持自定义控件类不被混淆
-keepclassmembers class * extends android.app.Activity{
       public void *(android.view.View);
}

# 保持枚举 enum 类不被混淆

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
# 保持 Parcelable 不被混淆
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
#---------------------------7.webview-----------------------


-keepclassmembers class * extends android.webkit.WebChromeClient{
   		public void openFileChooser(...);
}

-keep class **.Webview2JsInterface { *; }  #保护WebView对HTML页面的API不被混淆
-keepclassmembers class * extends android.webkit.WebViewClient {  #如果你的项目中用到了webview的复杂操作 ，最好加入
     public void *(android.webkit.WebView,java.lang.String,android.graphics.Bitmap);
     public boolean *(android.webkit.WebView,java.lang.String);
}
-keepclassmembers class * extends android.webkit.WebChromeClient {  #如果你的项目中用到了webview的复杂操作 ，最好加入
     public void *(android.webkit.WebView,java.lang.String);
}

**Comment by yuexiaodong1** [comment]
我把混淆放在主工程里面，播放一下就到头了

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/proguard-rules.pro 参考一下这个文件，你没有的混淆配上试试

**Comment by yuexiaodong1** [comment]
至少确定是混淆的问题了

**Comment by yuexiaodong1** [comment]
找到问题了，是定制的手机问题

**Comment by CarGuo** [comment]
好吧

**Comment by thirtyyuan** [comment]
> 找到问题了，是定制的手机问题

请问下最后是怎么解决的呢？混淆文件加了就好了？
