### ISSUE TITLE
如何获取视频第一帧作为封面

### ISSUE THREAD

**Issue by FynnJason** [CarGuo/GSYVideoPlayer#1110]
确实没有在Demo里面找到，眼睛都找花了，大佬能直接说一下吗？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/SampleCoverVideo.java

**Comment by shusheng007** [comment]
@CarGuo 如果使用你的方法设置第一帧特别费流量的，glide好像把整个视频都下载下来了，如果是本地视频没有问题，如果是网络视频最好不要用，或者用之前判断一下是否在WiFi环境下。

**Comment by GuoAxiang** [comment]
> @CarGuo 如果使用你的方法设置第一帧特别费流量的，glide好像把整个视频都下载下来了，如果是本地视频没有问题，如果是网络视频最好不要用，或者用之前判断一下是否在WiFi环境下。

我现在遇到这个问题了，用Glide加载视频封面特别费流量，请问有什么好方法吗

**Comment by CarGuo** [comment]
@GuoAxiang 还可以用系统 MediaCodec
