### ISSUE TITLE
其他协议和编码concat、rtsp、hls、rtmp、crypto、mpeg等。

### ISSUE THREAD

**Issue by liuzq8769** [CarGuo/GSYVideoPlayer#1113]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）
  String source1 = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
//        source1 = "rtmp://live.hkstv.hk.lxdns.com/live/hks";//香港卫视(Live)
        source1 = "rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov";//大熊兔（点播）  【不可用】
  source1 = "rtsp://218.204.223.237:554/live/1/6D1E43167B3A7BDA/oby9efo80duh9bjf.sdp";【不可用】
        source1 = "http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/prog_index.m3u8";//苹果提供的测试源（点播）
//        source1 = "http://ivi.bupt.edu.cn/hls/cctv5hd.m3u8";//CCTV5高清
     
## 问题描述：
以上多种协议地址，但是rtsp协议地址不可以使用
XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
参考问题集锦设置tcp连接试试

**Comment by liuzq8769** [comment]
使用的依赖是： 
//完整版引入
compile 'com.shuyu:GSYVideoPlayer:4.1.3'
使用VLC播放rstp协议地址
目前这个地址可以用 "rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov"

**Comment by CarGuo** [comment]
完整版依赖不行，使用java和exso依赖

**Comment by liuzq8769** [comment]
多谢
