### ISSUE TITLE
viewpager中使用出现卡顿

### ISSUE THREAD

**Issue by DingSong** [CarGuo/GSYVideoPlayer#1119]
单个pager没有问题
多个pager如果不设置looping不播放，
设置looping播放到到一半会黑屏，然后继续播放，重复循环
有没有解决方案，用多类型模式和单例都有这个问题

**Comment by darkrevier** [comment]
我也遇到了这个问题,ls这两个方法都用过了,我一切换pager也卡顿 有时候视频进度在走 但是画面不动

**Comment by DingSong** [comment]
我上面说的描述有问题，有一部分是我自己代码的问题
我重新描述一下，
一个viewpager中两个pager，需要打开页面时同时播放，
但是现在不设置looping两个都不播放，设置looping只播放最后一个
由于是启动页用都本地视频所以没有使用cache，另外懒加载也同样无效。

**Comment by CarGuo** [comment]
我理解没错的话，你是需要同时播放两个视频，也就是需要两个内核。
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/ListMultiVideoActivity.java  这个估计可以帮助到你。普通正常情况下，只有一个内核存在。

**Comment by DingSong** [comment]
确实是我自己的问题，重写了custommanager改出的问题
