### ISSUE TITLE
想实现缓存加密（防止视频泄露），怎样实现呢？谢谢

### ISSUE THREAD

**Issue by tabian** [CarGuo/GSYVideoPlayer#1121]

**Comment by CarGuo** [comment]
目前ex_so支持crypto加密，但是没试过本地的，应该不支持。ExoPlayer倒是支持，不过目前没有适配，你可以看看dev分支中，目前在针对ExoPlayer做一些优化，不过还没设计加解密这个，理论上ExoPlayer是有支持的

**Comment by tabian** [comment]
@CarGuo 我这边当第一次缓存修改前10个字节（保证无法直接打开缓存文件）。这边遇到的问题是缓存完成，播放的时候需要把前10个字节改回来播放，怎样实现呢？  @（有缓存的情况是直接ijkplayer传入url播放，不知道在什么地方改文件流字节）

**Comment by CarGuo** [comment]
缓存完成之后。在setup的时候，是会将url转为本地路径，你可以看看源码。看看继承后如何实现比较合适

**Comment by tabian** [comment]
OK 谢谢
