### ISSUE TITLE
视频开始播放就全部缓存了吗？

### ISSUE THREAD

**Issue by tiefeiniu** [CarGuo/GSYVideoPlayer#1122]
楼主你好！我一打开视频播放，然后断网，它能一直播放到完，如果我不想已播放就全部缓存，该怎么操作呢？播放完怎么彻底清除完缓存？

**Comment by CarGuo** [comment]
设置cache为false

**Comment by tiefeiniu** [comment]
关闭缓存方法没找到 setCache();有这个方法吗？

**Comment by CarGuo** [comment]
setup的时候传的。如果用的是builder模式就是在builder的时候传的

**Comment by tiefeiniu** [comment]
那退出时，清除全部的缓存是哪个方法呢？因为我一播放长视频（一小时以上），退出时再去打开新的界面，发现界面的封面图片加载不出来，播放短视频却可以加载，所以我怀疑是不是退出时缓存没清理掉

**Comment by CarGuo** [comment]
封面图你是用哪种实现的？demo中的类似于glide实现的，缓存并没有在视频库中处理

**Comment by tiefeiniu** [comment]
我用glide，不是视频的封面图片，是我打开视频后，退出视频再去打开一个新界面，新界面不是有很多条目吗，条目的封面图片加载不来，标题文字可以加载出来

**Comment by CarGuo** [comment]
这个还真没遇到

**Comment by tiefeiniu** [comment]
是内存泄漏造成的吗？打开短视频就可以加载图片，但打开长视频，图片就加载不出来，打log是有图片url的，我弄了很久了还没发现是什么原因， 什么情况下glide会加载不出图片呢？

**Comment by CarGuo** [comment]
设置了关闭缓存还会么？理论上是不会冲突的。没遇到过这个，有log吗，加载不出来的时候。

**Comment by nikolamakin** [comment]
作者，比如我range 了2分钟的视频，然后快播放完了，如何在继加2分钟的视频？靠range返回的新视频如何继续播放？
