### ISSUE TITLE
能否提供一个依赖，不需要ExoPlayer模块的代码

### ISSUE THREAD

**Issue by cochee** [CarGuo/GSYVideoPlayer#1123]
请问下能否提供一个不包含ExoPlayer模块的依赖？
因为只使用到IJKPlayer,不需要用到ExoPlayer。
而ExoPlayer大概占用了600KB的大小，希望可以精简掉

**Comment by CarGuo** [comment]
你可以在依赖的时候exclude掉试试。

**Comment by cochee** [comment]
debug模式可以编译过，release模式还需要加一些混淆配置
