### ISSUE TITLE
请问如何获取视频大小，以及在视频缓冲时的动画如何取消掉？

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1124]
如何做到视频缓冲时，黑屏过渡动画取消掉。

一按播放键的时候 封面会变成黑屏然后出现过渡动画转圈圈 

希望能够：按了播放按钮后，缓冲时,一直为封面，等缓冲成功播放时，直接显示画面。

**Comment by xi5528336** [comment]
以及视频大小（多少M）的获取？有相关方法的实现吗？ 麻烦了

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1135  视频大小问题重复

缓存动画问题继承后重载对应方法即可
