### ISSUE TITLE
网络ts流的点击播放加载时间过长

### ISSUE THREAD

**Issue by BingChaoLiu** [CarGuo/GSYVideoPlayer#1126]
你好，在点击播放网络ts流的时候加载时间比较长，有没有办法缩短加载时间，CacheWithPlay 已经设置为false

**Comment by CarGuo** [comment]
ts流加载长这个应该和服务度有关吧，等待服务端的response的

**Comment by BingChaoLiu** [comment]
我将视频地址扔到vlc中3-5秒可以播放，但是在程序中需要8-13秒

**Comment by CarGuo** [comment]
目前看来没什么办法，试试GSYVideoType.IJKEXOPLAYER2 模式
