### ISSUE TITLE
 集成框架后播放视频报错No pending exception expected: java.lang.NoSuchMethodError: no static or non-static method "Ltv/danmaku/ijk/media/player/IjkMediaPlayer;._injectCacheNode(IJJJJ)V"

### ISSUE THREAD

**Issue by handsomezwj** [CarGuo/GSYVideoPlayer#1127]
No pending exception expected: java.lang.NoSuchMethodError: no static or non-static method "Ltv/danmaku/ijk/media/player/IjkMediaPlayer;._injectCacheNode(IJJJJ)V"

**Comment by CarGuo** [comment]
确定是否超过64K方法数没分包。
确定是否因为混淆导致问题。

**Comment by handsomezwj** [comment]
做了分包，代码跑的debug，并且已经添加了混淆配置，我把使用ijkPlayer的so文件的版本号从0.8.2升级到0.8.8就会出现这个问题，重新退回到0.8.2没问题

**Comment by CarGuo** [comment]
你使用的是哪个版本的？？目前gsy最新版本对应的是0.8.8的ijk

**Comment by handsomezwj** [comment]
2.1

**Comment by CarGuo** [comment]
那就对了，你可以看看版本更新说明那里你就可以找到ijk的版本对应。

**Comment by handsomezwj** [comment]
//完整版引入,只要依赖下面一行就行了？
compile 'com.shuyu:GSYVideoPlayer:4.1.3'

**Comment by handsomezwj** [comment]
都导入的是最新的版本报错Failed to register native method tv.danmaku.ijk.media.player.IjkMediaPlayer._injectCacheNode(IJJJJ)V in /data/app/com.demo.test-2/base.apk:classes2.dex

**Comment by handsomezwj** [comment]
如果使用2.1的版本，横屏拍摄的视频能竖屏播放吗？

**Comment by CarGuo** [comment]
不是很理解你说的，项目已经集成有so，如果不需要项目的so，那只需要依赖java就可以

**Comment by BlackSnow-M** [comment]
> 现在只要把版本升级到4.1.3，同时jkPlayer的so文件版本都对应了，就会报上面那个错

你好，这个问题解决了吗，是什么原因呢
