### ISSUE TITLE
播放视频问题

### ISSUE THREAD

**Issue by fvaryu** [CarGuo/GSYVideoPlayer#1131]
## 问题描述：
播放此视频源https://oss.zhihanyun.com/o_1ce7uel8i1rjm1djcdbo9t0d9g8.mp4 在11s的时候进度会倒退
用手机录制的视频

## 问题机型/系统：

华为P10   8.0

## Demo中的复现步骤
demo打开VIDEO修改播放源即可

**Comment by CarGuo** [comment]
看起来是视频的帧时序和ijk的兼容问题，目前这种问题只能说修改视频源或者切换到exo模式播放

**Comment by CarGuo** [comment]
话说你这个视频也太厉害了，173M一分钟···

**Comment by fvaryu** [comment]
@CarGuo    只是个用手机自带的录的视频  难道华为这里有bug，不是很懂这块

**Comment by fvaryu** [comment]
@CarGuo 基本默认配置，是通过action调用系统相机，分辨率 uhd 4K 16:9 立体声 地理位置 开，拍照静音 开，其他没有设置

**Comment by CarGuo** [comment]
建议使用5.0.0-beta下的exoPlayer模式试试
