### ISSUE TITLE
这个播放器支持画面的局部模糊吗，比如应用于模糊掉视频里的其它水印信息 ，或者模糊掉人脸？

### ISSUE THREAD

**Issue by microshow** [CarGuo/GSYVideoPlayer#1133]
如题

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/effect  这里有类似添加水印和模糊的实现方法，具体可以到 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailFilterActivity.java 看看。

你的需求需要你对OpenGL的实现熟悉。固定位置模糊或者遮挡还是比较好实现的，可以参考demo，覆盖上一层就就好。

**Comment by microshow** [comment]
你的意思是在上层盖一个普通的view,还是使用opengl处理的呀

**Comment by microshow** [comment]
如果使用opengl 固定某个区域模糊该改哪里的参数呢 谢谢 @CarGuo

**Comment by CarGuo** [comment]
opengl啊，你看看上面https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/effect 目录下的实现

**Comment by CarGuo** [comment]
你可以参考水印那个
