### ISSUE TITLE
播放直播流时，感觉像录播视频一样

### ISSUE THREAD

**Issue by Demidong** [CarGuo/GSYVideoPlayer#1137]
/**
     * 恢复暂停状态
     *
     * @param seek 是否产生seek动作
     */
    @Override
    public void onVideoResume(boolean seek) ；
使用该方法恢复暂停，并且播放直播流时，手动暂停一会后，再手动点击播放按钮继续播放，发现没有实时播放，感觉像是录播一样。使用不带参数的onVideoResume（）菊花会转半天，有时候会一直转。

**Comment by CarGuo** [comment]
onVideoResume（）不能用于直播流。只有 onVideoResume(boolean seek) 才可以。因为seek的时候会重新链接上。至于你说的 `动暂停一会后，再手动点击播放按钮继续播放，发现没有实时播放，感觉像是录播一样` 估计也是需要seek以下去重新追帧，推荐你继承之后，重载`clickStartIcon() `方式去实现

**Comment by Demidong** [comment]
那又如何追帧呢？

**Comment by CarGuo** [comment]
重载`clickStartIcon()`方式，在播放的状态下参考`onVideoResume(boolean seek) `

**Comment by Demidong** [comment]
直播，那个时间不确定，都不知道追到哪一帧

**Comment by CarGuo** [comment]
你只要seek一下暂停时的那个往前加一点试试

**Comment by nsacer** [comment]
“你只要seek一下暂停时的那个往前加一点试试”腾讯云的视频直播，seekTo暂停之后的时间还是一直在转圈
