### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by wqjuser** [CarGuo/GSYVideoPlayer#1138]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

项目中有kotlin代码的时候发生了这样的问题！

**Comment by CarGuo** [comment]
编译不通过的log是什么？？？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/LazyRecyclerAdapter/tree/master/app-kotlin  我在自己的kotlin项目里添加编译，可以通过

**Comment by wqjuser** [comment]
我尝试从jcenter中完整引入就好了
