### ISSUE TITLE
播放配置问题

### ISSUE THREAD

**Issue by liuzq8769** [CarGuo/GSYVideoPlayer#1139]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
播放地址是：rtsp://admin:12345@192.0.0.64/mpeg4/ch1/sub/av_stream
XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
报错：
IJKMEDIA: Option ijkapplication not found
IJKMEDIA: method PAUSE failed: 551 Option not supported
```

xxxxxxx

```

**Comment by CarGuo** [comment]
没看懂

**Comment by liuzq8769** [comment]
使用大华子码流地址无法播放，log错误是IJKMEDIA: Option ijkapplication not found
IJKMEDIA: method PAUSE failed: 551 Option not supported。但是使用VLC是可以播放的

**Comment by CarGuo** [comment]
so要依赖ex so, 配置看问题集锦

**Comment by liuzq8769** [comment]
按照第三种方式配置的

**Comment by CarGuo** [comment]
是的，然后需要配置option，参看问题集锦，配置tcp

**Comment by liuzq8769** [comment]
大神，所有的问题集锦我都看了一遍。没有找到配置相关的解决方案，求教了

**Comment by CarGuo** [comment]
17、rtsp连接有问题

**Comment by liuzq8769** [comment]
海康：
rtsp://[username]:[password]@[ip]:[port]/[codec]/[channel]/[subtype]/av_stream
说明：
username: 用户名。例如admin。
password: 密码。例如12345。
ip: 为设备IP。例如 192.0.0.64。
port: 端口号默认为554，若为默认可不填写。
codec：有h264、MPEG-4、mpeg4这几种。
channel: 通道号，起始为1。例如通道1，则为ch1。
subtype: 码流类型，主码流为main，辅码流为sub。


例如，请求海康摄像机通道1的主码流，Url如下
主码流：
rtsp://admin:12345@192.0.0.64:554/h264/ch1/main/av_stream
rtsp://admin:12345@192.0.0.64:554/MPEG-4/ch1/main/av_stream


子码流：
rtsp://admin:12345@192.0.0.64/mpeg4/ch1/sub/av_stream
rtsp://admin:12345@192.0.0.64/h264/ch1/sub/av_stream


大华：
rtsp://username:password@ip:port/cam/realmonitor?channel=1&subtype=0
说明:
username: 用户名。例如admin。
password: 密码。例如admin。
ip: 为设备IP。例如 10.7.8.122。
port: 端口号默认为554，若为默认可不填写。
channel: 通道号，起始为1。例如通道2，则为channel=2。
subtype: 码流类型，主码流为0（即subtype=0），辅码流为1（即subtype=1）。


例如，请求某设备的通道2的辅码流，Url如下
rtsp://admin:admin@10.12.4.84:554/cam/realmonitor?channel=2&subtype=1 

地址格式是这样的

**Comment by CarGuo** [comment]
目前播放你这个链接超时····

**Comment by CarGuo** [comment]
Connection to tcp://192.0.0.64:554?timeout=0 failed: Connection timed out
    rtsp://admin:12345@192.0.0.64:554/h264/ch1/main/av_stream: Connection timed out

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/QUESTION.md 第17条
