### ISSUE TITLE
播放黑屏 用ExoPlayer可以正常播放

### ISSUE THREAD

**Issue by hfyqsy** [CarGuo/GSYVideoPlayer#1141]
http://106.14.186.44:9999/gps-web/aaaa.mp4

//完整版引入播放器
api 'com.shuyu:GSYVideoPlayer:4.1.2'

MediaPlayer播放也是可以正常播放的

**Comment by hfyqsy** [comment]
//完整版引入播放器
    api 'com.shuyu:GSYVideoPlayer:4.1.2'

**Comment by CarGuo** [comment]
首先你需要确定视频的编码和音频的编码是什么。

其次播放器

GSYVideoManager.instance().setVideoType 方法可以配置播放器为exo或者mediaplayer。
