### ISSUE TITLE
一进来播放界面缓存就增高，退出时缓存没减少（未播放）

### ISSUE THREAD

**Issue by tiefeiniu** [CarGuo/GSYVideoPlayer#1144]
WebDetailActivity ，一进来播放界面缓存就变高，退出来，缓存没减少，下次再进来，缓存就在原先基础上增高一倍，退出时我已清除缓存了；  在onDestroy（）方法里已执行以下三个方法，但是没用
       webPlayer.clearCurrentCache();
        GSYVideoManager.clearAllDefaultCache(WebDetailActivity.this);
        GSYVideoManager.releaseAllVideos();

**Comment by CarGuo** [comment]
WebDetailActivity 因为用了Glide，每次进来loadCover的时候都会大量加载

**Comment by tiefeiniu** [comment]
哪个播放类进来不需要大量加载呢？

**Comment by CarGuo** [comment]
你把`PreViewGSYVideoPlayer`的`startDownFrame`屏蔽了试试

**Comment by tiefeiniu** [comment]
startDownFrame 是啥？

**Comment by tiefeiniu** [comment]
小屏幕已屏蔽，还是一样

**Comment by CarGuo** [comment]
就是不要用PreViewGSYVideoPlayer，你试试用其他的
