### ISSUE TITLE
视频全屏的重力旋转问题

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1145]
#656 这种情况我试了下,但不是全屏的情况下也旋转了。我只想让它在视频全屏时旋转怎么做
参数的配置
orientationUtils.setRotateWithSystem(false);
orientationUtils.setEnable(true);

**Comment by CarGuo** [comment]
全屏的时候旋转，非全屏的时候不旋转？？
其实非全屏的时候旋转都是靠着 Activity的onConfigurationChanged(Configuration newConfig) 实现的。

类似detailPlayer页面，如果不走` detailPlayer.onConfigurationChanged(this, newConfig, orientationUtils, true, true);`，非全屏的时候是不会旋转的
 @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        //如果旋转了就全屏
        if (isPlay && !isPause) {
            detailPlayer.onConfigurationChanged(this, newConfig, orientationUtils, true, true);
        }
    }

**Comment by darkrevier** [comment]
那我没必要重写onConfigurationChanged方法了吧,如果我只在全屏时有重力旋转应该怎么设置呢,一直没搞懂,求解

**Comment by darkrevier** [comment]
我设置了 还是不好使
player.setRotateWithSystem(true);
player.setRotateViewAuto(true)
      //设置全屏按键功能
        videoplayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                videoplayer.setAutoFullWithSize(true);
                orientationUtils.resolveByClick();
                videoplayer.startWindowFullscreen(getContext(), false, true);
            }
        });

**Comment by okmin3** [comment]
orientationUtils.setEnable(true); 调用时机修改为回调GSYSampleCallBack 的onEnterFullscreen

然后GSYSampleCallBack 的onQuitFullscreen 调用orientationUtils.setEnable(false);
就是点击全屏才可以随手机旋转
