### ISSUE TITLE
视频进度问题

### ISSUE THREAD

**Issue by fvaryu** [CarGuo/GSYVideoPlayer#1146]
## 问题描述：

StandardGSYVideoPlayer.setGSYVideoProgressListener()里面的progress只能到99
URL：https://oss.zhihanyun.com/1524124485154471112.m3u8

## 问题机型/系统：

大部分机型

## Demo中的复现步骤

未改动其他，使用标准StandardGSYVideoPlayer

**Comment by fvaryu** [comment]
@CarGuo 这样呀  那判断视频播放完成不就不准确了？

**Comment by CarGuo** [comment]
不会，播放在完成有完成的回调接口
