### ISSUE TITLE
Android P 视频切换全屏短暂黑屏

### ISSUE THREAD

**Issue by thatnight** [CarGuo/GSYVideoPlayer#1148]
## 问题描述：

Android P 视频切换全屏短暂黑屏

## 问题机型/系统：

Android P x86模拟器

## Demo中的复现步骤

所有视频可以切换全屏的都会复现，应该是SurfaceView的销毁重建了。

**Comment by CarGuo** [comment]
demo中默认用的是textureVIew，texureView在模拟器上表现不是很好

**Comment by thatnight** [comment]
目前发现是个别Android P模拟器有这个问题，也许是系统问题吧，关了关了。
