### ISSUE TITLE
slf4j包冲突问题

### ISSUE THREAD

**Issue by walterFeng** [CarGuo/GSYVideoPlayer#115]
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/slf4j/impl/StaticLoggerBinder.class
不知道org/slf4j/impl/StaticLoggerBinder.class在library里哪个包下，冲突很难找，求解决。

**Comment by CarGuo** [comment]
GSYVideoPlayer依赖了videocache，videocache依赖了这个包

**Comment by chenkexu** [comment]
怎么解决的？@CarGuo

**Comment by CarGuo** [comment]
exclude 掉
