### ISSUE TITLE
显示流量提示怎么让它只提示一次

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1151]
public void clickStartIcon() {
        if (TextUtils.isEmpty(mUrl)) {
            Debuger.printfError("********" + getResources().getString(com.shuyu.gsyvideoplayer.R.string.no_url));
            //Toast.makeText(getActivityContext(), getResources().getString(R.string.no_url), Toast.LENGTH_SHORT).show();
            return;
        }
        if (mCurrentState == CURRENT_STATE_NORMAL || mCurrentState == CURRENT_STATE_ERROR) {
            if (!mUrl.startsWith("file") && !CommonUtil.isWifiConnected(getContext())
                    && mNeedShowWifiTip) {
                showWifiDialog();
                return;
            }
            startButtonLogic();

我在showWifiDialog()方法里把mNeedShowWifiTip设置成false,每次都还提示,现在需求是只提示一次,再播放不提示了

**Comment by CarGuo** [comment]
你可以继承后重写这个方法

**Comment by darkrevier** [comment]
public void clickStartIcon() {
        if (TextUtils.isEmpty(mUrl)) {
            Debuger.printfError("********" + getResources().getString(com.shuyu.gsyvideoplayer.R.string.no_url));
            //Toast.makeText(getActivityContext(), getResources().getString(R.string.no_url), Toast.LENGTH_SHORT).show();
            return;
        }
        if (mCurrentState == CURRENT_STATE_NORMAL || mCurrentState == CURRENT_STATE_ERROR) {
            if (!mUrl.startsWith("file") && !CommonUtil.isWifiConnected(getContext())
                    && mNeedShowWifiTip) {
                showWifiDialog();
                mNeedShowWifiTip = false
                return;
            }
            startButtonLogic();
        }
我加了一句mNeedShowWifiTip = false应该就不会走showWifiDialog();但是不管用 是在哪个位置重置了吗

**Comment by darkrevier** [comment]
重写哪个方法

**Comment by darkrevier** [comment]
列表播放视频设置成false都会重新初始化,所以没有效果？

**Comment by CarGuo** [comment]
继承重写showWIFIDialog方法啊，如果你判定不想弹出，就直接return然后调用stratplaylogic

**Comment by darkrevier** [comment]
我重写了showWIFIDialog方法\
  builder.setMessage("您正在使用移动网络，继续播放将消耗您"+ CommonUtils.getFileSize4MB(videoDetail.getFileSize())+"流量");
        builder.setPositiveButton(getResources().getString(com.shuyu.gsyvideoplayer.R.string.tips_not_wifi_confirm), new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                mNeedShowWifiTip = false;
                dialog.dismiss();
                startPlayLogic();
            }
        });
 mNeedShowWifiTip = false;
我的意思是list列表有很多视频,非wifi情况下只提示我一次消耗流量  然后我在列表非wifi看任意一个视频都不会再提示我了,我在同一个视频下是有效的,但是 我看别的视频还是会弹出

**Comment by darkrevier** [comment]
列表视频只提示我一次！不管我看任何的一个视频

**Comment by CarGuo** [comment]
既然都继承了，你想增加什么逻辑不都可以么…比如你增加回调，通过回调判断，比如增加本地持久化缓存判断

**Comment by darkrevier** [comment]
不清楚怎么弄

**Comment by CarGuo** [comment]
……
