### ISSUE TITLE
在某一帧解码时候卡住不动。造成内存泄露或ANR 版本2.08

### ISSUE THREAD

**Issue by dingjie142052** [CarGuo/GSYVideoPlayer#1153]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
在某一帧解码时候卡住不动。造成内存泄露或ANR

## 问题机型/系统：
平板

## Demo中的复现步骤
播放的视频某一帧有问题，会造成播放器卡住不动，或者播放器不起来

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

05-30 10:23:31.369 I/IJKMEDIA(11016): AudioCodec: avcodec, aac

05-30 10:23:31.369 I/IJKMEDIA(11016): SDL_RunThread: [17641] ff_aout_android

05-30 10:23:31.369 I/IJKMEDIA(11016): SDL_RunThread: [17642] ff_audio_dec

05-30 10:23:31.371 I/IJKMEDIA(11016): VideoCodec: avcodec, h264

05-30 10:23:31.371 W/IJKMEDIA(11016): fps: 30.000000 (normal)

05-30 10:23:31.371 W/IJKMEDIA(11016): fps: 30.000000 (normal)

05-30 10:23:31.371 D/IJKMEDIA(11016): FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720

05-30 10:23:31.371 D/IJKMEDIA(11016): FFP_MSG_SAR_CHANGED: 0, 1

05-30 10:23:31.371 D/IJKMEDIA(11016): ijkmp_get_msg: FFP_MSG_PREPARED

05-30 10:23:31.371 D/IJKMEDIA(11016): FFP_MSG_PREPARED:

05-30 10:23:31.372 I/IJKMEDIA(11016): SDL_RunThread: [17648] ff_video_dec

05-30 10:23:31.372 D/IJKMEDIA(11016): FFP_MSG_VIDEO_ROTATION_CHANGED: 0

05-30 10:23:31.390 D/IJKMEDIA(11016): IjkMediaPlayer_start

05-30 10:23:31.390 D/IJKMEDIA(11016): ijkmp_start()

05-30 10:23:31.390 D/IJKMEDIA(11016): ijkmp_start()=0

05-30 10:23:31.390 D/IJKMEDIA(11016): ijkmp_get_msg: FFP_REQ_START

05-30 10:23:31.407 D/IJKMEDIA(11016): SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=RV32(0x32335652, dp=0xb8487b18)

05-30 10:23:31.408 D/IJKMEDIA(11016): FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720

05-30 10:23:31.461 D/IJKMEDIA(11016): Video: first frame decoded

05-30 10:23:31.461 D/IJKMEDIA(11016): SDL_VoutFFmpeg_CreateOverlay(w=1280, h=720, fmt=RV32(0x32335652, dp=0xb8487b18)

05-30 10:23:31.461 D/IJKMEDIA(11016): FFP_MSG_VIDEO_SIZE_CHANGED: 1280, 720

05-30 10:23:31.470 D/IJKMEDIA(11016): ANativeWindow_setBuffersGeometry: w=1365, h=768, f=(0x1) => w=1280, h=720, f=RV32(0x32335652)

05-30 10:23:31.481 W/gralloc (  151):  Debugmem The fd=66, in vmalloc !!!! Ishwc=0

05-30 10:23:31.482 E/[Gralloc-ERROR](11016): int gralloc_backend_register(private_handle_t*):82 mmap( share_fd:76 ) failed with Out of memory

05-30 10:23:31.483 W/GraphicBufferMapper(11016): registerBuffer(0xb95aa610) failed -12 (Out of memory)

**Comment by CarGuo** [comment]
使用新版本试试
