### ISSUE TITLE
关于按全屏返回键后，视频声音消失的问题

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1154]
使用源码里的 RecyclerViewActivity， SampleCoverVideo，StandardGSYVideoPlayer 在全屏返回的时候声音突然消失  再按回全屏后才会有声音，不知道什么情况。 然后把RecyclerView中的item里的视频组件换成MultiSampleVideo（支持多个视频同时播放的组件）后却没有类似的情况 只是RecyclerView下滑后，视频不会释放掉。 请问是我设置的原因还是什么情况。

**Comment by CarGuo** [comment]
看demo代码，因为设置了非全屏静音接口

**Comment by xi5528336** [comment]
OK，当时有看到那里 以为那个方法是你注释 全屏不静音的方法实现
