### ISSUE TITLE
全屏播放的时候，播放结束了，切换到下一个视频，url等资源都更新到第二个视频了，但是没法播放？

### ISSUE THREAD

**Issue by pangrongxian** [CarGuo/GSYVideoPlayer#1156]
## 问题描述：

全屏播放的时候，播放结束了，切换到下一个视频，url等资源都更新到第二个视频了，但是没法播放？

## 问题机型/系统：

真机 小米4X

**Comment by CarGuo** [comment]
Demo中不是有么，播放下一个

**Comment by CarGuo** [comment]
ListGSYVideoPlayer
