### ISSUE TITLE
播放缓存视频

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1157]
list demo 中如果播放一个完整视频 已经缓存了的  然后我关网会提示网络不可用  用4G的时候会提示消耗流量，这个应该怎么解决

**Comment by CarGuo** [comment]
最新Demo中？5.0.0的？

**Comment by darkrevier** [comment]
是最新的,我具体说一下,list demo 中的第一个视频我会完整播放完,然后我上滑动列表,再滑回来点击播放会弹出上面两种提示

**Comment by CarGuo** [comment]
我在demo中没有复现啊。

**Comment by CarGuo** [comment]
ListVideoActivity页面的，是的，我试了demo不会呀，说起来你的链接不是m3u8之类的吧

**Comment by darkrevier** [comment]
不好意思,问题找到了 代码没更新到最新 打扰了。。。
