### ISSUE TITLE
横竖屏切换播放问题

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1161]
列表页视频正在播放,点击全屏再返回列表页 偶尔会出现视频重置不播放的问题，不知道大神遇到过没

**Comment by darkrevier** [comment]
只有横屏全屏才会出现,不知道什么原因

**Comment by CarGuo** [comment]
Demo怎么复现

**Comment by darkrevier** [comment]
LISTDemo 中 ListNormalAdapter   我点击全屏横屏快速按back键返回 会出现短暂横屏的现象

**Comment by darkrevier** [comment]
holder.gsyVideoPlayer.setShowFullAnimation(!getListNeedAutoLand()); 设置成了false的时候

**Comment by darkrevier** [comment]
还有一个问题就是也是list demo中 ，全屏横屏视频在播放 然后锁屏 再解锁视频暂停而且先竖屏然后才横屏 ,如果我想解锁之后让他退出全屏 或者是 重新播放 应该用哪个方法
