### ISSUE TITLE
m3u8 全屏播放，第一点击不能全屏，第二次点击才能全屏（附视频）

### ISSUE THREAD

**Issue by metooweb** [CarGuo/GSYVideoPlayer#1162]
[录屏](http://www.yinshop.cn/gsy/video.mp4)

**Comment by CarGuo** [comment]
demo怎么复现

**Comment by metooweb** [comment]
@CarGuo 把 detailplayer 里面的 播放地址 改成 m3u8 的地址 就这样

**Comment by metooweb** [comment]
@CarGuo 解决了，页面没配置好 ^_^ <activity
    android:name=".PlayActivity"
    android:configChanges="orientation|keyboardHidden|screenSize"
    android:screenOrientation="portrait" />
