### ISSUE TITLE
有软硬解切换api吗，没有就建议添加这个功能

### ISSUE THREAD

**Issue by kyriej** [CarGuo/GSYVideoPlayer#1167]

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/GSYVideoType.java

**Comment by kyriej** [comment]
切换播放器api呢，这里面只列举了播放器类型

**Comment by CarGuo** [comment]
```
GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2); 
```
