### ISSUE TITLE
视频播放状态下，导致父控件滑动事件不正常

### ISSUE THREAD

**Issue by G-Fantastic** [CarGuo/GSYVideoPlayer#1168]
## 问题描述：
将 视频控件（CustomGSYVideo，继承自  StandardGSYVideoPlayer） 放在 垂直的viewpager中，实现上滑下滑播放效果。
当滑动到第一页，再继续下滑（手指由上往下滑动）时，会有刷新的imageview跟随手指移动，问题是，视频没有播放时，一切正常，如果视频是 **播放状态**，那么  刷新的imageview 会**出现位置漂移，闪动。**
开始以为是视频控件的事件影响了父控件viewpager的事件，屏蔽 CustomGSYVideo 的所有事件，问题照样存在，也通过父控件拦截了所有事件，问题依旧。
public class CustomGSYVideo extends StandardGSYVideoPlayer {
              //
              其他代码
              //
 @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        return false;
    }
    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        return true;
    }
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        return false;
    }
}

## 问题机型/系统：
真机测试：
红米手机 android 4.4.4
海信f22 android 6.0.1

**Comment by CarGuo** [comment]
并不是很清楚问题，不过这个应该和库没什么太大关系，垂直的viewpager模式可以看看用recyclerview实现

**Comment by G-Fantastic** [comment]
是我描述的不清楚，还是不清楚问题发生的原因。
问题是：
手指由上往下滑，原本的效果是，有一个 imageview 控件也会由 上往下缓缓移动，但是 视频播放时，导致 imageview控件乱移动，位置无规律变化。
还有一个细节：
public void onSurfaceUpdated(Surface surface) {
        
        // 在此方法中添加以下代码，再配合事件拦截，上述 imageview 乱漂移的问题有很大的缓解，但没有根本解决，偶尔还有出现。
        setViewShowState(mTopContainer, GONE);
        setViewShowState(mBottomContainer, GONE);
        setViewShowState(mStartButton, GONE);
        setViewShowState(mLoadingProgressBar, GONE);
        setViewShowState(mThumbImageViewLayout, GONE);
        setViewShowState(mBottomProgressBar, VISIBLE);
        setViewShowState(mLockScreen, GONE);
}

**Comment by CarGuo** [comment]
可以的话上传一个视频，这样可以更清晰看到问题

**Comment by G-Fantastic** [comment]
正常状态：
![default](https://user-images.githubusercontent.com/10738277/40908765-40460ad0-681a-11e8-99bf-822bacdb0f20.gif)

不正常状态：
![default](https://user-images.githubusercontent.com/10738277/40908782-519a99e0-681a-11e8-8458-bfbaa3a1b378.gif)

**Comment by CarGuo** [comment]
眼力不好，实在没看出问题的点？？？

**Comment by G-Fantastic** [comment]
看顶部的“刷新图标”，我都是手指从上一直往下滑，不正常的那个 “刷新图标” 一直在跳动呀，在漂移呀

**Comment by CarGuo** [comment]
好像没重新场景，你可以看看 demo刚刚更新的PlayActivity，好像不会出这个问题
