### ISSUE TITLE
请问你的demo支持rtsp播放吗

### ISSUE THREAD

**Issue by MaryDQ** [CarGuo/GSYVideoPlayer#1169]
您好，您提供的demo好像打不开rtsp流啊

**Comment by CarGuo** [comment]
修改so依赖为exso依赖，然后参考问题集锦的第17条

**Comment by MaryDQ** [comment]
app的build.gradle修改本地的依赖为exso以后，报错，一些res文件缺失，
![image](https://user-images.githubusercontent.com/19642327/41021027-8d5e98b8-6997-11e8-87bb-25a0fcd97def.png)

**Comment by MaryDQ** [comment]
我的app的build.gradle具体如下：
`apply plugin: 'com.android.application'


android {

    def globalConfiguration = rootProject.extensions.getByName("ext")
    compileSdkVersion globalConfiguration.androidCompileSdkVersion
    buildToolsVersion globalConfiguration.androidBuildToolsVersion

    defaultConfig {
        applicationId "com.example.gsyvideoplayer"

        multiDexEnabled true

        minSdkVersion globalConfiguration.androidMinSdkVersion
        targetSdkVersion globalConfiguration.androidTargetSdkVersion

        versionCode 5
        versionName "4.0.0"

        javaCompileOptions {
            annotationProcessorOptions.includeCompileClasspath = true
        }
        ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi', 'armeabi-v7a', 'x86'
        }

    }


    signingConfigs {
        releaseConfig {
            storeFile file("../debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
        }
    }

    buildTypes {

        release {
            minifyEnabled false
            signingConfig signingConfigs.releaseConfig
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    def viewDependencies = rootProject.ext.viewDependencies
    def androidDependencies = rootProject.ext.androidDependencies
    def dataDependencies = rootProject.ext.dataDependencies
    annotationProcessor viewDependencies.apt_butterKnife
    //debugCompile dataDependencies.leakcanary
    implementation viewDependencies.butterKnife
    implementation androidDependencies.recyclerView
    implementation viewDependencies.DanmakuFlameMaster
    implementation viewDependencies.ndkbitmap_armv7a
    implementation viewDependencies.ndkbitmap_armv5
    implementation viewDependencies.ndkbitmap_x86
    implementation viewDependencies.glide
    implementation viewDependencies.glideProcessor
    implementation androidDependencies.support_v4
    implementation androidDependencies.design
    implementation dataDependencies.okhttpUtil
    implementation dataDependencies.okhttp
    implementation(dataDependencies.permissionsdispatcher) {
        // if you don't use android.app.Fragment you can exclude support for them
        exclude module: "support-v13"
    }
    annotationProcessor dataDependencies.permissionsdispatcherProcessor
    //jcenter
    //implementation "com.shuyu:GSYVideoPlayer:$gsyVideoVersion"
    //implementation "com.shuyu:gsyVideoPlayer-java:$gsyVideoVersion'
    //implementation "com.shuyu:gsyVideoPlayer-armv5:$gsyVideoVersion"
    //implementation "com.shuyu:gsyVideoPlayer-armv7a:$gsyVideoVersion"
    //implementation "com.shuyu:gsyVideoPlayer-arm64:$gsyVideoVersion"
    //implementation "com.shuyu:gsyVideoPlayer-x64:$gsyVideoVersion"
    //implementation "com.shuyu:gsyVideoPlayer-x86:$gsyVideoVersion"
    //    implementation "com.shuyu:gsyVideoPlayer-ex_so:$gsyVideoVersion"
    implementation project(':gsyVideoPlayer-ex_so')
}
`

**Comment by CarGuo** [comment]
你可以reset之后更新下demo，现在的demo已经修改为ex so的依赖

**Comment by MaryDQ** [comment]
reset是啥意思？android studio自带的功能吗

**Comment by MaryDQ** [comment]
是git的那个reset命令吗

**Comment by CarGuo** [comment]
额…我的意思是恢复demo到原本的样子，然后更新下新demo试试

**Comment by MaryDQ** [comment]
您好，试了下已经可以播放了，话说修改为exso的依赖我自己得在哪个地方改？另外想在自己的包路径下使用你的so库，是需要重新编译的吧？

**Comment by CarGuo** [comment]
```
compile 'com.shuyu:gsyVideoPlayer-java:5.0.0-beta'

compile 'com.shuyu:gsyVideoPlayer-ex_so:5.0.0-beta'
```
