### ISSUE TITLE
一直打印一个日志

### ISSUE THREAD

**Issue by magical-xu** [CarGuo/GSYVideoPlayer#1174]
是不是有日志 没关掉 发现在 播放视频时 一直打印一个log如下：
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
试了 demo 也是   
尝试了手动调用 Debuger.disable() 也还是会一直报  是不是没在日志管理下输出的

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);

**Comment by magical-xu** [comment]
没有这个方法

**Comment by CarGuo** [comment]
抱歉，那个是旧版本的，IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);

**Comment by magical-xu** [comment]
好的
