### ISSUE TITLE
播放同一个域名下视频，切换HTTP和HTTPS播放源，播放失败

### ISSUE THREAD

**Issue by haohaozaici** [CarGuo/GSYVideoPlayer#1175]
## 问题描述：

播放同一个域名下视频，切换HTTP和HTTPS播放源，播放失败
单独播放时都可以播放

## 问题机型/系统：

真机 小米5 Android8.0 MIUI开发版

## Demo中的复现步骤

修改Demo中的SimpleListVideoModelAdapter，替换为以下播放源
``` java
final String urlH = "https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8";
final String urlV = "http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8";
```

## 问题log（如果有）

```
// https -> http
06-07 09:26:26.411 11640-12402/com.example.gsyvideoplayer E/IJKMEDIA: http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8: Connection reset by peer
06-07 09:26:26.413 11640-12178/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

// http -> https
06-07 09:37:58.093 13044-13159/com.example.gsyvideoplayer E/IJKMEDIA: Unable to negotiate TLS/SSL session
06-07 09:37:58.099 13044-13159/com.example.gsyvideoplayer E/IJKMEDIA: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8: I/O error

```
猜测可能与OpenSSL有关...

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md  第18

**Comment by haohaozaici** [comment]
不好意思，之前没有注意和检索到...

**Comment by haohaozaici** [comment]
非常感谢~没有认真看注意事项。。
在网上检索了很久都没匹配到

**Comment by jacky-zhupengpeng** [comment]
我设置了为什么还是不可以
小米手机 9.0系统

**Comment by Piscen** [comment]
同上一个哥们的问题，小米8，9.0系统。
videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_timeout", -1);
        list.add(videoOptionModel);
设置了依然播放失败
