### ISSUE TITLE
请问支持WMV格式的视频吗

### ISSUE THREAD

**Issue by uncleShi** [CarGuo/GSYVideoPlayer#1178]

**Comment by CarGuo** [comment]
不支持

**Comment by HaoZongGit** [comment]
为什么我换了支持avi格式的ijkplayerarmv7里面的库编译成apk后库又改回原样了

**Comment by HaoZongGit** [comment]
![image](https://user-images.githubusercontent.com/39650943/41188007-4e479cb6-6be9-11e8-88e9-35d48369a421.png)
是这个地方只留v7是吧
![image](https://user-images.githubusercontent.com/39650943/41188014-6e7e133e-6be9-11e8-89dc-4136737005f8.png)
改这个地方的三个so不行么

**Comment by CarGuo** [comment]
是的
