### ISSUE TITLE
添加支持rtsp的依赖报错

### ISSUE THREAD

**Issue by 1294694985** [CarGuo/GSYVideoPlayer#1179]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：添加支持rtsp的依赖报错 
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

理论上是依赖重复或者方法冗余超限，但是我就是新建立了一个项目也是会出现这个问题。然后尝试添加
multiDexEnabled true      compile 'com.android.support:multidex:1.0.1'    并没有解决问题。 app module 
gradle 依赖如下 
![image](https://user-images.githubusercontent.com/17264211/41136109-62c76852-6b07-11e8-890b-edd003ffb710.png)

XXXX发生了这样的问题！

## Demo中的复现步骤  demo中添加rtsp直播流也没有能够支持啊。更改demo 支持rtsp的依赖之后也是报错。
![image](https://user-images.githubusercontent.com/17264211/41136160-a161927c-6b07-11e8-88d8-c1e576f2f1dc.png)

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

xxxxxxx

```

**Comment by CarGuo** [comment]
bin并不是很清楚的问题，demo使用rtsp正常编译运行
