### ISSUE TITLE
两级的fragment，全屏会有以下问题

### ISSUE THREAD

**Issue by wang869755676** [CarGuo/GSYVideoPlayer#1180]
## 问题描述：

当fragment中有ViewPager。viewPager中的fragment是RecyclerView，当童通过直接orientationUtils.resolveByClick()进去全屏，如果item位于屏幕的下方，进入全屏后，无法退出全屏，
打断点的时候是 未走 backToNormal();

**Comment by CarGuo** [comment]
不是很理解，为什么RecyclerView中的要调用orientationUtils.resolveByClick()进去全屏，全屏调用全屏方法啊

**Comment by wang869755676** [comment]
全屏是两种，一种是竖着的，一种横着的，我想要点击全屏的时候，直接进入到横着的效果。这是adapter里面
![image](https://user-images.githubusercontent.com/17445635/41141463-9e202ae8-6b24-11e8-9b14-ea197e1eecec.png)

![image](https://user-images.githubusercontent.com/17445635/41141425-7b105a6e-6b24-11e8-8a24-2ccf6c552fd5.png)

**Comment by CarGuo** [comment]
你把demo的RecyclerItemNormalHolder里，修改这两个设置就可以了啊
```
.setRotateViewAuto(false)
.setShowFullAnimation(false)
```
![5b1a23f6e4b0191ec6d55b68](https://user-images.githubusercontent.com/10770362/41142753-69996b4a-6b29-11e8-8e98-fd3d968aa747.jpg)

**Comment by wang869755676** [comment]
嗯，我那会试过这种方式，是可以的，按返回就能推出的，

**Comment by CarGuo** [comment]
所以？？

**Comment by wang869755676** [comment]
就是我用orintationUitls，直接进去全屏 那个退不出来的，用setRotateViewAuto(true) 这种直接进入全屏就可以的退出。

**Comment by wang869755676** [comment]
我现在还有个问题：就是在onPause中调用video.onVideoPause();然后回来的时候，不在onResume中调用video.onVideoResume(); 此时视频上是黑屏，我想让他显示为暂停时的那一帧，我需要如何做

**Comment by CarGuo** [comment]
为什么需要用这种？？？

**Comment by wang869755676** [comment]
我不是说一定需要这种的，而是在这种情况下有问题，
