### ISSUE TITLE
如何让 GSYTextureView重新渲染？

### ISSUE THREAD

**Issue by magical-xu** [CarGuo/GSYVideoPlayer#1181]
![企业微信截图_152843223922.png](https://upload-images.jianshu.io/upload_images/5120402-30cbd880fb9090a3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)  

问题：
已经加载的视频，在带有虚拟导航栏的手机上，把虚拟导航栏隐藏掉，布局变化会导致多出下一个页面的一块区域 见截图
我分析了一下布局发现 播放器的父布局和封面的View 高度都是对的了 就是 GSYTextureView的高度不对
调用了   
        GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);
        changeTextureViewShowType();
        GSYTextureView texture = getTexture();
        if (null != texture) {
            texture.requestLayout();
        }  
发现都无效，怎么让它能重新正确的渲染呢？

**Comment by CarGuo** [comment]
demo中怎么复现

**Comment by magical-xu** [comment]
demo中没这种场景 我再试试吧
