### ISSUE TITLE
将avi格式的视频转成MP4直接接就播不了了

### ISSUE THREAD

**Issue by HaoZongGit** [CarGuo/GSYVideoPlayer#1184]

**Comment by HaoZongGit** [comment]
h264和aac

**Comment by HaoZongGit** [comment]
E/IJKMEDIA: 192.168.31.98:8080/sd1516070888_2.MP4: Protocol not found
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [9313]
D/IJKMEDIA: FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by CarGuo** [comment]
如果转换后是h264h和aac是支持的
