### ISSUE TITLE
4.1.3 使用IJKPlayer播放本地视频失败

### ISSUE THREAD

**Issue by WaterElva** [CarGuo/GSYVideoPlayer#1185]
1.问题RT
2.如何设置循环播放？设置loop也无效 SYSTEM、IJKEXPLORE 难道要升到5.0才支持EXO?
3.还有个继承播放器的什么UI状态改变的方法（忘记名称了） 关闭网络后状态一直是缓冲状态，理论上断网后肯定抛出异常，但是并没有回调错误状态

**Comment by WaterElva** [comment]
问题1格式是MP4 只要不适用IJKPlayer就可以播放

**Comment by CarGuo** [comment]
本地视频file鞋子开头

**Comment by CarGuo** [comment]
Exo的loop要5.0才生效

**Comment by CarGuo** [comment]
第三个怎么demo重现。
