### ISSUE TITLE
怎么用mp4Parser处理过的视频，播发没画面只有声音

### ISSUE THREAD

**Issue by KnowledgeBegger** [CarGuo/GSYVideoPlayer#1186]
## 问题描述：
我用Mp4Parser框架替换了原视频的音频轨，在IjkPlayer模式下播放替换后的视频只有声音，没有画面。
我拿你的demo播放那个视频也是这样。
我切换为系统播放器模式，或者直接拿手机自带的播放器就有画面。

**Comment by CarGuo** [comment]
转换后的视频编码格式和音频编码格式是？

**Comment by KnowledgeBegger** [comment]
格式 iso6  
视频编解码器 avc
音频格式 aac

**Comment by CarGuo** [comment]
视频编码转为 h264 或 mpeg之类的吧

**Comment by KnowledgeBegger** [comment]
就是很奇怪，我拿英语趣配音（也是使用mp4parser），配出来的视频我把这个视频自己进行第二次配音，格式也是iso6  aac却能正常播放。

**Comment by CarGuo** [comment]
这就不是很清楚了
