### ISSUE TITLE
手动添加ijkplayer依赖的问题

### ISSUE THREAD

**Issue by HaoZongGit** [CarGuo/GSYVideoPlayer#1187]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：在demo里面手动添加ijkpalyer的库时提示已经存在一个 怎么把之前的去掉

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不是很理解，项目已经集成了ijk了
