### ISSUE TITLE
https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.3/runtime-1.0.3.aar, 这个依赖是哪里的？

### ISSUE THREAD

**Issue by smoothdvd** [CarGuo/GSYVideoPlayer#1188]
## 问题描述：

* What went wrong:
Could not resolve all files for configuration ':gsyVideoPlayer:debugCompileClasspath'.
> Could not find runtime.aar (android.arch.lifecycle:runtime:1.0.3).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.3/runtime-1.0.3.aar

**Comment by CarGuo** [comment]
maven { url 'https://maven.google.com' }
        google()

加上这个试试
