### ISSUE TITLE
添加依赖后一直报v4包重复

### ISSUE THREAD

**Issue by CheersLiu** [CarGuo/GSYVideoPlayer#1191]
这边添加依赖之后一直报v4包冲突，下载源码发现源码依赖中有两个不同版本的v4包，请问这个问题需要怎么处理

**Comment by CarGuo** [comment]
项目中的supprot包版本都是从 https://github.com/CarGuo/GSYVideoPlayer/blob/master/dependencies.gradle 这里获取的，所以你可以选择

升级的v4 v7等包到27.0.2

或者 exclude 处理掉冲突的
```
compile('com.xxxx.xxxx:1.1.0') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
}
```

**Comment by Selina592732122** [comment]
compile ('com.shuyu:GSYVideoPlayer:7.0.2'){
        exclude group: 'com.android.support', module: 'support-v4'
 }
请问已经这么写了还是无效，是为什么呢？
