### ISSUE TITLE
有个需求就是设置进度条不可以拖动，我禁止seekbar后，普通模式正常，全屏模式可以拖动，怎么回事

### ISSUE THREAD

**Issue by Luckylll** [CarGuo/GSYVideoPlayer#1193]
seekbar进度条禁止拖动，全屏无效

**Comment by CarGuo** [comment]
你是怎么设置禁止的？

**Comment by Luckylll** [comment]
继承StandardGSYVideoPlayer，设置mProgressBar.setEnabled(false);

**Comment by CarGuo** [comment]
重载init方法里设置的话应该是可以的

**Comment by Luckylll** [comment]
这样就设置死了，如果要恢复可以拖动呢？请问设置从指定时间开始播放该怎么设置？暂没找到

**Comment by CarGuo** [comment]
你是希望动态的外部设置的话，你需要player.getCurrentPlayer().XXXXX这样

**Comment by zhaowenhao2015** [comment]
> 这样就设置死了，如果要恢复可以拖动呢？请问设置从指定时间开始播放该怎么设置？暂没找到
你好我也遇到同样的问题，小屏不可以，全屏seekbar可以拖动，使用player.getCurrentPlayer().XXXXX找不到自定义的方法，你是怎么解决的呢  ？求指教

**Comment by xiaoshubin** [comment]
> > 这样就设置死了，如果要恢复可以拖动呢？请问设置从指定时间开始播放该怎么设置？暂没找到
> > 你好我也遇到同样的问题，小屏不可以，全屏seekbar可以拖动，使用player.getCurrentPlayer().XXXXX找不到自定义的方法，你是怎么解决的呢  ？求指教

也就是说使用你自己自定义的Player的的禁用方法，例如你自定义了一个禁止拖动的的Player：
class SeekGsyVideoPlayer: StandardGSYVideoPlayer {
    constructor(context: Context) : super(context) 
    constructor(context: Context, attrs: AttributeSet?) : super(context, attrs)
    fun setProgressBarEnabled(enabled: Boolean) {
        mProgressBar.isEnabled = enabled
    }
}
那么可以获取全屏的播放器，然后调用你自定义的setProgressBarEnabled方法
bind.videoPlayer. (fullWindowPlayer as SeekGsyVideoPlayer).setProgressBarEnabled(isLearnComplete)
