### ISSUE TITLE
播放卡顿

### ISSUE THREAD

**Issue by wang869755676** [CarGuo/GSYVideoPlayer#1194]
http://huashang.nos-eastchina1.126.net/video/1528707789000N1I9.mp4 此视频在播放过程中一卡一卡的，一直显示那个加载，然后波一下，又在加载，这个需要怎么解决

**Comment by CarGuo** [comment]
切换GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2); 试试
