### ISSUE TITLE
ListGSYVideoPlayer 会导致内存泄露

### ISSUE THREAD

**Issue by BerkeWu** [CarGuo/GSYVideoPlayer#1195]
问题描述：

在调用  GSYVideoManager.releaseAllVideos()  释放播放器后，会回调 onCompletion() 方法，但是  ListGSYVideoPlayer 重写了该方法，导致 super.onCompletion()  无法被调用，释放网络监听的方法没被调用，导致内存泄露

**Comment by CarGuo** [comment]
嗯嗯，是的，下版本修复

**Comment by CarGuo** [comment]
5.0.1

**Comment by wzgl5533** [comment]
我现在也有泄漏的问题，感觉还存在
`
* references com.shuyu.gsyvideoplayer.video.base.GSYVideoView$1.this$0 (anonymous implementation of android.media.AudioManager$OnAudioFocusChangeListener)
* references com.shuyu.gsyvideoplayer.video.ListGSYVideoPlayer.mContext
* leaks com.hitrobotgroup.hiiri.nobody.dkgc.activity.player.ContinuousPlayerAC instance
`

**Comment by CarGuo** [comment]
OnAudioFocusChangeListener 属于正常泄漏，系统污泄漏

**Comment by lzybilian** [comment]
但是这个泄漏，会持有activity，activity无法回收，就会内存溢出了

**Comment by coolmaye** [comment]
@lzybilian > 您最后解决了吗？仓主说可以直接无视，但是它持有了我的Activity啊，我反复开关十几次视频播放页面，内存会增加几百m的开销并且无法被释放，没有别的解决办法了吗

**Comment by lzybilian** [comment]
> @lzybilian > 您最后解决了吗？仓主说可以直接无视，但是它持有了我的Activity啊，我反复开关十几次视频播放页面，内存会增加几百m的开销并且无法被释放，没有别的解决办法了吗

我有点忘记了当时的场景了。
