### ISSUE TITLE
请问大神：横竖屏切换时弹幕会消失，DanmuView.pause后再resume弹幕也会消失，该怎么解决呢

### ISSUE THREAD

**Issue by KnightBubble** [CarGuo/GSYVideoPlayer#1198]

**Comment by CarGuo** [comment]
如demo中一样啊，消失只是瞬间，下一秒就都出来了

**Comment by KnightBubble** [comment]
其实想要的效果是不让它消失，因为下一秒出来的是后面的数据啦，相当于当前屏幕的弹幕没啦。。现在情况是横竖屏切换、暂停后再开始，都会清屏。。。

**Comment by KnightBubble** [comment]
大神我知道为什么切换横竖屏时弹幕会消失了，因为会重新执行DanmakuVideoPlayer的init的方法，会重新initDanmaku()初始化弹幕显示，danmuview与解析器都是新初始化的。。所以会这样。。这个有什么解决办法吗？

**Comment by CarGuo** [comment]
这是因为切换横竖屏的时候，是切换了显示控件，除非你把弹幕解析器等独立，切换时只切换渲染层，类似播放器只切换渲染控件，内核独立
