### ISSUE TITLE
似乎不支持avi格式的视频？？

### ISSUE THREAD

**Issue by tangjian211085** [CarGuo/GSYVideoPlayer#1199]
## 问题描述：

在测试过程中发现avi格式的视频播放不了

06-14 10:31:50.161 13639-13639/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Again http://192.168.1.88/video/2018/6de67dd994e248e78e9f76c71fdefcf0.avi
06-14 10:31:50.167 13639-13843/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
06-14 10:31:52.332 13639-13843/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
06-14 10:31:53.557 13639-13877/com.example.gsyvideoplayer E/IJKMEDIA: http://192.168.1.88/video/2018/6de67dd994e248e78e9f76c71fdefcf0.avi: **Invalid data found when processing input**
Invalid data found when processing input
06-14 10:31:53.557 13639-13843/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
06-14 10:31:53.558 13639-13639/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
06-14 10:31:53.558 13639-13639/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Again http://192.168.1.88/video/2018/6de67dd994e248e78e9f76c71fdefcf0.avi
06-14 10:31:53.561 13639-13843/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);

**Comment by tangjian211085** [comment]
设置这个后，播放avi格式报错。
Link Or mCache Error, Please Try Again http://192.168.1.88/video/2018/6de67dd994e248e78e9f76c71fdefcf0.avi
com.google.android.exoplayer2.ExoPlaybackException
Caused by: com.google.android.exoplayer2.source.**UnrecognizedInputFormatException**: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.

**Comment by CarGuo** [comment]
有外网测试url吗

**Comment by tangjian211085** [comment]
我之前用的是jiecao的，感觉用起来不太方便，切换全屏时不是特别的流畅。在网上看到这个，就想试试看的。外网的话，没有耶。项目已经交付了，我也不能随便上传视频了。可以的话，能否加下我QQ呢，我把视频发给你试试？？790548749

**Comment by tangjian211085** [comment]
1. GSYVideoType类中
    //默认播放内核IJK
    public final static int IJKPLAYER = 0;
    /**
     * IJKEXOPLAYER 和 IJKEXOPLAYER2 是互斥的
     * **IJKEXOPLAYER2 must be compile com.shuyu:gsyVideoPlayer-exo2:$gsyVideoVersion**
     */
    //EXO 2 播放内核
    public final static int IJKEXOPLAYER2 = 2;
    //EXO 1 播放内核，弃用，现在使用的是IJKEXOPLAYER2

2. dependencie.gradle文件下  
        gsyVideoVersion = '5.0.0-beta'
        videocache      : "com.shuyu:gsyvideoplayer-androidvideocache:${gsyVideoVersion}",
        只有这一处用到了gsyVideoVersion。

3.那么**must be compile com.shuyu:gsyVideoPlayer-exo2:$gsyVideoVersion**  这个又是什么意思呢？？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1206
