### ISSUE TITLE
请问，判断全屏的问题或者是拿到当前的videoPlayer对象问题。

### ISSUE THREAD

**Issue by taany6210** [CarGuo/GSYVideoPlayer#12]
我现在在MainActivity中有几个fragment，第一个fragment中一个RecyclerView，这里面的一个列表中有一个视频播放，切换fragment怎么暂停视频播放？
   还有在MainActivity的返回事件中怎么判断是不是需要播放器返回？
   另外就是第一个fragment按Home按钮到后台，再换到前台，如何做暂停和播放动作？
   最后就是ListVideo2Activity中如果换成RecyclerView在小窗口出来的时候回卡一下，没有listView流畅。

**Comment by CarGuo** [comment]
你用的是ListVideoUtils吗？如果是直接用VIdeoPLayer的有OnResume和OnPAUNSE的接口，LIstVIdeoUTils也可以直接拿回对象，然后全屏的话有监听接口，参考demo的simpleListener那样重载，有进入全屏和非全屏的接口，在按下返回键的位置demo里面应该有对应写的。然后释放是有对应的如releaseAllVIdeo之类接口的。视频退出全屏也有对应的静态方法，可以看下demo。至于recyclerview的问题，晚点我看一下，现在身边没电脑，方便的话你可以把你的实现方式给我看看吗？

**Comment by CarGuo** [comment]
更新了demo，目前发现recyclerView的小窗口没出现卡顿情况(＾－＾)

**Comment by taany6210** [comment]
卡顿的问题是我添加了代理导致的，去掉代理就不卡了，我不是用的ListVideoUtils，直接用的VIdeoPLayer在首页的fragment里面的adapter里，调用OnResume得要对象吧，给个邮箱吧，我吧具体的代码发给你帮我瞅瞅。我找了你的简书和这里没发现有邮箱。

**Comment by CarGuo** [comment]
359369982@qq.com  发这里吧~
