### ISSUE TITLE
本地的m3u8文件，加密的key文件也为本地的，报错不能打开本地加密的key文件！

### ISSUE THREAD

**Issue by chaoDream** [CarGuo/GSYVideoPlayer#1200]
m3u8加密使用的是本地的加密使用的这种方法

#EXT-X-KEY:METHOD=AES-128,URI="file://storage/emulated/0/Android/data/com.dongao.mobile.universities/files/Download/playOnline/3984_7644/keyText.txt",IV=0x96980095340314969443565909e6429e

就会报错误：

06-14 14:03:28.961 22091-22301/com.dongao.mobile.universities W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
06-14 14:03:28.961 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: IjkMediaPlayer_prepareAsync
06-14 14:03:28.961 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ijkmp_prepare_async()
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: ===== versions =====
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: ijkplayer    : k0.8.8
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: FFmpeg       : ff3.4--ijk0.8.7--20180103--001
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: libavutil    : 55.78.100
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: libavcodec   : 57.107.100
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: libavformat  : 57.83.100
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: libswscale   : 4.8.100
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: libswresample: 2.9.100
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: ===== options =====
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: player-opts : loop                         = 1
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: format-opts : ijkapplication               = -1584877984
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: format-opts : ijkiomanager                 = -1583883520
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: format-opts : protocol_whitelist           = crypto,file,http,https,tcp,tls,udp,hls
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: format-opts : allowed_extensions           = ALL
06-14 14:03:28.962 22091-22301/com.dongao.mobile.universities I/IJKMEDIA: ===================
06-14 14:03:28.964 22091-26238/com.dongao.mobile.universities I/IJKMEDIA: SDL_RunThread: [26238] ff_msg_loop
06-14 14:03:28.964 22091-26238/com.dongao.mobile.universities D/IJKMEDIA: message_loop
06-14 14:03:28.965 22091-26238/com.dongao.mobile.universities D/IJKMEDIA: FFP_MSG_FLUSH:
06-14 14:03:28.966 22091-26239/com.dongao.mobile.universities I/IJKMEDIA: SDL_RunThread: [26239] ff_vout
06-14 14:03:28.966 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ijkmp_prepare_async()=0
06-14 14:03:28.966 22091-26240/com.dongao.mobile.universities I/IJKMEDIA: SDL_RunThread: [26240] ff_read
06-14 14:03:28.966 22091-26240/com.dongao.mobile.universities D/IJKMEDIA: Opening 'file://storage/emulated/0/Android/data/com.dongao.mobile.universities/files/Download/playOnline/3984_7644/online.m3u8' for reading
06-14 14:03:28.966 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: Probing hls,applehttp score:100 size:2048
06-14 14:03:28.966 22091-26240/com.dongao.mobile.universities D/IJKMEDIA: Format hls,applehttp probed with size=2048 and score=100
06-14 14:03:28.968 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: new_program: id=0x0000
06-14 14:03:28.968 22091-26240/com.dongao.mobile.universities I/IJKMEDIA: HLS request for url 'http://v.dongaocloud.com/2b4f/2b4f/3d7/f48/f662831b13767c199869e4ac1036e012/f662831b13767c199869e4ac1036e012-000.ts', offset 0, playlist 0
06-14 14:03:28.968 22091-26240/com.dongao.mobile.universities I/IJKMEDIA: Opening 'file://storage/emulated/0/Android/data/com.dongao.mobile.universities/files/Download/playOnline/3984_7644/keyText.txt' for reading
06-14 14:03:28.968 22091-26240/com.dongao.mobile.universities E/IJKMEDIA: Unable to open key file file://storage/emulated/0/Android/data/com.dongao.mobile.universities/files/Download/playOnline/3984_7644/keyText.txt
06-14 14:03:28.968 22091-26240/com.dongao.mobile.universities I/IJKMEDIA: Opening 'crypto+http://v.dongaocloud.com/2b4f/2b4f/3d7/f48/f662831b13767c199869e4ac1036e012/f662831b13767c199869e4ac1036e012-000.ts' for reading
06-14 14:03:28.969 22091-26240/com.dongao.mobile.universities I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
06-14 14:03:28.969 22091-26240/com.dongao.mobile.universities I/IJKMEDIA: Hit DNS cache hostname = v.dongaocloud.com
06-14 14:03:28.969 22091-26240/com.dongao.mobile.universities I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
06-14 14:03:29.057 22091-26240/com.dongao.mobile.universities I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
06-14 14:03:29.057 22091-26240/com.dongao.mobile.universities D/IJKMEDIA: request: GET /2b4f/2b4f/3d7/f48/f662831b13767c199869e4ac1036e012/f662831b13767c199869e4ac1036e012-000.ts HTTP/1.1
                                                                          User-Agent: Lavf/57.83.100
                                                                          Accept: */*
                                                                          Connection: close
                                                                          Host: v.dongaocloud.com
                                                                          Icy-MetaData: 1
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='HTTP/1.1 200 OK'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: http_code=200
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Server: DnionOS/1.11.2.4_7'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Date: Thu, 14 Jun 2018 06:03:17 GMT'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Content-Type: application/octet-stream'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Content-Length: 592960'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Connection: close'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Last-Modified: Mon, 26 Dec 2016 05:27:23 GMT'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Expires: Sun, 24 Jun 2018 03:27:32 GMT'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Cache-Control: max-age=864000'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Accept-Ranges: bytes'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Age: 9347'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Via: CT-CMC-CNC-JSCZ-P-164-199 (DLC-3.0), XNOP061-CNC-SDJNS-C-226-113 (DLC-3.0)'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='HitType: TCP_F_HIT'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Server-Info: DnionATS'
06-14 14:03:29.137 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header=''
06-14 14:03:29.139 22091-26240/com.dongao.mobile.universities I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
06-14 14:03:30.494 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: Probing mp3 score:1 size:2048
06-14 14:03:30.494 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: Probing mp3 score:1 size:4096
06-14 14:03:30.497 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: Probing mp3 score:1 size:8192
06-14 14:03:30.499 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: Probing mp3 score:1 size:16384
06-14 14:03:46.272 22091-26240/com.dongao.mobile.universities D/IJKMEDIA: Statistics: 592944 bytes read, 0 seeks
06-14 14:03:46.273 22091-26240/com.dongao.mobile.universities I/IJKMEDIA: HLS request for url 'http://v.dongaocloud.com/2b4f/2b4f/3d7/f48/f662831b13767c199869e4ac1036e012/f662831b13767c199869e4ac1036e012-001.ts', offset 0, playlist 0
06-14 14:03:46.273 22091-26240/com.dongao.mobile.universities I/IJKMEDIA: Opening 'crypto+http://v.dongaocloud.com/2b4f/2b4f/3d7/f48/f662831b13767c199869e4ac1036e012/f662831b13767c199869e4ac1036e012-001.ts' for reading
06-14 14:03:46.273 22091-26240/com.dongao.mobile.universities I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
06-14 14:03:46.273 22091-26240/com.dongao.mobile.universities I/IJKMEDIA: Hit DNS cache hostname = v.dongaocloud.com
06-14 14:03:46.273 22091-26240/com.dongao.mobile.universities I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
06-14 14:03:46.394 22091-26240/com.dongao.mobile.universities I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
06-14 14:03:46.394 22091-26240/com.dongao.mobile.universities D/IJKMEDIA: request: GET /2b4f/2b4f/3d7/f48/f662831b13767c199869e4ac1036e012/f662831b13767c199869e4ac1036e012-001.ts HTTP/1.1
                                                                          User-Agent: Lavf/57.83.100
                                                                          Accept: */*
                                                                          Connection: close
                                                                          Host: v.dongaocloud.com
                                                                          Icy-MetaData: 1
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='HTTP/1.1 200 OK'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: http_code=200
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Server: DnionOS/1.11.2.4_7'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Date: Thu, 14 Jun 2018 06:03:34 GMT'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Content-Type: application/octet-stream'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Content-Length: 563440'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Connection: close'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Last-Modified: Mon, 26 Dec 2016 05:27:23 GMT'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Expires: Sun, 24 Jun 2018 03:27:47 GMT'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Cache-Control: max-age=864000'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Accept-Ranges: bytes'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Age: 9347'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Via: CT-CMC-CNC-JSCZ-P-164-198 (DLC-3.0), XNOP061-CNC-SDJNS-C-226-114 (DLC-3.0)'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='HitType: TCP_F_HIT'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header='Server-Info: DnionATS'
06-14 14:03:46.472 22091-26240/com.dongao.mobile.universities V/IJKMEDIA: header=''
06-14 14:03:46.473 22091-26240/com.dongao.mobile.universities I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
06-14 14:03:56.868 22091-26240/com.dongao.mobile.universities E/IJKMEDIA: Error when loading first segment 'http://v.dongaocloud.com/2b4f/2b4f/3d7/f48/f662831b13767c199869e4ac1036e012/f662831b13767c199869e4ac1036e012-000.ts'
06-14 14:03:56.868 22091-26240/com.dongao.mobile.universities D/IJKMEDIA: Statistics: 456512 bytes read, 0 seeks
06-14 14:03:56.869 22091-26240/com.dongao.mobile.universities D/IJKMEDIA: Statistics: 37098 bytes read, 0 seeks
06-14 14:03:56.869 22091-26240/com.dongao.mobile.universities E/IJKMEDIA: file://storage/emulated/0/Android/data/com.dongao.mobile.universities/files/Download/playOnline/3984_7644/online.m3u8: Invalid data found when processing input
06-14 14:03:56.869 22091-26240/com.dongao.mobile.universities I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [26240]
06-14 14:03:56.869 22091-26238/com.dongao.mobile.universities D/IJKMEDIA: FFP_MSG_ERROR: 0
06-14 14:03:56.869 22091-22301/com.dongao.mobile.universities E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
06-14 14:03:56.869 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: IjkMediaPlayer_release
06-14 14:03:56.870 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
06-14 14:03:56.870 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ffpipeline_set_surface()
06-14 14:03:56.870 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
06-14 14:03:56.870 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ijkmp_shutdown_l()
06-14 14:03:56.870 22091-26238/com.dongao.mobile.universities D/IJKMEDIA: message_loop exit
06-14 14:03:56.870 22091-26238/com.dongao.mobile.universities I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [26238]
06-14 14:03:56.871 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: wait for read_tid
06-14 14:03:56.871 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: wait for video_refresh_tid
06-14 14:03:56.875 22091-26239/com.dongao.mobile.universities I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [26239]
06-14 14:03:56.875 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ijkmp_shutdown_l()=void
06-14 14:03:56.875 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ijkmp_dec_ref(): ref=0
06-14 14:03:56.875 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ijkmp_shutdown_l()
06-14 14:03:56.875 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: ijkmp_shutdown_l()=void
06-14 14:03:56.876 22091-22301/com.dongao.mobile.universities D/IJKMEDIA: IjkMediaPlayer_setVolume
@CarGuo

**Comment by tangjian211085** [comment]
你好。请问你的可以播放avi格式的视频吗？

**Comment by chaoDream** [comment]
没有尝试，只尝试了m3u8，正常的都能播，就是加密的本地读取出了问题！ @tangjian211085

**Comment by CarGuo** [comment]
@chaoDream 替换依赖ex_so试试，它是支持crypto加密的。
然后加上白名单

```
VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", crypto,file,http,https,tcp,tls,udp);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by chaoDream** [comment]
现在用的就是这个
api('com.shuyu:gsyVideoPlayer-java:4.1.3') {
        exclude module: 'support-v4'
}
api('com.shuyu:gsyVideoPlayer-ex_so:4.1.3') {
        exclude module: 'support-v4'
}
然后加了两个支持，
VideoOptionModel videoOptionModel =
				new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "crypto,file,http,https,tcp,tls,udp,hls");
		VideoOptionModel videoOptionModel2 =
				new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_extensions", "ALL");
		List<VideoOptionModel> list = new ArrayList<>();
		list.add(videoOptionModel);
		list.add(videoOptionModel2);
		GSYVideoManager.instance().setOptionModelList(list);
然后才报的那个错误！
@CarGuo

**Comment by chaoDream** [comment]
不好意思，自己设置错参数了！导致播放不了！打扰了！ @CarGuo

**Comment by RockyQu** [comment]
@chaoDream 你好，请问我是播放一个加密的m3u8，加了上面的代码，报 Protocol 'file' not on whitelist 'crypto, file, http, https, tcp, tls, udp'! 你的是哪里参数设置错了？

**Comment by xm2017** [comment]
@chaoDream 大佬我也遇到类似的问题 请问参数错了指的是什么错了呢

**Comment by chaoDream** [comment]
我的是设置的m3u8中ts地址出错导致的！播放本地m3u8，就看你的ts的地址是否是本地的！ @xm2017

**Comment by xm2017** [comment]
@chaoDream  谢谢大佬 发现本地没有下载key  下载了就好了

**Comment by AttackPangHu** [comment]
> 我的是设置的m3u8中ts地址出错导致的！播放本地m3u8，就看你的ts的地址是否是本地的！ @xm2017

大佬，我这边本地的KEY和TS都下载好了，协议也全设置了，但是播放本地的M3U8索引文件还是会报错
 com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NumberFormatException: Invalid BigInteger: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:465)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
好像是解密出的问题，请问有遇到这种情况吗？

#EXT-X-KEY:METHOD=AES-128,URI="/storage/emulated/0/Android/data/com.prince.alone_recommend/files/Movies/87550e2509560098399b553328ef148d.key",IV=null
#EXTINF:3.003,
/storage/emulated/0/Android/data/com.prince.alone_recommend/files/Movies/.test.m3u8_0/0.ts
#EXTINF:3.003,
/storage/emulated/0/Android/data/com.prince.alone_recommend/files/Movies/.test.m3u8_0/1.ts
#EXTINF:3.003,
/storage/emulated/0/Android/data/com.prince.alone_recommend/files/Movies/.test.m3u8_0/2.ts
#EXTINF:3.003,
/storage/emulated/0/Android/data/com.prince.alone_recommend/files/Movies/.test.m3u8_0/3.ts
#EXTINF:3.003,
