### ISSUE TITLE
viewpager中播放视频问题

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1201]
viewpageradapter中的视频横竖屏切换具体应该怎么搞,没有相关demo,求指点

**Comment by CarGuo** [comment]
和在哪里没关系，具体说明问题？

**Comment by darkrevier** [comment]
全屏返回黑屏 但是视频还在播
 danmakuVideoPlayer.setLockLand(true);
        danmakuVideoPlayer.setRotateViewAuto(false);
        danmakuVideoPlayer.setIsTouchWiget(false);
        danmakuVideoPlayer.setShowFullAnimation(true);
        danmakuVideoPlayer.setNeedLockFull(true);
 getDanmakuVideoPlayer().getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                resolveFullBtn(getDanmakuVideoPlayer());
            }
        });
    private void resolveFullBtn(final StandardGSYVideoPlayer standardGSYVideoPlayer) {
        if (orientationUtils != null) {
            resolveFull();
        }
        standardGSYVideoPlayer.startWindowFullscreen(getContext(), false, true);
    }
    private void resolveFull() {
        if ( orientationUtils != null) {
            //直接横屏
            orientationUtils.resolveByClick();
        }
    }

**Comment by CarGuo** [comment]
是否配置了manifest
