### ISSUE TITLE
大佬，我在使用RecyclerView播放视频时候,将每个item的大小设置成了全屏，想每次滑动到一个item的时候，此item的播放器自动播放。

### ISSUE THREAD

**Issue by a1247366751** [CarGuo/GSYVideoPlayer#1202]
额 在进行代码改动的时候，发现只有限制RecyclerViw 每次滑动只能滑动一个item，就算一直下滑，也只能每次滑动1个item        这样的限制不知道该如何实现，请问大佬有思路吗？

**Comment by CarGuo** [comment]
你搜索下RecyclerView实现ViewPager效果吧······

**Comment by riseLishan** [comment]
我用的就是这个https://github.com/DingMouRen/LayoutManagerGroup，但是用RecyclerView滑动下一个全屏的item时，并不会全屏播放 @CarGuo ，往上滑，上边的视频可以自动播放，往下滑不可以自动播放 @CarGuo

**Comment by riseLishan** [comment]
@a1247366751 @CarGuo
