### ISSUE TITLE
关于sdk及相关依赖的版本

### ISSUE THREAD

**Issue by MeowStone** [CarGuo/GSYVideoPlayer#1203]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

看过demo，想用这个库，但是依赖的库版本等级太高，能不能退出个低版本的（可能要牺牲下UI的美观）？

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
类似
```
compile('com.xxxx.xxxx:1.1.0') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
}
```

**Comment by MeowStone** [comment]
`E:\test\build\intermediates\res\merged\debug\values-v26\values-v26.xml`
`No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.`
我该 exclude 哪个包？
