### ISSUE TITLE
播放avi格式视频的问题

### ISSUE THREAD

**Issue by tangjian211085** [CarGuo/GSYVideoPlayer#1206]
http://120.27.209.83/video/2018/2b0532425dd6401cacffc89eef50221e.avi
你好，上次说的播放avi格式视频的问题。这是外网播放地址，麻烦你看看行吗？

**Comment by CarGuo** [comment]
你可能需要在 https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh 
增加如下解码器，然后看看视频的音频编解码和视频编解码是否还需要增加，然后参考首页编译新的so
```
--enable-demuxer=avi 
```

**Comment by CarGuo** [comment]
如图，然后你只依赖java原创库就好了，然后把压缩包so放到你的项目下，注意是否已经指定了jni文件目录，为在demo已经测试可以了

```
sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
```

![](https://user-images.githubusercontent.com/10770362/41460406-3317beb4-70bf-11e8-9499-2273e02b6586.jpg)

[exso-avi.zip](https://github.com/CarGuo/GSYVideoPlayer/files/2105457/exso-avi.zip)

**Comment by tangjian211085** [comment]
你好。我替换exso-avi.zip里的so文件后，依然不能播放avi的视频。替换后发现只有libijkffmpeg.so文件发生了改变。另外两个都没有变化。但是你的截图里libijkffmpeg.so和libijkplayer.so都是发生了改变的(变为了蓝色)。那是不是因为libijkplayer.so的原因呢？

**Comment by tangjian211085** [comment]
请问module-lite-more.sh修改添加--enable-demuxer=avi 后，怎么进行编译呢？https://www.jianshu.com/p/bd289e25d272看的不怎么懂。安装了VMware和Ubuntu后，就不知道怎么继续了。需要在ubuntu里安装jdk和ndk吧，然后呢。。。。。是需要下载git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-android 这个源码吗？

**Comment by tangjian211085** [comment]
大神，非常感谢啊。更新分支后，的确可以正常播放了。不过呢我自己的项目还是有点问题，应该是我自己哪里没弄好，再好好看看。再次感谢你的分享，谢啦！！！
