### ISSUE TITLE
调用播放循环的时候,如何不直接显示播放按钮,只有触摸的时候才显示

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1208]

**Comment by CarGuo** [comment]
继承后参考StandardGSYVideoPlayer的changeXX方法，重载后设置

**Comment by darkrevier** [comment]
protected void resolveUIState(int state) {
        switch (state) {
            case CURRENT_STATE_NORMAL:
                changeUiToNormal();
                cancelDismissControlViewTimer();
                break;
            case CURRENT_STATE_PREPAREING:
                changeUiToPreparingShow();
                startDismissControlViewTimer();
                break;
            case CURRENT_STATE_PLAYING:
                changeUiToPlayingShow();
                startDismissControlViewTimer();
                break;
            case CURRENT_STATE_PAUSE:
                changeUiToPauseShow();
                cancelDismissControlViewTimer();
                break;
            case CURRENT_STATE_ERROR:
                changeUiToError();
                break;
            case CURRENT_STATE_AUTO_COMPLETE:
                changeUiToCompleteShow();
                cancelDismissControlViewTimer();
                break;
            case CURRENT_STATE_PLAYING_BUFFERING_START:
                changeUiToPlayingBufferingShow();
                break;
        }
里面的changeui的方法 我都把startbutton设置为gone 还是不好使

**Comment by CarGuo** [comment]
这就需要看，是在哪里导致播放ui出现的了。

**Comment by enjian971221** [comment]
解决了 changeUiToPlayingBufferingShow changeUiToPlayingShow 我是5.0.1版本的重写了下demo的player照抄的然后把上边两个方法的show全部改成了GONE
