### ISSUE TITLE
视频无法正常播放，报错：could not find codec parameters，求解~

### ISSUE THREAD

**Issue by Fanping** [CarGuo/GSYVideoPlayer#121]
03-23 20:10:52.724 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_profileBegin
03-23 20:10:52.724 19234-19234/tv.danmaku.ijk.media.example W/IJKMEDIA: monstartup already called
03-23 20:10:52.724 19234-19234/tv.danmaku.ijk.media.example W/local file debug: video path=/storage/emulated/legacy/data/munaiyi/munaiyi.m3u8 video uri=null
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_setup
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: av_version_info: 15121f1
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: ijk_version_info: e87bbda
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_create_from_android()
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d30045a)
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_inject_opaque()=void
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(-1)
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: moncleanup
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example V/IJKMEDIA: setDataSource: path /storage/emulated/legacy/data/munaiyi/munaiyi.m3u8
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/legacy/data/munaiyi/munaiyi.m3u8")
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_data_source(url="/storage/emulated/legacy/data/munaiyi/munaiyi.m3u8")=0
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0x9f70001d)
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ffpipeline_set_surface()
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_set_android_surface(surface=0x9f70001d)=void
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: IjkMediaPlayer_prepareAsync
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== versions =====
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: ijkplayer    : e87bbda
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: FFmpeg       : 15121f1
03-23 20:10:52.804 19234-20957/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [20957] ff_msg_loop
03-23 20:10:52.804 19234-20957/tv.danmaku.ijk.media.example D/IJKMEDIA: message_loop
03-23 20:10:52.804 19234-20957/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_FLUSH:
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: libavutil    : 55.34.100
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: libavcodec   : 57.64.100
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: libavformat  : 57.56.100
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: libswscale   : 4.2.100
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: libswresample: 2.3.100
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: ===== options =====
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : mediacodec                   = 0
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : opensles                     = 0
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : overlay-format               = 842225234
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : framedrop                    = 1
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: player-opts : start-on-prepared            = 0
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : ijkapplication               = 1643892096
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: format-opts : http-detect-range-support    = 0
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example I/IJKMEDIA: ===================
03-23 20:10:52.804 19234-20958/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [20958] ff_vout
03-23 20:10:52.804 19234-19234/tv.danmaku.ijk.media.example D/IJKMEDIA: ijkmp_prepare_async()=0
03-23 20:10:52.804 19234-20959/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_RunThread: [20959] ff_read
03-23 20:10:52.804 19234-20959/tv.danmaku.ijk.media.example D/IJKMEDIA: Setting default whitelist 'file,crypto'
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example V/IJKMEDIA: Probing hls,applehttp score:100 size:647
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example D/IJKMEDIA: Format hls,applehttp probed with size=2048 and score=100
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example V/IJKMEDIA: new_program: id=0x0000
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example I/IJKMEDIA: HLS request for url '/storage/emulated/legacy/data/munaiyi/1_1.ts', offset 0, playlist 0
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example V/IJKMEDIA: Probing flv score:100 size:2048
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example V/IJKMEDIA: Probing mp3 score:1 size:2048
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example D/IJKMEDIA: Format flv probed with size=2048 and score=100
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example E/IJKMEDIA: Option ijkapplication not found.
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example D/IJKMEDIA: Before avformat_find_stream_info() pos: 647 bytes read:647 seeks:0 nb_streams:0
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example D/IJKMEDIA: Statistics: 32768 bytes read, 0 seeks
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example I/IJKMEDIA: No longer receiving playlist 0
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example V/IJKMEDIA: format: start_time: -9223372036854.775 duration: 260.000 bitrate=0 kb/s
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example D/IJKMEDIA: After avformat_find_stream_info() pos: 647 bytes read:647 seeks:0 frames:0
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example W/IJKMEDIA: /storage/emulated/legacy/data/munaiyi/munaiyi.m3u8: **could not find codec parameters**
03-23 20:10:52.814 19234-20957/tv.danmaku.ijk.media.example D/IJKMEDIA: FFP_MSG_ERROR: 0
03-23 20:10:52.814 19234-20959/tv.danmaku.ijk.media.example I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [20959]
03-23 20:10:52.954 19234-19234/tv.danmaku.ijk.media.example E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
03-23 20:10:52.954 19234-19234/tv.danmaku.ijk.media.example D/IjkVideoView: Error: -10000,0
03-23 20:10:52.974 19234-19234/tv.danmaku.ijk.media.example I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
03-23 20:10:53.604 19234-19234/tv.danmaku.ijk.media.example I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@42595930 time:198338318

**Comment by CarGuo** [comment]
m3u8需要关缓存，然后确保你的video编码是 h264,h265，audio编码是acc。如果是mpeg等其他的，请自行编译so后替换项目中的so
