### ISSUE TITLE
退出全屏后status bar出现。

### ISSUE THREAD

**Issue by zhangli1845** [CarGuo/GSYVideoPlayer#1213]
进入activity时在oncreate（）方法里面调用
getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN);
去掉status bar显示。

然后播放视频，切到全屏幕。再执行backFromFull(activity);退出全屏。这个时候status bar显示。

想要隐藏status bar应该怎么处理？

**Comment by CarGuo** [comment]
全屏方法的statusbar设置为false

**Comment by zhangli1845** [comment]
才发现这个问题就是全屏时，你重新构造了player。可以在startWindowFullscreen方法传旧的状态，但是VIEW好像是不能传递。每次都new了一个，这个怎么处理呢？

**Comment by zhangli1845** [comment]
@CarGuo

**Comment by zhangli1845** [comment]
@CarGuo 才发现这个问题就是全屏时，你重新构造了player。可以在startWindowFullscreen方法传旧的状态，但是VIEW好像是不能传递。每次都new了一个，这个怎么处理呢？

**Comment by zhangli1845** [comment]
发现你这个机制好像很有问题，比如一个textview，在非全屏改变的text.在全屏时这个text还是没变。需要去手动设置一次

**Comment by zhangli1845** [comment]
比如一个textview，在非全屏改变的text.在全屏时这个text还是没变。需要去手动设置一次。

**Comment by CarGuo** [comment]
cloneParams方法

**Comment by zhangli1845** [comment]
@CarGuo 不行，重载cloneParams和startWindowFullscreen都试过，效果一样的，都不行

**Comment by CarGuo** [comment]
什么不行？text改变不行？？

**Comment by zhangli1845** [comment]
@CarGuo  是的，这是我的代码
 videoPlayer.clarity.setText(clarity.getText());
  videoPlayer.clarity = clarity;
其中“clarity”是textview。都是放在重载cloneParams和startWindowFullscreen执行。如果不加上 videoPlayer.clarity.setText(clarity.getText());这句的话。那么里面的text还是读取的XML里面定义的，而不是非全屏我修改过的

**Comment by zhangli1845** [comment]
另外我切换还有切换清晰度的方法，我也是模仿你的demo,sampleVideo中的
     switchVideoTypeDialog.initList(mUrlList, new SwitchVideoTypeDialog.OnListItemClickListener() {
            @Override
            public void onItemClick(int position) {
                final String name = mUrlList.get(position).getName();
                if (mSourcePosition != position) {
                    if ((mCurrentState == GSYVideoPlayer.CURRENT_STATE_PLAYING
                            || mCurrentState == GSYVideoPlayer.CURRENT_STATE_PAUSE)) {
                        final String url = mUrlList.get(position).getUrl();
                        onVideoPause();
                        final long currentPosition = mCurrentPosition;
                        getGSYVideoManager().releaseMediaPlayer();
                        cancelProgressTimer();
                        hideAllWidget();
                        new Handler().postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                setUp(url, mCache, mCachePath, mTitle);
                                setSeekOnStart(currentPosition);
                                startPlayLogic();
                                cancelProgressTimer();
                                hideAllWidget();
                            }
                        }, 500);
                        mTypeText = name;
                        mSwitchSize.setText(name);
                        mSourcePosition = position;
                    }
                } else {
                    Toast.makeText(getContext(), "已经是 " + name, Toast.LENGTH_LONG).show();
                }
            }
        });
这段来写的，在非全屏模式下切换正常，切换的全屏后，在切换清晰度后就不能自动播放了。

**Comment by CarGuo** [comment]
哦，如果是这种的设置text，除了在cloneParams中传递参数外，还需要
你可以重载startWindowFullscreen和resolveNormalVideoShow方法中进行设置，类似demo的`DanmakuVideoPlayer`，如果是外部设置的话，你可以`((YouPlayer)player.getCurrentPlayer()).xxxx`这样获取。

至于切换清晰度的，demo没问题的话参考demo吧

**Comment by zhangli1845** [comment]
关键是，切换清晰度的demo一直没有切换过全屏和正常屏。我在正常的屏是没问题的，一到全屏就出问题。要不，能不能简单讲下，切换全屏的这个动作，是做了些什么吗？需要从新设置些什么

**Comment by CarGuo** [comment]
DetailMoreTypeActivity
