### ISSUE TITLE
大佬又来麻烦你了,在RecyclerView模式下，在item里面的显示隐藏文字问题

### ISSUE THREAD

**Issue by a1247366751** [CarGuo/GSYVideoPlayer#1214]
在VideoAllCallBack中 监听了当点击播放按钮时，在onStartPrepared时  隐藏我自己设置的文字，  在播放完成时候 即onAutoComplete时 又重新显示出来,现在在我点击播放后，文字隐藏，然后我再点击其他item的播放按钮时，原来的item文字不会重新显示（我想让文字在点击其他item或者滑动至不可见后 ，文字重新显示），请问在某一item播放器    播放途中，点击其他item时  有哪个方法可以监听原Item的播放器的销毁状态  以实现我让文字重新显示的需求

**Comment by CarGuo** [comment]
个人觉得，你需要的是继承后，重载onCompletion()

或者类似 `ListADVideoPlayer` 的重载方法实现
