### ISSUE TITLE
请问如何在播放当前视频时候预加载下一个视频？

### ISSUE THREAD

**Issue by wisonic** [CarGuo/GSYVideoPlayer#1215]
@CarGuo 你好，非常感谢你的分享！请问如何在播放当前视频时候预加载下一个视频？

**Comment by CarGuo** [comment]
这个属于多播放内核的实现了。毕竟一个播放内核是不可能同时播放两个视频。

第一，参考ListMultiVideoActivity实现，在一个播放的时候，选择一个时机

setStartAfterPrepared false
然后
startPrepare()
之后在需要播放的时候  startAfterPrepared();，不过你需要判断是否视频已经prepared了。
当然，你需要继承后才能调用到这些方法。

第二、参考demo的DetailExoListPlayer，这个通过ConcatenatingMediaSource，内部exoplayer实现了一定的预加载播放效果。

**Comment by wisonic** [comment]
@CarGuo 我是在RecylerView中配合ViewPagerLayoutManager, 希望在播放当前视频时加载下一条。按照你提供的建议，选择了第一种方法进行了尝试，在onBindViewHolder 中初始化Player，setStartAfterPrepared 为 false，但是似乎不凑效，每次预加载的视频也在后台播放，而不是自动加载完成后暂停。 不知道我这里用法是否正确，能否再给我一点建议？多谢！

**Comment by CarGuo** [comment]
startPrepare()方法执行后，会去到 onPrepared() ，这时候
```
@Override
    public void onPrepared() {

        if (mCurrentState != CURRENT_STATE_PREPAREING) return;

        mHadPrepared = true;

        if (mVideoAllCallBack != null && isCurrentMediaListener()) {
            Debuger.printfLog("onPrepared");
            mVideoAllCallBack.onPrepared(mOriginUrl, mTitle, this);
        }

        //这里会暂停，不会进入播放阶段
        if (!mStartAfterPrepared) {
            setStateAndUi(CURRENT_STATE_PAUSE);
            return;
        }

        startAfterPrepared();
    }
```

**Comment by wisonic** [comment]
@CarGuo 感谢你这么早给我回复！我这边刚才试了在我的player中重写这个方法，预加载时候确实不会走到startAfterPrepared()。但是还是会自动播放。我在onInfo中发现缓冲完了就会播放。所以我加了如下逻辑：


    override fun onInfo(what: Int, extra: Int) {
        super.onInfo(what, extra)
        when(what){
            IMediaPlayer.MEDIA_INFO_BUFFERING_END,
            IMediaPlayer.MEDIA_INFO_AUDIO_DECODED_START,
            IMediaPlayer.MEDIA_INFO_VIDEO_DECODED_START ->
            {
                if(!isStartAfterPrepared){
                    onVideoPause()
                }
            }
        }
    }


虽然这样不会再自动播放，达到了我的目的，但是感觉这样还是不够优雅。请问你是否有更好的建议？

**Comment by CarGuo** [comment]
你这么实现的话，可能会在中途出现缓冲的状态然后就暂停了。

首先你用的是demo中的`CustomManager`、`MultiSampleVideo`这种模式吧？？
然后先设置了`setStartAfterPrepared false`，调用`startPrepare()方法，流程应就到了
```
@Override
    public void onPrepared() {
```
就暂停了，不会走`startAfterPrepared`，也就是`  getGSYVideoManager().start();`，那么应该是不会播放了。

如果真不知道为什么，你可以试试在onPrepared中，根据情况去对它进行onVideoPause()

**Comment by wisonic** [comment]
@CarGuo 经过一天的验证，我通过在onInfo中拦截的方式基本实现了我的需求，暂时也没有出现问题，因为在播放时候我把isStartAfterPrepared 置成了true。 然后有强迫症的我又直接拿你的源码在多任务这个类里面对MultiSampleVideo进行更改，按你的方法进行了setStartAfterPrepared false 和startPrepare。发现demo 中startAfterPrepared确实没调用，但是仍然自动播放了，虽然画面不会更新，但是时间还是在播放声音也在走进度条。所以能否麻烦你那边也验证一下？

**Comment by CarGuo** [comment]
你可以试试demo的ListADVideoActivity，它的广告和视频实现就是用这种方式

**Comment by wisonic** [comment]
@CarGuo 你好，我今天一直遇到一个问题，就是有时候滑动较快停下来，一个视频播放了1s左右，开始缓冲，然后又开始从头播放，请问有没有办法让缓冲后继续前面的进度播放？

**Comment by CarGuo** [comment]
不是很了解场景，滑动后停下，这时候视频已经播放了一秒了，然后seek失败了变成了从头播放这样？

**Comment by wisonic** [comment]
@CarGuo 场景是这样的。滑动切换视频，切换到某个视频时候，开始播放了1s左右后开始了缓冲，缓冲结束后又从头开始播了。

**Comment by wisonic** [comment]
@CarGuo 是的，cache为true。但是感觉完整缓存后，再次播放就没有这个现象了。
另外如果是用GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);是不是意味着全局都变成了EXO 2 播放内核？谢谢

**Comment by CarGuo** [comment]
是的，全局

**Comment by wisonic** [comment]
@CarGuo 切换到IJKEXOPLAYER2，预加载的模式也出现了播放一小段缓冲从头开始播的问题。请问从上层逻辑有没有办法解决这个问题？

**Comment by CarGuo** [comment]
可以试试调节这些参数看看有没有优化效果，对于默认模式下

```
list.add(videoOptionModel);
 videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);

  videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
 list.add(videoOptionModel);


        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
        list.add(videoOptionModel);

        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
        list.add(videoOptionModel);

 videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```


至于关键帧参数，应该还和视频的帧率还有大小相关，这个我也不大好说
