### ISSUE TITLE
播放m3u8非常卡顿，同链接用手机浏览器直接播放很流畅

### ISSUE THREAD

**Issue by tangting1900** [CarGuo/GSYVideoPlayer#1218]
http://223.110.243.138/PLTV/2510088/224/3221227177/index.m3u8
上面这个直播链接，播放会经常出现暂停缓冲，我用demo中直接输入URL的功能测试过也一样卡顿。
但是我用手机QQ打开链接，直接调用内置QQ浏览器播放又非常的流畅，小米手机自带的默认浏览器打开播放也非常流畅，所以排除是直播源的问题。
请问这种情况是需要设置什么播放缓冲逻辑吗？还是其它的什么问题呢？

**Comment by CarGuo** [comment]
``` 
GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2); 
```

**Comment by tangting1900** [comment]
@CarGuo  非常感谢，问题完美解决了。

**Comment by BushLee** [comment]
> ```
> GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2); 
> ```

您好，请问这个setVideoType这个方法在8.4.0版本有替代了吗？我发现没有这个方法了。

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class);

**Comment by BushLee** [comment]
> PlayerFactory.setPlayManager(Exo2PlayerManager.class);

感谢，我使用的就是EXO内核如下：
PlayerFactory.setPlayManager(Exo2PlayerManager.class);
CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_16_9);
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
GSYVideoType.enableMediaCodecTexture();

我发现ijk可以设置缓冲区大小，想请问以下使用exo播放m3u8可否扩大以下缓冲区呢？我在电视上播放总是播放一会就卡一会，我希望的是能够尽量多的缓冲以下内容，避免频繁卡顿。不知道这样对不对。
