### ISSUE TITLE
播放时的缓存动画取消掉的问题

### ISSUE THREAD

**Issue by a1247366751** [CarGuo/GSYVideoPlayer#1219]
查看源码，只发现了一个取消全屏动画的方法,还有一些渲染什么什么的  看不懂，需要继承哪个方法改写   才能取消掉 那个黑屏   小球转圈的缓存动画？以及播放本地视频时，前面加了file:///还是不能播放,我已经通过数据线传输到手机上了,如何获得本地内部存储视频路径。  我自己写的路径是这样的:url="file:///"+Environment.getDataDirectory().getPath()+"/Video/video_1.mp4";

**Comment by CarGuo** [comment]
你放到哪里就用哪里的路径啊······比如
```
String url = "file://"+ Environment.getExternalStorageDirectory().getPath() + "Download/132451525666042.mp4";
```
你说的那个是buffer时的loading效果吧，参考下NormalGSYVideoPlayer吧

**Comment by a1247366751** [comment]
@CarGuo   NormalGSYVideoPlayer 好像只有按钮的图像变化 我想知道什么样把那个loading和播放缓存前黑屏取消掉   只显示封面 一缓存好就直接图片封面消失 播放视频。像抖音那样的效果，麻烦你了

**Comment by CarGuo** [comment]
你继承后，重载getLayoutId，在布局里去掉就可以了，然后参考demo 的SampleCoverVideo，他就是loading完成才去掉封面

**Comment by CarGuo** [comment]
demo中的ListVideoActivity你试试，我这边看是不会出现黑屏，如果你觉得会有黑屏，你可以在
```
/**下方两个重载方法，在播放开始前不屏蔽封面*/
```
这demo两个方法里，做个几百毫秒的动画隐藏封面

**Comment by a1247366751** [comment]
我感觉是Loading去除的不完全导致的,按照你的说法我重载getLayoutId，然后自己重新创建了一个布局，在布局里面删除掉了ENDownloadView 然后加载的圆圈的确不见了 ，但是伴随着加载圆圈的黑屏仍然存在。是不是还要进行一些操作,以及我没有在ListVideoActivity和源码里找到/**下方两个重载方法，在播放开始前不屏蔽封面*/

**Comment by a1247366751** [comment]
@CarGuo

**Comment by CarGuo** [comment]
```
/*下方两个重载方法，在播放开始前不屏蔽封面*/ 
```
在SampleCoverVideo里。


ListVideoActivity让你看看demo里的会不会出现问题。

**Comment by a1247366751** [comment]
@CarGuo 真的感谢你  不知道咋说好了  麻烦你这么久 有点过意不去哈   已经解决了  麻烦了 麻烦了
