### ISSUE TITLE
m3u8视频播了第一个ts之后，就不能继续播了，请指教~

### ISSUE THREAD

**Issue by Fanping** [CarGuo/GSYVideoPlayer#122]
日志如下，谢谢，资源是从百度云盘下载到手机中的，只能播第一个片段，剩下的就播不了了~
[只能播放部分.txt](https://github.com/CarGuo/GSYVideoPlayer/files/864699/default.txt)

**Comment by CarGuo** [comment]
m3u8视频请遵循m3u8的分片协议，对应的路径需要有对应的各个切片。如果是直接本地播放多切片请使用concat，不过目前so没增加这类支持，有需要的可以配置ijk假如协议支持。

**Comment by CarGuo** [comment]
而且我记得，m3u8不能直接本地播放，本地直接播放m3u8需要特殊处理

**Comment by CarGuo** [comment]
https://github.com/Bilibili/ijkplayer/issues/2884 参考ijk
