### ISSUE TITLE
请问怎么改视频的码率，播放视频的时候很卡，源码中支持改码率吗

### ISSUE THREAD

**Issue by guiyanbing** [CarGuo/GSYVideoPlayer#1222]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
只有调节丢帧处理的

```
VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 30);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

或者

GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);

**Comment by guiyanbing** [comment]
谢谢，我试试
