### ISSUE TITLE
你好，请问哪个是监听视频播放到下一集

### ISSUE THREAD

**Issue by Merbn** [CarGuo/GSYVideoPlayer#1223]
## 问题描述：
请问哪个是监听视频播放到下一集

**Comment by CarGuo** [comment]
没有这样的监听，列表是通过每个视频内容结束后，自动播放下一集这样。

**Comment by Merbn** [comment]
@CarGuo 因为项目中是点播，当播放完当前集 自动播放下一集时，点播列表要更新状态（一个播放当前集的图标），所以才想要这个监听...
