### ISSUE TITLE
4.1.3之后开始会有错误,可能是内部冲突.请问怎么解决.

### ISSUE THREAD

**Issue by github-yyy** [CarGuo/GSYVideoPlayer#1225]
只是完整版依赖4.1.3或者5.0.0,然后编译运行的时候无法通过,错误如下
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

我没有添加和依赖其他东西,只是单独写了demo测试,就发现了这样的错误.

**Comment by CarGuo** [comment]
超过64k方法数了看起来

**Comment by github-yyy** [comment]
multiDexEnabled true
加了这行代码还是不行啊

**Comment by github-yyy** [comment]
您看下是不是您后来修改代码之后,有了重复的包依赖?

**Comment by CarGuo** [comment]
只加这个是不行的，你还得增加依赖和修改application，参考下demo吧

**Comment by github-yyy** [comment]
您的demo,build.gradle没有关于这个的吧.
还请赐教一下修改哪里呢,或者指点一下,您有空的话弄一个demo试一下,当然,我也就是请教请教,打扰到的话,不好意思啦.
