### ISSUE TITLE
全屏与非全屏UI切换问题

### ISSUE THREAD

**Issue by CheersLiu** [CarGuo/GSYVideoPlayer#1226]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
@CarGuo 在全屏与非全屏时有两套UI，我看布局的功能点支持切换，问下具体切换的操作Demo中有吗，具体在哪？
XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
demo中的LandLayoutVideo

**Comment by CheersLiu** [comment]
@CarGuo demo中有用到LandLayoutVideo的类是哪个呀？

**Comment by CarGuo** [comment]
DetailPlayer
