### ISSUE TITLE
您好，我现在项目需要语音合成，播报语音时候需要正在播放的播放器继续播放。我现在播报语音视频播放器就没有焦点了，处于暂停状态，可以使播放器继续播放，而语音合成播报互补影响吗

### ISSUE THREAD

**Issue by guiyanbing** [CarGuo/GSYVideoPlayer#1227]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
类似demo中的MultiSampleVideo就可以

**Comment by guiyanbing** [comment]
我直接用了MultiSampleVideo播放，还是会被抢占焦点
