### ISSUE TITLE
把原来详情带广告的里面的GSYSampleADVideoPlayer，用在广告列表列表复用错了问题

### ISSUE THREAD

**Issue by LLQQHH** [CarGuo/GSYVideoPlayer#1229]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
把原来详情带广告的里面的GSYSampleADVideoPlayer，用在广告列表列表复用错了问题

## 问题机型/系统：

例如 真机 红米4x

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
  final String url = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
            //final String urlAD = "http://video.7k.cn/app_video/20171202/6c8cf3ea/v.m3u8.mp4";
            final String urlAD = "http://static.zxart.cn/UploadFiles/media/Filmhead/8.flv";

            //多个播放时必须在setUpLazy、setUp和getGSYVideoManager()等前面设置
            holder.gsyVideoPlayer.setPlayTag(TAG);
            holder.gsyVideoPlayer.setPlayPosition(position);
            holder.rel_btn.setVisibility(View.VISIBLE);
            holder.btn.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                  holder.btn.postDelayed(new Runnable() {
                      @Override
                      public void run() {
                          runOnUiThread(new Runnable() {
                              @Override
                              public void run() {
                                  ArrayList<GSYSampleADVideoPlayerTest.GSYADVideoModel> urls = new ArrayList<>();
                                  //广告1
                                  urls.add(new GSYSampleADVideoPlayerTest.GSYADVideoModel(urlAD,
                                          "", GSYSampleADVideoPlayerTest.GSYADVideoModel.TYPE_AD));
                                  //正式内容1
                                  urls.add(new GSYSampleADVideoPlayerTest.GSYADVideoModel(url,
                                          "正文1标题", GSYSampleADVideoPlayerTest.GSYADVideoModel.TYPE_NORMAL));
                                  holder.gsyVideoPlayer.setAdUp(urls, true, 0);
                                  holder.gsyVideoPlayer.getCurrentPlayer().startAfterPrepared();
                                  holder.rel_btn.setVisibility(View.GONE);
                              }
                          });
                      }
                  },500);
                }
            });
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by LLQQHH** [comment]
我就是模仿那个来写的，我现在是相邻两个item点击都可以播放，而ListADVideoActivity我没看到解决相邻两个点击播放的问题的代码，是不是列表不能用GSYSampleADVideoPlayer这个类
![screenshot_2018-06-21-17-15-34-472_com example gsyvideoplayer](https://user-images.githubusercontent.com/19651932/41710655-c98244f6-7578-11e8-9cd3-7df43129027f.png)

**Comment by CarGuo** [comment]
这个我没有试过，因为列表那个我是针对做过防错位的

**Comment by LLQQHH** [comment]
ListADVideoActivity列表里面是已经带了广告地址，我现在是需要点击item的时候去请求广告地址，所以ListADVideoActivity不是很符合我的需要，而防止滑动错位demo是这么写：
 int lastVisibleItem = firstVisibleItem + visibleItemCount;
                //大于0说明有播放
                if (GSYVideoManager.instance().getPlayPosition() >= 0) {
                    //当前播放的位置
                    int position = GSYVideoManager.instance().getPlayPosition();
                    //对应的播放列表TAG
                    if (GSYVideoManager.instance().getPlayTag().equals(ListADNormalAdapter.TAG)
                            && (position < firstVisibleItem || position > lastVisibleItem)) {
                        //如果滑出去了上面和下面就是否，和今日头条一样
                        //释放广告和视频
                        if (GSYVideoADManager.instance().listener() != null) {
                            GSYVideoADManager.instance().listener().onAutoCompletion();
                        }
                        GSYVideoADManager.releaseAllVideos();
                        GSYVideoManager.releaseAllVideos();
                        listADNormalAdapter.notifyDataSetChanged();
但是如何防止相邻item点击都可以播放的问题：可否把代码位置跟我说下，谢谢

**Comment by CarGuo** [comment]
看看dev分支的ListADVideoActivity2，我觉得你可以是需要
```
holder.gsyVideoPlayer.setVideoAllCallBack(new GSYSampleCallBack() {

                @Override
                public void onClickStartIcon(String url, Object... objects) {
                    super.onClickStartIcon(url, objects);
                     //下面这个
                       if (holder.adVideoPlayer.getGSYVideoManager().listener() != null) {
                        holder.adVideoPlayer.getGSYVideoManager().listener().onAutoCompletion();
                    }
                }
```
