### ISSUE TITLE
关于播放器的一个问题

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1230]

**Comment by darkrevier** [comment]
层级Activity--viewpager-pageradapter-VideoPlayer
我在adapter中初始化的videoplayer播放器set了数据,但是我发现在VideoPlayer类中取的时候对象的地址变了,取得时候为null。。这个问题我不知道该怎么办，猫神遇到过没

**Comment by CarGuo** [comment]
你用哪个set的？？setup还是setupLazy

**Comment by darkrevier** [comment]
好想我没表达正确，在adapter里面初始化了videoplayer 并set了一个数据
  final View view = LayoutInflater.from(getContext()).inflate(R.layout.item__video_layout, null);
  CustomVideoPlayer videoPlayer = view.findViewById(R.id.customVideo);
  videoplayer.setData(data);
但是我在我创建的VideoPlayer中想取出这个数据 但是为null
后来调试过程中发现CustomVideoPlayer的地址变了所以没有取到数据 是这个意思

**Comment by CarGuo** [comment]
所以···我更懵逼了，你增加了个setData(data）方法，但是get出来的是null？？？？

**Comment by darkrevier** [comment]
就是videoplayer 对象地址变了 不是同一个
