### ISSUE TITLE
大佬,关于RecyclerView的标题栏问题。

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1232]
RecyclerView能实现播放前  标题栏可见，加载成功后标题栏消失,单击的时候标题栏出现吗，我运行了一下把标题栏变成了Visible.发现只有在加载成功后标题栏才会显示，随后消失，现在我想在这一基础上添加   播放前 标题栏也可见 应该什么做，我有自定义title添加上去，但是好像RecyclerView的复用出现了问题。能详细点吗。麻烦你了

**Comment by CarGuo** [comment]
参考StandardGSYVideoPlayer的onClickUiToggle中的方法，继承后重载处理
