### ISSUE TITLE
m3u8后缀的视频如何获取第一帧视频图片

### ISSUE THREAD

**Issue by woyoudianhuai** [CarGuo/GSYVideoPlayer#1234]
## 问题描述：

m3u8后缀的视频如何获取第一帧视频图片

**Comment by CarGuo** [comment]
这个很尴尬，目前来说是不支持

**Comment by woyoudianhuai** [comment]
有没有什么替代方案呢，想过视频一进来就加载，然后暂停，但这样就改了框架逻辑了

**Comment by CarGuo** [comment]
你可以下载这个m3u8，然后解析出其中一个ts，然后和demo一样用glide加载这个ts就可以

**Comment by hakulatata** [comment]
可实现吗？也想拿个缩略图啊
