### ISSUE TITLE
请问播放器支持类似于ImageView的ScaleType吗

### ISSUE THREAD

**Issue by wisonic** [CarGuo/GSYVideoPlayer#1236]
@CarGuo 请问播放器支持类似于ImageView的ScaleType CenterCrop和FixXY模式吗？如果目前没有，有什么实现方法吗？

**Comment by haohaozaici** [comment]
看readme哟
画面 ：调整显示比例:默认、16:9、4:3、填充，播放时旋转画面角度（0,90,180,270），镜像旋转。

**Comment by wisonic** [comment]
@haohaozaici 抱歉，我可能描述的不够清晰。我想知道的是播放器是否支持裁剪画面，比如有的手机屏幕高宽比 和 视频本身的高宽比不一致，但是这时候我想让画面比例不变填充频幕，比如会导致视频的头尾 或者 左右 超出的部分被裁剪， 请问这样的功能如何实现呢？能给点思路么？谢谢

**Comment by haohaozaici** [comment]
@wisonic 你说的这种情况，就是调整显示比例中的“填充模式”，更复杂的情况可以加入手势缩放，例如bilibili的三指旋屏

**Comment by wisonic** [comment]
@haohaozaici 多谢多谢！抱歉没仔细看demo。

**Comment by Werb** [comment]
@wisonic 他说的剪裁画面应该不是填充吧？

**Comment by androidCoderxiao** [comment]
所以最后怎么解决了吗 ？
