### ISSUE TITLE
怎么在viewpager 中使用像列表一样自动播放

### ISSUE THREAD

**Issue by ricardo0312** [CarGuo/GSYVideoPlayer#1237]

**Comment by CarGuo** [comment]
你用recyclerview实现的viewpager

**Comment by ricardo0312** [comment]
事实上是想用viewpager 再加上视差或者反转动画。

**Comment by CarGuo** [comment]
layoutmanager可以解决 https://github.com/DingMouRen/LayoutManagerGroup
