### ISSUE TITLE
播放4K视频卡顿问题

### ISSUE THREAD

**Issue by higherbean** [CarGuo/GSYVideoPlayer#1238]
## 问题描述：
播放4K视频的时候会很卡，我开了硬解码，感觉也没有效果，要从什么地方入手解决呢

## 问题机型/系统：
 
海思 Android4.4

**Comment by higherbean** [comment]
我播放的是本地的视频，网络延迟之类的问题不考虑

**Comment by CarGuo** [comment]
试试这个
```
VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 30);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

或者切换到  
```
GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);
```

**Comment by higherbean** [comment]
问题我解决了，
 ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
改成
 ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-all-videos", 1);
就好了，谢谢了
