### ISSUE TITLE
视频列表详情切换，有声音无画面同步

### ISSUE THREAD

**Issue by EinsteinLE** [CarGuo/GSYVideoPlayer#1240]
## 问题描述：

从视频播放列表切换至视频详情页时，如果是播放状态下点击item跳转，详情页只有声音和进度条在同步，画面停滞不动。如果是未播放状态可以跳转且播放。问题出现在安卓6.0及以下的版本中。6.0以上没有问题。

## 问题机型/系统：
Android 6.0以上手机：
坚果Pro2 Android 7.0.1
小米Mix2 Android 8.0.0
荣耀9 Android 8.0.0

Android 6.0及以下手机：
锤子 M1   Android 6.0.1
OPPO R9s   Android 6.0.1 
红米 Note3   Android 5.0.2

## Demo中的复现步骤

Demo中的SwitchListVideoActivity页面打开,点击播放视频，再进入详情页，就会出现画面停滞不播放的问题

**Comment by CarGuo** [comment]
目前没有6.0以下手机，不过我的小米和华为运行demo的SwitchListVideoActivity正常，可以看看是不是以为acitivity的style、共享元素动画这两个地方导致的。

**Comment by EinsteinLE** [comment]
因为相同的代码有的可以有的不可以，而且下载的是最新的demo。包括自己写个demo添加依赖或者回退版本也试过了。6.0及以下不能正常播放，确定是兼容问题。

**Comment by CarGuo** [comment]
可以看看是不是以为acitivity的style、共享元素动画这两个地方导致的。
