### ISSUE TITLE
请问有办法在播放前，设置视频本身rotation的旋转（90,270）吗

### ISSUE THREAD

**Issue by zhuoshirong** [CarGuo/GSYVideoPlayer#1242]
请教一下，请问有办法在播放前，设置视频本身rotation的旋转（90,270），然后播放时按旋转的角度播放

**Comment by CarGuo** [comment]
模式就会读取视频本身的选择角度，然后按照角度播放，详细见源码onInfo方法。
如果你是想设置旋转，可以参考demo SampleVideo

**Comment by zhuoshirong** [comment]
我看了你的DEMO里面基本都是播放时，才能点击旋转画面来进行旋转，SampleVideo，我没有找到这个类或者是activity

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/SampleVideo.java   


首先你可以看看onInfo方法，然后你继承后，如果不需要针对onInfo的那种继续计算，那么你直接设置 
播放前的mRotate就好了

**Comment by zhuoshirong** [comment]
好的，谢谢，我看一下

**Comment by zhuoshirong** [comment]
单独的视频播放页面PlayActivity， 这个里面就是用的你提到的播放器SampleVideo, 我在onCreate里面设置了mRotate=90，点击播放时，画面还是没有旋转；请教一下还有其他途径可以设置吗，谢谢

**Comment by zhuoshirong** [comment]
我的你给的https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/SampleVideo.java 这个里面增加一个方法,设置的，但是没有效果
    // 设置画面旋转角度
    public void setRotate(int rotate) {
        mRotate = rotate;
        if (mTextureView != null) {
            Log.e("TAGG", "不为空时设置播放前=" + rotate);
            mTextureView.setRotation(rotate);
            mTextureView.requestLayout();
        } else {
            Log.e("TAGG", "为空时" + rotate);
        }
    }

**Comment by zhuoshirong** [comment]
谢谢群主了，我解决了，用的VideoAllCallBack ，监听视频播放进度，在开始播放时设置旋转角度
