### ISSUE TITLE
广告详情 DetailADPlayer  页面，setAdUp 这个方法，无论广告还是正式内容的视频，视频链接只要是以 https 开头的，要把 cacheWithPlay 设为 true 才能正常播放，否则就会报 error 10000 错误。

### ISSUE THREAD

**Issue by ZQ173** [CarGuo/GSYVideoPlayer#1245]
## 问题描述：

setAdUp 这个方法，无论广告还是正式内容的视频，视频链接只要是以 https 开头的，要把 cacheWithPlay 设为 true 才能正常播放，否则就会报 error 10000 错误。

## 问题机型/系统：

真机 魅族pro5 Android7.0、一加5 Android8.1

## Demo中的复现步骤

Demo中的 DetailADPlayer 页面打开后会出现这个问题。

问题代码：(如果有)

1、广告视频使用 htpps 的链接，cacheWithPlay 设为 false，就会出现问题描述的情况了。

        ArrayList<GSYSampleADVideoPlayer.GSYADVideoModel> urls = new ArrayList<>();
        //广告1
        urls.add(new GSYSampleADVideoPlayer.GSYADVideoModel("https://static.zxart.cn/UploadFiles/media/Filmhead/8.flv",
                "我是广告 https ", GSYSampleADVideoPlayer.GSYADVideoModel.TYPE_AD));
        //正式内容1
        urls.add(new GSYSampleADVideoPlayer.GSYADVideoModel("http://static.zxart.cn/UploadFiles/media/201806/20180625chishan.mp4",
                "我是正式内容 http", GSYSampleADVideoPlayer.GSYADVideoModel.TYPE_NORMAL));
        detailPlayer.setAdUp(urls, false, 0);

2、视频是没问题的，下面代码将广告视频的链接 https 换成 http ，即广告和视频链接都是 http开头，cacheWithPlay 参数设为 false，其他代码不变，就能正常播放：

        ArrayList<GSYSampleADVideoPlayer.GSYADVideoModel> urls = new ArrayList<>();
        //广告1
        urls.add(new GSYSampleADVideoPlayer.GSYADVideoModel("http://static.zxart.cn/UploadFiles/media/Filmhead/8.flv",
                "我是广告 http ", GSYSampleADVideoPlayer.GSYADVideoModel.TYPE_AD));
        //正式内容1
        urls.add(new GSYSampleADVideoPlayer.GSYADVideoModel("http://static.zxart.cn/UploadFiles/media/201806/20180625chishan.mp4",
                "我是正式内容 http", GSYSampleADVideoPlayer.GSYADVideoModel.TYPE_NORMAL));
        detailPlayer.setAdUp(urls, false, 0);

3、广告视频还是使用 htpps 的链接，下面代码将setAdUp 方法里的 cacheWithPlay 参数设为 true，其他代码不变，就能正常播放：

        ArrayList<GSYSampleADVideoPlayer.GSYADVideoModel> urls = new ArrayList<>();
        //广告1
        urls.add(new GSYSampleADVideoPlayer.GSYADVideoModel("https://static.zxart.cn/UploadFiles/media/Filmhead/8.flv",
                "我是广告 https ", GSYSampleADVideoPlayer.GSYADVideoModel.TYPE_AD));
        //正式内容1
        urls.add(new GSYSampleADVideoPlayer.GSYADVideoModel("http://static.zxart.cn/UploadFiles/media/201806/20180625chishan.mp4",
                "我是正式内容 http", GSYSampleADVideoPlayer.GSYADVideoModel.TYPE_NORMAL));
        detailPlayer.setAdUp(urls, true, 0);

## 问题log（如果有）

06-27 14:46:26.553 7724-8343/com.zhangxiong.art E/IJKMEDIA: Option ijkiomanager not found.
06-27 14:46:28.496 7724-8343/com.zhangxiong.art E/IJKMEDIA: Invalid NAL unit size (25739 > 22504).
06-27 14:46:28.496 7724-8343/com.zhangxiong.art E/IJKMEDIA: missing picture in access unit with size 22508
06-27 14:46:28.572 7724-8059/com.zhangxiong.art E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xa936b6c0)
06-27 14:46:28.574 7724-8059/com.zhangxiong.art E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xa936b740)
06-27 14:46:28.576 7724-8059/com.zhangxiong.art E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xa936b8c0)
06-27 14:46:28.650 7724-8369/com.zhangxiong.art E/IJKMEDIA: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
06-27 14:46:28.651 7724-8369/com.zhangxiong.art E/IJKMEDIA: https://static.zxart.cn/UploadFiles/media/Filmhead/8.flv: I/O error
06-27 14:46:28.652 7724-8059/com.zhangxiong.art E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by CarGuo** [comment]
```
VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by ZQ173** [comment]
可能前两天公司后台服务器不稳定吧，现在无论设为 true 还是 false，都不会了，多谢老大了！

**Comment by ZJLeBron** [comment]
> ```
> VideoOptionModel videoOptionModel =
>                 new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
>         List<VideoOptionModel> list = new ArrayList<>();
>         list.add(videoOptionModel);
>         GSYVideoManager.instance().setOptionModelList(list);
> ```

大佬，我用的以前版本，确实setUp缓存必须为true才能播放https否则报错-10000
