### ISSUE TITLE
播放RTSP直播视频卡顿问题

### ISSUE THREAD

**Issue by caozhx** [CarGuo/GSYVideoPlayer#1246]
## 问题描述：
在局域网中接监控摄像头，使用的是rtsp协议，硬件是3288开发板，我下载的最新demo，把简单播放里的链接换成我的视频链接后，有时候播不出来，有时候能播出来，但是一分钟左右就卡死了；同样的环境同样的链接，使用饺子播放器能正常播放。不知道您有没有遇到这样的情况？
## 问题机型/系统：
真机：rk3288开发板 android5.1
## Demo中的复现步骤
Demo中播放链接换成rtsp的直播链接播放一分钟左右就卡死。
Demo中的detailPlayer页面打开后XXXX会出现这个问题。

**Comment by caozhx** [comment]
oppo R9 android5.1 上也是同样的问题
坚果pro1 android7.1上正常

**Comment by CarGuo** [comment]
请看问题集锦

**Comment by caozhx** [comment]
请问问题集锦里的哪个问题可以解决我的问题？我看了几遍没有看出来，求指教！！

**Comment by caozhx** [comment]
我看到关于这个问题的很多回答都是查看“问题集锦第17条”，但是我找到第17个问题发现好像不是关于这个问题的，大佬可以发个这个问题的链接吗？

**Comment by caozhx** [comment]
按问题集锦设置了以后可以连续播放了，也不会卡顿了，但是有时候会卡住几秒，然后快速播放到当前时间
