### ISSUE TITLE
自定义的surface_container视频渲染view的宽高问题

### ISSUE THREAD

**Issue by liusuqin** [CarGuo/GSYVideoPlayer#1249]
## 问题描述：surface_container视频渲染view的宽高问题
自定义的surface_container视频渲染view的的width，两边有黑边，不是全屏，视频是可以全屏播放的视频，Layout已经设置了match。这是为什么呀？大神

## Demo中的复现步骤
一直出现

问题代码：(如果有)

    <RelativeLayout
        android:id="@+id/surface_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center">

    </RelativeLayout>

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/GSYVideoType.java

```
   //默认显示比例

    public final static int SCREEN_TYPE_DEFAULT = 0;



    //16:9

    public final static int SCREEN_TYPE_16_9 = 1;



    //4:3

    public final static int SCREEN_TYPE_4_3 = 2;



    //全屏裁减显示，为了显示正常 CoverImageView 建议使用FrameLayout作为父布局

    public final static int SCREEN_TYPE_FULL = 4;



    //全屏拉伸显示，使用这个属性时，surface_container建议使用FrameLayout

    public final static int SCREEN_MATCH_FULL = -4;
```

**Comment by liusuqin** [comment]
设置了 FragmeLayout布局 ，但是没有用。，根布局也换Framlayout测试了，没起作用。这是我自定义的全部布局，大神你瞧瞧。
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorBlack">

    <FrameLayout
        android:id="@+id/surface_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/layout_top"
        android:gravity="center">

    </FrameLayout>

    <RelativeLayout
        android:id="@+id/thumb"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignBottom="@+id/surface_container"
        android:layout_alignTop="@+id/surface_container"
        android:scaleType="fitCenter">

        <ImageView
            android:id="@+id/thumbImage"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true"
            android:scaleType="centerCrop" />

    </RelativeLayout>

    <RelativeLayout
        android:id="@+id/layout_top"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:background="@drawable/video_title_bg"
        android:gravity="center_vertical"
        android:orientation="horizontal">


        <TextView
            android:id="@+id/tv_title"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_alignParentLeft="true"
            android:layout_marginLeft="@dimen/x12"
            android:gravity="center_vertical"
            android:text=""
            android:textColor="@color/colorWhite"
            android:textSize="@dimen/sp_12" />

        <ImageView
            android:id="@+id/iv_fullscreen"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:layout_marginRight="16dp"
            android:scaleType="center"
            android:src="@drawable/selector_video_full_screen" />

    </RelativeLayout>


    <LinearLayout
        android:id="@+id/layout_bottom"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:layout_alignParentBottom="true"
        android:background="#99000000"
        android:gravity="center_vertical"
        android:orientation="horizontal"
        android:visibility="invisible">

        <TextView
            android:id="@+id/current"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="@dimen/x12"
            android:gravity="center_vertical"
            android:singleLine="true"
            android:text="00:00:00"
            android:textColor="@color/colorWhite"
            android:textSize="@dimen/small_font" />

        <SeekBar
            android:id="@+id/progress"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:layout_weight="1.0"
            android:background="@null"
            android:max="100"
            android:maxHeight="4dp"
            android:minHeight="4dp"
            android:paddingBottom="8dp"
            android:paddingTop="8dp"
            android:progressDrawable="@drawable/video_seekbar_progress"
            android:thumb="@drawable/video_seekbar_thumb" />

        <TextView
            android:id="@+id/total"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginRight="@dimen/x12"
            android:singleLine="true"
            android:text="00:00:00"
            android:textColor="@color/colorWhite"
            android:textSize="@dimen/small_font" />

    </LinearLayout>

    <ProgressBar
        android:id="@+id/bottom_progressbar"
        style="?android:attr/progressBarStyleHorizontal"
        android:layout_width="match_parent"
        android:layout_height="1.5dp"
        android:layout_alignParentBottom="true"
        android:max="100"
        android:progressDrawable="@drawable/video_bottom_seekbar_progress"
        android:visibility="gone" />


    <moe.codeest.enviews.ENPlayView
        android:id="@+id/start"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:layout_gravity="center_vertical" />




</RelativeLayout>

**Comment by CarGuo** [comment]
参考demo中的

https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/SampleVideo.java


的resolveTypeUI

你可以在demo中跑跑试试

**Comment by liusuqin** [comment]
可以了，大神，感谢/握拳。
