### ISSUE TITLE
使用类似ListMultiVideoActivity的方式轮流播放偶发两个播放器会同时播放

### ISSUE THREAD

**Issue by wisonic** [CarGuo/GSYVideoPlayer#1250]
#1215[](https://github.com/CarGuo/GSYVideoPlayer/issues/1215)
列表滑动顺序播放当前页面视频，然后划过的播放器就release了。在ondestroy里面也调用了clearAllVideo。

但是偶尔出现某个视频开始播放，背后有个视频的声音还在播放，在manager中也找不到这个player。pauseall也没办法暂停。甚至ondestroy走了也没能停掉这个失控的播放器。只能手动杀掉app才能停止这个声音。

请问是否遇到过类似情况，或者这种状态下怎么才能停掉那个release但是并没真正停掉的player？

@CarGuo

**Comment by CarGuo** [comment]
这个问题应该和key有关~~ getKey()方法决定了这个video在Manager中的map位置，所以如果存在key重复、或者对应不上的，可能就会出现这个问题，建议你可以修改这个方法，返回你的唯一key规则。
