### ISSUE TITLE
请教一下 如何把背景铺满模糊播放效果 实现到整个界面背景上面 而不是播放器背景

### ISSUE THREAD

**Issue by WuShengXi** [CarGuo/GSYVideoPlayer#1252]
请教一下 如何把背景铺满模糊播放效果 实现到整个界面背景上面 而不是播放器背景

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/effect/GSYVideoGLViewCustomRender4.java

https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailFilterActivity.java

这个里面的
```
        //高斯拉伸视频铺满背景，替换黑色，前台正常比例播放

        //detailPlayer.setEffectFilter(new GaussianBlurEffect(6.0f, GaussianBlurEffect.TYPEXY));

        //detailPlayer.setCustomGLRenderer(new GSYVideoGLViewCustomRender4());

        //detailPlayer.setGLRenderMode(GSYVideoGLView.MODE_RENDER_SIZE);


```

**Comment by DubheBroken** [comment]
补充一下，要设置渲染模式以后才会生效

```Java
GSYVideoType.setRenderType(GSYVideoType.GLSURFACE)
```

**Comment by chapliny** [comment]
请教下，如何让高斯的边界和视频之间过度的平滑一点。

**Comment by QYC5535** [comment]
> ```java
> e(GSYVideoType.GLSURFACE)
> ```

添加这行代码以后，我发现视频方向变了
