### ISSUE TITLE
MP4视频播放 回到桌面 在进入 不会开始播放 有时候会跳动到开始位置 加载很慢

### ISSUE THREAD

**Issue by bux-git** [CarGuo/GSYVideoPlayer#1253]
## 问题描述：

MP4视频播放 回到桌面 在进入 不会开始播放 有时候会跳动到开始位置 加载很慢
使用其他视频资源没有问题，然后使用PlayerBase播放的话 加载也会慢 但是回到桌面再进入会继续播放

## 问题机型/系统：

例如 真机 小米 华为

## Demo中的复现步骤
直接使用Demo中的 详情 和输入URL页面 
视频地址：http://175.6.69.168:8000/mp4/student.mp4
麻烦大神帮忙看下

**Comment by bux-git** [comment]
正常播放就是开始加载时慢，后续播放正常，但是拖动进度条的话就会很慢，然后有大几率跳转回到开始位置

**Comment by bux-git** [comment]
已经加入这个，拖动加载慢，现在主要问题是，回到桌面再进入视频进入加载状态，然后会加载不出 进度条会持续移动到末尾，然后再跳到开始 从头开始播放
我试了demo中提供的视频没问题，我这个视频会出现这种情况

**Comment by CarGuo** [comment]
getCurPlay().onVideoResume(false);


或者


        GSYVideoManager.onResume(false);

**Comment by bux-git** [comment]
可以了 谢谢
 还有一个问题就是频繁拖动进度条的话 视频会出现卡带的声音 然后加载中  跳到开始 从头开始播放

**Comment by CarGuo** [comment]
```
  VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
        List<VideoOptionModel> list = new ArrayList<>();
       list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

```
