### ISSUE TITLE
出现这个,我布局都看不到了

### ISSUE THREAD

**Issue by weituotian** [CarGuo/GSYVideoPlayer#126]
![image](https://cloud.githubusercontent.com/assets/7270968/24323397/acf06454-11af-11e7-874e-81568f34f376.png)

![image](https://cloud.githubusercontent.com/assets/7270968/24323489/3a043004-11b1-11e7-850a-c3c55624daf0.png)

**Comment by weituotian** [comment]
@CarGuo 
因为构造器初始化的时候就new 了一个IjkMediaPlayer()
布局的时候也会new 这个
所以把IjkMediaPlayer的创建延后一点比较好啊

**Comment by CarGuo** [comment]
构造这个，只是为了在用这个单例的时候，避免不小心有时候null的情况。

**Comment by weituotian** [comment]
@CarGuo 
能不能用IsInEditView判断一下，在布局的时候就不要new了
