### ISSUE TITLE
GSYVideoManager问题请教

### ISSUE THREAD

**Issue by qinyang1018** [CarGuo/GSYVideoPlayer#1262]
## 问题描述：
viewpager中两个fragment都是列表形式播放器。 来回切换viewpager在fragment的可见不可见方法中进行播放器的暂停和播放。  
1、A Fragment切换到B Fragment  暂停 GSYVideoManager.onPause();  a列表播放器  
2 、GSYVideoManager.onResume(); 播放B fragment 播放器  此时A页面中播放器还会继续播放

**Comment by CarGuo** [comment]
GSYVideoManager 只会有一个播放内核，同一时间只会有一个播放中，你用的是哪个player？

**Comment by qinyang1018** [comment]
同时确实只有一个会播放，但是我到B页面时 不点击播放 A的还会在播放
![image](https://user-images.githubusercontent.com/15726024/42219149-6ccb325c-7efd-11e8-9d5f-3fd57097caaa.png)

**Comment by qinyang1018** [comment]
好的  感谢

**Comment by qinyang1018** [comment]
今天尝试了下 还是有问题，通过TAG判断了但是走了  GSYVideoManager.onResume(); 貌似两个页面的  GSYVideoManager是同一个
