### ISSUE TITLE
关于视频的单击显示定时任务 取消掉的问题

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1265]
就是我已经把双击事件继承后 不做操作了，现在想要取消掉单击时 出现那个定时 屏幕周边变暗的的定时任务，改成单击播放。那个单击事件在哪里进行设置？

**Comment by xi5528336** [comment]
@CarGuo

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/GSYADVideoPlayer.java   参考下这个吧，这个的单击触摸什么鬼都屏蔽了，这个一两句话说不清楚的
