### ISSUE TITLE
5.0以下机型 java.lang.NoClassDefFoundError 解决方法

### ISSUE THREAD

**Issue by lichen228** [CarGuo/GSYVideoPlayer#1266]
看到很多Issues提到了这个问题，作者也提示了是multi的原因，但都没补齐解决方法
自己也遇到了，把解决发出来，希望作者能更新到README里，让更多的人配置前就注意到

## 问题描述：
java.lang.NoClassDefFoundError：
com.shuyu.gsyvideoplayer.video.base.GSYVideoPlayer.getGSYVideoManager(GSYVideoPlayer.java:36)
com.shuyu.gsyvideoplayer.video.base.GSYVideoView.setSpeed(GSYVideoView.java:1003)
com.shuyu.gsyvideoplayer.builder.GSYVideoOptionBuilder.build(GSYVideoOptionBuilder.java:604)
com.shuyu.gsyvideoplayer.builder.GSYVideoOptionBuilder.build(GSYVideoOptionBuilder.java:567)
com.demo.activity.MainActivity.initVideoPlayer(MainActivity.kt:128)
com.demo.activity.MainActivity.onCreate(MainActivity.kt:52)

## 问题机型/系统：
Android5.0(API level 21)以下机型出现

## 解决方式:
1.app的build.gradle里配置(AS默认会配置，没有需补上)：
android {
    defaultConfig {
         multiDexEnabled true
    }
}
**2.重点：5.0以下机型，MyApp必须继承 MultiDexApplication**
很多人应该都是卡在这里了
5.0以上，因为ART的支持，MyApp直接继承Application即可，不会报错
5.0以下，因为Dalvik的执行，MyApp必须继承MultiDexApplication才可以

希望后续搜Issues的朋友看到这个能节省些时间

**Comment by CarGuo** [comment]
6666
