### ISSUE TITLE
全屏横竖屏问题

### ISSUE THREAD

**Issue by CheersLiu** [CarGuo/GSYVideoPlayer#1267]
@CarGuo 我继承StandardGSYVideoPlayer之后，视频时点击全屏按钮之后直接横屏，但是点击全屏按钮退出全屏的时候屏幕变成横向的了，这里有什么方法解决吗？

**Comment by CarGuo** [comment]
参考demo配置manifset

**Comment by CheersLiu** [comment]
@CarGuo 我没有表述清楚，横屏全屏之后，缩放按钮隐藏了，点击的是标题左边的返回按钮，返回之后退出了全屏，并且屏幕方向变成横向的。我使用的是全屏跟非全屏两套布局，但是全屏之后点击返回使用的是默认的返回方法。当我改变了返回按钮的id，尝试在全屏布局中使用自定义的返回按钮并设置点击事件回调，发现全屏之后点击这个按钮没有任何反应，请问这个问题应该要如何才能解决呢？我看你DEMO上StandardGSYVideoPlayer的startWindowFullscreent中在设置自定义的返回按钮的点击事件，我在我自定义的Player中复写这个方法，代码如下：
GSYBaseVideoPlayer gsyBaseVideoPlayer = super.startWindowFullscreen(context, actionBar, statusBar);
        if (gsyBaseVideoPlayer != null) {
            if(mBackIcon != null){
                  mBackIcon.setOnClickListener{
                              ......
                  }
            }
        }
但却没有触发这个回调，想请教下这应该如何解决呢？

**Comment by CheersLiu** [comment]
清单文件中的Activity配置跟你demo中的DetailPlayer是相同的

**Comment by CarGuo** [comment]
看的有点晕(=_=)
具体在demo怎么复现？我好定位

**Comment by CheersLiu** [comment]
@CarGuo 简单来说就是，我在全屏之后隐藏了退出全屏按钮，想通过点击返回按钮来实现退出全屏功能，但是现在按返回按钮之后屏幕会横过来，主要是想解决这个问题。

**Comment by CarGuo** [comment]
这个类似detailplayer的onBackPress方法
```
 @Override
    public void onBackPressed() {

        if (orientationUtils != null) {
            orientationUtils.backToProtVideo();
        }

        if (GSYVideoManager.backFromWindowFull(this)) {
            return;
        }
        super.onBackPressed();
    }
```

**Comment by CheersLiu** [comment]
@CarGuo 是的，我也是想在点击返回按钮的时候触发这个操作，现在的问题就是我使用默认的返回按钮的时候退出全屏后变成横屏，但是重新自定义返回按钮之后点击又没有任何反应，现在就想解决下这个

**Comment by CheersLiu** [comment]
@CarGuo 要怎么样才能设置返回按钮触发这个操作呢

**Comment by CarGuo** [comment]
看demo啊

**Comment by CheersLiu** [comment]
@CarGuo 我使用的是全屏与非全屏两套布局，但是在getBackButton方法获取到的是非全屏的返回按钮，请问全屏布局下的返回按钮要如何才能获取到呢？ 头布局上的id我都没有变依然是使用 <LinearLayout
        android:id="@+id/layout_top"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:layout_alignParentTop="true"
        android:layout_toEndOf="@+id/back_tiny"
        android:layout_toRightOf="@+id/back_tiny"
        android:background="@drawable/video_title_bg"
        android:gravity="center_vertical">

        <ImageView
            android:id="@+id/back"
            android:layout_width="48dp"
            android:layout_height="48dp"
            android:paddingLeft="10dp"
            android:scaleType="centerInside"
            android:src="@drawable/video_back" />

        <TextView
            android:id="@+id/title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:paddingLeft="10dp"
            android:textColor="@android:color/white"
            android:textSize="18sp" />
这样的，现在的情况是，我通过R.id.back获取到一个ImageView之后设置回调，发现依然走的默认的返回按钮方法，没有触发我这个回调，但如果我改变了这个布局文件中的返回按钮id之后，点击返回按钮之后就没有任何反应了。

**Comment by CarGuo** [comment]
一般是通过 player.getCurrentPlayer去获取，你可以在进去全屏的回调里去设置。

然后你也可以在继承的类里，通过isFullxxxx的标志位判断，然后增加接口回调出来，比如通过标志位，在
init方法中，对按键设置了点击，回调出来也根据标志位处理。

全屏和非全屏主要是切换了全新的控制ui
