### ISSUE TITLE
播放器中的控制UI如何去除，如何实现单击播放？

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1272]

**Comment by CarGuo** [comment]
控制UI你可以通过继承后，返回getLayoutId，另外一个问题 https://github.com/CarGuo/GSYVideoPlayer/issues/1265

**Comment by xi5528336** [comment]
@CarGuo  大佬,这个问题我自己看源码解决掉了  还有一个问题:就是如何在全屏状态下的屏幕里增加一些自己需要的按钮？

**Comment by CarGuo** [comment]
LandLayoutVideo demo中
