### ISSUE TITLE
软键盘弹出时，播放器怎样才能不缩小

### ISSUE THREAD

**Issue by 995518790** [CarGuo/GSYVideoPlayer#1273]
surface_container的宽高都是match_parent
视频资源也是竖屏的。
弹出软键盘时，播放器会缩小。
如果设置GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);，视频左右撑满，上下缩小了。
如何才能弹出软键盘，播放器不缩放，下面被覆盖一部分也没关系。

**Comment by CarGuo** [comment]
～activity的键盘配置，就去配置为不adjust或者其他的

**Comment by 995518790** [comment]
不行都试了，adjustresize视频缩小，其他adjustpan、adjustnothing都是把视频往上推，上半部分被覆盖了

**Comment by CarGuo** [comment]
adjustnothing 理论上是不会推动才对的。

或者你想bilibli，点击弹幕评论的时候，弹出新的一个透明层·

话说，这个不算视频的issue吧

**Comment by 995518790** [comment]
我这里因为其他功能必须要设置为adjustresize，我想知道有没有固定播放器宽高，不自适应的方法。

**Comment by CarGuo** [comment]
主布局都被挤压了，这个不适合。
你可以参考哔哩哔哩android客户端，它弹出来的时候，是多了一个类似dialog层的
