### ISSUE TITLE
关于播放和暂停按钮

### ISSUE THREAD

**Issue by mengbixiusi** [CarGuo/GSYVideoPlayer#1274]
问题描述:
请问如何监听播放和暂停按钮的点击事件,我在实现了GSYSampleCallBack接口的 onClickStartIcon()方法后,发现不起作用啊,,,,,,,,,,,,

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/listener/VideoAllCallBack.java


```



    //点击了播放状态下的开始按键--->停止，objects[0]是title，object[1]是当前所处播放器（全屏或非全屏）

    void onClickStop(String url, Object... objects);



    //点击了全屏播放状态下的开始按键--->停止，objects[0]是title，object[1]是当前所处播放器（全屏或非全屏）

    void onClickStopFullscreen(String url, Object... objects);




 //点击了暂停状态下的开始按键--->播放，objects[0]是title，object[1]是当前所处播放器（全屏或非全屏）

    void onClickResume(String url, Object... objects);



    //点击了全屏暂停状态下的开始按键--->播放，objects[0]是title，object[1]是当前所处播放器（全屏或非全屏）

    void onClickResumeFullscreen(String url, Object... objects);


```

**Comment by mengbixiusi** [comment]
谢谢回复,问题解决了.

我开始是用GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder(); 设置的回调
gsyVideoOption.setVideoAllCallBack(new GSYSampleCallBack() {} 不知道为什么不起作用

应该用StandardGSYVideoPlayer 来设置回调,刚开始使用,谢谢大佬解答,已赞
