### ISSUE TITLE
请问能支持视频流的录像和拍照?

### ISSUE THREAD

**Issue by luojianping168** [CarGuo/GSYVideoPlayer#1275]
我想实现和安防一样的 使用rtsp流地址连接摄像头,在手机端实现拍照录像功能,主要是h264和h265编码,关键是h265编码很多播放器实现不了器录像功能,还有要达到低延迟效果!

**Comment by CarGuo** [comment]
直播流目前不支持保存

**Comment by hj850113** [comment]
请问如果只想播放rtsp流，要怎样操作呢？

**Comment by CarGuo** [comment]
依赖exso和java
