### ISSUE TITLE
播放视频中网络断开没有上报异常

### ISSUE THREAD

**Issue by lejun** [CarGuo/GSYVideoPlayer#1276]
## 问题描述：

播放其他格式（mp4）过程中断开网络会上报网络异常，但是播放m3u8视频文件（设置不缓存），不但没有上报异常事件，却上报了已经播放完的事件

视频源：http://vod.umlink.cn/15becdb9597a477687d13d0ec1d73c2e/01b472986618464e991dbf7e9ef85b09-19d86b6450477cf60c93f763a7b71bcf-ld.m3u8

## 问题机型/系统：

OPPO A37m (在其他手机上也会有)

## Demo中的复现步骤
1.在网络情况下正常播放m3u8视频
2.正常播放一段时间后关闭手机网络
3.等待1min后进度条显示已经播放完（其时视频并没有播放完）

并没有异常日志，只是这种现象奇怪。。。

**Comment by CarGuo** [comment]
因为m3u8是多分片，分片缓冲播放完了就没了。

**Comment by lejun** [comment]
但是播放m3u8的视频没有设置缓存

**Comment by CarGuo** [comment]
没缓存，有缓冲
