### ISSUE TITLE
fragment中全屏返回无效的问题，GSYVideoManager.backFromWindowFull(getActivity())无效

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1277]
查看了代码中的videofragment  里面有个方法  
public boolean onBackPressed() {
        if (GSYVideoManager.backFromWindowFull(getActivity())) {
            return true;
        }
        return false;
    }

我在fragment中注册了返回监听然后调用这个方法还是没用，翻看了以前别人提的问题，也没找到解决办法  @CarGuo  大佬 求助  是不是还有其他的fragment代码

**Comment by xi5528336** [comment]
@CarGuo  在activity下发下去的？  不是很明白  有videoFragment与activity相关联的代码吗，或者解释一下activity下发给fragment  onBackPressed是什么样下发的。

**Comment by xi5528336** [comment]
@CarGuo  查看了FragmentVideoActivity中的代码  套用了里面的
 newFragment = new VideoFragment();
        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
        transaction.replace(R.id.frameLayout, newFragment);
        transaction.addToBackStack(null);
        transaction.commit();

@Override
    public void onBackPressed() {
        if (newFragment.onBackPressed()) {
            return;
        }
        finish();
    }

我的demo是一个Activity里有4个fragment  其中只有一个fragment是需要全屏播放退出的
,直接套用不行 ,transaction.replace(R.id.frameLayout, newFragment);   
R.id.frameLayout在我的demo是不是要改，我改成了我的Activity里面的父布局然后进去界面都是乱的.

**Comment by CarGuo** [comment]
fragment中没有back时间，back事件是从activity自己下发下去的，至于什么下发下去就看你自己实现。这和嵌套之类的没什么关系，调用到就可以
