### ISSUE TITLE
播放屏幕跟随手机旋转

### ISSUE THREAD

**Issue by CheersLiu** [CarGuo/GSYVideoPlayer#1278]
@CarGuo 在视频播放界面的Activity设置完android:configChanges="orientation|keyboardHidden|screenSize"属性，并且设置屏幕方向为竖屏，但是当打开手机的重力旋转开关之后，播放界面还是会随着手机的旋转而旋转，这个有办法解决吗？

**Comment by xi5528336** [comment]
你如果是使用了orientation，可以将orientation.setEnable(false);并且如果Activity里面重载了onConfigurationChanged方法 就把他删除掉或者做一些限制

**Comment by CheersLiu** [comment]
设置了orientation的Enable为false了 还是会跟着屏幕一起转

**Comment by CarGuo** [comment]
orientation.setEnable(false);
player.setLockLand true
player.setRotateViewAuto false
理论上是这样
