### ISSUE TITLE
so库正确编译情况下，ListView中的视频，有声音，没有画面

### ISSUE THREAD

**Issue by andrewhuhong** [CarGuo/GSYVideoPlayer#128]
ListView中的视频，有声音，没有画面，so库编译加载成功。在博主所给的demo中可以播放，导入自己所写工程，视频有声音，没画面，其他的功能都可以，这个如何解决？？？

**Comment by CarGuo** [comment]
同个播放的url吗？确定下textureView是否创建成功，跟踪GSYVideoPlayer下的onSurfaceTextureAvailable和onSurfaceTextureDestroyed是否正常创建和销毁。
如果是不同url，确定url的视频格式是否支持

**Comment by andrewhuhong** [comment]
是的，是同一个URL，借用博主你的Ddemo中的URL。我用红米Note3和小米2测试，有声音，没画面，用魅族的手机测试可以正常播放

**Comment by andrewhuhong** [comment]
我是在Fragment中使用的，同时也是在异步加载中的函数中使用：这个有影响么？
        @Override
        protected void onPostExecute(String s) {
            super.onPostExecute(s);
            getActivity().runOnUiThread(new Runnable() {
                public void run() {
                    // updating listview
                    try {
                        if (friendCommunityList.get(0) != null){
                            Log.d(TAG,friendCommunityList.toString());
                            //最开始的使用方法
                            //FriendCommunityListAdapter adapter = new FriendCommunityListAdapter(getActivity(), friendCommunityList);
                            //listView.setAdapter(adapter);

                            final NewFriendCommunityListAdapter adapter = new NewFriendCommunityListAdapter(getActivity(),friendCommunityList);
                            listView.setAdapter(adapter);
...
                               }
                   }
         }
}

**Comment by CarGuo** [comment]
你需要确定的是，GSYTextureView是否正确生成和创建

**Comment by andrewhuhong** [comment]
楼主大大，你说的很对，GSYTextureView没有创建，这个该如何在Fragment中正确创建？？不知如何下手，能指点一二，多谢！

**Comment by CarGuo** [comment]
创建是在内部处理的，参考下demo的布局和使用方式
