### ISSUE TITLE
全屏竖屏标题大小问题

### ISSUE THREAD

**Issue by AnJiuZhe** [CarGuo/GSYVideoPlayer#1280]
## 问题描述：

通过videoPlayer.getTitleTextView().setTextSize(14);设置标题大小,竖屏状态下有效果,点击全屏按钮后,标题大小并不是设置后的大小,请问用的是不同的布局吗?

**Comment by CarGuo** [comment]
继承后重写getLayoutId
或者videoPlayer.getCurrentPlayer，在进去全屏的会回调里设置
