### ISSUE TITLE
支持socket吗？

### ISSUE THREAD

**Issue by Gaoyongxian666** [CarGuo/GSYVideoPlayer#1281]
大神，我打算用安卓手机连接硬件端的wifi模块，然后通过socket收到传回来的数据（数据是视频），你写的这个框架好像不能直接用，我该怎么改呢？

**Comment by CarGuo** [comment]
你看了源码么。在默认模式下，缓存就是通过socket拉流，本地代理

**Comment by Gaoyongxian666** [comment]
看不太懂，是不是需要继承你的类然后改。然后改播放的那几个类。。自定义demo里好像没有，需要改哪几个类呢，我找不着，能给说下吗

**Comment by Gaoyongxian666** [comment]
我好像搞不定了，，，求帮忙加上socket通信方式的播放吧

**Comment by CarGuo** [comment]
我觉得···你应该去了解下socket和流···然后就知道库里已经有类似的支持了，不过你需要改改而已

**Comment by Gaoyongxian666** [comment]
那个类似的支持，能具体说下吗？

**Comment by Gaoyongxian666** [comment]
应该改哪个文件呢？
![demo](https://user-images.githubusercontent.com/35163802/42668712-b1d1475e-8684-11e8-91fb-8923743098c4.png)

**Comment by CarGuo** [comment]
proxy是开了本地127.0.0.1代理拉流，看看源码就知道了
