### ISSUE TITLE
多个视频fragment共存的问题.以及RecyclerViewActivity的界面复用问题

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1283]
@CarGuo 需求需要,把RecyclerViewActivity变成了RecyclerViewFragment 然后放了2个相邻的RecyclerFragment在ViewPager里   点击里面的一个Item播放,播放正常,然后测试的时候,先按暂停,然后点击全屏，全屏后播放键就没用了，点击之后会出现暂停播放按钮状态转换，但是画面不会动了.

测试了RecyclerActivity RecyclerFragment 发现 如果存在相邻就会出现这种情况，单个出现是没问题的,所以在你的demo中没有复现这种情况。然后我用了MulSample  这个问题就没了。  但是我不想实现
可以多个播放,只需要单个播放，应该怎么办？  以及在RecyclerView会出现界面复用的问题,看了你的demo,加了
 gsyVideoPlayer.initUIState(); 是不是就可以把界面复用问题解决掉了。

**Comment by CarGuo** [comment]
首先你配置了manifest没？这个和相邻的没什么关系，可以参考下https://github.com/CarGuo/GSYVideoPlayer/issues/1262

**Comment by xi5528336** [comment]
@CarGuo 

manifest 配置如下  
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"
            android:windowSoftInputMode="adjustPan"

GSYVideoPlayer只有一个播放内核，但是ViewPager中若含有2个播放列表时,我正常播放是没有问题的
点击播放  然后点击暂停再点击全屏时，画面就不会动了，播放按键能够点击但是只切换图标形态,操作失灵,应该就是  只能一个播放内核的原因。  使用MulSampleVideo 或者ViewPager中仅有一个播放列表没有问题。    如果现在用MulSapmileVideo 多内核播放,我的是一个RecyclerViewActivity的类似代码,不想使用多个播放，只希望能单个播放  应该怎么做。

**Comment by CarGuo** [comment]
个人感觉，像是在全屏的时候，你的列表监听滑动导致的问题。比如不同的fragment你要设置不同的tag给player

**Comment by CarGuo** [comment]
暂停全屏的時候才这个问题？那可以是哪个位置存在暂停的时候是出发了adapter的更新，然后判断标志不对

**Comment by xi5528336** [comment]
@CarGuo 如果是触发了adapter的更新，导致标志位的错误,那为什么如果播放器基础多核播放器MultiSampleVideo的时候  暂停全屏就正常了

**Comment by CarGuo** [comment]
因为多个内核

**Comment by xi5528336** [comment]
@CarGuo  在没解决问题前,我想先用多核播放器 但是又不想支持多个播放，有什么解决办法吗

**Comment by xi5528336** [comment]
@CarGuo  找到错误了，我在另外一个fragment里因为需要播放Raw文件下的视频来测试 就调用了GSYVideoManager.instance().setVideoType(context, 4);  切换成了系统播放器,然后把这句话删掉，调用默认IJK播放器 就没有全屏暂停的问题了，请问是什么原理

**Comment by CarGuo** [comment]
这个属于复用错位的问题，比如你需要在onbind的时候判断是否播放中去设置显不显示标题

**Comment by xi5528336** [comment]
@CarGuo 我就是在onBind中  setVideoAllCallBack()里的onPrepared里View.GONE, 自动播放完就View.VISIBLE，什么样才能避免复用错位。

**Comment by CarGuo** [comment]
你还需要在adapter中判断是否已经播放，然后去设置显示，这是简单的list错误问题

**Comment by VCE-K** [comment]
> 首先你配置了manifest没？这个和相邻的没什么关系，可以参考下#1262

大佬，我想问一下，不配置manifest的configChanges可不可以，我想通过viewmodel在fragment点击全屏的时候还能维持播放

**Comment by xi5528336** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by VCE-K** [comment]
谢谢大佬，我现在好像看到的视频播放器框架都是在asmanifest里面设置activity，我不知道可不可以通过view model之类的东西保持播放进度什么的，然后让视频全屏也正常播放

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xi5528336 ***@***.***&gt;
发送时间: 2023年6月24日 14:34
收件人: CarGuo/GSYVideoPlayer ***@***.***&gt;
抄送: VCE-K ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [CarGuo/GSYVideoPlayer] 多个视频fragment共存的问题.以及RecyclerViewActivity的界面复用问题 (#1283)





 这是来自QQ邮箱的假期自动回复邮件。 
 &nbsp; 
 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
