### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by fvaryu** [CarGuo/GSYVideoPlayer#1284]
## 问题描述：

使用EXOPlayer2无法播放, 使用ijkplayer5分钟之后会出现闪烁，而且视频播放时长超过显示的时长6分20

## 问题机型/系统：

红米4 系统6.0.1
中兴BA611c_6677 5.1
中兴V0840 7.1.1

## Demo中的复现步骤

Demo中GSYApplication中修改播放内核，在简单播放中播放
"https://oss.zhihanyun.com/1528110034781147129.m3u8"
onError中what = 1 extra=1,不知道是什么意思

视频有经过七牛转码,转码前地址https://oss.zhihanyun.com/o_1cf575kl31fgm8km12lpiel5epqk.mp4（同样不能播放）

补充：
1、猜测是不是视频分辨率太高了不支持，原视频分辨率3840 × 2160
2、经实验发现将3840x2160分辨率转为1080X608，960x540后播放正常

**Comment by fvaryu** [comment]
已确定问题所在，确实是分辨率太高无法播放，不支持2K？

**Comment by CarGuo** [comment]
可能是，毕竟软解码和手机的cpu有一点关系

**Comment by Android-Boys** [comment]
视频分辨率1920*1080 。播放失败的话  是不是走onError方法。what值是否为-10000
