### ISSUE TITLE
DrawerLayout 冲突

### ISSUE THREAD

**Issue by hanouba** [CarGuo/GSYVideoPlayer#1285]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

用A方法 添加依赖后，导致DrawerLayout的addDrawerListener方法无法使用

## 问题机型/系统：

直接报错

## Demo中的复现步骤

删除依赖后就正常了

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
？？

**Comment by hanouba** [comment]
我添加完整依赖后，DrawerLayout的方法addDrawerListener无法使用，删除依赖后就正常了，就是侧边栏的一个控件

**Comment by CarGuo** [comment]
这个不属于库的问题

**Comment by hanouba** [comment]
真的吗？

**Comment by hanouba** [comment]
哭

**Comment by CarGuo** [comment]
明显是····
