### ISSUE TITLE
视频播放缓慢

### ISSUE THREAD

**Issue by jianlin00000** [CarGuo/GSYVideoPlayer#1286]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

想请教一下大佬，经过测试对比发现，一个和你demo中的测试视频差不多大小的在线视频，在相同的网络条件下播放缓冲很慢，而大佬demo中的视频播放明显顺畅很多，是不是后台的文件服务器有什么特殊的配置 (最近一直被领导吐槽视频播放太慢.....)

**Comment by CarGuo** [comment]
你确定不是后台带宽和没有cdn加速的问题？
