### ISSUE TITLE
demo中此链接无法播放

### ISSUE THREAD

**Issue by 50kg** [CarGuo/GSYVideoPlayer#1287]
https://api.fabfr.com/api/url.php?xml=9a82637518784c64b475da862c56f446,360982&md5=ab5929e69b8ab5d65f9068c26533loij&type=iqiyi&hd=cq&wap=1&siteuser=&m3u8=1&lg=&cip=cq&iqiyicip=cq

此链接无法播放，使用MX播放器可以正常播放

**Comment by CarGuo** [comment]
403返回

**Comment by 50kg** [comment]
是的，虽然浏览器返回403，但是此链接 复制到QQ浏览器或者Mx Player网络串流的确可以播放。demo直接返回错误，不知道哪里的原因

**Comment by 50kg** [comment]
试了把缓存设置为false还是直接error 不知道哪里的问题 谢谢 @CarGuo

**Comment by CarGuo** [comment]
这就不清楚了
