### ISSUE TITLE
正在播放跳转到另一个播放 返回后好像不能resume,会黑屏

### ISSUE THREAD

**Issue by csh159** [CarGuo/GSYVideoPlayer#1289]
Debug查看了下onVideoResume方法 ，mCurrentState 参数变成了0，所以不能resume。还是必须重新设置一次，记入位置移动到这个位置。能不能自动onresume

**Comment by CarGuo** [comment]
正在播放跳转到另一个播放，默认内核只有一个，播放新的旧的自然normal了
