### ISSUE TITLE
功能优化

### ISSUE THREAD

**Issue by loveRose** [CarGuo/GSYVideoPlayer#129]
设置setIsTouchWiget方法无法控制全屏下的滑动功能，也无法自定义扩展设置。
解决方案，将GSYVideoPlayer类558行判断去除是否全屏条件，并且提供额外boolean变量控制，切切换全屏的时候，GSYBaseVideoPlayer类321行开始，未给全屏对象赋值IsTouchWiget或其他

**Comment by CarGuo** [comment]
这个方法并没打算给全屏功能下使用，全屏下有lock方法

**Comment by CarGuo** [comment]
update by 1.6.2
