### ISSUE TITLE
8.0系统播放音频时点击暂停崩溃

### ISSUE THREAD

**Issue by HortonGou** [CarGuo/GSYVideoPlayer#1290]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

8.0系统播放音频时点击暂停崩溃

## 问题机型/系统：

例如 真机 小米5 Android8.0

## Demo中的复现步骤

Demo中的SimpleDetailActivityMode1页面替换url为MP3链接，点击播放后再暂停会出现这个问题。

## 问题log（如果有）

![image](https://user-images.githubusercontent.com/9068449/42669364-8f428c2c-8687-11e8-83fc-eb03faab9ee3.png)

**Comment by CarGuo** [comment]
请提供测试url

**Comment by HortonGou** [comment]
只要是mp3都不行，其他格式音频没试过。测试的话可以用这个http://7xp06y.com1.z0.glb.clouddn.com/b10/%E4%B8%80%E6%97%A0%E6%89%80%E6%9C%89%E6%9C%89%E6%A2%A6%E8%80%8C%E5%B7%B2%20solo%20cut.mp3

**Comment by HortonGou** [comment]
还是不起作用，在其他手机上似乎没事，可能是手机平台的问题了
