### ISSUE TITLE
循环播放某段区域视频？

### ISSUE THREAD

**Issue by CatyVon** [CarGuo/GSYVideoPlayer#1291]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

项目中有个需求，是根据Listview的点击获取到播放起始时间以及结束时间，比如Item1的播放区域是1秒开始到5秒结束，默认是执行item1的播放区域，在用户未点击其他item的时候，视频一直是从1秒开始播放到5秒 ，然后一直如此循环，只有当用户点击了其他item获取到新的播放区域时间才会播放新的改时间区域的视频，请问大神怎么搞呢？

## 问题机型/系统：

例如 真机 小米MIX2 Android 8.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

**Comment by CarGuo** [comment]
目前并不支持这种实现

**Comment by CatyVon** [comment]
那有没有设置播放的监听 比如可以监听播放的时长  或者是给播放器设置结束时间的

发送自 Windows 10 版邮件应用

发件人: Shuyu Guo
发送时间: 2018年7月16日 8:41
收件人: CarGuo/GSYVideoPlayer
抄送: Monce; Author
主题: Re: [CarGuo/GSYVideoPlayer] 循环播放某段区域视频？ (#1291)

目前并不支持这种实现

**Comment by CatyVon** [comment]
你好 Header是什么的Header?  设置Ranger是具体怎么做呢？  实在是不好意思  一直这么麻烦你

发送自 Windows 10 版邮件应用

发件人: Shuyu Guo
发送时间: 2018年7月18日 8:54
收件人: CarGuo/GSYVideoPlayer
抄送: Monce; Author
主题: Re: [CarGuo/GSYVideoPlayer] 循环播放某段区域视频？ (#1291)

你可以通过header设置range

**Comment by CarGuo** [comment]
这个就是服务端配合，然后再请求的时候在请求的header带上range范围

**Comment by CatyVon** [comment]
哦 那估计这边不好实现  这边的功能是后台给一整段视频  然后还有一个分段数据  默认播放第一段  有一个开始和结束时间  只要用户不切换那个分段数据  就一直默认循环播放第一段  用户如果切换了分段  那么根据用户点击的分段数据  重新获取开始和结束时间  然后让视频以新的时间来播放  目前使用了sdk里面的seukto（long time）可以解决让视频在指定位置播放  但是那个结束时间没办法控制  不过也谢谢你了  麻烦这么多

发送自 Windows 10 版邮件应用

发件人: Shuyu Guo
发送时间: 2018年7月18日 14:34
收件人: CarGuo/GSYVideoPlayer
抄送: Monce; Author
主题: Re: [CarGuo/GSYVideoPlayer] 循环播放某段区域视频？ (#1291)

这个就是服务端配合，然后再请求的时候在请求的header带上range范围

**Comment by CarGuo** [comment]
一半阿里云这种都支持的，类似断点下载的概念
