### ISSUE TITLE
网络原因引起的重连

### ISSUE THREAD

**Issue by MaryDQ** [CarGuo/GSYVideoPlayer#1292]
## 问题描述：

项目中播放rtsp是正常的，但如果这时候网络卡顿了，会自动重连，一直重连不上，请问作者这个有相应的回调或者处理方法吗

**Comment by MaryDQ** [comment]
最近rtsp的依赖是动过了吗？播放rtsp很不稳定

**Comment by CarGuo** [comment]
没改版本号就没改过
