### ISSUE TITLE
播放rtsp出错

### ISSUE THREAD

**Issue by MaryDQ** [CarGuo/GSYVideoPlayer#1295]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

DetailPlayer界面播放rtsp链接，正常播放3分钟以后，出现错误 error while decoding MB 18 29, bytestream -7，测试了10来次，都是这个错误

## 问题机型/系统：

魅蓝note5

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

## 问题log（如果有）

07-17 10:37:21.463 21346-22631/com.microsys.videodemo W/IJKMEDIA: RTP: missed 5 packets
    max delay reached. need to consume packet
    RTP: missed 1 packets
    max delay reached. need to consume packet
    RTP: missed 6 packets

07-17 10:37:21.729 21346-22681/com.microsys.videodemo I/IJKMEDIA: concealing 606 DC, 606 AC, 606 MV errors in I frame
07-17 10:37:22.198 21346-22682/com.microsys.videodemo E/IJKMEDIA: error while decoding MB 32 5, bytestream -5
07-17 10:37:22.199 21346-22682/com.microsys.videodemo I/IJKMEDIA: concealing 1017 DC, 1017 AC, 1017 MV errors in P frame
07-17 10:37:22.273 21346-22683/com.microsys.videodemo E/IJKMEDIA: mmco: unref short failure
    illegal short term buffer state detected

**Comment by MaryDQ** [comment]
已经是设置了tcp播放，并且设置了是25帧

**Comment by CarGuo** [comment]
问题集锦中还有一些配置，如inbufer等

**Comment by Eyesomes** [comment]
怎么解决的? 我也遇到这种情况

**Comment by Eyesomes** [comment]
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "reconnect", 5);
        list.add(videoOptionModel);
        //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
设置了也会与这个错误,花屏

**Comment by hjywyj** [comment]
同问，怎么解决的
