### ISSUE TITLE
获取当前播放时间

### ISSUE THREAD

**Issue by hfyqsy** [CarGuo/GSYVideoPlayer#1297]
获取不到时间setGSYVideoProgressListener
 mVideo.setGSYVideoProgressListener((progress, secProgress, currentPosition, duration) -> {
            ;
            LogUtil.e(progress  +"  "+ secProgress +"   "+currentPosition +"  "+duration+"  "+
                    mVideo.getGSYVideoManager().getMediaPlayer().getCurrentPosition()+"    "+mVideo. getCurrentPositionWhenPlaying());
        });
![image](https://user-images.githubusercontent.com/23046221/42803014-399eebaa-89d7-11e8-9dd0-25a06a635a5b.png)

**Comment by CarGuo** [comment]
试试exo模式下可不可以，视频的音频编码和视频编码是？有测试url么
