### ISSUE TITLE
自动播放隐藏

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1298]
我的播放器写在了viewpager中,点击界面跳转到viewpager 我直接让他自动播放
调用startPlay之后 播放按钮和底部栏都显示  我想让他不显示怎么办
我重写了一下两个方法
    @Override
    protected void changeUiToPreparingShow() {
        super.changeUiToPreparingShow();
        setViewShowState(mStartButton, INVISIBLE);
        setViewShowState(mBottomContainer, INVISIBLE);
    }

    @Override
    public void startAfterPrepared() {
        super.startAfterPrepared();
        setViewShowState(mStartButton, INVISIBLE);
        setViewShowState(mBottomContainer, INVISIBLE);
    }
但是有的时候好使,有的时候还是会显示 为什么

**Comment by GavinDon** [comment]
我也是在viewpager中使用 ，我在viewpager 的changelistener中监听 获取当前的view 再去进行设置

**Comment by darkrevier** [comment]
@CarGuo onClickUiToggle方法里面我把所有的mBottomContainer地方设置为INVISIBLE 还是有的时候显示有的时候不显示。。

**Comment by darkrevier** [comment]
@CarGuo 我用我的地址 在你的playactivity demo中即使设置了INVISIBLE 也还是显示

**Comment by CarGuo** [comment]
你需要看StandardGSYVideoPlayer下的changexxxui等方法

**Comment by darkrevier** [comment]
是啊 我都设置为INVISIBLE 也不行，除了changeUiToPlayingShow 这个方法没有设置INVISIBLE

**Comment by darkrevier** [comment]
changeUiToPlayingShow这个方法 设置INVISIBLE 就会点击屏幕也不显示了 ,

changeUiToPreparingShow 
changeUiToPlayingBufferingShow
changeUiToNormal
changeUiToCompleteShow都设置了INVISIBLE 都不行
现在我是一点办法都没有

**Comment by CarGuo** [comment]
你直接在源码工程里搜索对应控件，所有使用的地方不就可以了。

**Comment by darkrevier** [comment]
大哥主要涉及到的我全改了 不好使  我说了 有的时候好使有的时候不好使  我要没设置成功也不可能会有不显示的时候啊 
主要是有的时候 会显示 不是每次都显示

**Comment by CarGuo** [comment]
😂这我也不好定位

**Comment by darkrevier** [comment]
@CarGuo 这怎么办啊,问题也找不出来 因为这事被说了一顿 影响用户体验

**Comment by CarGuo** [comment]
目前看来我也没办法，因为我这边也定位不出

**Comment by darkrevier** [comment]
@CarGuo 视频列表  加载不同url的视频  时不时就出现这种情况 ,查都不知道怎么查

**Comment by darkrevier** [comment]
你recyclerView 点击不同item 不同视频url 试一下 跳转到另一个Activity播放  就能测出来  这问题真让我无语

**Comment by darkrevier** [comment]
@CarGuo 大哥 能不能抬一手啊  很急啊 我调了好几天 还是不行 服了

**Comment by CarGuo** [comment]
最近刚好一直忙别的，你把在demo中的重现步骤提供下吧，我调试看看，你需要的是调用startPlayLogic的时候，不显示播放按钮和底部栏？

**Comment by darkrevier** [comment]
@CarGuo 是的 我们是点击列表页跳转到新的Activity中播放 ,我就用了 你的playActivity 实验 结果还是有问题   dev_dark下的playActivity中能复现这个问题

**Comment by CarGuo** [comment]
更新demo

https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/SampleCoverVideo.java


https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/ListVideoActivity.java

主要修改了这些，运行下demo，在ListVideoActivity下我这边测试这样是可以的。

```
/**
     * 下方重载方法，在播放开始不显示底部进度和按键
     */

    protected boolean byStartedClick;

    @Override
    protected void onClickUiToggle() {
        if (mIfCurrentIsFullscreen && mLockCurScreen && mNeedLockFull) {
            setViewShowState(mLockScreen, VISIBLE);
            return;
        }
        byStartedClick = true;
        super.onClickUiToggle();

    }

    @Override
    protected void changeUiToNormal() {
        super.changeUiToNormal();
        byStartedClick = false;
    }

    @Override
    protected void changeUiToPreparingShow() {
        super.changeUiToPreparingShow();
        Debuger.printfLog("Sample changeUiToPreparingShow");
        setViewShowState(mBottomContainer, INVISIBLE);
        setViewShowState(mStartButton, INVISIBLE);
    }

    @Override
    protected void changeUiToPlayingBufferingShow() {
        super.changeUiToPlayingBufferingShow();
        Debuger.printfLog("Sample changeUiToPlayingBufferingShow");
        setViewShowState(mBottomContainer, INVISIBLE);
        setViewShowState(mStartButton, INVISIBLE);
    }

    @Override
    protected void changeUiToPlayingShow() {
        super.changeUiToPlayingShow();
        Debuger.printfLog("Sample changeUiToPlayingShow");
        if (!byStartedClick) {
            setViewShowState(mBottomContainer, INVISIBLE);
            setViewShowState(mStartButton, INVISIBLE);
        }
    }

    @Override
    public void startAfterPrepared() {
        super.startAfterPrepared();
        Debuger.printfLog("Sample startAfterPrepared");
        setViewShowState(mBottomContainer, INVISIBLE);
        setViewShowState(mStartButton, INVISIBLE);
    }
```

**Comment by darkrevier** [comment]
@CarGuo 感谢你修改的这是直接在列表中播放 不显示播放按钮的问题, 当前的这个问题是跳转到新Activity中播放出现的不显示播放按钮 这个问题出现在demo中的PlayActivity中,用的是SampleVideo这个类 我不知道你问题解决没

**Comment by CarGuo** [comment]
你可以把PlayActivity中的SampleVideo替换成SampleCoverVideo试试

**Comment by darkrevier** [comment]
@CarGuo 谢谢大神 目前测试来看没有再出现问题。还有个问题 视频循环播放刚开始也需要隐藏播放按钮和底部控件 这个怎么解决呢

**Comment by CarGuo** [comment]
循环播放这个目前有个问题是，ijk模式下我这边不知道循环结束重新开始····

**Comment by darkrevier** [comment]
@CarGuo 那目前没有解决办法是吗

**Comment by CarGuo** [comment]
如果是单个循环播放，如果你是设置了ijk 的option循环的，那么这样使用应该也是可以的。

**Comment by darkrevier** [comment]
@CarGuo 我用的setLooping方法  出现不隐藏的问题

**Comment by darkrevier** [comment]
@CarGuo 他循环播放的时候走了changeUiToPlayingShow方法  里面都设置不可见的话 也是有问题的

**Comment by CarGuo** [comment]
changeUiToPlayingShow 不是需要通过 byStartedClick 才会显示吗

**Comment by darkrevier** [comment]
@CarGuo 循环的时候走到changeUiToPlayingShow的时候byStartedClick为true他不走下面的方法
  @Override
    protected void changeUiToPlayingShow() {
        super.changeUiToPlayingShow();
        if (!byStartedClick) {
            setViewShowState(mBottomContainer, INVISIBLE);
            setViewShowState(mStartButton, INVISIBLE);
        }
    }

**Comment by CarGuo** [comment]
进度条快进的时候，应该是触发了buffer的回调导致的。

**Comment by darkrevier** [comment]
@CarGuo 不好使
    @Override
    public void onStartTrackingTouch(SeekBar seekBar) {
        byStartedClick = true;
        super.onStartTrackingTouch(seekBar);
    }

    /***
     * 拖动进度条
     */
    @Override
    public void onStopTrackingTouch(SeekBar seekBar){
        byStartedClick = true;
        super.onStopTrackingTouch(seekBar);
    }

**Comment by CarGuo** [comment]
刚刚更新了SampleCoverVideo，你可以看看

**Comment by darkrevier** [comment]
@CarGuo 循环播放还是会显示

**Comment by CarGuo** [comment]
拖动的那个问题应该可以了，循环的话目前还没办法

**Comment by darkrevier** [comment]
@CarGuo 哎 我就是想解决循环显示的问题

**Comment by CarGuo** [comment]
并没有发现太大问题，因为控件显示肯定是与视频状态相关

**Comment by FullGuts** [comment]
自动播放隐藏已解决：新建类继承MyVideoPlayer

class MyVideoPlayer(context: Context, attrs: AttributeSet?) : StandardGSYVideoPlayer(context,attrs){
    override fun hideAllWidget() {
        super.hideAllWidget()
    }


    override fun changeUiToPreparingShow() {
        super.changeUiToPreparingShow()
        hide()
    }

    override fun changeUiToPauseShow() {
        super.changeUiToPauseShow()
        hide()
    }

    override fun changeUiToError() {
        super.changeUiToError()
        hide()
    }

    override fun changeUiToCompleteShow() {
        super.changeUiToCompleteShow()
        hide()
    }

    override fun changeUiToPlayingBufferingShow() {
        super.changeUiToPlayingBufferingShow()
        hide()
    }

    override fun changeUiToPrepareingClear() {
        super.changeUiToPrepareingClear()
        hide()
    }

    override fun changeUiToPlayingClear() {
        super.changeUiToPlayingClear()
        hide()
    }

    override fun changeUiToPauseClear() {
        super.changeUiToPauseClear()
        hide()
    }

    override fun changeUiToPlayingBufferingClear() {
        super.changeUiToPlayingBufferingClear()
        hide()
    }

    override fun changeUiToClear() {
        super.changeUiToClear()
        hide()
    }

    override fun changeUiToCompleteClear() {
        super.changeUiToCompleteClear()
        hide()
    }

    override fun changeUiToPlayingShow() {
        super.changeUiToPlayingShow()
        hide()

    }

    override fun changeUiToNormal() {
        super.changeUiToNormal()
        hide()
    }
    private fun hide() {
        setViewShowState(mTopContainer, INVISIBLE)
        setViewShowState(mBottomContainer, INVISIBLE)
        setViewShowState(mStartButton, INVISIBLE)
        setViewShowState(mLoadingProgressBar, INVISIBLE)
        setViewShowState(mThumbImageViewLayout, INVISIBLE)
        setViewShowState(mBottomProgressBar, INVISIBLE)
        setViewShowState(mLockScreen, GONE)
    }
}
