### ISSUE TITLE
全屏调整亮度问题

### ISSUE THREAD

**Issue by taany6210** [CarGuo/GSYVideoPlayer#13]
第一个单独的例子中，全屏调整亮度，调整到百分百了，然后松手又复位了，未保存亮度状态。再次向上滑动亮度又是从百分之60左右开始的。

**Comment by CarGuo** [comment]
感谢提醒，1.4.1已更新~

**Comment by qq294685358** [comment]
@CarGuo 请问1.4.1什么时候更新

**Comment by CarGuo** [comment]
已经更新了，详细请看主页的版本说明哟！ @qq294685358

**Comment by qq294685358** [comment]
在1.4.0这个版本里，滑动改变亮度有个bug，如果手放在屏幕上压着不动，亮度会一直增加，正常情况应该是手滑动了才会修改亮度

**Comment by CarGuo** [comment]
@qq294685358 你试下1.4.1吧，至于按着不动这个，感觉像是灵敏度问题，因为按着不动还是会有些许的动，我试着按照真的不动，倒是没有变化。

**Comment by qq294685358** [comment]
我刚刚更新了最新的1.4.1   手按着不动，亮度真的会一直增加，而音量就不会，我感觉是你坐标获取的有问题，能再看看吗

**Comment by CarGuo** [comment]
@qq294685358 我这边还真没出现，因为手指按照不动，都不会出现调节亮度啊

**Comment by qq294685358** [comment]
@CarGuo 是这样的，你先向上滑动一点，然后再按着不动，才会出现我说的情况

**Comment by CarGuo** [comment]
@qq294685358 哦哦，这是就是灵敏度的问题，我留着后面做优化！

**Comment by qq294685358** [comment]
但是为什么滑动改变音量就没事呢  我感觉应该是获取坐标的时候要获取相对坐标的问题

**Comment by CarGuo** [comment]
这是因为他们之间的换算不一样，这个问题我记下哈，放着后面修改 @qq294685358

**Comment by CarGuo** [comment]
@qq294685358 感谢你的提醒哈~~(✿◡‿◡)

**Comment by qq294685358** [comment]
没事  因为jiecao没有修改亮度这个功能，但是我的APP里要做这个功能，自己弄了半天也弄不好

**Comment by CarGuo** [comment]
@ @qq294685358  1.4.2刚刚更新了

**Comment by Crystalbye** [comment]
点个赞!1.4.2修复的两个BUG正好是在看的~

**Comment by CarGuo** [comment]
@qq294685358 @Crystalbye 因为某些原因，现在依赖的仓切换到了jitpack.io，如果使用依赖方式的，还请见谅切换，详细看主页下面哟~谢谢哈！
