### ISSUE TITLE
现在的版本不支持系统MediaPlayer了么。

### ISSUE THREAD

**Issue by ZdzCoding** [CarGuo/GSYVideoPlayer#1301]
## 问题描述：
看了项目介绍，基于IJKPlayer（兼容系统MediaPlayer与EXOPlayer2），但是没有发现设置系统MediaPlayer的枚举类型和相关源码，是删除了吗

**Comment by CarGuo** [comment]
支持，GSYVideoManager.instance().setVideoType(this, GSYVideoType.SYSTEMPLAYER);

**Comment by ZdzCoding** [comment]
谢谢，忘记前两天对代码回滚了，所以没找到。
