### ISSUE TITLE
播放rtsp，网络不好的情况下，onPlayError回调中，在横屏状态下重新调用startPlayLogic失效，竖屏状态可以正常重连

### ISSUE THREAD

**Issue by MaryDQ** [CarGuo/GSYVideoPlayer#1303]
我看了源码，startPlayLogic是对竖屏状态下的videoView进行渲染画面，横屏的要现在竖屏状态下点击全屏按钮才可以显示出来。请问有什么好的方法，可以直接在横屏状态下，重新播放出rtsp流

**Comment by CarGuo** [comment]
player.getCurrentPlayer. startPlayLogic

**Comment by MaryDQ** [comment]
thanks
