### ISSUE TITLE
rtsp 怎样取得帧数据

### ISSUE THREAD

**Issue by Leaderpaking** [CarGuo/GSYVideoPlayer#1304]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

rtsp什么方法能够拿到所有的帧数据，可以保存成图片

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
上层并不支持

**Comment by Leaderpaking** [comment]
好的谢谢
