### ISSUE TITLE
How to pause buffering when video playback is paused?

### ISSUE THREAD

**Issue by zhangming170622** [CarGuo/GSYVideoPlayer#1305]
（请务必按照issue模板，修改后提交问题）

## 问题描述：
How to pause buffering when video playback is paused?

## 问题机型/系统：

Sumsung GalaxyS5 Android6.1

## Demo中的复现步骤

All exmaples.

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
set cache false，it will Just buffer the data block that needs to be cached

**Comment by zhangming170622** [comment]
I have already cache to false.Here is code.
mVideoView.setUp(paramURL, false, paramTitle);
Is this right? Sorry, but I want to your help.

**Comment by zhangming170622** [comment]
I paused video play.But buffering is still on. How to pause buffering when pause video play?

**Comment by CarGuo** [comment]
```
list.add(videoOptionModel);
videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
list.add(videoOptionModel);
videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
list.add(videoOptionModel);
videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);

``` 
this may help you .
but buffer can not be stop when pause

**Comment by zhangming170622** [comment]
Thank you for your efforts. Why can't be stop when pause? Now I use "SYSTEMPLAYER GSYVideo Type".

**Comment by CarGuo** [comment]
No such API is provided
