### ISSUE TITLE
能竖屏全屏但是切到横屏 发现被裁剪成正方形了  如何解决

### ISSUE THREAD

**Issue by pricnehao** [CarGuo/GSYVideoPlayer#131]

**Comment by CarGuo** [comment]
是demo中么？有视频源的url吗

**Comment by pricnehao** [comment]
http://7xse1z.com1.z0.glb.clouddn.com/1490952951  这是一个视频连接 旋转之后就变成方形了

**Comment by CarGuo** [comment]
我在demo中测试了下，没有方啊

**Comment by pricnehao** [comment]
横竖屏切换都没有吗？  我用的就是你的demo的  切换屏幕横竖屏大小了被裁剪方了

**Comment by CarGuo** [comment]
可以上传下截图看看吗？

**Comment by pricnehao** [comment]
![image](https://cloud.githubusercontent.com/assets/13235939/24576598/43740ea8-16f1-11e7-9f8c-3a91d21f61ae.png)

**Comment by pricnehao** [comment]
发现 底部直接被裁剪掉了一部分  显示不全

**Comment by pricnehao** [comment]
![image](https://cloud.githubusercontent.com/assets/13235939/24576615/ace35740-16f1-11e7-8f65-bcc0d3073369.png)

**Comment by pricnehao** [comment]
请问您找到什么原因了吗？
