### ISSUE TITLE
播放引擎切换exoplayer，播放视频有画面没有声音

### ISSUE THREAD

**Issue by BingChaoLiu** [CarGuo/GSYVideoPlayer#1310]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放引擎切换exoplayer，播放视频时有画面没有声音，视频的具体信息是  视频编码：mpeg2video  音频编码：mp2或mp3

## 问题机型/系统：
坚果R1,机顶盒hisi mv200（android 7.0）

## log:
07-23 11:22:58.906 3791-3825 I/ExoPlayerImpl: Release 2cc8108 [ExoPlayerLib/2.8.2] [trident, DE106, smartisan, 27] [goog.exo.core]
07-23 11:22:58.914 3791-3791 W/AudioManager: Use of stream types is deprecated for operations other than volume control
    See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
07-23 11:22:58.935 3791-3919 D/SurfaceUtils: disconnecting from surface 0x79aa180010, reason disconnectFromSurface
07-23 11:22:58.969 3791-3825 I/ExoPlayerImpl: Init 7742b73 [ExoPlayerLib/2.8.2] [trident, DE106, smartisan, 27]
07-23 11:22:58.971 3791-3825 D/EventLogger: state [0.00, false, B]
    sourceInfo [periodCount=1, windowCount=1
      period [?]
      window [?, false, false]
    ]
07-23 11:22:58.972 3791-3825 D/EventLogger: loading [true]
07-23 11:23:02.022 3791-3971 W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
07-23 11:23:02.038 3791-3825 D/EventLogger: Tracks [
      Renderer:0 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/256, mimeType=video/mpeg2, res=704x576, supported=YES
        ]
      ]
      Renderer:1 [
07-23 11:23:02.039 3791-3825 D/EventLogger:     Group:0, adaptive_supported=N/A [
          [ ] Track:0, id=1/257, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=NO_UNSUPPORTED_TYPE
        ]
      ]
    ]
07-23 11:23:02.044 3791-3979 E/ACodec: found 1 codecs
07-23 11:23:02.053 3791-3979 I/OMXClient: Treble IOmx obtained
07-23 11:23:02.075 3791-3979 E/ACodec: codec OMX.qcom.video.decoder.mpeg2 selected
07-23 11:23:02.088 3791-3977 D/SurfaceUtils: connecting to surface 0x79aa2c8010, reason connectToSurface
07-23 11:23:02.089 3791-3977 I/MediaCodec: [OMX.qcom.video.decoder.mpeg2] setting surface generation to 3881986
07-23 11:23:02.089 3791-3977 D/SurfaceUtils: disconnecting from surface 0x79aa2c8010, reason connectToSurface(reconnect)
    connecting to surface 0x79aa2c8010, reason connectToSurface(reconnect)
07-23 11:23:02.093 3791-3979 I/ExtendedACodec: setupVideoDecoder()
07-23 11:23:02.101 3791-3979 I/ExtendedACodec: Decoder will be in frame by frame mode
07-23 11:23:02.102 3791-3979 W/ExtendedACodec: Failed to set frame packing format on component
07-23 11:23:02.108 3791-3979 W/ExtendedACodec: getParameter for input extradata failed
07-23 11:23:02.123 3791-3979 D/SurfaceUtils: set up nativeWindow 0x79aa2c8010 for 704x576, color 0x7fa30c06, rotation 0, usage 0x20002900
07-23 11:23:02.131 3791-3979 W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
07-23 11:23:02.135 3791-3979 I/chatty: uid=10190(com.introps.mediashare) CodecLooper identical 2 lines
07-23 11:23:02.136 3791-3979 W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
07-23 11:23:02.148 3791-3979 D/SurfaceUtils: set up nativeWindow 0x79aa2c8010 for 704x576, color 0x7fa30c06, rotation 0, usage 0x20002900
07-23 11:23:02.420 3791-3979 W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
07-23 11:23:03.185 3791-3979 I/chatty: uid=10190(com.introps.mediashare) CodecLooper identical 3 lines
07-23 11:23:03.188 3791-3979 W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
07-23 11:23:03.963 3791-3979 W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000

**Comment by BingChaoLiu** [comment]
看了一部分issues，mp2的是不支持的吗，还是说要重新编译so？在exoplayer的文档中看到，ffmpeg的扩展格式配置
MP1, MP2, MP3            –enable-decoder=mp3
我使用的是时候依赖的是：
    implementation 'com.shuyu:gsyVideoPlayer-java:5.0.1'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:5.0.1'

**Comment by CarGuo** [comment]
exo的ffmpeg的扩展没有集成到项目里。

**Comment by BingChaoLiu** [comment]
请教一下，如果需要集成的话麻烦吗，之前用的是GSY中默认的ijk，但是视频起播时间太慢了，就换成了exo

**Comment by CarGuo** [comment]
exo的ffmpeg可能会和ijk的ffmpeg产生冲突，你可以看看这个，这样可以拓展你你想要的，增加ffmpeg的source https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exo

**Comment by BingChaoLiu** [comment]
你的意思是不切换引擎，使用默认的，继承的方式扩展出来，使用exo吗，新手一个不知道理解的对不对

**Comment by CarGuo** [comment]
我的意思是，你可以参考这个链接去自定义exoplayermanager用到里面去，然后你可以增加ffmpeg的支持
