### ISSUE TITLE
viewpage 嵌套多个同类型fragment

### ISSUE THREAD

**Issue by huyue05** [CarGuo/GSYVideoPlayer#1314]
## 问题描述：
viewpage内嵌套多个页面，每个页面都有视频。
只有第一个fragment页面的视频可以播放 第二个fragment的页面和其他fragment的页面都无法播放
## 问题机型/系统：
所有都会出现这个问题
##报错信息
W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder

E/onchange: CURRENT_STATE_PREPAREING

E/IJKMEDIA:  http://resource.51xiaodou.com/default/o_1ci8q2ha11rdo7a1qt519upjt19.mp4  : No such file or directory

**Comment by CarGuo** [comment]
这个不属于库的问题

**Comment by huyue05** [comment]
那能告诉我是什么原因引起的吗

**Comment by CarGuo** [comment]
这个只能你自己调适看看
