### ISSUE TITLE
播放rtsp视频流无声音，并且暂停恢复播放进度不跟进

### ISSUE THREAD

**Issue by MeowStone** [CarGuo/GSYVideoPlayer#1315]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

添加了这些依赖
```
    compile ('com.shuyu:gsyVideoPlayer-java:5.0.0-beta')
    compile 'com.shuyu:gsyVideoPlayer-ex_so:5.0.0-beta'
```

播放网络上公开的rtsp流有画面有声音，而且暂停，恢复播放是重新加载，进度不滞后
播放海康威视的rtsp有画面无声音（用pc客户端播放有声音），暂停后恢复播放是从暂停的时间节点开始播放的。

**Comment by CarGuo** [comment]
请确定音频编码

**Comment by MeowStone** [comment]
@CarGuo 同事用 VCL移动端 播放相同的rtsp流有声音

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh  这是支持的协议，视频编码，音频编码，如果是打包文件内没有的音频编码，当前so是不会有声音的。
