### ISSUE TITLE
切换Url播放出错，急急急！

### ISSUE THREAD

**Issue by zt80hou** [CarGuo/GSYVideoPlayer#1317]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

demo 点击输入URL进入界面，切换Url之后播放出错

## 问题机型/系统：

真机华为荣耀7 PLK-UL00  Android6.0

## Demo中的复现步骤

Demo 点击输入URL进入界面
    地址1： http://cdn.linker.cc/SDYT/2018/02/14/YdASzTFGbs.mp4
    地址2： https://cdn.linker.cc/SDYT/2018/07/11/yYGKkf4zME.mp4
先播地址1，再播放地址2，地址2报错如下:
07-25 15:41:58.261 31442-32458/com.example.gsyvideoplayer E/IJKMEDIA: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
07-25 15:41:58.264 31442-32458/com.example.gsyvideoplayer E/IJKMEDIA: https://cdn.linker.cc/SDYT/2018/07/11/yYGKkf4zME.mp4: I/O error

退出App 重进

先播地址2，再播地址1， 地址1报错如下:
07-25 15:44:39.107 32682-1182/com.example.gsyvideoplayer W/IJKMEDIA: HTTP error 400 Bad Request
07-25 15:44:39.108 32682-1182/com.example.gsyvideoplayer E/IJKMEDIA: http://cdn.linker.cc/SDYT/2018/02/14/YdASzTFGbs.mp4: Server returned 400 Bad Request

因为项目中有类似这个场景，切换视频播放，跪求大神指导！

**Comment by CarGuo** [comment]
请看问题集锦
