### ISSUE TITLE
支持设置自定义IjkLibLoader以支持动态加载so包

### ISSUE THREAD

**Issue by PureDark** [CarGuo/GSYVideoPlayer#132]
目前`GSYVideoManager`实例化时都是使用`IjkMediaPlayer`的默认实例化方法
```java
mediaPlayer = new IjkMediaPlayer();
```

而IjkMediaPlayer是有指定IjkLibLoader的构造函数的
```java
    public IjkMediaPlayer(IjkLibLoader libLoader) {
        initPlayer(libLoader);
    }
```
现在我想在apk中排除掉体积很大的so包，改为下载到app的数据文件夹里，然后动态加载，但是没有找到可以在不hack这个库的源码的情况下更改提供给`IjkMediaPlayer`的`IjkLibLoader`的方法

EDIT:
唔，其实也不麻烦，给`GSYVideoManager`或者`GSYVideoPlayer`新增个`setIjkLibLoader`的方法，我待会提交个PR吧

**Comment by CarGuo** [comment]
嗯嗯

**Comment by CarGuo** [comment]
欢迎欢迎

**Comment by PureDark** [comment]
#133

**Comment by CarGuo** [comment]
已经合并
