### ISSUE TITLE
更新到5.0.1后concat不支持了

### ISSUE THREAD

**Issue by Average77** [CarGuo/GSYVideoPlayer#1320]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

原本用的4.1.1版本，换成5.0.1后，之前的concat不能播放了，原本4.1.1是可以的，没有动代码，就换了一下依赖。

## 问题log（如果有）

```


07-27 14:37:35.583 9912-10105/com.xingyuyou.xingyuyou D/J4A: J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.IMediaDataSource' loaded
07-27 14:37:35.583 9912-10105/com.xingyuyou.xingyuyou D/J4A: J4ALoader: OK: 'tv.danmaku.ijk.media.player.misc.IAndroidIO' loaded
07-27 14:37:35.583 9912-10105/com.xingyuyou.xingyuyou D/J4A: J4ALoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
07-27 14:37:35.586 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: ijkmediaplayer version : k0.8.8
07-27 14:37:35.591 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: IjkMediaPlayer_native_init
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: IjkMediaPlayer_native_setup
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou I/IJKMEDIA: av_version_info: ff3.4--ijk0.8.7--20180103--001
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou I/IJKMEDIA: ijk_version_info: k0.8.8
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: ffpipeline_create_from_android()
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: ijkmp_set_inject_opaque(0x34ea)
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: ijkmp_set_inject_opaque()=void
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x34ea)
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
07-27 14:37:35.592 9912-10105/com.xingyuyou.xingyuyou D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
07-27 14:37:35.593 9912-10105/com.xingyuyou.xingyuyou W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)


```

**Comment by Average77** [comment]
4.1.2就不行了，IjkPlayerManager.java:82   
  if (uri.getScheme().equals(ContentResolver.SCHEME_ANDROID_RESOURCE))  这一行报的错

**Comment by Average77** [comment]
so库是支持的，我没换so库，是因为代码报错的原因，具体是什么错误log没有打，只打了那一行。
W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
应该是 1.ffconcat 的本地地址不是url的原因吧

**Comment by CarGuo** [comment]
可以具体看看什么问题导致的，断点看看

**Comment by Average77** [comment]
07-30 10:58:11.963 10888-11181/com.xingyuyou.xingyuyou W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
07-30 10:58:11.963 10888-11181/com.xingyuyou.xingyuyou W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
07-30 10:58:11.963 10888-11181/com.xingyuyou.xingyuyou W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:597)
07-30 10:58:11.963 10888-11181/com.xingyuyou.xingyuyou W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
07-30 10:58:11.963 10888-11181/com.xingyuyou.xingyuyou W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:561)
07-30 10:58:11.964 10888-11181/com.xingyuyou.xingyuyou W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
07-30 10:58:11.964 10888-11181/com.xingyuyou.xingyuyou W/System.err:     at android.os.Looper.loop(Looper.java:164)
07-30 10:58:11.964 10888-11181/com.xingyuyou.xingyuyou W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)

 if (!TextUtils.isEmpty(url)) {
                    Uri uri = Uri.parse(url);
                    if (uri.getScheme().equals(ContentResolver.SCHEME_ANDROID_RESOURCE)) {
                        RawDataSourceProvider rawDataSourceProvider = RawDataSourceProvider.create(context, uri);
                        mediaPlayer.setDataSource(rawDataSourceProvider);
                    } else {
                        mediaPlayer.setDataSource(url, gsyModel.getMapHeadData());
                    }
                } else {
                    mediaPlayer.setDataSource(url, gsyModel.getMapHeadData());
                }

url = /storage/emulated/0/exter_test/1.ffconcat
uri.getScheme="NOT CACHED"
![fbe82yz h4x u m1r 3s9](https://user-images.githubusercontent.com/28084588/43375522-328d2370-93e8-11e8-9df1-e1e8337868ba.png)

**Comment by Average77** [comment]
5.0.1版本

**Comment by CarGuo** [comment]
你的url要file协议开头，区如file:// +路径

**Comment by Average77** [comment]
可以了QAQ，为什么之前没加也能播呢，4.1.1版本的

**Comment by CarGuo** [comment]
这个是为了兼容raw下的播放的时候改的，哈哈哈····

**Comment by renwfy** [comment]
@Average77 ,你的播放是怎么设置的，除了片接本地的  .ffconcat文件，播放还要设置哪些？

直接 这样好像不行  videoPlayer.setUp("file:///android_asset/aa.ffconcat",false,"测试");

**Comment by Average77** [comment]
还要设置   
   List<VideoOptionModel> list1 = new ArrayList<>();
        VideoOptionModel videoOptionModel2 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "safe", 0);
        VideoOptionModel videoOptionModel3 =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto");
        list1.add(videoOptionModel2);
        list1.add(videoOptionModel3);
        GSYVideoManager.instance().setOptionModelList(list1);
@renwfy 试一下看看呢

**Comment by renwfy** [comment]
@Average77 ,你现在 .ffconcat文件放哪里呢？
我现在放 assets 下面，提示文件找不到。


List list1 = new ArrayList();
VideoOptionModel videoOptionModel2 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "safe", 0);
VideoOptionModel videoOptionModel3 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto");
list1.add(videoOptionModel2);
list1.add(videoOptionModel3);
GSYVideoManager.instance().setOptionModelList(list1);

videoPlayer =  (StandardGSYVideoPlayer)findViewById(R.id.video_player);
videoPlayer.setUp("file:///android_asset/aa.ffconcat",false,"测试");

**Comment by Average77** [comment]
放sd卡昂~ @renwfy

**Comment by renwfy** [comment]
@Average77 ，再麻烦下，那url路径怎么拼呢，不要要以 file:/// 开始吗？

**Comment by Average77** [comment]
对啊，你拼一下咯，ffconcatPath=TextUtils.concat("file://",ffconcatPath).toString(); @renwfy

**Comment by Average77** [comment]
ffconcatPath就是ffconcat文件的本地路径 @renwfy

**Comment by renwfy** [comment]
@Average77 ，感谢！！，可以了。
