### ISSUE TITLE
如何让点击封面播放时,封面和视频画面无缝衔接,现在总有闪烁和黑屏问题？？？

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1321]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by darkrevier** [comment]
@CarGuo 偶尔出现播放按钮问题 在dev_dark分支下

**Comment by CarGuo** [comment]
看起来和 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/SampleCoverVideo.java 差不多？？？？

 目前demo中我这边测试  https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/ListVideoActivity.java 使用了 SampleCoverVideo.java，可以正常切换

**Comment by darkrevier** [comment]
@CarGuo  dev_dark分支下 PlayActivity中 是测试播放时显示播放按钮和底部控制栏的问题  多试几次就会出现

**Comment by CarGuo** [comment]
最新demo中的ListVideoActivity，使用了SampleCoverVideo的在你那边会有问题不？
