### ISSUE TITLE
投屏时播放器只显示控制控件（如声音，进度），不显示画面

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#1323]
投屏已实现，现在是自己定义了一套界面，感觉有点浪费。
可否在原播放器的基础上显示控制控件（如声音，进度，标题），不显示画面，声音。
进度跟着投屏视频走，就和优酷的投屏效果差不多。

**Comment by CarGuo** [comment]
你重载getLayoutId不就好了
