### ISSUE TITLE
如果我使用m3u8的格式来做一个视频监控  这个项目支持吗

### ISSUE THREAD

**Issue by hy20160705** [CarGuo/GSYVideoPlayer#1325]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
hls直播咯？支持

**Comment by hy20160705** [comment]
那我该怎么入手呀 我尝试将DetailExoListPlayer中的流地址改为我的“http://alhlsgw.lechange.com:9001/LCO/4E0688FPBQ1C28D/0/0/20180709115705/dev_20180709115705_7are6zi1scgmpkef.m3u8” 虽然播放出来了 但是这种直播类型的流没有进度 该怎么处理

**Comment by CarGuo** [comment]
你可以继承后，重载getLayoutId

**Comment by CarGuo** [comment]
ijkplayer为内核的也有ios版本的，你可以找找，不过so库和这边的的不大一样。

**Comment by hy20160705** [comment]
好的  有问题再来问你  哈哈哈(ಡωಡ)hiahiahia
