### ISSUE TITLE
8.0 Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by protectedMan** [CarGuo/GSYVideoPlayer#1327]
[demo对8.0有兼容问题兼容性。]
演示的视频链接
https://su.bcebos.com/v1/lezhu-test/system/version/QQ20180801-103519-HD.mp4

**Comment by CarGuo** [comment]
这是activity设置了固定方向，并且透明才会的问题吧？库里面有页面？？？

**Comment by protectedMan** [comment]
对啊，说的就是demo的问题。 我尝试了网上的解决方案，都没有解决掉。。。。

**Comment by protectedMan** [comment]
activity 的android:screenOrientation="portrait"移除后仍然报错。
可能是因为在代码里（com.shuyu.gsyvideoplayer.utils.OrientationUtils）设置了方向
<img width="707" alt="image" src="https://user-images.githubusercontent.com/17565737/43499682-4af1484a-957f-11e8-9ad3-67558b95352c.png">

**Comment by CarGuo** [comment]
demo也是27 sdk编译的，没出现这个问题

**Comment by protectedMan** [comment]
demo中我是在横屏状态下进入的playactivity才报错（而不是进入后再竖屏），如果竖屏进入后无论怎么变换屏幕状态都没有问题。

**Comment by CarGuo** [comment]
横屏状态下进入的playactivity，然后又需要自动旋转？？
