### ISSUE TITLE
播放视频，点击进度条进行定位，会出现定位不准的情况

### ISSUE THREAD

**Issue by diewu0421** [CarGuo/GSYVideoPlayer#1330]
问题：
播放视频，点击进度条进行定位，会出现定位不准的情况

问题机型：
锤子坚果pro2　Android 7.1

Demo中的复现步骤:
简单播放----> 简单直接播放--->然后点击进度条，
比如刚开始定位到1:55的位置，然后又自动跳到1:51了
PS:在Demo中，这个问题还会出现在当点击home键，然后又回到APP时，明明点击home之前是1:55秒，然后APP回到前台，定位又跳到了1:51。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md  
切换到exopalyer模式或者尝试下发配置

```
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by diewu0421** [comment]
感谢作者!

**Comment by HancockY** [comment]
可以的
