### ISSUE TITLE
mac上ijkplayer编译会报错，大神能给个Mac的编译流程么（支持https的）

### ISSUE THREAD

**Issue by Cloundhub** [CarGuo/GSYVideoPlayer#1331]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
mac上ijkplayer编译会报错，大神能给个Mac的编译流程么（支持https的）

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
先clean干净，
然后 https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh 用这个脚本
