### ISSUE TITLE
开始播放  暂停播放  继续播放动画修改

### ISSUE THREAD

**Issue by CatyVon** [CarGuo/GSYVideoPlayer#1332]
## 问题描述：

请问调用了seekto(long position)方法后，播放器的那个开始播放动画如何隐藏或者进行修改？
目前项目是需要重复播放某一时间段的内容，使用Timer定时执行seekto（）解决了，但每次seekto()调用后，视频定位到指定位置播放的时候，开始播放按钮以及动画会出现，占了播放窗口，因为某些时间段的视频很短，所以需要隐藏这个按钮。

## 问题机型/系统：
真机 小米mix2

**Comment by CarGuo** [comment]
继承后重载getLayoutId就好了。

**Comment by CatyVon** [comment]
是重写一个播放器类  继承GSYVideoPlayer  然后重新加载自己的layout布局么？ 仅仅隐藏那个播放按钮  应该不用这么麻烦吧？ 现在还不是很明白GSYVideoPlayer  所以写起来估计会有问题  麻烦大佬大概说一下  万分感谢

发送自 Windows 10 版邮件应用

发件人: Shuyu Guo
发送时间: 2018年8月1日 16:59
收件人: CarGuo/GSYVideoPlayer
抄送: Monce; Author
主题: Re: [CarGuo/GSYVideoPlayer] 开始播放 暂停播放 继续播放动画修改 (#1332)

继承后重载getLayoutId就好了。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/LandLayoutVideo.java    你看demo
