### ISSUE TITLE
视频播放到一半，视频加载等待，再播放从头开始了，这是什么情况？

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1334]

**Comment by Average77** [comment]
是不是在开始播放的回调里调用了seekto？

**Comment by 1687740344** [comment]
5.0.2好像也是这样！这是出现问题时的日志信息，华为平板BAH-W09，安卓版本7.0，EMUI版本5.1.1
    incrNetBadCounter mOnAppSuckTime mOnAppSuckTime=0 deta=-1
    RecoveredNetWork Traffic , so mOnAppSuckTime=0 modify -1
08-09 16:19:30.288 678-678/? E/Thermal-daemon: [ap] temp_new :42  temp_old :43
08-09 16:19:30.289 678-678/? E/Thermal-daemon: Report temperature: [ap] temp :42  report_threshold:1
08-09 16:19:31.241 4622-13188/? E/PushLog2848: [SocketRead_16:13:21-45506]connect occurs :com.huawei.android.pushagent.datatype.PushException: java.net.SocketException: Socket closed(android/null:-1)
    com.huawei.android.pushagent.datatype.PushException: java.net.SocketException: Socket closed
        at z.bp(Unknown Source)
        at com.huawei.android.pushagent.model.channel.entity.SocketReadThread.run(Unknown Source)
     Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at java.net.SocketInputStream.read(SocketInputStream.java:206)
        at ab.read(Unknown Source)
        at z.bp(Unknown Source) 
        at com.huawei.android.pushagent.model.channel.entity.SocketReadThread.run(Unknown Source) 
08-09 16:19:31.349 7809-7809/? E/wpa_supp: RSSI=-55;LINKSPEED=150;NOISE=9999;FREQUENCY=2412;
08-09 16:19:31.351 1652-2032/? E/WifiConfigManager: updateConfiguration freq=2412 BSSID=78:44:**:**:5d:60 RSSI=-54 "YUN"WPA_PSK

**Comment by CarGuo** [comment]
@1687740344 你这个log是华为推送接口的socket吧

**Comment by 1687740344** [comment]
8-09 16:36:12.502 14462-14944/com.xf.activity E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
08-09 16:36:12.651 14462-14944/com.xf.activity E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xc4f7d280)
08-09 16:36:12.653 14462-14944/com.xf.activity E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xc4f66e40)
08-09 16:36:12.655 14462-14944/com.xf.activity E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb03fc680)
08-09 16:37:04.746 14462-15561/codfdm.dfdxf.activity E/IJKMEDIA: Option ijkiomanager not found.

**Comment by 1687740344** [comment]
这个也是刚刚问题出现时打印的

**Comment by 1687740344** [comment]
日志信息太多了，看看这些是否有用
--------------------------------------------------------------------------------------------
08-09 16:08:16.504 1652-1751/? D/FingerprintActionsListener: touchDownIsValid MotionEvent.ACTION_DOWN 
    touchDownIsValidLazyMode = false  touchDownIsValidHiBoard = false
08-09 16:08:16.569 1652-2011/? D/InputReader: processEventsLocked code=330
08-09 16:08:16.573 18918-18918/com.xf.activity D/---sampleListener---: onClickStartError
08-09 16:08:16.574 18918-19528/com.xf.activity D/IJKMEDIA: IjkMediaPlayer_release
    IjkMediaPlayer_setVolume
08-09 16:08:16.575 18918-18918/com.xf.activity I/AudioManager: abandonAudioFocus
08-09 16:08:16.575 1652-26937/? I/MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10192/18918 clientId=android.media.AudioManager@5c302bacom.shuyu.gsyvideoplayer.video.base.GSYVideoView$1@d07e157
08-09 16:08:16.578 18918-18918/com.xf.activity D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
08-09 16:08:16.581 18918-18918/com.xf.activity I/AudioManager: abandonAudioFocus
08-09 16:08:16.582 1652-2539/? I/MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10192/18918 clientId=android.media.AudioManager@5c302bacom.shuyu.gsyvideoplayer.video.base.GSYVideoView$1@d07e157
08-09 16:08:16.583 2522-2639/? I/ScenarioService: check surface view pkg: com.xf.activity
08-09 16:08:16.585 1652-32040/? I/MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10192/18918 clientId=android.media.AudioManager@5c302bacom.shuyu.gsyvideoplayer.video.base.GSYVideoView$1@d07e157 req=2 flags=0x0
08-09 16:08:16.585 2522-2639/? I/ScenarioService: ID_VIDEO_END : 
------------------------------------------------------------------------------------

**Comment by CarGuo** [comment]
log上看像是ffmpeg和源的兼容问题，可以看看切换到exo模式下试试。GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);

**Comment by 1687740344** [comment]
是只需要直接在BaseApplication设置就可以了吗？？刚刚试了这种方式也是会出现这种情况

**Comment by CarGuo** [comment]
是的，如果这种方式也会出现，那么说明medicodec和ffmpeg下都会有问题，只能说是源的问题

**Comment by 1687740344** [comment]
请问那需要什么的源才能更好搭配呢？好比，格式mp4，avi等，或服务器类型呢？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md

**Comment by 1687740344** [comment]
Thank you
