### ISSUE TITLE
播放高码率视频的时候视频卡顿，结束不及时

### ISSUE THREAD

**Issue by LittleLiByte** [CarGuo/GSYVideoPlayer#1335]
## 问题描述：

用手机拍摄的视频（比如iPhone），播放高码率视频的时候视频画面卡顿，结束不及时，比如一个7s的视频，需要播放14，15s才会结束

## 问题机型/系统：
应该所有的机型都会出现，低端手机更加明显。
我手里的手机包括
三星 note5 Android7.0
魅蓝  5s Android6.0

## Demo中的复现步骤
我测试的视频放到网盘了，视频7s，大小40M
https://cloud.189.cn/t/MJ7Zv26RNBVj
（访问码：3052）

**Comment by LittleLiByte** [comment]
@CarGuo 感谢及时回复！🙏
再问个小问题，framedrop选项是一直设置还是检测到码率太高才设置？

**Comment by CarGuo** [comment]
这个看你需求，如果懒的话，可以一直设置
