### ISSUE TITLE
recycleview全屏返回item自动停止播放

### ISSUE THREAD

**Issue by yuwoquan** [CarGuo/GSYVideoPlayer#1338]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
当我在item点击全屏按钮，返回的时候无法回到item播放，回停止播放。

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0
小米4 小米5S
## Demo中的复现步骤

我参照ListNormalAdapter的代码设置

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
demo中怎么复现

**Comment by yuwoquan** [comment]
应该是我自己用的自定义recycleview控件导致的。我用系统的recycleview不会出现这个情况。我自己排查一下吧。感谢
