### ISSUE TITLE
TimerThread 内存泄漏了

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#1340]
com.shuyu:GSYVideoPlayer:5.0.1

![image](https://user-images.githubusercontent.com/17804057/43693301-b43703ba-995f-11e8-9ea1-7a308e0c0d09.png)

![image](https://user-images.githubusercontent.com/17804057/43693340-eb15a404-995f-11e8-98fe-8e80d711811c.png)

**Comment by CarGuo** [comment]
mDismissControlViewTimer 有对应的 cancelDismissControlViewTimer，目前没看出哪里内存泄漏了，能否提供详细信息，是在哪种情况下销毁时没有调用 cancelDismissControlViewTimer

**Comment by CarGuo** [comment]
@Wangct23 可以的话，还请提供下详细的泄漏情况，默认各个位置都会调用cancel，并且在view销毁时，也会判断调用多一次
```
  @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        cancelProgressTimer();
        cancelDismissControlViewTimer();
    }

```
