### ISSUE TITLE
解析视频  h264格式的可以正常播放，mpeg4的只有声音没有画面

### ISSUE THREAD

**Issue by 274875921** [CarGuo/GSYVideoPlayer#1342]
Video: h264, 1 reference frame (avc1 / 0x31637661), yuv420p(tv, bt709, left), 1920x1080 (1920x1088), 0/1, 17152 kb/s 这种log的视频 可以播放

Video: mpeg4, 1 reference frame (mp4v / 0x7634706D), none, 1280x720 (0x0), 0/1, 2038 kb/s 这样的就只显示声音没有画面

**Comment by CarGuo** [comment]
使用exso依赖
