### ISSUE TITLE
android 7.0 全屏onBackPressed()锁定竖屏全屏状态，无法退出界面。但是在6.0能够正常退出来。没有任何问题

### ISSUE THREAD

**Issue by yuwoquan** [CarGuo/GSYVideoPlayer#1346]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

android 7.0 全屏锁定竖屏全屏状态，无法退出界面。但是在6.0能够正常退出来。没有任何问题.
代码都基本参照demo。

## 问题机型/系统：

Android 7.0 小米5S
Android 6.0 小米4

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
最新demo里哪个页面复现。

**Comment by yuwoquan** [comment]
没有在demo里，只是我参照demo写在自己项目中

**Comment by CarGuo** [comment]
如果demo复现我才能定位问题

**Comment by yuwoquan** [comment]
恩，我了解。我尝试一下去解决一下，谢谢啦

**Comment by yuwoquan** [comment]
我在7.0系统onAutoComplete也就是播放完后调用onBackFullscreen()，是无法退出全屏，但是6.0确实不存在这个问题。能完美的退出全屏。然后我在clearFullscreenLayout()退出window层播放全屏效果。看到你之前有fix bug过。我录制了视频录制：
http://bmob-cdn-18241.b0.upaiyun.com/2018/08/16/0ae3eafb4004e7a5803780d180e54dda.mp4
------------
http://bmob-cdn-18241.b0.upaiyun.com/2018/08/16/b3eacc5e407a6ecb803bffba5612eef9.mp4

**Comment by CarGuo** [comment]
其实主要是demo怎么复现
