### ISSUE TITLE
全屏切换，出现明显的卡顿

### ISSUE THREAD

**Issue by missu263** [CarGuo/GSYVideoPlayer#1347]
当前界面为ViewPager+Fragment，viewpager设置了offsetlimit = 5 
fragment中为recyclerView的视频列表
在列表视频的播放过程中，进行全屏切换，界面会出现明显的卡顿
拜读了源代码，发现全屏的实现为新建一个GsyVideoplayer的实例，clone当前GsyVideoplayer的一些参数，然后通过addView的方式放到当前activity的window中进行播放的显示，然后还会进行屏幕旋转的操作
此过程在我当前activity的页面结构上会出现1～2秒的卡顿
请问为什么当初设计的时候为什么不考虑，直接把列表中播放的GsyVideoplayer实例add到window中去呢，而是选择新建一个呢？这样会不会省下了新建的耗时？？
请大佬问我该怎么解决全屏切换带来的卡顿呢？

**Comment by CarGuo** [comment]
这个demo中怎么复现？
你是否有配置了activity的manifest。

是不是屏幕旋转导致了你的ui执行了重绘制。

这个切换并不会耗时，基本感觉不出来。


还有你说的这种方式也是有的，比如demo带2的页面的列表。

**Comment by missu263** [comment]
已经确认了activity的manifest配置了
Demo中切换全屏，未出现卡顿的情况
会不会跟我的页面结构有关，我是ViewPager+Fragment , Fragment为recyclerView的视频列表

**Comment by CarGuo** [comment]
首先当前横屏activity下发是否会有activity，如果有，配置上manifest。

第二，你可以打印下viewPager、fragment、recyclerView，是不是在横屏时触发了重绘

比如viewPager的回调、fragment的onViewCreate、recyclerView的onBind等。如果堆栈下还有activity，可以也打印下，看看情况。
