### ISSUE TITLE
m3u8边播放边缓存能不能实现？

### ISSUE THREAD

**Issue by 995518790** [CarGuo/GSYVideoPlayer#1348]

**Comment by CarGuo** [comment]
可以，GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);模式下的cache支持

**Comment by 995518790** [comment]
感谢大佬

**Comment by 995518790** [comment]
GSYVideoType.IJKEXOPLAYER2加上去不能播放了，本来用默认能播放。
讲一下具体怎么搞

**Comment by CarGuo** [comment]
报的什么错

**Comment by 995518790** [comment]
08-10 11:00:09.387 1011-1327/? E/FingerSense.TouchProcessing: Touch coordinates (781, 1582)
08-10 11:00:09.612 462-462/? E/SELinux: avc:  denied  { find } for interface=vendor.huawei.hardware.hwsched::ISched pid=6089 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:hwsched_hwservice:s0 tclass=hwservice_manager permissive=0
08-10 11:00:09.613 6089-6432/com.sx.live E/BufferQueueProducer: [] [hwsched]Can not get hwsched service
08-10 11:00:09.642 1778-2302/? E/HsmCoreServiceImpl: onTransact in code is: 103
08-10 11:00:10.034 462-462/? E/SELinux: avc:  denied  { find } for interface=vendor.huawei.hardware.hwsched::ISched pid=6089 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:hwsched_hwservice:s0 tclass=hwservice_manager permissive=0
08-10 11:00:10.035 6089-6445/com.sx.live E/BufferQueueProducer: [] [hwsched]Can not get hwsched service
08-10 11:00:10.038 669-2018/? E/VDEC: [get_extension_index], "OMX.google.android.index.storeMetaDataInBuffers" not implemented
    [get_extension_index], "OMX.google.android.index.storeANWBufferInMetadata" not implemented
    [get_extension_index], "OMX.google.android.index.configureVideoTunnelMode" not implemented
    [set_parameter], allocate native buffer: Bad port index 1
08-10 11:00:10.038 669-2018/? E/OMXNodeInstance: setParameter(0xef9513c0:hisi.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f000008): Output:1 en=0) ERROR: BadPortIndex(0x8000101b)
08-10 11:00:10.038 669-2018/? E/VDEC: [get_extension_index], "OMX.google.android.index.storeANWBufferInMetadata" not implemented
    [get_extension_index], "OMX.google.android.index.storeMetaDataInBuffers" not implemented
08-10 11:00:10.038 669-2018/? E/OMXNodeInstance: getExtensionIndex(0xef9513c0:hisi.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
08-10 11:00:10.039 6089-6441/com.sx.live E/ACodec: [OMX.hisi.video.decoder.avc] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
08-10 11:00:10.039 669-2018/? E/VDEC: [set_parameter], allocate native buffer: Bad port index 1
08-10 11:00:10.039 669-2018/? E/OMXNodeInstance: setParameter(0xef9513c0:hisi.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f000008): Output:1 en=0) ERROR: BadPortIndex(0x8000101b)
08-10 11:00:10.039 669-2018/? E/VDEC: [get_extension_index], "OMX.google.android.index.storeANWBufferInMetadata" not implemented
    [get_extension_index], "OMX.google.android.index.storeMetaDataInBuffers" not implemented
08-10 11:00:10.039 669-2018/? E/OMXNodeInstance: getExtensionIndex(0xef9513c0:hisi.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
08-10 11:00:10.041 669-2018/? E/VDEC: [get_extension_index], "OMX.google.android.index.describeColorAspects" not implemented
    [get_extension_index], "OMX.google.android.index.describeHDRStaticInfo" not implemented
08-10 11:00:10.042 669-2018/? E/OMXNodeInstance: setConfig(0xef9513c0:hisi.decoder.avc, ConfigPriority(0x6f800002)) ERROR: BadParameter(0x80001005)
08-10 11:00:10.042 669-2018/? E/OMXNodeInstance: getConfig(0xef9513c0:hisi.decoder.avc, ConfigAndroidVendorExtension(0x6f100004)) ERROR: BadParameter(0x80001005)
08-10 11:00:10.067 669-2018/? E/VDEC: [get_extension_index], "OMX.google.android.index.AndroidNativeBufferConsumerUsage" not implemented
08-10 11:00:10.072 1011-2979/? E/WindowManager: win=Window{d657c19 u0 com.sx.live/com.sx.live.ui.activity.MainActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false
08-10 11:00:10.093 669-813/? E/OMXNodeInstance: setConfig(0xef951000:google.aac.decoder, ??(0x6f700006)) ERROR: Undefined(0x80001001)
08-10 11:00:10.095 669-813/? E/OMXNodeInstance: setConfig(0xef951000:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
08-10 11:00:10.096 669-2018/? E/OMXNodeInstance: getConfig(0xef951000:google.aac.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
08-10 11:00:10.098 669-2018/? E/VDEC: [get_extension_index], "OMX.google.android.index.AndroidNativeBufferConsumerUsage" not implemented
08-10 11:00:10.099 669-2018/? E/OMXNodeInstance: setParameter(0xef9513c0:hisi.decoder.avc, ParamPortDefinition(0x2000001)) ERROR: Undefined(0x80001001)
08-10 11:00:10.125 654-883/? E/stereoWidening_frame: output device is not A2DP
08-10 11:00:10.127 654-883/? E/stereoWidening_frame: output device is not A2DP
08-10 11:00:10.130 654-883/? E/stereoWidening_frame: output device is not A2DP
08-10 11:00:10.183 603-603/? E/WifiHAL: enter wifi_get_link_stats
08-10 11:00:10.186 668-668/? E/wificond: Failed to get NL80211_RATE_INFO_NOISE
    Failed to get NL80211_RATE_INFO_SNR
    Failed to get NL80211_STA_INFO_CNAHLOAD
08-10 11:00:10.187 1011-1355/? E/WificondControl: Noise: 0, Snr: -1, Chload: -1
08-10 11:00:10.187 1011-1355/? E/HwWifiStatStore: updateLinkSpeed  linkSpeed =54 lastSpdLev=1 index=2
08-10 11:00:10.188 1011-1355/? E/HwWifiStatStore: updateLinkSpeedTxRxInfo  lastSpdLev=1 16388 230 356075 252
08-10 11:00:10.538 1889-2101/? E/HSM: NatTrafficNotifyService:imsi is null, so return
08-10 11:00:11.452 654-883/? E/stereoWidening_frame: output device is not A2DP
08-10 11:00:11.458 1778-2302/? E/HsmCoreServiceImpl: onTransact in code is: 102
08-10 11:00:13.109 1011-1532/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
08-10 11:00:13.196 603-603/? E/WifiHAL: enter wifi_get_link_stats
08-10 11:00:13.199 668-668/? E/wificond: Failed to get NL80211_RATE_INFO_NOISE
    Failed to get NL80211_RATE_INFO_SNR
    Failed to get NL80211_STA_INFO_CNAHLOAD
08-10 11:00:13.199 1011-1355/? E/WificondControl: Noise: 0, Snr: -1, Chload: -1
08-10 11:00:13.200 1011-1355/? E/HwWifiStatStore: updateLinkSpeed  linkSpeed =81 lastSpdLev=2 index=3
08-10 11:00:13.201 1011-1355/? E/HwWifiStatStore: updateLinkSpeedTxRxInfo  lastSpdLev=2 32215 503 1167136 810
08-10 11:00:14.044 668-668/? E/wificond: Failed to get NL80211_RATE_INFO_NOISE
    Failed to get NL80211_RATE_INFO_SNR
    Failed to get NL80211_STA_INFO_CNAHLOAD
08-10 11:00:14.045 1011-1355/? E/WificondControl: Noise: 0, Snr: -1, Chload: -1
08-10 11:00:14.045 1011-1355/? E/HwWifiStatStore: updateLinkSpeed  linkSpeed =81 lastSpdLev=3 index=3
08-10 11:00:14.046 668-668/? E/wificond: Failed to get NL80211_RATE_INFO_NOISE
    Failed to get NL80211_RATE_INFO_SNR
08-10 11:00:14.047 668-668/? E/wificond: Failed to get NL80211_STA_INFO_CNAHLOAD
08-10 11:00:14.483 2951-6339/? E/HiAction_b: syncSend(): receive response timeout
08-10 11:00:14.484 2951-6339/? E/HiAction_XChannel.k-6: run(): LogXin failed, exit
08-10 11:00:16.206 603-603/? E/WifiHAL: enter wifi_get_link_stats
08-10 11:00:16.211 668-668/? E/wificond: Failed to get NL80211_RATE_INFO_NOISE
08-10 11:00:16.212 668-668/? E/wificond: Failed to get NL80211_RATE_INFO_SNR

**Comment by CarGuo** [comment]
暂时看不出来什么，如果方便提供下测试url，看起来相似解码失败。说起来你这个不是直播的吧。

**Comment by 995518790** [comment]
http://hjq-1257036536.cos.ap-shanghai.myqcloud.com/m3u8/m1/out2.m3u8
在腾讯云上

**Comment by CarGuo** [comment]
刚刚在demo的 detailPlayer 替换了你的链接，正常播放缓存，一个妹子弹琵琶。

你可以在demo上试试，打开GSYApplication的 //EXO 2 播放内核的屏蔽
然后把url复制的 detailPlayer 的 getUrl 方法下，设置 .setCacheWithPlay(true)

**Comment by 995518790** [comment]
哪个demo，我找不到啊

**Comment by CarGuo** [comment]
这个项目啊……
