### ISSUE TITLE
播放有防盗链(Referer)设置的视频链接，不能同时进行缓存

### ISSUE THREAD

**Issue by DingZugeng** [CarGuo/GSYVideoPlayer#1349]
## 问题描述：
播放一个视频链接，视频链接做了防盗链，添加了header：Referer，XXXX
在setup里指定不缓存时，视频播放正常。
但是把cacheWithPlay=true，并添加cachePath后，视频无法播放。
我看你在#520里答复的是需要将cacheWithPlay设置为false，是否这个框架添加防盗链的referer header后就无法进行缓存了呢？有没有办法可以解决，希望大佬百忙之中帮忙解答一下，谢谢啦

问题代码：(如果有)
        Map<String,String> header = new HashMap<>();
        header.put("Referer","http://www.androidpool.com");
        File cacheDir= new File(getActivity().getCacheDir().getAbsolutePath());
        mPlayer.setUp(mVideos.get(0).getUrl(), true, cacheDir,header,"Video 0");

**Comment by chengww5217** [comment]
就算是加 header 来验证，最后会给你重定向到一个下载链接的，请尝试直接获取下载链接，然后设置给播放器：

```java
/** 同步请求，自行开线程 **/
public static String getRedirectsUrl(String originUrl) {
        if (TextUtils.isEmpty(originUrl)) return originUrl;
        try {
            if (originUrl.startsWith("https")) {
                // Create a trust manager that does not validate certificate chains
                TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
                    public X509Certificate[] getAcceptedIssuers() {
                        return null;
                    }

                    public void checkClientTrusted(X509Certificate[] certs, String authType) {
                    }

                    public void checkServerTrusted(X509Certificate[] certs, String authType) {
                    }
                }};

                HostnameVerifier ignoreHostnameVerifier = new HostnameVerifier() {
                    public boolean verify(String s, SSLSession sslsession) {
                        return true;
                    }
                };
                HttpsURLConnection.setDefaultHostnameVerifier(ignoreHostnameVerifier);

                SSLContext sc = SSLContext.getInstance("TLS");
                sc.init(null, trustAllCerts, new SecureRandom());
                HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());

            }
            URL url = new URL(originUrl);
            HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
            urlConnection.setUseCaches(false);
            urlConnection.setInstanceFollowRedirects(false);
            urlConnection.setRequestProperty("Authorization", "Authorization..."); // 请求头
            urlConnection.setConnectTimeout(6000);
            urlConnection.setReadTimeout(6000);
            urlConnection.connect();
            int responseCode = urlConnection.getResponseCode();
            if (responseCode == 302 || responseCode == 301) {
                String url302 = urlConnection.getHeaderField("Location");
                if (TextUtils.isEmpty(url302)) {
                    url302 = urlConnection.getHeaderField("location"); //临时重定向和永久重定向location的大小写有区分
                }
                if (!(url302.startsWith("http://") || url302.startsWith("https://"))) { //某些时候会省略host，只返回后面的path，所以需要补全url
                    URL originalUrl = new URL(originUrl);
                    url302 = originalUrl.getProtocol() + "://" + originalUrl.getHost() + ":" + originalUrl.getPort() + url302;
                }

                return url302;
            } else if (responseCode == 200) {
                return originUrl;
            }
        } catch (IOException | NoSuchAlgorithmException | KeyManagementException e) {
            e.printStackTrace();
        }
        return "";
    }
```

**Comment by CarGuo** [comment]
@DingZugeng   你用着哪个版本？？用的是ijk模式吗？

**Comment by liuhuilong2016** [comment]
@DingZugeng 怎么添加Referer ？要修改源代码吗？

**Comment by CarGuo** [comment]
ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                //如果返回 null，就使用默认的
                return null;
            }

            /**
             * 通过自定义的 HttpDataSource ，可以设置自签证书或者忽略证书
             * demo 里的 GSYExoHttpDataSourceFactory 使用的是忽略证书
             * */
            @Override
            public DataSource.Factory getHttpDataSourceFactory(String userAgent, @Nullable TransferListener listener, int connectTimeoutMillis, int readTimeoutMillis,
                                                               Map<String, String> mapHeadData, boolean allowCrossProtocolRedirects) {
                //如果返回 null，就使用默认的
                GSYExoHttpDataSourceFactory factory = new GSYExoHttpDataSourceFactory(userAgent, listener,
                        connectTimeoutMillis,
                        readTimeoutMillis, allowCrossProtocolRedirects);
                factory.setDefaultRequestProperties(mapHeadData);
                return factory;
            }
        });


@liuhuilong2016
