### ISSUE TITLE
支持拖动进度时如果已缓冲，直接开始播放吗

### ISSUE THREAD

**Issue by quert999** [CarGuo/GSYVideoPlayer#135]
ijkplayer我之前找了一个编译好的，写了个demo，但是在拖进度的时候一定会有缓冲。
dalao你这个项目支持直接播放不缓冲吗？
我checkout下来看了下拖动进度的时候会出现loading图标但是有时候很快就消失，不知道是我网速问题还是你这边处理的。
想学习下怎么才能不缓冲直接播放。
给dalao递茶。

**Comment by CarGuo** [comment]
如果开启了缓存模式，那么走的是代理的url socket，缓冲就是走的边播边存的缓存，所以缓存速度快一些。如果关闭了缓存，那么和ijk的就差不多了。
