### ISSUE TITLE
播放途中走失败回调后会从头开始播放

### ISSUE THREAD

**Issue by Average77** [CarGuo/GSYVideoPlayer#1351]
## 问题描述：

开始播放后，把网络关闭，当走到缓存条没有的地方，会停止，然后把网络打开，点击播放按钮，就会从头还是播放。

## Demo中的复现步骤

简单直接播放和弹幕页面都有此情况，别的没有测试

请问有没有办法这种网络原因导致的播放失败，再点播放按钮能够接着刚才的播放呢

**Comment by Average77** [comment]
用户说卡的时候走到缓存条没有的地方也会从头播QAQ

**Comment by Average77** [comment]
我看了一下这个监听走了，而且mNetChanged 这里已经设置成true了，
mNetInfoModule = new NetInfoModule(getActivityContext().getApplicationContext(), new NetInfoModule.NetChangeListener() {
                @Override
                public void changed(String state) {
                    if (!mNetSate.equals(state)) {
                        Debuger.printfError("******* change network state ******* " + state);
                        mNetChanged = true;
                    }
                    mNetSate = state;
                }
            });

但是onError里 mNetChanged还是false。。。哇的一声哭出来
 if (mNetChanged) {
            mNetChanged = false;
            netWorkErrorLogic();
            if (mVideoAllCallBack != null) {
                mVideoAllCallBack.onPlayError(mOriginUrl, mTitle, this);
            }
            return;
        }
@CarGuo

**Comment by CarGuo** [comment]
哈哈哈···
首先，在onError中应该是会走onPlayError回调的吧。
然后，我这边测试mNetChanged 是true·····，如下图


![5b727915e4b0cdb6810cffdf](https://user-images.githubusercontent.com/10770362/44126187-4f771ba2-a069-11e8-8ebb-d6a0ff86abdf.png)


最后，你可以试试加上 
```
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by Average77** [comment]
加了那个也不行QAQ
    @Override
    public void onError(int what, int extra) {
        this.curr=getCurrentPositionWhenPlaying();
        super.onError(what, extra);
    }
重写了onerror()获取到当前进度， 重写 clickStartIcon ()
            if (curr > 0) {
                setSeekOnStart(this.curr);
                curr = 0;

            }
            startButtonLogic();

            在startButtonLogic()前判断进度大于0的话，就seek

这样能续播了~
