### ISSUE TITLE
SystemSensorManager 内存泄漏

### ISSUE THREAD

**Issue by krisez** [CarGuo/GSYVideoPlayer#1353]
## 问题描述：
SystemSensorManager 内存泄漏

## 问题机型/系统：

真机 Vivo X5M android 5.0.1

## Demo中的复现步骤
联动details下
在退出activity的时候
检测到sensormanager的引用持有

问题代码：(如果有)
```
if (mOrientationUtils != null)
            mOrientationUtils.releaseListener();
```
这是有的  可以没反应
## 问题log（如果有）

```
hprof: heap dump "/storage/sdcard0/Download/leakcanary-cn.krisez.car/260642e7-d4d6-4666-b814-b3f32a03ae52_pending.hprof" starting..
hprof: heap dump completed (24MB) in 3.202s

```

**Comment by CarGuo** [comment]
OrientationUtils 除了activity外部一个，还有gsybase里内部也有一个，这里的泄漏是外部？releaseListener不生效？

**Comment by krisez** [comment]
对呀，我也纳闷呀。release源代码有注销sensor的，但是就是有泄漏从该activity里面出来。
![aaa](https://user-images.githubusercontent.com/15455028/44078175-7370f5f0-9fd8-11e8-8281-ca63c5c0fa18.png)
我从activity里面退出来无论bomeib播没播放，都会有这个。

**Comment by CarGuo** [comment]
这就无解了，和AudioManager的泄漏一样。

**Comment by krisez** [comment]
那就GG了。
好吧

**Comment by CarGuo** [comment]
我试试下个版本全部修改为ApplicationContext给OrientationEventListener

**Comment by krisez** [comment]
no problem
