### ISSUE TITLE
监听播放状态

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#1354]
有没有监听方法能知道播放时是否正在播放和非播放这两个状态

**Comment by missu263** [comment]
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/15882147/44088361-68c9eeaa-9ff5-11e8-9505-8f6116f2865a.png">

在视频状态回调中，根据以上判断的状态来是看否在播放啊

**Comment by CarGuo** [comment]
good job
