### ISSUE TITLE
Referer 头信息设置没用

### ISSUE THREAD

**Issue by WuShengXi** [CarGuo/GSYVideoPlayer#1356]
Referer 头信息设置没用

**Comment by WuShengXi** [comment]
@Override
    public boolean setUp(String url, boolean cacheWithPlay, String title) {
        Map<String, String> header = new HashMap<>();
        header.put("Referer", BuildConfig.HTTP_SOURCE_URL);
        return super.setUp(url, cacheWithPlay, null, header, title);
    }

**Comment by CarGuo** [comment]
试试cacheWithPlay为false，我这边测试header信息正常，但是Referer有没有效就不知道了

**Comment by WuShengXi** [comment]
好的 谢谢了
