### ISSUE TITLE
全屏播放的时候，视频有1-2秒 由小放大的过程，感觉有些卡顿

### ISSUE THREAD

**Issue by geduo83** [CarGuo/GSYVideoPlayer#1359]
## 问题描述：

**竖屏切换到横屏，全屏播放的时候，视频有1-2秒 由小放大的过程，感觉有些卡顿，能不能去掉这个由小变大动画效果**

## 问题机型/系统：

**所有机型**

SDK版本：
compile 'com.shuyu:gsyVideoPlayer-java:5.0.2'
compile 'com.shuyu:gsyVideoPlayer-ex_so:5.0.2'

android sdk：27.0.2

**Comment by geduo83** [comment]
问题已经解决

**Comment by zhuguohui** [comment]
怎么解决的
