### ISSUE TITLE
RecyclerView列表视频快速滑动错位

### ISSUE THREAD

**Issue by wushangjun** [CarGuo/GSYVideoPlayer#136]
用demo试的。播放第一个视频全屏后切换回竖屏快速滑动到底部，底部还在播放着第一个视频。用ListView列表视频没有遇到。请问怎么解决？

**Comment by CarGuo** [comment]
这是是错位问题，在滚动监听那里做处理，划出了就释放。

**Comment by CarGuo** [comment]
新demo已经修复

**Comment by CarGuo** [comment]
新demo已经修复
