### ISSUE TITLE
Fragment中退出全屏如何默认为横屏？

### ISSUE THREAD

**Issue by LiuXinxing** [CarGuo/GSYVideoPlayer#1363]
## 问题描述：

我fragment所在的Activity已经在activity中设置android:screenOrientation="landscape"，初始播放时是横屏，全屏时也是横屏，退出全屏后为什么就变成了竖屏？

问题代码：(如果有)
具体代码如下：

  GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder();
                                gsyVideoOption.setThumbImageView(imageView)
                                        .setIsTouchWiget(true)
                                        .setRotateViewAuto(false)
                                        .setLockLand(true)
                                        .setAutoFullWithSize(false)
                                        .setShowFullAnimation(false)
                                        .setNeedLockFull(true)
                                        .setUrl(response.getList().get(0).getVideourl())
                                        .setCacheWithPlay(false)
                                        .build(mSgsyvpAboutXueteng);

                                mSgsyvpAboutXueteng.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
                                    @Override
                                    public void onClick(View v) {
                                        //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                                        mSgsyvpAboutXueteng.startWindowFullscreen(getActivity(), false, false);
                                    }
                                });

**Comment by yecaler** [comment]
大哥，怎么解决的？
