### ISSUE TITLE
【紧急】8.0 Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#1365]
GSYBaseVideoPlayer中的resolveFullVideoShow方法中GSYBaseVideoPlayer.this.mOrientationUtils.resolveByClick()的resolveByCick()中this.activity.setRequestedOrientation(0);和this.activity.setRequestedOrientation(1);方法在8.0的机子上会报错，Only fullscreen activities can request orientation，求解决办法

**Comment by i2863CookieZJ** [comment]
或者删除这两句代码

**Comment by i2863CookieZJ** [comment]
补充说明：8.0因为需求设置了透明状态栏，但是8.0只有全屏不透明的activity才可以设置方向，所以造成了问题

**Comment by CarGuo** [comment]
是的，这个需要满足三个条件才会触发，自行处理即可
