### ISSUE TITLE
屏幕左右旋转进入全屏，画面方向不对

### ISSUE THREAD

**Issue by missu263** [CarGuo/GSYVideoPlayer#1366]
非全屏模式时候，无论是向左还是向右旋转屏幕，实际上都是向左旋转屏幕的横屏画面

拜读了源码，旋转的时候进入全屏，OrientationUtils.resolveByClick()都是设置
`activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);`
这是实际上设置屏幕向左旋转横屏

但是还有这种应该向右反向横屏的情况呢
`activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_REVERSE_LANDSCAPE);`

如果自己去完善这种交互，对代码的修改侵入性非常强。因为进入全屏是GsyPlayerVideo内部的OrientationUtils变量去调用自身resolveByClick控制的

所以请问还有别的方法可以完善屏幕旋转进入全屏的交互呢？

**Comment by missu263** [comment]
WebDetailActivity的效果是正确的！
但是我看了Demo的代码，然后我现在还不行

DetailPlayer中的旋转效果就是我上述反应的问题，大神可以帮忙看一下，为什么DetailPlayer里面的旋转画面和方向对不上。。。
另外我在源码，也木有发现旋转进入横屏的时候有根据旋转角度判断设置横屏为方向横屏。。。
😳😳😳😳😳😳

**Comment by CarGuo** [comment]
setRotateViewAuto(true)
setAutoFullWithSize(false)

**Comment by missu263** [comment]
非常感谢😀😃😄
