### ISSUE TITLE
recycleView item滑出时产生的问题

### ISSUE THREAD

**Issue by wzgl5533** [CarGuo/GSYVideoPlayer#1368]
测试列表播放（上滑）中发现以下问题：
当上面的某一个播放中的视频滑出屏幕，下面的列表的某一个播放按钮会发生改变（据观察感觉是从播放到暂停的样子），不知道是怎么回事。

测试demo也会有这个现象

**Comment by CarGuo** [comment]
是会有，因为recycler复用的逻辑加上动画播放按键导致，你可以不使用带动画的播放按键。
