### ISSUE TITLE
第一次为网络播放的的情况下，设置了循环播放，放完后会继续使用网络播放，没使用本地缓存

### ISSUE THREAD

**Issue by Itachi110** [CarGuo/GSYVideoPlayer#1374]
## 问题描述：
设置循环播放，在第一次为网络播放的的情况下，放完后自动播放第二次依然会使用网络播放，没使用本地缓存，感觉这里可以优化一下

**Comment by CarGuo** [comment]
如果是默认缓冲的话，这个是正常的，因为这个缓冲只是很小的一小块，你seek一下都会重置。


如果想要效果，你设置使用边播边缓存为true

**Comment by Itachi6688** [comment]
设置使用边播边缓存为true，还是一样的效果
