### ISSUE TITLE
增加了 header 以后 第一次进入 加载 403 第二次进入正常播放 

### ISSUE THREAD

**Issue by WuShengXi** [CarGuo/GSYVideoPlayer#1375]
ecvVideo.setUp(data.getVideoUrl(), false, null, header, "");

**Comment by CarGuo** [comment]
请提供测试链接，需要设置的header

**Comment by WuShengXi** [comment]
http://zscc.video.kmzscc.com/zscc/ceshi/2018/08/18/wWdhsenWe5u21.mp4
Referer  : http://www.kmzscc.com/
header 只加了这一个

**Comment by WuShengXi** [comment]
额 我在研究下 是不是我这边逻辑的问题

**Comment by WuShengXi** [comment]
感谢
