### ISSUE TITLE
设置视频播放类型为SYSTEMPLAYER(系统播放器)会有进度回调问题

### ISSUE THREAD

**Issue by diewu0421** [CarGuo/GSYVideoPlayer#1377]
问题：
在Demo中的GSYApplication中修改视频播放类型为SYSTEMPLAYER，代码如下：
GSYVideoManager.instance().setVideoType(this, GSYVideoType.SYSTEMPLAYER); //系统播放器
会出现在循环播放时，进度回调不置零的问题

机型:
真机　锤子pro2 Android 7.1

复现步骤：
首先设置循环播放 player.setLooping(true),然后依次点击
Demo--->简单播放---->简单播放---->拖动进度条到底　
然后会发现，当视频重新播放时，进度条还是满的，没有重新开始

代码：
` //设置进度监听回调
                player.setGSYVideoProgressListener(new GSYVideoProgressListener() {
                    @Override
                    public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
                        SampleVideo player = (SampleVideo) getViewByPosition(position, R.id.video_item_player);
                        if (player != null) {
                            //打印进度
                            Log.e("VideoDetailAdapter", " progress = " + progress +
                                    " secProgress = " + secProgress +
                                    " currentPosition = " + currentPosition +
                                    "  duration = " + duration +
                                    "  hashcode = " + player.hashCode());
                        }
                    }
                }).build(mGsyVideoPlayer);`
打印的日志如下：
E: afterBindData: position 0  player's hashcode 252200639
E:  progress = 0 secProgress = 0 currentPosition = 0  duration = 10031  hashcode = 252200639
E:  progress = 0 secProgress = 0 currentPosition = 0  duration = 10031  hashcode = 252200639
E:  progress = 0 secProgress = 0 currentPosition = 0  duration = 10031  hashcode = 252200639
E:  progress = 3 secProgress = 0 currentPosition = 372  duration = 10031  hashcode = 252200639
E:  progress = 7 secProgress = 0 currentPosition = 722  duration = 10031  hashcode = 252200639
E:  progress = 10 secProgress = 0 currentPosition = 1080  duration = 10031  hashcode = 252200639
E:  progress = 14 secProgress = 0 currentPosition = 1441  duration = 10031  hashcode = 252200639
E:  progress = 17 secProgress = 0 currentPosition = 1799  duration = 10031  hashcode = 252200639
E:  progress = 21 secProgress = 0 currentPosition = 2160  duration = 10031  hashcode = 252200639
E:  progress = 25 secProgress = 0 currentPosition = 2520  duration = 10031  hashcode = 252200639
E:  progress = 28 secProgress = 0 currentPosition = 2880  duration = 10031  hashcode = 252200639
E:  progress = 32 secProgress = 0 currentPosition = 3240  duration = 10031  hashcode = 252200639
E:  progress = 35 secProgress = 0 currentPosition = 3601  duration = 10031  hashcode = 252200639
E:  progress = 39 secProgress = 0 currentPosition = 3961  duration = 10031  hashcode = 252200639
E:  progress = 42 secProgress = 0 currentPosition = 4308  duration = 10031  hashcode = 252200639
E:  progress = 45 secProgress = 0 currentPosition = 4610  duration = 10031  hashcode = 252200639
E:  progress = 48 secProgress = 0 currentPosition = 4908  duration = 10031  hashcode = 252200639
E:  progress = 51 secProgress = 0 currentPosition = 5204  duration = 10031  hashcode = 252200639
E:  progress = 54 secProgress = 0 currentPosition = 5508  duration = 10031  hashcode = 252200639
E:  progress = 57 secProgress = 0 currentPosition = 5810  duration = 10031  hashcode = 252200639
E:  progress = 60 secProgress = 0 currentPosition = 6109  duration = 10031  hashcode = 252200639
E:  progress = 63 secProgress = 0 currentPosition = 6414  duration = 10031  hashcode = 252200639
E:  progress = 66 secProgress = 0 currentPosition = 6715  duration = 10031  hashcode = 252200639
E:  progress = 69 secProgress = 0 currentPosition = 7016  duration = 10031  hashcode = 252200639
E:  progress = 72 secProgress = 0 currentPosition = 7316  duration = 10031  hashcode = 252200639
E:  progress = 75 secProgress = 0 currentPosition = 7616  duration = 10031  hashcode = 252200639
E:  progress = 78 secProgress = 0 currentPosition = 7920  duration = 10031  hashcode = 252200639
E:  progress = 81 secProgress = 0 currentPosition = 8221  duration = 10031  hashcode = 252200639
E:  progress = 84 secProgress = 0 currentPosition = 8519  duration = 10031  hashcode = 252200639
E:  progress = 87 secProgress = 0 currentPosition = 8820  duration = 10031  hashcode = 252200639
E:  progress = 90 secProgress = 0 currentPosition = 9120  duration = 10031  hashcode = 252200639
E:  progress = 93 secProgress = 0 currentPosition = 9417  duration = 10031  hashcode = 252200639
E:  progress = 96 secProgress = 0 currentPosition = 9704  duration = 10031  hashcode = 252200639
E:  progress = 99 secProgress = 0 currentPosition = 10006  duration = 10031  hashcode = 252200639
E:  progress = 99 secProgress = 0 currentPosition = 10006  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639
E:  progress = 100 secProgress = 0 currentPosition = 10031  duration = 10031  hashcode = 252200639

可以发现　progress 到了１００以后，还是100，没有为０，但是视频已经重新播放了

**Comment by CarGuo** [comment]
目前我这边测试不会，可能和当前环境有关，如果是视频已经缓存到本地的时候就没问题。
可以看下源码中，GSYVideoControlView的这个
```
    @Override
    public void onBufferingUpdate(int percent) {
        if (mCurrentState != CURRENT_STATE_NORMAL && mCurrentState != CURRENT_STATE_PREPAREING) {
            if (percent != 0) {
                setTextAndProgress(percent);
                mBufferPoint = percent;
                Debuger.printfLog("Net speed: " + getNetSpeedText() + " percent " + percent);
            }
            if (mProgressBar == null) {
                return;
            }
            //循环清除进度
            if (mLooping && mHadPlay && percent == 0 && mProgressBar.getProgress() >= (mProgressBar.getMax() - 1)) {
                loopSetProgressAndTime();
            }
        }
    }
```

**Comment by diewu0421** [comment]
作者你好，测试了几款机型，华为p20　vivo oppo 锤子pro2等几款，就锤子pro2出现了这种情况，设置模拟器Genymotion 7.0都不会出现，郁闷了，打死都不埋买锤子手机了
