### ISSUE TITLE
50个视频 来回切换

### ISSUE THREAD

**Issue by xiangou** [CarGuo/GSYVideoPlayer#1379]
公司项目 有50 来个视频  要求
1 切换视频 流畅
2切换完成后 播放上个视频播放的位置  （上个视频播放到5秒 这个视频从5秒开始播放）

//切换视频代码
long time = videoPlayer.getCurrentPositionWhenPlaying();
        videoPlayer.release();
        videoPlayer.setUp(url, true, "");
        videoPlayer.setSeekOnStart(time);
        videoPlayer.startPlayLogic();

经常性奔溃 切有加载黑屏 使用 EmptyControlVideo
请问最佳实践是什么

**Comment by xiangou** [comment]
android TV 后台同时开启50 个播放器等待播放？

**Comment by xiangou** [comment]
好像不太行

**Comment by xiangou** [comment]
好像不太行 要凉了

**Comment by CarGuo** [comment]
明显开50个不可能的，一个一个切换时必须的，最后做本地缓存，切换的时候缓存读取。release到重新setup之间是需要500毫秒以上的间隔才行

**Comment by xiangou** [comment]
现在我的方案是 把这50个视频串在一起 用Seekto 来切换
您说的本地缓存 是下载到本地吗

**Comment by xiangou** [comment]
现在我的方案是 把这50个视频串在一起变成一个视频 用Seekto 来切换
您说的本地缓存 是下载到本地吗

**Comment by CarGuo** [comment]
你的视频如果不是直播，就可以尝试缓存。
如果m3u8，就需要用exoplayer内核模式才支持缓存
直播目前不支持，不过issue里貌似有个改了底层支持了。

**Comment by xiangou** [comment]
好 我在研究下
