### ISSUE TITLE
Activity 里面设置了tablayout ，每个tablayout标签对于一个fragment 。 fragment里面的recycleView Item 点击播放然后点击全屏，会把Activity 变成横屏。 而且整个Activity的页面生命周期都重新走了一遍

### ISSUE THREAD

**Issue by zhouyaxu1** [CarGuo/GSYVideoPlayer#1381]
Activity 里面设置了tablayout ，每个tablayout标签对于一个fragment 。 fragment里面的recycleView Item 点击播放然后点击全屏，会把Activity 变成横屏。 而且整个Activity的页面生命周期都重新走了一遍

**Comment by CarGuo** [comment]
看问题集锦，配置manifest
