### ISSUE TITLE
依赖项目，报错。 帮忙看下，是啥原因。 别的依赖库就没问题，就是依赖视频库就下载不动

### ISSUE THREAD

**Issue by zhouyaxu1** [CarGuo/GSYVideoPlayer#1382]
Error:Could not resolve all dependencies for configuration ':consumer:productionDebugRuntimeClasspath'.
Could not determine artifacts for com.shuyu:gsyVideoPlayer-java:6.0.0-beta: Skipped due to earlier error

**Comment by zhouyaxu1** [comment]
就这个问题搞了一下午了... vpn也开了

**Comment by CarGuo** [comment]
如果你试demo没问题，那只能说是项目gradle可能存在版本问题，maven 指向问题之类的，对比下demo吧

**Comment by CarGuo** [comment]
http://jcenter.bintray.com/com/shuyu/GSYVideoPlayer/6.0.0-beta/  包所在

**Comment by zhouyaxu1** [comment]
非常感谢，原因找到了，应该是公司网络影响的。 很蛋疼
