### ISSUE TITLE
视频缓存进度在哪里获取  回调的哪个方法里能够拿到？

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1383]
@CarGuo   现在有个需求需要获取缓存进度  而且需要能够开始缓存  删除缓存，

如果一个视频缓存完毕了，不再是临时文件了 那还有什么办法删除吗，我想一开始设置.setCacheWithPlay(true),如果用户没有说要缓存该视频的话,就在onAutoComplete中删除该视频缓存,如果用户没有说要缓存该视频的话,如果有需要缓存该视频，则不进行删除视频缓存操作。

**Comment by CarGuo** [comment]
GSYManager
