### ISSUE TITLE
Android8.1.0 跳转到新的页面，然后返回！再点击放大按钮setRequestedOrientation无法调动onConfigurationChanged

### ISSUE THREAD

**Issue by chaoDream** [CarGuo/GSYVideoPlayer#1386]
跳转新页面再回到播放页面
resolveByClick（）
方法执行后，没办法监听到onConfigurationChanged
点击多次后，也就是设置多次resolveByClick（），恢复onConfigurationChanged的监听
@CarGuo

**Comment by CarGuo** [comment]
demo怎么复现
