### ISSUE TITLE
记录播放进度

### ISSUE THREAD

**Issue by Sing1** [CarGuo/GSYVideoPlayer#1387]
现在可以通过手动记录播放记录，希望可以加一个根据播放地址，自动记录播放记录，下次打开如果url一样的话直接继续上次播放

**Comment by CarGuo** [comment]
这个自己继承后包一层就好了，类似此类的业务逻辑并不会加到库里

具体可实现可使用 seekOnStart

或者参考

https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md  第 20、条
