### ISSUE TITLE
项目急，想请教一下要给视频添加前置图片广告展示有什么好的思路吗

### ISSUE THREAD

**Issue by LegendaryMystic** [CarGuo/GSYVideoPlayer#1388]
需求跟视频广告类似，图片展示一段时间后关掉，能够切换全屏

**Comment by CarGuo** [comment]
Demo不是有中途跳出广告的实现么，参考那个就可以

**Comment by LegendaryMystic** [comment]
没看到呢，惭愧惭愧，麻烦告知具体是那个案例（Activity）吗？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailADPlayer2.java

**Comment by LegendaryMystic** [comment]
从Demo  App 带广告2界面中没看到弹出广告效果，从代码上看是视频广告，我们广告有可能是视频有可能是图片，不过我昨天已经自己实现了，非常感谢！

**Comment by LaymanInCoding** [comment]
> 从Demo App 带广告2界面中没看到弹出广告效果，从代码上看是视频广告，我们广告有可能是视频有可能是图片，不过我昨天已经自己实现了，非常感谢！

请问下你是怎么实现的啊
