### ISSUE TITLE
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry

### ISSUE THREAD

**Issue by JeremyHwc** [CarGuo/GSYVideoPlayer#1392]
## 问题描述：
打包的时候出现Execution failed for task ':app:transformClassesWithJarMergingForDefaultRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/danikula/videocache/ByteArrayCache.class
## 问题机型/系统：
无
## Demo中的复现步骤
无
问题代码：(如果有)
我本地有个音乐播放库，通过module的方式进行了依赖了该音乐库，该库里面通过
implementation 'com.danikula:videocache:2.7.0'
依赖了videocache这个库，
但是我发现GSYVideoPlayer里面通过api方式依赖了videocache这个库
api project(':gsyvideoplayer-androidvideocache')

用什么办法可以解决吗？

**Comment by CarGuo** [comment]
gsy的videocache 版本是2.8.0，比官方的增加了header

**Comment by JeremyHwc** [comment]
在GSYVideoPlayer里面api project(':gsyvideoplayer-androidvideocache')
可以改成implemetation project(':gsyvideoplayer-androidvideocache')吗

**Comment by CarGuo** [comment]
和这个没关系

**Comment by JeremyHwc** [comment]
大佬知道我这个问题怎么解决呀 确实是gsyvideoplayer-androidvideocache里面的缓存库和另一个音频库冲突了

**Comment by CarGuo** [comment]
这得看你是怎么依赖gsy的。
你可以替换音频库的androidvideocache依赖为compile 'com.shuyu:gsyvideoplayer-androidvideocache:6.0.0-beta'

**Comment by JeremyHwc** [comment]
可以了 谢谢大佬
