### ISSUE TITLE
你好,我今天我用了你的项目,总体很好,但是我得需求实在列表播放时,滑动后回来继续看要记录之前得播放位置,用了demo得setSeekOnStart(),不过会闪动几秒,怎么办

### ISSUE THREAD

**Issue by xiangjie1992** [CarGuo/GSYVideoPlayer#1393]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

开发需求发生了这样的问题！

## 问题机型/系统：

所有得机子

## Demo中的复现步骤

列表播放-继续播放需求记录当前播放位置,使用setSeekOnStart()方法设定会闪动

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
播放前设置
```
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

或者

VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", startPosition);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

**Comment by zou-xian-liang** [comment]
> （请务必按照issue模板，修改后提交问题）
> 
> （ps 首页问题集锦和demo请先了解一下！）
> 
> ## 问题描述：
> 开发需求发生了这样的问题！
> 
> ## 问题机型/系统：
> 所有得机子
> 
> ## Demo中的复现步骤
> 列表播放-继续播放需求记录当前播放位置,使用setSeekOnStart()方法设定会闪动
> 
> 问题代码：(如果有)
> 
> ```
> xxxxxxx
> ```
> ## 问题log（如果有）
> ```
> 
> xxxxxxx
> ```

麻烦问下，你列表中每个视频的播放进度是如何保存的呢
