### ISSUE TITLE
视频播放几秒，回到桌面两分钟，再回到APP继续播放，然后视频播放到某个点就停止，未正常结束

### ISSUE THREAD

**Issue by tangjian211085** [CarGuo/GSYVideoPlayer#1394]
## 问题描述：

测试过程中发现一个问题：
就是在视频开始播放个一段时间(任意时间，可以是几秒或更多)后，手机回到桌面。这时player是暂停状态嘛，过一两分钟(或更长时间)后回到APP继续播放视频。那么这时视频在播放到某个位置是就会播放出错，而不是正常播放结束。观察后发现在回到桌面后再回到APP继续播放视频时，视频的缓存出现了问题如下：Stream ends prematurely at 19643340, should be 22939065，感觉就是缓存没结束就提前中断了。然后有报av_read_frame error: unknown异常。可以使用任意视频测试
请问这个问题怎解决呢？

## 问题机型/系统：

真机 测试过小米note4 Android6.0    vivo、oppoR57、三星、华为荣耀等机型

**Comment by CarGuo** [comment]
初步判断

如果是边播边缓存的服务的话，可能是被后台回收了，或者被手机断开连接。

如果对这种服务有需求的，可以使用exoplayer内核模式，加exoplayer的边播边缓存模式会好一些，exoplayer会做分块缓存

**Comment by tangjian211085** [comment]
.................
......GSYVideoPlayer: DMLog******** progress： 18 currentPosition： 40126 duration： 221356
......GSYVideoPlayer: DMLog******** progress： 18 currentPosition： 40146 duration： 221356
......GSYVideoPlayer: DMLog******** progress： 18 currentPosition： 40433 duration： 221356
......GSYVideoPlayer: DMLog******** progress： 18 currentPosition： 40692 duration： 221356
......GSYVideoPlayer: DMLog******** progress： 18 currentPosition： 40728 duration： 221356
......GSYVideoPlayer: DMLog******** progress： 18 currentPosition： 41033 duration： 221356
......IJKMEDIA: **Stream ends prematurely at 19643340, should be 22939065**
......IJKMEDIA: stream 1, offset 0x12bbbdb: partial file
......IJKMEDIA: av_read_frame error: unknown
......GSYVideoPlayer: DMLog******** progress： 18 currentPosition： 41188 duration： 221356
......IJKMEDIA: stream 0, offset 0x12bbc7c: partial file
......IJKMEDIA: av_read_frame error: unknown
......GSYVideoPlayer: DMLog******** progress： 18 currentPosition： 41343 duration： 221356

log日志如上。前面正常，然后就出现Stream ends prematurely at 19643340, should be 22939065的异常。谢谢啦，可是我不明白exoplayer内核模式什么意思，怎么使用呢？？？

**Comment by CarGuo** [comment]
如果任何数据源，比如运行demo 并运行demo的数据源，也会出现这个情况，并且是后台状态的话，那么久很可能是默认边播边缓存服务问题

你可以设置cache为false试试就可以验证。


默认的代理是起了一个本地服务，代理拉流，然后把数据存到本地文件，同时返回流给播放器。

至于exoplayer，需要看你用的是哪个版本，根据版本可以切换demo中的git tag，看https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/GSYApplication.java 就知道了。

**Comment by tangjian211085** [comment]
非常感谢你回复的这么快，很感谢。说的是这个吗：

        //GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER); //EXO 1 播放内核，弃用
        //GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2); //EXO 2 播放内核
        //GSYVideoManager.instance().setVideoType(this, GSYVideoType.SYSTEMPLAYER); //系统播放器

**Comment by tangjian211085** [comment]
//CacheFactory.setCacheManager(new ExoPlayerCacheManager());//exo缓存模式，支持m3u8，只支持exo
        //CacheFactory.setCacheManager(new ProxyCacheManager());//代理缓存模式，支持所有模式，不支持m3u8等
明白了，应该是这个才对。我先更新下代码试试，如还有问题再请教。谢谢啦

**Comment by tangjian211085** [comment]
//CacheFactory.setCacheManager(new ExoPlayerCacheManager());大神你好，这个注释打开依然有同样的问题。

**Comment by CarGuo** [comment]
如果关闭了cache还是会的话，那可能就是源的问题了。

**Comment by tangjian211085** [comment]
PlayerFactory.setPlayManager(new Exo2PlayerManager());打开后测试没问题了。自己项目里用的版本是5.0.0的，我看了下，应该只需要将videoType值设置为GSYVideoType.IJKEXOPLAYER2就好了，有待测试看效果。不行的话，就需要换成6.0.0版本了。谢谢大神了。另外，源指的是视频源吗？视频源会影响到缓存问题？

**Comment by CarGuo** [comment]
一般源是不会影响，但是可能源在服务器上存在一些其他问题等。

**Comment by tangjian211085** [comment]
已关闭的问题可以继续打开么？我使用的so是branches_avi分支下的，可以支持avi和mp4格式的视频播放。现在的问题是，使用这个方式PlayerFactory.setPlayManager(new Exo2PlayerManager());
CacheFactory.setCacheManager(new ExoPlayerCacheManager());播放视频后，mp4格式视频效果是很好的，但是avi格式的视频就播放不了了。

**Comment by CarGuo** [comment]
exoplayer是不支持avi的………

**Comment by tangjian211085** [comment]
请问有没有考虑弄个支持多个视频格式的so呢？exoplayer下的so可以通过编译ijk处理后支持avi格式的吗？怎么编译ijk呢，想去学习看看能不能自己搞搞，不能总是麻烦你了。

**Comment by CarGuo** [comment]
你看了readme那种结构图没？
现在主流的播放有exoplayer、ijkplayer、mediaplayer
mediaplayer是系统自带
ijkplayer是ffmpeg
exoplayer是基于Mediacodec

现在gsy是把这三个整合起来，对外提供，你可以理解为有三种内核。

然后ijkplayer是ffmpeg的，所以是通过编译出so提供播放能力。其中在gsy中又分为：
ijk普通so
gsy普通so
还有gsy拓展支持rtsp、rtmp、avi、concat等的 ex_so

**Comment by tangjian211085** [comment]
嗯，好的，谢啦。是应该好好看看
