### ISSUE TITLE
关于MultiVideoduoi多视频同时播放问题

### ISSUE THREAD

**Issue by yanlianhanlin** [CarGuo/GSYVideoPlayer#1395]
demo中的多任务支持，点击3个视频播放刚开始有3个播放播放了几秒之后只有一个视频播放，页面中的三个视频设置为打开页面自动播放，只有一个播放，其他视频都是正在加载中。
以上的问题应该怎么处理啊？

**Comment by CarGuo** [comment]
不是很理解，我这边demo没出现问题

**Comment by yanlianhanlin** [comment]
![screenshot_2018-08-28-17-12-38-032_com example gs](https://user-images.githubusercontent.com/9565630/44713519-df933780-aae5-11e8-80ca-f6bb82f58ff1.png)
![screenshot_2018-08-28-17-12-07-747_com example gs](https://user-images.githubusercontent.com/9565630/44713529-e457eb80-aae5-11e8-9284-7bb0e064f1d3.png)
设置为点开页面自动播放视频，进度条在走图像只有一个出来。也出现只有一个视频播放其他的都是正在加载中

**Comment by CarGuo** [comment]
或者在CustomManager中加上这个
```
    @Override
    protected IPlayerManager getPlayManager() {
        return new IjkPlayerManager();
    }
```

**Comment by yanlianhanlin** [comment]
谢谢

**Comment by gushiyixini** [comment]
太棒了
