### ISSUE TITLE
关于暂停后 拖动  再播放的问题

### ISSUE THREAD

**Issue by xiangou** [CarGuo/GSYVideoPlayer#1397]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

关于暂停后 拖动  再播放的 不能拖动到指定位置

问题代码：(如果有)
```

        videoPlayer.seekTo(50*1000);
  videoPlayer.onVideoResume();
      
         
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
看请问题集锦和历史issue
