### ISSUE TITLE
为什么onPlayError在网络断了之后播放不了 跳到最后进度的时候不回调？

### ISSUE THREAD

**Issue by lly7690** [CarGuo/GSYVideoPlayer#1398]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

为什么onPlayError在网络断了之后播放不了 跳到最后进度的时候不回调？

## 问题机型/系统：

小米mix2s

## Demo中的复现步骤

onPlayError在网络断了之后播放不了 跳到最后进度的时候不回调

**Comment by CarGuo** [comment]
如果不走onError，那就说明底层认为不是播放错误

**Comment by lly7690** [comment]
哦

**Comment by lly7690** [comment]
那怎么样才能监听到播放错误呢？

**Comment by CarGuo** [comment]
试试exoplayer内核内核模式下的。如果还是没回调，说明ffmpeg和mediacodec都不认为是错误，那····就是源问题了

**Comment by lly7690** [comment]
CustomManager怎么用？

**Comment by CarGuo** [comment]
哈哈，不好意思，刚刚回复错了，是另外一个issue的

**Comment by CarGuo** [comment]
m3u8分片结束了不走onPlayError的问题。你如果试过系统模式下的话，那么只能说是正常情况反应了。
如果你真的想监听网络变化，那么参考代码里的网络状态变化吧
