### ISSUE TITLE
列表视频有点卡顿

### ISSUE THREAD

**Issue by zkywalker** [CarGuo/GSYVideoPlayer#1401]
用recyclerview实现的类似微博那种自动播放当前位置的视频。
在滑动到视频卡片时在自动播放前有明显卡顿，但是观察微博没有类似的现象。
是不是因为每次播放都会释放重建播放器导致的？
ps:项目里用的gsy版本较老没有用setUpLazy这个方法

**Comment by CarGuo** [comment]
说实在的，老版本我有点忘记了，不够很可能是setup的时候构建了proxy的问题，新版本setup应该不会做这个动作

**Comment by zkywalker** [comment]
阅读了您这边的源码发现新老版本区别不大。我这边是公司自己魔改的Ijkplayer，每次自动播放器会手动释放上一个播放器，不知道有没有关系。观察了下demo也没有卡顿，我再看下
