### ISSUE TITLE
MultiSampleVideo能否支持循环播放一个视频列表

### ISSUE THREAD

**Issue by yanlianhanlin** [CarGuo/GSYVideoPlayer#1402]
现在用的MultiSampleVideo实现了3个播放器同时播放视频的功能。现在有个需求是这样的，每个播放器都有5个视频资源的播放列表，每个播放器要循环播放自己播放列表中的视频并且要每次播放完视频之后统计播放次数。请问能实现上面的需求吗？

**Comment by CarGuo** [comment]
`播放器都有5个视频资源的播放列表` 这个可以的，你参考代码的ListGSYVideoPlayer就可以了

`列表循环`，自己判断列表数量执行从头开始就可以

**Comment by yanlianhanlin** [comment]
我将ListGSYVideoPlayer中的一些方法放到MultiSampleVideo，但是3个播放器不能同时播放了，这个应该怎么设置

**Comment by CarGuo** [comment]
首先看看 **CustomManager** 中是否有这个代码

```
    @Override
    protected IPlayerManager getPlayManager() {
        return new IjkPlayerManager();
    }
```

其此看看MultiSample是否有
```
    @Override
    public GSYVideoViewBridge getGSYVideoManager() {
        CustomManager.getCustomManager(getKey()).initContext(getContext().getApplicationContext());
        return CustomManager.getCustomManager(getKey());
    }
```

保证Player之间的manager不互相干扰，应该就不会有问题

**Comment by yanlianhanlin** [comment]
@Override
    protected IPlayerManager getPlayManager() {
        return new IjkPlayerManager();
    }
   @Override
    public GSYVideoViewBridge getGSYVideoManager() {
        CustomManager.getCustomManager(getKey()).initContext(getContext().getApplicationContext());
        return CustomManager.getCustomManager(getKey());
    }
这两个都有，我看ListGSYVideoPlayer中setUp是用的GSYVideoView中的setUp
MultiSampleVideo没有setUp 我仿照ListGSYVideoPlayer中setUp的写法加上了 是因为这个的原因吗？

**Comment by yanlianhanlin** [comment]
``/**
 * 多个同时播放的播放控件
 * Created by guoshuyu on 2018/1/31.
 */

public class MultiSampleVideo extends StandardGSYVideoPlayer {

    private final static String TAG = "MultiSampleVideo";
    ImageView mCoverImage;
    String mCoverOriginUrl;
    int mDefaultRes;
    private LinearLayout layout_bottom;

    public MultiSampleVideo(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

    public MultiSampleVideo(Context context) {
        super(context);
    }

    public MultiSampleVideo(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    protected void init(Context context) {
        super.init(context);
        //拉伸全屏
        GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);
        mCoverImage = (ImageView) findViewById(R.id.thumbImage);
        layout_bottom = findViewById(R.id.layout_bottom);
        layout_bottom.setVisibility(GONE);
        //增加title
        this.getTitleTextView().setVisibility(View.GONE);
        //设置返回键
        this.getBackButton().setVisibility(View.GONE);
        this.setPlayTag(TAG);
        //获取播放按键
        this.getStartButton().setVisibility(GONE);
        //是否需要显示流量提示,默认true
        this.setNeedShowWifiTip(false);
        if (mThumbImageViewLayout != null &&
                (mCurrentState == -1 || mCurrentState == CURRENT_STATE_NORMAL || mCurrentState == CURRENT_STATE_ERROR)) {
            mThumbImageViewLayout.setVisibility(VISIBLE);
        }
        onAudioFocusChangeListener = new AudioManager.OnAudioFocusChangeListener() {
            @Override
            public void onAudioFocusChange(int focusChange) {
                switch (focusChange) {
                    case AudioManager.AUDIOFOCUS_GAIN:
                        break;
                    case AudioManager.AUDIOFOCUS_LOSS:
                        post(new Runnable() {
                            @Override
                            public void run() {
                                //todo 判断如果不是外界造成的就不处理
                            }
                        });
                        break;
                    case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT:
                        post(new Runnable() {
                            @Override
                            public void run() {
                                //todo 判断如果不是外界造成的就不处理
                            }
                        });
                        break;
                    case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK:
                        break;
                }
            }
        };
    }

    @Override
    public GSYVideoViewBridge getGSYVideoManager() {
        CustomManager.getCustomManager(getKey()).initContext(getContext().getApplicationContext());
        return CustomManager.getCustomManager(getKey());
    }

    @Override
    protected boolean backFromFull(Context context) {
        return CustomManager.backFromWindowFull(context, getKey());
    }

    @Override
    protected void releaseVideos() {
        CustomManager.releaseAllVideos(getKey());
    }


    @Override
    protected int getFullId() {
        return CustomManager.FULLSCREEN_ID;
    }

    @Override
    protected int getSmallId() {
        return CustomManager.SMALL_ID;
    }


    @Override
    public int getLayoutId() {
        return R.layout.video_layout_cover;
    }

    public void loadCoverImage(String url, int res) {
        mCoverOriginUrl = url;
        mDefaultRes = res;
        Glide.with(getContext().getApplicationContext())
                .setDefaultRequestOptions(
                        new RequestOptions()
                                .frame(1000000)
                                .centerCrop()
                                .error(res)
                                .placeholder(res))
                .load(url)
                .into(mCoverImage);
    }

    @Override
    public GSYBaseVideoPlayer startWindowFullscreen(Context context, boolean actionBar, boolean statusBar) {
        GSYBaseVideoPlayer gsyBaseVideoPlayer = super.startWindowFullscreen(context, actionBar, statusBar);
        MultiSampleVideo multiSampleVideo = (MultiSampleVideo) gsyBaseVideoPlayer;
        multiSampleVideo.loadCoverImage(mCoverOriginUrl, mDefaultRes);
        return multiSampleVideo;
    }

    @Override
    public GSYBaseVideoPlayer showSmallVideo(Point size, boolean actionBar, boolean statusBar) {
        //下面这里替换成你自己的强制转化
        MultiSampleVideo multiSampleVideo = (MultiSampleVideo) super.showSmallVideo(size, actionBar, statusBar);
        multiSampleVideo.mStartButton.setVisibility(GONE);
        multiSampleVideo.mStartButton = null;
        return multiSampleVideo;
    }

    public String getKey() {
        if (mPlayPosition == -22) {
            Debuger.printfError(getClass().getSimpleName() + " used getKey() " + "******* PlayPosition never set. ********");
        }
        if (TextUtils.isEmpty(mPlayTag)) {
            Debuger.printfError(getClass().getSimpleName() + " used getKey() " + "******* PlayTag never set. ********");
        }
        return TAG + mPlayPosition + mPlayTag;
    }


    /******************* 下方重载方法，在播放开始不显示底部进度和按键，不需要可屏蔽 ********************/
    protected boolean byStartedClick;

    @Override
    protected void onClickUiToggle() {
        if (mIfCurrentIsFullscreen && mLockCurScreen && mNeedLockFull) {
            setViewShowState(mLockScreen, VISIBLE);
            return;
        }
        byStartedClick = true;
        super.onClickUiToggle();

    }

    @Override
    protected void changeUiToNormal() {
        super.changeUiToNormal();
        byStartedClick = false;
    }

    @Override
    protected void changeUiToPreparingShow() {
        super.changeUiToPreparingShow();
        Debuger.printfLog("Sample changeUiToPreparingShow");
        setViewShowState(mBottomContainer, GONE);
        setViewShowState(mStartButton, GONE);
        setViewShowState(mProgressBar, GONE);
    }

    @Override
    protected void changeUiToPlayingBufferingShow() {
        super.changeUiToPlayingBufferingShow();
        Debuger.printfLog("Sample changeUiToPlayingBufferingShow");
        if (!byStartedClick) {
            setViewShowState(mBottomContainer, GONE);
            setViewShowState(mStartButton, GONE);
            setViewShowState(mProgressBar, GONE);
        }
    }

    @Override
    protected void changeUiToPlayingShow() {
        super.changeUiToPlayingShow();
        Debuger.printfLog("Sample changeUiToPlayingShow");
        if (!byStartedClick) {
            setViewShowState(mBottomContainer, GONE);
            setViewShowState(mStartButton, GONE);
            setViewShowState(mProgressBar, GONE);
        }
    }

    @Override
    protected void changeUiToCompleteShow() {
        super.changeUiToCompleteShow();
        if (!byStartedClick) {
            setViewShowState(mBottomContainer, GONE);
            setViewShowState(mStartButton, GONE);
            setViewShowState(mProgressBar, GONE);
        }
    }

    @Override
    public void startAfterPrepared() {
        super.startAfterPrepared();
        Debuger.printfLog("Sample startAfterPrepared");
        setViewShowState(mBottomContainer, GONE);
        setViewShowState(mStartButton, GONE);
        setViewShowState(mProgressBar, GONE);
    }

    @Override
    public void onStartTrackingTouch(SeekBar seekBar) {
        byStartedClick = true;
        super.onStartTrackingTouch(seekBar);
    }

    /******************* 下方添加播放列表和列表循环 ********************/
    protected List<GSYVideoModel> mUriList = new ArrayList<>();
    protected int mPlayPosition;
    /**
     * 设置播放URL
     *
     * @param url           播放url
     * @param position      需要播放的位置
     * @param cacheWithPlay 是否边播边缓存
     * @return
     */
    public boolean setUp(List<GSYVideoModel> url, boolean cacheWithPlay, int position) {
        return setUp(url, cacheWithPlay, position, null, new HashMap<String, String>());
    }

    /**
     * 设置播放URL
     *
     * @param url           播放url
     * @param cacheWithPlay 是否边播边缓存
     * @param position      需要播放的位置
     * @param cachePath     缓存路径，如果是M3U8或者HLS，请设置为false
     * @return
     */
    public boolean setUp(List<GSYVideoModel> url, boolean cacheWithPlay, int position, File cachePath) {
        return setUp(url, cacheWithPlay, position, cachePath, new HashMap<String, String>());
    }

    /**
     * 设置播放URL
     *
     * @param url           播放url
     * @param cacheWithPlay 是否边播边缓存
     * @param position      需要播放的位置
     * @param cachePath     缓存路径，如果是M3U8或者HLS，请设置为false
     * @param mapHeadData   http header
     * @return
     */
    public boolean setUp(List<GSYVideoModel> url, boolean cacheWithPlay, int position, File cachePath, Map<String, String> mapHeadData) {
        return setUp(url, cacheWithPlay, position, cachePath, mapHeadData, true);
    }

    /**
     * 设置播放URL
     *
     * @param url           播放url
     * @param cacheWithPlay 是否边播边缓存
     * @param position      需要播放的位置
     * @param cachePath     缓存路径，如果是M3U8或者HLS，请设置为false
     * @param mapHeadData   http header
     * @param changeState   切换的时候释放surface
     * @return
     */
    protected boolean setUp(List<GSYVideoModel> url, boolean cacheWithPlay, int position, File cachePath, Map<String, String> mapHeadData, boolean changeState) {
        mUriList = url;
        mPlayPosition = position;
        mMapHeadData = mapHeadData;
        GSYVideoModel gsyVideoModel = url.get(position);
//        boolean set = setUpLazy(gsyVideoModel.getUrl(), cacheWithPlay, cachePath, mapHeadData, gsyVideoModel.getTitle());
        boolean set = setUp(gsyVideoModel.getUrl(), cacheWithPlay, cachePath, gsyVideoModel.getTitle(), changeState);
        return set;
    }
    @Override
    protected void cloneParams(GSYBaseVideoPlayer from, GSYBaseVideoPlayer to) {
        super.cloneParams(from, to);
        MultiSampleVideo sf = (MultiSampleVideo) from;
        MultiSampleVideo st = (MultiSampleVideo) to;
        st.mPlayPosition = sf.mPlayPosition;
        st.mUriList = sf.mUriList;
    }

    @Override
    public void onCompletion() {
//        releaseNetWorkState();
        if (mPlayPosition < (mUriList.size())) {
            return;
        }
        super.onCompletion();
    }

    @Override
    public void onAutoCompletion() {
        if (playNext()) {
            return;
        }
        super.onAutoCompletion();
    }
    /**
     * 开始状态视频播放，prepare时不执行  addTextureView();
     */
    @Override
    protected void prepareVideo() {
        super.prepareVideo();
        if (mHadPlay && mPlayPosition < (mUriList.size())) {
            setViewShowState(mLoadingProgressBar, VISIBLE);
            if (mLoadingProgressBar instanceof ENDownloadView) {
                ((ENDownloadView) mLoadingProgressBar).start();
            }
        }
    }


    /**
     * 播放下一集
     *
     * @return true表示还有下一集
     */
    public boolean playNext() {
        if (mPlayPosition < (mUriList.size() - 1)) {
            mPlayPosition += 1;
            GSYVideoModel gsyVideoModel = mUriList.get(mPlayPosition);
            mSaveChangeViewTIme = 0;
            setUp(mUriList, mCache, mPlayPosition, null, mMapHeadData, false);
            if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) {
                mTitleTextView.setText(gsyVideoModel.getTitle());
            }
            startPlayLogic();
            return true;
        }
        return false;
    }
}

**Comment by yanlianhanlin** [comment]
大佬，列表播放问题解决了，每当列表视频播放完成之后我重置mPlayPosition数值重新播放列表出现了只有声音没有图像的问题，请问这个怎么解决？

**Comment by CarGuo** [comment]
有声音没画面说明surface没设置成功，你看看列表播放里的每次播放下一个的逻辑看看

**Comment by yanlianhanlin** [comment]
我就按照ListGSYVideoPlayer playnext方法写的
`
 @Override
    public void onAutoCompletion() {
        if (playNext()) {
            return;
        }else {
            if(mUriList.size()>1){
                mPlayPosition = mUriList.get(0).getType();
                playNext();
            }else {
                mSaveChangeViewTIme = 0;
                setUp(mUriList, mCache, mPlayPosition-mUriList.get(0).getType(), null, mMapHeadData, true);
                startPlayLogic();
            }
        }
        super.onAutoCompletion();
    }  
public boolean playNext() {
        if (mPlayPosition < (mUriList.size() - 1+mUriList.get(0).getType())) {
            mPlayPosition = mPlayPosition+1;
            GSYVideo gsyVideoModel = mUriList.get(mPlayPosition-mUriList.get(0).getType());
            mSaveChangeViewTIme = 0;
            setUp(mUriList, mCache, mPlayPosition-mUriList.get(0).getType(), null, mMapHeadData, false);
            if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) {
                mTitleTextView.setText(gsyVideoModel.getTitle());
            }
            startPlayLogic();
            return true;
        }
        return false;
    }`
还需要设置什么东西吗？

**Comment by yanlianhanlin** [comment]
我就按照ListGSYVideoPlayer playnext方法写的还需要设置什么东西吗？
‘’@Override public void onAutoCompletion() { if (playNext()) { return; }else { if(mUriList.size()>1){ mPlayPosition = mUriList.get(0).getType(); playNext(); }else { mSaveChangeViewTIme = 0; setUp(mUriList, mCache, mPlayPosition-mUriList.get(0).getType(), null, mMapHeadData, true); startPlayLogic(); } } super.onAutoCompletion(); } public boolean playNext() { if (mPlayPosition < (mUriList.size() - 1+mUriList.get(0).getType())) { mPlayPosition = mPlayPosition+1; GSYVideo gsyVideoModel = mUriList.get(mPlayPosition-mUriList.get(0).getType()); mSaveChangeViewTIme = 0; setUp(mUriList, mCache, mPlayPosition-mUriList.get(0).getType(), null, mMapHeadData, false); if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) { mTitleTextView.setText(gsyVideoModel.getTitle()); } startPlayLogic(); return true; } return false; }

**Comment by yanlianhanlin** [comment]
我是按照ListGSYVideoPlayer中playNext方式写的，还需要配置什么吗？
`   @Override
    public void onAutoCompletion() {
        if (playNext()) {
            return;
        }else {
            if(mUriList.size()>1){
                mPlayPosition = mUriList.get(0).getType();
                playNext();
            }else {
                mSaveChangeViewTIme = 0;
                setUp(mUriList, mCache, mPlayPosition-mUriList.get(0).getType(), null, mMapHeadData, true);
                startPlayLogic();
            }
        }
        super.onAutoCompletion();
    }`

`   public boolean playNext() {
        if (mPlayPosition < (mUriList.size() - 1+mUriList.get(0).getType())) {
            mPlayPosition = mPlayPosition+1;
            GSYVideo gsyVideoModel = mUriList.get(mPlayPosition-mUriList.get(0).getType());
            mSaveChangeViewTIme = 0;
            setUp(mUriList, mCache, mPlayPosition-mUriList.get(0).getType(), null, mMapHeadData, false);
            if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) {
                mTitleTextView.setText(gsyVideoModel.getTitle());
            }
            startPlayLogic();
            return true;
        }
        return false;
    }`

**Comment by yanlianhanlin** [comment]
`  @Override
    public void onAutoCompletion() {
        if (playNext()) {
            return;
        }else {
            if(mUriList.size()>1){
                mPlayPosition = mUriList.get(0).getType();
                playNext();
            }else {
                mSaveChangeViewTIme = 0;
                setUp(mUriList, mCache, mPlayPosition-mUriList.get(0).getType(), null, mMapHeadData, true);
                startPlayLogic();
            }
        }
        super.onAutoCompletion();
    }`
`  /**
     * 播放下一集
     *
     * @return true表示还有下一集
     */
    public boolean playNext() {
        if (mPlayPosition < (mUriList.size() - 1+mUriList.get(0).getType())) {
            mPlayPosition = mPlayPosition+1;
            GSYVideo gsyVideoModel = mUriList.get(mPlayPosition-mUriList.get(0).getType());
            mSaveChangeViewTIme = 0;
            setUp(mUriList, mCache, mPlayPosition-mUriList.get(0).getType(), null, mMapHeadData, false);
            if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) {
                mTitleTextView.setText(gsyVideoModel.getTitle());
            }
            startPlayLogic();
            return true;
        }
        return false;
    }`

**Comment by yanlianhanlin** [comment]
`  /**
     * 播放下一集
     *
     * @return true表示还有下一集
     */
    public boolean playNext() {
        if (mPlayPosition < (mUriList.size() - 1+mUriList.get(0).getType())) {
            mPlayPosition = mPlayPosition+1;
            GSYVideo gsyVideoModel = mUriList.get(mPlayPosition-mUriList.get(0).getType());
            mSaveChangeViewTIme = 0;
            setUp(mUriList, mCache, mPlayPosition-mUriList.get(0).getType(), null, mMapHeadData, false);
            if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) {
                mTitleTextView.setText(gsyVideoModel.getTitle());
            }
            startPlayLogic();
            return true;
        }
        return false;
    }`

**Comment by yanlianhanlin** [comment]
大佬我对比了两个类没找到问题原因，应该如何解决啊

**Comment by CarGuo** [comment]
自定义的组合，只能说自己多调试了
