### ISSUE TITLE
question

### ISSUE THREAD

**Issue by riseLishan** [CarGuo/GSYVideoPlayer#1406]
我用的就是这个https://github.com/DingMouRen/LayoutManagerGroup，但是用RecyclerView滑动下一个全屏的item时，并不会全屏播放 @CarGuo ，往上滑，上边的视频可以自动播放，往下滑不可以自动播放 @CarGuo

**Comment by CarGuo** [comment]
自动播放demo中有啊

**Comment by riseLishan** [comment]
已解决
