### ISSUE TITLE
setneedshowwifitip怎么无效？切换到移动数据不会弹窗！

### ISSUE THREAD

**Issue by lly7690** [CarGuo/GSYVideoPlayer#1409]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

setneedshowwifitip怎么无效？切换到移动数据不会弹窗！

## 问题机型/系统：
小米mix2s

## Demo中的复现步骤

option或播放器实例设置setneedshowwifitip为TRUE，切换到移动数据不会弹窗（开始/继续播放，播放中切换到移动数据）！

**Comment by CarGuo** [comment]
demo中哪个页面？cache是否为false

**Comment by lly7690** [comment]
cache为TRUE

**Comment by lly7690** [comment]
自己设的方法

**Comment by lly7690** [comment]
还有怎么设播放按钮的监听？

**Comment by CarGuo** [comment]
cache为true都缓存了，都不走流量了怎么提示。
问题的话请在demo复现。
播放按键的监听你可以继承后自己添加。

**Comment by lly7690** [comment]
缓存是存在当前APP里还是APP目录外的SD卡其它路径？我清了缓存再进也没提示呀。

**Comment by CarGuo** [comment]
默认是在app内的data/data下，你断点看下为什么不走就知道啦

**Comment by lly7690** [comment]
哦
