### ISSUE TITLE
可以播放.swf文件吗？

### ISSUE THREAD

**Issue by wahyip** [CarGuo/GSYVideoPlayer#141]
网络地址我尝试换为一个网络swf文件地址，但是播放不了，请问可以播放swf文件吗？

**Comment by CarGuo** [comment]
swf当前so是不支持的，如果需要支持，需要你自己编译so，加载swf的编译配置。替换项目中的so。

**Comment by kushanmao** [comment]
编译支持swf，是否还需要adobe支持

**Comment by CarGuo** [comment]
@kushanmao 这需要ffmpeg的支持问题，对于swf目前不是很了解。

**Comment by kushanmao** [comment]
好的，谢谢。
我想问一下，对于目前的Android系统，播放flv，swf，是否可以实现或者说有没有什么好的建议

**Comment by CarGuo** [comment]
android播放flv没问题，因为已经有人做了在此基础上重新编译so支持播放flv了。关键还是flv需要支持的播放类型是哪些，比如是mpeg，amr的还是acc，h264之类的，后者是目前就支持了，你支持的格式类型和协议越多，so就会越大，至于swf的，还真没研究。

**Comment by kushanmao** [comment]
ths
