### ISSUE TITLE
多媒体平板播放视频出现严重的延迟问题（声音字幕不同步）

### ISSUE THREAD

**Issue by Achenglove** [CarGuo/GSYVideoPlayer#1410]
## 问题描述：

多媒体平板播放视频出现严重的延迟问题（该平板是系统：window+android 5.0 双系统）

## 问题机型/系统：

会议平板，android系统5.0

**Comment by Achenglove** [comment]
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 25);
        List list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
这段丢帧处理的代码实在设置播放地址之前设置吗？具体设置位置是？

**Comment by CarGuo** [comment]
这个是全局的，参数具体可根据实际情况调节。
