### ISSUE TITLE
使用 6.0.0-beta 

### ISSUE THREAD

**Issue by xiaozhang-carl** [CarGuo/GSYVideoPlayer#1411]
该版本需要清除布局文件中的GSYImageCover，please remove GSYImageCover from your layout

**Comment by CarGuo** [comment]
？？？这个控件应该很多个大版本之前就需要去掉了吧。

**Comment by xiaozhang-carl** [comment]
是需要自定义布局，然后去掉吗

**Comment by CarGuo** [comment]
这个就是说你的layout文件中有GSYImageCover？？
