### ISSUE TITLE
全屏状态下 布局TEXTVIEW监听设置无效！不走点击事件监听代码！

### ISSUE THREAD

**Issue by lly7690** [CarGuo/GSYVideoPlayer#1415]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

全屏状态下 布局TEXTVIEW监听设置无效！

## 问题机型/系统：

mix2s

## Demo中的复现步骤

全屏状态下 布局TEXTVIEW监听设置无效！设了监听，不走监听代码！
比如全屏选集按钮，点击无反应！不走点击事件监听代码！

**Comment by CarGuo** [comment]
getcurrentplayer

或者参考源码 cloneParams 方法，基础重载

**Comment by zung** [comment]
同样的问题，全屏时 布局layout_bottom中自定义的按钮设置点击事件无效，非全屏时有效
