### ISSUE TITLE
用LISTGSYVIDEOPLAYER全屏选集（切换剧集）怎么有声音然后图像卡住？按返回键ANR

### ISSUE THREAD

**Issue by lly7690** [CarGuo/GSYVideoPlayer#1419]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

用LISTGSYVIDEOPLAYER全屏选集（切换剧集）怎么有声音然后图像卡住？按返回键ANR

## 问题机型/系统：
mix2s

## Demo中的复现步骤

用LISTGSYVIDEOPLAYER全屏选集（切换剧集）怎么有声音然后图像卡住？按返回键ANR

**Comment by CarGuo** [comment]
demo中是否正常？如果是手动调用，是否 getCurrentPlayer.XXXXX

**Comment by lly7690** [comment]
getcurrentplayer后面用啥方法？

**Comment by lly7690** [comment]
DEMO中没有全屏切换选集的

**Comment by CarGuo** [comment]
大哥，看源码啊，`ListGSYVideoPlayer` 里不就有 `playNext `么，
demo中不是有 
`((ListGSYVideoPlayer) detailPlayer.getCurrentPlayer()).playNext();` 么

多看代码，多看源码，多断点调试问题······

**Comment by lly7690** [comment]
哦
