### ISSUE TITLE
能否点击封面图直接直接展开window层全屏播放呢？

### ISSUE THREAD

**Issue by yuwoquan** [CarGuo/GSYVideoPlayer#1420]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

例如点击一个视频封面图。设置url，跟tilte进去直接window播放。
找到startWindowFullscreen()，但是没有设置url进去的。

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
这个你自己也可以加上，不过···

你这样的需求，还不如一个普通列表，然后点击打开一个像playActivity的页面播放就好了·····
