### ISSUE TITLE
有办法视频预加载吗

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1423]
比如列表视频播放,提前加载几秒中但不播放,当播放的时候有秒开的效果,大神有相关实现方法吗

**Comment by CarGuo** [comment]
并没有，你可以参考proxyCache，自己做一套预拉流的逻辑。

**Comment by zkywalker** [comment]
可以使用AndroidVideoCache实现预加载逻辑

**Comment by darkrevier** [comment]
@CarGuo @zkywalker 好的👌 3q

**Comment by darkrevier** [comment]
@zkywalker 老哥你做过吗 具体怎么能实现啊

**Comment by darkrevier** [comment]
@CarGuo  是在ProxyCacheManager中处理吗
