### ISSUE TITLE
rmvb播放不了是因为什么？

### ISSUE THREAD

**Issue by Snow13674282512** [CarGuo/GSYVideoPlayer#1424]
小米6https://wjwj8888.oss-cn-beijing.aliyuncs.com/video/%E9%98%B3%E5%85%89%E7%94%B5%E5%BD%B1www.ygdy8.com.%E6%AD%BB%E4%BE%8D2.HD.720p.%E9%9F%A9%E7%89%88%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97%E5%B9%95.rmvb这个是视频链接

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md  没编译支持
