### ISSUE TITLE
画面变形

### ISSUE THREAD

**Issue by JeremyHwc** [CarGuo/GSYVideoPlayer#1432]
我通过下面这行代码将视频画面显示比例调整成16:9
GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_16_9);
结果视频变形了，下面这个是图片
![1](https://user-images.githubusercontent.com/19958785/45281254-df456400-b509-11e8-9698-af13503b599b.jpg)

然后我注释掉这行代码//GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_16_9);
视频就正常了
![default](https://user-images.githubusercontent.com/19958785/45281360-30edee80-b50a-11e8-92d9-212f99a8f4fb.jpg)

**Comment by CarGuo** [comment]
竖屏的视频你设置16:9充满肯定是这样的····
