### ISSUE TITLE
完全参照Demo，但是onConfigurationChanged时会偶发调用onPause导致崩溃

### ISSUE THREAD

**Issue by MrWx1314** [CarGuo/GSYVideoPlayer#1436]
## 问题描述：

完全参照Demo，但是onConfigurationChanged时会偶发调用onPause导致崩溃

## 问题机型/系统：

全机型

**Comment by CarGuo** [comment]
manifest中是否配置了？

**Comment by MrWx1314** [comment]
找到原因了，manifest中设置的style与onConfigurationChanged互冲。感谢。
