### ISSUE TITLE
播放本地视频卡顿及加载时间过长

### ISSUE THREAD

**Issue by tiandawu** [CarGuo/GSYVideoPlayer#1439]
## 问题描述：
使用ijkplayer播放器内核
1、本地视频几百兆，加载时间过长
2、播放一段时间会出现卡顿现象

## 问题机型/系统：
系统：Android 4.4

**Comment by CarGuo** [comment]
4.4的算是老机器了把，卡顿挺正常的。
你可以试试问题集锦中的方法，比如设置丢帧，修改缓冲区等等

或者切换到exoplayer内核试试。

**Comment by tiandawu** [comment]
切换到exoplayer和systemplayer内核遇到乱码文件视频就不能播放，exoplayer为啥本地视频大一点，加载时间会很长。

**Comment by CarGuo** [comment]
这个和视频的关键帧和缓冲区有关系。  乱码文件是说路径吗？如果是路径的话可以encodce试试

**Comment by fanOfDemo** [comment]
4.4使用systemplayer不会卡顿，但是会出现宽度被拉伸的情况，
需要使用：
CustomGSYVideoPlayer extends NormalGSYVideoPlayer
CustomRenderView extends GSYRenderView
CustomTextureSurface extends SurfaceView
解决宽度问题；
5.0以上使用exoplayer。
我是这么解决的，以上经验供参考

**Comment by CarGuo** [comment]
@fanOfDemo systemplayer 导致宽度拉伸的有测试url提供下吗？

**Comment by fanOfDemo** [comment]
@CarGuo 随便下载一个抖音竖屏视频就能复现了
