### ISSUE TITLE
小米6手机安装demo后体验时发生内存泄漏，无缝切换按钮有时点击闪退

### ISSUE THREAD

**Issue by xuefeiyao** [CarGuo/GSYVideoPlayer#1441]
![1](https://user-images.githubusercontent.com/33013324/45416997-bd87e080-b6b3-11e8-9e56-8dcee278736e.png)
![2](https://user-images.githubusercontent.com/33013324/45417003-beb90d80-b6b3-11e8-8365-3a009597f423.png)
![3](https://user-images.githubusercontent.com/33013324/45417006-bfea3a80-b6b3-11e8-8961-7df4fce780b6.png)

**Comment by CarGuo** [comment]
@xuefeiyao 你这个泄漏应该是demo中的Glide泄漏，不是库泄漏，所以不用担心。
至于你的崩溃，你是什么android版本，因为切换到详情的demo用的是自动的android ActivityOptionsCompat 的 scene效果，低版本可能不存在这个。

**Comment by xuefeiyao** [comment]
android7.1.1
