### ISSUE TITLE
关于seekbar和current时间问题

### ISSUE THREAD

**Issue by bingdu0** [CarGuo/GSYVideoPlayer#1445]
## 问题描述：
      1.自定义布局，不写<SeekBar android:id="@+id/progress"/>,current时间不刷新,因为直播没有 
         seekbar的进度。
      2.怎么把current 时间的格式改成00:00:00  ，现在是00:00
## 问题机型/系统：

     华为mate8

## Demo中的复现步骤
     Demo 中的SampleVideo中的自定义布局sample_video.xml,把seekBar 注释掉问题1就会复现

**Comment by CarGuo** [comment]
你继承后，可以重写 setProgressAndTime 等方法
