### ISSUE TITLE
在调用release时候发生ANR

### ISSUE THREAD

**Issue by wisonic** [CarGuo/GSYVideoPlayer#1446]
## 问题描述：

在调用release时候发生ANR

## 问题机型/系统：

三星 SM-J200G等

问题代码：(如果有)

## 问题log

tv.danmaku.ijk.media.player.IjkMediaPlayer._release(Native method)

线上ANR统计发现大量ANR是因为这个问题导致。开发过程中又无法重现。请问这里为啥会导致ANR? 有解决思路吗？谢谢！

**Comment by CarGuo** [comment]
目前我也没重现这个问题，一般release不会导致这个

**Comment by Heber-xu** [comment]
这是一个比较高概率的问题，在华为手机上非常容易出现，oppo reno上面测试也容易出现，问题应该是出在Ijkplayer的release上面。我的问题是网络不可用的时候加载在线视频，然后退出时，在fragment的onDestory时候release，然后发生ANR。参考https://github.com/bilibili/ijkplayer/issues/3456

**Comment by CarGuo** [comment]
@Heber-xu 这个一般是异步释放和快速播放之间的导致的，推荐用两个内核或者设置一个flag用于延迟。或者切换到exoplayer模式内核

**Comment by beijingling** [comment]
使用异步线程释放可嘛
