### ISSUE TITLE
视频切换到全屏或者小窗口会黑屏1到2秒，但声音继续

### ISSUE THREAD

**Issue by clark0704** [CarGuo/GSYVideoPlayer#145]
视频切换到全屏或者小窗口会黑屏1到2秒，但声音继续，1到2秒后视频画面又出现了？从全屏退出也会这样屏幕黑个1到2秒，然后画面会回归正常，原因是什么（网络环境很好）

**Comment by CarGuo** [comment]
demo？你这种情况一般是开了硬解码或者切换到了exo模式

**Comment by clark0704** [comment]
问题是我没有开硬解码，也没有切换到exo模式，何解呢。

**Comment by clark0704** [comment]
问题是我没有开硬解码，也没有切换到exo模式，何解呢。
