### ISSUE TITLE
（视频小窗自定义看这里）ListVideo2Activity的视频小窗（非全局悬浮）我想定制下小窗的View样式，作者大大能不能提供下实现思路

### ISSUE THREAD

**Issue by xiaofei-dev** [CarGuo/GSYVideoPlayer#1453]
ListVideo2Activity的视频小窗我想定制下小窗的View样式，还有视频小窗出现时的初始位置，作者大大能不能提供下实现思路

**Comment by xiaofei-dev** [comment]
我还想往小窗里加个按钮，这样还需要控制小窗子View的点击事件

**Comment by CarGuo** [comment]
继承你使用的类，然后参考 `GSYBaseVideoPlayer` 的源码，重载下方方法等

```
cloneParams

showSmallVideo

hideSmallVideo

setSmallVideoTextureView

getLayoutId --> 根据flag选择布局
```

**Comment by xiaofei-dev** [comment]
> 继承你使用的类，然后参考 `GSYBaseVideoPlayer` 的源码，重载下方方法等
> 
> ```
> cloneParams
> 
> showSmallVideo
> 
> hideSmallVideo
> 
> setSmallVideoTextureView
> 
> getLayoutId --> 根据flag选择布局
> ```
嗯我继承的 StandardGSYVideoPlayer，重载以上方法就能实现是哈

**Comment by xiaofei-dev** [comment]
@CarGuo 嗯我继承的 StandardGSYVideoPlayer，重载以上方法就能实现是哈

**Comment by xiaofei-dev** [comment]
> @CarGuo 嗯我继承的 StandardGSYVideoPlayer，重载以上方法就能实现是哈

@CarGuo 嗯我继承的 StandardGSYVideoPlayer，重载以上方法就能实现是哈

**Comment by xiaofei-dev** [comment]
> 继承你使用的类，然后参考 `GSYBaseVideoPlayer` 的源码，重载下方方法等
> 
> ```
> cloneParams
> 
> showSmallVideo
> 
> hideSmallVideo
> 
> setSmallVideoTextureView
> 
> getLayoutId --> 根据flag选择布局
> ```
@CarGuo 嗯我继承的 StandardGSYVideoPlayer，重载以上方法就能实现是哈

**Comment by xiaofei-dev** [comment]
没发现有名为 getLayoutId  的方法

**Comment by CarGuo** [comment]
```
 public int getLayoutId()
```
肯定有

**Comment by xiaofei-dev** [comment]
> ```
>  public int getLayoutId()
> ```
> 肯定有

哦哦这个方法啊，那我明白了，我去放手实践下，作者大大先别关这个Issue哈，做好了来这边告诉你

**Comment by xiaofei-dev** [comment]
NestedScrollView 顶部我放了个视频播放View，往下滑的时候，视频小窗能正常显示出来，但往上滑回去的时候手指头拖着慢慢往上滑时小窗能正常消失，大窗能正常显示，然而我fling快速往上滑（fling效果）的时候报异常了：
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
我如果延迟调用smallVideoToNormal()，就没有异常了，小窗正常消失，但大窗没正常显示回播放状态！
`scroll.setOnScrollChangeListener { v: NestedScrollView?, scrollX: Int, scrollY: Int, oldScrollX: Int, oldScrollY: Int ->
            myLogger.d("scrollY:$scrollY,,,oldScrollY$oldScrollY")
            if (scrollY > gsyVideoPlayer.measuredHeight){
                mSlidingTabLayoutTop.visibility = View.VISIBLE
                //小窗口
                if (!smallVideoHelper.isSmall) {
                    smallVideoHelper.showSmallVideo(Point(dip(187), dip(105)), false, true)
                }
            }else{
                mSlidingTabLayoutTop.visibility = View.GONE
                if (smallVideoHelper.isSmall){
                    smallVideoHelper.smallVideoToNormal()//这里我如果快速滑上去就会崩溃
                }
            }
        }`
试了公司里多个不同型号和版本的测试机均会出现上面的问题，求解答~

**Comment by xiaofei-dev** [comment]
``

**Comment by xiaofei-dev** [comment]
表述有误，应该是 NestedScrollView 的 onTouchEvent 方法 接收到 MotionEvent.ACTION_UP 事件后执行的某行代码导致这个问题的发生，
```
Handler(Looper.getMainLooper()).post{
                        smallVideoHelper.smallVideoToNormal()
                    }
```
这样不会发生上面所说的异常崩溃了，但是无法正常切换到大窗！

**Comment by xiaofei-dev** [comment]
已基本解决上面遇到的问题，用的方式可能不太优雅！明天我把功能全部弄好了再贴出代码

**Comment by xiaofei-dev** [comment]
关于非全局悬浮视频小窗自定义问题大家在这里问我都可以！放假有时间了我再在这里总结一下~

**Comment by CarGuo** [comment]
good job
