### ISSUE TITLE
6.0.0-beta 缓存头不存在的问题依旧出现

### ISSUE THREAD

**Issue by Pancts** [CarGuo/GSYVideoPlayer#1455]
跟 #1407 的问题一致

`ProxyCacheManager ` 中 `UserAgentHeadersInjector addHeaders` 被正确调用了

但是 `injectCustomHeaders` 里 `Map<String, String> extraHeaders = headerInjector.addHeaders(url);` 返回的是空的

缓存头信息是用setMapHeadData方法添加的Map数据

**Comment by Pancts** [comment]
android不太熟悉哈 还是追了一下代码
问题貌似出现在 `ProxyCacheManager` 中,  `mMapHeadData` 改成静态变量就好了.

**Comment by CarGuo** [comment]
是的，多谢提供issue
