### ISSUE TITLE
6.0 exo m3u8 有声音没画面

### ISSUE THREAD

**Issue by 995518790** [CarGuo/GSYVideoPlayer#1458]
## 问题描述：

PlayerFactory.setPlayManager(new Exo2PlayerManager()); 
CacheFactory.setCacheManager(new ExoPlayerCacheManager());
用了6.0的exo m3u8 有声音没画面，缓存有了，
用StandardGSYVideoPlayer，
videoPlayer.setUp(url,true,"");
videoPlayer.startPlayLogic();
ijk的so文件你项目里拿来的。
大佬救我，没画面啊

## 问题机型/系统：

例如 真机 华为nova3  Android8.1

**Comment by CarGuo** [comment]
一个妹子弹琵琶的视频？？我试了DEMO下
```
PlayerFactory.setPlayManager(new Exo2PlayerManager());
CacheFactory.setCacheManager(new ExoPlayerCacheManager());
```
可以正常呀

**Comment by 995518790** [comment]
哪个demo

**Comment by CarGuo** [comment]
我在detailPlayer里试的

**Comment by 995518790** [comment]
大佬，还想问个问题，缓存默认路径?

**Comment by CarGuo** [comment]
你看demo的cleanCache就知道了

**Comment by 995518790** [comment]
找不到啊

**Comment by CarGuo** [comment]
GSYVideoManager.instance().clearAllDefaultCache(MainActivity.this); 一步一步找进去

**Comment by 995518790** [comment]
谢谢
