### ISSUE TITLE
setSeekOnStart()无效，跳转进度问题

### ISSUE THREAD

**Issue by breewf** [CarGuo/GSYVideoPlayer#1459]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

使用exo和ExoPlayerCacheManager()缓存模式，startPlayLogic()前调用setSeekOnStart()有效，可跳转正确位置但loading时间较长。

使用ijk且使用ProxyCacheManager()缓存模式，setSeekOnStart()方法无效，仍会从头开始播放。

使用 enable-accurate-seek 方案，跳转位置正确但视频seek的时候就会卡很久(2-3s)
使用seek-at-start方案跳转进度要么无效从头播放，要么进度不正常（比正常进度晚几秒）。

求解！

## 问题机型/系统：

真机 oppoR9s Android6.0

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
因为一个是ffmpeg，一个是mediacodec，ffmpeg下的ijk的关键帧查找问题。

ijk下你还可以试试以下的，播放前设置，不过这个是全局的。

```
VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", startPosition);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by breewf** [comment]
此方案进度值不正常，要么跳转到开始，要么比正常进度晚几秒，比如我设置的进度是10秒，他会调到6s左右。

**Comment by CarGuo** [comment]
正常，因为关键帧，所以如上才会有 `enable-accurate-seek` 。
所以这就是 medacodec 和 ffmpeg 的不同。
折中选择下吧。

**Comment by breewf** [comment]
enable-accurate-seek 可以跳转正确，但是跳转很慢，3秒左右，这什么原因造成的，有解决方案吗？

**Comment by CarGuo** [comment]
这个是视频的关键帧数量导致的，如果有兴趣，可以去了解下 ffmpeg 和 ffplay

**Comment by breewf** [comment]
好的，感谢回复。
