### ISSUE TITLE
页面跳转的问题

### ISSUE THREAD

**Issue by SerBad** [CarGuo/GSYVideoPlayer#1460]
## 问题描述：
 两个activity ，A和B都有集成StandardGSYVideoPlayer，然后从A跳到B的时候，
在A页面离开时调用.onVideoPause(); ，这个时候getCurrentState()获取到的是5
在B调用setup(String url, boolean cacheWithPlay, String title)方法，然后开始播放，调 startPlayLogic();
然后，就会导致A页面的.getCurrentState()在onStop方法里面变为了0.

**Comment by CarGuo** [comment]
正常，因为普通模式播放器内核只有一个。
所以如果你需要自己再A页面中最播放状态的保存。比如onPause的时候保存了播放中的状态和播放时长，
在恢复的时候设置setOnstart之后重新startplaylogic

**Comment by SerBad** [comment]
就是说，这个时候是需要我自己去处理的，对吧？

**Comment by CarGuo** [comment]
是的

**Comment by CarGuo** [comment]
good luck。
