### ISSUE TITLE
返回播放视频，出现有声音无画面情况

### ISSUE THREAD

**Issue by wisonic** [CarGuo/GSYVideoPlayer#1461]
使用ijk播放器，在抖音模式连续播放情况下，回滑播放，回滑到第五个以上，在华为P20上出现有声音没画面的问题。

奇怪的是代码层面切到exo然后播放，就不会出现这个问题了。而且切换回ijk也不会。

这块是否和使用了HttpProxyCache有关？

麻烦帮忙定位一下这个问题，多谢了！

**Comment by CarGuo** [comment]
有声音无画面和HttpProxyCache应该没关系，HttpProxyCache有关系的话连声音都会没有。
如果是正常能播放，但是切换会出现不能播放，问题应该出现在surface没正常设置进去

**Comment by wisonic** [comment]
我最开始也是判断surface被回收导致，怎么判断player中的surface是否可用，如果不可用怎么动态添加surface呢？

奇怪的是切换播放器后就不出现了，所以现在不知道该往哪个方向分析问题了。

**Comment by wisonic** [comment]
发现出问题的地方onSurfaceAvailable没有走，但是为啥有时候走有时候不走呢。@CarGuo

**Comment by wisonic** [comment]
视频页面使用了Lottie动画，发现这个问题和动画有关系，去掉后视频能正常显示画面了。多谢CarGruo~
