### ISSUE TITLE
关于播放器在非Activity中使用崩溃的问题

### ISSUE THREAD

**Issue by qinlang122** [CarGuo/GSYVideoPlayer#1462]
## 问题描述：

GSYVideoPlayer类中的第410行代码：((Activity) getContext()).getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
进行的强制类型转换，导致在非Activity中无法使用，如双屏机器的双屏异显，副屏使用的继承自Dialog的Presentation进行显示。这样就没办法在副屏上面显示视频。

## 问题机型/系统：

开发板，双屏设备

问题代码：
```
((Activity) getContext()).getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
```

**Comment by CarGuo** [comment]
确实，因为它会通过context去查找依附的activity，如果你有需要，可以继承后重写方法即可

**Comment by qinlang122** [comment]
还有就是，找半天好像并没有找到可以设置静音的方法。。。

**Comment by CarGuo** [comment]
搜索 setNeedMute
