### ISSUE TITLE
回调异常的疑问

### ISSUE THREAD

**Issue by dongdaniqng** [CarGuo/GSYVideoPlayer#1465]
## 问题描述：

我给播放器一个错的mp4播放地址，播放器的onError回调不会回调，请问这个是我的问题还是播放器设计如此？还有如果我给播放器一个正确的mp4地址，播放器的onPrepared也不会调用，不论错误还是正常
的地址都会走onComplete
## 问题机型/系统：

华为p10 p

## Demo中的复现步骤

问题代码：(如果有)
这个是测试代码：
   video_player.setUp(source1, false, "")
   video_player.gsyVideoManager.setListener(this)
   video_player.startPlayLogic()

    override fun onAutoCompletion() {
        "1".log()
    }

    override fun onPrepared() {
        "2".log()
    }

    override fun onCompletion() {
        "3".log()
    }

    override fun onVideoPause() {
        "4".log()
    }
 。。。
## 问题log（如果有）

TAG: http://clips.vorwaerts-gmbh.de/big_buck_bunny1.mp4
09-20 16:11:44.749 13145-13145 E/TAG: 3
09-20 16:11:48.766 13145-13539 E/IJKMEDIA: http://clips.vorwaerts-gmbh.de/big_buck_bunny1.mp4: Server returned 404 Not Found
09-20 16:11:48.769 13145-13529 E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by justziyang** [comment]
您好，您咋解决的啊？问题怎么关了~我也遇到了这个问题

**Comment by dongdaniqng** [comment]
不是这个回调，方法用错了



---原始邮件---
发件人: "justziyang"<notifications@github.com&gt;
发送时间: 2020年3月11日(周三) 下午2:17
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送: "dongdanqing"<wsddq@foxmail.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题: Re: [CarGuo/GSYVideoPlayer] 回调异常的疑问 (#1465)



您好，您咋解决的啊？问题怎么关了~我也遇到了这个问题
