### ISSUE TITLE
设置视频后台播放

### ISSUE THREAD

**Issue by whj33** [CarGuo/GSYVideoPlayer#1467]
请问怎么设置视频后台播放

**Comment by CarGuo** [comment]
不用设置，默认支持

**Comment by whj33** [comment]
请问我在页面A创建了一个Videoplayer的实例   然后跳到了页面B   怎么拿到页面A的videoplayer的实例

**Comment by CarGuo** [comment]
这个不属于项目问题了

**Comment by whj33** [comment]
就是没有办法拿到了吗？

**Comment by CarGuo** [comment]
这个属于实现的逻辑问题。你需要拿到做什么
view层一般是不建议跨Activity共享的。
如果是播放内核的，你可以通过Mamager拿到对应的mediaplyer。

**Comment by whj33** [comment]
就是这个videoplayer在后台播放的时候，我想在页面B拿到这个videoplayer的进度做一些操作

**Comment by CarGuo** [comment]
通过Manager拿到imediaplayer接口对象可以获取。
