### ISSUE TITLE
播放后自动停止走到onError方法

### ISSUE THREAD

**Issue by EasonHolmes** [CarGuo/GSYVideoPlayer#1468]
## 问题描述：

播放十几分钟后会自动到onError方法中，
what有可能会是-10000、-1000、-100、 extra 0,没有具体原因

 问题机型/系统：全系统机型

 Demo中的复现步骤

播放视频就会这样：https://om48i4f8o.qnssl.com/lo7K3Gz90T5bHgiXmI-XnAmFAD-u?e=1537549200&token=Qa9nc-s0Ye2U8iHKefkJW4APRQZ_npOKUB9JUO5b:71Pup39xwtpEpBEY0A7mIeEAMMs

**Comment by CarGuo** [comment]
可以试试在exoplayer内核模式下
