### ISSUE TITLE
暂停播放时切换全屏黑屏的问题

### ISSUE THREAD

**Issue by RockXiong** [CarGuo/GSYVideoPlayer#1469]
## 问题描述：

作者您好，我参考demo的DetailListPlayer实现自己的Activity，用的是ListGSYVideoPlayer，在暂停状态下切换横竖屏时会发生黑屏的情况，我仔细看了demo代码，运行发现部分实例也是如此情况(DetailListPlayer)，但一部分又没问题(DetailPlayer)。我对比了代码但是没找着需要在哪做什么设置，请问这个是bug吗还是我要怎么设置它才不会在切换时黑屏呢？

## 问题机型/系统：

小米5

## Demo中的复现步骤

Demo中的DetailListPlayer页面打开后点击播放->暂停->切换横屏会出现这个问题。

**Comment by CarGuo** [comment]
setShowPauseCover 为 true 就可以不黑

**Comment by RockXiong** [comment]
> setShowPauseCover 为 true 就可以不黑

好的，解决了，非常感谢~
