### ISSUE TITLE
弹幕点击问题

### ISSUE THREAD

**Issue by ZzjBeatYou** [CarGuo/GSYVideoPlayer#147]
给弹幕设置点击监听后videoplayer无法响应任何点击事件

**Comment by ZzjBeatYou** [comment]
dalao可以简单说下具体怎么改吗，谢谢了

**Comment by ZzjBeatYou** [comment]
自己弄好了，烈焰弹幕库中DanmakuTouchHelper类改下面这段代码就可以了
 @Override
        public boolean onDown(MotionEvent event) {
            if (danmakuView != null) {
                IDanmakuView.OnDanmakuClickListener onDanmakuClickListener = danmakuView.getOnDanmakuClickListener();
                if (onDanmakuClickListener != null) {
                    IDanmakus clickDanmakus = touchHitDanmaku(event.getX(), event.getY());
                    if (null != clickDanmakus && !clickDanmakus.isEmpty()) {
                        return true;
                    }
                }
            }
            return false;
        }

**Comment by CarGuo** [comment]
多谢你的回复～
