### ISSUE TITLE
希望缓存服务能自定义文件名

### ISSUE THREAD

**Issue by XuQK** [CarGuo/GSYVideoPlayer#1471]
`ProxyCacheManager.newProxy(Context context)`方法中，希望能加上原缓存库的`fileNameGenerator`方法，可以自定义文件名。
因为我们目前的视频播放逻辑是播放的时候，拿视频的源url（不能直接播放）去服务器请求加密过的能播的url，每次请求过来的url都是不一样的，如果不能自定义videoCache的文件名，那缓存就失效了。
还有自定义maxSize和maxFileCount~
望采纳

**Comment by CarGuo** [comment]
已经有支持文件名的
