### ISSUE TITLE
悬浮窗

### ISSUE THREAD

**Issue by yangchong211** [CarGuo/GSYVideoPlayer#1473]
大佬能否将悬浮窗部分的代码封装成一个库，如果使用的其他的视频播放器封装库，也可以快速实现你这种悬浮窗的效果。谢谢

**Comment by CarGuo** [comment]
https://github.com/yhaolpz/FloatWindow

**Comment by dary123** [comment]
> https://github.com/yhaolpz/FloatWindow

这个库使用后，视频控件悬浮后不播放
