### ISSUE TITLE
使用startWindowFullscreen方式全屏遇到的问题

### ISSUE THREAD

**Issue by hanouba** [CarGuo/GSYVideoPlayer#1474]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在使用startWindowFullscreen进行全屏操作时,界面按钮状态选择被重置了,无法保存选择状态;Chronometer的计时器在全屏时也被重置了,无法继续计时; 

## Demo中的复现步骤

问题代码：(如果有)
```

```

## 问题log（如果有）

xxxxxxx

```

**Comment by hanouba** [comment]
小屏幕下,做了个录制功能,带上计时器, 都正常工作;切换到全屏,计时器就重置了时间为0 ,其他一些控件比如所状态选择器,也会被重置,为默认状态;

**Comment by hanouba** [comment]
spPlay.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                spPlay.startWindowFullscreen(getActivity(), true, true);
            }
        });

**Comment by CarGuo** [comment]
参考demo，配置manifest

**Comment by hanouba** [comment]
配置了 没有作用

**Comment by CarGuo** [comment]
参考这个

https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/GSYADVideoPlayer.java

cloneParams：

https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/base/GSYBaseVideoPlayer.java
