### ISSUE TITLE
播放按钮无法替换？

### ISSUE THREAD

**Issue by wenjianxue** [CarGuo/GSYVideoPlayer#1475]
## 问题描述：

播放按钮无法替换？

## 问题机型/系统：

所有

## Demo中的复现步骤
所有

问题代码：(如果有)
```
GSYVideoControlView 类
    /**
     * 获取播放按键
     */
    public View getStartButton() {
        return mStartButton;
    }
```
mStartButton 是View 运行时是ENPlayView，实际上无法更换掉mStartButton的背景。。。

**Comment by CarGuo** [comment]
例如 ：
https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/NormalGSYVideoPlayer.java

这样修改
