### ISSUE TITLE
关于m3u8使用exoplayer能边播边缓存下来：xxx.v3.exo 文件

### ISSUE THREAD

**Issue by zhaoyongjiang** [CarGuo/GSYVideoPlayer#1476]
测试链接：http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8

PlayerFactory.setPlayManager(new Exo2PlayerManager());//EXO模式

CacheFactory.setCacheManager(new ExoPlayerCacheManager());//exo缓存模式，支持m3u8，只支持exo

String cachepath = Environment.getExternalStorageDirectory() + "/tsvideo/cache";

File file = new File(cachepath);

        if (!file.exists()) {
            file.mkdir();
        }

.setCachePath(file)

我在缓存路径中，看到了边播边下的文件：：xxx.v3.exo...是能播放的。。

大佬，你要是做hls缓存，那这个库就完美了。毕竟提前的部分缓存，这个应用场景真的很常用

**Comment by CarGuo** [comment]
hls目前还不支持
