### ISSUE TITLE
普通和全屏不同布局，view为空

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#1477]
重写init方法中  控件通过findviewbyid后为null

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/LandLayoutVideo.java

**Comment by i2863CookieZJ** [comment]
还是空  在init()方法中findviewbyid的控件都是空是什么情况

**Comment by i2863CookieZJ** [comment]
@Override
    protected void init(Context context) {
        super.init(context);
        menuRecycle = findViewById(R.id.menu_recycle);
        netStatus = findViewById(R.id.network_status);
        currentTime = findViewById(R.id.time);
        progressWheel = findViewById(R.id.load_status);
        playError = findViewById(R.id.play_error);
        playNum = findViewById(R.id.person_num);
        playTime = findViewById(R.id.video_time);

        findViewById(getPlayStatusId()).setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mCurrentState == CURRENT_STATE_PAUSE) {
                    clickStartIcon();
                } else {
                    if (NetWorkUtil.isWifi(mContext)) {
                        startPlayLogic();
                    } else {
                        showWifiDialog();
                    }
                }
            }
        });
这里的所有控件都是空

**Comment by CarGuo** [comment]
参考demo啊···

**Comment by CarGuo** [comment]
不是很理解的你问题，你有没有重写getLayoutId？参考demo的自定义实现啊····

**Comment by i2863CookieZJ** [comment]
重写了的 我按照demo写 但是在init中所有自定义的控件都是null

**Comment by i2863CookieZJ** [comment]
![image](https://user-images.githubusercontent.com/23622439/46240132-a5170600-c3d5-11e8-9998-312cd9ae4f8e.png)
我直接使用demo中弹幕的布局 我使用的版本是6.0.0 beta  之前 使用2.1.1的老版一切都ok，现在找不到布局中的控件有可能是什么情况呢？

**Comment by i2863CookieZJ** [comment]
解决了

**Comment by AldenLei** [comment]
@i2863CookieZJ 我也遇见同意的问题，请问怎么解决的啊？
