### ISSUE TITLE
列表页面进入详情页面，回来后列表页面卡主，但是还有声音

### ISSUE THREAD

**Issue by 465857721** [CarGuo/GSYVideoPlayer#1478]
## 问题描述：
列表页面播放，无缝进入详情页面 详情页面用 detailPlayer.setSurfaceToPlay();
播放没有问题 再回来到fragment中， 视频卡主不动了，如何处理？

## 问题机型/系统：

华为 P10 EMUI 8.0.0  Android 8.0.0

## Demo中的复现步骤
列表详情切换

**Comment by CarGuo** [comment]
demo复现？demo中返回列表的时候是故意停止了

**Comment by 465857721** [comment]
仿照demo写的  返回来 需要继续播，但是出现了有声音 无画面的问题

**Comment by 465857721** [comment]
setDisplay(null);
        //同一消息队列中去release
        releaseSurface(surface);
        return true

问题出在这里  我自己想办法解决吧

**Comment by songsh** [comment]
怎么解决的，能分享下吗？
