### ISSUE TITLE
升级了gradle到4.6后 出现, Program type already present: com.danikula.videocache.ByteArraySource","sources":[{}],"tool":"D8"

### ISSUE THREAD

**Issue by zj2050** [CarGuo/GSYVideoPlayer#1479]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

gradle 4.6，
implementation 'com.android.support:appcompat-v7:27.1.1'

implementation 'com.shuyu:GSYVideoPlayer:6.0.0-beta'

出现错误：
AGPBI: {"kind":"error","text":"Program type already present: com.danikula.videocache.ByteArraySource","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

## 问题机型/系统：

Build 编译无法通过

## 问题log（如果有）

AGPBI: {"kind":"error","text":"Program type already present: com.danikula.videocache.ByteArraySource","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
:app:buildInfoGeneratorDebug
FAILURE: Build failed with an exception.
```

**Comment by zj2050** [comment]
@CarGuo  ### **not player issues**  ? 什么意思？

**Comment by CarGuo** [comment]
不是项目问题

**Comment by zj2050** [comment]
@CarGuo 就是在引入 implementation 'com.shuyu:GSYVideoPlayer:6.0.0-beta' 这个后出现的问题，百度了的几种都不行， 有处理方案吗？

**Comment by CarGuo** [comment]
测试正常

**Comment by a4425421** [comment]
原因起冲突了，排除掉就可以编译了

implementation ('com.shuyu:GSYVideoPlayer:6.0.0-beta') {
        exclude module: 'support-v4'
    }

**Comment by zj2050** [comment]
@a4425421 依然是提示：
Program type already present: com.danikula.videocache.ByteArrayCache

**Comment by zj2050** [comment]
@a4425421 肯定是和这个冲突了，但我肯定无法修改某个库，所以想了解如何处理和屏蔽，谢谢
