### ISSUE TITLE
GSYVideoBaseManager--java.util.NoSuchElementException

### ISSUE THREAD

**Issue by breewf** [CarGuo/GSYVideoPlayer#1480]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

偶现该异常崩溃：

1 java.util.ArrayDeque.removeFirst(ArrayDeque.java:264)
2 com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:682)
3 com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:622)
4 com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:567)
5 com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:109)
6 android.os.Handler.dispatchMessage(Handler.java:108)
7 android.os.Looper.loop(Looper.java:166)
8 android.os.HandlerThread.run(HandlerThread.java:65)

求解如何避免？

## 问题机型/系统：

例如 真机 XiaoMi Android 8.0.0,level 26

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请确定不是其他崩溃导致的改崩溃，最好有复现步骤

**Comment by breewf** [comment]
https://github.com/google/ExoPlayer/issues/4738

复现步骤:视频列表上下滑动，播放器重复释放和播放；循环播放视频一段时间；点击跳转返回播放，滑动等。不必现，但复现概率较大。

这个问题exoplayer下的回答是线程问题，但是我的操作都是在主线程，有什么解决方案吗？

**Comment by Nstd** [comment]
同样遇到该问题，我的视频是在ViewPager中播放的，类似微信左右滑动查看视频或图片那种

**Comment by Nstd** [comment]
@CarGuo 看了下 `GSYVideoBaseManager`的源码
`MediaHandler`是运行在`HandlerThread`中的吧？
https://github.com/CarGuo/GSYVideoPlayer/blob/36c5405576864efbeb1abdad9cffe617018a617b/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/GSYVideoBaseManager.java#L147-L152

这个是个异步线程，但是`MediaHandler`里却直接操作了`playerManager`，会不会就是 @breewf 那个issue里提到的问题？
https://github.com/CarGuo/GSYVideoPlayer/blob/36c5405576864efbeb1abdad9cffe617018a617b/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/GSYVideoBaseManager.java#L550-L582

是不是应该把这些转发到 `mainThreadHandler`去做？

**Comment by 50kg** [comment]
楼主我也遇到了 一样的问题...

**Comment by breewf** [comment]
> 楼主我也遇到了 一样的问题...

我的操作是把它们切换到了同一个线程，目前没有发现问题。
类似这样：
@Override
    public void start() {
        if (playerManager != null) {
            mMediaHandler.post(() -> playerManager.start());
        }
    }

    @Override
    public void stop() {
        if (playerManager != null) {
            mMediaHandler.post(() -> playerManager.stop());
        }
    }

    @Override
    public void pause() {
        if (playerManager != null) {
            mMediaHandler.post(() -> playerManager.pause());
        }
    }

**Comment by breewf** [comment]
不这么操作的话的确不是在一个线程的（一个主线程，一个子线程），有
较大概率出现该异常。
