### ISSUE TITLE
创建两个播放器实例seekbar问题

### ISSUE THREAD

**Issue by whj33** [CarGuo/GSYVideoPlayer#1481]

**Comment by whj33** [comment]
因为需求问题，所以不想用多任务支持的模式，除了这个有其他解决方案吗，就是返回页面A的时候，页面B的播放器依然在后台播放，但是页面A的seekbar不跟随页面B的状态

**Comment by CarGuo** [comment]
？？？

**Comment by whj33** [comment]
我在页面A创建了一个videoplayer实例，然后跳转到页面B  又创建了一个videoplayer实例，页面B进行后台播放，页面B   finish以后 ，页面A的videoplayer的seekbar跟随页面B的videoplayer的进度，请问怎么解决

**Comment by whj33** [comment]
因为需求不想用多任务支持模式

**Comment by CarGuo** [comment]
这个你需要在返回到A页面的时候，比如onResume的时候获取B页面的进度，比如你在B的onDestroy的时候获取了进度之后，在A恢复时同步进度，或者用EventBus或者用其他VM模式，这个只能说看你自己的实现了。

**Comment by whj33** [comment]
请问如果设置页面A在后台播放，我想实现在页面B或者页面C展示一个页面A播放器的进度框，请问在其他页面怎么监听到页面A播放器的进度

**Comment by CarGuo** [comment]
我觉得，这种你在A监听后，通过message、evenbus、全局listener等等等都可以做吧。这不属于这个库的内容范畴

**Comment by whj33** [comment]
但是如果A页面finish以后   此页面就销毁了   所以无法   发送消息了

**Comment by whj33** [comment]
如果这个页面销毁以后就无法发送消息，   所以我想在其他页面获取到在后台播放器的一些进度监听回调

**Comment by whj33** [comment]
类似这种

![2](https://user-images.githubusercontent.com/24369121/46190409-0384ab80-c326-11e8-99a8-b430e3b0acb3.jpg)

**Comment by whj33** [comment]
上个页面finishi   以后   视频在后台播放 ，然后这个页面依旧可以获取到进度
