### ISSUE TITLE
手机4G的时候弹出的提示窗怎么没有继续播放和停止播放按钮了  在哪里修改颜色

### ISSUE THREAD

**Issue by JohnDwang** [CarGuo/GSYVideoPlayer#1483]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

手机4G的时候弹出的提示窗怎么没有继续播放和停止播放按钮了   发生了这样的问题！

## 问题机型/系统：

真机  三星  Android8.0

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
继承后重载，想弹什么框弹什么框

**Comment by JohnDwang** [comment]
我直接引入的StandardGSYVideoPlayer这个类中

 @Override
    protected void showWifiDialog() {
        if (!NetworkUtils.isAvailable(mContext)) {
            Toast.makeText(mContext, getResources().getString(R.string.no_net), Toast.LENGTH_LONG).show();
            return;
        }
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivityContext(),AlertDialog.THEME_HOLO_DARK);
        builder.setMessage(getResources().getString(R.string.tips_not_wifi));
        builder.setPositiveButton(getResources().getString(R.string.tips_not_wifi_confirm), new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                dialog.dismiss();
                startPlayLogic();
            }
        });
        builder.setNegativeButton(getResources().getString(R.string.tips_not_wifi_cancel), new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                dialog.dismiss();
            }
        });
        builder.create().show();
    }
这个方法修改

**Comment by JohnDwang** [comment]
是重新写个类继承StandardGSYVideoPlayer 重写showWifiDialog这个方法么 然后布局引入StandardGSYVideoPlayer 就行了么？

**Comment by JohnDwang** [comment]
ok
