### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by liuchenc** [CarGuo/GSYVideoPlayer#1486]
在列表上面,怎么做到一个播放完了,自动接着播放下一个视频资源

**Comment by CarGuo** [comment]
ListGSYVIdeoPlayer

**Comment by liuchenc** [comment]
啥意思?

**Comment by CarGuo** [comment]
如果你是说同一个播放窗口的下一个的话，就是ListGSYVIdeoPlayer
如果你是说播放完后播放下一个item的时候的话，那就是你需要自己做监听出出力

**Comment by liuchenc** [comment]
好的,我想问一下,有没有对外提供方法,隐藏视频播放的时候,下面显示的蓝色进度条

**Comment by CarGuo** [comment]
重载后在layoutid布局里去掉就可以了
