### ISSUE TITLE
播放完如何停留在最后一帧？

### ISSUE THREAD

**Issue by RockyQu** [CarGuo/GSYVideoPlayer#1487]
## 问题描述：

播放完如何停留在最后一帧？

**Comment by CarGuo** [comment]
你可以看看源码，现在播放完成之后是在complete和autocomplete的回调用release和释放了surface，如果需要你可以继承后做一些处理，当然刚开始没看源码可能有点吃力！

**Comment by RockyQu** [comment]
@CarGuo 打扰了，@override
public void onAutoCompletion() {
if (mNotReleaseWhenComplete) { return; } super.onAutoCompletion(); }
这种方式播放mp4的能停在最后一帧，但是播放m3u8的视频时就不行了，最后还是会黑屏，请问这如何处理，有什么思路可以讲讲吗？谢谢
