### ISSUE TITLE
设置长按事件无效

### ISSUE THREAD

**Issue by Nstd** [CarGuo/GSYVideoPlayer#1488]
## 问题描述：

StandardGSYVVideoPlayer.setOnLongClickListener() 无效
继承这个类，重新设置 gestureDetector （覆写onLongPress()）才行
希望能开放一个设置长按事件的接口

## 问题机型/系统：

真机 华为 MT7-CL00 Android7.0

**Comment by CarGuo** [comment]
类似这种需求继承处理即可，不常用的目前不考虑单独设置
