### ISSUE TITLE
如何播放本地视频或者raw资源视频

### ISSUE THREAD

**Issue by nuoyan2** [CarGuo/GSYVideoPlayer#1489]
如何播放本地视频或者raw资源视频 直接传String url是没有办法播放的
        String source1  =   "android.resource://" + getPackageName() + "/" + R.raw.czc_ad_abridgment;

        videoPlayer.setUp(source1, true, "测试视频");

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailPlayer.java

```
 //String url = "file://"+ Environment.getExternalStorageDirectory().getPath() + "Download/132451525666042.mp4";
```

```
//String url = "android.resource://" + getPackageName() + "/" + R.raw.test;
 //注意，用ijk模式播放raw视频，这个必须打开
//GSYVideoManager.instance().enableRawPlay(getApplicationContext());
```

**Comment by nuoyan2** [comment]
感谢大佬回答 我还想请教个问题 sd卡视频播放的方式

**Comment by nuoyan2** [comment]
不好意思看到了 你已经回答了sd卡播放方式 谢谢

**Comment by hanouba** [comment]
能支持flv格式吗

**Comment by w787959** [comment]
加上"file://"后播放本地视频，已经出现进度框正常行进，但是页面黑屏
