### ISSUE TITLE
封面图的问题

### ISSUE THREAD

**Issue by xiang23** [CarGuo/GSYVideoPlayer#149]
我的封面图是从后台接口动态读取的所以并没有一个固定的高度，recyclerview中使用当加入的imageview高为wrap_content的时候，点击播放会item会先缩小到播放按钮的大小然后再放大，有什么方法解决吗？ 另外问下您是如何解决硬编码导致花屏黑屏的？

**Comment by CarGuo** [comment]
硬解码黑屏目前还没有解决办法。你可以设置图片的控件固定大小，然后设置图片的缩放显示模式

**Comment by xiang23** [comment]
是我说的不够全。。。最后要达成的展示效果类似demo中的列表是item是一张张图的，但是宽度一定要堆满然后高度按实际大小，所以不能用固定图片控件的大小然后设置缩放模式显示

**Comment by CarGuo** [comment]
这就很奇怪了，图片没有下载下来你怎么知道大小呢？那么要么有接口提前告诉你大小，你提前设置好窗口高度和宽度，要么下载下来图片后，获取图片大小再显示窗口。再或者，返回给你的url最后面拼上大小参数给你。

**Comment by xundaozhe** [comment]
设置了宽度为沾满屏幕模式也设置了FIT_XY,为什么距离屏幕两边还是有距离?
特别是小米手机距离挺大的,其他也有问题,但是还好,没办法像demo里面那样占满屏幕

**Comment by xundaozhe** [comment]
切换成1.6.5就没问题了,还是希望作者给解释一下,谢谢

**Comment by xundaozhe** [comment]
切换成1.6.5在列表中使用滑动不那么流畅  *--*

**Comment by CarGuo** [comment]
不是很理解，是封面还是视频内容？？？ https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer/src/main/java/com/shuyu/gsyvideoplayer/utils/GSYVideoType.java 是否使用过？
