### ISSUE TITLE
关于循环播放本地一个视频 中间会短暂黑屏1秒左右问题

### ISSUE THREAD

**Issue by nuoyan2** [CarGuo/GSYVideoPlayer#1492]
代码是根据代码例子的简单siple代码基础更改的 
第一步增加封面
第二步videoPlayer 监听VideoAllCallBack接口在 onAutoComplete方法接收到消息后我  调用startPlayLogic();
现象 播放完成后悔0.5-1秒左右的黑屏才加载封面  请教下大佬有没有好的解决办法 感谢

**Comment by CarGuo** [comment]
你直接设置循环播放就可以啦， setLoop
