### ISSUE TITLE
https播放不了的问题

### ISSUE THREAD

**Issue by didiao11300** [CarGuo/GSYVideoPlayer#1493]
## 问题描述：

用https播放时候播放不了ijkplayer提示-10000的错误！

## 问题机型/系统：

meizu pro5

## Demo中的复现步骤

SimplePlayer.java页面

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

09-30 11:06:41.217 30788-30832/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
09-30 11:06:41.227 30788-30832/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
09-30 11:06:41.256 30788-30838/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
09-30 11:06:41.333 30788-30838/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: Error fetching info from https://v11-tt.ixigua.com/db6aedc973ace812aa574e1e3a93365a/5badf2f3/video/m/2207fc700f9d32d4d418e7871d745a52039115bc57e0000b16818220502/
09-30 11:06:41.334 30788-30838/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
09-30 11:06:41.341 30788-30838/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: Error fetching info from https://v11-tt.ixigua.com/db6aedc973ace812aa574e1e3a93365a/5badf2f3/video/m/2207fc700f9d32d4d418e7871d745a52039115bc57e0000b16818220502/
09-30 11:06:41.343 30788-30838/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
09-30 11:06:41.353 30788-30838/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: Error fetching info from https://v11-tt.ixigua.com/db6aedc973ace812aa574e1e3a93365a/5badf2f3/video/m/2207fc700f9d32d4d418e7871d745a52039115bc57e0000b16818220502/
09-30 11:06:41.355 30788-30842/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
09-30 11:06:41.361 30788-30842/com.example.gsyvideoplayer E/ProxyCache error: Error opening connection for https://v11-tt.ixigua.com/db6aedc973ace812aa574e1e3a93365a/5badf2f3/video/m/2207fc700f9d32d4d418e7871d745a52039115bc57e0000b16818220502/ with offset 0. Version: 6.0.0-beta
09-30 11:06:41.361 30788-30838/com.example.gsyvideoplayer E/HttpProxyCacheServer error: Error processing request. Version: 6.0.0-beta
09-30 11:06:41.363 30788-30837/com.example.gsyvideoplayer E/IJKMEDIA: http://127.0.0.1:34572/https%3A%2F%2Fv11-tt.ixigua.com%2Fdb6aedc973ace812aa574e1e3a93365a%2F5badf2f3%2Fvideo%2Fm%2F2207fc700f9d32d4d418e7871d745a52039115bc57e0000b16818220502%2F: End of file
09-30 11:06:41.363 30788-30823/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
09-30 11:06:41.363 30788-30788/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
09-30 11:06:41.364 30788-30788/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Again https://v11-tt.ixigua.com/db6aedc973ace812aa574e1e3a93365a/5badf2f3/video/m/2207fc700f9d32d4d418e7871d745a52039115bc57e0000b16818220502/
09-30 11:06:41.364 30788-30788/com.example.gsyvideoplayer E/GSYVideoPlayer: mCache Link https://v11-tt.ixigua.com/db6aedc973ace812aa574e1e3a93365a/5badf2f3/video/m/2207fc700f9d32d4d418e7871d745a52039115bc57e0000b16818220502/
09-30 11:06:41.370 30788-30823/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by CarGuo** [comment]
https支持播放，请确定链接的视频编码和音频编码，并且确定链接是否可播放
