### ISSUE TITLE
硬解花屏

### ISSUE THREAD

**Issue by Somony** [CarGuo/GSYVideoPlayer#1494]
请教：android使用硬解，解码ts流，在播放的时候会不定期的出现花屏，测试了几个手机都是如此，使用ios手机硬解流是没问题的。在刚打开播放器的时候，会打印出PPS不存在，后续再播放的时候也会打印出SPS不存在，请问这个改如何解决？

**Comment by CarGuo** [comment]
硬解码出现花屏目前是不可避免的，因为在硬解码没做什么兼容

**Comment by Somony** [comment]
有可以着手解决的方案吗？请教

**Comment by CarGuo** [comment]
目前硬解码优化的话你需要去看ijk的源码，通过修改ffmpeg做兼容
