### ISSUE TITLE
请问有没有移植到flutter平台下的计划

### ISSUE THREAD

**Issue by feeloc** [CarGuo/GSYVideoPlayer#1495]
如题，谢谢

**Comment by CarGuo** [comment]
移植到flutter如果不是widget级别的还不是很麻烦，麻烦的是没有IOS的

**Comment by feeloc** [comment]
了解了，感谢
flutter下现在还没有比较完善的播放器使用，我再学习学习吧

**Comment by aytunch** [comment]
@CarGuo I wish there was an iOS version and then we would have a Flutter version too. Your library is very needed in Flutter community:)
