### ISSUE TITLE
视频切换到全屏或者小窗口会黑屏1到2秒，但声音继续，1到2秒后视频画面又出现了？从全屏退出也会这样屏幕黑个1到2秒，然后画面会回归正常，原因是什么（网络环境很好）？（没有开硬解码或者exo模式）

### ISSUE THREAD

**Issue by clark0704** [CarGuo/GSYVideoPlayer#150]

**Comment by clark0704** [comment]
视频切换到全屏或者小窗口会黑屏1到2秒，但声音继续，1到2秒后视频画面又出现了？从全屏退出也会这样屏幕黑个1到2秒，然后画面会回归正常，原因是什么（网络环境很好）？（没有开硬解码或者exo模式）

**Comment by CarGuo** [comment]
能否提供下播放url

**Comment by clark0704** [comment]
是这样的，我们用的是ijk的播放器，但是呢，是自己用ijk改的，我就想问，出现这种黑屏的情况是什么？用的url是你们自己的。

**Comment by CarGuo** [comment]
你找找你是不是设置过ijk的setOption，具体设置了哪些？播放使用的是surface还是texture？

**Comment by clark0704** [comment]
用的是textureView，设置的option
    ((ffplay)mediaPlayer).setOption(1,"user-agent","*****");
            ((ffplay) mediaPlayer).setDataSource(((Model) msg.obj).getUrl(), ((Model) msg.obj).getMapHeadData());
            mediaPlayer.setLooping(((Model) msg.obj).isLooping());
            if (((Model) msg.obj).getSpeed() != 1 && ((Model) msg.obj).getSpeed() > 0) {
                ((ffplay) mediaPlayer).setSpeed(((Model) msg.obj).getSpeed());
            }

**Comment by clark0704** [comment]
用的是textureView，设置的option
((ffplay)mediaPlayer).setOption(1,"user-agent","*****");
((ffplay) mediaPlayer).setDataSource(((Model) msg.obj).getUrl(), ((Model) msg.obj).getMapHeadData());
mediaPlayer.setLooping(((Model) msg.obj).isLooping());
if (((Model) msg.obj).getSpeed() != 1 && ((Model) msg.obj).getSpeed() > 0) {
((ffplay) mediaPlayer).setSpeed(((Model) msg.obj).getSpeed());
}
 this.setOption(1, "reconnect", a.a("player.ffplay.reconnect"));
        this.setOption(4, "mediacodec", a.a("player.ffplay.mediacodec"));
        this.setOption(4, "mediacodec-hevc", a.a("player.ffplay.mediacodec-hevc"));
        this.setOption(4, "overlay-format", 842225234L);
        this.setOption(1, "reconnect_delay_max", 15L);
        this.setOption(4, "start-on-prepared", 0L);
        this.setOption(1, "addrinfo_timeout", 

- [ ] 20000000L);

**Comment by CarGuo** [comment]
mediacodec   mediacodec-hevc 设置为0或者去掉试试

**Comment by clark0704** [comment]
是这样的，这些：
this.setOption(1, "reconnect", a.a("player.ffplay.reconnect"));
this.setOption(4, "mediacodec", a.a("player.ffplay.mediacodec"));
this.setOption(4, "mediacodec-hevc", a.a("player.ffplay.mediacodec-hevc"));
this.setOption(4, "overlay-format", 842225234L);
this.setOption(1, "reconnect_delay_max", 15L);
this.setOption(4, "start-on-prepared", 0L);
this.setOption(1, "addrinfo_timeout",20000000L);
是设置在jar包中的，不好改。

**Comment by clark0704** [comment]
那么怎么改呢，求解。

**Comment by CarGuo** [comment]
mediacodec和mediacodec-hevc其实就是开启了硬解码，如果是1的话。这时候你可以试试再切换的时候，构建后渲染view时，seekto一下看看能否解决。

**Comment by clark0704** [comment]
我已经知道怎么解决了，谢谢。
