### ISSUE TITLE
关于播放视频卡顿问题

### ISSUE THREAD

**Issue by nuoyan2** [CarGuo/GSYVideoPlayer#1500]
播放一个网络视频在普通的安卓设备是不卡的 但是在小米电视机上就出现卡顿的情况，我更换了一个exoplayer框架就不会卡顿了，有点怀疑是不是设置软硬解码的问题？我想尝试切换下软硬解码有没有公开的接口 谢谢！

**Comment by CarGuo** [comment]
该项目也可以切换到exoplayer内核。
GSYVideoType. enableMediaCodec() 硬解码
