### ISSUE TITLE
播放横屏视频时第一帧闪烁问题

### ISSUE THREAD

**Issue by breewf** [CarGuo/GSYVideoPlayer#1504]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

使用模式：GSYVideoType.SCREEN_TYPE_DEFAULT 
在开始播放横屏视频时会出现第一帧视频从全屏被拉至居中这样一个闪烁的过程，竖屏视频无影响。复现概率较大，请问是什么原因？

## 问题机型/系统：

真机 小米 Android7.0

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by breewf** [comment]
使用的是exo2Mananger，测试sysManager无此问题。

**Comment by breewf** [comment]
定位问题是GSYTextureView在测量时多次测量 由全屏幕到视频尺寸大小变化引起。

@Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        measureHelper.prepareMeasure(widthMeasureSpec, heightMeasureSpec, (int) getRotation());
        setMeasuredDimension(measureHelper.getMeasuredWidth(), measureHelper.getMeasuredHeight());
    }

measureHelper在测量时如果mVideoWidth和mVideoHeight为0，此时测量结果为屏幕宽高，例如：mMeasuredWidth = 1080
mMeasuredHeight = 1920

此时setMeasuredDimension(measureHelper.getMeasuredWidth(), measureHelper.getMeasuredHeight());为屏幕大小

待视频宽高获取后，测量结果为计算后的视频宽高；此时setMeasuredDimension(measureHelper.getMeasuredWidth(), measureHelper.getMeasuredHeight());为视频宽高

此时由全屏到视频宽高，会造成一定概率的闪屏（由全屏拉伸至中间的闪烁）

现在我的处理是在MeasureHelper里的doMeasure(int widthMeasureSpec, int heightMeasureSpec)方法：
else {
            // no size yet, just adopt the given spec sizes
            mMeasuredWidth = 1;
            mMeasuredHeight = 1;
            return;
        }

这里面把mMeasuredWidth、mMeasuredHeight置了1，不让其全屏。这样就不会由全屏到居中的过程，闪烁也就没有了。

现在else方法是空的，没有操作。不知道这个问题是bug还是我使用的问题（使用Exoplayer有此问题，系统和ijk无此问题）。

作者可以考虑修复此问题或是有其他修复方案吗？

**Comment by Lollipopll** [comment]
> 定位问题是GSYTextureView在测量时多次测量 由全屏幕到视频尺寸大小变化引起。
> 
> @override
> protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
> measureHelper.prepareMeasure(widthMeasureSpec, heightMeasureSpec, (int) getRotation());
> setMeasuredDimension(measureHelper.getMeasuredWidth(), measureHelper.getMeasuredHeight());
> }
> 
> measureHelper在测量时如果mVideoWidth和mVideoHeight为0，此时测量结果为屏幕宽高，例如：mMeasuredWidth = 1080
> mMeasuredHeight = 1920
> 
> 此时setMeasuredDimension(measureHelper.getMeasuredWidth(), measureHelper.getMeasuredHeight());为屏幕大小
> 
> 待视频宽高获取后，测量结果为计算后的视频宽高；此时setMeasuredDimension(measureHelper.getMeasuredWidth(), measureHelper.getMeasuredHeight());为视频宽高
> 
> 此时由全屏到视频宽高，会造成一定概率的闪屏（由全屏拉伸至中间的闪烁）
> 
> 现在我的处理是在MeasureHelper里的doMeasure(int widthMeasureSpec, int heightMeasureSpec)方法：
> else {
> // no size yet, just adopt the given spec sizes
> mMeasuredWidth = 1;
> mMeasuredHeight = 1;
> return;
> }
> 
> 这里面把mMeasuredWidth、mMeasuredHeight置了1，不让其全屏。这样就不会由全屏到居中的过程，闪烁也就没有了。
> 
> 现在else方法是空的，没有操作。不知道这个问题是bug还是我使用的问题（使用Exoplayer有此问题，系统和ijk无此问题）。
> 
> 作者可以考虑修复此问题或是有其他修复方案吗？

exo模式下会闪屏，请问不修改源码，还有其他方式修复吗？
