### ISSUE TITLE
监听播放状态

### ISSUE THREAD

**Issue by whj33** [CarGuo/GSYVideoPlayer#1508]
请问我单纯就想监听播放器的播放状态怎么获取

  //正常
    public static final int CURRENT_STATE_NORMAL = 0;
    //准备中
    public static final int CURRENT_STATE_PREPAREING = 1;
    //播放中
    public static final int CURRENT_STATE_PLAYING = 2;
    //开始缓冲
    public static final int CURRENT_STATE_PLAYING_BUFFERING_START = 3;
    类似监听这些

**Comment by CarGuo** [comment]
/**
     * 获取当前播放状态
     */
    public int getCurrentState() {
        return mCurrentState;
    }


或者在 继承后重载  setStateAndUi 方法，每次更新都会调用这个方法
