### ISSUE TITLE
视频显示的时候被裁剪了

### ISSUE THREAD

**Issue by pricnehao** [CarGuo/GSYVideoPlayer#151]
你好作者大人 上次给你反应过就是用你demo打开视频在竖屏的时候显示正常全屏显示，但是转屏的时候发现视屏被裁剪了  你可用下面的测试视频地址试一试  当竖屏切换到横屏显示的时候 视频的头部被裁剪掉了一部分  请你查看  测试视频地址：http://7xse1z.com1.z0.glb.clouddn.com/1491813192

**Comment by zhengyouhong** [comment]
我也遇到了这个问题，  确实被裁剪了， 那个测量宽度高度的地方有问题

**Comment by pricnehao** [comment]
你好  你解决了吗

**Comment by zhengyouhong** [comment]
说个情况：如果将播放界面设置成了1:1的情况下：宽 > 高 的视频，上下会有黑边，而宽 < 高的视频， 会被裁剪。      在某个全屏播放界面，一个视频源的  height : width > 屏幕height : 屏幕width 的时候，视频会被左右拉伸，旋转之后，视频播放界面会变成1:1，被裁减了。

**Comment by CarGuo** [comment]
收到，晚点我看看～～～

**Comment by CarGuo** [comment]
确实被裁减了一些，而且这个视频是有旋转属性的，恰好在全屏的时候有个bug导致没有被旋转，晚点我一起修改下。

**Comment by CarGuo** [comment]
各位，刚刚更新了代码，已经解决了这个问题，不过合并到release发布远程仓版本还要等下一次，各位可以先从master的源码中依赖解决。欢迎回馈～

**Comment by pricnehao** [comment]
好的 谢谢

**Comment by zhengyouhong** [comment]
进入到全屏界面，  还是会铺满整个屏幕， 这样会被拉伸 很奇怪的感觉

**Comment by CarGuo** [comment]
@zhengyouhong 哪里？有url和截图嘛？

**Comment by zhengyouhong** [comment]
@CarGuo 能问下在GSYTextureView的onMeasure中，widthS和heightS的作用是干什么的？

**Comment by zhengyouhong** [comment]
暂停的时候  还是会被裁剪。  在全屏中，视频高度/宽度 > 屏幕高度/宽度时， 视频会被压缩变形

**Comment by CarGuo** [comment]
这个希望可以提供下url，因为还没有遇到这样的视频，这个视频是有旋转角度的，还是没有选择角度的？？暂停的时候被裁减这个我稍后修改下！

**Comment by CarGuo** [comment]
暂停的问题已经修改提交到master了，可以同步看看～至于后面这个问题，还望提供下流url

**Comment by pricnehao** [comment]
我今天看了下节操的demo  就是上面的那个url 竖屏是全屏显示 旋转90度也是没有被裁剪的  但是现在您的貌似 在竖屏不能全屏显示了  左右之间有空隙

**Comment by zhengyouhong** [comment]
@CarGuo  http://111.198.24.133:83/yyy_login_server/pic/YB059284/97778276040859/1.mp4  你看看这个视频。
我觉得有些情况是需要裁剪的， 比如在一些预览界面， 为了适应不同尺寸的视频，需要裁剪下，全屏的时候通常不需要。

**Comment by CarGuo** [comment]
@zhengyouhong 好的，晚点我看下。
@pricnehao 这么说有点难理解，可以上图对比看看

**Comment by CarGuo** [comment]
@zhengyouhong 了解了，是动画的问题导致拉伸，可以先关闭全屏动画效果解决这个问题。至于现在是完全显示的了。

**Comment by CarGuo** [comment]
@zhengyouhong @pricnehao 刚刚提交的master也修复了动画旋转时拉伸的问题，可以试试～如果还有什么情况，欢迎反馈～
