### ISSUE TITLE
请问目前是对AAC的音频格式不支持吗？

### ISSUE THREAD

**Issue by androidChao** [CarGuo/GSYVideoPlayer#1512]
目前aac格式音频的视频在所有手机上均没有声音(有很小的噪音),仅有画面，这种情况要重新编译so？

**Comment by CarGuo** [comment]
ijk 目前支持的格式是有AAC的 ： https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh

不行你可以切换到 exoplayer 内核试试
