### ISSUE TITLE
setSeekOnStart方法失效o

### ISSUE THREAD

**Issue by whj33** [CarGuo/GSYVideoPlayer#1513]
调用完   orientationUtils.resolveByClick() 

重新调用setup   setSeekOnStart方法

setSeekOnStart会失效   参数是有值的   但还是会从开头开始播放  请问为什么

**Comment by whj33** [comment]
但是如果不调用orientationUtils.resolveByClick()    就不会失效

**Comment by CarGuo** [comment]
player.getcurrentPlayer.setup
player.getcurrentPlayer.setSeekOnStart

**Comment by whj33** [comment]
我就是这样写的，但是有时候有用   但是有时候就没用

**Comment by whj33** [comment]
PositionWhenPlaying=detailPlayer.getCurrentPlayer().getCurrentPositionWhenPlaying();
                detailPlayer.getCurrentPlayer().setUp("http://video.licaishi365.com/8da3ed564208488bbe06ee7a288cee7a/87d63bc26d17429882328c3c8154fbfe-faacffaee4722462e689253933c2dca7-ld.mp4", true, "");
                Toast.makeText(MainActivity.this,PositionWhenPlaying+"",Toast.LENGTH_SHORT).show();
                detailPlayer.getCurrentPlayer().setSeekOnStart(PositionWhenPlaying);
                ((NextDetailVideo)detailPlayer.getCurrentPlayer()).clickStartIcon();
                if(orientationUtils.getIsLand()==1){
                    orientationUtils.resolveByClick();
                }

**Comment by CarGuo** [comment]
这就很奇怪了，demo中怎么复现？

**Comment by whj33** [comment]
类似这种

**Comment by whj33** [comment]
猫大人为什么不回复我啊？

**Comment by whj33** [comment]
灵光一闪   突然解决
