### ISSUE TITLE
请教是否支持自定义数据源？

### ISSUE THREAD

**Issue by Orienser** [CarGuo/GSYVideoPlayer#1515]
因为我的文件有经过一些处理，无法直接读取作为播放器的数据源。
那么有没有这么一种接口，可以让我使用自定义的数据源（例如一个InputStream），在我读取本地数据并处理后，再为播放器返回真正的视频数据（例如byte[]）。

**Comment by CarGuo** [comment]
你可以自定义PlayerManager

**Comment by ZhanRu** [comment]
大神能否详细说一下操作？找不到怎么自定义PlayerManager

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exo  @ZhanRu 自定义全家桶

**Comment by ZhanRu** [comment]
@CarGuo 回复好快 非常感谢

**Comment by ZhanRu** [comment]
@CarGuo  认真看了几遍，没找到方法啊大神。

看到了GSYExo2MediaPlayer有setDataSource(FileDescriptor fd)方法，但是我是WebDAV获取的InputStream，转不过来。
然后StandardGSYVideoPlayer没有类似的方法；
GSYExoModel就是URL，没有自定义流的地方；
我能力不如大神啊，能否麻烦稍微再多讲一下？感谢

**Comment by pie-tk** [comment]
@ZhanRu 你的自定义弄出来了吗
