### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by supermoutant** [CarGuo/GSYVideoPlayer#1518]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\0.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\1.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\2.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\3.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\4.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\5.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\6.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\7.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\8.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\9.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\10.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\11.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\12.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\13.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\14.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\15.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\16.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\17.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\18.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\19.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\20.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\21.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\22.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\23.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\24.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\25.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\26.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\27.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\28.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\29.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\30.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\31.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\32.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\33.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\34.jar, C:\WorkPlace\JunDingTv\master\TextGsyDemo\app\build\intermediates\transforms\dexBuilder\debug\35.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.BackStackRecord$Op

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by CarGuo** [comment]
类似问题清自行百度解决，属于依赖冲突或者版本冲突等问题
