### ISSUE TITLE
依赖冲突

### ISSUE THREAD

**Issue by whj33** [CarGuo/GSYVideoPlayer#1519]
我想使用您写的那个录音的库，解过碰到了依赖重复问题
Multiple dex files define Lcom/danikula/videocache/Cache;

    compile 'com.shuyu:GSYVideoPlayer:6.0.1'
    file 'com.github.CarGuo:RecordWave:v1.1.8'{
            exclude group:'com.danikula.videocache'
    }

这样还是无法解决   请问怎么解决好

**Comment by whj33** [comment]
解决了

**Comment by leigayu** [comment]
@whj33 我也遇到了，请问怎么解决的

**Comment by nxnyk** [comment]
请问怎么解决的

**Comment by itljw** [comment]
implementation ('com.github.CarGuo:RecordWave:v1.1.5'){
        exclude group: 'com.danikula',module:'videocache'
    }

**Comment by nxnyk** [comment]
> implementation ('com.github.CarGuo:RecordWave:v1.1.5'){
> exclude group: 'com.danikula',module:'videocache'
> }

解决了，谢谢
