### ISSUE TITLE
列表详情切换Android 4.4版本不能无缝播放

### ISSUE THREAD

**Issue by Jiangzqts** [CarGuo/GSYVideoPlayer#1520]
## 问题描述：

Demo中列表详情切换，不能无缝播放，会出现进度条正确，视频卡住现象

## 问题机型/系统：

夜神模拟器 Android 4.4 

## Demo中的复现步骤

Demo中的列表详情切换会出现这个问题。

## 问题log（如果有）

```

无错误日志
```

**Comment by CarGuo** [comment]
DEMO那个时5.0以上才支持的动画效果，如果需要支持低版本请自行兼容，库接下来不会再对5.0以下的做兼容处理哦。

**Comment by Jiangzqts** [comment]
嗯嗯，ok
