### ISSUE TITLE
请问我把一个mp4弄成加密的m3u8，没有服务器，可以在本地解密播吗？

### ISSUE THREAD

**Issue by RockyQu** [CarGuo/GSYVideoPlayer#1523]

**Comment by CarGuo** [comment]
没试过，不过本地播放m3u8是支持的

**Comment by RockyQu** [comment]
E/IJKMEDIA: Filename extension of '/storage/emulated/0/AAAAAAAAAAAA/cache/decrypt.key' is not a common multimedia extension, blocked for security reasons.
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all
E/IJKMEDIA: Unable to open key file /storage/emulated/0/AAAAAAAAAAAA/cache/decrypt.key
2018-10-17 13:40:12.621 27285-27563/com.example.gsyvideoplayer E/IJKMEDIA: Error when loading first segment '/storage/emulated/0/AAAAAAAAAAAA/cache/test-000.ts'
E/IJKMEDIA: /storage/emulated/0/AAAAAAAAAAAA/cache/index.m3u8: Invalid data found when processing input

请问我刚播放一个加密的m3u8报了这个错，其他的关于加密的issues也看了一下，找不出问题

**Comment by RockyQu** [comment]
我加了一段这个代码 
VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "crypto, file, http, https, tcp, tls, udp");
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

**Comment by RockyQu** [comment]
E/GSYVideoPlayer: cancelTimeOutBuffer
 E/IJKMEDIA: Protocol 'file' not on whitelist 'crypto, file, http, https, tcp, tls, udp'!
E/IJKMEDIA: /storage/emulated/0/AAAAAAAAAAAA/cache/index.m3u8: Invalid argument
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E/GSYVideoPlayer: cancelTimeOutBuffer

然后开始报这些了

**Comment by RockyQu** [comment]
和这个 decrypt.key 的文件名有什么关系吗？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1200

**Comment by RockyQu** [comment]
解决了，哈哈，原来是so库不对，要引ex_so的
