### ISSUE TITLE
高斯模糊封面填充黑色背景

### ISSUE THREAD

**Issue by itljw** [CarGuo/GSYVideoPlayer#1525]
请教下视频宽高显示不全时的黑色背景怎么用用封面的高斯模糊图片填充？

**Comment by CarGuo** [comment]
没有现成的效果，请看demo的GL模式的渲染。首先你需 OpengGL 的一些支持

demo

https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailFilterActivity.java

类似效果

https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailFilterActivity.java
