### ISSUE TITLE
退出全屏后没有声音

### ISSUE THREAD

**Issue by wqjuser** [CarGuo/GSYVideoPlayer#153]
视频播放退出全屏后继续播放没有声音。还有就是退出播放界面视频一直在后台播放

**Comment by CarGuo** [comment]
请参考demo，demo中有列表静音播放，全屏有声音的。有支持后台播放，有退后后台暂停，退出界面是否的

**Comment by wqjuser** [comment]
恩，这个问题解决了，谢谢
