### ISSUE TITLE
直接设置全屏的问题

### ISSUE THREAD

**Issue by zhanfangzxc** [CarGuo/GSYVideoPlayer#1530]
## 问题描述：

直接设置横屏播放，会出现一个白条，而且点击返回键的时候不需要返回到竖屏状态，需要直接finish掉当前Activity

## 问题机型/系统：

一加6 Android7.0

## Demo中的复现步骤

1.videoPlayer.currentPlayer.startWindowFullscreen(this, false, false)
通过上述代码设置进入Activity之后直接开启横屏模式，但是上方会出现状态栏
2. 点击返回按钮需要直接退出当前页面，而不是回到竖屏状态

**Comment by zhanfangzxc** [comment]
1. 对于第一个问题就是进来直接全屏，退出之后就直接finish掉当前Activity，不需要恢复到竖屏的视频播放状态，还有就是上方不是状态栏是工具栏，直接全屏就会出现这个
![image](https://user-images.githubusercontent.com/6426836/47201071-2ea16e80-d3ab-11e8-843a-455ca0f4f6d9.png)

**Comment by zhanfangzxc** [comment]
> 1、首先，你的页面是怎么样的？是类似detailplayer，然后需要进来全屏，之后可以退出到普通详情模式？？
> 
> 2、startWindowFullscreen(this, false, false)的时候，把statusbar标志位标志是就是没有状态栏
> 
> 3、返回按键监听处理要加上
> 
> 4、请仔细看demo

对于返回按键,我给他设置了新的点击事件，可是还是会先从横屏切换到竖屏，之后再点击一次才会退出当前播放界面

**Comment by CarGuo** [comment]
如果进来直接播放，不需要切换，那你直接设置Activity是横向全屏的，都不需要调用全屏接口

这样也不会有什么点击问题了

**Comment by yecaler** [comment]
已解决。详细解决方案：
1.使用DEMO中继承GSYVideoPlayer的播放器
2.实现onBackFullscreen方法
    @Override
    public void onBackFullscreen() {
        clearFullscreenLayout();
    }
3.实现clearFullscreenLayout方法



    /**
     * 退出window层播放全屏效果
     */
    @SuppressWarnings("ResourceType")
    @Override
    protected void clearFullscreenLayout() {
        if (!mFullAnimEnd) {
            return;
        }
        mIfCurrentIsFullscreen = false;
        int delay = 0;
        // ------- ！！！如果不需要旋转屏幕，可以不调用！！！-------
        // 不需要屏幕旋转，还需要设置 setNeedOrientationUtils(false)
//        if (mOrientationUtils != null) {
//            delay = mOrientationUtils.backToProtVideo();
//            mOrientationUtils.setEnable(false);
//            if (mOrientationUtils != null) {
//                mOrientationUtils.releaseListener();
//                mOrientationUtils = null;
//            }
//        }

        if (!mShowFullAnimation) {
            delay = 0;
        }

        final ViewGroup vp = (CommonUtil.scanForActivity(getContext())).findViewById(Window.ID_ANDROID_CONTENT);
        final View oldF = vp.findViewById(getFullId());
        if (oldF != null) {
            //此处fix bug#265，推出全屏的时候，虚拟按键问题
            SampleCoverVideo gsyVideoPlayer = (SampleCoverVideo) oldF;
            gsyVideoPlayer.mIfCurrentIsFullscreen = false;
        }

        if (delay == 0) {
            backToNormal();
        } else {
            postDelayed(new Runnable() {
                @Override
                public void run() {
                    backToNormal();
                }
            }, delay);
        }

    }
4.注释掉第3步中的
        // ------- ！！！如果不需要旋转屏幕，可以不调用！！！-------
        // 不需要屏幕旋转，还需要设置 setNeedOrientationUtils(false)
//        if (mOrientationUtils != null) {
//            delay = mOrientationUtils.backToProtVideo();
//            mOrientationUtils.setEnable(false);
//            if (mOrientationUtils != null) {
//                mOrientationUtils.releaseListener();
//                mOrientationUtils = null;
//            }
//        }
5.AndroidManifest中对应的activity下添加：
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
