### ISSUE TITLE
关于截图在回调中获取不到bitmap

### ISSUE THREAD

**Issue by zhaoaoranke** [CarGuo/GSYVideoPlayer#1531]
detailPlayer.taskShotPic(new GSYVideoShotListener() {
            @Override
            public void getBitmap(Bitmap bitmap) {
                if (bitmap != null) {
                    imageView.setImageBitmap(bitmap);
                }
            }
        });
代码没有进入到回调中，请问还需要设置什么吗？什么情况下回走回调

**Comment by CarGuo** [comment]
demo中复现不？

**Comment by zhaoaoranke** [comment]
demo没有尝试，我继承了StandardGSYVideoPlayer，只重写了getLayoutId()方法，然后用的是详情页播放模式SimpleDetailActivityMode1

**Comment by CarGuo** [comment]
试试demo吧
