### ISSUE TITLE
缓冲时 顶部和底部的进度布局 隐藏了就无法再出现了，点击也不会出现

### ISSUE THREAD

**Issue by Wing-Li** [CarGuo/GSYVideoPlayer#1533]
缓冲时 顶部和底部的进度布局 隐藏了就无法再出现了，点击也不会出现。

弱网环境下会出现，网速极慢。

**Comment by Wing-Li** [comment]
发现原因了，是因为视频初始设置的封面。
按照 com.example.gsyvideoplayer.video.SampleCoverVideo 类的写法加入了封面之后，就不行了。
应该是封面遮盖了点击事件吧，
我再看看问题。

**Comment by Wing-Li** [comment]
问题应该是这里吧？
不知道对不？

![image](https://user-images.githubusercontent.com/12133489/47205468-94e0be00-d3b8-11e8-9b0d-bc16907dac0a.png)

**Comment by CarGuo** [comment]
Demo 哪里复现？

**Comment by Wing-Li** [comment]
Demo 里可能没有这个式样。
我是自定了布局，将布局做成全屏的状态，页面一进来就是竖全屏。
这个问题，我已经解决了。
就是在自定义的类里面重写 onClick() 方法，处理一下 thumb 的点击事件。


    @Override
    public void onClick(View v) {
        super.onClick(v);
        int id = v.getId();

        // 解决视频缓冲时，点击封面，上下操作布局不显示的 BUG
        if (id == R.id.thumb) {
            // 因为这个状态在父类里面已经控制过了，所以这里将此状态排除掉
            if (mCurrentState != CURRENT_STATE_AUTO_COMPLETE) {
                // 个人觉得任何状态都应该可以 显示或隐藏 上下的UI，所以这里将所有的状态都包含了
                onClickUiToggle();
            }
        }
    }

**Comment by CarGuo** [comment]
good
