### ISSUE TITLE
大佬,rtmp协议视频的onVideoResume方法问题

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1534]
rtmp在暂时离开播放页面 又回来时 

    @Override
    protected void onResume() {
        super.onResume();
        videoPlayer.onVideoResume();
    }

方法执行后,一直在转圈不可播放 ,http协议的视频离开后又回来 onResume执行后 继续播放不会转圈

**Comment by CarGuo** [comment]
`videoPlayer.onVideoResume(false);`
