### ISSUE TITLE
rtmp和m3u8流切换播放时 报I/O error   Error (-10000,0) Server response validating failed错

### ISSUE THREAD

**Issue by koJer** [CarGuo/GSYVideoPlayer#1537]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
麻烦提供详细log

**Comment by koJer** [comment]
![image](https://user-images.githubusercontent.com/8786171/47282472-f8195d00-d611-11e8-9ee0-1edd985e7abf.png)
在onDestory里面调用了是释放播放器的方法。但是好像还是没用

**Comment by CarGuo** [comment]
请提供两个链接测试
或者可以试试问题集锦中的 dns clear
或者切换到exoplayer内核模式试试

**Comment by koJer** [comment]
dns clear 可以解决~
