### ISSUE TITLE
全屏与小屏切换后出现短暂黑屏然后声音一直有然后就出现声音画面不同步的问题

### ISSUE THREAD

**Issue by wqjuser** [CarGuo/GSYVideoPlayer#154]
我直接 compile 'com.shuyu:GSYVideoPlayer:1.6.2'到我的项目中然后写了一个activity里面放了一个 StandardGSYVideoPlayer和一个webview，切换全屏和小屏的时候就出现了全屏与小屏切换后出现短暂黑屏然后声音一直有然后就出现声音画面不同步的问题

**Comment by wqjuser** [comment]
这是我的xml文件
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        tools:context="com.snsoft.partner.main.VideoChangeActivity">

    

    <com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
            android:id="@+id/video_player"
            android:layout_width="match_parent"
            android:layout_height="180dp"/>

    <LinearLayout
            android:layout_marginTop="@dimen/dp10"
            android:layout_marginBottom="@dimen/dp2"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

        <TextView
                android:layout_marginTop="@dimen/dp2"
                android:layout_marginStart="@dimen/dp10"
                android:id="@+id/tv_relese_peo"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="1234564798789"/>

        <TextView
                android:gravity="end"
                android:id="@+id/tv_relese_date"
                android:text="shijian"
                android:layout_marginTop="@dimen/dp2"
                android:layout_marginEnd="@dimen/dp10"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>
    </LinearLayout>

    <TextView
            android:id="@+id/tv_content"
            android:layout_marginTop="6dp"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    <WebView
            android:id="@+id/web_content"
            android:layout_marginTop="2dp"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"></WebView>
</LinearLayout>
`以及我的Java文件
`public final static String TRANSITION = "TRANSITION";
    @BindView(R.id.video_item_player)
    StandardGSYVideoPlayer videoItemPlayer;
    @BindView(R.id.tv_relese_peo)
    TextView tvRelesePeo;
    @BindView(R.id.tv_relese_date)
    TextView tvReleseDate;
    @BindView(R.id.tv_content)
    TextView tvContent;
    @BindView(R.id.web_content)
    WebView webContent;

    ImageView videoImg;
    String videoTime;
    String supertext;
    String videocontent;
    String Video_Submit_Man;
    String url;
    String videoname;
    String videoPic;
//    @BindView(R.id.title_back_layout)
//    LinearLayout titleBackLayout;
//    @BindView(R.id.title_name_tv)
//    TextView titleNameTv;
    private boolean isFullVideo;
    private OrientationUtils orientationUtils;

    private boolean isTransition;

    private Transition transition;

    private boolean isPlay;
    private boolean isPause;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_change);
        ButterKnife.bind(this);
        isTransition = getIntent().getBooleanExtra(TRANSITION, false);
        url = getIntent().getStringExtra("videourl");
        videoname = getIntent().getStringExtra("videoname");
        videoPic = getIntent().getStringExtra("videoPic");
        videoTime = getIntent().getStringExtra("videoTime");
        supertext = getIntent().getStringExtra("supertext");
        videocontent = getIntent().getStringExtra("videocontent");
        Video_Submit_Man = getIntent().getStringExtra("Video_Submit_Man");
        initView();
        GSYVideoManager.instance().setTimeOut(4000, true);
    }

    public void initView() {
//        titleNameTv.setText("视频播放");
        videoImg = new ImageView(this);
        videoImg.setScaleType(ImageView.ScaleType.CENTER_CROP);
        Picasso.with(this).load(videoPic).into(videoImg);
        videoItemPlayer.setThumbImageView(videoImg);
        videoItemPlayer.setUp(url, false, null, videoname);
        videoItemPlayer.getTitleTextView().setVisibility(View.GONE);
        videoItemPlayer.getBackButton().setVisibility(View.GONE);
        videoItemPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //直接横屏
                orientationUtils.resolveByClick();
                //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                videoItemPlayer.startWindowFullscreen(VideoChangeActivity.this, true, true);
            }
        });
        //设置旋转
        orientationUtils = new OrientationUtils(this, videoItemPlayer);
        //初始化不打开外部的旋转
        orientationUtils.setEnable(false);
        //是否可以滑动调整
        videoItemPlayer.setIsTouchWiget(true);
        //设置返回按键功能
        videoItemPlayer.getBackButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onBackPressed();
            }
        });
        videoItemPlayer.setStandardVideoAllCallBack(new SampleListener() {
            @Override
            public void onPrepared(String url, Object... objects) {
                super.onPrepared(url, objects);
                //开始播放了才能旋转和全屏
                orientationUtils.setEnable(true);
                isPlay = true;
            }

            @Override
            public void onAutoComplete(String url, Object... objects) {
                super.onAutoComplete(url, objects);
            }

            @Override
            public void onClickStartError(String url, Object... objects) {
                super.onClickStartError(url, objects);
            }

            @Override
            public void onQuitFullscreen(String url, Object... objects) {
                super.onQuitFullscreen(url, objects);
                if (orientationUtils != null) {
                    orientationUtils.backToProtVideo();
                }
            }
        });

        videoItemPlayer.setLockClickListener(new LockClickListener() {
            @Override
            public void onClick(View view, boolean lock) {
                if (orientationUtils != null) {
                    //配合下方的onConfigurationChanged
                    orientationUtils.setEnable(!lock);
                }
            }
        });

        videoItemPlayer.setRotateViewAuto(true);
        videoItemPlayer.setLockLand(true);
        videoItemPlayer.setShowFullAnimation(true);
        videoItemPlayer.setNeedLockFull(true);
        if (supertext.equals("")) {
        } else {
            StringBuilder sb = new StringBuilder();
            sb.append("<html>");
            sb.append("<head>");
            sb.append("<title>欢迎您</title>");
            sb.append("</head>");
            sb.append(supertext);
            sb.append("</body>");
            sb.append("</html>");
            webContent.loadDataWithBaseURL(null, sb.toString(), "text/html", "utf-8", null);
        }
        tvReleseDate.setText(videoTime);
        tvContent.setText(videocontent);
        tvRelesePeo.setText(Video_Submit_Man);
    }

//    @OnClick(R.id.title_back_layout)
//    public void onViewClicked() {
//        this.finish();
//    }

    @Override
    public void onBackPressed() {
        if (orientationUtils != null) {
            orientationUtils.backToProtVideo();
        }
        if (StandardGSYVideoPlayer.backFromWindowFull(this)) {
            return;
        }
        super.onBackPressed();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        GSYVideoPlayer.releaseAllVideos();
        //GSYPreViewManager.instance().releaseMediaPlayer();
        if (orientationUtils != null)
            orientationUtils.releaseListener();
    }

    @Override
    protected void onPause() {
        super.onPause();
        videoItemPlayer.onVideoPause();
        isPause = true;
    }

    @Override
    protected void onResume() {
        super.onResume();
        isPause = false;
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        //如果旋转了就全屏
        if (isPlay && !isPause) {
            if (newConfig.orientation == ActivityInfo.SCREEN_ORIENTATION_USER) {
                if (!videoItemPlayer.isIfCurrentIsFullscreen()) {
                    videoItemPlayer.startWindowFullscreen(VideoChangeActivity.this, true, true);
                }
            } else {
                //新版本isIfCurrentIsFullscreen的标志位内部提前设置了，所以不会和手动点击冲突
                if (videoItemPlayer.isIfCurrentIsFullscreen()) {
                    StandardGSYVideoPlayer.backFromWindowFull(this);
                }
                if (orientationUtils != null) {
                    orientationUtils.setEnable(true);
                }
            }
        }
    }`

**Comment by CarGuo** [comment]
manifest 的config是否配置了？？？在demo中测试过吗url？
