### ISSUE TITLE
关于IJKEXOPLAYER内核下调整播放速率无效问题

### ISSUE THREAD

**Issue by AldenLei** [CarGuo/GSYVideoPlayer#1543]
播放器切换到IJKEXOPLAYER的内核，导致修改播放速率无效，setSpeed()方法中判断了是否是IjkMediaPlayer播放器，目前需求只能使用IJKEXOPLAYER内核（使用IjkMediaPlayer播放器seekTo()有误差），怎么可以在此内核下也修改播放器速率呢？

**Comment by CarGuo** [comment]
你用的旧版本吧，新版本的setSpeed都是通过  https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/base/GSYVideoView.java

```
if (getGSYVideoManager() != null) {
            getGSYVideoManager().setSpeed(speed, soundTouch);
        }
```

**Comment by AldenLei** [comment]
@CarGuo 你好，我使用了最新版本，但是自定义布局的时候，在init方法中findViewById找不到对应的view,返回是null,新布局我就在标准布局基础上新增了几个view,
public class QuCustomVideoPlayer extends StandardGSYVideoPlayer {
 public QuCustomVideoPlayer(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }
    public QuCustomVideoPlayer(Context context) {
        super(context);
    }
    public QuCustomVideoPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

  @Override
    public int getLayoutId() {
        return R.layout.video_layout_qu_custom;
    }
 @Override
    protected void init(Context context) {
        super.init(context);
        circleTextView = (TextView) findViewById(R.id.tv_circle);
        spleedTextView = (TextView) findViewById(R.id.tv_speed_adjust);
        rangeSelectionView = (RangeSelectionView) findViewById(R.id.rsv_range);
}
}
