### ISSUE TITLE
循环播放视频，画面会卡住

### ISSUE THREAD

**Issue by luomantic** [CarGuo/GSYVideoPlayer#1545]
## 问题描述：
循环播放一个文件夹下的4K视频，播放一两个小时后，画面会卡住或者黑屏。
切换不同的播放内核后，表现为播放不同的时间后，画面卡住或黑屏。

## 问题机型/系统：
rk3288板卡

## 复现：
问题可以复现，但是，无问题log，程序不奔溃，内存状态也是正常的。

**Comment by CarGuo** [comment]
这么诡异，我只能看着issue发呆

**Comment by luomantic** [comment]
> 这么诡异，我只能看着issue发呆

好吧，是好奇怪啊，换其他板卡，播放2K视频就没有这个问题。

**Comment by luomantic** [comment]
> 这么诡异，我只能看着issue发呆

经过测试后，结果发现是硬件通信的问题。已解决ths。

**Comment by ZJLeBron** [comment]
> > 这么诡异，我只能看着issue发呆
> 
> 经过测试后，结果发现是硬件通信的问题。已解决ths。

请问大佬硬件通信问题怎么检测解决的

**Comment by luomantic** [comment]
> > > 这么诡异，我只能看着issue发呆
> > 
> > 
> > 经过测试后，结果发现是硬件通信的问题。已解决ths。
> 
> 请问大佬硬件通信问题怎么检测解决的

之前硬件是i2c通信有问题，后来发现这个库也有问题，再后来重新根据exoplayer自定义了一版播放器，问题已解决.
