### ISSUE TITLE
请教下暂停后进度条跳动问题

### ISSUE THREAD

**Issue by itljw** [CarGuo/GSYVideoPlayer#1546]
设置了：
 VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
之后，正常播放拖动进度条不会跳动，但暂停后拖动进度条就又会出现跳动的问题，请问有办法解决吗？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1590

**Comment by Domlaa** [comment]
同样遇到该问题，使用的是系统的内核，但是拖动或点击进度条改变播放位置之后，进度条会有一帧明显的回退，请问要怎么解决呢
