### ISSUE TITLE
侧滑菜单

### ISSUE THREAD

**Issue by whj33** [CarGuo/GSYVideoPlayer#1547]
我想在横屏的时候可以弹出一个侧滑菜单  是一个viewpager

建议用什么实现好呢

用DrawerLayout的话好像有一点冲突   全屏的话viewpager不能出来

**Comment by CarGuo** [comment]
这个···不算这个项目的问题吧···

**Comment by whj33** [comment]
就是请问一下    全屏的话   从右侧弹出菜单   您建议用什么实现好

**Comment by CarGuo** [comment]
这个你估计需要看看源码，在 GSYVideoControlView 下的 ontouch 内，判断滑动的位置是右边多少的话，在down 或者 move的是否分发事件出去，调出侧滑
