### ISSUE TITLE
列表视频无法设置header

### ISSUE THREAD

**Issue by zhiyou007** [CarGuo/GSYVideoPlayer#1549]
根据官方demo,设置headers,然后把setCacheWithPlay(false),然后设置了头部,抓包发现没有设置成功

## 问题描述：

        gsyVideoOptionBuilder
                .setIsTouchWiget(false)
                .setThumbImageView(imageView)
                .setUrl(url)
                .setVideoTitle(title)
                .setSetUpLazy(true)//lazy可以防止滑动卡顿
                .setVideoTitle(title)
                .setCacheWithPlay(false)
                .setRotateViewAuto(true)
                .setLockLand(true)
                .setThumbPlay(true)
                .setPlayTag(videoModel.img)
                .setShowFullAnimation(true)
                .setNeedLockFull(true)
                .setPlayPosition(position)
                .setMapHeadData(headers)

这样设置setMapHeadData(headers)    然后抓包显示,没有设置进去

## 问题机型/系统：

 华为 Android6.0

**Comment by CarGuo** [comment]
我是试了demo正常

然后我测试了下，应该是 

            .setSetUpLazy(true)//lazy可以防止滑动卡顿

这个导致的，目前这个可能会导致header出现问题，其实新版中 setSetUpLazy 已经不起作用了

**Comment by zhiyou007** [comment]
可以了,但又出现一个问题,设置User-agent 怎么出来两个,是否中间没做下判断

**Comment by CarGuo** [comment]
ijk内核默认会带上一个 User-agent ，这个它内部写死了
