### ISSUE TITLE
横屏自定义布局fragment不能展示数据

### ISSUE THREAD

**Issue by whj33** [CarGuo/GSYVideoPlayer#1550]
就是我发现我在继承StandardGSYVideoPlayer以后   自定义布局的时候，我在布局里放了一个fragment，竖屏的时候fragment可以展示数据，但是横屏就不可以，请问可能是什么原因

**Comment by CarGuo** [comment]
fragment 在横竖屏之间没有传递 ，类似这个 https://github.com/CarGuo/GSYVideoPlayer/issues/1548

**Comment by whj33** [comment]
@Override
    public GSYBaseVideoPlayer startWindowFullscreen(Context context, boolean actionBar, boolean statusBar) {
        GSYBaseVideoPlayer gsyBaseVideoPlayer = super.startWindowFullscreen(context, actionBar, statusBar);

        NextDetailVideo listGSYVideoPlayer = (NextDetailVideo) gsyBaseVideoPlayer;
        mOnItemClickListener.onShareClick(listGSYVideoPlayer.viewpager_videoland);
        return listGSYVideoPlayer;
    }




    detailPlayer.setOnShareListener(new NextDetailVideo.OnShareClickListener() {
            @Override
            public void onShareClick(ViewPager viewPager) {
                    List<Fragment> mFragments = new ArrayList<>();
                    Fragment datafragment = new datafragment();
                    Fragment notefragment = new notefragment();
                    Fragment chooseclassfragment = new chooseclassfragment();
                    mFragments.add(chooseclassfragment);
                    mFragments.add(datafragment);
                    mFragments.add(notefragment);
                    ChooseFragmentPagerAdapter mainVPAdapter = new ChooseFragmentPagerAdapter(getSupportFragmentManager(), mFragments);
                    viewPager.setAdapter(mainVPAdapter);

**Comment by whj33** [comment]
我传递了之后发现列表能展示，但是viewpager不能展示

**Comment by whj33** [comment]
请问是什么原因

**Comment by CarGuo** [comment]
类似的问题都是一些配置或者布局问题，请自行查找吧
