### ISSUE TITLE
Demo里为什么这么多泄露呢

### ISSUE THREAD

**Issue by lelefly** [CarGuo/GSYVideoPlayer#1551]
![screenshot_2018-10-26-15-44-18-319_com example gsyvideoplayer](https://user-images.githubusercontent.com/18587168/47552280-e946e900-d936-11e8-9830-b8f240870171.png)

小米8

**Comment by CarGuo** [comment]
如果是AudioManager，可直接忽略

**Comment by lelefly** [comment]
> 如果是AudioManager，可直接忽略

都是这种Context泄露
![screenshot_2018-10-26-15-56-40-188_com example gsyvideoplayer](https://user-images.githubusercontent.com/18587168/47552774-18aa2580-d938-11e8-959c-95576d791e45.png)
