### ISSUE TITLE
导致 APP崩溃

### ISSUE THREAD

**Issue by CleverSJX** [CarGuo/GSYVideoPlayer#1552]
## 问题描述：
compile 'com.shuyu:gsyVideoPlayer-java:2.1.3'
compile 'com.shuyu:gsyVideoPlayer-ex_so:2.1.3'

APP 崩溃

## 问题机型/系统：

真机 Hisense  Android4.4.2
架构 armeabi-v7a

## 问题log（如果有）

```
SIGILL(ILL_ILLOPC)

1 #00 pc 0029972c /data/app-lib/com.longjing-1/libijkffmpeg.so [armeabi-v7a]
--
2 #01 pc 002998ab /data/app-lib/com.longjing-1/libijkffmpeg.so (ff_simple_idct_put_neon+54) [armeabi-v7a]


```

**Comment by CarGuo** [comment]
参考demo配置ndk过滤，注意如果有其他so，请选择配置上都有的so文件

**Comment by CleverSJX** [comment]
ndk 设置了
ndk {
            // 设置支持的SO库架构
            abiFilters 'armeabi' , 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
        }

**Comment by CarGuo** [comment]
目前该库支持如上so，但是你用的其他库是否也都有支持如上so？
可以尝试能否在demo复现
