### ISSUE TITLE
播放控件隐藏的时候如何修改

### ISSUE THREAD

**Issue by huclengyue** [CarGuo/GSYVideoPlayer#1555]
您好，请教一下，如何调整，触摸播放器后，播放控件自动隐藏的时间呢？还有在播放中如何点击屏幕后自动暂停呢

**Comment by CarGuo** [comment]
隐藏时间有 setDismissControlTime 

双击暂停的可以看源码 touchDoubleUp 和 onClickUiToggle 去重载

https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/base/GSYVideoControlView.java


```
    protected GestureDetector gestureDetector = new GestureDetector(getContext().getApplicationContext(), new GestureDetector.SimpleOnGestureListener() {
        @Override
        public boolean onDoubleTap(MotionEvent e) {
            touchDoubleUp();
            return super.onDoubleTap(e);
        }

        @Override
        public boolean onSingleTapConfirmed(MotionEvent e) {
            if (!mChangePosition && !mChangeVolume && !mBrightness) {
                onClickUiToggle();
            }
            return super.onSingleTapConfirmed(e);
        }
    });

```

**Comment by huclengyue** [comment]
好的 谢谢

**Comment by protectedMan** [comment]
setDismissControlTime设置为0，开始播放的时候这个暂停还是会闪一下。
有没有机制设置可以让开始播放时不显示暂停

**Comment by CarGuo** [comment]
@protectedMan   
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/SampleCoverVideo.java
看这个类的注释
    /******************* 下方重载方法，在播放开始不显示底部进度和按键，不需要可屏蔽 ********************/
