### ISSUE TITLE
暂停情况下切换全屏，先黑屏然后过一会才有画面

### ISSUE THREAD

**Issue by caopeng000** [CarGuo/GSYVideoPlayer#1556]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
我使用了阿里云播放内核进行播放，按照SystemPlayerManager的方式，继承IPlayerManager然后把该填写的播放事件放进去，然后使用阿里云内核播放的时候，从列表切换全屏的时候，会先黑屏一下，然后再进行播放。我也跟了代码。有个showDisplay方法，如果Sureface销毁后调用了    mediaPlayer.setSurface(null);我看系统播放内核也是这样的，但是他切换全屏就不会出现黑屏的情况，我是哪里出现问题了吗帮忙分析下，可提供我新写的阿里云播放内核java文件。谢谢了

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
这个我记得是和内核的内部处理方式有关，就是切换surface时，对surface的持有和绘制有关，我记得exoplayer1的时候也会出现这个问题，那时候旧版本我是用了比较粗的方式
```
    private void showDisplay(Message msg) {
        if (msg.obj == null && mediaPlayer != null) {
            mediaPlayer.setSurface(null);
        } else {
            Surface holder = (Surface) msg.obj;
            if (mediaPlayer != null && holder.isValid()) {
                mediaPlayer.setSurface(holder);
            }
            if (mediaPlayer instanceof IjkExoMediaPlayer) {
                if (mediaPlayer != null && mediaPlayer.getDuration() > 30
                        && mediaPlayer.getCurrentPosition() < mediaPlayer.getDuration()) {
                    mediaPlayer.seekTo(mediaPlayer.getCurrentPosition() - 20);
                }
            }
        }
    }
```

seek的时候会触发持有surface的立即重绘

**Comment by caopeng000** [comment]
我尝试了使用seekto方法，但是还是会出现短暂黑屏的情况，现在我看您代码使用的是EXO2，针对于exoplayer1出现的问题您是在现在的版本修复了吗？

**Comment by CarGuo** [comment]
你可以看看从readme跳过去看看版本文件
