### ISSUE TITLE
seekbar 进度条拖到视频最后，和视频时间差4-6秒才能播完成；

### ISSUE THREAD

**Issue by zhuoshirong** [CarGuo/GSYVideoPlayer#1557]
超过1分钟度视频，播放时拖动进度条视频最后，和视频总结束时间差4-6秒才能播完成，请问有解决方案吗；

**Comment by CarGuo** [comment]
如果是拖动后进度条跳动，可以看看问题集锦

**Comment by zhuoshirong** [comment]
哪里看，这里面没有看到呀；

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md

**Comment by wangchang163** [comment]
我也遇到这个问题了，seekto到一个时间之后，getcurrentposition获取的时间会随机小几秒到十秒不等

**Comment by CarGuo** [comment]
这个属于关键帧跳动问题，具体可见问题集锦
