### ISSUE TITLE
GSYImageCover问题

### ISSUE THREAD

**Issue by ZzjBeatYou** [CarGuo/GSYVideoPlayer#156]
为什么播放器布局中一定要有GSYImageCover？应该不是必须的吧，可能会造成oom

**Comment by CarGuo** [comment]
这个是暂停的时候，如果没有这个，退到后台，texture就会被销毁，再进来没播放之前就会黑色的。而且这里做了限制和回收，基本没遇到过oom

**Comment by ZzjBeatYou** [comment]
在项目中试了几天，视频频繁暂停OOM的概率的还是很高的
希望大佬能够给mFullPauseBitmap加入弱引用,或者提供不使用mCoverImageView的api

另外用leakcanary监测到VideoManager经常溢出

**Comment by CarGuo** [comment]
溢出的地方可以提供log吗？？？api后面我加一个吧！

**Comment by ZzjBeatYou** [comment]
![Uploading 微信图片_20170421212437.png…]()

**Comment by ZzjBeatYou** [comment]
```
android.media.AudioManager$1.this$0 (anonymous subclass of android.media.IAudioFocusDispatcher$Stub)
references android.media.AudioManager.mAudioFocusIdListenerMap
references java.util.HashMap.table
references array java.util.HashMap$HashMapEntry[].[1]
references java.util.HashMap$HashMapEntry.value
references com.shuyu.gsyvideoplayer.GSYVideoPlayer$1.this$0 (anonymous implementation of android.media.AudioManager$OnAudioFocusChangeListener)
```

**Comment by CarGuo** [comment]
android.media.AudioManager这个泄漏是系统的污染问题，找过挺多资料的，没什么效果，但这个泄漏不回造成太大问题，倒是你说的那个会引起OOM的，后面我增加个开关。

**Comment by CarGuo** [comment]
1.6.5已增加接口

**Comment by CarGuo** [comment]
1.6.5已增加接口

**Comment by chenhui3014** [comment]
android.media.AudioManager$1.this$0 (anonymous subclass of android.media.IAudioFocusDispatcher$Stub)
references android.media.AudioManager.mAudioFocusIdListenerMap
references java.util.HashMap.table
references array java.util.HashMap$HashMapEntry[].[1]
references java.util.HashMap$HashMapEntry.value
references com.shuyu.gsyvideoplayer.GSYVideoPlayer$1.this$0 (anonymous implementation of android.media.AudioManager$OnAudioFocusChangeListener)

这个内存溢出还是一直报，没有解决方案吗

**Comment by CarGuo** [comment]
AudioManager这个其实代码已经正常释放，他的一些泄露属于系统级别的污染，这个你可以在stackflow上看看，目前我还没找到什么好的方案，如果有什么建议可以提出下。
