### ISSUE TITLE
实现音频播放器

### ISSUE THREAD

**Issue by bingdu0** [CarGuo/GSYVideoPlayer#1565]
## 问题描述：
想用GSYVideoPlayer 实现一个音频的播放器，自定义布局里面我没有写 
```
<FrameLayout
        android:id="@+id/surface_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center">
    </FrameLayout>
```
这个，然后就报空指针
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.getChildCount()' on a null object reference
        at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.addTextureView(GSYTextureView.java:269)
```
我就播放一个音频还要加那个FrameLayout吗？实现音频播放，界面是自定义的 还有什么注意事项吗？
## 问题机型/系统：

华为mate8

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/6db7648038a8de03ee7fbb82d051dc12d9cbfa5c/app/src/main/res/layout/empty_control_video.xml  类似这吧

https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java

**Comment by bingdu0** [comment]
对，我是参考的这一个，但是播放音频的时候，是没有画面的。添加  
  ```
<FrameLayout
        android:id="@+id/surface_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center">

    </FrameLayout>
```
的话，假如我不知道地址是MP3 或者MP4 格式，MP4的就会有画面了，EmptyControlVideo只是无任何控制ui的播放，但是我不加的话，会报空指针。

**Comment by bingdu0** [comment]
> https://github.com/CarGuo/GSYVideoPlayer/blob/6db7648038a8de03ee7fbb82d051dc12d9cbfa5c/app/src/main/res/layout/empty_control_video.xml 类似这吧
> 
> https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java

对，我是参考的这一个，但是播放音频的时候，是没有画面的。添加
```
<FrameLayout
      android:id="@+id/surface_container"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:gravity="center">

  </FrameLayout>
```
的话，假如我不知道地址是MP3 或者MP4 格式，MP4的就会有画面了，EmptyControlVideo只是无任何控制ui的播放，但是我不加的话，会报空指针。我就想实现只有ui控制，没有播放的画面。

**Comment by CarGuo** [comment]
哦，你是想mp4的时候也没画面是吧，你那你可以考虑layout不改的情况下，继承重载下 addTextureView
