### ISSUE TITLE
自定义两套布局布局原理

### ISSUE THREAD

**Issue by qhs107** [CarGuo/GSYVideoPlayer#1566]
@Override
    public int getLayoutId() {
        if (mIfCurrentIsFullscreen) {
            //横屏
            return R.layout.layout_video_land;
        }
        //竖屏
        return R.layout.layout_video_normal;
    }

我在横屏状态下给布局添加了一个viewpager,
竖屏状态下没有添加，
切回竖屏然后又切回横屏以后发现viewpager数据消失了

请问两套布局的原理是什么

**Comment by CarGuo** [comment]
就是切换了view显示，全屏的时候新构建了一个view，clone了参数去同步显示

**Comment by qhs107** [comment]
如果只是横屏状态下需要展示一个控件，竖屏不需要这个控件，这个时候需要传递什么吗

**Comment by CarGuo** [comment]
public int getLayoutId()  返回两个布局就可以了

不过重载方式记得补上这个
```
    public GSYVideoControlView(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

```

**Comment by qhs107** [comment]
我横屏时候控件适配上数据以后，切竖屏然后再切回来   数据就没了    是不是还要再次适配一遍数据

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1571
