### ISSUE TITLE
列表详情页切换后，从详情页返回，怎么让列表的播放接上详情页的？

### ISSUE THREAD

**Issue by swustmuzi** [CarGuo/GSYVideoPlayer#1568]
## 问题描述：

列表详情页切换后，从详情页返回，怎么让列表的播放接上详情页的？

尝试了用列表到详情的方式，返回后列表的没有播放，求教一下

**Comment by CarGuo** [comment]
因为过去详情的时候，其实列表的已经被释放了。
而在详情destory的时候，也是释放了内核

其实从列表到详情，切换的是播放UI，播放内核还在，所以成功切换，这里切换的主要是监听和surface。

所以如果详情回到列表还需继续播放，那么页面销毁时，内核不能释放，只是实现播放的surface和监听切换，逻辑和从列表过去是一样的

**Comment by swustmuzi** [comment]
> 因为过去详情的时候，其实列表的已经被释放了。
> 而在详情destory的时候，也是释放了内核
> 
> 其实从列表到详情，切换的是播放UI，播放内核还在，所以成功切换，这里切换的主要是监听和surface。
> 
> 所以如果详情回到列表还需继续播放，那么页面销毁时，内核不能释放，只是实现播放的surface和监听切换，逻辑和从列表过去是一样的

那在内核被释放的情况下，播放同一个视频，这样有办法恢复到上一次播放的进度吗？

**Comment by CarGuo** [comment]
这个需要你自己记录实现了。
比如返回的时候，setup、setonStart、startPlayLogic
