### ISSUE TITLE
全屏和半屏的布局切换

### ISSUE THREAD

**Issue by mejealousy** [CarGuo/GSYVideoPlayer#157]
你好，请问：
         1.实现全屏和半屏的布局切换，看代码里，注释写需要重载构造函数，这指要进行什么操作吗？
         2.看代码里，似乎没有重新调用 getLayoutId() 的地方，所以这个全屏和半屏的思路是？
不是太明白，希望指点下，感谢。

**Comment by CarGuo** [comment]
你看到demo中的LandVideo

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/LandLayoutVideo.java

**Comment by mejealousy** [comment]
嗯，我是先看了 demo 中的 landVideo 例子，不明白才过来询问。
是可以实现全屏和半屏在播放时候的动态布局切换吗，还是其他？感觉，是不是哪里理解有误。

**Comment by CarGuo** [comment]
布局的话是你getLayoutId是什么，它就是什么。不过因为全屏和非全屏之间的一些强关系，需要重载那个构造函数，全屏的标志为才能在getLayoutId之前生效。

**Comment by mejealousy** [comment]
OK，那是我理解错了。
我以为是在视频播放的时候，全屏和半屏可以动态切换。
感谢~
