### ISSUE TITLE
求助！关于两个Player同时播放的问题

### ISSUE THREAD

**Issue by 103945089** [CarGuo/GSYVideoPlayer#1570]
## 问题描述：两个Player同时播放的问题。

场景是这样，一个player播放暂停的时候，我会在这个player所在的ViewGrop再添加一个player用来播放广告视屏(需求如此)。现在遇到的问题是，外面的player onpause之后。 里面新建的player在startPlayLogic之后，外面的player会被release掉？ 现象是这个player onresume是从头开始播放的？

求助，源码不是很懂，正在看！谢谢

## 问题机型/系统：

```

**Comment by CarGuo** [comment]
下载Demo，Demo中有多个同时播放的支持，有多个广告实现的demo效果

**Comment by 103945089** [comment]
OK 谢谢 好运！
