### ISSUE TITLE
视频暂停时添加广告图片

### ISSUE THREAD

**Issue by Bard456** [CarGuo/GSYVideoPlayer#1571]
## 问题描述：

想在视频暂停时，添加一个广告图片，目前在普通播放时，在自己写的播放详情界面可以实现，但是在全屏播放时，如何在暂停时添加一个广告图片？

**Comment by CarGuo** [comment]
看一下 GSYBaseVideoPlayer 和   的源码你就知道， 主要是 
```
cloneParams   \   startWindowFullscreen \ resolveFullVideoShow
```

对他们的使用实现可以参考 StandardGSYVideoPlayer的

```
cloneParams   \   startWindowFullscreen \ resolveFullVideoShow
```
