### ISSUE TITLE
java.util.NoSuchElementException

### ISSUE THREAD

**Issue by JeremyHwc** [CarGuo/GSYVideoPlayer#1573]
java.util.ArrayDeque.removeFirst(ArrayDeque.java:264)
--
2 com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(Unknown Source:65)
3 com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(Unknown Source:75)
4 com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(Unknown Source:25)
5 com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(Unknown Source:2)
6 android.os.Handler.dispatchMessage(Handler.java:105)
7 android.os.Looper.loop(Looper.java:171)
8 android.app.ActivityThread.main(ActivityThread.java:6699)
9 java.lang.reflect.Method.invoke(Native Method)
10 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
11 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

机型有这些：
![qq 20181102163028](https://user-images.githubusercontent.com/19958785/47902224-a9df4600-debc-11e8-8293-22274b861796.png)

**Comment by CarGuo** [comment]
希望能找到复现场景，因为有一些崩溃属于二次崩溃的
