### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by JeremyHwc** [CarGuo/GSYVideoPlayer#1574]
com.google.android.exoplayer2.Timeline$1.getPeriod(Timeline.java)
--
2 com.google.android.exoplayer2.Timeline.getPeriod(Timeline.java)
3 com.google.android.exoplayer2.ExoPlayerImpl.playbackInfoPositionUsToWindowPositionMs(ExoPlayerImpl.java)
4 com.google.android.exoplayer2.ExoPlayerImpl.getCurrentPosition(ExoPlayerImpl.java)
5 com.google.android.exoplayer2.ExoPlayerImpl.getContentPosition(ExoPlayerImpl.java)
6 com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java)
7 com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java)
8 com.google.android.exoplayer2.analytics.AnalyticsCollector.generatePlayingMediaPeriodEventTime(AnalyticsCollector.java)
9 com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java)
10 com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java)
11 com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java)
12 com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java)
13 com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java)
14 com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java)
15 android.os.Handler.dispatchMessage(Handler.java:102)
16 android.os.Looper.loop(Looper.java:145)
17 android.app.ActivityThread.main(ActivityThread.java:5942)
18 java.lang.reflect.Method.invoke(Native Method)
19 java.lang.reflect.Method.invoke(Method.java:372)
20 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
21 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

![1541149064 1](https://user-images.githubusercontent.com/19958785/47904749-79011000-dec0-11e8-8d52-1f9a3ecea136.jpg)

**Comment by CarGuo** [comment]
希望能找到复现场景，因为有一些崩溃属于二次崩溃的

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1573
