### ISSUE TITLE
播放m3u8 的视频，下面进度条会跳转到开始的位置

### ISSUE THREAD

**Issue by xxxunfind** [CarGuo/GSYVideoPlayer#1575]
## 问题描述：

播放m3u8 的视频，下面时间和进度条会跳转到开始的位置，视频还是连续播放

## 问题机型/系统：

例如 真机 红米note3 Android6.0

## Demo中的复现步骤
视频地址：
https://miniprogram.yex360.com/m3u8?url=https://s.yex360.com/pub/common/201807/3DHVAXIR78XmBJ8zWgoeR3s3QDUcYP8Ex3N33JYk.m3u8
Demo中的detailPlayer页面打开后,播放到6分56秒左右的时候会出现这个问题。

**Comment by CarGuo** [comment]
可以切换到exo模式试试
```
        //PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
        //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
        //PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
```

**Comment by xxxunfind** [comment]
切换到exo 模式的话界面会一直在loading，等了十几分钟都是
切换到系统模式，进度条一直在走，有声音，画面会卡那里，没有更新

**Comment by CarGuo** [comment]
那基本上就是流的问题了

**Comment by xxxunfind** [comment]
嗯，有没有什么好的处理办法，跳过有问题的播放后面的？ 我有试过在微信里播放是可以播放的

**Comment by CarGuo** [comment]
我用demo播放  PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式 

播放你这个url，正常啊，不会出现一只loading

在detailPlayer页面下，关闭了cache的

**Comment by xxxunfind** [comment]
我测试的时候也试过关闭了cache 还是会一直loading  在06:56左右的时候，与机型有关？

**Comment by CarGuo** [comment]
哦，我是直接拖拽过去可以，播放到那个节点确实还是会。
和机型没关系，这个应该是在获取m3u8的ts切片时，流的时序可能会出现问题

大概在34的ts这里出现了问题

**Comment by xxxunfind** [comment]
类似这种问题，大佬有没有什么好的建议？

**Comment by CarGuo** [comment]
目前没什么太好的建议，主要是不确定问题是什么
