### ISSUE TITLE
在activity 里监听不到gsyMediaPlayerListener

### ISSUE THREAD

**Issue by pyp163** [CarGuo/GSYVideoPlayer#1578]
电视盒子
在activity 里监听不到gsyMediaPlayerListener
 videoView.getGSYVideoManager().setListener(gsyMediaPlayerListener);

 private GSYMediaPlayerListener gsyMediaPlayerListener = new GSYMediaPlayerListener(){
        @Override
        public void onPrepared() {
            LogDog.i("--------onPrepared----------");
        }

        @Override
        public void onAutoCompletion() {

        }

        @Override
        public void onCompletion() {

        }

        @Override
        public void onBufferingUpdate(int percent) {
            LogDog.i("--------percent----------"+percent);
        }

        @Override
        public void onSeekComplete() {

        }

        @Override
        public void onError(int what, int extra) {

        }

        @Override
        public void onInfo(int what, int extra) {
            LogDog.i("--------what----------"+what);
        }

        @Override
        public void onVideoSizeChanged() {

        }

        @Override
        public void onBackFullscreen() {

        }

        @Override
        public void onVideoPause() {

        }

        @Override
        public void onVideoResume() {

        }

        @Override
        public void onVideoResume(boolean seek) {

        }
    };

**Comment by CarGuo** [comment]
不是很理解

**Comment by pyp163** [comment]
@CarGuo 
在播放时videoView.getGSYVideoManager().setListener(gsyMediaPlayerListener);是无效的，
以下方法并没执行
 @Override
    public void onBufferingUpdate(int percent) {
        LogDog.i("--------percent----------"+percent);
    }
  @Override
    public void onError(int what, int extra) {

    }
    @Override
    public void onInfo(int what, int extra) {
        LogDog.i("--------what----------"+what);
    }
 @Override
    public void onCompletion() {

    }
我想监听这些方法，来实现我想要功能，由于电视频ui不同，摇控器操作

**Comment by CarGuo** [comment]
getGSYVideoManager().setListener(gsyMediaPlayerListener); 方法不是对外公开使用的，
对外公开使用的是videocallback
如果你真的需要，推荐你继承后做自定义

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1302

**Comment by pyp163** [comment]
@CarGuo 好的，谢谢，我知道该怎么做了
