### ISSUE TITLE
setup之前回调或者release之前回调记录当前播放时间

### ISSUE THREAD

**Issue by jialovegirl** [CarGuo/GSYVideoPlayer#1580]
需要在切换当前播放或退出播放器的时候记录播放时间

正常退出播放器，我重写了release()方法，在调用
`super.release();`
之前是可以获取到播放时间

在切换播放URL的时候调用了
`setUp(url, false, titleText);`
没有进入release方法

有没有办法在当前播放将要销毁时获取到播放时间？

自定义播放继承了StandardGSYVideoPlayer

thx!

**Comment by jialovegirl** [comment]
看了下onCompletion回调，好像这个是在新的URL设置进去才会执行，getCurrentPositionWhenPlaying返回0

**Comment by CarGuo** [comment]
onLossAudio 或者 onLossTransientAudio
