### ISSUE TITLE
wifi和4g切换问题

### ISSUE THREAD

**Issue by caopeng000** [CarGuo/GSYVideoPlayer#1581]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

现在产品需要说如果是4G的话则在当前视图展示是否继续使用移动网络播放，而项目中是直接弹出个Dialog，请问下这款的功能我应该在哪里添加

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
默认有showWifiDialog，如果不够可以继承后重载，源码有注释
