### ISSUE TITLE
E/IJKMEDIA: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protoco

### ISSUE THREAD

**Issue by zt80hou** [CarGuo/GSYVideoPlayer#1582]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
项目直接引用的so文件
报错信息如下，是不是这个流有问题？
11-06 17:26:45.120 13910-14325/? E/IJKMEDIA: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
11-06 17:26:45.121 13910-14325/? E/IJKMEDIA: https://ihzlh.linker.cc/ihzlh/ec9791add603193d31df93b87f063dfc.m3u8: I/O error
11-06 17:26:45.124 13910-13910/? E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

## 问题机型/系统：

PLK-UL00/Android6.0

## Demo中的复现步骤

demo可以直接播放

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
demo中是否复现

**Comment by CarGuo** [comment]
可以看看是不是切换dns问题
```
VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
```

如果还是不行，再试试

```
        //PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
```

**Comment by zt80hou** [comment]
Exo2可以，解决了，谢谢！
