### ISSUE TITLE
您好，请问现在支持缓存的加密吗？

### ISSUE THREAD

**Issue by zzzzzzzjy** [CarGuo/GSYVideoPlayer#1584]
比如通过修改文件部分字节或其他方式使缓存的文件不被其他软件识别&播放

**Comment by CarGuo** [comment]
如果你说的是exoplayer的缓存的话，基本不会被识别

如果是androidvideocache的话，目前不支持。

**Comment by zzzzzzzjy** [comment]
好的，谢谢
