### ISSUE TITLE
是否支持react-native项目呢

### ISSUE THREAD

**Issue by zhanfangzxc** [CarGuo/GSYVideoPlayer#1587]
搜了issue，没有太多在RN项目中使用的示例，所以想请问一下
## 问题描述：

是否能够支持在react-native项目中使用

**Comment by CarGuo** [comment]
只有android版本，所以没有考虑rn，需要你自己通过viewmanager封装下

**Comment by zhanfangzxc** [comment]
能否明示一下呢，因为之前没有使用过ReactNative，目前刚开始做，希望能给一些更详细的说明

**Comment by CarGuo** [comment]
https://juejin.im/post/5946253561ff4b006cee4d65   参考这

**Comment by zhanfangzxc** [comment]
请问您之后有适配rn的倾向吗，因为我还是不知道如何下手，您的项目中的界面主要是很多Activity一类的，如果我需要自己去向rn暴露各种pause和start这种方法该怎么做呢，是不是还是需要调用ijkplayer的这些方法？
