### ISSUE TITLE
集成时显示包冲突

### ISSUE THREAD

**Issue by fengjian123** [CarGuo/GSYVideoPlayer#1589]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```Execution failed for task ':gsyvideoplayertest:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex


xxxxxxx

```

**Comment by CarGuo** [comment]
所以我觉得这种问题，在这里提 issue 是没有意义的····
