### ISSUE TITLE
使用慢速播放时，视频已经停止播放，但是seekbar和时间还没播放完

### ISSUE THREAD

**Issue by Ideaqjj** [CarGuo/GSYVideoPlayer#159]
使用慢速播放时，视频已经停止播放，但是seekbar和时间还没播放完

**Comment by CarGuo** [comment]
demo中未发现，有url嘛？

**Comment by Ideaqjj** [comment]
我播放的是本地视频，有这个问题

**Comment by CarGuo** [comment]
我这边也播放的过本地的···

**Comment by Ideaqjj** [comment]
-,-真的，我直接在demo里设置0.25f或者0.35f的播放速度，视频停止了，进度条也还在走，声音也还在走

**Comment by CarGuo** [comment]
按照ijk的说法，我文档上也写着推荐是0.5-2，bilibili自己的设置也是这个范围

**Comment by Ideaqjj** [comment]
了解了，多谢大神
