### ISSUE TITLE
Ijk拖动进度跳，画面未变化问题

### ISSUE THREAD

**Issue by itljw** [CarGuo/GSYVideoPlayer#1590]
设置了：  VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);

            VideoOptionModel videoOptionModel1 =
                    new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 25);

            List<VideoOptionModel> list = new ArrayList<>();
            list.add(videoOptionModel);
            list.add(videoOptionModel1);
            GSYVideoManager.instance().setOptionModelList(list);

            PlayerFactory.setPlayManager(IjkPlayerManager.class);

暂停，然后拖动进度条，画面停留在暂停时的画面，不会改变到拖动位置的画面，要过一段时间才会改变，请问有办法解决吗？

**Comment by CarGuo** [comment]
"enable-accurate-seek",  打开了的话，有些视频确实会可能出现这种效果，因为视频的关键帧问题，如果无法接受，只能切换其他模式试试。
```
        //PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
        //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
        //PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
```

**Comment by itljw** [comment]
本来是用exo模式的，但在htc one4.4系统的手机上会出现黑屏、画面和声音不同步的问题，所以才切回ijk试试...大佬，exo横竖屏切换后导致画面不同步的问题有办法解决吗？

**Comment by CarGuo** [comment]
你用的是哪个版本的？？demo中会出现这样的问题吗？？这个问题应该是比较老了的吧？？

**Comment by itljw** [comment]
用的是6.0.1，demo中也会，我用的是DetailPlayer那个页面测试     PlayerFactory.setPlayManager(Exo2PlayerManager.class);，切换到竖屏的全屏会黑屏，有声音没画面，但切换到横屏的全屏又没问题...

**Comment by itljw** [comment]
https://fs.bozhong.com/2018110814422289612.MP4，暂停后多切换几次竖屏的全屏就会出现了

**Comment by CarGuo** [comment]
不好意思，这么久才注意到，刚刚试了下，没复现问题呢

**Comment by woshiyizhijiao** [comment]
> 本来是用exo模式的，但在htc one4.4系统的手机上会出现黑屏、画面和声音不同步的问题，所以才切回ijk试试...大佬，exo横竖屏切换后导致画面不同步的问题有办法解决吗？

请问下这个问题解决了么， 我这里同样出现了这个问题， VideoOptionModel如果不设置是没事的

**Comment by itljw** [comment]
抱歉，没有，你在看下其它issue看有没有相关的。。。
