### ISSUE TITLE
使用最新的so库，播放rmvb格式，有声音没有画面

### ISSUE THREAD

**Issue by Icando26** [CarGuo/GSYVideoPlayer#1591]
## 问题描述：

使用最新6.0.1的so库，播放rmvb格式，有声音没有画面，有个别mvb，avi格式的电影有画面没有声音

真机测试：

    小米5Android8.0、华为meta8 Android8.0

     网上下载至手机的rmvb格式的电影，手机自带播放器播放没有问题，使用自己下的（但忘了是哪里下载的）so库也是播放ok的。

**Comment by AndroidJohnsonWang** [comment]
遇到同样问题
