### ISSUE TITLE
在androidx集成是发生错误

### ISSUE THREAD

**Issue by ksballetba** [CarGuo/GSYVideoPlayer#1593]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

androidx项目集成发生依赖失败

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for androidx.media:media:1.0.0
Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/media/media/1.0.0/media-1.0.0.aar'.
Could not HEAD 'https://dl.google.com/dl/android/maven2/androidx/media/media/1.0.0/media-1.0.0.aar'.
Connect to dl.google.com:443 [dl.google.com/6.6.6.6] failed: Connection timed out: connect
Connection timed out: connect
xxxxxxx

```

**Comment by crazecoder** [comment]
什么时候适配androidx，support已经不更新了，国外库基本上都已经适配androidx了

**Comment by CarGuo** [comment]
@crazecoder 下个版本
