### ISSUE TITLE
连续播放，播放一集后再播放下一集之前，有没有相应的回调？

### ISSUE THREAD

**Issue by lyq027** [CarGuo/GSYVideoPlayer#1594]
连续播放，播放一集后再播放下一集之前，有没有相应的回调？
使用场 景：
播放完一集，自动播下一集，需要更态更新当前集数的状态。

**Comment by Totomiz** [comment]
我重写了这个方法，在剧集自动播放下一集时候，该方法没有调用呢，我也需求差不多，需要更新一些文字状态
