### ISSUE TITLE
如何优化RTMP协议视频的延时

### ISSUE THREAD

**Issue by HotmilKz** [CarGuo/GSYVideoPlayer#1598]
在测试的时候 播放延时大概有5s左右，有什么方法或者设置能把延时控制在3s左右

**Comment by CarGuo** [comment]
不修改so源码的情况下， 只能参考 https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md   17

**Comment by HotmilKz** [comment]
@CarGuo

 IjkMediaPlayer ijkMediaPlayer = null;  
ijkMediaPlayer = new IjkMediaPlayer();  
ijkMediaPlayer.setOption(1, "analyzemaxduration", 100L);  
ijkMediaPlayer.setOption(1, "probesize", 10240L);  
ijkMediaPlayer.setOption(1, "flush_packets", 1L);  
ijkMediaPlayer.setOption(4, "packet-buffering", 0L);  
ijkMediaPlayer.setOption(4, "framedrop", 1L); 

这个应该在哪里设置？
