### ISSUE TITLE
视频高度写死，有黑边问题

### ISSUE THREAD

**Issue by itljw** [CarGuo/GSYVideoPlayer#1600]
视频列表需要写死高度，导致上下出现黑边，有方法处理吗？试过拉伸，但都是全屏拉伸，而我只需要高度能填充满显示区域就行，宽度不需要做拉伸，大佬，有办法处理吗？

**Comment by CarGuo** [comment]
你这总情况的话，需要自定义surface去实现了，类似 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/CustomRenderVideoPlayer.java

**Comment by itljw** [comment]
好的，谢谢大佬，我去试试
