### ISSUE TITLE
播放rtsp流 播放延迟问题

### ISSUE THREAD

**Issue by silence-jianghuan** [CarGuo/GSYVideoPlayer#1602]
已经根据问题集锦优化 rtsp流秒开，开始延迟很低，但是播放过程中延迟越来越严重，请问有什么办法解决

**Comment by HotmilKz** [comment]
请问在哪里设置rtsp的秒开

**Comment by silence-jianghuan** [comment]
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,
                "rtsp_transport", "tcp");
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video");
        //根据媒体类型来配置
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
        list.add(videoOptionModel);
        //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);

        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 8);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(1, "analyzemaxduration", 100);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(4, "framedrop", 1);
        list.add(videoOptionModel);

         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50);

        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

**Comment by silence-jianghuan** [comment]
> @silence-jianghuan 只能说用问题集锦中的丢帧优化下看看



> 请问在哪里设置rtsp的秒开

https://www.jianshu.com/p/843c86a9e9ad

**Comment by silence-jianghuan** [comment]
> 请问在哪里设置rtsp的秒开

https://www.jianshu.com/p/843c86a9e9ad

**Comment by silence-jianghuan** [comment]
> @silence-jianghuan 只能说用问题集锦中的丢帧优化下看看

嗯 好的 感谢， 已经根据问题集锦里面相关的文章进行优化了 有一定效果，播放时间长了 延迟没那么严重了
