### ISSUE TITLE
关闭硬件加速后,视频无法渲染

### ISSUE THREAD

**Issue by bxhuhu** [CarGuo/GSYVideoPlayer#1605]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

因为开启硬件加速的情况下,虽然视频能播放,在进度条,标题存在花屏的现象,所以关闭硬件加速
但是关闭硬件加速之后,没有花屏,但是视频画面无法渲染.

## 问题机型/系统：

真机 华为HUAWEI BTV-W09

## Demo中的复现步骤

Demo中没有发现这个问题, 因为项目还集成了Unity工程.还引入了腾讯SDK,但是应该没有关联吧.

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by bxhuhu** [comment]
![img_1407](https://user-images.githubusercontent.com/15007944/48595250-cf755080-e98e-11e8-9938-74e096faff5c.JPG)
![Uploading IMG_1408.JPG…]()

**Comment by CarGuo** [comment]
demo不复现我只能说对比下demo。
或者看看是不是manifest配置 android:hardwareAccelerated
https://github.com/CarGuo/GSYVideoPlayer/issues/75

**Comment by bxhuhu** [comment]
唉.. 花屏你知道什么其他解决方法吗?

**Comment by CarGuo** [comment]
话说，你试过 GSYVideoType.setRenderType(GSYVideoType.SUFRACE); 试试吗？

**Comment by bxhuhu** [comment]
刚才试了,还是会花屏, 这种可能是哪方面引起的?  帮我分析下嘛..  我再调试看看, 我觉得跟渲染 硬件加速有关系,我看了网上好像可以针对View关闭硬件加速

**Comment by bxhuhu** [comment]
解决了,有点玄学,你都不敢信...  我把背景色从#000000改到了灰色就ok了.... 我去
