### ISSUE TITLE
无法解析ts流，http协议的ts流

### ISSUE THREAD

**Issue by huijiawanquba** [CarGuo/GSYVideoPlayer#1607]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在解析ts流，http链接的时候解析失败，无法播放。用exo的player可以播放，但是没有声音。
报错信息如下：
tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
链接如下：
Failed to open file 'http://192.168.0.1:8088/ts/prog?freq=259000&qam=2&rate=6875&sid=51&pmt=51&dcid=259000_51_00888881&check_device_drm=0&ecm=500' or configure filtergraph
## 问题机型/系统：

真机 华为荣耀note10 Android8.1

## Demo中的复现步骤

Demo中的InputUrlDetailActivity页面输入上面的ts流地址，点击播放会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
是否有外部流提供测试
