### ISSUE TITLE
使用 LandLayoutVideo 出现内存泄露

### ISSUE THREAD

**Issue by 15319934357** [CarGuo/GSYVideoPlayer#1608]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by 15319934357** [comment]
问题描述：

XXXX发生了这样的问题！
问题机型/系统：

例如 真机 小米note2 Android7.0
Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码： 

LandLayoutVideo 播放出现内存泄露

问题log（如果有）

如果不播放，关掉Activity可正常回收，如果一旦播放，再关掉页面，就会出现泄露无法回收，
  @Override
    public void onDestroy() {
        super.onDestroy();
        if (isPlay) {
         
            getCurPlay().release();
       
        }

        if (orientationUtils != null)
            orientationUtils.releaseListener();
       
    }
同样的方式测试过5.0demo  可以正常回收。

**Comment by 15319934357** [comment]
问题描述：

LandLayoutVideo 播放出现内存泄露
问题机型/系统：

华为荣耀6
Demo中的复现步骤

Demo中的detailPlayer页面打开后播放可出现。

问题代码：



问题log 

如果不播放，关掉Activity可正常回收，如果一旦播放，再关掉页面，就会出现泄露无法回收，
@override
public void onDestroy() {
super.onDestroy();
if (isPlay) {

        getCurPlay().release();
   
    }

    if (orientationUtils != null)
        orientationUtils.releaseListener();
   
}

同样的方式测试过5.0demo 可以正常回收。

**Comment by 15319934357** [comment]
getCurPlay().release();  无法彻底释放播放器。。可以在Android Studio 3.2.1  中测试。同样的问题，用你的5.0Demo不存在。没有什么Log，关掉页面后，打开多少次就有多少个实例。

**Comment by CarGuo** [comment]
getCurPlay().release(); 只要能调用到playerManager的IjkMediaPlayer的release就可以了，剩下的是ffmpeg在jni的内部异步释放
