### ISSUE TITLE
多个video播放会出现播放一段时间之后有个别video卡住

### ISSUE THREAD

**Issue by yanlianhanlin** [CarGuo/GSYVideoPlayer#1610]
我是参考大佬的MultiSampleVideo实现的多个播放器同时播放视频的功能。我是左侧固定一个视频播放器，右侧是一个linearlayout根据接口动态添加播放器播放视频，现在出现两个问题求教大佬应该怎么解决。
1.在播放一段时间之后会随机出现一个播放器视频卡住的问题，请问这个问题怎么解决？
2.我在右侧动态添加的时候设置了的右侧静音不播放声音，但是在播放一段时间的时候有时会出现右侧声音播放的问题，请问这个问题是因为什么原因出现的？

**Comment by CarGuo** [comment]
类似问题，只有描述我也无能为力
