### ISSUE TITLE
播放RTSP实时流出现问题，协议不支持

### ISSUE THREAD

**Issue by forever123** [CarGuo/GSYVideoPlayer#1612]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

安卓播放RTSP实时流发生了这样的问题！

## 问题机型/系统：

例如 真机华为P9 Android 7.0

## Demo中的复现步骤

Demo中的StandardGSYVideoPlayer面打开
String source1 = "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov";会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov   Protocol not found

```

**Comment by CarGuo** [comment]
需要ex_so依赖
