### ISSUE TITLE
封面问题

### ISSUE THREAD

**Issue by xyZangGit** [CarGuo/GSYVideoPlayer#1613]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

看了问题锦集，
我目前 封面是有一个URL地址，视频是由一个url地址，但是我看到demo里面的
SampleCoverVideo是
封面和视频都是一个地址；
我想分开写
我应该如何修改

 public void loadCoverImage(String url, int res) {
        mCoverOriginUrl = url;
        mDefaultRes = res;
        Glide.with(getContext().getApplicationContext())
                .setDefaultRequestOptions(
                        new RequestOptions()
                                .frame(1000000)
                                .centerCrop()
                                .error(res)
                                .placeholder(res))
                .load(url)
                .into(mCoverImage);
    }

没有找到单独loadVideoURL的类似方法

**Comment by CarGuo** [comment]
既然是demo里的，你改一改方法呗，把loadCoverImage(xxx,xxx,xxx)不就好了
