### ISSUE TITLE
demo问题

### ISSUE THREAD

**Issue by okmin3** [CarGuo/GSYVideoPlayer#1616]
小米8
大概看了下,直接编译的demo然后发现
demo 无法重力自动旋转?
case R.id.list_btn_2:
                //支持全屏重力旋转的列表播放，滑动后不会被销毁
                JumpUtils.goToVideoPlayer2(this);
对应 ListVideo2Activity 无法演示重力旋转
 case R.id.list_detail:
                //支持旋转全屏的详情模式
                JumpUtils.goToDetailPlayer(this);
这个也不行.
最后我一个个点了.就发现web detail具有.重力旋转功能...是我手机有问题.还是demo有问题....

**Comment by CarGuo** [comment]
列表是默认没有开启重力旋转支持的，列表的话demo里只有这个做了，

https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/ListVideoActivity.java

但是我忘记有没有打开标记位了

**Comment by okmin3** [comment]
折腾好久,终于知道原因了.因为我手机自己设置了屏幕锁定
/**
     * 是否更新系统旋转，false的话，系统禁止旋转也会跟着旋转
     *
     * @param rotateWithSystem 默认true
     */
    public void setRotateWithSystem(boolean rotateWithSystem) {
        this.mRotateWithSystem = rotateWithSystem;
    }
因为这个默认值是true. 我手机禁止了,所以不能旋转,只有WebDetailActivity 把这个值设置成false了.所以才会有上述现象.
建议默认系统禁止旋转也能旋转.因为我平常使用其他APP.爱奇艺,腾讯视频,其他github播放器等等 系统禁止旋转都不会对重力旋转产出影响.
个人感觉默认是无视系统禁止,才是常规操作.
