### ISSUE TITLE
我用的是无UI的界面,想让视频连续播放时中间过渡平缓 些,现在是黑一下一闪而过

### ISSUE THREAD

**Issue by chigang** [CarGuo/GSYVideoPlayer#1619]
我用的是无UI的界面,想让视频连续播放时中间过渡平缓 些,现在是黑一下一闪而过

**Comment by chigang** [comment]
就是下一个视频一下子就进来了,感觉不是很好

**Comment by CarGuo** [comment]
额···所以我没太明白

**Comment by chigang** [comment]
就是切换视频时会会有一会没有视频，背景是黑色就会展现出来，视频切换不是很平滑

**Comment by CarGuo** [comment]
参考 https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/ListGSYVideoPlayer.java
