### ISSUE TITLE
请问如何写gradle,优雅的过滤其他so 和传统播放器控件不同，刚开始有点不熟悉 ，看demo ondestory也没有释放操作 onresume没写播放那个

### ISSUE THREAD

**Issue by qssq** [CarGuo/GSYVideoPlayer#162]

**Comment by CarGuo** [comment]
请务必看demo和wik。比如
GSYVideoManager.onPause();静态方法，或者GSYVideoPlayer的onPause，释放的方法，全局返回的方法都有。

**Comment by qssq** [comment]
嗯，工具类方法五花八门 眼花缭乱  我看了playactivity发现没对onResume做处理所以我就误解了。ondestory也没做处理

**Comment by qssq** [comment]
有过滤so的提供吗，我现在只用v7a，我刚刚运行崩溃我哈怀疑是这个问题，l我的crashactivity都没走直接闪退 好奇怪

**Comment by qssq** [comment]
您的gradle玩的如此完美 请问过滤 so应该如何写的完美一点呢

libijkffmpeg.so	update ijk to 0.7.8.1 (2017-03-21)	23 days ago
libijkplayer.so	update ijk to 0.7.8.1 (2017-03-21)	23 days ago
libijksdl.so 比如只需要7a的

我以前是这样写的
  packagingOptions {
        exclude "lib/arm64-v8a/libimagepipeline.so"
        exclude "lib/x86/libimagepipeline.so"
        exclude "lib/x86_64/libimagepipeline.so"
        exclude "lib/armeabi/libimagepipeline.so"




    }
这样好累如果要忽略3个的话

**Comment by qssq** [comment]
```
    packagingOptions {
        exclude "lib/arm64-v8a/libimagepipeline.so"
        exclude "lib/x86/libimagepipeline.so"
        exclude "lib/x86_64/libimagepipeline.so"
        exclude "lib/armeabi/libimagepipeline.so"

        exclude "lib/arm64-v8a/libijksdl.so"
        exclude "lib/x86/libijksdl.so"
        exclude "lib/x86_64/libijksdl.so"
        exclude "lib/armeabi/libijksdl.so"

        exclude "lib/arm64-v8a/libijkplayer.so"
        exclude "lib/x86/libijkplayer.so"
        exclude "lib/x86_64/libijkplayer.so"
        exclude "lib/armeabi/libijkplayer.so"

        exclude "lib/arm64-v8a/libijkffmpeg.so"
        exclude "lib/x86/libijkffmpeg.so"
        exclude "lib/x86_64/libijkffmpeg.so"
        exclude "lib/armeabi/libijkffmpeg.so"


    }
```

求优雅的写法

**Comment by CarGuo** [comment]
http://www.jianshu.com/p/86e4b336c17d

**Comment by qssq** [comment]
虚拟键盘的问题我知道，但是菜单都没有呀，全屏我肯定得隐藏虚拟键盘的，但是菜单是应该点一下出来的，但是某些事情出现了一点情况

**Comment by CarGuo** [comment]
目前是错误了 会有 updateStartImage中有mCurrentState == CURRENT_STATE_ERROR，具体你想要什么自定义效果，完全可以拷贝一份standard播放器的代码，然后修改成你想要的逻辑
