### ISSUE TITLE
fragment中Recyclerview做无缝切换时，新页面会黑屏暂停不自动播放

### ISSUE THREAD

**Issue by No8blackball** [CarGuo/GSYVideoPlayer#1620]
## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 Honor v10 Android8.0

## Demo中的复现步骤

Demo中将fragment中列表的SampleCoverVideo替换成SwitchVideo做无缝切换效果会出现如题的bug。

**Comment by CarGuo** [comment]
demo中SwitchVideo工作正常，如替换请参考注意是哪些不同的需要处理，此类问题不属于bug

**Comment by No8blackball** [comment]
我是将demo的下载下来用fragment做无缝切换出现的bug。但是activity里面不会出现类似问题，不知道作者试过没有

**Comment by CarGuo** [comment]
这里的无缝切换用的是就是5.0的activity之间的共享元素动画，这个需要你看看具体的问题了

**Comment by EHG613** [comment]
@No8blackball 请问如何解决的，我也是fragment recyclerview ,切换后不自动播放
