### ISSUE TITLE
全屏无法播放下一部

### ISSUE THREAD

**Issue by Bard456** [CarGuo/GSYVideoPlayer#1622]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

开发以后添加了片头广告的需求，但是设置播放地址的时候是设置的一个，没有用List，因此想着在广告视频播放完成之后onAutoComplete里面再重新setUp视频地址，设置之后，正常的时候播放完广告可以正常播放重新setUp的视频，但是在一开始播放广告全屏就不能继续播放，会变成重新播放的界面，点击播放之后，还是重新播放广告，不会播放视频，断点跟进之后发现点击播放按钮以后，mOriginUrl和mUrl仍然为之前广告的地址

```
@Override
    public void onAutoComplete(String url, Object... objects) {
        if (!url.equals(videoUrl)) {
            mView.getVideoPlayer().startPlayLogic(videoUrl);
        }
    }

 public void startPlayLogic(String url) {
        setUp(url, true, mTitle);
        startPlayLogic();
    }
```

## 问题log（如果有）

```
E/MediaPlayerNative: Attempt to call getDuration in wrong state: mPlayer=0x0, mCurrentState=1
E/MediaPlayerNative: error (-38, 0)
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
E/MediaPlayer: Error (-38,0)

```

**Comment by CarGuo** [comment]
mView.getVideoPlayer().getCurrentPlayer().startPlayLogic(videoUrl);
