### ISSUE TITLE
带账号密码的rtsp视频流放不了

### ISSUE THREAD

**Issue by zuimengliu** [CarGuo/GSYVideoPlayer#1623]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
类似这种地址的播放不出来
rtsp://admin:12345678@120.211.60.16:60200/cam/realmonitor?channel=1&subtype=1

**Comment by CarGuo** [comment]
是否已经使用了ex_so依赖，设置了tcp连接？

**Comment by alaj** [comment]
在常见问题集锦里有rtsp问题说明，成功解决，感谢
