### ISSUE TITLE
求助，RecyclerView切换时会重新播放

### ISSUE THREAD

**Issue by lzy6** [CarGuo/GSYVideoPlayer#1625]
问题描述：
RecyclerView全屏切换(类似抖音切换效果),在滑动一小部分松手，回到原视频后，会重新播放这个视频，我不想重新播放，滑动松手的时候每次都执行到了下面的执行代码里，我判断isInPlayingState状态为true就return掉，但是页面会卡停止在那里，像暂停，但又不是暂停状态。

问题机型/系统：
真机 华为Mate10Pro Android9.0

问题?执行代码：
```
val itemView = rv_list.getChildAt(0)
        itemView.video_view.isLooping = true
        itemView.video_view.startPlayLogic()
```
问题log
卡住时getCurrentState()=2

```

**Comment by CarGuo** [comment]
不是很理解，使用recyclerView实现的类上下滑动viewPager是吧？
在滑动一小段位置后，松开回到原来的视频位置，这时候触发了重新播放？
这个应该是你自己处理导致的吧？
本身视频播放没做这个逻辑啊

**Comment by lzy6** [comment]
你好，可能是GSY逻辑不同，我是用自定义layoutmanager实现recyclerview上下滑动，如果用原声videoView或其他第三方视频播放，没发现这个问题。喜欢用GSY，好多注释等。请问我可以加群么交流么？qq:1299951716

**Comment by CarGuo** [comment]
如果你是想交流技术的，em~~可以不用进群的，群里大部分时候才是在斗图和讨论跳槽的。

你是想实现滑过之后，在回来原来的视频继续刚刚的播放是吧？？

如果是这种需求， setSeekOnStart可以帮助你，如果不满意还有下面的

这个，不过这个目前是全局的，也就是每个视频你都需要在播放前设置一次

```
VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", startPosition);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

```

**Comment by lzy6** [comment]
谢谢，我试试
