### ISSUE TITLE
开始加载前几秒后自动暂停

### ISSUE THREAD

**Issue by 50kg** [CarGuo/GSYVideoPlayer#1629]
因为demo中初始化播放器时url同时设置(所以没问题)，但是由于业务逻辑需要，暂时无url，所以在初始化的时候未设置URL只设置了其他参数，在点击播放按钮的时候，才去网络请求拿到URL后在设置
gsyVideoOptionBuilder.setUrl("xxx");
gsyVideoOptionBuilder.build(detailPlayer);

之后手动调用gsyVideoPlayer.clickStartIcon();或gsyVideoPlayer.getStartButton().performClick();可以播放，但是播放前3秒后会自动暂停（回到封面状态），需要再次点击后才播放

如果demo中改成上述逻辑，可复现
另外如果未设置URL，则封面图不显示
以上 致敬

**Comment by CarGuo** [comment]
成功获取设置之后，不是应该是调用startPlayLogic吗？

**Comment by 50kg** [comment]
谢谢谢谢 二次暂停解决了。另外如果不设置url封面不生效 建议优化一下。谢谢 我自己自定义解决了
