### ISSUE TITLE
完美 不过 视频出现问题的时候 控制ui无法显示点击一下马上又消失了，那么问题来了 华为手机只有虚拟按键

### ISSUE THREAD

**Issue by qssq** [CarGuo/GSYVideoPlayer#163]
所以会导致无法返回了很尴尬 ，我是根据playactivity全面界面模仿写的。。

**Comment by qssq** [comment]
另外请问监听 布局ui显示隐藏的方法是哪个，因为我发现如果一直改写 playactivity中控件的ui发现并不是最好的坚决方法有时候一个项目多种多样的，如果可以监听，我可以在视频层上面覆盖一些东西。而不需要集成那个playview然后做一些事情，不然显得有点乱了

**Comment by CarGuo** [comment]
你可以参考detailPlayer，在全屏的时候有做滑动弹出虚拟按键的支持。然后你可以外部监听onError接口接收到错误。你可以看看wiki，最基础的是GSYBase，然后是GSYVideoPlayer，然后是StandardGSYVideoPlayer。StandardGSYVideoPlayer那里就有你想要支持的那些

**Comment by qssq** [comment]
得熟悉源码了。。又是一个痛苦的学习过程。。

**Comment by qssq** [comment]
滑动隐藏 貌似手机本来支持

**Comment by qssq** [comment]
最后一个问题， 我看了下，现在没提供这个方法对吧？只能改源码？ 就是监听显示隐藏的。

**Comment by CarGuo** [comment]
加了显示和隐藏的支持，但是没有这个监听

**Comment by qssq** [comment]
嗯，可以告诉我在哪个界面嘛，好急哦，boss让我们一个星期完成，其他地方我都有把握，可是播放器还没接触，改造成适合设计ui的得多琢磨了。

**Comment by qssq** [comment]
大概看了下，很多个 显示隐藏方法，我又选择困难症了，这么多，难道要给每一个方法设置监听吗

**Comment by qssq** [comment]
是用什么控制显示隐藏的呢 我还没找到具体代码

**Comment by qssq** [comment]
调试半天没找到是哪个方法调用的指定时间隐藏ui,只找到了显示的， 因为有日志，隐藏ui的没有日志。

**Comment by qssq** [comment]
找到了但愿 只是hideAllWidget 和另外一个show方法，

**Comment by qssq** [comment]
为何返回按钮默认隐藏的呢

**Comment by qssq** [comment]
请问底部的进度颜色怎么改，

**Comment by qssq** [comment]
点击也触发了隐藏。。

**Comment by qssq** [comment]
完美大神

**Comment by qssq** [comment]
奇怪了，为何音频无法获取焦点啊？？？我怎么弄都不行了，我以前的app都可以的，这个视频怎么都没法获取焦点，导致音乐在播放的时候视频也播放，又没法控制不播放，

**Comment by CarGuo** [comment]
GSYVideoPlayer 内部也有 AudioManager
```
AudioManager.OnAudioFocusChangeListener onAudioFocusChangeListener
```
