### ISSUE TITLE
视频被拉撑

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#1632]
http://images-cdn.adun.ccsobey.com//1a7678fe-db0b-4730-9064-c417b4eb8f24.mp4   
这个视频是横向视频，但是在竖直全屏的时候，垂直方向被拉满了

**Comment by CarGuo** [comment]
请提供使用代码

**Comment by i2863CookieZJ** [comment]
使用的是emptycontrolvideo

**Comment by CarGuo** [comment]
从数据返回看，这是一个竖屏视频

Video: h264, 1 reference frame (avc1 / 0x31637661), yuvj420p(pc, left), 352x640 [SAR 320:99 DAR 16:9], 0/1, 2514 kb/s  

width 352 height 640  Reinit context to 352x640, pix_fmt: yuvj420p
