### ISSUE TITLE
安卓华为P9播放RTSP 摄像头实时流缓冲时间太长

### ISSUE THREAD

**Issue by forever123** [CarGuo/GSYVideoPlayer#1633]
## 问题描述：

安卓播放RTSP发生了缓冲时间过长的问题！

## 问题机型/系统：

例如 真机 HUAWEI P9

## Demo中的复现步骤

Demo中的Player页面打开后加载RTSP涉嫌头实时流会缓冲近10秒，每次打开都会进行大约10秒左右的缓冲

**Comment by CarGuo** [comment]
例如  https://github.com/CarGuo/GSYVideoPlayer/issues/859
