### ISSUE TITLE
如何实现列表详情的无缝切换？

### ISSUE THREAD

**Issue by songsh** [CarGuo/GSYVideoPlayer#1634]
## 问题描述：

不知如何实现，请说明，最好有代码，

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/switchplay
