### ISSUE TITLE
列表详情切换

### ISSUE THREAD

**Issue by songsh** [CarGuo/GSYVideoPlayer#1635]
## 问题描述：

这个demo 在魅族4, Android 5.1 上播放时，切换到详情页，播放画面卡住，只有进度条走

## 问题机型/系统：

例如 真机 魅族4, Android 5.1 

## Demo中的复现步骤

Demo中的switchplay 会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
我这边没复现，具体推测可能是因为Material design的共享元素效果印象，可以从这里入手

**Comment by CarGuo** [comment]
只有进度条走说明内核还是在播放，页面黑了应该是surface的问题。很大可能就是 starttActivity 的共享元素动画导致的。

可以断点调试下动画结束，还有PlayerManager的surface传递之类的。

最简单是 demo 的共享元素效果两边都去掉 试试
