### ISSUE TITLE
在RN封装的原生组件中导致第一加载黑屏

### ISSUE THREAD

**Issue by WuZhenXing** [CarGuo/GSYVideoPlayer#1637]
public class TextViewManager extends SimpleViewManager<LinearLayout> {

}

ReactNative
视频第一次加载黑屏，需要旋转一次手机后才能加载出来。

可能是RN的生命周期导致的，因为后面加入的 textView 都需要旋转屏幕才能正常显示。

希望在修复在组件渲染提前加载组件。 

旋转屏幕后会重新出发生命周期触发重新绘制

**Comment by CarGuo** [comment]
RN封装的组件这个问题，因为目前没有对Rn兼容的计划，所以只能你自己调试了。
黑屏这个很大程度在于 surface 没有创建，这个应该和Rn的布局node有关。
至于全屏显示的时候，完全是脱离了rn的框架。如果是rn下使用旋转，记得给MainActivity配置上AndroidManifest配置config
