### ISSUE TITLE
GSYTextureView not support onRenderResume now

### ISSUE THREAD

**Issue by caopeng000** [CarGuo/GSYVideoPlayer#1639]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

ViewPager左右切换的时候，我调用了GSYVideoManager.releaseAllVideos();然后再次切换回来继续播放的时候，播放了两秒钟就提示了GSYTextureView not support onRenderResume now。请问这是什么问题导致的，我该怎么处理。谢谢

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
GSYVideoManager.releaseAllVideos(); 直接释放了所有的，怎么继续播放？

**Comment by caopeng000** [comment]
那我尝试下调用pasue播放器试试
