### ISSUE TITLE
支持h264吗

### ISSUE THREAD

**Issue by Icando26** [CarGuo/GSYVideoPlayer#164]
从摄像头获取的是h264数据流，可以播放吗 怎么播呢

**Comment by CarGuo** [comment]
支持，但是目前so支持的是acc的音频编码，但是你的数据流要组成数据流，比如mp4之类

**Comment by Icando26** [comment]
现在我是获取的h264数据数组，怎么组成你说的数据流 然后播放呢

**Comment by CarGuo** [comment]
h264数据数组估计你要使用concat协议
