### ISSUE TITLE
Https支持

### ISSUE THREAD

**Issue by millerzhu** [CarGuo/GSYVideoPlayer#1640]
首先非常感谢作者开源。目前项目要求视频也要做Https双向校验，但是找不到自定义请求设置SSL的方法，麻烦帮忙解答下，谢谢~

**Comment by CarGuo** [comment]
好吧，你这个问题有点难到我了，毕竟一般视频播放校验更多的通过header设置验证或者crypto加密。
只能说现在提供你三种思路：
1、参考 ProxyCacheManager、HttpProxyCacheServerClients、HttpUrlSource，在代理层面 HttpURLConnection openConnection的时候你就可以设置你的https证书校验。（当然，这不支持m3u8等）

2、参考 `RawDataSourceProvider`，实现一个 IMediaDataSource，然后自己的http框架去拉流，理论上可行，如已有的proxy源码 `HttpUrlSource`。

3、使用exoplayer模式`PlayerFactory.setPlayManager(Exo2PlayerManager.class);`，参考ExoSourceManager -> getHttpDataSourceFactory  ，自定义DefaultHttpDataSourceFactory 和 DefaultHttpDataSource 。
当然，你可以试试全局的 `HttpsURLConnection` ，因为ExoPlayer内部用的是HttpURLConnection

**Comment by millerzhu** [comment]
您的建议很有帮助，再次感谢~

**Comment by xyZangGit** [comment]
> 首先非常感谢作者开源。目前项目要求视频也要做的Https双向校验，但是找不到自定义请求设置SSL的方法，麻烦帮忙解答下，谢谢〜

请问你的HTTPS证书问题是怎么解决的，看了作者的回答，尝试了一下，还是不行，希望您能看到
