### ISSUE TITLE
设置循环播放setloop(true)，无法循环播放

### ISSUE THREAD

**Issue by dujingxue1997** [CarGuo/GSYVideoPlayer#1641]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

循环播放

## 问题机型/系统：

乐视，三星

## Demo中的复现步骤

recyclerview item 视频 设置循环播放

问题代码：(如果有)
```
holder.videoPlay.setLooping(true);
```

## 问题log（如果有）

```
11-30 22:11:39.235 7763-9904/cn.wdquan.wdquan E/IJKMEDIA: http://wdquan-space.b0.upaiyun.com/VIDEO/2018/11/22/ae0645396048_hls_time10.m3u8: error while seeking
11-30 22:11:39.235 7763-9904/cn.wdquan.wdquan D/IJKMEDIA: ffp_toggle_buffering_l: end
11-30 22:11:39.235 7763-9902/cn.wdquan.wdquan D/IJKMEDIA: FFP_MSG_BUFFERING_START:
11-30 22:11:39.235 7763-9902/cn.wdquan.wdquan D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
11-30 22:11:39.235 7763-9902/cn.wdquan.wdquan D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
11-30 22:11:39.235 7763-9902/cn.wdquan.wdquan D/IJKMEDIA: FFP_MSG_BUFFERING_END:

```

**Comment by dujingxue1997** [comment]
补充一下，DEMO使用的是 无UI控制

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXOPlayer内核模式

切换到exoplayer内核可以解决，目前看起来应该是ffplay在帧时序上解析出了兼容问题

**Comment by dujingxue1997** [comment]
还是不行，播放完就停止了。

**Comment by dujingxue1997** [comment]
> PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXOPlayer内核模式
> 
> 切换到exoplayer内核可以解决，目前看起来应该是ffplay在帧时序上解析出了兼容问题
还是不行，播放完就停止了。

**Comment by CarGuo** [comment]
我这边切换到 PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXOPlayer内核模式 之后，设置setloop(true) 正常循环

**Comment by dujingxue1997** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class); 这一句写在application还是BASEActivity中？
我这里就播放一遍，然后就停止了
