### ISSUE TITLE
一个进度预览视频窗口思路

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1642]
研究了一下previewVideo之后,看到了它的布局就是在布局中加了一个ImageView来显示图片，通过监听是否滑动来显示图片，现在我想做一个进度预览视频窗口，把您布局中的imageView 换成了MultiSampleVideo希望能够做成一个点击seekbar 然后弹出一个小窗口,小窗口里面也弹出视频来播放，到时会有服务器推相应时间的流来播放。但是发现一点进去就闪退，是哪里的设置有问题吗，这个思路可行吗？

**Comment by CarGuo** [comment]
以前试过了，这种类型的，以前旧版中有，但是效果也比不是很好

**Comment by xi5528336** [comment]
@CarGuo   旧版本哪个版本有  有demo能参考下吗
