### ISSUE TITLE
视频全屏时候，有时候出现，物理返回键，取消全屏不能返回小屏状态

### ISSUE THREAD

**Issue by caopeng000** [CarGuo/GSYVideoPlayer#1644]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

频繁点击全屏和小屏功能区，当视频处于全屏的时候，再次点击返回按钮失效了。也不能切换到小屏幕了。帮忙解惑一下吧。谢谢。我debug断点了。

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
demo中怎么复现
