### ISSUE TITLE
播发异常

### ISSUE THREAD

**Issue by mengxiangqipa** [CarGuo/GSYVideoPlayer#1645]
demo及集成中不能播放以下地址
http://dmp-media.eos-beijing-1.cmecloud.cn/201811/15/0F04C0981D8D4DFFA053CB8966A2985F.3gp
华为，小米，锤子等各机型均不能播放，该视频本身首帧蓝屏，但是该链接在浏览器可以播放，用android普通videoview 能播放

**Comment by CarGuo** [comment]
默认的ijk内核并没有打包 3gp 的解码
可以尝试切换内核使用
````
        //PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
        //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
````

**Comment by mengxiangqipa** [comment]
非常感谢，我尝试一下！发自我的华为手机-------- 原始邮件 --------主题：Re: [CarGuo/GSYVideoPlayer] 播发异常 (#1645)发件人：Shuyu Guo 收件人：CarGuo/GSYVideoPlayer 抄送：YobertJomi ,Author 默认的ijk内核并没有打包 3gp 的解码

可以尝试切换内核使用

        //PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式

        //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式





—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CarGuo/GSYVideoPlayer","title":"CarGuo/GSYVideoPlayer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/CarGuo/GSYVideoPlayer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@CarGuo in #1645: 默认的ijk内核并没有打包 3gp 的解码\r\n可以尝试切换内核使用\r\n````\r\n        //PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式\r\n        //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式\r\n````\r\n"}],"action":{"name":"View Issue","url":"https://github.com/CarGuo/GSYVideoPlayer/issues/1645#issuecomment-443571004"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/CarGuo/GSYVideoPlayer/issues/1645#issuecomment-443571004",

"url": "https://github.com/CarGuo/GSYVideoPlayer/issues/1645#issuecomment-443571004",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

},

{

"@type": "MessageCard",

"@context": "http://schema.org/extensions",

"hideOriginalBody": "false",

"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",

"title": "Re: [CarGuo/GSYVideoPlayer] 播发异常 (#1645)",

"sections": [

{

"text": "",

"activityTitle": "**Shuyu Guo**",

"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",

"activitySubtitle": "@CarGuo",

"facts": [



]

}

],

"potentialAction": [

{

"name": "Add a comment",

"@type": "ActionCard",

"inputs": [

{

"isMultiLine": true,

"@type": "TextInput",

"id": "IssueComment",

"isRequired": false

}

],

"actions": [

{

"name": "Comment",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"CarGuo/GSYVideoPlayer\",\n\"issueId\": 1645,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"

}

]

},

{

"name": "Close issue",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"CarGuo/GSYVideoPlayer\",\n\"issueId\": 1645\n}"

},

{

"targets": [

{

"os": "default",

"uri": "https://github.com/CarGuo/GSYVideoPlayer/issues/1645#issuecomment-443571004"

}

],

"@type": "OpenUri",

"name": "View on GitHub"

},

{

"name": "Unsubscribe",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 418846096\n}"

}

],

"themeColor": "26292E"

}

]

**Comment by mengxiangqipa** [comment]
> 默认的ijk内核并没有打包 3gp 的解码
> 可以尝试切换内核使用
> 
> ```
>         //PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
>         //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
> ```

切换模式后能播放了
