### ISSUE TITLE
能否基于GSYVideoPlayer开发一个weex的视频插件?

### ISSUE THREAD

**Issue by mythbobo** [CarGuo/GSYVideoPlayer#1646]
播放器功能很强大。而且我看到你也有开发weex相关的东西。不知道能否给weex增加一个全能的视频播放插件？期待你的回复。感谢!

**Comment by CarGuo** [comment]
目前并没有这个打算，毕竟最大的缺陷是该项目没有ios端，做成插件也只是单端，所以没有封装为weex和rn的打算
