### ISSUE TITLE
封装ReactNative时，视频显示黑屏但是有声音

### ISSUE THREAD

**Issue by zhanfangzxc** [CarGuo/GSYVideoPlayer#1647]
## 问题描述：

封装ReactNative时，视频显示黑屏但是有声音

**Comment by CarGuo** [comment]
目前该项目暂未尝试对rn做支持。
一般黑屏有声音，基本都是surface的问题，首先确定surface层是否正确创建，然后是否正确传到playmanager中。
如果都正常的话，再看看你视频控件大小是否不对了。
最后再确定是否因为没配置硬件加速的愿意么导致

**Comment by yubaokang** [comment]
RN 不支持 动态 addView  百度这个问题就好了
