### ISSUE TITLE
播放器后台播放问题

### ISSUE THREAD

**Issue by qhs107** [CarGuo/GSYVideoPlayer#1648]
我继承的是StandardGSYVideoPlayer    退出页面    设置播放器后台播放    从新进入页面   从新New一个播放器    请问这时候会走什么监听   播放器会销毁   然后从新实例一个吗

**Comment by CarGuo** [comment]
如果我理解没错的话，你是在A页面实现了一个播放器，然后播放着，跳到B页面有开了一个播放器，默认旧的播放器会被销毁。
