### ISSUE TITLE
关于视频不是从一开始播放，而是自己记录播放的位置，下次从当前位置播放

### ISSUE THREAD

**Issue by clark0704** [CarGuo/GSYVideoPlayer#165]
关于视频不是从一开始播放，而是自己记录播放的位置，下次从当前位置播放？怎么实现？

**Comment by CarGuo** [comment]
有setSeekOnStart接口在播放前偏移，有getCurrentPositionWhenPlaying获取当前播放接口。记得setSeekOnStart 要在 startPlayLogic();之前

**Comment by clark0704** [comment]
谢谢，真是好人。

**Comment by xiangou** [comment]
不是很精确 会有 3秒左右的误差 有解决方法吗

**Comment by xiangou** [comment]
感谢你的付出  
问题解决了
