### ISSUE TITLE
能否在播放界面增加【播放下一个】的按钮？点击自动播放列表中的下一个文件

### ISSUE THREAD

**Issue by bbssyyuui** [CarGuo/GSYVideoPlayer#1650]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

能否在播放界面增加【播放下一个】的按钮？点击自动播放列表中的下一个文件，这样就不用每次切到下一个都得返回到列表手动选一个播放了。

**Comment by Wangct23** [comment]
这种功能应该可以自己实现吧

**Comment by CarGuo** [comment]
继承后重写getLayoutId
