### ISSUE TITLE
您好，我看demo里面列表都是用的SampleCoverVideo，我依赖后，包中没有这个类，只有使用StandardGSYVideoPlayer，出现全屏按音量键自动切换回小屏，单独使用是没这个问题的

### ISSUE THREAD

**Issue by liuzhengnan666** [CarGuo/GSYVideoPlayer#1651]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
问题1：SampleCoverVideo是在demo里的
问题2：没明白

**Comment by liuzhengnan666** [comment]
问题1：implementation 'com.shuyu:GSYVideoPlayer:6.0.1' 如何使用SampleCoverVideo？
问题2：就是在RecycleView中使用StandardGSYVideoPlayer，点击全屏后，在全屏状态按音量键，就自动恢复到原来的样子

**Comment by CarGuo** [comment]
问题1肯定是从demo中拷过去啊
问题2如何在dmeo复现
