### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 26122 (eg.h264.decoder)

### ISSUE THREAD

**Issue by zhaoaoranke** [CarGuo/GSYVideoPlayer#1652]
在夜神模拟器循环播放视频（每次播放完成重置播放器），播放一段时间出现A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 26122 (eg.h264.decoder) 引起崩溃，请问一下可能是什么原因引起的？或者我该怎么排查这个问题呢？

模拟器系统 4.4

**Comment by zhaoaoranke** [comment]
我开启了硬解码 GSYVideoType.enableMediaCodec();    内核使用的是Exo2PlayerManager

**Comment by zhaoaoranke** [comment]
下面是网上一些朋友遇到的问题：
BUG导致：应用程序崩溃，过一小会儿会自动退出。

Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)



遇到这个问题很无奈，但是经过不断探索终于找到了问题的原因！！！

这个问题非常不给面子，居然在给上级演示程序的时候突然崩坏！ 哭哭哭！！！NND看老子一会儿怎么治你！！！


这个是典型的多线程引起的问题，

我当时的应用场景是：

SurfaceView里面有一个Bitmap成员变量

而我们都知道SurfaceView里面的绘图方法是在一个新开的线程里面执行的，在这个绘图方法里，会执行把Bitmap绘制到Canvas上面的操作

当我点击一个按钮的时候，可能会改变Bitmap的引用，指向另外一张处理完成的图片，这个时候Bitmap这个成员变量会被我recycle()，释放掉。

问题就在这里了，我在recycle这个Bitmap的时候，也许Thread中正在执行把Bitmap绘制到Canvas上的操作，可能刚好正在执行当中，或者执行了一半，而GC毫不留情地把这个Bitmap请上了天堂，就这样，Java调用底层的API当中就突然发生了Error，因此这个问题才没有任何的Java异常提示。

**Comment by CarGuo** [comment]
内核使用的是Exo2PlayerManager下 GSYVideoType.enableMediaCodec(); 是无效的，因为 EXO2就是mediacodec

至于 : Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 26122 (eg.h264.decoder)  这个很难看出问题，这种问题还有可能是其他崩溃导致的
