### ISSUE TITLE
播放速度问题

### ISSUE THREAD

**Issue by TODOFix** [CarGuo/GSYVideoPlayer#1653]
## 问题描述：

使用小米mix2s播放dome 调整速度为1.25,1.5,2.0没有播放速度没有变快
但是0.25,0.5的速度确有变慢
使用模拟器9.0，调整速度1.25,1.5,2.0是都是正常的

## 问题机型/系统：

小米mix2s 9.0系统

## Demo中的复现步骤

使用小米mix2s播放dome 调整速度为1.25,1.5,2.0

问题代码：(如果有)
```
demo 中带控制器的调整速度的代码
```

**Comment by CarGuo** [comment]
我这边没复现问题，或者你可以尝试切换到EXOplayer内核模式试试

PlayerFactory.setPlayManager(Exo2PlayerManager.class);

**Comment by TODOFix** [comment]
添加  PlayerFactory.setPlayManager(Exo2PlayerManager.class); 1.25,1.5,2.0速度的确有加快
