### ISSUE TITLE
长按事件设置无效

### ISSUE THREAD

**Issue by huangruiLearn** [CarGuo/GSYVideoPlayer#1654]
参考了 GSYVideoControlView中   gestureDetector后 新写了个类  

 public class MyPlayer extends StandardGSYVideoPlayer {

    public MyPlayer(@NonNull Context context) {
        super(context);
    }

    public MyPlayer(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }

    public MyPlayer(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

   @Override
    protected void init(Context context) {
         gestureDetector = new GestureDetector(getContext().getApplicationContext(), new GestureDetector.SimpleOnGestureListener() {
           @Override
           public boolean onDoubleTap(MotionEvent e) {

               touchDoubleUp();
               return super.onDoubleTap(e);
           }

           @Override
           public boolean onSingleTapConfirmed(MotionEvent e) {
                if (!mChangePosition && !mChangeVolume && !mBrightness) {
                   onClickUiToggle();
               }
               return super.onSingleTapConfirmed(e);
           }
           ////加上这个
           @Override
           public void onLongPress(MotionEvent e) {
                super.onLongPress(e);
           }

       });
        super.init(context);

}
}
onLongPress没有生效

**Comment by CarGuo** [comment]
gestureDetector  是在onTouch中调用的，你应该先调试打印下 onTouch 下的情况

**Comment by CarGuo** [comment]
抱歉，忽略了因为` new GestureDetector(getContext().getApplicationContext()` 的初始化会需要getContext导致时序在init之后了

在init方法内修改为这样

```
        post(new Runnable() {
            @Override
            public void run() {
                gestureDetector = new GestureDetector(getContext().getApplicationContext(), new GestureDetector.SimpleOnGestureListener() {
                    @Override
                    public boolean onDoubleTap(MotionEvent e) {
                        touchDoubleUp();
                        return super.onDoubleTap(e);
                    }

                    @Override
                    public boolean onSingleTapConfirmed(MotionEvent e) {
                        if (!mChangePosition && !mChangeVolume && !mBrightness) {
                            onClickUiToggle();
                        }
                        Debuger.printfError("555a","9999999999999999999999");
                        return super.onSingleTapConfirmed(e);
                    }

                    @Override
                    public void onLongPress(MotionEvent e) {
                        super.onLongPress(e);
                        Debuger.printfError("555a","0000000000000000000000");
                    }
                });
            }
        });
```
