### ISSUE TITLE
能否支持带广告的详情列表模式，可以切换下一集的

### ISSUE THREAD

**Issue by fengjian123** [CarGuo/GSYVideoPlayer#1656]
能否支持带广告的详情列表模式，可以切换下一集的，后者用什么思路去写

**Comment by CarGuo** [comment]
项目是支持的，不过需要你自己处理。最简单的如 GSYSampleADVideoPlayer

一个列表，切换时自己可以处理下一集是播放list+1的广告还是lis+2的视频之类

**Comment by fengjian123** [comment]
嗯，我自定义继承GSYBaseADActivityDetail这个类了，然后传入要加载的视频和广告集合，播放完一个视频后，动态改变资源
