### ISSUE TITLE
目前需要自己做对应逻辑，因为实际上真实播放器只有一个，播放UI通过播放共享播放器，如果要另外一个处于暂停，你需要继承播放器，在被释放的回调里拦截下来释放，然后记录播放位置，判断是否播放过，然后设置对应的UI，在再次点击播放的时候，通过setSeekOnStart，然后再次续播等等，一些细节会比较多。

### ISSUE THREAD

**Issue by xyZangGit** [CarGuo/GSYVideoPlayer#1657]
_Originally posted by @CarGuo in https://github.com/CarGuo/GSYVideoPlayer/issues/585#issuecomment-343841774_
大佬，这个问题是否可以在demo里面写一个，我目前也遇到这样的问题了，视频播放的frgament是在viewpage里面是复用的，当前frgament播放，然后滑到另外一个frgament里面，视频暂停一下又继续播放了，按照您的建议逻辑，我搞了好几天没搞定，希望大大看到指导一下

**Comment by CarGuo** [comment]
不是很理解。

**Comment by xyZangGit** [comment]
我晚上给您截图说明吧，希望大大留意一下
