### ISSUE TITLE
动态添加video移除和多个视频播放问题

### ISSUE THREAD

**Issue by yanlianhanlin** [CarGuo/GSYVideoPlayer#1658]
我是参考MultiSampleVideo做的一个功能，在一个LinearLayout中添加多个videoplayer同时播放，当videoplayer不再需要时调用LinearLayout.removeAllViews移除所有videoplayer时，每一个videoplayer会走生命周期释放吗？还是需要调用其他的什么方法？

当多个视频同时播放有时会随机一个video播放卡住，这种情况下是因为什么？

**Comment by CarGuo** [comment]
移除的时候你需要调用Manager去release所有内核。

至于随机卡住，这个要看是surface问题、网络问题、还是内存问题了。

**Comment by yanlianhanlin** [comment]
我用的是demo里面的CustomManager类，是调用CustomManager.releaseAllVideos(String key)获取对应的key移除，还是直接调用  CustomManager.clearAllVideo()直接全部移出？
随机卡住一般在第一遍播放缓存到本地之后，第二遍播放内容的时候出现。
播放的时候下面会弹出Background sticky concurrent mark sweep GC freed 21137(1089KB) AllocSpace objects, 0(0B) LOS objects, 37% free, 3MB/5MB, paused 13.118ms total 32.168ms这个提示 播放卡顿是因为这个原因吗？

**Comment by CarGuo** [comment]
多个播放内核毕竟会出现大内存的消耗，你这个只是cg在是否内存，不过也是内存消耗过大的一个表现。
如实全部移除，是 CustomManager.clearAllVideo()

**Comment by punchxu** [comment]
多视频同时播放可以实现四个画面的同时播放吗？四个画面的分配可以自己进行调节吗？

**Comment by yanlianhanlin** [comment]
@CarGuo  我在监听日志时候会打印出这些信息，这些是错误吗？
’E/AudioFlinger: PlaybackThread::Track::getNextBuffer:There is not enough data from AudioTrack!!! ’
‘E/IJKMEDIA: Option ijkapplication not found.’
‘ E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xabd09c80)’

**Comment by CarGuo** [comment]
@punchxu 可以同时播放吗，但是内存分配没办法自己调节

**Comment by punchxu** [comment]
> @punchxu 可以同时播放吗，但是内存分配没办法自己调节

是指只能在列表上同时播放，而没办法实现四分屏或者九分屏的同时播放，是吗？

**Comment by CarGuo** [comment]
如果你要实现一个屏幕播放多个源，那么你需要自己自定义去OpenGL绘制 @punchxu

**Comment by YeGuli** [comment]
你好，我想问一下，如果要实现页面中多个player分别播不同的源应该怎么做？我现在用的是GSYADVideoPlayer，多个play同时播放的话只有最后一个能播出来

**Comment by CarGuo** [comment]
@YeGuli demo中的MultiSampleVideo
