### ISSUE TITLE
关于同时播放音频和视频的问题

### ISSUE THREAD

**Issue by fengjian123** [CarGuo/GSYVideoPlayer#1661]
我在项目中分别集成了音频和视频播放器，两者都是继承StandardGSYVideoPlayer播放器，不过我发现，只要播放了音频，再去播放视频，回来音频那里就不能正常播放了，而且进度也乱了，是我没处理好的原因还是底层不支持同时播放音频和视频？你的最底层是不是只实例化了一个播放器

**Comment by CarGuo** [comment]
是的，默认底层只有一个ffplay或者mediacodec，如果需要多个可以参考 demo 的 `MultiSampleVideo`

**Comment by fengjian123** [comment]
嗯，我重写了下getGSYVideoManager，用了你demo中的CustomManager之后就可以了。
