### ISSUE TITLE
依赖冲突

### ISSUE THREAD

**Issue by DingSong** [CarGuo/GSYVideoPlayer#1662]
因为有其他的第三方包用到了ijk，并且修改了ijk中部分内容，但是包名类名没有不变。
导致我现在使用gsy会冲突，这个有没有什么成本低的解决方案呢？

**Comment by CarGuo** [comment]
需要看下第三方的ijk版本是那个版本，如果和gsy的对的上，那你可以在依赖gsy的时候用exculde移除ijk
