### ISSUE TITLE
如何选择视频或者音频文件进行缓存到本地

### ISSUE THREAD

**Issue by fengjian123** [CarGuo/GSYVideoPlayer#1664]
现在我们的需求是这样的，加载视频和音频时可以边播边缓存，但是不会保存在本地，断网之后是不能重新播放的，但是可以在列表或者当前页面中主动去下载（其实是缓存）到本地，这样下次就能直接播放，不需要请求网络。这样的话是该如何实现？好像如果设置cacheWithPlay为true的话，播放的时候就已经缓存在本地了。

**Comment by CarGuo** [comment]
你这是两套逻辑了，一套是下载，一套是播放分开的。
等于你下载的时候直接用http去拉流就好了啊。
下载完了才支持播放

**Comment by fengjian123** [comment]
@CarGuo 我的意思是下载也下到缓存里，不能通过其他软件搜索到，只能自己的App播放使用，就和打开cache的时候一样，有没有直接的方法，还是需要自己去实现一套主动缓存的方案？

**Comment by CarGuo** [comment]
可以啊，你下载到app沙盒内，别的应用就搜索不到了，默认项目的也是下载到应用的沙盒内

比如 `"/data/data/" + context.getPackageName() + "/cache/";`
