### ISSUE TITLE
播放到倒数1秒的时候卡住了

### ISSUE THREAD

**Issue by lzy6** [CarGuo/GSYVideoPlayer#1665]
问题描述：

播放到倒数1秒的时候卡住了，（10秒视频播放到9秒的时候卡住）在setListener没监听到错误信息，我设置了isLooping，没用，还是卡。只有某些视频会，大部分视频是没问题的并且可以循环播放。

问题机型/系统：

华为mate10Pro(所有机型都会出现)

GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

**Comment by CarGuo** [comment]
试试 `PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式`
有可能视频的帧时许和ijkplayer的ffplay兼容有问题

**Comment by lzy6** [comment]
懂了，谢谢
