### ISSUE TITLE
播放http 和 rtmp直播流延迟问题

### ISSUE THREAD

**Issue by 136093330** [CarGuo/GSYVideoPlayer#1668]
## 问题描述：

点击暂停后，在播放，有延迟，应该怎么处理呢？

## 问题机型/系统：

华为v8

## GSY依赖版本

依赖所有平台

## Demo中的复现步骤

播这两个流：http://ksdlive.gwpd.iqilu.com/ggpd.m3u8    rtmp://live.hkstv.hk.lxdns.com/live/hks1 其中的一个， 点击暂停，停一会 ，在点击播放， 就有延迟了，可以拿两台手机对比，第一次播放不会有延迟

**Comment by CarGuo** [comment]
试试
```
        List<VideoOptionModel> list = new ArrayList<>();
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,  "http-detect-range-support", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 8);
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by 136093330** [comment]
> 
> 
> 试试
> 
> ```
>         List<VideoOptionModel> list = new ArrayList<>();
>         VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,  "http-detect-range-support", 0);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 8);
>         list.add(videoOptionModel);
>         GSYVideoManager.instance().setOptionModelList(list);
> ```

还是一样会有延迟，比如网络不好的时候，播着播着卡住了，然后网络好了在继续播，这个时候就延迟了。 这个是测试的流地址rtmp://live.hkstv.hk.lxdns.com/live/hks1，延迟挺严重的。

**Comment by CarGuo** [comment]
IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);  可以加快解析。另外目前这个延迟没什么办法
