### ISSUE TITLE
全屏时，点击多视频源选项时 ，NavigationBar /底部导航栏会被自动激活为可见状态，是否可以一直未隐藏状态

### ISSUE THREAD

**Issue by colaly** [CarGuo/GSYVideoPlayer#1672]
## 问题描述：

全屏时，点击多视频源选项时 ，NavigationBar /底部导航栏会被自动激活为可见状态，这样会挡住多视频源的选择，当点击顶部其他选项时，不会出现此问题，详情如下图
![](https://ww3.sinaimg.cn/large/baf74e11ly1fy4db1wfc9j20lc0c0dg9.jpg)
![](https://ww4.sinaimg.cn/large/baf74e11ly1fy4dfw5decj20k00b9wvw.jpg)
## 问题机型/系统：

例如 真机 华为Nova  Android8.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Demo中的【打开VIDEO】页面打开后可以选择分辨率，但是它为竖屏，却默认显示状态栏和底部导航栏，因此无法测试。

**Comment by CarGuo** [comment]
弹出的是dialog吧？？dialog所在的window不是全屏的吧

**Comment by colaly** [comment]
> 弹出的是dialog吧？？dialog所在的window不是全屏的吧

感谢大佬的提示

**Comment by SuperZhouyong** [comment]
> > 弹出的是dialog吧？？dialog所在的window不是全屏的吧
> 
> 感谢大佬的提示

这个怎么改的哦，我代码设置全屏了，没有生效
