### ISSUE TITLE
not support qulity m3u8 in playes 

### ISSUE THREAD

**Issue by isarjanfaza** [CarGuo/GSYVideoPlayer#1673]
how Select Custom Qulity in player ??

**Comment by isarjanfaza** [comment]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1625000,RESOLUTION=1920x1080,CLOSED-CAPTIONS=NONE
chunklist_b1625000.m3u8?nimblesessionid=316504658
#EXT-X-STREAM-INF:BANDWIDTH=925000,RESOLUTION=854x480,CLOSED-CAPTIONS=NONE
chunklist_b925000.m3u8?nimblesessionid=316504658
#EXT-X-STREAM-INF:BANDWIDTH=600000,RESOLUTION=640x360,CLOSED-CAPTIONS=NONE
chunklist_b600000.m3u8?nimblesessionid=316504658
#EXT-X-STREAM-INF:BANDWIDTH=350000,RESOLUTION=426x240,CLOSED-CAPTIONS=NONE
chunklist_b350000.m3u8?nimblesessionid=316504658

**Comment by CarGuo** [comment]
default ijkplayer mode not support BANDWIDTH
exoplayer mode `PlayerFactory.setPlayManager(Exo2PlayerManager.class);` may support，but you may need Refer to this custom：

https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exo


and find how to select BANDWIDTH in https://github.com/google/ExoPlayer

**Comment by isarjanfaza** [comment]
how show in GSYVideoPlayer custom layout ?
and user select ??
thanks

**Comment by CarGuo** [comment]
@override 
getLayoutId()
