### ISSUE TITLE
RecycleView播放视频列表，调用videoAdapter.notifyDataSetChanged()，正在播放视频暂停

### ISSUE THREAD

**Issue by hiyounglee** [CarGuo/GSYVideoPlayer#1676]
## 问题描述：

通过RecycleView播放视频列表，视频列表滑动自动播放，当调用videoAdapter.notifyDataSetChanged()方法时（如刷新列表，加载更多等），视频暂停，如何更新列表数据时，不暂停正在播放的视频

## 问题机型/系统：

真机 华为Android8.0

## GSY依赖版本

com.shuyu:gsyVideoPlayer-java:6.0.1

## Demo中的复现步骤

刷新列表，调用notifyDataSetChanged()方法时

**Comment by CarGuo** [comment]
如果没做额外判断，这是正常情况。
除非你用notifyItem之类的

**Comment by hiyounglee** [comment]
我在执行了videoAdapter.notifyDataSetChanged()方法后，调用gsyBaseVideoPlayer.startPlayLogic();方法播放视频，还是没有效果，依旧是暂停，不能播放，如何操作才能不会暂停呢，你说的notifyItem具体是哪个类里的方法呢，谢谢

**Comment by CarGuo** [comment]
你可以没理解我的意识，首先你调用了 notifyDataSetChanged 是刷新整个recycler的，这时候每个item都会被刷新，刷新的时候可能就触发了 setup 之类的方法导致视频重置了。

所以你需要在holder内判断如果视频正常播放，那么不重新初始化

或者更新状态的时候通过recyclerView的notifyItem或者notifyRange去局部更新

**Comment by hiyounglee** [comment]
现在明白你什么意思了，知道怎么去做了，谢谢

**Comment by Gui-Ji** [comment]
这种情况下分页加载怎么去处理自动播放和设置数据问题。

**Comment by Gui-Ji** [comment]
> 现在明白你什么意思了，知道怎么去做了，谢谢

请问如何去处理下拉刷新和自动播放holder填充数据问题，我现在处理方式是区分局部刷新和全局刷新 局部刷新就不去重新设置数据，全局刷新才去设置数据，请问有什么更好推荐方式去判断
