### ISSUE TITLE
安卓版本5.1.1为啥播放器不跑起来，无法播放

### ISSUE THREAD

**Issue by chigang** [CarGuo/GSYVideoPlayer#1677]
安卓版本5.1.1为啥播放器不跑起来，无法播放

**Comment by CarGuo** [comment]
有什么错误提示？demo有问题？

**Comment by chigang** [comment]
12-18 13:13:07.471 479-20022/system_process E/WindowManagerService: leow rotation = 90
    port
12-18 13:13:07.581 479-496/system_process E/Sensors: MPU is not available
12-18 13:13:07.685 31297-31297/com.example.gsyvideoplayer E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
12-18 13:13:08.065 31297-31457/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
12-18 13:13:08.106 31297-531/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
12-18 13:13:08.114 31297-531/com.example.gsyvideoplayer E/ProxyCache error: Error opening connection for http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4 with offset 82844. Version: 6.0.1
12-18 13:13:08.119 31297-31903/com.example.gsyvideoplayer E/HttpProxyCacheServer error: Error processing request. Version: 6.0.1
12-18 13:13:08.405 31297-530/com.example.gsyvideoplayer E/IJKMEDIA: http://127.0.0.1:49582/http%3A%2F%2F9890.vod.myqcloud.com%2F9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4: End of file
12-18 13:13:08.406 31297-31446/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
12-18 13:13:08.406 31297-31297/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
12-18 13:13:08.407 31297-31297/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Again http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4
    mCache Link http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4
12-18 13:13:08.409 31297-31446/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by chigang** [comment]
能播放了
