### ISSUE TITLE
在小米android9.0上IjkPlayerManager内核设置倍速失效

### ISSUE THREAD

**Issue by MrZWC** [CarGuo/GSYVideoPlayer#1678]
## 问题描述：
GSYVideoPlayer的demo在小米mix3 android9.0上使用IjkPlayerManager内核setspeed失效。目前测试小米android9.0系统设置倍速都不行

**Comment by CarGuo** [comment]
Exo2PlayerManager 可以吗？ PlayerFactory.setPlayManager(Exo2PlayerManager.class);
已确定倍数无效和视频源无关吗？

**Comment by MrZWC** [comment]
> Exo2PlayerManager 可以吗？ PlayerFactory.setPlayManager(Exo2PlayerManager.class);
> 已确定倍数无效和视频源无关吗？

Exo2PlayerManager和SystemPlayerManager能用，只有ijkplayer设置倍速无效。确认和视频源无关。这是我爆的错误
![image](https://user-images.githubusercontent.com/32127097/49982794-9930ee00-ff99-11e8-8fa5-039bccda9ab6.png)
粗略分析似乎是小米9.0系统更改了底层代码导致出现问题
![image](https://user-images.githubusercontent.com/32127097/49982830-d5fce500-ff99-11e8-8f06-879d03641ff8.png)
不知道是否是这样

**Comment by MrZWC** [comment]
> > Exo2PlayerManager 可以吗？ PlayerFactory.setPlayManager(Exo2PlayerManager.class);
> > 已确定倍数无效和视频源无关吗？
> 
> Exo2PlayerManager和SystemPlayerManager能用，只有ijkplayer设置倍速无效。确认和视频源无关。这是我爆的错误
> ![image](https://user-images.githubusercontent.com/32127097/49982794-9930ee00-ff99-11e8-8fa5-039bccda9ab6.png)
> 粗略分析似乎是小米9.0系统更改了底层代码导致出现问题
> ![image](https://user-images.githubusercontent.com/32127097/49982830-d5fce500-ff99-11e8-8f06-879d03641ff8.png)
> 不知道是否是这样

**Comment by CarGuo** [comment]
目前看来是兼容问题

**Comment by rexuehuaqingchun** [comment]
> 目前看来是兼容问题

那个这个问题能给出一个解决方法嘛，楼上的朋友说通过设置ijk的参数可以解决该问题，但是我和另一位仁兄都没有解决！急需一些方向，谢谢大佬无私的开源奉献，十分感谢！

**Comment by CarGuo** [comment]
只能说，高版本api要支持倍数，推荐设置为exoplayer2模式内核
