### ISSUE TITLE
请问，列表播放自动切换的时候偶尔会卡住

### ISSUE THREAD

**Issue by tianhonglilei** [CarGuo/GSYVideoPlayer#1679]
问题描述：
华为的部分机型，几十个上百个视频，列表播放，偶尔会出现切换的时候卡住，显示最后一帧或者黑屏。
没有走结束的监听，有时候黑屏是切换成功了，但是黑屏了，点击一下屏幕，画面又出来了。不太明白什么原理。
视频是m3u8格式，使用的exo2的播放内核。
看了很多issue 黑屏和卡住是没有开启硬件加速。
硬件加速和硬解码这样配置就行么？
GSYVideoType.enableMediaCodec();
GSYVideoType.enableMediaCodecTexture();
android:hardwareAccelerated="true"

问题机型/系统：
华为VIE AL10 / Android 8.0

GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'

Demo中的复现步骤
复制的demo中的listvideoplayer。

**Comment by tianhonglilei** [comment]
问题描述：
华为的部分机型，几十个上百个视频，列表播放，偶尔会出现切换的时候卡住，显示最后一帧或者黑屏。
没有走结束的监听，有时候黑屏是切换成功了，但是黑屏了，点击一下屏幕，画面又出来了。不太明白什么原理。
视频是m3u8格式，使用的exo2的播放内核。
看了很多issue 黑屏和卡住是没有开启硬件加速。
硬件加速和硬解码这样配置就行么？
GSYVideoType.enableMediaCodec();
GSYVideoType.enableMediaCodecTexture();
android:hardwareAccelerated="true"

问题机型/系统：
华为VIE AL10 / Android 8.0

GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'

Demo中的复现步骤
复制的demo中的listvideoplayer。

**Comment by tianhonglilei** [comment]
华为的有一部P20 Android 8.0 经常出现开始播放就黑屏，有时候杀死程序，再打开就好了，有时候重启几次都不行，华为云测相同机型版本也没有出现这种情况，其他厂商机型也没有出现，不好意思啊，大神，这么多问题写了一个issue。麻烦您了

**Comment by CarGuo** [comment]
enableMediaCodec(); 只针对ijk有用，exo2本来就是mediacodec的，所以打开不打开没区别。
你用的是是最新版本吗？
使用的代码是如何？
卡住黑屏分很多种情况

比如偶尔卡住黑屏

- 有可能是网络导致断流了
- 有可能是设置了cache为true，使用的缓存过程出现异常

切换成功正在播放黑屏

- 可能是Surface创建失败
- 可能Surface没正常设置到播放内核。

默认的 TextureView 有时候可能存在一些兼容性，可以尝试下切换到Surface模式
`GSYVideoType.setRenderType(GSYVideoType.SUFRACE);`

如果是用缓存cache为true的话，exo2模式 可以试试看看
`CacheFactory.setCacheManager(ExoPlayerCacheManager.class);`

**Comment by tianhonglilei** [comment]
您好，切换成surface以后还是会黑屏，请教一下您，怎么判断surface或者texture是否创建，如果没有创建，如何进行手动创建？
还有一个问题，列表切换下一集的情况下，会被后台的喜马拉雅直播抢走声音播放焦点，然后有画面，没有声音。实在不好意思，又要劳烦您了~
