### ISSUE TITLE
怎么才能去掉TitleBar?

### ISSUE THREAD

**Issue by QueryGad** [CarGuo/GSYVideoPlayer#168]
onCreate()方法中调用了getSupportActionBar().hide();隐藏了titleBar 全屏返回后 titlebar又显示了出来  。如何全屏后还能一直隐藏titlebar？

**Comment by Jiangwen-Wong** [comment]
可以在退出全屏的回调再次隐藏title。
```
 detailPlayer.setStandardVideoAllCallBack(new SampleListener() {
          
            @Override
            public void onQuitFullscreen(String url, Object... objects) {
                super.onQuitFullscreen(url, objects);
                mPlayer.getTitleTextView().setVisibility(View.VISIBLE);
            }
        });
```

**Comment by QueryGad** [comment]
mPlayer.getTitleTextView().setVisibility(View.VISIBLE); 我把这句话加上了  但是没有任何效果

**Comment by QueryGad** [comment]
player.setStandardVideoAllCallBack(new SampleListener() {
            @Override
            public void onPrepared(String url, Object... objects) {
                super.onPrepared(url, objects);
                //开始播放了才能旋转和全屏
                player.getTitleTextView().setVisibility(View.VISIBLE);
                orientationUtils.setEnable(true);
                isPlay = true;
            }

**Comment by Jiangwen-Wong** [comment]
我上面写错了，应该是`setVisibility(View.INVISIBLE);`

**Comment by CarGuo** [comment]
所以问题解决了么？

**Comment by QueryGad** [comment]
问题没有解决，加invisible还是gone都没有解决掉横屏过后再竖屏titlebar显示出来的问题
player.setStandardVideoAllCallBack(new SampleListener() {
            @Override
            public void onPrepared(String url, Object... objects) {
                super.onPrepared(url, objects);
                //开始播放了才能旋转和全屏
                player.getTitleTextView().setVisibility(View.INVISIBLE);
                orientationUtils.setEnable(true);
                isPlay = true;
            }

**Comment by CarGuo** [comment]
我好像理解了，你是想隐藏actionbar那一块的是吧？
```
/**
     * 利用window层播放全屏效果
     *
     * @param context
     * @param actionBar 是否有actionBar，有的话需要隐藏
     * @param statusBar 是否有状态bar，有的话需要隐藏
     */
    public GSYBaseVideoPlayer startWindowFullscreen(final Context context, final boolean actionBar, final boolean statusBar) 
```
actionBar你设置为false

**Comment by QueryGad** [comment]
漂亮，谢谢作者！这个问题解决了。
