### ISSUE TITLE
show Dialog in when press play

### ISSUE THREAD

**Issue by isarjanfaza** [CarGuo/GSYVideoPlayer#1680]

**Comment by isarjanfaza** [comment]
[https://www.photobox.co.uk/my/photo?album_id=5519409346&photo_id=501472501454](url)
please check and how remove this message box ??

thanks

**Comment by CarGuo** [comment]
function `showWifiDialog` In the case of cellular networks
you can override it

**Comment by isarjanfaza** [comment]
please write here code function  showWifiDialog 
disable Dialog

thanks

**Comment by CarGuo** [comment]
you can call setNeedShowWifiTip(false) disable Quickly
