### ISSUE TITLE
not stream m3u8 with segment??

### ISSUE THREAD

**Issue by isarjanfaza** [CarGuo/GSYVideoPlayer#1683]
my line is :
http://tk3.fastbroad.com/i/WEATHERNATION_1@441739/master.m3u8?hdnts=data=ip=5.122.27.251,id=CJ775053~acl=/i/WEATHERNATION_1@441739/*~exp=1544788776~hmac=fd9253535d708c3d9d161c2f82b91a82a12283939f897061d82d6d9fbdd6d7e0
http://tk3.fastbroad.com/i/WEATHERNATION_1@441739/index_2000_av-p.m3u8?sd=10&rebase=on&hdntl=exp=1544799576~acl=%2fi%2fWEATHERNATION_1%40441739%2f*~data=hdntl,ip%3d5.122.27.251,id%3dCJ775053~hmac=adcc442666c5223b6c7b5085cca4b8ba10d372af43ad35ffbd6a2fedcab9420e
http://tk3.fastbroad.com/i/WEATHERNATION_1@441739/segment154478874_2000_av-p.ts?sd=10&rebase=on&hdntl=exp=1544799576~acl=/i/WEATHERNATION_1@441739/*~data=hdntl,ip=5.122.27.251,id=CJ775053~hmac=adcc442666c5223b6c7b5085cca4b8ba10d372af43ad35ffbd6a2fedcab9420e
http://tk3.fastbroad.com/i/WEATHERNATION_1@441739/segment154478875_2000_av-p.ts?sd=10&rebase=on&hdntl=exp=1544799576~acl=/i/WEATHERNATION_1@441739/*~data=hdntl,ip=5.122.27.251,id=CJ775053~hmac=adcc442666c5223b6c7b5085cca4b8ba10d372af43ad35ffbd6a2fedcab9420e
http://tk3.fastbroad.com/i/WEATHERNATION_1@441739/index_2000_av-p.m3u8?sd=10&rebase=on&hdntl=exp=1544799576~acl=%2fi%2fWEATHERNATION_1%40441739%2f*~data=hdntl,ip%3d5.122.27.251,id%3dCJ775053~hmac=adcc442666c5223b6c7b5085cca4b8ba10d372af43ad35ffbd6a2fedcab9420e
http://tk3.fastbroad.com/i/WEATHERNATION_1@441739/segment154478876_2000_av-p.ts?sd=10&rebase=on&hdntl=exp=1544799576~acl=/i/WEATHERNATION_1@441739/*~data=hdntl,ip=5.122.27.251,id=CJ775053~hmac=adcc442666c5223b6c7b5085cca4b8ba10d372af43ad35ffbd6a2fedcab9420e
when master line not stream but when play in web site  urls is work
please help me?
thanks

**Comment by CarGuo** [comment]
i not sure what you mean

**Comment by isarjanfaza** [comment]
segment154478876_2000_av-p.ts
segment154478877_2000_av-p.ts
segment154478878_2000_av-p.ts


segment ++

**Comment by CarGuo** [comment]
support normal m3u8
