### ISSUE TITLE
大佬，rtmp协议的发送message data有api可以调用吗？

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1687]
@CarGuo  因为有一个接口需要用到这个 rtmp协议的message data传值来调用接口，所以想问下有方法调用吗

**Comment by xi5528336** [comment]
这个服务器那边会推一个录播视频以直播流的形式推给我们，然后需要快进快退功能，要求我们Android客户端这边以message data传给他们来控制rtmp视频的快进快退。我对这个不是很了解  有什么建议吗。
![image](https://user-images.githubusercontent.com/35209545/50040570-eb990a00-0080-11e9-8a14-aeb3b9a97291.png)

**Comment by CarGuo** [comment]
理论上，你是在url上带上的，或者在header带上

**Comment by xi5528336** [comment]
@CarGuo  你说的带上是指在http的请求协议上操作吗 还是rtmp协议

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1695
