### ISSUE TITLE
重复访问m3u8资源

### ISSUE THREAD

**Issue by JewSaten** [CarGuo/GSYVideoPlayer#1688]
## 问题描述： 播放m3u8格式视频，抓包看到重复的访问

> 把链接复制到demo中也是一样的问题

## GSY依赖版本  
6.0.1

## Demo中的复现步骤

Demo中的webdetail, 复制我自己的m3u8进去也是重复访问

## 问题log

# | Result | Protocol | Host | URL | Body | Caching | Content-Type | Process | Comments | Custom
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
6 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
7 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
8 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
9 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
10 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
11 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
12 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
13 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
14 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
15 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
16 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
17 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
18 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
19 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
20 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
21 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
22 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
23 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
24 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
25 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
26 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
27 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
28 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
29 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
30 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
31 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
32 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
33 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
34 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
35 | 200 | HTTP | storage1.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 742 |   | application/vnd.apple.mpegurl |   |   |  
36 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |  
37 | 301 | HTTP | mpsnode.zp03d.cn | /vod/20181206/e98bf01833b1c16f69/playlist.m3u8 | 0 |   | text/html |   |   |

**Comment by CarGuo** [comment]
不是很理解你的问题

**Comment by CarGuo** [comment]
m3u8内是一个一个的切片，是按照ts一个请求完，继续请求下一个ts

**Comment by JewSaten** [comment]
产品说ios不会这样重复请求

**Comment by JewSaten** [comment]
问题在于播放器会重复去请求m3u8这个文件，  ios上的那个只会请求一次，ts文件，如果重复请求，那个是正常的

**Comment by CarGuo** [comment]
方便提供下外网url测试下么
