### ISSUE TITLE
请问怎么设置请求头

### ISSUE THREAD

**Issue by JewSaten** [CarGuo/GSYVideoPlayer#1689]
## 问题描述：

setUpLazy， getGSYVideoOptionBuilder().setMapHeadData ，GSYVideoManager.instance().setOptionModelList 设置均无效

## 问题机型/系统：

小米6

## GSY依赖版本

6.0.1

请问怎么设置才能弄，谢谢

**Comment by JewSaten** [comment]
> 1.
'''
  Map<String, String> mapHeaderData = new HashMap<>();
        mapHeaderData.put("hulu", "xmandroid");
        videoView.setUpLazy(ConfigUtils.getVdoUrl(context, item.play_url), true, null, mapHeaderData, "");
'''

> 2. 
‘’‘
 Map<String, String> mapHeaderData = new HashMap<>();
        mapHeaderData.put("hulu","xmandroid");
        getGSYVideoOptionBuilder().setMapHeadData(mapHeaderData)
                .setVideoAllCallBack(this).setGSYVideoProgressListener(this)
                .build(getGSYVideoPlayer());
‘’’

> 我是这样弄得没效果

**Comment by JewSaten** [comment]
请问要怎么设置才能有效

**Comment by JewSaten** [comment]
这个是http协议的请求头吗还是？

**Comment by JewSaten** [comment]
是不是要exo的才可以

**Comment by CarGuo** [comment]
如果是ijk模式下的，demo应该可以在log下看到设置进入的头信息

**Comment by JewSaten** [comment]
主要是设置了抓包看不到，服务端也没收到，是不是这个head是播放器的参数，而不是http协议的head

**Comment by CarGuo** [comment]
我这边抓包正常

![5c19c18fe4b087bbc75bb6e3](https://user-images.githubusercontent.com/10770362/50198166-5bf7a200-0385-11e9-86a0-2a0eae2cea39.png)

**Comment by JewSaten** [comment]
可以指导下你怎么做的吗，或者你提交到demo项目我学习下

**Comment by CarGuo** [comment]
就是正常的设置，detailplayer里有

**Comment by JewSaten** [comment]
我也是这么弄得，只不过我是跟着demo的webdetail那要做的然后在setMapHeadData

**Comment by JewSaten** [comment]
我在demo的webdetail设置一样没效果

**Comment by CarGuo** [comment]
这就不清楚了，都是一样的，正常设置

**Comment by CarGuo** [comment]
刚刚好像注意到，你用 setup ，不要用 setupLazy

**Comment by CarGuo** [comment]
那就很奇怪了，测试都是正常

**Comment by liuyiyuan** [comment]
播放器设置配置的时候不要使用setUpLazy; 直接调用setUp() 方法，就能够让你想新增的header设置成功
