### ISSUE TITLE
全屏问题

### ISSUE THREAD

**Issue by xuanu** [CarGuo/GSYVideoPlayer#1691]
## 问题描述：
是否一定要设置一个方向吗？
在manifest中不配置方向
横屏进入时，全屏后，退出全屏，模拟器会换个方向
竖屏进入，   全屏后，退出全屏，没有问题
视频地址：https://www.bilibili.com/video/av38384152
## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

**Comment by CarGuo** [comment]
是的，目前是需要在AndroidManifest配置方法

**Comment by xuanu** [comment]
设置横屏也不可以吗？
我试了一下，设置为横屏还是会有同样的问题。

**Comment by xuanu** [comment]
以前也有个软件使用了你的这个功能，好像旧的版本转屏是没问题的。

**Comment by CarGuo** [comment]
具体忘记了，因为一直都是在有配置的情况下使用

**Comment by xuanu** [comment]
横屏的时候，我是通过放大布局来实现的。
