### ISSUE TITLE
是否支持对加密视频进行播发

### ISSUE THREAD

**Issue by fengjian123** [CarGuo/GSYVideoPlayer#1693]
为了防止对视频，音频进行盗链和传播，打算对音视频进行加密处理，为了适配gsy播放器，使用什么方案的加密和解密技术比较合适，希望给个思路@CarGuo

**Comment by CarGuo** [comment]
ijk内核的，依赖ex-so是支持 crypto 加解密的。

**Comment by fengjian123** [comment]
这个crypto加密是不是在ex-so里面已经集成了，直接用就可以还是要自己去实现？

**Comment by fengjian123** [comment]
刚刚看了下在你的ex-so 里面好像已经集成了，不过具体如何使用，有没有例子可以借鉴一下？是用crypto加密后直接可以播放吗？播放器自带解密功能？@CarGuo

**Comment by fengjian123** [comment]
@CarGuo好的，谢谢大佬

**Comment by fengjian123** [comment]
如果我用AES对下载的视频进行加密保存，然后播放的时候可以通过gsy配置自动解密播放吗？还是需要解密后再通过gsy去播放，这样的话，效率就慢很多了。

**Comment by CarGuo** [comment]
没这么试过，我也不好说

**Comment by fengjian123** [comment]
所以还是要自己实现解密才能用gsy去播放吗？那ex-so里面那个crypto怎么用？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1523
https://github.com/CarGuo/GSYVideoPlayer/issues/396
