### ISSUE TITLE
rtmp协议的message data 发送实现

### ISSUE THREAD

**Issue by xi5528336** [CarGuo/GSYVideoPlayer#1695]
有什么办法在播放的时候发送这种类型的数据
![image](https://user-images.githubusercontent.com/35209545/50213285-1e603c80-03b8-11e9-9d69-0daea7354c21.png)
public boolean setUp(String url, boolean cacheWithPlay, File cachePath, Map<String, String> mapHeadData, String title) 是在mapHeadData头部添加吗

**Comment by CarGuo** [comment]
项目应该不支持，我记得 LibRTMP 好像可以推流，不过这个是服务推流吧，总觉得你是需求怪怪的。

目前gsy没打包这个协议，而且这个打包完还得自己改jni代码
```
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocol=librtmp*"
```
