### ISSUE TITLE
视频列表第一次进来没问题，向上滑动后，视频控件展示变小如下图

### ISSUE THREAD

**Issue by wozhizhizhi** [CarGuo/GSYVideoPlayer#1701]
请问下大佬，视频列表第一次进来没问题，向上滑动后，在看回来，视频控件展示变小收缩了，找了好几天都没发现是什么原因！
![1545220672 1](https://user-images.githubusercontent.com/6690175/50218930-828afc80-03c8-11e9-986d-51449dcf8497.png)

**Comment by CarGuo** [comment]
demo不复现的问题，我也很难定位

**Comment by wozhizhizhi** [comment]
好的大佬我在仔细找找,多谢了
