### ISSUE TITLE
官方Demo RecycleView 全屏和小窗列表，点击全屏获取退出全屏进度条无反映；进度条不会动

### ISSUE THREAD

**Issue by combing520** [CarGuo/GSYVideoPlayer#1704]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！
官方Demo RecycleView 全屏和小窗列表，点击全屏获取退出全屏进度条无反映；进度条不会动
## 问题机型/系统：
真机 红米6； 华为 MHA-AL00; VIVO x7; 小米6 等 10几个测试机
例如 真机 小米note2 Android7.0

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`
例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤
使用 Demo 中的 RecycleView 的全屏和小窗； 点击任意一个条目的全屏或者退出全屏； 主要观察对应的进度条
Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/pull/1694/files

**Comment by CarGuo** [comment]
fix https://github.com/CarGuo/GSYVideoPlayer/pull/1694/files
