### ISSUE TITLE
rtmp 播放无声音，可否上传一个支持的so

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#1705]
## 问题描述：

rtmp 播放无声音，可否上传一个支持的so， 

> 编译IJK的动态链接库，绝对是对于win党最大的打击

## GSY依赖版本
    compile 'com.shuyu:gsyVideoPlayer-java:4.1.3'
    compile 'com.shuyu:gsyVideoPlayer-ex_so:4.1.3'
    compile 'com.shuyu:GSYVideoPlayer-exo2:4.1.3'

```
我看这个 说可以 播放，难道是升级一下6.0，或者 我代码的问题？
https://blog.csdn.net/mei_jia12/article/details/84573234

**Comment by CarGuo** [comment]
播放无声音？可以提供外链吗？你可以首先确定下音频的编码

**Comment by yang0000meng** [comment]
加载m3u8直播时  加载m3u8很卡 
所以加了下面代码，导致 rtmp://10454.liveplay.myqcloud.com/live/ahws 无声音
  videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,  "http-detect-range-support", 0);
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
//        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 8);
//        list.add(videoOptionModel);

**Comment by Likeyong** [comment]
videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);

其实好像只要去掉这个就好了,我这边也遇到了这个问题,参考了你的解决方式,遍历测试每个,发现去掉这个我这边就没问题了
