### ISSUE TITLE
使用RecycleView 全屏和小窗列表，现在点击进入全屏或者退出全屏进度条在播放过程中无反映；进度条依然不会刷新；只用在播放完成的时候进度条才突然到100%

### ISSUE THREAD

**Issue by combing520** [CarGuo/GSYVideoPlayer#1706]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！
使用RecycleView 全屏和小窗列表，现在点击进入全屏或者退出全屏进度条在播放过程中无反映；进度条依然不会刷新；只用在播放完成的时候进度条才突然到100%；麻烦你那边更新代码后，自己先运行下；
我是在Fragment 中使用的；
## 问题机型/系统：
真机；主流的 华为，小米；ViVo，Oppo都一样
例如 真机 小米note2 Android7.0

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'
例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤
在Fragment中集成 RecycleView 的全屏和小窗列表； 点击进入全屏或者是从全屏中退出来；分别注意切换前后的进度条；只有等到视频播放完成后才会突然将进度条更新到100%；播放过程中进度条依然不会动
Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by combing520** [comment]
切换前后 的进度条不刷新； 但是点击播放的界面后； 进度条又会刷新； 不点击播放的区域是绝对不会刷新进度条

**Comment by CarGuo** [comment]
最新demo已经修复。

**Comment by combing520** [comment]
嗯；好的；我先下载下来看下； 谢谢

**Comment by combing520** [comment]
这次的 新的 Demo 好像问题更加严重；  一样的地方；RecycleView 小窗和全屏； 现在也有的地方时间能刷新； 有的地方时间不能刷新，但是进度条都是不能刷新

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/releases/download/v6.0.2/app-release.apk

我这边测试正常了，你可以安装这个试试，如果有问题可以录制个视频看下这样直观些

**Comment by combing520** [comment]
我可以加下你的微信或者QQ； 方便说下情况？
不然没次都需要这样沟通；可能效率会低很多

**Comment by combing520** [comment]
嗯； 我这边主要不太客观的将我这边的情况反馈过来； 我试了例子；我当前使用的 是红米4x，Android 7.1.2 ; 点击给的安装包；然后也是切换的时候后会有一瞬间的同步；然后就又不同步了；只要加载完成后才同步了

**Comment by combing520** [comment]
大神； 你好； 现在使用你给的 Demo ; 是可以同步进度条和时间；但是运行刚刚从你那边下载的 项目；直接运行的话，还是不能同步； 是不是现在的项目是不是还没有更新代码？

**Comment by CarGuo** [comment]
你看下提交，有6.0.2的应该就是

**Comment by combing520** [comment]
嗯，我下载的就是最新 6.0.2的； 只是运行起来和你给的那个安装包有区别；安装包的进度条和时间有更新； 下载的项目直接运行就不能；

**Comment by CarGuo** [comment]
你确定本地运行的是否 GSYVideoHelper 中有 restartTimerTask 方法的调用吧

**Comment by combing520** [comment]
有的

**Comment by combing520** [comment]
分别是第 250 行 和322行  都执行了 mGsyVideoPlayer.restartTimerTask();

**Comment by CarGuo** [comment]
目前测试6.0.2已修复

**Comment by combing520** [comment]
并没有好； 50 行 和322行 都执行了 mGsyVideoPlayer.restartTimerTask();  但是 6.0.2 处源码的地方是红色的； 我这边用你官方的Demo ;直接跑也是不可以；
