### ISSUE TITLE
用ListGSYVideoPlayer循环播放视频，内存泄漏

### ISSUE THREAD

**Issue by luomantic** [CarGuo/GSYVideoPlayer#1708]
（ps 首页问题集锦和demo已经了解一下了！）

## 问题描述：
描述：rk3288用ListGSYVideoPlayer循环播放视频，用IJK内核播放视频，播放时间久了会黑屏，无ANR，但是检测到内存泄漏。
猜想：现在的onAutoComplete中调用的PlayNext，会不会是每次播放完一个视频后，资源没释放。
求助：想让每次播放完成之后释放掉所有的资源，谢谢你。
![tim 20181224110217](https://user-images.githubusercontent.com/13751295/50389933-6510b680-076b-11e9-80f4-c98a7212294d.png)

## 问题机型/系统：
rk3288

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤
Demo中的

问题代码：(如果有)
```
@Override
public void onAutoCompletion() {
        if (playNext()) {
            return;
        }
        super.onAutoCompletion();
}

public boolean playNext() {
        if (mPlayPosition < (mUriList.size() - 1)) {
            mPlayPosition +=1;
            GSYVideoModel gsyVideoModel = mUriList.get(mPlayPosition);
            mSaveChangeViewTIme = 0;
            setUp(mUriList, mCache, mPlayPosition, null, mMapHeadData, false);
            if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) {
                mTitleTextView.setText(gsyVideoModel.getTitle());
            }
            startPlayLogic();
            return true;
        }else if(mPlayPosition==(mUriList.size()-1)) {//循环播放
            mPlayPosition = 0;
            GSYVideoModel gsyVideoModel = mUriList.get(mPlayPosition);
            mSaveChangeViewTIme = 0;
            setUp(mUriList, mCache, mPlayPosition, null, mMapHeadData, false);
            if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) {
                mTitleTextView.setText(gsyVideoModel.getTitle());
            }
            startPlayLogic();
            return true;
        }
        return false;
    }
```

## 问题log（如果有）
无问题log

**Comment by CarGuo** [comment]
startPlayLogic 的时候会调用到 startPrepare ，之后 调用到 onCompletion  的   setStateAndUi(CURRENT_STATE_NORMAL);  然后   getGSYVideoManager().releaseMediaPlayer();

**Comment by luomantic** [comment]
> startPlayLogic 的时候会调用到 startPrepare ，之后 调用到 onCompletion 的 setStateAndUi(CURRENT_STATE_NORMAL); 然后 getGSYVideoManager().releaseMediaPlayer();
好吧，谢谢你，我再仔细的检查测试一下...  赞+1

**Comment by CarGuo** [comment]
因为 ListGSYVideoPlayer 模式只有一个内核的，每次都是释放后重新播放，你可以在 IjkPlayerManager 的 release 打印是否有被调用

**Comment by luomantic** [comment]
> 因为 ListGSYVideoPlayer 模式只有一个内核的，每次都是释放后重新播放，你可以在 IjkPlayerManager 的 release 打印是否有被调用

好的，谢谢大佬的建议，我先去试一下，哈哈....  实在不行，我就只能提高机器的配置了

**Comment by Android-Boys** [comment]
我也遇到一样的问题了。播放久了会黑屏。轮流播放
