### ISSUE TITLE
Channel is unrecoverably broken and will be disposed 

### ISSUE THREAD

**Issue by Android-Boys** [CarGuo/GSYVideoPlayer#1710]
## 问题描述：
3-5个播放器同时播放，过一会就会出现这个问题。无明显的oom异常

Channel is unrecoverably broken and will be disposed  异常

## 问题机型/系统：

android 8.0 tv

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

**Comment by CarGuo** [comment]
不明觉厉
