### ISSUE TITLE
视频划走后onPause暂停，划回来黑屏

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1711]
## 问题描述：

RecyclerView嵌套StandardGSYVideoPlayer,视频划走后onPause暂停，划回来黑屏
## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

在ListMultiVideoActivity这个类

**Comment by CarGuo** [comment]
demo中，划走是release了吧？

如果你要实现 划走后onPause ，回来继续播放，这个首先要理解recyclerview的item是存在复用的，这一块的管理需要即自己处理。

**Comment by akaisiliz** [comment]
demo中我已改成onpause()，RecyclerView划走后再划回来视频是暂停状态但是黑屏，是sufaceview销毁了吗？我如何处理

**Comment by CarGuo** [comment]
首先要知道这里的黑屏是因为暂停的黑屏还是错误的黑屏。
如果点击还能正常播放，那就是正常的黑屏。

setShowPauseCover 可以实现加上暂停帧显示效果，但是存在OOM的可能。

**Comment by akaisiliz** [comment]
嗯是正常的黑屏，setShowPauseCover我加上了，但是会得到两个结果，如果播放中点击暂停滑走在回来是有暂停帧的，如果播放中滑走滑回来就黑屏了，如何显示暂停帧

**Comment by CarGuo** [comment]
源码里是在 changeUiToPauseShow  ，在 onClickUiToggle 和 resolveUIState 会调用，正常的话 onVideoPause()是会通过  setStateAndUi(CURRENT_STATE_PAUSE); 调用到 resolveUIState

**Comment by akaisiliz** [comment]
嗯我看过了setStateAndUi和resolveUIState都走了，但是是黑屏

**Comment by CarGuo** [comment]
你可以调试看看bitmap是不是不正常或者没有正常绘制上去

**Comment by akaisiliz** [comment]
嗯，我看过initCover，mFullPauseBitmap确实为空串，不过显示出来的也是为空

**Comment by CarGuo** [comment]
问题应该就是在这里，可以看看是什么逻辑导致为空的
