### ISSUE TITLE
大佬，请教一个问题，播放器播频繁opening可能是什么原因？

### ISSUE THREAD

**Issue by Redoteam** [CarGuo/GSYVideoPlayer#1713]
![qq20181224-0](https://user-images.githubusercontent.com/17085002/50409066-92706980-082a-11e9-8615-de5f176b08b5.png)
播了一秒不到就opening，次数特别多，这个是导致视频卡顿的原因吗？如果是的话，可能是什么原因导致频繁重新opening？麻烦大佬了！！

**Comment by CarGuo** [comment]
m3u8是一个类目录文件，里面的ts链接才是真实的流地址，buffer加载的时候，会预先加载一批ts文件，所以会打开加载一批ts流。

**Comment by Redoteam** [comment]
谢谢了，大概明白了，频繁opening是因为ts链接才是真实流地址，m3u8是个目录，里面有很多ts文件。

**Comment by CarGuo** [comment]
这个是给直播的
