### ISSUE TITLE
本地视频拖动进度问题

### ISSUE THREAD

**Issue by z8806c** [CarGuo/GSYVideoPlayer#1715]
本地视频测试 设置了enable-accurate-seek

SystemPlayerManager 模式下快速拖动进度条 当前帧可以快速显示出来，但seek不准确,找附近关键帧
Exo2PlayerManager 模式下快速拖动进度条 当前帧加载慢，不能实时显示 但seek精确

只能二选一？Exo2PlayerManager 模式下本地视频不能像系统模式快速显示当前帧吗？

**Comment by CarGuo** [comment]
enable-accurate-seek 只针对 IJK模式有效

至于 sys 和 exo 的取舍，或者exo2你可以看看exoplayer的官网看看是否有可优化的
