### ISSUE TITLE
多任务视频播放问题

### ISSUE THREAD

**Issue by akaisiliz** [CarGuo/GSYVideoPlayer#1716]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
demo中我已改成onpause()，RecyclerView划走后再划回来视频是暂停状态但是黑屏，需要显示暂停的那一帧图，我如何处理？

## 问题机型/系统：

小米4

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Demo中的ListMultiVideoActivity类

问题代码：(如果有)
if (customManager.getPlayTag().equals(ListMultiNormalAdapter.TAG)
                                && (position < firstVisibleItem || position > lastVisibleItem)) {
                            CustomManager.onPause(customManagerEntry.getKey());
}

**Comment by CarGuo** [comment]
setShowPauseCover 方法有做暂停帧截图显示，但是多了可能存在OOM

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1711 issue合并
