### ISSUE TITLE
6.0.2 视频的尺寸被缩小

### ISSUE THREAD

**Issue by combing520** [CarGuo/GSYVideoPlayer#1717]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！
使用 6.0.2版本； 进入的时候会显示 视频的 封面图片； 当视频准备播放的时候； 画面的宽度会突然缩小一部分；设置了全屏是没有用的； 此时缩小后的 VideoView大约只占全屏宽度的 90% + ；但是小于100%
## 问题机型/系统：

例如 真机 小米note2 Android7.0
真机 小米6 ； Vivo X7 ； 华为MHA-AL00; 红米4X
## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'
例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

1. ' implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'  将6.0.2 倒入到项目中
2. 使用 官方的 videoPlayer
3. 进入页面后使用自动播放 videoPlayer.startPlayLogic()
4. 视频在缓存的时候； 视频的封面图片会占据全屏；等到视频 准备好了，要播放的时候；视频的宽度会缩小；原来播放器设置的是  android:layout_width="match_parent"； 实际在播放的时候大概宽度只有90% +， 小于100 %； 没有设置任何的padding 和margin;

////================////
附带一句； 列表的播放进度条还是不能及时更新进度条和时间； 具体情况已经发到你的 QQ邮箱；可以的话，麻烦看下QQ邮箱； 加下 QQ； 谢谢大神

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请提供测试视频url测试缩小问题，我这边测试正常。
然后看了你的邮件了，有可能是你的-java的aar包缓存不正常问题。因为java包6.0.2之前有一次发布失败，所以发布了两次，正常如下图
![5c22f8c8e4b087bbc763e73c](https://user-images.githubusercontent.com/10770362/50431142-7096e580-0903-11e9-8ca8-d4af9dffaeee.jpg)

**Comment by combing520** [comment]
视频地址如下：
http://restest.ccwb.cn/public/Upload/2/20181221/20181221154059PW37XX.mp4
http://restest.ccwb.cn/public/Upload/2/20181221/20181221154015ETFGNB.mp4
http://restest.ccwb.cn/public/Upload/2/20181221/201812211540186DGXAP.mp4
http://restest.ccwb.cn/public/Upload/2/20181221/20181221154021QXRUEQ.mp4
麻烦大神看下了； 谢谢； 

那个 6.0.2 的问题； 我现在清理下项目 再 依赖下 implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'   ；应该就可以了吧

**Comment by CarGuo** [comment]
C:\Users\{用戶名}\.m2
C:\Users\{用戶名}\.gradle 

在这两个目录下，搜索 gsyVideoPlayer 相关的目录文件，都删了，然后clean项目重新gradle同步。

**Comment by CarGuo** [comment]
@combing520 我在demo的videoPlayer中播放 http://restest.ccwb.cn/public/Upload/2/20181221/20181221154059PW37XX.mp4
Video: h264, 1 reference frame (avc1 / 0x31637661), yuv420p(left), 720x1280, 0/1, 1375 kb/s  videoWidth: 720 videoHeight: 1280

竖屏的视频，大小正常啊

**Comment by combing520** [comment]
大神；具体的内容已经发送到你的QQ邮件; 麻烦查看下

**Comment by CarGuo** [comment]
看了，没看出问题的点在哪里？？？

**Comment by combing520** [comment]
你可以看到会闪一下？ 然后本来是全屏的以下就多出来一点黑边了。就是视频的画面突然变小了； 我这边是Mac 电脑；

也需要 在对应的 Wins电脑
C:\Users{用戶名}.m2
C:\Users{用戶名}.gradle

在这两个目录下，搜索 gsyVideoPlayer 相关的目录文件，都删了，然后clean项目重新gradle同步。 ？

**Comment by CarGuo** [comment]
mac也有 .gradle和 .m2 的文件夹，也是在用户名目录下的隐藏文件夹。

**Comment by CarGuo** [comment]
是有看到闪一下，那个应该是封面和视频比例不一样的正常现象吧。

视频比例和手机分辨率比例不一样，所以存在黑边。可以看看 GSYVideoType 
```
public class GSYVideoType {

    //默认显示比例
    public final static int SCREEN_TYPE_DEFAULT = 0;

    //16:9
    public final static int SCREEN_TYPE_16_9 = 1;

    //4:3
    public final static int SCREEN_TYPE_4_3 = 2;

    //全屏裁减显示，为了显示正常 CoverImageView 建议使用FrameLayout作为父布局
    public final static int SCREEN_TYPE_FULL = 4;

    //全屏拉伸显示，使用这个属性时，surface_container建议使用FrameLayout
    public final static int SCREEN_MATCH_FULL = -4;
```

**Comment by combing520** [comment]
嗯；好的； 我试试； 谢谢； 我按照大神的删除了，现在是可以同步了？

**Comment by combing520** [comment]
删除后现在出现了一个问题； 就是使用你的依赖库的地方全都红色 Cannont resolve symbol ; 但是可以正常运行，不会出现编译出错；只是你的依赖库都不会出现提示

**Comment by combing520** [comment]
谢谢大神； 已经解决了； 不好意思麻烦大神了；大神可以 close 这个了；
