### ISSUE TITLE
有个需求，录制gif带弹幕的功能，就是gif上有弹幕，这个怎么实现啊，效果参考b站

### ISSUE THREAD

**Issue by kyriej** [CarGuo/GSYVideoPlayer#1718]
有个需求，录制gif带弹幕的功能，就是gif上有弹幕，这个怎么实现啊，效果参考b站

**Comment by CarGuo** [comment]
如果你看了源码 GifCreateHelper ，就知道这里最终是对 TextureView 的每一帧转化为bitmap，然后保存本地，在停止的时候，对多个bitmap合成gif。

所以这里如果你需要弹幕也一起录制，那么你需要在保存bitmap的时候，不只是保存 画面的bitmap，还需要把弹幕的surface bitmap也保存下来。

比如说，GifCreateHelper  的 startSaveBitmap 的时候获得了当前帧bitmap，然后把弹幕的bitmap也解出来，合并后再绘制到一块

**Comment by kyriej** [comment]
大佬，如果绘制弹幕的surfaceview应该用什么方法呢，或者有什么具体的类，我去研究下

**Comment by CarGuo** [comment]
弹幕的是要看b站的issue吧
