### ISSUE TITLE
rtsp播放时候内存泄漏导致卡死~！

### ISSUE THREAD

**Issue by 136093330** [CarGuo/GSYVideoPlayer#1719]
## 问题描述：rtsp播放时候内存泄漏导致卡死~！

在demo里面的简单播放

## 问题机型/系统：

华为v8

## GSY依赖版本

直接源码依赖

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1720 合并问题
