### ISSUE TITLE
AppBarLayout 配合 GSYVideoPlayer作为头部播放联动上滑出现问题

### ISSUE THREAD

**Issue by yanyulou** [CarGuo/GSYVideoPlayer#1722]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

AppBarLayout 配合 GSYVideoPlayer作为头部播放联动上滑的时候，当播放器视频后，无论暂停与否，AppBarLayout.OnOffsetChangedListener中的onOffsetChanged会一直调用，也就是会一直消耗性能

## 问题机型/系统：

例如 真机 华为，小米等机型

## GSY依赖版本

  implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'

## Demo中的复现步骤

Demo中的ScrollingActivity页面打开后AppBarLayout会出现这个问题，

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
onOffsetChanged 调用目前来说是正常的
