### ISSUE TITLE
如何以横屏的方式打开一个视频

### ISSUE THREAD

**Issue by Hanniballol** [CarGuo/GSYVideoPlayer#1727]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我希望在系统方向锁定的情况下，以横屏的方式打开一个activity并横屏播放视频，请问有响应的实现吗

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
你直接把播放器在activity布局里设置为铺满，在Androidmanifest设置ac锁定横屏就好啦

**Comment by Hanniballol** [comment]
@CarGuo 但是需要根据响应的需求来判断是否需要横竖屏，如果上一个界面是横屏我就以横屏打开，如果上一个界面是竖屏我需要以竖屏打开

**Comment by Hanniballol** [comment]
如果代码强制横屏会有切换动画，这样达不到预期

**Comment by CarGuo** [comment]
你配置两个activity不就好了。

**Comment by Hanniballol** [comment]
OK
