### ISSUE TITLE
updateProcessTimer  定时有时取消失败

### ISSUE THREAD

**Issue by woyoudianhuai** [CarGuo/GSYVideoPlayer#1729]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

updateProcessTimer  进度定时器 定时取消失败

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

ListGSYVideoPlayer 全屏时切换下一首或者点击暂停 一定概率定时器还一直在不停的走

问题代码：(如果有)
 protected void setStateAndUi(int state) {
        mCurrentState = state;

        if ((state == CURRENT_STATE_NORMAL && isCurrentMediaListener())
                || state == CURRENT_STATE_AUTO_COMPLETE || state == CURRENT_STATE_ERROR) {
            mHadPrepared = false;
        }
        //CURRENT_STATE_PLAYING_BUFFERING_START

        switch (mCurrentState) {
            case CURRENT_STATE_NORMAL:
                Logger.d("cancelProgressTimer", isCurrentMediaListener() + "++>" + mCurrentState);
                if (isCurrentMediaListener()) {
                    cancelProgressTimer();
                    getGSYVideoManager().releaseMediaPlayer();
                    releasePauseCover();
                    mBuffterPoint = 0;
                    mSaveChangeViewTIme = 0;
                }
                if (audioFocusManager != null) {
                    audioFocusManager.abandonAudioFocus();
                }
                releaseNetWorkState();
                break;
            case CURRENT_STATE_PREPAREING:
                //cancelProgressTimer();
                resetProgressAndTime();
                break;
            case CURRENT_STATE_PLAYING:
                startProgressTimer();
                break;
            case CURRENT_STATE_PAUSE:
                //startProgressTimer();
                cancelProgressTimer();//此处取消定时器
                break;
            case CURRENT_STATE_ERROR:
                if (isCurrentMediaListener()) {
                    getGSYVideoManager().releaseMediaPlayer();
                }
                break;
            case CURRENT_STATE_AUTO_COMPLETE:
                cancelProgressTimer();
                if (mProgressBar != null) {
                    mProgressBar.setProgress(100);
                }
                if (mCurrentTimeTextView != null && mTotalTimeTextView != null) {
                    mCurrentTimeTextView.setText(mTotalTimeTextView.getText());
                }
                if (mBottomProgressBar != null) {
                    mBottomProgressBar.setProgress(100);
                }
                break;
        }
        resolveUIState(state);
    }
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
可以在外部调用，继承后增加类似源码中的如下方法，调用的时候通过 player.getCurrentPlayer().restartTimerTask()
```
    /**
     * 重新开启进度查询以及控制view消失的定时任务
     * 用于解决GSYVideoHelper中通过removeview方式做全屏切换导致的定时任务停止的问题
     * GSYVideoControlView   onDetachedFromWindow（）
     */
    public void restartTimerTask() {
        startProgressTimer();
        startDismissControlViewTimer();
    }
```

**Comment by woyoudianhuai** [comment]
好的，非常感谢
