### ISSUE TITLE
音频焦点设置无效

### ISSUE THREAD

**Issue by qssq** [CarGuo/GSYVideoPlayer#173]
以前的app就获取音频管理器然后requestfocus就可以达到让其他正在播放的暂停效果，现在不行了，搞不懂了。。

**Comment by CarGuo** [comment]
不是很理解，GSY内部也有AudioManager

**Comment by qssq** [comment]
是啊，我搞不懂了为什么无法获取焦点，第一次见，我以前的项目不管是录音还是播放，都能抢，这次我在播放的时候获取焦点，音乐还是没有停止，好痛苦啊，没有半点思绪了

**Comment by qssq** [comment]
好了，好像是我把我自己以前的代码改乱了，没有做 监听处理
