### ISSUE TITLE
播放mp4加密视频加载时长为10秒左右

### ISSUE THREAD

**Issue by Xcffangbo** [CarGuo/GSYVideoPlayer#1733]
## 问题描述：
播放mp4加密视频加载时长为10秒左右

## 问题机型/系统：红米/Android 6.0 API 23

真机 Redmi Note 4X

## GSY依赖版本
 implementation 'com.shuyu:GSYVideoPlayer:6.0.1'

## Demo中的复现步骤
使用Demo 中无添加功能的 Simple 播放即可
链接：https://1252442451.vod2.myqcloud.com/9532a465vodtransgzp1252442451/a1b39efd9031868223641919000/v.f30.mp4?t=5c2cd8ad&exper=0&us=d28xc3gns57i&sign=707fd65abce346b7923e9bd2a61522e7
问题代码：
为了简便复现BUG,直接 setup  startPlayLogic 即可复现
目前只尝试出了切换内核到System.class 下可恢复延迟播放，但无奈项目必须使用IJK来完成播放。

麻烦大神抽空帮忙看一下有没有更好地解决方法，或者折中策略，在此感谢！

**Comment by CarGuo** [comment]
我这边测试是  403 Forbidden

**Comment by Xcffangbo** [comment]
好的，上边那个链接是两个小时过期，现在设置了不过期的链接，麻烦有空的话看一下 

https://1252442451.vod2.myqcloud.com/e10b01bdvodgzp1252442451/a1b39efd9031868223641919000/playlist.f9.mp4?t=833c7dbd&exper=0&us=ajml03t9r7er&sign=b2e357f8294c51e51d5530ab9eab6e7e

**Comment by Xcffangbo** [comment]
我又看了一下，可不可能跟版本低的手机解密时花费时长有关呢？

**Comment by Xcffangbo** [comment]
大神，周末打扰了，但还是请有时间帮忙看一下， 万分感谢！

**Comment by CarGuo** [comment]
看了下，目前没什么头绪

**Comment by Xcffangbo** [comment]
大神，我又回来了， 这个BUG已经解决掉了 ，我添加了      IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_ERROR);
解决了长时间加载的问题，但是不是很懂，还请大神能帮我解答一下，万分感谢！

**Comment by CarGuo** [comment]
这是把低级的log输出屏蔽了

**Comment by CarGuo** [comment]
你可以看看log输出，我测试的时候是看到，解码的时候，so层有d和v级别的log输出很多，这个时候可能会占用资源等待吧，那时候看到了也没考虑过这个问题

**Comment by Xcffangbo** [comment]
感谢大神指导~
