### ISSUE TITLE
使用 Exo2PlayerManager 获取不到视频宽高

### ISSUE THREAD

**Issue by bilx** [CarGuo/GSYVideoPlayer#1734]
## 问题描述：

 PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)
 CacheFactory.setCacheManager(ExoPlayerCacheManager::class.java)

切换到 Exo播放器的之后

![image](https://user-images.githubusercontent.com/22422723/50592283-74f86b00-0ece-11e9-9b22-3357ee16e51c.png)

LoggerUtil.LOG_D(" height = ${gsyVideoManager.currentVideoHeight} width = ${gsyVideoManager.currentVideoWidth}")
        LoggerUtil.LOG_D(" height2 = ${gsyVideoManager.videoHeight} width2 = ${gsyVideoManager.videoWidth}")
        LoggerUtil.LOG_D(" height3 = $currentVideoHeight width3 = $currentVideoWidth")

以上获取的宽高都是 0 

## GSY依赖版本

api "com.shuyu:gsyVideoPlayer-java:6.0.1"
    api "com.shuyu:GSYVideoPlayer-exo2:6.0.1"
    api "com.shuyu:gsyVideoPlayer-ex_so:6.0.1"

**Comment by bilx** [comment]
请问一下是否有其他获取视频宽高比的方式呢？

**Comment by prohack** [comment]
老哥，最后有解决吗，我拿到的也是0，用了作者回复的方式也还是0
