### ISSUE TITLE
如何获取视频详细信息

### ISSUE THREAD

**Issue by tiandawu** [CarGuo/GSYVideoPlayer#1735]
如何获取视频详细信息如：码率、贞率、分辨率等

**Comment by CarGuo** [comment]
自定义playerManager，参考ijkplayer或者exoplayer官方接口。

如ijk

https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-example/src/main/java/tv/danmaku/ijk/media/example/widget/media/InfoHudViewHolder.java
