### ISSUE TITLE
recycle列表播放 引起崩溃

### ISSUE THREAD

**Issue by Leavds** [CarGuo/GSYVideoPlayer#1737]
![image](https://user-images.githubusercontent.com/26810069/50744606-9a370180-125f-11e9-8336-206afe27ab4e.png)
![image](https://user-images.githubusercontent.com/26810069/50744643-e8e49b80-125f-11e9-972d-f7648228357d.png)

android.view.LayoutInflater.createView(LayoutInflater.java:620)
--
3 ......
4 Caused by:
5 java.lang.NoClassDefFoundError:android.support.v4.graphics.drawable.DrawableWrapper
6 android.support.v7.widget.DrawableUtils.canSafelyMutateDrawable(DrawableUtils.java:149)
7 android.support.v7.widget.AppCompatDrawableManager.setPorterDuffColorFilter(AppCompatDrawableManager.java:739)
8 android.support.v7.widget.AppCompatDrawableManager.tintDrawable(AppCompatDrawableManager.java:276)
9 android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
10 android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:85)
11 android.support.v7.widget.AppCompatProgressBarHelper.loadFromAttributes(AppCompatProgressBarHelper.java:54)
12 android.support.v7.widget.AppCompatSeekBarHelper.loadFromAttributes(AppCompatSeekBarHelper.java:48)
13 android.support.v7.widget.AppCompatSeekBar.<init>(AppCompatSeekBar.java:50)
14 android.support.v7.widget.AppCompatSeekBar.<init>(AppCompatSeekBar.java:43)
15 android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:139)
16 android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016)
17 android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073)
18 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
19 android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
20 android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
21 android.view.LayoutInflater.inflate(LayoutInflater.java:492)
22 android.view.LayoutInflater.inflate(LayoutInflater.java:397)
23 android.view.LayoutInflater.inflate(LayoutInflater.java:353)
24 android.view.View.inflate(View.java:17902)
25 com.shuyu.gsyvideoplayer.video.base.GSYVideoView.initInflate(GSYVideoView.java:281)
26 com.shuyu.gsyvideoplayer.video.base.GSYVideoView.init(GSYVideoView.java:268)
27 com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.init(GSYVideoControlView.java:197)
28 com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.init(GSYBaseVideoPlayer.java:97)
29 com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.init(StandardGSYVideoPlayer.java:98)
30 com.yidi.minilive.activity.video.SampleCoverVideo.init(SampleCoverVideo.java:84)
31 com.shuyu.gsyvideoplayer.video.base.GSYVideoView.<init>(GSYVideoView.java:165)
32 com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.<init>(GSYVideoControlView.java:185)
33 com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.<init>(GSYBaseVideoPlayer.java:88)
34 com.shuyu.gsyvideoplayer.video.base.GSYVideoPlayer.<init>(GSYVideoPlayer.java:25)
35 com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.<init>(StandardGSYVideoPlayer.java:93)
36 com.yidi.minilive.activity.video.SampleCoverVideo.<init>(SampleCoverVideo.java:55)
37 java.lang.reflect.Constructor.constructNative(Native Method)
38 java.lang.reflect.Constructor.newInstance(Constructor.java:423)
39 android.view.LayoutInflater.createView(LayoutInflater.java:594)
40 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
41 android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
42 android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
43 android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
44 android.view.LayoutInflater.inflate(LayoutInflater.java:492)
45 android.view.LayoutInflater.inflate(LayoutInflater.java:397)
46 com.yidi.minilive.activity.video.RecyclerNormalAdapter.onCreateViewHolder(RecyclerNormalAdapter.java:39)
47 android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
48 android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
49 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
50 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
51 android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
52 android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
53 android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
54 android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
55 android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
56 android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
57 android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
58 android.view.View.layout(View.java:15184)
59 android.view.ViewGroup.layout(ViewGroup.java:4901)
60 com.hn.library.refresh.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:401)
61 com.hn.library.refresh.PtrFrameLayout.onLayout(PtrFrameLayout.java:347)
62 android.view.View.layout(View.java:15184)
63 android.view.ViewGroup.layout(ViewGroup.java:4901)
64 android.widget.RelativeLayout.onLayout(RelativeLayout.java:1154)
65 android.view.View.layout(View.java:15184)
66 android.view.ViewGroup.layout(ViewGroup.java:4901)
67 android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
68 android.view.View.layout(View.java:15184)
69 android.view.ViewGroup.layout(ViewGroup.java:4901)
70 android.widget.RelativeLayout.onLayout(RelativeLayout.java:1154)
71 android.view.View.layout(View.java:15184)
72 android.view.ViewGroup.layout(ViewGroup.java:4901)
73 android.widget.FrameLayout.layoutChildren(FrameLayout.java:500)
74 android.widget.FrameLayout.onLayout(FrameLayout.java:435)
75 android.view.View.layout(View.java:15184)
76 android.view.ViewGroup.layout(ViewGroup.java:4901)
77 android.widget.RelativeLayout.onLayout(RelativeLayout.java:1154)
78 android.view.View.layout(View.java:15184)
79 android.view.ViewGroup.layout(ViewGroup.java:4901)
80 android.widget.FrameLayout.layoutChildren(FrameLayout.java:500)
81 android.widget.FrameLayout.onLayout(FrameLayout.java:435)
82 android.view.View.layout(View.java:15184)
83 android.view.ViewGroup.layout(ViewGroup.java:4901)
84 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1883)
85 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1737)
86 android.widget.LinearLayout.onLayout(LinearLayout.java:1646)
87 android.view.View.layout(View.java:15184)
88 android.view.ViewGroup.layout(ViewGroup.java:4901)
89 android.widget.FrameLayout.layoutChildren(FrameLayout.java:500)
90 android.widget.FrameLayout.onLayout(FrameLayout.java:435)
91 android.view.View.layout(View.java:15184)
92 android.view.ViewGroup.layout(ViewGroup.java:4901)
93 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1883)
94 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1737)
95 android.widget.LinearLayout.onLayout(LinearLayout.java:1646)
96 android.view.View.layout(View.java:15184)
97 android.view.ViewGroup.layout(ViewGroup.java:4901)
98 android.widget.FrameLayout.layoutChildren(FrameLayout.java:500)
99 android.widget.FrameLayout.onLayout(FrameLayout.java:435)
100android.view.View.layout(View.java:15184)
101android.view.ViewGroup.layout(ViewGroup.java:4901)
102android.widget.LinearLayout.setChildFrame(LinearLayout.java:1883)
103android.widget.LinearLayout.layoutVertical(LinearLayout.java:1737)
104android.widget.LinearLayout.onLayout(LinearLayout.java:1646)
105android.view.View.layout(View.java:15184)
106android.view.ViewGroup.layout(ViewGroup.java:4901)
107android.widget.FrameLayout.layoutChildren(FrameLayout.java:500)
108android.widget.FrameLayout.onLayout(FrameLayout.java:435)
109android.view.View.layout(View.java:15184)
110android.view.ViewGroup.layout(ViewGroup.java:4901)
111android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2654)
112android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2340)
113android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1318)
114android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6664)
115android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
116android.view.Choreographer.doCallbacks(Choreographer.java:591)
117android.view.Choreographer.doFrame(Choreographer.java:560)
118android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
119android.os.Handler.handleCallback(Handler.java:808)
120android.os.Handler.dispatchMessage(Handler.java:103)
121android.os.Looper.loop(Looper.java:229)
122android.app.ActivityThread.main(ActivityThread.java:5493)
123java.lang.reflect.Method.invokeNative(Native Method)
124java.lang.reflect.Method.invoke(Method.java:515)
125com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
126com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
127dalvik.system.NativeStart.main(Native Method)

**Comment by CarGuo** [comment]
Demo怎么复现
