### ISSUE TITLE
外部播放监听onPrepared状态

### ISSUE THREAD

**Issue by qhs107** [CarGuo/GSYVideoPlayer#1738]
如果界面onDestroy   不release播放器，在外部可以通过GSYVideoManager.instance().getCurPlayerManager().pause()设置播放器暂停或继续，请问在外部有onPrepared的监听吗

**Comment by qhs107** [comment]
GSYVideoManager.instance().setListener(new GSYMediaPlayerListener() {  


这个监听在外部好像是无效的

**Comment by CarGuo** [comment]
这个内部切换时会被覆盖的，你这种需要使用自定义 GSYVideoManager。然后继承player，重写

```
  @Override
    public GSYVideoViewBridge getGSYVideoManager() {
        return  YourVideoManager.instance();
    }

```
