### ISSUE TITLE
OrientationUtils setClick赋值无效

### ISSUE THREAD

**Issue by wanggaowan** [CarGuo/GSYVideoPlayer#1739]
## 问题描述：

mOrientationUtils.setClick(false); 赋值无效

## 问题机型/系统：

所有机型都有这样的问题

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:6.0.2'

## Demo中的复现步骤

只要调用OrientationUtils中的setClick方法，赋值均无效

问题代码：(如果有)
```
//  系统代码，没有使用Click参数
public void setClick(boolean Click) {
        this.mClick = mClick;
 }
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不是很理解，设置这个干啥？

**Comment by wanggaowan** [comment]
我继承了OrientationUtils，重写了屏幕旋转逻辑，如果视频是横向全屏，那么竖屏播放时不允许旋转，横向播放时，根据感应器方向正向和反向横屏旋转，不会由横向切换到纵向

**Comment by CarGuo** [comment]
貌似我这边正常
