### ISSUE TITLE
视频变形问题

### ISSUE THREAD

**Issue by xhh1993** [CarGuo/GSYVideoPlayer#1743]
## 问题描述：

在详情页顶部播放一个竖屏的视频发生了变形，但是全屏没有问题。
视频尺寸如下（使用windows播放器查看到的视频信息）：
视频大小：544 * 960
纵横比：实际1:1，显示0.568:1

**Comment by CarGuo** [comment]
请提供问题效果图和测试url

**Comment by xhh1993** [comment]
感谢回复，问题已经解决了。
是添加了水印代码，导致竖屏播放变形还有第一次播放完成以后回放只有声音没有视频。
去除水印代码恢复正常
