### ISSUE TITLE
直播禁止拖动，不禁止音量和亮度手势调节。

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#1749]
直播禁止拖动，不禁止音量和亮度手势调节。
setIsTouchWiget 设置false 就把音量和亮度手势调节都给关闭了，怎样只设置禁止拖动，例如直播，直播一拖动就会一直加载中。

**Comment by CarGuo** [comment]
你可以继承后重载  touchSurfaceMove ，参考源码处理
