### ISSUE TITLE
视频全屏的问题

### ISSUE THREAD

**Issue by clark0704** [CarGuo/GSYVideoPlayer#175]
请问视频全屏的机制是什么，是简单的横竖屏切换，更换布局，还是在windows层播放？

**Comment by CarGuo** [comment]
具体逻辑看看源码GSYBaseVideoPlayer和ListVideoUtil

**Comment by clark0704** [comment]
横屏的时候切换清晰度，再播放视频，有声音，但画面是初始画面，感觉像是盖住了全屏播放得画面，竖屏就没问题

**Comment by CarGuo** [comment]
demo 中的 playActivity 没发现问题，不过SampleVideo是没做startWindowFullscreen的兼容处理的，startWindowFullscreen这种全屏需要你在全屏上，加上清晰度切换的逻辑处理，参看demo中对其的继承

**Comment by clark0704** [comment]
那这个逻辑怎么写呢，给个思路，大神。

**Comment by walterFeng** [comment]
某些手机上 全屏播放，statusbar影藏了，但statusbar的区域还是黑色的，这个黑色区域会盖住视频画面。@CarGuo

**Comment by CarGuo** [comment]
@walterFeng 具体什么机器？？

**Comment by DarrenHkk** [comment]
大神，全屏自动暂停该怎么解决？@CarGuo

**Comment by xujianlafeng** [comment]
我也遇到了横竖屏切换，状态栏覆盖视频区域的问题。我的是在小米的机子上面出现的，用的是StandardGSYVideoPlayer。具体操作：竖屏隐藏状态栏，点击切换横屏没有问题，再点击切换竖屏，状态栏出来了而且覆盖了视频区域。

**Comment by CarGuo** [comment]
请测试最新版本
