### ISSUE TITLE
Exo模式播放失败，ijk模式快进不能播放，长视频播放一段时间失败

### ISSUE THREAD

**Issue by colaly** [CarGuo/GSYVideoPlayer#1750]
## 问题描述：
问题1：
ExoPlayer2模式播放地址302的时候报错
问题2：
ExoPlayer2模式有部分地址不能播放，报错Source error.http://jdplay.lecloud.com/play.videocache.lecloud.com/270/47/109/letv-uts/14/ver_00_22-1122413088-avc-418735-aac-48000-5492000-328669926-e8d97f86fdb20cc61de5c4de0ee079d9-1546863163247.m3u8?crypt=99aa7f2e179&b=478&nlh=4096&nlt=60&bf=30&p2p=1&video_type=mp4&termid=0&tss=ios&platid=1&splatid=105&its=0&qos=3&fcheck=0&amltag=100&mltag=100&uid=992624403.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1547137800&nkey=be60b57f559c2df3d77421471ebb97e8&nkey2=1650a0773b7986e67f1aecec572780f8&auth_key=1547137800-1-0-1-105-ae85eff16c18581b4364bc251e2885ae&geo=CN-19-246-1&mmsid=66902369&tm=1547119206&key=78ce86aa39c9c7a5056956c46cc6dfe0&playid=0&vtype=13&cvid=1650604119571&payff=0&uidx=0&errc=0&gn=50038&ndtype=2&vrtmcd=106&buss=100&cips=59.42.63.19
问题3：
ijk模式快进不能播放，长视频播放一段时间失败，同一个视频exo模式可以实现快进

## 问题机型/系统：

真机 华为nove  Android8.0

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`
## 问题log（如果有）
问题1：
ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302
问题2：
 com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.

**Comment by CarGuo** [comment]
可以升级6.0.2 

exoplayer播放不出应该是识别类型错误，无法正确设置datesource，你可以通过如下解决

```
 /**
     * 是否需要覆盖拓展类型，目前只针对exoPlayer内核模式有效
     * @param overrideExtension 比如传入 m3u8,mp4,avi 等类型
     */
    public void setOverrideExtension(String overrideExtension) {
        this.mOverrideExtension = overrideExtension;
    }
```



或者参考 [ExoSourceManager](https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-exo_player2/src/main/java/tv/danmaku/ijk/media/exo2/ExoSourceManager.java)
自定义getMediaSource 使用
```
        /*ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                return null;
            }
        });*/
```

**Comment by colaly** [comment]
> 可以升级6.0.2
> 
> exoplayer播放不出应该是识别类型错误，无法正确设置datesource，你可以通过如下解决
> 
> ```
>  /**
>      * 是否需要覆盖拓展类型，目前只针对exoPlayer内核模式有效
>      * @param overrideExtension 比如传入 m3u8,mp4,avi 等类型
>      */
>     public void setOverrideExtension(String overrideExtension) {
>         this.mOverrideExtension = overrideExtension;
>     }
> ```
> 或者参考 [ExoSourceManager](https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-exo_player2/src/main/java/tv/danmaku/ijk/media/exo2/ExoSourceManager.java)
> 自定义getMediaSource 使用
> 
> ```
>         /*ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
>             @Override
>             public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
>                 return null;
>             }
>         });*/
> ```

已经发现的这个扩展方法，同时，感谢，解答！！！
当使用ijk内核的时候http://yun.hlxy.org/20181225/%E6%84%9B%E5%9B%9E%E5%AE%B6%E4%B9%8B%E9%96%8B%E5%BF%83%E9%80%9F%E9%81%9E%20EP478/1200kb/hls/index.m3u8 这个链接只有图像没有声音，log：W/IJKMEDIA: Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate
    Consider increasing the value for the 'analyzeduration' and 'probesize' options
同时，想问有没有方法可以控制播放失败了，自动切换其他内核播放

**Comment by colaly** [comment]
我通过文件后缀来判断使用ijk或者使用exo基本上可以解决上述问题了

**Comment by CarGuo** [comment]
播放器内核是全局的，只有播放前知道视频的容器协议，编码协议去变换了。
ijk下的黑屏你看问题集锦就好了
