### ISSUE TITLE
视频播放异常走onError。

### ISSUE THREAD

**Issue by Android-Boys** [CarGuo/GSYVideoPlayer#1751]
## 问题描述：
俩个播放器，播放rtsp协议的 辅码流数据，一切正常，也不会执行onError。。可是播放主码流，就会走OnError 方法 what值  是 -10000。 我笔记本和大屏是一个局域网都是插网线。电脑笔记本播放没得问题通过vlc。初步判断不是网络问题。 现场给领导演示，结果出问题了。大佬求教啊

## 问题机型/系统：
Android 8.0 TV

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1752
