### ISSUE TITLE
硬解码hevc导致native崩溃

### ISSUE THREAD

**Issue by YeGuli** [CarGuo/GSYVideoPlayer#1753]
## 问题描述：

你好，使用播放器硬解码TS-H265的udp流时，有很大几率出现native崩溃的问题。

## 问题机型/系统：

华为m5平板，支持video/hevc

## GSY依赖版本：

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.2`

## 问题代码：
这是VideoOptionModel的设置：
VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-all-videos", 1)
VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1)
VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-handle-resolution-change", 1)

## 问题log：
E/ACodec: [OMX.hisi.video.decoder.hevc] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
E/HISI_OMXVDEC: allocate native buffer: Bad port index 1
E/OMXNodeInstance: setParameter(0xe9e24b20:hisi.decoder.hevc, OMX.google.android.index.allocateNativeHandle(0x7f000008): Output:1 en=0) ERROR: BadPortIndex(0x8000101b)
E/HISI_OMXVDEC: >>>>>>>portDefn->nPortIndex = 0 xFramerate = 0
E/HISI_OMXVDEC: xFramerate > 60000, not reasonalbe , mFrameRate = 0
E/HISI_OMXVDEC: get_extension_index: OMX.google.android.index.describeColorAspects not implemented!
E/HISI_OMXVDEC: get_extension_index: OMX.google.android.index.describeHDRStaticInfo not implemented!
E/HISI_OMXVDEC: get_config: unknown index 0x6f100004
E/OMXNodeInstance: getConfig(0xe9e24b20:hisi.decoder.hevc, ConfigAndroidVendorExtension(0x6f100004)) ERROR: BadParameter(0x80001005)
/com.xxx.xxx A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 18964 (CodecLooper)
/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
/? A/DEBUG: Build fingerprint: 'HUAWEI/SHT-W09/HWSHT:8.0.0/HUAWEISHT-W09/128(C00):user/release-keys'
/? A/DEBUG: Revision: '0'
/? A/DEBUG: ABI: 'arm'
/? A/DEBUG: pid: 18804, tid: 18964, name: CodecLooper  >>> com.sumavision.android2507 <<<
/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
/? A/DEBUG:     r0 00000000  r1 00004a14  r2 00000006  r3 00000008
/? A/DEBUG:     r4 00004974  r5 00004a14  r6 bf302610  r7 0000010c
2/? A/DEBUG:     r8 bf3027f0  r9 c04af180  sl 7f000001  fp bf302690
/? A/DEBUG:     ip 00000000  sp bf302600  lr ec53b477  pc ec56c3ac  cpsr 200f0010
/? A/DEBUG: backtrace:
/? A/DEBUG:     #00 pc 0004b3ac  /system/lib/libc.so (tgkill+12)
/? A/DEBUG:     #01 pc 0001a473  /system/lib/libc.so (abort+54)
/? A/DEBUG:     #02 pc 0009858b  /system/lib/libstagefright.so (_ZN7android6ACodec13getPortFormatEjRNS_2spINS_8AMessageEEE+3446)
/? A/DEBUG:     #03 pc 00096d65  /system/lib/libstagefright.so (_ZN7android6ACodec14configureCodecEPKcRKNS_2spINS_8AMessageEEE+4372)
/? A/DEBUG:     #04 pc 0009ff93  /system/lib/libstagefright.so (_ZN7android6ACodec11LoadedState20onConfigureComponentERKNS_2spINS_8AMessageEEE+62)
/? A/DEBUG:     #05 pc 000a04a9  /system/lib/libstagefright.so (_ZN7android6ACodec11LoadedState17onMessageReceivedERKNS_2spINS_8AMessageEEE+140)
/? A/DEBUG:     #06 pc 0000fe43  /system/lib/libstagefright_foundation.so (_ZN7android25AHierarchicalStateMachine13handleMessageERKNS_2spINS_8AMessageEEE+74)
/? A/DEBUG:     #07 pc 0000fc5d  /system/lib/libstagefright_foundation.so (_ZN7android8AHandler14deliverMessageERKNS_2spINS_8AMessageEEE+24)
/? A/DEBUG:     #08 pc 00012203  /system/lib/libstagefright_foundation.so (_ZN7android8AMessage7deliverEv+62)
/? A/DEBUG:     #09 pc 0001092d  /system/lib/libstagefright_foundation.so (_ZN7android7ALooper4loopEv+480)
/? A/DEBUG:     #10 pc 0000d5d3  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+274)
/? A/DEBUG:     #11 pc 000486cf  /system/lib/libc.so (_ZL15__pthread_startPv+22)
/? A/DEBUG:     #12 pc 0001b02f  /system/lib/libc.so (__start_thread+32)

**Comment by CarGuo** [comment]
H265 的硬解码 主要和硬件相关

**Comment by YeGuli** [comment]
我在java层初始化mediacodec进行硬解码及渲染时并没有出现过崩溃的情况，初始化代码如下：
```java
String CODEC_MIME = "video/hevc";
ByteBuffer bf = ByteBuffer.allocateDirect(vps.length + sps.length + pps.length);
bf.put(vps);
bf.put(sps);
bf.put(pps);
MediaCodec codec = MediaCodec.createDecoderByType(CODEC_MIME);
MediaFormat fmt = MediaFormat.createVideoFormat(CODEC_MIME,getWidth(),getHeight());
fmt.setByteBuffer("csd-0", bf);
Surface sf = getSurface();
codec.configure(fmt, sf, null, 0);
codec.start();
```

**Comment by CarGuo** [comment]
你试过用 mediacodec 直接去解码那个流了么

**Comment by YeGuli** [comment]
嗯啊，我试过直接从指定udp端口读数据然后使用mediacodec去解是可以的，但是我写的解ts的代码解出来的音频有各种问题，所以想用咱们的播放器调用硬解去播放。或者是有没有这样的接口可以把视频流回调到java层让应用主动去调用mediacodec硬解之类的。

**Comment by YeGuli** [comment]
好的，我去看一下相关的issues。
之前解码的时候播放器默认用的是软解，但是软解hevc一直会有灰屏的现象；现在通过更改option换成硬解后就容易崩，偶尔不崩的时候效果挺棒的，也没有灰屏了。

**Comment by YeGuli** [comment]
我用支持了udp的脚本重新打了so，但是还是会崩溃，日志是一样的。。

**Comment by CarGuo** [comment]
这就不是很清楚了，有测试url吗

**Comment by YeGuli** [comment]
我是用vlc把h265的ts视频文件推送到测试机指定端口上的，我发给你一个h265的ts文件，可以不？

**Comment by xxdhh** [comment]
请问后续问题解决了吗
