### ISSUE TITLE
rtsp视频，播放大华的摄像头视频，播放了7.8分钟   画面卡主，正在加载小图标显示

### ISSUE THREAD

**Issue by Android-Boys** [CarGuo/GSYVideoPlayer#1755]
## 问题描述：

rtsp视频，播放大华的摄像头视频，播放了7.8分钟   画面卡主，正在加载小图标显示
## 问题机型/系统：

Android 8.0 TV

![https://i.loli.net/2019/01/12/5c395cdfe41ad.jpg](https://i.loli.net/2019/01/12/5c395cdfe41ad.jpg)

**Comment by CarGuo** [comment]
请看问题集锦，之前设置tcp

**Comment by Android-Boys** [comment]
看过了，已经加上去了         VideoOptionModel videoOptionMode07 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");

**Comment by Android-Boys** [comment]
但是还是不行

**Comment by CarGuo** [comment]
有测试url吗

**Comment by Android-Boys** [comment]
公安专网，没得测试url
