### ISSUE TITLE
有一个问题请教大佬

### ISSUE THREAD

**Issue by Android-Boys** [CarGuo/GSYVideoPlayer#1758]
楼主 你好，目前 我在做一个广告机。
 截图操作，返回一个Bitmap，然后ImageView加载进去。。

每15s 就会截图一次。imageView 加载下。。。这是目前的流程。。

广告机中途播放，总会崩溃。第二天来就发现  前天打开的广告机，退出了播放界面。。。我初步怀疑是截图的Bitmap  。 导致内存oom。

大佬觉得呢  截图那块  太频繁 会不会导致这样的问题

**Comment by CarGuo** [comment]
比如项目里，其实也有类似的，确实太频繁了会有问题。因为截图成bitmap的时候，开销的内存和当前视频的分辨率还有当前app消耗的内存状态有管，还是bitmap的recycle是否及时。

比如截图的时候可以尽量减低bitmap的质量，比如修改为565吗模式，尺寸也缩减下看看是否有效。
