### ISSUE TITLE
关于播放器的封面问题

### ISSUE THREAD

**Issue by Rabbit95** [CarGuo/GSYVideoPlayer#1759]
## 问题描述：

RecyclerView中播放器封面为黑色，尝试提前加载封面图片和使用本地文件，也无效。
播放器能正常播放，但是封面一直都是黑色的，要点击播放后，然后再点击另一个Item,使播放器处于停止播放的状态才会显示封面。

## 问题机型/系统：

模拟器 Android5.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Fragment 加载 RecyclerView ,所有Item播放器封面黑色，点击Item1播放器播放，点击Item2播放器播放，Item1播放暂停，封面正常，其他Item封面黑色

问题代码：
参考Dome,RecyclerView例子
Adapter中：
...
`ImageView  imageView = new ImageView(mContext);`
`imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);`

//ImageLoader是Gilde封装的图片加载类，确认工具没问题的
`ImageLoader.load(mContext,ImageURL,imageView);`

//设置封面
`GSYVideoOptionBuilder..setThumbImageView(imageView)....build(videoPlayer);`
...

不知道问题出在哪，请教各位大佬。

**Comment by CarGuo** [comment]
Demo貌似没复现问题啊

**Comment by Rabbit95** [comment]
> Demo貌似没复现问题啊

我也不知道问题在哪里...
代码都是大佬你Demo里的，我的Demo是Activity嵌套ViewPager,ViewPager加载Fragment,Fragment里有个RecyclerView,RecyclerView使用的Adapter是例子的，以及RecyclerItemBaseHolder和RecuclerItemNormalHolder也都是直接复用例子的，数据链接是使用写死的链接，播放器其他也都没有问题，就是第一次加载Fragment时视频封面出不来，非要视频加载一次后封面才会出来，在这个Demo中的另一个Activity却能正常显示封面。

**Comment by CarGuo** [comment]
这就只能你自己解决了

**Comment by a18008112518** [comment]
mThumbImageViewLayout.setVisibility(View.VISIBLE);

**Comment by PengliangC** [comment]
> mThumbImageViewLayout.setVisibility(View.VISIBLE);

可以，解决了，我也是首次不出现，getThumbImageViewLayout().setVisibility(View.VISIBLE)然后setThumbImageView就可以了

**Comment by Rabbit95** [comment]
> > mThumbImageViewLayout.setVisibility（View.VISIBLE）;
> 
> 可以，解决了，我也是首次不出现，getThumbImageViewLayout（）。setVisibility（View.VISIBLE）然后setThumbImageView就可以了

请问是哪个对象调用getThumbImageViewLayout()方法？

**Comment by Rabbit95** [comment]
> > mThumbImageViewLayout.setVisibility(View.VISIBLE);
> 
> 可以，解决了，我也是首次不出现，getThumbImageViewLayout().setVisibility(View.VISIBLE)然后setThumbImageView就可以了

解决了，万分感谢！
