### ISSUE TITLE
自定义问题

### ISSUE THREAD

**Issue by marscl** [CarGuo/GSYVideoPlayer#1766]
## 问题描述：

请问能否在loading之前，自定义添加动画

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

```

**Comment by CarGuo** [comment]
loading之前，自定义添加动画?

**Comment by marscl** [comment]
请问在刚开始播放后点全屏，会播放两次，出现两个声音。
