### ISSUE TITLE
请问在刚开始播放后点全屏，会播放两次，出现两个声音。

### ISSUE THREAD

**Issue by marscl** [CarGuo/GSYVideoPlayer#1767]
## 问题描述：

在刚开始播放后点全屏，会播放两次，出现两个声音。

## 问题机型/系统：

 真机 小米note2 Android7.0

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'

**Comment by CarGuo** [comment]
Demo怎么浮现

**Comment by marscl** [comment]
用的SampleControlVideo

**Comment by marscl** [comment]
//外部辅助的旋转，帮助全屏
        orientationUtils = new OrientationUtils(this, videoPlayer);
        //初始化不打开外部的旋转
        orientationUtils.setEnable(false);
        if (videoPlayer.getFullscreenButton() != null) {
            videoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (orientationUtils.getIsLand() != 1) {
                        //直接横屏
                        orientationUtils.resolveByClick();
                    }
                    //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                    videoPlayer.startWindowFullscreen(MainActivity.this,true, true);
                }
            });
        }

        new GSYVideoOptionBuilder()
                .setCacheWithPlay(true)
                .setVideoTitle("")
                .setIsTouchWiget(true)
                .setRotateViewAuto(false)
                .setLockLand(false)
                .setShowFullAnimation(false)//打开动画
                .setNeedLockFull(true)
                .setSeekRatio(1).build(videoPlayer);
      videoPlayer.getStartButton().setVisibility(View.GONE);

**Comment by marscl** [comment]
@Override
    public void onBackPressed() {
        if (orientationUtils != null) {
            orientationUtils.backToProtVideo();
        }
        if (GSYVideoManager.backFromWindowFull(this)) {
            return;
        }
        super.onBackPressed();
    }


    @Override
    protected void onPause() {
        super.onPause();
        videoPlayer.getCurrentPlayer().onVideoPause();
        isPause = true;
    }

    @Override
    protected void onResume() {
        super.onResume();
        videoPlayer.getCurrentPlayer().onVideoResume();
        isPause = false;
    }

  
    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (isPlay) {
            videoPlayer.getCurrentPlayer().release();
        }
        if (orientationUtils != null)
            orientationUtils.releaseListener();
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        //如果旋转了就全屏
        if (isPlay && !isPause) {
            videoPlayer.onConfigurationChanged(this, newConfig, orientationUtils, true, true);
        }
    }

**Comment by marscl** [comment]
在播放开始后点击全屏，按返回退出。多弄几次，就会出现了

**Comment by CarGuo** [comment]
demo中哪个页面

**Comment by marscl** [comment]
按照那个detailPlayer写的

**Comment by CarGuo** [comment]
如果demo无法复现我也没办法定位
