### ISSUE TITLE
播放录制视频无声音

### ISSUE THREAD

**Issue by findvoid** [CarGuo/GSYVideoPlayer#1769]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我用camera录制的视频播放没有声音,用系统的播放器播放有声音
## 问题机型/系统：

 真机 一加6 Android9
## GSY依赖版本

 compile 'com.shuyu:gsyVideoPlayer-java:6.0.2'
    compile 'com.shuyu:gsyVideoPlayer-ex_so:6.0.2'
    compile 'com.shuyu:GSYVideoPlayer-exo2:6.0.2'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后本地同样的文件会出现这个问题。

问题代码：(如果有)
mediaRecorder.setCamera(mCamera);
        mediaRecorder.setVideoSource(MediaRecorder.VideoSource.CAMERA);
        mediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);
        mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.H264);
        mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);

String source1 = Environment.getExternalStorageDirectory() + "/VCourseDir/"+"814cc839-f5d6-4a9e-a760-03430b84c204/"+"216e2325-954b-44c6-974c-7e5f1181d3cf/20190118_134403.mp4";
        videoPlayer.setUp(source1, true, "测试视频");

**Comment by CarGuo** [comment]
AMR 没支持解码，请使用AAC或切换到exoplayer内核

**Comment by findvoid** [comment]
多谢
