### ISSUE TITLE
进入全屏播放按钮不会消失

### ISSUE THREAD

**Issue by qq527743998** [CarGuo/GSYVideoPlayer#1773]
## 问题描述：
    recycleview 进入全屏，  播放按钮不消失  发生了这样的问题！
    recycleview 进入全屏，  偶尔视频在顶部只显示半截  发生了这样的问题！
    recycleview 进入全屏，  设置.setShowFullAnimation(false) 无法返回  发生了这样的问题！

## 问题机型/系统：

小米8 Android9.0

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:6.0.3'

## Demo中的复现步骤

Demo中的recycleview页面打开后不会出现这个问题。

问题代码：(如果有)
无
问题log（如果有）
无

**Comment by CarGuo** [comment]
demo不复现我也没办法定位
