### ISSUE TITLE
recyclerview列表播放视频时，我反复小幅度上下滑动列表 ，视频会卡住。

### ISSUE THREAD

**Issue by 172047459** [CarGuo/GSYVideoPlayer#1775]
## 问题描述：
recyclerview列表播放视频时，我反复小幅度上下滑动列表 ，视频会卡住。
## 问题机型/系统：
我手里的几个华为8.0都有这个问题
## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1
## Demo中的复现步骤
recyclerview列表播放视频时，我反复小幅度上下滑动列表 ，视频会卡住。我自己打了log，在反复小幅度上下滑动列表时，是没有走任何recyclerview的方法

**Comment by CarGuo** [comment]
你需要看是否触发了视频的哪些方法，我这边并没有复现这个问题

**Comment by 172047459** [comment]
你好  因为我是列表自动播放视频  recyclerview播放下一个视频时会将上一个视频 该item会调用videoPlayer.onVideoPause();   然后下一个视频会调用videoPlayer.getStartButton().performClick();    然后我在列表中每个item的视频都播放几秒之后快速的滑动下一个视频， 在这个过程中，有些视频就会卡住 。  我没有使用缓存到本地，所以这个是跟网络加载有关系吗，还是跟别的有关系

**Comment by Lollipopll** [comment]
> 你好 因为我是列表自动播放视频 recyclerview播放下一个视频时会将上一个视频 该item会调用videoPlayer.onVideoPause(); 然后下一个视频会调用videoPlayer.getStartButton().performClick(); 然后我在列表中每个item的视频都播放几秒之后快速的滑动下一个视频， 在这个过程中，有些视频就会卡住 。 我没有使用缓存到本地，所以这个是跟网络加载有关系吗，还是跟别的有关系
你好，有解决吗？我也遇到卡顿问题，看了下日志 跟video释放有关
