### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by hy20160705** [CarGuo/GSYVideoPlayer#1776]
大佬 这种问题一般是怎么导致的 readAt 476539 / 32768 => java.net.ProtocolException

**Comment by CarGuo** [comment]
解析出来的数据长度异常

**Comment by hy20160705** [comment]
那是服务器返回的数据有问题  还是我本地解析的时候有问题  是在MediaHttpConnect里面报的这个错

**Comment by hy20160705** [comment]
在pc上是可以正常播放的

**Comment by CarGuo** [comment]
如果可以请提供流

**Comment by hy20160705** [comment]
http://36.22.178.70:10099/oss/appfile/3e623b52ca4a4d5387a02ecfd2b77786.mp4 (不能正常播放)
http://36.22.178.70:10099/oss/appfile/98d62b1831f24b50bf82cef5111873de.mp4（可以正常播放）
初步估计是视屏格式的问题  当文件比较大的时候就不能播放了

**Comment by CarGuo** [comment]
容器协议都是mp4，要确定的是视频编码和音频编码格式，不能播放的一般都是这类问题。

**Comment by hy20160705** [comment]
https://blog.csdn.net/mabeijianxi/article/details/72983362
https://github.com/mabeijianxi/small-video-record

**Comment by CarGuo** [comment]
本地没问题，服务器有问题，那要不就是服务器的流提供有问题。要不就是压缩之类的导致包的完整解析有问题。

你可以切换到exo的内核模式，看看是否播放有问题
