### ISSUE TITLE
悬浮窗口适配的问题

### ISSUE THREAD

**Issue by wang869755676** [CarGuo/GSYVideoPlayer#1777]
floatutil 中的 utils 这块代码
 @RequiresApi(api = Build.VERSION_CODES.M)
    public static boolean hasPermission(Context context) {
        return Settings.canDrawOverlays(context);
    }
换成下面
     public static boolean hasPermission(Context context) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            return Settings.canDrawOverlays(context);
        }

        return true;
    }
不然的话，会在低版本中找不到报错

**Comment by CarGuo** [comment]
demo中的用的时候直接改就好了。@RequiresApi(api = Build.VERSION_CODES.M) 也是已经指明了
