### ISSUE TITLE
多任务 硬解码 部分视频无法播放

### ISSUE THREAD

**Issue by join-lich** [CarGuo/GSYVideoPlayer#1779]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

功能：模板化多任务，刷新视频，硬解码，
视频编码：mpeg4
大部分的设备使用没有问题，但是在部分设备上会出现
硬解码后的视频部分播放，关闭硬解码可以播放但是会卡顿
声音正常播放

## 问题机型/系统：

问题设备小米电视4c32寸

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.1'

## Demo中的复现步骤

问题代码：(如果有)

GSYVideoType.enableMediaCodec();
---
if (content.contains(".m3u8")) {
  videoPlayer.setUp(content, false, "");
} else if (content.startsWith("android.resource://")) {
  videoPlayer.setUp(content, false, "");
} else {
  videoPlayer.setUp(content, true, "");
}
---

list.add(new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-all-videos", 1));
list.add(new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec_mpeg4", 1));

**Comment by join-lich** [comment]
问题是这样啊
我举个栗子
多任务有俩视频
第一次进来 任务a 执行成功 视频音频，任务b 执行失败 只有音频
第二次进来可能出现 任务a 执行失败 只有音频 ，任务b 执行成功 视频音频
就是多任务不能同时硬解码这个问题之前遇到过么？

**Comment by CarGuo** [comment]
这个场面目前无法复现

**Comment by CarGuo** [comment]
可能是代理缓存服务挂了，这个目前还没遇到过，你可以在proxy_cache相关的地方看看
