### ISSUE TITLE
老哥 又来请教问题了。

### ISSUE THREAD

**Issue by Android-Boys** [CarGuo/GSYVideoPlayer#1780]
## 问题描述：
切换的时候偶尔会出现这样的黑屏，不清楚这种是处于播放的什么状态，或者说执行了changeUiTo 什么导致这个问题的产生。下面就图片
## 问题机型/系统：
Android TV 6.0

[https://imgchr.com/i/kZAhnA](图片)

**Comment by CarGuo** [comment]
你这图片我看不懂啊

**Comment by Android-Boys** [comment]
同时又几个播放器播放。然后播放了一段时间，大屏或者小屏 就会黑屏

**Comment by CarGuo** [comment]
这个得看log，有可能是内存不足或者其他情况导致停止播放了
