### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by yuye1124956** [CarGuo/GSYVideoPlayer#1781]
## 问题描述：
OrientationUtils传入的activity内存泄漏
## 问题机型/系统：
真机 小米note2 Android7.0

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

**Comment by CarGuo** [comment]
```if (orientationUtils != null)
            orientationUtils.releaseListener();```

页面销毁时调用了没？？

**Comment by yuye1124956** [comment]
是我没调用 调用后已无此bug 感谢

**Comment by AttackPangHu** [comment]
为什么我调用了还是会内存泄漏？
