### ISSUE TITLE
你好, 大神, 进度拖拽时, 对话框上显示的进度比如是5分23秒, 但是我松手后, 时间往前跳2秒左右, 显示5分21秒, 再重新开始播, 我自定义时, 可以控制吗?

### ISSUE THREAD

**Issue by wqc910605** [CarGuo/GSYVideoPlayer#1786]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
这个寻找关键帧，你可以试试问题集锦中的方式
