### ISSUE TITLE
视频切换清晰度的问题？

### ISSUE THREAD

**Issue by clark0704** [CarGuo/GSYVideoPlayer#179]
能在视频全屏的时候处理清晰度吗？意思是在startwindowFullScreen方法中加入切换视频源的逻辑和UI，谢谢。

**Comment by CarGuo** [comment]
目前没有安排，后面会在加上吧

**Comment by clark0704** [comment]
我这边比较着急啊，大神。能写个demo吗？

**Comment by CarGuo** [comment]
demo已更新，可参考DetailMoreTypeActivity

**Comment by wangrunxiang** [comment]
@CarGuo 这个demo只是一个视频多个清晰度，如果是多个视频，每个视频多个清晰度应该怎么写？
