### ISSUE TITLE
Recyclerview列表item多种类型时,视频item播放卡顿

### ISSUE THREAD

**Issue by liuchenc** [CarGuo/GSYVideoPlayer#1791]
当recyclerview的item存在多种类型时,比如单张图片加文字,大图加文字,多图,纯文本,视频.当iten为视频时播放卡顿,类似线程阻塞的感觉.整个列表都是纯视频的不存在这种情况,播放非常流畅.就是多种类型穿插的时候有这种现象
测试手机华为LDN-AL20 系统8.0.0  小米,vivo也有此情况
 GSY依赖版本:implementation 'com.shuyu:GSYVideoPlayer:6.0.0-beta'

**Comment by CarGuo** [comment]
个人觉得这个问题和库没关系
