### ISSUE TITLE
横竖屏切换全屏问题

### ISSUE THREAD

**Issue by NerdAnonymous** [CarGuo/GSYVideoPlayer#1792]
## 问题描述：

在开启自动跟随旋转的条件下，全屏横屏播放视频时，HOME让应用到后台，然后把手机在竖屏状态下使劲摇两下，回到应用，这时候视频还是全屏播放，不过变成了全屏竖屏，查看原因是因为作者在所有demo中的onPause方法中把isPause标记位设置成true，然后从后台进入前台时，onResume的回调在onConfigurationChanged回调之后执行，因此当走到onConfigurationChanged的isPlay && !isPause这个判断时，isPause标记位还是true，导致danmakuVideoPlayer.onConfigurationChanged不走，导致视频变成了全屏竖屏播放，我是直接临时去除了标记位解决，不知道大佬有什么好的解决方案没。

## 问题机型/系统：

与机型无关

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的DanmkuVideoActivity页面打开会出现这个问题，其他的界面应该也有这个问题。

**Comment by NerdAnonymous** [comment]
标记位取消后，会出现进入恢复状态黑屏问题.

**Comment by CarGuo** [comment]
不是很理解场景
