### ISSUE TITLE
播放网络视频MP4（时长大于一小时）和 播放下载后的视频 加载过长 20秒以上

### ISSUE THREAD

**Issue by billytoe** [CarGuo/GSYVideoPlayer#1793]
## 问题描述：

播放网络视频MP4（时长大于一小时）和 播放下载后的视频 加载过长 20秒以上，时长短的视频 加载时间还可以，您问 我应该从什么方面解决？

## 问题机型/系统：

 真机 小米5 Android6.0 其他机型现象相同

问题代码：(如果有)
```
视频 url 地址  http://vodsd.huidengzhiguang.com/va/2018/L18027_2018xinjiapoxiliejiangzuodailingshixiujingxin.mp4
```

**Comment by Kuanghusing** [comment]
try
`IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT)`

**Comment by CarGuo** [comment]
try
IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT)

**Comment by billytoe** [comment]
嗯嗯 谢谢， 我们试了 确实 效率高了，但 对码流稍微 大点的，用手机自带的浏览器可以流畅播放 ，但放到咱们的播放器中 还是 很快 声画不对位了，还有什么地方 可以 优化吗？   视频地址 是http://od.huisheng.wenhuajiaoliu.net/%E8%A7%82%E6%83%B3%E5%8A%A8%E7%94%BB/%E8%AF%AD%E5%8A%A0%E6%8C%81%E7%9A%84%E4%BF%AE%E6%B3%95181025.mp4

**Comment by CarGuo** [comment]
可以看问题集锦，设置合适的丢帧数。
