### ISSUE TITLE
每次播放时都如下设置播放器模式  设置 EXO模式时 video-cache怎么找不到缓存文件

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#1797]
版本 6.0.3
每次播放时都如下设置播放器模式  设置 EXO模式时播放m3u8   video-cache怎么找不到缓存文件
if(strUrl.endsWith("concat")){
            //PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
            //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
            PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
           // CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
            CacheFactory.setCacheManager(ProxyCacheManager.class);//代理缓存模式，支持所有模式，不支持m3u8等
        }
        else {
            PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
            //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
            //PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
            CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
        }

**Comment by CarGuo** [comment]
找不到的意思是？？？exo在缓存时是分块缓存的，比如一个文件会分拆成很多个小文件缓存，并且这个文件是无法拿出来直接播放的。

**Comment by yang0000meng** [comment]
默认缓存文件 不应该存储到 app 的video-cache 文件夹下面吗？打开文件夹 下面一个文件都没有

**Comment by yang0000meng** [comment]
或者我怎么知道缓存了m3u8， 哪里能获取进度或地址。

**Comment by CarGuo** [comment]
exo存在不是存在在这里的，exo的缓存是在。

我记得判断是位置是 getGSYVideoManager().isCacheFile()

ExoSourceManager 的 resolveCacheState 判断的。缓存的位置应该是在 data/data 如图位置下

![5c60f011e4b012ff06876fbc](https://user-images.githubusercontent.com/10770362/52545484-da574a00-2df2-11e9-853a-3351ea55927a.png)

**Comment by yang0000meng** [comment]
getGSYVideoManager().isCacheFile() 显示false 
m3u8缓存如何才调用呢。 已传值setCacheWithPlay(cache) cache==true

在getMediaSource如下代码 调用 getGSYVideoManager().isCacheFile()
 if(strUrl.toLowerCase().indexOf(".concat")>-1){
            //PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
            //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
            PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
           // CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
            CacheFactory.setCacheManager(ProxyCacheManager.class);//代理缓存模式，支持所有模式，不支持m3u8等
        }
        else {
            PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
            //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
            //PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
            CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
            ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
                @Override
                public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                    if(videoPlayer.getGSYVideoManager().isCacheFile()){

                        String str="1";
                    }
                    else {
                        String str2 = "2";
                    }
                    return  null;
                }
            });
        }

**Comment by CarGuo** [comment]
你可以通过看看 data data 包名 路径下是否有生成如图的文件，我这边demo测试正常

**Comment by yang0000meng** [comment]
配置我没写错，那就关闭了，谢谢回复。
