### ISSUE TITLE
ExoPlayerCacheManager  默认 User-Agent 可否移除

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#1798]
ExoPlayerCacheManager  默认 User-Agent 可否移除
传入新的  User-Agent  ExoPlayerCacheManager   不覆盖，不更新User-Agent 

默认 ：User-Agent: ExoSourceManager/2.9.1.0216 (Linux;Android 8.1.0) ExoPlayerLib/2.9.3

**Comment by CarGuo** [comment]
应该是在  ExoSourceManager 的 Util.getUserAgent


```

    private DataSource.Factory getHttpDataSourceFactory(Context context, boolean preview) {
        DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent(context,
                TAG), preview ? null : new DefaultBandwidthMeter());
        if (mMapHeadData != null && mMapHeadData.size() > 0) {
            for (Map.Entry<String, String> header : mMapHeadData.entrySet()) {
                dataSourceFactory.getDefaultRequestProperties().set(header.getKey(), header.getValue());
            }
        }
        return dataSourceFactory;
    }
```

**Comment by yang0000meng** [comment]
调试下，还是不覆盖 ，传入值 User-Agent 不覆盖原来的
传入值如下图：
https://pan.baidu.com/s/1mwQ9PeC8iQ0DgJhEtl3kig

这个是访问结果
GET http://vodpc-bj.wasu.cn/pcsan14/pc/news/2017-12/23/2017122310013367679bcbee3.mp4?auth_key=19ac1de047c605aabc7a68e4f3526cb6-1549871401-69da7158ebaaab73cc8bc09c48fd293f-&sk=511297f5959c5ee56ce6d06f12ed6d56 HTTP/1.1
Referer: https://www.wasu.cn/Play/show/id/5007724
User-Agent: ExoSourceManager/2.9.1.0216 (Linux;Android 8.1.0) ExoPlayerLib/2.9.3

条件：
调用的是Exo2PlayerManager
videoPlayer.getGSYVideoManager().isCacheFile()) 显示 false

**Comment by CarGuo** [comment]
你需要自定义source或者自定义exomanager

自定义source 
```
    /*ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                return null;
            }
        });*/
```

**Comment by yang0000meng** [comment]
官方demo 
DetailExoListPlayer 修改   
//使用 exo 的 CacheDataSourceFactory 实现
        detailPlayer.setExoCache(false); ==true


修改 GSYExo2PlayerView
 protected boolean setUp(List<GSYVideoModel> url, int position, File cachePath, Map<String, String> mapHeadData, boolean changeState) {
     。。。。。。

        //不支持边播边缓存
        boolean set = setUp(gsyVideoModel.getUrl(), false, cachePath, gsyVideoModel.getTitle(), changeState);
修改 
 boolean set = setUp(gsyVideoModel.getUrl(), true, cachePath, gsyVideoModel.getTitle(), changeState);

这样是否就支持 m3u8缓存了呢

**Comment by CarGuo** [comment]
我觉得你还是大概看下源码吧
