### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by PreviousTlx** [CarGuo/GSYVideoPlayer#1799]
内存泄漏问题描述：

跑demo的时候，发生了这样的问题，demo的版本是6.0.3！

 问题机型/系统：

 真机 华为FlA-AL10 Android8.0

 GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

 Demo中的复现步骤

Demo中的列表页面播放经常性会出现这个问题。
[](url)
![device-2019-02-13-110256](https://user-images.githubusercontent.com/18514235/52683901-52eb1180-2f7f-11e9-8aa0-b80a443ce863.png)

**Comment by CarGuo** [comment]
泄漏的是？

**Comment by PreviousTlx** [comment]
在列表界面点击返回的时候，leak会有泄漏的消息反馈。
![device-2019-02-13-114758](https://user-images.githubusercontent.com/18514235/52685586-3e117c80-2f85-11e9-8838-97518e2d643c.png)

**Comment by CarGuo** [comment]
我试了下这边没出现类似的泄漏提示
