### ISSUE TITLE
自定义控件于播放界面,如何设置监听

### ISSUE THREAD

**Issue by ByHSH** [CarGuo/GSYVideoPlayer#180]
想在全屏播放的时候选集,我在activity里面可以拿到全屏时的控件,但是设置在activity里面的监听事件onclick里面的方法没有走,请问我要怎么做才行呢?

**Comment by CarGuo** [comment]
全屏是切换了一个播放页面实现全屏。所以你需要把一些操作在startwindowFullScreen的时候同步设置给全屏播放页面，参考stardradGSYVideoPlayer中的startwindowFullScreen逻辑处理

**Comment by ByHSH** [comment]
解决了,谢谢郭大大
