### ISSUE TITLE
无控制页面，无法设置自动播放，还有就是加载的时候黑屏，想实现加载的时候显示封面

### ISSUE THREAD

**Issue by dujingxue1997** [CarGuo/GSYVideoPlayer#1800]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

无控制页面，无法设置自动播放，加载的时候黑屏

## 问题机型/系统：

三星S7

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤
EmptyControlVideo试过

**Comment by dujingxue1997** [comment]
@Override
    protected void changeUiToPreparingShow() {
        super.changeUiToPreparingShow();
        setViewShowState(mThumbImageViewLayout,VISIBLE);
    }

封面的问题，看了源码之后解决了。 就是无控制页面的自动播放，没有看到怎么弄

**Comment by CarGuo** [comment]
自动播放的意思是？

**Comment by dujingxue1997** [comment]
我用了钉某人的viewpagerLayoutManager，滑到ITEM的时候自动播放，我设置startPlayLogic也不会播放。

我用以下代码代替 但是会有 播放按钮

public class EmptyControlVideo extends StandardGSYVideoPlayer {
    private ImageView play;
    private RelativeLayout thumb;


    public EmptyControlVideo(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

    public EmptyControlVideo(Context context) {
        super(context);

    }

    public EmptyControlVideo(Context context, AttributeSet attrs) {
        super(context, attrs);
    }



    @Override
    public int getLayoutId() {
        return R.layout.empty_control_video;
    }

    @Override
    protected void init(Context context) {
        super.init(context);
        play = findViewById(R.id.start);
        play.setVisibility(INVISIBLE);
        thumb = findViewById(R.id.thumb);
        //thumb.setVisibility(VISIBLE);

    }


    @Override
    protected void touchSurfaceMoveFullLogic(float absDeltaX, float absDeltaY) {
        super.touchSurfaceMoveFullLogic(absDeltaX, absDeltaY);
        //不给触摸快进，如果需要，屏蔽下方代码即可
        mChangePosition = false;

        //不给触摸音量，如果需要，屏蔽下方代码即可
        mChangeVolume = false;

        //不给触摸亮度，如果需要，屏蔽下方代码即可
        mBrightness = false;
        play.setVisibility(INVISIBLE);


    }

    @Override
    protected void changeUiToError() {
        super.changeUiToError();
        setViewShowState(mThumbImageViewLayout,VISIBLE);
    }

    @Override
    protected void changeUiToPreparingShow() {
        super.changeUiToPreparingShow();
        setViewShowState(mThumbImageViewLayout,VISIBLE);
    }

    @Override
    protected void touchDoubleUp() {
           super.touchDoubleUp();
        //不需要双击暂停
    }

    public void autoPlay() {
        play.performClick();
    }


    @Override
    protected void touchSurfaceUp() {
        super.touchSurfaceUp();
        play.setVisibility(INVISIBLE);

    }

**Comment by CarGuo** [comment]
并不是很理解

**Comment by dujingxue1997** [comment]
public void autoPlay() {
    play.performClick();
}

外部调用 这个方法，才实现滑到ITEM播放视频，我想知道设置这个startPlayLogic为啥没有用

**Comment by CarGuo** [comment]
额····貌似不会啊，你可以看demo的滑动自动播放
