### ISSUE TITLE
局域网视频缓冲时间过长是什么原因呢、

### ISSUE THREAD

**Issue by luyun181** [CarGuo/GSYVideoPlayer#1804]
## 问题描述：

18M的视频缓冲时间在20秒以上

## 问题机型/系统：

 真机 小米x5   华为 荣耀10

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`
对视频编码有什么要求吗？

**Comment by CarGuo** [comment]
最大的可能是找不到关键帧。或者看看关闭缓存试试。

或者你可以切换到 PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式 看看，

**Comment by luyun181** [comment]
不是所有的都不行，我用demo的视频下载下来就开秒开

**Comment by luyun181** [comment]
关了缓存，加上exo 模式，开秒开了

**Comment by CarGuo** [comment]
因为视频存在关键帧问题，默认ijk是使用ffmpeg的ffplay去播放的，播放时会需要寻找关键帧

**Comment by wjj201411** [comment]
> 最大的可能是找不到关键帧。或者看看关闭缓存试试。
> 
> 或者你可以切换到 PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式 看看，

使用PlayerFactory.setPlayManager(Exo2PlayerManager.class);这种方式确实可以秒开，但是声音缺变的很诡异，有声响
