### ISSUE TITLE
播放视频的时候，视频的画面不会动，只听到视频的音乐

### ISSUE THREAD

**Issue by combing520** [CarGuo/GSYVideoPlayer#1805]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
播放视频的时候，视频的画面不会动，只听到视频的音乐 ；使用系统自带的视频播放器是能看到视频播放中有图像的切换

XXXX发生了这样的问题！
播放视频，视频的地址为：
http://liverecord.ccwb.cn/qukan/user/1546852074723973/upload/rei.mp4

## 问题机型/系统：

例如 真机 小米note2 Android7.0
真机 Vivo x9  Android 7.0  红米 4x  Android 7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
## Demo中的复现步骤
使用 Demo中的普通视频播放； 替换 对应的 播放地址为 上述地址
Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
api "com.shuyu:gsyVideoPlayer-java:$gsyVideoVersion"
    api "com.shuyu:GSYVideoPlayer-exo2:$gsyVideoVersion"
    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    api "com.shuyu:gsyVideoPlayer-ex_so:$gsyVideoVersion"


用这几个依赖，这个视频的编码不是 h264等，是mpeg的，要用 ex_so

**Comment by combing520** [comment]
意思是 我去掉：
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'


然后使用以下三个一起替代上面的?
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
//是否需要ExoPlayer模式
implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
//更多ijk的编码支持
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

**Comment by CarGuo** [comment]
你原本依赖是怎么样的？

**Comment by combing520** [comment]
我原来的依赖 是 ：  implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

**Comment by combing520** [comment]
如果将原来的 ： implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'  

替换成以下三个  
mplementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
//是否需要ExoPlayer模式
implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
//更多ijk的编码支持
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

编译的时候会出现报错 ：
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: java.lang.IllegalStateException: Dex archives: setting .DEX extension only for .CLASS files

**Comment by CarGuo** [comment]
仅仅

 implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3' 是不行的，因为没有so文件

最少依赖

mplementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

**Comment by combing520** [comment]
好的； 我试试；谢谢大神

**Comment by combing520** [comment]
可以了的； 大神 可以 close 了； 打扰大神了；谢谢大神
