### ISSUE TITLE
6.0.3、6.0.2编译错误 6.0.1正常

### ISSUE THREAD

**Issue by 50kg** [CarGuo/GSYVideoPlayer#1806]
从6.0.3提示 min-sdk-version 最低26，我的是19 。6.0.1是没问题的

AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.\u003cclinit\u003e:()V: invalid opcode ba - invokedynamic requires --min-sdk-version \u003e\u003d 26 (currently 19)","sources":[{}]}
Task :app:transformClassesWithDexForBaseDebug FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:transformClassesWithDexForBaseDebug'.
 com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted

**Comment by CarGuo** [comment]
demo编译是否正常？？

**Comment by justziyang** [comment]
我也遇到了~AS版本 3.2.1~编译不过来 R文件 一直报红色Cannot resolve symbol 'R'

**Comment by CarGuo** [comment]
奇怪，我这边demo挺正常的

**Comment by 50kg** [comment]
@CarGuo 找到原因了，如果把demo改成JavaVersion.VERSION_1_7 也会出现同样的错误，必须是1.8才行吗？项目里有的库不支持1.8 尴尬了

**Comment by CarGuo** [comment]
@50kg https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/UPDATE_VERSION.md  6.0.1 到最新我觉得其中影响的应该是exoplayer，可以试试只依赖java和so，不依赖exoplayer
```
  api "com.shuyu:gsyVideoPlayer-java:$gsyVideoVersion"
  
   api "com.shuyu:gsyVideoPlayer-armv5:$gsyVideoVersion"
   api "com.shuyu:gsyVideoPlayer-armv7a:$gsyVideoVersion"
```

**Comment by 50kg** [comment]
找到解决办法了，1：JavaVersion.VERSION_1_8 改成1.8，2：gradle 从3.2.1降级到3.1.4 
另外gradle 大于3.2的话参考下面issues xiaxiayige 老哥的解决办法
https://github.com/BuglyDevTeam/Bugly-Android-Demo/issues/67

另外感谢作者 谢谢
