### ISSUE TITLE
自定义布局

### ISSUE THREAD

**Issue by qhs107** [CarGuo/GSYVideoPlayer#1807]
请问自定义布局getLayoutId     切换横竖屏的时候    这两个view生命周期会有什么变化

我目前的需求是    横屏状态需要展示一个viewpager但是竖屏状态并不需要

然而第一次给viewpager适配上数据以后     我重新切换一下横竖屏   发现数据就消失了

请问这种情况怎么办？

（如果我重新适配数据的话    viewpager并不会显示数据了     但是奇怪的是我调用两次就可以出现数据    但是有一些问题）

**Comment by CarGuo** [comment]
不是很理解场景，

但是

第一，首先你是否参考配置了 AndroidManifest ？

第二，数据需要在竖屏设置好，在横屏传递过去，参考源码，因为全屏页面每次都是重新构建的

- cloneParams:

https://github.com/CarGuo/GSYVideoPlayer/blob/234e1579955cd308e36ee58ff144a01bb318e28d/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/StandardGSYVideoPlayer.java#L334

- startWindowFullscreen:

https://github.com/CarGuo/GSYVideoPlayer/blob/234e1579955cd308e36ee58ff144a01bb318e28d/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/StandardGSYVideoPlayer.java#L358


如果需要外部获取，可以通过  player.getCurrentPlayer().xxxxx 去获取

**Comment by qhs107** [comment]
![hg95sa_flks5 u8 h 142zi](https://user-images.githubusercontent.com/23162038/52830157-8b6b2680-310a-11e9-8ba1-91dfa90229a0.png)

**Comment by qhs107** [comment]
UI图是这样的    右边就是我所说的viewpager     但是这个viewpager竖屏时候并不需要展示    请问建议怎么实现比较好呢

**Comment by qhs107** [comment]
还有就是如果竖屏传递横屏的时候    cloneParams   startWindowFullscreen都需要设置还是设置一个就好，有什么区别吗     麻烦大神简介一下

**Comment by qhs107** [comment]
@Override
    protected void cloneParams(GSYBaseVideoPlayer from, GSYBaseVideoPlayer to) {
        super.cloneParams(from, to);
        NextDetailVideo sf = (NextDetailVideo) from;
        NextDetailVideo st = (NextDetailVideo) to;
        st.mPlayPosition = sf.mPlayPosition;
        st.mUriList = sf.mUriList;
        st.mOnItemClickListener = sf.mOnItemClickListener;
       sf.magic_indicator_videoland=st.magic_indicator_videoland;
        sf.viewpager_videoland=st.viewpager_videoland;
        st.viewpager_videoland.setAdapter(sf.viewpager_videoland.getAdapter());


我现在的思路是横竖屏都设置一个viewpager但是发现横屏的viewpager传递不过去数据

**Comment by CarGuo** [comment]
cloneParams 传递数据
startWindowFullscreen 设置状态

**Comment by qhs107** [comment]
请问横屏切换回竖屏的时候，横屏的View会完全销毁吗

**Comment by CarGuo** [comment]
是的，横屏的view每次都是新创建的，退出时销毁。
所以状态都是通过cloneParams同步的。
