### ISSUE TITLE
播放Amazon返回mp3数据失真, log里打印E/IJKMEDIA: Header missing

### ISSUE THREAD

**Issue by ZhJYe** [CarGuo/GSYVideoPlayer#1809]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
从avs返回的mp3流保存在本地文件并播放

## 问题机型/系统：
所有机型和系统

## GSY依赖版本

compile 'com.shuyu:GSYVideoPlayer:6.0.3'
然后自己复制你的demo重的.so到我项目的libs目录

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

02-16 16:46:42.634 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_stop()
    ijkmp_stop()=0
    IjkMediaPlayer_reset
    IjkMediaPlayer_release
    ijkmp_set_android_surface(surface=0x0)
02-16 16:46:42.634 10297-10678/com.linkplay.alexaforbt D/IJKMEDIA: message_loop exit
02-16 16:46:42.634 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: ffpipeline_set_surface()
02-16 16:46:42.634 10297-10678/com.linkplay.alexaforbt I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [10678]
02-16 16:46:42.634 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
    ijkmp_shutdown_l()
02-16 16:46:42.638 10297-10683/com.linkplay.alexaforbt I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [10683]
02-16 16:46:42.644 10297-10679/com.linkplay.alexaforbt I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [10679]
02-16 16:46:42.786 10297-10680/com.linkplay.alexaforbt I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [10680]
02-16 16:46:42.798 10297-10682/com.linkplay.alexaforbt I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [10682]
02-16 16:46:42.800 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_shutdown_l()=void
    IjkMediaPlayer_native_setup
02-16 16:46:42.800 10297-10393/com.linkplay.alexaforbt I/IJKMEDIA: av_version_info: ff3.4--ijk0.8.7--20180103--001
    ijk_version_info: k0.8.8
02-16 16:46:42.800 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: ffpipeline_create_from_android()
    ijkmp_set_inject_opaque(0x2c96)
    ijkmp_set_inject_opaque()=void
    ijkmp_set_ijkio_inject_opaque(0x2c96)
02-16 16:46:42.802 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
    ijkmp_android_set_mediacodec_select_callback()
    ffpipeline_set_mediacodec_select_callback
    ijkmp_android_set_mediacodec_select_callback()=void
02-16 16:46:42.803 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_dec_ref(): ref=0
    ijkmp_shutdown_l()
    ijkmp_shutdown_l()=void
02-16 16:46:42.813 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
02-16 16:46:42.813 10297-10393/com.linkplay.alexaforbt V/IJKMEDIA: setDataSource: path /data/user/0/com.linkplay.alexaforbt/cache/1550306802807.mp3
02-16 16:46:42.813 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_set_data_source(url="/data/user/0/com.linkplay.alexaforbt/cache/1550306802807.mp3")
    ijkmp_set_data_source(url="/data/user/0/com.linkplay.alexaforbt/cache/1550306802807.mp3")=0
    IjkMediaPlayer_prepareAsync
    ijkmp_prepare_async()
02-16 16:46:42.814 10297-10393/com.linkplay.alexaforbt I/IJKMEDIA: ===== versions =====
    ijkplayer    : k0.8.8
    FFmpeg       : ff3.4--ijk0.8.7--20180103--001
    libavutil    : 55.78.100
    libavcodec   : 57.107.100
    libavformat  : 57.83.100
    libswscale   : 4.8.100
    libswresample: 2.9.100
    ===== options =====
    format-opts : ijkapplication               = 494913310080
    format-opts : ijkiomanager                 = 494954398336
    ===================
02-16 16:46:42.815 10297-10393/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_prepare_async()=0
02-16 16:46:42.815 10297-10837/com.linkplay.alexaforbt I/IJKMEDIA: SDL_RunThread: [10837] ff_vout
02-16 16:46:42.815 10297-10838/com.linkplay.alexaforbt I/IJKMEDIA: SDL_RunThread: [10838] ff_read
02-16 16:46:42.815 10297-10836/com.linkplay.alexaforbt I/IJKMEDIA: SDL_RunThread: [10836] ff_msg_loop
02-16 16:46:42.816 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: message_loop
02-16 16:46:42.817 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: FFP_MSG_FLUSH:
02-16 16:46:42.821 10297-10838/com.linkplay.alexaforbt W/IJKMEDIA: Format mp3 detected only with low score of 25, misdetection possible!
02-16 16:46:42.821 10297-10838/com.linkplay.alexaforbt E/IJKMEDIA: Option ijkapplication not found.
02-16 16:46:42.822 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: FFP_MSG_OPEN_INPUT:
02-16 16:46:42.822 10297-10838/com.linkplay.alexaforbt W/IJKMEDIA: Estimating duration from bitrate, this may be inaccurate
02-16 16:46:42.822 10297-10838/com.linkplay.alexaforbt I/IJKMEDIA: max_frame_duration: 10.000
    Input #0, mp3, from '/data/user/0/com.linkplay.alexaforbt/cache/1550306802807.mp3':
      Metadata:
02-16 16:46:42.823 10297-10838/com.linkplay.alexaforbt I/IJKMEDIA:     encoder         : 
    Lavf57.71.100
        data            : 
    [{"time":0,"type":"sentence","start":299,"end":310,"value":"In baseball"},{"time":6,"type":"word","start":299,"end":301,"value":"In"},{"time":6,"type":"viseme","value":"i"},{"time":68,"type":"viseme","value":"t"},{"time":119,"type":"word","start":302,"end
      Duration: 
    00:00:10.79
    , start: 
    0.000000
    , bitrate: 
    48 kb/s
        Stream #0:0
    : Audio: mp3, 24000 Hz, mono, s16p, 48 kb/s
    SDL_Android_AudioTrack: CHANNEL_OUT_MONO
02-16 16:46:42.824 10297-10838/com.linkplay.alexaforbt I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
02-16 16:46:42.824 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: FFP_MSG_FIND_STREAM_INFO:
02-16 16:46:42.838 10297-10838/com.linkplay.alexaforbt I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
    audio_session_id = 2081
    AudioCodec: avcodec, mp3
02-16 16:46:42.838 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: FFP_MSG_COMPONENT_OPEN:
02-16 16:46:42.839 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
    FFP_MSG_PREPARED:
02-16 16:46:42.839 10297-10842/com.linkplay.alexaforbt I/IJKMEDIA: SDL_RunThread: [10842] ff_audio_dec
02-16 16:46:42.839 10297-10841/com.linkplay.alexaforbt I/IJKMEDIA: SDL_RunThread: [10841] ff_aout_android
02-16 16:46:42.840 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:42.843 10297-10297/com.linkplay.alexaforbt D/IJKMEDIA: IjkMediaPlayer_start
    ijkmp_start()
    ijkmp_start()=0
02-16 16:46:42.843 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
02-16 16:46:42.853 10297-10841/com.linkplay.alexaforbt D/IJKMEDIA: avcodec/Audio: first frame decoded
02-16 16:46:42.853 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: FFP_MSG_AUDIO_DECODED_START:
02-16 16:46:42.854 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: FFP_MSG_AUDIO_RENDERING_START:
02-16 16:46:42.855 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:42.855 10297-10842/com.linkplay.alexaforbt I/IJKMEDIA: overread, skip -5 enddists: -3 -3
02-16 16:46:42.855 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:42.857 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:43.236 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:43.436 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:43.636 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:43.834 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:43.835 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:44.037 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:44.234 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:44.437 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:44.438 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:44.637 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:44.836 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:45.037 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:45.038 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:45.236 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:45.436 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:45.636 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:45.636 10297-10842/com.linkplay.alexaforbt I/IJKMEDIA: overread, skip -7 enddists: -1 -1
02-16 16:46:45.637 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:45.637 10297-10842/com.linkplay.alexaforbt I/IJKMEDIA: overread, skip -6 enddists: -4 -4
02-16 16:46:45.840 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:46.040 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:46.236 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:46.238 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:46.438 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:46.638 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:46.639 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:46.841 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:47.037 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:47.237 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:47.238 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:47.439 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:47.636 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:47.838 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:47.840 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:48.037 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:48.240 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:48.240 10297-10842/com.linkplay.alexaforbt I/IJKMEDIA: overread, skip -9 enddists: -2 -2
02-16 16:46:48.241 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:48.439 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:48.639 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:48.839 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:48.840 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:49.040 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:49.239 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:49.439 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:49.440 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:49.641 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:49.839 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:49.841 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:50.037 10297-10842/com.linkplay.alexaforbt E/IJKMEDIA: Header missing
02-16 16:46:50.659 10297-10838/com.linkplay.alexaforbt I/IJKMEDIA: ffp_toggle_buffering: completed: OK
02-16 16:46:50.660 10297-10836/com.linkplay.alexaforbt D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
    FFP_MSG_COMPLETED:
02-16 16:46:50.773 10297-10838/com.linkplay.alexaforbt I/IJKMEDIA: ffp_toggle_buffering: eof

**Comment by CarGuo** [comment]
不是很理解你的问题，demo如何复现

**Comment by ZhJYe** [comment]
[音频文件.zip](https://github.com/CarGuo/GSYVideoPlayer/files/2873900/default.zip)
你播下这个mp3的音频文件看看

**Comment by ZhJYe** [comment]
我用的是ijk模式播放的

**Comment by CarGuo** [comment]
本地播放？？

**Comment by ZhJYe** [comment]
对的, 播放本地文件

**Comment by CarGuo** [comment]
试试 `PlayerFactory.setPlayManager(Exo2PlayerManager.class);` 模式，ijk内核在用ffmepg解析的时候有兼容不完整问题

**Comment by ZhJYe** [comment]
好的, 谢谢

**Comment by ZhJYe** [comment]
我只播放纯音频的话需要怎么用这个库呢

**Comment by CarGuo** [comment]
只播放纯音频用这个库其实没太大必要，你直接用mediaplyer去播放不是更好更轻么

**Comment by ZhJYe** [comment]
mediaplayer解析某些直播流的时候太慢了, 有时候需要一分多钟

**Comment by ZhJYe** [comment]
我现在用这个库是直接new一个ijk的播放器实例, 如果我想切换内核的话, 应该怎么用呢
            mIjkContentPlayer = new IjkMediaPlayer();
            mIjkContentPlayer.setWakeMode(mContext, PowerManager.PARTIAL_WAKE_LOCK);
            mIjkContentPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
            mIjkContentPlayer.setOnCompletionListener(mIjkMediaCompletionListener);
            mIjkContentPlayer.setOnPreparedListener(mIjkMediaPreparedListener);
            mIjkContentPlayer.setOnErrorListener(mIjkMediaErrorListener);
            mIjkContentPlayer.setOnInfoListener(mIjkMediaInfoListener);
            mIjkContentPlayer.setOnSeekCompleteListener(mIjkSeekCompleteListener);

**Comment by CarGuo** [comment]
你可以看readme和wiki

**Comment by ZhJYe** [comment]
好的, 谢谢
