### ISSUE TITLE
获取视频关键帧或者每秒的bitmap等等

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [CarGuo/GSYVideoPlayer#181]
看见demo中有本地视频小图预览功能
请问如何获取本地视频x秒的缩略图或者视频x秒-x秒的关键帧呢
现在项目有个需求像微信小视频那样现实分享的视频时间10s以内，底部和微信一样显示当前选中的10s的视频的缩略图
我利用ffmpeg获取视频xx秒的视频有点慢大概需要0.4秒一张
ffmpeg -ss 00:04:08 -i Mononoke.mp4 -frames：v 1 out1.jpg
利用MediaMetadataRetriever获取xx秒的图片大概也需要0.5s一张，效率太差了
请问大神如何快速的获取本地视频x秒的缩略图，Thanks
[demoGif](http://note.youdao.com/yws/public/resource/58e66944c038ab4625a8447d336cbe00/xmlnote/F390FA3543FF4A50AC3C85F2B4EB47D3/5369)

**Comment by CarGuo** [comment]
你获取的时候，可以指定图片大小小一点，速度还是过得去。至于我这边，其实目前测试的做法是，直接静音，然后显示seek的画面。

**Comment by Lee-Wang-Jing** [comment]
Thanks very much.
