### ISSUE TITLE
屏幕旋转问题

### ISSUE THREAD

**Issue by F1ReKing** [CarGuo/GSYVideoPlayer#1811]
## 问题描述：

我要实现，点击全屏按钮后可以横屏旋转，而不是旋转后进入全屏，但是竖立手机后，不退出全屏，现在会自动退出全屏。

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

**Comment by CarGuo** [comment]
不是很理解，类似demo中的 playActivity
