### ISSUE TITLE
是否有计划开发Cordova插件

### ISSUE THREAD

**Issue by ttgzs** [CarGuo/GSYVideoPlayer#1814]
@CarGuo 看了插件好多的介绍和功能，但是没有看到关于Cordova插件的相关信息，不知道是否有计划推出Cordova插件呢？

**Comment by CarGuo** [comment]
目前没有做成cordova插件的计划，和rn一样，因为没有ios版的，所以没这个计划。

Cordova插件封装还是很简单的，如果需要自己做个plugin就可以了

**Comment by ttgzs** [comment]
Android的还好，ios的有些困难

**Comment by CarGuo** [comment]
目前我也爱莫能租😂
