### ISSUE TITLE
多路视频同时播放，当一个视频全屏时，API 19 出现视频混乱

### ISSUE THREAD

**Issue by hfyqsy** [CarGuo/GSYVideoPlayer#1815]
## 问题描述：

多路视频同时播放，当一个视频全屏时，API 19 出现视频混乱

## 问题机型/系统：

 真机 vivo api 19

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'`

问题代码：
多路视频同时直播，当其中的一个全屏播放的时候 [出现多个视频混乱切换播放]

**Comment by hfyqsy** [comment]
[VID_20190220_093316.zip](https://github.com/CarGuo/GSYVideoPlayer/files/2882641/VID_20190220_093316.zip)
这个是出现问题的视频

**Comment by CarGuo** [comment]
看起来有点奇怪，你这边配置了AndroidManifest了吗？试过在demo的多任务列表播放过吗？

**Comment by hfyqsy** [comment]
<item name="android:windowContentOverlay">@null</item>   是因为这个属性导致的
