### ISSUE TITLE
小米电视4C同时播放问题

### ISSUE THREAD

**Issue by cnkker** [CarGuo/GSYVideoPlayer#1816]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

小米电视4C 32寸，软件DEMO中开启硬解码后,如下
 <application
       ……
        android:hardwareAccelerated="true"
      ……
      />
开启多任务，同时只能播放一个视频

## 问题机型/系统：

小米电视4C  32寸

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

## Demo中的复现步骤

添加硬件加速后，重新打包

Demo中的detailPlayer页面打开多任务播，同时播放视频，放会出现这个问题。
只有一个视频播放，其他是黑屏

问题代码：(如果有)
```
无
```

## 问题log（如果有）
无
```

xxxxxxx

```

**Comment by CarGuo** [comment]
是的，要多个同事播放，请参考demo多任务。
