### ISSUE TITLE
部分MP4格式的网络连接不播放

### ISSUE THREAD

**Issue by nanchen2251** [CarGuo/GSYVideoPlayer#1817]
## 问题描述：

http://customer.viewsky.cn/partner/resource/activity/attribute/operationVideo/7
这个链接在浏览器是可播放的。MP4格式，但为啥该播放器无法播放？

## 问题机型/系统：

任意手机

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
implementation 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式

切换内核试试，ijk内核目前你信息解析失败

**Comment by nanchen2251** [comment]
感谢，。可以了。

**Comment by nanchen2251** [comment]
经检测 华为 P20 上面还是一直加载不出来，采用的是 demo 的 PlayActivity。Android 版本 9.0

**Comment by nanchen2251** [comment]
体现在 UI 上是，加载转了两圈，就自动停止了。

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class); 内核的？可以提供流么

**Comment by nanchen2251** [comment]
经多次测试，插上SIM卡，切换为 4G 网络可以了。怀疑是网络问题，但不太明白，为何在 WIFI 环境下
，直接把视频放WebView 播放是没任何问题的。

**Comment by CarGuo** [comment]
或者和DNS解析有关？

**Comment by RuoYuHoney** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class); 
当我设置成这个之后，集成gsyVideoPlayer-ex_so是否还有效，这样的话对于mpeg编码有声音无画面情况怎么解决？

**Comment by CarGuo** [comment]
这个没关系，只是你需要切换内核使用，针对不同视频
