### ISSUE TITLE
多视频无缝连续播放设置setLooping出错

### ISSUE THREAD

**Issue by qinyang1018** [CarGuo/GSYVideoPlayer#1818]
## 问题描述：

使用多视频无缝连续播放设置setLooping后在播放完最后一个视频后一次跳最后一个视频

## 问题机型/系统：

华为 mate9 8.0

## GSY依赖版本

最新demo中

## Demo中的复现步骤

Demo中的DetailListPlayer 增加 detailPlayer.setLooping(true);

预期效果应该是整个list中的视频文件再次循环

**Comment by CarGuo** [comment]
这个本来就没有整个列表再次循环的支持

**Comment by qinyang1018** [comment]
@CarGuo   这个功能能否实现呢？  现在有这种需求  但是没思路实现

**Comment by qinyang1018** [comment]
@CarGuo  感谢您的回答  现在项目有这方面需求，我没目前没找到实现思路，不知道您能否指点下

**Comment by CarGuo** [comment]
demo 中的 GSYExo2MediaPlayer ，用 ConcatenatingMediaSource 你可以看看
