### ISSUE TITLE
播放m3u8快进拖动后卡顿

### ISSUE THREAD

**Issue by zhoubotongs** [CarGuo/GSYVideoPlayer#1820]
## 问题描述：
播放m3u8快进拖动后，本来已经加载完成了，但是会卡顿几秒
## 问题机型/系统：
所有机型
## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
可以看看问题集锦，或者切换到exoplayer内核
