### ISSUE TITLE
监听视频播放器的状态不对

### ISSUE THREAD

**Issue by hele-jeremy** [CarGuo/GSYVideoPlayer#1821]
## 问题描述：

使用连续播放时我需要统计用户实际真正播放了多长时间的视频的需求,使用了你demo中的
连续播放的写法 参考了ListGSYVideoPlayer.java这个类的写法 ,通过你说的我在setStateAndUi(int state)这个方法里面来监听播放器的播放状态 但是出现了 state 状态和实际的播放器状态不一致的问题,比如当前播放器正在播放中 但是state并不是在CURRENT_STATE_PLAYING这个状态. 求解答 急

## 问题机型/系统：
这个和机型无关

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
 implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

## Demo中的复现步骤

[Demo中的DetailListPlayer页面打开后会出现这个问题。]([url]([url]([url](url))))

问题代码：(如果有)
```
[xxxxxxx](url)
```
DetailListPlayer
![image](https://user-images.githubusercontent.com/20302878/53246186-ec869180-36ea-11e9-8e48-75c59f731509.png)

**Comment by hele-jeremy** [comment]
因为我现在需要统计用户真正实际播放的视频时长 因此必须需要准确的知道当前播放器的状态

**Comment by hele-jeremy** [comment]
求指导  很急 谢谢!!!!

**Comment by CarGuo** [comment]
不是很理解，你是在哪里输出的？

**Comment by hele-jeremy** [comment]
![image](https://user-images.githubusercontent.com/20302878/53318822-790f9a80-390b-11e9-9fb1-d2b33f10d418.png)

**Comment by hele-jeremy** [comment]
如上图我的页面是需要播放一个系列有很多章节的视频课程 我需要当用户在这个界面进行播放课程视频的时候 要准确的统计出当用户退出这个界面的时候实际观看了多长时间的视频课程 不包括用户拖动进度条的时间 而是真实的时间观看时间  我的思路是监听播放器 player的状态当是真正的播放的时候的状态是开始计时当是暂听pause 或者 停止时等非播放状态时 停止计时  因此我是在 setStateAndUi(int state) 这个方法里面进行视频播放器的状态监听的 但是有时候监听的状态是不对的 实际在播放但是回调给的状态却不是播放的状态 如下图 我正在播放课程视频 但是回调的状态却不是播放状态
![image](https://user-images.githubusercontent.com/20302878/53319197-cf310d80-390c-11e9-916f-b06218624607.png)

**Comment by hele-jeremy** [comment]
[KVideoVipPlayer.txt](https://github.com/CarGuo/GSYVideoPlayer/files/2899272/KVideoVipPlayer.txt)
[KVideoControlPlayer.txt](https://github.com/CarGuo/GSYVideoPlayer/files/2899273/KVideoControlPlayer.txt)
这是我的模仿你的DetailListPlayer的源码 可以帮忙看看吗啊 是我调用的方式不对吗 啊

**Comment by hele-jeremy** [comment]
![image](https://user-images.githubusercontent.com/20302878/53319525-bbd27200-390d-11e9-8e49-c1438465f85e.png)
就比如 当切换播放到写一个视频教程 此时调用playNext()方法来实现的  此时看log状态 播放器的状态就不是播放的状态 
在每次playnext重新播放的时候需要做一些什么重置之类的的操作吗啊  还是调用的姿势不对  求指教  急谢谢

**Comment by hele-jeremy** [comment]
knowledge_oppo_v1.1.0.apk

**Comment by hele-jeremy** [comment]
[knowledge_oppo_v1.1.0.zip](https://github.com/CarGuo/GSYVideoPlayer/files/2899287/knowledge_oppo_v1.1.0.zip)
 这个是app 可以装到手机上帮我看看吗啊  
![image](https://user-images.githubusercontent.com/20302878/53320059-65663300-390f-11e9-9507-e87654cfd960.png)

**Comment by CarGuo** [comment]
你需要的话可能要等到有时间才能帮你详细看，如果你不急的话。

上面你说的playNext就是每次都重构了一个新的内核去播放，播放状态肯定会经历重新构建的流程。

至于其他时候，有时候和当前状态有关，比如切换全屏的时候，是切换了view。

**Comment by hele-jeremy** [comment]
这个我还没有试过横竖屏切换的时候 播放状态对不对
有的时候可能一进入这个界面进行播放 状态就回调不对 就不是播放状态
这个 gif里面就可以看出很多的 状态回调不对的问题
![bug](https://user-images.githubusercontent.com/20302878/53322152-7ca81f00-3915-11e9-8467-b92e3499d9ba.gif)

**Comment by hele-jeremy** [comment]
![image](https://user-images.githubusercontent.com/20302878/53327100-17a6f600-3922-11e9-843c-a648d5f94c72.png)
我把setSeekOnStart()方法给注释掉了  也还是会出现 播放状态回调的状态不对的情况

**Comment by hele-jeremy** [comment]
![image](https://user-images.githubusercontent.com/20302878/53327267-6e143480-3922-11e9-89e4-3a40eba72f99.png)
![image](https://user-images.githubusercontent.com/20302878/53327285-766c6f80-3922-11e9-9706-1d19a341286f.png)
状态回调不对的情况 基本都是 实际在播放中 但是回调回来的状态却是 1  即 prepare状态

**Comment by hele-jeremy** [comment]
是不是可以禁用缓存的模式下试一下

**Comment by hele-jeremy** [comment]
![image](https://user-images.githubusercontent.com/20302878/53333628-6314d080-3931-11e9-8d05-e933a914bc25.png)

**Comment by hele-jeremy** [comment]
大佬能给点意见吗啊

**Comment by hele-jeremy** [comment]
> 你需要的话可能要等到有时间才能帮你详细看，如果你不急的话。
> 
> 上面你说的playNext就是每次都重构了一个新的内核去播放，播放状态肯定会经历重新构建的流程。
> 
> 至于其他时候，有时候和当前状态有关，比如切换全屏的时候，是切换了view。

大佬给点意见啊

**Comment by CarGuo** [comment]
我还是不是很理解，不过这么说啊，你应该打印所有状态出来对比下，看看是什么情况。

比如播放中如果出现了不是播放中的状态和回调，那这个状态是什么，才能知道可能是什么导致的。

然后播放的时候，开始进入的时候是有可能会走prepare和buffer等状态的，所以你还是最好把状态都打印，然后跟一下看看

**Comment by hele-jeremy** [comment]
![image](https://user-images.githubusercontent.com/20302878/53384860-52a73900-39b7-11e9-89c3-79200d977422.png)
我在setStateAndUi里面将所有的状态都打印出来了  发现 播放状态回调回来的状态是prepare准备状态

**Comment by CarGuo** [comment]
播放到一半的时候，出现这个回调？？

如果是开始播放的时候，这个很正常

**Comment by monsterLin** [comment]
@hele-jeremy 最近在做m3u8直播也需要统计时长，我的处理方案是在`setStateAndUi`方法中去监听`CURRENT_STATE_PLAYING` ，相关代码:
```
                if (!TextUtils.isEmpty(mPreviousTitle)) {
                    //上一个节目不为空，非第一次进入
                    if (!mPreviousTitle.equals(mCurrentTitle)) {
                        mPreviousTitle = mCurrentTitle;
                        long mEndTime = System.currentTimeMillis();
                        Debuger.printfLog(TAG, "before video endTime: " + mEndTime);
                        float mDurationTime = (float) (mEndTime - mStartTime) / 1000;
                        //上报观看时长
                        if (null != zqTvMediaBuryListener) {
                            zqTvMediaBuryListener.uploadPlayDuration(mPreviousTitle, mDurationTime);
                            Debuger.printfLog(TAG, "before video durationTime: " + mDurationTime);
                        }
                        mStartTime = System.currentTimeMillis();
                        Debuger.printfLog(TAG, "=>> current video startTime: " + mStartTime);
                    }
                } else {
                    //上一个节目为空，第一次进入
                    mPreviousTitle = mCurrentTitle;
                    mStartTime = System.currentTimeMillis();
                    Debuger.printfLog("current video startTime: " + mStartTime);
                }
```

**Comment by NewDirection** [comment]
> ![image](https://user-images.githubusercontent.com/20302878/53384860-52a73900-39b7-11e9-89c3-79200d977422.png)
> 我在setStateAndUi里面将所有的状态都打印出来了 发现 播放状态回调回来的状态是prepare准备状态

最后咋解决的？
