### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by rd-wang** [CarGuo/GSYVideoPlayer#1822]
## 问题描述：

私人问题  希望能得到帮助
并不是库的问题
自定义切换清晰度setup之后只有声音没有图像，无法呼出操作栏 。但是可以改变亮度双击暂停播放
通过实体按键返回 正常。再次进入全屏就正常了

## 问题机型/系统：

所有

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

问题代码：(可能是)

    @Override
    public GSYBaseVideoPlayer startWindowFullscreen(Context context, boolean actionBar, boolean statusBar) {
        KLXVideoView gsyVideoPlayer = (KLXVideoView) super.startWindowFullscreen(context, actionBar, statusBar);
        if (gsyVideoPlayer != null) {
            gsyVideoPlayer.partEntity = partEntity;
            gsyVideoPlayer.detailEntity = detailEntity;
            gsyVideoPlayer.mSourcePosition = mSourcePosition;
            gsyVideoPlayer.qualityUrlList = partEntity.getMediaFiles();
            gsyVideoPlayer.mTypeText = mTypeText;
            gsyVideoPlayer.initViewStyle();
            if (gsyVideoPlayer.partEntity != null && gsyVideoPlayer.detailEntity != null) {
                gsyVideoPlayer.showFullButton();
                setAdapterData(gsyVideoPlayer);
            }
            gsyVideoPlayer.setTouchProgressTimeColor(touchProgressTimeHighLightColor, touchProgressTimeNormalColor);
        }
        return gsyVideoPlayer;
    }

    @Override
    protected void resolveNormalVideoShow(View oldF, ViewGroup vp, GSYVideoPlayer gsyVideoPlayer) {
        super.resolveNormalVideoShow(oldF, vp, gsyVideoPlayer);
        if (gsyVideoPlayer != null) {
            KLXVideoView mVideoView = (KLXVideoView) gsyVideoPlayer;
            mVideoView.hideFullButton();
            mSourcePosition = mVideoView.mSourcePosition;
            qualityUrlList = mVideoView.partEntity.getMediaFiles();
            mTypeText = mVideoView.mTypeText;
            setUp(qualityUrlList, mCache, mCachePath, mTitle);
        }
    }

    private void setAdapterData(KLXVideoView gsyVideoPlayer) {
        if (gsyVideoPlayer.qualityAdapter == null) {
            gsyVideoPlayer.qualityAdapter =
                    new QualityAdapter(gsyVideoPlayer.partEntity.getMediaFiles(),getQualityListener(gsyVideoPlayer),gsyVideoPlayer);
        }
        gsyVideoPlayer.recyclerQuality = gsyVideoPlayer.findViewById(R.id.recycler_quality);
        gsyVideoPlayer.mLayoutQuality = gsyVideoPlayer.findViewById(R.id.layout_quality);
        gsyVideoPlayer.recyclerQuality.setLayoutManager(new LinearLayoutManager(getContext()));
        gsyVideoPlayer.recyclerQuality.setAdapter(gsyVideoPlayer.qualityAdapter);
        for (VideoDataInfoEntity en : gsyVideoPlayer.partEntity.getMediaFiles()) {
            if (Strings.isEquals(en.getMediaKeyFullUrl(), mUrl)) {
                gsyVideoPlayer.mTypeText = en.getQualityName();
                gsyVideoPlayer.mVideoQuality.setText(gsyVideoPlayer.mTypeText);
            }
        }
} 

    public OnListItemClickListener getQualityListener(KLXVideoView gsyVideoPlayer) {
        return new OnListItemClickListener() {
            @Override
            public void onItemClick(int position) {
                final String name = gsyVideoPlayer.partEntity.getMediaFiles().get(position).getQualityName();
                if (gsyVideoPlayer.mSourcePosition != position) {
                    if ((gsyVideoPlayer.mCurrentState == GSYVideoPlayer.CURRENT_STATE_PLAYING
                            || gsyVideoPlayer.mCurrentState == GSYVideoPlayer.CURRENT_STATE_PAUSE)) {
                        final String url = gsyVideoPlayer.partEntity.getMediaFiles().get(position).getMediaKeyFullUrl();
                        gsyVideoPlayer.onVideoPause();
                        final long currentPosition = gsyVideoPlayer.mCurrentPosition;
                        gsyVideoPlayer.getGSYVideoManager().releaseMediaPlayer();
                        gsyVideoPlayer.cancelProgressTimer();
                        gsyVideoPlayer.hideAllWidget();
                        new Handler().postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                gsyVideoPlayer.setUp(url, mCache, mCachePath, mTitle);
                                gsyVideoPlayer.setSeekOnStart(currentPosition);
                                gsyVideoPlayer.startPlayLogic();
                                gsyVideoPlayer.cancelProgressTimer();
                                gsyVideoPlayer.hideAllWidget();
                            }
                        }, 500);
                        gsyVideoPlayer.mTypeText = name;
                        gsyVideoPlayer.mVideoQuality.setText(name);
                        gsyVideoPlayer.mSourcePosition = position;
                        gsyVideoPlayer.mLayoutQuality.setVisibility(GONE);
                    }
                } else {
                    Toast.makeText(getContext(), "已经是 " + name, Toast.LENGTH_LONG).show();
                }
            }
        };
    }
 

自定义的xml如下
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/black">

    <FrameLayout
        android:id="@+id/surface_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center" />

    <RelativeLayout
        android:id="@+id/thumb"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentStart="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        android:background="#000000"
        android:scaleType="fitCenter" />

    <RelativeLayout
        android:id="@+id/layout_no_wifi"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentTop="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentBottom="true"
        android:background="#CC000000"
        android:scaleType="fitCenter" />

    <RelativeLayout
        android:id="@+id/layout_quality"
        android:layout_width="290dp"
        android:layout_height="match_parent"
        android:layout_alignParentTop="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentBottom="true"
        android:background="#CC000000"
        android:scaleType="fitCenter">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_quality"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="40dp"
            android:layout_centerInParent="true"
            android:layout_marginBottom="40dp"
            android:fadingEdge="none"
            android:overScrollMode="never" />
    </RelativeLayout>

    <RelativeLayout
        android:id="@+id/layout_collection"
        android:layout_width="280dp"
        android:layout_height="match_parent"
        android:layout_alignParentTop="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentBottom="true"
        android:background="#CC000000"
        android:scaleType="fitCenter">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_collection"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="40dp"
            android:layout_marginBottom="40dp"
            android:fadingEdge="none"
            android:overScrollMode="never" />
    </RelativeLayout>

    <RelativeLayout
        android:id="@+id/layout_share"
        android:layout_width="270dp"
        android:layout_height="match_parent"
        android:layout_alignParentTop="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentBottom="true"
        android:background="#CC000000"
        android:gravity="center_vertical"
        android:scaleType="fitCenter">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_share"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="40dp"
            android:layout_marginBottom="40dp"
            android:fadingEdge="none"
            android:overScrollMode="never" />

    </RelativeLayout>

    <FrameLayout
        android:id="@+id/layout_bottom"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true">

        <LinearLayout
            android:id="@+id/bottom_menu"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_40"
            android:background="@drawable/video_bottom_bg"
            android:gravity="center_vertical"
            android:orientation="horizontal"
            android:visibility="visible">

            <ImageView
                android:id="@+id/mini_start"
                android:layout_width="@dimen/dp_32"
                android:layout_height="@dimen/dp_32"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_gravity="center_vertical"
                android:background="@drawable/ripple_default"
                android:padding="@dimen/dp_10"
                android:scaleType="fitXY"
                android:src="@drawable/ic_player_pause_white" />

            <ImageView
                android:id="@+id/next_video"
                android:layout_width="@dimen/dp_32"
                android:layout_height="@dimen/dp_32"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_gravity="center_vertical"
                android:background="@drawable/ripple_default"
                android:padding="@dimen/dp_10"
                android:scaleType="fitXY"
                android:src="@drawable/player_video_next" />

            <TextView
                android:id="@+id/current"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="00:00"
                android:textColor="#ffffff"
                android:textSize="@dimen/font_11" />

            <SeekBar
                android:id="@+id/progress"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical"
                android:layout_weight="1"
                android:background="@null"
                android:max="100"
                android:maxHeight="@dimen/dp_2"
                android:minHeight="@dimen/dp_2"
                android:progressDrawable="@drawable/layer_progress_4dffffff_99ffffff_f0dd71_progress"
                android:thumb="@drawable/layer_seek_bar_ffffff_thumb" />

            <TextView
                android:id="@+id/total"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="00:00"
                android:textColor="#ffffff"
                android:textSize="@dimen/font_11" />

            <TextView
                android:id="@+id/video_quality"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:gravity="center"
                android:paddingHorizontal="@dimen/dp_5"
                android:text="清晰度"
                android:textColor="#ffffff"
                android:textSize="@dimen/font_13" />

            <TextView
                android:id="@+id/video_collection"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:gravity="center"
                android:paddingHorizontal="5dp"
                android:text="选集"
                android:textColor="#ffffff"
                android:textSize="@dimen/font_13" />

            <ImageView
                android:id="@+id/fullscreen"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:padding="@dimen/dp_12"
                android:scaleType="center"
                android:src="@drawable/video_enlarge" />
        </LinearLayout>

        <LinearLayout
            android:id="@+id/bottom_right_menu"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_40"
            android:layout_gravity="right"
            android:gravity="right"
            android:orientation="horizontal" />
    </FrameLayout>

    <ProgressBar
        android:id="@+id/bottom_progressbar"
        style="?android:attr/progressBarStyleHorizontal"
        android:layout_width="match_parent"
        android:layout_height="@dimen/px_2"
        android:layout_alignParentBottom="true"
        android:max="100"
        android:progressDrawable="@drawable/layer_progress_4dffffff_99ffffff_f0dd71_progress" />

    <ImageView
        android:id="@+id/back_tiny"
        android:layout_width="@dimen/dp_24"
        android:layout_height="@dimen/dp_24"
        android:layout_marginLeft="@dimen/dp_6"
        android:layout_marginTop="@dimen/dp_6"
        android:visibility="gone" />

    <moe.codeest.enviews.ENDownloadView
        android:id="@+id/loading"
        android:layout_width="@dimen/dp_28"
        android:layout_height="@dimen/dp_28"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:visibility="invisible" />

    <ImageView
        android:id="@+id/start"
        android:layout_width="@dimen/dp_48"
        android:layout_height="@dimen/dp_48"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:layout_gravity="center_vertical"
        android:background="@drawable/shape_oval_ffffff"
        android:padding="@dimen/dp_18"
        android:scaleType="centerInside" />

    <TextView
        android:id="@+id/tv_hint"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/start"
        android:layout_marginTop="@dimen/dp_8"
        android:gravity="center"
        android:paddingHorizontal="@dimen/dp_16"
        android:textColor="@color/white"
        android:textSize="@dimen/font_14"
        android:visibility="visible" />

    <ImageView
        android:id="@+id/small_close"
        android:layout_width="30dp"
        android:layout_height="30dp"
        android:paddingLeft="10dp"
        android:paddingTop="10dp"
        android:scaleType="centerInside"
        android:src="@drawable/video_small_close"
        android:visibility="gone" />

    <ImageView
        android:id="@+id/lock_screen"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_alignParentLeft="true"
        android:layout_centerVertical="true"
        android:layout_marginLeft="50dp"
        android:padding="10dp"
        android:scaleType="centerInside"
        android:src="@drawable/unlock"
        android:visibility="visible" />

    <FrameLayout
        android:id="@+id/top_menu"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_toEndOf="@+id/back_tiny"
        android:layout_toRightOf="@+id/back_tiny">

        <LinearLayout
            android:id="@+id/layout_top"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_50"
            android:background="@drawable/video_title_bg"
            android:gravity="center_vertical">

            <ImageView
                android:id="@+id/back"
                android:layout_width="@dimen/dp_50"
                android:layout_height="@dimen/dp_50"
                android:paddingLeft="10dp"
                android:scaleType="centerInside"
                android:src="@drawable/ic_back" />

            <TextView
                android:id="@+id/title"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:paddingLeft="@dimen/dp_10"
                android:textColor="@android:color/white"
                android:textSize="@dimen/font_14" />

            <ImageView
                android:id="@+id/ic_share"
                android:layout_width="@dimen/dp_50"
                android:layout_height="@dimen/dp_50"
                android:paddingRight="10dp"
                android:scaleType="centerInside"
                android:src="@drawable/ic_share" />

        </LinearLayout>
    </FrameLayout>

    <RelativeLayout
        android:id="@+id/preview_layout"
        android:layout_width="@dimen/seek_bar_image"
        android:layout_height="100dp"
        android:layout_above="@+id/layout_bottom"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="@dimen/dp_30"
        android:visibility="gone" />

</RelativeLayout>

## 问题log

并没有发现

**Comment by CarGuo** [comment]
如果demo没办法复现，我也很难定位

**Comment by rd-wang** [comment]
可以帮忙看一下吗 我留一下联系方式(qq:179366099)

**Comment by rd-wang** [comment]
不是重新设置视频链接的问题 点击监听空实现都会出现黑屏  好像是控制层的view 和播放视频的view都没了

**Comment by CarGuo** [comment]
说实话，这种问题只能自己看合适些。

**Comment by rd-wang** [comment]
感谢回复。 已经解决了 。
