### ISSUE TITLE
进度条问题

### ISSUE THREAD

**Issue by NerdAnonymous** [CarGuo/GSYVideoPlayer#1826]
版本 6.0.3 在使用demo中的自定义EXO下一集之间的无缝切换问题，点击下一集的时候，或者拖动进度条到影片结尾，会先播放个2到3秒，然后进度条才变成0，进度条并没有无缝切换

**Comment by CarGuo** [comment]
这里应该是和定时器还有buffer回调有关

**Comment by NerdAnonymous** [comment]
使得 我大概看了下逻辑 拖动进度的时候走的是progressChanged，然后这时候比如说拖动到0，这时候根据进度改变时间为0，然后实际上ProgressTimerTask这个方法又走了一遍，然后走到setTextAndProgress中的 int position = getCurrentPositionWhenPlaying();这一句拿的是拖动前的最后播放时间，然后设置了一下，进度条就又跳回到这个时间，这算不算bug

**Comment by CarGuo** [comment]
拖动到0的时候，还在buffer，然后有进入 setTextAndProgress 触发的场景？

**Comment by CarGuo** [comment]
你可以看看继承重写 setProgressAndTime 方法，在上面代码注释哪里加判断试试

**Comment by NerdAnonymous** [comment]
嗯 已经处理过了

**Comment by NerdAnonymous** [comment]
还有个问题，就是在下一级切换的时候，如果我切换到全屏去切换下一集的时候，直接就是
 com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(0, null, null, video/avc, avc1.640015, -1, null, [272, 480, -1.0], [-1, -1])

也是demo的自定义exo可复现

**Comment by CarGuo** [comment]
player.getCurrentPlayer().playNext() ??

**Comment by NerdAnonymous** [comment]
GSYExoVideoManager.instance().next();我自己的项目中有全屏切换的需求，但是出问题了，然后我进demo，我是这么尝试的 我暂时把返回按键的点击事件设置成下一级 ，然后我进入全屏，按返回，然后就出这个异常了

**Comment by CarGuo** [comment]
这个可能需要你自己看下，最好参考项目中的  player.getCurrentPlayer().playNext() 方法去调用

**Comment by NerdAnonymous** [comment]
好 谢谢解答 一入视频深似海

**Comment by shuaimango** [comment]
求大神优化setProgressAndTime

**Comment by thirtyyuan** [comment]
The above mentioned `setProgressAndTime()` caused the problem of beating after dragging the `Seekbar`. It seems to be the same problem as [#692] (https://github.com/CarGuo/GSYVideoPlayer/issues/692) and has been solved, and that's save my life, thanks!
