### ISSUE TITLE
m3u8视频清晰度问题

### ISSUE THREAD

**Issue by walterFeng** [CarGuo/GSYVideoPlayer#1827]
## 问题描述：

m3u8的视频很糊，清晰度与ios其他播放器播放的效果差别很大。

## 问题机型/系统：

 真机 小米5 Android8.0 (个人判断与机型无关 所有手机都可重现)

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1' 及其他所有版本

## Demo中的复现步骤

demo中的任一视频控件修改Url为：http://oktupbtle.bkt.clouddn.com/video/4c93a2cfdd5e595f7affcd71da0206c6.m3u8   等m3u8格式的视频可重现
(为了观察清楚 再修改一下视频控件的高度为match_parent) 

## 同一个URL与ios对比截图：
gsy:
![wechatimg19](https://user-images.githubusercontent.com/23520425/53329953-5049ce00-3928-11e9-8d07-77fb03609630.jpeg)
ios:
![wechatimg20](https://user-images.githubusercontent.com/23520425/53329956-53dd5500-3928-11e9-9901-2708fc977aed.jpeg)

**Comment by CarGuo** [comment]
试试

//EXOPlayer内核，支持格式更多
PlayerFactory.setPlayManager(Exo2PlayerManager.class);

**Comment by walterFeng** [comment]
@CarGuo  使用 PlayerFactory.setPlayManager(Exo2PlayerManager.class);  清晰度已经解决，谢谢
