### ISSUE TITLE
下一级问题

### ISSUE THREAD

**Issue by NerdAnonymous** [CarGuo/GSYVideoPlayer#1829]
DetailExoListPlayer的下一级是有问题的，问题就是你只有切换成全屏在切换回来的时候，点下一集就会出问题，DetailListPlayer的没有问题，好像是因为切换时导致suface销毁后仍然复用的问题

**Comment by CarGuo** [comment]
这个需要看看，你可以对比下两个的playerManager，或videomanager的区别。

**Comment by NerdAnonymous** [comment]
问题已经找到解决方案，出问题是在GSYVideoBaseManager 类中releaseSurface(Message msg)方法中的  playerManager.releaseSurface();在这个回调中销毁的surface和msg中发送的不是同一个surface，比如说我从小屏切换到全屏，需要销毁的是小屏幕的surface，这个小屏幕的surface存在msg.obj中，然而playerManager.releaseSurface()中所销毁的是大屏幕时的surface，然后下一集的时候，大屏幕的surface被销毁，造成无法渲染，你也可以排查一下

**Comment by CarGuo** [comment]
收到～～～

**Comment by aSmartTortoise** [comment]
请问下，我使用LandLayoutVideo实现多个视频前后连续播放的时候，当前屏幕属于全屏，且当前视频播放完的时候，我在onAutoComplete回调方法中 写了这么两行代码“
detailPlayer.setUp(url, true, "012");
detailPlayer.startPlayLogic();”想实现播放下一个视频，结果视频没有渲染。但是如果屏幕不是全屏就没有问题。请教下了~~

**Comment by aSmartTortoise** [comment]
再翻看其他已解决的issue后，找到了解决方案了，
