### ISSUE TITLE
小米8 android9.0 miui10.2 设置倍速播放无效  测试了其他两台华为机型,均正常 

### ISSUE THREAD

**Issue by sagaciousfrog** [CarGuo/GSYVideoPlayer#1831]
//是否需要ExoPlayer模式
    compile 'com.shuyu:GSYVideoPlayer-exo2:6.0.1'

    //更多ijk的编码支持
    compile 'com.shuyu:gsyVideoPlayer-ex_so:6.0.1'

**Comment by sagaciousfrog** [comment]
通过 getCurPlay().setSpeedPlaying(mPlaySpeed, true);进行播放速度设置的

**Comment by CarGuo** [comment]
收到，我看看怎么复现，目前手头没有小米8

**Comment by yangfeng1994** [comment]
我的也是小米8MIUI10.2的倍速播放失效，一倍以上的播放速度失效，一倍一下的，是可以的。一台华为荣耀8的可以，一台OPPO的也可以。

**Comment by BryanSharp** [comment]
这个很好修复的

**Comment by BryanSharp** [comment]
过几天有空了我提个pr，有啥奖励吗？我这边测试已经没问题了

**Comment by sagaciousfrog** [comment]
> 过几天有空了我提个pr，有啥奖励吗？我这边测试已经没问题了

QAQ,

**Comment by CarGuo** [comment]
@BryanSharp waiting for you

**Comment by CarGuo** [comment]
@BryanSharp 有后续么？🌹

**Comment by bigbigpeng3** [comment]
@BryanSharp 同作者问，有能够不换ijk解码的实现方式吗？

**Comment by bigbigpeng3** [comment]
@CarGuo 大哥你找到了什么解决方案吗？～

**Comment by keyoumi** [comment]
咋解决的啊。我也不敢说。我也不敢问

**Comment by wangzhaoyang123** [comment]
小米的这款机型就是会出这样的问题，audiotrack的高倍速设置无效，需要开启soundtouch设置倍速

**Comment by CarGuo** [comment]
@wangzhaoyang123 你的意思是需要开始 soundtouch 为 1 的配置？会变调的avfliter？

**Comment by wangzhaoyang123** [comment]
对 通常android23以上的机型使用audiotrack加速就可以了 但是小米这个机型audiotrack一倍以上的设置无效 需要配置打开soundtouch 


发自我的iPhone
------------------ 原始邮件 ------------------
发件人: Shuyu Guo <notifications@github.com>
发送时间: 2019年6月13日 18:40
收件人: CarGuo/GSYVideoPlayer <GSYVideoPlayer@noreply.github.com>
抄送: wangzhaoyang123 <1250495028@qq.com>, Mention <mention@noreply.github.com>
主题: 回复：[CarGuo/GSYVideoPlayer] 小米8 android9.0 miui10.2 设置倍速播放无效  测试了其他两台华为机型,均正常  (#1831)




@wangzhaoyang123 你的意思是需要开始 soundtouch 为 1 的配置？会变调的avfliter？

**Comment by CarGuo** [comment]
我这边没有小米系列手机，我让别人试了下确实可以，ijk内核和exo内核都可以··· ijk需要设置 soundtouch true
