### ISSUE TITLE
实在没有办法了，是我太菜，还是提个Issue吧！

### ISSUE THREAD

**Issue by LittleFatBoy** [CarGuo/GSYVideoPlayer#1833]
## 问题描述：

在ScrollView中使用六个自定义Player同时播放多路Rtmp直播视频
但是在加载第二个视频的时候第一个播放器就暂停了
自动以的Player是按照Demo中的MultiSampleVideo做的
唯一 一点区别是：我做了UI自定义，按照业务逻辑调用了startButtonLogic()方法
求大哥指点!!!谢啦。。。

## 问题机型/系统：
我这里有三个真鸡：分别是6.0 和两个8.0
这个问题在三个手机上都存在，不是机型的问题
## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`
## Demo中的复现步骤
我把Demo 中URL改成我的直播流后确实是可以播放（这一点就是我玩不明白的原因吧）
问题代码：(如果有)

 //开始播放调用
    public void setUpPlayer(String tag,int cameraPosition,String url,String liveName){
        //调用接口，得到直播流URL后执行这个方法
        //嗯~~~明明是按着Demo照抄过来的啊
       //这个方法在自定义的Player和Activity进行交互
        setPlayTag(tag);
        setPlayPosition(cameraPosition);
        setUpLazy(url,false,null,null,liveName);
        getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startWindowFullscreen(mContext,false,true);
            }
        });
        //一些配置
        setRotateViewAuto(true);
        setLockLand(true);
        setReleaseWhenLossAudio(false);
        setShowFullAnimation(true);
        setIsTouchWiget(false);
        setNeedLockFull(true);
        setVideoAllCallBack(new GSYSampleCallBack() {

            @Override
            public void onQuitFullscreen(String url, Object... objects) {
                super.onQuitFullscreen(url, objects);
                mFullKey = "null";
            }

            @Override
            public void onEnterFullscreen(String url, Object... objects) {
                super.onEnterFullscreen(url, objects);
                //getTitleTextView().setText((String) objects[0]);
                mFullKey = getKey();
            }

            @Override
            public void onAutoComplete(String url, Object... objects) {
                super.onAutoComplete(url, objects);
            }
        });
        startButtonLogic();
    }

## 问题log（如果有）
不会报错

**Comment by CarGuo** [comment]
已qq解决

**Comment by Benson189** [comment]
请问是如何解决的啊？我也是遇到这个问题。一个activity放了两个MultiSampleVideo，想同时播放两路rtsp直播流，但是其中一个播放另一个就会暂停~求告知啊~~~感谢

**Comment by vip404** [comment]
同问
