### ISSUE TITLE
.mp4首次加载很慢！！

### ISSUE THREAD

**Issue by itkun2013** [CarGuo/GSYVideoPlayer#1835]
## 问题描述：

我这里有个需求：
  服务器端使用nodhttp做的轻量级服务器，安卓写的，通过socket读流把本地的mp4格式 拼成http://192.168.31.39:9000/?filePath=/sdcard/Download/movie/v7.mp4，局域网视频，在丢给机顶盒APP播放，大视频比如超过400M以上的，首次加载特别慢，至少20秒以上，越大越慢，请问有解决方案或者实现方案么，是否需要音频解码 ！

## 问题机型/系统：

小米盒子

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.03'`

**Comment by CarGuo** [comment]
这个首次加载不只是客户端的问题，类似特殊化定制需求需要你自己看看了，说起来项目里也有代理socket拉流并保存的逻辑，你可以看看
