### ISSUE TITLE
Failed to resolve: support-media-compat

### ISSUE THREAD

**Issue by LiuDongCai** [CarGuo/GSYVideoPlayer#1837]
implementation 'com.shuyu:GSYVideoPlayer:6.0.3'
集成进来的时候报这个错：
Failed to resolve: support-media-compat

**Comment by LiuDongCai** [comment]
compileSdkVersion 27
buildToolsVersion "27.0.3"

minSdkVersion 16
targetSdkVersion 27

implementation 'com.android.support:design:27.1.1'
implementation 'com.android.support:appcompat-v7:27.1.1'

**Comment by CarGuo** [comment]
这个你参考下demo的配置，或者

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

//不依赖ExoPlayer模式
//implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'

//更多ijk的编码支持
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

**Comment by LiuDongCai** [comment]
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

//不依赖ExoPlayer模式
//implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'

//更多ijk的编码支持
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

还是不行

**Comment by CarGuo** [comment]
那试试如6.0.1或者5.0.2

**Comment by LiuDongCai** [comment]
谢谢，6.0.1的可以
然后我想问，我想实现一个需求，就是自动循环播放一个视频，无法手动暂停，右上角显示剩余时长，其余用户无法操作（比如放大、显示进度条，快进等）。
这个可以实现吗？要怎么弄

**Comment by CarGuo** [comment]
你可以参考代码里广告的实现。
