### ISSUE TITLE
前后台切换，恢复播放时间问题

### ISSUE THREAD

**Issue by l46321233** [CarGuo/GSYVideoPlayer#1839]
## 问题描述：

前后台切换，恢复播放时间总会往前跳几秒

## 问题机型/系统：

华为 荣耀8X，荣耀青春版

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo前后台切换也会有这个问题

**Comment by l46321233** [comment]
jiaozi播放器是正常不会出现跳秒问题

**Comment by CarGuo** [comment]
看问题集锦或者切换内核
