### ISSUE TITLE
怎么在视频前面加广告呢?像腾讯视频一样

### ISSUE THREAD

**Issue by fzxm** [CarGuo/GSYVideoPlayer#184]
我看您 GsyVideoPlayer里面 有个"TODO: 2016/11/13 跳过广告" 这个是用来控制广告的吗 能否给个思路?

**Comment by CarGuo** [comment]
double by https://github.com/CarGuo/GSYVideoPlayer/issues/189

**Comment by riseLishan** [comment]
有个"TODO: 2016/11/13 跳过广告"  我想问下控制广告的在那个类里？

**Comment by riseLishan** [comment]
有个"TODO: 2016/11/13 跳过广告"  我想问下控制广告的在那个类里？ @CarGuo @fzxm

**Comment by cervy** [comment]
连续播放2个应该可行吧
