### ISSUE TITLE
exoplayer在androidx下会报错

### ISSUE THREAD

**Issue by crazecoder** [CarGuo/GSYVideoPlayer#1842]
## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.0-beta1'`

## 问题log（如果有）

```

D8: Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler

```

建议去exoplayer的dev1分支编译成aar导入

**Comment by CarGuo** [comment]
我在demo中测试正常，你在demo中如何复线？

**Comment by crazecoder** [comment]
我是在项目里，如果是demo的确没问题，一和别的androidx库一起用就会报这个

**Comment by CarGuo** [comment]
估计是androidx版本不一样导致的？

**Comment by crazecoder** [comment]
不是，版本不一致，不会报support的错误信息

**Comment by CarGuo** [comment]
这就很奇怪了，因为我这边测试还挺正常的
