### ISSUE TITLE
请问我要添加 支持wma 格式的话 配置文件应该怎么加？

### ISSUE THREAD

**Issue by BoBoJiangs** [CarGuo/GSYVideoPlayer#1844]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

请问我要添加 支持wma 格式的话 配置文件应该怎么加？

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请看首页的两个.sh文件和编译教程

**Comment by BoBoJiangs** [comment]
看了的 但是不知道怎么增加wma 格式支持 具体代码应该怎么写啊

**Comment by CarGuo** [comment]
修改配置，重新打包so。

**Comment by BoBoJiangs** [comment]
.sh 里面配置怎么加 能麻烦指导一下不 谢谢大佬

**Comment by CarGuo** [comment]
比如

--enable-decoder=wmalossless \
    --enable-decoder=wmapro \
    --enable-encoder=wmav1 \
    --enable-decoder=wmav1 \
    --enable-encoder=wmav2 \
    --enable-decoder=wmav2 \
    --enable-decoder=wmavoice \
    --enable-demuxer=xwma \
    --enable-demuxer=avi \
    --enable-muxer=avi \
    --enable-demuxer=asf \
    --enable-muxer=asf \
    --enable-encoder=wmv1 \
    --enable-decoder=wmv1 \
    --enable-encoder=wmv2 \
    --enable-decoder=wmv2 \
    --enable-decoder=wmv3 \
    --enable-decoder=wmv3_crystalhd \
    --enable-decoder=wmv3_vdpau \
    --enable-decoder=wmv3image \
