### ISSUE TITLE
播放4k视频卡顿

### ISSUE THREAD

**Issue by kimfengzj** [CarGuo/GSYVideoPlayer#1845]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：播放4k视频卡顿

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
PlayerFactory.setPlayManager(Exo2PlayerManager.class);
 GSYVideoType.enableMediaCodec();
                    List<VideoOptionModel> list = new ArrayList<>();
                    VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50);

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
如果丢帧还是会的话，可以试试切换到exoplayer的内核模式再试试，如果还是会，说明软解码极限了

**Comment by join-lich** [comment]
@CarGuo 
长时间播放视频 会产生卡顿情况 
有的设备会播放几十小时不卡 有的设备几分钟就产生丢帧的现象

**Comment by kimfengzj** [comment]
感谢回复，我尝试过了exoplayer的内核模式，但卡顿情况还是出现

**Comment by kimfengzj** [comment]
终于搞定，在android6.0系统使用
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
GSYVideoType.enableMediaCodecTexture();
来渲染
