### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by AlexQcs** [CarGuo/GSYVideoPlayer#1846]
## 问题描述：

添加 最新版本 构建项目报错Android resource linking failed

## 问题机型/系统：

例如 真机 小米8青春版 Android8.1.0

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.0.0-beta1'

## Demo中的复现步骤

v4和v7包都是27.1.1

**Comment by CarGuo** [comment]
7.0 开始使用了 androidx 哦
