### ISSUE TITLE
是否支持播放至指定时间/位置自动暂停播放？

### ISSUE THREAD

**Issue by ZhanRu** [CarGuo/GSYVideoPlayer#1847]
## 问题描述：

是否支持播放至指定时间/位置暂停播放？不是在指定时间暂停，而是播放至指定时间自动暂停。
有用GSYVideoProgressListener回调，但是这个回调不是固定毫秒数回调，有可能跳过指定时间，请问是否支持设置一个时间，然后播放到那个时间自动暂停？

## 问题机型/系统：

全机型

## GSY依赖版本

    api 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    api 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'

## Demo中的复现步骤

```
非BUG，此项留空
```

问题代码：(如果有)
```
非BUG，此项留空
```

## 问题log（如果有）

```
非BUG，此项留空
```

**Comment by CarGuo** [comment]
你可以看demo和源码中广告的实现，其中一个就是类似这样的

**Comment by ZhanRu** [comment]
> 你可以看demo和源码中广告的实现，其中一个就是类似这样的

感谢大神回复，请问有具体的类名吗？

**Comment by ZhanRu** [comment]
> 你可以看demo和源码中广告的实现，其中一个就是类似这样的

是ListADVideoActivity和ListADVideoActivity2吗？好像没看出来具体怎么设置的

**Comment by ZhanRu** [comment]
> 你可以看demo和源码中广告的实现，其中一个就是类似这样的

找到了  GSYSampleADVideoPlayer类，感谢大佬

**Comment by ZhanRu** [comment]
@CarGuo 再次请问大神，如何支持一个视频中插入多条指定时间弹出的广告？

**Comment by CarGuo** [comment]
demo里有 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailADPlayer2.java
