### ISSUE TITLE
依赖5.0.2,报错找不到 libijkffmpeg.so

### ISSUE THREAD

**Issue by q296494327** [CarGuo/GSYVideoPlayer#1848]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

引入5.0.2后:
"GSYVideoPlayer-java"      : "com.shuyu:gsyVideoPlayer-java:5.0.2",
"GSYVideoPlayer-armv7a"    : "com.shuyu:gsyVideoPlayer-armv7a:5.0.2",

## 问题机型/系统：

 真机 小米mix2 8.0

## GSY依赖版本

"GSYVideoPlayer-java"      : "com.shuyu:gsyVideoPlayer-java:5.0.2",
 "GSYVideoPlayer-armv7a"    : "com.shuyu:gsyVideoPlayer-armv7a:5.0.2",

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```
报错找不到 libijkffmpeg.so

```

**Comment by CarGuo** [comment]
是运行中报错的么，如果是的话，需要增加ndk过滤

**Comment by q296494327** [comment]
是的,点击播放就报这个错

**Comment by q296494327** [comment]
我是分module开发的,我是要在video的module里的build.gradle里过滤so吗

**Comment by CarGuo** [comment]
在打包的时候，配置ndk过滤。

**Comment by q296494327** [comment]
谢谢.搞定了
 debug {
            ndk {
                abiFilters "armeabi"
            }
        }

        release {
          
            ndk {
                abiFilters "armeabi"
            }
        }
