### ISSUE TITLE
求解决思路

### ISSUE THREAD

**Issue by hele-jeremy** [CarGuo/GSYVideoPlayer#1849]
## 问题描述：
你好 问一下 就是现在我们在做一个看课程的app里面有一些音频的课程我们使用该播放器进行播放的播放的是m4a格式的,  现在是我们要做类似今日头条或者知识星球这种(看附件gif)的退出这个播放界面之后需要展示一个悬浮窗来控制播放的通知通知栏可能也需要展示一个控制栏 问一下这种是怎么实现的 给点思路 播放器我目前是放在Activity里面进行播放的
## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.３'`

![logic](https://user-images.githubusercontent.com/20302878/53929746-b6bdb180-40c9-11e9-9127-8d9fe5e1dcc3.gif)
![logic2](https://user-images.githubusercontent.com/20302878/53929752-b8877500-40c9-11e9-982c-8c9e887c1f04.gif)

**Comment by CarGuo** [comment]
悬浮窗你可以参考项目本身demo里有的那种思路，切换播放ui，使用同个内核。
通知栏的话你需要用remoteView去做咯
