### ISSUE TITLE
两套布局属性出错（重置）

### ISSUE THREAD

**Issue by krisez** [CarGuo/GSYVideoPlayer#1850]
## 问题描述：

XXXX发生了这样的问题！
自定义全屏与非全屏布局属性问题
从全屏切出来不能判断状态，只要有切出去的动作，该属性就会被重置
同时，如果在`resolveNormalVideoShow`方法里设置会导致正常的非全屏播放未做任何操作就默认点击，所以该方法里没有设置，同时`startWindowFullscreen`也一样

## 问题机型/系统：

虚拟机 android 8.1 
真机 vivo x23 

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤
Demo中LandLayoutVideo加入以下代码就会出现，只要从全屏切换成正常就会有属性不对

问题代码：(如果有)
```
xml布局，全屏与非全屏均加入了以下代码
<ImageView
        android:id="@+id/iv_test"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/custom_enlarge"
        android:layout_alignParentEnd="true"
        android:layout_margin="24dp"
        android:layout_alignParentRight="true" />
```
```
//activity代码
detailPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (!detailPlayer.isClick()) {
                    //直接横屏
                    orientationUtils.resolveByClick();

                    //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                    detailPlayer.startWindowFullscreen(InputUrlDetailActivity.this, true, true);
                }
            }
        });

@Override
    public void onBackPressed() {

        if (!detailPlayer.isClick()) {

            if (orientationUtils != null) {
                orientationUtils.backToProtVideo();
            }

            if (GSYVideoManager.backFromWindowFull(this)) {
                return;
            }
            super.onBackPressed();
        }
    }
```
```
//video代码
private boolean isClick = false;

    @Override
    protected void init(Context context) {
        super.init(context);
        findViewById(R.id.iv_test).setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                isClick = true;
            }
        });
......//省略部分
       }

    public boolean isClick() {
        Log.d("LandLayoutVideo", "isClick:" + isClick + "-isFull:" + mIfCurrentIsFullscreen);
        return isClick;
    }
```
## 问题log（如果有）

```

2019-03-07 13:53:13.896 5817-5817/com.example.gsyvideoplayer D/LandLayoutVideo: isClick:false-isFull:false(非全屏未点击，状态对的，能够直接退出该activity)
2019-03-07 13:53:27.529 5817-5817/com.example.gsyvideoplayer D/LandLayoutVideo: isClick:false-isFull:false(非全屏未点击，状态对的，能够直接进入全屏)
2019-03-07 13:53:50.845 5817-5817/com.example.gsyvideoplayer D/LandLayoutVideo: isClick:true-isFull:false(非全屏已点击，状态对的，不能够直接进入全屏，效果对的)
2019-03-07 13:53:54.535 5817-5817/com.example.gsyvideoplayer D/LandLayoutVideo: isClick:true-isFull:false(非全屏已点击，状态对的，不能够退出activity，效果对的)
2019-03-07 13:54:33.944 5948-5948/com.example.gsyvideoplayer D/LandLayoutVideo: isClick:false-isFull:true(全屏未点击能够跳出全屏状况)
2019-03-07 13:54:54.174 5948-5948/com.example.gsyvideoplayer D/LandLayoutVideo: isClick:false-isFull:true(全屏已点击，状态错误,得到的全是false)
//无论在backToNormal还是clearFullLayout都是false，在avtivity获取也是false
```

**Comment by krisez** [comment]
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    //更多ijk的编码支持
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'
依赖

**Comment by CarGuo** [comment]
不是很理解你的问题

**Comment by krisez** [comment]
比如我这样干
```
CustomVideo video = findViewById(xxxx);
video.isXXXX();//非全屏情况下，该状态是我想要的，全屏下，该状态一直都是默认的那个
```
状态怎么改变的？
布局里某一个点击事件 将该状态设置为true  `xxx = true` 一定时间后设置该 `xxx=false`
但是我全屏时  无论在哪使用该属性，均为false  
Activity、CustomVideo都是false 只要是全屏

**Comment by CarGuo** [comment]
你可以看下 cloneParams 
https://github.com/CarGuo/GSYVideoPlayer/blob/5107b674e31ba14bb6dbb7c00e41560f8ebe5f88/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/base/GSYBaseVideoPlayer.java#L210


startWindowFullscreen

https://github.com/CarGuo/GSYVideoPlayer/blob/5107b674e31ba14bb6dbb7c00e41560f8ebe5f88/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/base/GSYBaseVideoPlayer.java#L575

https://github.com/CarGuo/GSYVideoPlayer/blob/5107b674e31ba14bb6dbb7c00e41560f8ebe5f88/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/StandardGSYVideoPlayer.java#L360

**Comment by krisez** [comment]
将属性同步么？
但是我不用同步啊，我的想法是非全屏与全屏各自管理自己的属性，不需要clone
就好比：非全屏 boolean想true就true，想false就false
切换到全屏后，默认false，然后某个操作变换为true，再获取该属性时，它一直为false，我拦截了退出全屏的cleanFullLayout方法都不行，还是false
T^T||

**Comment by CarGuo** [comment]
那你通过是否全屏标志物去做判断初始化啊

**Comment by krisez** [comment]
mIsFullScreen？
没用这个，我想的是，这个应该是正常的，但我那个自添加属性  真不正常。

**Comment by CarGuo** [comment]
不是很理解你的意思，你不是可以通过全屏标记位去分别初始化各个状态么？

 不然的话，你通过player.getCurrentPlayer() 强制类型转化后设置吧

**Comment by krisez** [comment]
初始化了，但是我在其他位置获取这个属性的时候，一直未初始化的值，我中间对这个值的操作，没有保存下来。
    我全屏的时候点击了屏幕一次，播放器添加的属性isClick（初始化为false）更改为true
    但是我在activity或者播放器里面获取这个值的时候，均为false，就认为我的更改没有作用，除非是在该属性发生变化的方法里。
```
public void A(){
    icClick = true;//在这个方法里能够拿到true，但是其他方法里就是false
}
public boolean get(){
    return isClick;//返回的是false
}
```
我想说的就是，不做设置，只响应我的点击事件，但是在响应的时候给了我错误的值，非全屏就没这问题

**Comment by krisez** [comment]
```
public void A(){
    icClick = true;//在这个方法里能够拿到true，但是其他方法里就是false
   Log.d(TAG,"" + isClick); //打印的是true
}
```

**Comment by krisez** [comment]
大佬，你可以将代码拖进demo里瞅瞅你就知道了。

**Comment by CarGuo** [comment]
类似问题并不是项目问题，定制需求还需要你自己过下了
