### ISSUE TITLE
可以区分网络buffering还是本地buffering吗？

### ISSUE THREAD

**Issue by lala9662** [CarGuo/GSYVideoPlayer#1851]
拖动进度条的时候，如果那段位置的视频还没从网络加载想显示loading，如果加载了就不显示loading。但是看了一下onInfo调用，好像并不区分缓冲是本地还是网络，都是what==701再what==702。

有没有哪里的回调能知道当前是从网络加载数据，还是只是本地呢？

**Comment by CarGuo** [comment]
没有区分本地和网络的 buffering

**Comment by lala9662** [comment]
那只能用别的办法做了。。。￣□￣｜｜
