### ISSUE TITLE
列表页面 和详情切换问题

### ISSUE THREAD

**Issue by lvgang22** [CarGuo/GSYVideoPlayer#1852]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：列表和详情视频无缝 卡顿 声音有 但是界面不动

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 努比亚z11 华为noa2 

## GSY依赖版本

 implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
Demo怎么复现

**Comment by lvgang22** [comment]
就是demo 中  列表详情切换按钮 --在列表点击播放 --再点击详情按钮 ，出现有声音 但是界面不动的情况

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/releases/download/v7.0.0-beta1/app-release.apk

我这边测试正常

**Comment by lvgang22** [comment]
确实也是想向您请教请教 我录了屏，但是没发给你发

**Comment by CarGuo** [comment]
可以上传zip包的，issue回复里

**Comment by lvgang22** [comment]
[1.zip](https://github.com/CarGuo/GSYVideoPlayer/files/2944676/1.zip)
   <Button
            android:id="@+id/open_switch"
            android:layout_width="240dp"
            android:layout_height="wrap_content"
            android:layout_marginTop="20dp"
            android:text="列表详情切换" /> 的按钮操作

**Comment by CarGuo** [comment]
这个看起来，有没有可能元素共享的动画效果异常导致的
