### ISSUE TITLE
全屏视频切换浮窗视频为什么要重新创建一个播放器

### ISSUE THREAD

**Issue by hseury** [CarGuo/GSYVideoPlayer#1856]
## 问题描述：

大神你好，我在看源码ListVideo2Activity的过程中，发现在处理视频进行浮窗切换的时候都是重新创建了一个GSYBaseVideoPlayer实例，复制播放器的参数重新播放，我理解使用同一个播放器，改变view的大小即可。反复切换悬浮窗感觉会消耗较大。请问这样设计有什么原因呢？

**Comment by CarGuo** [comment]
因为这样状态好管理，同时最主要是不同状态的窗口可能ui不一样。
这里切换的是ui显示层，对于播放内核并没有切换。

**Comment by hseury** [comment]
大神你好，在video_player_standard这个布局文件中，是同时放了small_close这样的view来操作小屏视频的，在GSYBaseVideoPlayer中也是负责小屏操作的，设计思路是StandardVideoPlayer既可以操作大屏，也可以操作小屏。我想如果使用一个播放器，通过small_id来区分视频状态，是否可以一个播放器来控制大小屏的ui变化

**Comment by oveeeee** [comment]
> 大神你好，在video_player_standard这个布局文件中，是同时放了small_close这样的view来操作小屏视频的，在GSYBaseVideoPlayer中也是负责小屏操作的，设计思路是StandardVideoPlayer既可以操作大屏，也可以操作小屏。我想如果使用一个播放器，通过small_id来区分视频状态，是否可以一个播放器来控制大小屏的ui变化

应该可以，我就是三种尺寸不同ui的屏幕用的同一个FloatVideo。
