### ISSUE TITLE
如果是多个视频列表播放，怎么设置播放第几个视频，而不是播放下一集

### ISSUE THREAD

**Issue by dary123** [CarGuo/GSYVideoPlayer#1857]
如果是多个视频列表播放，怎么设置播放第几个视频，而不是播放下一集

**Comment by CarGuo** [comment]
不理解你的意思。

**Comment by dary123** [comment]
就是一个电视剧，不是有很多集嘛，用户选择哪一集，就跳转到哪一集播放，而不是使用playNext方法播放列表中的下一集

**Comment by CarGuo** [comment]
这个和playNext一个思路啊，你自己实现指定位置就可以了，关键就是重新setup

**Comment by wangrunxiang** [comment]
我也是copy了playnext的代码，改了一下来设置指定第几个视频，但是会playerror

com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(0, null, null, video/avc, avc1.64001F, -1, null, [854, 480, -1.0], [-1, -1])

**Comment by weiwenjuan** [comment]
电视剧可以按集播放吗？解决了吗？
