### ISSUE TITLE
gsyVideoPlayer-java 用到ijkplayer_exo 了吗？

### ISSUE THREAD

**Issue by bingdu0** [CarGuo/GSYVideoPlayer#1859]
1.gsy 不是已经把 ijk和exo 分离了吗，ijk的exo还是1.5.11 还有必要导这个库吗？

![image](https://user-images.githubusercontent.com/13532640/54081715-f263b000-4343-11e9-9baf-e22b304dc017.png)

2. gsyVideoPlayer-exo_player2 中的引用了ijk 的java 库，然后 IjkExo2MediaPlayer  只用到了AbstractMediaPlayer 这个抽象类和IMediaPlayer 这个接口吗？

![image](https://user-images.githubusercontent.com/13532640/54081960-cbf44380-4348-11e9-8a60-9aa50d46fd1e.png)

**Comment by CarGuo** [comment]
是分离了，只是因为历史原因保留着ijk的接口
