### ISSUE TITLE
Demo里的无缝切换在全屏下有问题

### ISSUE THREAD

**Issue by lala9662** [CarGuo/GSYVideoPlayer#1860]
## 问题描述：

Demo的无缝切换只是旋转了屏幕，我加上全屏之后发现，加载另一个清晰度的时候后播放全屏的画面停止了，但是进度在动，声音也有，就是画面一直不动，是没渲染在全屏的view上？就是PlayPickActivity那个例子，加了全屏就不行。

## 问题机型/系统：

任意

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的PlayPickActivity页面可重现

**Comment by lala9662** [comment]
就是在SmartPickVideo里只加了一句切换到横屏的时候全屏
`videoPlayer.startWindowFullscreen(PlayPickActivity.this,true,true);`
然后再全屏的时候选择清晰度切换，然后就出现我的问题了

**Comment by lala9662** [comment]
你好，大神有没有头绪，是暂时无法解决还是？我看源码还是不知道哪里的问题。

**Comment by CarGuo** [comment]
我不是很理解，PlayPickActivity在demo里应该就已经是全屏了的，这时候应该是旋转屏幕就可以而不需要调用全屏。

如果是detail类型的，你应该参考demo中的detail页面

**Comment by lala9662** [comment]
@CarGuo 

`//设置全屏按键功能,这是使用的是选择屏幕，而不是全屏
        videoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                orientationUtils.resolveByClick();
            }
        });
`

这段就是你的PlayPickActivity里的代码，你自己也加了注释。

我就在resolveByClick后加一句
`
orientationUtils.resolveByClick();
videoPlayer.startWindowFullscreen(PlayPickActivity.this,true,true);
`
这样才是旋转加全屏，然后再全屏下切换清晰度，就有问题。

我就是需要在全屏下用你GSYVideoManager.tmpInstance的逻辑切换清晰度。

**Comment by lala9662** [comment]
你用到GSYVideoManager.tmpInstance的就只有这个demo，就是PlayPickActivity。
我看了，没有全屏，那个全屏按钮点击只是横屏。

**Comment by lala9662** [comment]
@CarGuo 实在不好意思打扰你，但是真的有点急，我看了两天源码都找不到问题所在。

https://www.youtube.com/watch?v=Y3WDeaPT2PU&feature=youtu.be
录了个视频，就是按我说的加了这么一句后的问题，可以看到最后切完清晰度的时候，进度条在动，声音也有，但是画面停止了。

真的就在PlayPickActivity里加了这么一句，我也不是要求你给我解决办法，只是想确认你是否明白我的问题所在，明白这是个问题。

**Comment by CarGuo** [comment]
我应该明白你的问题了，目前吧playerManager里的 surface.release(); 屏蔽应该可暂时解决

```
@Override
    public void releaseSurface() {
        Debuger.printfError("**** showDisplay releaseSurface***** " + surface);
        if (surface != null) {
            //surface.release();
            surface = null;
        }
    }
```

**Comment by CarGuo** [comment]
简单来说，你可以直接把这个方法重写了
```
 @Override
    public boolean onSurfaceDestroyed(Surface surface) {
        //清空释放
        setDisplay(null);
        //同一消息队列中去release,屏蔽这个
        //releaseSurface(surface);
        return true;
    }
```

**Comment by lala9662** [comment]
确实可以了，这个不release会不会有别的问题？我是否应该在退出全屏的时候release？

**Comment by lala9662** [comment]
十分感谢

**Comment by CarGuo** [comment]
不会
