### ISSUE TITLE
能不能动态修改布局

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#1861]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

可不可以动态修改布局，就是在一个条件达成后，换成另外一套llayout
还有，在FloatingVideo中设置setLooping()没有反应

## 问题机型/系统：

魅族

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.0-beta1'

**Comment by CarGuo** [comment]
setLooping  和在那个控件没关系。同一个view内不支持你所说的动态修改布局
