### ISSUE TITLE
wifi和 3G/4G网络切换的问题

### ISSUE THREAD

**Issue by hele-jeremy** [CarGuo/GSYVideoPlayer#1862]
## 问题描述：

在一个视频列表中播放视频关于WIFI和3G/4G网络切换的问题

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

现在我们做的一个看课程的app中播放的是一个课程视频列表 ,也是模仿着你的那个DeailListPlayer来写的
我也禁用了缓存 但是切换的时候并不会弹出提示流量播放的对话框(showWifiDialog()方法) 我想问一下 这个是我需要自己进行扩展 还是说直接在你的那些方法上进行扩展,比如这个几个方法:showWifiDialog() isShowNetConfirm() 中进行扩展呢?

**Comment by hele-jeremy** [comment]
![silu](https://user-images.githubusercontent.com/20302878/54098970-f4844800-43f1-11e9-9265-70d990c82705.gif)
我的项目中的情景

**Comment by CarGuo** [comment]
你可以debug跟一下， showWifiDialog默认是有的，你需要看什么问题导致判断不执行这个方法
