### ISSUE TITLE
关于循环的问题

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#1868]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我使用的是FloatingVideo，在里面设置了一个button，点击后setLooping（）。视频没有循环，
等视频结束，再次点击就可以循环播放了。这个是不能动态设置循环播放吗，内核也切到了exoplayer。设置播放速度的时候正常

## 问题机型/系统：

魅蓝

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.0-beta1'

**Comment by CarGuo** [comment]
setLooping 必须在播放前设置才有效我记得

**Comment by oveeeee** [comment]
> setLooping 必须在播放前设置才有效我记得

好吧
