### ISSUE TITLE
播放过程中，开启或关闭硬解后，调用什么方法重新播放，使其生效

### ISSUE THREAD

**Issue by dary123** [CarGuo/GSYVideoPlayer#1871]
播放过程中，开启或关闭硬解后，调用什么方法重新播放（不从头开始，还是当前进度，只是为了使开启硬解生效），使其生效

**Comment by CarGuo** [comment]
？？一般setup之后就可以重新startplaylogic

**Comment by dary123** [comment]
startplaylogic方法执行后会重新从0开始播放

**Comment by dary123** [comment]
而且我想问下开启硬件解码后会有什么好处

**Comment by CarGuo** [comment]
setSeekOnStart之后再重新播放。硬解码和你的硬件相关的性能可以被使用上咯

**Comment by dary123** [comment]
setSeekOnStart方法需要知道当前进度才能设置吧，获取当前进度毫秒的方法有么

**Comment by CarGuo** [comment]
有的，你看wiki的api文档
