### ISSUE TITLE
循环播放问题

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#1875]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

设置循环播放后，他的状态是不是不会进入CURRENT_STATE_AUTO_COMPLETE状态，具体的这个循环播放功能代码在哪儿里

## 问题机型/系统：

魅族

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.0-beta1'

**Comment by CarGuo** [comment]
是不会进去， 播放前设置setLooping

**Comment by oveeeee** [comment]
> 是不会进去， 播放前设置setLooping

具体的实现代码是在那儿里，我找了好久没找到

**Comment by CarGuo** [comment]
什么实现代码？ setLooping 方法啊？

**Comment by oveeeee** [comment]
> 什么实现代码？ setLooping 方法啊？

我还是考虑一下其他方法把，麻烦您了

**Comment by oveeeee** [comment]
已解决动态设置循环播放问题

**Comment by SuperKung** [comment]
> 已解决动态设置循环播放问题

咋解决的呢？

**Comment by zhaoxu233** [comment]
1.记录修改设置循环状态时的播放位置
2.修改循环状态
3.调用seekOnStart设置播放位置 
4.最后调用startPlayLogic方法 
就可以动态设置循环状态 但是有一个体验不太好的地方 
就是调用seekOnStart后播放的进度和原来有些许差别
用户会有一个卡顿的感知

**Comment by zhaoxu233** [comment]
> > 已解决动态设置循环播放问题
> 
> 咋解决的呢？

1.获取修改设置循环状态时的播放位置
2.修改循环状态
3.调用seekOnStart设置播放位置
4.最后调用startPlayLogic方法
就可以动态设置循环状态 但是有一个体验不太好的地方
就是调用seekOnStart后播放的进度和原来有些许差别
用户会有一个卡顿的感知
