### ISSUE TITLE
两套布局 旋转问题

### ISSUE THREAD

**Issue by krisez** [CarGuo/GSYVideoPlayer#1876]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

当我没开启系统竖屏时，视频会跟着设备旋转即使我在注册文件里写了强制竖屏也不行

代码里用了OrientationUtils的，有这个就跟着设备转了，我把这个全部注释了，没有跟着设备转了，但是我点击全屏时设备没有横屏，想问问，如何让设备一直保持竖屏，全屏才横屏

用了` orientationUtils.setEnable(false)` 后视频没有跟着设备旋转，但是我切全屏的时候，虽然它横过来了，布局却没有更换成全屏的布局，简而言之就是，视频没有进入全屏，需要再点击一次全屏按钮

想问问怎么解决，，，，谢谢大佬

## 问题机型/系统：

vivo x5m   huawei p10

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by krisez** [comment]
机型应该没多大关系

**Comment by CarGuo** [comment]
你说的是这个方法导致的问题？  setRotateWithSystem(boolean rotateWithSystem)

**Comment by krisez** [comment]
setRotateWithSystem(boolean rotateWithSystem)  默认为true嘛。
我设置为false  也没用呀。。
在竖屏下  还是旋转了

**Comment by krisez** [comment]
问题解决了
1、不用旋转工具类
2、自定义屏幕旋转方法
3、复写底层全屏按键事件
```
 @Override
    public GSYBaseVideoPlayer startWindowFullscreen(Context context, boolean actionBar, boolean statusBar) {
        Video video = (Video) super.startWindowFullscreen(context, actionBar, statusBar);
        video.mListener = mListener;
        return video;
    }
```
4、先旋转屏幕再处理全屏与非全屏逻辑

**Comment by krisez** [comment]
emmm
再加一个 设置rtsp_video_player.isRotateViewAuto = false
我丢，(╯‵□′)╯︵┻━┻
