### ISSUE TITLE
GSYRenderView 的宽高获取

### ISSUE THREAD

**Issue by yangfeng1994** [CarGuo/GSYVideoPlayer#1877]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

想让视频的封面与视频的宽高一样，在 第一次onPrepared 的时候，获取到的 GSYRenderView为空，请问用什么方法，能把视频的封面与视频在播放器中显示的宽高一样，这样封面与视频一样大小，看起来会更完美。

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 华为荣耀8 Android7.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.0-beta1'`

**Comment by CarGuo** [comment]
因为这里是只有在surface添加成功之后才会有正确高度，你可以参考 https://github.com/CarGuo/GSYVideoPlayer/blob/6db7648038a8de03ee7fbb82d051dc12d9cbfa5c/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/MeasureHelper.java
