### ISSUE TITLE
手机放横，视频未全屏

### ISSUE THREAD

**Issue by zwping** [CarGuo/GSYVideoPlayer#1878]
version均为最新版
![](https://images.gitee.com/uploads/images/2019/0314/173221_dd6657ca_1615540.jpeg)

**Comment by CarGuo** [comment]
一般都是没有配置manifest或者没有参照demo

**Comment by zwping** [comment]
主要的原因是没有配置manifest ？
manifest其实是有配置的

**Comment by CarGuo** [comment]
你看demo就知道了，一直都是配置manifset的问题和没有参照demo问题

**Comment by zwping** [comment]
参照demo能否说下关键代码呢？

或者是说和布局也有关联？gsy播放的核心代码很精简，看不出与playActivity（demo）有啥不同

**Comment by CarGuo** [comment]
你应该参考比如detailplayer或者detaillistplayer页面得

**Comment by zwping** [comment]
manifest
orientationUtils
onConfigurationChanged (这个未配置)，
三个关键配置，缺一个配置了，现在已ok，thx !!
