### ISSUE TITLE
手势音量调节

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#1879]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

手势滑动音量调节，滑动一下，音量瞬间满格。怎么让音量调节的度像调节亮度那样比较顺滑

## 问题机型/系统：

魅族

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.0'`

**Comment by oveeeee** [comment]
就是调节音量也可以像调节亮度那样，按照一定的百分比跳动，目前调节音量的百分比不稳定

**Comment by CarGuo** [comment]
这个你可以继承后重写内部touch接口实现。

**Comment by oveeeee** [comment]
> 这个你可以继承后重写内部touch接口实现。
