### ISSUE TITLE
Error E/IJKMEDIA - 请帮助 - 秘鲁

### ISSUE THREAD

**Issue by Welsi** [CarGuo/GSYVideoPlayer#188]
Video of error:
https://drive.google.com/open?id=0B8p4j252zK3Ka1RjTlZ2ZU9SWTA

 E/IJKMEDIA: error reading header
 E/IJKMEDIA: http://s85.youmaker.com/flv/2017/3-25/mp44010338552690c9d787540a0b4ce1c2478e8321b85.mp4: End of file

**Comment by CarGuo** [comment]
i try Connection timed out for this url 
http://s85.youmaker.com/flv/2017/3-25/mp44010338552690c9d787540a0b4ce1c2478e8321b85.mp4

**Comment by Welsi** [comment]
the video in https://drive.google.com/open?id=0B8p4j252zK3Ka1RjTlZ2ZU9SWTA it is default url of sample

**Comment by CarGuo** [comment]
default url http://baobab.wdjcdn.com/14564977406580.mp4  in demo？you can try delete 
```
GSYVideoManager.instance().setTimeOut(4000, true);
```
in detailPlayer

**Comment by Welsi** [comment]
Thanks for the support, this is solved
