### ISSUE TITLE
能否自定义缓存key

### ISSUE THREAD

**Issue by yuye1124956** [CarGuo/GSYVideoPlayer#1882]
用的七牛 每次视频返回是带token和时间戳的 所有每次缓存key都不一样 能否自定义缓存key（比如忽略url参数当缓存key）

**Comment by CarGuo** [comment]
我记得是可以的，不过需要自定义你自己的cache层逻辑，就是CacheManager，如果是exo的需要自定义source就可以了

**Comment by hongyang51** [comment]
@yuye1124956 @CarGuo  
`          mediaSource = new ExtractorMediaSource.Factory(getDataSourceFactoryCache(mAppContext, cacheEnable, preview, cacheDir))
                        .setExtractorsFactory(new DefaultExtractorsFactory())
                        .setCustomCacheKey(contentUri.getPath())
                        .createMediaSource(contentUri);`
     .setCustomCacheKey(contentUri.getPath()) 这个就是自定义key 
    在  ExoSourceManager 110+ 行
