### ISSUE TITLE
使用网线网络播放视频提示当前使用移动网络播放，继续播放将消耗流量

### ISSUE THREAD

**Issue by Achenglove** [CarGuo/GSYVideoPlayer#1885]
## 问题描述：

会议平板使用网线连接机子，播放视频时经常提示当前使用移动网络播放，继续播放将消耗流量

## 问题机型/系统：

Android5.1

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:6.0.1'

**Comment by CarGuo** [comment]
因为内部判断方法只判断了wifi，你继承后重写判断方法就可以了。

**Comment by Achenglove** [comment]
继承哪一个类？

**Comment by CarGuo** [comment]
你用的哪个player类就继承哪个，比如standardxxxx

**Comment by Achenglove** [comment]
![image](https://user-images.githubusercontent.com/26593441/54573738-77c42000-4a28-11e9-9661-81d1d43b7063.png)

**Comment by CarGuo** [comment]
你继承后直接重写 isShowNetConfirm 方法就好了，写你想要的逻辑

**Comment by Achenglove** [comment]
网线连接的网络类型是什么？平时手机判断的网络类型不是有WIFI、2G、3G、4G

**Comment by CarGuo** [comment]
是的，平常是2G，3G，4G，wifi

**Comment by Achenglove** [comment]
我现在使用的会议平板是使用网线的网络，但是还是会提示当前使用移动数据网络，我想在使用网线的网络情况下去掉这个提示，那么怎么判断当前网络是网线的网络？
