### ISSUE TITLE
列表自动播放

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#1886]
你好 请问一下 如何实现视频List自动播放 最后一个播放完 又继续播放第一个?

**Comment by CarGuo** [comment]
参考detailListPlayer，在基础上实现最后一个回到第一个

**Comment by Born-alone** [comment]
![图片](https://user-images.githubusercontent.com/25575326/54574290-beb31500-4a2a-11e9-8c6e-90d891acd877.png)
你好 请问如何在回到第一个 在重新setUp一遍？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/217ee3edce530af6aebd378e1588032c11a45a49/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/ListGSYVideoPlayer.java#L145


https://github.com/CarGuo/GSYVideoPlayer/blob/217ee3edce530af6aebd378e1588032c11a45a49/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/ListGSYVideoPlayer.java#L154

**Comment by XinStudent** [comment]
我想问下，demo里的viewPager2的给item设置封面还不行是嘛
