### ISSUE TITLE
rtsp播放一段时间后延时3,4秒的问题

### ISSUE THREAD

**Issue by azxcffdgadf** [CarGuo/GSYVideoPlayer#1888]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

rtsp播放一段时间后延时3,4秒的问题

## 问题机型/系统：

 真机 小米6 Android8.0,荣耀9 Android 8.0

## GSY依赖版本

    api "com.shuyu:gsyVideoPlayer-java:6.0.1"
    api "com.shuyu:GSYVideoPlayer-exo2:6.0.1"
    api "com.shuyu:gsyVideoPlayer-ex_so:6.0.1"

## Demo中的复现步骤

Demo中的DetailPlayer页面打开后过一段时间会出现这个问题。

问题代码：(如果有)
==============================>详情:
首先用你原来的DetailPlayer不修改任何代码;开始播放rtsp延时1秒左右,还有时花屏,播放一段时间后延时有3到4秒的样子;
然后:在DetailPlayer中,我加入如下代码:
      PlayerFactory.setPlayManager(IjkPlayerManager.class);
      CacheFactory.setCacheManager(ProxyCacheManager.class);
      GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);
      GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);
      VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
      List<VideoOptionModel> list = new ArrayList<>();
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 8);
      list.add(videoOptionModel);
      videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
      list.add(videoOptionModel);
      GSYVideoManager.instance().setOptionModelList(list);

开始时延时1秒以内,过了一会儿延时就有3,4秒的延时了.请问怎么优化.你这边的所有文档我都仔细阅读过;
优化如上我都加了.怎么解决?

**Comment by CarGuo** [comment]
这个如果ffmpeg的配置无法解决，那么只能去改ijk的ffplay了
