### ISSUE TITLE
实现有试看，试看结束后弹出开通VIP弹框的效果(像腾讯视频播放器那样)，需要怎样实现呢？

### ISSUE THREAD

**Issue by Achenglove** [CarGuo/GSYVideoPlayer#189]

**Comment by fzxm** [comment]
我也想知道 大神给个思路?

**Comment by CarGuo** [comment]
思路的话，我只能说你不是vip的，首先代码里缓存需要关闭，然后比如在请求的时候加上header，校验header来给你放流，在播放结束的时候弹出提示。

**Comment by Achenglove** [comment]
不是很理解，能具体讲讲怎么添加吗， 那个播放时间怎么控制呢？求帮助，急用

**Comment by CarGuo** [comment]
@Achenglove 比如你在请求的header加上Range=0-3333 这个段的数据，服务端只返回这部分流给你，类似断点下载

**Comment by Achenglove** [comment]
像我们请求数据时，基本都是请求json数据包，然后拿到json对象里面的视频URL就进行播放，你所说的加上Header是在请求网络数据(json)时，添加请求头？还是对拿到的视频URL添加header呢？

**Comment by GadusBetter** [comment]
楼主解决了吗  我现在也碰到这样的需求了，分享一下呗

**Comment by MrTrying** [comment]
@Achenglove 可以在更新`seekbar`的`timer`里面添加一个`progress`的`callback`，这样可以监听时间，在播放器的父布局中添加一个遮盖， 播放就可以了

**Comment by MrTrying** [comment]
@CarGuo 视频前贴广告的实现类似与VIP，只是在视频播放前显示而已。但是暂停出现的那种广告，暂时还没有做过，不过感觉这个需求还是不应该在播放器中完成，做了满足不了大众的需求

**Comment by yangchong211** [comment]
关于vip这个功能，我已经实现了，可以参考代码：https://github.com/yangchong211/YCVideoPlayer

**Comment by CarGuo** [comment]
目前已经外放了GSYVideoProgressListener，你可以这个做简单的实现，不过最好的其实是设置mapheader，通过HTTP的header指定range，这样才是最安全的最保险的

**Comment by darkrevier** [comment]
@CarGuo setUpLazy中可以添加header  是不是预加载可以用header实现？
