### ISSUE TITLE
非全屏静音播放仍然占用手机音频输出

### ISSUE THREAD

**Issue by thirtyyuan** [CarGuo/GSYVideoPlayer#1890]
## 问题描述：

RecyclerView 中自动播放的 Demo 非全屏静音播放仍然占用系统音频输出（暂时没找到相关 issue）

## 问题机型/系统：

OnePlus 5T，Android 9.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'`

## Demo中的复现步骤

Demo 中使用 RecyclerView 有关的两个示例，在第三方音乐播放器先播放的情况下，再点击列表中的视频进行播放，视频虽然已经静音，但是仍然占用了音频输出，导致第三方音乐播放器暂停播放。

**Comment by CarGuo** [comment]
这个应该是和代码中的audioManager有关，你可以看看它相关的

**Comment by thirtyyuan** [comment]
好的，我先看看，感谢！

**Comment by savage-lin** [comment]
> 好的，我先看看，感谢！

哥，后来你是怎么处理的？

**Comment by thirtyyuan** [comment]
> > 好的，我先看看，感谢！
> 
> 哥，后来你是怎么处理的？

查一下相关使用就知道了，比如：`mAudioManager.requestAudioFocus(null, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);`
