### ISSUE TITLE
android 8.0以下手机 播放直播流过程中，点击全屏按钮  app闪退

### ISSUE THREAD

**Issue by haihaiyun** [CarGuo/GSYVideoPlayer#1894]
## 问题描述：

 GSYVideoPlayer 6.0.2 的版本，华为麦芒5 华为畅享7plus 和 红米4X  ZUK-Z1 播放直播流过程中，点击全屏按钮  app会闪退。

## 问题机型/系统：

华为麦芒5 华为畅享7plus 和 红米4X  ZUK-Z1

## GSY依赖版本

 GSYVideoPlayer 6.0.2

## Demo中的复现步骤

播放直播流过程中，点击全屏按钮  app会闪退

## 问题log（如果有）

[log.txt](https://github.com/CarGuo/GSYVideoPlayer/files/2990696/log.txt)

**Comment by haihaiyun** [comment]
OPPO R9sk  存在类似问题

**Comment by CarGuo** [comment]
demo会有问题？没复现呢
