### ISSUE TITLE
minSdkVersion  16能帮忙做下兼容吗

### ISSUE THREAD

**Issue by hongyancode** [CarGuo/GSYVideoPlayer#1895]
## 问题描述：

添加依赖时发生错误
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.shuyu:gsyVideoPlayer-java:7.0.0-beta1] C:\Users\Administrator\.android\build-cache\12135da0cf278bc47947b3c300bd1bc58f8925fc\output\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.shuyu.gsyvideoplayer" to force usage

## 问题机型/系统：
 classpath 'com.android.tools.build:gradle:2.3.3'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

compileSdkVersion 27
    buildToolsVersion "27.0.3"
    defaultConfig {
        applicationId "com.xx.xx,xx"
        minSdkVersion 16
        targetSdkVersion 22

## GSY依赖版本

    //完整版引入
    compile 'com.shuyu:GSYVideoPlayer:7.0.0-beta1'

## Demo中的复现步骤

manifest  添加了 

    <uses-sdk
        android:minSdkVersion="16"
        tools:overrideLibrary="com.shuyu.gsyvideoplayer.lib" />

问题代码：(如果有)
```
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.shuyu:gsyVideoPlayer-java:7.0.0-beta1] C:\Users\Administrator\.android\build-cache\12135da0cf278bc47947b3c300bd1bc58f8925fc\output\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.shuyu.gsyvideoplayer" to force usage

## 问题log（如果有）

Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.shuyu:gsyVideoPlayer-java:7.0.0-beta1] C:\Users\Administrator\.android\build-cache\12135da0cf278bc47947b3c300bd1bc58f8925fc\output\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.shuyu.gsyvideoplayer" to force usage

**Comment by CarGuo** [comment]
你只依赖java和so，不依赖exoplayer，然后强制降低依赖

**Comment by Achenglove** [comment]
@hongyancode 你处理好这个兼容问题了吗？我已遇到这个问题

**Comment by CandyYoung** [comment]
@CarGuo 请问，项目中已编译好的so最低支持版本是多少？

**Comment by CarGuo** [comment]
单纯so的话16可以的

**Comment by CandyYoung** [comment]
> 单纯so的话16可以的

14可以吗？

**Comment by CarGuo** [comment]
@CandyYoung  可以
