### ISSUE TITLE
销毁问题

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#1896]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

悬浮窗 播放完毕后销毁FLoatingPlayerview里的内容是在哪儿进行销毁的

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.0.0-beta1'

**Comment by CarGuo** [comment]
销毁内容？

**Comment by oveeeee** [comment]
> 销毁内容？

悬浮窗播放时，播放结束会把FloatingVideo移除

**Comment by CarGuo** [comment]
这个监听结束之后关闭不就好了？
