### ISSUE TITLE
暂停后黑屏问题

### ISSUE THREAD

**Issue by QiChunJie** [CarGuo/GSYVideoPlayer#1898]
在缓冲时， 滚出屏幕， 缓冲完成后暂停（此时依然在屏幕之外）， 然后滚进屏幕， 发现是黑屏。
showPauseCover设置为true, 也debug了， showPauseCover正常走到了drawBitmap; releasePauseCover也没走回收， 但是滚回去是黑屏。 版本6.0.1

**Comment by CarGuo** [comment]
因为 showPauseCover 是在暂停的时候才会去 drawBitmap，缓冲时并没有，而滑出屏幕draw的就是黑的

**Comment by QiChunJie** [comment]
我看了以下， 确实是在暂停的时候绘制的封面， 猜测应该和不可见时， 会destroy TextureView有关， 有什么办法能够使这种情况和在暂停时滑出屏幕，滑回来之后一切正常效果相同吗？

**Comment by CarGuo** [comment]
你滑出屏幕的时候手动调用生产封面咯

**Comment by QiChunJie** [comment]
也是个办法， 在onSurfaceAvailable调用添加封面 ， 感谢！
