### ISSUE TITLE
请教一下  视频两侧有黑边怎么设置让其铺满

### ISSUE THREAD

**Issue by QueryGad** [CarGuo/GSYVideoPlayer#190]
我们是双端开发 ，我看了苹果端的两侧没有黑边，应该是设置的问题吧？想请作者帮下忙！

**Comment by CarGuo** [comment]
请问可以提供下截图吗

**Comment by CarGuo** [comment]
尝试1.6.5

**Comment by dovginka** [comment]
请问1.6.5怎么让其铺满屏幕，有什么方法吗

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer/src/main/java/com/shuyu/gsyvideoplayer/utils/GSYVideoType.java
