### ISSUE TITLE
列表详情切换，跳转详情，或者从详情页返回有闪烁现象

### ISSUE THREAD

**Issue by hanliangel** [CarGuo/GSYVideoPlayer#1901]
## 问题描述：
从列表页跳转到详情页，执行共享元素过度动画，视频播放画面会在动画开始的一瞬间，闪烁一下，包括你的Demo也会。
从详情页返回列表页的时候，会执行返回的共享元素动画，目前我在详情Activity的onDestory当中执行将播放的surface切换到列表的操作。
但是在共享动画完成，切换的一瞬间，会露出列表页播放器位置之前的画面。看起来就是画面剧烈闪烁了一下。
请问这种场景和需求，你有建议怎么完成么？如果你需要看效果，我可以在你的Demo上做修改，给你提交个pull request，方便你进行查看。

**Comment by CarGuo** [comment]
所有机型都会？貌似我这边看到的不会闪烁一下

**Comment by hanliangel** [comment]
从列表跳转到详情，跳帧不明显，因为视频相近两帧的画面比较相似。
但是从详情页返回列表页会很明显，因为你的Demo里面返回列表页后就直接停止播放了，所以看不出来。
你可以尝试吧返回之后再列表页的播放也加上，我在这块实现的方案会闪烁明显的原因是：跳转详情的一瞬间残留在列表的画面，和在详情页停留几秒然后返回到列表时的一瞬间画面，由于相隔时间较长，差异较大，所以会感觉有一个闪烁的效果。
建议：希望你那有时间的话，能在demo中加入一个从详情返回后在列表中继续播放的效果，测试视频可以选一个背景会变化的视频，目前的演讲视频，背景一直没变，可能体现不出来这种效果。因为对这套框架的工作流程机制，还不是非常了解，所以我自己比较难找到确切的原因并解决。thankyou~~

**Comment by CarGuo** [comment]
是详情返回到列表，列表可以尝试先清空surface画面，让它纯黑色的，试试这样会不好一些。
