### ISSUE TITLE
网络视频播放，有时单击会调用setmVideoPlayPreparedListener的onPlayPrepared方法

### ISSUE THREAD

**Issue by askskysun** [CarGuo/GSYVideoPlayer#1905]
## 问题描述：

网络视频播放，有时单击会调用setmVideoPlayPreparedListener的onPlayPrepared方法

## 问题机型/系统：

真机 HUAWEI_JDN-W09

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤
不稳定重现

**Comment by CarGuo** [comment]
貌似我目前无法重现问题
