### ISSUE TITLE
重写StandardGSYVideoPlayer 的onClickUiToggle 再次点击退出全屏用哪个方法

### ISSUE THREAD

**Issue by miniframework** [CarGuo/GSYVideoPlayer#1908]
public class myStandardGSYVideoPlayer extends StandardGSYVideoPlayer {

    Context mcontext;

    public myStandardGSYVideoPlayer(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

    public myStandardGSYVideoPlayer(Context context) {
        super(context);
    }

    public myStandardGSYVideoPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public void setMyContext(Context context) {
        mcontext = context;
    }
    @Override
    protected void onClickUiToggle() {

        if(!mIfCurrentIsFullscreen) {
            startWindowFullscreen(mcontext, true, true);
            super.onClickUiToggle();
        } else {
            hideNavKey(mContext);

        }

    }
}

**Comment by miniframework** [comment]
@Override
    protected void onClickUiToggle() {

        if(!mIfCurrentIsFullscreen) {
            Log.d("myStandardGSYVi", ""+mIfCurrentIsFullscreen);
            super.startWindowFullscreen(mcontext, true, true);
            super.onClickUiToggle();
        } else {
            Log.d("myStandardGSYVi", ""+mIfCurrentIsFullscreen);
            super.onBackFullscreen();
        }
    }
 这样不行 onBackFullscreen()

**Comment by CarGuo** [comment]
你时类似detailplayer那种播放模式吧？如果是你需要把点击回调出来

```
 @Override
    public void onBackPressed() {

        if (orientationUtils != null) {
            orientationUtils.backToProtVideo();
        }

        if (GSYVideoManager.backFromWindowFull(this)) {
            return;
        }
        super.onBackPressed();
    }


```

**Comment by miniframework** [comment]
> 你时类似detailplayer那种播放模式吧？如果是你需要把点击回调出来
> 
> ```
>  @Override
>     public void onBackPressed() {
> 
>         if (orientationUtils != null) {
>             orientationUtils.backToProtVideo();
>         }
> 
>         if (GSYVideoManager.backFromWindowFull(this)) {
>             return;
>         }
>         super.onBackPressed();
>     }
> ```

   @Override
    protected void onClickUiToggle() {

        if(!mIfCurrentIsFullscreen) {
            Log.d("myStandardGSYVi", ""+mIfCurrentIsFullscreen);
            gsyBaseVideoPlayer = startWindowFullscreen(mcontext, false, true);

        } else {
            Log.d("myStandardGSYVi", ""+mIfCurrentIsFullscreen);
            backFromWindowFull(mcontext);
        }
        super.onClickUiToggle();

    }

    public  void backFromWindowFull(Context context) {

            if (GSYVideoManager.instance().lastListener() != null) {
                GSYVideoManager.instance().lastListener().onBackFullscreen();
            }

    }

我是这样弄的

**Comment by CarGuo** [comment]
不是很理解
