### ISSUE TITLE
如何进入熄屏

### ISSUE THREAD

**Issue by GIVEWAYTO** [CarGuo/GSYVideoPlayer#1909]
## 问题描述：

由于我用来只当音频库使用，所以在音乐播放的时候，不会影响手机自带的熄屏效果，这需要怎么设置呢？

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

com.shuyu:gsyVideoPlayer-java:6.0.3

**Comment by CarGuo** [comment]
GSYVideoManager.instance().getCurPlayerManager().getMediaPlayer().setScreenOnWhilePlaying();

**Comment by GIVEWAYTO** [comment]
GSYVideoManager.instance().getCurPlayerManager().getMediaPlayer().setScreenOnWhilePlaying(false);的调用时机是什么？

因为现在我调用后是报getMediaPlayer()空指针异常，或者是需要怎么初始化，因为我看源码：
GSYVideoBaseManager类中的initVideo  直接设置的  说明是有值得

IMediaPlayer mediaPlayer = playerManager.getMediaPlayer();
            mediaPlayer.setOnCompletionListener(this);
            mediaPlayer.setOnBufferingUpdateListener(this);
            mediaPlayer.setScreenOnWhilePlaying(true);
            mediaPlayer.setOnPreparedListener(this);
            mediaPlayer.setOnSeekCompleteListener(this);
            mediaPlayer.setOnErrorListener(this);
            mediaPlayer.setOnInfoListener(this);
            mediaPlayer.setOnVideoSizeChangedListener(this);
            mediaPlayer.prepareAsync();

**Comment by GIVEWAYTO** [comment]
Attempt to invoke interface method 'tv.danmaku.ijk.media.player.IMediaPlayer com.shuyu.gsyvideoplayer.player.IPlayerManager.getMediaPlayer()' on a null object reference

**Comment by CarGuo** [comment]
在onPrepared内设置

**Comment by GIVEWAYTO** [comment]
还是不行，已经进入onPrepared进入设置了

public class AudioPlayer extends StandardGSYVideoPlayer {
    public AudioPlayer(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

    public AudioPlayer(Context context) {
        super(context);
    }

    public AudioPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void onPrepared() {
        super.onPrepared();

          GSYVideoManager.instance().getCurPlayerManager().getMediaPlayer().setScreenOnWhilePlaying(false);
        
    }
}

**Comment by GIVEWAYTO** [comment]
这次不报空指针，但是没有熄屏的效果

**Comment by CarGuo** [comment]
推荐通过自定义PlayerManager解决
