### ISSUE TITLE
循环播放问题

### ISSUE THREAD

**Issue by ZzjBeatYou** [CarGuo/GSYVideoPlayer#191]
设置```setLooping(true)```后拖动底部seekbar出现的问题

- 视频的mLoadingProgressBar不会显示
- 并且暂停时拖动,画面不会切到拖动时间的那一帧

### `找了好久才发现是setLooping的问题- -`

**Comment by CarGuo** [comment]
确实有有这个问题，后面修复下

**Comment by CarGuo** [comment]
1.6.5 fix
