### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by azxcffdgadf** [CarGuo/GSYVideoPlayer#1910]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
你在群里说过:延迟的问题一般要不就是服务器配合，要不就是切换内核，要不就是直接配置缓冲，要不就是直接改ffplay.我这边是局域网,rtsp视频流,360p的视频.
开始时延时1秒以内,过了一会儿延时就有3,4秒的延时了.请问怎么优化

## 问题机型/系统：

 真机 三星s5 Android6.0.1

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'

//是否需要ExoPlayer模式
implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.1'

//更多ijk的编码支持
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.1'

## Demo中的复现步骤

Demo中的SimplePlayer页面打开后会出现这个问题。

问题代码：(如果有)
    String source1 = "rtsp://192.168.1.2/live";
    videoPlayer.setUp(source1, true, "测试视频");

    PlayerFactory.setPlayManager(IjkPlayerManager.class);

    VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,
        "rtsp_transport", "tcp");
    List<VideoOptionModel> list = new ArrayList<>();
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags",
        "prefer_tcp");
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,
        "allowed_media_types", "video"); //根据媒体类型来配置
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size",
        1316);
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf",
        1);  // 无限读
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,
        "analyzemaxduration", 100);
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
    list.add(videoOptionModel);
    //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering",
        0);
    list.add(videoOptionModel);

    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max-buffer-size",
        20000);
    list.add(videoOptionModel);

    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "min-frames",
        500);
    list.add(videoOptionModel);

     videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max_cached_duration", 2000);
    list.add(videoOptionModel);

    GSYVideoManager.instance().setOptionModelList(list);
其他代码一样

## 问题log（如果有）

03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=00 [
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=89 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=89 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=10 []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=f7 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=d9 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=41 [A]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=13 []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=4c [L]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=22 ["]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=04 []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=37 [7]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=da [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=97 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=c8 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=89 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=a8 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=ab [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=17 []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=80 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=a6 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=65 [e]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=78 [x]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=f3 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=4a [J]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=35 [5]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=fe [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=7b [{]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=0c []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=bf [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=8b [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=fe [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=bc [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=31 [1]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=13 []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=9d [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=5d []]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=ed [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=fb [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=a4 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=c6 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=0f []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=00 [
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=58 [X]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=a9 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=7a [z]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=14 []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=00 [
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=15 []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=8a [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=4e [N]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=a7 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=ca [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=26 [&]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=c8 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=fe [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=fc [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=bd [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=96 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=c3 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=2b [+]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=82 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=19 []
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=94 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=95 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=38 [8]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=90 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=a4 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=84 [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=64 [d]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=6a [j]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=64 [d]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=28 [(]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=dc [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=0 c=dc [�]
03-25 20:45:12.231 29730-30377/com.example.gsyvideoplayer D/IJKMEDIA: ct_type:1 pic_struct:0
03-25 20:45:12.231 29730-30384/com.example.gsyvideoplayer D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
03-25 20:45:12.231 29730-30384/com.example.gsyvideoplayer D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 1
03-25 20:45:12.231 29730-30384/com.example.gsyvideoplayer D/IJKMEDIA: ct_type:1 pic_struct:0
03-25 20:45:12.231 29730-30384/com.example.gsyvideoplayer D/IJKMEDIA: no picture ooo
03-25 20:45:12.231 29730-30384/com.example.gsyvideoplayer I/IJKMEDIA: concealing 1218 DC, 1218 AC, 1218 MV errors in P frame
03-25 20:45:12.241 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: tcp_read_packet:
03-25 20:45:12.241 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=0 c=dc [�]
03-25 20:45:12.351 29730-30377/com.example.gsyvideoplayer I/IJKMEDIA: ffp_toggle_buffering: completed: OK
03-25 20:45:12.351 29730-30375/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
03-25 20:45:12.351 29730-30375/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_COMPLETED:
03-25 20:45:12.351 29730-29730/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
03-25 20:45:12.351 29730-29730/com.example.gsyvideoplayer I/GSYVideoPlayer: 6116562------------------------------ dismiss CURRENT_STATE_AUTO_COMPLETE
03-25 20:45:12.351 29730-29730/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToCompleteShow
03-25 20:45:12.361 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: tcp_read_packet:
03-25 20:45:12.361 29730-30377/com.example.gsyvideoplayer V/IJKMEDIA: ret=0 c=dc [�]
03-25 20:45:12.361 29730-29764/com.example.gsyvideoplayer E/libGLESv1: HWUI Protection: wrong call from hwui context F:ES1-glDeleteTexturesSEC
03-25 20:45:12.361 29730-29730/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
03-25 20:45:12.361 29730-29730/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
03-25 20:45:12.361 29730-29730/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_surface()
03-25 20:45:12.361 29730-29730/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
03-25 20:45:12.361 29730-30366/com.example.gsyvideoplayer D/libEGL: eglTerminate EGLDisplay = 0x9e26538c
03-25 20:45:12.361 29730-30366/com.example.gsyvideoplayer D/libEGL: eglTerminate EGLDisplay = 0x9e26538c
03-25 20:45:12.361 29730-29730/com.example.gsyvideoplayer D/libEGL: eglTerminate EGLDisplay = 0xbeff8cdc
开始时延时1秒以内,过了一会儿延时就有3,4秒的延时了.请问怎么优化.谢谢

**Comment by CarGuo** [comment]
如果服务器没办法配置，那么你可以通过ijkplayer的ffplay定制修改，主要是buffer，追帧，同步等

**Comment by azxcffdgadf** [comment]
buffer,追帧,同步分别是那些参数呢?

**Comment by azxcffdgadf** [comment]
比如是:在你这个优化的基础上加那些参数呢?
    VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,
        "rtsp_transport", "tcp");
    List<VideoOptionModel> list = new ArrayList<>();
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags",
        "prefer_tcp");
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,
        "allowed_media_types", "video"); //根据媒体类型来配置
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size",
        1316);
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf",
        1);  // 无限读
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,
        "analyzemaxduration", 100);
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
    list.add(videoOptionModel);
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
    list.add(videoOptionModel);
    //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
    videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering",
        0);
    list.add(videoOptionModel);
谢谢?

**Comment by CarGuo** [comment]
不是参数，你要去看ijkplayer的ffplay源码

**Comment by azxcffdgadf** [comment]
意思是通过类似:videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);这样仅仅写option是不行的,要修改ffplay的c语言源码?才行?是吗?

**Comment by CarGuo** [comment]
是的，细节上的调整直接跳转 https://github.com/bilibili/ijkplayer/tree/master/ijkmedia/ijkplayer，然后重新打包so

**Comment by azxcffdgadf** [comment]
好的,谢谢
