### ISSUE TITLE
读取播放raw文件夹视频

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#1911]
## 问题描述：

读取播放 raw 文件夹中视频 播放错误

## GSY依赖版本

om.shuyu:GSYVideoPlayer:6.0.1

问题代码：(如果有)
![图片](https://user-images.githubusercontent.com/25575326/54964674-5626e380-4fa8-11e9-962e-319769fe4517.png)

## 问题log（如果有）
![图片](https://user-images.githubusercontent.com/25575326/54964713-722a8500-4fa8-11e9-8132-ad658f63b915.png)

**Comment by CarGuo** [comment]
先确定时视频问题还是路径问题。
demo中的raw下视频是否可以播放？

**Comment by Born-alone** [comment]
![图片](https://user-images.githubusercontent.com/25575326/54967823-8922a480-4fb3-11e9-9411-5232e21131a2.png)

把这个链接 放在 DetailPlayer 里面播放是没有问题的 

![图片](https://user-images.githubusercontent.com/25575326/54967862-ace5ea80-4fb3-11e9-93ce-5a6750ddec71.png)

切换到 DetailListPlayer 就还是播不了 Demo中的raw下视频亦是如此

![图片](https://user-images.githubusercontent.com/25575326/54967973-fb938480-4fb3-11e9-9f46-1712cbd3cf39.png)

**Comment by CarGuo** [comment]
因为cache设置为true了，cache要设置为false
