### ISSUE TITLE
播放网易云音乐，从全屏状态下切换至横屏会同时播放音乐，有两个声音

### ISSUE THREAD

**Issue by woshiyizhijiao** [CarGuo/GSYVideoPlayer#1912]
## 问题描述：
播放网易云音乐的时候，去打开简单详情1或者简单详情2开始播放。音乐暂停
当前切换到全屏，这个时候我如果返回到竖屏界面的话，音乐也会同时播放，有两个声音

## 问题机型/系统：
三星s9 9.0 
华为荣耀8 8.0  
小米 note 4x 6.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

简单详情1，简单详情2

**Comment by CarGuo** [comment]
推测应该是切换view的时候，AudioManager释放焦点导致的

**Comment by woshiyizhijiao** [comment]
有什么好的处理方式么？
切换的时候一定会释放焦点么？
我尝试着在playing回调中调用
`mAudioManager.requestAudioFocus(onAudioFocusChangeListener, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);`
但是这样旋转屏幕的时候会自动暂停，我还要处理这个，感觉不是很好

**Comment by CarGuo** [comment]
我找个时间看看吧，其实最高就是你重写了audiomanager，然后判断横竖屏，在横屏的时候manager传递过去的，然后横屏销毁时判断视频是否结束去决定是否销毁。
