### ISSUE TITLE
点击退出全屏的问题

### ISSUE THREAD

**Issue by miniframework** [CarGuo/GSYVideoPlayer#1918]
@Override
    protected void onClickUiToggle() {
        if (mIfCurrentIsFullscreen) {
            if (!mLockCurScreen) {       
                GSYVideoManager.backFromWindowFull(mcontext);
//                if (GSYVideoManager.instance().lastListener() != null) {
//                  GSYVideoManager.instance().lastListener().onBackFullscreen();
//                  }
            }
        }
  }

如果用GSYVideoManager.backFromWindowFull  这个就退出到列表界面，  如果用我注释的写法就没问题，就能从全屏退出到原始播放。为什么不能用GSYVideoManager.backFromWindowFull

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1919
