### ISSUE TITLE
Bug # resolveNormalVideoShow  line 366 没判断mFullscreenButton != null

### ISSUE THREAD

**Issue by miniframework** [CarGuo/GSYVideoPlayer#1919]
自定义布局
  
 @Override
    public int getLayoutId() {
        return R.layout.myvideo;   //myvideo  去掉了全屏按钮。 full  
    }

设置点击屏幕全屏

startWindowFullscreen   里面判断了 mFullscreenButton != null

再次点击退出全屏onBackFullscreen  －－》 resolveNormalVideoShow 里面没判断
mFullscreenButton ＝＝null 

getFullscreenButton().setImageResource(getEnlargeImageRes());

导致null

**Comment by CarGuo** [comment]
收到
