### ISSUE TITLE
多个界面同时播放视频

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#1920]
两个界面 都需要播放视频
 A 界面进入后自动播放视频 -> 点击跳转至 B 界面 也需要播放视频  
当我 B  界面关闭后 回到 A 界面时 视频继续播放不了
应该怎么处理 
B界面试过了用原生 VideoView去播放 但回到A界面时 还是继续播放不了

![图片](https://user-images.githubusercontent.com/25575326/55058450-f2cfab00-50a6-11e9-9a87-8487c276f1fb.png)

**Comment by CarGuo** [comment]
正常，因为播放的时候失去了音频焦点，你可以看看demo中的多任务

**Comment by Born-alone** [comment]
好的 多谢
