### ISSUE TITLE
怎么监控播放错误（比如网络超时后），再去改变界面UI，提示用户

### ISSUE THREAD

**Issue by zhangqaing** [CarGuo/GSYVideoPlayer#1921]
你好，有以下问题需要您解答:
## 问题机型/系统：

 真机 华为p10  Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'`

## Demo中的复现步骤

怎么监控播放错误（比如网络超时后），再去改变界面UI，提示用户,怎么去获取播放状态，再去改变界面ui,提示用户，谢谢

**Comment by zhangqaing** [comment]
用的是SmartPickVideo 这个控件

**Comment by zhangqaing** [comment]
已解决

**Comment by CarGuo** [comment]
继承重写 onError 或者  setStateAndUi(); case CURRENT_STATE_ERROR

**Comment by zhangqaing** [comment]
你好，就是我重写了onError后，替换那个播放图标会出现两个图标重复，我在监控到错误后，怎么更换播放图标后，再次点击后又开始播放，谢谢

**Comment by CarGuo** [comment]
如果是播放按键，类似这个

```
 @Override
    protected void updateStartImage() {
        if (mIfCurrentIsFullscreen) {
            if(mStartButton instanceof  ImageView) {
                ImageView imageView = (ImageView) mStartButton;
                if (mCurrentState == CURRENT_STATE_PLAYING) {
                    imageView.setImageResource(R.drawable.video_click_pause_selector);
                } else if (mCurrentState == CURRENT_STATE_ERROR) {
                    imageView.setImageResource(R.drawable.video_click_play_selector);
                } else {
                    imageView.setImageResource(R.drawable.video_click_play_selector);
                }
            }
        } else {
            super.updateStartImage();
        }
    }
```

**Comment by zhangqaing** [comment]
你好在onerror 重写方法里ENPlayView enPlayView = (ENPlayView) mStartButton;
        enPlayView.setDuration(2000);
        enPlayView.setBackgroundResource(R.drawable.duopinggb);还是会有两个图片重复，麻烦你了，能方便价格微信么？谢谢

**Comment by CarGuo** [comment]
你直接重写 updateStartImage 根据 mCurrentState == CURRENT_STATE_ERROR判断

**Comment by zhangqaing** [comment]
其中enPlayView.setBackgroundResource(R.drawable.video_selector);  就是我想替换的图片，但是还是有两个图片重叠，就是最前面我就有这个问题

@Override
    protected void updateStartImage() {
        if (mIfCurrentIsFullscreen) {
            if(mStartButton instanceof  ImageView) {
                ImageView imageView = (ImageView) mStartButton;
                if (mCurrentState == CURRENT_STATE_PLAYING) {
                    imageView.setImageResource(R.drawable.video_click_pause_selector);
                } else if (mCurrentState == CURRENT_STATE_ERROR) {
                    imageView.setImageResource(R.drawable.video_click_play_selector);
                } else {
                    imageView.setImageResource(R.drawable.video_click_play_selector);
                }
            }
        } else {
            if (mStartButton instanceof ENPlayView) {
                ENPlayView enPlayView = (ENPlayView) mStartButton;
                enPlayView.setDuration(500);
                if (mCurrentState == CURRENT_STATE_PLAYING) {
                    enPlayView.play();
                } else if (mCurrentState == CURRENT_STATE_ERROR) {
                   
                    enPlayView.setBackgroundResource(R.drawable.video_selector);
                } else {
                   
                    enPlayView.setBackgroundResource(R.drawable.video_selector);
                }
            } else if (mStartButton instanceof ImageView) {
                ImageView imageView = (ImageView) mStartButton;
                if (mCurrentState == CURRENT_STATE_PLAYING) {
                    imageView.setImageResource(com.shuyu.gsyvideoplayer.R.drawable.video_click_pause_selector);
                } else if (mCurrentState == CURRENT_STATE_ERROR) {
                    imageView.setImageResource(com.shuyu.gsyvideoplayer.R.drawable.video_click_error_selector);
                } else {
                    imageView.setImageResource(com.shuyu.gsyvideoplayer.R.drawable.video_click_play_selector);
                }
            }
        }
    }

**Comment by CarGuo** [comment]
类似独立业务问题，只能你自己调适了
