### ISSUE TITLE
缓存问题，一个视频看了一会退出，重新打开，从0缓存么？

### ISSUE THREAD

**Issue by miniframework** [CarGuo/GSYVideoPlayer#1924]
1.一个视频看了一会退出，重新打开，从0缓存么？
2.看了一会，退出，然后打开拖动到快完。怎么缓存。
3.直接拖动到最后，会缓存么。
4.缓存是能分段么？一段从本地读，没的话，从服务器读。

**Comment by CarGuo** [comment]
如果设置了本地缓存，会从缓存度，目前两种缓存模式还不大一样。
一种是一个文件，通过region和offet去写文件，而另外一种事会有多个文件，具体你看源码吧…
