### ISSUE TITLE
视频生命周期问题

### ISSUE THREAD

**Issue by QiChunJie** [CarGuo/GSYVideoPlayer#1926]
GSYVideoPlayer框架， 在播放中断网， 在报Error的时候， 走的周期是changeUiToNormal -> changeUiToPreparing -> changeUiToError。 为什么在好多情况下， 都是返回到初始状态，然后重新准备， 准备完成后Buffer, 才seek到保存的位置呢？ 感觉这样会造成好多显示的问题。 想问一下， 这个框架就是这么设计的吗？

**Comment by CarGuo** [comment]
因为断网后，原本的ffplay连接就断开了，需要重新构建一个新的去播放

**Comment by QiChunJie** [comment]
哦，原来是这样。不过这样确实会导致显示问题。 有没有什么办法能取到changUiToError时的最后一个帧吗？ 现在Error好像就是黑屏了， 然后再次重试， 还是黑色的背景

**Comment by CarGuo** [comment]
你参考源码中的pause cover的做法

**Comment by QiChunJie** [comment]
源码看了， 是从TextureView取的，但是视频看不到的时候已经销毁了，所有取不到帧

**Comment by CarGuo** [comment]
你需要在surface 销毁前获取出来bitmap，然后用image去显示
