### ISSUE TITLE
播放按钮的三角缺了一块

### ISSUE THREAD

**Issue by xusheng927** [CarGuo/GSYVideoPlayer#193]
![qq 20170424094002](https://cloud.githubusercontent.com/assets/8056822/25319585/2f4be17e-28d2-11e7-8ca1-55d90e7a2b9e.jpg)
怎么让它不缺，或者更改播放、暂停的静态图片

**Comment by CarGuo** [comment]
这个哪个版本？？？最新版本中有个NormalGSYVideoPlayer是静态图片的，然后缺一角这个问题最新版本应该也修复了

**Comment by xusheng927** [comment]
这是很久之前发现的问题，没有更新到最新版本就来issue我感到很抱歉。
