### ISSUE TITLE
依赖出现问题

### ISSUE THREAD

**Issue by Achenglove** [CarGuo/GSYVideoPlayer#1930]
## 问题描述：

依赖出现问题

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

问题代码：(如果有)

![image](https://user-images.githubusercontent.com/26593441/55298882-c7f8a480-5462-11e9-87d0-d5ca21a44260.png)

**Comment by CarGuo** [comment]
基本上都是tragetsdk，gradle等的问题，如果懒得查找，只依赖 java 和 so，不依赖exoplayer
