### ISSUE TITLE
使用列表自动播放无声音

### ISSUE THREAD

**Issue by jygsdjflsd** [CarGuo/GSYVideoPlayer#1931]
问题描述：按照demo上使用recyclerview的列表自动播放发现播放没声音，然后测试demo发现只要是列表相关的视频都是只有画面没声音，

        机型：用的是红米note7/android系统9.0，然后又测试了华为v9play/android系统7.0

        依赖版本：com.shuyu:GSYVideoPlayer:6.0.1

        demo上所有与列表播放的视频都没有声音，使用简单播放有声音

**Comment by jygsdjflsd** [comment]
使用最新版implementation 'com.shuyu:GSYVideoPlayer:7.0.0-beta1'还是同样的问题

**Comment by CarGuo** [comment]
demo里做了静音
