### ISSUE TITLE
播放分辨率设置

### ISSUE THREAD

**Issue by jygsdjflsd** [CarGuo/GSYVideoPlayer#1932]
问题描述：因为录制分辨率的原因，摄像头所有支持的分辨率和屏幕分辨率都不一致，页面把播放器设置竖直全屏，因为分辨率问题播放的视频要么宽度不够、要么高度不够，嫩不能设置播放器类似于Imageview的centerCrop效果？

GSY依赖版本： 当前最新版本7.0.0-beta1

**Comment by CarGuo** [comment]
可以，看 GSYVideoType.SCREEN_TYPE_FULL
