### ISSUE TITLE
ava.io.FileNotFoundException  /storage/emulated/0/GSYVideo/15540307959332.jpg (No such file or directory)

### ISSUE THREAD

**Issue by Leavds** [CarGuo/GSYVideoPlayer#1933]
#25202 java.io.FileNotFoundException
/storage/emulated/0/GSYVideo/15540307959332.jpg (No such file or directory)

com.luck.picture.lib.compress.Engine.compress(Engine.java:98)

1 io.reactivex.exceptions.OnErrorNotImplementedException:/storage/emulated/0/GSYVideo/15540307959332.jpg (No such file or directory)
--
2 io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
3 ......
4 Caused by:
5 java.io.FileNotFoundException:/storage/emulated/0/GSYVideo/15540307959332.jpg (No such file or directory)
6 java.io.FileOutputStream.open0(Native Method)
7 java.io.FileOutputStream.open(FileOutputStream.java:301)
8 java.io.FileOutputStream.<init>(FileOutputStream.java:226)
9 java.io.FileOutputStream.<init>(FileOutputStream.java:171)
10 com.luck.picture.lib.compress.Engine.compress(Engine.java:98)
11 com.luck.picture.lib.compress.Luban.get(Luban.java:178)
12 com.luck.picture.lib.compress.Luban.access$1400(Luban.java:24)
13 com.luck.picture.lib.compress.Luban$Builder.get(Luban.java:286)
14 com.luck.picture.lib.PictureBaseActivity$2.apply(PictureBaseActivity.java:217)
15 com.luck.picture.lib.PictureBaseActivity$2.apply(PictureBaseActivity.java:211)
16 io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
17 io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runSync(FlowableObserveOn.java:332)
18 io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:174)
19 io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
20 io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
21 java.util.concurrent.FutureTask.run(FutureTask.java:266)
22 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
23 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
24 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
25 java.lang.Thread.run(Thread.java:764)

这个 什么问题？

**Comment by Leavds** [comment]
使用版本  6.0.2  系统版本 Android 8.1.0,level 27
ROMvivo /FUNTOUCH
CPU架构 armeabi
前后台状态 前台
设备机型VIVO V1813A

**Comment by CarGuo** [comment]
截图没截成功？？本地文件读写权限？

**Comment by Leavds** [comment]
截图？没加截图功能  ，权限应该是有的  没有的话，不应该报这个错

**Comment by CarGuo** [comment]
那很奇怪啊，这里是 /storage/emulated/0/GSYVideo/15540307959332.jpg
