### ISSUE TITLE
在Demo中SimplePlayer设置循环播放后，不循环，且最后一直闪现加载状态

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#1937]

**Comment by ZJLeBron** [comment]
另外请问有多任务播放和单任务的实现区别讲解文档吗

**Comment by CarGuo** [comment]
有测试链接吗？
多任务和单任务在于内核多个和单个。

**Comment by ZJLeBron** [comment]
String source1 = "http://wdquan-space.b0.upaiyun.com/VIDEO/2018/11/22/ae0645396048_hls_time10.m3u8";
        videoPlayer.setUp(source1, true, "测试视频");
        videoPlayer.setLooping(true);
这是我在demo中的simplepalyer中改的，加了一个setLooping（true）就出现上述bug了

**Comment by ZJLeBron** [comment]
我看了MultiSampleVideo和SampleCoverVideo都是继承StandardGSYVideoPlayer的没看明白怎么实现的多任务，能指点一下吗，谢谢

**Comment by CarGuo** [comment]
他们用的  Manager 不同，你可以看看。如果循环问题，可以切换到exoplayer内核试试
```

    @Override
    public GSYVideoViewBridge getGSYVideoManager() {
        CustomManager.getCustomManager(getKey()).initContext(getContext().getApplicationContext());
        return CustomManager.getCustomManager(getKey());
    }
```

**Comment by ZJLeBron** [comment]
setPlayManager
(java.lang.Class<? extends com.shuyu.gsyvideoplayer.player.IPlayerManager>)
in PlayerFactory cannot be applied
to
(tv.danmaku.ijk.media.exo2.Exo2PlayerManager)
切换内核报错

**Comment by CarGuo** [comment]
额····你可以看下为啥报错，类型不匹配还是

**Comment by ZJLeBron** [comment]
> 额····你可以看下为啥报错，类型不匹配还是

类型不匹配

**Comment by CarGuo** [comment]
我这边测试没问题

**Comment by CarGuo** [comment]
我这边测试exoplayer内核设置正常，测试循环播放正常
