### ISSUE TITLE
为什么有时候全屏不了？

### ISSUE THREAD

**Issue by anpoz** [CarGuo/GSYVideoPlayer#194]
有些时候点全屏不能全屏，只能强制把布局转为横向。这个很奇怪，并且按照demo的LandLayoutVideo那样继承StandardGSYVideoPlayer不能全屏，都是出现只是强制转为横屏的情况。

**Comment by anpoz** [comment]
比如这样子

![screenshot_20170424-162902](https://cloud.githubusercontent.com/assets/2825342/25328674/658a0fde-290b-11e7-913f-97fd782873d8.png)

**Comment by CarGuo** [comment]
参考demo中的detailplayer，配置manifest，然后还有configure
