### ISSUE TITLE
播放视频有画面 无声音

### ISSUE THREAD

**Issue by xyZangGit** [CarGuo/GSYVideoPlayer#1941]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
所有测试机  播放这个地址   没有声音 
https://file.shftz.cn:8443/filesystem/download/10/2019/3/26/ce2c7c66-e9eb-42be-adf6-f9008385ea8c.mov/play

## 问题机型/系统：
机型：小米mix2s  安卓9.0   华为荣耀 8X  安卓8.0

## GSY依赖版本
api 'com.shuyu:gsyVideoPlayer-java:6.0.1'
    api 'com.shuyu:gsyVideoPlayer-x64:6.0.1'
    api 'com.shuyu:gsyVideoPlayer-armv7a:6.0.1'
    api 'com.shuyu:gsyVideoPlayer-arm64:6.0.1'
    api 'com.shuyu:gsyVideoPlayer-x86:6.0.1'

## Demo中的复现步骤

问题代码：(如果有)

## 问题log（如果有）

V/IJKMEDIA: stream 0, sample 3878, dts 155080000
    stream 1, sample 7464, dts 155500000
    stream 0, sample 3879, dts 155120000
    stream 1, sample 7464, dts 155500000
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
nal_unit_type: 1, nal_ref_idc: 1

**Comment by CarGuo** [comment]
```
Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, 1536 kb/s
```

ijk 的so 没有打包这种音频格式的，要么自己从根目录两个.sh文件自己添加配置之后重新打包so。
要不尝试切换到 exoplayer 模式

https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md

https://www.jianshu.com/p/bd289e25d272

**Comment by ZJLeBron** [comment]
> ```
> Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, 1536 kb/s
> ```
> ijk 的so 没有打包这种音频格式的，要么自己从根目录两个.sh文件自己添加配置之后重新打包so。
> 要不尝试切换到 exoplayer 模式
> 
> https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md
> 
> https://www.jianshu.com/p/bd289e25d272

我的也是有画面无声音，音频格式 pcm s16 le    切换到Exo2PlayerManager无法播放

**Comment by CarGuo** [comment]
@ZJLeBron  https://github.com/CarGuo/GSYVideoPlayer/issues/1942
