### ISSUE TITLE
请问能否实现一路视频同时渲染到两个textureview上？

### ISSUE THREAD

**Issue by guanbo123456** [CarGuo/GSYVideoPlayer#1944]
请问能否实现一路视频同时渲染到两个textureview上？也就是一路视频在两个view上同步播放

**Comment by CarGuo** [comment]
这个需要你自己做，比如用GLSurfaceView，自己做opengl

**Comment by guanbo123456** [comment]
谢谢大神的回答，能否再说的详细些？

**Comment by CarGuo** [comment]
因为你是需要一路视频绘制到两个画面，所以你需要在一Surface上，把画面数据绘制到B，所以可以用GLSurfaceView把画面数据同步下来绘制过去
