### ISSUE TITLE
exoplayer下如何只进行音频播放

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#1945]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

exoplayer下如何只进行音频播放。

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

**Comment by CarGuo** [comment]
尝试用 DummySurface dummySurface
