### ISSUE TITLE
使用IjkPlayerManager播放本地视频失败

### ISSUE THREAD

**Issue by LunHongShao** [CarGuo/GSYVideoPlayer#1946]
## 问题描述：

使用IjkPlayerManager播放本地视频时传入本地路径如：/sdcard/新喜剧之王.mp4，在IjkPlayerManager中判断Uri的Scheme()时为空，与android.resource对比时抛空指针异常

问题代码：
if (!TextUtils.isEmpty(url)) {
                    Uri uri = Uri.parse(url);
                    if (uri.getScheme().equals(ContentResolver.SCHEME_ANDROID_RESOURCE)) {
                        RawDataSourceProvider rawDataSourceProvider = RawDataSourceProvider.create(context, uri);
                        mediaPlayer.setDataSource(rawDataSourceProvider);
                    } else {
                        mediaPlayer.setDataSource(url, gsyModel.getMapHeadData());
                    }
                } else {
                    mediaPlayer.setDataSource(url, gsyModel.getMapHeadData());
                }

**Comment by CarGuo** [comment]
本地文件file开头

**Comment by gaosen1023** [comment]
我这样添加本地视频无法播放呢大佬，请问怎么处理

file://storage/emulated/0/LanPin/VIDEO_20190413_170845.mp4

**Comment by CarGuo** [comment]
file:///sxxxxxx
