### ISSUE TITLE
播放优酷的切片段问题

### ISSUE THREAD

**Issue by moyaying** [CarGuo/GSYVideoPlayer#195]
请问怎么播放youku的一个视频，多个切段问的问题？

**Comment by CarGuo** [comment]
如果是m3u8就提供m3u8协议的地址，如果是多个ts的，需要concat协议，但是目前的so没有支持concat协议，如果有需要参考首页重新编译so，问题集锦中也有

**Comment by moyaying** [comment]
好的，谢谢
