### ISSUE TITLE
继承 StandardGSYVideoPlayer    java.lang.NullPointerException

### ISSUE THREAD

**Issue by Leavds** [CarGuo/GSYVideoPlayer#1950]
有这个  surface_container

![image](https://user-images.githubusercontent.com/26810069/55702472-41ffcf00-5a09-11e9-8d79-c75933334a7f.png)

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/bg_live">

    <FrameLayout
        android:id="@+id/surface_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center">

    </FrameLayout>

    <LinearLayout
        android:id="@+id/layout_bottom"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_alignParentBottom="true"
        android:background="#99000000"
        android:gravity="center_vertical"
        android:orientation="horizontal"
        android:visibility="gone">

        <TextView
            android:id="@+id/current"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="16dp"
            android:text="00:00"
            android:textColor="#ffffff" />

        <SeekBar
            android:id="@+id/progress"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:layout_weight="1.0"
            android:background="@null"
            android:max="100"
            android:maxHeight="4dp"
            android:minHeight="4dp"
            android:paddingBottom="8dp"
            android:paddingTop="8dp"
            android:progressDrawable="@drawable/video_seek_progress"
            android:thumb="@drawable/video_seek_thumb" />

        <TextView
            android:id="@+id/total"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginRight="16dp"
            android:text="00:00"
            android:textColor="#ffffff" />

        <ImageView
            android:id="@+id/fullscreen"
            android:layout_width="@dimen/dp_20"
            android:layout_height="@dimen/dp_20"
            android:scaleType="centerCrop"
            android:layout_marginRight="@dimen/dp_5"
            android:src="@drawable/video_enlarge" />
    </LinearLayout>

    <ProgressBar
        android:id="@+id/bottom_progressbar"
        style="@android:style/Widget.Holo.ProgressBar.Horizontal"
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="@dimen/dp_45"
        android:progressDrawable="@drawable/progressbar_horizontal"/>

    <RelativeLayout
        android:id="@+id/thumb"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentStart="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true">

        <com.hn.library.view.FrescoImageView
            android:id="@+id/iv_thumb_weiVideo"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop"
            android:visibility="visible"
            app:actualImageScaleType="centerCrop"
            app:failureImage="@drawable/bg_live"
            app:failureImageScaleType="centerCrop"
            app:roundAsCircle="false" />

    </RelativeLayout>

</RelativeLayout>

**Comment by CarGuo** [comment]
demo怎么复现

**Comment by Leavds** [comment]
demo   没复现 ，主要是线上bugly有的用户出现这种问题

**Comment by CarGuo** [comment]
@Leavds 因为bugly上有些崩溃是二次崩溃导致的
