### ISSUE TITLE
请问作者SmallVideoHelper 的作用

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#1951]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

SmallVideoHelper 的作用是什么。是会处理悬浮窗全屏的问题吗

## 问题机型/系统：

魅蓝

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

**Comment by CarGuo** [comment]
悬浮窗在demo里，这个是处理当前页面的可拖动小窗口显示
