### ISSUE TITLE
如何未加载提前缓存

### ISSUE THREAD

**Issue by fanss** [CarGuo/GSYVideoPlayer#1953]

**Comment by CarGuo** [comment]
建议通过proxyCache去代理拉流，这样就可以和播放中的流同一个缓存，居然看源码

**Comment by fanss** [comment]
好的 谢谢

**Comment by Lollipopll** [comment]
> 好的 谢谢

请教一下详细操作，之前没接触过这些内容，现在了解到的proxyCache会通过代理返回一个url，如何把这个url预拉流？

**Comment by Lollipopll** [comment]
> 好的 谢谢

刚试了一下，用proxyCache获取的代理url，然后通过okhttp去请求这个链接，确实把文件下载到本地了，请教一下这样流程正确吗？我只要管理好okhttp的请求即可是吗
