### ISSUE TITLE
是否支持swf 格式？

### ISSUE THREAD

**Issue by zhangqaing** [CarGuo/GSYVideoPlayer#1954]
## 问题描述：

http://player.youku.com/player.php/sid/XMTI5NjkwNTkwMA==/v.swf 这个视频格式的播放不了，返回错误

## 问题机型/系统：

华为mate 10 android 9.0

## GSY依赖版本

 implementation 'com.shuyu:GSYVideoPlayer:6.0.1'

## Demo中的复现步骤

SmartPickVideo 这个类，播放直接错误

**Comment by CarGuo** [comment]
不支持，要支持需要自己编译so，具体参考 

https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md

https://www.jianshu.com/p/bd289e25d272

**Comment by zhangqaing** [comment]
好的，谢谢
