### ISSUE TITLE
请问默认缓存路径是什么，缓存上限可以设置吗，超过缓存上限会自动清除最早的视频吗

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#1955]
谢谢

**Comment by CarGuo** [comment]
你可以看 ProxyCacheManager 的 clearCache 还有 HttpProxyCacheServer 的 Builder

**Comment by ZJLeBron** [comment]
默认最大512M缓存超过512M采取LruCache算法存储对吧

**Comment by CarGuo** [comment]
嗯嗯

**Comment by tydqcjj** [comment]
这个看下能不能设置

`
ProxyCacheManager.instance().setProxy(newProxy());   
private HttpProxyCacheServer newProxy() {
    return new HttpProxyCacheServer.Builder(this)
            .maxCacheSize(1024 * 1024 * 1024)       // 1 Gb for cache
            .build();
}`
