### ISSUE TITLE
请问有音频播放api吗

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#1958]

**Comment by CarGuo** [comment]
正常播放就可以

**Comment by ZJLeBron** [comment]
播放报错，请大佬帮看一下.IjkMediaPlayer: Error (-10000,0)
 E/IJKMEDIA: http://cdn1.100rd.com/o_1cggnu8insukcnu18lt6rcegpf2.mp3: Invalid data found when processing input
IJKMEDIA: SDL_JNI_DetachThreadEnv: [6771]
 D/IJKMEDIA: FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by ZJLeBron** [comment]
播放视频没问题，播放音频报错。

**Comment by ZJLeBron** [comment]
设置成 GSYVideoType.IJKEXOPLAYER 就是可以播放音频了，但是这个类型播放器就不会循环播放了

**Comment by CarGuo** [comment]
如果GSYVideoType.IJKEXOPLAYER 然后设置looping，会用 LoopingMediaSource ，具体可见 ExoSourceManager 的 getMediaSource

**Comment by ZJLeBron** [comment]
> 如果GSYVideoType.IJKEXOPLAYER 然后设置looping，会用 LoopingMediaSource ，具体可见 ExoSourceManager 的 getMediaSource

没太明白具体怎么用IJKEXOPLAYER 实现循环播放，能说具体点吗

**Comment by CarGuo** [comment]
exoplayer内是通过用 MediaSource  设置数据源的，各种 MediaSource 嵌套得到想要的效果，比如项目里，是 通过 ExoSourceManager 的 getMediaSource方法去得到的，你可以看看

**Comment by ZJLeBron** [comment]
> exoplayer内是通过用 MediaSource 设置数据源的，各种 MediaSource 嵌套得到想要的效果，比如项目里，是 通过 ExoSourceManager 的 getMediaSource方法去得到的，你可以看看

谢谢，我再看下源码
