### ISSUE TITLE
mTextureView是在哪儿渲染结束的

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#1959]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

mTextureView是在哪儿渲染结束的

## 问题机型/系统：

魅蓝

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
不是很理解

**Comment by oveeeee** [comment]
> 不是很理解

就是我想在渲染结束后，获取到mTextureView的宽高。我看是在addTextureView()中实例化的一个mTextureView,setStartAfterPrepared()调用的这个，可以我在setStartAfterPrepared()之后获取到的mTextureView的宽高仍然是0

**Comment by CarGuo** [comment]
这个你可以看 demo 中的 https://github.com/CarGuo/GSYVideoPlayer/blob/21e9a19eadcefd9753296819575c784585d117a3/app/src/main/java/com/example/gsyvideoplayer/view/CustomRenderView.java#L17

和

**Comment by jygsdjflsd** [comment]
setRenderType设置为GLSURFACE或者SUFRACE时 列表播放只显示缩略图不播放视频

**Comment by CarGuo** [comment]
@jygsdjflsd demo怎么复现

**Comment by jygsdjflsd** [comment]
我在demo的MainActivity oncreate最后设置了下GSYVideoType.setRenderType(GSYVideoType.SUFRACE);

**Comment by CarGuo** [comment]
demo 已修复
