### ISSUE TITLE
请问是否支持对m3u8文件的key所对应URI链接二次加解密

### ISSUE THREAD

**Issue by chrislanbo** [CarGuo/GSYVideoPlayer#1961]
目前做客户端播放加密的m3u8视频
但是key无论在本地还是在线，都很容易被获取
能否做到对URI的链接二次加密，读取的时候在解密出真实的链接，从而实现播放效果
麻烦指一条路，感谢

**Comment by CarGuo** [comment]
如果我认知没错的话，不支持，这个我也没经验···

**Comment by chrislanbo** [comment]
> 如果我认知没错的话，不支持，这个我也没经验···

仍然感谢
