### ISSUE TITLE
 请问下怎么设置不可点击和刚开始播放时不显示暂停按钮?

### ISSUE THREAD

**Issue by wuxifan** [CarGuo/GSYVideoPlayer#1962]
## 问题描述：

请问下怎么设置不可点击和刚开始播放时不显示暂停按钮?

## 问题机型/系统：

android

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'

**Comment by CarGuo** [comment]
看源码继承重载方法
