### ISSUE TITLE
v7.0.1有非androidx的版本吗？

### ISSUE THREAD

**Issue by ysyyun** [CarGuo/GSYVideoPlayer#1963]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

全屏与非全屏切换，surface释放问题。大神，看着这个问题已修复，替换了下。以前的项目使用的support库，一些第三方库还不支持androidx，导致编译打包失败

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by CarGuo** [comment]
没
