### ISSUE TITLE
单例模式下，不同页面的视频相互影响

### ISSUE THREAD

**Issue by QiChunJie** [CarGuo/GSYVideoPlayer#1965]
老哥， 最近遇到一个问题相当棘手： 即目前框架是单例管理视频的，因此不同页面播放视频会相互影响， 比如A页面跳到B页面，此时应该是暂停的； 然后B页面播放一下视频， 回到A时就回到了Normal状态； 我试着把GSYVideoManager改为了非单例模式； 情况基本好了。 但是还出现了一个情况， A页面的视频在loading时， 跳转到B, 这时我的处理是loading完之后暂停（因此loading直接暂停是有问题的）。 从B继续播放视频，回到A发现莫名奇妙的调用了一次Playing(手动暂停后系统好像执行了一次Playing， 没找到是哪里playing的， 时间比较紧)。 老哥能否看一下这个GSYVideoManager怎么解单例比较合适？ 万分感谢！！！

**Comment by CarGuo** [comment]
回到B页面自己掉了playing？你是自己的activity还是继承的gsy提供的activity？？？
嗯···感觉这个你可以断点或者打印下，应该比较好调试的

**Comment by QiChunJie** [comment]
A loading时切换到B， B点击播放prepare -> 开始播放； 此时A视频loading结束并暂停； 从B返回A, A最后的状态是暂停； 但是返回A后， 自己调用了一次changeUiToPlaying, 我查了一下，好像没地方手动调changeUiToPlaying或者play操作；猜测应该是B页面视频播放影响的，调了好久， 没找到原因。

**Comment by CarGuo** [comment]
建议是你断点 changeUiToPlaying  看看调用堆栈

**Comment by CarGuo** [comment]
我在demo做了简单的测试，测试正常啊， 你是不是基础了  GSYBaseActivityDetail 导致的？？？

**Comment by CarGuo** [comment]
我加了个 issueTest  分支   https://github.com/CarGuo/GSYVideoPlayer/tree/issueTest  

在 DetailControlActivity 增加了类似你说的，你播放之后，点跳转，播放之后，再回来，貌似是正常

**Comment by QiChunJie** [comment]
没有， activity是自己的。 你试的代码应该是单例吧。 单例导致的问题是A -> 播放 -> B -> 播放 -> 返回A， A好像是回到了Normal状态；

**Comment by QiChunJie** [comment]
然后我把GsyVideoManager解了单例， 最终的结果是A -> loading -> B -> 播放 -> 返回A, 此时会出现错误状态。 这是一个很少数情况的偶发错误， 根据网速概率不同， 而且我处理的是VideoView所在的Fragment不可见时， loading完成后暂停

**Comment by CarGuo** [comment]
不是单例的，我改成了多任务的了。测试正常

**Comment by CarGuo** [comment]
你看新分支上，demo上上面说的。
