### ISSUE TITLE
视频黑屏

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#1966]
参照 Demo DetailListPlayer 改的一个无UI 界面的视频播放器 
视频有时播放久了 就会出现黑屏现象(有没有声音不确定)

我试了一下 用VideoVideo播放相同的视频源 设置一下 
activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND); 就会黑屏

![图片](https://user-images.githubusercontent.com/25575326/56116214-dcc35500-5f97-11e9-965a-dcb0e0bf0183.png)

GSYVideoPlayer设置这个是否有影响

**Comment by CarGuo** [comment]
不是很理解现在的问题
