### ISSUE TITLE
升级Androidx包，然后播放器播不了

### ISSUE THREAD

**Issue by liusuqin** [CarGuo/GSYVideoPlayer#1969]
## 问题描述：
升级Androidx包，然后播放器播不了(急急急，大神，求解。)

## 问题机型/系统：

华为p20 pro /Android9.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

一直存在

## 问题log
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libijkffmpeg.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"

**Comment by CarGuo** [comment]
Demo正常
