### ISSUE TITLE
自动播放问题

### ISSUE THREAD

**Issue by ZuJunJun** [CarGuo/GSYVideoPlayer#1970]
## 问题描述：

RecyclerView中item是一个全屏的VideoView（抖音列表），滑动列表展示上一个item，能够自动播放，但是滑动列表展示下一个item，不能自动播放，方式用的demo里面自动RECYCLERIVEW的方式.

## 问题机型/系统：

真机

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:5.0.1'`

## Demo中的复现步骤

一个设置自动播放全屏的item，recyclerview,上下滑动。

麻烦看一下解决办法，谢谢。

**Comment by CarGuo** [comment]
目前demo并没有发现问题

**Comment by ZuJunJun** [comment]
> 目前demo并没有发现问题

请问是全屏的item么？我下载下来你的代码，把自动Recyclerview那个类型的item改成全屏的，其他都没动，就会出现问题。

**Comment by CarGuo** [comment]
你可以看看代码中自动播放计算位置的逻辑

**Comment by ZuJunJun** [comment]
应该是屏幕一半上下偏移多少为开始自动播放，应该是这么理解吧，但是，helper类里面visiableCount再滑道下一个的时候是0，滑到上一个1，传的值是您代码里一样的写法。




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>;
发送时间: 2019年4月21日(星期天) 下午2:34
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "朱军军"<1244685420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CarGuo/GSYVideoPlayer] 自动播放问题 (#1970)




你可以看看代码中自动播放计算位置的逻辑

**Comment by CarGuo** [comment]
因为demo里的不是全屏的。如果是需要类似抖音的，你需要自己实现

**Comment by softwareXiaotao** [comment]
> ##
> ## 问题机型/系统：
> 真机
> 
> ## GSY依赖版本
> `implementation 'com.shuyu:gsyVideoPlayer-java:5.0.1'`
> 
> ## Demo中的复现步骤
> 一个设置自动播放全屏的item，recyclerview,上下滑动。
> 
> 麻烦看一下解决办法，谢谢。



> ## 问题描述：
> RecyclerView中item是一个全屏的VideoView（抖音列表），滑动列表展示上一个item，能够自动播放，但是滑动列表展示下一个item，不能自动播放，方式用的demo里面自动RECYCLERIVEW的方式.
> 
> ## 问题机型/系统：
> 真机
> 
> ## GSY依赖版本
> `implementation 'com.shuyu:gsyVideoPlayer-java:5.0.1'`
> 
> ## Demo中的复现步骤
> 一个设置自动播放全屏的item，recyclerview,上下滑动。
> 
> 麻烦看一下解决办法，谢谢。

你解决了吗  解决了 代码可以贴一下嘛
