### ISSUE TITLE
播放Https的问题  android:usesCleartextTraffic="true"

### ISSUE THREAD

**Issue by twlk-jzy** [CarGuo/GSYVideoPlayer#1971]
## 问题描述：

播放Https的时候  如果在application中配置了 android:usesCleartextTraffic="true"  会导致无法正常播放

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中 每一个如此

**Comment by CarGuo** [comment]
经测试，在demo加入 application android:usesCleartextTraffic="true" 后，正常
