### ISSUE TITLE
视频怎么设置高斯模糊

### ISSUE THREAD

**Issue by wangweishou123** [CarGuo/GSYVideoPlayer#1972]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：就是按照文档描述的步骤去设置了播放类型，添加了高斯模糊。但是那个视频两边的黑色框还是无法模糊化

XXXX发生了这样的问题！

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
使用的是如下代码：
backupRendType = GSYVideoType.getRenderType();
  //设置为GL播放模式，才能支持滤镜，注意此设置是全局的
 GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);
standardGSYVideoPlayer.setEffectFilter(new SampleBlurEffect());
standardGSYVideoPlayer.setCustomGLRenderer(new GSYVideoGLViewColorRender());
其中的GSYVideoGLViewColorRender类是从demo里面copy过来的

**Comment by CarGuo** [comment]
低版本手机不再地址，因为也没有办法测试了。
还有，黑色你觉得应该怎么高斯？黑色高斯后会是什么样子的？？？
并且黑色也不是surface的，是控件层的了

**Comment by wangweishou123** [comment]
啊，这样的话，我要怎么去掉黑色部分换成模糊的效果呢

**Comment by CarGuo** [comment]
首先第一点，你应该知道什么是高斯模糊，然后你就会知道，纯色高斯模糊是没有效果的！

**Comment by CotTan** [comment]
使用opgl 之后手机录制的视频会旋转

**Comment by wangweishou123** [comment]
不是。我用你的demo的时候，你的视频播放的时候，左右两边是可以模糊的。但是我们用的时候不行

**Comment by CarGuo** [comment]
@wangweishou123 拿应该是用的 GSYVideoGLViewCustomRender4 这个模式的，做了双层显示，底层拉伸铺满
