### ISSUE TITLE
使用opengl （高斯模糊） 之后手机录制的视频会旋转（竖屏变成横屏）

### ISSUE THREAD

**Issue by CotTan** [CarGuo/GSYVideoPlayer#1974]
## 问题描述：
使用opengl （高斯模糊） 之后手机录制的视频会旋转（竖屏变成横屏）
![QQ图片20190422120401](https://user-images.githubusercontent.com/11958737/56482431-bd2baf80-64f6-11e9-94b8-50ade851dff5.jpg)

## 问题机型/系统：

所有机型

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

滤镜 里面的视频改成自己手机录制的

**Comment by CarGuo** [comment]
请提供下url

**Comment by CotTan** [comment]
没有外网的地址

**Comment by CarGuo** [comment]
同个url只在gl模式会？

**Comment by CotTan** [comment]
对

**Comment by zhangjunwei369** [comment]
大佬,我自定义 继承StandardGSYVideoPlayer,播放网络视频也是横屏,
所有机型
url : https://greedycat.oss-cn-hongkong.aliyuncs.com/m3u8/9b400f8d-eb74-4784-b275-5bf5302ff901.m3u8

**Comment by CarGuo** [comment]
因为 GL 模式下没有处理视频自带的旋转属性

**Comment by shenbingkai** [comment]
请问背景模糊这个功能要怎么开启，我直接下载apk没有找到

**Comment by Matt-Yen-Ting** [comment]
請問有解決這個問題了嗎？

**Comment by CarGuo** [comment]
@Matt-Yen-Ting  因为视频默认的 Rotate 需要在 onInfo 回调才可以获取，所以内部不做这部分逻辑，如果有对应视频状态，可以通过自定义去完成

**Comment by yykou** [comment]
@CotTan 您好，麻烦问下，这个问题最后是怎么解决的？

**Comment by keepmovng** [comment]
请教下大家，这个问题解决了吗？

**Comment by keepmovng** [comment]
> @Matt-Yen-Ting 因为视频默认的 Rotate 需要在 onInfo 回调才可以获取，所以内部不做这部分逻辑，如果有对应视频状态，可以通过自定义去完成

请问下大佬具体可以怎么做呢？
