### ISSUE TITLE
弱网环境loading如何隐藏

### ISSUE THREAD

**Issue by hanouba** [CarGuo/GSYVideoPlayer#1976]
## 问题描述：

弱网络环境下 请求到视频地址 但是加载比较慢,会一直显示loading ;
这个加载loading很久都不消失好几分钟; 
如何根据时间判断来隐藏这个loading?

## 问题机型/系统：

华为荣耀8 android8.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中没有复现 拿到播放地址有无法在demo上播放

**Comment by CarGuo** [comment]
无法播放？？不是很理解

**Comment by hanouba** [comment]
就是公司项目里面的视频地址单独拿出来播放不了,有加密处理

**Comment by CarGuo** [comment]
那你得看怎么加密的，你这么说我也木办法哦 。比如在header
