### ISSUE TITLE
依赖失败问题

### ISSUE THREAD

**Issue by CJinYe** [CarGuo/GSYVideoPlayer#1977]
## 问题描述：

依赖失败问题

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'

## 问题log（如果有）

error: resource android:attr/dialogCornerRadius not found.
Message{kind=ERROR, text=error: resource android:attr/dialogCornerRadius not found., sources=[C:\Users\Programmer\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.0-beta01.aar\2c43f6dc24605333215e5e4ff39cbbf9\res\values-v28\values-v28.xml:9:5-12:13], original message=, tool name=Optional.of(AAPT)}

**Comment by CarGuo** [comment]
类似问题请自行查找解决，当前最新版本是 targetSdk 28，androidx
