### ISSUE TITLE
不切换横竖屏的情况下 如何更新布局？

### ISSUE THREAD

**Issue by BzCoder** [CarGuo/GSYVideoPlayer#1978]
## 问题描述：

我现在继承的是LandLayoutVideo，问题是如何动态切换布局，我的场景：一个直播播放器，一个点播播放器，两个界面不同，只要切换线路布局就要做动态改变。因为按照现在的模式用Visable Gone也很难实现。

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
这个不属于项目的范畴了吧

**Comment by BzCoder** [comment]
@CarGuo 因为现在横屏和竖屏可以两个不同的布局嘛，我就想直播和点播视频也要两个不同布局。因为现在你的Control层是只有一层，并且按钮逻辑已经按照控件ID封装完毕了。所以我要先切换线路的时候就无法切换你的ControlUI。我感觉这个还算是一个比较常见的场景吧，网易新闻直播里就有。

**Comment by CarGuo** [comment]
其实，为什么不是两个播放控件呢？一定要在一个控件里？

**Comment by BzCoder** [comment]
@CarGuo 考虑只是controlUI替换，其实使用SetVisible也能解决（但是按照现在的分层不允许），换UI是个轻量级的操作，但是初始化两个播放器操作感觉有点重，而且两个播放器之间的切换操作怕自己这边处理不好。

**Comment by CarGuo** [comment]
内核只有一个的情况下，并不会有太重的问题
