### ISSUE TITLE
你好，如何在全屏改变标题和播放url（类似下一集）

### ISSUE THREAD

**Issue by 50kg** [CarGuo/GSYVideoPlayer#1979]
业务逻辑原因不能一次性全部拿到播放url和title，所有没用demo里的DetailListPlayer，所以有没有办法全屏时改变url和title，返回全屏也需要同步数据，这是我的代码，怎么修改

GSYBaseVideoPlayer currentPlayer = getGSYVideoPlayer().getCurrentPlayer();
getGSYVideoOptionBuilder()
.setUrl(videoUrl)
.setVideoTitle(videoTitle)
.build(currentPlayer);

**Comment by CarGuo** [comment]
getCurrentPlayer之后不能用builder，直接用player设置

**Comment by 50kg** [comment]
getCurrentPlayer方法返回是GSYBaseVideoPlayer对象，没用设置url和title的对外方法怎么办，虽然我可以拿到继承自StandardGSYVideoPlayer的对象 添加了2个设置标题和url的犯法，但是这个好像不是全屏播放器

        MyVideoStandard detailPlayer = (MyVideoStandard) getGSYVideoPlayer();
        detailPlayer.setTitle(videoTitle);
        detailPlayer.setUrl(videoUrl);
        detailPlayer.startPlayLogic();
