### ISSUE TITLE
搞什么鬼?之前还可以的,现在我发现地址http前面给我自动加上了127.0.0.1了

### ISSUE THREAD

**Issue by qssq** [CarGuo/GSYVideoPlayer#198]
E/IJKMEDIA: http://127.0.0.1:56575/http%3A%2F%2Fv.she 后面的保密了,总之 之前好好的,玩着玩着无法播放了还给我加上了这个垃圾东西.

**Comment by yhsj0919** [comment]
不是不是开启缓存了,你可以看一下缓存说明
