### ISSUE TITLE
是否有方法可以拿到解码后的二进制数据

### ISSUE THREAD

**Issue by jjwong1991** [CarGuo/GSYVideoPlayer#1980]

**Comment by CarGuo** [comment]
目前来说没有

**Comment by jjwong1991** [comment]
感谢回复，由于这边有需求必须拿到解码后的帧数据处理后再播放，如果要拿的话ijkplayer是否有方法，还是说要从更底层入手？

**Comment by CarGuo** [comment]
你可以从底层处理，也可以参考项目的GLSurfaceView，可以在绘制钱前进行OpenGL处理
