### ISSUE TITLE
导入6.0.3报错

### ISSUE THREAD

**Issue by 317056658** [CarGuo/GSYVideoPlayer#1982]
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 28.0.0, 22.2.1. Examples include com.android.support:animated-vector-drawable:28.0.0 and com.android.support:support-v4:22.2.1 more... (Ctrl+F1)   请问大神怎么解决？

**Comment by CarGuo** [comment]
log上不是说了么，就是库冲突啊，类似问题请网上自行解决

**Comment by 317056658** [comment]
大佬您好， 你说你的6.0.3版本 支持安卓的库只到27.1.1   但我这边安卓支持库是28.0.0  这样不会有什么兼容性问题吧？   我实在是菜啊 ，所以来请教大佬。谢谢 




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>; 
发送时间: 2019年4月23日(星期二) 下午5:19
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>; 
抄送: "那都不是事儿"<317056658@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CarGuo/GSYVideoPlayer] 导入6.0.3报错 (#1982)




log上不是说了么，就是库冲突啊，类似问题请网上自行解决

**Comment by CarGuo** [comment]
你可以看看哪些冲突了，如果冲突了使用 gradle 依赖时 exculde 就好了
