### ISSUE TITLE
你好，全屏setUp后获取的url还是旧的，如何克隆参数

### ISSUE THREAD

**Issue by 50kg** [CarGuo/GSYVideoPlayer#1984]
全屏播放器重新设置了setUp，但是取到的url还是上一个旧的，需要退出全屏再进入才正常，手动克隆参数  或者 有没有方法获取当前播放url 

GSYBaseVideoPlayer currentPlayer = getGSYVideoPlayer().getCurrentPlayer();
currentPlayer.setUp(videoUrl, false, title);
currentPlayer.startPlayLogic();

**Comment by CarGuo** [comment]
正常是通过内部的closeParams方法传的。setup的时候我记得可以不用current的

**Comment by 50kg** [comment]
如果不用current的setUp，全屏url不生效，大小窗口各设置一遍 解决了
