### ISSUE TITLE
Fragment的子Fragment中使用 StandardGSYVideoPlayer，播放前几秒或前十几秒卡顿

### ISSUE THREAD

**Issue by zhoupeng2** [CarGuo/GSYVideoPlayer#1985]
问题描述：

在Fragment 使用Viewpager+Fragment。在子Fragment的子Fragment中使用 StandardGSYVideoPlayer，播放前几秒或前十几秒卡顿，是在低端机下卡顿 视频总长度 1m20s.
不点播放 操作和滑动都很流畅。
看了之前 Closed 的Issues 也出现过这个问题。但是我是在Fragment的子Fragment中使用。
问题机型/系统：

OPPO R9m  Android 5.1  运行内存 4G

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'
Demo中的复现步骤

在子Fragment的子Fragment中使用 StandardGSYVideoPlayer，前几秒或者十几秒也可能一直卡顿。

麻烦看一下解决办法，谢谢。

**Comment by zhoupeng2** [comment]
在 Fragment使用的话 是不会卡顿的

**Comment by CarGuo** [comment]
这个和在哪里使用没关系，卡顿原因和播放器无关，只能你自己找找哪里造成的，我也没办法帮你看的。

**Comment by zhoupeng2** [comment]
好的。谢谢

**Comment by zhoupeng2** [comment]
是我布局的问题，Activity+Fragment+子Fragment。布局xml实在嵌套太多层导致卡顿
