### ISSUE TITLE
GSYSampleCallBack方法回调问题

### ISSUE THREAD

**Issue by liuchenc** [CarGuo/GSYVideoPlayer#1986]
GSYSampleCallBack这个回调类,加载进度条只会在第一次加载的时候会走onStartPrepared()和onPrepared这两个方法,当网络不稳定的时候进度条会再次显示隐藏,这时候没有走这两个方法,请问作者这是怎么回事?我现在是要在加载进度条每次出现,隐藏的时候做相应的处理,做类似抖音之类的加载效果,请作者指点

**Comment by CarGuo** [comment]
不是很理解

**Comment by liuchenc** [comment]
就是我在监听视频加载的时候,发现GSYSampleCallBack这接口回调里的onStartPrepared(开始加载)和onPrepared(加载中)这两个方法,只会在视频刚开始加载时候执行,播放过程中,比如说网络不稳定的时候也会显示加载圈,但是这个时候并未执行上面两个方法,请问作者怎么拿到加载的实时监听?

**Comment by CarGuo** [comment]
你看源码在player的基类中有 void onInfo方法和 onBufferingUpdate 这两个方法，你看看实现吧，继承后重载吧

**Comment by liuchenc** [comment]
作者您好!我想问下player的基类中void onInfo(int what,int extra)方法中这两个参数里的what返回的常量代表什么意思




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 中午11:59
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "LCC"<565117124@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CarGuo/GSYVideoPlayer] GSYSampleCallBack方法回调问题 (#1986)




Closed #1986.

**Comment by liuchenc** [comment]
我是想知道怎么通过它来控制缓冲进度条的显示隐藏


------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 中午11:59
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "LCC"<565117124@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CarGuo/GSYVideoPlayer] GSYSampleCallBack方法回调问题 (#1986)




Closed #1986.

**Comment by liuchenc** [comment]
作者您好!我想问下player的基类中void onInfo(int what,int extra)方法中这两个参数里的what返回的常量代表什么意思
我是想知道怎么通过它来控制缓存进度条的显示隐藏


------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>;
发送时间: 2019年4月27日(星期六) 晚上7:24
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "LCC"<565117124@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CarGuo/GSYVideoPlayer] GSYSampleCallBack方法回调问题 (#1986)




你看源码在player的基类中有 void onInfo方法和 onBufferingUpdate 这两个方法，你看看实现吧，继承后重载吧

**Comment by CarGuo** [comment]
如果是ijk模式的话，你可以参考

```
  /*
     * Do not change these values without updating their counterparts in native
     */
    int MEDIA_INFO_UNKNOWN = 1;
    int MEDIA_INFO_STARTED_AS_NEXT = 2;
    int MEDIA_INFO_VIDEO_RENDERING_START = 3;
    int MEDIA_INFO_VIDEO_TRACK_LAGGING = 700;
    int MEDIA_INFO_BUFFERING_START = 701;
    int MEDIA_INFO_BUFFERING_END = 702;
    int MEDIA_INFO_NETWORK_BANDWIDTH = 703;
    int MEDIA_INFO_BAD_INTERLEAVING = 800;
    int MEDIA_INFO_NOT_SEEKABLE = 801;
    int MEDIA_INFO_METADATA_UPDATE = 802;
    int MEDIA_INFO_TIMED_TEXT_ERROR = 900;
    int MEDIA_INFO_UNSUPPORTED_SUBTITLE = 901;
    int MEDIA_INFO_SUBTITLE_TIMED_OUT = 902;

    int MEDIA_INFO_VIDEO_ROTATION_CHANGED = 10001;
    int MEDIA_INFO_AUDIO_RENDERING_START  = 10002;
    int MEDIA_INFO_AUDIO_DECODED_START    = 10003;
    int MEDIA_INFO_VIDEO_DECODED_START    = 10004;
    int MEDIA_INFO_OPEN_INPUT             = 10005;
    int MEDIA_INFO_FIND_STREAM_INFO       = 10006;
    int MEDIA_INFO_COMPONENT_OPEN         = 10007;
    int MEDIA_INFO_VIDEO_SEEK_RENDERING_START = 10008;
    int MEDIA_INFO_AUDIO_SEEK_RENDERING_START = 10009;
    int MEDIA_INFO_MEDIA_ACCURATE_SEEK_COMPLETE = 10100;

    int MEDIA_ERROR_UNKNOWN = 1;
    int MEDIA_ERROR_SERVER_DIED = 100;
    int MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK = 200;
    int MEDIA_ERROR_IO = -1004;
    int MEDIA_ERROR_MALFORMED = -1007;
    int MEDIA_ERROR_UNSUPPORTED = -1010;
    int MEDIA_ERROR_TIMED_OUT = -110;
```

**Comment by liuchenc** [comment]
作者您好!你们做加载进度条显示隐藏也是根据这些状态判断的吗




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 上午9:52
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "LCC"<565117124@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CarGuo/GSYVideoPlayer] GSYSampleCallBack方法回调问题 (#1986)




如果是ijk模式的话，你可以参考
   /*      * Do not change these values without updating their counterparts in native      */     int MEDIA_INFO_UNKNOWN = 1;     int MEDIA_INFO_STARTED_AS_NEXT = 2;     int MEDIA_INFO_VIDEO_RENDERING_START = 3;     int MEDIA_INFO_VIDEO_TRACK_LAGGING = 700;     int MEDIA_INFO_BUFFERING_START = 701;     int MEDIA_INFO_BUFFERING_END = 702;     int MEDIA_INFO_NETWORK_BANDWIDTH = 703;     int MEDIA_INFO_BAD_INTERLEAVING = 800;     int MEDIA_INFO_NOT_SEEKABLE = 801;     int MEDIA_INFO_METADATA_UPDATE = 802;     int MEDIA_INFO_TIMED_TEXT_ERROR = 900;     int MEDIA_INFO_UNSUPPORTED_SUBTITLE = 901;     int MEDIA_INFO_SUBTITLE_TIMED_OUT = 902;     int MEDIA_INFO_VIDEO_ROTATION_CHANGED = 10001;     int MEDIA_INFO_AUDIO_RENDERING_START  = 10002;     int MEDIA_INFO_AUDIO_DECODED_START    = 10003;     int MEDIA_INFO_VIDEO_DECODED_START    = 10004;     int MEDIA_INFO_OPEN_INPUT             = 10005;     int MEDIA_INFO_FIND_STREAM_INFO       = 10006;     int MEDIA_INFO_COMPONENT_OPEN         = 10007;     int MEDIA_INFO_VIDEO_SEEK_RENDERING_START = 10008;     int MEDIA_INFO_AUDIO_SEEK_RENDERING_START = 10009;     int MEDIA_INFO_MEDIA_ACCURATE_SEEK_COMPLETE = 10100;     int MEDIA_ERROR_UNKNOWN = 1;     int MEDIA_ERROR_SERVER_DIED = 100;     int MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK = 200;     int MEDIA_ERROR_IO = -1004;     int MEDIA_ERROR_MALFORMED = -1007;     int MEDIA_ERROR_UNSUPPORTED = -1010;     int MEDIA_ERROR_TIMED_OUT = -110;

**Comment by CarGuo** [comment]
触摸的时候不是
