### ISSUE TITLE
无法播放 .mpg 格式的视频

### ISSUE THREAD

**Issue by combing520** [CarGuo/GSYVideoPlayer#1990]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
视频格式 没法播放，该视频的格式为： http://liverecord.ccwb.cn/qukan/user/1555559877052955/upload/cecfa4ff-e560-4664-b12a-1dad74c83cd8.mpg
XXXX发生了这样的问题！
在播放的时候，没法播放成功
## 问题机型/系统：

例如 真机 小米note2 Android7.0
真机  华为MHA-AL100 ; 红米4 ； 
## GSY依赖版本
    implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1072
