### ISSUE TITLE
视频卡顿

### ISSUE THREAD

**Issue by JohnDwang** [CarGuo/GSYVideoPlayer#1995]
视频
视频播放卡顿 

华为mate20 pro  9.0

播放url：http://quanzi-vedios.oss-cn-beijing.aliyuncs.com/1556968311572.mp4

**Comment by CarGuo** [comment]
H256 Video: hevc  编码兼容问题，切换到 EXO模式 即可

PlayerFactory.setPlayManager(Exo2PlayerManager.class); //EXO模式
