### ISSUE TITLE
列表视频退出全屏 列表里的视频不会继续播放

### ISSUE THREAD

**Issue by JamesGZM** [CarGuo/GSYVideoPlayer#1997]
## 问题描述：

我Activity嵌套一个ViewPager Fragment Fragment里面继续嵌套ViewPager ListFragment 最后这个ListFragment里面放视频和其他item的混合列表 结果视频退出全屏会直接触发onScrolled并且会走到releaseAllVideos 这个问题暂时没有定位到哪里 

## 问题机型/系统：

真机 华为meta10 Android9.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`
 `implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'`

## Demo中的复现步骤

Demo中未复现

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```
我通过给OnScrollListener增加以下代码解决了该问题
`int firstVisibleItem, lastVisibleItem;
            int state;

            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
                //记录当前滑动状态
                state = newState;
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {

                super.onScrolled(recyclerView, dx, dy);

                firstVisibleItem = manager.findFirstVisibleItemPosition();
                lastVisibleItem = manager.findLastVisibleItemPosition();
                //大于0说明有播放
                if (GSYVideoManager.instance().getPlayPosition() >= 0) {
                    //当前播放的位置
                    int position = GSYVideoManager.instance().getPlayPosition();
                    //对应的播放列表TAG
                    if (GSYVideoManager.instance().getPlayTag().equals("BigVideo")
                            && (position < firstVisibleItem || position > lastVisibleItem)) {

                        //如果滑出去了上面和下面就是否，和今日头条一样
                        //是否全屏
                        if (!GSYVideoManager.isFullState(context) && state != SCROLL_STATE_IDLE) {
                            GSYVideoManager.releaseAllVideos();
                            adapter.notifyDataSetChanged();
                            GUtils.LogD("releaseAllVideos");
                        }
                    }

                }

            }`

**Comment by JamesGZM** [comment]
可能是嵌套太多或者是调用的一个状态栏库（ImmersionBar）出现了这个bug

**Comment by CarGuo** [comment]
看看AndroidManifset配置了没？然后需要看看你的onscroll内怎么增加判断

**Comment by JamesGZM** [comment]
@CarGuo AndroidManifset 是正常的 然后我onscroll里面就是增加了上面的代码

**Comment by CarGuo** [comment]
这个需要你自己看看是什么导致了 onscroll 内触发 release
