### ISSUE TITLE
ExoPlayer 支持 切片 301 吗

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#1998]
## 问题描述：
切片网址：http://cn1.78love.cn/hls/20190503/e0a6285e7448914bf3e7817b1a761934/1556829930/index.m3u8  切片会跳转到新网址

exoplayer  缓存设为true false 都不支持
IJKplayer 支持

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.03'`

## Demo中的复现步骤

先换电脑，demo一直跑不起来 ，还是麻烦楼主了

**Comment by CarGuo** [comment]
我记得默认是不行的exoplayer，你要自定义source貌似

**Comment by huangxiaoyu** [comment]
有解决办法了么? 我这用的也是exo  直播的时候播放切片地址301

**Comment by huangxiaoyu** [comment]
> 有解决办法了么? 我这用的也是exo 直播的时候播放切片地址301

昨天试着自定义source,设置allowCrossProtocolRedirects为true,早上测试可以播放了.

**Comment by CarGuo** [comment]
header.put("allowCrossProtocolRedirects", "true");

@huangxiaoyu  可以这样配置

![image](https://user-images.githubusercontent.com/10770362/80296557-f3a5a580-87ae-11ea-9fff-20c2d7c8aea4.png)

**Comment by huangxiaoyu** [comment]
> header.put("allowCrossProtocolRedirects", "true");
> 
> @huangxiaoyu 可以这样配置，内部做了判断，如下图
> 
> ![image](https://user-images.githubusercontent.com/10770362/80296557-f3a5a580-87ae-11ea-9fff-20c2d7c8aea4.png)

哈哈 这样就更简单了 不用自定义了  非常感谢
