### ISSUE TITLE
列表播放

### ISSUE THREAD

**Issue by supercwn** [CarGuo/GSYVideoPlayer#200]
列表播放全屏为啥会先竖屏后在横屏的，怎么让列表点击全屏直接横屏？

**Comment by CarGuo** [comment]
有动画开关的，你可以设置动画为false，land为true

**Comment by supercwn** [comment]
恩， 设置了切换的顺滑度也是很好，从全屏回到列表播放的时候还是存在明显的过渡。备注：我修改了resolveChangeFirstLogic(0);

**Comment by CarGuo** [comment]
可以看到下detailplayer

**Comment by supercwn** [comment]
就是觉得奇怪，detailplayer没有出现那个问题，但是在列表播放就出现了
