### ISSUE TITLE
列表播放item暂停切换全屏后，全屏模式下暂停，退出全屏，item不能保持状态

### ISSUE THREAD

**Issue by simonhjq2014** [CarGuo/GSYVideoPlayer#2001]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

问题描述：
在Fragment里面嵌套recycleview里进行gsyvideoplayer的播放

问题机型/系统：
例如 真机 所有安卓

GSY依赖版本 6.0.3
例如 implementation 'com.shuyu:gsyVideoPlayer-java: 6.0.3'

问题详情：列表item播放时，点击暂停，点击全屏，若直接点击缩放或播放一段时间暂停点击缩放，全屏退出，item视频不保持暂停状态，会直接继续播放，若是在列表item没有点击暂停，直接点击全屏，全屏状态下点击暂停，退出全屏，item视频可以保持暂停状态。

**Comment by CarGuo** [comment]
请提供下demo复现流程
