### ISSUE TITLE
视频缓存

### ISSUE THREAD

**Issue by Neils320** [CarGuo/GSYVideoPlayer#2002]
PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
下使用
 CacheFactory.setCacheManager(ProxyCacheManager.class);//代理缓存模式
gsySmallVideoHelperBuilder .setCacheWithPlay(true)//开启缓存
缓存路径下没有缓存文件，指定其他缓存路径也没有缓存文件
断网下不能播放缓存文件，是否有其他问题，请教一下，如何使用视频缓存，

**Comment by Neils320** [comment]
使用demo 中运行代码，没有一个可以缓存下文件的事例

**Comment by CarGuo** [comment]
你的视频协议是什么？m3u8?

**Comment by Neils320** [comment]
不好意思，我的问题，已经解决，现在关闭
