### ISSUE TITLE
无法对m3u8格式的视频截取略缩图

### ISSUE THREAD

**Issue by ykbjson** [CarGuo/GSYVideoPlayer#2004]
## 问题描述：

在播放m3u8格式的视频时，无法对m3u8格式的视频截取略缩图，各种方法都试过了，Demo里的Glide方式，网上的MediaMetadataRetriever方式、ThumbnailUtils方式等等等等，求大佬给个提示和思路啊，谢谢。

## 问题机型/系统：

 真机 小米note3 Android8.1

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by ykbjson** [comment]
测试地址  https://www.625135.com/20190505/C4B7sKAW/index.m3u8

**Comment by CarGuo** [comment]
首先你要知道 m3u8是什么
m3u8只是一个索引文件，里面包含了很多视频的ts片段，你要把m3u8内的文件地址解析出来，才能获取到

**Comment by 951AB159BA** [comment]
您好，想问下，播放时候的TS文件可以哪个路径获取到，或者有下载的TS合并的文件吗？我要单独获取这个路径
