### ISSUE TITLE
demo中DetailControlActivity横屏后，SampleControlVideo布局老是重新走init方法？

### ISSUE THREAD

**Issue by baowenqing** [CarGuo/GSYVideoPlayer#2008]
为什么会横竖屏切换， 布局一直走init方法。导致自定义的状态不能刷新

**Comment by CarGuo** [comment]
首先你要理解源码中全屏是怎么全屏的。事实上切换全屏时，是切换了控件显示，保持每个不变，你看GSYBaseVideoPlayer源码是如何同步状态的
