### ISSUE TITLE
进度条 显示 进度不正确 大于 视频时长

### ISSUE THREAD

**Issue by protectedMan** [CarGuo/GSYVideoPlayer#2009]
![6B5E9B40-F80E-4F7F-B77E-0A4DBA6711EA](https://user-images.githubusercontent.com/17565737/57683945-5322a800-7667-11e9-9340-b27ed7f06946.png)
使用的是最新版本的demo，视频链接在这里
http://su.bcebos.com/v1/lezhu-test/moment/20190514/android/_15143_1557821456195.mp4

**Comment by CarGuo** [comment]
试试exo内核

**Comment by protectedMan** [comment]
好的
