### ISSUE TITLE
使用StandardGSYVideoPlayer 播放完成后再拖动进度条无法继续播放

### ISSUE THREAD

**Issue by lhx546920268** [CarGuo/GSYVideoPlayer#201]
拖动进度条后出现加载指示器后直接播放完成，进度条直接跳回100%

**Comment by CarGuo** [comment]
是的，现在是播放完了需要重新点击播放进度条才有效
因为播放器已经释放了那时候。

**Comment by lhx546920268** [comment]
我重写了拖动进度条的方法，如果是播放结束后拖动进度条，就重新添加播放器继续播放，并且设置播放进度

**Comment by wangrunxiang** [comment]
@lhx546920268 播放结束后是怎么判断的？然后怎么继续播放并且设置进度？

**Comment by wangrunxiang** [comment]
我看了一下，如果播放完再拖动进度条，可以seek到对应的时间，但是进度条会往最右边跳 @CarGuo
