### ISSUE TITLE
拖动SeekBar跳动问题

### ISSUE THREAD

**Issue by worldlk** [CarGuo/GSYVideoPlayer#2010]
## 问题描述：

我把边播变缓存设置成了False， ijk的关键帧也设置了，seekbar拖动了之后按住不动，会来回的跳动。

## 问题机型/系统：

真机 华为mate8 Android 8.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的简单播放-->简单直接播放

**Comment by CarGuo** [comment]
ok，下版本发布解决
