### ISSUE TITLE
频繁播放异常

### ISSUE THREAD

**Issue by xhh1993** [CarGuo/GSYVideoPlayer#2011]
![GTRQQNKH K1MTD176((L$40](https://user-images.githubusercontent.com/17424639/57823568-9a757980-77ca-11e9-9eb3-b1e5c82bd278.png)

频繁在同一个页面切换不同的影片，每一部播放几秒后切换下一部，大概切换了20部左右会出现如上如图所示异常。出现以后，即便退出页面再进来也是不能在播放了，只能退出app再进来。

使用的是EXO模式，且添加了缓存m3u8缓存支持。

我以为是缓存满了，但是貌似每次播放前清除缓存也是没有用的，应该不是这个问题。

想用dome测试，但是实在是不方便测试。

**Comment by CarGuo** [comment]
哪个版本？ 7.0.1吗
这个问题一般是存在 surface 释放和 mediacodcec 绘制的时候之间的问题。出现这种问题可以把 playerManager对象给null处理掉试试。

**Comment by xhh1993** [comment]
版本是6.0.1，不过应该和版本没啥关系
我尝试在退出页面的时候PlayerFactory.setPlayManager(null);还是不行
但是神奇的是，每次出现这个异常后，整个app内的播放页面都是不能在播放了。需要重新退出app再进来才恢复正常。
可能是重新进入APP在MyApp里面调用了,
 PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8

**Comment by CarGuo** [comment]
7.0.1 针对 surface 修复过，虽然不是全屏，但你这个看起来也是类似 surface 切换的问题
<img width="575" alt="image" src="https://user-images.githubusercontent.com/10770362/57834353-b2f78b00-77ee-11e9-9bce-699639a48008.png">

**Comment by xhh1993** [comment]
非常感谢耐心回复，但是7.0.1的版本和我项目不兼容，始终编译不了。我再看看其他办法吧

**Comment by CarGuo** [comment]
你可以看看修改了什么，然后改一下就可以了

**Comment by Domlaa** [comment]
> 7.0.1 针对 surface 修复过，虽然不是全屏，但你这个看起来也是类似 surface 切换的问题
> <img alt="image" width="575" src="https://user-images.githubusercontent.com/10770362/57834353-b2f78b00-77ee-11e9-9bce-699639a48008.png">

大佬求教，现在用的是最新的版本，还是会有这个问题。
