### ISSUE TITLE
如何判断播放类型

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#2012]
## 问题描述：

如何判断是直播还是普通的视频文件，直播如何不然进度条和textview动，使用exoplayer的内核

## 问题机型/系统：

魅蓝note3

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3‘

**Comment by CarGuo** [comment]
是直播还是普通的视频文件 这个让你后台告诉你啊·····
至于不让进度条和拖动你看源码的 emptyvideo 那个

**Comment by oveeeee** [comment]
> 是直播还是普通的视频文件 这个让你后台告诉你啊·····
> 至于不让进度条和拖动你看源码的 emptyvideo 那个

emmmm我是前后台一起做的，我记得exoplayer有个方法可以判断，不知道这个项目有没有暴露出来
