### ISSUE TITLE
直播问题

### ISSUE THREAD

**Issue by oveeeee** [CarGuo/GSYVideoPlayer#2013]
## 问题描述：

播放直播时，进度条会动，几秒刷新一次。如何不让他刷新进度条

直播源
http://hls1a.douyucdn.cn/live/288016rlols5_2200/playlist.m3u8?wsSecret=f8392e76f18d9248ab4fe790ba3e5952&wsTime=1558063584&token=h5-douyu-0-288016-9d2456b5d4d1dcf7848571e5332424d8&did=afa52d9a861296fa5ca5537e00021531

内核用的exoplayer
## 问题机型/系统：

魅蓝note3

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
重载 getLayoutId
