### ISSUE TITLE
getAudioSessionId空指针

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [CarGuo/GSYVideoPlayer#2017]
## 问题描述：

因为做均衡器，需要获取AudioSessionId，使用了1.videoPlayer.getGSYVideoManager().getPlayer().getMediaPlayer().getAudioSessionId()
2.GSYVideoManager.instance().getCurPlayerManager().getMediaPlayer().getAudioSessionId()
均报空指针，1.是getPlayer为空，2是getCurPlayerManager为空

## 问题机型/系统：

真机 htc android4.4 小米9 se android 9.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by AndroidJohnsonWang** [comment]
在onPrepared获取倒是有时候没问题，但有时报错 Option ijkapplication not found.然后audioSessionId=0

**Comment by CarGuo** [comment]
Option ijkapplication not found. 这个不是错误，默认就会有的
