### ISSUE TITLE
有画面没声音

### ISSUE THREAD

**Issue by zfl5232577** [CarGuo/GSYVideoPlayer#2018]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）
（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

有画面没声音
播放连接，hls协议
http://gslb.dianshihome.com/gslb/live?stream_id=hunan

## 问题机型/系统：

例如 真机 小米6 Android8.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

使用的默认的内核

问题代码：(如果有)

## 问题log（如果有）
Audio: mp3 ([3][0][0][0] / 0x0003), 0 channels
音频格式

**Comment by CarGuo** [comment]
Audio: mp2 ，如果需要支持mp2，要自定义so打包，参考 
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md
https://www.jianshu.com/p/bd289e25d272

**Comment by dendrocyte** [comment]
您好, 我也是遇到要播放mp2的問題, 已定義so打包,
請問我該怎麼將so置換？

我是引用這幾包library
`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'
    //是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.0.2'
    //更多ijk的编码支持
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.0.2'`

**Comment by CarGuo** [comment]
将 so 放入主项目内，不依赖远程so

**Comment by dendrocyte** [comment]
我參考了https://github.com/CarGuo/GSYVideoPlayer/issues/1942
移植了自編繹的so 放入專案裡
但是我仍然需要hls live 做exoplayer

目前引入的library
`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'
    //是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.0.2'`

使用
PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)
卻會出現error

請問我也要自編繹exoplayer嗎？

**Comment by dendrocyte** [comment]
我照著您的說法做了, 但仍無法播放, 故另開新的issue 詢問, 感謝您的回覆
