### ISSUE TITLE
播放过程中播放地址失效 403，会一直发重试消息，不能提示缓冲失败

### ISSUE THREAD

**Issue by heil-look** [CarGuo/GSYVideoPlayer#2019]
播放过程中播放地址失效，返回403错误，结果播放器不调用播放错误接口。
不断的打印日志。日志如下.

E/IJKMEDIA: stream 1, offset 0x4b3feb6: partial file
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
D/IJKMEDIA: request: GET /00d6605d42d8c882e51a676fe66a9262?sign=4096fe40408f6615c9fc781e6330db56&t=5ce79462 HTTP/1.1
    User-Agent: Lavf/57.56.100
    Accept: */*
    Range: bytes=78905014-
    Connection: close
    Host: movies.ks.51tv.com
    Icy-MetaData: 1
W/IJKMEDIA: HTTP error 403 Forbidden
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4

**Comment by CarGuo** [comment]
有链接提供测试嘛

**Comment by heil-look** [comment]
测试地址，30分钟后失效:https://movies.ks.51tv.com/00d6605d42d8c882e51a676fe66a9262?sign=33d31fca9e9884db7de6f7d62682ae71&t=5ce7f175

**Comment by CarGuo** [comment]
试试 PlayerFactory.setPlayManager(Exo2PlayerManager.class);

**Comment by heil-look** [comment]
Exo2PlayerManager好像没有问题，不会重复请求，会提示出错。这么说就是ijkplayer的问题了，请问有办法解决么？

**Comment by CarGuo** [comment]
ijkplayer 目前暂停维护了，有需要还是 Exo2PlayerManager 吧
