### ISSUE TITLE
提供下载功能了么？

### ISSUE THREAD

**Issue by tenda2014** [CarGuo/GSYVideoPlayer#2021]
## 问题描述：

我想实现下载功能
请问框架内提供下载了么？有没有什么方法可以实现，包括mp4格式和m3u8格式。

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
Mp4全是有，m3u8没有，目前你可以自定义mediaSource或者自定义playmanager实现

**Comment by yyg20101** [comment]
> Mp4全是有，m3u8没有，目前你可以自定义mediaSource或者自定义playmanager实现

MP4的下载方式，是不是
GSYVideoManager.instance().getCurCacheManager().doCacheLogic(this,GSYVideoManager.instance().getPlayer().getMediaPlayer(),"http://xxxxx.mp4",null,null);

**Comment by CarGuo** [comment]
不是，直接通过内置的 AndroidVideoCache 框架，获取到本地 127 ip服务地址，然后直接用http下载这个地址就好了。视频播放的时候会同样通过这个地址读取缓存，但是记得开始播放的时候要暂停下载

**Comment by yyg20101** [comment]
> 不是，直接通过内置的 AndroidVideoCache 框架，获取到本地 127 ip服务地址，然后直接用http下载这个地址就好了。视频播放的时候会同样通过这个地址读取缓存，但是记得开始播放的时候要暂停下载

我发的那个是从播放代码中挖出来的，我如果需要预下载mp4，有没有demo代码片段。另外如果我是exo模式，缓存策略应该就是内置的exo缓存策略了。

**Comment by CarGuo** [comment]
新 demo 增加 https://github.com/CarGuo/GSYVideoPlayer/commit/dba2125db83decf90ed78846a79d2eccf190fd39

**Comment by may7be** [comment]
> 不是，直接通过内置的 AndroidVideoCache 框架，获取到本地 127 ip服务地址，然后直接用http下载这个地址就好了。视频播放的时候会同样通过这个地址读取缓存，但是记得开始播放的时候要暂停下载

请问一下，怎么暂停？requestCall.cancel()吗？ @CarGuo
