### ISSUE TITLE
minSdkVersion 16怎样兼容呢？

### ISSUE THREAD

**Issue by Achenglove** [CarGuo/GSYVideoPlayer#2022]
## 问题描述：

本项目最低版本是16，博主项目得最低版本是19，需要怎样处理才能兼容到最低为16的版本呢？

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'

**Comment by CarGuo** [comment]
源码依赖吧，然后去除exoplayer的依赖

**Comment by Achenglove** [comment]
以这种方式结合依赖？
implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'

//根据你的需求ijk模式的so
implementation 'com.shuyu:gsyVideoPlayer-armv5:7.0.1'
implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.0.1'
implementation 'com.shuyu:gsyVideoPlayer-arm64:7.0.1'
implementation 'com.shuyu:gsyVideoPlayer-x64:7.0.1'
implementation 'com.shuyu:gsyVideoPlayer-x86:7.0.1'

**Comment by CarGuo** [comment]
这个你看网上的在AndroidManifset中用replace等声明咯
