### ISSUE TITLE
连续播放11-12个视频就卡顿好几秒

### ISSUE THREAD

**Issue by huluxia** [CarGuo/GSYVideoPlayer#2024]
每次在新打开的activity里面连续点开11-12个视频，就卡好几秒，甚至软件无响应，这是什么问题

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by CarGuo** [comment]
连续11-12个activity内存…卡很正常，一般企业都会做activity复用管理，不会进入activity无限堆栈的……

**Comment by huluxia** [comment]
可能我没有说明白，就是视频列表显示在一个activity中，我打开关闭这个列表中的视频，当在11-12时候，就直接卡黑屏了，得过几秒才能播放，有时候直接失去响应。我看其他人也提过这个问题，就是那个频繁打开视频的issuse，我和他一个问题，不过我用的新版也有这个问题，内核用的是


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Lollipopll** [comment]
请问有解决方案吗？我这边也是同样的问题，主要用在列表播放，频繁的滑动切换就会卡顿

**Comment by CarGuo** [comment]
可能存在是release的问题，试试在release和播放之前稍等一下

**Comment by huluxia** [comment]
就是在我说的那个数值容易出那个问题，后面播放几十个也不会，有点纳闷了


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
