### ISSUE TITLE
下载好的视频m3u8，concat， 不支持 2倍以上倍速

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#2026]
下载好的视频m3u8，concat， 不支持 2倍以上倍速

**Comment by CarGuo** [comment]
本来就不支持2倍以上

**Comment by yang0000meng** [comment]
在线的m3u8 ，concat  都支持2倍以上 ，
下载好的 mp4 也支持 2倍以上，
下载好的 m3u8，concat 不支持吗

**Comment by CarGuo** [comment]
我记得2倍以上一直都是兼容有问题，所以我一直都写着0.5-2倍

**Comment by yang0000meng** [comment]
好吧 ，知道了
