### ISSUE TITLE
亮度调节dialog全屏显示不全

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [CarGuo/GSYVideoPlayer#2029]
## 问题描述：

当横屏并全屏隐藏状态栏和底部导航栏的时候，调节亮度dialog时，显示不全。
如果自定义亮度dialog xml，写死固定边距UI会不好看，因为亮度dialog需要和音量dialog一样，跟随底部导航的消失显示变换间距。不知道为什么音量的dialog没有这个问题

## 问题机型/系统：

真机 小米9 se Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的List全屏和小窗口列表界面（有底部导航的手机）

**Comment by CarGuo** [comment]
红米pro5，有底部导导航

<img width="606" alt="image" src="https://user-images.githubusercontent.com/10770362/58522992-4a98a880-81f5-11e9-8548-38720ca7fb5a.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/10770362/58523007-51272000-81f5-11e9-871b-d6b691f56ca7.png">

**Comment by AndroidJohnsonWang** [comment]
Htc m8sw android 4.4
![Screenshot_2019-05-29-09-51-48](https://user-images.githubusercontent.com/15881869/58524035-5dad7780-81f9-11e9-9eb4-5595858b9eba.png)

Nokia x6  android9.0
![Screenshot_2019-05-29-09-56-24](https://user-images.githubusercontent.com/15881869/58524039-630ac200-81f9-11e9-898a-8798b71cbc7e.png)

另外，google Nexus6底部导航栏出来的时候也会挡住，demo只有一种状态所以体现不出来**

**Comment by CarGuo** [comment]
底部导航栏出来的时候也会挡住很正常，但是底部导航收起来的时候，应该是显示的啊，特别是第一个，已经绘制上了，怎么会挡住？rom的问题？有看到原因吗？

**Comment by AndroidJohnsonWang** [comment]
没找到原因，特意把手机反过来，让音量diaolg那边靠近导航栏，发现音量diaolg会随着导航栏出现和消失自动变化位置，不会被挡住，检查发现两边dialog写法没有什么不同，不知道是不是其他地方处理了什么

**Comment by CarGuo** [comment]
感觉就是布局文件的不同和代码layoutparams不同，我这里没办法复现，刚更新了demo，你看看能不能复现

**Comment by AndroidJohnsonWang** [comment]
还是不行，我用模拟器测试可以复现
![image](https://user-images.githubusercontent.com/15881869/58525822-af590080-81ff-11e9-840c-d737c5e60e03.png)
模拟器版本
![image](https://user-images.githubusercontent.com/15881869/58525939-15de1e80-8200-11e9-9420-3a25fe090977.png)

**Comment by CarGuo** [comment]
刚刚提交，已经解决

**Comment by AndroidJohnsonWang** [comment]
亮度照着这样改了没问题了，滑动改变音量的会挂掉
![image](https://user-images.githubusercontent.com/15881869/58548115-47c0a680-823b-11e9-9f0d-c455a747b02d.png)

**Comment by AndroidJohnsonWang** [comment]
另外提一个MP4视频，编码是AVC1，只有声音没有视频，我重新编译so,开启了所有的格式也还是一样

**Comment by CarGuo** [comment]
失误失误，那个是我cv的问题。已经修改。

至于你的编码问题，你直接去看ffmpeg的配置吧
