### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by WalkingRoy** [CarGuo/GSYVideoPlayer#203]
![Uploading QQ图片20170430174954.jpg…]()
最新版本，一直提示内存泄漏，出现频率很高

**Comment by mejealousy** [comment]
内存泄漏信息：
GSYVideoPlayer 的 ProgressTimerTask 持有 context 
使用的是最新版本，工具 leakcanary，一直提示内存泄漏，出现频率很高
上一条图片一直看不了。。。

**Comment by CarGuo** [comment]
@mejealousy 请问下是那个版本？方便重新上传图片吗？

**Comment by mejealousy** [comment]
版本：1.6.4，不是最新
![1494229506 1](https://cloud.githubusercontent.com/assets/9346810/25794875/5cc24d1c-3405-11e7-9a95-bb2961362ae4.jpg)

**Comment by mejealousy** [comment]
@CarGuo

**Comment by CarGuo** [comment]
可以的话尝试最新版本。
