### ISSUE TITLE
Disable StandardGSYVideoPlayer Default Menu (Play/Pause Buttons)

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2030]
Hi there. First of all, thanks for the great work :)

1- How do I disable/hide default menu (e.g. Play/Pause button, Fast Forward options) when I play the video. I want no play/pause button, no fast forward detection, no progressBar, no nothing when the video plays.
2- How do I disable auto full screen mode when I rotate my device?

How do I do that?

I am following SimplePlayer demo and using StandardGSYVideoPlayer. Thanks again :)

**Comment by CarGuo** [comment]
I think you need something like this : 

https://github.com/CarGuo/GSYVideoPlayer/blob/6db7648038a8de03ee7fbb82d051dc12d9cbfa5c/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java

you can  override getLayoutId function to custom UI


2、 setRotateViewAuto false

**Comment by muzeasd** [comment]
> I think you need something like this :
> 
> https://github.com/CarGuo/GSYVideoPlayer/blob/6db7648038a8de03ee7fbb82d051dc12d9cbfa5c/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java
> 
> You can override getLayoutId function to custom UI
> 
> 2, setRotateViewAuto false

Thanks for the prompt answer. I hope if I don't use the custom UI, this functionality, EmptyControlVideo  will work. I have tried setRotateViewAuto(false). But it does not disable the auto full screen on rotation.

**Comment by CarGuo** [comment]
i not sure which template mode you choose in demo project

like `DetailPlayer.class` in Demo ，you can remove override  `onConfigurationChanged` function to avoid auto full screen on rotation.  

The key is `onConfigurationChanged ` and `OrientationUtils`

**Comment by muzeasd** [comment]
Ok. I just tried **EmptyControlVideo**. It is not working. I just copy pasted the code, used this control in my XML file. Then wherever I was using _StandardGSYVideoPlayer_ , I replaced it with EmptyControlVideo.
