### ISSUE TITLE
androidx 项目引入GSYVideoPlayer 编译不通过

### ISSUE THREAD

**Issue by xiandao** [CarGuo/GSYVideoPlayer#2031]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

androidx 项目引入GSYVideoPlayer 编译不通过

我在项目中使用了databing , livedata

## 问题机型/系统：

小米8 ，Android系统9

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.0.1'

## Demo中的复现步骤
gradle.properties 中：

android.useAndroidX=true
android.enableJetifier=true
android.enableAapt2=false

build.gradle 中：
implementation 'com.shuyu:GSYVideoPlayer:7.0.1'

问题代码：(如果有)
没有写代码，一编译就出问题

## 问题log（如果有）

错误: 不兼容的类型: MainActivity无法转换为LifecycleOwner

**Comment by CarGuo** [comment]
类似冲突问题需要你自己处理

**Comment by qqnp1100** [comment]
原因：
引入GSYVideoPlayer后，`androidx.core`版本为`1.1.0-alpha02`，该版本有bug，`ComponentActivity`没有`LifecycleOwner`接口。
解决方法：
```
    implementation('com.shuyu:gsyVideoPlayer-java:7.0.1') {
        exclude group: 'android.core'
    }
```
然而并没有什么卵用，`androidx.core`版本还是`1.1.0-alpha02`
百度半天才发现`enforcedPlatform`可以强制覆盖版本。。。
```
    implementation enforcedPlatform('androidx.core:core:1.0.2')
```
这样就可以=.=

**Comment by CarGuo** [comment]
@qqnp1100 正确打开方式👍👍👍
