### ISSUE TITLE
More than one file was found with OS independent path 'lib/armeabi-v7a/libijkplayer.so'

### ISSUE THREAD

**Issue by SheepYang1993** [CarGuo/GSYVideoPlayer#2032]
## 问题描述：

More than one file was found with OS independent path 'lib/armeabi-v7a/libijkplayer.so'

## 问题机型/系统：

真机 小米note2 Android7.0

## GSY依赖版本

使用了以下依赖
```
implementation('com.shuyu:GSYVideoPlayer:6.0.3') {
    exclude group: "com.android.support"
}
implementation('com.shuyu:gsyVideoPlayer-armv7a:6.0.3') {
    exclude group: "com.android.support"
}
implementation('com.shuyu:gsyVideoPlayer-ex_so:6.0.3') {
    exclude group: "com.android.support"
}
implementation('com.shuyu:GSYVideoPlayer-exo2:6.0.3') {
    exclude group: "com.android.support"
}
```

## Demo中的复现步骤

编译无报错，run的时候报错。

**Comment by CarGuo** [comment]
看问题集锦，ndk过滤了解下

**Comment by teller110** [comment]
implementation 'com.shuyu:GSYVideoPlayer:7.1.1'
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.1'
ndk{
        abiFilters('armeabi', 'armeabi-v7a')
   }

More than one file was found with OS independent path 'lib/armeabi-v7a/libijkplayer.so'
