### ISSUE TITLE
列表中采用GSYVideoType.SCREEN_TYPE_FULL 没有裁剪的问题

### ISSUE THREAD

**Issue by 465857721** [CarGuo/GSYVideoPlayer#2033]
## 问题描述：
在列表中，竖向视频，特殊比例（例如5：4 高5 宽4），采用SCREEN_TYPE_FULL视频没有裁剪反而压缩了 

## 问题机型/系统：

 真机 小米note2 Android8.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
请提供视频源
