### ISSUE TITLE
EXO内核滑动快进

### ISSUE THREAD

**Issue by GentlemanAyy** [CarGuo/GSYVideoPlayer#2034]
问题描述：
    滑动屏幕快进,如果播放器正处于加载中,进度会置0
问题机型/系统： 
    真机 9.0 hw mate20pro
GSY依赖版本:
    implementation 'com.shuyu:GSYVideoPlayer:7.0.1'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.0.1'
Demo中的复现步骤
        PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_DEFAULT);
        GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
        GSYVideoType.disableMediaCodec();

**Comment by GentlemanAyy** [comment]
在Demo中 自定义EXO中 快速左右滑动 会出现 进度归0

**Comment by CarGuo** [comment]
只有在 自定义EXO中 会出现？

**Comment by GentlemanAyy** [comment]
好像都有这个问题

**Comment by CarGuo** [comment]
收到

**Comment by CarGuo** [comment]
最近测试没能复现问题
