### ISSUE TITLE
播放器播放状态回调问题

### ISSUE THREAD

**Issue by Lollipopll** [CarGuo/GSYVideoPlayer#2035]
videocallback中只有一些btn的点击事件，请问调用onvideoresume或pause的时候没有更加详细的回调能说明是播放或者暂停吗？

**Comment by CarGuo** [comment]
不是很理解，你调用暂停了，不是你已经知道暂停了么？

**Comment by Lollipopll** [comment]
是因为有些业务依赖视屏正式绘制出来的状态，来回切页面的时候，通过调用videoResume好像没发现有相应的播放回调

**Comment by yunshuipiao** [comment]
@CarGuo 还有另一种情况，我在A位置点击暂停，需要在B位置收到状态做事情
