### ISSUE TITLE
设置的背景在视频播放后才生效

### ISSUE THREAD

**Issue by fjyuqiang** [CarGuo/GSYVideoPlayer#2038]
## 问题描述：

设置的背景在视频播放后才生效

## 问题机型/系统：

真机 小米MIX3 Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

按照Demo中simplePlayer的方法设置视频背景图，默认进入的时候显示的是黑屏，只有视频播放一次之后才生效。
问题代码：(如果有)
//增加封面
        ImageView imageView = new ImageView(this);
        imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
        imageView.setImageResource(R.mipmap.xxx1);
        videoPlayer.setThumbImageView(imageView);

**Comment by CarGuo** [comment]
？？怎么复现的？？demo

**Comment by fjyuqiang** [comment]
下面是设置的方法，xml里是嵌套在CollapsingToolbarLayout里的
private void initPlayer() {
        //增加封面
        ImageView imageView = new ImageView(this);
        imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
        imageView.setImageDrawable(getResources().getDrawable(R.drawable.bg_cherish_topic));
        //设置旋转
        orientationUtils = new OrientationUtils(this, videoPlayer);
        //视频Builder配置
        GSYVideoOptionBuilder gsyVideoOptionBuilder = new GSYVideoOptionBuilder();
        gsyVideoOptionBuilder
                .setThumbImageView(imageView) //设置封面
                .setIsTouchWiget(true) //是否可以滑动界面改变进度，声音等
                .setRotateViewAuto(false)  //是否开启自动旋转
                .setLockLand(false) //一全屏就锁屏横屏，默认false竖屏，可配合setRotateViewAuto使用
                .setAutoFullWithSize(true) //是否根据视频尺寸，自动选择竖屏全屏或者横屏全屏，注意，这时候默认旋转无效
                .setShowFullAnimation(true) //是否使用全屏动画效果
                .setNeedLockFull(false) //是否需要全屏锁定屏幕功能 如果单独使用请设置setIfCurrentIsFullscreen为true
                .setThumbPlay(true) //是否点击封面可以播放
                .setCacheWithPlay(false) //是否边缓存，m3u8等无效
                .setStartAfterPrepared(false) //是否自动播放
                .setUrl(video_url) //播放url
                .setVideoTitle("")//视频title
                .setNeedShowWifiTip(true)
                .setVideoAllCallBack(new GSYSampleCallBack() {
                    @Override
                    public void onPrepared(String url, Object... objects) {
                        super.onPrepared(url, objects);
                        //开始播放了才能旋转和全屏
                        videoPlayer.startAfterPrepared();
                        orientationUtils.setEnable(true);
                        isPlay = true;
                    }

                    @Override
                    public void onQuitFullscreen(String url, Object... objects) {
                        super.onQuitFullscreen(url, objects);
                        if (orientationUtils != null) {
                            orientationUtils.backToProtVideo();
                        }
                    }
                }).setLockClickListener(new LockClickListener() {
            @Override
            public void onClick(View view, boolean lock) {
                if (orientationUtils != null) {
                    //配合下方的onConfigurationChanged
                    orientationUtils.setEnable(!lock);
                }
            }
        }).build(videoPlayer);
        //显示wifi确定框
        videoPlayer.startPlayLogic();
        //隐藏返回键
        videoPlayer.getBackButton().setVisibility(View.GONE);
        //设置全屏按键功能,这是使用的是选择屏幕，而不是全屏
        videoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //直接横屏
                orientationUtils.resolveByClick();

                //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                videoPlayer.startWindowFullscreen(GameDetailActivity.this, true, true);
            }
        });

**Comment by CarGuo** [comment]
我需要的是demo中的复线步骤

**Comment by fjyuqiang** [comment]
demo中的复现步骤，没懂意思
上面流程参照Demo中的ScrollingActivity.class来的

**Comment by fjyuqiang** [comment]
已经找到问题了，我是原来流程：
增加封面-配置视频-隐藏组件标题和返回
改为：
增加封面-隐藏组件标题和返回-配置视频
已正常显示

**Comment by CarGuo** [comment]
ok
