### ISSUE TITLE
在recyclerView中使用如何实现划出屏幕暂停功能，谢谢

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#2040]

**Comment by CarGuo** [comment]
默认模式只有一个内核，滑出屏幕暂停你就没办法播放新的哦，你可以参考demo中小窗口支持的列表例子，滑出的时候不显示小窗口而是暂停

**Comment by ZJLeBron** [comment]
谢谢，我加了onScrollStateChanged监听item是否划出屏幕已经解决这个问题，你的小窗口功能是通过onScrollStateChanged监听的吗

**Comment by CarGuo** [comment]
是的
