### ISSUE TITLE
DetailPlayerActivity设置一个卡顿点，小屏幕调用changeUiToPlayingBufferingShow()方法会有加载loading,全屏调用该方法无效

### ISSUE THREAD

**Issue by zhaowenhao2015** [CarGuo/GSYVideoPlayer#2041]
## 问题描述：
你好，我DetailPlayerActivity设置一个卡顿点，小屏幕调用changeUiToPlayingBufferingShow()方法会有加载loading,全屏调用该方法无效，这是什么原因？
## 问题机型/系统：
 真机 
## GSY依赖版本
 `implementation 'com.shuyu:GSYVideoPlayer:6.0.1'`
## Demo中的复现步骤
我是使用的是demo里面DetailPlayerActivity和LandLayoutVideo

问题代码：(如果有)
DetailPlayerActivity类中
在这个.setGSYVideoProgressListener(new GSYVideoProgressListener() {
                    @Override
                    public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
                         int curTime = (int) (currentPosition / 1000f);
                        memberManager(progress, currentPosition, duration);

                    }
                })方法回调，做了下面方法逻辑
 public void memberManager(int progress, int currentPosition, int duration) {
        vpnKaDunTimes.add("10");
        vpnKaDunTimes.add("20");
        vpnKaDunTimes.add("30");
        //vpn 卡顿
        if (memberType == 1 && vpnKaDunTimes != null && vpnKaDunTimes.size() > 0) {
            if (vpnKaDunTimes.contains(currentPosition + "")) {
                //设置卡顿
                detailPlayer.kaDunPlay();
                curVpnShowDialog++;
                vpnKaDunTimes.remove(currentPosition + "");
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        detailPlayer.RelieveKaDunPlay();
                        //        vpn 弹窗
                        if (curVpnShowDialog >= vpnShowDialog) {
                            if (orientationUtils != null) {
                                orientationUtils.backToProtVideo();
                            }
                            getCurPlay().onVideoPause();
                            if (!memberVpnDialog.isShowing()) {
                                memberVpnDialog.show();
                            }
                            curVpnShowDialog = 0;
                        }
                    }
                }, 5000);
            }
        }
    }

LandLayoutVideo类中
 /**
     * 卡顿
     */
    public void kaDunPlay() {

        onVideoPause();
        changeUiToPlayingBufferingShow();
        surface_container.setClickable(false);

    }

    /**
     * 卡顿解除
     */
    public void RelieveKaDunPlay(){
                surface_container.setClickable(true);
                onVideoResume();
                changeUiToPlayingBufferingClear();
    }

**Comment by CarGuo** [comment]
你要确定调用的是不是全屏的那个，通过getCurrentPlayer()方法去调用

**Comment by zhaowenhao2015** [comment]
那全屏要如何去调用加载loading，是哪个方法？求指教

**Comment by zhaowenhao2015** [comment]
> 你要确定调用的是不是全屏的那个，通过getCurrentPlayer()方法去调用

那全屏要如何去调用加载loading，是哪个方法？求指教

**Comment by CarGuo** [comment]
不是很理解

**Comment by zhaowenhao2015** [comment]
> 不是很理解
我在LandLayoutVideo类中getLayoutId()横竖屏自定义了不同加载旋转的progressBar，在init（）方法中初始化，通过isIfCurrentIsFullscreen判断全屏时候，显示自定义progressbar，就报'void android.widget.ProgressBar.setVisibility(int)' on a null object reference空，而非全屏则没有问题，大佬这是什么原因？

**Comment by CarGuo** [comment]
没能复现问题

**Comment by zhaowenhao2015** [comment]
> 没能复现问题
我把复现的demo邮箱发给你了 ，你帮忙看一下好吗

**Comment by zhaowenhao2015** [comment]
大佬，我是在DetailPlayer和LandLayoutVideo中复现的，小屏播放卡顿暂停progressbar，FrameLayout surface_container显示没问题，全屏卡顿暂停就不会显示progressbar和surface_container。如果只在全屏布局sample_video_land  添加Progressbar组件，而正常的布局sample_video_normal不添加progressbar,还会报空null 。我设置的卡顿点是10s,20s，30s.
展示入口是demo里面的  按钮DETAIL模式   可以查看效果

大佬，小弟初入菜鸟，急需解决方案，有时间帮忙看一下，必有赞赏，跪谢




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 下午4:10
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "一枝笔"<776369672@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CarGuo/GSYVideoPlayer] DetailPlayerActivity设置一个卡顿点，小屏幕调用changeUiToPlayingBufferingShow()方法会有加载loading,全屏调用该方法无效 (#2041)




没能复现问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

GSYVideoPlayer-master.zip (132.18M, 2019年07月14日 08:38 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=763132399e0684963047741744360b4e0b03530054030c5515545608551b0d550c031f5b5a07004c0057060a56550b045d53025c622f39266b6864500653563154504b5c101b54004b45574b4c4c5011380c&t=exs_ftn_download&code=8129b69a

**Comment by CarGuo** [comment]
em···如果你需要的话，可以通过 getLayoutId 实现你自己的布局，如果 FrameLayout 可以你完全可以修改为 FrameLayout， 至于判空问题，你可以重载对应方法处理就好了

**Comment by zhaowenhao2015** [comment]
全屏调用onvediopause()后，自己定义的progressbar。setvisible(View.VISIBLE)没效果，不会显示呢

**Comment by zhaowenhao2015** [comment]
> em···如果你需要的话，可以通过 getLayoutId 实现你自己的布局，如果 FrameLayout 可以你完全可以修改为 FrameLayout， 至于判空问题，你可以重载对应方法处理就好了

全屏调用onvediopause()后，自己定义的progressbar。setvisible(View.VISIBLE)没效果，不会显示呢

**Comment by zhaowenhao2015** [comment]
> em···如果你需要的话，可以通过 getLayoutId 实现你自己的布局，如果 FrameLayout 可以你完全可以修改为 FrameLayout， 至于判空问题，你可以重载对应方法处理就好了

感觉全屏页面没有刷新，重新调用onVedioResume(),progressbar会闪一下就消失了呢

**Comment by CarGuo** [comment]
em·····所以问题是？

**Comment by zhaowenhao2015** [comment]
> em·····所以问题是？

我想实现全屏的时候调用onVedioPause()方法，旋转progressBar能显示出来，但是setVisible(VIew.visible)没有效果

**Comment by CarGuo** [comment]
这样？

```
.setVideoAllCallBack(new GSYSampleCallBack() {
                    @Override
                    public void onEnterFullscreen(String url, Object... objects) {
                        super.onEnterFullscreen(url, objects);
                        detailPlayer.getCurrentPlayer().onVideoPause();
                        ((LandLayoutVideo)detailPlayer.getCurrentPlayer()).showloading();
                    }
·····

    public void showloading() {
        changeUiToPlayingBufferingShow();
    }

```

**Comment by zhaowenhao2015** [comment]
> 这样？
> 
> ```
> .setVideoAllCallBack(new GSYSampleCallBack() {
>                     @Override
>                     public void onEnterFullscreen(String url, Object... objects) {
>                         super.onEnterFullscreen(url, objects);
>                         detailPlayer.getCurrentPlayer().onVideoPause();
>                         ((LandLayoutVideo)detailPlayer.getCurrentPlayer()).showloading();
>                     }
> ·····
> 
>     public void showloading() {
>         changeUiToPlayingBufferingShow();
>     }
> ```

  .setGSYVideoProgressListener(new GSYVideoProgressListener() {
                    @Override
                    public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
                      detailPlayer.onVideoPause();
                }).build(getCurPlay());

 public void showloading() {
        changeUiToPlayingBufferingShow();
    }

**Comment by CarGuo** [comment]
？？？？

**Comment by zhaowenhao2015** [comment]
> ？？？？

gsyVideoOption.setGSYVideoProgressListener(new GSYVideoProgressListener() {
                    @Override
                    public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
                        detailPlayer.getCurrentPlayer().onVideoPause();
                        ((LandLayoutVideo)detailPlayer.getCurrentPlayer()).showloading();
                    }
·····

    public void showloading() {
        changeUiToPlayingBufferingShow();
    }我是在这里面调用的

**Comment by zhaowenhao2015** [comment]
> ？？？？

gsyVideoOption.setGSYVideoProgressListener(new GSYVideoProgressListener() {
@override
public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
         detailPlayer.onVideoPause();
}).build(getCurPlay());

public void showloading() {
          changeUiToPlayingBufferingShow();
}

**Comment by zhaowenhao2015** [comment]
> ？？？？
我是在这里面调用的呢

**Comment by zhaowenhao2015** [comment]
> ？？？？

找到原因了 ，detailPlayer一直是非全屏的呢，进全屏的时候把全屏的对象赋值给他就好了，尴尬谢谢大佬
