### ISSUE TITLE
关于横竖屏切换，ui不同步问题

### ISSUE THREAD

**Issue by wangyikai1234567** [CarGuo/GSYVideoPlayer#2042]
## 问题描述：
我再框架的基础上 添加了一textview充当字幕，竖屏的时候显示正常，但是切换到横屏之后字幕内容不随进度的改变而改变。（ps：我的textview没有写在 layout_bottom中），

## 问题机型/系统：

真机 三星s6  但是与机型无关

## GSY依赖版本

 compile 'com.shuyu:GSYVideoPlayer:5.0.2'

## Demo中的复现步骤

额，，，这个 切换横竖屏的时候就会复现
 是需要我再自定义一个全屏的layout么？

**Comment by CarGuo** [comment]
你需要看看demo或者GSYBaseVideoPlayer，通过cloneParams和showxxxxxfull与resolvenormalxxx方法，同步状态和现实，你看源码的视线，或者你直接看demo中弹幕的例子

**Comment by wangyikai1234567** [comment]
谢谢，看了弹幕的，明白了------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>
发送时间: 2019年6月4日(星期二) 晚上7:36
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "wangyikai1234567"<2285281993@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CarGuo/GSYVideoPlayer] 关于横竖屏切换，ui不同步问题 (#2042)



你需要看看demo或者GSYBaseVideoPlayer，通过cloneParams和showxxxxxfull与resolvenormalxxx方法，同步状态和现实，你看源码的视线，或者你直接看demo中弹幕的例子
 
&mdash;
