### ISSUE TITLE
获取原始视频宽高,在画面出现前处理

### ISSUE THREAD

**Issue by mikeliu60** [CarGuo/GSYVideoPlayer#2045]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

大哥，我现在想要 在画面出现前 获取mp4的原始宽高，然后如果高度大于宽度就拉伸视频，有没有什么方法可以调用

## 问题机型/系统：

all

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by mikeliu60** [comment]
我有一个思路就是 因为我们的视频moov在前面  获取moov 读取里面的宽高信息
<img width="286" alt="屏幕快照 2019-06-08 下午3 16 05" src="https://user-images.githubusercontent.com/6337551/59143740-7c351f00-8a00-11e9-987b-0b98f3265bb2.png">

**Comment by CarGuo** [comment]
em····你可以参考Demo ，自定义Surface。

比如 CustomRenderView 中的实例

**Comment by mikeliu60** [comment]
> 
> 
> em····你可以参考Demo ，自定义Surface。
> 
> 比如 CustomRenderView 中的实例

大哥 昨天研究了一下，不太清楚应该自定义哪些点，大哥能不能提点一下，我现在正在看surfacetexture egl 这些

**Comment by CarGuo** [comment]
Demo 中不是有 CustomRenderView 么，它使用了自定义的  surface 控件，你可以参考源码实现一个你自己的，比如参考 GSYTextureView 。 关键代码是 MeasureHelper

**Comment by mikeliu60** [comment]
> Demo 中不是有 CustomRenderView 么，它使用了自定义的 surface 控件，你可以参考源码实现一个你自己的，比如参考 GSYTextureView 。 关键代码是 MeasureHelper

大哥，我参考GSYTextureView自定义了一下，发现效果和设置match full一样，都是初始画面原始比例，过一秒后才拉伸，不知道是我定义的不对呢(修改了getCurrentVideoHeight让他返回view的高)，还是需要加个surfacetexture做个二次处理

**Comment by CarGuo** [comment]
事实上视频 onPrepared 之后就可以获得宽高了，之后就是 add 这个显示的view 进去，时机可能需呀你自己把控下

**Comment by mikeliu60** [comment]
> 事实上视频 onPrepared 之后就可以获得宽高了，之后就是 add 这个显示的view 进去，时机可能需呀你自己把控下

大哥，忘了说一点，我们的视频播放是像抖音首页那样可以上下滑动的，每次都是先原始比例，然后过一秒再拉伸，不知道是不是和列表有关

**Comment by CarGuo** [comment]
em····有gif之类的可以看看嘛

**Comment by mikeliu60** [comment]
> em····有gif之类的可以看看嘛

哥，已经解决了，是thumbimage高度比视频高度小造成的，重新设置下图片大小就OK了，非常感谢哥耐心的解答
