### ISSUE TITLE
重写了封面消失的方法，在prepared过程保持显示封面，但是在刚开始播放的时候会有一个闪烁

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#2046]
就像RecyclerView的notifyItemChange触发的闪烁动画一样，请问如何取消这个闪烁，谢谢

**Comment by CarGuo** [comment]
？？？场景在demo怎么复现

**Comment by ZJLeBron** [comment]
已参考SampleCoverVideo解决此问题

**Comment by ZJLeBron** [comment]
> ？？？场景在demo怎么复现

 player.setThumbImageView(ivFocusImg);但是我用这个方法设置封面后，在prepared完成后开始播放的时候就会闪烁一下
