### ISSUE TITLE
这个问题我也复现了，全屏返回不能返回，一般先竖屏再返回到原大小，可是竖屏之后没返回原大小，我的测试机手机必现概率90%了，全屏返回修复一下策略吧，能直接返回不，别先把视频竖向再返回，能否改用监听传感器？

### ISSUE THREAD

**Issue by xuywei** [CarGuo/GSYVideoPlayer#2049]
这个问题我也复现了，全屏返回不能返回，一般先竖屏再返回到原大小，可是竖屏之后没返回原大小，我的测试机手机必现概率90%了，全屏返回修复一下策略吧，能直接返回不，别横向，是不是跟陀螺仪太灵敏的缘故

_Originally posted by @xuywei in https://github.com/CarGuo/GSYVideoPlayer/issues/606#issuecomment-500320993_

**Comment by CarGuo** [comment]
………
Demo复现步骤

**Comment by yang0000meng** [comment]
全屏 返回 确实有问题 ，我都是强制退出activty  解决了
