### ISSUE TITLE
如何播放本地视频文件？

### ISSUE THREAD

**Issue by westlinkin** [CarGuo/GSYVideoPlayer#205]

**Comment by CarGuo** [comment]
直接传本地文件路径

**Comment by westlinkin** [comment]
在`StandardGSYVideoPlayer`的上，用`public boolean setUp(String url, boolean cacheWithPlay, Object... objects)` 这个方法，url为file path，不能播放本地视频。

网络视频可以播放，但将这个url的mp4文件下载下来后，当做本地视频来播放，就放不了了

**Comment by CarGuo** [comment]
请确定路径正确，并且文件已经存放到sd上，因为播放本地文本是没问题，网络文件在缓存之后也是作为本地文件播放，所以你需要看看使用上那里出现了问题

**Comment by westlinkin** [comment]
必须放到`Environment.getExternalStorageDirectory()`下吗？ 放到`Context.getCacheDir()`下不行么

**Comment by CarGuo** [comment]
播放前用file.exist判断下文件是否存在先

**Comment by westlinkin** [comment]
确实是我自己的问题。

**Comment by huangxiaoyu** [comment]
> 确实是我自己的问题。

我也遇到这个问题 你是怎么处理的  我也是mp4下载本地 用Exo2PlayerManager可以播放,使用IjkPlayerManager就不能播放  提示找不到文件

**Comment by lzxshare** [comment]
播放器播放本地视频时例如手机相册里面的视频，会一直处于加载状态，无法播放，应该是没有适配安卓10，安卓10不能通过文件路径直接访问文件，要用uri去访问，这个希望作者适配下

**Comment by huangxiaoyu** [comment]
> 播放器播放本地视频时例如手机相册里面的视频，会一直处于加载状态，无法播放，应该是没有适配安卓10，安卓10不能通过文件路径直接访问文件，要用uri去访问，这个希望作者适配下

播放地址支持uri   你传个uri进去不就行了

**Comment by wangyangzi** [comment]
> 确实是我自己的问题。

你他喵倒是说下是什么问题啊
