### ISSUE TITLE
Prevent Video Restart upon Orientation Change

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2052]
Hi. Is there any way I can prevent video restart (all that video setup and play process starting all over again) upon screen orientation change? When I change my screen from Portrait to Landscape, the video setup process starts all over again which is feels really bad? Can I achieve this with EmptyVideoControl? Thanks for any input :)

**Comment by CarGuo** [comment]
it is reproduced in the demo program?

Did you  configuration All activity in AndroidManifest like demo?

```
       <activity
            android:name=".PlayEmptyControlActivity"
            /// this configChanges and screenOrientation
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait" />
```

**Comment by muzeasd** [comment]
It worked :) But another small issue arised after this. 

My landscape layout file shows only EmptyControlVideo with width and height set as "match_parent". Everything else is  "gone". Still video player only takes half the screen. And rest of it is visible and empty. Can you guide why ?
