### ISSUE TITLE
全局设置GSYVideoType.SCREEN_TYPE_FULL，效果是拉伸变形而不是裁剪。

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#2055]
demo中的PlayActivity中切换到全屏模式正常，但是退出该页面打开其他页面，就不裁剪效果了，而是拉伸效果，请问怎么解决

**Comment by ZJLeBron** [comment]
设置成裁剪模式，打开demo中“带广告”页面，广告是被拉伸的而不是裁剪

**Comment by CarGuo** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/10770362/59398949-bcabe880-8dc4-11e9-9b73-b7efbe9cb33f.png">

**Comment by ZJLeBron** [comment]
我用的是SCREEN_TYPE_FULL，而且父布局是FrameLayout；demo只有SampleVideo设置SCREEN_TYPE_FULL正常，其他页面的播放器是被拉伸的而不是裁剪，应该是和你的SampleVIdeo封装有关系，我正在看

**Comment by CarGuo** [comment]
应该是  SampleVideo 的 getlayoutId

 public int getLayoutId() {
        return R.layout.sample_video;
    }

surface_container 是 FrameLayout

默认是
    <RelativeLayout
        android:id="@+id/surface_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center">

    </RelativeLayout>

**Comment by ZJLeBron** [comment]
大佬，你为啥不把默认的封装成Framlayout，RelativeLayout有这个bug还把它设置成默认的，是有其他作用考虑吗

**Comment by CarGuo** [comment]
忘记了，历史太悠久了，貌似我记得某些场景需要re
