### ISSUE TITLE
我遇到recycleView错位和在fragment里面无法全屏（已经处理）

### ISSUE THREAD

**Issue by adminqqz** [CarGuo/GSYVideoPlayer#2056]
## 问题描述：
我遇到两个问题，已经处理完成
1、HomeFragment 首页的播放器,点击全屏无法旋转。
2、recycleView 滑动。列表出现空白,这个问题是item 父体要设置warp_conten

处理办法,需要在承载 Fragment的 Activity上添加 需要添加（具体参数参考demo）
            android:name=".ui.activity.MainActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Translucent"/>

**Comment by CarGuo** [comment]
？？？？？？？
Demo复现步骤

**Comment by adminqqz** [comment]
![QQ图片20190613151200](https://user-images.githubusercontent.com/12959954/59411365-a7977f80-8ded-11e9-9200-835bfabcaf11.png)
![QQ图片20190613151200ss](https://user-images.githubusercontent.com/12959954/59411393-b8e08c00-8ded-11e9-9a9c-b1a66385556b.png)

出现了kongb空白后，点击一个视频播放，又展现出来了，请问如何处理。

**Comment by adminqqz** [comment]
还有一个问题，就是这个项目，MainActivity+Fragment+videoFragment+newsFragment 
在videoFragment 里面点击全屏旋转了过后。就暂停了。呜呜，怎么办

**Comment by CarGuo** [comment]
首先，请参考demo和问题集锦，然后再demo中尝试复现
然后，你的这个问题其中一点有点像是没有配置 AndroidManifest

**Comment by adminqqz** [comment]
> 首先，请参考demo和问题集锦，然后再demo中尝试复现
> 然后，你的这个问题其中一点有点像是没有配置 AndroidManifest

回答。frament无法全屏处理好了。需要在MainActivity添加 
  <activity
            android:name=".ui.activity.MainActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Translucent"/>

**Comment by adminqqz** [comment]
关于RecycleView 列表视频滑动出现空白处的问题，在demo里面我试不出来。从demo里面来看listView有个tag. 而recycleView 好像不需要

**Comment by CarGuo** [comment]
你还是看demo对比下吧

**Comment by adminqqz** [comment]
> 你还是看demo对比下吧

ok！大佬 呜哇。
