### ISSUE TITLE
exoplayer seekto 临近帧

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#2058]
能否设置 跳转到 临近帧。
ExoPlayer默认seekto的时候是精准帧，在2.7.0之后可以通过ExoPlayer.setSeekParameters(SeekParameters.XXX);修改为上一帧，下一帧，临近帧，精准帧四种。

晚上高峰期  有写 m3u8  比较卡， seekto  有得重新加载4，5次 才能seekto  成功。
监控http  m3u8  是加载成功 了，ts 切片也加载成功了。

**Comment by CarGuo** [comment]
暂时你可以需要参考 https://github.com/CarGuo/GSYVideoPlayer/tree/e686ae6cdc8500361e27f21786a9ab170103c1cb/app/src/main/java/com/example/gsyvideoplayer/exo  自定义exo接入

**Comment by CarGuo** [comment]
现版本可通过自定义playermanager解决
下版本内置支持
