### ISSUE TITLE
setSeekOnStart方法耗时会有短暂黑屏，请问如何取消黑屏，在setSeeKOnStart方法中显示封面或者减少耗时

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#2059]

**Comment by ZJLeBron** [comment]
另外，我的播放器跳转到其他页面设置为CURRENT_STATE_PAUSE专题，在新的页面返回后却变成CURRENT_STATE_NORMAL状态了

**Comment by CarGuo** [comment]
用问题集锦种的 seek-at-start 试试

问题2 默认情况下只有一个内核，其他地方初始化了，旧的页面就销毁了

**Comment by ZJLeBron** [comment]
> 用问题集锦种的 seek-at-start 试试
> 
> 问题2 默认情况下只有一个内核，其他地方初始化了，旧的页面就销毁了

明白了，请问问题一如何在seekOnStart耗时过程中不让黑屏然显示封面呢~

**Comment by CarGuo** [comment]
问题集锦中的 seek-at-start 是配置ffmpeg的启动播放偏移，是通过 option 配置的，不过每次用完记得清空。

而 java 接口的 seekOnStart 是播放成功之后再触发seek，所以黑屏无法避免

**Comment by ZJLeBron** [comment]
是的我开启了精准seek，因为有些视频不开启精准seek，onResume会从头播放，那这个黑屏是无法避免了啊大佬。。不开启精准seek就不会黑屏~两者不能兼得现在~

**Comment by CarGuo** [comment]
不是精准 seek ，是  seek-at-start   https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md#20精准的某个时间开始播放      问题集锦第20，精准是第六条

**Comment by ZJLeBron** [comment]
哦我原来开的是精准定位，会耗时短暂黑屏，现在用seek-at-start 不会出现黑屏了，谢谢
