### ISSUE TITLE
Display Loading ProgressBar When EmptyControlVideo Loading URL

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2061]
Hi. I can not seem to figure out how do I display a loading progressbar when EmptyControlVideo is loading a URL. Wanna show message if stream is broken or hide the progressBar when stream loads successfully. How do I achieve that? Thanks :)

**Comment by CarGuo** [comment]
onInfo funciton 
onPrepared function

**Comment by muzeasd** [comment]
Do I override it in super classes or do I add some kind of listener on EmptyControlVideo? Is there any example?

**Comment by CarGuo** [comment]
you can override these funciton , most funciton and params is protect

**Comment by muzeasd** [comment]
Yes. I overridden both of them. OnPrepared() is called immediately I play file. But onInfo() is called a lot of times and I can not figure out against which number should I display the loadingLayout and against which number should I hide it. 

Also, above scenario is for when I load the video for the first time. How do I detect the video is in buffering mode so that I display the loadingLayout again - that is when video is playing and suddenly internet goes away?

Thanks for your time and patience with me.

**Comment by muzeasd** [comment]
Ok. You can close it. I solved it.
