### ISSUE TITLE
为什么没有截取视频首帧的方法

### ISSUE THREAD

**Issue by adminqqz** [CarGuo/GSYVideoPlayer#2063]
没有截取视频首帧的方法。
没有对视频控件，圆角的方法。（尝试过了issues里面的 没效果）

**Comment by CarGuo** [comment]
截取视频首帧是 glide 实现的。
视频控件圆角并不属于该库问题

**Comment by adminqqz** [comment]
可以提供一下，实现圆角的思路吗？尝试无果

**Comment by CarGuo** [comment]
https://blog.csdn.net/eoeandroida/article/details/76117898
https://blog.haloxin.me/post/91.html

**Comment by adminqqz** [comment]
![QQ截图20190614163154](https://user-images.githubusercontent.com/12959954/59495506-fc0c2f00-8ec1-11e9-8e8b-d894a2be2fad.png)
嗯，尝试了下，没有效果。
![QQ截图20190614163233](https://user-images.githubusercontent.com/12959954/59495531-09291e00-8ec2-11e9-9e0d-3cb6b697ede6.png)

还有封面的首帧 SampleCoverVideo Activity  加载图片的 startWindowFullscreen 都不会执行。是不是需要 提前播放一次，然后在暂停，以这种思路来获取首帧

**Comment by adminqqz** [comment]
![QQ图片20190613151200](https://user-images.githubusercontent.com/12959954/59496130-607bbe00-8ec3-11e9-9a45-5e53d0dae58e.png)
初始化封面，这个方法也不会执行。正确的操作方式是怎么样的呢，demo里面全部是设置的默认图，看不出加载首帧的效果。555.

**Comment by adminqqz** [comment]
首帧，处理好了。
 final SampleCoverVideo videoContainer = helper.getView(R.id.video_item_player);
需要在使用的地方调用（如adapter）
 videoContainer.loadCoverImage(url,R.drawable.icon_share_sms);。


现在就差圆角啦

**Comment by adminqqz** [comment]
已经处理完毕。
