### ISSUE TITLE
部分手机缓存报错

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#2065]
com.danikula.videocache.ProxyCacheException: Error opening connection for https://vod.100rd.com/customerTrans/7cc7dd8d134103a7724724809f86616c/3e2d7ac0-16b5061ae52-0004-4e6b-0d3-ee642.mp4 with offset 2722033. Version: 2.7.1

 Caused by: java.io.FileNotFoundException: https://vod.100rd.com/customerTrans/7cc7dd8d134103a7724724809f86616c/3e2d7ac0-16b5061ae52-0004-4e6b-0d3-ee642.mp4
请问如何解决

**Comment by CarGuo** [comment]
com.danikula.videocache.ProxyCacheException: Error opening connection for

Caused by: java.io.FileNotFoundException:

从log上看链接不上这个地址

**Comment by ZJLeBron** [comment]
但是卸载重新安装就没这个问题了，所以判断可能是缓存库danikula的问题~

**Comment by CarGuo** [comment]
不好说，如果是问题的话，需要看复现问题步骤

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2079
