### ISSUE TITLE
请问如何实现fragment的recycleview列表的视频全屏重力旋转

### ISSUE THREAD

**Issue by kozhnpc** [CarGuo/GSYVideoPlayer#2066]
已经看过了所有的issue下关于这类旋转问题的解答，之前作者也说可以参考listvideoactivity和listnormaladapter紧张修改，但是我在这个demo中紧进行修改后，并没有产生效果，想请问大家，这种在fragment中列表的全屏旋转是怎么实现的，稍微给个思路，谢谢

**Comment by CarGuo** [comment]
em ···· demo 中我记得是可以的，问题在于你手机的旋转开关有没有打开？没打开的话demo中要设置强制旋转api
