### ISSUE TITLE
是否支持RTSP呢

### ISSUE THREAD

**Issue by FSY-Specter** [CarGuo/GSYVideoPlayer#207]
是否支持RTSP呢

**Comment by CarGuo** [comment]
支持，目前用的是ijkplayer的module-lite-hevc.sh编译出来的

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/232#issuecomment-305063592

**Comment by CarGuo** [comment]
https://github.com/Bilibili/ijkplayer/issues/2259

**Comment by CarGuo** [comment]
https://github.com/Bilibili/ijkplayer/issues/2741

**Comment by CarGuo** [comment]
http://www.ffmpeg.org/ffmpeg-protocols.html   ffmpeg protocols

**Comment by CarGuo** [comment]
https://github.com/Bilibili/ijkplayer/issues/1346  tcp

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/232 link to

**Comment by zxrmmxt** [comment]
> 支持，目前用的是ijkplayer的module-lite-hevc.sh编译出来的

大佬，对rtsp播放的延迟有做优化吗，我现在公司的项目，播放rtsp时间越长，延迟越大
