### ISSUE TITLE
无法访问IMediaPlayer

### ISSUE THREAD

**Issue by hu374307261** [CarGuo/GSYVideoPlayer#2070]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
错误: 无法访问IMediaPlayer
找不到tv.danmaku.ijk.media.player.IMediaPlayer的类文件
错误: 无法访问OnBufferingUpdateListener
找不到tv.danmaku.ijk.media.player.IMediaPlayer$OnBufferingUpdateListener的类文件
XXXX发生了这样的问题！

## 问题机型/系统：小米note Android 7.0

例如 真机 小米note2 Android7.0 

## GSY依赖版本 
导入model java 
例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤
无
Demo中的detailPlayer页面打开后XXXX会出现这个问题。
无
问题代码：(如果有)
```无
xxxxxxx
```无

## 问题log（如果有）

```无

xxxxxxx

```无

**Comment by CarGuo** [comment]
不是很理解

**Comment by hu374307261** [comment]
自己把代码复制进来，修改，无法运行，提示没有访问资源

**Comment by CarGuo** [comment]
你没依赖吧

**Comment by hu374307261** [comment]
请问如何开始静音，隐藏全部视频上的UI？
