### ISSUE TITLE
有时播放mp4类型的文件时，当播放器所在Activity退出后，播放器依然会占用网速，貌似没有停止加载视频

### ISSUE THREAD

**Issue by ns-jin** [CarGuo/GSYVideoPlayer#2072]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

有时播放mp4类型的文件时，当播放器所在Activity退出后，播放器依然会占用网速，貌似没有停止加载视频

## 问题机型/系统：

例如 真机 小米红米5 plus Android8.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

播放mp4视频流

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
看你有没有释放了
