### ISSUE TITLE
如何实现列表跳转详情无缝切换清晰度

### ISSUE THREAD

**Issue by hu374307261** [CarGuo/GSYVideoPlayer#2074]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
如何实现列表无缝播放详情后可以切换清晰度，如单独播放的那个一样的方式
XXXX发生了这样的问题！
需求实现
## 问题机型/系统：
小米note
例如 真机 小米note2 Android7.0

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`
例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```无
xxxxxxx
```无

## 问题log（如果有）
无
```

xxxxxxx

```

**Comment by CarGuo** [comment]
自己参考demo
