### ISSUE TITLE
详情返回列表，列表不会播放，卡住了

### ISSUE THREAD

**Issue by hu374307261** [CarGuo/GSYVideoPlayer#2076]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
详情返回列表，列表不会播放，卡住了，时间会走？
XXXX发生了这样的问题！
小米 8
## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本
'com.shuyu:gsyVideoPlayer-java:7.0.1'`
例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤
无
Demo中的detailPlayer页面打开后XXXX会出现这个问题。
无
问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
无法复现  I have no idea

**Comment by hu374307261** [comment]
在fragment页面里，详情回退，页面卡住，时间在走？

**Comment by CarGuo** [comment]
Demo复现步骤
