### ISSUE TITLE
横竖屏切换UI问题

### ISSUE THREAD

**Issue by jasonwang1991** [CarGuo/GSYVideoPlayer#2077]
## 问题描述：

现在我要修改在横屏和竖屏下返回键和横竖屏切换键 怎么设置
 mFullscreenButton.setImageResource(R.mipmap.chatroom_live_btn_full);
        setShrinkImageRes(R.mipmap.chatroom_live_btn_reduce);
        setEnlargeImageRes(R.mipmap.chatroom_live_btn_full); 设置横竖屏切换键无效

![image](https://user-images.githubusercontent.com/23151366/59756239-eaf56080-92bb-11e9-99e8-d948b635856a.png)

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/LandLayoutVideo.java

参考这个吧

**Comment by jasonwang1991** [comment]
横竖屏控件没有问题  返回按键怎么处理

**Comment by CarGuo** [comment]
不是很理解

**Comment by jasonwang1991** [comment]
怎么设置横竖屏情况下返回键mBackButton的UI修改         Configuration mConfiguration = this.getResources().getConfiguration(); //获取设置的配置信息
        int ori = mConfiguration.orientation; //获取屏幕方向
        if (ori == Configuration.ORIENTATION_LANDSCAPE) {
            mBackButton.setImageResource(R.mipmap.chatroom_live_btn_back);
        } else if (ori == Configuration.ORIENTATION_PORTRAIT) {
            mBackButton.setImageResource(R.mipmap.chatroom_live_btn_close);
        }

我设置了没有效果，

**Comment by jasonwang1991** [comment]
找到了 重写了setUp方法  在其中设置了横竖屏下左上角返回按钮图片的修改
