### ISSUE TITLE
setOnDoubleClick设置监听无效，请问什么原因，demo中好像没用这方法

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#2078]

**Comment by ZJLeBron** [comment]
另外，可以在全屏动画的时候背景设置成透明吗（动画过程周边是黑色的），并缩短动画时长吗

**Comment by CarGuo** [comment]
因为内部有 touchDoubleUp ，你可以重载下。

动画是共享元素过场

**Comment by ZJLeBron** [comment]
退出全屏动画完毕后闪烁一下才开始列表播放，demo中ListVideoActivity也有这个想象，请问有优化方案吗？

**Comment by ZJLeBron** [comment]
另外请问这个共享元素动画的android:duration在哪里设置

**Comment by CarGuo** [comment]
直接用的 TransitionManager.beginDelayedTransition

至于闪的问题我在demo中没复现

**Comment by ZJLeBron** [comment]
是版本问题吗？我下载的7.0.0版本的demo，ListVideoActivity列表播放全屏退出后是会有一下闪烁的

**Comment by ZJLeBron** [comment]
ListVideoActivity中暂停状态进入全屏后，不显示视频画面也不显示封面，请问有优化方案吗

**Comment by CarGuo** [comment]
没有，这个问题貌似很老了，我这边没再出现过呢。
不显示视频画面也不显示封面，这个又个设置截图显示的，但是会有可能引发 oom 的风险，如果是想显示封面的话，自己继承后显示就好了

**Comment by ZJLeBron** [comment]
请问demo中有设置截图显示的例子吗

**Comment by ZJLeBron** [comment]
还有如何设置ijk的打印日志级别，禁止打印这些正常日志，多谢哈哈

**Comment by CarGuo** [comment]
setShowPauseCover

**Comment by ZJLeBron** [comment]
已经支付宝赞赏qq没绑定卡，麻烦把我加进qq群，多谢 735241435
