### ISSUE TITLE
代理缓存错误

### ISSUE THREAD

**Issue by nihaohebin** [CarGuo/GSYVideoPlayer#2079]
## 问题描述：

在播放过程中，很卡顿，最终发生错误：代理缓存错误，导致播放错误

## 问题机型/系统：

 真机 荣耀10 android版本9

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

播放这个视频就会http://v1.mycs.cn/85/6970/35897/Oj8zNTpyOyM.mp4

问题代码：(如果有)
无

## 问题log（如果有）错误日志

 E/ProxyCache error: Error reading data from 
 http://v1.mycs.cn/85/6970/35897/Oj8zNTpyOyM.mp4. Version: 7.0.1
 E/HttpProxyCacheServer error: Error processing request. Version: 7.0.1
 E/IJKMEDIA: Stream ends prematurely at 712704, should be 121590156
 E/IJKMEDIA: stream 0, offset 0xae003: partial file
 E/IJKMEDIA: av_read_frame error: unknown
 D/IJKMEDIA: ffp_toggle_buffering_l: end
 E/IJKMEDIA: TYPE_FIL: Input buffer exhausted before END element found

```

**Comment by CarGuo** [comment]
切换到exoplayer 和exo的cache 试试

**Comment by nihaohebin** [comment]
> 切换到exoplayer 和exo的cache 试试

我卸载重装之后又可以，部分机子会这样，好像9.0系统概率会大一些

**Comment by CarGuo** [comment]
因为本地 server 127 和文件貌似在9.0会引起一些问题，具体我这边没复现

**Comment by nihaohebin** [comment]
> 因为本地 server 127 和文件貌似在9.0会引起一些问题，具体我这边没复现

好的，大佬。谢谢指导，还有，我想问一下，我播放视频，都是播放一个URL对吧。这个视频服务器有没有好的建议。这样我播放视频就会流畅稳定。因为有时候，我发现播放这个视频，有时候就用google浏览器去打开这个视频也会很卡，或者播放不了，除了播放器这个问题外，还有可能就是视频服务不稳定也应该有很大影响。所以请教一下有没有什么好的建议，包括什么cdn？？

**Comment by CarGuo** [comment]
一般和视频格式还有视频协议有关系，比如你一个视频的GOP帧，码率等也会影响视频打开。秒开这东西是个比较细的概念，很多地方可以优化，比如视频帧率，码率，格式，协议，首帧设置。当然网络和cdn肯定也有关系

**Comment by nihaohebin** [comment]
> 一般和视频格式还有视频协议有关系，比如你一个视频的GOP帧，码率等也会影响视频打开。秒开这东西是个比较细的概念，很多地方可以优化，比如视频帧率，码率，格式，协议，首帧设置。当然网络和cdn肯定也有关系

大佬，我总结出原因了，好像是在切换wifi和4G过程中就会走onPlayError，然后出现缓存错误，然后就是一直卡在那个缓冲节点上。

**Comment by nihaohebin** [comment]
> 一般和视频格式还有视频协议有关系，比如你一个视频的GOP帧，码率等也会影响视频打开。秒开这东西是个比较细的概念，很多地方可以优化，比如视频帧率，码率，格式，协议，首帧设置。当然网络和cdn肯定也有关系

然后还有就是网络差的情况下。出现概率很大很大。应该可以复现的

**Comment by CarGuo** [comment]
明白，切换网络错误的话  onPlayError 应该会清楚缓存
