### ISSUE TITLE
华为p30系统播放器报错MediaPlayerNative: error (1, -2147483648)

### ISSUE THREAD

**Issue by pyp163** [CarGuo/GSYVideoPlayer#2080]
## 问题描述：
华为p30系统播放器报错MediaPlayerNative: error (1, -2147483648)

## 问题机型/系统：

华为p30 android9

## GSY依赖版本

    api 'com.shuyu:gsyVideoPlayer-java:6.0.1'
    api 'com.shuyu:gsyVideoPlayer-armv7a:6.0.1'
    api 'com.shuyu:gsyVideoPlayer-arm64:6.0.1'

**Comment by CarGuo** [comment]
没明白

**Comment by pyp163** [comment]
华为p30 用SystemPlayerManager.class模式 播放器报错MediaPlayerNative: error (1, -2147483648)
IjkPlayerManager.class模式下正常

**Comment by CarGuo** [comment]
说明很大可能视频的编码协议或者音频编码协议不支持咯，比如网络协议，容器协议、视频编码、音频编码等都可以影响

**Comment by pyp163** [comment]
其它手机平板都没问题，就华为的不行，这个有点懵

**Comment by CarGuo** [comment]
因为 MediaPlayer 是用的 MediaCodec ，MediaCodec 和系统版本有关
