### ISSUE TITLE
How to set Aspect Ratio

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2081]
Hi. How do I change the aspect ratio of the video? I am using EmptyControlVideo player from the sample but don't know how to change the default aspect ratio to FITXY, which means there should be no black region in the video. Thanks for any pointer in right direction :)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/GSYVideoType.java

```
    //默认显示比例
    public final static int SCREEN_TYPE_DEFAULT = 0;

    //16:9
    public final static int SCREEN_TYPE_16_9 = 1;

    //4:3
    public final static int SCREEN_TYPE_4_3 = 2;

    //全屏裁减显示，为了显示正常 CoverImageView 建议使用FrameLayout作为父布局
    public final static int SCREEN_TYPE_FULL = 4;

    //全屏拉伸显示，使用这个属性时，surface_container建议使用FrameLayout
    public final static int SCREEN_MATCH_FULL = -4;

    public static int getShowType() {
        return TYPE;
    }

    /**
     * 设置显示比例,注意，这是全局生效的
     */
    public static void setShowType(int type) {
        TYPE = type;
    }

```

**Comment by muzeasd** [comment]
I don't know how to set these values on EmptyVideoControl. Can you give an example please?

**Comment by CarGuo** [comment]
GSYVideoType. setShowType()

  //default
    public final static int SCREEN_TYPE_DEFAULT = 0;

    //16:9
    public final static int SCREEN_TYPE_16_9 = 1;

    //4:3
    public final static int SCREEN_TYPE_4_3 = 2;

    //crop full
    public final static int SCREEN_TYPE_FULL = 4;

    // fix xy
    public final static int SCREEN_MATCH_FULL = -4;
