### ISSUE TITLE
大佬，请教一个切换视频的问题

### ISSUE THREAD

**Issue by wangyikai1234567** [CarGuo/GSYVideoPlayer#2085]
## 问题描述：
我在做视频处理相关的项目，当我视频裁处理毕之后，不退出当前播放页，但是要把视频切换成处理之后的。我看了相关的 issues 差不多都是按播放下一集的逻辑。
请问大佬，有其他的办法可以操作么
 
## 问题机型/系统：

与机型无关

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'`

**Comment by CarGuo** [comment]
不是很理解什么意思

**Comment by wangyikai1234567** [comment]
是这样我再做 视频裁剪，当我裁剪完后，要切换视频，但是不刷新当前页面。而我目前做出的效果是，当裁剪完后，从30s开始往后播放，只有退出当前页面再进入的时候才会正常显示；

**Comment by CarGuo** [comment]
参考demo 中的 SampleVideo 切换清晰度 或者 SmartPickVideo
