### ISSUE TITLE
小米8设置播放速度无效，有调用setSpeedPlaying

### ISSUE THREAD

**Issue by yangyeefeng** [CarGuo/GSYVideoPlayer#2088]
## 问题描述：

小米8手机，设置播放速度无效

## 问题机型/系统：

真机 小米8，MIUI版本 10.3.3.0，Android版本 9

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:6.0.3'

## Demo中的复现步骤

Demo中点击“带控制的DEMO”，点击“播放速度“即可复现问题。点击后显示的播放速度有变化，但是视频真正的播放速度没变。0.25和0.5时有效，1.5和2时无效，大于1时则无效

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1864

https://github.com/CarGuo/GSYVideoPlayer/issues/1831


IJK模式内核 souchtouch 需要设置为 1， 然后同步时钟以为是音频流。

如果不支持请切换到 exo 内核测试

**Comment by yangyeefeng** [comment]
非常感谢~
