### ISSUE TITLE
全屏和横屏使用两套布局，全屏返回的时候报错。

### ISSUE THREAD

**Issue by LsFern** [CarGuo/GSYVideoPlayer#2089]
## 问题描述：
全屏和横屏使用两套布局，横屏不显示返回按钮和点击全屏按钮。然后自定义样式点击全屏后，全屏点击返回或者退出全屏按钮报错

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

   implementation ('com.shuyu:gsyVideoPlayer-java:6.0.1'){
        exclude module: 'support-v4'
    }
    implementation ('com.shuyu:GSYVideoPlayer-exo2:6.0.1'){
        exclude module: 'support-v4'
    }
    implementation ('com.shuyu:gsyVideoPlayer-ex_so:6.0.1'){
        exclude module: 'support-v4'
    }

问题代码：(如果有)
```
全屏布局：
<ImageView
            android:id="@+id/fullscreen"
            android:layout_width="wrap_content"
            android:layout_height="fill_parent"
            android:paddingRight="16dp"
            android:scaleType="center"
            android:src="@drawable/video_enlarge" />

横屏布局：
<!--<ImageView-->
            <!--android:id="@+id/fullscreen"-->
            <!--android:layout_width="wrap_content"-->
            <!--android:layout_height="fill_parent"-->
            <!--android:paddingRight="16dp"-->
            <!--android:scaleType="center"-->
            <!--android:src="@drawable/video_enlarge" />-->

可以看出横屏注释了这个id为fullScreen的控件

源码报错：
![image](https://user-images.githubusercontent.com/32630118/59973442-95c69100-95d2-11e9-82de-9d7878ce5abe.png)

![image](https://user-images.githubusercontent.com/32630118/59973444-9c550880-95d2-11e9-92f2-9a54c17016c5.png)

![image](https://user-images.githubusercontent.com/32630118/59973446-a414ad00-95d2-11e9-8ff9-ad9c3f635f49.png)

```

## 问题log（如果有）

```

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageResource(int)' on a null object reference
        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.resolveNormalVideoShow(GSYBaseVideoPlayer.java:365)
        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.backToNormal(GSYBaseVideoPlayer.java:438)
        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer$3.run(GSYBaseVideoPlayer.java:400)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)


```
解决办法：打开横屏的那个注释，才可以正常切换。
期望：横竖屏相互之间不影响

**Comment by LsFern** [comment]
源码报错截图：
![image](https://user-images.githubusercontent.com/32630118/59973469-e9d17580-95d2-11e9-94b7-bc359b3fc4bf.png)

![image](https://user-images.githubusercontent.com/32630118/59973470-edfd9300-95d2-11e9-8025-1e15cef5e865.png)

![image](https://user-images.githubusercontent.com/32630118/59973472-f524a100-95d2-11e9-8c21-05d66f035452.png)

**Comment by CarGuo** [comment]
demo怎么复现？

**Comment by LsFern** [comment]
> demo怎么复现？



> demo怎么复现？

重写getLayoutId发方法

@Override
public int getLayoutId() {
    if (mIfCurrentIsFullscreen) {
        return R.layout.sample_video_land;
    }
    return R.layout.sample_video_normal;
}
横竖屏布局保持一致， 使用video_layout_normal布局代码
注释横屏的id为fullscreen控件，然后退出全屏就会报错。

解决办法：
取消注释，重写getEnlargeImageRes方法即可
@override
public int getEnlargeImageRes() {
return 0;
}

**Comment by CarGuo** [comment]
哦，明白了 因为是 **注释横屏的id为fullscreen控件**
