### ISSUE TITLE
手机锁屏后解锁的视频全屏

### ISSUE THREAD

**Issue by Achenglove** [CarGuo/GSYVideoPlayer#209]
GSYVideoPlayer在全屏播放的情况下，按下手机锁屏按钮将手机锁屏，然后再把手机解锁，此时视频由原来的横屏全屏变成竖屏全屏了，这个需要怎样处理才能在解锁后直接处于横屏全屏状态呢？

**Comment by CarGuo** [comment]
demo中那个会这样？？

**Comment by Achenglove** [comment]
会，全部都会，这个需要怎么配置才能解决呢？请指教一下

**Comment by CarGuo** [comment]
我这边demo没重现这个问题

**Comment by CarGuo** [comment]
我大概知道了，你把动画和自动旋转关闭吧

**Comment by Achenglove** [comment]
好的，问题已经解决，谢谢，必须给颗星

**Comment by CarGuo** [comment]
1.6.5已发布

**Comment by Achenglove** [comment]
好的，已经更新，谢谢
