### ISSUE TITLE
循环播放，就是播放完成以后继续重头播放，setLooping(true) 不起作用。

### ISSUE THREAD

**Issue by smilexuetao** [CarGuo/GSYVideoPlayer#2091]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请修改模版，并标出 Demo 哪个页面复现

**Comment by smilexuetao** [comment]
> 
> 
> 请修改模版，并标出 Demo 哪个页面复现，提供复现流数据

是重新播放，就是一个视频播放完成了。我想重新播放，是设置setLooping吗？

**Comment by smilexuetao** [comment]
不是你理解的列表循环，是一个单个视频重新播放。
