### ISSUE TITLE
Show Error Message Against "404 Not Found" Response

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2097]
Hello there. I use EmptyControlVideo. I want to be able to know when there is "404 Not Found" response against an URL so that I may be able to show appropriate message accordingly. Example log

`com.v3s.solutions.livewebcams V/IJKMEDIA: header='HTTP/1.1 404 Not Found'
com.v3s.solutions.livewebcams V/IJKMEDIA: http_code=404
com.v3s.solutions.livewebcams W/IJKMEDIA: HTTP error 404 Not Found
com.v3s.solutions.livewebcams I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke
com.v3s.solutions.livewebcams E/IJKMEDIA: URL_GOES_HERE: Server returned 404 Not Found`

How do I achieve that? Thanks :)

**Comment by CarGuo** [comment]
Sorry,  default IjkPlayerManager can only be received in onError function when `what -10000,  extra 0` , but it's not just callback  by 404 
```
@Override
public void onError(int what, int extra) {
 
}

```

you can do what you what like 

https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exo  

custom IjkExo2MediaPlayer

**Comment by muzeasd** [comment]
How would I trace what player is being used by EmptyControlVideo, under the hood?

**Comment by CarGuo** [comment]
if you try custom IjkExo2MediaPlayer ，you need to  `implements IPlayerManager`  like 

https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/exo/GSYExoPlayerManager.java

and then `PlayerFactory.setPlayManager(YourManager.class);`

or

default class you need Override onError and get when ` what -10000, extra 0 `, 

@Override
public void onError(int what, int extra) {
 
}

**Comment by muzeasd** [comment]
Thanks. You can close it :)
