### ISSUE TITLE
.m3u8直播流播放的时候滑动进度条或者快进后退都会卡主并一直处于加载状态

### ISSUE THREAD

**Issue by XINDZ** [CarGuo/GSYVideoPlayer#210]
直播流地址http://l2.stream.nxtv.com.cn/hls-live/live/_definst_/liveevent/gg.m3u8

**Comment by CarGuo** [comment]
直播可以快进？

**Comment by XINDZ** [comment]
后台返回的地址既有这种直播流也有点播的 所以我就用StandardGSYVideoPlayer来播放

**Comment by anpoz** [comment]
可以判断是否为直播流，然后将进度条setVisibility(View.VISIBLE)

**Comment by XINDZ** [comment]
进度条是私有的获取不到 而且还有滑动快进后退都会造成卡顿

**Comment by anpoz** [comment]
StandardGSYVideoPlayer是继承FrameLayout的，layout获取子view直接用findViewById就行了
StandardGSYVideoPlayer.findViewById(R.id.progress).setVisibility(View.INVISIBLE);

**Comment by XINDZ** [comment]
谢谢 这样是可以隐藏掉progressbar 但是左右滑动进度还是卡 您知道该怎么禁止快进后退吗

**Comment by CarGuo** [comment]
@XINDZ 有lock参数获知touch参数，touch参数又分全屏和非全屏，可以看看首页的版本更新说明，或者看源码

**Comment by XINDZ** [comment]
我在StandardGSYVideoPlayer和GSYVideoPlayer的onTouch 方法里通过getDuration 方法判断总长度是否大于0 ,因为直播流的时长都是0 这样是直播流的话 progressbar 和快进后退都能被禁止掉了

**Comment by CarGuo** [comment]
@XINDZ 👍
