### ISSUE TITLE
退出到后台不播放

### ISSUE THREAD

**Issue by dary123** [CarGuo/GSYVideoPlayer#2100]
已经去掉了以下代码

@Override
    public void onPause() {
        mPlayerView.getCurrentPlayer().onVideoPause();
        super.onPause();
        isPause = true;
    }

    @Override
    protected void onResume() {
        mPlayerView.getCurrentPlayer().onVideoResume(false);
        super.onResume();
        isPause = false;
    }

但是还是一退出到后台视频就暂停，重新回到前台又开始播放

**Comment by CarGuo** [comment]
没发现这个问题····

**Comment by dary123** [comment]
你的demo也是这样的呀，虽然你demo按回到桌面的按键，重新进入就退到刚开始的界面了，但是我通过按安卓底部左侧第一个按钮(管理操作键)查看进程，然后回到播放页面，播放按钮明显删了一下从暂停变成播放，也就是说退到后台桌面会暂停，再回到前台开始继续播放，我想要的是退到桌面继续播放不暂停

**Comment by CarGuo** [comment]
[1561696117608121.mp4.zip](https://github.com/CarGuo/GSYVideoPlayer/files/3337556/1561696117608121.mp4.zip)

如上水平，测试正常

**Comment by dary123** [comment]
解决了，是我的问题，但是还有个问题，我使用了[https://github.com/yhaolpz/FloatWindow](url)这个悬浮框库，因为你这个库虽然支持小窗，但是不支持后台桌面悬浮框显示，我就使用了这个库，使用之后，将播放控件addView到悬浮框中后不播放，但是还是显示的播放按钮，不是暂停按钮，但是实际上画面是暂停的

**Comment by CarGuo** [comment]
支持桌面悬浮显示的，但是我那时候是支持改过来的，demo里我是写死不在桌面的，你可以看看，前提是你开启了悬浮窗权限

**Comment by dary123** [comment]
demo也是用的这个库吗，我没有找到相关代码额，我已经开启了悬浮窗权限，可以悬浮在桌面上，就是画面禁止不动，悬浮前还是会动的

**Comment by dary123** [comment]
其他控件都可以操作，比如暂停恢复，拖动进度条，这些控件都没受到影响，就是画面不动了

**Comment by dary123** [comment]
demo确实可以，估计是我的问题，我再看看
