### ISSUE TITLE
播放过程中卡死问题，缓冲条不继续缓冲了

### ISSUE THREAD

**Issue by nihaohebin** [CarGuo/GSYVideoPlayer#2105]
## 问题描述：
都是出现在网络不稳定，网络较差的情况下。
- 1、设置缓存true，播放一个mp4视频，中途缓冲停止。播放卡死（网络较差时出现概率大，偶发）
- 2、设置缓存false,  播放一个m3u8视频，中途缓冲停止，切换4G，自动seekstart很远一段播放。（稳定重现）
- 3、设置缓冲false,  播放一个m3u8视频，缓冲到某个位置后就停止缓冲了,卡死现象，一直在等待缓冲。（偶发）
## 问题机型/系统：

 任何机型

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'

## Demo中的复现步骤

- 1、播放视频链接：http://v1.mycs.cn/146/50891/37849/Oj0zODRyOSU.mp4 ，播放视频由于弱网或网络较差的环境下。播放到中途缓冲停止。重新进入播放，还是播放到缓冲位置后卡死。清除缓存后重新进入播放正常
- 2、播放视频，http://alisrc.mycs.cn/0/Oj4zODxyOiE/Oj4zODxyOiE.m3u8 ，1、在播放到中途网络不稳定导致停止缓冲，在他播放到缓冲节点后就会转圈等待，2、然后切换这个不稳定的wifi网络，到4G网络后，他会直接缓存并直接跳到最后播放结束，正常应该切换网络后，直接在停止缓冲的那个节点继续缓冲播放的

问题代码：(如果有)
```
无
```

## 问题log（如果有）

```
D/IJKMEDIA: ffp_toggle_buffering_l: start
D/IJKMEDIA: FFP_MSG_BUFFERING_START:
I/GSYVideoPlayer: changeUiToPlayingBufferingShow
D/JIGUANG-JCore-IMPL: [JCommonInterface] onEvent action:waked
I/GSYVideoPlayer: 417648617------------------------------ surface_container ACTION_UP
I/GSYVideoPlayer: onClickBlank

这是播放到中间卡死不动了。一直在转圈等待缓冲

退出后，再次播放还是卡死在缓冲条的末端，最后日志如下：

D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ffp_toggle_buffering_l: start
D/IJKMEDIA: FFP_MSG_BUFFERING_START:
I/GSYVideoPlayer: changeUiToPlayingBufferingShow
D/IJKMEDIA: IjkMediaPlayer_native_finalize
D/IJKMEDIA: IjkMediaPlayer_release
D/EGL_adreno: eglMakeCurrent: 0xaed6f3a0: ver 3 1 (tinfo 0xaec398d0)
D/IJKMEDIA: IjkMediaPlayer_native_finalize
D/IJKMEDIA: IjkMediaPlayer_release
D/EGL_adreno: eglMakeCurrent: 0xaed6f3a0: ver 3 1 (tinfo 0xaec398d0)


```

**Comment by nihaohebin** [comment]
应该跟机型无关，其他手机和模拟器都出现过。而且，我设置了缓冲setCacheWithPlay false还是会有缓冲。不知道为啥

**Comment by nihaohebin** [comment]
关闭缓存配置下，播放视频，http:\/\/alisrc.mycs.cn\/0\/Oj4zODxyOiE\/Oj4zODxyOiE.m3u8  ，1、在播放到中途网络不稳定导致停止缓冲，在他播放到缓冲节点后就会转圈等待，2、然后切换这个不稳定的wifi网络，到4G网络后，他会直接缓存并直接跳到最后播放结束。这个稳定重现。（应该切换网络后，直接在停止缓冲的那个节点继续缓冲播放的。大佬，这算不算bug呢。）

**Comment by nihaohebin** [comment]
大佬，影响好大呀。第二种情况。在缓冲过程中，关闭一下网络，然后再开启，当他播放到缓冲节点之后，直接自动跳到最后了。

**Comment by nihaohebin** [comment]
E/IJKMEDIA: stream 1, offset 0x3459c2e: partial file
 E/IJKMEDIA: av_read_frame error: unknown
 E/IJKMEDIA: stream 1, offset 0x3459d4f: partial file
 E/IJKMEDIA: av_read_frame error: unknown
 I/IJKMEDIA: ffp_toggle_buffering: error: -5
 D/IJKMEDIA: FFP_MSG_ERROR: 0
 E/IJKMEDIA: stream 0, offset 0x3459e5f: partial file
 E/IJKMEDIA: av_read_frame error: unknown
 E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
 E/GSYVideoPlayer: cancelTimeOutBuffer
 I/GSYVideoPlayer: changeUiToError
 E/GSYVideoPlayer: Link Or mCache Error, Please Try Again http://v1.mycs.cn/71/4661/36685/
 E/TAG: ┌─────────────────────────────────────────────────────────────────────────────────
 E/TAG: │ BaseVideoFragment.onPlayError  (BaseVideoFragment.java:157)
 E/TAG: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
 E/TAG: │ onPlayError url = http://v1.mycs.cn/71/4661/36685/Ojw9NDhyPik.mp4
 E/TAG: └─────────────────────────────────────────────────────────────────────────────────
 I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
 D/IJKMEDIA: IjkMediaPlayer_release
 D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
 D/IJKMEDIA: ffpipeline_set_surface()
 D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
 D/IJKMEDIA: ijkmp_shutdown_l()
 D/IJKMEDIA: message_loop exit
 D/IJKMEDIA: wait for read_tid
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25884]
 I/IJKMEDIA: convert image convert_frame_count = 0
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25900]
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25890]
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25885]
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25886]
 D/AudioTrack: stop() called with 29681600 frames delivered
 D/android.media.AudioTrack: [HSM] AudioTrace stop() uid: 10152, pid: 25331
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25889]
 D/IJKMEDIA: Statistics: 52669209 bytes read, 0 seeks
 D/IJKMEDIA: wait for video_refresh_tid
 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd03f9e40)
 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd03f9e80)
 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd03f9ec0)
 D/IJKMEDIA: ijkmp_shutdown_l()=void
 D/IJKMEDIA: ijkmp_dec_ref(): ref=0
 D/IJKMEDIA: ijkmp_shutdown_l()
 D/IJKMEDIA: ijkmp_shutdown_l()=void
 D/IJKMEDIA: IjkMediaPlayer_setVolume
 E/GSYVideoPlayer: cancelTimeOutBuffer

播放视频过程中，自动暂停，然后播放失败。重新播放了

**Comment by lanmao1** [comment]
我也遇到了，有解决办法吗？影响太大了

**Comment by CarGuo** [comment]
@nihaohebin 问题1看起来像是cache的问题，可以推荐换成exoplayer + exocache模式

问题2 我测试的情况下，正常应该会走 netWorkErrorLogic ，不会有什么问题

**Comment by lanmao1** [comment]
我再研究下

**Comment by nihaohebin** [comment]
> @nihaohebin 问题1看起来像是cache的问题，可以推荐换成exoplayer + exocache模式
> 
> 问题2 我测试的情况下，正常应该会走 netWorkErrorLogic ，不会有什么问题

对，他会走，但是清楚当前播放状态了。就是我播放到88秒，然后被清除了，重新播放，但是我希望从原来节点播放。所以现在在播放错误前记录播放当前进度。然后在seek到播放错误的位置，再重新开始播放

**Comment by jarvan11** [comment]
> HelloJokerWord

遇到同样问题，有解决么？@HelloJokerWord

**Comment by jarvan11** [comment]
> E/IJKMEDIA: stream 1, offset 0x3459c2e: partial file E/IJKMEDIA: av_read_frame error: unknown E/IJKMEDIA: stream 1, offset 0x3459d4f: partial file E/IJKMEDIA: av_read_frame error: unknown I/IJKMEDIA: ffp_toggle_buffering: error: -5 D/IJKMEDIA: FFP_MSG_ERROR: 0 E/IJKMEDIA: stream 0, offset 0x3459e5f: partial file E/IJKMEDIA: av_read_frame error: unknown E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0) E/GSYVideoPlayer: cancelTimeOutBuffer I/GSYVideoPlayer: changeUiToError E/GSYVideoPlayer: Link Or mCache Error, Please Try Again http://v1.mycs.cn/71/4661/36685/ E/TAG: ┌───────────────────────────────────────────────────────────────────────────────── E/TAG: │ BaseVideoFragment.onPlayError (BaseVideoFragment.java:157) E/TAG: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄ E/TAG: │ onPlayError url = http://v1.mycs.cn/71/4661/36685/Ojw9NDhyPik.mp4 E/TAG: └───────────────────────────────────────────────────────────────────────────────── I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time D/IJKMEDIA: IjkMediaPlayer_release D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0) D/IJKMEDIA: ffpipeline_set_surface() D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void D/IJKMEDIA: ijkmp_shutdown_l() D/IJKMEDIA: message_loop exit D/IJKMEDIA: wait for read_tid I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25884] I/IJKMEDIA: convert image convert_frame_count = 0 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25900] I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25890] I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25885] I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25886] D/AudioTrack: stop() called with 29681600 frames delivered D/android.media.AudioTrack: [HSM] AudioTrace stop() uid: 10152, pid: 25331 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25889] D/IJKMEDIA: Statistics: 52669209 bytes read, 0 seeks D/IJKMEDIA: wait for video_refresh_tid E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd03f9e40) E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd03f9e80) E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd03f9ec0) D/IJKMEDIA: ijkmp_shutdown_l()=void D/IJKMEDIA: ijkmp_dec_ref(): ref=0 D/IJKMEDIA: ijkmp_shutdown_l() D/IJKMEDIA: ijkmp_shutdown_l()=void D/IJKMEDIA: IjkMediaPlayer_setVolume E/GSYVideoPlayer: cancelTimeOutBuffer
> 
> 播放视频过程中，自动暂停，然后播放失败。重新播放了

遇到同样情况，有解决么？@HelloJokerWord
