### ISSUE TITLE
cancelTimeOutBuffer

### ISSUE THREAD

**Issue by CrzGitHub** [CarGuo/GSYVideoPlayer#2106]
7.0.1 版本 小米Note3 M8 跳转到手机自带浏览器 再回到播放页面 无法继续播放 报cancelTimeOutBuffer

**Comment by CrzGitHub** [comment]
暂停状态下显示暂停广告 暂停广告点击后跳转到指定手机自带浏览器的URL广告链接

**Comment by CarGuo** [comment]
不是很理解，广告链接里播放了视频或者音频了？

**Comment by CrzGitHub** [comment]
是的，我们里面有视频音频。 换成普通的文本广告 不在出现。

**Comment by CrzGitHub** [comment]
除了小米手机会出现 华为 魅族 oppo vivo 都没有问题

**Comment by CarGuo** [comment]
因为视频内部有 AudioManager 做焦点处理，你可以设置 setReleaseWhenLossAudio 或者重载 onGankAudio，onLossAudio，onLossTransientAudio方法
