### ISSUE TITLE
解决硬解码切换全屏时花屏的一个思路

### ISSUE THREAD

**Issue by zhkrb** [CarGuo/GSYVideoPlayer#2109]
## 问题描述：

开启MediaCodec后旋转花屏

## 问题机型/系统：

Google Pixel XL

## GSY依赖版本
api 'com.shuyu:gsyVideoPlayer-java:7.0.1'
##

主要还是讨论下解决思路

目前全屏切换的逻辑是在`startWindowFullscreen`中新实例化一个Player，再把参数全部设置过去。但使用ijkplayer硬解码的话没有办法保证新的Player播放时MediaCodec解码首帧一定是IDR帧，只有B帧的话没有办法重建完整图像，才导致的花屏。

参考bbc在ijkplayer中的[回复](https://github.com/bilibili/ijkplayer/issues/1324#issuecomment-220245297)，以及提到的[项目](https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/DoubleDecodeActivity.java)，可以通过保存SurfaceTexture,然后在`onSurfaceTextureDestroyed`中阻止SurfaceTexture销毁，然后重新给TextureView设置SurfaceTexture，这样不会让MediaCodec重建,保证切换后不会花屏。

但这个可行的前提是单播放器，我重写了`startWindowFullscreen`逻辑，以及`IGSYSurfaceListener.onSurfaceDestroyed()`，让它不要再次创建一个Player和`setDisplay(null)`。目前解决了我的花屏问题。

还有一个思路是关闭精准Seek，在旋转后seek到当前位置，这样会跳动到之前的I帧播放，不过这个我测试了几次都没有成功。

大概就是这样，有没有其他的解决方式，或者说在主分支或者新分支里修改这个问题的计划呢？

**Comment by CarGuo** [comment]
全屏的时候触发 seek 这个做过，因为可能回出现全屏之后卡断所以就去除了，至于你提到的第一种方法我还没试过，可以试试

**Comment by CarGuo** [comment]
第一种方法方便提一个demo看看吗

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/mediacodec  我大概加了个类似的 demo

**Comment by zhkrb** [comment]
邮件有延迟，抱歉回复晚了。

我是直接把`startWindowFullscreen`和`resolveNormalVideoShow`复制一份改了下，[Demo](https://github.com/zhkrb/DemoTest)
