### ISSUE TITLE
支持不支持播放音频的时候，有多首音频，自动播放下一首的的功能呢？

### ISSUE THREAD

**Issue by liguangze** [CarGuo/GSYVideoPlayer#2110]
或者有多个视频或者音频，类似分章节的，播放完了这个，自动播放下一个，支持这种吗

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailListPlayer.java
