### ISSUE TITLE
无网络进入全屏加载失败后退出全屏，activity底部tabhost被移除屏幕一半，显示不全了

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#2113]
请问从哪里入手解决问题，视频加载成功后，退出全屏是不会有这个bug的

**Comment by CarGuo** [comment]
em·····你看看 GSYBaseVideoPlayer 会不会影响到，还有 onConfigurationChanged 相关的
还有和隐藏 statusbar 、actionbar 有没有关系

**Comment by ZJLeBron** [comment]
我看了是actionBar造成，我的页面是需要显示actionBar的，但是现在我发现全屏时候视频不是在actionbar下面，而是视频的顶部被actionbar覆盖了，请问怎么解决，谢谢

**Comment by CarGuo** [comment]
调用 startWindowFullscreen 时配置的

**Comment by ZJLeBron** [comment]
statusBar设置为false会显示状态栏，但是状态栏把视频给覆盖了，请问如何让视频从状态栏下方开始显示而不被覆盖呢，player.startWindowFullscreen(getActivity(), false, false)

**Comment by CarGuo** [comment]
应该怎么在demo复现呢

**Comment by ZJLeBron** [comment]
> 应该怎么在demo复现呢

sorry忘了回，在demo中的ListNormalAdapter中把statusBar设置成false就会出现这种情况（statusBar把视频给遮盖）        standardGSYVideoPlayer.startWindowFullscreen(context, true, false);

**Comment by CarGuo** [comment]
你需要重写 startWindowFullscreen 方法，然后你看下 hideSupportActionBar 静态方法
