### ISSUE TITLE
自定义底部进度条弹出的 seekbar 的 thumb,图片该怎是什么尺寸的？

### ISSUE THREAD

**Issue by zung** [CarGuo/GSYVideoPlayer#2117]
## 问题描述：

我设置底部弹出进度条的thumb，无论用什么尺寸的图标，都显示不正确，会在进度条下方，而且拖动进度 ，thumb 要比实际进度快，拖到最后正好是快一倍。

## 问题机型/系统：

任何机型

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:4.1.2'

**Comment by CarGuo** [comment]
正常自定义就可以啦
