### ISSUE TITLE
ListGSYVideoPlayer内存泄露

### ISSUE THREAD

**Issue by yangsk94** [CarGuo/GSYVideoPlayer#2118]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

资源都已经释放，但是播放视频退出就会导致内存泄漏

## 问题机型/系统：

 真机 国美

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

## Demo中的复现步骤

Demo中的DetailListPlayer页面打开后也会出现这个问题。

**Comment by yangsk94** [comment]
内存泄漏

**Comment by yangsk94** [comment]
![Image text]https://github.com/yangsk94/img-folder/blob/master/xielou1.jpeg
![Image text]https://github.com/yangsk94/img-folder/blob/master/xielou2.jpeg

**Comment by CarGuo** [comment]
AudioManager 的问题请忽略
