### ISSUE TITLE
关于使用GSYVideoPlayer遇到的几个问题（详情全屏后页面滑动，内存泄漏）

### ISSUE THREAD

**Issue by zmmzhaomaomao** [CarGuo/GSYVideoPlayer#2119]
# 问题描述：
1.添加了GSYVideoPlayer播放器的页面中（布局：ConstraintLayout:{GSYVideoPlayer+RecyclerView}），全屏后再退出全屏发现页面中可滑动的部分被滑动（RecyclerView）,推测是由于隐藏导航按键引起的，Demo中 WEB DETAIL页面也存在同样问题。

2.GSYVideoPlayer播放器主动调用startWindowFullscreen方法时，actionBar和statusBar两个参数代表的分别是是否需要隐藏actionBar和statusBar，如果设置为true, 但是在GSYBaseVideoPlayer的startWindowFullscreen方法中调用的saveLocationStatus中会导致mListItemRect[1]的位置不对的问题（Activity启用沉浸式时和Theme设置为NoActionBar时）

3.内存泄漏的问题，使用StandardGSYVideoPlayer时，如果在视频加载时退出页面，此时ENDownloadView的动画正在执行会导致泄露，建议在StandardGSYVideoPlayer的release()方法中
调用ENDownloadView的release()方法。也建议在StandardGSYVideoPlayer的release()方法中调用cancelProgressTimer()与cancelDismissControlViewTimer()方法。音频焦点监听器的释放建议也在release()方法中进行调用，因为同样会出现内存泄漏的情况。

## 问题机型/系统：

例如 真机 小米Mi8 Android8.1;  Meizu note8 Android 8.1；华为 Nova4 Android9.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的WEB DETAIL页面打开后全屏再返回会出现这个问题。

问题代码：(如果有)
建议在StandardGSYVideoPlayer中添加：
`@Override
    public void release() {
        super.release();
        if (!isReleaseWhenLossAudio()) {
            releaseAudioFocusListener();
        }
        if (mLoadingProgressBar instanceof ENDownloadView) {
            ((ENDownloadView) mLoadingProgressBar).release();
        }
        cancelProgressTimer();
        cancelDismissControlViewTimer();
    }

    /**
     * 释放音频焦点变化监听器
     */
    public void releaseAudioFocusListener() {

        mAudioManager.abandonAudioFocus(onAudioFocusChangeListener);
        Log.d(TAG, "release audio focus change listener");
    }`

**Comment by CarGuo** [comment]
音频焦点的那个可以忽略

**Comment by zmmzhaomaomao** [comment]
感谢关注！ 请问第一点和第二点是否可以确认？或者我可以有什么方式解决吗？

**Comment by CarGuo** [comment]
第一个问题确实会有，单貌似是 WebView 中会出现，而 RecyclerView 应该是不会的。

第二个问题说的位置不对，是动画的位置不对是吧？

**Comment by zmmzhaomaomao** [comment]
> 第二个问题说的位置不对，是动画的位置不对是吧？

第一个问题在我的那个结构中是会出现的（ConstraintLayout+{自定义的GSYVideoPlayer+各种控件+RecyclerView}），这个问题是和虚拟导航键有关系；
第二个问题是这样的：我的Activity是使用了沉浸式的，statusBar的部分使用了一个额外的颜色，接着再跟着播放器摆放，主题使用的是NoActionBar，这个activity也没有使用额外的Toolbar或者ActionBar，我在调用startWindowFullscreen时，actionBar参数值是false，statusBar是true，这时跟随代码会发现临时保存的videoPlayer的屏幕位置的值会减去statusBar的高度，但是statusBar又是控制全屏之后statusBar显不显示的，在我看来，这里是有点冲突了，一点愚见，请待指教。

**Comment by CarGuo** [comment]
目前我在Demo 的 ScrollingActivity 中貌似没出发现这个问题。

至于 statusBar ，这个里的保存只是为了动画退出全屏的时候，因为非全屏是有状态栏的，需要找到减去状态栏的绘制动画回去

**Comment by zmmzhaomaomao** [comment]
> 目前我在Demo 的 ScrollingActivity 中貌似没出发现这个问题。
> 
> 至于 statusBar ，这个里的保存只是为了动画退出全屏的时候，因为非全屏是有状态栏的，需要找到减去状态栏的绘制动画回去

statusBar保存位置我明白是为了什么，这也是我为什么单独提出了这个问题，因为我在启动动画后，全屏到正常时，位置不能准确显示到正常窗口。针对“_因为非全屏是有状态栏的，需要找到减去状态栏的绘制动画回去_”，我认为要判断activity是否启用了沉浸式，如果启用了，我认为可以不用减去状态栏的高度，如果未启用可以减去。 我在我自定义的GSYVideoPlayer中，我重写了startWindowFullScreen的方法，没有减去statusbar的高度（因为我启用的沉浸式），最终动画能完美的到达正常窗口的位置，因此我认为保存VideoPlayer位置时，需要判断是否启用沉浸式以及是否存在ActionBar。

**Comment by CarGuo** [comment]
了解，明白了，是因为沉浸式导致的，最近也有人提出这个问题。 get

至于第一个问题，因为虚拟导航导致的滑动？

**Comment by zmmzhaomaomao** [comment]
> 了解，明白了，是因为沉浸式导致的，最近也有人提出这个问题。 get
> 
> 至于第一个问题，因为虚拟导航导致的滑动？

我认为是的，我刚刚使用了未启用导航键的手机（Vivo x20plus Android 7.1.1）去验证了这个问题，在未启用导航键的手机上未出现页面滑动的情况。

**Comment by CarGuo** [comment]
沉浸式问题修复已提交到 master ，至于导航建问题我在红米pro上没复现

**Comment by zmmzhaomaomao** [comment]
> 沉浸式问题修复已提交到 master ，至于导航建问题我在红米pro上没复现

ok  感谢关注，我会把这个issues关闭掉，如果后续我对这个问题有进展，我将把解决方案反馈出来。
