### ISSUE TITLE
横屏时候所有联网重新走了一遍

### ISSUE THREAD

**Issue by QueryGad** [CarGuo/GSYVideoPlayer#212]
之前一个项目用了GSYVideoPlayer没有这种情况，但是这两次用都是这种情况，点击横屏所有的联网重新走一遍，从横屏切换为竖屏又重新获取全部联网数据。仔细对比这三次的代码，并没有发现有什么不同。实在是想不出来，求作者指点迷津！！！

**Comment by CarGuo** [comment]
请配置manifets，参考demo哟

**Comment by QueryGad** [comment]
不行  配置和Demo上的一致 还是重新获取全部数据

**Comment by CarGuo** [comment]
activity配置manifest

**Comment by QueryGad** [comment]
android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"  是这个吧  我配置了

**Comment by CarGuo** [comment]
你底部的activity也要

**Comment by QueryGad** [comment]
就是这个原因，终于解决了。谢谢作者
