### ISSUE TITLE
可否全屏的时候在播放器之上悬浮一个View

### ISSUE THREAD

**Issue by combing520** [CarGuo/GSYVideoPlayer#2122]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
请问下；可否在播放器全屏的时候悬浮一个自定义的View于播放器之上
XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
可以

**Comment by LvslGit** [comment]
> 可以

请问最新版本加的有全局View了么？

**Comment by CarGuo** [comment]
@LvslGit demo 有啊

**Comment by combing520** [comment]
请问下；传递View ；在 播放器全屏与否都能显示的话；在 Demo 中有？ 如果有的话，请问下，可以参考demo中的哪一个？谢谢

**Comment by CarGuo** [comment]
WindowActivity

**Comment by combing520** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 上午9:47
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>; 
抄送: "swirlLG"<545830588@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CarGuo/GSYVideoPlayer] 可否全屏的时候在播放器之上悬浮一个View (#2122)




WindowActivity

**Comment by LvslGit** [comment]
> WindowActivity

谢谢，我准备在这个view上添加长按点击事件。可以的吧。

**Comment by LvslGit** [comment]
> WindowActivity

你好，我问下，我用StandardGSYVideoPlayer 这个对象，怎么添加他的长按点击事件呢，我使用getCurrentPlayer也不行啊，点击事件不启用。

**Comment by LvslGit** [comment]
> WindowActivity

哈哈，我通过继承自定义你的VideoPlayer解决问题了。
