### ISSUE TITLE
IllegalStateException mpjni: start: null mp

### ISSUE THREAD

**Issue by Leavds** [CarGuo/GSYVideoPlayer#2123]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

mpjni: start: null mp

com.shuyu.gsyvideoplayer.player.IjkPlayerManager.start(IjkPlayerManager.java:194)

## 问题机型/系统：

一加 A6010

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

偶现

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

android.app.ActivityThread.performResumeActivity(ActivityThread.java:3919)
--
3 ......
4 Caused by:
5 java.lang.IllegalStateException:mpjni: start: null mp
6 tv.danmaku.ijk.media.player.IjkMediaPlayer._start(Native Method)
7 tv.danmaku.ijk.media.player.IjkMediaPlayer.start(IjkMediaPlayer.java:523)
8 com.shuyu.gsyvideoplayer.player.IjkPlayerManager.start(IjkPlayerManager.java:194)
9 com.shuyu.gsyvideoplayer.GSYVideoBaseManager.start(GSYVideoBaseManager.java:454)

**Comment by Leavds** [comment]
这是什么原因  引起的  怎么处理

**Comment by CarGuo** [comment]
很明显是 ijk 为空的时候调用了 start
