### ISSUE TITLE
遥控器ok键无响应 KEYCODE_DPAD_CENTER

### ISSUE THREAD

**Issue by pyp163** [CarGuo/GSYVideoPlayer#2124]
## 问题描述：
android 9.0
  布局:
   <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.vod.activity.Main2Activity">

    <com.publics.video.EmptyControlVideo
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:focusable="false"
        android:focusableInTouchMode="false">

    </com.publics.video.EmptyControlVideo>
</androidx.constraintlayout.widget.ConstraintLayout>

Activity:
public class Main2Activity extends BaseActivity {

    private EmptyControlVideo video;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
        video = findViewById(R.id.video_view);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        LogDog.i("------键值--------"+keyCode);
        return super.onKeyDown(keyCode, event);
    }
}
遥控器按ok无响应：
ok键值：TvWindowManager: key event key = KEYCODE_DPAD_CENTER
按上下左右键有响应有打印Log

## 问题机型/系统：

某电视机顶盒子 Android9.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by CarGuo** [comment]
em……我不认为这个是项目的问题

**Comment by pyp163** [comment]
但是我去掉播放器按ok键正常
<com.publics.video.EmptyControlVideo
    android:id="@+id/video_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:focusable="false"
    android:focusableInTouchMode="false">

</com.publics.video.EmptyControlVideo>

**Comment by pyp163** [comment]
android7.0正常

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1302

**Comment by pyp163** [comment]
#1302 的代有参考过
因为不让EmptyControlVideo有焦点不需要实现onKeyDown
android:focusable="false"
android:focusableInTouchMode="false"
onKeyDown由Activity来控制，上下左右键可以响应，就ok键不响应很尴尬

**Comment by CarGuo** [comment]
em····这个还真不是很清楚

**Comment by CarGuo** [comment]
@xwlcn   demo 现在提供了 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/TvVideoPlayer.java

另外就像你说的，override onClick 处理
