### ISSUE TITLE
视频暂停时，计时任务没有停止，请问为什么暂停的时候需要启动startProgressTimer方法；

### ISSUE THREAD

**Issue by peiguojie123** [CarGuo/GSYVideoPlayer#2126]
## 问题描述：

视频暂停时，计时任务没有停止，请问为什么暂停的时候需要启动startProgressTimer方法；

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:5.0.2'`

问题代码：(如果有)
https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/base/GSYVideoControlView.java

            第245行
            case CURRENT_STATE_PAUSE:
                startProgressTimer();
                break;

## 问题log（如果有）

07-10 18:39:07.392 13773-13773/cn.wdcloud.luke D/ProgressBar: setProgress, old = 9, new = 9, max = 100, backtrace = android.widget.ProgressBar.setProgress:1311 com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setProgressAndTime:896 com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setTextAndProgress:882 com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView$ProgressTimerTask$1.run:1029 android.os.Handler.handleCallback:815 , this = cn.wdcloud.luke.courseedit.weight.EditVideoBar{332a4c58 VFED.... ........ 140,10-561,70 #7f0f0348 app:id/progress}

**Comment by CarGuo** [comment]
请看最新版本
