### ISSUE TITLE
我没有开启缓存,第一次播放,getNetSpeedText一直是0 

### ISSUE THREAD

**Issue by dary123** [CarGuo/GSYVideoPlayer#2127]
我没有开启缓存,第一次播放,getNetSpeedText一直是0 ，试了很多资源,有秒播的，也有开始缓冲时间较长的，都显示为0

**Comment by CarGuo** [comment]
我这边测试正常

**Comment by dary123** [comment]
我知道什么原因了，因为我是开始的时候进行设置的，没有用计时器，是不是还需要一个计时器，每隔1秒重新设置

**Comment by CarGuo** [comment]
额····没太明白你的意思

**Comment by dary123** [comment]
我添加了一个TextView在播放器上，用来显示getNetSpeedText获取的值，但是setText方法我只调用了一次，刚进入界面的时候调用的，然后就不再更新TextView的文本内容了，即使getNetSpeedText()方法获取的值有变化，TextView显示的还是跟之前一样，因为我没有设置一个计时器，每隔1秒重新更新下TextView显示的内容
