### ISSUE TITLE
自定义Manager 利用setListener方法 与startPrepare是否有办法解决冲突

### ISSUE THREAD

**Issue by aozaoz112233** [CarGuo/GSYVideoPlayer#2128]
## 问题描述：

您好，我希望能够在外部使用Manager setListener以监听GSYMediaPlayerListener
于是我自定义了VideoManager重写了getPlayManager()，在使用setListener时发生了如下问题:

startPrepare方法会覆盖Listener，于是先setListener再startPlayLogic会收不到回调，于是我重写了startPrepare把Listener相关的 gsyVideoManager.setListener(this) 给屏蔽了，最后发现startPlayLogic无法再生效。（如：我stop之后再调用startPlayLogic或者如同demo一样切换清晰度，能看到onBufferingUpdate在加载但view没有任何显示）

请问有办法能更好的方法保证能收到GSYMediaPlayerListener

## 问题机型/系统：

任一

## GSY依赖版本

com.shuyu:GSYVideoPlayer:6.0.3

## Demo中的复现步骤

非demo问题

问题代码：(如果有)

**Comment by CarGuo** [comment]
你可以对你需要的做一层代理模式啊

**Comment by aozaoz112233** [comment]
抱歉我没能理解您的意思，感觉代理模式无法解决接口回调被覆盖的问题。

我目前的解法是自定义VideoPlayer，把GSYVideoBaseManager中GSYMediaPlayerListener实现方法全部复写，在调super的同时去调我另写的一个Listener，但感觉这样写不怎么好，如果您有更好的方案可以抽空写一下，谢谢。
