### ISSUE TITLE
6.0.3引入项目资源冲突appcompat-v7-27.0.2.aar

### ISSUE THREAD

**Issue by GothJoker** [CarGuo/GSYVideoPlayer#2130]
## 问题描述：

6.0.3  //GSYVideoPlayer 视频播放 完整版引入
        implementation ('com.shuyu:GSYVideoPlayer:6.0.3') {
            exclude(group: 'com.android.support')
        }

引入后  报这个错误 ：Attribute "duration" already defined with incompatible format.
Message{kind=ERROR, text=Attribute "duration" already defined with incompatible format., sources=[C:\Users\hasee\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\ac46ab1862849ca2511842dca00a87f2\res\values\values.xml:252:5-69], original message=, tool name=Optional.of(AAPT)}

![image](https://user-images.githubusercontent.com/20930913/61037494-c3e30800-a3fd-11e9-9341-bf02b036b54f.png)

**Comment by CarGuo** [comment]
em·····so ？

**Comment by GothJoker** [comment]
有什么好的办法解决吗？ 我找了好久

**Comment by CarGuo** [comment]
和你项目冲突了只能你自己找哇
