### ISSUE TITLE
Android 9.0 缓存问题

### ISSUE THREAD

**Issue by p-jie** [CarGuo/GSYVideoPlayer#2132]
## 问题描述：

Android 9.0 缓存问题

## 问题机型/系统：

小米8 Android9.0

华为 荣耀 Android9.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中用9.0的机器打开视频，暂停，等缓存完了以后，退出重新打开，依然要加载缓存，而不是读取缓存文件

问题具体描述：

在android 9.0 以下的版本，开启默认的缓存模式，边播放视频边缓存的情况下，缓存完了视频再重新打开该视频的时候，会直接读取缓存文件。

在android 9.0 的版本 边播放视频边缓存的情况下，缓存完了视频再重新打开该视频的时候，不会读取缓存文件，而是会重新进行缓存，这样一来会导致缓存文件越来越多，越来越大。是否有办法在6.0.3版本处理呢？ demo版本是7.0.3的，也有这样的问题，而且我不希望依赖7.0的版本，因为7.0版本您引入了androidx的依赖包，在老项目中使用会导致各种包重复的问题。

请问下是否有办法解决android 9.0 上缓存问题？

**Comment by p-jie** [comment]
缓存问题不能解决吗？

**Comment by CarGuo** [comment]
····
其实就是 http 在高版本的问题啊

https://github.com/CarGuo/GSYVideoPlayer/commit/ee3c8a1a65d95fd482963e6c6a587af31eb09f8d
