### ISSUE TITLE
启动悬浮窗崩溃

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [CarGuo/GSYVideoPlayer#2135]
## 问题描述：

Demo启动悬浮窗崩溃

## 问题机型/系统：

真机 华为 CUN-AL00 Android5.1

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

## Demo中的复现步骤

Demo中的WindowActivity页面点击悬浮窗会出现这个问题。

## 问题log（如果有）

![image](https://user-images.githubusercontent.com/15881869/61199448-930e1600-a710-11e9-9087-899e8fffd78b.png)

**Comment by AndroidJohnsonWang** [comment]
问题是FloatPhone 的60行， if (Util.hasPermission(mContext)) ，没有判断6.0版本以上才能用。本来想自己继承重写的，发现FloatPhone 不是公开类，没辙了

**Comment by CarGuo** [comment]
FloatPhone 我这边是在 demo 里的啊···

**Comment by AndroidJohnsonWang** [comment]
OK，解决了
