### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by ManoR88** [CarGuo/GSYVideoPlayer#2138]
Hello developer on quitting full screen there is white blink in status bar for few seconds a... how to avoid it
![image](https://user-images.githubusercontent.com/43945872/61264025-9a80fe00-a7a8-11e9-984a-d9cfd0802726.png)

**Comment by CarGuo** [comment]
How to Reproduced it

**Comment by ManoR88** [comment]
Any solution to avoid that white color in status bar ?

**Comment by CarGuo** [comment]
I'm not sure what you mean ，could you tell me how to reproduced it in demo
