### ISSUE TITLE
全屏时候隐藏Statusbar引发crash

### ISSUE THREAD

**Issue by UrielSun** [CarGuo/GSYVideoPlayer#2142]
## 问题描述：
集成播放器全屏是调取startWindowFullscreen(this, true, true)引发空指针异常

## 问题机型/系统：

真机 小米9 Android9.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

## Demo中的复现步骤
1.新建项目继承自Activity(非AppCompatActivity)
2.点击全屏按钮调取startWindowFullscreen(this, true, true)引发空指针

原因:Activity继承自ContextThemeWrapper，所以会调取getAppCompActivity(((ContextThemeWrapper) context).getBaseContext());
此时的context为android.app.ContextImpl所以会直接返回null

问题代码：(如果有)
```
public static AppCompatActivity getAppCompActivity(Context context) {
        if (context == null) return null;
        if (context instanceof AppCompatActivity) {
            return (AppCompatActivity) context;
        } else if (context instanceof ContextThemeWrapper) {
            return getAppCompActivity(((ContextThemeWrapper) context).getBaseContext());
        }
        return null;
    }
```

## 问题log（如果有）

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window androidx.appcompat.app.AppCompatActivity.getWindow()' on a null object reference
        at com.shuyu.gsyvideoplayer.utils.CommonUtil.hideSupportActionBar(CommonUtil.java:128)
        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.startWindowFullscreen(GSYBaseVideoPlayer.java:587)
        at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.startWindowFullscreen(StandardGSYVideoPlayer.java:363)

```

**Comment by CarGuo** [comment]
所以继承 AppCompatActivity 不就可以了

**Comment by UrielSun** [comment]
FlutterActivity继承自Activity,这个时候如果想用你这封装成Flutter插件就有问题了

**Comment by CarGuo** [comment]
哦，你是在 flutter 里使用啊，兼容 Activity 的代码已经提交了，不过得下个版本更新，推荐你可以通过继承后重载解决。

不过，你是用的 PlatformView 方式集成的？还是新的页面打开的？

**Comment by UrielSun** [comment]
嗯。感谢，我用的PlatformView的方式~
