### ISSUE TITLE
对于tv或者盒子来说，版本太高了

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#2147]
对于tv或者盒子来说，版本太高了，

有考虑兼容吗，或者有什么替代的？

**Comment by CarGuo** [comment]
？？？

**Comment by renwfy** [comment]
@CarGuo ， minSdkVersion 19
                     targetSdkVersion 28      ， 一般电视还徘徊在4.4……

**Comment by CharlesMing** [comment]
下载源码 修改版本号吧
