### ISSUE TITLE
onVideoResume 无法播放

### ISSUE THREAD

**Issue by KalvinZhuang** [CarGuo/GSYVideoPlayer#2149]
## 问题描述：
onPause =》 onResume  
表现：
进度条正常，画面不动，声音正常

## 问题机型/系统：

魅蓝note6 android 7.1

## Demo中的复现步骤
简单播放-》简单直接播放（我是直接 master 分支build 安装的）

## 备注
-  releases 上下载了demo 是可以的
-  v7.0.2 tag build 的也没有这个问题  _(:з」∠)_

**Comment by CarGuo** [comment]
master 和 7.0.2 在这块功能上没有修改过呢
