### ISSUE TITLE
播放器界面全屏后，不会显示时间和电量等信息

### ISSUE THREAD

**Issue by zourb** [CarGuo/GSYVideoPlayer#2150]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放器界面全屏后，不会显示时间和电量等信息

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

小米8 Lite

## Demo中的复现步骤

Demo中的detailPlayer页面打开后全屏播放会出现这个问题。

**Comment by CarGuo** [comment]
是的，不显示

**Comment by zourb** [comment]
@CarGuo 这个有办法规避么

**Comment by CarGuo** [comment]
你看bilibili的android客户端全屏就知道了

**Comment by zourb** [comment]
bilibili看着像是自己加的时间和电量View

**Comment by CarGuo** [comment]
是的，就是如此
