### ISSUE TITLE
请问RTSP播放的时候，如何获取每帧数据？

### ISSUE THREAD

**Issue by soul7630** [CarGuo/GSYVideoPlayer#2153]
请问RTSP流播放的时候，有没有提供回调方法能实时获取帧数据的？

**Comment by CarGuo** [comment]
没有

**Comment by caik123** [comment]
急切需要这个功能

**Comment by CarGuo** [comment]
em····或者你可以考虑 GLSurfaceView 吧，参考  https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/render/view/GSYVideoGLView.java

https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/effect

https://blog.csdn.net/nimeghbia/article/details/77899355
