### ISSUE TITLE
请问下// X, Y, Z, U, V中的U,V是什么意思？

### ISSUE THREAD

**Issue by MaryDQ** [CarGuo/GSYVideoPlayer#2154]
GSYVideoGLViewSimpleRender这个类里边的
private final float[] mTriangleVerticesData = {
            // X, Y, Z, U, V
            -1.0f, -1.0f, 0.0f,
            0.0f, 0.0f, 1.0f,
            -1.0f, 0.0f, 1.0f,
            0.0f, -1.0f, 1.0f,
            0.0f, 0.0f, 1.0f,
            1.0f, 1.0f, 0.0f,
            1.0f, 1.0f,};

最近在研究矩阵
XYZ的意思我能懂，请问下U,V指的是什么？

**Comment by CarGuo** [comment]
uv纹理坐标

**Comment by MaryDQ** [comment]
好的谢谢
