### ISSUE TITLE
APK Size too large - 25 MB

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2155]
Hi there. First, thanks for the great work.

I have included all the projects (gsyVideoPlayer, gsyVideoPlayer-armv5, gsyVideoPlayer-armv7 etc). This causes the APK size to be too large. I tried unloading some of the modules (only 3 libraries were there as a result - gsyVideoPlayer, gsyVideoPlayer-exo_player2 and gsyVideoPlayer-java) but the size remained unchanged.

How do I reduce the APK size ( ideally less than 10MB )? Thanks :)

**Comment by CarGuo** [comment]
ndk filter

**Comment by muzeasd** [comment]
Thanks. That is the first thing I tried, but size remains unchanged. This is what I tried

`
    viewDependencies = 
[
            ijkplayer_java       : "tv.danmaku.ijk.media:ijkplayer-java:${ijkplayer}",
            ijkplayer_exo        : "tv.danmaku.ijk.media:ijkplayer-exo:${ijkplayer}",
            transitionseverywhere: "com.andkulikov:transitionseverywhere:${transitionseverywhere}",
            exo_player2          : "com.google.android.exoplayer:exoplayer:${exo_player2}",
            exo_player2_rtmp     : "com.google.android.exoplayer:extension-rtmp:${exo_player2}",
            glide                : "com.github.bumptech.glide:glide:${imageLoader}",
            glideProcessor       : "com.github.bumptech.glide:compiler:${imageLoader}",
//            butterKnife          : "com.jakewharton:butterknife:${butterKnifeVersion}",
//            apt_butterKnife      : "com.jakewharton:butterknife-compiler:${butterKnifeVersion}",
//            ijkplayer_armv7a     : "tv.danmaku.ijk.media:ijkplayer-armv7a:${ijkplayer}",
//            ijkplayer_armv5      : "tv.danmaku.ijk.media:ijkplayer-armv5:${ijkplayer}",
//            ijkplayer_arm64      : "tv.danmaku.ijk.media:ijkplayer-arm64:${ijkplayer}",
//            ijkplayer_x86_64     : "tv.danmaku.ijk.media:ijkplayer-x86_64:${ijkplayer}",
//            ijkplayer_x86        : "tv.danmaku.ijk.media:ijkplayer-x86:${ijkplayer}",
//            DanmakuFlameMaster   : "com.github.ctiao:DanmakuFlameMaster:${DanmakuFlameMaster}",
//            ndkbitmap_armv7a     : "com.github.ctiao:ndkbitmap-armv7a:${DanmakuFlameMasterSo}",
//            ndkbitmap_armv5      : "com.github.ctiao:ndkbitmap-armv5:${DanmakuFlameMasterSo}",
//            ndkbitmap_x86        : "com.github.ctiao:ndkbitmap-x86:${DanmakuFlameMasterSo}",
//            floatWindow          : "com.github.yhaolpz:FloatWindow:${floatWindow}",
    ]`

As you can see, only the required libs are there. Rest are commented out. Still no effect. Am I doing something wrong??

**Comment by muzeasd** [comment]
Ok. Thanks. I fixed it by reading [this](https://www.jianshu.com/p/86e4b336c17d) link.
