### ISSUE TITLE
缓存的问题

### ISSUE THREAD

**Issue by xiaoyao521** [CarGuo/GSYVideoPlayer#2156]
如果需要使用MP4的缓存文件，因该怎么使用，怎么监听

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/f64ecf552ee7ac8d9cfdaa1a5b827821bd1fcf3e/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/cache/ProxyCacheManager.java#L91

**Comment by xiaoyao521** [comment]
好的，谢谢




| |
要智浩
邮箱：15101601513@163.com
|

签名由 网易邮箱大师 定制

在2019年07月29日 14:09，Shuyu Guo 写道：

https://github.com/CarGuo/GSYVideoPlayer/blob/f64ecf552ee7ac8d9cfdaa1a5b827821bd1fcf3e/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/cache/ProxyCacheManager.java#L91
