### ISSUE TITLE
Video not showing in Release version

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2157]
Hello there. Everything is working fine. But when I installed the release version of the app, the video is not showing. though I can listen to the audio sound. How do I debug this ? Thanks

**Comment by CarGuo** [comment]
what's the type of video encoded in your video stream?
h264? mpeg?

try `e x_so`  if it's mpeg 。

```
implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.0.2'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.0.2'
```

also try to change default surface to SurfaceView

```
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
```

**Comment by muzeasd** [comment]
Mostly I use follwing type of video URLs
[Manly Beach](https://cf-stream.coastalwatch.com/cw/manlycamerahd.stream/playlist.m3u8)

Played this using **ffplay** and found out that most of them were using **h264** under the hood.

I am using EmptyControlVideo. Shall this line be put in constructor of EmptyControlVideo??

/////  =============   code eample ==================

public EmptyControlVideo(Context context, AttributeSet attrs) 
{
        super(context, attrs);
        GSYVideoType. setShowType(SCREEN_MATCH_FULL);
        GSYVideoType.setRenderType(GSYVideoType.SUFRACE);        // <<---------- your line here
}

**Comment by CarGuo** [comment]
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);  is global config , your can put it in application or you like

**Comment by muzeasd** [comment]
Ok. I tried that. It is working. BUT......with a problem. I can not take a snapshot no more.  It throws **not supported exception now** exception in GSYSurfaceView::taskShotPic(). I changed that render type to GSYVideoType.GLSURFACE and, I think, it is working. You can close this but I am gonna open another issue related to snaphot with GSYVideoType.SURFACE params
