### ISSUE TITLE
onError 偶尔 回调whats -10000  extra 0错误，播放不出来

### ISSUE THREAD

**Issue by xwaitalonec** [CarGuo/GSYVideoPlayer#2158]
## 问题描述：

onError 偶尔 回调whats -10000  extra 0错误，播放不出来

## 问题机型/系统：

红米 note7 android9 和机型系统应该没关系在三星android9上也有这个问题

## GSY依赖版本
IJK模式
 PlayerFactory.setPlayManager(IjkPlayerManager.class);
使用CustomManager  EmptyControlVideo多任务同时播放2个， 一个有问题回调whats -10000  extra 0，一个没问题 不是百分百出现
`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

**Comment by CarGuo** [comment]
请提供有问题的视频流

**Comment by xwaitalonec** [comment]
http://statics.dual-whatsapp.com/DailyRecordVideo/5cff7f51cf1cfe004451f6b4/20190731/VID_e44f038494e0757e41e4722fe1a0bd30.mp4  多谢




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>;
发送时间: 2019年7月30日(星期二) 上午9:54
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "谢超"<1446252306@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CarGuo/GSYVideoPlayer] onError 偶尔 回调whats -10000  extra 0错误，播放不出来 (#2158)




请提供有问题的视频流

**Comment by xwaitalonec** [comment]
这个是第三方加了美颜的sdk录的视频




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>;
发送时间: 2019年7月30日(星期二) 上午9:54
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "谢超"<1446252306@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CarGuo/GSYVideoPlayer] onError 偶尔 回调whats -10000  extra 0错误，播放不出来 (#2158)




请提供有问题的视频流

**Comment by CarGuo** [comment]
这个地址 Unable to connect to
显示 unreachable

**Comment by xwaitalonec** [comment]
这个地址需要翻墙的

**Comment by CarGuo** [comment]
今天测试的时候已经翻了。

**Comment by xwaitalonec** [comment]
确定翻出去了,浏览器可以打开吗?




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 晚上8:44
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>; 
抄送: "谢超"<1446252306@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CarGuo/GSYVideoPlayer] onError 偶尔 回调whats -10000  extra 0错误，播放不出来 (#2158)




今天测试的时候已经翻了。

**Comment by CarGuo** [comment]
翻了，但是浏览器打不开你的链接

<img width="854" alt="image" src="https://user-images.githubusercontent.com/10770362/62337381-eea91380-b506-11e9-921e-ff0c8c616bc1.png">

**Comment by xwaitalonec** [comment]
这个错误码是在哪抛出的吗，还是我自己去看吧




------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>; 
发送时间: 2019年8月2日(星期五) 上午9:22
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>; 
抄送: "谢超"<1446252306@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CarGuo/GSYVideoPlayer] onError 偶尔 回调whats -10000  extra 0错误，播放不出来 (#2158)




翻了，但是浏览器打不开你的链接

**Comment by OvenCroc** [comment]
大佬 我也遇到了这个问题 我是两个直播流之间切换 比如我现在在播放A地址,然后切换到B地址 B就不能播放了, 单独播放每个地址都是可以的 错误码也是10000和0  我是用的版本是6.0.3 测试机型是as 自带虚拟机

**Comment by xwaitalonec** [comment]
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);&nbsp; &nbsp;加这个试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oven"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 晚上6:17
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;; 
抄送: "谢超"<1446252306@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CarGuo/GSYVideoPlayer] onError 偶尔 回调whats -10000  extra 0错误，播放不出来 (#2158)




大佬 我也遇到了这个问题 我是两个直播流之间切换 比如我现在在播放A地址,然后切换到B地址 B就不能播放了, 单独播放每个地址都是可以的 错误码也是10000和0  我是用的版本是6.0.3 测试机型是as 自带虚拟机

**Comment by OvenCroc** [comment]
> 
> GSYVideoType.setRenderType(GSYVideoType.SUFRACE);&nbsp; &nbsp;加这个试试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Oven"<notifications@github.com&gt;; 发送时间: 2020年2月20日(星期四) 晚上6:17 收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;; 抄送: "谢超"<1446252306@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [CarGuo/GSYVideoPlayer] onError 偶尔 回调whats -10000 extra 0错误，播放不出来 (#2158) 大佬 我也遇到了这个问题 我是两个直播流之间切换 比如我现在在播放A地址,然后切换到B地址 B就不能播放了, 单独播放每个地址都是可以的 错误码也是10000和0 我是用的版本是6.0.3 测试机型是as 自带虚拟机 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬 我加了你发的那句代码 但是还是不行 而且用你的demo跑也是一样可以复现, 流程就是先播放一个直播的m3u8地址, 然后再切换到另一个m3u8地址 两个地址都是可以用的, 单独播放也都可以 , 但是在同一个页面里面先后播放这两个地址, 就会出现我之前说到的10000的那个情况.

**Comment by OvenCroc** [comment]
//修复,点击多个url导致不能播放的bug
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1));
        GSYVideoManager.instance().setOptionModelList(list);

好像可以解决我的这个问题 哈哈哈
