### ISSUE TITLE
Can not Take Snapshot with  GSYVideoType.SURFACE

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2159]
Hello there. I can not take a snapshot when render type is set as _GSYVideoType.SURFACE_. It throws **not supported exception now** exception in GSYSurfaceView::taskShotPic().

Exact message is:   "GSYSurfaceView not support taskShotPic now"

I changed that render type to GSYVideoType.GLSURFACE and, I think, it is working.

I was using the default render type but I had to use the above mentioned because videos were not being shown in Release version of app. What am I doing wrong?

**Comment by CarGuo** [comment]
default render type is TextureView ,  you may try to resolve with this

https://stackoverflow.com/questions/16693194/textureview-onsurfacetextureavailable-never-called-inside-relativelayout-inside

like set hardwareAccelerated="true"

**Comment by muzeasd** [comment]
Okey. Thanks. It worked.
