### ISSUE TITLE
问下 如果是support版本的（6.0.3），7.0以后解决的BUG是不是无法得到修复

### ISSUE THREAD

**Issue by kokobebekoko** [CarGuo/GSYVideoPlayer#2160]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

问下 如果是support版本的，7.0以后版本解决的BUG是不是无法得到修复

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
bug 只在新版本修复
