### ISSUE TITLE
Why EmptyVideoControl.isInPlayingState() returns true

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2161]
Hello there. I want to take snapshot only when video url is loaded in the player. 

So I check if player is in playing state by checking condition mentioned in title. The problem is:  it returns TRUE even if the video is still loading. Should it not return FALSE when video is still loading?

How do check that video is still loading and should display appropriate message if I try to take snapshot before video is is loaded? Thanks

**Comment by CarGuo** [comment]
because of `isInPlayingState` function included preparing status ：

```
    public boolean isInPlayingState() {
        return (mCurrentState >= 0 && mCurrentState != CURRENT_STATE_NORMAL
                && mCurrentState != CURRENT_STATE_AUTO_COMPLETE && mCurrentState != CURRENT_STATE_ERROR);
    }

```

your may try `player.getCurrentPlayer().getCurrentState()`  and judgment with :

```
  
    public static final int CURRENT_STATE_NORMAL = 0;

    public static final int CURRENT_STATE_PREPAREING = 1;

    public static final int CURRENT_STATE_PLAYING = 2;

    public static final int CURRENT_STATE_PLAYING_BUFFERING_START = 3;

    public static final int CURRENT_STATE_PAUSE = 5;

    public static final int CURRENT_STATE_AUTO_COMPLETE = 6;

    public static final int CURRENT_STATE_ERROR = 7;

```

**Comment by muzeasd** [comment]
Ok. Thanks. This did the trick

```
if(player.getCurrentPlayer().getCurrentState() == CURRENT_STATE_PLAYING ||
                            player.getCurrentPlayer().getCurrentState() == CURRENT_STATE_PAUSE){

// my code here

}
```
