### ISSUE TITLE
编译时候报错

### ISSUE THREAD

**Issue by OOOOOldZhu** [CarGuo/GSYVideoPlayer#2167]
## 问题描述：
编译时候报错
Error: Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`
![image](https://user-images.githubusercontent.com/24487309/62233540-5e31dc80-b3fb-11e9-8716-0925bf8befef.png)

![image](https://user-images.githubusercontent.com/24487309/62233469-3c385a00-b3fb-11e9-84a6-31a817f93e22.png)
![image](https://user-images.githubusercontent.com/24487309/62233504-4b1f0c80-b3fb-11e9-98f9-91ba75fa7a7b.png)

**Comment by CarGuo** [comment]
7.0.2是 androidx的了

**Comment by OOOOOldZhu** [comment]
> 7.0.2是 androidx的了

那我该怎么解决？亲

**Comment by OOOOOldZhu** [comment]
> 7.0.2是 androidx的了

你的库多少版本之后是AndroidX？ 我打算依赖一个旧版本。

**Comment by CarGuo** [comment]
7.x.x开始 androidx
