### ISSUE TITLE
内存释放不掉

### ISSUE THREAD

**Issue by tangkoucan** [CarGuo/GSYVideoPlayer#2169]
反复进入退出视频页面，并且退出视频页面 onDestroy（） 调用视频释放代码releaseVideos（）等，但是通过AS profiler 工具分析 内存越来越大，主要体现在 others 部分，始终无法释放，试了提供的demo一样存在这个问题。
![image](https://user-images.githubusercontent.com/5821598/62357548-e3c1a380-b545-11e9-94cb-904bdf8eb46e.png)

## 问题机型/系统：
Android 机顶盒 4.4系统
## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'
implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.1'

不知道新版本是否已经解决这个问题，有人遇到过吗，希望大神指导！

**Comment by CarGuo** [comment]
release 会有一个异步的过程，至于在 4.4 上现在表现怎么样就不是很好说了，因为个人现在的项目基本上都是 5.0 以上的了
