### ISSUE TITLE
用代码控制播放暂停，频繁后无法正常暂停和播放

### ISSUE THREAD

**Issue by Lucifer119119** [CarGuo/GSYVideoPlayer#2170]
## 问题描述：

用代码控制播放暂停，频繁后无法正常暂停和播放

## 问题机型/系统：

真机 一加6T Android 9.0

## GSY依赖版本

 `implementation 'com.shuyu:GSYVideoPlayer:6.0.3'

我用了DEMO中的无UI界面   在Adapter中动态调用onVideoPause 和 onVideoResume 
当点击频繁后发现无法正常暂停和播放 
DEBUG断点后 发现 在 onVideoResume中 有判断一个mCurrentPosition >0 
不知道为何会=0

**Comment by CarGuo** [comment]
新版本改了，旧版本你可以参考 重载改方法
<img width="777" alt="image" src="https://user-images.githubusercontent.com/10770362/62362281-3489ca00-b54f-11e9-981e-53e9b89b3945.png">
