### ISSUE TITLE
Video not Playing When Player is loaded using Rapid Taps

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2174]
Hello there. I have a video screen on which I play video and also show thumbnails of other videos / URLs. Player works fine if I use GO SLOW approach. But if I tap very quickly on the thumbnails, the video does not load. It just goes black.

Note: I am using EmptyControlVideo.

Here is the code that I use to play the video from suggestions showing in GridLayout.

```
// click listener - in adapter
imgThumbnail.setClickListener(new View.OnClicklistener(){
    @Override
     public void onClick(View view) {
         playVideo(cam.getSource())  // call here
     }
});

// load video function
void playVideo(String source) {
        if(player != null) {
            if(player.isInPlayingState()) {
                player.onVideoPause();
                player = null;
                player = findViewById(R.id.player);
            }
        }

        player.setUp(source, true, "VideoPlayer");
        player.startPlayLogic();
}

```

Why video no loading if I tap quickly on the thumbnails? What am I doing wrong?

**Comment by CarGuo** [comment]
I'm not sure about the scene of this problem, because I can't reproduce it.

**Comment by muzeasd** [comment]
How shall I help you in this regard? Was I able to clearly describe the problem? 

The problem

There is this **EmptyControlVideo** on a screen which works perfectly fine. Below this control, I also have a RecyclerView which holds thumbnails for other video URLs. Tapping on any of those thumbnails will load the video URL in EmptyControlVideo player. Again, it works fine if I watch a loaded video for 10-15 seconds and then load another. 

But if I start tapping quickly on those thumbnails, by which I mean, I tap on **Thumbnail 1** then within a second I tap on **Thumbnail 2**, then within a second I tap on **Thumbnail 3** and so on. If you repeat this step 7-8 times.....then you will see that video will not load. 

I am gonna share my log for both scenarios.....when video loads....and when video does not load
[https://drive.google.com/file/d/1WlK5b5jFlIalEHMQYvUs3eWlN6c4qxr0/view?usp=sharing](Working Video Log)
[https://drive.google.com/file/d/1z5-k8PInQSfdaFWspiH6Ztc7CcdpRh7d/view?usp=sharing](Not Working Video Log - When Thumbnails Tapped Quickly)

As you can see, in the working video log, that there are NAL units being logged properly.  But in the other log, where video is not working when thumbnails are tapped quickly, the incorrect NAL units are being recorded.

Hope I was able to help you diagnose the issue. If still unsure about the scenario, please feel free to ask. Thanks for the great efforts :)

**Comment by CarGuo** [comment]
I see , because of  ".release" function is async ,  sometime you have to waiting for it done .

like the scene of  “ tapping quickly on those thumbnails” , I suggest you may need to added some flag, to determine if you need to start playing right away , like double checked .

**Comment by muzeasd** [comment]
Ok. I add a flag which I set to TRUE which then determines that I need to load video right away. Then what change I do in the **playVideo(String source)** function written in question? Can you write a little example code plz?

**Comment by muzeasd** [comment]
Ok. I solved it without doing any custom work.
