### ISSUE TITLE
最低支持7.0？

### ISSUE THREAD

**Issue by lijq126** [CarGuo/GSYVideoPlayer#2175]
最低支持7.0？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/702bc6e552e667bb167cf582f51a84151ec15987/dependencies.gradle#L13

**Comment by lijq126** [comment]
我用最新版的7.0.2提示最低支持7.0

**Comment by lijq126** [comment]
Default interface methods are only supported starting with Android N (--min-api 24): void com.google.android.exoplayer2.Player$EventListener.onLoadingChanged(boolean)

**Comment by lijq126** [comment]
compileOptions {

        sourceCompatibility JavaVersion.VERSION_1_8

        targetCompatibility JavaVersion.VERSION_1_8

    }
配置这个后解决
