### ISSUE TITLE
dash support

### ISSUE THREAD

**Issue by westlinkin** [CarGuo/GSYVideoPlayer#2177]
Does this library support DASH? separate video and audio streams.

**Comment by CarGuo** [comment]
Not supported, you need to reconfiguration  and rebuild  "so"  to support

https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh

**Comment by dendrocyte** [comment]
@CarGuo 
I have noticed GsyVideoPlayer v7.1.8 support exoplayer v2.12.1.
Does this package support exoplayer-core only?
or else support exoplayer-dash, exoplayer-hls?

**Comment by CarGuo** [comment]
`ExoSourceManager.setExoMediaSourceInterceptListener`   & `getMediaSource` function can custom add `DashMediaSource` @dendrocyte

**Comment by dendrocyte** [comment]
@CarGuo Thanks! It is soooo impressive about entry point to support drm.
