### ISSUE TITLE
声音很模糊，听不清

### ISSUE THREAD

**Issue by lainT** [CarGuo/GSYVideoPlayer#2179]
## 问题描述：

正常播放视频，但是声音模糊，音量最大也听不到声音（视频源放在其他地方，是正常的）

## 问题机型/系统：

所有真机

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by lainT** [comment]
> ## 问题描述：
> 正常播放视频，但是声音模糊，音量最大也听不到声音（视频源放在其他地方，是正常的）
> 
> ## 问题机型/系统：
> 所有真机
> 
> ## GSY依赖版本
> 例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
请提供测试视频源

**Comment by lainT** [comment]
> 请提供测试视频源

https://files.eceibs20.com/files/ceibs/microlecture/59c07731e189b/59c07926b6239/1505786150/2/video/59c07923defbd.mp4?tdsourcetag=s_pctim_aiomsg

**Comment by CarGuo** [comment]
视频源的问题，测试了 mediacodec 内核和ijk的 ffmpeg 内核都这样
