### ISSUE TITLE
URL suggestion demo app

### ISSUE THREAD

**Issue by yo-1234** [CarGuo/GSYVideoPlayer#2183]
Very good. A full working exo apk. Easier than storing history of "enter URL" might be to store in text file in GSYVideo folder URLs of demo videos load at start. Thank you.

**Comment by yo-1234** [comment]
Maybe in (ext_)storage\GSYVideo\demo1_URL.5.0.1.txt :
http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4

Thank you.

**Comment by CarGuo** [comment]
Historical reasons lead to design so .
you can custom playManager and cacheManager to fix it
