### ISSUE TITLE
在横屏视频全屏和非全屏比例设置问题

### ISSUE THREAD

**Issue by uncleTan** [CarGuo/GSYVideoPlayer#2186]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```
能否区分非全屏和全屏下视频比例问题，比如在横屏视频未全屏的时候设置 GSYVideoType 为SCREEN_TYPE_FULL （全屏裁减显示），全屏的时候我想设置为SCREEN_TYPE_DEFAULT(默认比例显示），请问如何设置？

**Comment by CarGuo** [comment]
这个设置是全局的，你可以参看demo，利用自定义 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/view/CustomRenderView.java 去使用，自己加上是否全屏判断

**Comment by uncleTan** [comment]
好的

**Comment by uncleTan** [comment]
> 这个设置是全局的，你可以参看demo，利用自定义 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/view/CustomRenderView.java 去使用，自己加上是否全屏判断

OK
