### ISSUE TITLE
关于播放器里的布局控件命名

### ISSUE THREAD

**Issue by WalkingRoy** [CarGuo/GSYVideoPlayer#219]
你好：
希望能考虑在布局文件里的控件命名方式上，不是简单的写 start，back，cover 这些，而是再加上像 video_start，类似的前缀

**Comment by CarGuo** [comment]
如今改的话，对旧版本的兼容就不大好了

**Comment by mejealousy** [comment]
只修改父类的布局控件名，应该不会有什么影响吧
