### ISSUE TITLE
周期方法调用onVideoPause和onVideoResume的问题

### ISSUE THREAD

**Issue by centerzx** [CarGuo/GSYVideoPlayer#2191]
## 问题描述：

在使用demo过程中发现，根据页面周期方法调用onVideoPause和onVideoResume，能够顺利暂停，但是onVideoResume时只有声音在播，图像不动。

## 问题机型/系统：

测试是用的小米4s

## GSY依赖版本

最新 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

## Demo中的复现步骤

demo中简单播放->简单直接播放。按电源键息屏和亮屏就能复现。

**Comment by CarGuo** [comment]
如下图gif，测试没有复现问题，测试正常

![555](https://user-images.githubusercontent.com/10770362/63234402-b07e5480-c267-11e9-9d42-2be55a2a23f9.gif)

**Comment by Piscen** [comment]
遇到同样问题  机型vivo y67a ，作者直接close了是啥情况
