### ISSUE TITLE
采用边播边缓存的时候，网路慢的情况下，声画不同步

### ISSUE THREAD

**Issue by tinoPeng** [CarGuo/GSYVideoPlayer#2192]
采用边播边缓存的时候，网路慢的情况下，播的时候，声画不同步，就算已经播过一遍了，再播第二遍时候，还是会声画不同步，这是因为缓存的时候，导致丢帧了吗？请问该怎么设置一下呢

**Comment by CarGuo** [comment]
看历史 issue 和问题集锦，试试丢帧或者切换到exoplayer内核模式

**Comment by tinoPeng** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager::class.java) 设置成了这个模式，但是播放已经缓存后的视频时，有时候还是会出现，声音和画面不同步的问题。

**Comment by tinoPeng** [comment]
我们的app 是放在小米电视上进行使用的，

**Comment by CarGuo** [comment]
有测试url吗？我这边没什么办法复现

**Comment by tinoPeng** [comment]
http://image.haochengzhang.com/xcp3.mp4  这个是视频的url,  这个声画不同步的问题不是必发的，偶发性的有时候播着播着就不同步了，不知道是不是第一遍边播变缓存的时候，缓存后的视频源已经是不同步的了

**Comment by CarGuo** [comment]
我这边测试暂时没发现
