### ISSUE TITLE
集成播放器后，频繁切换播放视频会出现so库报错，日志如下，能帮忙分析吗，谢谢

### ISSUE THREAD

**Issue by ZJLeBron** [CarGuo/GSYVideoPlayer#2195]
#00 pc 000000000007a6c4 /system/lib64/libc.so (tgkill+8) [arm64-v8a]
--
2 #01 pc 0000000000077920 /system/lib64/libc.so (pthread_kill+64) [arm64-v8a]
3 #02 pc 000000000002538c /system/lib64/libc.so (raise+24) [arm64-v8a]
4 #03 pc 000000000001d24c /system/lib64/libc.so (abort+52) [arm64-v8a]
5 #04 pc 000000000045aee0 /system/lib64/libart.so (art::Runtime::Abort()+364) [arm64-v8a]
6 #05 pc 00000000000c3d88 /system/lib64/libart.so (art::LogMessage::~LogMessage()+1208) [arm64-v8a]
7 #06 pc 0000000000301448 /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1740) [arm64-v8a]
8 #07 pc 00000000003014c4 /system/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+116) [arm64-v8a]
9 #08 pc 00000000000e197c /system/lib64/libart.so (art::ArenaPool::FreeArenaChain(art::Arena*)+32) [arm64-v8a]
10 #09 pc 00000000000e1374 /system/lib64/libart.so (art::MemMapArena::MemMapArena(unsigned long, bool, char const*)+376) [arm64-v8a]
11 #10 pc 00000000000dea60 /system/lib64/libart.so (art::DexFile::GetIndexForMethodId(art::DexFile::MethodId const&) const+244) [arm64-v8a]
12 #11 pc 00000000000e41bc /system/lib64/libart.so (std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(bool)+268) [arm64-v8a]
13 #12 pc 00000000000e34b8 /system/lib64/libart.so (art::BitVector::NumSetBits() const+404) [arm64-v8a]
14 #13 pc 00000000000d86b0 /system/lib64/libart.so (art_quick_alloc_object_initialized_tlab_instrumented+64) [arm64-v8a]
15 #14 pc 00000000000610bc /data/app/com.mmia.wavespotandroid-1/lib/arm64/libijksdl.so (J4AC_tv_danmaku_ijk_media_player_IjkMediaPlayer__postEventFromNative+56) [arm64-v8a]
16 #15 pc 00000000000243d8 /data/app/com.mmia.wavespotandroid-1/lib/arm64/libijkplayer.so [arm64-v8a]
17 #16 pc 0000000000021644 /data/app/com.mmia.wavespotandroid-1/lib/arm64/libijkplayer.so [arm64-v8a]
18 #17 pc 0000000000012a1c /data/app/com.mmia.wavespotandroid-1/lib/arm64/libijksdl.so [arm64-v8a]
19 #18 pc 00000000000770f4 /system/lib64/libc.so (__pthread_start(void*)+204) [arm64-v8a]
20 #19 pc 000000000001e7d0 /system/lib64/libc.so (__start_thread+16) [arm64-v8a]

**Comment by CarGuo** [comment]
类似 https://github.com/CarGuo/GSYVideoPlayer/issues/2174 ，请确保release等情况下再播放
