### ISSUE TITLE
kotlin编译不通过

### ISSUE THREAD

**Issue by Achenglove** [CarGuo/GSYVideoPlayer#2197]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
自己的项目用kotlin开发，引进7.0.2版本之后编译不通过，找不到布局文件

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

## Demo中的复现步骤
自己的项目用kotlin开发，引进7.0.2版本之后编译不通过，找不到布局文件
![image](https://user-images.githubusercontent.com/26593441/63253095-c7429c80-c2a3-11e9-8a4a-0533b913e851.png)

**Comment by CarGuo** [comment]
androidx 7.x 版本之后

**Comment by Achenglove** [comment]
怎样处理呢？现在是Fragment找不到布局文件，但是Activity能正常使用。如果引进implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'项目就能通过编译，有处理方法吗？

**Comment by CarGuo** [comment]
Androidx 的兼容问题，你可以网上找找就知道为什么
