### ISSUE TITLE
请问m3u8缓存是一直缓存直到缓存完成吗

### ISSUE THREAD

**Issue by marscl** [CarGuo/GSYVideoPlayer#2198]
## 问题描述：

请问m3u8缓存是一直缓存直到缓存完成吗

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
如果你用的是 exoplayer 内核，使用exo缓存模式并且打开，那就是。
不然就不是。
