### ISSUE TITLE
在setShowFullAnimation为false的时候，点击全屏会闪一下再全屏

### ISSUE THREAD

**Issue by sugarkawhi** [CarGuo/GSYVideoPlayer#22]

**Comment by sugarkawhi** [comment]
ListNormalAdapter 中
        holder.gsyVideoPlayer.setRotateViewAuto(true);
        holder.gsyVideoPlayer.setLockLand(true);
        holder.gsyVideoPlayer.setPlayTag(TAG);
        holder.gsyVideoPlayer.setShowFullAnimation(**false**);
会闪一下

**Comment by CarGuo** [comment]
确实有这个问题😁，多谢提醒，我后面看看哈

**Comment by CarGuo** [comment]
update by 1.4.7
