### ISSUE TITLE
全屏无法播放

### ISSUE THREAD

**Issue by plmmanwu** [CarGuo/GSYVideoPlayer#220]
全屏无法播放，该设置的属性都设置好了，整个recyclerview就第一个条目全屏可播放，其他条目不行，请问是什么原因

**Comment by CarGuo** [comment]
不是很理解？demo中的哪类情况。

**Comment by plmmanwu** [comment]
demo  recycler 最后一条

**Comment by CarGuo** [comment]
试试最新demo
