### ISSUE TITLE
列表播放不能暂停

### ISSUE THREAD

**Issue by Gui-Ji** [CarGuo/GSYVideoPlayer#2200]
## 问题描述：

reyclerview自动播放，有多个viewType时，当视频已经移出屏幕，此时没有videoType触发自动播放，视频播放不会停止播放。我该怎么去监听当前播放的videotype已经移出屏幕

## 问题机型/系统：

真机 小米9 Android9.0

## GSY依赖版本

implementation  'com.shuyu:gsyVideoPlayer-java:6.0.3'

**Comment by CarGuo** [comment]
我觉得，这个不是项目的
Issues

**Comment by Gui-Ji** [comment]
是的，我想请教一下，recylerview自动播放中，ScrollCalculatorHelper能拿到自动播放的position，如果一屏当中有多个视频item，当我手动点击播放时则不知道播放的position（请问ScrollCalculatorHelper有办法判断到吗），所以我无法在ScrollListener判断当前播放position有没有移除屏幕。我看到demo中列表小窗口的点击是通过点击播放自己实现保存位置的

**Comment by Gui-Ji** [comment]
已经解决 谢谢

**Comment by shenjiabing** [comment]
> 已经解决 谢谢

怎么解决的？求告知

**Comment by Gui-Ji** [comment]
> > 已经解决 谢谢
> 
> 怎么解决的？求告知

在滚动完成的监听 监听播放位置getPlayPosition（）， 判断当前播放位置移出屏幕则暂停播放

if ((playPosition < firstVisibleItem || playPosition > lastVisibleItem)) {
   GSYVideoManager.onPause();}
