### ISSUE TITLE
FfPlay Plays Some URLs But IJKPlayer Cannot 

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2201]
Hello there. Ffplay can play some URLs but IJKPlayer can not. What could be the reason. Here are examples URLS with logs

**Example 1**

**URL**:  https://stream-5gw.1000eyes.de/cupertino/dusfcae.stream/playlist.m3u
**Log**: E/ProxyCache error: Error opening connection for https://stream-5gw.1000eyes.de/cupertino/dusfcae.stream/playlist.m3u with offset 0. Version: 7.0.1

**Example 2**

**URL**:  http://mmb.aa1.netvolante.jp:1025/mjpg/video.mjpg
**Log**: E/IJKMEDIA: http://127.0.0.1:34977/http%3A%2F%2Fmmb.aa1.netvolante.jp%3A1025%2Fmjpg%2Fvideo.mjpg: Invalid data found when processing input

What could be wrong? Do I need to decorate these kind of URLs in a special way ?? Thanks

**Comment by CarGuo** [comment]
default  "so" lib not support mjpg ：https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh

m3u8 not support proxyCache

**Comment by muzeasd** [comment]
You mean I will have to change this setting and then build again??

**Comment by CarGuo** [comment]
yes
