### ISSUE TITLE
Android sdk19机顶盒 使用MediaPlayer引擎+TextureView 播放有声音无画面

### ISSUE THREAD

**Issue by tianxiake** [CarGuo/GSYVideoPlayer#2202]
## 问题描述：

机顶盒版本是19,使用TextureView进行渲染的时候，如果切换到系统播放引擎会出现有声音无画面的情况，但是另外两个引擎播放是正常的。

## 问题机型/系统：

机顶盒 CM201  Android4.4

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.0.2'

## Demo中的复现步骤
切换到系统播放引擎播放就会出现这个问题

**Comment by CarGuo** [comment]
textureview可能是application的硬件layer加速没打开问题。

**Comment by tianxiake** [comment]
> textureview可能是application的硬件layer加速没打开问题。

开了硬件加速也不行。我自己写了Demo测试了下 在prepare之前把TextureView给构建了,然后在去使用MediaPlayer播放是可以的,现在GSY是在prepare之后去构建TextureView。这是我的测试代码：

 public class MediaplayerAndTextureActivity extends AppCompatActivity {

    private static final String TAG = "MediaplayerAndTextureActivity";
    @BindView(R.id.tv_text_ure)
    TextureView textureView;
    private Surface mySurface;
    private MediaPlayer mediaPlayer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_mediaplayer_and_texture);
        ButterKnife.bind(this);

        textureView.setSurfaceTextureListener(new TextureView.SurfaceTextureListener() {
            @Override
            public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
                HiLogger.i(TAG, "onSurfaceTextureAvailable");
                mySurface = new Surface(surface);
                play("http://vfx.mtime.cn/Video/2019/06/29/mp4/190629004821240734.mp4");
            }

            @Override
            public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {
                HiLogger.i(TAG, "onSurfaceTextureSizeChanged");
            }

            @Override
            public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
                return false;
            }

            @Override
            public void onSurfaceTextureUpdated(SurfaceTexture surface) {
                HiLogger.i(TAG, "onSurfaceTextureAvailable");
            }
        });


    }

    private void play(String url) {
        try {
            mediaPlayer = new MediaPlayer();
            mediaPlayer.setSurface(mySurface);
            mediaPlayer.setDataSource(url);
            mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
            mediaPlayer.prepareAsync();
            mediaPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
                @Override
                public void onPrepared(MediaPlayer mp) {
                    HiLogger.i(TAG, "onPrepared");
                    mediaPlayer.start();
                }
            });
        } catch (Exception e) {
            HiLogger.e(TAG, "", e);
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
    }
}

**Comment by tianxiake** [comment]
> textureview可能是application的硬件layer加速没打开问题。
