### ISSUE TITLE
您好，ListView如何实现自动播放，弄几天了，麻烦！

### ISSUE THREAD

**Issue by yyhLum** [CarGuo/GSYVideoPlayer#2203]
## 问题描述：

您好，ListView如何实现自动播放？在PlayActivity里面可以自动播放，加上一个简单的ListView+BaseAdapter后，一直被封面挡着，里面在播放。我的想法要么隐藏封面、要么获取播放按钮后面的操作，试了几天没实现，麻烦！

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

**Comment by CarGuo** [comment]
自动播放demo有，请自行参考，类似需求非库issue
