### ISSUE TITLE
重力感应问题 屏幕旋转问题

### ISSUE THREAD

**Issue by CatyVon** [CarGuo/GSYVideoPlayer#2204]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

使用 模式二 SimpleDetailActivityMode2 根据demo将自己的项目进行了调整  实现了小屏播放  以及重力感应旋转屏幕  但是目前重力感应貌似仅支持逆时针旋转  并且播放页面会正常旋转  如果顺时针旋转  播放页面就会上下颠倒 

## 问题机型/系统：

真机 三星S10 小米8

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'

## Demo中的复现步骤

无

问题代码：(如果有)
无

## 问题log（如果有）
无

![image](https://user-images.githubusercontent.com/34530416/63561660-5f36d380-c58d-11e9-8164-aac2ec621439.png)
![image](https://user-images.githubusercontent.com/34530416/63561666-61992d80-c58d-11e9-857d-e4d9531c470a.png)

**Comment by CarGuo** [comment]
如下动图，测试正常：

![444444](https://user-images.githubusercontent.com/10770362/63756052-4b230700-c8ea-11e9-92a4-c02d6942cb95.gif)

**Comment by CatyVon** [comment]
难道是6.0.1太老么

**Comment by CarGuo** [comment]
你可以看看版本更新文件，那里有说明各个版本更新了什么。
这一块貌似没怎么更新过
