### ISSUE TITLE
某些avi格式的在线视频播放完后不能自动停止

### ISSUE THREAD

**Issue by mxmhao** [CarGuo/GSYVideoPlayer#2205]
## 问题描述：

某些avi格式的在线视频播放完后不能自动停止，而且进度时间一直在递增

## 问题机型/系统：

所有机型

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.0.2'
    implementation 'com.shuyu:gsyVideoPlayer-arm64:7.0.2'

## Demo中的复现步骤
使用的： 模式二 SimpleDetailActivityMode2

## 问题log
```
W/IJKMEDIA: HTTP error 416 Requested Range Not Satisfiable
E/IJKMEDIA: Header missing
E/IJKMEDIA: header damaged
```

**Comment by CarGuo** [comment]
请提供测试url

**Comment by mxmhao** [comment]
没法提供url，只能提供一个视频，请放到您的私人服务器上测试
链接: https://pan.baidu.com/s/1PUtmh7v9nPuTQ0rNnXH_Mw 提取码: 57yb

**Comment by mxmhao** [comment]
补充一下，是用http链接播放

**Comment by CarGuo** [comment]
如果需要 http 播放测试的，请提供在线测试url
