### ISSUE TITLE
StandardGSYVideoPlayer固定高度，使用SCREEN_TYPE_DEFAULT模式视频显示变形

### ISSUE THREAD

**Issue by SongJeen** [CarGuo/GSYVideoPlayer#2206]
## 问题描述：

请问怎么在StandardGSYVideoPlayer固定高度时，合适的填充满视频画面？

## 问题机型/系统：

真机 安卓手机

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'  和版本无关

## Demo中的复现步骤

不知道demo中有没有固定高度的显示。

问题代码：(如果有)
```
      <com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
                    android:id="@+id/scv_player"
                    android:layout_width="match_parent"
                    android:layout_height="500dp"/>
```

## 问题log（如果有）

```
无
```

**Comment by CarGuo** [comment]
绘制逻辑：

https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/MeasureHelper.java

https://github.com/CarGuo/GSYVideoPlayer/tree/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/render/view


可自定义参考

https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/view/CustomRenderView.java

**Comment by SongJeen** [comment]
是使用SCREEN_TYPE_FULL模式变形。

**Comment by CarGuo** [comment]
我这边测试正常
