### ISSUE TITLE
自定义组件获取不到

### ISSUE THREAD

**Issue by yyhLum** [CarGuo/GSYVideoPlayer#2207]
## 问题描述：

您好，getLayoutId自定义一个button组件，获取不到点击事件是怎么回事？

**Comment by CarGuo** [comment]
不理解

**Comment by yyhLum** [comment]
我继承StandardGSYVideoPlayer类，重写getLayoutId方法， 引用了自己定义的布局，这个自定义布局我就在原有的基础上，加了一个button，但是这个button我获取不到点击事件

**Comment by CarGuo** [comment]
请参考demo，demo中有类似的，如SampleControlVideo
