### ISSUE TITLE
ijk内核播放视频声音画面不同步

### ISSUE THREAD

**Issue by itzhouyansun** [CarGuo/GSYVideoPlayer#2209]
另外用系统内核mediaplayer播放某些视频。播放到某一个固定节点会出错，但是手动拖拽跳过此节点不会出错，错误code（1,-1004）
（下面视频链接大概在四分之三进度的时候会播放失败）：http://maoyan.meituan.net/movie/videos/854x480650986faadaa4c2d8c5d7fd59961e169.mp4

**Comment by CarGuo** [comment]
如果 mediaplayer 、exoplayer 、ijkplayer都有问题，说明视频留本身兼容有问题，某个节点出错可能某个节点的帧序列存在错乱之类的。

**Comment by itzhouyansun** [comment]
exoplayer播放没有问题，只是播放的时候cpu占用过高，我们是车联网车机项目，运行环境板子设备配置较低，尝试硬解码也一样，请问在播放时应有何优化

**Comment by CarGuo** [comment]
一样的，默认 ffmpeg 下的软解能力更吃 cpu 性能
