### ISSUE TITLE
CoverVideo  的 ENPlayView 点击监听播放问题

### ISSUE THREAD

**Issue by xyZangGit** [CarGuo/GSYVideoPlayer#2212]
对ENPlayView start = findViewById(R.id.start);
        start.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                LogUtils.i("点击了播放按钮");
//                GSYVideoManager.onPause();
                GSYVideoManager.onResume();

            }
        });

播放按钮进行监听，进行一系列事件之后，在播放
然后 怎么自己控制播放，没找到控制播放的 代码  ，
尝试了很多播放的方法也不行

**Comment by CarGuo** [comment]
不理解你的意思

**Comment by JeahWan** [comment]
@xyZangGit  start控件 performclick 就好了鸭
