### ISSUE TITLE
本地视频播放

### ISSUE THREAD

**Issue by yeqinfu** [CarGuo/GSYVideoPlayer#2213]
## 问题描述：

本地文件路径播放，那个进度条一直是0，setGSYVideoProgressListener 回调secProgress一直是返回零，是要设置什么吗？

**Comment by CarGuo** [comment]
本地文件没有缓冲进度条

**Comment by yeqinfu** [comment]
> 本地文件没有缓冲进度条

那请问我怎么看到播放进度？

**Comment by CarGuo** [comment]
正常进度条还是有的啊，只是没有缓冲进度条。

**Comment by yeqinfu** [comment]
> 正常进度条还是有的啊，只是没有缓冲进度条。

是这样，本地视频比如十秒，我点击播放，进度一直停在0，等到播放十秒后突然就变成进度到底了。demo我也试过。那个输入URL的demo，输入本地视频路径。也是这个效果

**Comment by CarGuo** [comment]
那就是视频兼容问题，比如你视频的编码压缩导致关键帧等丢失问题，可以尝试切换到exoplayer内核试试。

**Comment by yeqinfu** [comment]
> 那就是视频兼容问题，比如你视频的编码压缩导致关键帧等丢失问题，可以尝试切换到exoplayer内核试试。

果然是这个问题。 谢谢！
