### ISSUE TITLE
自定义增加了下一集按钮，但全屏状态下切换黑屏，有声音无画面

### ISSUE THREAD

**Issue by JeahWan** [CarGuo/GSYVideoPlayer#2218]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

自定义实现了下一集功能，但是在全屏状态下通过点击按钮的监听调用了startPlayLogic方法，有声音，无画面

## 问题机型/系统：

任意

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

**Comment by CarGuo** [comment]
player.getCurrentPlayer. startPlayLogic();

**Comment by JeahWan** [comment]
@CarGuo 感谢！~
