### ISSUE TITLE
视频旋转错乱

### ISSUE THREAD

**Issue by zhangqilu** [CarGuo/GSYVideoPlayer#2219]
问题描述：

横向旋转手机，等待视频播放完成，点击播放按键，继续播放。
竖向旋转手机，播放正常，横向旋转手机，播放界面异常。

## 问题机型/系统：

例全部机型

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的ListVideoActivity 
/**
* 列表时是否需要支持重力旋转
*
* @return 返回true为支持列表重力全屏
*/
public boolean getListNeedAutoLand() {
return true;
}

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/commit/5f7da07245a65d4f5e1523d9c7ab010513aab058

**Comment by zhangqilu** [comment]
@CarGuo  还是不行，你多旋转几次

**Comment by zhangqilu** [comment]
复现步骤
横向旋转手机，等待视频播放完成，点击播放按键，继续播放。
竖向旋转手机，播放正常，横向旋转手机，播放正常有时正常  
 竖向旋转手机，播放界面异常。
