### ISSUE TITLE
MP4格式视频播放有声音没画面

### ISSUE THREAD

**Issue by yueshao6800** [CarGuo/GSYVideoPlayer#222]
播放MP4格式的视频，遇到的问题是
小米手机5：在线视频（有声音无画面），本地视频（有声音无画面）；
魅族note5:   在线视频（有声音无画面），本地视频（有声音有画面）；
没测其他更多手机

**Comment by yueshao6800** [comment]
用你的demo播放也是同样的问题，

**Comment by CarGuo** [comment]
视频的编码格式是？？

**Comment by yueshao6800** [comment]
编码格式是MP4格式，我发现似乎是码率的问题，视频的码率到了2700kbps左右的话，就放不出来，我用用视频转换工具把码率调到2300kbps左右就可以了，视频分辨率是720*1280的

**Comment by CarGuo** [comment]
不是这个格式，是视频的编码，你转换之后视频编码可能是变了，原本的视频编码是什么类型？因为目前的so支持的是 H264/H265/H263 如果是MPEG的，需要重新编译so

**Comment by yueshao6800** [comment]
用魔影工厂转换的时候，这个格式我选择的是h.264/AVC,应该就是H264格式的

**Comment by feer921** [comment]
Lenevo android 4.4.2播放有声音，没画面

**Comment by feer921** [comment]
直接使用的是 Demo程序

**Comment by CarGuo** [comment]
h264是支持的，如果是mpeg就需要重新编译so支持了

**Comment by zyaman** [comment]
怎么重新编译so啊

**Comment by CarGuo** [comment]
github首页有编译so的教程，你需要做的是选择需要的module.sh，然后补上你需要的格式
