### ISSUE TITLE
多播的问题

### ISSUE THREAD

**Issue by Xujun770366270** [CarGuo/GSYVideoPlayer#2220]
大哥你好:我想请教的问题问题是 我们做类似监控室的9画面的需求,请问这种情况下如何实现多个画面同时播放

**Comment by CarGuo** [comment]
Demo里有多个内核实现同步播放，不过这样对流量和实时性要求比较高。
要不就是服务端给你配置好参数，你一个流可配置画面。

**Comment by Xujun770366270** [comment]
流量实时性还好,我们是在局域网,
目前用了你的Demo ,当播放其中一个的时候,其它的就会暂停播放,这个应该是因为你做了全局单列的一个原因,  
请问一下,你说的多个内核的Demo是哪一个, ListMuiltiVideoAcitivity ?  ,这个我看了,好像不能用

**Comment by Xujun770366270** [comment]
大哥,项目中我找到了,你说的是 MultiSampleVideo这个类谢谢

**Comment by Xujun770366270** [comment]
用了你Demo中的MultiSampleVideo 多播控件,但是在内存和CPU消耗得很高,是我还需要设置什么么设置么?
下面是两个内存和Cpu 使用情况
1.在使用EmptyControlVideo 情况下的cpu使用情况 cpu: 3%    内存:43M

![QQ图片20190831113334](https://user-images.githubusercontent.com/13106539/64058804-478dc980-cbe3-11e9-8ac3-a0aded17ceb0.jpg)

2.在使用EmptyControlVideo 情况下的cpu使用情况 cpu: 23%    内存:76M
![8](https://user-images.githubusercontent.com/13106539/64058806-507e9b00-cbe3-11e9-85ae-0f93e8b1714e.jpg)

在播放器设置方面,我也开启了硬件解码,关闭软件,关闭缓存

        List<VideoOptionModel> list = new ArrayList<>();
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
        list.add(videoOptionModel);
        //硬解码：1、打开，0、关闭
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
        list.add(videoOptionModel);
        //软解码：1、打开，0、关闭
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "videotoolbox", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
        list.add(videoOptionModel);
        // 通过立即清理数据包来减少等待时长
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
        list.add(videoOptionModel);
        //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);

        //============================降低延时================================
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "http-detect-range-support", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "skip_loop_filter", 48);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "skip_loop_filter", 8);
        list.add(videoOptionModel);

    恳请大哥指导

**Comment by CarGuo** [comment]
Demo中的多播，是开了多个内核各自加载渲染，肯定占用内存😂

**Comment by Xujun770366270** [comment]
大哥你说的意思我不是很懂
目前的情况是,我都是只播放一个视频,没有同时播放多个视屏播放 ,用 EmptyControlVideo  和 MultiSampleVideo  在播放同一个视屏源的情况下对比 ,他们 的内存和CPU对比, 两者相差很大, 

我在测试的时候,发现,EmptyControlVideo  在不开硬件解码的时候 和 MultiSampleVideo 的cpu 内存使用情况差不多, 是不是MultiSampleVideo  的播放方式是不是不支持硬件解码

**Comment by Xujun770366270** [comment]
大哥,你好,目前原因找到了, 是因为在软解码的情况下,cpu和内存都消耗得比较高,
使用了MultiSampleVideo 之后,使用GSYVideoManager的设置是失效的,是要CustomManager去通过player的key拿到对应的CustomManager 然后再去设置才生效,
但是发现cpu抖动还是很厉害,本来正常情况下是 20%,但是经常会出现百分之40的情况,大哥对这种情况有没有什么建议?

**Comment by CarGuo** [comment]
这个 cpu 抖动应该是属于 ffmpeg 造成，具体怎么导致的暂时我也不好定位。

**Comment by Xujun770366270** [comment]
好的,谢谢大哥

**Comment by guodongAndroid** [comment]
@Xujun770366270 老哥，请问视频监控9宫格画面做的怎么样？有Demo可以发一份么？

**Comment by pie-tk** [comment]
@Xujun770366270 老哥，问一下，你的视频数据是什么形式的，怎么给解码库的？
