### ISSUE TITLE
exoplyer 缓存最大 和最小时间设置 能不能可以设置

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#2222]
exoplyer 缓存在这里可以设置，能不能把参数改为可以设置的，或者我怎么自定义可一个更改呢
 DefaultLoadControl loadControl = new DefaultLoadControl();

--------------老大的源码 ------------------

 
protected void prepareAsyncInternal() {
        new Handler(Looper.getMainLooper()).post(
                new Runnable() {
                    @Override
                    public void run() {
                        mTrackSelector = new DefaultTrackSelector();
                        mEventLogger = new EventLogger(mTrackSelector);
                        boolean preferExtensionDecoders = true;
                        boolean useExtensionRenderers = true;//是否开启扩展
                        @DefaultRenderersFactory.ExtensionRendererMode int extensionRendererMode = useExtensionRenderers
                                ? (preferExtensionDecoders ? DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER
                                : DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON)
                                : DefaultRenderersFactory.EXTENSION_RENDERER_MODE_OFF;

                        rendererFactory = new DefaultRenderersFactory(mAppContext, extensionRendererMode);
                        DefaultLoadControl loadControl = new DefaultLoadControl();
                        mInternalPlayer = ExoPlayerFactory.newSimpleInstance(mAppContext, rendererFactory, mTrackSelector, loadControl, null, Looper.getMainLooper());
                        mInternalPlayer.addListener(IjkExo2MediaPlayer.this);
                        mInternalPlayer.addAnalyticsListener(IjkExo2MediaPlayer.this);
                        mInternalPlayer.addListener(mEventLogger);
                        if (mSpeedPlaybackParameters != null) {
                            mInternalPlayer.setPlaybackParameters(mSpeedPlaybackParameters);
                        }
                        if (mSurface != null)
                            mInternalPlayer.setVideoSurface(mSurface);

                        mInternalPlayer.prepare(mMediaSource);
                        mInternalPlayer.setPlayWhenReady(false);
                    }
                }
        );
    }

**Comment by yang0000meng** [comment]
自定义 Exo2PlayerManager IjkExo2MediaPlayer ExoPlayerCacheManager 小修改下实现了，不过升级麻烦了

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer#7102019-09-01 刚好更新了，你可能需要这个

```
GSYVideoManager
    .instance()
    .setPlayerInitSuccessListener(new IPlayerInitSuccessListener() {
        ///播放器初始化成果回调，可用于播放前的自定义设置
        @Override
        public void onPlayerInitSuccess(IMediaPlayer player, GSYModel model) {
            if (player instanceof IjkExo2MediaPlayer) {
                ((IjkExo2MediaPlayer) player).setTrackSelector(new DefaultTrackSelector());
                ((IjkExo2MediaPlayer) player).setLoadControl(new DefaultLoadControl());
            }
        }
    });
```

**Comment by yang0000meng** [comment]
正好升级下，~_~
