### ISSUE TITLE
有没有正在缓冲的回调函数

### ISSUE THREAD

**Issue by qq61821191** [CarGuo/GSYVideoPlayer#2223]
## 问题描述：

文档查了很久，想实现缓冲中，更改loading布局在下方添加TextView显示当前网速。
所以问下各位是否有缓冲中的回调函数，还有目前我在进度回调函数中 getNetSpeed获取当前网速，日志中显示都是0kb。我在全局application中 
PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
配置了EXO。
主要问题
1：缓冲中的回调函数
2：获取网速是0kb的问题

**Comment by qq61821191** [comment]
发完个issue之后，突然开窍了。
1.自定义UI 在Loading的view下面加个TextView用于显示网速
2.重写获取实时进度的接口，设置网速文本。
3.重写changeUiToPlayingBufferingShow方法 这个是缓冲的回调函数，在这里设置网速TextView可见
4.重写changeUiToPlayingShow方法 这个是准备要播放的回调，在这里设置网速的Text View不可见

然后还发现问题，就是网速为何一直经常的是0kb？？

**Comment by qq61821191** [comment]
private Handler mHandler=new Handler(){
        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            switch (msg.what){
                case NET_SPEED:
                    tvNetSpeed.setText((String)msg.obj);
                    break;
            }

        }
    };

    @Override
    protected void setTextAndProgress(int secProgress) {
        super.setTextAndProgress(secProgress);
        String netSpeed=getNetSpeedText();
        Message msg = Message.obtain();
        msg.what = NET_SPEED;
        msg.obj = netSpeed;
        mHandler.sendMessage(msg);
        Logger.d("网速哦："+netSpeed);
    }


在setTextAndProgress方法中getNetSpeedText();发现基本都可以返回正常的网速，但是更新UI的话，日志显示卡住了，UI更新了卡住时的网速，等缓冲完毕播放了，网速才会继续返回

**Comment by CarGuo** [comment]
不是很理解你现在的问题，我这边测试没什么问题···
