### ISSUE TITLE
视频录制完后，不能播放

### ISSUE THREAD

**Issue by Jack-Xiao** [CarGuo/GSYVideoPlayer#2225]
## 问题描述：
视频录制 MediaCodec 录完后，立即播放无法播放，播放器使用的是StandardGSYVideoPlayer。
随后点击播发器，就可以播放了。

## 问题机型/系统：
真机 红米Note7 Pro

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

## Demo中的复现步骤
1、视频录制 MediaCodec
2、录制完成，立即播放本地录制的视频，但无法播放（播放器使用的是StandardGSYVideoPlayer）。
3、但点击播发器，就可以播放了

**Comment by CarGuo** [comment]
视频的容器协议，视频编码和音频编码是什么

**Comment by Jack-Xiao** [comment]
D/IJKMEDIA: Opening '/storage/emulated/0/bibi/video/1567395399903.mp4' for reading
    Setting default whitelist 'file,crypto'
V/IJKMEDIA: Probing mov,mp4,m4a,3gp,3g2,mj2 score:100 size:2048
D/IJKMEDIA: Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
V/IJKMEDIA: type:'ftyp' parent:'root' sz: 24 8 1328637
D/IJKMEDIA: ISO: File Type Major Brand: mp42
V/IJKMEDIA: type:'free' parent:'root' sz: 3191 32 1328637
    type:'mdat' parent:'root' sz: 1061109567 3223 1328637
    type:'ftyp' parent:'root' sz: 24 8 1328637
D/IJKMEDIA: ISO: File Type Major Brand: mp42
V/IJKMEDIA: type:'free' parent:'root' sz: 3191 32 1328637
    type:'mdat' parent:'root' sz: 1061109567 3223 1328637
**E/IJKMEDIA: moov atom not found**
D/IJKMEDIA: Statistics: 65536 bytes read, 3 seeks
**E/IJKMEDIA: /storage/emulated/0/bibi/video/1567395399903.mp4: Invalid data found when processing input**
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [8932]
I/IJKMEDIA: SDL_RunThread: [8931] ff_vout
D/IJKMEDIA: FFP_MSG_FLUSH:
D/IJKMEDIA: FFP_MSG_ERROR: 0
**E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)**

这是其中第一次去立即播放的日志。

**Comment by Jack-Xiao** [comment]
录制完成。释放VideoMediaCodec、AudioMediaCodec。 然后回调播放刚录制的本地视频。

**Comment by Jack-Xiao** [comment]
视频是.mp4 封装格式。 音频aac， 视频H264。
问题是
1）录制完立即播放，基本播放不了。
2）点击之后就可以播放了。

**Comment by CarGuo** [comment]
这个格式应该是没问题，你这个场景我没办法复现，播放本地你需要 file:// + 本地路径
