### ISSUE TITLE
compileSdkVersion  version 问题

### ISSUE THREAD

**Issue by Xujun770366270** [CarGuo/GSYVideoPlayer#2228]
如果导入你的GSYVideoPlayer 是需要 compileSdkVersion 28 否则会报如下错误
![image](https://user-images.githubusercontent.com/13106539/64100077-6932b080-cd9d-11e9-8453-b6f08918c4ff.png)

现在我的问题是想用到  compileSdkVersion 26  请问大哥,是否有办法解决

**Comment by CarGuo** [comment]
不行，新版本需要28和 Androidx
