### ISSUE TITLE
请问是如何解决的啊？我也是遇到这个问题。一个activity放了两个MultiSampleVideo，想同时播放两路rtsp直播流，但是其中一个播放另一个就会暂停~求告知啊~~~感谢

### ISSUE THREAD

**Issue by vip404** [CarGuo/GSYVideoPlayer#2231]
请问是如何解决的啊？我也是遇到这个问题。一个activity放了两个MultiSampleVideo，想同时播放两路rtsp直播流，但是其中一个播放另一个就会暂停~求告知啊~~~感谢

_Originally posted by @Benson189 in https://github.com/CarGuo/GSYVideoPlayer/issues/1833#issuecomment-484819672_

**Comment by CarGuo** [comment]
如果是重定向的话，请看issue 置顶的那个。
然后设置 dns_clear

**Comment by Benson189** [comment]
这个问题我后来解决了
两个播放器设置不同的tag就能同时播放了
gsyVideoPlayer.setPlayTag()
貌似是这么一个方法

**Comment by vip404** [comment]
谢谢，现在可以同时播放了，但是播放rtsp视频流的时候会报错IJKMEDIA: method PAUSE failed: 551 Option not supported
单播放器StandardGSYVideoPlayer不报错。您遇到过吗？

**Comment by Benson189** [comment]
没有诶，我的两个都是rtsp流没有这样的问题

**Comment by CarGuo** [comment]
如果是重定向的话，请看issue 置顶的那个。
然后设置 dns_clear
