### ISSUE TITLE
more than one library with package name 'androidx.vectordrawable'

### ISSUE THREAD

**Issue by Enigma-Guo** [CarGuo/GSYVideoPlayer#2232]
more than one library with package name 'androidx.vectordrawable'  集成6.0.3以上会报错，怎么解决？

**Comment by CarGuo** [comment]
6.0.3 应该是没有 androidx

**Comment by Enigma-Guo** [comment]
最新版本好像最低只支持minSdkVersion 19，7.1.0支持了沉浸式  想集成一下 高版本搞上去跟本地各种不兼容啊

**Comment by CarGuo** [comment]
你可以 fork 之后修改源码
