### ISSUE TITLE
不开启硬件加速不能播放

### ISSUE THREAD

**Issue by Xujun770366270** [CarGuo/GSYVideoPlayer#2234]
今天测试发现,必须开启硬件加速,否则无法播放
        android:hardwareAccelerated="true" ,默认是开启,但是在实际使用中, 硬件加速会对内存有很大的消耗, 我们项目中做了测试, 开启硬件加速120M 和不开启硬件加速 200M, 相差60多M 请问一下作者大哥如何 避免这个问题
     我们是做智能硬件的,所有内存消耗比较大

**Comment by CarGuo** [comment]
设置成surfaceview模式

**Comment by Xujun770366270** [comment]
好的,谢谢大哥

**Comment by Xujun770366270** [comment]
> 设置成surfaceview模式

谢谢大哥,亲测有用
