### ISSUE TITLE
音频状态下设置封面、小屏封面正常 全屏封面播放完毕后消失并且快进后退失效

### ISSUE THREAD

**Issue by 17679416879** [CarGuo/GSYVideoPlayer#2235]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

全屏状态下播放音频完成后黑屏没有封面了、点击重新播放也没有封面产生并且顶部的状态栏消失了、屏幕快进后退失效

## 问题机型/系统：

任何机型

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:5.0.1'

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
全屏默认是没有封面的我记得，代码里
