### ISSUE TITLE
内网地址无法播放

### ISSUE THREAD

**Issue by cuijiao1993** [CarGuo/GSYVideoPlayer#2240]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：内网m3u8、mp4视频地址无法播放，rtsp、rtmp在内网能播放，在外网所有格式的视频流都能播放，想请问下是库里面是否有什么需要连接互联网进行验证的？我这边是纯脱机使用。

XXXX发生了这样的问题！

## 问题机型/系统：

Android电视盒子 Android4.4.4系统

## GSY依赖版本

   api 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    api 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
    
    api 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
没什么特殊的

**Comment by cuijiao1993** [comment]
好的，谢谢
