### ISSUE TITLE
参照博主的DetailExoListPlayer写的可以实现无缝下一集，标题不能改变

### ISSUE THREAD

**Issue by alsguo** [CarGuo/GSYVideoPlayer#2247]
参照博主的DetailExoListPlayer写的可以实现无缝下一集，标题不能跟随改变，一直显示第一个视频的标题。
试了博主Demo中DetailExoListPlayer，也是这个问题，一直显示第一个视频的标题
@CarGuo

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/commit/97d3ac769ca30ab54fabd7f7e6a6ed82782f7910
