### ISSUE TITLE
如何同时设置不同的显示比例？

### ISSUE THREAD

**Issue by kennir** [CarGuo/GSYVideoPlayer#2248]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我有两个fragment，一个想显示default的视频比例，一个想显示full的视频比例，但是GSYVideoType是静态变量无法同时设置不同的值

## 问题机型/系统：

所有设备

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'`

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
GSYVideoType 默认是全局的，所以你只能全局生效，在播放前动态设置。
或者你集成后自定义 render ，可参考demo https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/view/CustomRenderView.java
