### ISSUE TITLE
全屏切换黑屏

### ISSUE THREAD

**Issue by 15281046619** [CarGuo/GSYVideoPlayer#2249]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

使用系统模式，全屏和非全屏切换过程每次会出现黑屏一段时间。偶尔出现一直黑屏

## 问题机型/系统：

例如 真机 小米8 Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
demo 哪个页面会复现
