### ISSUE TITLE
在 showFullAnimation() 中 post 一个执行 resolveFullVideoShow() 的 Runnable 时，runnable 并没有得到执行

### ISSUE THREAD

**Issue by thirtyyuan** [CarGuo/GSYVideoPlayer#2252]
## 问题描述

当我在 `showFullAnimation()` 中 post 一个执行`resolveFullVideoShow()` 的 Runnable 时，发现 runnable 并没有得到执行。

## 问题机型/系统

OnePlus 5T & etc. Android 9 / 8.

## GSY 依赖版本

`com.shuyu:GSYVideoPlayer:6.0.2`

## Demo 中的复现步骤
尽可能快的点击，使得播放器不停地、尽可能快地放大缩小。
复现时是在列表中、Activity中（单个播放器）都可复现，自定义 Player 继承自 NormalGSYVideoPlayer。Demo 难于复现，项目中也是要故意尝试很多次才会出现一次，但出现一次时问题就比较严重，只能重启 App。

问题代码：

![问题代码](https://user-images.githubusercontent.com/16081968/64870407-cd932100-d675-11e9-8f96-50dcc5139819.png)

## 问题 Log
此段代码片段在 `startWindowFullscreen()` 方法中，注意两个 Log：

正常情况
``` log
startWindowFullscreen() addView() showFullAnimation=true
startWindowFullscreen() resolveFullVideoShow() showFullAnimation=true
```

异常情况（post 中的 runnable 不被执行）
``` log
startWindowFullscreen() addView() showFullAnimation=true
```

[完整日志链接](https://github.com/CarGuo/GSYVideoPlayer/files/3610526/video_error.log)
[自定义 Player](https://github.com/CarGuo/GSYVideoPlayer/files/3610565/FeedVideoPlayer.txt)

## 具体表现
列表中发生该问题的表现：
1. 图中区域 【1】：本该全屏居中播放的视频，靠在屏幕左上角播放；
2. 图中区域【2】：顶部 statusBar 隐藏，底部本该有的 tabBar 被 系统的 navigationBar 遮住。

![列表中发生该问题的表现图](https://user-images.githubusercontent.com/16081968/64872166-46e04300-d679-11e9-968b-43c9559cc12d.jpg)

Activity 中发生该问题的表现：
1. 整个视频遮住部分屏幕区域（顶部 statusBar，底部系统的 navigationBar 均隐藏）
![Activity 中发生该问题的表现图](https://user-images.githubusercontent.com/16081968/64873656-21086d80-d67c-11e9-9d2a-cc54c475515c.jpg)

**Comment by CarGuo** [comment]
是的，这个场景确实存在问题，下个版本将修正这个问题。

**Comment by thirtyyuan** [comment]
问题所在，view 在 attachInfo 为空时，如果 view 已经 attached，会把 runnable 对象丢到 runQueue 中执行（否则不会执行）。

View 的 post() 方法源码如下：
![View 的 post() 方法源码](https://user-images.githubusercontent.com/16081968/64874922-8eb59900-d67e-11e9-8325-19f93f6736f1.png)

在先前 Log 信息基础上，再在 post 前打印当前 view 的 attach 信息，得到如下结果：
异常时的日志：
``` log
startWindowFullscreen() addView() showFullAnimation=true
startWindowFullscreen() isAttached=false
```
正确执行时的日志：
``` log
startWindowFullscreen() addView() showFullAnimation=true
startWindowFullscreen() isAttached=true
startWindowFullscreen() resolveFullVideoShow() showFullAnimation=true
```
正在尝试在 `startWindowFullscreen()` 开始时，判断 `isAttachedToWindow() == false` 就返回 null。

另外想和各位探讨下：
1. 日常使用什么替代 `view.post()` 比较好？（已经进过检验的方案）

**Comment by thirtyyuan** [comment]
假期里还能及时回复，感受到作者的用心👏另外请问是否有修复此问题的方案呢？

**Comment by CarGuo** [comment]
其实这个问题在这周四修复一个issue 2244的时候就发现了，这个主要是在于全屏控件是动态add到rootview上的，所以在退出全屏的时候，会有可能全屏view已经reomve了，而这边还在延时的问题，还有中间view导致的一些错位问题，你可以看看上面那个issue，这个这几天看看怎么修复

**Comment by thirtyyuan** [comment]
好嘞，我晚点看看，如果需要，可以先 close 了😁
--
Sent from myMail for Android Saturday, 14 September 2019, 00:20AM +08:00 from Shuyu Guo  notifications@github.com :
