### ISSUE TITLE
如何宽度撑满，高度自适应

### ISSUE THREAD

**Issue by kennir** [CarGuo/GSYVideoPlayer#2253]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我想让视频宽度撑满，高度自适应（或者截短），我已经自定义了CustomRenderView, 但是不清楚怎么设置 MeasureHelper 让他达到这个效果？

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
这个就是自己按比例计算调整布局啊

**Comment by kennir** [comment]
我把布局改成这样

```
    <FrameLayout
        android:id="@+id/surface_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/videoBackgroundColor"
        android:gravity="center"
        android:layout_centerVertical="true" />
```

然后自定义了TextureView, 设置MeasureHelper的类型为SCREEN_MATCH_FULL
```
measureHelper.setAspectRatio(GSYVideoType.SCREEN_MATCH_FULL)
```

但是这时候视频的高度没有比例而是被拉伸了

**Comment by CarGuo** [comment]
如果你自定义，你可以打印计算逻辑啊，实现自己的 measureHelper

**Comment by kennir** [comment]
理解了，谢谢

**Comment by SiberiaDante** [comment]
@kennir 请问下动态设置高度的方法：
`ViewGroup.LayoutParams ivPostLayoutParams = mVideoPlayer.getLayoutParams();
ivPostLayoutParams.height = ScreenUtils.getScreenWidth() * bitmap.getHeight() / bitmap.getWidth();
ivPostLayoutParams.width = ScreenUtils.getScreenWidth();
mVideoPlayer.setLayoutParams(ivPostLayoutParams);`
只是这种方式不生效
