### ISSUE TITLE
最新版本如何播放RTSP直播流

### ISSUE THREAD

**Issue by 547555857** [CarGuo/GSYVideoPlayer#2256]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

最新版本如何播放RTSP直播流

## 问题机型/系统：

无新人

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'`

## Demo中的复现步骤
我按照demo给的代码播放rtsp 播放失败

问题代码：(如果有)

IJKMEDIA: rtsp://ajj:12345678@218.21.217.122:65523/h264/ch40/sub/av_stream: Protocol not found

**Comment by CarGuo** [comment]
需要切换到 ex_so 依赖，看问题集锦
