### ISSUE TITLE
Android 5.1系统，视频播放中压后台，再切换到前台，画面卡住不动，有声音和进度条

### ISSUE THREAD

**Issue by yueshao6800** [CarGuo/GSYVideoPlayer#2258]
Android 5.1系统，视频播放中压后台，再切换到前台，画面卡住不动，有声音和进度条

 问题机型/系统：

 真机 魅蓝note2 Android5.1
 模拟器 Android 5.1

 GSY依赖版本

7.1.0

Demo必先

**Comment by CarGuo** [comment]
我这边测试无法复现，推荐 
        GSYVideoType.setRenderType(GSYVideoType.SURFACE); 
试试
