### ISSUE TITLE
rtmp格式的流播放没有画面，黑屏

### ISSUE THREAD

**Issue by cuijiao1993** [CarGuo/GSYVideoPlayer#2264]
## 问题描述：

使用 PlayerFactory.setPlayManager(Exo2PlayerManager.class);  rtmp可以正常拉出画面，只是拉流的速度有点慢；
但是使用 PlayerFactory.setPlayManager(IjkPlayerManager.class);  rtmp拉流成功的速度很快，但是没有画面，黑屏；
想请问下默认的so库支持rtmp格式吗？
这种问题是需要自己编译ijk吗？

## 问题机型/系统：

电视盒子 Android 4.4.4

## GSY依赖版本

   api 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    api 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
    api 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

**Comment by CarGuo** [comment]
默认不支持，要ex_so

**Comment by cuijiao1993** [comment]
01-01 01:38:58.871 17893-17893/com.hnsh.wuhanstadium E/ViewRootImpl: 201409092 enable acc for view=com.hnsh.wuhanstadium/com.hnsh.wuhanstadium.activity.PlayVideoActivity
01-01 01:38:58.909 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_release
01-01 01:38:58.909 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_native_setup
01-01 01:38:58.909 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ffpipeline_create_from_android()
01-01 01:38:58.909 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d4004ee)
01-01 01:38:58.909 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_set_inject_opaque()=void
01-01 01:38:58.909 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x1d4004ee)
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium V/IJKMEDIA: setDataSource: path rtmp://10.160.86.101:1935/vlMIP/srcMIP01
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_set_data_source(url="rtmp://10.160.86.101:1935/vlMIP/srcMIP01")
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_set_data_source(url="rtmp://10.160.86.101:1935/vlMIP/srcMIP01")=0
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setLoopCount
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(8)
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: moncleanup
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOption
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOption
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOption
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOption
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOption
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOption
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.910 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOption
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setVolume
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ffpipeline_set_volume
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_prepareAsync
01-01 01:38:58.911 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_prepare_async()
01-01 01:38:58.911 17893-18340/com.hnsh.wuhanstadium I/IJKMEDIA: SDL_RunThread: [18340] ff_msg_loop
01-01 01:38:58.911 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: message_loop
01-01 01:38:58.912 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: FFP_MSG_FLUSH:
01-01 01:38:58.915 17893-18341/com.hnsh.wuhanstadium I/IJKMEDIA: SDL_RunThread: [18341] ff_vout
01-01 01:38:58.915 17893-18342/com.hnsh.wuhanstadium I/IJKMEDIA: SDL_RunThread: [18342] ff_read
01-01 01:38:58.915 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_prepare_async()=0
01-01 01:38:58.917 17893-18342/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
01-01 01:38:58.922 17893-18342/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
01-01 01:38:59.175 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: FFP_MSG_OPEN_INPUT:
01-01 01:38:59.178 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: FFP_MSG_FIND_STREAM_INFO:
01-01 01:38:59.182 17893-18342/com.hnsh.wuhanstadium I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
01-01 01:38:59.182 17893-18342/com.hnsh.wuhanstadium I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
01-01 01:38:59.185 17893-18342/com.hnsh.wuhanstadium I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
01-01 01:38:59.185 17893-18342/com.hnsh.wuhanstadium I/IJKMEDIA: audio_session_id = 144
01-01 01:38:59.186 17893-18351/com.hnsh.wuhanstadium I/IJKMEDIA: SDL_RunThread: [18351] ff_audio_dec
01-01 01:38:59.186 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: FFP_MSG_COMPONENT_OPEN:
01-01 01:38:59.186 17893-18350/com.hnsh.wuhanstadium I/IJKMEDIA: SDL_RunThread: [18350] ff_aout_android
01-01 01:38:59.186 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
01-01 01:38:59.186 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: FFP_MSG_PREPARED:
01-01 01:38:59.186 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_start
01-01 01:38:59.186 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_start()
01-01 01:38:59.186 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_start()=0
01-01 01:38:59.186 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
01-01 01:38:59.188 17893-18350/com.hnsh.wuhanstadium D/IJKMEDIA: avcodec/Audio: first frame decoded
01-01 01:38:59.188 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: FFP_MSG_AUDIO_DECODED_START:
01-01 01:38:59.188 17893-18340/com.hnsh.wuhanstadium D/IJKMEDIA: FFP_MSG_AUDIO_RENDERING_START:
01-01 01:38:59.214 17893-17893/com.hnsh.wuhanstadium W/SurfaceView: screen pos, onLayout changed=true,left=0 top=0 right=1280 bottom=720
01-01 01:38:59.223 17893-17893/com.hnsh.wuhanstadium W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
01-01 01:38:59.223 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
01-01 01:38:59.223 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_set_android_surface(surface=0x2320001d)
01-01 01:38:59.223 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ffpipeline_set_surface()
01-01 01:38:59.223 17893-17893/com.hnsh.wuhanstadium D/IJKMEDIA: ijkmp_set_android_surface(surface=0x2320001d)=void
01-01 01:39:01.597 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
01-01 01:39:01.599 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
01-01 01:39:01.605 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
01-01 01:39:01.614 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
01-01 01:39:09.986 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
01-01 01:39:09.987 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
01-01 01:39:09.993 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
01-01 01:39:10.001 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
01-01 01:39:18.366 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
01-01 01:39:18.368 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
01-01 01:39:18.374 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
01-01 01:39:18.383 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
01-01 01:39:26.758 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
01-01 01:39:26.759 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
01-01 01:39:26.765 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
01-01 01:39:26.774 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
01-01 01:39:35.181 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
01-01 01:39:35.182 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
01-01 01:39:35.188 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
01-01 01:39:35.197 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
01-01 01:39:43.546 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
01-01 01:39:43.547 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
01-01 01:39:43.553 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
01-01 01:39:43.562 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
01-01 01:39:51.961 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
01-01 01:39:51.963 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
01-01 01:39:51.969 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
01-01 01:39:51.978 17893-18237/com.hnsh.wuhanstadium I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2


这是我播放rtmp时得log，可以麻烦大佬帮我看下这个是否成功拉到了视频流？
一直黑屏不出画面。
