### ISSUE TITLE
A设备全屏播放时，B设备通过信令的方式更新A设备的播放进度，出现黑屏状态

### ISSUE THREAD

**Issue by jason4it** [CarGuo/GSYVideoPlayer#2266]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

A设备全屏播放时，B设备通过信令的方式更新A设备的播放进度，出现黑屏状态

非全屏状态，通过信令的方式更新播放进度，正常。

更新播放进度方法：
    videoPlayView.setSeekOnStart(15000);
    videoPlayView.startPlayLogic();

## 问题机型/系统：

真机 小米9 Android9.0
真机 华为 EML-AL00 Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

问题代码：(如果有)

**Comment by CarGuo** [comment]
videoPlayView.getCurrentPlayer().setSeekOnStart(15000);
videoPlayView.getCurrentPlayer().startPlayLogic();

**Comment by jason4it** [comment]
刚刚试了下，没问题的，多谢
