### ISSUE TITLE
AudioManager 内存泄漏 问题

### ISSUE THREAD

**Issue by 752375734** [CarGuo/GSYVideoPlayer#2267]

**Comment by CarGuo** [comment]
没看到你上传的问题？
如果是 AudioManager 的请忽略

**Comment by 752375734** [comment]
为什么忽略呀？ 看leakcanary里面的引用链条，还真是，最下面是GSYVideoView引用activity context泄漏

**Comment by 752375734** [comment]
想上传个图片，不知道怎么上传

**Comment by CarGuo** [comment]
因为是这是系统级别的“污染”造成的，可见：

https://www.jianshu.com/p/50653a1fbf4d
https://www.jianshu.com/p/9c1114dbb324
https://stackoverflow.com/questions/6445052/android-context-memory-leak-listview-due-to-audiomanager

**Comment by AttackPangHu** [comment]
我按照简书的解决方案  还是会有泄漏问题

**Comment by Tomie-cycle** [comment]
同理，这个内存泄漏

**Comment by linrb685** [comment]
> 我按照简书的解决方案或出现问题

你解决了吗？我也是按照简书操作，结果还是有问题

**Comment by CarGuo** [comment]
> > 我按照简书的解决方案或出现问题
> 
> 
> 
> 你解决了吗？我也是按照简书操作，结果还是有问题

因为这个是正常现象，可以忽略，后来 AudioManager 出新的api了

**Comment by linrb685** [comment]
> > > 我按照简书的解决方案或出现问题
> > 
> > 
> > 你解决了吗？我也是按照简书操作，结果还是有问题
> 
> 因为这是正常现象，可以触发，随后 AudioManager 出新的 api 了

那新版的还会出现这个问题吗，是跟GSY的版本有关系吗

**Comment by linrb685** [comment]
> > > 我按照简书的解决方案或出现问题
> > 
> > 
> > 你解决了吗？我也是按照简书操作，结果还是有问题
> 
> 因为这个是正常现象，可以忽略，后来 AudioManager 出新的api了

同一个播放器在更换播放源（播放地址）的时候是否需要先停止或者销毁正在播放的，然后在设置新的播放地址同时开启播放？

**Comment by CarGuo** [comment]
@linrb685 需要

**Comment by linrb685** [comment]
> @linrb685 需要

好的  谢谢，这样如果频繁的更换播放源的话会不会增加系统的开销
