### ISSUE TITLE
HttpProxyCacheServer缓存限制512M如何更改

### ISSUE THREAD

**Issue by farendaibiao** [CarGuo/GSYVideoPlayer#2268]
## 问题描述：

新手尝试，请教大大们个问题
HttpProxyCacheServer中DEFAULT_MAX_SIZE = 512 * 1024 * 1024;
这个值如何修改成更大的值
请问有demo提示一下吗
按照这个Issues
github.com/CarGuo/GSYVideoPlayer/issues/1955
tydqcjj给的方案，我没有成功

## 问题机型/系统：

无

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

暂无

**Comment by CarGuo** [comment]
自定义 XXProxyCacheManager ，然后设置你的 CacheManager，你可以把 ProxyCacheManager cv 出来，然后 CacheFactory.setCacheManager(XXProxyCacheManager.class);/ :
```
    /**
     创建缓存代理服务,带文件目录的.
     */
    public HttpProxyCacheServer newProxy(Context context, File file) {
        if (!file.exists()) {
            file.mkdirs();
        }
        HttpProxyCacheServer.Builder builder = new HttpProxyCacheServer.Builder(context);
        builder.cacheDirectory(file);
        builder.headerInjector(userAgentHeadersInjector);
        builder.maxCacheFilesCount()
        builder.maxCacheSize()
        mCacheDir = file;
        return builder.build();
    }

    public void setProxy(HttpProxyCacheServer proxy) {
        this.proxy = proxy;
    }

    /**
     创建缓存代理服务
     */
    public HttpProxyCacheServer newProxy(Context context) {
        return new HttpProxyCacheServer.Builder(context.getApplicationContext())
                .headerInjector(userAgentHeadersInjector).maxCacheFilesCount().maxCacheSize().build();
    }
```

<img width="992" alt="image" src="https://user-images.githubusercontent.com/10770362/65297955-40cbf400-db9c-11e9-878a-303284df0032.png">

**Comment by farendaibiao** [comment]
> CacheFactory.setCacheManager(XXProxyCacheManager.class);

感谢您的指导，我试试看

**Comment by farendaibiao** [comment]
> 自定义 XXProxyCacheManager ，然后设置你的 CacheManager，你可以把 ProxyCacheManager cv 出来，然后 CacheFactory.setCacheManager(XXProxyCacheManager.class);/ :
> 
> ```
>     /**
>      创建缓存代理服务,带文件目录的.
>      */
>     public HttpProxyCacheServer newProxy(Context context, File file) {
>         if (!file.exists()) {
>             file.mkdirs();
>         }
>         HttpProxyCacheServer.Builder builder = new HttpProxyCacheServer.Builder(context);
>         builder.cacheDirectory(file);
>         builder.headerInjector(userAgentHeadersInjector);
>         builder.maxCacheFilesCount()
>         builder.maxCacheSize()
>         mCacheDir = file;
>         return builder.build();
>     }
> 
>     public void setProxy(HttpProxyCacheServer proxy) {
>         this.proxy = proxy;
>     }
> 
>     /**
>      创建缓存代理服务
>      */
>     public HttpProxyCacheServer newProxy(Context context) {
>         return new HttpProxyCacheServer.Builder(context.getApplicationContext())
>                 .headerInjector(userAgentHeadersInjector).maxCacheFilesCount().maxCacheSize().build();
>     }
> ```
> 
> <img alt="image" width="992" src="https://user-images.githubusercontent.com/10770362/65297955-40cbf400-db9c-11e9-878a-303284df0032.png">

感谢您的指导，我试试看

**Comment by farendaibiao** [comment]
> 自定义 XXProxyCacheManager ，然后设置你的 CacheManager，你可以把 ProxyCacheManager cv 出来，然后 CacheFactory.setCacheManager(XXProxyCacheManager.class);/ :
> 
> ```
>     /**
>      创建缓存代理服务,带文件目录的.
>      */
>     public HttpProxyCacheServer newProxy(Context context, File file) {
>         if (!file.exists()) {
>             file.mkdirs();
>         }
>         HttpProxyCacheServer.Builder builder = new HttpProxyCacheServer.Builder(context);
>         builder.cacheDirectory(file);
>         builder.headerInjector(userAgentHeadersInjector);
>         builder.maxCacheFilesCount()
>         builder.maxCacheSize()
>         mCacheDir = file;
>         return builder.build();
>     }
> 
>     public void setProxy(HttpProxyCacheServer proxy) {
>         this.proxy = proxy;
>     }
> 
>     /**
>      创建缓存代理服务
>      */
>     public HttpProxyCacheServer newProxy(Context context) {
>         return new HttpProxyCacheServer.Builder(context.getApplicationContext())
>                 .headerInjector(userAgentHeadersInjector).maxCacheFilesCount().maxCacheSize().build();
>     }
> ```
> 
> <img alt="image" width="992" src="https://user-images.githubusercontent.com/10770362/65297955-40cbf400-db9c-11e9-878a-303284df0032.png">

大大，能否再问个问题。关于LRU缓存算法
private void trim(List<File> files) {
        long totalSize = countTotalSize(files);
        int totalCount = files.size();
        for (File file : files) {
            boolean accepted = accept(file, totalSize, totalCount);
            if (!accepted) {
                long fileSize = file.length();
                boolean deleted = file.delete();
                if (deleted) {
                    totalCount--;
                    totalSize -= fileSize;
                    HttpProxyCacheDebuger.printfLog("Cache file " + file + " is deleted because it exceeds cache limit");
                } else {
                    HttpProxyCacheDebuger.printfError("Error deleting file " + file + " for trimming cache");
                }
            }
        }
    }
能否取消删除文件或者取消LRU缓存算法呢？

**Comment by CarGuo** [comment]
简单来说，不行

**Comment by farendaibiao** [comment]
> 简单来说，不行

好的，感谢告知，谢谢您的解答！
