### ISSUE TITLE
关于播放器未开始播放时，调用暂停接口无效

### ISSUE THREAD

**Issue by road2019** [CarGuo/GSYVideoPlayer#2271]
## 问题描述：

播放器正在初始化并准备开始播放，此时需要暂停播放，但调用播放暂停无效

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by CarGuo** [comment]
我记得源码里做了处理了

**Comment by road2019** [comment]
谢谢，找到原因了，在播放器初始化之前会有一系列的耗时处理，此时退出页面无法暂停，必须判断状态，跳过初始化，回来后恢复现场。源码中针对未初始化完成时暂停有效，并在下一次恢复播放时继续未完成的初始化并开始播放。
