### ISSUE TITLE
播放中 或者暂停时 退出Activity 没能立即停止的问题

### ISSUE THREAD

**Issue by yangxu1210** [CarGuo/GSYVideoPlayer#2272]
### 问题描述：

`播放问题`
普通的Activity使用StandardGSYVideoPlayer, 播放/暂停 状态下 退出Activity表现如下：

1. 播放状态下，退出 没有立即停止播放 退回到上一个界面的时候还能听到视频的声音，大概3秒左右才彻底停止。
2. 暂停状态下，退出Activity时 播放器的 播放按钮和loading按钮同时出现 闪烁，然后就开始播放了大概3秒 再彻底停止。。。
3. 确定Activity已经根据文档 分别在 onPause、 onResume、onDestroy回调中调用了相关代码。

`全屏模式下的封面无法显示问题`
非全屏模式下播放完毕 封面图显示正常，全屏模式播放完毕后 黑屏。

`设备型号：HUAWEI P10`
PS：
各位大佬有遇到类似问题的 麻烦告知一下怎么解决 谢谢了

**Comment by CarGuo** [comment]
全屏状态下模式就是没有封面的。
至于第一和第二，demo的复现步骤是？因为默认的ijk内核，release是存在一定的异步时长的，但是你这个3秒有点夸张。
或者你可以切换到exo的内核模式试试。
