### ISSUE TITLE
是否支持解析链接加播放地址

### ISSUE THREAD

**Issue by 748297973** [CarGuo/GSYVideoPlayer#2273]
https://jx.wawakj.top/?url=这个是解析地址
http://v3.bjssmd.net/20190920/ILEmMMWG/index.m3u8这个是播放源

https://jx.wawakj.top/?url=http://v3.bjssmd.net/20190920/ILEmMMWG/index.m3u8这样可以应用在播放器播放吗,有什么思路

**Comment by CarGuo** [comment]
not support

**Comment by 748297973** [comment]
感谢
