### ISSUE TITLE
flv格式的视频不能快进

### ISSUE THREAD

**Issue by cuijiao1993** [CarGuo/GSYVideoPlayer#2274]
（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

flv格式的视频不能快进

使用了Exo2PlayerManager和IJKPlayerManager内核，都不能快进。

## 问题机型/系统：

电视盒子，Android 4.4.4
## GSY依赖版本

api 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    api 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
    api 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

**Comment by CarGuo** [comment]
请提供测试url

**Comment by ZhuSky** [comment]
https://upos-sz-mirrorks3.bilivideo.com/upgcxcode/37/18/123061837/123061837-1-336.flv?e=ig8euxZM2rNcNbN37wdVhwdlhb4MhwdVhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1604999646&gen=playurl&os=ks3bv&oi=1781853779&trid=c1b1d83c99674127984d725f98a8ec5bt&platform=android&upsig=94d2ab5613952835336823a0ecfc3dc9&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&orderid=0,3&logo=80000000


@CarGuo 大神，这个播放地址，进度条无法快进

**Comment by ZhuSky** [comment]
日志：
![image](https://user-images.githubusercontent.com/18596232/98642112-d5c51a00-2367-11eb-931b-a228d29d0ad4.png)
 依赖：
    api 'com.shuyu:gsyVideoPlayer-java:7.1.6'
    api 'com.shuyu:GSYVideoPlayer-exo2:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-ex_so:7.1.6'

**Comment by ZhuSky** [comment]
"User-Agent": " Bilibili Freedoooooom\/MarkII",
			"Accept": " *\/*",
			"Connection": " close",
			"Range": " bytes=0-"


这是url的header
