### ISSUE TITLE
按Home键回到桌面播放暂停，再点击返回播放视频画面卡住

### ISSUE THREAD

**Issue by liushuiping** [CarGuo/GSYVideoPlayer#2275]
按Home键回到桌面播放暂停，再点击返回播放页面发现音频继续在播但是视频画面卡住不动了

**Comment by CarGuo** [comment]
机型，测试url，demo复现步骤。

**Comment by liushuiping** [comment]
公司自己的平板，测试过一般在手机上是没问题的，猜测可能是系统问题。后来没有用onVideoResume方法，直接重播startPlayLogic然后再定位到之前播放的进度setSeekOnStart播放又可以了

**Comment by CarGuo** [comment]
这种我就没办法定位了，你可以试试切到到 exoplayer 模式，使用 mediacodec 播放试试，如果也不行就是这平板兼容性问题了

**Comment by SongJeen** [comment]
这个问题很容易复现，估计很多人都是因为这个原因弃用这个库的吧

**Comment by CarGuo** [comment]
我这边测试demo在手机平台和电视平台正常@SongJeen 目前测试基本在 5.0 以上，对于5.0以下的基本不做支持。

**Comment by SongJeen** [comment]
我手机系统是安卓9.0，挂在后台很容易出现黑屏这个问题。

**Comment by liushuiping** [comment]
看了下播放器设置, GSYVideoType.setRenderType(GSYVideoType.GLSURFACE)设置中间播放View为GSYVideoGLView也不会出现上述问题。。。再问下这个播放器有记住上次播放进度的功能么？
