### ISSUE TITLE
关于设置播放总时长的问题

### ISSUE THREAD

**Issue by liuxvdong031** [CarGuo/GSYVideoPlayer#2276]
作者您好:
现在我们遇到一个这样的需求.
需要为播放器设置一个假的总播放时长,例如视频url的播放时长是60秒.我们先显示一个180的播放时长.
我可以通过getDuration获取播放时长,但是并没有相应的set方法.
请问有方法可以实现么?

**Comment by CarGuo** [comment]
不是很理解你的问题，但是我觉得可以在 header 增加播放请求区域

**Comment by liuxvdong031** [comment]
类似与爱奇艺的vip视频, 只能试看五分钟的.
我们的试看和非试看的不是同一个url.
试看的视频是一个60秒的视频.
非试看的是一个128秒的视频.
现在想在试看视频显示一个128秒的视频总长度.
![image](https://user-images.githubusercontent.com/18443386/65479050-83ecd680-debe-11e9-8a21-b82b0556981b.png)

**Comment by CarGuo** [comment]
我们做视频的，这个肯定是从服务端处做限制，不然很随意就被破解了，服务端根据用户返回不同的链接，链接的流里头部包含了完整时长，但是流内容不完整。
