### ISSUE TITLE
怎么去掉自动播放

### ISSUE THREAD

**Issue by poison8** [CarGuo/GSYVideoPlayer#2277]
播放器怎么去掉自动播放

**Comment by CarGuo** [comment]
不是很理解你说的？

**Comment by poison8** [comment]
现在就是跳转到播放页就自动播放 我想不让它自动播放，怎么设置不让自动播放

**Comment by poison8** [comment]
我进入页面后 使用pause 然后 用 resume resume事件不响应

**Comment by poison8** [comment]
我找了源码 没有 autoplay 相关的东西

**Comment by CarGuo** [comment]
demo 里哪个页面？一般播放是调用 startPlayLogic

**Comment by poison8** [comment]
那个设置为false 是 不自动播放吗？ 还是

**Comment by CarGuo** [comment]
哪个？播放方法就是 startPlayLogic 啊？
