### ISSUE TITLE
某些视频很奇怪光有背景音乐但是没有人说话的声音，ios 和 mac上却可以播放出人声

### ISSUE THREAD

**Issue by Codexiaofeifei** [CarGuo/GSYVideoPlayer#2278]
## 问题描述：

使用IJK默认内核 播放视频url  http://vod-xhpfm.zhongguowangshi.com/NewsVideo/201908/e9cc3fbe67ba40109c0cafb06813868d.mp4 出现视频中人声未播放出来的现象 ，将该地址放在ios手机 或 mac自带播放器 或 mac chrome上播放均能正常播放  (android手机上微信和QQ也均不能播放出人声)
## 问题机型/系统：
例如 真机 小米9 (android 手机都会这样，排除少数不会这样的)

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的SimplePlayer 更换一下播放地址即可复现

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/65610531-13d87080-dfe4-11e9-945b-fa7ae5d1ec49.png)

推测可能是 aac mp4a 的编码兼容问题
