### ISSUE TITLE
列表详情切换页面，进入详情页播放结束后，返回列表页视频无法播放

### ISSUE THREAD

**Issue by qqnp1100** [CarGuo/GSYVideoPlayer#2280]
## 问题描述：

Demo中的列表详情切换页面，进入详情页播放结束后，返回列表页视频无法播放

## 问题机型/系统：

真机 小米mix2 华为novo3

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'`

## Demo中的复现步骤

Demo主页点击列表详情切换，进入列表后点击视频的详情，在详情页等待视频播放完，返回列表页，该视频将无法播放

## 上图
![svid_20190925_171040_1 00_00_03--00_00_23](https://user-images.githubusercontent.com/14014255/65587634-c1358f00-dfb8-11e9-84f1-e5982942f0b3.gif)

**Comment by CarGuo** [comment]
这个故意设置为这样的，你可以看源码

**Comment by qqnp1100** [comment]
可是在视频播放中返回，列表就还可以点击播放，为什么播放结束后要设置成这样。。。
还有，有木有什么办法解决，我在SwitchDetailActivity找了半天也没找到解决方法T.T

**Comment by CarGuo** [comment]
不好意思，这个是我的问题，看错了，以为是说切换到详情之后返回停止播放了。

**Comment by qqnp1100** [comment]
期待能解决这个问题哈(￣▽￣)~*

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/commit/977d9d5248c77e274bcd0dc163ed0b96c33c5509

**Comment by qqnp1100** [comment]
牛皮嗷，已测试，可以正常播放了
