### ISSUE TITLE
Ijkplayer 如何添加 AC-3 codec? 否则高清格式（mts, mt2s）光有画面没有声音

### ISSUE THREAD

**Issue by ooyellow58** [CarGuo/GSYVideoPlayer#2281]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
理论上：
```
支持 ac3
编译

    --enable-encoder=ac3 \
    --enable-decoder=ac3 \
    --enable-encoder=ac3_fixed\
    --enable-decoder=atrac3 \
    --enable-decoder=atrac3p \
    --enable-encoder=eac3 \
    --enable-decoder=eac3 \
    --enable-muxer=ac3 \
    --enable-demuxer=ac3 \
    --enable-muxer=eac3 \
    --enable-demuxer=eac3 \
```

**Comment by ooyellow58** [comment]
事实上，mediaplayer 也是只有画面没有声音。

**Comment by CarGuo** [comment]
mediaplayer 是 mediacodec 的解码，这个支持解码类型是固定的
