### ISSUE TITLE
如何清除缓存

### ISSUE THREAD

**Issue by limengxin** [CarGuo/GSYVideoPlayer#2283]
## 问题描述：

setCacheWithPlay(TRUE)时，如何清除缓存或者调用什么方法

## 问题机型/系统：

真机 小米6 Android9.0

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.0'

**Comment by CarGuo** [comment]
```
   GSYVideoManager.instance().clearAllDefaultCache(MainActivity.this);
                //String url = "https://res.exexm.com/cw_145225549855002";
                //GSYVideoManager.clearDefaultCache(MainActivity.this, url);
```

**Comment by limengxin** [comment]
问题描述：
当播放m3u8视频时我想缓存，并在全局设置了代码，如下：
PlayerFactory.setPlayManager(Exo2PlayerManager.class)；
CacheFactory.setCacheManager(ExoPlayerCacheManager.class)；
并且播放器设置了：
setCacheWithPlay(TRUE)
但是我发现并不能缓存，mp4和m3u8格式都不能，如果去掉全局代码或者设置为其他缓存模式后，mp4能成功缓存，m3u8不能。
请问还需要在其他地方设置吗？

**Comment by CarGuo** [comment]
ExoPlayerCacheManager 正常缓存，如下图所示：

<img width="950" alt="image" src="https://user-images.githubusercontent.com/10770362/65669434-1f747780-e076-11e9-9bfb-f1fde0028b4a.png">

**Comment by limengxin** [comment]
刚才加上了文件存储权限，再使用exo缓存模式的时候，底下的缓存白条确实是动了，只是每次加载的比较少不过也够用了，不像代理缓存模式下一直加载完，但是没有找到这个cache文件夹下的exo文件以及内容，再使用exo缓存模式情况下是否要设置指定缓存文件夹

**Comment by CarGuo** [comment]
这个是在 data/data 目录下
