### ISSUE TITLE
使用多个同时播放的控件，在退出的时候只释放一个，另外一个未释放。

### ISSUE THREAD

**Issue by hdd1024** [CarGuo/GSYVideoPlayer#2284]
项目有使用MultiSampleVideo做两个页面同事播放不同页面的需求，在两个都在播放时候点击退出按钮回调登陆页，只有A页面的MultiSampleVideo组件释放了资源，B页面的MultiSampleVideo还在继续播放未释放资源。通过打断点发现B页面页执行了
`//释放所有
        if (mSVPLiveFragment != null) {
            mSVPLiveFragment.setVideoAllCallBack(null);
            GSYVideoManager.releaseAllVideos();
        }`但是却未释放资源！

**Comment by CarGuo** [comment]
MultiSampleVideo 用的是自定义的 CustomManager 呀，不是用 GSYVideoManager

**Comment by hdd1024** [comment]
谢谢！问题解决了，改成`if (mSVPLiveFragment != null) {
            mSVPLiveFragment.setVideoAllCallBack(null);
            CustomManager.releaseAllVideos(mSVPLiveFragment.getKey());
        }`两个页面就都能关闭了
