### ISSUE TITLE
rn集成这个播发器

### ISSUE THREAD

**Issue by wq13718048209** [CarGuo/GSYVideoPlayer#2285]
## 问题描述：

请问ReactNative Android端可以集成您这个播放器用吗

## 问题机型/系统：

无

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by poison8** [comment]
我集成了 implementation ('com.shuyu:gsyVideoPlayer-java:6.0.1'）

**Comment by poison8** [comment]
用的很好的 我集成了这个播放器

**Comment by wq13718048209** [comment]
> 用的很好的 我集成了这个播放器

能指导一下吗 大佬  求教

**Comment by poison8** [comment]
加我qq：65428248

**Comment by wq13718048209** [comment]
> 加我qq：65428248

您的这个qq加不上啊 是不是写错了

**Comment by poison8** [comment]
你说你的qq 我加你吧

**Comment by wq13718048209** [comment]
> 你说你的qq 我加你吧

我的qq是582752848  谢谢了
