### ISSUE TITLE
listVideoUtil.setVideoAllCallBack(new SampleListener()里的onClickStartIcon方法怎么不走

### ISSUE THREAD

**Issue by plmmanwu** [CarGuo/GSYVideoPlayer#229]

**Comment by plmmanwu** [comment]
监听回调里不走onClickStartIcon方法 怎么解决

**Comment by CarGuo** [comment]
demi的listVideoUitl模式下的，第一次点击，是由自己布局的那个播放按键触发的吧

**Comment by plmmanwu** [comment]
那要怎么在listVideoUitl模式下在视频onPrepear之前监听视频，除了onClickStartIcon这个方法有什么好的解决方案吗
