### ISSUE TITLE
EXO内核在多任务情况下暂停后全屏会黑屏

### ISSUE THREAD

**Issue by zzh3321** [CarGuo/GSYVideoPlayer#2290]
## 问题描述：

切换到exo内核，再到多任务列表中播放视频，点击暂停，点击全屏播放，这个时候原来的画面黑屏了，必须点击开始播放，重新显示画面

## 问题机型/系统：

真机  华为荣耀9

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中到exo页面切换exo内核，再到多任务去，可重现

**Comment by CarGuo** [comment]
是的，正常现象，如果有需要，设置pasue cover参数

**Comment by zzh3321** [comment]
可以麻烦告诉下具体怎么设置吗，这个不太懂，感谢

**Comment by zzh3321** [comment]
找到了，setShowPauseCover，感谢~
