### ISSUE TITLE
请问全屏模式的横竖屏切换怎么监听的到？

### ISSUE THREAD

**Issue by yangxu1210** [CarGuo/GSYVideoPlayer#2291]
## 请问全屏模式的横竖屏切换怎么监听的到？

**翻找一圈没找着 麻烦知道的大佬告知一下**

### 3.建议对外放开OrientationUtils 屏幕旋转帮助类，修改init()方法修饰符,让大家修改内部旋转逻辑。

**自定义播放器 继承自StandardGSYVideoPlayer 类然后重写 onConfigurationChanged 方法不走。** 

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

**Comment by CarGuo** [comment]
GSYSampleCallBack 不是有么 ：

```
    //进去全屏，objects[0]是title，object[1]是当前所处播放器（全屏或非全屏）
    @Override
    public void onEnterFullscreen(String url, Object... objects) {

    }

    //退出全屏，objects[0]是title，object[1]是当前所处播放器（全屏或非全屏）
    @Override
    public void onQuitFullscreen(String url, Object... objects) {

    }
```

需求2 你可以参看 demo 中重写了  onConfigurationChanged(Configuration newConfig)  的逻辑

需求3 这个可以考虑后续版本增加
