### ISSUE TITLE
一个mp4视频 不过后缀是.ppppp怎么播放

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#2293]
一个mp4视频 不过后缀是.ppppp怎么播放

**Comment by CarGuo** [comment]
exoplayer 内核的可以 setOverrideExtension
<img width="598" alt="image" src="https://user-images.githubusercontent.com/10770362/65825204-de16de80-e2a6-11e9-89e5-68ce7006b0b5.png">

**Comment by yang0000meng** [comment]
我这边地址问题 。。不是播放器的问题，exoplayer可以自动识别。

**Comment by yang0000meng** [comment]
exoplayer
