### ISSUE TITLE
黑屏问题

### ISSUE THREAD

**Issue by frulistrawberry** [CarGuo/GSYVideoPlayer#2296]
## 问题描述：
参考demo PlayEmptyControlActivity设置全屏是出现只有声音没有画面的问题
调用代码 videoPlayer.startWindowFullscreen(this,false,false);

## 问题机型/系统：

例如 真机 华为mate20Pro Android9.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

 videoPlayer.setUp(“http:\/\/cripple.oss-cn-beijing.aliyuncs.com\/85524b03-88cb-4b4f-bb15-b177bdbfe85c201909291529058.mp4?Expires=1885102198&OSSAccessKeyId=LTAIwIMSrFp3QBrH&Signature=dLY49PO936sRY31Hp6JAEh%2B3NtQ%3D”, true, "");
   videoPlayer.startWindowFullscreen(this,false,false);
    videoPlayer.startPlayLogic();

**Comment by CarGuo** [comment]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/10770362/66296381-03978e00-e920-11e9-9ddd-8135641a0a2f.png">


demo 测试正常
