### ISSUE TITLE
使用系统播放器，视频暂停时，全屏和原始大小进行切换，会自动进行播放

### ISSUE THREAD

**Issue by linuhap** [CarGuo/GSYVideoPlayer#2299]
## 问题描述：

应用为横屏应用。使用系统播放器，视频暂停时，全屏和原始大小进行切换后，会自动进行视频播放

## 问题机型/系统：

小米8

## GSY依赖版本

compile 'com.shuyu:GSYVideoPlayer:6.0.1'

## Demo中的复现步骤

app为强制横屏。视频暂停，点击右下角全屏按钮进行切换

问题代码：
```
        videoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                videoPlayer.startWindowFullscreen(demoActivity.this, false, false);
            }
        });
        // 设置返回按键功能
        videoPlayer.getBackButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (GSYVideoManager.isFullState(demoActivity.this)) {
                    // 全屏状态变为小窗
                    videoPlayer.getFullscreenButton().performClick();
                } 
            }
        });
```

**Comment by linuhap** [comment]
提供一种我的解决方案：

`        videoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ViewGroup.LayoutParams layoutParams = videoPlayer.getLayoutParams();
                if (isFullScreen) {
                    layoutParams.width = videoPlayerWidth;
                    layoutParams.height = videoPlayerHeight;
                    videoPlayer.setLayoutParams(layoutParams);
                } else {
                    if (videoPlayerHeight == 0) {
                        videoPlayerHeight = layoutParams.height;
                        videoPlayerWidth = layoutParams.width;
                    }

                    layoutParams.width = LayoutParams.MATCH_PARENT;
                    layoutParams.height = LayoutParams.MATCH_PARENT;
                    videoPlayer.setLayoutParams(layoutParams);
                }

                isFullScreen = !isFullScreen;
            }
        });`

**Comment by CarGuo** [comment]
只有系统播放器会？
