### ISSUE TITLE
如何换exoplay的播放器

### ISSUE THREAD

**Issue by guojiadui** [CarGuo/GSYVideoPlayer#230]

**Comment by CarGuo** [comment]
GSYVideoManager有setVideoType

**Comment by guojiadui** [comment]
还有就是类似于,http://183.59.185.72:30001/PLTV/88888905/224/3221227270/10000100000000060000000001141346_0.smil这种的电视直播链接没声音，如何解决

**Comment by CarGuo** [comment]
你需要确定，视频的音频编码是什么
