### ISSUE TITLE
播放视频的时候按home键在进入app,画面不动但是有声音

### ISSUE THREAD

**Issue by barryyanggoing** [CarGuo/GSYVideoPlayer#2302]
播放视频的时候按home键在进入app,画面不动但是有声音

**Comment by CarGuo** [comment]
demo 怎么复现？
手机机型和系统是？

**Comment by barryyanggoing** [comment]
乐视1
复现步骤：打开简单直接播放Activity播放视频，按手机home键返回到桌面，再点击桌面图标进入，进度在变，声音能听到，但是视频图像静止。

**Comment by CarGuo** [comment]
我这边华为和小米测试正常，乐视1 的 Android 版本是？ 或者推荐你切换渲染控件试试 GSYVideoType.setRenderType(GSYVideoType.SUFRACE);

**Comment by barryyanggoing** [comment]
android 6.0，如你所说，要加上GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
感谢！！！
