### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by alanzyz** [CarGuo/GSYVideoPlayer#2303]
## 问题描述：

GSYVideoControlView 内存泄漏！

## 问题机型/系统：

例如 真机 三星 s6 

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.0'

## monkey 内存泄漏

问题代码：(如果有)

问题出在GSYVideoControlView 类 1061行。

  private class ProgressTimerTask extends TimerTask {
}
持有外部类应用。

**Comment by CarGuo** [comment]
请问是 demo 哪个页面可以复现，因为我记得各个位置都补充了  cancelProgressTimer

**Comment by alanzyz** [comment]
你說的demo指的是我的应用么？

**Comment by CarGuo** [comment]
是这个项目运行的demo

**Comment by alanzyz** [comment]
我是我的项目跑出来的。GSYVideoControlView 类 1061行。。你的我暂时没跑。

**Comment by alanzyz** [comment]
你用leak工具能抓到么

**Comment by CarGuo** [comment]
我也是感觉比较奇怪，因为 onDetachedFromWindow 里确实是调用了。

**Comment by CarGuo** [comment]
做了一些修改，下个版本应该不会用 timerTask了

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/commit/106df8101ec63eac55aefa1d1441655f35a96c65
