### ISSUE TITLE
当视频播放完，拖动进度条到某个位置无法正常播放

### ISSUE THREAD

**Issue by barryyanggoing** [CarGuo/GSYVideoPlayer#2305]
## 问题描述：

当视频播放完，拖动进度条到某个位置无法正常播放。

## 问题机型/系统：

例如 真机 乐视1 Android6.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'`

## Demo中的复现步骤
让视频播放完，显示封面图片后，向左拖动进度条，无法正常播放，一直显示封面图片。

**Comment by CarGuo** [comment]
看源码，这是设计如此，有需要可以看源码继承修改

**Comment by kanfRUI** [comment]
具体参考哪些源码？是否告知一下
