### ISSUE TITLE
从后台恢复后画面静止，音乐继续播放

### ISSUE THREAD

**Issue by kennir** [CarGuo/GSYVideoPlayer#2306]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

从后台恢复后画面静止，音乐继续播放

## 问题机型/系统：

真机 红米 Pro

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'`

## Demo中的复现步骤

Demo中打开简单播放->简单直接播放 开始播放视频，按Home将demo放置到后台，再次点击demo图标打开demo，声音恢复播放，但是画面保持静止不动

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2302

**Comment by kennir** [comment]
经测试设置为 SURFACE 或者 TEXTURE 都没有解决该问题

**Comment by CarGuo** [comment]
主要是我这边没出息问题，看起来像是特定机型或者系统问题…

**Comment by kennir** [comment]
测试下来不管有没有用保存的texture都调用mySurfaceListener?.onSurfaceAvailable(surface)后可以正常恢复播放，不知道有没有什么其他的问题

```
    override fun onSurfaceTextureAvailable(surfaceTexture: SurfaceTexture?, width: Int, height: Int) {
        if (savedTexture == null) {
            savedTexture = surfaceTexture
            surface = Surface(surfaceTexture)
        } else {
            setSurfaceTexture(savedTexture)
        }

        mySurfaceListener?.onSurfaceAvailable(surface)
    }
```

**Comment by CarGuo** [comment]
你的意思是，再源码层补上如图蓝色的部分？

<img width="905" alt="image" src="https://user-images.githubusercontent.com/10770362/66638101-ed067500-ec46-11e9-8e05-c164d7130e98.png">

**Comment by czeall** [comment]
OPPO R9M同样问题。
经查询是在回到后台的时候textureView执行了onSurfaceTextureDestroyed方法，回到前台又执行了onSurfaceTextureAvailable，textureview的surface发生了重建。
目前还没有合适的解决办法，换用surfaceView的话又有其他问题。
求解决。

**Comment by kennir** [comment]
@CarGuo  对的

**Comment by kennir** [comment]
我是红米Pro， 目测可以了， SurfaceView我也不能用，RecyclerView滚动的时候会随机出现黑色的闪动

**Comment by CarGuo** [comment]
> OPPO R9M同样问题。
> 经查询是在回到后台的时候textureView执行了onSurfaceTextureDestroyed方法，回到前台又执行了onSurfaceTextureAvailable，textureview的surface发生了重建。
> 目前还没有合适的解决办法，换用surfaceView的话又有其他问题。
> 求解决。

既然发生重构，应该会通过回调回调出去啊。 你是最新版本吗？

**Comment by czeall** [comment]
> > OPPO R9M同样问题。
> > 经查询是在回到后台的时候textureView执行了onSurfaceTextureDestroyed方法，回到前台又执行了onSurfaceTextureAvailable，textureview的surface发生了重建。
> > 目前还没有合适的解决办法，换用surfaceView的话又有其他问题。
> > 求解决。
> 
> 既然发生重构，应该会通过回调回调出去啊。 你是最新版本吗？

刚更新最新的版本，看到在onSurfaceTextureAvailable做了修改。但问题还是没有解决。回到后台或者切换其他app返回前台后仍然声音继续播放画面静止。

**Comment by CarGuo** [comment]
@czeall 我这边测试的几台机器都没问题，这个只能你调试看看。
基本上你可以在 PlayerManager 的 showDisplay ；和 GSYTextureView、GSYTextureRenderView 去看看是哪个流程出现兼容问题，最终都会到 showDisplay 里

**Comment by Devinmzt** [comment]
我这边边好几台机子都出问题了   7.0以下的机子都会出现这个问题  回滚到7.0.2是正确的

**Comment by Devinmzt** [comment]
我这边边好几台机子都出问题了包括华为 魅族等 7.0以下的机子都会出现这个问题   sdk回滚到7.0.2是正确的 @CarGuo

**Comment by CarGuo** [comment]
@Devinmzt 你需要先确定这个修改是否会fix了你的问题？ demo 上运行下，如果可以我发个新包。

**Comment by CarGuo** [comment]
7.1.1已经发布

**Comment by czeall** [comment]
> 7.1.1已经发布

播放器sdk回退到7.0.2版本是正常的，7.1.0和7.1.1都会出现该问题。

**Comment by CarGuo** [comment]
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/10770362/66694570-563dc500-ece7-11e9-97bb-2ce457fd3487.png">


@czeall 应该是这个区别

**Comment by CarGuo** [comment]
@czeall 我刚刚更新了 demo ，你再试试，如果可以我发布个 fix 版本

**Comment by czeall** [comment]
> @czeall 我刚刚更新了 demo ，你再试试，如果可以我发布个 fix 版本

刚拉的代码，测试还是不行。

**Comment by CarGuo** [comment]
@czeall 如果 7.0.2 没问题，那应该是一样的效果，奇怪

**Comment by CarGuo** [comment]
如下图两张所示，我在云测上目前只找到 R9s ，测试正常 @czeall 
![222221](https://user-images.githubusercontent.com/10770362/66695461-68723000-ecf4-11e9-870a-f2be26708b68.gif)
![image](https://user-images.githubusercontent.com/10770362/66695466-7cb62d00-ecf4-11e9-8f28-a6204eb951f8.png)

**Comment by CarGuo** [comment]
测试2 云测上目前只找到 R7s ，测试正常 @czeall

GIF：
![344](https://user-images.githubusercontent.com/10770362/66695555-a459c500-ecf5-11e9-80ed-1a9e6eb9ef58.gif)

png 机型信息 ：

![image](https://user-images.githubusercontent.com/10770362/66695557-b0de1d80-ecf5-11e9-94fe-dbaa7879187d.png)

**Comment by czeall** [comment]
自测了三款oppo真机，只有OPPO R9M有这个问题，其他两款OPPO 没有问题。
以下是OPPO R9M 测试信息：

[OPPO R9M 测试.zip](https://github.com/CarGuo/GSYVideoPlayer/files/3720261/OPPO.R9M.zip)

**Comment by CarGuo** [comment]
R9M 我这边测试拿不到机器，都是占用，如果只是特性机型的话，很大概念我这边没办法定位到问题·····远程真机开销推贵的。

**Comment by czeall** [comment]
> R9M 我这边测试拿不到机器，都是占用，如果只是特性机型的话，很大概念我这边没办法定位到问题·····远程真机开销推贵的。

好的，谢大佬。

**Comment by CarGuo** [comment]
@kennir @Devinmzt 你们可以升级到 7.1.1 ，看问题是否解决。

**Comment by kennir** [comment]
@CarGuo 好，我测一下，谢谢

**Comment by CarGuo** [comment]
那我先 close 了，R9M 上的问题看缘分吧～～
