### ISSUE TITLE
非全屏backbutton 怎么处理

### ISSUE THREAD

**Issue by smallneil** [CarGuo/GSYVideoPlayer#2308]

**Comment by CarGuo** [comment]
？？？？？

**Comment by smallneil** [comment]
videoplayer.getBackButton().setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (GSYVideoManager.isFullState(act)) {
                        // 全屏状态变为小窗
                        videoplayer.getFullscreenButton().performClick();
                    }else{
                       
                    }
                }
            });

**Comment by CarGuo** [comment]
不是很理解你的意思

**Comment by smallneil** [comment]
> 不是很理解你的意思

不好意思 已经处理了
