### ISSUE TITLE
全屏状态下返回键不可用，点击事件传递的View是surface_container

### ISSUE THREAD

**Issue by Daimhim** [CarGuo/GSYVideoPlayer#2309]
## 问题描述：

准备写一个弹幕播放器，继承了StandardGSYVideoPlayer，但是在全屏状态返回按钮不起作用，即使使用mVpVideoPlayer.getBackButton()设置监听也没有作用，打印onClick发现点击事件的传递都是surface_container，所以想问一下有什么处理案例没有

## 问题机型/系统：

真机小米8S puls

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.0'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
@Override
    public void onClick(View v) {
        super.onClick(v);
        Timber.i("onClickonClickonClick %s %s,%s %s %s",mIfCurrentIsFullscreen,
                v.getId(),com.shuyu.gsyvideoplayer.R.id.back,v.getClass().getSimpleName(),R.id.surface_container);
        if (mIfCurrentIsFullscreen && v.getId() == com.shuyu.gsyvideoplayer.R.id.back) {
            GSYVideoManager.backFromWindowFull(getContext());
        }
    }
```

## 问题log（如果有）
 onClickonClickonClick false 2131296680,2131296332 ENPlayView 2131296685
 onClickonClickonClick true 2131296685,2131296332 RelativeLayout 2131296685
 onClickonClickonClick true 2131296685,2131296332 RelativeLayout 2131296685
 onClickonClickonClick true 2131296685,2131296332 RelativeLayout 2131296685
 onClickonClickonClick true 2131296685,2131296332 RelativeLayout 2131296685
 onClickonClickonClick true 2131296685,2131296332 RelativeLayout 2131296685

**Comment by CarGuo** [comment]
mVpVideoPlayer.getCurrentPlayer().getBackButton()
