### ISSUE TITLE
如何设置让视频开始播放第一帧之后默认背景图再消失 不要显示黑色背景？

### ISSUE THREAD

**Issue by AndSync** [CarGuo/GSYVideoPlayer#2310]
## 问题描述：

如何设置让视频开始播放第一帧之后默认背景图再消失 不要显示黑色背景？

## 问题机型/系统：

All devices 

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

```

**Comment by CarGuo** [comment]
demo 中有个 SampleCoverVideo

**Comment by AndSync** [comment]
3Q
