### ISSUE TITLE
exo播放MP4失败，但是切换成ijk可以正常播放

### ISSUE THREAD

**Issue by 752375734** [CarGuo/GSYVideoPlayer#2312]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
exo播放MP4失败，但是切换成ijk可以正常播放
## 问题机型/系统：
所有机型
## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤
这个链接 ：http://v.kjjl100.com/zbkhf/2020cjykb/60.mp4
问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
看了下 log  应该是系统的 MediaCodec 对该视频的编码存在不兼容，解析时获取参数失败。
