### ISSUE TITLE
请问，怎么可以让底部状态栏不会点击消失呢

### ISSUE THREAD

**Issue by zhang26** [CarGuo/GSYVideoPlayer#2313]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by zhang26** [comment]
不好意思，我是想让底部的状态栏长存，一直显示，按照您说的，在GSYVideoControlView中并没有找到对应的设置方法

**Comment by CarGuo** [comment]
changeUiToxxxxxxxx

比如 StandardGSYVideoPlayer 中的 changeUiToPlayingBufferingClear 等

 setViewShowState(mBottomContainer, INVISIBLE);

**Comment by zhang26** [comment]
谢谢，解决了，我还想请教一个问题，如果我的播放器只占屏幕的中间一部分，然后我现在想点击全屏按钮的时候让播放器充满整个屏幕，请问该如何处理

**Comment by CarGuo** [comment]
e m???? 不是很理解

**Comment by zhang26** [comment]
就是说我现在页面上最中间一块是这个播放器，然后其他部分是一些其他组件，然后我想在点击全屏按钮的时候让播放器占满整个屏幕

**Comment by CarGuo** [comment]
这种 demo 不是有吗？

**Comment by zhang26** [comment]
我看demo中的是类似的进入头条内种方式，写的一个list，效果不一样啊

**Comment by CarGuo** [comment]
detailplayer  之类的页面啊，你只是把播放控件布局调整而已。

**Comment by zhang26** [comment]
我刚试了，有个问题，我的屏幕是横向的，然后我的播放器窗口是局部的，我现在点击全屏按钮，按钮发生变化，然后窗口没有变化，再次点击全屏按钮屏幕变成纵向的，请问应该怎么解决，我想要点击全屏按钮变成全屏的，不希望他变成纵向的

**Comment by zhang26** [comment]
方便加您个联系方式吗，或者您加我，有一些不太懂的地方想像您请教请教
