### ISSUE TITLE
想请问下，so包下不下来，有没有什么其他导入方式

### ISSUE THREAD

**Issue by Zhangxd77** [CarGuo/GSYVideoPlayer#2314]
## 问题描述：
编译过程中，下面这几个so包下不下来，想请问有没有so包导入方式，不依赖的
//根据你的需求ijk模式的so
implementation 'com.shuyu:gsyVideoPlayer-armv5:7.1.1'
implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.1'
implementation 'com.shuyu:gsyVideoPlayer-arm64:7.1.1'
implementation 'com.shuyu:gsyVideoPlayer-x64:7.1.1'
implementation 'com.shuyu:gsyVideoPlayer-x86:7.1.1'

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
项目里不是就有了吗？所以so

**Comment by Zhangxd77** [comment]
公司电脑是不能上外网，所以只能拍照这种形式了，抱歉

他就是会编译在这里报这几个包下不下来，我另一个电脑之前同样代码是可以正常跑的，
但是这个电脑就不行了，我不知道是不是不能上外网原因，还烦请您帮看看
![image](https://user-images.githubusercontent.com/20806535/66728564-53260e80-ee78-11e9-974e-7f59ddad6889.png)
![image](https://user-images.githubusercontent.com/20806535/66728593-6df88300-ee78-11e9-9453-f240686e7533.png)

**Comment by Zhangxd77** [comment]
implementation 'com.shuyu:gsyVideoPlayer-armv5:6.0.3'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'
    implementation 'com.shuyu:gsyVideoPlayer-x86:6.0.3'

项目是单独这么依赖的这几个

**Comment by CarGuo** [comment]
不是，我的意思是，你把github项目下来下来，里面就有了so
