### ISSUE TITLE
请问如何可以让整个项目只保持横向，不会纵向

### ISSUE THREAD

**Issue by zhang26** [CarGuo/GSYVideoPlayer#2315]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
？？？？

**Comment by zhang26** [comment]
我现在想要把这个播放器放到tv上，不想让他旋转屏幕

**Comment by CarGuo** [comment]
这个就是 AndroidManifset 配置的啊

**Comment by zhang26** [comment]
但是项目中有一些地方，比如播放的时候点击返回按钮，他会切成竖屏

**Comment by CarGuo** [comment]
这个你不使用代码中的旋转就好了

**Comment by zhang26** [comment]
现在是这样，我现在用的是exo，窗口局部开始播放，点击全屏按钮，进入全屏，但是进度条在走，屏幕没有反应，然后再次点击全屏不论怎么点都是进度条在走，屏幕不动，请问该如何解决

**Comment by CarGuo** [comment]
不是很理解，我这边只能从 demo 帮你去复现问题

**Comment by zhang26** [comment]
我用demo中的DetailPlayer，去掉方向旋转，默认方向为横向，然后把布局改成这样
![图片](https://user-images.githubusercontent.com/42343371/66740425-c4c88180-eea5-11e9-9219-7249d2728429.png)，其他没有改动

**Comment by zhang26** [comment]
如上图，我现在点击播放，然后点击全屏，画面进入全屏，但是只有进度条在走，画面卡住不动，然后取消全屏进度条继续前进，画面黑屏，继续操作依然是这样，请问应该怎么解决

**Comment by zhang26** [comment]
demo可以复现
