### ISSUE TITLE
锁屏后解锁黑屏

### ISSUE THREAD

**Issue by kennir** [CarGuo/GSYVideoPlayer#2316]
## 问题描述：

在播放时锁屏，然后解锁，会出现黑屏

## 问题机型/系统：

OPPO

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'`

相关问题 
#2306

**Comment by CarGuo** [comment]
R9M？
什么型号和什么版本号？

**Comment by kennir** [comment]
目前发现oppo R11S / vivo NEX都有这个情况

**Comment by kennir** [comment]
@CarGuo  感觉是锁屏和放置到后台再回来的事件处理不一样导致的，我们回来没有要求自动播放，如果自动播放了就不会黑

**Comment by CarGuo** [comment]
我明白你的意思了，你可能需要的是 setShowPauseCover 设置为 true 的效果 
<img width="693" alt="image" src="https://user-images.githubusercontent.com/10770362/66738943-36063580-eea2-11e9-85a1-370711a47747.png">

**Comment by kennir** [comment]
@CarGuo  我试一下，似乎回来是不是黑屏也不是必定的，我测下来5次里有1次不黑

**Comment by CarGuo** [comment]
你的问题时，暂停后，锁屏，然后解锁，会出现黑屏，点继续播放可以正常出现画面？
