### ISSUE TITLE
demo中DetailPlayer修改布局后播放视频切换全屏画面不动，进度条前进

### ISSUE THREAD

**Issue by zhang26** [CarGuo/GSYVideoPlayer#2318]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。
demo中的DetailPlayer，去掉方向旋转，默认方向为横向，然后把布局改成这样，如图，我现在点击播放，然后点击全屏，画面进入全屏，但是只有进度条在走，画面卡住不动，然后取消全屏进度条继续前进，画面黑屏，继续操作依然是这样，请问应该怎么解决

![](https://user-images.githubusercontent.com/42343371/66740425-c4c88180-eea5-11e9-9219-7249d2728429.png)

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by zhang26** [comment]
大佬，在吗

**Comment by zhang26** [comment]
@CarGuo

**Comment by CarGuo** [comment]
我还是不是很理解，detail模式，全屏代码中在config中，这个又和旋转类有关，如果你需要自定义，看源码修改就好啦

**Comment by zhang26** [comment]
现在是这样，旋转内个解决了，我把布局设置成上边内样，然后播放视频，点击全屏，这时候界面会卡住不动，然后进度条一直在走，请问是什么原因导致的呢

**Comment by c4jeff** [comment]
> 现在是这样，旋转内个解决了，我把布局设置成上边内样，然后播放视频，点击全屏，这时候界面会卡住不动，然后进度条一直在走，请问是什么原因导致的呢

请问黑屏卡住不动，进度条在走 最后是怎么解决的？
