### ISSUE TITLE
rtsp 格式播放不了，报错如下！

### ISSUE THREAD

**Issue by 121104115wyb** [CarGuo/GSYVideoPlayer#232]
rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov    播放链接（在其他非开源播放器上可以播放）

05-17 10:13:36.345 28386-28833/com.example.gsyvideoplayer E/IJKMEDIA: rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov: Protocol not found
05-17 10:13:36.345 28386-28639/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
05-17 10:13:36.358 28386-28386/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
05-17 10:13:36.359 28386-28386/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Againrtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov
05-17 10:13:36.370 28386-28639/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by kinghom** [comment]
同问，希望楼主可以解答一下，能否播放rtsp流视频以及如何播放rtsp

**Comment by CarGuo** [comment]
需要自行编译so，替换了项目so即可。编译方式首页有，在module.sh上使能对应协议支持

**Comment by zhangle1** [comment]
http://download.csdn.net/detail/hebeixmg/9604675  这里有编译好的  cv一下就好了 亲测可用

**Comment by CarGuo** [comment]
0.6.0的注意修改下ijk的远程以来版本的版本号

**Comment by qq328848298** [comment]
请问RTSP客户端播放时，返回461 Unsupported transport的RTSP消息错误码，通常会是什么原因？如何解决



At 2017-05-31 10:22:36, "zhangle1" <notifications@github.com> wrote:


http://download.csdn.net/detail/hebeixmg/9604675 这里有编译好的 cv一下就好了 亲测可用

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/207 link

**Comment by CarGuo** [comment]
试试ex so的2.0.3版本，详见github首页

**Comment by puyanlin668** [comment]
请问楼主，怎么样才能支持rtsp播放啊，难道要自己编译so文件吗，支持在Android7.0播放吗，是64位的CPU

**Comment by CarGuo** [comment]
支持，rtsp使用第三种依赖

**Comment by jj8401** [comment]
@CarGuo 我将 build.gradle 修改为 
compile fileTree(dir: 'libs', include: ['*.jar'])

    //compile project(':gsyVideoPlayer-java')
    //compile project(':gsyVideoPlayer-armv5')
    //compile project(':gsyVideoPlayer-armv7a')
    //compile project(':gsyVideoPlayer-armv64')
    //compile project(':gsyVideoPlayer-x86')
    //compile project(':gsyVideoPlayer-x86_64')

    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    //compile project(':gsyVideoPlayer-ex_so')

    compile 'com.shuyu:gsyVideoPlayer-java:2.0.9'

//    compile 'com.shuyu:gsyVideoPlayer-armv5:2.0.9'
//    compile 'com.shuyu:gsyVideoPlayer-armv7a:2.0.9'
//    compile 'com.shuyu:gsyVideoPlayer-arm64:2.0.9'
//    compile 'com.shuyu:gsyVideoPlayer-x64:2.0.9'
//    compile 'com.shuyu:gsyVideoPlayer-x86:2.0.9'

    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    compile 'com.shuyu:gsyVideoPlayer-ex_so:2.0.9'

并在 RecyclerItemNormalHolder中将一个 url 替换为 局域网rtsp，setCacheWithPlay 设置为 false，但是仍然不能播放，是什么原因呢

**Comment by rebertBen** [comment]
RTSP流协议不支持，报错：rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov 播放链接（在其他非开源播放器上可以播放）

05-17 10:13:36.345 28386-28833/com.example.gsyvideoplayer E/IJKMEDIA: rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov: Protocol not found
05-17 10:13:36.345 28386-28639/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by CarGuo** [comment]
@rebertBen 看readme，用ex_so，然后看问题集锦

**Comment by rebertBen** [comment]
不行，还是报错。
2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo E/IJKMEDIA: rtsp://10.1.2.47/10.1.2.4_hk.sdp: Protocol not found
2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25529]
2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_FLUSH:
2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_ERROR: 0
2019-07-04 16:45:53.410 25359-25528/com.bo.testdemo I/IJKMEDIA: SDL_RunThread: [25528] ff_vout
2019-07-04 16:45:53.411 25359-25359/com.bo.testdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by Shangege337X** [comment]
> 不行，还是报错。
> 2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo E/IJKMEDIA: rtsp://10.1.2.47/10.1.2.4_hk.sdp: Protocol not found
> 2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25529]
> 2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_FLUSH:
> 2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_ERROR: 0
> 2019-07-04 16:45:53.410 25359-25528/com.bo.testdemo I/IJKMEDIA: SDL_RunThread: [25528] ff_vout
> 2019-07-04 16:45:53.411 25359-25359/com.bo.testdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

最后解决了吗？大哥？我也出现了这个原因，看楼上说是更新SO编译库，正准备去尝试看下

**Comment by rebertBen** [comment]
> > 不行，还是报错。
> > 2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo E/IJKMEDIA: rtsp://10.1.2.47/10.1.2.4_hk.sdp: Protocol not found
> > 2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25529]
> > 2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_FLUSH:
> > 2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_ERROR: 0
> > 2019-07-04 16:45:53.410 25359-25528/com.bo.testdemo I/IJKMEDIA: SDL_RunThread: [25528] ff_vout
> > 2019-07-04 16:45:53.411 25359-25359/com.bo.testdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
> 
> 最后解决了吗？大哥？我也出现了这个原因，看楼上说是更新SO编译库，正准备去尝试看下

没有尝试，我换了一个播放器框架，你试试，回头告诉我一下。

**Comment by Shangege337X** [comment]
今天早上尝试了，确实是这个问题，我项目里导入的是bibibi的源so编译库依赖，好像是不支持rtsp以及https协议，需要自己去重新编译一遍，改里面的一些配置，生成so文件，然后放入项目里就行了，折腾了几天终于解决了！


------------------ 原始邮件 ------------------
发件人: "rebertBen"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 中午11:09
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "印象"<190699030@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [CarGuo/GSYVideoPlayer] rtsp 格式播放不了，报错如下！ (#232)



  
不行，还是报错。
 2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo E/IJKMEDIA: rtsp://10.1.2.47/10.1.2.4_hk.sdp: Protocol not found
 2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25529]
 2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_FLUSH:
 2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_ERROR: 0
 2019-07-04 16:45:53.410 25359-25528/com.bo.testdemo I/IJKMEDIA: SDL_RunThread: [25528] ff_vout
 2019-07-04 16:45:53.411 25359-25359/com.bo.testdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
  
最后解决了吗？大哥？我也出现了这个原因，看楼上说是更新SO编译库，正准备去尝试看下
  
没有尝试，我换了一个播放器框架，你试试，回头告诉我一下。

**Comment by rebertBen** [comment]
厉害了




------------------ 原始邮件 ------------------
发件人: "Shangege337X"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 中午11:13
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "雨寒"<409342223@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CarGuo/GSYVideoPlayer] rtsp 格式播放不了，报错如下！ (#232)



今天早上尝试了，确实是这个问题，我项目里导入的是bibibi的源so编译库依赖，好像是不支持rtsp以及https协议，需要自己去重新编译一遍，改里面的一些配置，生成so文件，然后放入项目里就行了，折腾了几天终于解决了！ 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "rebertBen"<notifications@github.com>; 
 发送时间: 2019年7月25日(星期四) 中午11:09 
 收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>; 
 抄送: "印象"<190699030@qq.com>;"Comment"<comment@noreply.github.com>; 
 主题: Re: [CarGuo/GSYVideoPlayer] rtsp 格式播放不了，报错如下！ (#232) 
 
 
 
    
 不行，还是报错。 
  2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo E/IJKMEDIA: rtsp://10.1.2.47/10.1.2.4_hk.sdp: Protocol not found 
  2019-07-04 16:45:53.409 25359-25529/com.bo.testdemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25529] 
  2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_FLUSH: 
  2019-07-04 16:45:53.409 25359-25527/com.bo.testdemo D/IJKMEDIA: FFP_MSG_ERROR: 0 
  2019-07-04 16:45:53.410 25359-25528/com.bo.testdemo I/IJKMEDIA: SDL_RunThread: [25528] ff_vout 
  2019-07-04 16:45:53.411 25359-25359/com.bo.testdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0) 
    
 最后解决了吗？大哥？我也出现了这个原因，看楼上说是更新SO编译库，正准备去尝试看下 
    
 没有尝试，我换了一个播放器框架，你试试，回头告诉我一下。

**Comment by ygknight** [comment]
rtsp请求格式为OPTIONS 如何更换为SETUP类型？

**Comment by EarlJiRH** [comment]
那个换播放器框架的大佬能给一下您的播放器地址吗？那个改配置的大佬，资源能共享一下吗？

**Comment by zhaoxiaolang** [comment]
> ###
> **[ghost](/ghost) ** commented [Jul 25, 2019](#issuecomment-514878156) via email 大佬，有哪个rtsp包没

**Comment by kinghom** [comment]
已经收到你的飞鸽传书啦....

**Comment by ygknight** [comment]
GSYTech&nbsp;




杨州慢
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月18日(星期五) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] rtsp 格式播放不了，报错如下！ (#232)





  

 
**ghost ** commented Jul 25, 2019 via email 大佬，有哪个rtsp包没

**Comment by ygknight** [comment]
GSYTech&nbsp;




杨州慢
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月18日(星期五) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] rtsp 格式播放不了，报错如下！ (#232)





 已经收到你的飞鸽传书啦....
