### ISSUE TITLE
截图问题请教

### ISSUE THREAD

**Issue by wyw1267** [CarGuo/GSYVideoPlayer#2320]
大佬，刚学习播放器的架构，想请教一下现在播放器截图用的什么方案？能做到精准截图（非I帧截图）么。 截图后，是否可以先显示，然后再手动保存。多谢了

**Comment by CarGuo** [comment]
就是播放到哪里，从画面上扣出来的，你看源码。

**Comment by wyw1267** [comment]
这个我看了，就是通过getbitmap来获取，但是这样取出来的数据并不是原始的视频帧数据吧。
我想了解一下，能不能在通过MediaCodec硬解码的情况下，拿出原始的视频帧数据的图片，比如4K的码流，拿出来的图片应该也是4K的。通过从画面上扣的方式只能拿view处理渲染显示之后的图片了。
还望大佬指教啊

**Comment by CarGuo** [comment]
你可以用 OpenGL 去实现，或者你用 系统 MediaCodec 去抠出来也行
