### ISSUE TITLE
是否支持在视频进度条上 进行  【打点】

### ISSUE THREAD

**Issue by ppg408331701** [CarGuo/GSYVideoPlayer#2321]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

是否支持在视频进度条上 进行  【打点】
![image](https://raw.githubusercontent.com/ppg408331701/SemicircleProgress/master/img/WechatIMG275.jpeg)

点击某个打点信息后，控制到对应的时间节点

**Comment by CarGuo** [comment]
类似需求可自己自定义实现
