### ISSUE TITLE
recycleview 下拉刷新 图片remove导致封面图不展示

### ISSUE THREAD

**Issue by heyangJob** [CarGuo/GSYVideoPlayer#2322]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

视频列表，下拉刷新数据，由于imageview是一个，每次刷新都是先移除，导致下拉刷新，封面图被移除

## 问题机型/系统：

真机 华为荣耀9 Android8.0

## GSY依赖版本

implementation   api 'com.shuyu:gsyVideoPlayer-java:6.0.3'

## Demo中的复现步骤

问题代码：(如果有)
```
和onCreateViewHolder一样
 @Override
    protected BaseViewHolder onCreateDefViewHolder(ViewGroup parent, int viewType) {
        switch (viewType) {
            case ClassPhotoBean.PHOTO_VIDEO:
                gsyVideoOptionBuilder = new GSYVideoOptionBuilder();
                imageView = new CustomImageView(mContext);
                break;
        }
        return super.onCreateDefViewHolder(parent, viewType);
    }

onBind

        //增加封面
        ViewGroup.LayoutParams playerParams = gsyVideoPlayer.getLayoutParams();
        playerParams.height = Constant.WINDOW_WIDTH * 9 / 16;
        imageView.setLayoutParams(playerParams);

        if (imageView.getParent() != null) {
            ViewGroup viewGroup = (ViewGroup) imageView.getParent();
            viewGroup.removeView(imageView);
        }
        
        imageView.setUrlAfterMeasureLayout(imgUrl, 9f / 16, R.drawable.default_img_169);

     每次下拉刷新 数据源刷新了  image先移除了，没有添加了
   

```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
这并不是框架的 issue

**Comment by heyangJob** [comment]
请问这种封面图这么添加，多布局的 每次刷新adapter都将上次的image移除的，下面的添加方法也走了

**Comment by CarGuo** [comment]
比如 demo 的 SampleCoverVideo

**Comment by heyangJob** [comment]
用的就是 SampleCoverVideo

**Comment by CarGuo** [comment]
SampleCoverVideo 没有所谓的外部添加 imageView 的逻辑啊

**Comment by heyangJob** [comment]
多谢大佬，我用的是SampleCoverVideo这个控件，但是使用还是之前的方式
`  //增加封面
        ViewGroup.LayoutParams playerParams = gsyVideoPlayer.getLayoutParams();
        playerParams.height = Constant.WINDOW_WIDTH * 9 / 16;
        imageView.setLayoutParams(playerParams);

        if (imageView.getParent() != null) {
            ViewGroup viewGroup = (ViewGroup) imageView.getParent();
            viewGroup.removeView(imageView);
        }

        imageView.setUrlAfterMeasureLayout(imgUrl, 9f / 16, R.drawable.default_img_169);

        if (TextUtils.isEmpty(videoUrl)) {
            return;
        }

        //防止错位，离开释放
        //gsyVideoPlayer.initUIState();
        gsyVideoOptionBuilder
                .setIsTouchWiget(false)
                .setThumbImageView(imageView)
                .setUrl(videoUrl)
                .setVideoTitle(title)
                .setCacheWithPlay(false)
                .setRotateViewAuto(true)
                .setLockLand(true)
                .setPlayTag(TAG)
                .setShowFullAnimation(false)
                .setNeedLockFull(true)
                .setPlayPosition(position)
                .setVideoAllCallBack(new GSYSampleCallBack() {
                    @Override
                    public void onPrepared(String url, Object... objects) {
                        super.onPrepared(url, objects);

                    }

                    @Override
                    public void onQuitFullscreen(String url, Object... objects) {
                        super.onQuitFullscreen(url, objects);
                    }

                    @Override
                    public void onEnterFullscreen(String url, Object... objects) {
                        super.onEnterFullscreen(url, objects);
                        gsyVideoPlayer.getCurrentPlayer().getTitleTextView().setText((String) objects[0]);
                    }
                }).build(gsyVideoPlayer);
        //增加title
        gsyVideoPlayer.getTitleTextView().setVisibility(View.GONE);
        //设置返回键
        gsyVideoPlayer.getBackButton().setVisibility(View.GONE);
        //设置全屏按键功能
        gsyVideoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                resolveFullBtn(gsyVideoPlayer);
            }
        });`

**Comment by CarGuo** [comment]
SampleCoverVideo 上就不要用外部设置进去的封面模式了

**Comment by heyangJob** [comment]
恩 谢大佬，问题已经解决，没好好看源码
