### ISSUE TITLE
如何全局获取视频正在播放？

### ISSUE THREAD

**Issue by barryyanggoing** [CarGuo/GSYVideoPlayer#2323]
## 问题描述：

如题

问题代码：(如果有)
IPlayerManager playManager = PlayerFactory.getPlayManager();
if (playManager != null) {
     ToastUtil.show("是否在播放1" + playManager.isPlaying());
     return playManager.isPlaying();
}
视频在播放的时候返回false，这个不能作为全局是否在播放的获取吗？

**Comment by kyzgxiaoguo** [comment]
兄得，你用的是androidx版本还是suppor版本，

**Comment by barryyanggoing** [comment]
suppor版本

**Comment by kyzgxiaoguo** [comment]
怎么添加的依赖，能给复制一下吗，我这下载不下来怎么 ，，我搞得6.0.0和6.0.3

**Comment by kyzgxiaoguo** [comment]
qq：826189539，，加个好友呗

**Comment by barryyanggoing** [comment]
compile 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    compile 'com.shuyu:gsyVideoPlayer-armv5:6.0.3'
    compile 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'
    compile 'com.shuyu:gsyVideoPlayer-arm64:6.0.3'
    compile 'com.shuyu:gsyVideoPlayer-x64:6.0.3'
    compile 'com.shuyu:gsyVideoPlayer-x86:6.0.3'

**Comment by CarGuo** [comment]
GSYVideoManager.instance().getCurPlayerManager().getMediaPlayer()
