### ISSUE TITLE
倍速播放 2倍速 没有效果

### ISSUE THREAD

**Issue by 704720467** [CarGuo/GSYVideoPlayer#2325]
#1430  问题描述：

倍速播放 2倍速 没有效果，不能2倍速播放！

## 问题机型/系统：

真机 小米MIX2 Android9.0

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.1'  //是否需要ExoPlayer模式
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.0.2'

## Demo中的复现步骤
    Demo中的“带控制DEMO”选项观看 
```

xxxxxxx

```

**Comment by CarGuo** [comment]
可以使用 exoplayer 内核模式尝试
