### ISSUE TITLE
预加载视频问题

### ISSUE THREAD

**Issue by liuhuiAndroid** [CarGuo/GSYVideoPlayer#2326]
感谢分享。
我这边有一个需求是，有80+视频片段，App收到指令后播放对应的视频片段。希望GSYVideoPlayer可以在播第一个视频的时候，开始预加载第二个视频，这样当连续播放第二个视频的开始不会有卡顿现象。我想问下：一个播放内核是不可能同时播放两个视频，能实现这样的需求吗？或者有什么别的方法吗？麻烦指点一下。

**Comment by kennir** [comment]
我也有这样的需求，应该可以通过video cache去实现，不过我只想预载视频的前2分钟吗，不知道是否有sample

**Comment by CarGuo** [comment]
IJK 内核下 这种需求你只能用 MultiSampleVideo 模式去实现，因为只有一个内核的情况下不大可以实现。

对了，exo 的有demo也有 GSYExo2PlayerView 使用 ConcatenatingMediaSource 实现也行
