### ISSUE TITLE
OrientationUtils 代码中存在魔法值，并且书写不规范。

### ISSUE THREAD

**Issue by alanzyz** [CarGuo/GSYVideoPlayer#2328]
## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'`

## Demo中的复现步骤

 

问题代码：(如果有)
line: 115
     } else if (!(mIsLand == 2)) {

**Comment by CarGuo** [comment]
多谢提醒
