### ISSUE TITLE
播放视频时，播放失败

### ISSUE THREAD

**Issue by kyzgxiaoguo** [CarGuo/GSYVideoPlayer#2330]
## 问题描述：播放视频时，播放失败

XXXX发生了这样的问题！

## 问题机型/系统：华为Meta9

例如 真机  Android9.1.1

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
```

## 问题log（如果有）

```

tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

```

**Comment by CarGuo** [comment]
请提供视屏源

**Comment by alanzyz** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1757

**Comment by alanzyz** [comment]
> 请提供视屏源
这里面有这个好像
https://github.com/CarGuo/GSYVideoPlayer/issues/1757

**Comment by kyzgxiaoguo** [comment]
[播放操作视频.zip](https://github.com/CarGuo/GSYVideoPlayer/files/3754591/default.zip)

**Comment by kyzgxiaoguo** [comment]
我的软件播放视频类型是
![image](https://user-images.githubusercontent.com/23161220/67272799-cae6df80-f4ef-11e9-8bc7-06747643c618.png)，都是这种问题，播放了之后自动暂停，然后我看后台log就是播放失败

**Comment by CarGuo** [comment]
你的视频编码和音频编码是什么？？

**Comment by kyzgxiaoguo** [comment]
flv ，mp3,mp4等等格式

**Comment by CarGuo** [comment]
这是容器协议，我说的是编码协议，aac，amr h264这种

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2332
