### ISSUE TITLE
视频总时长获取错误

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#2335]
## 问题描述：
正常播放情况下突然断网导致视频加载失败，返回到上级界面后再次进入视频播放页面点击播放，视频总时间始终是11秒，麻烦大佬看一下

## 问题机型/系统：

真机 红米note3 Android6.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'`
## 截图
![image](https://user-images.githubusercontent.com/13781886/67374342-9f2d2d80-f5b3-11e9-8bfa-4eac3d7b3ebd.png)

**Comment by CarGuo** [comment]
确定下是不是本地缓存导致的

**Comment by zhangyujiu** [comment]
是开启了缓存的

**Comment by CarGuo** [comment]
proxy cache 模式的？ 如果是缓存文件导致的，建议关闭或者切换到 exoplayer 和 exocache
