### ISSUE TITLE
新建一个视频播放器，设置setSeekOnStart画面卡住

### ISSUE THREAD

**Issue by zhang26** [CarGuo/GSYVideoPlayer#2336]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

在一个activity中设置一个播放器，在播放的之前设置进度，开始播放的时候会有两三秒的卡顿，画面卡住不动，进度条在走，播放的是本地文件，求解

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
可以试试用:

 [https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md#20精准的某个时间开始播放](精准的某个时间开始播放)

setSeekOnStart 因为其实需要 prepared 之后，再 seek ，再缓冲

**Comment by zhang26** [comment]
直接加上这个就好了吗

**Comment by CarGuo** [comment]
这个是全局的，如果是 ijk 内核模式，你需要主要不需要的地方吧 "seek-at-start" 去掉

```
VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", startPosition);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by zhang26** [comment]
exo呢

**Comment by zhang26** [comment]
那目前就无法解决了呗

**Comment by CarGuo** [comment]
最多参考 SampleCoverVideo ，你可以做到播放前卡在封面上等待

**Comment by zhang26** [comment]
好的
