### ISSUE TITLE
内核，IJK等添加到何处

### ISSUE THREAD

**Issue by kyzgxiaoguo** [CarGuo/GSYVideoPlayer#2337]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
![image](https://user-images.githubusercontent.com/23161220/67389569-744fd300-f5cd-11e9-96be-72c72f098528.png)

```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by alanzyz** [comment]
就这几行呀，根据自己的需要，添加到application类里

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager
