### ISSUE TITLE
内存泄漏-demo中和自己使用

### ISSUE THREAD

**Issue by yandan66** [CarGuo/GSYVideoPlayer#2339]
## 问题描述：

打开demo中DetailFilterActivity, 不断点击全屏/退出全屏引发内存泄漏, 看了下mContext引发的

## 问题机型/系统：

真机 小米6 Android9.0 API 28

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的DetailFilterActivity页面打开后不断点击全屏/退出全屏会出现这个问题。
![error](https://ae01.alicdn.com/kf/Hcbe05fcfaf56405e9427c96f02dc3f7es.png)

**Comment by alanzyz** [comment]
截图不全，再添加喜爱。，最好是点进去的截图。另外作者之前写的那些不能修复的泄漏你看了么

**Comment by alanzyz** [comment]
另外升级最新版本，7.1.1

**Comment by CarGuo** [comment]
ENPlayView 的问题我记得我修复过，如果还有问题，建议 getLayoutId 替换为自己的播放按键

**Comment by yandan66** [comment]
等我去拉下最新分支试试
