### ISSUE TITLE
How to set setOnSeekBarChangeListener() in RecyclerView adapter

### ISSUE THREAD

**Issue by Rupesh2Singh** [CarGuo/GSYVideoPlayer#234]
Hi CarGuo
I want to know how to set Seekbar in recyclerview adapter so that at specific time or percentage of video play interval it will open some dialogbox/custom message in video playback.

**Comment by RudreshJR** [comment]
Hi 
I also want same thing like this.. Can  u tell how to get progress of video ,means how much percentage video has watched

**Comment by Rupesh2Singh** [comment]
finally i found the solution and it's working fine to display custom dialog box by calling
holder.gsyVideoPlayer.mProgressBar.setOnSeekBarChangeListener()
