### ISSUE TITLE
网络变化重试和错误状态下点击逻辑能否优化下

### ISSUE THREAD

**Issue by lhholylight** [CarGuo/GSYVideoPlayer#2340]
网络状态变化后重试前能不能先加个判断，判断下当前的网络状态在进行重试啊，不然断网了忽然在重试画面闪一下会很怪异。
另外错误状态下（CURRENT_STATE_ERROR）点击surface_container的逻辑是从头重新播放，我看有好多地方出现异常后重播都是从头开始的，能否改成从异常点开始播放啊。上面网络状态的还好修改，后面的这个如果用你的库的不好调整。

**Comment by vincent19921017wang** [comment]
哥们，有本事自己写啊~
人家好心开源，你白嫖完就算了，还要在这泄愤？
脑子呢

**Comment by CarGuo** [comment]
1、netWorkErrorLogic 可以继承后自定义逻辑。
2、isShowNetConfirm 方法可以判断，也可以继承。
3、clickStartIcon 、startButtonLogic 和 、onClick 也可以继承没，在源码继承上修改你要的逻辑就可以了······

开源库不会封装到面面俱到的。
