### ISSUE TITLE
视频声音和画面不同步

### ISSUE THREAD

**Issue by heyangJob** [CarGuo/GSYVideoPlayer#2342]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

视频和声音不同步

## 问题机型/系统：

华为 荣耀青春版9

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤
一样的代码  demo播放正常  我写的播放视频和声音不同步，是不是少了什么设置？我项目的代码是从demo复制过来的，（使用的是SimplePlayer里面的，没有开取硬解码）

问题代码：(如果有)
        gsyVideoPlayer.setUp(videoUrl, true, "测试视频");
       //增加title
        gsyVideoPlayer.getTitleTextView().setVisibility(View.VISIBLE);
        //设置返回键
        gsyVideoPlayer.getBackButton().setVisibility(View.VISIBLE);
        //设置旋转
        orientationUtils = new OrientationUtils(this, gsyVideoPlayer);
        //设置全屏按键功能,这是使用的是选择屏幕，而不是全屏
        gsyVideoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                orientationUtils.resolveByClick();
            }
        });
        //是否可以滑动调整
        gsyVideoPlayer.setIsTouchWiget(true);
        //设置返回按键功能
        gsyVideoPlayer.getBackButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onBackPressed();
            }
        });
        gsyVideoPlayer.startPlayLogic();

## 问题log（如果有）

```

xxxxxxx

```

**Comment by heyangJob** [comment]
设置硬解码就可以，这个视频码率比较高 ，属于高清视频

**Comment by heyangJob** [comment]
使用硬解码 切换全屏时，先展示封面图，然后到视频，感觉不是连贯的 封面图使用的是SampleCoverVideo

**Comment by CarGuo** [comment]
软解码可以试试问题集锦的丢帧处理

**Comment by heyangJob** [comment]
我很奇怪的的是  你用的demo就没问题 ，我把你demo的代码复制过来，跑起来程序，就发现 音频和画面不同步。

**Comment by CarGuo** [comment]
😂这么诡异，i have not idea

**Comment by heyangJob** [comment]
使用硬解码 横竖屏切换 视频会黑2秒钟。。。。

**Comment by CarGuo** [comment]
所以你需要我上面给你的那个类，demo针对硬解码做了处理

**Comment by heyangJob** [comment]
大佬，用了你给我的那个类 还是黑屏

**Comment by heyangJob** [comment]
我直接使用这个控件的 MediaCodecVideo

**Comment by heyangJob** [comment]
大佬 ，好奇怪，我新建一个项目，引入你的库，写了一个demo，使用软解码播放视频，画面和音频是同步的，把代码复制我现在的项目中，就出现画面和音频不同步，开启硬解码就同步了。难道那个地方还配置了什么。。。。。

**Comment by heyangJob** [comment]
大佬 ，我找的原因了 我打包的时候使用了
//        ndk {
//            abiFilters "armeabi"
//        }
