### ISSUE TITLE
如何记住视频地址的播放进度

### ISSUE THREAD

**Issue by sam629205** [CarGuo/GSYVideoPlayer#2345]
重复打开视频地址时，每次都默认从头开始播放。现在我自己采取的解决方法时，2s延时之后打开上次自己记住的播放进度，但是感觉这个方式有点low。

**Comment by CarGuo** [comment]
你可以继承后，重载在 `public void onAutoCompletion() ` ，在 super 之前记录

**Comment by sam629205** [comment]
记录进度没问题，但是播放的时候setup这个方法并没有传递默认跳转位置的参数，不知道怎么从中间开始播放。

**Comment by CarGuo** [comment]
setSeekonStart 或者看问题集锦中也有另外一个全局方法…
