### ISSUE TITLE
准备播放时，从显示占位图到显示播放画面时有一帧黑屏的问题

### ISSUE THREAD

**Issue by zmmzhaomaomao** [CarGuo/GSYVideoPlayer#2347]
## 问题描述：
作者您好：目前我使用的是6.0.3版本，由于原版在点击播放按钮后，会将占位图隐藏，显示底色和加载进度进行加载，直到加载成功后显示播放画面。我们在此基础上做了一些修改，在 changeUiToPlayingShow()中才将mThumbImageViewLayout的显示状态设置为INVISIBLE，但是我们在使用的时候发现占位图到播放画面的显示中会有一帧显示底色（即，changeUiToPlayingShow()方法执行完后，播放器还未将内容渲染过来），我尝试在pauseLogic和startAfterPrepared调用之后才将mThumbImageViewLayout设置为INVISIBLE 但是也还是会有几帧的底色。参考其他App，例如微博、抖音，它们从占位图到播放画面一气呵成，中间不会有底色问题，体验比较优。我想请教，我们要如何解决这个问题呢？

XXXX发生了这样的问题！

## 问题机型/系统：

 真机 小米8 Android 8.1.0  和 华为荣耀 nova4 Android 9

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

由于Demo没有进行改造，是直接从底色状态到播放画面的，也显示的比较好。但是我们需要在加载时，显示占位图。

问题代码：(如果有)
```
@Override
    protected void changeUiToPlayingShow() {
        Debuger.printfLog("changeUiToPlayingShow");

        setViewShowState(llBuffering, INVISIBLE);
        if (!isShowOnlyClose) {
            setViewShowState(mTopContainer, VISIBLE);
            setViewShowState(mBottomContainer, VISIBLE);
            setViewShowState(mStartButton, VISIBLE);

//            setViewShowState(mThumbImageViewLayout, INVISIBLE);
            setViewShowState(mThumbImageViewLayout, VISIBLE);
//            setViewShowState(mBottomProgressBar, INVISIBLE);
            setViewShowState(mLockScreen, (mIfCurrentIsFullscreen && mNeedLockFull) ? VISIBLE : GONE);

            ibVoice2.setVisibility(View.VISIBLE);
        }
        if (isShowVoice) {
            setShowVoice(true, mShowVoiceCurrTimeLeftMargin);
        }
        if (mLoadingProgressBar instanceof ENDownloadView) {
            ((ENDownloadView) mLoadingProgressBar).reset();
        }
        updateStartImage();
    }
```

**Comment by zmmzhaomaomao** [comment]
研究了下饺子播放器的实现，发现它的addTextureView的调用时机更早（在开始播放时，prepared之前）。目前已有思路实现，但暂时还不清楚作者将该动作放在后面的动机，待后续更新补充。


思路：重写startAfterPrepared，去除方法实现中的addTextureView调用；重写prepareVideo 添加addTextureView调用

**Comment by CarGuo** [comment]
demo 的 SampleCoverVideo 不是可以吗？

**Comment by zmmzhaomaomao** [comment]
> demo 的 SampleCoverVideo 不是可以吗？

- -！不好意思，刚刚验证了下确实可以。。   我研究下它的实现。。。谢谢

**Comment by panhongx** [comment]
刚解决完这个问题。虽然Issue被关了，但还是补充说下吧。
SampleCoverVideo 确实可以解决刚播放占位图和第一帧之间的黑屏，但添加Cover的时候需要注意View的尺寸。刚开始我是直接放了一个ImagView进去，然后这个ImageView被拉伸成全屏了，体验不太好。解决的方法是在Cover外加了一层View，这个外层的view可以全屏，但是imageView还是保持原来的宽高比。

```
RelativeLayout coverContainer = new RelativeLayout(this);
ImageView imageView = new ImageView(this);
RelativeLayout.LayoutParams lp = new RelativeLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT);
lp.width = targetWidth;  // 保持宽高比的情况下，根据Cover图片实际宽高和屏幕尺寸计算
lp.height = targetHeight;
lp.addRule(RelativeLayout.CENTER_IN_PARENT, RelativeLayout.TRUE);
imageView.setLayoutParams(lp);
coverContainer.addView(imageView, lp);

GlideApp.with(this).load(mCoverUrl)
		.apply(RequestOptions.bitmapTransform(new RoundedCorners(Utils.dp2px(5))))
		.into(imageView);

mVideoPlayer.setThumbImageView(coverContainer);

```

**Comment by ymwm-lxl** [comment]
这一个很有用，翻了Issuse 才能找到这个解决办法，希望在 wiki 中有记录

**Comment by weifengteng** [comment]
接到项目中就是会出现封面到播放画面之间闪一下黑屏，心碎……

**Comment by CarGuo** [comment]
@weifengteng 参考现在 demo 中的 SampleCoverVideo

**Comment by weifengteng** [comment]
@CarGuo   昨天研究了一天，我用的版本和遇到的问题以及处理过程和@zmmzhaomaomao  一样，看了下SampleCoverVideo没有什么特殊处理，全靠播放器内部逻辑处理隐藏和显示。我做了同样的接入，然后再changeUiToPlayingShow()方法中做延迟隐藏封面，还是会闪黑屏，从现在的SampleCoverVideo中确实看不出来什么……

**Comment by weifengteng** [comment]
@zmmzhaomaomao 可否介绍一下你的解决办法？

**Comment by weifengteng** [comment]
@CarGuo 
@Override
    public void onSurfaceAvailable(Surface surface) {
        super.onSurfaceAvailable(surface);
        if (GSYVideoType.getRenderType() != GSYVideoType.TEXTURE) {
            if (mThumbImageViewLayout != null && mThumbImageViewLayout.getVisibility() == VISIBLE) {
                mThumbImageViewLayout.setVisibility(INVISIBLE);
            }
        }
    }

在这个方法里 mThumbImageViewLayout.setVisibility(INVISIBLE); 延迟150ms执行解决了黑屏问题

**Comment by GHMike** [comment]
在不添加封面的情况下还是黑屏闪一下
