### ISSUE TITLE
求问播放器如何设置下次进来自动上次位置进行播放

### ISSUE THREAD

**Issue by cherysky** [CarGuo/GSYVideoPlayer#2348]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
目前的播放器我设置了exo缓存，但是好像没什么用，我上次播放到一半退出，下次再进来又重头开始播放了，该怎么做成记住上次的位置下次直接播放

## 问题机型/系统：

 真机 小米note2 Android7.0

## GSY依赖版本

  implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
//是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.1'
//根据你的需求ijk模式的so
    implementation 'com.shuyu:gsyVideoPlayer-armv5:7.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-arm64:7.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-x64:7.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-x86:7.1.1'

## Demo中的复现步骤

Demo中的播放器都是这个问题，每次进来都是重新开始播放

问题代码：(如果有)
无

## 问题log（如果有）
无

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2345

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2345
