### ISSUE TITLE
getGSYVideoManager().seekTo 不自动播放，需要手动点击播放按钮

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#2349]
播放m3u8 内核 Exo2PlayerManager 
 获取seek 地址 然后去下载，下载成功后 回调  getGSYVideoManager().seekTo(mPlayPosition);
seekto成功了，就是不自动播放，需要手动点击播放按钮才播放

**获取seek 地址**
 @Override
    public void onStopTrackingTouch(SeekBar seekBar) {
        if (mVideoAllCallBack != null && isCurrentMediaListener()) {
            if (isIfCurrentIsFullscreen()) {
                Debuger.printfLog("onClickSeekbarFullscreen");
                mVideoAllCallBack.onClickSeekbarFullscreen(mOriginUrl, mTitle, this);
            } else {
                Debuger.printfLog("onClickSeekbar");
                mVideoAllCallBack.onClickSeekbar(mOriginUrl, mTitle, this);
            }
        }
        if (getGSYVideoManager() != null && mHadPlay) {
            try {
                int time = seekBar.getProgress() * getDuration() / 100;

            downVideoSeek(time);

            } catch (Exception e) {
                Debuger.printfWarning(e.toString());
            }
        }
        mHadSeekTouch = false;
    }

**下载成功后 回调  getGSYVideoManager().seekTo(mPlayPosition);**
  public void start(Module_VideoSourceEntity source) {
            //onVideoPause();
            //setSeekOnStart(time);
            //setStateAndUi(CURRENT_STATE_PREPAREING);
            getGSYVideoManager().seekTo(mPlayPosition);

            //setPlayPosition(time);
//            new Handler().postDelayed(new Runnable() {
//                @Override
//                public void run() {
//                  startPlayLogic();
//                }
//            }, 500);
            //startPlayLogic();
            //startButtonLogic();
        }

上面的方法都试过了就是不播放。

下面这种可以播放不过得重新加载一次
setSeekOnStart(time)
startPlayLogic();

是线程问题，还是哪里需要设置下。

**Comment by CarGuo** [comment]
不是很理解场景

**Comment by yang0000meng** [comment]
相当于播放本地m3u8 文件 ，
当点击SeekBar  时，先判断 本地m3u8内  Seekto 位置 那个切片是否下载成功
不成功先暂停等下载成功后 在seekto  
下载成功后再回调 getGSYVideoManager().seekTo(mPlayPosition); 
这样 seekto 位置跳转成功了，但不自动播放 ，需要手动点击播放按钮才播放。
这样不知道我表达是否清楚
