### ISSUE TITLE
内存泄露？

### ISSUE THREAD

**Issue by General110** [CarGuo/GSYVideoPlayer#235]
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115] local reference table dump:
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       511: 0x15055000 android.widget.RelativeLayout
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       510: 0x1507db40 java.lang.Object[] (3 elements)
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       509: 0x15054c00 com.dodo.dome.view.view.SampleVideo
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       508: 0x1507e160 android.content.res.XmlBlock$Parser
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       507: 0x1329adf0 com.android.internal.policy.PhoneLayoutInflater
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       506: 0x1329adf0 com.android.internal.policy.PhoneLayoutInflater
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       505: 0x15054c00 com.dodo.dome.view.view.SampleVideo
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       504: 0x15050c00 com.dodo.dome.view.view.SampleVideo
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       503: 0x1504cc00 com.dodo.dome.view.view.SampleVideo
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       502: 0x15048c00 com.dodo.dome.view.view.SampleVideo
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]   Summary:
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.support.v7.widget.ContentFrameLayout
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]       492 of com.dodo.dome.view.view.SampleVideo (491 unique instances)
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]         2 of java.lang.Object[] (3 elements) (2 unique instances)
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]         6 of java.lang.Class (5 unique instances)
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.String[] (3 elements)
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]         3 of java.lang.String (3 unique instances)
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.widget.RelativeLayout
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]         4 of com.android.internal.policy.PhoneLayoutInflater (1 unique instances)
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115]         2 of android.content.res.XmlBlock$Parser (2 unique instances)
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115] 
05-17 19:03:06.634 12792-12792/com.dodo.dome A/art: art/runtime/barrier.cc:90] Check failed: count_ == 0 (count_=-1, 0=0) Attempted to destroy barrier with non zero count
05-17 19:03:06.635 12792-12792/com.dodo.dome A/art: art/runtime/runtime.cc:372] Runtime aborting --- recursively, so no thread-specific detail!
05-17 19:03:06.635 12792-12792/com.dodo.dome A/art: art/runtime/runtime.cc:372] 
                                                       
                                                       --------- beginning of crash

**Comment by CarGuo** [comment]
不像是

**Comment by General110** [comment]
05-17 19:03:04.107 12792-12792/com.dodo.dome A/art: art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): **local reference table overflow (max=512)** @CarGuo

**Comment by leveychen** [comment]
我这边也看到内存泄漏了。 显示是GSYVideoPlayer $ Timer  这一块的东西

**Comment by CarGuo** [comment]
我这边目前最新版本Leaks没输出泄漏，如果有麻烦贴下图和log可以吗。
