### ISSUE TITLE
进度条与播放位置不同步

### ISSUE THREAD

**Issue by Achenglove** [CarGuo/GSYVideoPlayer#2352]
## 问题描述：

在视频没有加载完成之前直接拖动进度条到某个位置，然后在视频加载完成后正常播放，进度条跟播放位置不同步

## 问题机型/系统：

 真机 小米Mi MAX3 Android9

## GSY依赖版本

 `com.shuyu:GSYVideoPlayer:6.0.3'`

**Comment by CarGuo** [comment]
请测试最新版本的 demo 是否复现
