### ISSUE TITLE
暂停时图标显示异常

### ISSUE THREAD

**Issue by caiyoufei** [CarGuo/GSYVideoPlayer#2353]
## 问题描述：

暂停时图标显示异常

## 问题机型/系统：

红米6 安卓9.0 miui10

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.1'

## Demo中的复现情况
![GIF (1)](https://user-images.githubusercontent.com/11989916/67848446-491e3400-fb37-11e9-8bad-f4ad3cf9c532.gif)
视频尺寸根据封面大小设置的比例，宽度为200dp
![视频封面图](https://user-images.githubusercontent.com/11989916/67848552-7d91f000-fb37-11e9-815a-f3bbe2c0ccda.jpg)

**Comment by CarGuo** [comment]
不是很理解，但是默认的动画图标不是图片而是View 绘制上去的

**Comment by caiyoufei** [comment]
@CarGuo 就是你看点击暂停的时候，那个按钮动画跑上面去了，但是播放的时候是正常的

**Comment by caiyoufei** [comment]
![GIF](https://user-images.githubusercontent.com/11989916/67856585-71ae2a00-fb47-11e9-8231-9d87e8843fb2.gif)

**Comment by caiyoufei** [comment]
正常情况应该是这样的：
![GIF](https://user-images.githubusercontent.com/11989916/67856850-0e70c780-fb48-11e9-9773-8dd5f8214a13.gif)

**Comment by caiyoufei** [comment]
出现这个情况的原因是，一开始只是一个200dp宽度的view，没有全屏。全屏后就正常展示

**Comment by caiyoufei** [comment]
有没有可能是因为我读取视频后才设置的控件尺寸导致的？
![image](https://user-images.githubusercontent.com/11989916/67857201-ba1a1780-fb48-11e9-9139-e4ec47050c51.png)

**Comment by caiyoufei** [comment]
@CarGuo 测试发现问题产生的原因了，一开始我设置了高度为0，再视频读取到宽高后再设置控件高度，然后就出现了按钮不正确的情况，如果我一开始是match_parent就没有该问题
![image](https://user-images.githubusercontent.com/11989916/67860978-d8384580-fb51-11e9-820a-c144e6b539ca.png)

**Comment by CarGuo** [comment]
直接使用普通图片看看？

**Comment by caiyoufei** [comment]
不是封面图片造成了，我不设置封面，一样的会有这样的情况，在XML中不使用layout_height = "0dp"就好了

**Comment by caiyoufei** [comment]
你不会是说暂停和播放图标用图片吧，刚开始用和这个lib，还没熟悉到这个份上

**Comment by CarGuo** [comment]
有 NormalGSYVideoPlayer

**Comment by caiyoufei** [comment]
好的，Thanks
