### ISSUE TITLE
切换横屏后，视频没有全屏展示

### ISSUE THREAD

**Issue by caopeng000** [CarGuo/GSYVideoPlayer#2354]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

切换横屏后，视频没有全屏展示

## 问题机型/系统：

Mate 30

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

只用的是旧的版本的代码，后来测试再发现在华为meta 30，Android 10版本上切换横屏后，视频没有全屏

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请确定是否配置了 Android Manifset 和 demo是否复现

**Comment by caiyoufei** [comment]
![image](https://user-images.githubusercontent.com/11989916/67857655-f00bcb80-fb49-11e9-9458-342d91256361.png)
@caopeng000 横竖切换和全屏2个方式都要调用

**Comment by CarGuo** [comment]
demo 测试正常，请自行对比demo检查
