### ISSUE TITLE
关于拖动进度条预览的问题

### ISSUE THREAD

**Issue by cherysky** [CarGuo/GSYVideoPlayer#2355]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
在播放器描述里看到有这个功能，但是代码里好像没找到，业务上面需要这个功能，滑动进度条会出现每一帧的预览画面出现，可以说下实现的思路吗？

## 问题机型/系统：

 真机 小米note2 Android7.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
//是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.1'
//根据你的需求ijk模式的so
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.1'
    implementation 'com.android.support:multidex:1.+'

## Demo中的复现步骤

问题代码：(如果有)
暂无

## 问题log（如果有）
暂无

**Comment by CarGuo** [comment]
demo 中的 PreViewGSYVideoPlayer ，如果方便最好是服务器直接给你返回一系列图片地址。
