### ISSUE TITLE
监听底部按钮切换横屏没有全屏，手动设置全屏后，横屏切换到竖屏需要点两次才能回返回？

### ISSUE THREAD

**Issue by snowf07** [CarGuo/GSYVideoPlayer#2357]
`` final OrientationUtils orientationUtils = new OrientationUtils(this, standardGSYVideoPlayer);
        /**
         * 播放视频
         */
        VideoPlayerHelper.getInstance().play(getApplicationContext(), url, false, standardGSYVideoPlayer, null);
        //设置全屏按键功能
        standardGSYVideoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                orientationUtils.resolveByClick();

            }
        });

**Comment by CarGuo** [comment]
看demo

**Comment by snowf07** [comment]
我现在就是想实现能点击按钮切换横屏保持全屏状态，然后可以切回来

**Comment by snowf07** [comment]
现在的问题就是我调用   orientationUtils.resolveByClick();方法能切换横屏，不是全屏状态，
通过调用
``           orientationUtils.resolveByClick();
                //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                standardGSYVideoPlayer.startWindowFullscreen(SimpleActivity.this, true, true);
**能全屏，但是再返回要按两次才能保持竖屏**

**Comment by CarGuo** [comment]
不是很理解你的场景，demo中怎么复现

**Comment by snowf07** [comment]
从竖屏切换到横屏能理解么

**Comment by CarGuo** [comment]
所以你能在 demo 中复述下出现问题的流程吗？

**Comment by snowf07** [comment]
能加个微信不，我拍个视频给你

**Comment by snowf07** [comment]
现在demo也运行不起来
* What went wrong:
A problem occurred configuring root project 'GSYVideoPlayer-master'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.3.11)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.11/kotlin-reflect-1.3.11.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.11/kotlin-reflect-1.3.11.jar'.
            > Remote host closed connection during handshake
   > Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.11)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.3.11/kotlin-stdlib-1.3.11.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.3.11/kotlin-stdlib-1.3.11.jar'.
            > Remote host closed connection during handshake
   > Could not download xercesImpl.jar (xerces:xercesImpl:2.9.1)
      > Could not get resource 'https://jcenter.bintray.com/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar'.
         > Could not GET 'https://jcenter.bintray.com/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar'.
            > Remote host closed connection during handshake

**Comment by snowf07** [comment]
找到原因了，是因为没有设置
       standardGSYVideoPlayer.setAutoFullWithSize(true);导致的
