### ISSUE TITLE
退出后还在缓存视频，很坑啊

### ISSUE THREAD

**Issue by forEveryDay** [CarGuo/GSYVideoPlayer#236]
公司的测试视频文件超大，不仅播放不出来，而且退出后后台还在一直下载

**Comment by forEveryDay** [comment]
发现可以配置是否缓存，可以了

**Comment by forEveryDay** [comment]
不过又发现新问题了，视频播放只有声音，没有画面，地址是：http://test1-store.oss-cn-beijing.aliyuncs.com/5916b4bb12bbb0e45dc2896a.mp4，应该是MP4格式啊

**Comment by CarGuo** [comment]
这个问题一般是视屏编码问题，mp4的视频编码也有很多，目前so支持的是h263.264.265等，如果是mpeg之类的。需要自行更换so,编译so增加你需要的格式
