### ISSUE TITLE
视频界面只有声音没有画面

### ISSUE THREAD

**Issue by langmaobin** [CarGuo/GSYVideoPlayer#2361]
## 问题描述：

单独把demo里面的“无UI界面”类拿出来放到我自己写的测试项目里面播放视频都没问题，但是集成到另一个项目里面播放相同视频地址就只有声音没有画面了

## 问题机型/系统：
华为p30 pro 荣耀6x

## GSY依赖版本

 implementation 'com.shuyu:GSYVideoPlayer:7.1.1'

问题代码：(如果有)
```
videoPlayer.setUp(url, true, "");
videoPlayer.startPlayLogic();
```

**Comment by CarGuo** [comment]
这就很诡异了，要不你切换到 Surface View模式试试

**Comment by langmaobin** [comment]
你好，怎么切换到 Surface View模式呢

Shuyu Guo <notifications@github.com> 于2019年10月31日周四 下午5:48写道：

**Comment by CarGuo** [comment]
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
