### ISSUE TITLE
此版本播放不了rtsp地址视频

### ISSUE THREAD

**Issue by Dreamskya** [CarGuo/GSYVideoPlayer#2363]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

下载此最新GSYVideoPlay工程此时，rtsp地址播放视频，无法播放，出现黑屏现象。以前添加implementation 'com.shuyu:GSYVideoPlayer:6.0.0-beta' 可以进行rtsp播放。

## 问题机型/系统：

真机，MI5 Android版本8.0.0

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:6.0.0-beta' 可以播放rtsp地址视频，此目前最新版本播放不了rtsp地址视频。黑屏现象

## Demo中的复现步骤

就把项目中的其中一个mp4地址更改成rtsp地址测试，不能进行播放。黑屏现象

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
rtsp 需要使用第三种依赖 ex_so 的依赖，同时看问题集锦配置 tcp 等
