### ISSUE TITLE
视频播放中途自动暂停，然后又重新从0开始播放

### ISSUE THREAD

**Issue by Achenglove** [CarGuo/GSYVideoPlayer#2365]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

视频播放到中途过程中，网络不好，然后视频就自动暂停，再自动重头开始重新播放

## 问题机型/系统：

例如 真机 小米MI MAX3 Android9.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
有可能是网络错误导致，请关闭 cache 再试试

**Comment by Achenglove** [comment]
![image](https://user-images.githubusercontent.com/26593441/68001342-a5e82e80-fc9e-11e9-8836-f83ce276322a.png)
就是关闭边播放边缓存这个才会出现的

**Comment by CarGuo** [comment]
你可以看看 onError 回调和网络变化回调里的处理逻辑是否生效

**Comment by Achenglove** [comment]
@CarGuo 我的项目是用Kotlin写的，然后引用了 'com.shuyu:gsyVideoPlayer-java:6.0.3'版本的库，Fragment能自动引入控件，但是换成 'com.shuyu:gsyVideoPlayer-java:7.0.2'以上版本，Fragment就不能找到对应的布局控件id了，这是什么问题啊

**Comment by Achenglove** [comment]
![Y61)$SYOM}4OF$I{ DFUOJ](https://user-images.githubusercontent.com/26593441/68012465-14d87e00-fcc5-11e9-9f03-6a81d76ba211.png)

**Comment by CarGuo** [comment]
这种树煜兼容冲突问题， 7.0 开始是 androidx 的版本，请注意更版本依赖的冲突

**Comment by wangrunxiang** [comment]
同样问题，部分手机，onError回调what 1 extra 1
