### ISSUE TITLE
7.1.1版本-运行报错无法访问IMediaPlayer

### ISSUE THREAD

**Issue by WhatXiao** [CarGuo/GSYVideoPlayer#2366]
问题描述：
直接用android studio3.2.1-运行，无法编译成功。错误: 无法访问IMediaPlayer
找不到tv.danmaku.ijk.media.player.IMediaPlayer的类文件报错无法访问IMediaPlayer

## 问题机型/系统：
真机 华为荣耀v9play Android7.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1

**Comment by CarGuo** [comment]
demo 测试正，请确定是不是依赖冲突等问题

**Comment by WhatXiao** [comment]
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //noinspection GradleCompatible
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0-alpha02'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0-alpha02'

    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'

    //根据你的需求ijk模式的so
    implementation 'com.shuyu:gsyVideoPlayer-armv5:7.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-arm64:7.1.1'
}

**Comment by WhatXiao** [comment]
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        GSYVideoManager.releaseAllVideos();
    }
}
主要就是 GSYVideoManager这个无法引用的感觉，所以建立了一个空项目来只依赖GSY，里面没有其他依赖。

**Comment by CarGuo** [comment]
因为冲突问题我很难去定位，可能什么问题导致打包不进去或者依赖失败

**Comment by WhatXiao** [comment]
好的，谢谢。把项目发给了同事，让他用3.2.1的AS打开可以运行。初步判断可能是开发工具的原因。
