### ISSUE TITLE
SwitchPlay使用时碰到的BUG

### ISSUE THREAD

**Issue by MrZzhouWorld** [CarGuo/GSYVideoPlayer#2367]
## 问题描述：

使用SwitchPlay做列表详情无缝切换时出现问题。
1.列表视频只有在播放时才能进详情，若修改示例代码在暂停时也可进详情，则详情会黑屏。
2.进入详情后，若退出至后台，再从后台进入，正常应该恢复播放，但是没有恢复播放，播放按钮却显示在播放。
3.若从详情返回至列表，列表的播放器先停留在暂停状态，再变成初始状态。

## 问题机型/系统：

例如 华为MATE8 Android8.0以及其余测试机

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

```

**Comment by CarGuo** [comment]
1、 暂停会黑屏是因为切换的渲染层又没有播放，这很正常，你可以试试其他 app 的这种状态下的实现。

2、SwitchUtil 的   gsyVideoPlayer.setReleaseWhenLossAudio(true); 设置为 true

3、这是默认使用了这样的变化，你可以看着自定义处理。
