### ISSUE TITLE
修改播放器上面的按钮图片

### ISSUE THREAD

**Issue by zhangnin** [CarGuo/GSYVideoPlayer#2369]
<moe.codeest.enviews.ENDownloadView
            android:id="@+id/loading"
            android:layout_width="28dp"
            android:layout_height="28dp"
            android:layout_gravity="center"
            android:visibility="invisible" />

        <moe.codeest.enviews.ENPlayView
            android:id="@+id/start"
            android:layout_width="60dp"
            android:layout_height="60dp"
            android:layout_gravity="center" />

请问，怎么改这两个图片呢？

**Comment by CarGuo** [comment]
参考 NormalGSYVideoPlayer

**Comment by zhangnin** [comment]
感谢 * - *

**Comment by zhangnin** [comment]
> 参考NormalGSYVideoPlayer

感谢 *-*
