### ISSUE TITLE
视频宽度被压缩

### ISSUE THREAD

**Issue by protectedMan** [CarGuo/GSYVideoPlayer#2370]
使用demo最新版本测试的，视频宽度被压缩。
视频地址 ：http://su.bcebos.com/v1/lezhu-test/moment/iOS/9034-1572615668307.mp4
![image](https://user-images.githubusercontent.com/17565737/68030020-7fa0ae00-fcf3-11e9-9e3c-d613584f0a83.png)
视频实际的尺寸是这样的
![image](https://user-images.githubusercontent.com/17565737/68030148-c1c9ef80-fcf3-11e9-9404-cfb4f736d3f6.png)

**Comment by CarGuo** [comment]
如下图，demo 测试正常 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/10770362/68104234-4778b580-ff15-11e9-94d7-42f39d81961c.png">

**Comment by protectedMan** [comment]
![IMG_7355](https://user-images.githubusercontent.com/17565737/68104812-77c15380-ff17-11e9-9b09-6d5da4049198.JPG)
我这边三款测试机，oppo，魅族，sharp 都出现这相同的情况。

**Comment by CarGuo** [comment]
你用 detailplayer 测试，一般我用这个测试比较多

**Comment by protectedMan** [comment]
detailplayer确实没问题，我正在使用本库的项目中也是遇到了这种情况，你这边有什么排查建议吗。

**Comment by CarGuo** [comment]
一般就是布局 surface_container 是 RelativeLayout 还是 FrameLayout
 
    <RelativeLayout
        android:id="@+id/surface_container"


然后 计算高度逻辑在 MeasureHelper，demo detailplayer 用的是 LandLayoutVideo 的 sample_video_land 和 sample_video_normal ，还有和 match_parent 或者 wrap_content 有关系
