### ISSUE TITLE
播放器全屏时，没有弹幕

### ISSUE THREAD

**Issue by zhangnin** [CarGuo/GSYVideoPlayer#2371]
DanmkuVideoActivity、DanmakuVideoPlayer  参照这两个类写的，全屏时弹幕看不到，不知道少了那些配置。

**Comment by CarGuo** [comment]
全屏和非全屏的时候，是有状态同步的

**Comment by zhangnin** [comment]
> 全屏和非全屏的时候，是有状态同步的

您好，我看了DanmakuVideoPlayer 的这行代码：
//todo 这是为了demo效果，实际上需要去掉这个，外部传输文件进来
mParser = createParser(this.getResources().openRawResource(R.raw.comments));

comments 这个文件里如果删除<d ></d> 数据，横屏就不会有弹幕

**Comment by zhangnin** [comment]
> 全屏和非全屏的时候，是有状态同步的

我在demo上试了，也是有这个问题的，不是状态同步的问题：

1、正常情况：全屏的时候在DanmakuVideoPlayer调用 addDanmaku是没有问题的；
2、出错情况：全屏的时候在DanmakuVideoPlayer发个消息给DanmkuVideoActivity，让DanmkuVideoActivity调用addDanmaku，这时是肯定没有弹幕的。。。

**Comment by CarGuo** [comment]
不是很理解，如果是外部调用，你需要 player.getCurrentPlayer().xxxxxx去设置

**Comment by zhangnin** [comment]
> 不是很理解，如果是外部调用，你需要 player.getCurrentPlayer().xxxxxx去设置

全屏的时候，我在外部需要掉用addDanmaku这个方法，但是全屏时DanmakuVideoPlayer重新初始化了，所以外部调用addDanmaku会无效。。。您可以在demo试下，必现的问题


// *************DanmakuVideoPlayer.java****************

@Override
    public void onClick(View v) {
        super.onClick(v);
        switch (v.getId()) {
            case R.id.send_danmaku:
// 这里调用是正常的
//                addDanmaku(true);
// 通过发消息到外部activity，调用addDanmaku这个方法是无效的
                RxBus.getDefault().post("", "LIVE_ROOM_SHARE");
                break;
            case R.id.toogle_danmaku:
                mDanmaKuShow = !mDanmaKuShow;
                resolveDanmakuShow();
                break;
            default:
                break;
        }
    }

// *************DanmkuVideoActivity.java****************

  RxBus.getDefault()
                .subscribe(this, "LIVE_ROOM_SHARE", new RxBus.Callback<String>() {
                    @Override
                    public void onEvent(String s) {
// 这里在半屏状态下是正常的，全屏状态下是不能显示弹幕的
                        danmakuVideoPlayer.addDanmaku(true);
                    }
                });

**Comment by CarGuo** [comment]
我测试弹幕的切换和发送都正常啊 demo ，切换是可以正常展示和发送，如下图 gif 所示。


![2222](https://user-images.githubusercontent.com/10770362/68099008-ef34ba00-fefa-11e9-827c-00bd9cb54bdc.gif)


如果你是说切换的时候会清空之后再显示出来，这是正常的。

**Comment by zhangnin** [comment]
> 我测试弹幕的切换和发送都正常啊 demo ，切换是可以正常展示和发送，如下图 gif 所示。
> 
> ![2222](https://user-images.githubusercontent.com/10770362/68099008-ef34ba00-fefa-11e9-827c-00bd9cb54bdc.gif)
> 
> 如果你是说切换的时候会清空之后再显示出来，这是正常的。

已解决：我在DanmakuVideoPlayer的init()方法去接收外部消息，这样才是对的

**Comment by gmqxqs** [comment]
@CarGuo 
在activity下调用initDanmaku()方法，小屏可以显示弹幕，全屏无法显示弹幕

**Comment by ilovexy2tom** [comment]
> @CarGuo 在activity下调用initDanmaku()方法，小屏可以显示弹幕，全屏无法显示弹幕

这个问题我也遇到了，我这边遇到的是这样，全屏下，你发送弹幕的时候直接调用的是小屏幕的弹幕对象发送的

**Comment by ilovexy2tom** [comment]
> @CarGuo 在activity下调用initDanmaku()方法，小屏可以显示弹幕，全屏无法显示弹幕


 所以我最后的解决方案是，因为我的是消息联动的，用他们在init里面加方法肯定是不行的

  (player.currentPlayer as DanmakuVideoPlayer).addDanmaku(text, isMine)
  
  就这样就解决了。
