### ISSUE TITLE
多任务模式，多个视频同时播放，如果只想其中一个有声音如何设置呢，目前的声音设置都是全局的

### ISSUE THREAD

**Issue by minggithub666** [CarGuo/GSYVideoPlayer#2373]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
CustomManager 中针对每个 Manager 做独立处理就可以了，CustomManager 是有个 map 保存对应的 Manager
