### ISSUE TITLE
底层FFmpeg是用的最新的吗

### ISSUE THREAD

**Issue by kyzgxiaoguo** [CarGuo/GSYVideoPlayer#2375]
## 问题描述：底层FFmpeg是用的最新的吗

底层FFmpeg是用的最新的吗

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不是

**Comment by kyzgxiaoguo** [comment]
如果要使用最新的，怎么搞呀

**Comment by CarGuo** [comment]
去拉 ijkplayer 的库，修改配置文件的 ffmpeg 版本，重新编译so
