### ISSUE TITLE
锁屏播放音频的处理

### ISSUE THREAD

**Issue by liguangze** [CarGuo/GSYVideoPlayer#2376]
## 问题描述：

播放音频，没有锁屏的时候正常播放，当锁屏一点时间后，就会自动停止，

## 问题机型/系统：

例如 真机 华为麦芒

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

这个问题只是在华为的手机上出现，这个是不是系统杀死进程了呢，咱们的播放器保活怎么处理呢

**Comment by CarGuo** [comment]
如下图，了解一下
<img width="532" alt="image" src="https://user-images.githubusercontent.com/10770362/68104117-bb668e00-ff14-11e9-9937-d24d7cdf7a8a.png">

**Comment by liguangze** [comment]
谢谢了，这些我了解过了，这个必须要通过用户设置才可以，但是领导说凯叔，喜马拉雅一类的就没有问题，您知道有什么好点的解决措施吗，不是通过用户去设置，万分感谢

**Comment by CarGuo** [comment]
如果你们找上华为付费内置白名单，也没有任何问题，后台包活现在所示没有什么绝对可以的，这个让你领导找华为转账付费，之前我网易云音乐都会·····

**Comment by liguangze** [comment]
好的，万分感谢，您知道什么渠道吗，还是官网就可以

**Comment by CarGuo** [comment]
具体联系我就不知道了，以前都是公司的运营和商务联系得
