### ISSUE TITLE
亮度调节得支持系统调节，不然电视上调节不方便

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#2377]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

亮度调节得支持系统调节，不然电视上调节不方便，
一般电视上，都是用系统自带调节，但是发现打开播放器，系统调节无效

## 问题机型/系统：

例如 电视

## Demo中的复现步骤

问题代码：(如果有)

**Comment by CarGuo** [comment]
播放器用的是 app 亮度，在 onBrightnessSlide 方法。
```
Window window = this.getWindow();
WindowManager.LayoutParams lp = window.getAttributes();
lp.screenBrightness = brightness;
window.setAttributes(lp);
```


如果你有需要，可以基础后重写 onBrightnessSlide 方法，修改为 Settings.System

**Comment by renwfy** [comment]
好的，我试试
