### ISSUE TITLE
   源码中 setProgressAndTime 有2个 是否重复

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#2379]
protected void setTextAndProgress(int secProgress) {
        int position = getCurrentPositionWhenPlaying();
        int duration = getDuration();
        int progress = position * 100 / (duration == 0 ? 1 : duration);
        setProgressAndTime(progress, secProgress, position, duration);
        setProgressAndTime(progress, secProgress, position, duration);
    }

**Comment by CarGuo** [comment]
是的，thx
