### ISSUE TITLE
是否直接播放sdcard视频？

### ISSUE THREAD

**Issue by mirror5821** [CarGuo/GSYVideoPlayer#238]

**Comment by mirror5821** [comment]
//需要路径的
        //videoPlayer.setUp(url, true, new File(FileUtils.getPath()), "");

**Comment by mirror5821** [comment]
//需要路径的
//videoPlayer.setUp(url, true, new File(FileUtils.getPath()), ""); 请问是这个地方吗？

**Comment by CarGuo** [comment]
播放sd卡就直接传入本地视频文件路径即可
