### ISSUE TITLE
测试demo，播放异常

### ISSUE THREAD

**Issue by 15281046619** [CarGuo/GSYVideoPlayer#2380]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

  代码设置PlayerFactory.setPlayManager(SystemPlayerManager.class)后，暂停在点击全屏后，会自动播放，全屏暂停返回正常模式一样会自动播放。代码不设置PlayerFactory.setPlayManager(SystemPlayerManager.class)播放正常。
后来下载demo运行，增加PlayerFactory.setPlayManager(SystemPlayerManager.class)测试了一些模块，也会出现这种问题。

## 问题机型/系统：

例如 真机 小米8 Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'`

## Demo中的复现步骤

Demo中的DetailNormalActivityPlayer页面打开后会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
没有
```

## 问题log（如果有）

```
没有

xxxxxxx

```

**Comment by CarGuo** [comment]
Demo 怎么复现

**Comment by CarGuo** [comment]
就是全屏幕和退出全屏，在暂停的时候 SystemPlayerManager 会导致暂停失效继续播放？

**Comment by 15281046619** [comment]
对

**Comment by 15281046619** [comment]
就是这个意思




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuyu Guo"<notifications@github.com&gt;; 
发送时间: 2019年11月5日(星期二) 下午2:15
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;; 
抄送: "_兲空シ戀ě"<1161413754@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CarGuo/GSYVideoPlayer] 测试demo，播放异常 (#2380)




就是全屏幕和退出全屏，在暂停的时候 SystemPlayerManager 会导致暂停失效继续播放？

**Comment by 15281046619** [comment]
有没有什么解决方案呀？求帮助呀

**Comment by 15281046619** [comment]
> 就是全屏幕和退出全屏，在暂停的时候 SystemPlayerManager 会导致暂停失效继续播放？

有没有什么解决方案呀？求帮助呀

**Comment by CarGuo** [comment]
建议暂时切换到 ExoPlayerCacheManager
