### ISSUE TITLE
视频在加载完播放前全屏闪一下的问题

### ISSUE THREAD

**Issue by zhouxiaocong** [CarGuo/GSYVideoPlayer#2382]
## 问题描述：
项目中有这样类似抖音视频播放功能，分为竖视频与横视频，竖屏时全屏裁剪播放，横屏时等比播放，在这个场景下，视频控件在xml的宽高都是充满的，现在出现一个问题为：横屏视频在加载时封面图正常等比展示，在视频加载完正要播放时，有一定几率会全屏闪一下（本是等比居中的横视频突然拉高充满了屏幕），然后再正常播放，检查了项目代码和部分源码，在播放前并未做封面图的类型修改与播放器提供的渲染模式的修改，怀疑是播放前未获取视频宽高时直接渲染满控件宽高，底层渲染的问题，麻烦看下是否存在这个问题。

## 问题机型/系统：

例如 真机 open R11S

## GSY依赖版本

例如 v7.1.1

## Demo中的复现步骤

还未在demo中做这实验

**Comment by CarGuo** [comment]
这是因为封面图和视频播放显示比例不同导致的吧，就是封面图显示的逻辑和视频播放时的渲染比例不一样，Demo 不是有 SampleCoverVideo 么？改下支持你要的比例就可以了

**Comment by zhouxiaocong** [comment]
感谢回复~封面图的缩放模式是居中等比，视频设置的模式也是等比播放，封面图的取值是视频第一帧，按逻辑封面图与视频都是等比居中，比例应该都是一致的。（SampleCoverVideo看过了，之前使用其中重载在播放前封面图不隐藏的逻辑）现在的现象是它不是一定复现的，同一个视频偶尔闪偶尔不闪，还未找到规律，但出现时机就是在正好加载完要播放时，再次感谢回复~

**Comment by zhouxiaocong** [comment]
感谢回复，封面图的缩放模式是居中等比，视频设置的模式也是等比播放，封面图的取值是视频第一帧，按逻辑封面图与视频都是等比居中，比例应该都是一致的。（SampleCoverVideo看过了，之前使用其中重载在播放前封面图不隐藏的逻辑）现在的现象是它不是一定复现的，同一个视频偶尔闪偶尔不闪，还未找到规律，但出现时机就是在正好加载完要播放时，再次感谢回复

**Comment by zhouxiaocong** [comment]
抱歉有一处忘加上：该功能是RecyclerView, item为充满屏幕的视频（类似刷抖音视频的功能实现）

**Comment by CarGuo** [comment]
如果不是复现的共享，我这边很难从 demo 去跟踪

**Comment by zhouxiaocong** [comment]
了解，我尝试在demo复现和自行查询原由，有后续再次联系，感谢回复~

**Comment by zhouxiaocong** [comment]
嗨喽~ 在经过研读源码后，发现测量方法处默认设置的为该控件的宽高，然后再判断渲染模式进行宽高转换为视频播放区域的宽高，在最初mVideoWidth，mVideoHeight未获取成功都为0时，视频的宽高播放一直为测量方法返回的默认控件大小。

问题：渲染模式使用默认等比例播放视频，在还未获取成功mVideoWidth，mVideoHeight时，此时视频播放区域为控件的宽高进行播放。

例子：视频控件宽高设置全屏，渲染模式为等比例播放，当前屏幕比为：1080x1920，播放一个为1080x627的视频，在还未获取到该视频宽高时，视频的渲染播放区域为1080x1920，这样出现了先播放出1080x1920的区域，然后获取成功该视频宽高重新赋值后，再渲染为1080x627的区域大小，导致出现了加载完播放时先全屏闪一下的问题

源码处：MeasureHelper->
prepareMeasure(int widthMeasureSpec, int heightMeasureSpec, int rotate)->
doMeasure(int widthMeasureSpec, int heightMeasureSpec)->

        int width = View.getDefaultSize(mVideoWidth, widthMeasureSpec);
        int height = View.getDefaultSize(mVideoHeight, heightMeasureSpec);

想法：是否可以在成功获取视频的宽高后再进行播放

以上为自我研读理解，麻烦查看是否存在该问题，或者现版本应怎么解决这个闪一下的问题。

**Comment by CarGuo** [comment]
收到～

**Comment by CarGuo** [comment]
在增加上 

```

        if(mVideoHeight == 0 || mVideoWidth == 0) {
            /*mMeasuredWidth = 0;
            mMeasuredHeight = 0;
            return;*/
        }
```

测试下默认 IJK 内核可以正常，但是使用 mediaCodec 的因为surface为0会有问题

**Comment by zhouxiaocong** [comment]
收到~ 
请问该问题的解决代码大概什么时候会更新至新版本，目前使用的是gradle依赖，未导入源码
（本人项目中使用的是exoplayer,麻烦能加测一下嘛~）

**Comment by CarGuo** [comment]
实测修改为如下可以解决问题

```

        if (mVideoHeight == 0 || mVideoWidth == 0) {
            mMeasuredWidth = 1;
            mMeasuredHeight = 1;
            return;
        }

```

新版本估计没那么快，如果着急可以看 ： https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/view/CustomRenderView.java 自定义处理

**Comment by zhouxiaocong** [comment]
收到~ 目前按自定义已处理好。

**Comment by zhouxiaocong** [comment]
哈喽～ 目前这个问题解决方案在用户体验上感觉还是不够友好，封面图不闪设置为0后，那出现的就是黑屏闪一下的状态了，一般封面图都是视频的第一帧，能否在第一帧完全渲染出来后，再隐藏封面图。

**Comment by ymwm-lxl** [comment]
楼上说的问题很关键，我在继承之后重写了 changeUiToPreparingShow() 方法，在这里面把封面图setViewShowState(mThumbImageViewLayout, VISIBLE);这样在加载的时候就是封面图，但是这样视频开始播放会闪烁两下，体验很差
