### ISSUE TITLE
不开启软解码CPU占用高

### ISSUE THREAD

**Issue by CleverSJX** [CarGuo/GSYVideoPlayer#2383]
##  不开启硬解码CPU占用高

 软解码将近60%, 硬解码15左右正常, 视频 4.5m,是质量很低的视频

![image](https://user-images.githubusercontent.com/26036692/68191680-03f07b00-ffeb-11e9-9174-c05c6a9c254e.png)

## 版本
```
   implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'
```

**Comment by CarGuo** [comment]
很正常啊，软解码是完全依靠CPU的。

**Comment by CleverSJX** [comment]
好的吧
