### ISSUE TITLE
ex_so:7.1.1无法播放rtsp

### ISSUE THREAD

**Issue by teller110** [CarGuo/GSYVideoPlayer#2385]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

vlc建立的rtsp推流无法播放

## 问题机型/系统：

例如 真机 三星s8+ Android9.0

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.1'

## Demo中的复现步骤
无法播放在本地vlc中打开的rtsp推流，在其它电脑上用vlc可以播放

问题代码：(如果有)
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
        videoPlayer.setUp(rtspUrl, true, "");
## 问题log（如果有）

E/IJKMEDIA: Connection to tcp://172.16.7.53:554?timeout=0 failed: No route to host
E/IJKMEDIA: rtsp://172.16.7.53:554/110: No route to host
D/IJKMEDIA: FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2112 

看你错误是  No route to host

**Comment by xuganwen** [comment]
这个no route to host  是什么原因，怎么解决的

**Comment by baikimi** [comment]
Connection to tcp://192.168.1.240:554?timeout=0 failed: No route to host
2021-08-18 17:49:29.392 7220-9268/com.benliu.packter E/IJKMEDIA: rtsp://admin:123456@192.168.1.240:554/h264/ch1/main/av_stream: No route to host
2021-08-18 17:50:14.611 7220-9283/com.benliu.packter E/IJKMEDIA: Connection to tcp://192.168.1.240:554?timeout=0 failed: No route to host
2021-08-18 17:50:14.611 7220-9283/com.benliu.packter E/IJKMEDIA: rtsp://admin:123456@192.168.1.240:554/h264/ch1/main/av_stream: No route to host

偶尔会同样出现“No route to host”，什么原因，怎么解决？
