### ISSUE TITLE
全屏弹幕不显示问题

### ISSUE THREAD

**Issue by liulance** [CarGuo/GSYVideoPlayer#2388]
您好，请问系啊，我看demo 里面，全屏的时候是加载了一遍本地文件，我的实际项目是打开activity 的时候请求的json文件，加载弹幕，小屏的时候可以加载，切换全屏的时候，就不显示了，

请问下，在切换全屏的时候，这里怎么重新加载弹幕？谢谢

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2371

**Comment by liulance** [comment]
@CarGuo 你好，上面这个问题跟我的不一样，demo 全屏时候加载了一遍本地文件，我项目里面没有用到本地文件，请问全屏时候怎么加载？
![image](https://user-images.githubusercontent.com/22095781/68357451-60b97600-0150-11ea-9296-e704faf0c288.png)

**Comment by CarGuo** [comment]
你可以把请求到的文件保存在本地进行显示，或者将 loader 加载实现成单例在全屏于非全屏之间共享

**Comment by liulance** [comment]
@CarGuo 我请求到的是个json 格式的字符串，要转化成文件才可以吗？

**Comment by CarGuo** [comment]
demo DanmkuVideoActivity 页面中不是有 getDanmu 方法吗？

**Comment by liulance** [comment]
@CarGuo 我的意思是，你demo 里面 getDanmu 获取的是.txt 的文件，我实际项目里面获取到的是json，是不是必须要把json 转为文件存储，然后全屏的时候加载文件么？

**Comment by CarGuo** [comment]
这个和内部的  DanmakuLoaderFactory.create(DanmakuLoaderFactory.TAG_BILI); 有关系
 DanmakuLoaderFactory.create(DanmakuLoaderFactory.TAG_BILI);//这个是xml的方式
DanmakuLoaderFactory.TAG_ACFUN//这个是josn

**Comment by liulance** [comment]
@CarGuo ![image](https://user-images.githubusercontent.com/22095781/68368898-f61a3180-0173-11ea-9d66-2a85df252851.png)
我看源码，这里loader加载的是流或者文件uri 地址呀

现在我的问题就是，小屏的时候可以显示弹幕，切换到全屏后，弹幕就不显示了，我不知道怎么把弹幕数据给设置进去
