### ISSUE TITLE
设置GSYVideoType.setRenderType(GSYVideoType.SUFRACE)渲染后截图返回null

### ISSUE THREAD

**Issue by kongshanniao** [CarGuo/GSYVideoPlayer#2390]
## 问题描述：设置渲染模式 GSYVideoType.setRenderType(GSYVideoType.SUFRACE);后使用
com.zzl.ztcm.player.SmartPickVideo该播放控件
 通过view.taskShotPic(bitmap -> {
            if (bitmap != null) {

              }
        });
截图，返回null。

## 问题机型/系统：

原生android5.0系统

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:6.0.3'

**Comment by CarGuo** [comment]
SUFRAC ：   

  /**
     * 获取截图
     *
     * @param shotHigh 是否需要高清的
     */
    public void taskShotPic(GSYVideoShotListener gsyVideoShotListener, boolean shotHigh) {
        Debuger.printfLog(getClass().getSimpleName() + " not support taskShotPic now");
    }

**Comment by kongshanniao** [comment]
使用您上述的方法进行截图，还是返回null，是SUFRAS模式下不支持截屏吗？

**Comment by CarGuo** [comment]
是的
