### ISSUE TITLE
调用 getGSYVideoManager().releaseMediaPlayer()  视频上还能看到封面图

### ISSUE THREAD

**Issue by zhangnin** [CarGuo/GSYVideoPlayer#2392]
我调用
onVideoPause()
getGSYVideoManager().releaseMediaPlayer();
还能在视频View上看到图片；此处可以去掉视频View上的图片吗？

**Comment by CarGuo** [comment]
Demo 怎么复现？

**Comment by zhangnin** [comment]
我在 DetailControlActivity 里加个按钮，点击调用 SampleControlVideo 里的
onVideoPause()
getGSYVideoManager().releaseMediaPlayer();

这样就可以复现。

**Comment by zhangnin** [comment]
我用了一个比较笨的方法，直接隐藏视频View 0.0
