### ISSUE TITLE
请问，可以切换其它播放器sdk吗？

### ISSUE THREAD

**Issue by Lizi123** [CarGuo/GSYVideoPlayer#2397]
```

请问，可以切换其他播放器sdk吗

```

**Comment by CarGuo** [comment]
可以啊，默认支持 ijk ，exo ，mediaplayer，如果还有其他，自定义 PlayerManager 就可以了

**Comment by Lizi123** [comment]
弱弱的问一句...自定义PlayerManager要继承IPlayerManager，但是IPlayerManager里面getMediaPlayer();返回的是IMediaPlayer；而IMediaPlayer是ijk的；我用的播放器sdk并不是ijk的，这就会报错，是我自定义的方法不对么？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exo

参考这个吧

**Comment by Lizi123** [comment]
看了还是不太明白 这个继承的问题 怎么解决呢？
GSYExoPlayerManager的
@Override
    public IMediaPlayer getMediaPlayer() {
        return mediaPlayer;
    }
返回的这个IMediaPlayer还是ijk的。不太懂，求指点。

**Comment by CarGuo** [comment]
IMediaPlayer 只是个抽象接口，你直接继承 IMediaPlayer ，用你的 player 实现这些接口就可以了

**Comment by Lizi123** [comment]
自定义的player继承AbstractMediaPlayerOption并自定义了IPlayerManager
 IjkMutiVideoControl not found.
可能原因是什么呢？求指点><

**Comment by CarGuo** [comment]
IjkMutiVideoControl not found 是什么？？？ 没看到懂

**Comment by Lizi123** [comment]
没事了，那个报错不影响的。但是我现在自定义了player和PlayerManager之后用PlayerFactory.setPlayManager后还是没办法播放，也没有报错信息，我想问除了自定义player和PlayerManager还有别的需要调整或注意的么？求指点``

**Comment by CarGuo** [comment]
主要亮点，Surface 是否正确设置，还有跟踪你的 mediaplayer 是否被执行播放了

**Comment by Lizi123** [comment]
解决了，感谢大神指点迷津^-^
