### ISSUE TITLE
不知道为什么我的@Override的函数都不会被回掉,求解惑

### ISSUE THREAD

**Issue by HimiGame** [CarGuo/GSYVideoPlayer#2399]
public class Test extends StandardGSYVideoPlayer{ 

  @Override
    protected void onClickUiToggle() {
        super.onClickUiToggle();
    }

    @Override
    protected void hideAllWidget() {
        super.hideAllWidget();
    }

}
想自定义很多东西，都没法继续。。希望大佬回复下

**Comment by CarGuo** [comment]
不是很理解啊？
