### ISSUE TITLE
关于m3u8切换清晰度问题

### ISSUE THREAD

**Issue by shinemaomao** [CarGuo/GSYVideoPlayer#2400]
大神 ，您好！请问播放m3u8格式视频的时候如何切换清晰度？

**Comment by CarGuo** [comment]
就像 demo 一样，只是切换 url 而已

**Comment by shinemaomao** [comment]
那是不是需要解析m3u8格式的视频获取到 高清 超清 标清地址？还是需要提供3个不同的m3u8格式地址？像腾讯可以生成多码率的m3u8格式，切换也是在同一个里面切换，如以下格式 #EXTM3U

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000

http://example.com/low.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000

http://example.com/mid.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=7680000

http://example.com/hi.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=65000,CODECS="mp4a.40.5"

http://example.com/audio-only.m3u8

是否需要我们去解析 m3u8获取不同的地址，经行缓冲？

**Comment by CarGuo** [comment]
暂时时没有支持内部自己解析 m3u8 清晰度的功能，需要你外部解析，exo模式的话可以使用自定义 source
