### ISSUE TITLE
如何跳过指定时间的视频段落

### ISSUE THREAD

**Issue by kennir** [CarGuo/GSYVideoPlayer#2402]
## 问题描述：

我想跳过视频的末尾3分钟，怎么实现是最合适的？和进度有关的地方我找下来有

setProgressAndTime
onProgressChanged

我觉得比较合适的地方可能是onProgressChanged，那么是否可以在onProgressChanged里调用seek ?

**Comment by CarGuo** [comment]
onProgressChanged 内部监听 可以
