### ISSUE TITLE
老版本好像不支持，wav和wam格式的文件源

### ISSUE THREAD

**Issue by kyzgxiaoguo** [CarGuo/GSYVideoPlayer#2403]
## 问题描述：
建议重新编译ffmpeg动态so库

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
是的，ijk 模式看项目主页的两个 .sh 文件和https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md

其他两个模式看 Android MediaCodec 的支持格式
