### ISSUE TITLE
mts 视频出画面，没有声音

### ISSUE THREAD

**Issue by ooyellow58** [CarGuo/GSYVideoPlayer#2407]
https://archive.org/download/scm-10794-mtstestfile/00007.mts

**Comment by CarGuo** [comment]
看一下你的音频编码是什么就知道了

**Comment by ooyellow58** [comment]
AC3

**Comment by CarGuo** [comment]
确实没有打包支持，看根目录的两个 sh 文件就知道了，可以看这个去配置 [编码支持](https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md#ac3)

**Comment by ooyellow58** [comment]
上次你说ijkplayer 已经支持，如何调整
https://github.com/CarGuo/GSYVideoPlayer/issues/2281

**Comment by CarGuo** [comment]
重新编译 so ，配置上 ac3
