### ISSUE TITLE
视频加载失败时  怎么样可以把返回按钮保持常显呢

### ISSUE THREAD

**Issue by underwes** [CarGuo/GSYVideoPlayer#2408]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：视频加载失败时  怎么样可以把返回按钮保持常显呢

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

视频加载失败时 想要那个返回按钮常显

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
继承重写，使用你自己的 getLayoutId ，还可以重写 changeUiToError 等方法

**Comment by underwes** [comment]
好的 谢谢
