### ISSUE TITLE
请问如何禁止进度条的拖动？

### ISSUE THREAD

**Issue by Jibinghao** [CarGuo/GSYVideoPlayer#2409]
## 问题描述：

请问如何禁止进度条的拖动？产品要求视频不能拖动进度条

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
touchSurfaceMove 、  touchSurfaceMoveFullLogic 、 touchSurfaceUp 这三个方法是触摸视频快进的回调

然后 onStartTrackingTouch 、onStopTrackingTouch 是 seekbar 触摸的回调
继承后重写这些方法就可以
另外还有  mProgressBar 变量也可以在重写的 init 方法中设置 enable

**Comment by smallmouse2009** [comment]
if (!isComplete || (data != null && data.status != 1)) {
      videoPlayer.getProgress().setOnTouchListener(new OnTouchListener() {
        @Override
        public boolean onTouch(View v, MotionEvent event) {
          if (MotionEvent.ACTION_UP == event.getAction()) {
            VKToastUtils.toast(DynamicPlayerActivity.this, "未完成预习，不可以拖动进度条哦~");
          }
          return true;
        }
      });
    } else {
      videoPlayer.getProgress().setOnTouchListener(videoPlayer);
    }

**Comment by AaronQinhuai** [comment]
同求，可不可以加个开关啊

**Comment by Jibinghao** [comment]
> ```
> if (!isComplete || (data != null && data.status != 1)) {
>   videoPlayer.getProgress().setOnTouchListener(new OnTouchListener() {
>     @Override
>     public boolean onTouch(View v, MotionEvent event) {
>       if (MotionEvent.ACTION_UP == event.getAction()) {
>         VKToastUtils.toast(DynamicPlayerActivity.this, "未完成预习，不可以拖动进度条哦~");
>       }
>       return true;
>     }
>   });
> } else {
>   videoPlayer.getProgress().setOnTouchListener(videoPlayer);
> }
> ```

我是这样做的，继承这个类StandardGSYVideoPlayer，新增一个方法
`   public void setProgressBarEnabled(boolean enabled) {
        mProgressBar.setEnabled(enabled);
    }`

**Comment by Jibinghao** [comment]
> 同求，可不可以加个开关啊

我是这样做的，继承这个类StandardGSYVideoPlayer，新增一个方法
`
   public void setProgressBarEnabled(boolean enabled) {
        mProgressBar.setEnabled(enabled);
    }
`
