### ISSUE TITLE
顶部跟底部控制栏显示问题

### ISSUE THREAD

**Issue by YumikoAzu** [CarGuo/GSYVideoPlayer#2410]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

想实现跟bilibili一样的效果:手指滑动视频中间位置会显示视频进度提示框，而且顶部底部栏会显示，底部栏的进度条跟随手指滑动改变进度。我现在实现了可以 滑动时候显示顶部底部栏但继续滑动，顶部底部栏会自动消失，在哪里可以调整这个呢？

## 问题机型/系统：

 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
StandardGSYVideoPlayer 中的  changeUiToPlayingShow 等 changeUi****** 等方法
