### ISSUE TITLE
视频未加载出来点击进度条，开始播放是进度条不变化

### ISSUE THREAD

**Issue by moujunqiang** [CarGuo/GSYVideoPlayer#2411]
问题描述：

demo中有一个长视频，用samplevideo播放，在视频正在加载的时候进度条，等视频开始播放 进度条没有回弹 跟随进度变化，一直保持不动。
 问题机型/系统：

真机 一加5T android 9.0
GSY依赖版本

    implementation 'com.shuyu:GSYVideoPlayer:6.0.3'

Demo中的复现步骤

demo中，detail列表模式，切换下一集，切换到第三个长视频也是这种情况

**Comment by moujunqiang** [comment]
进度条不是没有变化，而是过了一段时间才根据当前播放时时间变化，播放那个一小时的视频一分钟才开始变化，播放九分钟的视频十秒左右开始变化

**Comment by CarGuo** [comment]
如下图，是因为播放内核有时候会有返回 0 的 bug ，所以这里 setProgressAndTime 增加了 不等于才设置的判断，这样才不会出现进度条时不时诡异抖动的情况。但是越长的视频，才 0 到 1 的比例所需要时间就越长，导致这个设置有问题。

因为播放前调整进度条不会触发内核 seek 导致了这个异常。

这里我刚刚修改了，在 onPrepared 的使用 force 到 0 。

<img width="983" alt="image" src="https://user-images.githubusercontent.com/10770362/69114932-e24ec380-0ac1-11ea-8c89-acfe6bc9ee23.png">

**Comment by moujunqiang** [comment]
这个我依赖的6.xx的版本可以用吗

**Comment by CarGuo** [comment]
你可以继承后 cv 重写方法

**Comment by moujunqiang** [comment]
好的 谢谢
