### ISSUE TITLE
怎么播放音频文件 

### ISSUE THREAD

**Issue by xiaoyao521** [CarGuo/GSYVideoPlayer#2416]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

请问用咱们的框架怎么播放.m4a 的文件

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)

**Comment by xiaoyao521** [comment]
大神，请问怎么播放音频文件啊

**Comment by CarGuo** [comment]
正常播放啊？？？？
