### ISSUE TITLE
添加了"enable-accurate-seek"还是不够精准

### ISSUE THREAD

**Issue by zzh3321** [CarGuo/GSYVideoPlayer#2419]
## 问题描述：

我们项目对seek的要求非常高，希望可以准确seek，目前已经添加了"enable-accurate-seek"，有一定效果，但是还是不够满足需求，我们的视频比较短，有没有办法在不增加视频关键帧的情况下实现精准seek？精确到秒的那种。感谢~

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by CarGuo** [comment]
视频关键帧就那样，能有什么办法？

**Comment by zzh3321** [comment]
视频太多了，重新回炉加关键帧有点麻烦，一点办法也没有了吗o(╥﹏╥)o

**Comment by CarGuo** [comment]
木有，至少在我的理解上，关键帧和 seek 是相关的。

**Comment by zzh3321** [comment]
嗯，感谢大佬解答~
