### ISSUE TITLE
为什么detailvideo全屏模式下音量和亮度手势调节需要触摸两次才有效？

### ISSUE THREAD

**Issue by chenzheng8975** [CarGuo/GSYVideoPlayer#242]
作者你好：
我想咨询一下，为什么detail video、detail list在全屏模式下，音量和亮度手势调节需要触摸两次才有效？

**Comment by CarGuo** [comment]
触摸两次才生效？？？

**Comment by chenzheng8975** [comment]
是的啊 detail video、detail list点击进去，全屏模式下播放，手势调节音量和亮度，第一下触摸没反应，第二下触摸才可以进行调节，不知道是为什么？

**Comment by chenzheng8975** [comment]
经测试 是手机问题！
