### ISSUE TITLE
请教一下kotlin 继承StandardGSYVideoPlayer 构造方法问题

### ISSUE THREAD

**Issue by YumikoAzu** [CarGuo/GSYVideoPlayer#2420]
## 问题描述：
kotlin 继承StandardGSYVideoPlayer 重载三个构造方法，重写getLayoutId()设置竖屏横屏两套布局，getLayoutId()里面mIfCurrentIsFullscreen横屏后依然为false。换Java写没有问题，mIfCurrentIsFullscreen 横屏后log输出true。但把kotlin转换成Java代码，三个重载方法看着没问题。
 public APlayer(@NotNull Context context, boolean fullFlag) {
      Intrinsics.checkParameterIsNotNull(context, "context");
      super(context, fullFlag);
   }

   public APlayer(@NotNull Context context) {
      Intrinsics.checkParameterIsNotNull(context, "context");
      super(context);
   }

   public APlayer(@NotNull Context context, @NotNull AttributeSet attrs) {
      Intrinsics.checkParameterIsNotNull(context, "context");
      Intrinsics.checkParameterIsNotNull(attrs, "attrs");
      super(context, attrs);
   }

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

问题代码：
class APlayer : StandardGSYVideoPlayer {
constructor(context: Context, fullFlag: Boolean) : super(context, fullFlag)

    constructor(context: Context) : super(context)

    constructor(context: Context, attrs: AttributeSet) : super(context, attrs)

override fun getLayoutId(): Int {

        Log.d("land", mIfCurrentIsFullscreen.toString())
        if (mIfCurrentIsFullscreen) {
            Log.d("land", "land")
            return R.layout.layout_player_fullscreen
        }

        return R.layout.layout_player_normal
    }
}

**Comment by CarGuo** [comment]
这个方法在内部是通过反射

```  
  public GSYVideoPlayer(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    } 
```

GSYBaseVideoPlayer

```
           //通过被重载的不同构造器来选择
            Constructor<GSYBaseVideoPlayer> constructor;
            final GSYBaseVideoPlayer gsyVideoPlayer;
            if (!hadNewConstructor) {
                constructor = (Constructor<GSYBaseVideoPlayer>) GSYBaseVideoPlayer.this.getClass().getConstructor(Context.class);
                gsyVideoPlayer = constructor.newInstance(mContext);
            } else {
                constructor = (Constructor<GSYBaseVideoPlayer>) GSYBaseVideoPlayer.this.getClass().getConstructor(Context.class, Boolean.class);
                gsyVideoPlayer = constructor.newInstance(mContext, true);
            }

```

**Comment by YumikoAzu** [comment]
> 这个方法在内部是通过反射
> 
> ```
>   public GSYVideoPlayer(Context context, Boolean fullFlag) {
>         super(context, fullFlag);
>     } 
> ```
> 
> GSYBaseVideoPlayer
> 
> ```
>            //通过被重载的不同构造器来选择
>             Constructor<GSYBaseVideoPlayer> constructor;
>             final GSYBaseVideoPlayer gsyVideoPlayer;
>             if (!hadNewConstructor) {
>                 constructor = (Constructor<GSYBaseVideoPlayer>) GSYBaseVideoPlayer.this.getClass().getConstructor(Context.class);
>                 gsyVideoPlayer = constructor.newInstance(mContext);
>             } else {
>                 constructor = (Constructor<GSYBaseVideoPlayer>) GSYBaseVideoPlayer.this.getClass().getConstructor(Context.class, Boolean.class);
>                 gsyVideoPlayer = constructor.newInstance(mContext, true);
>             }
> ```

那kotlin有解决办法？

**Comment by CarGuo** [comment]
主要是你要 debug 下为什么会出现这个问题，在源码的位置

**Comment by qiuqiutang** [comment]
今天也困扰了这个问题，解决方法如下：
constructor(context: Context) : super(context)
constructor(context: Context, attrs: AttributeSet) : super(context, attrs)
改成
constructor(context: Context?) : super(context)
constructor(context: Context?, fFlag: Boolean?) : super(context, fFlag)
