### ISSUE TITLE
播放视频有声音画面不动

### ISSUE THREAD

**Issue by Eaken** [CarGuo/GSYVideoPlayer#2423]
## 问题描述：
使用共享元素从列表页进入详情页后，返回后列表页播放视频有声音画面不动

## 问题机型/系统：
真机 小米note8 Android9.0

## GSY依赖版本
implementation 'com.shuyu:GSYVideoPlayer:7.1.1'

## Demo中的复现步骤
我扩展了一下demo的SwitchPlay，但在详情页结束后没有释放视频，详情页的videoplayer也保留着并且在返回列表页后用cloneParams方法将详情页的videoplayer复制到列表页的videoplayer上去了，也用了addTextureView()方法，但是就是有声音进度条也在动但画面不动。demo的SwitchPlay返回后视频是已经释放了的。

**Comment by Eaken** [comment]
大神，请问怎么让画面动起来

**Comment by CarGuo** [comment]
SwitchPlay 回到列表我是没做继续播放处理的，因为太麻烦······

**Comment by Eaken** [comment]
> SwitchPlay 回到列表我是没做继续播放处理的，因为太麻烦······

那有什么办法能让画面动起来吗，一定要先释放了资源才行吗

**Comment by CarGuo** [comment]
主要是需要在不释放内核的情况下，再次切换 surface 和同步状态

**Comment by wangzhen6039** [comment]
@CarGuo 你好，同样的问题。 针对这个问题，"主要是需要在不释放内核的情况下，再次切换 surface 和同步状态"。 是不是可以再次无缝切换回来啊？

**Comment by wangzhen6039** [comment]
> @CarGuo 你好，同样的问题。 针对这个问题，"主要是需要在不释放内核的情况下，再次切换 surface 和同步状态"。 是不是可以再次无缝切换回来啊？

#2758 这个issue可以解决这个问题。
