### ISSUE TITLE
GSYVideoPlayer播放视频的时候按home键，播放其他的app音视频，再返回到GSY播放的视频，发现视频播放不了了。

### ISSUE THREAD

**Issue by barryyanggoing** [CarGuo/GSYVideoPlayer#2426]
## 问题描述：

如题

## GSY依赖版本

例如 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

GSYVideoPlayer播放视频的时候按home键，播放其他的app音视频，再返回到GSY播放的视频，发现视频播放不了了。

**Comment by CarGuo** [comment]
不是bug，很正常啊，播放其他音视频，默认你的视频就被释放，要重新播放。

内部通过音频监听接口，默认在音频焦点切换时释放了视频，你如果需要自定义这个，重写对应lossxxxxx方法就好了

**Comment by barryyanggoing** [comment]
嗯，我看了下源码，重写了那个方法就行了------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>
发送时间: 2019年11月24日(星期天) 下午5:25
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com>;
抄送: "BarryYang"<614994859@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CarGuo/GSYVideoPlayer] GSYVideoPlayer播放视频的时候按home键，播放其他的app音视频，再返回到GSY播放的视频，发现视频播放不了了。 (#2426)



不是bug，很正常啊，播放其他音视频，默认你的视频就被释放，要重新播放。
 
内部通过音频监听接口，默认在音频焦点切换时释放了视频，你如果需要自定义这个，重写对应lossxxxxx方法就好了
 
&mdash;
