### ISSUE TITLE
Video Not Playing When Proguard Enabled

### ISSUE THREAD

**Issue by muzeasd** [CarGuo/GSYVideoPlayer#2428]
Hello there.  I am using a recyclerView on the PlayVideo screen which suggests videos based on genre of the video being played at the moment. I play the video when user taps on any of the thumbnails, from the suggestion videos (as I have setup a click listener on each item). 

I have included all the KEEP rules that are necessary, from the main page. But the video is not played when user taps on one of the suggestion videos.

Note: 
1) App working absolutely fine when ProGuard is disabled.
2) If I play video from my mainScreen, where all the videos are listed, the videos starts playing  (when ProGuard is enabled)
3) I am using EmptyControlVideo and I override **onInfo()** function. This function tells that video stream gets loaded (when ProGuard is enabled)

Using following KEEP rules, from main page of GSYVideoPlayer.

`-keep class tv.danmaku.ijk.media.player.** {*; }
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer{ *; }
-keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi{ *; }
-keep class com.shuyu.gsyvideoplayer.video.** { *; }
-keep class com.shuyu.gsyvideoplayer.video.base.** { *; }
-keep class com.shuyu.gsyvideoplayer.utils.** { *; }
-keep class tv.danmaku.ijk.** { *; }

-keep public class * extends android.view.View{
    *** get*();
    void set*(***);
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}`

**Comment by CarGuo** [comment]
In demo project ，I change `minifyEnabled true` in `build.gradle` fire and working absolutely fine
