### ISSUE TITLE
全屏后点击返回，屏幕会旋转，但仍是全屏状态

### ISSUE THREAD

**Issue by anpoz** [CarGuo/GSYVideoPlayer#243]
自定义布局后就出现了这个问题，请问大概是什么原因导致的，能否提供一些思路
这个状态下点击返回和按返回键都没反应

![screenshot_20170523-152201](https://cloud.githubusercontent.com/assets/2825342/26342728/c5ef1b40-3fcb-11e7-8c1e-e05dd11dd872.png)

**Comment by CarGuo** [comment]
你是列表的還是detail的？是util模式的还是普通模式的？

**Comment by anpoz** [comment]
应该是detail的，进入全屏模式的代码是
mOrientationUtils.resolveByClick();
mPlayer.startWindowFullscreen(PandaStreamActivity.this, true, true);

**Comment by CarGuo** [comment]
detail的话，参看demo的onBackPressed
