### ISSUE TITLE
如何实现像爱奇艺那种先试播几分钟，后面购买后才可以全部播放？

### ISSUE THREAD

**Issue by Jibinghao** [CarGuo/GSYVideoPlayer#2430]
## 问题描述：

如何实现像爱奇艺那种先试播几分钟，后面购买后才可以全部播放？

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2276
