### ISSUE TITLE
rtmp直播流关闭packet-buffering会播着播着卡死，开启packet-buffering后卡住调用startPlayLogic会黑屏

### ISSUE THREAD

**Issue by lixuandeng** [CarGuo/GSYVideoPlayer#2431]
## 问题描述：

使用StandardGSYVideoPlayer播放**rtmp直播流**，播着播着回调了onIno()方法，参数what值为MediaPlayer.MEDIA_INFO_BUFFERING_START = **701**，哦，是开始缓冲了，但是视频就**卡在缓冲开始的那一帧再也不播放**了，必须要调用startPlayLogic()方法才能继续播放，但是调用此方法过程中可能是相当于重新初始化播放器，于是会有1-2秒的**黑屏**，用户体验很不好。

 于是我去问题集锦找了17条按照您的代码一字不拉写了，没有缓冲了，但是直播流仍然会播着播着就卡在某一帧然后永远都起不来了，求助！！谢谢作者。

## 问题机型/系统：

真机小米6 Android9.0 锤子手机（大部分机型都复现过）

## GSY依赖版本

`implementation 'com.shuyu:GSYVideoPlayer:7.1.1'`

## Demo中的复现步骤

没有在demo中试过。

问题代码：(如果有)
```
GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_DEFAULT);
//            GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);
            //EXOPlayer内核，支持格式更多
            //PlayerFactory.setPlayManager(Exo2PlayerManager.class);

            VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
            List<VideoOptionModel> list = new ArrayList<>();
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
            list.add(videoOptionModel);
            //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
            list.add(videoOptionModel);


    @Override
    public void onInfo(int what, int extra) {
        super.onInfo(what, extra);
        if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START && isLiveStreaming == 1) {
            startPlayLogic();
        }
    }


```

## 问题log（如果有）

```

无log，卡住以后的isInPlayingState()还是返回true。

```

我猜测这可能是ijkplayer源码的问题，因为之前使用ijkplayer也有遇到同样的问题，只是想问下作者是否知道怎么规避，是否可以让我的直播流禁止packet-buffering但是不会卡顿，或者开启packet-buffering卡顿后调用哪个重新开始方法能让直播流不黑屏，都可以，谢谢。

**Comment by CarGuo** [comment]
是的，确实是， rtmp 推荐切换到 exoplayer 内核模式 PlayerFactory.setPlayManager(Exo2PlayerManager.class);

**Comment by lixuandeng** [comment]
> 是的，确实是， rtmp 推荐切换到 exoplayer 内核模式 PlayerFactory.setPlayManager(Exo2PlayerManager.class);

那请教下，是在原来代码的基础上增加这一行代码就可以了吗，我增加了以后rtmp直播流无法播放，我调试发现一直回调GSYVideoView中的onInfo方法。

` @Override
    public void onInfo(int what, int extra) {
        if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START) {
            mBackUpPlayingBufferState = mCurrentState;
            //避免在onPrepared之前就进入了buffering，导致一只loading
            if (mHadPlay && mCurrentState != CURRENT_STATE_PREPAREING && mCurrentState > 0)
                setStateAndUi(CURRENT_STATE_PLAYING_BUFFERING_START);
        } 
    }`

what一直返回701，明明在按照您写的配置中，我已经把package-buffering关了，但是由于一直回调到oninfo走不出去，导致视频没有播放出来，我试着在videoplayer中重写了以下：
` @Override
    public void setOverrideExtension(String overrideExtension) {
        this.mOverrideExtension = overrideExtension;
    }`

还是一直回调onInfo返回701，请问我该怎么解决呢？谢谢作者！

**Comment by lixuandeng** [comment]
> 是的，确实是， rtmp 推荐切换到 exoplayer 内核模式 PlayerFactory.setPlayManager(Exo2PlayerManager.class);

那请教下，不知道是不是我写的顺序有问题，以下：

`
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
            List<VideoOptionModel> list = new ArrayList<>();
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
            list.add(videoOptionModel);
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
            list.add(videoOptionModel);
            //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
            videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
            list.add(videoOptionModel);     
GSYVideoManager.instance().setOptionModelList(list);

            //EXOPlayer内核，支持格式更多
            PlayerFactory.setPlayManager(Exo2PlayerManager.class);
            
            ijkVideoView.startPlayLogic();
`
然而视频播放的时候还是会卡顿，并且回调videoplayer中的onInfo方法，what=701，我的问题并没有得到解决，请问该如何处理呢，谢谢作者！！

**Comment by CarGuo** [comment]
onInfo 卡顿 701 是因为 MEDIA_INFO_BUFFERING_START 吧， Exo2PlayerManager.class 下 VideoOptionModel 是无效的
