### ISSUE TITLE
setShowType是默认的，为什么还是拉升了呢

### ISSUE THREAD

**Issue by barryyanggoing** [CarGuo/GSYVideoPlayer#2432]
设置后显示视频
![TIM图片20191128105724](https://user-images.githubusercontent.com/13274104/69773491-fdaa8480-11cd-11ea-93ed-3a824e6e8696.jpg)
正确显示视频
![TIM截图20191128105653](https://user-images.githubusercontent.com/13274104/69773495-000cde80-11ce-11ea-9f9f-07a967d5488f.png)
帮忙看下，谢谢。

**Comment by CarGuo** [comment]
不是很明白

**Comment by barryyanggoing** [comment]
就是本来是竖向的视频，加载后成了横向铺满了

**Comment by CarGuo** [comment]
有视频url吗？

**Comment by barryyanggoing** [comment]
你好，我QQ发给你了，因为我用的是本地视频，没有视频的链接。

**Comment by CarGuo** [comment]
收到了 ，拿到的尺寸就是  videoWidth: 1280 videoHeight: 720

**Comment by CarGuo** [comment]
下个版本修复
