### ISSUE TITLE
实现类似抖音效果

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#2434]
我们项目现在需要做类似抖音的效果，需求如下：

- 当播放当前视频时，自动缓存后面几个视频

- 视频缓冲不要一下缓冲完。比如缓冲20s，停止缓冲，等到播放到10s时继续缓冲后面10s ，以此类推。

大佬，请问此框架可以实现吗

**Comment by CarGuo** [comment]
sorry，没有现成的

**Comment by CarGuo** [comment]
不过你看最新demo，有一个 DetailDownloadPlayer ，你看看怎么处理

**Comment by zhangyujiu** [comment]
好的，谢谢了

**Comment by zhangyujiu** [comment]
你好，我仿照DetailDownloadPlayer实现预先下载功能，但是没有下载整个视频，文件命名使用Md5FileNameGenerator命名后加上.download后缀，这时关闭网络播放缓存的这个视频并不能播放，请问是怎么回事，谢谢
