### ISSUE TITLE
音频播放没有封面的问题

### ISSUE THREAD

**Issue by sunnyamuren** [CarGuo/GSYVideoPlayer#2437]
这个我觉得是功能的欠缺，提个意见
## 问题描述：
音频播放的时候，一片黑色，没有cover，看过源码，在prepare后，就
        setViewShowState(mThumbImageViewLayout, INVISIBLE);
所以不可见cover了。
我是继承StandardGSYVideoPlayer，如果自己覆写 抽象函数，那么需要自己判断播放源是音频还是视频，来控制mThumbImageViewLayout 的显示，但会和 GSYVideoControlView 类 Line376 Onclick中的 else if (i == R.id.thumb)，分支冲突。
此处提个issue，看看作者有什么意见，谢谢

## 问题机型/系统：
所有
## GSY依赖版本
 api 'com.shuyu:GSYVideoPlayer:7.1.1'

**Comment by sunnyamuren** [comment]
我觉得算是个功能性的缺失，希望能改进

**Comment by CarGuo** [comment]
你可以继承后重写 getLayoutId，覆盖你喜欢的控件

**Comment by sunnyamuren** [comment]
了解您的意思，不过，覆盖之后，封面的父布局，在父类中还是有处理的，总体而言，可能需要改变布局的层次。目前我自己处理掉了，在跟布局重新增加封面布局，原来的您的封面布局依然存在。只是觉得这么写，有点难受，可能还是我看的源码不够深入。

**Comment by CarGuo** [comment]
就是你 getLayoutId 返回你自己的布局，cv 原本的布局之后，在上面覆盖你自己的布局做封面之类的就好了啊～～～布局只要 id 和 class 一样，其他的位置什么的都无所谓的

**Comment by sunnyamuren** [comment]
这个我理解，id一样就可以，不过 R.id.thumb 这个layout，在GSYVideoControlView 这个类里有click事件处理，继承StandardGSYVideoPlayer 重写changeUiToNormal changeUiToPlayingShow 这几个函数，来控制 封面的显示，是不行的。设置可见后，点击的时候，` public void onClick(View v) {
        int i = v.getId();
        if (mHideKey && mIfCurrentIsFullscreen) {
            hideNavKey(mContext);
        }
        if (i == R.id.start) {
            clickStartIcon();
        } else if (i == R.id.surface_container && mCurrentState == CURRENT_STATE_ERROR) {
            if (mVideoAllCallBack != null) {
                Debuger.printfLog("onClickStartError");
                mVideoAllCallBack.onClickStartError(mOriginUrl, mTitle, this);
            }
            prepareVideo();
        } else if (i == R.id.thumb) {
            if (!mThumbPlay) {
                return;
            }
            if (TextUtils.isEmpty(mUrl)) {
                Debuger.printfError("********" + getResources().getString(R.string.no_url));
                //Toast.makeText(getActivityContext(), getResources().getString(R.string.no_url), Toast.LENGTH_SHORT).show();
                return;
            }
            if (mCurrentState == CURRENT_STATE_NORMAL) {
                if (isShowNetConfirm()) {
                    showWifiDialog();
                    return;
                }
                startPlayLogic();
            } else if (mCurrentState == CURRENT_STATE_AUTO_COMPLETE) {
                onClickUiToggle();
            }
        } else if (i == R.id.surface_container) {
            if (mVideoAllCallBack != null && isCurrentMediaListener()) {
                if (mIfCurrentIsFullscreen) {
                    Debuger.printfLog("onClickBlankFullscreen");
                    mVideoAllCallBack.onClickBlankFullscreen(mOriginUrl, mTitle, GSYVideoControlView.this);
                } else {
                    Debuger.printfLog("onClickBlank");
                    mVideoAllCallBack.onClickBlank(mOriginUrl, mTitle, GSYVideoControlView.this);
                }
            }
            startDismissControlViewTimer();
        }`
surface_container 这块的事件就无法响应了。现在我继承重写后，在根布局 自己加了个 imageview，占位显示倒是可以满足需求，只是不是很好的方法，其实是 觉得，是否作者可以考虑，在播放音频的时候，有个开关选择是否保持显示 cover呢？ 这样的话，源码里面的点击事件 我觉得要修改的。

**Comment by CarGuo** [comment]
音频播放后续会增加直接支持

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/commit/5e5ae182457830be7778df0f6a43ccafc228316d
