### ISSUE TITLE
GSYVideo 是否能够支持多屏异显！

### ISSUE THREAD

**Issue by AnandLin** [CarGuo/GSYVideoPlayer#2439]
## 问题描述：

GSYVideo 是否能够支持多屏异显！发现GSYVideo播放器在使用Android多屏异显时，在副屏使用的继承自Dialog的Presentation进行显示。当副屏幕播放视频，主屏幕会被暂停播放，并且黑屏现象，查看代码发现只有一个GSYVideoManager单例，但使用支持多视频CustomManager依然出现切换到视频后会抢占另外在播视频的资源，导致另外一个屏幕黑屏现象

## 问题机型/系统：

努比亚z17mini 或 内部Android测试机

**Comment by CarGuo** [comment]
没测试过 Presentation 下的情况，但是如果是custommanager，只要tag之类的不同，应该不会抢占，比如demo

**Comment by AnandLin** [comment]
你好，我设置过不同的Tag，在setUp之前，但好像依然不起左右，我的界面效果是Banner里面嵌套视频的，在多屏幕时候，只要一端屏幕切换过来时候，另一段视频就会画面暂停，声音被抢占情况！
`if(isMainScreen){
            gsyVideo.setPlayTag("Main");
        }else {
            gsyVideo.setPlayTag("Sub");
        }
        if(media.getPath() != null){
            gsyVideo.setUp(media.getPath(),media.getHeadLength(), false, "");
        }else {
            gsyVideo.setUp(media.getUrl(),"", true, "");
        }
        gsyVideo.setLooping(true);`

**Comment by CarGuo** [comment]
MultiSampleVideo 的 onAudioFocusChangeListener 应该重新处理过了啊

**Comment by AnandLin** [comment]
可以了，有效果了，謝謝，这里还有个疑问，就是多屏时候想设置副屏设置静音效果，利用setNeedMute设置，如下：
`if(isMainScreen){
    gsyVideo.setPlayTag("Main");
    gsyVideo.setNeedMute(false);
}else {
    gsyVideo.setPlayTag("Sub");
    gsyVideo.setNeedMute(true);
}
if(media.getPath() != null){
    gsyVideo.setUp(media.getPath(),media.getHeadLength(), false, "");
}else {
    gsyVideo.setUp(media.getUrl(),"", true, "");
}
gsyVideo.setLooping(true);`
在EmptyControlVideo中设置了静音代码：
`public void setNeedMute(boolean needMute){
    CustomManager.getCustomManager(getKey()).setNeedMute(needMute);
}`
但发现首次是有效果的，在副屏轮播完一次后，依然会出现多个声音效果的！

**Comment by CarGuo** [comment]
这就不是很清楚了，你调试看看是不是哪里没生效吧～

**Comment by AnandLin** [comment]
可以了，应该是触发条件位置不正确的原因，我在启动播放后在设置静音就没问题的！谢谢大神抽时间帮忙解答！
