### ISSUE TITLE
你这个全屏和非全屏的状态切换我怎么老是驾驭不了

### ISSUE THREAD

**Issue by leeyushi** [CarGuo/GSYVideoPlayer#2445]
切换到全屏后，非全屏的状态老是会丢失，还有注册事件之类的也会丢失，从新注册也不行，同样的代码，一部分View不会丢失样式，一部分View会丢失显示样式，明明已经都用相同的办法保存过了

**Comment by leeyushi** [comment]
切换到全屏，怎么把注册事件的回调也绑定过去

**Comment by leeyushi** [comment]
功能多，文档写的再详细也还是很乱，爬了两天坑， 很多东西不调试源码根本搞不明白，到现在有一些东西还没搞明白

**Comment by CarGuo** [comment]
全屏是和全屏是通过    startWindowFullscreen  、resolveNormalVideoShow  和  cloneParams 实现，开源项目也就是自己看源码，又不完整的付费项目
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/GSYVIDEO_PLAYER_PROJECT_INFO.md
