### ISSUE TITLE
rtsp直播流播放，获取btye[]数据的问题？

### ISSUE THREAD

**Issue by wflian** [CarGuo/GSYVideoPlayer#2448]
问题描述：
播放rtsp直播源视频正常，有办法获取rtsp直播源的数据吗？这边要做转码处理，rtp推流给服务器？

问题机型/系统：
所有版本。

GSY依赖版本
 implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
  implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.1'
  implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.1'

播放已经没有问题，只是轻微的延迟，想问问有办法获取直播的 视频数据吗

**Comment by CarGuo** [comment]
目前不支持获取btye[]数据，延迟目前我也木有什么好的方法～～
