### ISSUE TITLE
设置为循环播放后，不会执行onAutoCompletion方法吗？

### ISSUE THREAD

**Issue by barryyanggoing** [CarGuo/GSYVideoPlayer#2450]
## 问题描述：

设置为循环播放后，播放完成，不会执行onAutoCompletion方法吗？

如果有其他的回调方法，是哪个呢

**Comment by weifengteng** [comment]
同问

**Comment by kyriej** [comment]
同问，

**Comment by CarGuo** [comment]
……肯定不会执行啊，执行了就释放了。。。
循环播放就像是动画的repeat -1一样，你如果需要的话，可以外部监听进度实现循环播放的次数监听
