### ISSUE TITLE
播放广告时如何显示返回按钮

### ISSUE THREAD

**Issue by shuaimango** [CarGuo/GSYVideoPlayer#2451]
感谢

**Comment by CarGuo** [comment]
自己实现布局啊，你可以重写广告播放控件的 getLayoutId

**Comment by shuaimango** [comment]
> 自己实现布局啊，你可以重写广告播放控件的 getLayoutId

不是布局的问题。播放正常视频时，点击视频画面会出现返回按钮，标题栏等；播放广告时，点击什么都不会出现，现在需求是点击时返回按钮要显示出来。我看源码做了 * 广告期间不需要触摸的处理，是这个原因吧？

**Comment by CarGuo** [comment]
是的，具体逻辑其实你都可以参考继承方法去自定义
