### ISSUE TITLE
怎么提前获取视频的宽高，然后改变父布局的大小，因为是在recycleview里面，大小不固定

### ISSUE THREAD

**Issue by kylodw** [CarGuo/GSYVideoPlayer#2452]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
服务器返回给你啊………不然你一个一个自己去解析每种协议的容器头信息吗？

**Comment by kylodw** [comment]
好吧，谢谢解答。现在就是服务器没返回，然后我自己计算，怎么实现都不太行，点击播放后的我在onVideoSizeChanged里处理好了。
