### ISSUE TITLE
夜间模式和视频横屏全屏似乎有冲突

### ISSUE THREAD

**Issue by farendaibiao** [CarGuo/GSYVideoPlayer#2456]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

夜间模式
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
时，视频切换成横屏全屏显示会闪屏，视频播放进度失效，显示横屏普通模式的初始界面。
竖屏（注释orientationUtils.resolveByClick();之后）可以正常衔接。

## 问题机型/系统：

华为荣耀6plus

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤
activity使用AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
切换到夜间模式

全屏代码和Demo一样
        danmakuVideoPlayer.getFullscreenButton().setOnClickListener(v -> {
            //直接横屏
            orientationUtils.resolveByClick();
            //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
            danmakuVideoPlayer.startWindowFullscreen(VideoPlayerActivity.this, true, true);
        });

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by farendaibiao** [comment]
补充问题log
https://github.com/CarGuo/GSYVideoPlayer/issues/1869
就是这个，如果没有catch
tv.danmaku.ijk.media.player.AndroidMediaPlayer.getVideoHeight(AndroidMediaPlayer.java:201)

**Comment by CarGuo** [comment]
我在 demo 中测试正常

**Comment by farendaibiao** [comment]
> 我在 demo 中测试正常

我这里OrientationUtils里面调用了setRequestedOrientation就会导致Video信息丢失
在AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);下

**Comment by farendaibiao** [comment]
> 我在 demo 中测试正常
我这里OrientationUtils里面调用了setRequestedOrientation就会导致Video信息丢失
在AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);下


        <activity
            android:name=".activity.VideoPlayerActivity"
            android:configChanges="keyboard|orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Translucent" />

**Comment by CarGuo** [comment]
？？？

**Comment by farendaibiao** [comment]
> ？？？
在AppCompatDelegate.MODE_NIGHT_YES下，OrientationUtils里面setRequestedOrientation调用改变屏幕方向就会导致Video信息丢失。
AppCompatDelegate.MODE_NIGHT_NO时没问题

Manifest和一般的一样
        <activity
            android:name=".activity.VideoPlayerActivity"
            android:configChanges="keyboard|orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Translucent" />

**Comment by CarGuo** [comment]
问题是我在 demo 中没有复现问题， 难道是 8.0 以上的 https://www.jianshu.com/p/1ed07ddbbbe5 这个冲突？？？

**Comment by farendaibiao** [comment]
> 问题是我在 demo 中没有复现问题， 难道是 8.0 以上的 https://www.jianshu.com/p/1ed07ddbbbe5 这个冲突？？？

整个帖子看过，不大确定是不是这样，我手上真机没有安卓6以上的。一般用模拟器雷电、夜神等等能到安卓7。

**Comment by CarGuo** [comment]
有点诡异，复现不来现在

**Comment by farendaibiao** [comment]
> 有点诡异，复现不来现在

我现在只能确定横纵屏切换用setRequestedOrientation会有些问题产生，和视频全屏没关系。
问题在哪我一直没查出来

**Comment by farendaibiao** [comment]
> 有点诡异，复现不来现在

![image](https://user-images.githubusercontent.com/48914448/70306667-68009c00-1842-11ea-91d4-a45d4626e6c2.png)

**Comment by farendaibiao** [comment]
> 有点诡异，复现不来现在

![image](https://user-images.githubusercontent.com/48914448/70306791-ae55fb00-1842-11ea-9490-551f4a639cc4.png)

夜间模式下旋屏被检测到了
android:configChanges="orientation"这个似乎没起作用

**Comment by farendaibiao** [comment]
> > 有点诡异，复现不来现在
> 
> ![image](https://user-images.githubusercontent.com/48914448/70306791-ae55fb00-1842-11ea-9490-551f4a639cc4.png)
> 
> 夜间模式下旋屏被检测到了
> android:configChanges="orientation"这个似乎没起作用

![image](https://user-images.githubusercontent.com/48914448/70306981-1e648100-1843-11ea-932f-3da7a5dfb04d.png)
再加一个细节

**Comment by dudukee** [comment]
将`OrientationUtils`中的
```java
if (mVideoPlayer != null && mVideoPlayer.isVerticalFullByVideoSize()) {
    return; }
```
try-catch暂时解决了, 不知道有没有更好的方案

**Comment by farendaibiao** [comment]
> 将`OrientationUtils`中的
> 
> ```java
> if (mVideoPlayer != null && mVideoPlayer.isVerticalFullByVideoSize()) {
>     return; }
> ```
> 
> try-catch暂时解决了, 不知道有没有更好的方案

我也是catch了，只能保证不崩溃。。。

**Comment by CarGuo** [comment]
我是比较奇怪为啥我没复现······

**Comment by dudukee** [comment]
> 我是比较奇怪为啥我没复现······

我这边崩溃场景是这样的:
开启自动旋屏的前提下, 手机横屏, 点击视频详情页, 详情页有推荐视频, 如果视频加载成功就手动返回非全屏状态, 一直点推荐视频. 
这么操作3-5次就会出现这个crash

**Comment by CarGuo** [comment]
我尽量看看能否复现

**Comment by CarGuo** [comment]
经过测试我这边没有复现问题，如果最新 demo 存在问题请重新开一个 issue
