### ISSUE TITLE
添加gradle依赖后，gradle同步没问题，但是运行工程提示Cause: duplicate entry: android/support/v4/media/MediaBrowserCompat$CallbackHandler.class，项目无法运行

### ISSUE THREAD

**Issue by PayneJay** [CarGuo/GSYVideoPlayer#2457]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:GSYVideoPlayer:7.1.2'`

## Demo中的复现步骤

无

## 问题log（如果有）

```

Cause: duplicate entry: android/support/v4/media/MediaBrowserCompat$CallbackHandler.class


```

**Comment by CarGuo** [comment]
androix  ， 没有用 support，冲突了
<img width="591" alt="image" src="https://user-images.githubusercontent.com/10770362/70424614-9c769100-1aaa-11ea-8b00-8994d0213d06.png">

**Comment by PayneJay** [comment]
> 项目现在用的是 androidx ， 没有用 support，冲突了
> <img alt="image" width="591" src="https://user-images.githubusercontent.com/10770362/70424614-9c769100-1aaa-11ea-8b00-8994d0213d06.png">

那是需要把我的项目升到androidx？或者哪个版本是没有用Androidx的，我依赖下那个版本

**Comment by CarGuo** [comment]
6开头的没有，你看下更新文档，首页有链接

**Comment by PayneJay** [comment]
> 6开头的没有，你看下更新文档，首页有链接

好的，多谢🙏

**Comment by PayneJay** [comment]
文档上有获取第一帧的功能，没有找到对应的方法，想问下是哪个😅

**Comment by CarGuo** [comment]
Demo里现在直接用 Glide 获取了

**Comment by PayneJay** [comment]
> Demo里现在直接用 Glide 获取了

项目是基于ijkplayer，因此也应该集成了ffmpeng，所以是否支持ffmpeng命令实现视频转码和获取某一帧，或者项目里有提供现成的方法可供调用吗？
