### ISSUE TITLE
ExoPlayerCacheManager EXO缓存模式下怎么实现预加载

### ISSUE THREAD

**Issue by cherysky** [CarGuo/GSYVideoPlayer#2460]
## 问题描述：

ExoPlayerCacheManager EXO缓存模式下可以实现预加载么，就像抖音那样，播放当前这一条预加载下一条

## 问题机型/系统：

真机 小米note2 Android7.0

## GSY依赖版本

 implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
//是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.1'
//根据你的需求ijk模式的so
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.1'

## Demo中的复现步骤
由于公司的视频都是m3u8格式的，所以使用了EXO内核，并且使用EXO缓存，现在需要新增一个像抖音一样的预加载功能，播放当前视频时候预先加载下一条视频，这样子滑到下一条时候就可以立即播放，做到无加载播放下一条视频，请问可以实现吗，有没有现成API可以调用

问题代码：(如果有)
无

## 问题log（如果有）
无

**Comment by CarGuo** [comment]
你看demo自定义exo，用了拼接sourcre可以实现类似效果
