### ISSUE TITLE
全屏模式下播放结束，这个时候拖动进度条自动回到最后一秒。

### ISSUE THREAD

**Issue by Jibinghao** [CarGuo/GSYVideoPlayer#2465]
## 问题描述：

全屏模式下播放结束，这个时候拖动进度条自动回到最后地方。

 PlayerFactory.setPlayManager(Exo2PlayerManager.class);

## 问题机型/系统：

华为MATE20PRO 

## GSY依赖版本

 api 'com.shuyu:GSYVideoPlayer:7.1.2'

## Demo中的复现步骤

在全屏正常播放，当播放结束后，拖动进度条到任意位置，松手后自动滚到最后一秒

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by Jibinghao** [comment]
[视频.zip](https://github.com/CarGuo/GSYVideoPlayer/files/3959744/default.zip)
录制了一个视频，效果图如上，需要解压出来。

**Comment by CarGuo** [comment]
播放结束之后，内核默认是直接被 release 的

**Comment by Jibinghao** [comment]
但是进度条还是可以拖动，画面不动，而声音在播放。

**Comment by CarGuo** [comment]
没有啊，我在 demo 测试， 全屏 release 之后拖动进度条不会播放声音
