### ISSUE TITLE
播放m3u8时， 获取用户快进后，如何获取将要播放的切片 

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#2467]
播放m3u8时， 获取用户快进后，如何获取将要播放的切片 

现在采用的方法是根据获取快进后的Duration ，自己判断 要加载的切片。
这样 不精准，纯在误差。

**Comment by CarGuo** [comment]
除了使用 exo 内核然后自定义 source 支持自己获取 ts ，其他都不支持

**Comment by yang0000meng** [comment]
哪还是自己 判断吧
