### ISSUE TITLE
视频同步：有声音，没画面，拖动进度条无效

### ISSUE THREAD

**Issue by and1990** [CarGuo/GSYVideoPlayer#2468]
问题描述：

场景：
1. Activity A 有个播放器，Activity B也有有个播放器
2. 在Activity A点击按钮跳转到Activity B，Activity B能够同步播放画面和进度
3. 从Activity B返回后，Activity A也能够同步Activity B的播放画面和进度

问题：
反复查看了demo，没有Activity之间跳转视频同步的例子。仿照demo实现后，有声音，没画面，拖动进度条没有效果的。

## 问题机型/系统：

锤子坚果pro2，一加7pro

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤
如上场景描述

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
如果 demo 没问题，我也没什么办法

**Comment by and1990** [comment]
> 如果 demo 没问题，我也没什么办法

不是demo没有问题，是你的demo中没有activity之间共享player的例子。

**Comment by CarGuo** [comment]
现在的实现是到列表就停止了，如果要的话请自己自定义

**Comment by and1990** [comment]
> 现在的实现是到列表就停止了，如果要的话请自己自定义

我试了下回到最初的Activity后出现了”有声音，进度条正常显示，画面可以显示，但没有播放“。

最初的Activity A：
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.switch_list_video_item);
        gsyVideoPlayer = findViewById(R.id.video_item_player);
        String url = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
        View detailButton = gsyVideoPlayer.findViewById(R.id.detail_btn);
        detailButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                SwitchUtil.savePlayState(gsyVideoPlayer);
                jump = true;
                gsyVideoPlayer.getGSYVideoManager().setLastListener(gsyVideoPlayer);
                SwitchDetailActivity.startTActivity(SwitchVideoActivity.this, gsyVideoPlayer);

            }
        });
        gsyVideoPlayer.setUp(url, true, "测试啊");
        gsyVideoPlayer.startPlayLogic();
    }

    @Override
    protected void onResume() {
        if (jump) {
            SwitchUtil.clonePlayState(gsyVideoPlayer);
            gsyVideoPlayer.setSurfaceToPlay();
        }
        super.onResume();
    }
```

跳转后的Activity B：
``` @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.switch_activity_detail_player);
        detailPlayer = findViewById(R.id.detail_player);
        SwitchUtil.optionPlayer(detailPlayer, getIntent().getStringExtra(URL), true, "这是title");

        SwitchUtil.clonePlayState(detailPlayer);

        detailPlayer.setIsTouchWiget(true);

        detailPlayer.setSurfaceToPlay();

        ViewCompat.setTransitionName(detailPlayer, OPTION_VIEW);
    }

    @Override
    protected void onPause() {

        SwitchUtil.savePlayState(detailPlayer);

        super.onPause();
    }
```
现象：

1. 首次进入到A页面后，视频正常播放
2. 点击按钮进入B页面后，可以正常同步A的播放画面、进度，播放正常
3.点击返回按钮，返回A页面后，可以正常同步B的进度，声音也有，但是画面没有播放

**Comment by and1990** [comment]
再补充一点。
如果一个Activity有2个player，视频可以正常同步，没有问题，代码如下。
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.switch_list_video_item);

        player = findViewById(R.id.video_item_player);
        player.findViewById(R.id.detail_btn).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                jump = true;
                SwitchUtil.savePlayState(player);
                player.getGSYVideoManager().setLastListener(player);

                SwitchUtil.clonePlayState(player2);
                player2.setSurfaceToPlay();
            }
        });
        player.setUp(url, true, "测试啊");
        player.startPlayLogic();


        player2 = findViewById(R.id.video_item_player2);
        player2.findViewById(R.id.detail_btn).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                SwitchUtil.savePlayState(player2);
                player2.getGSYVideoManager().setLastListener(player2);

                SwitchUtil.clonePlayState(player);
                player.setSurfaceToPlay();

            }
        });
    }
```

但是在2个Activity间进行视频同步时，返回第1个activity后，视频不播放。

**Comment by CarGuo** [comment]
> 2个Activity间进行视频同步时，返回第1个activity后，视频不播放。

这是设定就是这样···

**Comment by savage-lin** [comment]
> 再补充一点。
> 如果一个Activity有2个player，视频可以正常同步，没有问题，代码如下。
> 
> ```
> @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         setContentView(R.layout.switch_list_video_item);
> 
>         player = findViewById(R.id.video_item_player);
>         player.findViewById(R.id.detail_btn).setOnClickListener(new View.OnClickListener() {
>             @Override
>             public void onClick(View v) {
>                 jump = true;
>                 SwitchUtil.savePlayState(player);
>                 player.getGSYVideoManager().setLastListener(player);
> 
>                 SwitchUtil.clonePlayState(player2);
>                 player2.setSurfaceToPlay();
>             }
>         });
>         player.setUp(url, true, "测试啊");
>         player.startPlayLogic();
> 
> 
>         player2 = findViewById(R.id.video_item_player2);
>         player2.findViewById(R.id.detail_btn).setOnClickListener(new View.OnClickListener() {
>             @Override
>             public void onClick(View v) {
>                 SwitchUtil.savePlayState(player2);
>                 player2.getGSYVideoManager().setLastListener(player2);
> 
>                 SwitchUtil.clonePlayState(player);
>                 player.setSurfaceToPlay();
> 
>             }
>         });
>     }
> ```
> 
> 但是在2个Activity间进行视频同步时，返回第1个activity后，视频不播放。

大佬，最后怎么解决的？列表返回怎么让画面动起来？
