### ISSUE TITLE
类似ios那种实时缩略图预览

### ISSUE THREAD

**Issue by nxnyk** [CarGuo/GSYVideoPlayer#2469]
![~~N5FH%(XOZ%5@FXHA)MC)V](https://user-images.githubusercontent.com/42330422/70877423-5a90a200-1ff8-11ea-9e4a-f48652782cb9.png)
 类似这种的，在底部显示每一帧的实时缩略图，这个怎么实现呀。大佬能否给点思路啥的

**Comment by CarGuo** [comment]
这个要你自己取帧，你可以用 Gilde 或者其他库去取

**Comment by nxnyk** [comment]
取到了。。但是不知道用啥去关联视频。。

**Comment by nxnyk** [comment]
尝试用recycleview。。但是好像不太好实现。。

**Comment by CarGuo** [comment]
类似 PreViewGSYVideoPlayer
