### ISSUE TITLE
怎么去掉播放控件的开始按钮？

### ISSUE THREAD

**Issue by lingchen52** [CarGuo/GSYVideoPlayer#247]
我在做一个直播软件，需要进去后直接播放视频，不显示播放开始、暂停按钮、进度条、时间等view,怎么设置？

**Comment by loveRose** [comment]
该参数在GSYBaseVideoPlayer类的View参数mStartButton，实例化一般都在他的实现子类中的init，比如GSYVideoPlayer继承了GSYBaseVideoPlayer，在init方法中对mStartButton进行实例化 
protected void init(Context context) {
        this.mContext = context;
        View.inflate(context, getLayoutId(), this);
        mStartButton = findViewById(R.id.start);
        mSmallClose = findViewById(R.id.small_close);
        mBackButton = (ImageView) findViewById(R.id.back);
。。。
等，你需要的界面ui都在这里面
