### ISSUE TITLE
视频缓存成功后，为什么还会在去重复请求视频的部分数据

### ISSUE THREAD

**Issue by xxchenqi** [CarGuo/GSYVideoPlayer#2470]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
你好，我在做轮播视频功能时候发现的问题：
通过Charles抓包发现，视频在缓存成功后(确认已缓存，在断网的情况可以播放)，
在去播放时，还会在重复请求视频的部分数据，
抓包发现Range：bytes=3693962- ，
实际视频在第一次请求的时候已经加载完成了。

我自己用phpStudy开文件服务时，再次播放就不会出现这个问题。
我们内网文件服务的路径大概是这样的:
http://172.31.27.164:82/imp/test/downloadfile/download/?fileName=group1_M00/00/01/rB8bpV3lwPmAMLfZACI-mBPB9nc456.mp4

是否是文件服务器的问题，导致重复去请求 视频部分数据?是的话应该如何修改？

## 问题机型/系统：

例如 真机 华为MLA-AL10 Android7.0

## GSY依赖版本

    implementation 'com.shuyu:GSYVideoPlayer:7.1.2'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.2'

## Demo中的复现步骤

无

问题代码：(如果有)
```
无
```

## 问题log（如果有）

```
无
```

**Comment by CarGuo** [comment]
你说的是缓冲还是缓存？？？？？

**Comment by xxchenqi** [comment]
> 你说的是缓冲还是缓存？？？？？

缓存，代码里用的方法边播边缓存：
videoPlayer.setUp(url, true, "");

**Comment by CarGuo** [comment]
如果是默认缓存，你看本地的内部目录下是否已经保存完整的视频文件看看，如果是完整保存了的话，url 应该会被重置为 file 开头的

**Comment by xxchenqi** [comment]
> 如果是默认缓存，你看本地的内部目录下是否已经保存完整的视频文件看看，如果是完整保存了的话，url 应该会被重置为 file 开头的

我查看了data/data/包名/cache/video-cache/目录下的文件分别是:
545e089d7c451ad36a60e98d5ff34772.mp4.download
5814c42f516e4b7f4e82e8b5e8eeed14.mp4
8384219518fd3bb8d0b7c0e830b68b95.mp4.download
8a98af2fc86667e10c38808a1a2b1a9a.mp4.download

我用的是exo模式:
PlayerFactory.setPlayManager(Exo2PlayerManager.class);

其中3个文件后缀是.download，是不是这3个文件没有下载完整？
这个是否是文件服务器那边的问题导致没有下载完整？

**Comment by CarGuo** [comment]
是的，.download 说明还没有下载完整
