### ISSUE TITLE
ExoPlayer模式和IJKPlayer模式，两种同时开启，ExoPlayer不起作用

### ISSUE THREAD

**Issue by kyzgxiaoguo** [CarGuo/GSYVideoPlayer#2474]
## 
ExoPlayer模式和IJKPlayer模式，两种同时开启，ExoPlayer不起作用

## 问题描述：

ExoPlayer模式和IJKPlayer模式，两种同时开启，ExoPlayer不起作用

## 问题机型/系统：

例如 真机 华为meta20

## GSY依赖版本
    api 'com.shuyu:gsyVideoPlayer-java:6.0.3'

    api 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

    api 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'

## Demo中的复现步骤
在Application中，进行全局两种模式开启：ExoPlayer和IJKPlayer，但是ExoPlayer不起作用

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
同时还能使用一种
