### ISSUE TITLE
关于设置报文头不生效的问题

### ISSUE THREAD

**Issue by ekfans** [CarGuo/GSYVideoPlayer#2477]
大家好，我在使用GSY的时候，应要求，需要设置视频流的header，但是我在player.setMapHeadData之后，使用Wireshark抓包后，并没有找到我设置进去的头。是我设置对么？

**Comment by CarGuo** [comment]
如下图，我这边测试看到的数据正常。

![image](https://user-images.githubusercontent.com/10770362/71224969-fdeff880-2311-11ea-96e8-bbcdf652f279.png)

**Comment by ekfans** [comment]
> 如下图，我这边测试看到的数据正常。
> 
> ![image](https://user-images.githubusercontent.com/10770362/71224969-fdeff880-2311-11ea-96e8-bbcdf652f279.png)

和我们自己编译了Ijkplayer动态库有关系么？因为我们自己编译了动态库以支持rtsp协议

**Comment by CarGuo** [comment]
这就不清楚了，gsy的ex_so 依赖也支持 rtsp，你可以看问题集锦试试

**Comment by ekfans** [comment]
> 这就不清楚了，gsy的ex_so 依赖也支持 rtsp，你可以看问题集锦试试

好的，谢谢！
