### ISSUE TITLE
关于关闭系统自动旋转情况下的视频旋转

### ISSUE THREAD

**Issue by L1nS** [CarGuo/GSYVideoPlayer#2478]
## 问题描述：

需求：在关闭系统的自动旋转情况下，
进入全屏模式（左侧横屏），手机为竖直时不需要旋转，当手机转到右侧时候，希望视频能反转过来，变为右侧横屏。
demo中没看到我想要的这种效果。

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

**Comment by CarGuo** [comment]
把 video 和用到的 OrientationUtils 的 RotateWithSystem 设置为false
