### ISSUE TITLE
不能播放未缓存完的视频

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#2479]
## 问题描述：

缓存一部分视频后关闭网络，重新打开页面播放缓存文件，播放失败

## 问题机型/系统：

例如 真机 华为mate20

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## 问题log（如果有）

```

tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

```

**Comment by CarGuo** [comment]
demo 怎么复现，测试正常

**Comment by zhangyujiu** [comment]
把SimplePlayer中的地址换成`https://resource.ghzs.com/video/game/5db26ccbac85e2013b5c7bb4.mp4` 试一下呢
实现步骤：
1. 打开SimplePlayer加载一部分缓存
2. 快速关闭页面并关闭网络
3. 再次打开SimplePlayer，视频不能播放

**Comment by zhangyujiu** [comment]
但是这个视频是可以的呢`https://resource.ghzs.com/video/game/5d663bbca6b93e01024b6123.mp4`

**Comment by CarGuo** [comment]
我看了下，应该是视频编码的问题，就是 GOP 和 IBP 帧的编排问题，缓存的视频部分因为帧序列编码不够没办法完整解析

**Comment by zhangyujiu** [comment]
那应该没有解决方法吧

**Comment by CarGuo** [comment]
我这边暂时没有

**Comment by zhangyujiu** [comment]
那好吧，非常感谢
