### ISSUE TITLE
怎么切换音轨？

### ISSUE THREAD

**Issue by lingchen52** [CarGuo/GSYVideoPlayer#248]
我有一个么m3u8的直播流，里面有多个音轨，只有一个和视频是同步的，其它的音轨和视频无关，使用ijkplayer解码时，播放的音轨是随机的，有时正常，有时不正常，怎么解决这个问题，能给些方法和建议吗？我之前参照博客http://blog.csdn.net/yangchengtest/article/details/52996835修改了一些ijkplayer的源码，但博客后面一部分看不懂，不知道怎么做，求解答，望尽快回复，谢谢！

**Comment by CarGuo** [comment]
![wechatimg19](https://cloud.githubusercontent.com/assets/10770362/26482307/6084c520-4219-11e7-97a7-8d725c75c7aa.jpeg)

**Comment by lingchen52** [comment]
@CarGuo 我用getTrackInfo()得到音轨后，使用selectTrack(int track)切换音轨ijkplayer总是报错，log上打印header missing,这是啥原因，是我使用方式不对吗？
``final List<Integer> audiotracks = new ArrayList<>();
        mIjkplayerLivePreview.setOnPreparedListener(new IMediaPlayer.OnPreparedListener() {
            @Override
            public void onPrepared(IMediaPlayer mp) {
                ITrackInfo[] ijkTrackInfos = mIjkplayerLivePreview.getTrackInfo();
                for (int i = 0; i < ijkTrackInfos.length; i++) {
                    if(ijkTrackInfos[i].getTrackType() == ITrackInfo.MEDIA_TRACK_TYPE_AUDIO){
                        if(ijkTrackInfos[i].getInfoInline().contains("kb/s")){
                            audiotracks.add(i);
                            Log.d("LivePreviewActivity", "------------");
                        }
                    }
                }
                if (audiotracks.size() > 0) {
                    //多音轨切换
                    mIjkplayerLivePreview.selectTrack(audiotracks.size() - 1);
                }
