### ISSUE TITLE
关于关闭系统自动旋转下的视频全屏旋转问题。

### ISSUE THREAD

**Issue by L1nS** [CarGuo/GSYVideoPlayer#2480]
## 问题描述：

[https://github.com/CarGuo/GSYVideoPlayer/issues/2478](url)
可能是我的描述有问题。
将video 和用到的 OrientationUtils 的 RotateWithSystem 设置为false，并没有达到我想要的效果。
我看了工具类中的代码。
if (!autoRotateOn && mRotateWithSystem) {
                    return;
                }
置为false后只是跳过了这个判断，达到在关闭系统自动旋转后还能够自动旋转。
而我想要的效果，你可以参考b站的视频播放
在关闭系统自动旋转情况下
1.视频处于非全屏。旋转手机屏幕，不会进入全屏模式。
2.视频处于全屏。手机为竖直情况，视频不会退出全屏，也不会旋转。只会在手机横屏时候翻转。

目前我想自己重写一个OrientationUtils工具类，在activity中使用。
但是看到OrientationUtils这个类在GSYBaseVideoPlayer和GSYVideoHelper里面都有使用，这样会不会引起冲突？

**Comment by CarGuo** [comment]
如上提交所示，目前只能下个版本支持了

**Comment by L1nS** [comment]
运行了最新的代码，发现一个小问题
`// 设置反向横屏
                else if (rotation > 30 && rotation < 95) {
                    if (mClick) {
                        if (!(mIsLand == LAND_TYPE_REVERSE) && !mClickPort) {
                            return;
                        } else {
                            mClickLand = true;
                            mClick = false;
                            mIsLand = LAND_TYPE_REVERSE;
                        }
                    } else if (!(mIsLand == LAND_TYPE_REVERSE)) {
                        mScreenType = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
                        mActivity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_REVERSE_LANDSCAPE);
                        if (mVideoPlayer.getFullscreenButton() != null) {
                            mVideoPlayer.getFullscreenButton().setImageResource(mVideoPlayer.getShrinkImageRes());
                        }
                        mIsLand = LAND_TYPE_REVERSE;
                        mClick = false;
                    }
                }`

还是在关闭系统自动旋转情况下
进入全屏，显示为向左的全屏，此时直接向右转，无法反向横屏
因为mClick=true，mIsLand=1，直接走return。
必须向左转后，mClick=false。再向右，才能反向横屏

**Comment by CarGuo** [comment]
是的，点击的必须过去了，这个是设计这样的
