### ISSUE TITLE
如何使直播视频暂停一会后点击播放按钮，按照视频实际的时间继续进行播放？

### ISSUE THREAD

**Issue by ErieCorner** [CarGuo/GSYVideoPlayer#2481]
## 问题描述：

- 需求要直播视频暂停一会继续播放时按照视频实际时间继续进行播放，而不是暂停的那个时间继续播放。

## GSY依赖版本

`implementation 'com.shuyu:GSYVideoPlayer:6.0.3'`；因没有适配AndroidX，所以用的是低版本依赖。

**Comment by CarGuo** [comment]
Release 之后重新 startplaylogic

**Comment by alen252** [comment]
> Release 之后重新 startplaylogic

恢复播放的时候执行Release再startplaylogic，这样会黑屏 @CarGuo
