### ISSUE TITLE
请问播放器怎么屏蔽触摸滑动快进功能？亮度和声音不能屏蔽

### ISSUE THREAD

**Issue by zhangnin** [CarGuo/GSYVideoPlayer#2485]
setIsTouchWiget(true)
setIsTouchWigetFull(true)

这样设置会把声音、亮度都给屏蔽掉的。我只想屏蔽快进功能。

**Comment by CarGuo** [comment]
重载 `touchSurfaceMove` 方法，针对 mChangePosition 进行处理
