### ISSUE TITLE
平板项目整体固定横屏，GsyVideoPlayer点击全屏后点返回走旋转逻辑直接把屏幕方向设置竖屏

### ISSUE THREAD

**Issue by liverloop** [CarGuo/GSYVideoPlayer#2488]
使用的小播放器，放大没问题，点退出全屏就把方向切换为竖屏了？

**Comment by liverloop** [comment]
使用的 6.0.3版本

**Comment by liverloop** [comment]
如何配置后， 不使用代码的旋转？

**Comment by CarGuo** [comment]
不是很理解

**Comment by VCE-K** [comment]
我也遇到了这个问题，我是自己看着GSYVideoPlayer的示例apk的fragment下使用的例子敲了一遍，我也是平板屏幕固定不能自动旋转，然后我点击视频的全屏，视频只显示一秒，就会直接把app的屏幕方向设置竖屏，而且还在fragment的视频列表页面，只是屏幕变成显示横屏显示了，这个时候再列表任意视频点击全屏就没问题，能正常显示和发声。ps:我复制了一遍代码拿过来运行也是会这样子，华为平板，美特11

**Comment by VCE-K** [comment]
老兄，能告诉我如何解决吗
