### ISSUE TITLE
可以用项目中的方法实时监听网络变化吗

### ISSUE THREAD

**Issue by moujunqiang** [CarGuo/GSYVideoPlayer#2489]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
可以用项目中的方法实时监听网络变化吗
GSYVideoVidew中的createNetWorkState（）方法不是public的，只能自己额外重新写监听吗

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
是的，自己外部监听

**Comment by moujunqiang** [comment]
大部分视频播放都有这个4g和wifi网络状态切换监听去给用户提示，后面会考虑增加网络监听方法，方便开发者重写实现自己的逻辑吗

**Comment by CarGuo** [comment]
这个功能内置了，请看源码

**Comment by moujunqiang** [comment]
嗯看到有这个方法，就是外部调用不到

**Comment by moujunqiang** [comment]
这个功能内置了 想咨询下具体怎么去自定义使用呢

**Comment by CarGuo** [comment]
protect 的方法，重载就好了

**Comment by moujunqiang** [comment]
还有一个问题，内置的网络状态监听，在切换全屏再切回之后就网络监听就被销毁了

**Comment by CarGuo** [comment]
因为切换是切换了的控件，会重新构建，你看全屏的逻辑就知道了

**Comment by moujunqiang** [comment]
全屏切换到全屏这个时候是可以继续监听到，从全屏再切换到半屏就监听不到了。

**Comment by CarGuo** [comment]
哦哦，我觉得你的场景是播放完或者没有播放就全屏，之后返回的时候非全屏的没有构建，这是项目的 bug

**Comment by CarGuo** [comment]
你可以重载 resolveNormalVideoShow 方法，然后super 之后加上这个

```

        if (mCurrentState != CURRENT_STATE_NORMAL
                || mCurrentState != CURRENT_STATE_AUTO_COMPLETE) {
            createNetWorkState();
        }
```

**Comment by moujunqiang** [comment]
重载resolveNormalVideoShow 这个方法 我在自己的项目和demo中都试了 不行
