### ISSUE TITLE
可以循环播放吗 ?

### ISSUE THREAD

**Issue by rzy686** [CarGuo/GSYVideoPlayer#249]
可以循环播放吗 ?
比如 视频 播放结束后 设置 下一个 视频源 , 相关的 视图 进行初始化 什么的

**Comment by rzy686** [comment]
![Uploading 图片.png…]() 刚看到

**Comment by rzy686** [comment]
不好意思 刚看到
 —— DetailListPlayer 详情类型的DEMO，播放一个列表，自动播放下一个，手机旋转\点击全屏等效果。

**Comment by insomniatt** [comment]
断网以后 开启了 cache 缓存 能循环播放吗? demo 测试的时候是停止了
