### ISSUE TITLE
拖动进度条重新缓存

### ISSUE THREAD

**Issue by moujunqiang** [CarGuo/GSYVideoPlayer#2498]
## 问题描述：
视频播放过程中有缓存完，这时候点击进度条切换进度之后会重新缓存消耗流量
## 问题机型/系统：

真机 一加5t  android9.0
## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的SimpleDetailActivityMode2页面打开后会出现这个问题。

**Comment by moujunqiang** [comment]
准确的说应该是缓冲，消耗流量缓存完毕，点击进度条之后会重新缓冲再次消耗流量

**Comment by CarGuo** [comment]
这是正常的，你可以去理解缓冲和缓存的差别，缓冲你seek之后就会重新请求，因为缓冲是一个很小的块不断的在内存你走。

**Comment by moujunqiang** [comment]
这个应该是不正常的吧，边播边存。我播放的时候已经消耗流量缓存了，既然正常情况断网是可以继续播放的，但是seek之后就要重新请求重新缓存再次消耗流量，这个应该是不合理的

**Comment by haohaozaici** [comment]
系统MediaPlayer向前(未播放内容的区域)seek，已缓冲的内容不会重新缓冲，如web页播放，Exoplayer好像也是这样(忘了~)，ijkplayer会重新缓冲。
向后seek全都会重新缓冲。

ijkplayer可以使用`AndroidVideoCache`优化此问题
exoplayer可以添加`CacheDataSource`优化此问题

**Comment by moujunqiang** [comment]
目前使用过程中向前向后都会重新缓冲

**Comment by moujunqiang** [comment]
想问下大神是什么情况下导致的这个问题呢？

**Comment by haohaozaici** [comment]
说说我的理解，已缓冲表示通过网络请求，或本地文件等数据源，加载到InputStream中作为可以随时读取的内容。
往已缓冲且播放过的区域拖动时，因为数据使用完之后就出队列了，并没有记录下来，所以需要重新加载到InputStream。
往已缓冲且未播放内容的区域拖动时，可以根据位置读取InputStream指定内容，所以在部分情况下不需要重新加载到InputStream。

要解决你的问题，就是在网络请求时，先将网络内容下载到本地，再加载到InputStream，这样就不需要重复进行网络请求了，`AndroidVideoCache`，`CacheDataSource`都可以做到。

**Comment by CarGuo** [comment]
你说的缓存已经有了也内置了，你可以看源码。
你应该理解缓冲的概念，ffmpeg中所谓的缓冲就是一个很小的块，而且这个块的大小是可以配置，缓冲是在内存里，这个块一般只会维持一个固定大小。
如果你seek了就会清楚之后重置
