### ISSUE TITLE
错误的style导致编译不通过

### ISSUE THREAD

**Issue by hewjinxu** [CarGuo/GSYVideoPlayer#2499]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
错误的style定义导致编译不通过

## 问题机型/系统：

黑鲨手机2

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

问题代码：(如果有)
```
    <style name="common_title_tv">
        <item name="android:textColor">@color/</item>
    </style>
```

## 问题log（如果有）

```
\merged.dir\values\values.xml:7721: error: expected color reference but
got (raw string) @color/.
```

**Comment by CarGuo** [comment]
不是项目问题。冲突请自行解决

**Comment by hewjinxu** [comment]
比较奇怪的是.gradle缓存中gsyplayer-java目录中有这个style，总是编译不过，我手动将.gradle中gsyplayer的value.xml这个style删除后编译通过了。

**Comment by CarGuo** [comment]
common_title_tv  如果我没记错，我这边应该没有这个

**Comment by hewjinxu** [comment]
网络抖动导致解包错乱？不管怎么样，不是gsy的问题，感谢老哥，加油
