### ISSUE TITLE
上次提到的夜间模式旋屏造成闪屏崩溃的解决方案

### ISSUE THREAD

**Issue by farendaibiao** [CarGuo/GSYVideoPlayer#2500]
问题如下：
https://github.com/CarGuo/GSYVideoPlayer/issues/2456
解决方案出自
https://blog.csdn.net/llld5553/article/details/99622202

android:configChanges="orientation|keyboard|screenSize|uiMode|keyboardHidden"
加上uiMode，防止用户模式变化造成的问题

**Comment by CarGuo** [comment]
收到，thx~~
