### ISSUE TITLE
关于播放实时byte[]数据源的问题

### ISSUE THREAD

**Issue by wflian** [CarGuo/GSYVideoPlayer#2501]
## 问题描述：
第三方外设返回的实时byte[]视频流，该播放器支持吗？
## 问题机型/系统：
所有手机
## GSY依赖版本
implementation 'com.shuyu:GSYVideoPlayer:7.1.2'

**Comment by CarGuo** [comment]
切换使用 eco 内核 ： `PlayerFactory.setPlayManager(Exo2PlayerManager.class);`
使用自定的 `ExoSourceManager.setExoMediaSourceInterceptListener`  MediaSource
自定义  MediaSource 的 DataSource

DataSource 的 read 方法就有 byte[] 数据。

```
 int read(byte[] buffer, int offset, int readLength) throws IOException;
```

**Comment by wflian** [comment]
不是要读取视频的byte[]数据，是要播放外接设备回调的yuv的byte[]数据或者h264的byte[]数据

**Comment by pie-tk** [comment]
@wflian 我也是要播放byte的h265视频数据，你成功了吗？

**Comment by caik123** [comment]
> 切换使用 eco 内核 ： `PlayerFactory.setPlayManager(Exo2PlayerManager.class);`
> 使用自定的 `ExoSourceManager.setExoMediaSourceInterceptListener` MediaSource
> 自定义 MediaSource 的 DataSource
> 
> DataSource 的 read 方法就有 byte[] 数据。
> 
> ```
>  int read(byte[] buffer, int offset, int readLength) throws IOException;
> ```

能给个例子吗？

**Comment by caik123** [comment]
> 切换使用 eco 内核 ： `PlayerFactory.setPlayManager(Exo2PlayerManager.class);`
> 使用自定的 `ExoSourceManager.setExoMediaSourceInterceptListener` MediaSource
> 自定义 MediaSource 的 DataSource
> 
> DataSource 的 read 方法就有 byte[] 数据。
> 
> ```
>  int read(byte[] buffer, int offset, int readLength) throws IOException;
> ```

能给个例子吗？

**Comment by Onewon** [comment]
> > 切换使用 eco 内核 ： `PlayerFactory.setPlayManager(Exo2PlayerManager.class);`
> > 使用自定的 `ExoSourceManager.setExoMediaSourceInterceptListener` MediaSource
> > 自定义 MediaSource 的 DataSource
> > DataSource 的 read 方法就有 byte[] 数据。
> > ```
> >  int read(byte[] buffer, int offset, int readLength) throws IOException;
> > ```
> 
> 能给个例子吗？

https://github.com/google/ExoPlayer/issues/4212

**Comment by chenchongyu** [comment]
请问你最后实现该功能了吗？

**Comment by CarGuo** [comment]
@chenchongyu  v8.3.0 之后有，IJK 下支持：

 * feat(Media DataSource): Video playback data source supports data input stream.(Currently only IJK kernel is supported) (#3582)
