### ISSUE TITLE
wav格式的在demo里无法播放

### ISSUE THREAD

**Issue by zhangjianwei1** [CarGuo/GSYVideoPlayer#2504]

**Comment by zhangjianwei1** [comment]
自己放进DEMO里的一个wav文件，使用音频播放无法播放音频

**Comment by CarGuo** [comment]
[支持wav](https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md#支持wav)

https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite.sh

https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh

https://www.jianshu.com/p/bd289e25d272

**Comment by zhangjianwei1** [comment]
群主可以拉我入群么，QQ扫码因为没有绑定银行卡付不了费，可以微信支付您，QQ:931920687
微信:18548914366

**Comment by hughdev** [comment]
> 支持wav

不明白啥意思啊？重新编译？还是啥意思呀？
