### ISSUE TITLE
不是要读取视频的byte[]数据，是要播放外接设备回调的yuv的byte[]数据或者h264的byte[]数据

### ISSUE THREAD

**Issue by wflian** [CarGuo/GSYVideoPlayer#2505]
## 问题描述：

不是要读取视频的byte[]数据，是要播放外接设备回调的yuv的byte[]数据或者h264的byte[]数据

## 问题机型/系统：

全部

## GSY依赖版本
implementation 'com.shuyu:GSYVideoPlayer:7.1.2'

**Comment by CarGuo** [comment]
实话实说，那你需要的根本不是播放器项目吧？？？？你只是需要绘制就行啦，要不用opengl要不直接用glsurfaceview啊

**Comment by wflian** [comment]
嗯！绘制的方案我已经实现了！因为项目中，有rtsp、url视频的播放，引入你的项目，所以想看看有没有直接播放的方式。

**Comment by hanyechun** [comment]
> 嗯！绘制的方案我已经实现了！因为项目中，有rtsp、url视频的播放，引入你的项目，所以想看看有没有直接播放的方式。
你好，请问怎么实现的？

**Comment by hanyechun** [comment]
@wflian 你好，请问你怎么绘制的？
