### ISSUE TITLE
大哥 如何获取到视频播放区域的宽高

### ISSUE THREAD

**Issue by WangkeqiangS** [CarGuo/GSYVideoPlayer#2506]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

需求是：获取到视频播放区域的宽高  仅显示画面部分的区域

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
@Override
    public int getCurrentVideoWidth() {
        if (getGSYVideoManager() != null) {
            return getGSYVideoManager().getVideoWidth();
        }
        return 0;
    }

    @Override
    public int getCurrentVideoHeight() {
        if (getGSYVideoManager() != null) {
            return getGSYVideoManager().getVideoHeight();
        }
        return 0;
    }

在视频 prepared 成功之后

**Comment by WangkeqiangS** [comment]
大哥 这样获取的是视频的宽高   我想获取的是视频播放区域view的宽高

**Comment by CarGuo** [comment]
？？？？？视频播放区域你直接看获取不就得了

**Comment by WangkeqiangS** [comment]
mDetailPlayer.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
               Log.e("1111",mDetailPlayer.getWidth()+"***"+mDetailPlayer.getHeight());
            }
        });

**Comment by WangkeqiangS** [comment]
这样获取出的view宽高  就包括了黑色区域
想获取的是  显示画面的区域  不包括黑色区域

**Comment by WangkeqiangS** [comment]
谢谢大哥  我知道该怎么搞了
getCurrentPlayer().getRenderProxy().getShowView().getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                @Override
                public void onGlobalLayout() {
                    int height = getCurrentPlayer().getRenderProxy().getShowView().getHeight();
                    int width = getCurrentPlayer().getRenderProxy().getShowView().getWidth();
                }
            });

**Comment by 951AB159BA** [comment]
> 
> 
> 谢谢大哥 我知道该怎么搞了
> getCurrentPlayer().getRenderProxy().getShowView().getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
> @override
> public void onGlobalLayout() {
> int height = getCurrentPlayer().getRenderProxy().getShowView().getHeight();
> int width = getCurrentPlayer().getRenderProxy().getShowView().getWidth();
> }
> });

为什么我使用了你的方法还是横屏的全屏幕包括黑边的高宽度？大佬你怎么弄的？

**Comment by WangkeqiangS** [comment]
我这边是没问题的&nbsp; 你再试一下其它的视频，会不会是你视频的问题，获取出来的宽高单位是px




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bright little angel holy sword"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 晚上6:09
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"眉间雪"<2443209949@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 大哥 如何获取到视频播放区域的宽高 (#2506)





  
谢谢大哥 我知道该怎么搞了
 getCurrentPlayer().getRenderProxy().getShowView().getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
 @override
 public void onGlobalLayout() {
 int height = getCurrentPlayer().getRenderProxy().getShowView().getHeight();
 int width = getCurrentPlayer().getRenderProxy().getShowView().getWidth();
 }
 });
  
为什么我使用了你的方法还是横屏的全屏幕包括黑边的高宽度？大佬你怎么弄的？

**Comment by nxnyk** [comment]
> 我这边是没问题的&nbsp; 你再试一下其它的视频，会不会是你视频的问题，获取出来的宽高单位是px
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"bright little angel holy sword"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月27日(星期一) 晚上6:09 收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;; 抄送:&nbsp;"眉间雪"<2443209949@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 大哥 如何获取到视频播放区域的宽高 (#2506) 谢谢大哥 我知道该怎么搞了 getCurrentPlayer().getRenderProxy().getShowView().getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() { @override public void onGlobalLayout() { int height = getCurrentPlayer().getRenderProxy().getShowView().getHeight(); int width = getCurrentPlayer().getRenderProxy().getShowView().getWidth(); } }); 为什么我使用了你的方法还是横屏的全屏幕包括黑边的高宽度？大佬你怎么弄的？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

老哥，你这是在哪儿设置的这个监听呀？

**Comment by WangkeqiangS** [comment]
我继承了StandardGSYVideoPlayer重写了onPrepared()方法，在这里面做的操作

**Comment by nxnyk** [comment]
> 我继承了StandardGSYVideoPlayer重写了onPrepared()方法，在这里面做的操作

听君一席话胜读十年书，悟了悟了~谢谢老哥~
