### ISSUE TITLE
请问，声音在播，画面不动，这种情况怎么处理，有那个方法可以监听吗？

### ISSUE THREAD

**Issue by zhangnin** [CarGuo/GSYVideoPlayer#2507]

**Comment by CarGuo** [comment]
没有，怎么出现的这种情况？

**Comment by zhangnin** [comment]
播放器在A页面，第一次进入A页面，A页面里点击再次进入A页面【先finish之前的】，这个时候会出现画面暂停声音播放的现象

**Comment by wj576038874** [comment]
我也遇到了相同的问题 列表播放 当播放的item滑出屏幕时，就调用GSYVideoManager.onPause();暂停播放 然后当重新显示出来的时候调用GSYVideoManager.onResume(true); 画面不动了 进度条再动，声音也在播放 就是画面无法继续播放

**Comment by CarGuo** [comment]
@wj576038874 你这个是不一样，你这个是滚出屏幕就被释放了，正常情况，如果有疑问可以看源码。

**Comment by CarGuo** [comment]
@zhangnin  你的问题我没有复现，不过很明显是生命周期控制视频内核的问题。

**Comment by wj576038874** [comment]
> @wj576038874 你这个是不一样，你这个是滚出屏幕就被释放了，正常情况，如果有疑问可以看源码


> @wj576038874 你这个是不一样，你这个是滚出屏幕就被释放了，正常情况，如果有疑问可以看源码。



> 我也遇到了相同的问题 列表播放 当播放的item滑出屏幕时，就调用GSYVideoManager.onPause();暂停播放 然后当重新显示出来的时候调用GSYVideoManager.onResume(true); 画面不动了 进度条再动，声音也在播放 就是画面无法继续播放



> @wj576038874 你这个是不一样，你这个是滚出屏幕就被释放了，正常情况，如果有疑问可以看源码。



> @wj576038874 你这个是不一样，你这个是滚出屏幕就被释放了，正常情况，如果有疑问可以看源码。
滑出屏幕的时候 我只是调用了GSYVideoManager.onPause();暂停播放 没有想demo中调用GSYVideoManager.releaseAllVideos();释放呀  然后重新可见的时候我调用GSYVideoManager.onResume(true);恢复播放  进度条都是对的 也执行了seekTo方法 但是就是画面不动  这个有什么好的解决办法吗？

**Comment by wj576038874** [comment]
> @CarGuo  
滑出屏幕的时候 我只是调用了GSYVideoManager.onPause();暂停播放 没有想demo中调用GSYVideoManager.releaseAllVideos();释放呀 然后重新可见的时候我调用GSYVideoManager.onResume(true);恢复播放 进度条都是对的 也执行了seekTo方法 但是就是画面不动 这个有什么好的解决办法吗？

**Comment by CarGuo** [comment]
@wj576038874  你看源码啊，应该是 surafce 没创建吧

**Comment by wj576038874** [comment]
@CarGuo  可以指点一下不  QAQ

**Comment by wj576038874** [comment]
@CarGuo GSYVideoManager.onPause();调用这个方法时候  surafce销毁了吗？

**Comment by wangtaolin** [comment]
> 没有，怎么出现的这种情况？
使用设备为小米电视机，然后网络不太好的情况下会必现！

**Comment by CarGuo** [comment]
没这个条件复现问题啊我这边😂😂

**Comment by anjiuzhe** [comment]
@wj576038874 也是你这种情况，有什么解决办法吗？
