### ISSUE TITLE
GSYVideoPlayer subtitle with (.srt) file 

### ISSUE THREAD

**Issue by YasirNabeel** [CarGuo/GSYVideoPlayer#2509]
i just wondering the way of implementation a method to show subtitle from srt file using GSYVideoPlayer

**Comment by CarGuo** [comment]
GSYVideoPlayer  default use Ijkplayer , only support mkv subtitle like this ：

```
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "subtitle", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

if you choose  Exo2 : `PlayerFactory.setPlayManager(Exo2PlayerManager.class);` I add a new demo like ：https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exosubtitle

**Comment by YasirNabeel** [comment]
Thank you, I did use the Exo2 with the help from your demo and it's worked perfectly but it was missing merging media source with an array of media sources so i can add more then one subtitle or more then video sources for different qualities so it can be controlled correctly by "Track Selection Dialog" like so in the kotlin code below:
`val mediaSourceArray: ArrayList<BaseMediaSource> = ArrayList()
mediaSourceArray.add(videoSource)
subtitles!!.subtitles.forEach {
val textMediaSource = SingleSampleMediaSource.Factory(dataSourceFactory)
                                       .createMediaSource(Uri.parse(it.url), textFormat, C.TIME_UNSET)
mediaSourceArray.add(textMediaSource)
}

val mediaSource =
MergingMediaSource(*mediaSourceArray.toArray(arrayOfNulls(mediaSourceArray.size)))`

**Comment by CarGuo** [comment]
You can custom what you need. Demo mainly provides ideas for implementation.
good luck!
