### ISSUE TITLE
本地视频预览播放，承载视频的TextureView四周留黑边问题

### ISSUE THREAD

**Issue by ttsy-80** [CarGuo/GSYVideoPlayer#2510]
@CarGuo 
问题描述：
1 ，本地视频预览播放，视频四周留黑边问题
2，本地视频宽*高 = 1920 * 1080，设置播放比例GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_16_9);

 问题机型/系统：
 真机 华为 nova 3e Android9.0 (其实多个手机都出现这个问题)

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'`

## Demo中的复现步骤
打开Demo中SimplePlayer界面，更改播放地址为本地地址，设置播放比例为
GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_16_9);

**Comment by CarGuo** [comment]
？？？黑边不正常？？？？

**Comment by ttsy-80** [comment]
[http://chuantu.xyz/t6/710/1578398467x2073530527.jpg](url)  像这样显示

**Comment by CarGuo** [comment]
如果可以麻烦提供视频链接

**Comment by ttsy-80** [comment]
是用手机拍摄的本地视频，用华为手机竖拍，生成的视频分辨率是1920*1080，视频角度应该是90

**Comment by CarGuo** [comment]
我这边没办法看出是什么问题····
