### ISSUE TITLE
高帧播放问题，请问一下  120帧以上的播放，声音卡顿，这个需要怎么处理呢

### ISSUE THREAD

**Issue by lwl49** [CarGuo/GSYVideoPlayer#2511]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放手机本地问题，该文件是120帧以上的，播放到一半，画面正常，声音卡顿这样的问题！

## 问题机型/系统：

基本所有所有都会，vivo x23  nova 4

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后，使用简单播放，简单直接播放也会出现声音卡顿。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
试试切换到 PlayerFactory.setPlayManager(Exo2PlayerManager.class);

如果是默认 ijk 的，可以试试 

VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);

**Comment by lwl49** [comment]
OK了，使用IJK 的那个设置，请问这个设置是将帧的设置吗？把120帧，将到50来播放？

**Comment by CarGuo** [comment]
就是丢帧
