### ISSUE TITLE
报错：Hit dns cache but connect fail hostname = ***.****.***, ip = 

### ISSUE THREAD

**Issue by EsZhangHome** [CarGuo/GSYVideoPlayer#2514]
## 问题描述：

报错dns连接错误：

真机 vivo X23 android 9 

E/IJKMEDIA: Failed to resolve hostname ***.****.***: No address associated with hostname

播放过程中出现这种情况的报错。咋回事，求大神指点!

**Comment by EsZhangHome** [comment]
问题解决

**Comment by bananaCaptain** [comment]
@EsZhangHome 请问怎样解决的？谢谢
