### ISSUE TITLE
什么时候出flutter版?

### ISSUE THREAD

**Issue by ThinOfSnowDance** [CarGuo/GSYVideoPlayer#2515]
## 问题描述：

什么时候出flutter版?

## 问题机型/系统：

什么时候出flutter版?

## GSY依赖版本

什么时候出flutter版?

## Demo中的复现步骤

什么时候出flutter版?

问题代码：(如果有)
```
什么时候出flutter版?
```

什么时候出flutter版?

```

什么时候出flutter版?

```

**Comment by CarGuo** [comment]
想下 iOS 需要从头做一半 GSY ，顶不住顶不住。

**Comment by eyingyang** [comment]
希望出个flutter版，嘿嘿！
