### ISSUE TITLE
Detail页面切换全屏失败

### ISSUE THREAD

**Issue by mzh1992** [CarGuo/GSYVideoPlayer#2516]
## 问题描述：
自定义UI添加了一个控件后，不是添加在topLayout和bottomLayout中，全屏切换时产生了Bug.

## 问题机型/系统：

redmi k20 pro    android 10

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2

## Demo中的复现步骤

Demo中的detailPlayer页面中的LandLayoutVideo 的布局文件sample_video_normal中随意在根布局添加一个ImageView，然后切换使用全屏功能，发现不能切换全屏，此时显示为一半黑屏，一半正常显示详情页。
![1](https://user-images.githubusercontent.com/7950227/72121916-683b0c80-3397-11ea-9f12-7ae5df9dd097.png)
![2](https://user-images.githubusercontent.com/7950227/72121917-68d3a300-3397-11ea-9e60-3ff3f7aab5e0.png)
问题代码：(如果有)

-----布局中添加的控件----

<ImageView
        android:id="@+id/test_image_view"
        android:layout_width="40dp"
        android:layout_height="80dp"
        android:layout_alignParentRight="true"
        android:src="@mipmap/ic_launcher" />

-------------------------------

LandLayoutVideo 覆盖的方法

private View test_image_view;

 @Override
    protected void init(Context context) {
        super.init(context);
        //省略中间部分代码

        test_image_view = findViewById(R.id.test_image_view);
    }

@Override
    protected void changeUiToPlayingShow() {
        super.changeUiToPlayingShow();
        test_image_view.setVisibility(View.VISIBLE);
    }

    @Override
    protected void changeUiToPlayingClear() {
        super.changeUiToPlayingClear();
        test_image_view.setVisibility(View.INVISIBLE);
    }

**Comment by 748297973** [comment]
我也这样,具体什么原因
