### ISSUE TITLE
播放器普通，全屏切换播放时间归零

### ISSUE THREAD

**Issue by hikalids** [CarGuo/GSYVideoPlayer#2518]
#2517  问题描述：
单播放器播放时，用的systemplayerManager从小屏幕全屏互相切换时，播放内容重新从头播放，但是seekbar时间没有变

## 问题机型/系统：
OppoA57
Android 23

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
demo复现？
