### ISSUE TITLE
音频和视频数据是分开的byte,能否支持同时播放，且同步

### ISSUE THREAD

**Issue by pie-tk** [CarGuo/GSYVideoPlayer#2519]
## 问题描述：

从远程分别取得音频和视频的byte数据，如何能同时播放

## 问题机型/系统：

所有

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2505
