### ISSUE TITLE
视频快进和跳播问题

### ISSUE THREAD

**Issue by loveRose** [CarGuo/GSYVideoPlayer#252]
现在情况是这样的，当我视频比较长，一般是1到2个小时，当我开始播放，拖动进度条到一定长度的时候，他会加载很久很久很久，这个很久已经无法让人接受了，这个播放器调节播放点的时候   他需要把该点之前的内容全部加载完成之后才能播放啊，并不能点击哪个点，就从哪个点开始加载播放啊？？？

**Comment by CarGuo** [comment]
你是否开启了边播边缓存？？

**Comment by loveRose** [comment]
使用的是 m3u8,如果使用mp4格式没问题，mp4进入首次加载会慢一点但是不会出现拖动卡顿一直加载的情况，而m3u8首次加载会很快，但是拖动大多会出现一直加载，加载几分钟才能播放，以上情况都未开启缓存，并且m3u8视频不能开启缓存，开启之后会无法播放

**Comment by CarGuo** [comment]
这种情况ijk那边之前的issue回复的，这是服务器的问题比较可能

**Comment by loveRose** [comment]
但是相对iOS来说却不存在这个问题，那边也是用的m3u8，他们是用的阿里云上面的播放器SDK

**Comment by CarGuo** [comment]
因为所谓的m3u8就是多分片的视频拼接在一起，这个你需要看阿里云的那个播放sdk是否有携带哪些请求header或者其他特殊处理，来配合实现m3u8的seek

**Comment by loveRose** [comment]
那也就是。。。这个seekTo直接加载当前点的功能咯？？？

**Comment by CarGuo** [comment]
是的，只是m3u8的格式比较特殊，针对多分片，seekto之后其实有可能等于切换的到其他分片了。

**Comment by CarGuo** [comment]
https://github.com/Bilibili/ijkplayer/issues/3172

**Comment by drivedreams** [comment]
我也有这个问题：https://github.com/Bilibili/ijkplayer/issues/2874
我分析了好久，到现在还没解决，后来用了vitamio 同样的视频就没有这个问题，应该不是视频源的问题。 我分析了一部分，大家可以一起分析下啊

**Comment by CarGuo** [comment]
所有的M3u8吗？还是特定的，因为vitamio和exo等的，视频的同步时钟和ijk的不大一样，就像某些压缩过的视频，关键帧太少，ijk直接seekto之后就跳转回0

**Comment by loveRose** [comment]
出问题的是m3u8，也不是所有的，我查出，出问题的视频都是在某个点有问题，应该是播放器的容错率，这个容错需要处理时间长




发自网易邮箱大师
在2017年06月08日 20:41，Shuyu Guo 写道：

所有的M3u8吗？还是特定的，因为vitamio和exo等的，视频的同步时钟和ijk的不大一样，就像某些压缩过的视频，关键帧太少，ijk直接seekto之后就跳转回0

**Comment by liujinggit** [comment]
flv格式的我也遇到了,拖动的话会加载很长很长时间,有时间还加载不出来,黑屏,又重新播放了...

**Comment by KXwonderful** [comment]
试了下本地flv格式的，播放时拖动的话会加载很长时间，偶尔还会加载不出来，又重新播放了
