### ISSUE TITLE
DanmakuVideoPlayer类的onCompletion方法会引发ANR，导致崩溃

### ISSUE THREAD

**Issue by zhangnin** [CarGuo/GSYVideoPlayer#2521]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

DanmakuVideoPlayer类的onCompletion方法会引发ANR，导致崩溃

## 问题机型/系统：

VIVO V1818CA | Android 8.1.0,level 27
荣耀 YAL AL00 | Android 10,level 29
小米 MI 9 | Android 10,level 29
魅族 PRO 5 | Android 7.0,level 24
金立 S10CL | Android 7.1.1,level 25

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)

DanmakuVideoPlayer.java

    @Override
    public void onCompletion() {
        releaseDanmaku(this);
    }

## 问题log（如果有）

Input dispatching timed out

ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 18. Wait queue head age: 5619.5ms.)

1 java.lang.Object.wait(Native Method)
2 java.lang.Object.wait(Object.java:422)
3 java.lang.Thread.join(Thread.java:1262)
4 java.lang.Thread.join(Thread.java:1338)
5 master.flame.danmaku.ui.widget.DanmakuView.k(DanmakuView.java:9)
6 master.flame.danmaku.ui.widget.DanmakuView.j(DanmakuView.java:1)
7 master.flame.danmaku.ui.widget.DanmakuView.release(DanmakuView.java:1)
8 com.example.gsyvideoplayer.video.DanmakuVideoPlayer.onCompletion(DanmakuVideoPlayer.java:131)

**Comment by CarGuo** [comment]
DanmakuVideoPlayer 应该是在 demo 里的，应该是可以自己修改和处理问题的吧？
