### ISSUE TITLE
请问能实时播放从网络获取的每一帧byte视频数据吗

### ISSUE THREAD

**Issue by pie-tk** [CarGuo/GSYVideoPlayer#2522]
## 问题描述：

实时从网络获取的一帧一帧byte视频数据，如何实时丢给播放器播放？有相应的接口吗？

## 问题机型/系统：

真机

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2501#issuecomment-570109088
