### ISSUE TITLE
视频被裁剪成正方形

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#2524]
## 问题描述：

在浏览器上播放能正常显示视频尺寸，但在手机上播放就被裁成正方形了，全屏播放也会被裁，麻烦大佬看一下

![image](https://user-images.githubusercontent.com/13781886/72399719-ecb7d180-3781-11ea-94ab-b52fd8ee380f.png)

## 问题机型/系统：
所有机型

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

把Demo中的SimplePlayer页面的地址替换为下面地址

`https://resource.ghzs.com/video/game/5deb5663b625b569173a2712.mp4`

**Comment by CarGuo** [comment]
基础播放器之后，重载 getLaoutId ，然后将 id 为 surface_container 的从 RelativeLayout 换成 FrameLayout 就好了

**Comment by zhangyujiu** [comment]
搞定了，非常感谢。但是为什么RelativeLayout会导致此问题呢

**Comment by CarGuo** [comment]
因为你这个视频是 270 度的旋转属性，导致渲染布局在布局的时候，需要 Rotate ，然后旋转导致重新布局计算大小的时候 RelativeLayout 的最终返回大小计算不对。

**Comment by LibertyJiang** [comment]
"然后将 id 为 surface_container 的从 RelativeLayout 换成 FrameLayout 就好了" 这个怎么处理呢？

**Comment by CarGuo** [comment]
@LibertyJiang  继承，Override getLayoutId 方法
