### ISSUE TITLE
在使用seekto方法中，非常的慢，大约要5秒左右！！！！

### ISSUE THREAD

**Issue by liguangze** [CarGuo/GSYVideoPlayer#2525]
播放音频，我们有一个记录播放的功能，就是上次退出会记录播放的功能，下次进来直接在这个位置播放，
我是在onPrepared的回调中。调用seekTo的方法，现在特别慢，要有5秒的延时，是我调用的地方不对吗，还是怎么，有什么优化的办法吗

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class); 试试

**Comment by liguangze** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class); 设置后就报错呢，走了错误的回调。onPlayError里面怎么打印错误信息呢，字段是什么 URL是有的

**Comment by CarGuo** [comment]
有测试 URL 吗？

**Comment by liguangze** [comment]
我感觉根URL没有关系，这个是出错的URL
https://ncdn.wfkids.net/sv/322fb42a-16c6b12ff88/322fb42a-16c6b12ff88.mp3

我的版本是6.0.0-beta 根这个有关系吗
我想升级到最新的，总是有错，我是从别人手机接到项目，所以就没有改

**Comment by liguangze** [comment]
ExoSourceManager.setSkipSSLChain(true);这个方法没有呢

  implementation 'com.shuyu:gsyVideoPlayer-java:6.0.0-beta'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.0-beta'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.0-beta'

依赖的这三个

也必须要升级到最新的吗，

**Comment by CarGuo** [comment]
是的，这个是新增加的方法，旧版本需要自己实现 ssl 忽略

**Comment by liguangze** [comment]
好的，感谢开源，我试试PlayerFactory.setPlayManager(Exo2PlayerManager.class)这个好使不

**Comment by CarGuo** [comment]
我试了换到 Exo2PlayerManager 后 seek 是可以的了，你有两个选择：

1、把域名的 ssl 证书问题处理下。

2、在客户端做忽略。

以上
