### ISSUE TITLE
播放完成后，能否 停留在最后一帧

### ISSUE THREAD

**Issue by nxnyk** [CarGuo/GSYVideoPlayer#2526]
我现在要做视频的实时预览，能否做到播放完成后不自动释放，黑屏， 停在最后一帧，然后向前seek可以实时预览seek后的帧，大佬请问下怎么操作呢？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1487

https://github.com/CarGuo/GSYVideoPlayer/issues/479


你看源码，还有暂停的时候从 surface 扣图的行为可以参考

**Comment by nxnyk** [comment]
> #1487
> 
> #479
> 
> 你看源码，还有暂停的时候从 surface 扣图的行为可以参考

好的，我试试 谢谢大佬
