### ISSUE TITLE
gradle依赖下载不到

### ISSUE THREAD

**Issue by PayneJay** [CarGuo/GSYVideoPlayer#2527]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

ERROR: Unable to resolve dependency for ':app@anbanDebug/compileClasspath': Could not download GSYVideoPlayer.aar (com.shuyu:GSYVideoPlayer:6.0.1)

## 问题机型/系统：

例如 真机 Nexus6P Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

添加gradle依赖后，build工程失败，提示：ERROR: Unable to resolve dependency for ':app@anbanDebug/compileClasspath': Could not download GSYVideoPlayer.aar (com.shuyu:GSYVideoPlayer:6.0.1)

**Comment by PayneJay** [comment]
不知道大家有没有遇到过这种情况啊

**Comment by CarGuo** [comment]
https://bintray.com/carguo/GSYVideoPlayer/gsyVideoPlayer/6.0.1  没有问题
