### ISSUE TITLE
暂停之后，有什么方法可以同时禁止缓冲吗

### ISSUE THREAD

**Issue by moujunqiang** [CarGuo/GSYVideoPlayer#2528]
## 问题描述：

暂停之后视频还在继续缓存继续消耗流量，有什么方法可以暂停缓存吗
## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
缓冲暂停目前没有这个

**Comment by moujunqiang** [comment]
那可以禁止缓冲吗

**Comment by moujunqiang** [comment]
我这边有个功能是做的投屏，投屏到电视，手机上视频时暂停播放的，但是还在后台消耗流量进行缓冲，

**Comment by CarGuo** [comment]
禁止缓冲那视频怎么播放，帧解析不是顺序的

**Comment by moujunqiang** [comment]
如果我想实现上面说的功能，投屏的时候视频暂停 不消耗流量，这个目前还实现不了是吗

**Comment by CarGuo** [comment]
你可以把缓冲设置小一些，这样缓冲就不会占用太多流量

**Comment by moujunqiang** [comment]
好的 我试一下 谢谢
