### ISSUE TITLE
页面退出后还继续播放声音

### ISSUE THREAD

**Issue by wangpingtaohn** [CarGuo/GSYVideoPlayer#2529]
## 问题描述：

在Activity1播放了当前视频，然后跳转到Activity2后，从Activity2返回后，在Activity1里执行跳转到Activity3，然后执行Activity1的finish方法并且在onDestroy()方法里执行了MyGSYVideoManager.releaseAllVideos()，发现页面已退出，但是声音还在继续播放。

## 问题机型/系统：
跟机型没有关系，测了好几款都一样。

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
在demo里测试正常

**Comment by wangpingtaohn** [comment]
感觉调用MyGSYVideoManager.releaseAllVideos()不起作用，后台又重新播放了一遍。

**Comment by CarGuo** [comment]
首先你这个manager 是不是被应用到你的 player  

或者你可以直接调用plaer 的释放看看

**Comment by wangpingtaohn** [comment]
【或者你可以直接调用plaer 的释放看看】怎么调用？

**Comment by CarGuo** [comment]
你看 DetailPlayer

**Comment by jiukedao** [comment]
我也出现了这种情况，但不是播放器的问题。

    我的情况是这样的：有的时候网络不好，用户退出页面时，后台仍在执行查询播放地址的网络请求，等到用户回退到上一个页面，后台的网络请求才回调了播放相关的代码，就会造成页面退出还继续播放声音的情况。

**Comment by Lucklyheart** [comment]
因为onDestroy方法执行会有不同时间的延迟，所以不建议在onDestroy里做回收操作，所以可以将回收的相关操作放在onFInish里面。
