### ISSUE TITLE
拖动进度条时底部时间轴不会跟随变化

### ISSUE THREAD

**Issue by equationl** [CarGuo/GSYVideoPlayer#2530]
## 问题描述：

拖动底部进度条时，进度条的时间不会跟随变化。
见图：
![QQ图片20200116200921](https://user-images.githubusercontent.com/6501123/72524113-2d0b7280-389c-11ea-9867-a9e83073f582.gif)
拖动进度条时红圈所示时间不会变化
![image](https://user-images.githubusercontent.com/6501123/72524150-41e80600-389c-11ea-8997-60d1ead69632.png)

## 问题机型/系统：

真机 三星S10 Android10.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

## Demo中的复现步骤

demo中任意一个播放页面打开均可复现。

不知道这个是不是库的特性？还是希望能够实时更新时间比较直观一点。
另外，简介中所说的进度条小窗口实时预览功能怎么使用？我搜索以前的issue发现作者说是在demo中的PreViewGSYVideoPlayer里，但是我在新版并没有发现这个，是否在新版删除了这个功能？

**Comment by CarGuo** [comment]
这个是没有的，只有手在屏幕上滑动那种才有

**Comment by CarGuo** [comment]
后续可以考虑加上
