### ISSUE TITLE
全屏与正常小屏参数传递

### ISSUE THREAD

**Issue by 748297973** [CarGuo/GSYVideoPlayer#2532]
在全屏的时候选择倍速2.0或者屏幕比例4:3吧，切换小屏倍速/比例不再生效，在切换全屏也不生效，点击项的选择文字也恢复到了初始状态，用克隆参数貌似不行，不知道用对了吗

**Comment by CarGuo** [comment]
选择倍速我在demo 中测试正常啊，比例4:3的设置也是全局的啊·······


你需要看 cloneParams 、startWindowFullscreen、resolveNormalVideoShow 这三个方法

**Comment by 748297973** [comment]
倍速设置可以了，但是在全屏下比如点击了2.0x，倍速显示2.0x，再切换回小屏（小屏的倍速显示被隐藏了），再切换全屏，倍速的地方不是显示2.0x，变成了默认值

**Comment by CarGuo** [comment]
这个需要你同步设置，你看另外那两个方法在标准播放器中的做法。
