### ISSUE TITLE
播放mkv格式视频  有画面无声音

### ISSUE THREAD

**Issue by WangkeqiangS** [CarGuo/GSYVideoPlayer#2536]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题机型/系统：

真机 华为meta 20 Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

在demo也是一样的  替换位avi格式的so 播放mkv

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
