### ISSUE TITLE
请问setVideoAllCallBack 下的 onPlayError 回调时间能设置吗？

### ISSUE THREAD

**Issue by zhangnin** [CarGuo/GSYVideoPlayer#2539]
## 问题描述：

请问setVideoAllCallBack 下的 onPlayError 回调时间能设置吗？

我这样设置是无效的：GSYVideoManager.instance().setTimeOut(5000, false)

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不是很理解需求啊····

**Comment by zhangnin** [comment]
拉流失败，这个onPlayError 回调的时间太长了，能设置短点吗？

**Comment by zhangnin** [comment]
> 不是很理解需求啊····

就是说这个流我拉了3s还不能回来，就直接回调onPlayError ，而不用等十几秒才回调onPlayError 这个方法。

**Comment by CarGuo** [comment]
setTimeOut 需要在播放前设置的，如下图所示

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/10770362/73828216-d14d5d00-483b-11ea-9545-8a41a08a8dbb.png">

**Comment by zhangnin** [comment]
我直接改源码，把里面的8s改成3s，不生效

**Comment by CarGuo** [comment]
测试正常
