### ISSUE TITLE
在Fragment下，点击全屏按钮，全屏不了，在点击全屏按钮才可以，怎么才能在fragment下全屏。

### ISSUE THREAD

**Issue by Jacky-Xu** [CarGuo/GSYVideoPlayer#254]
![qq 20170601170907](https://cloud.githubusercontent.com/assets/10206252/26672821/368935f2-46ed-11e7-84b2-a1b987076b98.png)
``

 playVideo.getFullscreenButton().setOnClickListener( v ->{
            //直接横屏
            //外部辅助的旋转，帮助全屏
            orientationUtils = new OrientationUtils(getActivity(), playVideo);
            //初始化不打开外部的旋转
            orientationUtils.setEnable(true);

            orientationUtils.resolveByClick();
            //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
            playVideo.startWindowFullscreen(getActivity(), true, true);
        } );

**Comment by CarGuo** [comment]
是否配置了manifest？

**Comment by Jacky-Xu** [comment]
@CarGuo  是要配置MainActivity的默认水平方向吗？

**Comment by loveRose** [comment]
android:configChanges="orientation|screenSize|smallestScreenSize|keyboard|keyboardHidden|navigation"

**Comment by loveRose** [comment]
别且Activity中要实现该方法
@Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
}

一定要记得 super.onConfigurationChanged()不能去掉了  不然系统会无法找到配置文件中的要求对应的方法

**Comment by Jacky-Xu** [comment]
@loveRose  thanks , 已经解决了。非常感谢你的帮助。
