### ISSUE TITLE
希望添加一个自动切换解码的功能

### ISSUE THREAD

**Issue by mSoftDeveloper** [CarGuo/GSYVideoPlayer#2540]
## 问题描述：

希望大神添加一个自动切换解码的功能
ijk有软硬解码方式，一般为了性能和流畅都会使用硬解，但是硬解有局限性，有些视频超出了硬解解码的范围就需要软解来解决，虽然软解有性能问题，但是为了满足需求也会不得以而为之，所以希望大神可以做一个自切换软硬解码功能（硬解失败的时候自动切换为软解播放），大神的框架封装的太好，实在是不敢妄动，还希望大神可以帮忙实现以下，大神辛苦了（膜拜~~~）

**Comment by CarGuo** [comment]
这是暂时支持不了，毕竟失败的原因很多，而且判断的逻辑比较麻烦，需要播放过程中动态切换内核的工作量，不如播放前服务端返回格式去选择播放
