### ISSUE TITLE
repeat continuous play video

### ISSUE THREAD

**Issue by hermaini** [CarGuo/GSYVideoPlayer#2541]
hello, i'm already create continuous play video, with 3 videos, it's possible to repeat from the first videos after last videos already finished ..??

thanks for the answer

**Comment by CarGuo** [comment]
You can manually adjust the playback position in the code to realize the cyclic play of the list

**Comment by hermaini** [comment]
can you explain the example please ..?

**Comment by hermaini** [comment]
this is my code : 

`videoView            = findViewById(R.id.videoView);
        initVideo();
        videoView.getTitleTextView().setVisibility(View.GONE);
        videoView.getBackButton().setVisibility(View.GONE);
        videoView.getFullscreenButton().setVisibility(View.GONE);
        videoView.setVideoAllCallBack(this);
        videoView.setIsTouchWiget(true);
        videoView.setRotateViewAuto(false);
        videoView.setLockLand(false);
        videoView.setAutoFullWithSize(true);
        videoView.setShowFullAnimation(false);
List<Video> videos = (List<Video>) result;
                    List<GSYVideoModel> urls = new ArrayList<>();
                    for(int i=0; i< videos.size(); i++){
                        urls.add(new GSYVideoModel(videos.get(i).getUrl(), videos.get(i).getType()));
                    }
                    videoView.setUp(urls, true, 0);
                    videoView.startPlayLogic();`

**Comment by hermaini** [comment]
i don't know how to check if last video already finished, so i can repeat play again from first video
