### ISSUE TITLE
竖屏视频全屏的问题

### ISSUE THREAD

**Issue by androidCoderxiao** [CarGuo/GSYVideoPlayer#2542]
## 问题描述：

setAutoFullWithSize 设置了false 但是竖屏的视频点击全屏 还是竖屏播放的  没有横屏，有办法点了全屏按钮后 让所以视频都强制横屏吗？  感谢 

## 问题机型/系统：
 真机

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
demo 里不是可以吗？？？

**Comment by androidCoderxiao** [comment]
> demo 里不是可以吗？？？
DEMO 里面没试过  配置都是和DEMO 代码一致的

**Comment by CarGuo** [comment]
我测试了 demo 没发现问题，你可以下载 demo 看看

**Comment by CarGuo** [comment]
我测试了 demo 没发现问题，你可以下载 demo 看看

**Comment by androidCoderxiao** [comment]
> 我测试了 demo 没发现问题，你可以下载 demo 看看

找到问题了 是我代码有问题  ，感谢耐心回复 谢谢  ！！
