### ISSUE TITLE
音视频不同步

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#2545]
## 问题描述：

1.音视频不同步，音频正常播放，视频播放延迟变慢

2.视频播放进度显示时间大于视频真实时长(见下图，视频总时长18s，播放进度大于了18s)。

![image](https://user-images.githubusercontent.com/13781886/74126036-e1858380-4c11-11ea-88a7-cfde3a623c12.png)

## 问题机型/系统：

例如: mumu模拟器

## GSY依赖版本

例如： `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

Demo中的SimplePlayer页面替换链接 `https://resource.ghzs.com/video/game/5da575bbfcc3af003411aee6.mp4` 可复现

**Comment by CarGuo** [comment]
请看问题集锦和  https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q   另外还可以切换到exo内核
