### ISSUE TITLE
setProgressAndTime这个方法没有执行

### ISSUE THREAD

**Issue by 12345nbaa** [CarGuo/GSYVideoPlayer#2546]
## 问题描述：
1.setProgressAndTime这个方法没有执行，导致进度条只能拖，可能的原因是什么？谢谢
override fun setProgressAndTime(
        progress: Int,
        secProgress: Int,
        currentTime: Int,
        totalTime: Int
    ) {
        super.setProgressAndTime(progress, secProgress, currentTime, totalTime)
        if (progress != 0) {
            mProgressBar.progress = progress
        }
    }

## GSY依赖版本
例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'`

**Comment by CarGuo** [comment]
demo测试正常

**Comment by 12345nbaa** [comment]
有可能是什么原因导致的？排查对比了之前的也都不行

**Comment by CarGuo** [comment]
需要你在demo复现，我好排查问题

**Comment by 12345nbaa** [comment]
找到原因了，组件化开发中一个app用了7.1.2版本的我用的7.1.1版本，恰好setProgressAndTime的参数个数修改了，导致低版本的找不到这个方法。所以没有实时进度。
解决方法：下沉库，统一使用一个版本就好了。

**Comment by 12345nbaa** [comment]
ps：进度条，设置android:layout_width="match_parent",左右两侧也有间距，这个间距能去掉吗？谢谢

**Comment by 12345nbaa** [comment]
ps：进度条，设置android:layout_width="match_parent",左右两侧也有间距，这个间距能去掉吗？让进度条与视频同宽。谢谢

**Comment by alanzyz** [comment]
setProgressAndTime 方法不走，也遇到，很无解。看了你的好像并没有发现思路
