### ISSUE TITLE
在切换到全屏后，原先的自定义控件不见了，如何显示出来

### ISSUE THREAD

**Issue by QYC5535** [CarGuo/GSYVideoPlayer#2547]
问题描述：

首先很感谢作者开源，首次使用，花了一些时间查看源码和Issues。我继承StandardGSYVideoPlayer类，没重写getLayoutId()方法，继续使用原有的布局。但是在切换到全屏的时候，原有的自定义View没能显示出来，我尝试调整自定义View层级和动态添加自定义View都没能显示，请问我要如何才能显示自定义View。

问题机型/系统：

华为P30 Android10.0

GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer:7.1.2'

Demo中的复现步骤

我再Demo的SimpleDetailActivityMode2类对应的布局XML文件中添加了一个TextView，在切换到全屏的时候我想把这个TextView也显示出来。

问题代码：(如果有)

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/activity_detail_player"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.core.widget.NestedScrollView
        android:id="@+id/post_detail_nested_scroll"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fillViewport="true">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <View
                android:layout_width="match_parent"
                android:layout_height="@dimen/post_media_height" />

            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="@string/detail_text"
                android:textSize="16sp" />

        </LinearLayout>

    </androidx.core.widget.NestedScrollView>

    <com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
        android:id="@+id/detail_player"
        android:layout_width="match_parent"
        android:layout_height="@dimen/post_media_height" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="我想在全屏的时候继续显示"
        android:textColor="@android:color/white"
        android:background="@android:color/holo_red_dark"
        android:textSize="24dp"
        android:layout_centerInParent="true"/>

</RelativeLayout>

## 问题log（如果有）

无

**Comment by duzihao2424** [comment]
遇到同样的问题。横屏了之后，重置了布局。

**Comment by CarGuo** [comment]
看源码，有对应的clone和设置处理

**Comment by QYC5535** [comment]
补充一下我的解决方案，最终还是采用了LandLayoutVideo的横竖屏对应不同的布局文件，横屏的时候把自定义控件放到LandLayoutVideo的布局文件中进行显示。
