### ISSUE TITLE
viewpager + fragment 内存溢出

### ISSUE THREAD

**Issue by 799536960** [CarGuo/GSYVideoPlayer#2548]
使用场景：使用ViewPager播放视频列表，当ViewPager切换页面时候播放当前页面视频。
操作方法：快速滑动ViewPager，会越滑越卡顿，直至OutOfMemoryError。

我看一个issues和我一样的问题 
你的回复是单独维护一个播放器 
可是播放器内核不是只有一个嘛

**Comment by 799536960** [comment]
![LYCQ3FCJ%ZH~B@81 K()QMD](https://user-images.githubusercontent.com/12708719/74247900-bee29000-4d21-11ea-9d04-4e938295ccc6.png)

**Comment by 799536960** [comment]
上面我是把播放器 放在activity 然后滑到当前fragment 自己把播放器添加到fragment播放容器中
 可是没有解决问题

**Comment by CarGuo** [comment]
这个不属于项目问题，怎么可能一个页面就开一个播放内核…
这类问题一般都是几个内核循环使用和提前缓存。
平常使用 ViewPager或者RecyclerView 都知道复用和回首呀

**Comment by 799536960** [comment]
我的意思是  我看文档说的是 默认就是一个内核的  我继承的StandardGSYVideoPlayer 为什么每个fragment 还会开一个内核呢

**Comment by 799536960** [comment]
@CarGuo 能否解答下 谢谢了

**Comment by 799536960** [comment]
不好意思 我终于找到原因了 是哪个竖直viewpager内存溢出的 啊啊啊

**Comment by wangpingtaohn** [comment]
> 不好意思 我终于找到原因了 是哪个竖直viewpager内存溢出的 啊啊啊

请教下，怎么解决了？
