### ISSUE TITLE
GSYExo播放-初始指定集数无效，下一集进度条不重置

### ISSUE THREAD

**Issue by yokeqi** [CarGuo/GSYVideoPlayer#2550]
## 问题描述：

1. 想要实现初始播放第N集，调用GSYExo2PlayerView的setup(List<GSYVideoModel> url, int position)，指定position无效
2. 下一集调用GSYExoVideoManager.instance().next()，进度条未重置，Demo也是一样

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.2'

## Demo中的复现步骤

2. Demo中的自定义Exo页面打开后快进一段位置，点击下一集会出现这个问题。

## 问题代码

1. IjkExo2MediaPlayer.prepareAsyncInternal中，初始化ExoPlayer只传递了数据源，没有看到seekto，我用土办法在player和mgr中加了play(int windowIndex)方法来跳转指定集数，然后在View的onPrepared方法中调用GSYExoVideoManager.instance().play(mPlayPosition);实现第几集播放
2. 我除了调用next再调用View的resetProgressAndTime方法解决;

**Comment by yokeqi** [comment]
第二个问题，参考GSYVideoPlayer.playnext()处理解决
`@Override
public void onAutoCompletion() {
    if (playNext())
        return;
    super.onAutoCompletion();
}

public boolean playNext() {
    if (mPlayPosition >= (mUriList.size() - 1))
        return false;

    mPlayPosition++;
    mSaveChangeViewTIme = 0;
    GSYExoVideoManager.instance().next();
    resetProgressAndTime();
    updateControlState();
    return true;
}`

**Comment by CarGuo** [comment]
已经简单化修复该问题
