### ISSUE TITLE
点击进度条出现进度条时刻倒退

### ISSUE THREAD

**Issue by Kbaseczy** [CarGuo/GSYVideoPlayer#2552]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在进度条上选择某点进行跳跃，会自动跳到选择点前一段。总是会往后退一段播放。！

## 问题机型/系统：

例如 真机 一加5 android10

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请看问题集锦
