### ISSUE TITLE
exo内核出现花屏

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#2554]
## 问题描述：

exo内核在模拟器中播放视频出现花屏，设置`GSYVideoType.SUFRACE`和`开启硬件加速`都无效，麻烦大佬看一下，谢谢

![device-2020-02-18-140149](https://user-images.githubusercontent.com/13781886/74708484-8843d280-5257-11ea-9644-e3866238f7b9.png)

## 问题机型/系统：

例如 mumu模拟器

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

Demo中的DetailExoListPlayer页面更换`https://resource.ghzs.com/video/game/5e1dad407169d915352e93d3.mp4`链接会出现

**Comment by CarGuo** [comment]
模拟器的不做适配，exo内核本来就是用的 MediaCodec 的了。

**Comment by zhangyujiu** [comment]
那是什么原因造成的呢？只是部分视频会有这种问题

**Comment by CarGuo** [comment]
硬件解码和视频的兼容问题，比如帧率码率编码方式等等
