### ISSUE TITLE
详情页播放，先暂停视频，横竖屏切换时，视频会自动开始播放，应该不会自动播放才对

### ISSUE THREAD

**Issue by ForgetSky** [CarGuo/GSYVideoPlayer#2559]
## 问题描述：

详情页播放，先暂停视频，横竖屏切换时，视频会自动开始播放，应该不会自动播放才对；使用的系统模式

## 问题机型/系统：

例如 真机 华为mate20 Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后， 先暂停视频，横竖屏切换时，视频会自动开始播放

问题代码：(如果有)
无

## 问题log（如果有）

无

**Comment by CarGuo** [comment]
我这边测试  Demo 的  detailPlayer 正常啊

**Comment by ForgetSky** [comment]
PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式， 是这种模式吗

**Comment by CarGuo** [comment]
哦，系统模式这个确实是已知问题。
