### ISSUE TITLE
你好，怎么把我自己编译的so文件加到你的这个项目呢

### ISSUE THREAD

**Issue by gypnick** [CarGuo/GSYVideoPlayer#256]
我按着ijkplayer官方的方法重新编译生成ijkplayer的工程以后可以播放avi格式的，然后把.so文件复制替换到你的工程里面，好像并不能播放avi格式的，是哪里没弄对吗

**Comment by gypnick** [comment]
我按着ijkplayer官方的方法重新编译生成ijkplayer的工程以后可以播放avi格式的，然后把.so文件复制替换到你的工程里面，好像并不能播放avi格式的，是哪里没弄对吗

**Comment by CarGuo** [comment]
需要替换所有的so，然后确保你的so版本和ijkjava版本一致，现在的GSY是ijk的0.8.0

**Comment by gypnick** [comment]
以前是直接覆盖的so文件好像不行，我删了在重新加入就可以了，还有一个新的问题：你的so库不支持avi格式的文件，用你的so库播放avi后这个avi文件好像就被删除了，这是怎么回事啊

**Comment by CarGuo** [comment]
新版本已修正

**Comment by duhang324** [comment]
在哪里替换so呢

**Comment by CarGuo** [comment]
你把so放到自己的so目录里，不依赖远程so就可以了

**Comment by sxf141** [comment]
https://github.com/gypnick

**Comment by sxf141** [comment]
https://github.com/gypnick 
你好，你编译好的so能否发我一份，一直编码不过

**Comment by wang869755676** [comment]
@gypnick 能否提供一份编译好的so文件（15738755077@163.com） ，还有一下，如果要是自己编译支持更多的格式。是否直接使用
cd config
rm module.sh
ln -s module-default.sh module.sh 这个命令就可以了，还是要修改module.sh
