### ISSUE TITLE
编译需要ndk

### ISSUE THREAD

**Issue by yedajiang44** [CarGuo/GSYVideoPlayer#2561]
as版本：4.0
仅仅是添加远程引用`implementation 'com.shuyu:GSYVideoPlayer:7.1.2'`
但是项目编译出错（非ndk项目）
`No version of NDK matched the requested version 21.0.5935234`
即便是我项目用到了ndk，然而我在sdk管理器里并没找到这个版本的sdk

**Comment by CarGuo** [comment]
不需要，so都是编译好的了
