### ISSUE TITLE
视频播放完毕，进行截图，是个黑色图片

### ISSUE THREAD

**Issue by Freedomhxb** [CarGuo/GSYVideoPlayer#2563]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机  荣耀20s

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

Demo中打开 带控制DEMO 然后等视频播放完毕，点击截图，提示成功，但是是一个黑色的图片。图片不正确。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
正常情况，看源码你就知道为什么
