### ISSUE TITLE
exoplayer模式 播放直播流 获取时长不为0

### ISSUE THREAD

**Issue by kyriej** [CarGuo/GSYVideoPlayer#2565]
exoplayer模式 播放直播流 获取时长不为0，大于0，正常是返回0,试过好几个直播流获取时长都大于0

**Comment by CarGuo** [comment]
请提供测试 url

**Comment by CarGuo** [comment]
请提供测试 url

**Comment by kyriej** [comment]
http://39.130.206.132:6410/gitv_live/ZJWS-HD/ZJWS-HD.m3u8

**Comment by CarGuo** [comment]
如下图所示，如果你说的是起始时间的话，重载下 setProgressAndTime 方法就可以了

![image](https://user-images.githubusercontent.com/10770362/75943623-78bbbf00-5ed0-11ea-9e97-334613a1ab19.png)

**Comment by kyriej** [comment]
大佬这个是Exo模式吗，ijk跟系统播放器 获取总时长为0是正确的，exo 却能获取到时长那个，直播流是没有时长才对，不是说的起始时间

**Comment by CarGuo** [comment]
exo 解析出来的这个没办法，你可以继承后重载 setProgressAndTime 解决

**Comment by kyriej** [comment]
好的，谢谢大佬
