### ISSUE TITLE
播放暂停切换到其他app看视频再回来导致异常

### ISSUE THREAD

**Issue by 627219641** [CarGuo/GSYVideoPlayer#2567]
## 问题描述：

播放视频途中，切换到浏览器（或者其他app），点开其中的视频播放，再回来，会导致视频播放终止，底部左边时间显示正常，右边总时长显示00：00，进度条跳到最后。

## 问题机型/系统：

所有机型

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

**Comment by CarGuo** [comment]
请测试最新 demo ，其他视频播放默认情况下会直接释放播放器，如果需要自定义，参考 onLossAudio、onGankAudio、onLossTransientAudio等方法重载
