### ISSUE TITLE
你好，播放视频速度比正常慢，本来6秒的视频播放了28秒

### ISSUE THREAD

**Issue by guluwa** [CarGuo/GSYVideoPlayer#257]
视频链接：http://resources.oursvideo.com/1496656098309391001.mp4

**Comment by CarGuo** [comment]
没发现啊，demo中播放正常

**Comment by guluwa** [comment]
用苹果手机拍的视频然后转成MP4格式，播放会出现这样的情况，安卓手机拍的视频没有问题。

**Comment by CarGuo** [comment]
demo么？哪个Activity？真机？哪个版本？
