### ISSUE TITLE
屏幕旋转问题，OrientationUtils 工具类

### ISSUE THREAD

**Issue by Alexxiaopang** [CarGuo/GSYVideoPlayer#2570]
## 问题描述：

使用OrientationUtils 这个帮助类，旋转非常灵敏，手机才倾斜一点点就立马横屏了，体验非常不好

能否开放init（）方法让我们自定义旋转参数，或者提供设置检测角度的方法

## 问题机型/系统：

 真机 红米8 Android9.0   华为荣耀等

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

Demo中的能旋转的activity都能复现该问题。

**Comment by CarGuo** [comment]
已经提交，下个版本发布，你可以现在 demo 测试看看

**Comment by Alexxiaopang** [comment]
好的，期待下个版本的提交
