### ISSUE TITLE
RecyclerView 中 切换横竖屏 布局问题 

### ISSUE THREAD

**Issue by androidCoderxiao** [CarGuo/GSYVideoPlayer#2572]
## 问题描述：
你好我现在的 需求场景是这样的 ，有点像抖音的效果，横竖屏的时候都是可以上下滑动来切换视屏的 ，所以我用了 RecyclerView  来实现 ，item 的布局就是一个播放器 ，点击全屏时候 只是旋转了屏幕方向 。
点击旋转的代码 
//设置全屏按键功能
            gsyVideoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    //直接横屏
                    orientationUtils.resolveByClick();
                }
            });
目前的问题是我想旋转了之后加载另外一套布局 ，并且当前的播放状态也能同步， 不知道是否有什么好办法 能实现呢 ？谢谢了

**Comment by CarGuo** [comment]
只是旋转方向，这个你可以参考 demo 中的 LandLayoutVideo ，通过自己改变 mIfCurrentIsFullscreen 去处理
