### ISSUE TITLE
你好，横屏时候怎么控制控件如进度条，时间手动代码隐藏？

### ISSUE THREAD

**Issue by 951AB159BA** [CarGuo/GSYVideoPlayer#2579]
你好，横屏时候怎么控制控件如进度条，时间手动代码隐藏？我打了断点看到横屏时候startWindowFullscreen函数，,又重新new了一个GSYVideoView。原来的view和里面的子控件Id都变了。

**Comment by CarGuo** [comment]
player.getCurrentPlayer()

**Comment by 951AB159BA** [comment]
> getCurrentPlayer()

谢谢！
