### ISSUE TITLE
你好，是否可以把crypto 默认打开

### ISSUE THREAD

**Issue by coldmn3** [CarGuo/GSYVideoPlayer#258]
项目使用的ijk应该是没有打开 crypto ，如果播放一些加密的m3u8视频，会导致解密失败无法播放。

**Comment by CarGuo** [comment]
有log和url可以提供下么？

**Comment by CarGuo** [comment]
https://github.com/Bilibili/ijkplayer/issues/2348  类似这个？

**Comment by coldmn3** [comment]
是的，把--disable-protocol=crypto 改成enable 替换so后就可以播放了。

**Comment by CarGuo** [comment]
好的，下个版本加上～

**Comment by coldmn3** [comment]
感谢老司机！

**Comment by JinJieGu** [comment]
@CarGuo 请问crypto 开关打开了吗

**Comment by CarGuo** [comment]
打开了
