### ISSUE TITLE
如何直接全屏播放？

### ISSUE THREAD

**Issue by ForgetSky** [CarGuo/GSYVideoPlayer#2581]
## 问题描述：
想实现的效果为 在打开页面的时候直接全屏播放，点击返回键，返回详情页；
使用videoPlayer.startWindowFullscreen()后声音开始播放，画面未播放；
需要再次点击播放按钮后，视频可以播放

## 问题机型/系统：

例如 真机 华为mate30

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

无

问题代码：(如果有)
```
无
```

## 问题log（如果有）

```
无

```

**Comment by CarGuo** [comment]
你直接全屏activity 啊………
