### ISSUE TITLE
如何优雅的停止播放

### ISSUE THREAD

**Issue by alanzyz** [CarGuo/GSYVideoPlayer#2582]
## 问题描述：
代码中要实现，不是会员播放次数达到5，新打开的视频就不能看。但是停止视频后，音频还在。有没有优雅的方式停止播放
     
    public void stopPlayer() {
        mISdlan = true;
        PlayVideoView currentPlayer = (PlayVideoView) getCurrentPlayer();
        currentPlayer.rl_dlan_father.setVisibility(VISIBLE);
        super.onAutoCompletion();
        release();
    }

## 问题机型/系统：

三星s6

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'`

解决方案：使用：
setShowPauseCover 为false，似乎也不错。可以实现声音视频都中断

**Comment by alanzyz** [comment]
帮忙评价一下，解决方案里的方法——setShowPauseCover 为false

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2583

**Comment by alanzyz** [comment]
我们的应用，在带有广告的形式下，此方法不能停止播放。
