### ISSUE TITLE
“已看过”——用户那里的——如何优雅的确认

### ISSUE THREAD

**Issue by alanzyz** [CarGuo/GSYVideoPlayer#2583]
## 问题描述：

项目想实现，当用户看过一定视频长度后，认定为此次为看过。这个功能如何优雅的实现，请作者帮个忙

## 问题机型/系统：

全部机型

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'

尝试的解决方案：
在用户看到视频，切换另外一个视频的时候，拿到当前进度，大约百分之10认定为已经看过。
但是这种解决方案有bug：比如用户快看完了。然后拖动进度条到百分之十一下，然后在看另外一个。
请问有没有播放时长的字段，或者有没有优雅的实现方式上的建议？万分感谢！！

**Comment by alanzyz** [comment]
或者监听他曾经拖动到百分之十以上的时候，视为他看过。也行，监听拖动条的方法是哪个

**Comment by CarGuo** [comment]
onProgressChanged 、onStartTrackingTouch、onStopTrackingTouch 等等方法你可以重载

**Comment by alanzyz** [comment]
嗯嗯，找到了，是的，的在这里处理，我之前是页面发生变化调用，getduration， 结果测试发现了这个bug。用户可以作弊

**Comment by alanzyz** [comment]
今天我在issue里，搜索“进度条”发现了这几个方法。是的，我现在想想怎么利用这个东西。
