### ISSUE TITLE
进度对话框字体颜色

### ISSUE THREAD

**Issue by tongzifang** [CarGuo/GSYVideoPlayer#2584]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题机型/系统：全部机型

例如 真机 小米note2 Android7.0

## GSY依赖版本
    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'

    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.2'

    implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.2'

## Demo中的复现步骤

 

问题代码：(如果有)
```
GSYVideoOptionBuilder. setDialogProgressColor(int highLightColor, int normalColor)

 public void build(StandardGSYVideoPlayer gsyVideoPlayer) {
     ..............

        if (mDialogProgressHighLightColor > 0 && mDialogProgressNormalColor > 0) {
            gsyVideoPlayer.setDialogProgressColor(mDialogProgressHighLightColor, mDialogProgressNormalColor);
        }

        build((GSYBaseVideoPlayer) gsyVideoPlayer);
    }


## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
继承后你就可以为所欲为啦，甚至那可以 getLayoutId 重载
