### ISSUE TITLE
安卓Q本地文件如何加载访问

### ISSUE THREAD

**Issue by tianjiaoshanzai** [CarGuo/GSYVideoPlayer#2586]
## 问题描述：
在模拟器安卓7.0系统，使用file://协议访问外置存储视频没有问题，但是在安卓Q上视频播放总是失败，看log是permission denied，安卓新机制的一些内存访问权限也加了，但是没效果，是否有其他本地视频链接方式

## 问题机型/系统：

真机 小米9 Android10.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by tianjiaoshanzai** [comment]
![image](https://user-images.githubusercontent.com/38492739/76094392-84f16a80-5ffd-11ea-8a80-dd1c6d5266e4.png)

**Comment by CarGuo** [comment]
https://mp.weixin.qq.com/s/GwQwugqe277ndVi4GYolKQ
