### ISSUE TITLE
竖屏 横屏  切换

### ISSUE THREAD

**Issue by chuxiaokeAndroid** [CarGuo/GSYVideoPlayer#2590]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：activity加载继承StandardGSYVideoPlayer类，竖屏时界面上加了一个倍速按钮，按钮触发正常，当全屏横屏的时候，倍速按钮无效。求知这种情况怎么处理

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
你看源码中的  cloneParams \ startWindowFullscreen \ resolveNormalVideoShow 等方法，比如

![image](https://user-images.githubusercontent.com/10770362/76294199-60dba500-62ed-11ea-8dda-52ffc269480d.png)

**Comment by chuxiaokeAndroid** [comment]
我看了您说的这个类，但是我怎么可以拿到我activity  videoPlayer对象，去改变倍速
