### ISSUE TITLE
全局小窗请教（非bug），谢谢

### ISSUE THREAD

**Issue by Alexxiaopang** [CarGuo/GSYVideoPlayer#2591]
## 问题描述：
播放后返回就在App（只在app内部）显示一个全局的小窗，点击回到播放界面，多窗口需要启动浮层弹窗而且桌面也能显示，可以请教一下需要怎么操作么？谢了

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

**Comment by CarGuo** [comment]
不是很理解你的意思

**Comment by Alexxiaopang** [comment]
> 不是很理解你的意思

就是类似虎牙的效果，进入详情播放，返回的时候变成小窗口，点击小窗口又进入详情，但是在其他activity页面不会影响这个窗口，回到桌面窗口暂停并消失

**Comment by Alexxiaopang** [comment]
看了你全局窗口的方法，可以设置拦截，我这边试一下，谢谢
