### ISSUE TITLE
手动设置StartAfterPrepared再点击播放，画面不动

### ISSUE THREAD

**Issue by moujunqiang** [CarGuo/GSYVideoPlayer#2595]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

手动设置StartAfterPrepared（false）再点击播放按钮，有声音但是画面不动

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:3'`

问题代码：(如果有)

## 问题log（如果有）

 /**
     * 播放下一集
     *
     * @return true表示还有下一集
     */
    public boolean playNext() {
        if (mPlayPosition < (mUriList.size() - 1)) {
            mPlayPosition += 1;
            GSYVideoModel gsyVideoModel = mUriList.get(mPlayPosition);
            mSaveChangeViewTIme = 0;
            setUp(mUriList, mCache, mPlayPosition, null, mMapHeadData, false);
            if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) {
                mTitleTextView.setText(gsyVideoModel.getTitle());
            }
            setStartAfterPrepared(false);
            startPlayLogic();
            return true;
        }
        return false;
    }xxxxxxx

```

**Comment by moujunqiang** [comment]
demo中 广告1 点击跳过会是这个样子

**Comment by CarGuo** [comment]
demo 测试正常
