### ISSUE TITLE
播放视频过程中会进入onPlayError的回调  但是看不到具体的原因 想知道造成的因素是什么？

### ISSUE THREAD

**Issue by ljchengx** [CarGuo/GSYVideoPlayer#2596]
## 问题描述：

播放视频过程中会进入onPlayError的回调  但是看不到具体的原因 想知道造成的因素是什么？

## 问题机型/系统：

Device Manufacturer: HUAWEI
Device Model       : HUAWEI M2-801W

## GSY依赖版本

"com.shuyu:GSYVideoPlayer:6.0.2"

## Demo中的复现步骤

正常播放过程中

问题代码：(如果有)
```
        @Override
        public void onPlayError(String url, Object... objects) {
            super.onPlayError(url, objects);
            KLog.e(objects);
            LogUtils.iTag("onPlayError = ",objects);
        }
```

## 问题log（如果有）

```
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

11:46:53.026 I/onPlayError =  [main, onPlayError(VideoFragment.java:293)]: args[0] = 对刀操作2
args[1] = com.ykt.resourcecenter.utils.video.SampleCoverVideo{30e1706 V.E...... ......ID 0,0-1920,1200 #7f090234 app:id/full_id}

```

**Comment by CarGuo** [comment]
很多中原因，比如网络断开了，流中断了，数据异常了等等都会造成 tcp 断开。

**Comment by ljchengx** [comment]
> 很多中原因，比如网络断开了，流中断了，数据异常了等等都会造成 tcp 断开。

您好，现在发现一个新问题，我这边有一个视频是mp4格式的，是一个录制工具录制的视频，直接播放源文件的时候是无法进行拖动的，我咨询了他们录制的方式，他们的方式大概意思是如果录制界面不动，就只录制音频，大概是这么个意思，我使用当前版本播放文件时就会出现无法拖动，每次拖动都会回到最开始重新播放。

**Comment by chailijun** [comment]
碰到类似的情况，求解？？？

**Comment by chailijun** [comment]
希望能把错误通过异常抛出来，这样方便查问题
