### ISSUE TITLE
关于触摸反馈的问题

### ISSUE THREAD

**Issue by sans9212** [CarGuo/GSYVideoPlayer#2598]
触摸控制，感受效果不太好，不能自定义。
触摸开始不太灵敏，触控完成以后进度比较大。

**Comment by CarGuo** [comment]
我理解没错的话，应该内置了 mSeekRatio 可支持自定义，甚至你可以重载 touchSurfaceMove \ touchSurfaceMoveFullLogic \ touchSurfaceUp 等方法
