### ISSUE TITLE
关于列表过程中，总有0.1秒有声音的问题

### ISSUE THREAD

**Issue by decide15** [CarGuo/GSYVideoPlayer#2599]
## 问题机型/系统：
 真机华为mate20，红米5

## GSY依赖版本

    api 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    api 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'

问题代码：
StandardGSYVideoPlayer
startPlayLogic()

问题

因为是列表播放，所以滑动过程全程静音播放，偶尔有一瞬间有声音，静音方式是
class MuteIjkPlayerManager : IjkPlayerManager() {
    override fun setNeedMute(needMute: Boolean) {
        mediaPlayer.setVolume(0f,0f)
    }
 
    override fun initVideoPlayer(context: Context?, msg: Message?, optionModelList: MutableList<VideoOptionModel>?, cacheManager: ICacheManager?) {
        super.initVideoPlayer(context, msg, optionModelList, cacheManager)
        mediaPlayer.setVolume(0f,0f)
    }
}
复写了一个MuteIjkPlayerManager ，重写了setNeedMute
PlayerFactory.setPlayManager(MuteIjkPlayerManager::class.java)

上述代码日志运行无问题，主要是刷上几十次，总有一次会有瞬间声音，大概是一个视频播放的前50毫秒会有声音

**Comment by CarGuo** [comment]
可能是每次播放前后存在的时间差

**Comment by CarGuo** [comment]
暂时测试没有发现问题，如果静音出现类似问题可以参考源码调整 `  mediaPlayer.setVolume(0f,0f)` 的位置

**Comment by Sunhee21** [comment]
同样出现了这个问题

**Comment by Sunhee21** [comment]
> 暂时测试没有发现问题，如果静音出现类似问题可以参考源码调整 ` mediaPlayer.setVolume(0f,0f)` 的位置

发现在GSYVideoBaseMnager 579行 释放时把静音取消的代码
