### ISSUE TITLE
什么时候能加上在全屏下虚拟按键被隐藏，滑动调出虚拟按键导致改变进度的bug啊

### ISSUE THREAD

**Issue by qq294685358** [CarGuo/GSYVideoPlayer#26]
什么时候能加上在全屏下虚拟按键被隐藏，滑动调出虚拟按键导致改变进度的bug啊

**Comment by CarGuo** [comment]
有在做对应处理哈，逐步更新中，已经记着的了，改好了通知你~

**Comment by CarGuo** [comment]
update by v1.5.1

**Comment by qq294685358** [comment]
我更新了1.5.1，有个小问题，在滑动调出虚拟按键时，确实不会改变进度了，但是在大概2-3秒后顶部的状态栏隐藏了，虚拟按键却没有隐藏，希望能把这个再优化一下

**Comment by CarGuo** [comment]
并没做有2-3秒的隐藏，手动点击屏幕才会隐藏。

**Comment by qq294685358** [comment]
我觉得还是加上去比较好，市面上主流的播放器都有这个

**Comment by CarGuo** [comment]
update by 1.5.3
