### ISSUE TITLE
为什么播放不了youku视频

### ISSUE THREAD

**Issue by moyaying** [CarGuo/GSYVideoPlayer#260]
视频地址：
http://pl-ali.youku.com/playlist/m3u8?vid=XMjc5NzczMDgzMg%3D%3D&type=flv&ups_client_netip=14.18.236.76&ups_ts=1497000114&utid=slbBEdG%2BMmoCAQ4S7ExAwg8N&ccode=0401&psid=c5305b42cbfa0a8cbf1f1fbe718b9817&ckey=&duration=305&expire=18000&ups_key=0deb27e85b55a83c45993289ef59b648

**Comment by moyaying** [comment]
1.6.4版本可以播放，1.6.6播放不了

**Comment by longzekai** [comment]
高版本的还播放不了？这个是什么情况？

**Comment by moyaying** [comment]
还不清楚，你随便去youku找一个视频地址试试就知道了。

**Comment by CarGuo** [comment]
ijk的log显示是http 403，没有权限。
