### ISSUE TITLE
播放异常

### ISSUE THREAD

**Issue by chuxiaokeAndroid** [CarGuo/GSYVideoPlayer#2600]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：当前视频地址错误了，是否有监听输出。目前只看到onPlayError这个方法，但是这个方法没有说明啥原因出错了。

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by chuxiaokeAndroid** [comment]
有没有方法可以监听具体原因出错的

**Comment by CarGuo** [comment]
只有 onPlayError 告知失败
