### ISSUE TITLE
exo内核循环播放视频没有回调onCompletion方法

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#2606]
## 问题描述：

exo内核，设置循环播放，当播放完毕后没有回调onCompletion方法

![image](https://user-images.githubusercontent.com/13781886/77130536-4cd53780-6a93-11ea-99b0-dafef4cbd2d9.png)

打了断点，上图箭头所指位置没有调用，请问是什么原因导致的呢

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

**Comment by CarGuo** [comment]
循环播放时不会走结束的，循环播放如果走结束播放器就 release 了

**Comment by zhangyujiu** [comment]
好的，谢谢。我用了另外的方法，设置不循环，并在onAutoCompletion回调中设置重新播放就可以实现循环播放了

**Comment by wuyihao1991** [comment]
> 好的，谢谢。我用了另外的方法，设置不循环，并在自动完成上中设置重新播放就可以实现循环播放了

问下你是怎么实现的吗，我也在做循环播放
