### ISSUE TITLE
视频尺寸设定

### ISSUE THREAD

**Issue by Ysrfengnull** [CarGuo/GSYVideoPlayer#2607]
怎么设置视频尺寸，保证视频播放时按照视频尺寸比例播放，没有黑边

**Comment by Ysrfengnull** [comment]
![image](https://user-images.githubusercontent.com/27189624/77130928-b0139980-6a94-11ea-8c74-8d8911ad8152.png)

**Comment by CarGuo** [comment]
GSYVideoType
