### ISSUE TITLE
exoplayer 播放m3u8格式视频 偶尔会出现播放不了的情况

### ISSUE THREAD

**Issue by zhiguo-ren** [CarGuo/GSYVideoPlayer#2609]
问题描述：
使用 exoplayer 内核，播放m3u8格式视频 偶尔会出现播放不了的情况或卡住不动情况；
报错信息：
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:386)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:150)
        at android.os.HandlerThread.run(HandlerThread.java:61)

## 问题机型/系统：
不区分机型；

## GSY依赖版本
 implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2

测试url：
https://video.xintujing.cn/3f3dbb21vodtransgzp1251091601/a6606ed85285890798451409537/v.f230.m3u8   这个是报上面错误到 ，不能播放，但是ijk到可以

https://video.xintujing.cn/d0f2f304vodtranscq1251091601/8bfc7b785285890799841280770/v.f62177.m3u8  这个是会卡在一小时五十七到五十八分之间某个时刻，卡住就不动了。

**Comment by zhiguo-ren** [comment]
还有一个奇怪的问题，这个流  https://video.xintujing.cn/3f3dbb21vodtransgzp1251091601/bf0b31075285890799998505709/v.f61713.m3u8
Android 手机都没声音，过了片头背景音乐后，只有杂音，听不见人的说话声音，但是ios和web端没问题，没报什么错，从表面代码找不到问题原因，有时间帮看看。

**Comment by CarGuo** [comment]
> https://video.xintujing.cn/3f3dbb21vodtransgzp1251091601/a6606ed85285890798451409537/v.f230.m3u8 这个是报上面错误到 ，不能播放，但是ijk到可以

这个我在 demo 测试 exo 模式下正常

> https://video.xintujing.cn/3f3dbb21vodtransgzp1251091601/bf0b31075285890799998505709/v.f61713.m3u8

这个我 seek 了几次测试也没什么问题

> https://video.xintujing.cn/3f3dbb21vodtransgzp1251091601/bf0b31075285890799998505709/v.f61713.m3u8 看了视频是 aac 的音频编码，试了下初步感觉问题是兼容是兼容问题，可能是音频编码时与 Android 的 mediacodec 不兼容
