### ISSUE TITLE
需求要直播视频暂停一会继续播放时按照视频实际时间继续进行播放

### ISSUE THREAD

**Issue by Alexxiaopang** [CarGuo/GSYVideoPlayer#2611]
## 问题描述：
需求要直播视频暂停一会继续播放时按照视频实际时间继续进行播放，而不是暂停的那个时间继续播放。
## GSY依赖版本
implementation 'com.shuyu:GSYVideoPlayer:7.1.2'；
## 具体实现：
使用的是ijk模式，拉流协议是rmtp
已经重写了clickStartIcon（）方法，并实现暂停后调用startPlayLogic，但是只有声音，黑屏
            try {
//                getGSYVideoManager().start();
                startPlayLogic();
            } catch (Exception e) {
                e.printStackTrace();
            }
附上ijk设置：
        List<VideoOptionModel> list = new ArrayList<>();
        VideoOptionModel videoOptionModel;
//        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
//        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max_cached_duration", 3000);
        list.add(videoOptionModel);

        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "stimeout", 30 * 1000);
        list.add(videoOptionModel);

        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "listen_time", 30 * 1000);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect", 1);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

**Comment by CarGuo** [comment]
不是很理解

**Comment by Alexxiaopang** [comment]
使用ijk模式播放直播，如果按了暂停键，后面再按播放键，并没有按照最新的时间进行播放，还是之前暂停的时间
我按照你之前回复别人issues，重写播放按键的方法（clickStartIcon），暂停时候调用startPlayLogic去再次播放，这时候是最新时间的声音，但是视频页面是黑屏的

**Comment by Alexxiaopang** [comment]
> 不是很理解
使用ijk模式播放直播，如果按了暂停键，后面再按播放键，并没有按照最新的时间进行播放，还是之前暂停的时间
我按照你之前回复别人issues，重写播放按键的方法（clickStartIcon），暂停时候调用startPlayLogic去再次播放，这时候是最新时间的声音，但是视频页面是黑屏的

**Comment by CarGuo** [comment]
你可以尝试在 onVideoResume 的时候 seek 一下看看流是否支持。
如果需要  startPlayLogic ，需要先 release 是否 surface 等，黑屏可能就是 surface 未正常设置到 playermanager 中

**Comment by Alexxiaopang** [comment]
onVideoResume  做seek不支持流，直接卡住不播放了，声音也没有，那请问需要怎么操作才能让视屏不黑屏，谢了

**Comment by CarGuo** [comment]
主要在于 surface 没有被正常设置到 playermanager 中，我也不知道该怎么复现你问题

**Comment by Alexxiaopang** [comment]
这个是拉流地址：rtmp://pull01.biliquan.com/live/streamName1974?auth_key=1584953801-0-0-3f8f53974467f0f40e784f6f6ff8a362
你也可以拿项目中的demo复现，demo中是不会跳转到当前时间的，你可以修改一下按钮点击事件，变成startPlayLogic ，这时候就是黑屏有声音
有什么办法可以让播放到当前时间？

**Comment by Alexxiaopang** [comment]
感谢在百忙之中抽空回复我的issues，请问有什么好的办法不？暂时没有思路

**Comment by darcycui** [comment]
我找到一个解决方法：
1.暂停
2.拖动进度条并记录拖动的位置 videoPlayer.seekOnStart = seekBar.progress
3.恢复播放 调用startAfterPrepared（）方法
注意：步骤3不能调用startPlayLogic（）会黑屏

**Comment by Alexxiaopang** [comment]
> 秒

感谢老铁的回复，但是我这个是直播，并没有对应的seekbar，无法感知视频的seekbar的最大值，你这个方法我尝试一下

**Comment by phx1314** [comment]
//            setStateAndUi(CURRENT_STATE_PLAYING);

**Comment by phx1314** [comment]
//            setStateAndUi(CURRENT_STATE_PLAYING);
这样就好了

**Comment by Alexxiaopang** [comment]
> // setStateAndUi(CURRENT_STATE_PLAYING);
> 这样就好了

老铁，这个在哪里用？

**Comment by phx1314** [comment]
try {
//                release();
                startPlayLogic();
//                mCurrentPosition=0;
//                getGSYVideoManager().start();
            } catch (Exception e) {
                e.printStackTrace();
            }
//            setStateAndUi(CURRENT_STATE_PLAYING);

**Comment by phx1314** [comment]
> > // setStateAndUi(CURRENT_STATE_PLAYING);
> > 这样就好了
> 
> 老铁，这个在哪里用？
网络停掉再开的话貌似有点问题

**Comment by Alexxiaopang** [comment]
> > > // setStateAndUi(CURRENT_STATE_PLAYING);
> > > 这样就好了
> > 
> > 
> > 老铁，这个在哪里用？
> > 网络停掉再开的话貌似有点问题

刚刚试了，还是黑屏警告，看来这个问题比较难解决了

**Comment by phx1314** [comment]
> > > > // setStateAndUi(CURRENT_STATE_PLAYING);
> > > > 这样就好了
> > > 
> > > 
> > > 老铁，这个在哪里用？
> > > 网络停掉再开的话貌似有点问题
> 
> 刚刚试了，还是黑屏警告，看来这个问题比较难解决了

那就很奇怪，我这边注销就不黑屏了

**Comment by Alexxiaopang** [comment]
关闭，我在暂停的开始的时候重新设置了videoplayer，能实现到当前帧
