### ISSUE TITLE
全屏时自定义按钮点击事件无效

### ISSUE THREAD

**Issue by zung** [CarGuo/GSYVideoPlayer#2614]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

全屏时发生了这样的问题！

## 问题机型/系统：

例如 真机 Pixel 2 Android10

## GSY依赖版本

 implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后全屏会出现这个问题。

问题代码：(如果有)
```
无
```

## 问题log（如果有）

```

无

```

**Comment by Alexxiaopang** [comment]
可以翻一下issues，可以在 startWindowFullscreen这个方法赋值并绑定，传递view，findid

**Comment by CarGuo** [comment]
getCurrentPlay() 或者参考 cloneParams 和 startWindowFullscreen
