### ISSUE TITLE
大佬，我在做机顶盒视频快进的过程中遇到进度条显示的时候，无法监听到遥控器按键。

### ISSUE THREAD

**Issue by Weisx0904** [CarGuo/GSYVideoPlayer#2615]
大佬，我在做机顶盒视频快进的过程中遇到进度条显示的时候，无法监听到遥控器按键。能不能帮忙解决下

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1302
