### ISSUE TITLE
请问有非androidx版本吗，我们项目比较大，用到很多其他第三方，这样使得播放库跟其他都不兼容

### ISSUE THREAD

**Issue by 951AB159BA** [CarGuo/GSYVideoPlayer#2616]
请问有非androidx版本吗，我们项目比较大，用到很多其他第三方，这样使得播放库跟其他都不兼容，后面是否考虑增加?请问6.x.x版本有跟7.0以上版本一样维护吗？

**Comment by CarGuo** [comment]
6.×的没维护了，基本上只维护有 Androidx 的 ，其实如果你想用非 Androidx 的，可以自己改改，也就是包名不同的全局修改而已
