### ISSUE TITLE
GSYVideoPlayer进度条的问题

### ISSUE THREAD

**Issue by Weisx0904** [CarGuo/GSYVideoPlayer#2620]
大神，请教一个进度条的问题，下载了那个SimplePlay的包，做了一个视频的demo，现在想修改一下进度条，但是找不到进度条的位置（代码）。我想要的功能是，做了快进的方法，但是进度条没有同步（进度条点移动速度比较快），我想让进度条随着我快进的速度移动。

**Comment by CarGuo** [comment]
直接继承，mProgressBar 是 protect 的，还有 touchSurfaceMove、touchSurfaceMoveFullLogic、touchSurfaceUp 等方法

**Comment by Weisx0904** [comment]
我是用在机顶盒上的，用实体按键监听，进度条的点显示的移动速度可调吗

**Comment by CarGuo** [comment]
mProgressBar 对象你拿得到了，你本身就是你的自己设置

**Comment by Weisx0904** [comment]
好的 谢谢 我先试试 不懂再来问你

**Comment by Weisx0904** [comment]
大神 又有一个问题 我在用单击的时候可以用videoPlayer.getCurrentPositionWhenPlaying()获取到当前时间，但是双击的时候也是用这个方法值为0。我做了单击双击的判断(System.currentTimeMillis() - DOUBLE_CLICK_TIME)>600
