### ISSUE TITLE
视频是竖屏就铺满显示  横屏就正常比例显示  求教

### ISSUE THREAD

**Issue by LDJHXM** [CarGuo/GSYVideoPlayer#2621]
请教一下怎么实现类似抖音视频    视频尺寸是竖屏的就铺满显示  视频尺寸是横屏的就宽度铺满高度正常播放~ 现在是如果设置了全屏剪裁或拉伸显示的话 有些视频是横着拍的就会严重拉伸

**Comment by CarGuo** [comment]
GSYVideoType.SCREEN_TYPE_CUSTOM + GSYVideoType.setScreenScaleRatio

**Comment by missu263** [comment]
> GSYVideoType.SCREEN_TYPE_CUSTOM + GSYVideoType.setScreenScaleRatio
> 按照视频分辨率设置你想要的比例，给每个视频设置

GSYVideoType.setShowType 是全局生效的呀。但是实际业务中是，一个纵向的列表，需要横竖铺满，全屏就默认状态下。这个时候需要在每个视频播放前单独进行一次全局设置呀？

**Comment by duanyuanlei** [comment]
@missu263  有解决办法吗？正在寻找setShowType设置后， 如何刷新下页面，在手机测试时候发现如果此时虚拟导航出来挤一下，再放开他似乎就会从新计算， 但是requestLayout,inflate 之类似乎都不好使，  @CarGuo  这个需求还没有办法弄吗？
