### ISSUE TITLE
播放时跳转到另一页面再返回，播放进度会归零

### ISSUE THREAD

**Issue by potterLee** [CarGuo/GSYVideoPlayer#2622]
## 问题描述：

播放时跳转到另一页面再返回，播放进度会归零

## 问题机型/系统：

例如 真机 小米6 Android9.0

## GSY依赖版本

    implementation 'com.shuyu:GSYVideoPlayer:7.1.3'

## Demo中的复现步骤

Demo中的SimpleDetailActivityMode1页面播放时随便跳转到另一页面再返回会出现这个问题。

问题代码：(如果有)

 /**
     * 恢复暂停状态
     *
     * @param seek 是否产生seek动作
     */
    @Override
    public void onVideoResume(boolean seek) {
        mPauseBeforePrepared = false;
        if (mCurrentState == CURRENT_STATE_PAUSE) {
            try {
                if (mCurrentPosition >= 0 && getGSYVideoManager() != null) {
                    if (seek) {
                        getGSYVideoManager().seekTo(mCurrentPosition);
                    }
                    getGSYVideoManager().start();
                    setStateAndUi(CURRENT_STATE_PLAYING);
                    if (mAudioManager != null && !mReleaseWhenLossAudio) {
                        mAudioManager.requestAudioFocus(onAudioFocusChangeListener, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
                    }
                    mCurrentPosition = 0;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

**Comment by 748297973** [comment]
我也是,我的是A activity 再跳转到A activity 再返回,回到上一个A activity后,当前进度会归零,拖动无效,看日志是被释放了调用了onDestroy然后释放了,但是刚开始跳转没释放,返回后又调用了onDestroy,不知道咋整

**Comment by CarGuo** [comment]
测试正常，请提供出现问题的 url
