### ISSUE TITLE
关于7.1.2更新提交的一个问题请教

### ISSUE THREAD

**Issue by NerdAnonymous** [CarGuo/GSYVideoPlayer#2623]
在7.1.2及其以后的版本中
gsyVideoPlayer-exo_player2/src/main/java/tv/danmaku/ijk/media/exo2/IjkExo2MediaPlayer.java 

onVideoSizeChanged()方法中，这个pixelWidthHeightRatio参数是什么意思，宽高比？那为什么还要做width*pixelWidthHeightRatio的操作，为什么不是height*pixelWidthHeightRatio？请大佬教我

**Comment by CarGuo** [comment]
有的视频，需要用这个计算后才是真正的尺寸。

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/77729197-0ce4f600-7039-11ea-9abf-2f6f5ac25b54.png)

ijk 中对应的是

**Comment by NerdAnonymous** [comment]
嗯 我看了计算尺寸的整个流程，我其实想问的是为什么有的视频要用宽和这个widthpixelWidthHeightRatio去相乘才是视频的真正尺寸？跟一般的等比计算好像不太一样

**Comment by CarGuo** [comment]
因为视频除了像素尺寸之外，还有一个比例信息，和内置旋转角度一样

**Comment by NerdAnonymous** [comment]
嗯 看了几遍科普文章 知道咋回事了 谢了
