### ISSUE TITLE
OrientationUtils 持有mActivity ，在Adapter 中有可能导致内存泄漏

### ISSUE THREAD

**Issue by ymwm-lxl** [CarGuo/GSYVideoPlayer#2625]
OrientationUtils 持有mActivity ，在Adapter 中有可能导致内存泄漏 
在列表中放置播放器， OrientationUtils  中持有的mActivity 会导致内存泄漏，建议添加弱引用

**Comment by AttackPangHu** [comment]
這個問題好像一直都有。

**Comment by ymwm-lxl** [comment]
> 这个问题好像一直都有。

已经三个月了，还没有改= =

**Comment by CarGuo** [comment]
没有修改这个计划

**Comment by ymwm-lxl** [comment]
因为这个是视频的控件，内存泄漏导致的内存过高，希望能够尽快解决，在 OrientationUtils 中对调用的 activity 使用**弱引用**应该就可以修复这个问题，希望开发者能够重视

**Comment by CarGuo** [comment]
@ymwm-lxl  已经提交，可以测试下

**Comment by ymwm-lxl** [comment]
感谢作者，明天上午我更新版本试一下

**Comment by CarGuo** [comment]
@ymwm-lxl 目前只在demo上更新源码，还没发布哦～

**Comment by ymwm-lxl** [comment]
😓那下个版本的发布大概是在什么时间呢？

**Comment by CarGuo** [comment]
你可以先试试看问题有没有解决，具体发布还得看测试结果呢～
