### ISSUE TITLE
类似抖音的竖屏视频，按下全屏按键，过度效果生硬

### ISSUE THREAD

**Issue by alanzyz** [CarGuo/GSYVideoPlayer#2626]
## 问题描述：
类似抖音的竖屏视频，按下全屏按键，过度效果生硬

## 问题机型/系统：

真机 三星s6  Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'`

## Demo中的复现步骤

类似抖音的竖屏视频，按下全屏按键，过度效果生硬。请问项目有添加动画，或者配置的地方么，或者你有什么建议

**Comment by CarGuo** [comment]
？？？？

**Comment by alanzyz** [comment]
demo里按下右下角的全屏，显示效果生硬

**Comment by CarGuo** [comment]
你有试过demo里其他的效果么？推荐全试试
