### ISSUE TITLE
播放时，如何获取视频是否缓存完成？

### ISSUE THREAD

**Issue by zombiu** [CarGuo/GSYVideoPlayer#2629]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放时，如何获取视频是否缓存完成？是否有相关的回调接口！

## 问题机型/系统：

真机 小米note2 Android8.0

## GSY依赖版本

com.shuyu:GSYVideoPlayer:6.0.3

## Demo中的复现步骤

无

问题代码：(如果有)

**Comment by zombiu** [comment]
我这边需要知道缓存完成之后，将视频放到相册里！

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/37286e844af165ad73861bfb1688da33a7596d21/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/GSYVideoBaseManager.java#L404



和

https://github.com/CarGuo/GSYVideoPlayer/blob/37286e844af165ad73861bfb1688da33a7596d21/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/cache/ProxyCacheManager.java#L94
