### ISSUE TITLE
可以把这个delayTime开放出来吗，我10秒的短视频，他就占了2.5秒，对视频查看体验，不是很好

### ISSUE THREAD

**Issue by yovenny** [CarGuo/GSYVideoPlayer#263]
private void startDismissControlViewTimer() {
        this.cancelDismissControlViewTimer();
        this.mDismissControlViewTimer = new Timer();
        this.mDismissControlViewTimerTask = new StandardGSYVideoPlayer.DismissControlViewTimerTask();
        this.mDismissControlViewTimer.schedule(this.mDismissControlViewTimerTask, 2500L);
    }

**Comment by CarGuo** [comment]
下个版本加上

**Comment by CarGuo** [comment]
try 1.6.7
