### ISSUE TITLE
安卓本地资源怎么进行播放

### ISSUE THREAD

**Issue by toneaky** [CarGuo/GSYVideoPlayer#2633]
## 问题描述：

录制视频及音乐后，进行视频播放，拿到的是本地的mp4视频资源

## 问题机型/系统：

例如 真机 小米Max2
## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
xxxxxxx

```

**Comment by CarGuo** [comment]
file协议开头

**Comment by toneaky** [comment]
file:///storage/emulated/0/CameraDemo/video/SucessVideo/20200401110538.mp4
这种地址感觉放了没效果啊

**Comment by toneaky** [comment]
解决了，自己弄叉了。
