### ISSUE TITLE
大神，请问可以设置缓存的大小么？怎么设置？现在默认是512M

### ISSUE THREAD

**Issue by stewForAni** [CarGuo/GSYVideoPlayer#2635]

**Comment by CarGuo** [comment]
大佬，下个版本才支持，ProxyCacheManager 增加了 DEFAULT_MAX_SIZE

**Comment by stewForAni** [comment]
> 大佬，下个版本才支持，ProxyCacheManager 增加了 DEFAULT_MAX_SIZE
大哥，完了，我用的是 6.0.3

**Comment by CarGuo** [comment]
大哥，别急，自定义下自己的 CacheManager ，然后调用  builder.maxCacheSize(); 既可以了，cv 一个现在源码里的 ProxyCacheManager

**Comment by stewForAni** [comment]
> CacheManager

自定义CacheManager继承ProxyCacheManager，调用builder.maxCacheSize()。
然后我在哪个地方把这个自定义的CacheManager设置进去？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/05f7e469f8c15311cd521838f3dccdcdbe0b5c1d/app/src/main/java/com/example/gsyvideoplayer/GSYApplication.java#L49
