### ISSUE TITLE
大哥，我又来了！

### ISSUE THREAD

**Issue by stewForAni** [CarGuo/GSYVideoPlayer#2636]
## 问题描述：

6.0.3版本，进入activity是默认全屏模式，然后用GSYVideoOptionBuilder设置setFullHideStatusBar和setFullHideActionBar无效

## 问题机型/系统：

华为 honor 8X

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3

**Comment by CarGuo** [comment]
这个只在 resolveFullVideoShow 方法里处理的，默认就是全屏你外部自己处理就好了

**Comment by stewForAni** [comment]
> 这个只在 resolveFullVideoShow 方法里处理的，默认就是全屏你外部自己处理就好了

谢谢大哥，那我自己处理吧
