### ISSUE TITLE
关于倍速播放的问题

### ISSUE THREAD

**Issue by IvesZY** [CarGuo/GSYVideoPlayer#2637]
大佬，请问一下，我用您demo上面mp4网络视频地址，可以实现倍速播放，但是用我自己的网络视频地址，倍速播放无效，已经让美工把视频编码换成和您的视频一样的了，不过我的视频大小有四百多M，会不会因为视频大小的原因导致的？麻烦大佬能给点意见

**Comment by IvesZY** [comment]
忘了说，是用的非AndroidX版本，引用的6.0.3的完整版本

**Comment by CarGuo** [comment]
不大清楚，如果方便可以提供 url 测试。

**Comment by IvesZY** [comment]
不好意思，他们不让给，我现在在下载不同大小的视频测试，目前298M的视频是OK的

**Comment by CarGuo** [comment]
倍速和音频大小没关系，主要是和音频的同步时钟有关。

**Comment by IvesZY** [comment]
我视频是无声的视频，那是不是因为没音频导致的

**Comment by CarGuo** [comment]
宾果～没有音频的不支持倍速

**Comment by IvesZY** [comment]
我这边加了音频还是无效，要裂开了，大佬，对音频格式有无要求

**Comment by CarGuo** [comment]
你用的是 ijk 内核还是 exo 内核？

**Comment by IvesZY** [comment]
ijk的内核

**Comment by CarGuo** [comment]
ijk 的同步时钟是音轨，setSpeed 的时候你试试开启 soundTouch ，然后注意允许手机的版本 6.0 以上。

如果不行再试试 exo 内核。

**Comment by IvesZY** [comment]
手机上是没问题的，我的APK安装在Android TV上，其他的网络URL都OK ，后台提供的URL在手机上能倍速，电视上就不行，盒子是Android 9.0的

**Comment by CarGuo** [comment]
····推进你试试 exo 内核，如果不行我也木办法了

**Comment by IvesZY** [comment]
换成EXO的内核，开启soundTouch ，可以倍速了，感谢大佬
