### ISSUE TITLE
画面旋转可以放一个方法出来使用么？

### ISSUE THREAD

**Issue by ymwm-lxl** [CarGuo/GSYVideoPlayer#2638]
画面旋转可以放一个方法出来使用么？

**Comment by CarGuo** [comment]
setRotateViewAuto

setLockLand

setRotateWithSystem

OrientationUtils  class

**Comment by ymwm-lxl** [comment]
代码开始播放有办法不显示播放按钮么

**Comment by CarGuo** [comment]
你继承后在开始播放的方法调用 onClickUiToggle

**Comment by ymwm-lxl** [comment]
好的，非常感谢，之前提过一个内存泄漏的问题，希望新版本中解决，

**Comment by ymwm-lxl** [comment]
继承后在开始播放的方法调用 onClickUiToggle 仍然没有生效
