### ISSUE TITLE
问题请教，关于广告页

### ISSUE THREAD

**Issue by Alexxiaopang** [CarGuo/GSYVideoPlayer#2639]
## 问题描述：

请教一下，我看demo的广告页都是要继承GSYBaseADActivityDetail<R,T> 毕竟项目里面不可能继承这个，请问有什么办法兼容？

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

**Comment by CarGuo** [comment]
参考 GSYBaseADActivityDetail 直接写就可以了，GSYBaseADActivityDetail 就是一个封装例子
