### ISSUE TITLE
直播流，onbuffering回调问题

### ISSUE THREAD

**Issue by amszsthl** [CarGuo/GSYVideoPlayer#264]
调试发现，onbuffering这个方法是一直在调用的，而且如果是播放直播流的话，percent返回的一直是0。测试有的情况是视频播放自动暂停了（有可能网络不稳定吧）有没有可能优化？还有请问有没有好的方法获取直播流缓冲进度？相当于断网重连。

**Comment by CarGuo** [comment]
有url么？

**Comment by amszsthl** [comment]
这个问题不是必现的就是，流地址：rtmp://rtmp-xy.1234tv.com/live/202010

**Comment by One28Piece** [comment]
我也遇到相同的问题，直播流一直调用changeUiToPlayingBufferingShow

**Comment by amszsthl** [comment]
这个问题可能是ijk的问题或者是我的代码问题，rtmp流onInfo回调bufferStart就卡住了，701状态值。到不了702。需要手动点击播放按钮才继续播放。

**Comment by c1024** [comment]
我播放直播流时切换后台，再回来播放有时会卡在changeUiToPlayingBufferingShow
