### ISSUE TITLE
请教问题, 没有url的情况下,能否播放视频数据?

### ISSUE THREAD

**Issue by wulileon** [CarGuo/GSYVideoPlayer#2640]
请问大佬, 如果没有视频url, 但是可以通过socket从服务端下载数据, 是否能够播放从 socket 中取到的视频数据?

**Comment by CarGuo** [comment]
不支持

**Comment by wulileon** [comment]
大神,再请教一下, 这种情况是否能自定义proxy或者缓存实现"在线播放"? 或者有什么方法可以实现吗?

**Comment by wulileon** [comment]
大神,再请教一下,  我看源码里面有 ByteArrayCache,  这个是否能用于接收 byte数据流然后缓存在本地, 播放器读取缓存数据来实时播放在线视频? 还是我这个没有 url 的情况的问题, 或者是否有其他方式实现?

**Comment by pie-tk** [comment]
@wulileon 解决了么？
