### ISSUE TITLE
列表自动播放的问题

### ISSUE THREAD

**Issue by LDJHXM** [CarGuo/GSYVideoPlayer#2641]
最新版本
防抖音功能  列表自动播放  播放第一个正常  下一个播放就会一直准备中 回调onStartPrepared  在下一个视频就正常播放 隔一个视频才能播放成功~(一直卡在onStartPrepared的再次点击播放才可以正常播放)

**Comment by LDJHXM** [comment]
这个问题之前在饺子播放器也有过 都是一样的问题 又时候是必现的 有时候就没问题 看起来好像和网络有关 但是你的demo列表播放也有这个问题 隔着一个视频播放有时候播放失败 一直卡在onStartPrepared 再次点击就可以播放了

**Comment by LDJHXM** [comment]
我找到问题了 原因是我先播放着网易云音乐 然后再去打开视频列表  这时音乐停了 但是列表就会出现隔着一个才能自动播放成功的问题了 节操也是这样

**Comment by CarGuo** [comment]
列表自动播放 只是 demo 里一个演示例子，具体可以自己参考如何调整
