### ISSUE TITLE
使用了方案c的依赖，和问题17的代码，依然无法播放rtsp

### ISSUE THREAD

**Issue by 298068845** [CarGuo/GSYVideoPlayer#2644]
## 问题描述：

无法播放rtsp视频，日志提示大致如下
Unable to connect to  "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
……
Cause by: unknown protocol : rtsp

## 问题机型/系统：

zte android9

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.3'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.3'
## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOphtionModel);
GSYVideoManager.instance().setOptionModelList(list);

已经将问题17的代码加进去，把issues的都看了一遍，实在找不到原因了

**Comment by 298068845** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class);
把这个代码注释了就没这个报错了，按readme描述这个支持格式更多不是应该适用场景更多吗，注释以后没报错点击播放就一直在loading，多次尝试播放顶多能播一两秒就继续卡在loading处了，cacheWithPlay已经是false

**Comment by CarGuo** [comment]
这个是exoplayer内核，不是ex_so依赖

**Comment by 298068845** [comment]
我的rtsp流是aac音频格式，播放不出声音，我应该用demo的哪个部分去测试呢

**Comment by 298068845** [comment]
//ijk内核，默认模式
PlayerFactory.setPlayManager(IjkPlayerManager.class);
用了这个模式就有声音了，这个默认模式不是不用主动设置的那种默认吗……
