### ISSUE TITLE
封面顶部是加了个黑色的蒙层嘛？

### ISSUE THREAD

**Issue by nxnyk** [CarGuo/GSYVideoPlayer#2645]
![Inked微信图片_20200408110529_LI_Moment](https://user-images.githubusercontent.com/42330422/78740368-249d7200-7989-11ea-92d8-c3c8e9e6fca0.jpg)
 如何取消这个蒙层呀~

**Comment by CarGuo** [comment]
继承后你可以重载 getLayoutId，这个是在 

```
    <LinearLayout
        android:id="@+id/layout_top"
        android:background="@drawable/video_title_bg"
·····
``` 

这里设置的

**Comment by nxnyk** [comment]
> 继承后你可以重载 getLayoutId，这个是在
> 
> ```
>     <LinearLayout
>         android:id="@+id/layout_top"
>         android:background="@drawable/video_title_bg"
> ·····
> ```
> 
> 这里设置的

ok 谢谢
