### ISSUE TITLE
GSYVideoGLView.addGLView拿到的GLSurfaceView不能用

### ISSUE THREAD

**Issue by xuzh2017** [CarGuo/GSYVideoPlayer#2646]
## 问题描述：
大佬。我VR播放需要只能用GLSurfaceView，通过
GSYVideoGLView.addGLView(context, textureViewContainer, rotate, gsySurfaceListener, videoParamsListener, effect, transform, customRender, mode);
拿到后运行报下面错误
java.lang.IllegalStateException: setRenderer has already been called for this instance
是这一句gsyVideoGLView.initRender();逻辑导致的异常。但是还是没找到原因。
如果直接new GLSurfaceView()是没问题的，
麻烦给看一下吧

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

代码
    @Override
    protected void addTextureView() {
        if (mTextureView == null || glSurfaceView == null) {
            glSurfaceView = GSYVideoGLView.addGLView(mContext, mTextureViewContainer, mRotate, this, this, mEffectFilter, mMatrixGL, null, mMode);
            mTextureViewContainer.removeAllViews();
            mTextureViewContainer.addView(glSurfaceView);
        }
        mVRLibrary = getVRLibrary();
  }

**Comment by CarGuo** [comment]
setRenderer has already been called for this instance 了啊，如果你需要自己做的话，推荐你自定义 view ： 参考demo 的 ： CustomRenderView + CustomRenderVideoPlayer
