### ISSUE TITLE
大哥 我又又来了

### ISSUE THREAD

**Issue by stewForAni** [CarGuo/GSYVideoPlayer#2647]
1.我自己写了ProxyCacheManager，把max-size定为20M，但是发现缓存超过20M了，没有触发clearcache，请问怎么回事，该怎么处理？

2.我这边视频的链接每次调接口，后缀都会不一样，请问可以修改缓存标识嘛？比如只取链接的前缀，然后设置在哪个位置？

3.【6.0.3版本】

4.谢谢大哥

**Comment by CarGuo** [comment]
1、clearcache 并不是内部调用的，不同视频之间才会自动清理。
2、这个标示只能你自己按照业务方式去决定。

**Comment by stewForAni** [comment]
> 1、clearcache 并不是内部调用的，不同视频之间才会自动清理。
> 2、这个标示只能你自己按照业务方式去决定。

大哥下午好啊！

1.视频在cdn，虽然内容一样，但每次链接地址不一样（后缀签名会变），这样算是不同视频吧？定了20M缓存空间，然后看几遍下载几遍，小白不清楚为啥了。。。

2.这个key我想知道在ProxyCacheManager的哪里设置？

**Comment by CarGuo** [comment]
你看 clearCache 方法，里面用了 Md5FileNameGenerator
