### ISSUE TITLE
4g网络播放视频经常出现加载中的界面

### ISSUE THREAD

**Issue by YaCZHong** [CarGuo/GSYVideoPlayer#2648]
## 问题描述：
使用4g网络播放一段50分钟左右的视频，网络是正常的，但在播放的过程中经常出现加载中的界面，加载了一段时间，继续播放，播放了一会又重新加载。但是切换到WIFI却又回归正常，已经有设置为setCacheWithPlay(false)，所以想请教一下，在不切换内核的情况下，有什么解决的方法吗？

## 问题机型/系统：

真机 荣耀9 Android9.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
这个没啥办法，估计是 DNS 和运行商的问题

**Comment by YaCZHong** [comment]
好吧，谢谢
