### ISSUE TITLE
demo里详情的时候，全屏点手机返回键，底部菜单栏会隐藏

### ISSUE THREAD

**Issue by wangjianchi** [CarGuo/GSYVideoPlayer#265]
详情的时候，全屏的时候按手机返回键，会隐藏系统底部菜单栏，点退出全屏不会

**Comment by CarGuo** [comment]
哪个Activity？

**Comment by wangjianchi** [comment]
华为P9上发生的，我看了除了PlayActivity,都有这个问题

**Comment by wangjianchi** [comment]
![Uploading device-2017-06-12-154819.png…]()

是不是因为这个方法引起的？public static boolean backFromWindowFull(Context context)

**Comment by CarGuo** [comment]
目前看来不是

**Comment by CarGuo** [comment]
找到问题了。是这里的问题导致。全屏标识位没有生效。
![wechatimg24](https://user-images.githubusercontent.com/10770362/27026978-43d69170-4f92-11e7-8c7d-d0e054220ff7.jpeg)

下图按照下图处理即可解决，下个版本将修复问题。

![wechatimg23](https://user-images.githubusercontent.com/10770362/27026997-5bce6172-4f92-11e7-8f07-0041ba9ba4fc.jpeg)

**Comment by wangjianchi** [comment]
谢谢大神，我测试了，已经可以了

**Comment by chowaikong** [comment]
这个问题依然存在。
依赖版本：2.1.1
配置代码与 demo 的 DetailPlayer 一致
测试机型：荣耀 5X（Android 6.0.1）, Google Pixel（Android 8.1.0）
