### ISSUE TITLE
我在一个界面同时设置了多个播放器，需要对单个播放器进行静音开启调整，应该怎么做？

### ISSUE THREAD

**Issue by zhaichuankai** [CarGuo/GSYVideoPlayer#2651]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米6x Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
Demo 中的 CustomManager 配合 MultiSampleVideo

**Comment by zhaichuankai** [comment]
demo中都是调整系统的音量来实现的啊- -
