### ISSUE TITLE
自定义缓存key

### ISSUE THREAD

**Issue by stewForAni** [CarGuo/GSYVideoPlayer#2652]
请问如何自定义缓存key，ijkplayer内核，6.0.3版本。

菜鸡一只，希望大神讲明白点。

**Comment by CarGuo** [comment]
需要就是自定义 `ProxyCacheManger` ，然后设置HttpProxyCacheServer 的 fileNameGenerator

**Comment by stewForAni** [comment]
> 需要就是自定义 `ProxyCacheManger` ，然后设置HttpProxyCacheServer 的 fileNameGenerator

谢谢哥，爱你😍
