### ISSUE TITLE
华为p30全屏旋转屏幕的问题

### ISSUE THREAD

**Issue by HolmesBill** [CarGuo/GSYVideoPlayer#2656]
（！！！！请务必务必按照issue模板，修改 后提交问题！！！！，不按模板提Isuue删除处理）
（ps 首页问题集锦和demo请先了解一下！）

提问前建议先看看： https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
问题描述：
华为手机发生了这样的问题！安装我们的app，在看视频的时候点击全屏，但全屏不来，先变成横屏，在变成竖屏，player没变法，只有屏幕在变

问题机型/系统：
HUAWEI P30 Android10

GSY依赖版本
 implementation 'com.shuyu:GSYVideoPlayer:7.1.3'

问题代码：(如果有)

xxxxxxx
问题log（如果有）

因为这部华为手机连不上电脑，所以看不到日志

**Comment by CarGuo** [comment]
我这样是 p30pro， demo 测试正常
