### ISSUE TITLE
OrientationUtils 8.0手机 设置屏幕方向crash问题

### ISSUE THREAD

**Issue by yangxu1210** [CarGuo/GSYVideoPlayer#2659]
## 问题描述：

OrientationUtils类没有对8.0系统的Only fullscreen activities can request orientation crash处理啊

## 问题机型/系统：

真机 Android8.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by yangxu1210** [comment]
gradle集成方式 我们现在要解决这个问题 怎么破呀。。。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1869#issuecomment-569615314

demo 没有发现问题

**Comment by yangxu1210** [comment]
升级最新的版本 相关api会不会变动太多





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuyu Guo"<notifications@github.com&gt;; 
发送时间: 2020年4月14日(星期二) 中午11:47
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;; 
抄送: "杨太太"<511576657@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CarGuo/GSYVideoPlayer] OrientationUtils 8.0手机 设置屏幕方向crash问题 (#2659)





 
#1869 (comment)
 
demo 没有发现问题

**Comment by yangxu1210** [comment]
老版本、6.0.1的 远程依赖方式 大佬有什么办法可以解决这个问题么



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuyu Guo"<notifications@github.com&gt;; 
发送时间: 2020年4月14日(星期二) 中午11:47
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;; 
抄送: "杨太太"<511576657@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CarGuo/GSYVideoPlayer] OrientationUtils 8.0手机 设置屏幕方向crash问题 (#2659)





 
#1869 (comment)
 
demo 没有发现问题

**Comment by CarGuo** [comment]
6.x 的已经不维护了，可以参考issue 的改动自定调整
