### ISSUE TITLE
集成到项目中有声音没有图像

### ISSUE THREAD

**Issue by mclmdream** [CarGuo/GSYVideoPlayer#266]
1.集成到项目中有声音没有图像，后台报SDL_Overlay(ffmpeg): overlay_free_l；

**Comment by CarGuo** [comment]
请查看问题集锦

**Comment by mclmdream** [comment]
在module配置文件加上需要额外支持的格式，这个格式是指视频格式还是x86之类的这种格式？另外播放同一个视频，已经把arm64-v8a，armeabi，armeabi-v7a，x86，x86_64的.so都加上了，在新建项目中把你的demo源码集成可以播放，但是在公司项目还是有声音没有图像，是不是个公司项目jar包之类的冲突了？

**Comment by CarGuo** [comment]
有声音没图像有两种情况，

一种是视频的编码格式当前so没有额外支持，需要自己配置后重新编译。

另外一种外部原因导致TextureView没有正常创建和显示好，这种是什么原因就需要你自己调试了

**Comment by mclmdream** [comment]
谢谢大牛的提示，找到问题了，使用TextureView必须开启硬件加速器，否则setSurfaceTextureListener()的回调方法不会执行，

**Comment by windflowersnowandmoon** [comment]
我也遇到一模一样的问题，开加速就好了，但是群主能讲下原因吗？在新建项目中把你的demo源码集成可以播放，但是在公司项目还是有声音没有图像。也是这样的问题，我新建的项目没有开加速也是正常的。

**Comment by CarGuo** [comment]
API版本问题

**Comment by zht392204992** [comment]
画面正常，但是没有声音，怎么解决

**Comment by CarGuo** [comment]
首先你需要确定音频的编码是什么。

其次播放器

GSYVideoManager.instance().setVideoType 方法可以配置播放器为exo或者mediaplayer。

**Comment by liuxusuifeng** [comment]
我把播放器组件打包到ReactNative上播放出现有声音没有画面请问有解决方案吗？上面的方案都试了都不行

**Comment by zhouwenton** [comment]
可以播放手机本地的视频吗

**Comment by lixiang5054** [comment]
我也遇到这个问题 我加上硬件加速也不行  降低视频分辨率是可以的  但是TV自身播放缓存的高清视频 是可以的 这是为什么呢
