### ISSUE TITLE
demo中的SwitchListVideoActivity页面，当列表切换到详情页再返回到列表页后，列表页的视频直接播放到了结束

### ISSUE THREAD

**Issue by linfeizheng** [CarGuo/GSYVideoPlayer#2662]
## 问题描述：

demo中的SwitchListVideoActivity页面，当列表切换到详情页再返回到列表页后，列表页的视频直接播放到了结束

## 问题机型/系统：

例如 真机 google pixel1 Android8.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

## Demo中的复现步骤

Demo中的SwitchListVideoActivity页面，按问题描述操作一遍会出现这个问题。

问题代码：(如果有)
```
无
```

## 问题log（如果有）

```
无

```

**Comment by CarGuo** [comment]
设计如此，你看 demo 源码，如有需要再继续自定义可自行调整，这个只是 demo 展示思路。
