### ISSUE TITLE
关于adPlayer 广告播放器的相关特性

### ISSUE THREAD

**Issue by czeall** [CarGuo/GSYVideoPlayer#2663]
作者好：
       最近在调研Android视频播放器添加广告头广告尾的实现方案发现了作者的处理方法。在使用广告头播放器的过程中，发现广告播放器只是提供了列表播放广告头+正片+广告尾和UI上的处理，并没有针对视频做预加载处理。
      想咨询一下作者如果要在广告播放器上进行预加载的操作(广告头播放结束前加载正片视频部分内容，避免播放正片时造成缓冲)应该怎么处理；如果要在正片中间添加广告播放的话有没有什么好的实现方案。

**Comment by CarGuo** [comment]
Demo 里 DetailDownloadPlayer 中的 startDownload 支持播放前提前下载部分。

DetailExoListPlayer 的例子支持列表中提前预加载，使用的是 ConcatenatingMediaSource
