### ISSUE TITLE
当播放器播放结束后，进度条会停留在结束，可否停留在0秒，并且恢复封面

### ISSUE THREAD

**Issue by linfeizheng** [CarGuo/GSYVideoPlayer#2664]
## 问题描述：

当播放器播放结束后，进度条会停留在结束，可否停留在0秒，并且恢复封面

## 问题机型/系统：

真机 pixel1 Android8.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

## Demo中的复现步骤

demo都试停留在结束，求一个思路实现我的需求

**Comment by CarGuo** [comment]
changeUiToCompleteClear 和 changeUiToCompleteShow 重载这两个方法

刚刚更新了下 demo 中的 LandLayoutVideo 和 DetailPlayer

**Comment by chuxiaokeAndroid** [comment]
我试了这两个方法，继承的StandardGSYVideoPlayer这个类。播放完毕之后，界面是黑屏，不显示封面

**Comment by CarGuo** [comment]
你试demo

**Comment by ymwm-lxl** [comment]
我播放完成时候进度条停留在结束，但是画面从0开始重新播放了
