### ISSUE TITLE
多款手机出现，视频播放到一定时间停止，再次点击从头开始播放

### ISSUE THREAD

**Issue by hellogaod** [CarGuo/GSYVideoPlayer#2667]
## 问题描述：
1.视频连接：https://shuianxuexiao-pro.oss-cn-beijing.aliyuncs.com/video/%E9%A1%B9%E7%9B%AE%E5%A4%8D%E5%B7%A5%E5%AE%89%E5%85%A8%E3%80%81%E7%96%AB%E6%83%85%E9%98%B2%E6%8E%A7%E5%9F%B9%E8%AE%AD-2.mp4

2.视频大小：53M
3.视频时长：45分钟
当视频从头开始播放到20分钟左右，停止播放，并且点击视频则从头开始播放

## 问题机型/系统：

华为P30，华为Note2，华为mate10都出现过以上问题，而且必显

## GSY依赖版本

允许的就是本Demo

## Demo中的复现步骤

把https://shuianxuexiao-pro.oss-cn-beijing.aliyuncs.com/video/%E9%A1%B9%E7%9B%AE%E5%A4%8D%E5%B7%A5%E5%AE%89%E5%85%A8%E3%80%81%E7%96%AB%E6%83%85%E9%98%B2%E6%8E%A7%E5%9F%B9%E8%AE%AD-2.mp4放到简单视频中的详情2中播放

## 问题log（如果有）
GSYVideoPlayer: cancelTimeOutBuffer
Link Or mCache Error, Please Try Again 视频Url。

**Comment by CarGuo** [comment]
以私聊对接

**Comment by wdeo3601** [comment]
@hellogaod 遇到相同问题了，请问你是怎么解决的

> ## 问题描述：
> 1.视频连接：https://shuianxuexiao-pro.oss-cn-beijing.aliyuncs.com/video/%E9%A1%B9%E7%9B%AE%E5%A4%8D%E5%B7%A5%E5%AE%89%E5%85%A8%E3%80%81%E7%96%AB%E6%83%85%E9%98%B2%E6%8E%A7%E5%9F%B9%E8%AE%AD-2.mp4
> 
> 2.视频大小：53M
> 3.视频时长：45分钟
> 当视频从头开始播放到20分钟左右，停止播放，并且点击视频则从头开始播放
> 
> ## 问题机型/系统：
> 华为P30，华为Note2，华为mate10都出现过以上问题，而且必显
> 
> ## GSY依赖版本
> 允许的就是本Demo
> 
> ## Demo中的复现步骤
> 把[https://shuianxuexiao-pro.oss-cn-beijing.aliyuncs.com/video/%E9%A1%B9%E7%9B%AE%E5%A4%8D%E5%B7%A5%E5%AE%89%E5%85%A8%E3%80%81%E7%96%AB%E6%83%85%E9%98%B2%E6%8E%A7%E5%9F%B9%E8%AE%AD-2.mp4放到简单视频中的详情2中播放](https://shuianxuexiao-pro.oss-cn-beijing.aliyuncs.com/video/%E9%A1%B9%E7%9B%AE%E5%A4%8D%E5%B7%A5%E5%AE%89%E5%85%A8%E3%80%81%E7%96%AB%E6%83%85%E9%98%B2%E6%8E%A7%E5%9F%B9%E8%AE%AD-2.mp4%E6%94%BE%E5%88%B0%E7%AE%80%E5%8D%95%E8%A7%86%E9%A2%91%E4%B8%AD%E7%9A%84%E8%AF%A6%E6%83%852%E4%B8%AD%E6%92%AD%E6%94%BE)
> 
> ## 问题log（如果有）
> GSYVideoPlayer: cancelTimeOutBuffer
> Link Or mCache Error, Please Try Again 视频Url。

@hellogaod 我这遇到相同的问题了，请问你是怎么解决的

**Comment by ssyijiu** [comment]
我也遇到这个问题了
public static final int CURRENT_STATE_ERROR = 7;
到了这个状态之后，就会从头播放，有办法继续原来的进度播放吗 ？
