### ISSUE TITLE
华为mate2.0 直播180度颠倒

### ISSUE THREAD

**Issue by yubaokang** [CarGuo/GSYVideoPlayer#2671]
## 问题描述：

华为mate2.0发生了视频旋转180度的问题，其他手机好的

## 问题机型/系统：

真机 华为mate2.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'`

## Demo中的复现步骤

抱歉，指定机型问题

**Comment by CarGuo** [comment]
推荐你调试 MeasureHelper .  doMeasure 和 GSYVideoView . onInfo -> etGSYVideoManager().getRotateInfoFlag()

**Comment by yubaokang** [comment]
抱歉了，这个问题是我们视频直播提供商的问题
