### ISSUE TITLE
m3u8下载技术请教

### ISSUE THREAD

**Issue by 11bq** [CarGuo/GSYVideoPlayer#2676]
现在有下载m3u8的需求,但是视频链接来源不固定,加密的方式也不固定,目前需求中已发现的大概有7,8种类型的,用GSY都可以播,但是想实现下载的话,需要得到ts的真实地址,直接打开链接获取到内容做判断的话,无法兼顾绝大部分的类型,所以想请教一下你们解析url的时候是怎么获取到真实的ts地址的,如果不便说的话,可以说一下大概的实现原理吗,万分感谢

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2557
