### ISSUE TITLE
你好，问一个我想问一个与bug无关的问题，为什么在旋转屏幕的时候需要重新创建GSYBaseVideoPlayer对象呢？

### ISSUE THREAD

**Issue by liangjiaxi** [CarGuo/GSYVideoPlayer#2683]
我有个疑惑，就是在旋转屏幕的时候可以我们可以直接替换layout和再次调用init方法即可，重新创建GSYBaseVideoPlayer不是更加复杂了吗？

**Comment by CarGuo** [comment]
其实这么说吧：
1、首先需要全屏的时候把视频添加到顶层 view 里面。
2、有些需求全屏 view 和非全屏 view 样式独立不同。
3、clone 一个参数一致的对象，在退出全屏时销毁，在渲染显示的时候相互独立，这样比较好区分管理。
4、Surface 的构建和恢复也独立了。
虽然复杂度变高，但是在一些场景，特别是列表到全屏的场景，你不用去管理播放中的 Surface 和 View 究竟需要依附哪个 parent 和 remove 。

**Comment by liangjiaxi** [comment]
好的，我懂你的思路了，谢谢你！
