### ISSUE TITLE
如何关闭日志

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#2684]
![image](https://user-images.githubusercontent.com/22672329/80085140-6aae2480-858a-11ea-9ee1-7587926b8a63.png)

播放视频，后台一直在打印日志，怎么关闭？

![image](https://user-images.githubusercontent.com/22672329/80084266-39812480-8589-11ea-9fa2-3d2b017a0823.png)
GSYVideoManager目前没有这个方法

GSY版本：com.shuyu:GSYVideoPlayer:6.0.3

**Comment by CarGuo** [comment]
IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);

        Debugerdisable.

**Comment by kkouer** [comment]
为何不生效呢?

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/3839#issuecomment-1624493911 @kkouer

**Comment by kkouer** [comment]
@CarGuo 看不懂啊,大佬,本人菜鸟,能否明示呢?

**Comment by jarvan11** [comment]
IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_DEBUG)
这是IJK内核的输出日志设置，EXO内核的输出日志设置代码是什么
