### ISSUE TITLE
自定义界面  在点击全屏的时候会显示一个列表  列表数据和宽度都显示不出来

### ISSUE THREAD

**Issue by Lyl521** [CarGuo/GSYVideoPlayer#2685]
## 问题描述：
自定义界面  在点击全屏的时候会显示一个列表  列表数据和宽度都显示不出

## 问题机型/系统：
 小米note2 Android7.0

## GSY依赖版本

`implementation '"com.shuyu:GSYVideoPlayer:6.0.2'`

## Demo中的复现步骤
我把修改UI的代码写到了全屏按钮的点击事件里面

问题代码：(如果有)
 player.getFullscreenButton().setOnClickListener(v -> {
             在这里修改UI  但是无效果
             }

**Comment by CarGuo** [comment]
player.getCurrentPlayer().getFullscreenButton().setOnClickListener(v -> {

}
