### ISSUE TITLE
加载视频中视频Pause后Resume会只有声音没有画面

### ISSUE THREAD

**Issue by Teemo100** [CarGuo/GSYVideoPlayer#2686]
## 问题描述：

加载网络视频时，在加载期间APP返回到桌面，然后再返回APP，继续加载网络视频后，只有声音没有画面

## 问题机型/系统：

 Oppo Reno3   小米Max 

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

## Demo中的复现步骤

加载个网络视频，加载到一半的时候，把APP退到后台回到手机桌面，再回到APP之后再继续加载就不显示画面了

问题代码：(如果有)
Resume 里调用
```
public void start() {
        if (isPaused()) {
            onVideoResume(false);
        } else if (isCompleted()) {
            onVideoReset();
            startPlayLogic();
        } else {
            startPlayLogic();
        }
    }
```
Pause里调用
```
onVideoPause();
setStateAndUi(CURRENT_STATE_PAUSE);
```

**Comment by CarGuo** [comment]
demo 哪个页面复现问题？？
