### ISSUE TITLE
关于DanmakuVideoPlayer播放和其它App播放焦点问题？

### ISSUE THREAD

**Issue by TeaHerbal** [CarGuo/GSYVideoPlayer#2687]
## 问题描述
在弹幕DEMO界面播放视频，然后点击通知栏中的其他app的播放音乐按键来抢占焦点，导致弹幕Player页面卡主，（关闭其他app或不关闭一样效果）点击播放或者快进等都无效

## 问题机型/系统：

例如 真机 红米20pro Android10.0

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

Demo中的DanmkuVideoActivity页面打开后播放，然后点击通知栏中其它的app音乐播放器会出现这个问题。
PS:菜鸟第一次提问题，不知道是否符合大神要求的格式，望大神帮忙解决一下

**Comment by CarGuo** [comment]
em····不就是这个的问题吗？

```
    @Override
    public void onVideoPause() {
        super.onVideoPause();
        danmakuOnPause();
    }

    @Override
    public void onVideoResume(boolean isResume) {
        super.onVideoResume(isResume);
        danmakuOnResume();
    }
```

**Comment by TeaHerbal** [comment]
感谢大神的解答，我描述问题有误，不是弹幕卡主不动，而是弹幕播放器卡住不动，多级播放器(可以下一级播放)也会出现卡住不动的现象，大神可以试一下，先进入酷狗播放器，然后播放一首歌，切换出去，使通知栏有酷狗播放器按钮，然后进入demo中的DanmkuVideoActivity页面播放视频，后向下画出通知栏中的酷狗播放器播放歌曲抢占焦点，然后DanmkuVideoActivity界面的卡住不动，点击播放按钮无用

**Comment by CarGuo** [comment]
danmakuVideoPlayer.setReleaseWhenLossAudio(false);

**Comment by TeaHerbal** [comment]
谢谢大佬的指点，问题解决了，我之前设置的true
