### ISSUE TITLE
ffmpeg yuvj420格式的图片生成的视频  播放黑屏   求助大佬- -

### ISSUE THREAD

**Issue by zhaichuankai** [CarGuo/GSYVideoPlayer#2689]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米6x Android8.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

xxxxxxx

```

**Comment by zhaichuankai** [comment]
Option ijkapplication not found.

**Comment by zhaichuankai** [comment]
试了几个播放器，系统播放器是没问题的   qq的播放器也是黑屏   电脑上带的播放器也没问题

**Comment by zhaichuankai** [comment]
我把资源放在demo中也是黑屏  无论是那种格式 还是硬解码

**Comment by CarGuo** [comment]
请提供测试流 url，Demo 中也可以通过  PlayerFactory.setPlayManager(SystemPlayerManager.class); 切换到系统播放内核
