### ISSUE TITLE
demo中SimplePlayer的screenOrientation改为landscape

### ISSUE THREAD

**Issue by huangruiLearn** [CarGuo/GSYVideoPlayer#2692]
## 问题描述：

demo中SimplePlayer的screenOrientation改为landscape 后, 运行进入SimplePlayer自动变成竖屏了又,没有横屏播放

## 问题机型/系统：

 genymontion和as自带的模拟器有这个问题,真机没有  

## GSY依赖版本

 implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

## Demo中的复现步骤

demo中SimplePlayer的screenOrientation改为landscape 在进入SimplePlayer自动变成竖屏了又,没有横屏播放

**Comment by CarGuo** [comment]
em····如下图所示，正常啊

![](https://user-images.githubusercontent.com/10770362/80454982-83895200-895d-11ea-8894-254c906dd51f.gif)
