### ISSUE TITLE
自定义切换声音，默认播放静音

### ISSUE THREAD

**Issue by tinoPeng** [CarGuo/GSYVideoPlayer#2694]
您好，我想视频一进来是默认静音播放的，然后设置声音大小不滑动屏幕，而是点击想在底部增加一个音量icon，点击icon后显示声音的progressbar来设置声音大小的，请问这个需要怎么自定义呢，或者说是重写哪个方法？我这边自定义了一视频播放布局，在底部添加了一个音量icon，但是点击icon没反应，好像都没有走点击事件监听。不知道问题出现在哪？求指教。
    @Override
    public int getLayoutId() {
        View inflate = LayoutInflater.from(App.getInstance()).inflate(R.layout.layout_video, null);
        iv_voice = inflate.findViewById(R.id.iv_voice);
        iv_voice.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
//这里的方法没有走
                ToastUtil.showShort("设置声音");
            }
        });
        return R.layout.layout_video;
    }

**Comment by CarGuo** [comment]
Demo ListNormalAdapter 里就是用了播放静音，在 onPrepared。

至于你说这个方法没做，那是因为需要放到 init 方法里重载，然后确保按键的层级在 surface_container 之上
