### ISSUE TITLE
请问是否支持rmvb后缀的视频？

### ISSUE THREAD

**Issue by 951AB159BA** [CarGuo/GSYVideoPlayer#2695]
如题。我试了下，播放本地的rmvb视频无法播放，其他格式的视频可以播放。后期是否可以增加支持这个格式的视频？

**Comment by CarGuo** [comment]
https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q

https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/GSYVIDEO_PLAYER_PROJECT_INFO.md
