### ISSUE TITLE
全屏播放bug请教

### ISSUE THREAD

**Issue by liugang0324** [CarGuo/GSYVideoPlayer#2696]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

recyclerview列表的视频点击播放正常，点击全屏就有问题，播放的按钮不消失，退出后视频暂停播放也点击无响应

## 问题机型/系统：

 真机 华为荣耀10，模拟器等同一个效果

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的未出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```
我将onbind方法拿到adapter中了
![图片](https://user-images.githubusercontent.com/26995960/80457482-f694c780-8961-11ea-82bf-b91b9c23d619.png)

问题截图：
![图片](https://user-images.githubusercontent.com/26995960/80458094-de717800-8962-11ea-9e7a-6d7f55d14b8c.png)

![图片](https://user-images.githubusercontent.com/26995960/80457902-9d796380-8962-11ea-96d0-5a1ca444505a.png)

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
Demo 不复现 I have not idea
