### ISSUE TITLE
大神请教，播放网络视频缓冲还没开始的时候就拖动进度条，缓冲开始后回到0点播放，我想让视频从我拖拽的位置开始播放，怎么实现？

### ISSUE THREAD

**Issue by march12321** [CarGuo/GSYVideoPlayer#2698]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
看问题集锦，在比较下面的位置有一个配置。
