### ISSUE TITLE
横竖屏不同布局的时候，当目前切换成横屏后，放在后台一段时间，重新回到前台时，横屏的布局却变成竖屏的布局了

### ISSUE THREAD

**Issue by 951AB159BA** [CarGuo/GSYVideoPlayer#2699]
当横竖屏设置为不同布局的时候，当目前切换成横屏后，放在后台一段时间，比较长，重新回到前台时，横屏还是横屏，但是布局却变成竖屏的布局了。目前发现过2次了。可能是系统内存回收导致的变量问题出现布局异常。麻烦查下。

**Comment by 951AB159BA** [comment]
注意：正常情况下横竖屏切换布局是没问题的。

**Comment by CarGuo** [comment]
e么·····这个很奇怪啊，demo 没有复现这个，因为就算是 mIfCurrentIsFullscreen 变为 false ，但是 getLayoutId 已经装载了，除非整个 View 重新构建了，而全屏和非全屏是独立的两个 View

**Comment by 951AB159BA** [comment]
> 
> 
> e么·····这个很奇怪啊，demo 没有复现这个，因为就算是 mIfCurrentIsFullscreen 变为 false ，但是 getLayoutId 已经装载了，除非整个 View 重新构建了，而全屏和非全屏是独立的两个 View

你那边把横屏放到后台后，可以用AndroidStudio的Terminate Application按钮模拟被内存杀死，试试看。我是用DetailPlayer尝试的。

**Comment by CarGuo** [comment]
如下图所示，全屏后台 Terminate Application 后

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/10770362/80577458-80fc2a80-8a39-11ea-84e3-b00ac082eaa6.png">

**Comment by 951AB159BA** [comment]
> 
> 
> 如下图所示，全屏后台 Terminate Application 后
> 
> <img alt="image" width="1241" src="https://user-images.githubusercontent.com/10770362/80577458-80fc2a80-8a39-11ea-84e3-b00ac082eaa6.png">

那不是有问题么。正常切横屏时标题栏不在的，你现在横屏的布局又变成竖屏的布局的。你看看正常情况切横屏时什么效果

**Comment by 951AB159BA** [comment]
> 
> 
> 如下图所示，全屏后台 Terminate Application 后
> 
> <img alt="image" width="1241" src="https://user-images.githubusercontent.com/10770362/80577458-80fc2a80-8a39-11ea-84e3-b00ac082eaa6.png">

我说的这种就是模拟后台被杀死的情况。我真实情况是放在后台一段时间回到前台就是这样了

**Comment by CarGuo** [comment]
em····如果你说的是这个，那 Application 或者 Acitiviry 级别需要做的处理，比如最简单的

````
    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        onBackPressed();

    }
````
