### ISSUE TITLE
库的体积太大，占了将近16M

### ISSUE THREAD

**Issue by Gaussen** [CarGuo/GSYVideoPlayer#27]

**Comment by CarGuo** [comment]
你可以在你的app module下加入ndk过滤，带64的so就不会被打包进去了，而且你的用 as的apk分析包看，实际大小这么大，但是打包进去其实并没有那么大！

android {
···
defaultConfig {
···
ndk {
//APP的build.gradle设置支持的SO库架构
abiFilters 'armeabi', 'armeabi-v7a', 'x86'
}
}
}

文／恋猫月亮（简书作者）
原文链接：http://www.jianshu.com/p/86e4b336c17d

**Comment by Gaussen** [comment]
我正考虑该怎么弄呢 ，谢谢啊！
