### ISSUE TITLE
exo核播放本地m3u8失败

### ISSUE THREAD

**Issue by balaYYYYYYYY** [CarGuo/GSYVideoPlayer#2701]
m3u8有key的都播放不了 因为key保存在本地 不是网络路径 然后报错了

**Comment by haohaozaici** [comment]
问题就是key的uri不对，提供一下你的m3u8文件看看

**Comment by balaYYYYYYYY** [comment]
> 问题就是key的uri不对，提供一下你的m3u8文件看看

key是对的 但是是本地路径 然后exo播放的时候好像要将key转uri然后就报错了 感觉应该是exo问题 明天去exo的开源看看 其他的核都没问题

**Comment by balaYYYYYYYY** [comment]
> 问题就是key的uri不对，提供一下你的m3u8文件看看

应该和exoplayer有关 和框架无关

**Comment by CarGuo** [comment]
我这边复现不了问题
