### ISSUE TITLE
使用 GSYVideoType.setRenderType(GSYVideoType.GLSURFACE)部分视频会旋转180度

### ISSUE THREAD

**Issue by gaoxuefeng** [CarGuo/GSYVideoPlayer#2703]
GSYVideoType.setRenderType(GSYVideoType.GLSURFACE)部分视频会旋转180度,不设置的时候正常播放

**Comment by gaoxuefeng** [comment]
知道原因了跟#1974问题一样

**Comment by keepmovng** [comment]
> 知道原因了跟#1974问题一样

请问您解决这个问题了吗？能教一下吗
