### ISSUE TITLE
问题咨询，请问想添加播放进度在哪里修改？

### ISSUE THREAD

**Issue by oybo** [CarGuo/GSYVideoPlayer#2705]
问题咨询，请问想添加播放进度在哪里修改？ 谢谢， 刚看这个库。

**Comment by CarGuo** [comment]
不是很理解。

**Comment by oybo** [comment]
作者大大你好，我是想问：比如我想保存每次视频播放的进度，下次播放自动在上次播放的进度继续播放 而不是每次都是从0开始，请问支持吗？ 谢谢。

**Comment by oybo** [comment]
> 不是很理解。

作者大大你好，我是想问：比如我想保存每次视频播放的进度，下次播放自动在上次播放的进度继续播放 而不是每次都是从0开始，请问支持吗？ 谢谢。

**Comment by CarGuo** [comment]
问题集锦有，还有简单的setSeekOnStart api

**Comment by oybo** [comment]
> setSeekOnStart
好的，非常感谢。
