### ISSUE TITLE
使用 GSYVideoType.setRenderType(GSYVideoType.GLSURFACE)时候，封面隐藏后，会出现短暂黑屏

### ISSUE THREAD

**Issue by dahai2070** [CarGuo/GSYVideoPlayer#2706]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

使用  GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);  opengl 渲染模式的时候，
按demo中，重写 onSurfaceSizeChanged，代码如下，封面图片隐藏的时机仍然过早，封面隐藏后存在一段短暂的黑屏时间。
    @Override
    public void onSurfaceAvailable(Surface surface) {
        
        if (GSYVideoType.getRenderType() != GSYVideoType.TEXTURE) {
            if (mThumbImageViewLayout != null && mThumbImageViewLayout.getVisibility() == VISIBLE) {
                mThumbImageViewLayout.setVisibility(INVISIBLE);
            }
        }
    }

我尝试在  com.shuyu.gsyvideoplayer.render.glrender.GSYVideoGLViewSimpleRender#onSurfaceChanged（） 回调中去隐藏 封面，还是早了点，问题依旧，没找到好的隐藏封面的时机

## 问题机型/系统：

均有。

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

## Demo中的复现步骤
在 com.example.gsyvideoplayer.simple.SimpleListVideoActivityMode1#onCreate （）中
设置 渲染模式 为
 GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);
封面隐藏后将出现短暂黑屏。

**Comment by CarGuo** [comment]
正常情况，可以参考 SampleCoverVideo 尝试优化

**Comment by balaYYYYYYYY** [comment]
> 正常情况，可以参考 SampleCoverVideo 尝试优化

大佬 exo核播放有key加密的本地m3u8失败 因为key的地址是本地 无法转uri 有方法解决吗？

**Comment by dahai2070** [comment]
正常啊，，，，，
目前的解决是在渲染器的 onSurfaceChanged（）回调中延迟150毫秒执行封面的隐藏，但是这个笨方法，，肯定在某些手机上，仍然会黑屏。

**Comment by haohaozaici** [comment]
exoplayer可以在onRenderedFirstFrame
