### ISSUE TITLE
全屏播放停止后，封面图没有显示

### ISSUE THREAD

**Issue by linfeizheng** [CarGuo/GSYVideoPlayer#2707]
## 问题描述：

全屏播放停止后，封面图没有显示

## 问题机型/系统：

例如 真机 pixel Android8.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

## Demo中的复现步骤

Demo中的SimpleDetailActivityMode2页面打开后,全屏播放结束后player变黑色，没有显示封面图。

**Comment by CarGuo** [comment]
全屏下播放完是没有封面的，常规设计，如果需要请自己继承后处理。
