### ISSUE TITLE
当播放的m3u8存在坏块的时候播放会有问题

### ISSUE THREAD

**Issue by xuqingquan1995** [CarGuo/GSYVideoPlayer#2709]
当播放的m3u8存在坏块的时候播放到坏块的时候会出现暂停，点继续播放会从头开始播放
例如：http://wukongfenshen.com/m3u8/test.m3u8
播放以上链接的时候，这个链接在大约31秒处有一个坏块

**Comment by CarGuo** [comment]
设计如此～

**Comment by xuqingquan1995** [comment]
是EXOPlayer的问题还是？
