### ISSUE TITLE
gsyvideoplayer窗口适应问题

### ISSUE THREAD

**Issue by lingchen52** [CarGuo/GSYVideoPlayer#271]
大神，你的gsyvideoplayer的画面缩放不太完美，容易出现黑边或者铺不满屏幕以及超出屏幕，我之前用ijkplayer的ijkvideoview用IRendView.AR_MATCH_PARENT参数对屏幕适应就非常好，没出现上诉问题，希望在下次更新时多添加一种全屏显示
这是ijkplayer官方demo里的ijkvideoview里910行-930行的一段代码
`//-------------------------
    // Extend: Aspect Ratio
    //-------------------------

    private static final int[] s_allAspectRatio = {

            IRenderView.AR_ASPECT_FIT_PARENT,

            IRenderView.AR_ASPECT_FILL_PARENT,

            IRenderView.AR_ASPECT_WRAP_CONTENT,

            IRenderView.AR_MATCH_PARENT,//全屏

            IRenderView.AR_16_9_FIT_PARENT,

            IRenderView.AR_4_3_FIT_PARENT};

    private int mCurrentAspectRatioIndex = 3;

    private int mCurrentAspectRatio = s_allAspectRatio[3];

    public int toggleAspectRatio() {

        mCurrentAspectRatioIndex++;

        mCurrentAspectRatioIndex %= s_allAspectRatio.length;

        mCurrentAspectRatio = s_allAspectRatio[mCurrentAspectRatioIndex];

        if (mRenderView != null)

            mRenderView.setAspectRatio(mCurrentAspectRatio);

        return mCurrentAspectRatio;

    }
`

**Comment by CarGuo** [comment]
视频的比例和手机的比例适配下，只能有两种选择，在比例不一致的情况下，一种是有黑边，一种是超出屏幕来铺满。超出屏幕来铺满这个目前也有对应的接口设置。

**Comment by CarGuo** [comment]
try 1.6.7
