### ISSUE TITLE
视频列表能自动播放吗

### ISSUE THREAD

**Issue by liudaohong** [CarGuo/GSYVideoPlayer#2711]
我现在是用的startPlayLogic(); 在onBindViewHolder 加载内容就调用了 很卡顿

**Comment by liudaohong** [comment]
视频播放有 进度回调的吗  我需要自己显示进度

**Comment by CarGuo** [comment]
demo 的 AutoPlayRecyclerViewActivity，如果要自己显示进度，重载后实现 setProgressAndTime 或者外部 setGSYVideoProgressListener
