### ISSUE TITLE
视频时间回调会出现时间丢失的情况

### ISSUE THREAD

**Issue by Devinmzt** [CarGuo/GSYVideoPlayer#2712]
## 问题描述：
通过GSYVideoProgressListener的得到的回调时间currentPosition，然后换算成秒会出现时间不连续的情况如下这种
currentPosition=377868  377秒
currentPosition=379140  379秒
 
发现问题是GSYVideoControlView中progressTask固定1000毫秒回调一次， 能不能对外提供一个progressTask 中delayMills的方法

## 问题机型/系统：

所有机型

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

问题代码：
GSYVideoControlView：

    Runnable progressTask = new Runnable() {
        @Override
        public void run() {
            if (mCurrentState == CURRENT_STATE_PLAYING || mCurrentState == CURRENT_STATE_PAUSE) {
                setTextAndProgress(0);
            }
            if (mPostProgress) {
                postDelayed(this, 1000);
            }
        }
    };

**Comment by CarGuo** [comment]
继承后重载就可以了
