### ISSUE TITLE
视频释放后，回到上个页面视频不能继续播放

### ISSUE THREAD

**Issue by liulance** [CarGuo/GSYVideoPlayer#2713]
## 问题描述：
打开A视频播放页，再跳转到B视频列表页，再点击跳转到A视频播放页，此时关闭当前A页面，释放Video，回到B页面，再关闭B页面回到A页面，由于Video已经释放了，此时想在A页面继续播放视频，应该如何操作？谢谢

## 问题机型/系统：

所有机型

## GSY依赖版本
com.shuyu:GSYVideoPlayer:6.0.3

## Demo中的复现步骤

未看到Demo中有这个页面

问题代码：(如果有)
无

**Comment by CarGuo** [comment]
重新 setup 和 setSeekOnStart 啊，播放内核之后一个，自己做判断，在页面跳转的时候保存进度
