### ISSUE TITLE
视频播放结束后，退出全屏，修改播放器UI无效

### ISSUE THREAD

**Issue by linfeizheng** [CarGuo/GSYVideoPlayer#2714]
## 问题机型/系统：

例如 真机 pixel Android8.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`

## Demo中的复现步骤

视频开始我进入了全屏。播放结束后我调用了 getFullscreenButton().performClick();
然后修改进度条的进度，时间置0，发现没有效果

问题代码：(如果有)
```
    @Override
    public void onAutoCompletion() {
        super.onAutoCompletion();
        if (mIfCurrentIsFullscreen) {
            getFullscreenButton().performClick();
        }
        //以下几句都没有生效
        changeUiToNormal();
        setViewShowState(mBottomContainer, VISIBLE);
        mProgressBar.setProgress(0);
        mCurrentTimeTextView.setText("00:00");
        mProgressBar.setEnabled(false);
    }
```

**Comment by CarGuo** [comment]
player.getCurrentPlayer

**Comment by linfeizheng** [comment]
我重载了cloneParams，改变from的UI怎么还是没有生效呢，还需要做哪些操作希望能稍微说的详细点，新手看代码一知半解
`    @Override
    protected void cloneParams(GSYBaseVideoPlayer from, GSYBaseVideoPlayer to) {
        super.cloneParams(from, to);
        DetailVideoPlayer sf = (DetailVideoPlayer) from;
        DetailVideoPlayer st = (DetailVideoPlayer) to;
        if (st.mProgressBar != null && sf.mProgressBar != null) {
            if (st.mCurrentState == CURRENT_STATE_AUTO_COMPLETE) {
                st.mProgressBar.setProgress(0);
                st.mProgressBar.setSecondaryProgress(0);
            } else {
                st.mProgressBar.setProgress(sf.mProgressBar.getProgress());
                st.mProgressBar.setSecondaryProgress(sf.mProgressBar.getSecondaryProgress());
            }
        }
        if (st.mTotalTimeTextView != null && sf.mTotalTimeTextView != null) {
            st.mTotalTimeTextView.setText(sf.mTotalTimeTextView.getText());
        }
        if (st.mCurrentTimeTextView != null && sf.mCurrentTimeTextView != null) {
            if (st.mCurrentState == CURRENT_STATE_AUTO_COMPLETE) {
                st.mCurrentTimeTextView.setText("00:00");
            } else {
                st.mCurrentTimeTextView.setText(sf.mCurrentTimeTextView.getText());
            }
        }
    }`

**Comment by CarGuo** [comment]
cloneParams 是传递状态和参数的，

startWindowFullscreen 和 resolveFullVideoShow 是处理 UI 的，比如你看 StandardGSYVideoPlayer 的这两个方法
