### ISSUE TITLE
exo内核设置静音无效

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#2715]
## 问题描述：

我们的项目需要进入页面播放时开启静音，setNeedMute(true)无效，需要延迟几百毫秒设置静音才会成功，但是部分机型可能会出现短暂的声音后又静音。

## 问题机型/系统：

所有机型

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

Demo中的DetailExoListPlayer页面会出现这个问题。

![image](https://user-images.githubusercontent.com/13781886/81403761-adfdbb00-9166-11ea-8ca8-761a0c7bc810.png)

**Comment by CarGuo** [comment]
你需要在播放器准备好之后设置，通过设置 setPlayerInitSuccessListener ，然后在 onPlayerInitSuccess 里面获取到 IMediaPlayer 然后 setVolume

**Comment by zhangyujiu** [comment]
![image](https://user-images.githubusercontent.com/13781886/81925797-8f3e6f00-9613-11ea-8bd4-d9c1e0496601.png)
那可不可以在initSuccess后判断needMute来设置是否静音

**Comment by CarGuo** [comment]
只要你能拿到 media 对象

**Comment by zhangyujiu** [comment]
好的，感谢解答

**Comment by cjcj125125** [comment]
实时播放过程中可以开启和关闭静音嘛？

**Comment by zhangyujiu** [comment]
> 实时播放过程中可以开启和关闭静音嘛？

可以的
