### ISSUE TITLE
播放中wifi和 3G/4G网络切换的问题

### ISSUE THREAD

**Issue by WengHaobin** [CarGuo/GSYVideoPlayer#2716]
## 问题描述：

在详情页中播放视频关于WiFi和移动网络切换的问题

## 问题机型/系统：

vivo z5 Android9.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

## Demo中的复现步骤

直接4g点击播放会弹出WiFi确认，但是在WiFi播放中点击暂停，切换4g再播放不会弹出

问题代码：

![GSYVideoControlView](https://user-images.githubusercontent.com/16800049/81463183-10e46600-91ea-11ea-9228-fc50e1053357.png)

经过查看GSYVideoView中关于WiFi弹框的代码，发现是正常或者是错误状态下才会弹框，播放中或者暂停都不会弹框。是否需要优化该部分代码？

**Comment by CarGuo** [comment]
这个其实你可以在外部通过参考 createNetWorkState ，外部处理。

**Comment by WengHaobin** [comment]
OK，已找到解决办法，感谢！
