### ISSUE TITLE
无法播放https的优酷链接

### ISSUE THREAD

**Issue by 951AB159BA** [CarGuo/GSYVideoPlayer#2717]
https://v.youku.com/v_show/id_XNjMyMjYxNTgw.htm 链接无法播放

**Comment by CarGuo** [comment]
……大哥，你这是个html

**Comment by 951AB159BA** [comment]
那为什么浏览器可以播放呢？

**Comment by luxi78** [comment]
😄😄😄😄😄😄😄😄😄
顺着作者文章 https://juejin.cn/post/6940079274674094117 前来观光的

**Comment by zhangjingex** [comment]
笑死，这就不像一个程序员一个行内人提出的问题

**Comment by 8MiYile** [comment]
你不套解析能播放就有鬼了

**Comment by aimerneige** [comment]
前来围观

**Comment by appleneko2001** [comment]
LMAO
