### ISSUE TITLE
视频封面不变

### ISSUE THREAD

**Issue by caopeng000** [CarGuo/GSYVideoPlayer#2718]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在全屏情况下，点击暂停播放视频，然后拖动seek完成后，视频封面没有任何变化。DEMO没问题。为什么放到我的项目中就有问题了。大爱作者给我一个debug方向点吧。

目前已经debug到了
GSYVideoView
中的

updatePauseCover()
没发现任何异常。是有其他的点我没跟到吗
## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by caopeng000** [comment]
问题找到了。
  VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

我设置了这个东西就不能每次seek设置最新视频封面了。
但是seek会回弹

**Comment by CarGuo** [comment]
这个和封面没啥关系啊···
