### ISSUE TITLE
exo2内核能否直接修改useragent

### ISSUE THREAD

**Issue by jialovegirl** [CarGuo/GSYVideoPlayer#2719]
翻了以前的issues,没有发现可以设置的地方...

` PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        ExoSourceManager.setSkipSSLChain(true);`

在这里也没有方法可以直接设置ua
`ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                return null;
            }
        });`

thx~

**Comment by jialovegirl** [comment]
看源码里,最后
`private HttpURLConnection makeConnection(
            URL url,
            @HttpMethod int httpMethod,
            byte[] httpBody,
            long position,
            long length,
            boolean allowGzip,
            boolean followRedirects,
            Map<String, String> requestParameters)
            throws IOException {
...
connection.setRequestProperty("User-Agent", userAgent);`
好像userAgent没有可以修改的地方

**Comment by CarGuo** [comment]
是的，目前没支持

你可以通过 

ExoSourceManager.setExoMediaSourceInterceptListener 的 getMediaSource 来自定义暂时

**Comment by CarGuo** [comment]
代码已提交，下个版本正式支持

**Comment by jialovegirl** [comment]
thx~~
