### ISSUE TITLE
播放bilibili视频，加Header问题

### ISSUE THREAD

**Issue by moyaying** [CarGuo/GSYVideoPlayer#272]
http://cn-jszj-dx-v-07.acgvideo.com/vg3/2/b6/18438568-1-hd.mp4?expires=1497527100&platform=pc&ssig=EyWLVLDUlRNZecqxsDb7PA&oi=236121164&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2071029969

播放需要加头部：
Referer： http://www.bilibili.com/

我试了，但是就是播不出来，请问为什么？

**Comment by yueban** [comment]
好像是 bilibili 又进一步优化了防盗链机制
