### ISSUE TITLE
7.1.3  横屏视频由小屏切换全屏，会自动切回小屏

### ISSUE THREAD

**Issue by sans9212** [CarGuo/GSYVideoPlayer#2721]
gsyVideoOption
            .setIsTouchWiget(true)
            .setRotateViewAuto(false)
            .setLockLand(false)
            .setAutoFullWithSize(true)
            .setShowFullAnimation(false)
            .setNeedLockFull(true)
            .setUrl(path)
            .setCacheWithPlay(true)

按此代码 7.1.2及以前屏幕切换无此问题

**Comment by CarGuo** [comment]
demo 怎么复现？

**Comment by Leonw2229** [comment]
我自己新建项目测试高帧率和高码率的时候升级到7.1.3也会自动切换回小屏幕；跟7.1.2没有任何改动，只升级了版本号

**Comment by CarGuo** [comment]
麻烦提供下 demo 的复现步骤和测试 url

**Comment by Leonw2229** [comment]
> 麻烦提供下 demo 的复现步骤和测试 url

找到发生原因了，您可以使用demo中的WebDetail测试

```
    @Override
    public GSYVideoOptionBuilder getGSYVideoOptionBuilder() {
        String url = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
        //String url = "https://d131x7vzzf85jg.cloudfront.net/upload/documents/paper/b2/61/00/00/20160420_115018_b544.mp4";
        //增加封面。内置封面可参考SampleCoverVideo

        ImageView imageView = new ImageView(this);
        loadCover(imageView, url);
        return new GSYVideoOptionBuilder()
                .setThumbImageView(imageView)
                .setUrl(url)
                .setCacheWithPlay(false)
                .setRotateWithSystem(false)
                .setVideoTitle("测试视频")
                .setIsTouchWiget(true)
                .setRotateViewAuto(false)
                .setLockLand(false)
                .setShowFullAnimation(false)
                .setNeedLockFull(true);
    }
```
是因为我项目里面和我自己新建测试用的demo里面 **setLockLand()** 传的是true导致的，
另外想问一下这个方法具体的意思是什么，我看注释不是很明白。。。

**Comment by sans9212** [comment]
今天没事的时候好好调试了一下，这两个参数有关联
.setLockLand(false)
            .setAutoFullWithSize(true)   ---这个为true的时候就会出现

/-----------------------接下来是关键-------------------------/
             //直接横屏
            orientationUtils?.resolveByClick()
            //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
            detailPlayer?.startWindowFullscreen(this, true, true)
     
      这个两个方法都会走到下边的这个方法

   @SuppressLint("SourceLockedOrientationActivity")
    public void resolveByClick() {
        if (mIsLand == LAND_TYPE_NULL && mVideoPlayer != null && mVideoPlayer.isVerticalFullByVideoSize()) {
            return;
        }
        mClick = true;
        if (mIsLand == LAND_TYPE_NULL) {
            int request = mActivity.getRequestedOrientation();
            if (request == ActivityInfo.SCREEN_ORIENTATION_REVERSE_LANDSCAPE) {
                mScreenType = ActivityInfo.SCREEN_ORIENTATION_REVERSE_LANDSCAPE;
            } else {
                mScreenType = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
            }
            setRequestedOrientation(mScreenType);
            if (mVideoPlayer.getFullscreenButton() != null) {
                mVideoPlayer.getFullscreenButton().setImageResource(mVideoPlayer.getShrinkImageRes());
            }
            mIsLand = LAND_TYPE_NORMAL;
            mClickLand = false;
        } else {
            mScreenType = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
            if (mVideoPlayer.getFullscreenButton() != null) {
                if (mVideoPlayer.isIfCurrentIsFullscreen()) {
                    mVideoPlayer.getFullscreenButton().setImageResource(mVideoPlayer.getShrinkImageRes());
                } else {
                    mVideoPlayer.getFullscreenButton().setImageResource(mVideoPlayer.getEnlargeImageRes());
                }
            }
            mIsLand = LAND_TYPE_NULL;
            mClickPort = false;
        }

    }

      7.1.2 版本 这两个方法被调用   第一次  **mIsLand = 0**，然后**mIsLand = LAND_TYPE_NORMAL**，这时候mIsLand 的值被改变了，但是第二次 mIsLand 的值还是 0 ！！。
      然后我试了一下7.1.4版本  第一次 **mIsLand = 0**，然后**mIsLand = LAND_TYPE_NORMAL**， 第二次 **mIsLand = 1**  ,这个就导致  detailPlayer?.startWindowFullscreen(this, true, true)  走下来的时候直接返回竖屏了。


     个人建议  ：  orientationUtils?.resolveByClick() 这个方法被调用的时候就应该去判断视频该怎么显示  detailPlayer?.startWindowFullscreen(this, true, true)  不要再次去调用改变屏幕放向

     附上测试视频地址：https://www.mmicloud.com:65/20200606/9atFZd4k/index.m3u8
