### ISSUE TITLE
视频正在播放切换别的APP，再切换回来视频黑屏

### ISSUE THREAD

**Issue by Janky-Young** [CarGuo/GSYVideoPlayer#2722]
## 问题描述：

打开视频正在播放，程序进入后台，打开头条APP播放视频，拖动头条视频进度条。切换回来视频黑屏，状态编程CURRENT_STATE_NORMAL。

## 问题机型/系统：

真机 红米4 Android6.0

## GSY依赖版本

`implementation 'com.shuyu:GSYVideoPlayer:7.1.2'`

## Demo中的复现步骤

Demo中切换到后台再打开变成了demo首页，无法复现。

**Comment by CarGuo** [comment]
？？？？默认就是这样设计的啊，你可以设置 setReleaseWhenLossAudio 为false
