### ISSUE TITLE
旋转视频组件所在的根布局播放黑屏

### ISSUE THREAD

**Issue by CleverSJX** [CarGuo/GSYVideoPlayer#2724]
## 问题描述：
我是在电视上使用的APP,因为电视的方向是固定横屏的无法旋转,我现在手动把视频组件所在的根布局旋转90度,其他的组件旋转后都正常,但是视频组件有问题
第一种模式
```
 PlayerFactory.setPlayManager(SystemPlayerManager.class);
 GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
```
这种情况视频没有被旋转还是横屏播放,其他的图片组件的什么的都是正常被旋转了90度
![电视被旋转90度图片](https://user-images.githubusercontent.com/26036692/81946231-b146ea00-9631-11ea-80fe-f3bc906aa636.png)

第二种模式
```
 PlayerFactory.setPlayManager(SystemPlayerManager.class);
 GSYVideoType.setRenderType(GSYVideoType.TEXTURE);
```
这种情况在长虹的电视系统是5.1.1的系统上直接黑屏了,只有声音没画面,  正常情况下横屏播放这个视频是没有问题的

旋转的代码
```
 ViewGroup.LayoutParams layoutParams = rootLayout.getLayoutParams();
 int height = UIUtils.getScreenHeight(this);
 int width = UIUtils.getScreenWidth(this);
 layoutParams.width = height;
 layoutParams.height = width;
 rootLayout.setTranslationX(((width - height) / 2f));
 rootLayout.setTranslationY(-(width - height) / 2f);
 rootLayout.setRotation(-90f);
```

## 问题机型/系统：

真机 长虹电视    5.1.1

## GSY依赖版本

``` 
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3
implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3
```

**Comment by CarGuo** [comment]
？？？不是把所在的activity旋转？？？？

**Comment by CleverSJX** [comment]
> ？？？不是把所在的activity旋转？？？？

因为电视的方向在系统层级被固定了横屏,我无法旋转Activity的方向,只能通过旋转布局的方向来实现竖屏效果

**Comment by CarGuo** [comment]
不是很理解你的问题，为什么需旋转布局？？之前挺多tv开发他们也是正常使用就可以了

**Comment by CleverSJX** [comment]
> 不是很理解你的问题，为什么需旋转布局？？之前挺多tv开发他们也是正常使用就可以了

因为有些客户需要把电视竖着放,他们的视频是竖屏的,电视的activity是固定横屏的,所以只能旋转布局

**Comment by CarGuo** [comment]
那你重载改写 ijk 模式下的 onInfo 里的旋转角度试试

**Comment by CleverSJX** [comment]
> 那你重载改写 ijk 模式下的 onInfo 里的旋转角度试试

我在ijk模式下视频在6.0的小米tv上播放黑屏,所以才用的system
