### ISSUE TITLE
手机拍摄视频，角度旋转问题

### ISSUE THREAD

**Issue by bichao1986** [CarGuo/GSYVideoPlayer#2725]
## 问题描述：

我现在用的是StandardGSYVideoPlayer，现在问题是所有手机拍摄的视频，在TV上都出现了视频角度不对的问题，这个是否有方法可以直接调用？我看问题集锦里提到了这个问题，只是我在封装的库里没有看到，还请大佬给说一下具体的方法？或者给指出具体demo是那个？感谢
我看demo里的播放的视频角度是正常的，然后复制过来以后，在tv里就出现了播放视频角度异常的问题
## 问题机型/系统：
TV

**Comment by CarGuo** [comment]
请提供测试url

**Comment by bichao1986** [comment]
http://oss.littlehotspot.com/forscreen/resource/1589521557415.mp4
这个地址用chrome是没办法直接播放的，然后下载下来以后用暴风播放也是倒着的，但是用vlc是可以直接正常播放的

**Comment by CarGuo** [comment]
默认使用 ijk 内核

Video: hevc, 1 reference frame (hvc1 / 0x31637668), yuvj420p

Video Rotate Info 180

视频里带着的旋转信息就是  180


如下图所示，demo 的 detailplayer 显示如下，正常


![image](https://user-images.githubusercontent.com/10770362/82033115-d8072e00-96ce-11ea-9c71-139e6ec84e59.png)

**Comment by bichao1986** [comment]
现在是这样的，我刚测试了ijk的内核和系统内核，现在这个视频是倒过来的
我也用源码demo做了测试，视频角度都没问题
![765e0e334acc7b1895036521d7041c7](https://user-images.githubusercontent.com/11400852/82036526-9331c600-96d3-11ea-92cc-4df1b0683235.jpg)
是不是在什么地方需要做一下设置？
我这边现在用到的设置
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
GSYVideoType.enableMediaCodec();
这个设置应该跟视频角度没关系的吧

**Comment by CarGuo** [comment]
没有关系，你是说 demo 没有复现这个问题？
但是接入之后就反了？？？？
你后看到 onInfo 回调里旋转角度信息是否在 demo 和你的项目里一致？

**Comment by bichao1986** [comment]
我刚debug了一下代码，现在是这样的，用demo的话播放视频角度是正常的，没有任何问题，但是我移植到我自己项目里的代码以后，角度就不对了，然后我发现了一个问题，就是在GSYVideoBaseManager的onInfo方法里
if (listener() != null) {
                    listener().onInfo(what, extra);
                }
这一段代码被调用的时候what参数是3，extra参数是0，而且只被调用了两次，然后造成GSYVideoView的inInfo方法不会进
else if (what == getGSYVideoManager().getRotateInfoFlag()) {
            mRotate = extra;
            Debuger.printfLog("Video Rotate Info " + extra);
            if (mTextureView != null)
                mTextureView.setRotation(mRotate);
        }
这一个逻辑,所以导致视频角度不对
我在demo里debug的时候，发现这个listener().onInfo(what, extra);会被调用多次，其中有一次调用的extra参数会带有角度，所以demo里是没有问题的，是不是哪里代码我没设置对哪？

**Comment by CarGuo** [comment]
demo 不复现我也懵逼
