### ISSUE TITLE
列表详情切换demo中，在列表界面时，将应用切换到后台视频仍在播放

### ISSUE THREAD

**Issue by Acoee** [CarGuo/GSYVideoPlayer#2727]
问题描述：
列表详情切换demo中，在列表界面时，将应用切换到后台视频仍在播放。看代码似乎是属于待完善到代码，希望大神给个指示或者说是完善一下demo。另外在issues发现很多和我一样，希望能实现从详情返回列表后，列表能继续详情到播放进度并继续播放，不知道大神能不能在现有demo上满足一下这样的需求？

问题机型/系统：
机型无关

Demo中的复现步骤
Demo中的 SwitchListVideoActivity 打开后，在视频播放时，将应用切换到后台，视频仍然在继续播放。

**Comment by CarGuo** [comment]
1、demo 中在  SwitchListVideoActivity 中屏蔽了后台的代码，因为和切换时会有一点冲突，这个需要被你自己坐下判断，比如时点击的还是后台的。

2、列表能继续详情到播放进度并继续播放 https://github.com/CarGuo/GSYVideoPlayer/issues/1355
