### ISSUE TITLE
点击全屏按钮后显示异常

### ISSUE THREAD

**Issue by Mystery406** [CarGuo/GSYVideoPlayer#2728]
## 问题描述：
点击全屏按钮后显示异常
![QQ截图20200520090836](https://user-images.githubusercontent.com/17538405/82393628-946b4600-9a79-11ea-8f8b-1b0874fd32ff.png)
这可能是什么情况呢，直接把demo里的LandLayoutVideo搬过来的，布局里只改了左上角箭头的图标

## 问题机型/系统：
在华为P20 Android10.0上出现这个问题，在其他测试机型上倒是没有这个问题

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.4'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.4'

## Demo中的复现步骤
demo中未出现这个问题

**Comment by CarGuo** [comment]
demo 不复现你只能看 demo，一般就是 AndroidManifest 的配置或者 onConfigurationChanged
