### ISSUE TITLE
请问支持播放本地视频么，支持播放透明视频吗？

### ISSUE THREAD

**Issue by hezheng1978** [CarGuo/GSYVideoPlayer#2729]
## 问题描述：

请问支持播放本地视频么，支持播放透明视频吗？

## 问题机型/系统：

夜神模拟器 Android 4.2.2

**Comment by CarGuo** [comment]
本地播放支持，透明视频不理解，surface 容器在 Android 上不会透明的

**Comment by hezheng1978** [comment]
好的，谢谢，透明视频，就是想在不遮挡下层视图的情况下播放一段特效视频。

**Comment by CarGuo** [comment]
em·····我大概理解上应该是像看直播的时候弹出礼物动画那种。。。。。适合用 lottie 或者 svgplayuer 实现。
你说的上面播放视频还透视到下面的应用UI，不现实，那还不如直接一个 lottie 上层播放。

**Comment by hezheng1978** [comment]
是的，目前是使用svga方式来实现了，谢谢啦！
