### ISSUE TITLE
你好，issue你手动去清理，其实并不能共同进步

### ISSUE THREAD

**Issue by panyancen** [CarGuo/GSYVideoPlayer#2731]
提个issue，你可以不回答，但是可以给大家做一下讨论，共同分析问题，一去搜索问题什么都没有，issue看似少，其实这么做并不能帮助大家。

**Comment by CarGuo** [comment]
其实，从 issue上说，没有后续回复的我就当做没用关闭了。
其次，大部分的 issue 都是可以通过源码和文档解决，关闭只是因为我不想做人肉搜索工具。
再者吧，我更希望提pr的，而不是问接口的，有用有意义的issue其实我都回复了。
