### ISSUE TITLE
基于AndroidVideoCache实现本地代理对M3U8视频格式的缓存处理

### ISSUE THREAD

**Issue by missu263** [CarGuo/GSYVideoPlayer#2735]
求教一个问题：
【背景】：基于AndroidVideoCache实现本地代理对M3U8视频格式的缓存处理，就是本地会预下载第一个ts的文件，实现播放器（IJKPlayer）的秒开
【实现】：播放器设置的播放URL为 127.0.0.1/https://xxxx.m3u8，本地代理去请求https://xxxx.m3u8拿到playlist，这个时候会将playlist的每个ts片的地址也改为127.0.0.1/https://xxxx.ts，然后将这部分数据通过连接播放器的socket返回给播放器，后续本地代理会再收到127.0.0.1/https://xxxx.ts的请求
【碰到的问题】：上述实现过程还只是本地代理发送真正的请求，然后把网络流的数据通过播放器连接来的socket原封不动的返回。但是实际的播放过程中，发现播放器发起的ts请求，不是从第一个ts片开始请求播放（随机的）。这导致播放就乱了，而且最后播放器出现一直缓冲。
这里面会不会是因为播放器内部收到的http header不正确导致的啊，因为代理写入的response header为：
"HTTP/1.1 200 OK\n" + "Accept-Ranges: bytes\n"
                + format("Content-Length: %d\n", getContentLength(connection)) + "Connection: keep-alive\n"
                + format("Date: %s",gmtFormat.format(new Date()) + "\n")
                + format("Content-Type: %s\n", "application/octet-stream") + "\n"; // headers end

**Comment by CarGuo** [comment]
AndroidVideoCache 实现本地代理对 M3U8 缓存支持不好做，因为这期间还涉及到 seek 或者多线程加速下载 m3u8 分片等的问题。

你可以看看 exo 在 m3u8 的缓存支持逻辑

**Comment by missu263** [comment]
找到原因了，是因为在对m3u8的playlist修改之后，没有修改response header中的content-length导致的

顺便问一下大神，对于IJK播放器的起播速度优化，有什么建议吗？
我现在的实现，就是播放器还是单例，然后提前去下载m3u8的第一个ts数据，缓存在SDcard上，然后用播放器请求一个ts的时候，直接就返回咯。

**Comment by missu263** [comment]
ijkplayer 起播需要多大的buffer数据啊

**Comment by CarGuo** [comment]
ijkplayer 可以看配置的 option ，参考下问题集锦

**Comment by missu263** [comment]
好的 感谢回答
