### ISSUE TITLE
seek速度太慢了

### ISSUE THREAD

**Issue by 951AB159BA** [CarGuo/GSYVideoPlayer#2736]
本地视频，在调用seek后，转圈5到6秒才能播放。其他软件的播放器seek本地视频不用1秒就能立刻播放出画面了。建议优化下。速度太慢了，理论本地视频不是网上的不用经历下载，应该很快才对。

**Comment by CarGuo** [comment]
和帧率和编码有关系，试试切换到  PlayerFactory.setPlayManager(Exo2PlayerManager.class); 

或者看看问题集锦

可以尝试以下设置
```
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by 951AB159BA** [comment]
> 
> 
> 和帧率和编码有关系，试试切换到 PlayerFactory.setPlayManager(Exo2PlayerManager.class);
> 
> 或者看看问题集锦
> 
> 可以尝试以下设置
> 
> ```
> VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
> List<VideoOptionModel> list = new ArrayList<>();
> list.add(videoOptionModel);
> GSYVideoManager.instance().setOptionModelList(list);
> ```

这个快慢是跟缓存应该没关系吧。我目前没有用缓存。我试了你上述代码，是快了点，但是不太稳定，有时候seek到某个位置1秒立刻播放，有时4秒左右才能播放。

**Comment by CarGuo** [comment]
正常
