### ISSUE TITLE
请问下如何重写或继承ProxyCacheManager并且实现调用？

### ISSUE THREAD

**Issue by 951AB159BA** [CarGuo/GSYVideoPlayer#2739]
如题，要做的是自定义缓存实现，请问把我把ProxyCacheManager复制过来了，改了下，弄成新的cache，请问怎么在代码中调用。麻烦回答下，谢谢！

**Comment by CarGuo** [comment]
简单的话是

XXXX implements ICacheManager 

CacheFactory.setCacheManager(xxxxxCacheManager.class);


复杂的话你需要从自定义 IPlayerManager 开始

**Comment by 951AB159BA** [comment]
> 
> 
> 简单的话是
> 
> XXXX implements ICacheManager
> 
> CacheFactory.setCacheManager(xxxxxCacheManager.class);
> 
> 复杂的话你需要从自定义 IPlayerManager 开始

好的，谢谢！
