### ISSUE TITLE
在播放列表添加标题文字怎么添加错乱问题。

### ISSUE THREAD

**Issue by wcnmtx** [CarGuo/GSYVideoPlayer#274]
使用的是RecyclerView2Activity  我用    RecyclerItemViewHolder 用  listVideoUtil.getGsyVideoPlayer().getTitleTextView().setText(); 这个方法然后title 标题文字错乱了。

**Comment by CarGuo** [comment]
listVideoUtil应该是单例模式的，每次播放才加入到item中，所以不是很明白title错误是什么？

**Comment by wcnmtx** [comment]
我把20条ArrayList<String>模拟数据。换成用 ArrayList<VideoModel> 这里添加真实数据 。VideoModel 定义 一个videoUrl和videoName 两个参数 ，视屏列表能正常显示。 但是对应的标题错乱了。我看到你添加视屏用了一个TAG 。解决问题，但是title 并没有。

**Comment by wcnmtx** [comment]
简单点来说，我就是想往  视屏列表    里面给每个视屏添加title ，但是title 错乱，没有对应 
比如 ABCD 视屏4个视屏 对应 abcd 标题。 实则对应可能是 aaab

**Comment by CarGuo** [comment]
如果你用的listVideoUtil模式，那么title不在视频端处理啊，是自己recycler处理的吧？

**Comment by wcnmtx** [comment]
对我用的是 listVideoUtil 模式，我这样貌似还是没有,
final String title[] = {"111111", "22222222", "3333333333"};
        listItemBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                getRecyclerBaseAdapter().notifyDataSetChanged();
                listVideoUtil.setPlayPositionAndTag(position, TAG);
                listVideoUtil.setObjects(title);
                listVideoUtil.startPlay(videoModel.getVideo());
            }
        });

**Comment by CarGuo** [comment]
sorry，还真的是ListVideoUtil的问题，你是依赖了源码嘛？在下图下面增加这个！

![wechatimg84](https://user-images.githubusercontent.com/10770362/27312553-a2e8f6e4-559b-11e7-8a87-f5a202ddaa9e.jpeg)

**Comment by wcnmtx** [comment]
恩.这样取值的话 每次还是第一个.我直接定义一个了String  title;  写了get set 方法 
 private String title;  

       if (title != null && !TextUtils.isEmpty(title)) {
              gsyVideoPlayer.getTitleTextView().setText(title);
       }

然后    listVideoUtil.setTitle(videoModel.getvideoName()); 
  gsyVideoPlayer.getTitleTextView().setVisibility(View.VISIBLE);
这样也可以.亲测有效.谢啦.
