### ISSUE TITLE
在线播放mp4失败，下载后能播放，复制地址用浏览器可以直接播放

### ISSUE THREAD

**Issue by tangxianqiang** [CarGuo/GSYVideoPlayer#2741]
05-27 14:21:26.311 5535-6683/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
05-27 14:21:26.321 5535-6684/cn.ctnma.telemedicinecloud.debug I/HttpProxyCacheDebuger: Opened connections: 0
05-27 14:21:26.321 5535-6683/cn.ctnma.telemedicinecloud.debug I/HttpProxyCacheDebuger: Ping response: `ping ok`, pinged? true
05-27 14:21:26.321 5535-5535/cn.ctnma.telemedicinecloud.debug I/HttpProxyCacheDebuger: Proxy cache server started. Is it alive? true
05-27 14:21:26.331 5535-6683/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
05-27 14:21:26.331 5535-6683/cn.ctnma.telemedicinecloud.debug I/HttpProxyCacheDebuger: Ping response: `ping ok`, pinged? true
05-27 14:21:26.331 5535-6685/cn.ctnma.telemedicinecloud.debug I/HttpProxyCacheDebuger: Opened connections: 0
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug V/IJKMEDIA: setDataSource: path http://127.0.0.1:38762/http%3A%2F%2F10.18.33.220%3A8213%2Fycpx%2FPath%2F1590547396094%2F%E4%BA%BA%E4%BD%93%E8%A7%A3%E5%89%96%E8%AE%B2%E5%BA%A7.mp4
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:38762/http%3A%2F%2F10.18.33.220%3A8213%2Fycpx%2FPath%2F1590547396094%2F%E4%BA%BA%E4%BD%93%E8%A7%A3%E5%89%96%E8%AE%B2%E5%BA%A7.mp4")
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:38762/http%3A%2F%2F10.18.33.220%3A8213%2Fycpx%2FPath%2F1590547396094%2F%E4%BA%BA%E4%BD%93%E8%A7%A3%E5%89%96%E8%AE%B2%E5%BA%A7.mp4")=0
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_setOptionLong
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_setLoopCount
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(1)
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: moncleanup
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_setVolume
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ffpipeline_set_volume
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_prepareAsync
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_prepare_async()
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: ===== versions =====
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: ijkplayer    : k0.8.8
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: FFmpeg       : ff3.4--ijk0.8.7--20180103--001
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: libavutil    : 55.78.100
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: libavcodec   : 57.107.100
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: libavformat  : 57.83.100
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: libswscale   : 4.8.100
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: libswresample: 2.9.100
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: ===== options =====
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: player-opts : loop                         = 1
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: format-opts : ijkapplication               = -1396764720
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: format-opts : ijkiomanager                 = -1392655792
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: ===================
05-27 14:21:26.331 5535-6686/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: SDL_RunThread: [6686] ff_msg_loop
05-27 14:21:26.331 5535-6686/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: message_loop
05-27 14:21:26.331 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_prepare_async()=0
05-27 14:21:26.331 5535-6687/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: SDL_RunThread: [6687] ff_vout
05-27 14:21:26.331 5535-6688/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: SDL_RunThread: [6688] ff_read
05-27 14:21:26.331 5535-6686/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: FFP_MSG_FLUSH:
05-27 14:21:26.331 5535-6688/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: Opening 'http://127.0.0.1:38762/http%3A%2F%2F10.18.33.220%3A8213%2Fycpx%2FPath%2F1590547396094%2F%E4%BA%BA%E4%BD%93%E8%A7%A3%E5%89%96%E8%AE%B2%E5%BA%A7.mp4' for reading
05-27 14:21:26.331 5535-6688/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
05-27 14:21:26.331 5535-6688/cn.ctnma.telemedicinecloud.debug I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
05-27 14:21:26.331 5535-6688/cn.ctnma.telemedicinecloud.debug I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
05-27 14:21:26.341 5535-6688/cn.ctnma.telemedicinecloud.debug I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
05-27 14:21:26.341 5535-6688/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: request: GET /http%3A%2F%2F10.18.33.220%3A8213%2Fycpx%2FPath%2F1590547396094%2F%E4%BA%BA%E4%BD%93%E8%A7%A3%E5%89%96%E8%AE%B2%E5%BA%A7.mp4 HTTP/1.1
    User-Agent: Lavf/57.83.100
    Accept: */*
    Range: bytes=0-
    Connection: close
    Host: 127.0.0.1:38762
    Icy-MetaData: 1
05-27 14:21:26.351 5535-6689/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheDebuger: Error fetching info from http://10.18.33.220:8213/ycpx/Path/1590547396094/人体解剖讲座.mp4
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err: java.io.FileNotFoundException: http://10.18.33.220:8213/ycpx/Path/1590547396094/人体解剖讲座.mp4
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:147)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpUrlSource.getMime(HttpUrlSource.java:250)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:60)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:40)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:230)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:51)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:332)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-27 14:21:26.431 5535-6689/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheDebuger: Error fetching info from http://10.18.33.220:8213/ycpx/Path/1590547396094/人体解剖讲座.mp4
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err: java.io.FileNotFoundException: http://10.18.33.220:8213/ycpx/Path/1590547396094/人体解剖讲座.mp4
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:147)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:77)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:62)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:40)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:230)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:51)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:332)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-27 14:21:26.531 5535-6689/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheDebuger: Error fetching info from http://10.18.33.220:8213/ycpx/Path/1590547396094/人体解剖讲座.mp4
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err: java.io.FileNotFoundException: http://10.18.33.220:8213/ycpx/Path/1590547396094/人体解剖讲座.mp4
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:147)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:77)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCache.isUseCache(HttpProxyCache.java:52)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:44)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:230)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:51)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:332)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-27 14:21:26.591 5535-6689/cn.ctnma.telemedicinecloud.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-27 14:21:26.591 5535-6690/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
05-27 14:21:26.651 5535-6690/cn.ctnma.telemedicinecloud.debug E/ProxyCache error: Error opening connection for http://10.18.33.220:8213/ycpx/Path/1590547396094/人体解剖讲座.mp4 with offset 0. Version: 7.1.4
05-27 14:21:26.651 5535-6689/cn.ctnma.telemedicinecloud.debug E/HttpProxyCacheServer error: Error processing request. Version: 7.1.4
05-27 14:21:26.651 5535-6689/cn.ctnma.telemedicinecloud.debug I/HttpProxyCacheDebuger: Opened connections: 0
05-27 14:21:26.651 5535-6688/cn.ctnma.telemedicinecloud.debug I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
05-27 14:21:26.651 5535-6688/cn.ctnma.telemedicinecloud.debug E/IJKMEDIA: http://127.0.0.1:38762/http%3A%2F%2F10.18.33.220%3A8213%2Fycpx%2FPath%2F1590547396094%2F%E4%BA%BA%E4%BD%93%E8%A7%A3%E5%89%96%E8%AE%B2%E5%BA%A7.mp4: End of file
05-27 14:21:26.651 5535-6688/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6688]
05-27 14:21:26.651 5535-6686/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: FFP_MSG_ERROR: 0
05-27 14:21:26.651 5535-5535/cn.ctnma.telemedicinecloud.debug E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
05-27 14:21:26.651 5535-6691/cn.ctnma.telemedicinecloud.debug W/Last modified date {} is not set for file {}: Wed May 27 14:21:26 GMT+08:00 2020
    /storage/emulated/0/Android/data/cn.ctnma.telemedicinecloud.debug/cache/video-cache/b945a8874b804d1186d7da11837e9991.mp4.download
05-27 14:21:26.651 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_release
05-27 14:21:26.651 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
05-27 14:21:26.651 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ffpipeline_set_surface()
05-27 14:21:26.651 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
05-27 14:21:26.651 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_shutdown_l()
05-27 14:21:26.651 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: wait for read_tid
05-27 14:21:26.651 5535-6686/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: message_loop exit
05-27 14:21:26.651 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: wait for video_refresh_tid
05-27 14:21:26.651 5535-6686/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6686]
05-27 14:21:26.661 5535-6687/cn.ctnma.telemedicinecloud.debug I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6687]
05-27 14:21:26.661 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_shutdown_l()=void
05-27 14:21:26.661 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_dec_ref(): ref=0
05-27 14:21:26.661 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_shutdown_l()
05-27 14:21:26.661 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: ijkmp_shutdown_l()=void
05-27 14:21:26.661 5535-5535/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_setVolume
05-27 14:21:29.301 5535-5573/cn.ctnma.telemedicinecloud.debug I/art: Explicit concurrent mark sweep GC freed 34207(1969KB) AllocSpace objects, 18(3MB) LOS objects, 40% free, 18MB/30MB, paused 1.549ms total 108.405ms
05-27 14:21:29.311 5535-5561/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_native_finalize
05-27 14:21:29.311 5535-5561/cn.ctnma.telemedicinecloud.debug D/IJKMEDIA: IjkMediaPlayer_release

**Comment by tangxianqiang** [comment]
补充：
vivo x7 5.1.1  会出现这种情况：有些mp4视频可以在线播放 ，有些不能，需要先下载后播放，提示如上；
Android 10 ，小米则都可以在线播放（相同的播放地址）

**Comment by CarGuo** [comment]
中文url请先格式化后再传入

**Comment by tangxianqiang** [comment]
已解决，谢谢，这个我觉得可以给基础差的人留下提示。。。
