### ISSUE TITLE
全屏与恢复Activity方向的问题

### ISSUE THREAD

**Issue by RenJie233** [CarGuo/GSYVideoPlayer#2742]
## 问题描述：

Activity在manifest中设置强制横屏，初始方向正常，在Activity中点击全屏按钮进入全屏模式，再次点击推出全屏的时候，Activity变成竖屏了，这个问题怎么解决？

## 问题机型/系统：

模拟机 Pixel XL API 27

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.4'

**Comment by CarGuo** [comment]
看demo，并且配置manifest

**Comment by RenJie233** [comment]
manifest设置了，screenOrientation的值设的是sensorLandscape，demo我看值都是portrait，没有横屏的啊

**Comment by CarGuo** [comment]
你是电视的？？？
如果是这样你需要重写 onBackFullscreen 方法，参考 GSYBaseVideoPlayer 源码里的

**Comment by RenJie233** [comment]
是平板的，重写resolveNormalVideoShow()这个方法么，是不是在这里设置屏幕方向就行了

**Comment by CarGuo** [comment]
重写 onBackFullscreen 方法，参考 GSYBaseVideoPlayer 源码里的

**Comment by RenJie233** [comment]
好的

**Comment by 382202771** [comment]
你好  这个应该怎么改了  退出全屏时候就能保持原来的横屏了 求助

**Comment by CarGuo** [comment]
@382202771 重写 onBackFullscreen 方法，去掉旋转的逻辑啊····
