### ISSUE TITLE
在播放音频的时候使用流量播放会弹窗，点继续播放后播放失败

### ISSUE THREAD

**Issue by Veryed-VS** [CarGuo/GSYVideoPlayer#2744]
在播放音频的时候使用流量播放会弹窗，点继续播放后播放失败，无法继续播放。使用WIFI连接无问题。

**Comment by CarGuo** [comment]
demo 的音频例子复现？

**Comment by Veryed-VS** [comment]
是的，修改demo的音频例子URL为网络音乐：
private String getUrl() {
//        String url = "android.resource://" + getPackageName() + "/" + R.raw.test3;
//        String url  = "http://cdn.yyupload.com/down/1358595/music/%E5%8F%A4%E5%85%B8%E6%B8%85%E9%9F%B3/%E7%AC%9B%E5%AD%90%E6%BC%94%E5%A5%8F%E5%AE%B6-%E9%99%86%E6%98%A5%E9%BE%84%E4%B8%93%E8%BE%91/09.%E6%B1%9F%E5%8D%97%E6%98%A5.mp3";
        String url = "http://cdn.yyupload.com/down/1358595/music/%E5%87%A1%E6%AD%8C%E5%92%8F%E6%B3%95/%E9%BB%91%E9%B8%AD%E5%AD%90%E5%90%88%E5%94%B1%E5%9B%A2/%E9%BB%91%E9%B8%AD%E5%AD%90%20-%20%E5%A4%A7%E6%82%B2%E5%92%92.mp3";
        //注意，用ijk模式播放raw视频，这个必须打开
        GSYVideoManager.instance().enableRawPlay(getApplicationContext());

        ///exo raw 支持
        //String url =  RawResourceDataSource.buildRawResourceUri(R.raw.test).toString();

        return url;
    }

具体表现:wifi播放正常，移动网络无法播放。
.setNeedShowWifiTip(false)  取消弹窗。仍然无法播放。
已验证：链接是正常的，移动网络正常。

**Comment by Veryed-VS** [comment]
> demo 的音频例子复现？
好像要回复你这边才会有提醒。再回复一下。

**Comment by Veryed-VS** [comment]
不好意思。发现切换内核就好了。这个问题仅在ikj内核出现。EXO内核没问题。
