### ISSUE TITLE
在使用SystemPlayerManager为内核的时候，activity跳转导致视频黑屏

### ISSUE THREAD

**Issue by fldevil** [CarGuo/GSYVideoPlayer#2745]
## 问题描述：

在使用SystemPlayerManager为内核的时候，在视频activity中打开一个新的activity，在返回，视频界面黑屏切不能播放

## 问题机型/系统：

安卓主板 RK 3288 Android5.1

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'
implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.4'

## Demo中的复现步骤

Demo中GSYApplication设置PlayerFactory.setPlayManager(SystemPlayerManager.class); 打开DetailListPlayer界面进行视频播放，然后home键返回桌面，在重新进入应用，视频黑屏切无法播放

**Comment by CarGuo** [comment]
测试正常 ，如下图

![5ed0808f68f7f_5ed080904620e](https://user-images.githubusercontent.com/10770362/83217864-523fb400-a19f-11ea-887b-ef77bbfa5afb.gif)

**Comment by fldevil** [comment]
别通过直接点击图标的方式进入，通过任务菜单的方式重新进入app呢？我这边很容易复现出来呢

**Comment by CarGuo** [comment]
一样，试了好几次
