### ISSUE TITLE
使用demo 列表视频播放，点击播放后，快速滚动列表有卡顿，如何解决？

### ISSUE THREAD

**Issue by kulong51** [CarGuo/GSYVideoPlayer#2746]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
demo试了没特别的感觉，卡顿一般就是释放的时候。

**Comment by liyuhaolol** [comment]
> demo试了没特别的感觉，卡顿一般就是释放的时候。

您好，看到了一样的问题，这里也想跟您反馈一下，我对比了饺子视频的demo和您的框架的demo，在列表页滑动的时候，无论是出屏幕停止播放，还是切换小窗。您的demo确实会有肉眼可见的卡顿，会明显感受的不跟手。这个问题，饺子视频的框架是完全感觉不到的，感觉您可以在释放视频这部分逻辑下手看看是不是造成了线程阻塞。
我的测试设备是小米8

**Comment by BananaHuo** [comment]
华为mate20 pro 我用viewpager2编码抖音列表也出现了卡顿的情况，是偶尔出现，非常偶尔，如果播放的时候view.post{play}播放滑动界面卡顿情况减少，但是还是会出现卡顿，不知道为啥
