### ISSUE TITLE
从横屏按返回键切换到竖屏后，再按返回键退出页面，声音还在播放

### ISSUE THREAD

**Issue by 951AB159BA** [CarGuo/GSYVideoPlayer#2748]
1.设置了setautoFullAnimation为true之后，从横屏到竖屏到退出。横屏返回和竖屏返回这几个按钮快速频繁点击，直到退出页面，发现声音仍在播放的问题出现概率较高。设置了false之后目前没发现问题。
2.还有一次偶现，也是横屏到竖屏到退出，再按返回键还有声音。不清楚如何出现，但退出来后我看到上个页面被重新创建了，目测可能是播放页面被回收了，导致退出播放页面还有声音在。
麻烦作者留意下退出页面声音还在的问题，多留意和实验几下，第二点比较难出现，不过也出现了2次。

**Comment by CarGuo** [comment]
demo可以复现？
