### ISSUE TITLE
rtmp直播流有画面没声音

### ISSUE THREAD

**Issue by sunbest110** [CarGuo/GSYVideoPlayer#2750]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放直播流rtmp的时候，只有画面没有声音

## 问题机型/系统：

例如  华为，小米

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

问题代码：(如果有)
 /**此中内容：优化加载速度，降低延迟*/
        List<VideoOptionModel> list = new ArrayList<>();
        VideoOptionModel videoOptionModel;
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "videotoolbox", "1");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
        list.add(videoOptionModel);
//        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
//        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
        list.add(videoOptionModel);
        //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);//https://link.jianshu.com/?t=http%3A%2F%2Fivi.bupt.edu.cn%2Fhls%2Fcctv5phd.m3u8
        //播放m3u8时候  cacheWithPlay设为false
      //  PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        videoPlayer.setUp(url, type.equals("rtmp"), "");
        videoPlayer.setShowFullAnimation(false);

## 问题log（如果有）
协议是H.264 ACC在电脑端vlc上有声音，我尝试切换 exo模式也不行。

**Comment by sunbest110** [comment]
rtmp://58.200.131.2:1935/livetv/hunantv 这个地址exo模式有声音，rtmp://ctc-zhenjiang04.rt1.gensee.com/5324e855b28b453db7b0ec226598b76c_171391_0_8801038305_1591077225_205d01b8/video 这个地址那个模式都没声音

**Comment by sunbest110** [comment]
我这边参考楼主的自定义so，解决了

**Comment by CarGuo** [comment]
@sunbest110 可以可以

**Comment by cloudmist** [comment]
> 我这边参考楼主的自定义so，解决了

大佬，你还有编译出来的so文件吗

**Comment by Ahuangshang** [comment]
@sunbest110 请问你用的哪个so库
