### ISSUE TITLE
demo的列表页滑动关闭，切换小窗会明显感觉到卡顿

### ISSUE THREAD

**Issue by liyuhaolol** [CarGuo/GSYVideoPlayer#2753]
## 问题描述：

您的demo在列表页的滑动关闭，滑动切换小窗的逻辑，会感觉到非常明显的卡顿

## 问题机型/系统：

真机，小米8

## GSY依赖版本

demo就假设为最新版

## Demo中的复现步骤

简单列表页1，简单列表页2，当播放中，滑动列表，将视频滑动出屏幕那一瞬间，会有肉眼和手都能感觉到的卡顿。我觉得这应该是释放视频造成的意外的线程阻塞？

这种场景，在饺子视频的demo中，不会有一点卡顿的问题。
感觉是个问题，故反馈

**Comment by CarGuo** [comment]
你切换到其他内核模式试试

**Comment by liyuhaolol** [comment]
> 你切换到其他内核模式试试

今天专门拿demo各个内核切换，测试了一下，就在把正在播放的item移出屏幕那一瞬间，可以感觉到明显的卡一下。

**Comment by CarGuo** [comment]
奇怪，我这边没有很明显的感觉，难道是因为机器原因？？

**Comment by liyuhaolol** [comment]
> 奇怪，我这边没有很明显的感觉，难道是因为机器原因？？

跟机器无关，我现在用模拟器来演示一下吧，因为手机不在身上，为了可视化表达这个问题，你可以进去开发者选项->监控->HWUI呈现模式分析->在屏幕上显示为条形图。
图标里，如果超过红线，那么说明系统存在卡顿，超出越多，卡顿越明显。
这是GSY的demo，简单列表1，将播放的item滑出屏幕的一瞬间显示的图
<div><img src='https://wx1.sinaimg.cn/mw1024/4369f9c9ly1gftxkqrnalj20gb0wy4mf.jpg' width="360px"/></div>
可以看到滑出屏幕的一瞬间，条状图超过红线非常多，可以感到明显的顿挫感，不跟手。
这是Jiaozi的demo的列表页滑出屏幕的图
<div><img src='https://wx3.sinaimg.cn/mw1024/4369f9c9ly1gftxkqos2ej20gg0x3dzp.jpg' width="360px"/></div>
Jiaozi的demo滑出后，就超过红线一点点，几乎感觉不到卡顿，所以通过可视化来说，GSY的demo确实存在卡顿。可能是您这边感知不明显而已，我翻了翻记录，也不止我一个人有说过列表页滑动卡顿的问题吧。所以感觉这确实是个BUG。

**Comment by CarGuo** [comment]
这个应该有一部分是 Cover ImageView 造成的，可以试试新提交的  RecyclerViewActivity

**Comment by CarGuo** [comment]
如下图所示，修改后的逻辑看起来 release 之后也没有太多耗时夸张的卡顿问题。

![image](https://user-images.githubusercontent.com/10770362/85259174-257b7580-b49b-11ea-8ce3-a2237c90a642.png)

![image](https://user-images.githubusercontent.com/10770362/85259472-b6eae780-b49b-11ea-9071-c230f4e28097.png)

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/85260900-fe727300-b49d-11ea-9354-a35a364985c0.png)


![image](https://user-images.githubusercontent.com/10770362/85261174-5f01b000-b49e-11ea-8cda-fa8d6a817568.png)


从内核上看，exo 的平均 release 耗时会好一些。

**Comment by liyuhaolol** [comment]
我这里测试了最新的demo了，确实有非常大的改进，基本感知不到卡顿的问题了。虽然细细的拖动，还是能有顿一下的感觉，exo的效果确实最好，基本感知不到卡顿，ijk，系统内核还是稍稍微微有一点感知。不过相较于以前，提升很大了。期待您的下一个版本更新。

**Comment by CarGuo** [comment]
这个应该不用版本发布，因为改的是 demo 里的演示代码而已～～

**Comment by dtboy1995** [comment]
> 我这里测试了最新的demo了，确实有非常大的改进，基本感知不到卡顿的问题了。虽然细细的拖动，还是能有顿一下的感觉，exo的效果确实最好，基本感知不到卡顿，ijk，系统内核还是稍稍微微有一点感知。不过相较于以前，提升很大了。期待您的下一个版本更新。

新版任然卡顿啊
