### ISSUE TITLE
GSYVideoManager.instance().setOptionModelList()使用问题

### ISSUE THREAD

**Issue by CandyYoung** [CarGuo/GSYVideoPlayer#2754]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

GSYVideoManager.instance().setOptionModelList()似乎不起作用。

想知道这个方法的作用范围和调用时机

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setOptionModelList() 只在播放前设置有效，全局，然后只对 ijk 模式有效果。

**Comment by CandyYoung** [comment]
尝试使用ijk模式播放一个h265的视频，画面卡顿很严重，而用system或exo2则可以流畅播放。
ijk模式下已enableMediaCodec和enableMediaCodecTexture；也已根据根据以往issue记录使用了dropframe 50，发现并没有改善。
视频信息：
编解码器: MPEG-H Part2/HEVC (H.265) (hvc1)
视频分辨率: 1920x1080
帧率: 30
已解码格式: Planar 4:2:0 YUV

如果想继续使用ijk以兼容更多的视频格式和较低的版本兼容性（兼容到14）的话，作者有什么建议吗？

**Comment by CarGuo** [comment]
因为码率太高，不同机器CPU的软解码能力不够所以h265可能会出现这种情况的。并且你帧率才30，drop 50没用的。

你可以参考首页链接自己编译so，修改配置和ffplay逻辑。
