### ISSUE TITLE
demo上的列表详情页面进入详情页面出现有声无图现象

### ISSUE THREAD

**Issue by kulong51** [CarGuo/GSYVideoPlayer#2758]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 oppor9sk Androi6.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## Demo中的复现步骤

Demo中的SwitchDetailActivity页面打开后会出现这个问题。

**Comment by CarGuo** [comment]
我这边测试好像没复现这个问题，出现这个问题一般是 surface 没成功创建。可以 debug 下是不是 sufurce 没有成功被创建然后设置到 playerManager 里

**Comment by kulong51** [comment]
> 我这边测试好像没复现这个问题，出现这个问题一般是 surface 没成功创建。可以 debug 下是不是 sufurce 没有成功被创建然后设置到 playerManager 里

改成这样就可以了，mVideoPlayer.postDelayed(() -> mVideoPlayer.setSurfaceToPlay(), 500);

**Comment by CarGuo** [comment]
@kulong51 可能是 surface 的构建时机兼容问题～ good ！
