### ISSUE TITLE
调用onVideoResume  从头开始播放

### ISSUE THREAD

**Issue by Ysrfengnull** [CarGuo/GSYVideoPlayer#2759]
## 问题描述：
Demo 小于20S的视频 在手动你调用暂停后，再次调用onVideoResume  从头开始播放没法续播，

超过1分钟的视频 调用onVideoResume  ，续播时间都会后退2s开始播放

**Comment by CarGuo** [comment]
Ijk默认内核的话，参考问题集锦的seek
