### ISSUE TITLE
老版本GsyVideoPlayer类中的starturl（url）方法被什么替换了

### ISSUE THREAD

**Issue by plmmanwu** [CarGuo/GSYVideoPlayer#276]
老版本GsyVideoPlayer类中的starturl（url）方法被什么替换了，现在手动调用什么方法

**Comment by plmmanwu** [comment]
复制recyclerviewdemo的代码，不知道为什么不能点击播放，必须要手动调用播放逻辑，以前用的是starturl（url），新版本这个方法不存在了，很纳闷

**Comment by CarGuo** [comment]
你说的老版本是哪个版本？印象中没有starturl这接口哟

**Comment by plmmanwu** [comment]
164的，说错了，是startVideo(String url)

**Comment by plmmanwu** [comment]
调用startPlayLogic()方法，只能播放，暂停不了。再次点击只能重头开始

**Comment by CarGuo** [comment]
startVideo??没找到吖，1.6.4的哪个类？哪行？

**Comment by plmmanwu** [comment]
类GSYVideoPlayer 1306行

**Comment by plmmanwu** [comment]
public void startVideo(String url){
        mUrl=url;
        if (TextUtils.isEmpty(mUrl)) {
            Toast.makeText(getContext(), getResources().getString(R.string.no_url), Toast.LENGTH_SHORT).show();
            return;
        }
        if (mCurrentState == CURRENT_STATE_NORMAL || mCurrentState == CURRENT_STATE_ERROR) {
            if (!mUrl.startsWith("file") && !CommonUtil.isWifiConnected(getContext())
                    && mNeedShowWifiTip) {
                showWifiDialog();
                return;
            }
            startButtonLogic();
        } else if (mCurrentState == CURRENT_STATE_PLAYING) {
            GSYVideoManager.instance().getMediaPlayer().pause();
            setStateAndUi(CURRENT_STATE_PAUSE);
            if (mVideoAllCallBack != null && isCurrentMediaListener()) {
                if (mIfCurrentIsFullscreen) {
                    Debuger.printfLog("onClickStopFullscreen");
                    mVideoAllCallBack.onClickStopFullscreen(mUrl, mObjects);
                } else {
                    Debuger.printfLog("onClickStop");
                    mVideoAllCallBack.onClickStop(mUrl, mObjects);
                }
            }
        } else if (mCurrentState == CURRENT_STATE_PAUSE) {
            if (mVideoAllCallBack != null && isCurrentMediaListener()) {
                if (mIfCurrentIsFullscreen) {
                    Debuger.printfLog("onClickResumeFullscreen");
                    mVideoAllCallBack.onClickResumeFullscreen(mUrl, mObjects);
                } else {
                    Debuger.printfLog("onClickResume");
                    mVideoAllCallBack.onClickResume(mUrl, mObjects);
                }
            }
            GSYVideoManager.instance().getMediaPlayer().start();
            setStateAndUi(CURRENT_STATE_PLAYING);
        } else if (mCurrentState == CURRENT_STATE_AUTO_COMPLETE) {
            startButtonLogic();
        }
    }

**Comment by CarGuo** [comment]
我看了下git的log下，没有startVideo这样的方法哟，在1.6.4

**Comment by plmmanwu** [comment]
当初是作为lib库拷贝进来的，版本号也找不到，印象中就是164，结果看你的release记录，也找不到这个方法。郁闷，你看到上面代码没印象吗。要不你留下邮箱，我发你邮箱，你看下
