### ISSUE TITLE
hideKey使用是不是有点不对

### ISSUE THREAD

**Issue by xuzh2017** [CarGuo/GSYVideoPlayer#2760]
if (hideKey) {showNavKey(context, systemUiVisibility); }
这个判断是不是不对。如果hidekey为true，那不是应该隐藏虚拟键码。为什么还要show，现在我
setHideKey（false）结果从全屏返回后虚拟键被隐藏了

**Comment by xuzh2017** [comment]
版本7.1.3

**Comment by CarGuo** [comment]
没发现什么问题

**Comment by xuzh2017** [comment]
> 没发现什么问题


    //是否隐藏虚拟按键
    protected boolean mHideKey = true; 这个为true的时候应该hideNavKey吧。为什么是show呢？

**Comment by xuzh2017** [comment]
还有demo的detailplayer跳转第三方APP再回来，虚拟键显示有问题

**Comment by liyujiang-gzu** [comment]
@CarGuo 大哥，` setHideKey(false);`或者` setHideKey(true);`似乎并不一定有效果，`HUAWEI PRA-AL00X`这款手机进入全屏后无论如何都会隐藏底部的导航栏，从全屏回来底部导航栏没法恢复。
