### ISSUE TITLE
 java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by kulong51** [CarGuo/GSYVideoPlayer#2761]
## 问题描述：

集成最新VideoPlayer 开发列表到详情页面，用到demo 中视频共享，列表跟详情界面都有Cover,从列表进入详情 有时候会报错，导致详情界面一直处于加载视频状态

## 问题机型/系统：

例如 真机 oppo r9sk Android6.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## 问题log（如果有）

 java.lang.IllegalArgumentException: width and height must be > 0
06-06 11:35:01.587 22644-22644/ W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:852)
06-06 11:35:01.587 22644-22644/ W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
06-06 11:35:01.587 22644-22644/ W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:798)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.initCover(GSYTextureView.java:136)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.render.GSYRenderView.initCover(GSYRenderView.java:112)
06-06 11:35:01.587 22644-22644/W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYTextureRenderView.initCover(GSYTextureRenderView.java:147)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.updatePauseCover(GSYVideoView.java:248)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.changeUiToPauseShow(StandardGSYVideoPlayer.java:509)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.resolveUIState(GSYVideoControlView.java:824)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setStateAndUi(GSYVideoControlView.java:363)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onVideoPause(GSYVideoView.java:503)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.startAfterPrepared(GSYVideoView.java:826)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.swcy.shortvideo.common.widget.VideoPlayer.startAfterPrepared(VideoPlayer.java:345)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onPrepared(GSYVideoView.java:595)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.onPrepared(GSYVideoControlView.java:616)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.onPrepared(GSYBaseVideoPlayer.java:166)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$1.run(GSYVideoBaseManager.java:250)
06-06 11:35:01.587 22644-22644/ W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
06-06 11:35:01.587 22644-22644/ W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-06 11:35:01.587 22644-22644/ W/System.err:     at android.os.Looper.loop(Looper.java:179)
06-06 11:35:01.587 22644-22644/ W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5769)
06-06 11:35:01.587 22644-22644 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-06 11:35:01.587 22644-22644/ W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
06-06 11:35:01.588 22644-22644/ W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
06-06 11:35:01.588 22644-22644/ D/IJKMEDIA: ijkmp_pause()

xxxxxxx

```![image](https://user-images.githubusercontent.com/15215841/83935215-2305f400-a7ea-11ea-8b2e-08fb77e10d32.png)

**Comment by CarGuo** [comment]
Demo怎么复现

**Comment by kulong51** [comment]
> Demo怎么复现

已找到原因
