### ISSUE TITLE
播放assets里的文件？

### ISSUE THREAD

**Issue by cervy** [CarGuo/GSYVideoPlayer#2762]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述（mVideoPlayerView extends StandardGSYVideoPlayer）：

mVideoPlayerView.setUp(path/*file:///android_asset/xxxx.mp4, 该文件是有且有效的*/, true/*or false*/, "");
mVideoPlayerView.setAutoFullWithSize(true);
mVideoPlayerView.setLooping(true);
GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);
mVideoPlayerView.startPlayLogic();
发生了以下问题：
E/IJKMEDIA: /android_asset/xxxx.mp4: No such file or directory
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

## 问题机型/系统：

全部，，，

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

我怀疑是某个全局的设置禁用了播放assets里的文件，，多谢解答

**Comment by CarGuo** [comment]
看demo detailPlayer 页面底部 getUrl 方法里注释部分。

**Comment by cervy** [comment]
GSYVideoManager.instance().enableRawPlay(getApplicationContext()); 也是打开了的

**Comment by CarGuo** [comment]
你看demo那个，assets是怎么播放的，还分exo的和ijk的

**Comment by cervy** [comment]
private String getUrl() {

        //String url = "android.resource://" + getPackageName() + "/" + R.raw.test;
        //注意，用ijk模式播放raw视频，这个必须打开
        GSYVideoManager.instance().enableRawPlay(getApplicationContext());

        ///exo 播放 raw
        //String url = "rawresource://" + getPackageName() + "/" + R.raw.test;

        ///exo raw 支持
        //String url =  RawResourceDataSource.buildRawResourceUri(R.raw.test).toString();

        //断网自动重新链接，url前接上ijkhttphook:
        //String url = "ijkhttphook:https://res.exexm.com/cw_145225549855002";

        //String url = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
        //String url = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
        //String url = "http://7xjmzj.com1.z0.glb.clouddn.com/20171026175005_JObCxCE2.mp4";
        //String url = "http://hjq-1257036536.cos.ap-shanghai.myqcloud.com/m3u8/m1/out2.m3u8";
        //String url = "http://223.110.243.138/PLTV/2510088/224/3221227177/index.m3u8";
        //String url = "http://qiniu.carmmi.com/image/132451525666042.mp4";
        //String url = "http://ucp.wn.sunmath.cn/file-upload/gYQJHxK9iNQKJeWyS/V80418-103803.mp4?rc_uid=7sCFCGoaF2iTc9vH9&rc_token=prJK-xGutKmy2LDQO-OZASjob0o1u_s3e5SgMHmgjtn";
        //String url = "http://7xse1z.com1.z0.glb.clouddn.com/1491813192";
        //String url = "file://"+ Environment.getExternalStorageDirectory().getPath() + "Download/132451525666042.mp4";

        //String url =  "http://ipsimg-huabei2.speiyou.cn/010/video/other/20180427/40288b156241ec6301624243bdf7021e/40288b156290270d0162a3e7eb2e0726/1524814477/movie.mp4";
        //String url =  "http://ipsimg-huabei2.speiyou.cn/010/video/other/20180424/40288b156290270d0162a3db8cdd033e/40288b156290270d0162a3e8207f074f/e787a64c-f2d0-48fe-896d-246af05f111a.mp4";

        //String url =  "http://video.7k.cn/app_video/20171202/6c8cf3ea/v.m3u8.mp4";
        //String url =  "http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8";
        //String url = "rtmp://ctc-zhenjiang04.rt1.gensee.com/5324e855b28b453db7b0ec226598b76c_171391_0_8801038305_1591077225_205d01b8/video";
        String url = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
        //String url = "https://pointshow.oss-cn-hangzhou.aliyuncs.com/McTk51586843620689.mp4";
        //String url = "http://pointshow.oss-cn-hangzhou.aliyuncs.com/transcode/ORIGINAL/Mnbc61586842828593.mp4";
        //ssl error
        //String url =  "https://file.shftz.cn:8443/filesystem/download/10/2019/3/26/ce2c7c66-e9eb-42be-adf6-f9008385ea8c.mov/play";
        //String url =  "https://us-4.wl-cdn.com/hls/20200225/fde4f8ef394731f38d68fe6d601cfd56/index.m3u8";
        //String url =  "https://cdn61.ytbbs.tv/cn/tv/55550/55550-1/play.m3u8?md5=v4sI4lWlo4XojzeAjgBGaQ&expires=1521204012&token=55550";
        //String url =  "http://1253492636.vod2.myqcloud.com/2e5fc148vodgzp1253492636/d08af82d4564972819086152830/plHZZoSkje0A.mp4";

        //String url = "rtsp://ajj:12345678@218.21.217.122:65523/h264/ch40/sub/av_stream";
        //String url = "rtsp://ajj:ajj12345678@218.21.217.122:65522/h264/ch15/sub/av_stream";//String url =  "rtsp://cloud.easydarwin.org:554/stream0.sdp";
        //String url = "http://s.swao.cn/o_1c4gm8o1nniu1had13bk1t0l1rq64m.mov";
        //String url = "http://api.ciguang.tv/avideo/play?num=02-041-0491&type=flv&v=1&client=android";
        //String url = "http://video.7k.cn/app_video/20171213/276d8195/v.m3u8.mp4";
        //String url = "http://103.233.191.21/riak/riak-bucket/6469ac502e813a4c1df7c99f364e70c1.mp4";
        //String url = "http://7xjmzj.com1.z0.glb.clouddn.com/20171026175005_JObCxCE2.mp4";
        //String url = "https://media6.smartstudy.com/ae/07/3997/2/dest.m3u8";
        //String url = "http://cdn.tiaobatiaoba.com/Upload/square/2017-11-02/1509585140_1279.mp4";

        //String url = "http://hcjs2ra2rytd8v8np1q.exp.bcevod.com/mda-hegtjx8n5e8jt9zv/mda-hegtjx8n5e8jt9zv.m3u8";
        //String url = "http://7xse1z.com1.z0.glb.clouddn.com/1491813192";
        //String url = "http://ocgk7i2aj.bkt.clouddn.com/17651ac2-693c-47e9-b2d2-b731571bad37";
        //String url = "http://111.198.24.133:83/yyy_login_server/pic/YB059284/97778276040859/1.mp4";
        //String url = "http://vr.tudou.com/v2proxy/v?sid=95001&id=496378919&st=3&pw=";
        //String url = "http://pl-ali.youku.com/playlist/m3u8?type=mp4&ts=1490185963&keyframe=0&vid=XMjYxOTQ1Mzg2MA==&ep=ciadGkiFU8cF4SvajD8bYyuwJiYHXJZ3rHbN%2FrYDAcZuH%2BrC6DPcqJ21TPs%3D&sid=04901859548541247bba8&token=0524&ctype=12&ev=1&oip=976319194";
        //String url = "http://hls.ciguang.tv/hdtv/video.m3u8";
        //String url = "https://res.exexm.com/cw_145225549855002";
        //String url = "http://storage.gzstv.net/uploads/media/huangmeiyan/jr05-09.mp4";//mepg
        //String url = "https://zh-files.oss-cn-qingdao.aliyuncs.com/20170808223928mJ1P3n57.mp4";//90度
        return url;
    }

**Comment by cervy** [comment]
没有，以前是可以播放的，现在突然不行了，，

**Comment by CarGuo** [comment]
如下所示， 通过这个 url 和 enableRawPlay 就可以了，demo测试正常。
String url = "android.resource://" + getPackageName() + "/" + R.raw.test;
    GSYVideoManager.instance().enableRawPlay(getApplicationContext());

**Comment by cervy** [comment]
> 如下所示， 通过这个 url 和 enableRawPlay 就可以了，demo测试正常。
> String url = "android.resource://" + getPackageName() + "/" + R.raw.test;
> GSYVideoManager.instance().enableRawPlay(getApplicationContext());

在raw里面的话，也遇到一个问题，同一个播放器实例，再次  mVideoPlayerView.setUp(path/*另一个raw里的视频资源*/, false, "");
                mVideoPlayerView.startPlayLogic();
报错：E/IJKMEDIA: pipe:126: Invalid data found when processing input
           E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by CarGuo** [comment]
？？？没发现什么问题

**Comment by cervy** [comment]
必现的，有点神，，大神，有其它排查这个问题的思路吗

**Comment by CarGuo** [comment]
我在 demo 中先播放 R.raw.test ，之后播放完后再次
 

        String url = "android.resource://" + getPackageName() + "/" + R.raw.test1;
        detailPlayer.setUp(url, false, "");
        detailPlayer.startPlayLogic();


正常播放

**Comment by cervy** [comment]
没播完再另一个呢

**Comment by CarGuo** [comment]
你要先 release，然后延迟下再播放

**Comment by cervy** [comment]
> 你要先 release，然后延迟下再播放

什么都没改，现在直接切换到下一个又可以了，，，第一个有重播无重播都可以

**Comment by CarGuo** [comment]
一般是要 release 的

**Comment by cervy** [comment]
> 一般是要 release 的

好的，
