### ISSUE TITLE
后台播放音乐时候视频突然暂停

### ISSUE THREAD

**Issue by 951AB159BA** [CarGuo/GSYVideoPlayer#2763]
当GSYVideoplayer视频切到后台播放，然后打开爱奇艺观看网上视频播放，GSYVideoplayer的视频会突然停止，声音也停止，按钮状态也没有还原。必现。

**Comment by CarGuo** [comment]
默认下是这样的，可以设置 setReleaseWhenLossAudio(false); 或者重载 onLossAudio、onLossTransientCanDuck、onLossTransientCanDuck、onGankAudio 等方法
