### ISSUE TITLE
重新播放怎么实现？

### ISSUE THREAD

**Issue by toneaky** [CarGuo/GSYVideoPlayer#2765]
Q
## 问题描述：
重新播放的实现， 我需要在一个按钮点击后，进行重新播放
但是没有提供对应的方法，
自己写的两行代码
  video_player.seekTo(1000L)
   video_player.onVideoResume()
会出现这样的问题，就是虽然是从1秒钟开始放，但进度条，还是会停留在先前的位置
XXXX发生了这样的问题！
![erro](https://user-images.githubusercontent.com/19887354/83990337-e4a03e80-a97b-11ea-9cb4-621afc2516e7.png)

**Comment by CarGuo** [comment]
setTextAndProgress

**Comment by toneaky** [comment]
![image](https://user-images.githubusercontent.com/19887354/83997516-27b8dc80-a991-11ea-8bbf-c02ecd25dcdb.png)
这个是protect方法，调用不了？

**Comment by CarGuo** [comment]
你继承下之后，自己写个方法 public 调用它就好了，如果你需要在外部调用的话

**Comment by toneaky** [comment]
好的，谢谢，懂了
