### ISSUE TITLE
提点小建议

### ISSUE THREAD

**Issue by sunbest110** [CarGuo/GSYVideoPlayer#2766]
我用的是6.0.3版本
![image](https://user-images.githubusercontent.com/12553543/84005013-05c65680-a99f-11ea-9b3d-ba79df9bb544.png)
当正常播放结束，再点击startbutton；
![image](https://user-images.githubusercontent.com/12553543/84005140-3dcd9980-a99f-11ea-99de-0047b08ca50b.png)
回调用onclickStartError的回调而不是start的

**Comment by sunbest110** [comment]
![image](https://user-images.githubusercontent.com/12553543/84005353-9735c880-a99f-11ea-8bea-0d1072840c9c.png)

**Comment by sunbest110** [comment]
![E1F9DB3D-155F-44D9-A124-A26AA4EBFD81](https://user-images.githubusercontent.com/12553543/84005492-c9dfc100-a99f-11ea-8f13-0ea640387d44.png)

**Comment by CarGuo** [comment]
收到
