### ISSUE TITLE
循环播放视频，长时间播放视频会画面卡死

### ISSUE THREAD

**Issue by MrUncleYzw** [CarGuo/GSYVideoPlayer#2771]
## 问题描述：
循环播放广告视频，全都是本地视频，例如有3个视频循环播放，一段时间后会在某个视频卡死

## 问题机型/系统：

定制android机（7.0）

## GSY依赖版本

最新版

问题代码：(如果有)
    public void initVideo(String url) {
        mContentBinding.screenStdplayer.loadCoverImage(url, R.drawable.icon_deauft_screen);
        GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);
        GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder();
        gsyVideoOption
                .setAutoFullWithSize(true)
                .setIsTouchWiget(true)
                .setRotateViewAuto(false)
                .setLockLand(false)
                .setShowFullAnimation(true)
                .setNeedLockFull(true)
                .setUrl(url)
                .setStartAfterPrepared(true)
                .setCacheWithPlay(false)
                .setVideoAllCallBack(new GSYSampleCallBack() {
                    @Override
                    public void onPlayError(String url, Object... objects) {
                        super.onPlayError(url, objects);
                        System.out.println("++++++++++++onPlayError");
                        isPlayingVideo = false;
                        isPlayImage = false;
                        mContentBinding.screenIv.setVisibility(View.VISIBLE);
                    }
                    @Override
                    public void onAutoComplete(String url, Object... objects) {
                        super.onAutoComplete(url, objects);
                        isPlayingVideo = false;
                        setLoadingViewStyle(true);
                        mContentBinding.screenStdplayer.showThumView();
                    }

                    @Override
                    public void onClickBlank(String url, Object... objects) {
                        super.onClickBlank(url, objects);
                        exitScreenActivity();
                    }

                    @Override
                    public void onPrepared(String url, Object... objects) {
                        super.onPrepared(url, objects);
                        //开始播放了才能旋转和全屏
                        isPlayingVideo = true;
                        mContentBinding.screenIv.setVisibility(View.GONE);
                        setLoadingViewStyle(false);
                        AdvUtils.upDateAdvPlatTimes(MyApplication.currentScreenCabadvConfig);
                    }

                    @Override
                    public void onQuitFullscreen(String url, Object... objects) {
                        super.onQuitFullscreen(url, objects);
                    }
                }).setLockClickListener((view, lock) -> {
        }).build(mContentBinding.screenStdplayer);
        mContentBinding.screenStdplayer.startPlayLogic();
    }

每次都播放我都会调用这个初始化的方法，不知道是不是我这里写法有问题 还不是应该这么重复的初始化 （3个内核都会出现这种问题）

## 问题log（如果有）

    com.google.android.exoplayer2.util.EGLSurfaceTexture$GlException: eglChooseConfig failed: success=false, numConfigs[0]=0, configs[0]=android.opengl.EGLConfig@210
        at com.google.android.exoplayer2.util.EGLSurfaceTexture.chooseEGLConfig(EGLSurfaceTexture.java:234)
        at com.google.android.exoplayer2.util.EGLSurfaceTexture.init(EGLSurfaceTexture.java:125)
        at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.initInternal(DummySurface.java:215)
        at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.handleMessage(DummySurface.java:186)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

xxxxxxx

```

**Comment by CarGuo** [comment]
demo 怎么复现？可以试试切换 exo 内核是不是也会
