### ISSUE TITLE
同时使用多集功能和切换清晰度功能

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2775]
## 问题描述：

想了解一下怎么同时使用多集功能和切换清晰度功能，我看demo，如果使用多集的话要用GSYVideoModel，如果使用多清晰度的话要用SwitchVideoModel，如果两个同时要用，该怎么选择

**Comment by CarGuo** [comment]
自定义啊，demo 只是参考，你自己写个整合起来就好了
