### ISSUE TITLE
多播问题

### ISSUE THREAD

**Issue by Xujun770366270** [CarGuo/GSYVideoPlayer#2779]
大哥你好,我在做多视频播放功能,场景是,用你的播放控件去打开,目前我做的是4画面同时播放,
问题一: 目前出现的问题是,如果4画面打开的是同一个摄像头,我这边是能够正常播放的
但是,如果我的4画面打开的分别是 不同的摄像头,那么总会有最后一个摄像头不能正常播放(做过不下20次播放), 请问一下,如何解决,
![image](https://user-images.githubusercontent.com/13106539/84461772-db76e080-ac9f-11ea-9aa5-d37af71a6a0b.png)

问题二 :有的时候会出现流量提示框(当前为4G流量,是否继续播放),请问,这个如如何去掉

![image](https://user-images.githubusercontent.com/13106539/84461806-f6495500-ac9f-11ea-8618-6a3ba04dd912.png)

**Comment by CarGuo** [comment]
重写 isShowNetConfirm 的可以处理。

不能播放的问题，如果用的是 ijk 内核的，可以参看问题集锦设置 dns clear ，然后在看看，我估计是内网同 ip 不同端口？

**Comment by Xujun770366270** [comment]
![image](https://user-images.githubusercontent.com/13106539/84469917-bd67ab00-acb4-11ea-9c37-0fd956e03137.png)
我这边肯定,IP 是不相同的, 他们有很低的概率能同时播放,大部分情况只能播放三个,总有一个播放不出来, 我想是不是能存的缓存的问题, 我播放的视频源都是720P资源

**Comment by Xujun770366270** [comment]
另外,您这边的播放控件,能降低分辨率显示么,比如说我的源播放 是 720P,但是4分屏的时候,我用360P显示,这样可以节约资源

**Comment by CarGuo** [comment]
又可能，分辨率码率帧率会导致内存不够。
不能，这个降低流的行为需要在服务端转码，但是你可以设置丢帧 drop_frame 看看

**Comment by Xujun770366270** [comment]
我这里可以开启更多的内存空间么?

**Comment by Xujun770366270** [comment]
你好,我这里可以开启更多的缓存空间么?

**Comment by CarGuo** [comment]
哪个缓存空间？？

**Comment by Xujun770366270** [comment]
![image](https://user-images.githubusercontent.com/13106539/84612922-9ac3d500-aef4-11ea-93f9-db909b404079.png)
这两个buffer

**Comment by CarGuo** [comment]
ijk 下这个是可以配置的
