### ISSUE TITLE
内存泄漏&闪退

### ISSUE THREAD

**Issue by HolenZhou** [CarGuo/GSYVideoPlayer#2780]
## 问题描述：

内存泄漏 & 闪退

## 问题机型/系统：

例如 真机 三星Note10+ 10.0系统

## GSY依赖版本

运动最新master代码

## Demo中的复现步骤

1.Demo中随便进入几个页面运动退出，LeakCanary有很多报警
2.Demo中进入多任务页面，同时点击播放三个视频，然后上滑，就会闪退

## 问题log（如果有）
![image](https://user-images.githubusercontent.com/11223102/84462131-cf3f5300-aca0-11ea-9c9a-d87c250dde12.png)

**Comment by CarGuo** [comment]
你要泄漏的是什么，如果是 AudioManager 的请无视。
测试没有出现崩溃

**Comment by HolenZhou** [comment]
@CarGuo 在ijk模式下崩溃没有堆栈，我刚试了在Exo模式下也会crash:
![image](https://user-images.githubusercontent.com/11223102/84492617-029dd400-acd9-11ea-80a0-552f69da0184.png)

**Comment by HolenZhou** [comment]
顺便想请教下大佬，我有一个需求，需要一个列表里面的所有可见视频同时播放，而且一进入就一直播放，滑动时也是在一直播放，因为要播放的是个比较短的需要循环播放的动作指导视频，需求目的是用video来代替gif取得更好的视觉效果。请问这种需求，使用框架中的多任务的方式能够实现吗，我刚改了发现不太好改出这样的效果哦

**Comment by CarGuo** [comment]
奇怪，我这边没有崩溃，你这个看起来是 List 被 remove 之后导致出现问题。我这边没出现。

同时那么多个 view 效果不是特别好的。因为内存开销会很大。推荐你用 lottie 还是 SVGPlayer

**Comment by HolenZhou** [comment]
好的，谢谢了，我再研究下

**Comment by coolmaye** [comment]
> 

您说可以直接无视，但是它持有了我的Activity啊，我反复开关十几次视频播放页面，内存会增加几百m的开销并且无法被释放，没有别的解决办法了吗
