### ISSUE TITLE
触摸显示滑动进度Dialog松开后无法Dismiss

### ISSUE THREAD

**Issue by c4jeff** [CarGuo/GSYVideoPlayer#2781]
## 问题描述：

在ViewPager2中使用，触摸显示滑动进度dialog的过程中，稍微上移一点，touch事件会被ViewPager2夺去，导致GSYVideoControlView不走MotionEvent.ACTION_UP，也就导致touchSurfaceUp无法调用，此时dialog无法dismiss

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## Demo中的复现步骤

1. 触摸显示滑动进度dialog
2. 稍微上移一点后(此时事件被ViewPager2夺去)
3. 松开手
4. 此时dialog无法dismiss

**Comment by CarGuo** [comment]
这个不算是播放器的问题了吧？手势冲突你需要自己处理，例如个问题你可以继承播放器后重写对应方法，新闻基本是protect的
