### ISSUE TITLE
m3u8播放

### ISSUE THREAD

**Issue by yefangqingchen** [CarGuo/GSYVideoPlayer#2782]
## 问题描述：

已经配置PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)了，但是还是不支持m3u8播放。地址：http://192.168.2.2:8888/xingfu/xingfu.m3u8

## GSY依赖版本

com.shuyu:GSYVideoPlayer:7.1.4

问题代码：
1、已经在Application中设置PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)

2、使用控件GSYSampleADVideoPlayer（播放MP4可以）

3、在demo中可以设置PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)可以播放，但是在项目中不行。

**Comment by CarGuo** [comment]
demo可以，项目不行？？？那么是因为你没有配置支持 http 的？

**Comment by yefangqingchen** [comment]
额，这个里面支持 ts文件播放吗？服务器对m3u8文件进行了分段加密，有多个ts文件，可以播放吗

**Comment by CarGuo** [comment]
支持啊，AES128？key是16位的？

**Comment by yefangqingchen** [comment]
是的，我看你帮助文档里面没写关于 ：
服务器对m3u8文件进行了分段加密，有多个ts文件
然后 AES128加解密这些

**Comment by CarGuo** [comment]
那是支持的

**Comment by yefangqingchen** [comment]
ijkplayer支持是吧，第一个问题你说 那么是因为你没有配置支持 http 的 ，这个我没有太明白，我没在main中和GSYApplication看到你说的这个http配置什么的。

**Comment by yefangqingchen** [comment]
额，你说的是network-security-config ？

**Comment by CarGuo** [comment]
ijk 和 exo 都支持加密的。ijk 需要用 e x_so 第三种依赖。

对的说的是高版本下的  network-security-config

**Comment by yefangqingchen** [comment]
好的，我抽空研究下，先去画界面了
