### ISSUE TITLE
Vivo视频点击加载崩溃

### ISSUE THREAD

**Issue by guangmingxiong9999** [CarGuo/GSYVideoPlayer#2783]
VIVO V1732A   Android 8.1.0,level 27

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

错误日志

java.lang.NoClassDefFoundError: Not a primitive type: '\u0000'
--
16 com.shuyu.gsyvideoplayer.video.base.GSYVideoView.isCurrentMediaListener(GSYVideoView.java:1)
17 com.shuyu.gsyvideoplayer.video.base.GSYVideoView.setUp(GSYVideoView.java:11)
18 com.shuyu.gsyvideoplayer.video.base.GSYVideoView.setUp(GSYVideoView.java:7)
19 com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setUp(GSYVideoControlView.java:2)
20 com.shuyu.gsyvideoplayer.video.base.GSYVideoView.setUp(GSYVideoView.java:2)
21 com.shuyu.gsyvideoplayer.a.a.build(GSYVideoOptionBuilder.java:54)
22 com.shuyu.gsyvideoplayer.a.a.build(GSYVideoOptionBuilder.java:11)

**Comment by CarGuo** [comment]
Demo复现？？

**Comment by guangmingxiong9999** [comment]
@CarGuo 项目中bugly捕捉到的

**Comment by CarGuo** [comment]
java.lang.NoClassDefFoundError  看起来和项目没太大关系

**Comment by guangmingxiong9999** [comment]
好的，谢谢
