### ISSUE TITLE
播放RTSP协议,握手问题

### ISSUE THREAD

**Issue by DocHuangys** [CarGuo/GSYVideoPlayer#2784]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我们有录播设备，是RTSP协议的直播流。出现问题是，连接rtsp url一直不能播放视频，当我在pc端使用VLC MediaPlay连接一次录播设备后，手机端就能正常播放。看了下录播设备的运行日志，当我重启录播设备后，直接用手机连接，录播设备没有收到rstp service连接，公司前辈说的握手失败，

## 问题机型/系统：

oppo A8

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'`
请问这种情况该怎么解决呢？

**Comment by CarGuo** [comment]
不是很理解，首先使用第三种依赖 ex_so，然后按照问题集锦使用tcp链接

**Comment by DocHuangys** [comment]
好的，我试试
