### ISSUE TITLE
播放进度回调 时间不固定 

### ISSUE THREAD

**Issue by yangjianhong** [CarGuo/GSYVideoPlayer#2785]
看30秒视频 给积分 再回调进度的时候 设置进度条的值  不是固定时间返回进度 无法设置进度条进度

**Comment by CarGuo** [comment]
不是很理解

**Comment by yangjianhong** [comment]
setGSYVideoProgressListener 能不能 固定时间回调 比如 1毫秒或者 100 毫秒 回调一次 现在回调的时间都是不是固定的 
 还有能不能做个类型 抖音播放的 demo

**Comment by CarGuo** [comment]
这个其实你通过自己设置一个定时器就可以解决啊？？？

**Comment by yangjianhong** [comment]
那可否写个 抖音的播放demo  谢谢了

**Comment by CarGuo** [comment]
I have not idea
