### ISSUE TITLE
大神请这种音频格式，自己编译该加什么？ aac lc加入编译的时候会Unknown option "lc".

### ISSUE THREAD

**Issue by wjj201411** [CarGuo/GSYVideoPlayer#2787]
General
Complete name                  : C:\Users\Administrator\Desktop\8bf4f9f8222c000b02692e6743b970f2.mp4
Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom (isom/iso2/avc1/mp41)
File size                      : 454 KiB
Duration                       : 35 s 968 ms
Overall bit rate               : 103 kb/s
Writing application            : Lavf57.58.101

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L3.1
Format settings                : CABAC / 16 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 16 frames
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 35 s 709 ms
Bit rate                       : 50.7 kb/s
Nominal bit rate               : 489 kb/s
Width                          : 640 pixels
Height                         : 368 pixels
Display aspect ratio           : 1.739
Frame rate mode                : Constant
Frame rate                     : 24.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.009
Stream size                    : 221 KiB (49%)
Writing library                : x264 core 148 r2699
Encoding settings              : cabac=1 / ref=16 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=4 / chroma_me=0 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=8 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=30 / scenecut=0 / intra_refresh=0 / rc_lookahead=60 / rc=abr / mbtree=1 / bitrate=489 / ratetol=1.0 / qcomp=0.60 / qpmin=20 / qpmax=51 / qpstep=3 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box        : avcC

Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : mp4a-40-2
Duration                       : 35 s 968 ms
Bit rate mode                  : Constant
Bit rate                       : 48.0 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 212 KiB (47%)
Default                        : Yes
Alternate group                : 1

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md
