### ISSUE TITLE
固定全屏列表播放时，全屏显示不全

### ISSUE THREAD

**Issue by Mysqi** [CarGuo/GSYVideoPlayer#2788]
## 问题描述：

某些机型自定义全屏时出现头部和底部黑色，未全屏播放，区域显示不全。
直接用StandardGSYVideoPlayer来播放也同时出现这个情况

## 问题机型/系统：

真机 小米mi5 Android8.0能够正常全屏显示。
真机 华为HUAWEI CLT-AL00  Android10.0 显示异常。

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## 相关链接
正常显示http://file.wecanplus.net/images/comty/2020/6/compress/cfebca71e7034451cb2e8d329fdb1ae0_607x1080.jpg
显示异常链接：
http://file.wecanplus.net/images/comty/2020/6/compress/63a87e20ca46c553b31303d1403abe0f_498x1080.jpg
视频链接：
http://videotest.wecanplus.com.cn//2020/06/18/13/14/37/f3b2095ec69d3dff402f59f4d3eeea29.mp4

**Comment by CarGuo** [comment]
我不是特别理解你的意思，同一个视频在不同手机上出现黑边不是很正常嘛？
