### ISSUE TITLE
如何进来不点击播放按钮就直接播放，找了很久的文档，没找到这个功能

### ISSUE THREAD

**Issue by denghanhao** [CarGuo/GSYVideoPlayer#2790]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
startPlayLogic

**Comment by denghanhao** [comment]
> startPlayLogic

大牛，中间的暂停键能不能隐藏，十分感谢答复

**Comment by CarGuo** [comment]
不要的话，你直接布局去掉就好了，重写getLayoutId

**Comment by denghanhao** [comment]
> 不要的话，你直接布局去掉就好了，重写getLayoutId

谢谢大佬

**Comment by hellobenji** [comment]
重写完成以后 全屏以后的ui所有的点击事件都不起作用是怎么回事
