### ISSUE TITLE
本地视频，.mpg格式

### ISSUE THREAD

**Issue by AndyRenJie** [CarGuo/GSYVideoPlayer#2793]
我想问下GSYVideoPlayer是否支持播放本地视频，我在Demo中没有看到这块儿，另外还想问下咱们的播放器是否支持.mpg等其他格式视频文件

**Comment by CarGuo** [comment]
DetailPlayer 的 fileSearch ，或者 file:// + xxx

**Comment by AndyRenJie** [comment]
已经解决了，谢谢，那是否支持.mpg格式的视频文件

**Comment by CarGuo** [comment]
推荐阅读下这个，你大概就知道怎么支持了：

https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q

https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/BUILD_SO.md

https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md
