### ISSUE TITLE
播放有画面，声音不正常

### ISSUE THREAD

**Issue by 627219641** [CarGuo/GSYVideoPlayer#2795]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放视频声音滋滋声，无法听清楚

## 问题机型/系统：

vivo x21A

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Demo中的SimplePlayer简单播放，使用以下地址播放出现问题 https://vivo-oss-sz-vcollege.oss-cn-shenzhen.aliyuncs.com/ccd20503-c83f-4e58-93df-1b0b634b195d.mp4?Expires=1593505185&OSSAccessKeyId=LTAIr99WSxTqYboJ&Signature=nXefeRLRrhiQCMM9alY2wnfSUiQ%3D，该视频格式是h264,音频是aac，44.1 kHz,用电脑或者ios都可以播放

**Comment by CarGuo** [comment]
这个应该是编码有兼容问题

Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s

ENCODING_PCM_16BIT
