### ISSUE TITLE
悬浮窗ui怎么定制呢?

### ISSUE THREAD

**Issue by dev-yangyang** [CarGuo/GSYVideoPlayer#2796]
## 问题描述：

需求需要定制悬浮窗ui,看过代码之后发现是因为setSmallVideoTextureView设置触摸事件处理之后,事件无法传递到原来的onTouch方法里,所以原有的ui在点击之后就不会再出现.

有没有开放api或者其他方式可以快捷定制自己的ui呢?

**Comment by CarGuo** [comment]
推荐自定义 GSYVideoHelper 和 重写 showSmallVideo 方法


另外通过 

```

        final ViewGroup vp = getViewGroup();
        GSYVideoPlayer gsyVideoPlayer = (GSYVideoPlayer) vp.findViewById(getSmallId());
```

是可以获取到 small 的 view 对象的

**Comment by dev-yangyang** [comment]
好的,我试着写一下
