### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [CarGuo/GSYVideoPlayer#2797]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential security problem.
我不说中文。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/security/advisories/GHSA-phfh-c834-844x
