### ISSUE TITLE
播放本地视频黑屏

### ISSUE THREAD

**Issue by Aarondue** [CarGuo/GSYVideoPlayer#280]
我使用的播放器是StandardGSYVideoPlayer，使用如下本地url（确认无误）进行传值，为什么没反应呢？
        final String url = "/storage/emulated/0/DCIM/Camera/VID_20170617_233809.mp4";
        gsyVideoPlayer.setUp(url, false , null, "这是title");

**Comment by CarGuo** [comment]
看看是不是mpeg编码，可以试试ex-so的so

**Comment by lixiang5054** [comment]
你好问题解决了吗？
