### ISSUE TITLE
只能播放4路,不能播放5路

### ISSUE THREAD

**Issue by Xujun770366270** [CarGuo/GSYVideoPlayer#2800]
在同时播放视频的时候用了 MultiSampleVideo 这个类, 目前发现,最多只支持4路播放,再加一路就无法播放,请问作者有对这这方面限制么?

**Comment by CarGuo** [comment]
毕竟内存和网络会顶不住的，我没做限制

**Comment by Xujun770366270** [comment]
内存目前看是够的,我播的都是低分辨率的视屏,不知道为什么原因

**Comment by CarGuo** [comment]
那就不知道了，代码上确实没做限制
