### ISSUE TITLE
ExoPlayer播放m3u8 抓包问题

### ISSUE THREAD

**Issue by guangmingxiong9999** [CarGuo/GSYVideoPlayer#2803]
## 问题描述：

请问使用ExoPlayer播放m3u8会被抓包，有没有什么方式使m3u8文件不被抓到，像ijkplayer内核播放一样。或者有没有什么方式，即使拿到文件也不能播放

**Comment by CarGuo** [comment]
使用类似 GSYDefaultHttpDataSource ，然后把 url.openConnection 替换为

 HttpURLConnection uc    = (HttpURLConnection) url.openConnection(Proxy.NO_PROXY);

**Comment by guangmingxiong9999** [comment]
@CarGuo  大佬，按照你说的，读取ts文件的时候没被抓到，但是读取m3u8文件的链接依旧被抓到了，还要设置什么地方吗

**Comment by CarGuo** [comment]
一样的啊， DefaultHlsDataSourceFactory 里面 createDataSource 的方法，最终回到 ParsingLoadable 的 load

**Comment by guangmingxiong9999** [comment]
@CarGuo 可以了，大佬 谢谢
