### ISSUE TITLE
功能问题：如何指定快进（快退）的秒数，并同步进度条

### ISSUE THREAD

**Issue by ff-frida** [CarGuo/GSYVideoPlayer#2808]
## 问题描述：
1：现在需要增加功能，增加2个按钮，一个快进，一个是快退
2：点击快进或者快退，快进n秒或者快退n秒。
3：快进api是啥，如何同步快进后的进度条呢

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

问题代码：(如果有)
```

```

**Comment by CarGuo** [comment]
```
        detailPlayer.seekTo();
        detailPlayer.getGSYVideoManager().seekTo();
        GSYVideoManager.instance().seekTo();
        
```


另外 setTextAndProgress 方法需要你自己继承后调用，因为是 protect 的

**Comment by ff-frida** [comment]
> ```
>         detailPlayer.seekTo();
>         detailPlayer.getGSYVideoManager().seekTo();
>         GSYVideoManager.instance().seekTo();
>         
> ```
> 
> 另外 setTextAndProgress 方法需要你自己继承后调用，因为是 protect 的
首先感谢回答。
一下是我的代码。
在布局增加快退按钮，点击事件执行以下代码。
```
//获取整个视频的时间
int total = getDuration();
//获取当前播放的时间点
int currentTime = getCurrentPositionWhenPlaying();
//计算快退之后的时间-5秒
 int rewind = currentTime - 5000;
 if (rewind >= 0 && rewind <= total) {
      Debuger.printfLog("->>mIvBack  seekTo " + rewind);
      //直接移动到具体的时间节点就可以了
       getGSYVideoManager().seekTo(rewind);
} else if (rewind < 0) {
       getGSYVideoManager().seekTo(0);
}
//这样移动时间节点之后，进度条会自动更新，不需要额为的操作。
```
