### ISSUE TITLE
有提供m3u8切片下载解密的外部接口吗？ 这块功能的源码在哪个库里

### ISSUE THREAD

**Issue by cherysky** [CarGuo/GSYVideoPlayer#2809]
## 问题描述：

求解怎么实现自定义m3u8切片下载加密并播放

## 问题机型/系统：

 真机 小米note2 Android7.0

## GSY依赖版本

 implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.1'
implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.1'

## Demo中的复现步骤
目前项目是企业自己提供m3u8视频，但是这个视频的所有切片是单独加密，加密规则公司自己规定，目前用的exo2的库，内核用的exo,缓存也用的exo, 目前框架在下载切片解码播放方面有涉及到加密和解密的步骤吗， 可以自定义一个下载播放模块内嵌进框架吗，还有源码里面从下载到接码播放这一块的代码在哪个库里，在java层还是在so里面？

问题代码：(如果有)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2557

https://github.com/CarGuo/GSYVideoPlayer/issues/2803
