### ISSUE TITLE
监听到网络变化时如何在播放器上覆盖一层新view

### ISSUE THREAD

**Issue by xundaozhe** [CarGuo/GSYVideoPlayer#281]
已经知道需要重写showWifiDialog(),但是是在recyclerView中使用的播放器,不知道如何添加一层view,求给点思路(效果要类似于网易新闻中网络变换时播放器上面覆盖的一层view),挺急的,谢谢

**Comment by CarGuo** [comment]
不是很理解，有截图吗？

**Comment by xundaozhe** [comment]
![ik znm 9vtw 3o v m72 8t](https://user-images.githubusercontent.com/18245798/27368087-2c1a7e50-5683-11e7-9d94-9502c2b14002.png)

**Comment by xundaozhe** [comment]
老哥,就是这种,试了很多方式都有问题

**Comment by CarGuo** [comment]
首先继承播放器，然后复制布局，在布局上加view，然后记得这个view的层级要高于渲染层那个container，然后返回getLayoutId用你自己的布局

**Comment by xundaozhe** [comment]
感谢,感谢,感谢,为什么github没有打赏的功能 - _ -

**Comment by xundaozhe** [comment]
您好,按照您说的方法现在布局可以显示了,可是recyclerview滚动的时候命名没点击播放按钮,这个view会自动显示,如何解决(麻烦您了)

**Comment by xundaozhe** [comment]
已经解决了,框架真好用,谢谢

**Comment by hele-jeremy** [comment]
你是如何实现这种 在3G4G 和 wifi切换的情况下展示一个view提示用户当前是否继续播放的
求解决思路
