### ISSUE TITLE
is:issue is:open 如何提前缓存将要播放的一堆视频？

### ISSUE THREAD

**Issue by cervy** [CarGuo/GSYVideoPlayer#2810]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailDownloadPlayer.java 例如这个

**Comment by cervy** [comment]
那个模拟是仅仅模拟缓存进度吗

**Comment by CarGuo** [comment]
demo 是通过代理提前下载在本地，你看源码逻辑

**Comment by cervy** [comment]
请问缓存后的文件名后缀有的是 .mp4.download是什么情况a

**Comment by CarGuo** [comment]
因为还没有缓存完整，但是不影响缓存部分播放

**Comment by cervy** [comment]
好的， 若那个代理下载工具用其它的，是不是只要按Androidvideocache的规则指定文件名与存储路径就ok了呢

**Comment by CarGuo** [comment]
是的
