### ISSUE TITLE
rtsp实时流如何监控是否可用

### ISSUE THREAD

**Issue by Henrylhd** [CarGuo/GSYVideoPlayer#2811]
## 问题描述：

 相机断网   连网过程中 通过GSYVideoManager().isPlaying()无法获得对应的状态

## 问题机型/系统：

小米盒子_GITV MIUI TV版本  1.5.93

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤
我用小米盒子 播放相机实时的rtsp流视频，然后相机断网  视频卡住  当相机连网之后 无法检测到 对应的状态进行重连 会导致一直卡住

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2757#issuecomment-640343341
