### ISSUE TITLE
exo模式，视频播放完成后拖动进度条，有声音无画面

### ISSUE THREAD

**Issue by wdeo3601** [CarGuo/GSYVideoPlayer#2813]
## 问题描述：

demo里的 `自定义EXO` 播放视频，播放完成后再去拖动进度条，这时候会有音频继续播放，但是没有画面。ijk模式无此问题。

## 问题机型/系统：  

三星S8/android9.0  

## GSY依赖版本

```
    GSYVideoPlayerVersion=7.1.4
    //GSYVideoPlayer 视频播放
    implementation "com.shuyu:gsyVideoPlayer-java:$GSYVideoPlayerVersion"
    implementation "com.shuyu:GSYVideoPlayer-exo2:$GSYVideoPlayerVersion"
    implementation "com.shuyu:gsyVideoPlayer-armv5:$GSYVideoPlayerVersion"
    implementation "com.shuyu:gsyVideoPlayer-armv7a:$GSYVideoPlayerVersion"
    implementation "com.shuyu:gsyVideoPlayer-x86:$GSYVideoPlayerVersion"
```

## Demo中的复现步骤

Demo中的 `自定义EXO` 点击进入后，播放完成后拖动进度条。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
我没记错的话，播放完之后拖动应该不会继续播放呀，直接切换到 exo 内核模式试试，不要试 demo 的 自定义

**Comment by wdeo3601** [comment]
> 我没记错的话，播放完之后拖动应该不会继续播放呀，直接切换到 exo 内核模式试试，不要试 demo 的 自定义

嗯，我昨天先是在我自己的项目里试了下，发现播放完后拖动会有声音，然后又用 demo 试了下，demo里切换 exo、自定义exo，都是播放完后拖动有声音，切换到ijk就是正常的。。

**Comment by CarGuo** [comment]
那还真得做处理，重载下  `onCompletion` ， 和 `onAutoCompletion` 方法，增加：


        mHadPlay = false;

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/commit/8d0d0d36f21ae439eeadd6d587218e67f953cf21 和 https://github.com/CarGuo/GSYVideoPlayer/commit/cfdcef17a15e72d612a946ccb555fe1514bf1d4c
