### ISSUE TITLE
为什么退出全屏一定是会旋转屏幕到竖屏

### ISSUE THREAD

**Issue by Matchas-xiaobin** [CarGuo/GSYVideoPlayer#2814]
#2517  问题描述：

为什么退出全屏一定是会旋转屏幕到竖屏？

## 问题机型/系统：

真机 华为notepad

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## Demo中的复现步骤

```
app限制就是横屏使用，点击全屏后，在退出全屏，被强制竖屏了
```

问题代码：(如果有)

```
```

## 问题log（如果有）

```
```

**Comment by ff-frida** [comment]
目前也是横屏开发，接入这个lib，是6.0.3版本的；其他版本应区别不大把。
1：我act设置android:configChanges="orientation|keyboardHidden|screenSize"            android:screenOrientation="landscape"
2：我在播放里面，直接写死了全屏，也就是进去就是一个全屏播放的节面，那个全屏按钮，我已经屏蔽了
3：如果发现横屏act，返回横屏act出现短暂的屏幕旋转的情况，你可尝试这样解决。
```
在退出的逻辑页面，例如调用finish。你做一个延后finish的操作。比如延后300ms调用finish这样。
就不会出现短暂的旋转，反正我最近也折腾这个，按back返回是不会出现这个情况，就是页面代码完成之后，调用finish会这样。
延后finish为什么会正常了，这个还没找到为原因。
```

可以看看这个。https://blog.csdn.net/baidu_36170592/article/details/102702238#comments_12663121

**Comment by Matchas-xiaobin** [comment]
> 1：我actsettingandroid：configChanges =“ orientation | keyboardHidden | screenSize” android：screenOrientation =“ landscape”
> 2 ：我也是设置横屏开发，接受这个lib，是6.0.3版本的；其他版本应区别不大把。：我在播放里面，直接写死了全屏，也就是进去就是一个全屏播放的节面，那个全屏按钮，我已经屏蔽了
> 3：如果发现横屏动作，返回横屏动作出现短暂的屏幕旋转的情况，你可尝试这样解决。
> 
> ```
> 在退出的逻辑页面，例如调用finish。你做一个延后finish的操作。比如延后300ms调用finish这样。
> 就不会出现短暂的旋转，反正我最近也折腾这个，按back返回是不会出现这个情况，就是页面代码完成之后，调用finish会这样。
> 延后finish为什么会正常了，这个还没找到为原因。
> ```
> 
> 可以看看这个[。https:](https://blog.csdn.net/baidu_36170592/article/details/102702238#comments_12663121) //blog.csdn.net/baidu_36170592/article/details/102702238#comments_12663121[](https://blog.csdn.net/baidu_36170592/article/details/102702238#comments_12663121)

谢谢你的回复。 
不过我这情况不一样，我这儿是APP全部都是横屏状态的，给平板开发嘛，纯横屏的。
小窗口播放视频，然后点击全屏播放，调用的detailPlayer.startWindowFullscreen(activity, false, true)
然后退出全屏播放，恢复小窗口的时候，会被强制切换到竖屏，导致activity走reCreate了。

目前已经临时解决了这个问题，因为不想增加项目moudle了，所以我看了下源代码，然后重写了activity的setRequestedOrientation(requestedOrientation: Int) 方法，注释掉了super.setRequestedOrientation(requestedOrientation)
达到了我想要的效果。

**Comment by ff-frida** [comment]
> > 1：我actsettingandroid：configChanges =“ orientation | keyboardHidden | screenSize” android：screenOrientation =“ landscape”
> > 2 ：我也是设置横屏开发，接受这个lib，是6.0.3版本的；其他版本应区别不大把。：我在播放里面，直接写死了全屏，也就是进去就是一个全屏播放的节面，那个全屏按钮，我已经屏蔽了
> > 3：如果发现横屏动作，返回横屏动作出现短暂的屏幕旋转的情况，你可尝试这样解决。
> > ```
> > 在退出的逻辑页面，例如调用finish。你做一个延后finish的操作。比如延后300ms调用finish这样。
> > 就不会出现短暂的旋转，反正我最近也折腾这个，按back返回是不会出现这个情况，就是页面代码完成之后，调用finish会这样。
> > 延后finish为什么会正常了，这个还没找到为原因。
> > ```
> > 
> > 
> > 可以看看这个[。https:](https://blog.csdn.net/baidu_36170592/article/details/102702238#comments_12663121) //blog.csdn.net/baidu_36170592/article/details/102702238#comments_12663121
> 
> 谢谢你的回复。
> 不过我这情况不一样，我这儿是APP全部都是横屏状态的，给平板开发嘛，纯横屏的。
> 小窗口播放视频，然后点击全屏播放，调用的detailPlayer.startWindowFullscreen(activity, false, true)
> 然后退出全屏播放，恢复小窗口的时候，会被强制切换到竖屏，导致activity走reCreate了。
> 
> 目前已经临时解决了这个问题，因为不想增加项目moudle了，所以我看了下源代码，然后重写了activity的setRequestedOrientation(requestedOrientation: Int) 方法，注释掉了super.setRequestedOrientation(requestedOrientation)
> 达到了我想要的效果。

感谢提供思路，以后遇到这样情况也有方案了，3q

**Comment by 555chy** [comment]
不是有提供这个方法吗，setOnlyRotateLand
