### ISSUE TITLE
M3U8拖动进度条卡死

### ISSUE THREAD

**Issue by ilovexy2tom** [CarGuo/GSYVideoPlayer#2817]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

m3u8，seekto，特别慢。切换了Exo内核，尝试过其他的流媒体播放。比如xfPlayer,做不到秒播，基本上3-4秒就可以播放。

需要如何配置才能达到一样的效果。

## 问题机型/系统：

真机 红米k20pro android 10.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中切换EXO内核，在Demo写死我的m3u8路径，缓冲至少30秒不动

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请提供测试链接

**Comment by ilovexy2tom** [comment]
http://www.ldshen.com/play/short/30062020158/30062020158.m3u8










在 2020-07-06 16:29:41，"Shuyu Guo" <notifications@github.com> 写道：

请提供测试链接

**Comment by ilovexy2tom** [comment]
http://www.ldshen.com/play/long/0407202025/0407202025.m3u8













在 2020-07-06 16:29:41，"Shuyu Guo" <notifications@github.com> 写道：

请提供测试链接

**Comment by CarGuo** [comment]
感觉像是推流服务的问题

**Comment by ilovexy2tom** [comment]
> 感觉像是推流服务的问题

不是的，我换了一个七牛播放器可以了。

但是我想用你这个库的其他逻辑，包括大小屏旋转，怎么自定义内核呢？

**Comment by CarGuo** [comment]
继承 BasePlayerManager 或者 IPlayerManager 就可以了

**Comment by ilovexy2tom** [comment]
> 继承 BasePlayerManager 或者 IPlayerManager 就可以了

我希望能使用你们的库，这个问题能修复么。我看了你的wiki里面的issue，都没解决。

**Comment by CarGuo** [comment]
这边三种内核的本质一个是 ffmpeg ，一个是 mediacodec ， 本质上所有播放器都是用这两种，所以两种都有问题的时候，本质上不是内核的问题，而是流本身有兼容问题。

七牛用的是应该是 ffmpeg 的吧，这就需要看它和 ijkplayer 在出某些情况下的处理是不是有什么不同，默认下 ijkplayer 都是按照标准做解析和解码的。

**Comment by ilovexy2tom** [comment]
> 这边三种内核的本质一个是 ffmpeg ，一个是 mediacodec ， 本质上所有播放器都是用这两种，所以两种都有问题的时候，本质上不是内核的问题，而是流本身有兼容问题。
> 
> 七牛用的是应该是 ffmpeg 的吧，这就需要看它和 ijkplayer 在出某些情况下的处理是不是有什么不同，默认下 ijkplayer 都是按照标准做解析和解码的。

好的，那我只能去尝试一下了。非常感谢解答。
