### ISSUE TITLE
怎样设置播放器的单击事件 双击事件 的监听器  

### ISSUE THREAD

**Issue by liudaohong** [CarGuo/GSYVideoPlayer#2818]
需要将事件改为 单击暂停  双击点赞

**Comment by CarGuo** [comment]
onTouch 方法你可以直接重载，还有 touchDoubleUp 、onClickUiToggle、touchLongPress 的方法可可以重载

**Comment by liudaohong** [comment]
touchDoubleUp  ，touchLongPress 这两方法没有

**Comment by CarGuo** [comment]
7.1.4有的

**Comment by liudaohong** [comment]
好的 我更新 试下
