### ISSUE TITLE
小窗口模式，默认为位置。

### ISSUE THREAD

**Issue by ZhetengDashen** [CarGuo/GSYVideoPlayer#282]
showSmallVideo  这个方法可否增加两个参数，小窗口默认的位置。

**Comment by CarGuo** [comment]
可以是可以，不过没那么快有新版本喔

**Comment by ZhetengDashen** [comment]
@CarGuo 那我现在要是修改 只能去改源码了。是吧。

**Comment by ZhetengDashen** [comment]
重写了 NormalGSYVideoPlayer  showSmallVideo（） 方法     
      FrameLayout.LayoutParams lp = (LayoutParams) gsyBaseVideoPlayer.getLayoutParams();
        int marginLeft = CommonUtil.getScreenWidth(this.mContext) - size.x;
        lp.setMargins(marginLeft, 0, 0, 0);  放到右上角了。

**Comment by CarGuo** [comment]
这样也可以
