### ISSUE TITLE
播放卡顿率检测

### ISSUE THREAD

**Issue by missu263** [CarGuo/GSYVideoPlayer#2820]
请教播放卡顿率检测，播放卡顿率定义为播放器的消费速度大于播放器下载视频数据的速度。

请问这个这种这个该怎么去检测播放的卡顿率呢？

**Comment by CarGuo** [comment]
onInfo 里面 buffer 不就是卡了么·······

**Comment by missu263** [comment]
> onInfo 里面 buffer 不就是卡了么·······

这个是不是可以用来统计播放的自然卡顿啊，不包括拖进度seek之后的卡顿呢大神

**Comment by CarGuo** [comment]
比如这个 https://github.com/CarGuo/GSYVideoPlayer/issues/2757

**Comment by missu263** [comment]
大佬，顺便反馈一个问题：
我在Demo中的输入URL的播放器中，用如下地址：https://rescdn.yishihui.com/longvideo/transcode/video/2018-12-13/739cc97673bd44dc9d9e94b7642f58691544778829917.m3u8?Expires=1594352189&OSSAccessKeyId=LTAIHZz0zdTMC7HN&Signature=tPnsMxoBAsmCvkKsdK73G7iZKV0%3D
用Wi-Fi开始播放，然后马上切换到4G。等用Wi-Fi播完缓冲之后，视频就进入到AUTO_COMPLETION的状态了呢？。。。。

**Comment by CarGuo** [comment]
理论上应用没内部做了网络监听，如果网络发生变化导致的error会在后面重新new 一个内核去播放。
因为流播放是一个长连接，网络变了自然就断了

**Comment by missu263** [comment]
> 理论上应用没内部做了网络监听，如果网络发生变化导致的error会在后面重新new 一个内核去播放。
> 因为流播放是一个长连接，网络变了自然就断了

现在的情况是，从Wi-Fi切换到4G，缓冲停止加载，等缓冲数据播放完，播放页也没有进入到error了，而是直接回调auto_complete了呢。

但是从4G切换到Wi-Fi，播放器的缓冲还能正常加载。

我看demo中，一开始用Wi-Fi起播后，就切换到4G，也会出现这个情况。

所以我现在在onAutoCompletion做类似于netWorkErrorLogic的重试逻辑。。

实际上现在netWorkErrorLogic如果没有进入到error就不会生效。

困惑🤔️

**Comment by CarGuo** [comment]
如果是切换网络之后 GSYVideoBaseManager 的 onError 没有触发，那就不会走 View 的 onError
