### ISSUE TITLE
小窗口按键关闭

### ISSUE THREAD

**Issue by ShaoB** [CarGuo/GSYVideoPlayer#2821]
您好，怎么区分是小窗口按键关闭，还是主动调用hideSmallVideo关闭。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/2394d7da3ce599c5a8640dd22a4b45fb5fd68df0/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/base/GSYBaseVideoPlayer.java#L924

参考下这个
