### ISSUE TITLE
关于视频播放切换到其他界面，在返回的问题

### ISSUE THREAD

**Issue by yefangqingchen** [CarGuo/GSYVideoPlayer#2824]
版本 ： com.shuyu:GSYVideoPlayer:7.1.4

手机 ：vivo

问题描述：先打开一第一个视频播放界面播放视频，然后在打开一个相同的界面播放视频，从第二个界面返回了第一个界面。
1、第一个界面播放器背景黑色、暂停状态，点击暂停按钮后是从头开始播放的。
2、开始我以为是生命周期没处理好，就继承了GSYBaseActivityDetail去做，效果还是这样。

我用demo试一下，不会黑屏，但是右边的总时长会变成 00:00 且视频不能播放了。

这是啥原因。。

**Comment by CarGuo** [comment]
默认播放内核只有一个，你需要在返回原来的视频时自己做处理，必须重新播放和setseekonstart，你看b站的处理方式。。。。
当然demo也有多内核，不过不推荐

**Comment by yefangqingchen** [comment]
setseekonstart我知道，设置从哪里开始播放

我现在做的是在onRestart中设置 setseekonstart 然后开始播放，但是好像是从新走了一遍流程才跳到具体的播放时间

**Comment by CarGuo** [comment]
对的，setseekonstart 是就是重新播放，还有另外一个ijk内核可用的，也是需要重头播放。

```
VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", startPosition);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
```


一般都是一个播放内核，在 A 播放跳去 B 播放，那么 A 肯定就被释放了，不然 B 怎么播放。
所以返回 A 的时候，再播放 A 肯定是新的链接，从头开发播放。

**Comment by yefangqingchen** [comment]
我记得有个qq付费群的来着，刚才去github上找了下没找到，方便告知一下吗
________________________________
发件人: Shuyu Guo <notifications@github.com>
发送时间: 2020年7月10日 2:46
收件人: CarGuo/GSYVideoPlayer <GSYVideoPlayer@noreply.github.com>
抄送: 夜方轻尘 <yefangqingchen@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [CarGuo/GSYVideoPlayer] 关于视频播放切换到其他界面，在返回的问题 (#2824)


对的，setseekonstart 是就是重新播放，还有另外一个ijk内核可用的，也是需要重头播放。

VideoOptionModel videoOptionModel =

                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", startPosition);

        List<VideoOptionModel> list = new ArrayList<>();

        list.add(videoOptionModel);

        GSYVideoManager.instance().setOptionModelList(list);



一般都是一个播放内核，在 A 播放跳去 B 播放，那么 A 肯定就被释放了，不然 B 怎么播放。
所以返回 A 的时候，再播放 A 肯定是新的链接，从头开发播放。

―

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer#二其他推荐 174815284 @yefangqingchen
