### ISSUE TITLE
startWindowFullscreen方法下，设置view不生效

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2825]
## 问题描述：

重写startWindowFullscreen方法，然后在这个方法的回调下，去设置某个view，然后这个view不生效，没有看到这个view，断点也是能走到的，百思不解

问题代码：(如果有)
```
override fun startWindowFullscreen(context: Context?, actionBar: Boolean, statusBar: Boolean): GSYBaseVideoPlayer {
        val videoPlayer = super.startWindowFullscreen(context, actionBar, statusBar) as KinoVideoPlayer
        if (mUriList.isNotEmpty() && (mUriList[mPlayPosition] as KinoVideoModel).isTryToSee) {
            mLlTryToSee?.visibility = View.VISIBLE
        }
        return videoPlayer
    }
```

**Comment by CarGuo** [comment]
是不是 cloneParams 需要的参数没有执行？

**Comment by wangrunxiang** [comment]
执行了

**Comment by wangrunxiang** [comment]
@CarGuo

**Comment by wangrunxiang** [comment]
而且mUriList这个成员变量，在你的父类的cloneParams上都已经实现了赋值的

**Comment by CarGuo** [comment]
肯定没执行，因为是 (videoPlayer as xxxxx).mLlTryToSee?.visibility = View.VISIBLE

**Comment by wangrunxiang** [comment]
你说的是什么意思？是View也要走cloneParams？

**Comment by wangrunxiang** [comment]
view不是全屏调init的时候，重新findviewbyid了吗？

**Comment by CarGuo** [comment]
你的代码是要这样  (videoPlayer as xxxxx).mLlTryToSee?.visibility = View.VISIBLE 而不是  mLlTryToSee?.visibility = View.VISIBLE

**Comment by wangrunxiang** [comment]
为什么是要videoPlayer. mLlTryToSee ?.visibility = View.VISIBLE这样？不是重新init的时候已经赋值了吗？意思是说startWindowFullscreen回调的时候，还是在非全屏的播放器下回调？然后videoPlayer指的是全屏之后的播放器？

**Comment by wangrunxiang** [comment]
@CarGuo

**Comment by CarGuo** [comment]
val videoPlayer = super.startWindowFullscreen(context, actionBar, statusBar) as KinoVideoPlayer 这句话构建得到的是全屏的对象啊，videoPlayer 被 return 回去的才是你要的全频那个类

**Comment by CarGuo** [comment]
startWindowFullscreen 这句话是非全屏对象调用的

**Comment by wangrunxiang** [comment]
嗯，我刚刚也发现了，明白了

**Comment by wangrunxiang** [comment]
谢谢大佬指导
