### ISSUE TITLE
视频播放完了，想展示一个view

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2826]
## 问题描述：

视频播放完了，想展示一个view，有没有像亮度声音这样的接口，我找了一下没有找到？大佬提示一下？如果没有这样的接口的话，自己要怎么样实现？如果是自己写布局的话，这个view应该在什么时机去展示

**Comment by yefangqingchen** [comment]
VideoAllCallBack接口中的onAutoComplete方法

https://github.com/CarGuo/GSYVideoPlayer/wiki/VideoAllCallBack

**Comment by wangrunxiang** [comment]
所以只可以自己实现？没有像亮度那种方式的接口是吗？

**Comment by wangrunxiang** [comment]
@yefangqingchen @CarGuo

**Comment by yefangqingchen** [comment]
你实现这个接口，播放完之后会回调onAutoComplete这个方法
