### ISSUE TITLE
How to get progress of the video when it is fullscreen mode

### ISSUE THREAD

**Issue by RudreshJR** [CarGuo/GSYVideoPlayer#283]
When using tiny window, from seekbar mProgressBar we will get progress percentage but how to get progress of the video when it is fullscreen mode.. In StandardGSYVideoPlayer in startWindowFullscreen method not using any seekbar

**Comment by CarGuo** [comment]
GSYVideiManager instance . you can get ijkmediaplayer

**Comment by RudreshJR** [comment]
can u just tell from GSYVideoManager instance how to get progress

**Comment by magical-xu** [comment]
long progress2 = GSYVideoManager.instance().getMediaPlayer().getCurrentPosition();
Log.d("magical", "manager: " + progress2);
