### ISSUE TITLE
拖动进度条和屏幕滑动一样效果

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2830]
问题描述：

希望拖动进度条的SeekBar，也和屏幕滑动一样的效果，也就是showProgressDialog，看了一下代码，会很复杂，有没有简便的方法

拖动进度条这部分，应该是覆盖seekbar的两个回调方法onStartTrackingTouch和onStopTrackingTouch，问题在于怎么显示ProgressDialog感觉比较麻烦

大佬们有没有比较好的方式

**Comment by CarGuo** [comment]
有啥问题，就是 showProgressDialog(deltaX, seekTime, mSeekTimePosition, totalTime, totalTimeDuration); 和  dismissProgressDialog 两个方法而已
