### ISSUE TITLE
oppo A59手机，切换全屏或者从全屏切换回来，画面不动

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2831]
## 问题描述：

oppo A59手机，切换全屏或者从全屏切换回来，画面不动，五秒后才会继续播放，但是，这期间五秒过程中，进度条一直会动，其他手机没有发现这个问题

## 问题机型/系统：
oppo a59

## 问题录像
http://dev.wangrunxiang.com/device-2020-07-13-220307.mp4

**Comment by wangrunxiang** [comment]
希望各位大佬帮忙看看 @CarGuo

**Comment by CarGuo** [comment]
Demo 怎么复现？用的什么内核模式

**Comment by wangrunxiang** [comment]
用的exo内核模式，demo上我没有去复现，因为我们用的自己的加密的m3u8，有自己的解密过程，所以就没有去尝试。
渲染模式怎么看？  @CarGuo

**Comment by CarGuo** [comment]
GSYVideoTypesetRenderType    TEXTURE,SUFRACE和GLSURFACE

**Comment by wangrunxiang** [comment]
我没有设置过，看默认值是TEXTURE的

**Comment by CarGuo** [comment]
可以试试  SUFRACE 的

**Comment by wangrunxiang** [comment]
你自己不是注释都说SUFRACE和全屏动画不太兼容吗

**Comment by wangrunxiang** [comment]
如果为了这台手机改成SUFRACE，会不会其他手机也有其他问题，这就坑了

**Comment by CarGuo** [comment]
动画全屏的效果 值得是暂停时的 cover 的全屏，比如 setShowPauseCover 接口你没有打开的话，都差不多，你可以试试

**Comment by wangrunxiang** [comment]
好，我先试试，这个SUFRACE和TEXTURE的区别就是TEXTUREView和SUFRACEview的差别？

**Comment by CarGuo** [comment]
是的～

**Comment by wangrunxiang** [comment]
试了一下GSYVideoType.setRenderType(GSYVideoType. SUFRACEview)，还是一样的效果

**Comment by wangrunxiang** [comment]
有没有可能是编解码或者这个联发科cpu的问题？

**Comment by wangrunxiang** [comment]
@CarGuo

**Comment by CarGuo** [comment]
exo内核虽然是有硬解码，但是感觉不至于啊……你试试ijk内核默认软解码会不会……
另外你可以调试每次这样playermamanger里的surface有没有正常设置和切换

**Comment by wangrunxiang** [comment]
同样的手机，老版本是用rn做的，底层也是用的exo内核，播放是没有问题的

**Comment by wangrunxiang** [comment]
然后就是你说的调试应该怎么样调试？ @CarGuo

**Comment by CarGuo** [comment]
你如果可以，提供下有问题的视频链接，我测试下吧

**Comment by wangrunxiang** [comment]
不是单纯一两个视频有问题，是所有视频都有问题，这些视频我们有一套自己的加密方式，提供给你确实比较麻烦

**Comment by wangrunxiang** [comment]
方便私信个邮箱或者QQ或者微信吧，我把解密的类也一同发给你？

**Comment by wangrunxiang** [comment]
不动的时候是有声音的，还有没有其他什么可能？我再试试先？

**Comment by CarGuo** [comment]
Exo2PlayerManager 的  showDisplay 是不是正常把 surface 设置到 mediaPlayer 里面。

GSYTextureRenderView 的  onSurfaceAvailable 是不是正常创建

**Comment by wangrunxiang** [comment]
这个问题还没解决，先别close吧？

**Comment by CarGuo** [comment]
主要是看你那边能不能找出问题的点，我这边测试是没发现问题………

**Comment by wangrunxiang** [comment]
这两天没时间去调试，先开着吧，过两天有时间我再调调
