### ISSUE TITLE
有人用这个来做详情页的banner吗？

### ISSUE THREAD

**Issue by MYaoDan** [CarGuo/GSYVideoPlayer#2832]
关于继续播放和暂停播放有问题想要请教大佬。QQ774629431

**Comment by CarGuo** [comment]
？？？？

**Comment by MYaoDan** [comment]
> ？？？？
大佬，我从详情页暂停视频播放，但是从该详情页跳转下一个详情页后，下一个详情页会播放上一个详情页的声音，我在finish()方法里面调用了GSYVideoManager.releaseAllVideos();

**Comment by CarGuo** [comment]
不明白你的问题，A -> B ，B finish GSYVideoManager.releaseAllVideos();？？？？
