### ISSUE TITLE
视频切换全屏主题，及进度拖动问题

### ISSUE THREAD

**Issue by Ysrfengnull** [CarGuo/GSYVideoPlayer#2833]
1.切换全屏，主题tab 颜色是白色
![image](https://test-static-public-log56-com.oss-cn-hangzhou.aliyuncs.com/kydd_app/test/device-2020-07-14-151849.png)
2.进度拖动问题
####  全局设置
``` java 
 VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
```
在页面销毁后需要还原设置吗

**Comment by CarGuo** [comment]
？？？？不理解
