### ISSUE TITLE
为什么静音方法不管用？

### ISSUE THREAD

**Issue by MYaoDan** [CarGuo/GSYVideoPlayer#2835]
我在详情页设置 GSYVideoManager.instance().setNeedMute(true)后，视频播放完毕重新播放，声音还是会播放出现

**Comment by CarGuo** [comment]
这个需要每次播放设置

**Comment by MYaoDan** [comment]
我重写了clickStartIcon()方法，然后调用了 GSYVideoManager.instance().setNeedMute(true);，还是不管用，第一次静音播放完，重新播放第二次还是会有声音，请问大佬，应该在哪调用？

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setPlayerInitSuccessListener 的 onPlayerInitSuccess 里面设置
或者在 VideoCallback 的 onPrepared
