### ISSUE TITLE
setRotateViewAuto好像不生效

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2836]
## 问题描述：

manifest配置了这个activity为portrait，系统的旋转锁定没有锁，是打开的，然后希望不会跟随系统旋转而旋转，setRotateViewAuto为false，发现没效果，手机旋转横屏，播放器自动全屏了

所以如果想达到上述效果，应该什么样的姿势？

**Comment by CarGuo** [comment]
orientationUtils.setRotateWithSystem(false);
和 
player.setRotateWithSystem
两个

**Comment by wangrunxiang** [comment]
/**
     * 是否更新系统旋转，false的话，系统禁止旋转也会跟着旋转
     *
     * @param rotateWithSystem 默认true
     */
    public void setRotateWithSystem

player的setRotateWithSystem的注释是说，false，系统禁止旋转也会跟着旋转，我理解的意思是，突破系统锁定屏幕的限制，去跟随系统旋转而已，但是我的目的是不跟随系统旋转，而不是突破系统限制

**Comment by CarGuo** [comment]
那就是  setRotateViewAuto 和  orientationUtils.setEnable(false);

**Comment by wangrunxiang** [comment]
两个同时设置？

**Comment by CarGuo** [comment]
是的

**Comment by wangrunxiang** [comment]
但是GSYBaseVideoPlayer下的mOrientationUtils要在resolveFullVideoShow方法在实例化，如果没有跑到这个方法的话，都是null，设置不了吧？

**Comment by CarGuo** [comment]
orientationUtils.setEnable(false); 是外部的那个，比如  detailplayer 里，而 


而内部的 ori 主要是和 onConfigurationChanged 和 setRotateViewAuto 有关系，比如  resolveFullVideoShow

   mOrientationUtils.setEnable(isRotateViewAuto());

**Comment by wangrunxiang** [comment]
你是说在GSYBaseActivityDetail的成员变量的那个？这个跟activity绑定了？想在StandardGSYVideoPlayer内部做这部分设置，操作不了？

**Comment by wangrunxiang** [comment]
initObserver()
        initListener()
        initVideoBuilderMode()
        orientationUtils.isEnable = false
        detail_player.isRotateWithSystem = false

这两个都设置了，还是能跟着手机旋转而全屏

**Comment by CarGuo** [comment]
哦，如果你说的是 GSYBaseActivityDetail ，你只需要把 getDetailOrientationRotateAuto 就好了·····

**Comment by wangrunxiang** [comment]
嗯，但是只有这个办法了吗？其实不希望这个逻辑在Activity这一层，按职责分割的话，这种旋转逻辑应该是要在player里面的吧？在player里面有办法控制吗？

**Comment by wangrunxiang** [comment]
getDetailOrientationRotateAuto我看了一下只在两个地方调用onPrepared和onPrepared，如果是在播放中，因为某些条件改变这个值，不生效

**Comment by CarGuo** [comment]
………大哥，你看源码啊，事实上你都可以不用这个activity啊！！！！！！

**Comment by wangrunxiang** [comment]
我知道我可以不用这个activity，但是不是你们文档说让我们这么去用简单吗？

**Comment by wangrunxiang** [comment]
但是这个getDetailOrientationRotateAuto只有在onStartPrepared和onPrepared调用，在过程中要修改不能让他旋转的话，要怎么修改方便？

**Comment by CarGuo** [comment]
我不是很明白你的问题， orientationUtils 你拿不到吗？它是protected 的啊！！！

**Comment by wangrunxiang** [comment]
orientationUtils 设置早了的话 会被getDetailOrientationRotateAuto的返回值给覆盖，这个方法还是抽象方法

**Comment by CarGuo** [comment]
> 在过程中要修改不能让他旋转的话

你什么时候就看你需要呗，自己组合下，代码都在那里····

**Comment by wangrunxiang** [comment]
好吧。。。。。。。
