### ISSUE TITLE
在RecyclerView中使用，封面会被清除的问题

### ISSUE THREAD

**Issue by shejishi** [CarGuo/GSYVideoPlayer#284]
框架很不错哇，使用起来很舒服。
现在遇到一个问题，在RecyclerView中使用的时候，滑动出屏幕的时候会出现
封面变黑的问题（不知道有没有人遇到）

我的处理方法是将holder中的thumbIv变为成员变量，在加载的时候去掉
demo中的thumbIv.getParent() !=null 的判断。

目的是让每一个都拥有一个实例，不被清除

**Comment by CarGuo** [comment]
具体是哪个Activity的模式？？？

**Comment by shejishi** [comment]
@CarGuo 

![_20170624095345](https://user-images.githubusercontent.com/16817857/27504778-7f9fa978-58c3-11e7-89e6-560597173bbe.png)

具体是这个holder中使用，我直接使用 你的StandardGSYVideoPlayer在项目中，同样会出现滑动出去屏幕
的图片会直接被清除，后面我修改了这个holder里面的代码，将ImageView直接修改为成员变量之后就不会出现这种问题，我是加载网络图片的，一般项目里面都会使用网络图片，使用本地图片的很少吧：

![_20170624100155](https://user-images.githubusercontent.com/16817857/27504818-5ddde920-58c4-11e7-84cc-0dd27cac51d6.png)
