### ISSUE TITLE
长按和长按抬起事件

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2840]
## 问题描述：

按照#1538的方式去写了个GestureDetector,在init的时候赋值给成员变量gestrueDetector，但是看了一下只有一个onLongPress方法，监听不到长按之后的抬起。
如果是常规的话，setOnLongClickListener和cancelLongClick就能监听到长按抬起事件，但是父类中的gestrueDetector覆盖了setOnLongClickListener，我应该怎么去处理？

**Comment by CarGuo** [comment]
不是有个onTouch的可以重载么？

**Comment by wangrunxiang** [comment]
我重载了onIntercept去拦截up事件 判断之前触发过onLongPress的话，就是长按事件的抬起
  onTouch感觉有点难做到

**Comment by CarGuo** [comment]
这个还是看你们需求了。
