### ISSUE TITLE
miui12和一加手机的旋转全屏

### ISSUE THREAD

**Issue by Alexxiaopang** [CarGuo/GSYVideoPlayer#2842]
测试机型：小米9，miui12
版本：7.1.4
miui12使用的是android10的手势，会有底部手势小白条（下面简称小白条）
使用视频的全屏之后，底部小白条消失了（不使用视频控件，直接全屏是有小白条的）
期望：请问全屏做了什么操作会让小白条消失，能否保留这个小白条？谢谢

**Comment by CarGuo** [comment]
代码里屏蔽了nav bar

**Comment by Alexxiaopang** [comment]
但是这不是Q导航栏推荐的方式，强制隐藏会出现出现各种问题，我尝试setHide(false),但是双击又变成了true，还有旋转回来也会出现问题

**Comment by CarGuo** [comment]
这个是默认行为，你可以重载对应方法去自定义
