### ISSUE TITLE
修改黑色背景颜色

### ISSUE THREAD

**Issue by meanhan** [CarGuo/GSYVideoPlayer#2845]
视频尺寸没有全屏时 怎么修改空余部分黑色背景颜色

 GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

**Comment by CarGuo** [comment]
????????

**Comment by meanhan** [comment]
![Screenshot_2020-07-20-15-30-41-365_com luckybird sport](https://user-images.githubusercontent.com/19726739/87911700-a3cd3680-ca9e-11ea-8f21-7784960fc1d4.jpg)

这种 视频尺寸就这么大   不是全屏时   上下黑色区域 怎么修改成其他颜色

**Comment by ff-frida** [comment]
你需要继承播放器，然后自己重写xml。修改xml布局的bg就可以了。你可以试试，

**Comment by clp334264003** [comment]
同问，如何让封面作为背景图片哈

**Comment by CarGuo** [comment]
看 demo 的 effect 目录，自己看 GSYVideoGLViewCustomRender 、 GSYVideoGLViewCustomRender4 ，自己加对应的 OpenGL 处理
