### ISSUE TITLE
两套布局控制UI没反应

### ISSUE THREAD

**Issue by yefangqingchen** [CarGuo/GSYVideoPlayer#2847]
有两套UI : 竖屏布局、横屏布局

横屏布局中的一些控件在竖屏布局中是没有的，我控制横屏布局中的某些控件隐藏和显示没反应，难道必须两套布局中的控件都要有才能操作吗 ？

**Comment by CarGuo** [comment]
参考 LandLayoutVideo ，另外外部控制用 player.getCurrentPlayer()

**Comment by yefangqingchen** [comment]
有日志开关吗

**Comment by yefangqingchen** [comment]
不知道为什么播放器黑屏了，没有错误日志

**Comment by yefangqingchen** [comment]
我就是在全屏的时候，发送通知切换下一集，就黑屏了。
竖屏的时候没毛病，，

**Comment by yefangqingchen** [comment]
卧槽，我找到原因了

**Comment by yefangqingchen** [comment]
竖屏切换下一集的时候是用的下面这3行代码，是正常的，但是横屏还这么用不行
videoPlayer.setUp(it.codes[0].cUrl, true, it.mName)
videoPlayer.seekOnStart = (viewModel.watchModel!!.duration * 1000).toLong()
videoPlayer.currentPlayer.startPlayLogic()
横屏要这样，使用当前currentPlayer，才正常。
videoPlayer.currentPlayer.setUp(it.codes[0].cUrl, true, it.mName)
videoPlayer.currentPlayer.seekOnStart = (viewModel.watchModel!!.duration * 1000).toLong()
videoPlayer.currentPlayer.startPlayLogic()

**Comment by hponiang** [comment]
建议作者把这个重点提示一下，我也是碰到类似问题，全屏时控制 不了状态，搞了半天，才发现
