### ISSUE TITLE
全屏播放广告后回到正常视频但是视频自己暂停不动了，画面不动声音还是继续的

### ISSUE THREAD

**Issue by liuxusuifeng** [CarGuo/GSYVideoPlayer#2848]
## 问题描述：

全屏下视频中途播放广告，播放完广告后切回正常视频的时候只有声音没有画面了，画面暂停在了播放广告前的最后一帧，会有暂停按钮弹出，但是点击按钮也不能播放视频，声音却是正常播放的，无论是否按暂停键，但是非全屏状态下播放完广告是能正常播放的，请问我是哪里配置没对吗？Demo是没问题的，我是按照demo自己写了一遍，在react-native上运行的

## 问题机型/系统：

红米10

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中没问题

**Comment by liuxusuifeng** [comment]
用Layout Inspector查看的时候发现全屏广告播放完后，全屏广告的那个Layout层还存在，没有消失，只是它底下的player状态设置为gone了而已，请问是跟这个有关系吗？

**Comment by CarGuo** [comment]
Demo 中没有问题·····我没办法啊····如果有声音没有画面，基本上就是 Surface 的设置问题，你调试下 PlayerManager 的 Surface 是不每次切换都正常设置····

**Comment by javakam** [comment]
发现在使用 "系统模式" 时会出现这个问题, 再改用"Exo2PlayerManager"后这个问题没有了, 但是偶尔会有绿屏问题
PlayerFactory.setPlayManager(SystemPlayerManager::class.java) //系统模式

型号:华为Mate30 Pro 5G 版本, HarmonyOS 2
版本: v8.1.5-jitpack
