### ISSUE TITLE
用StandardGSYVideoPlayer怎么设置视频的清晰度？

### ISSUE THREAD

**Issue by TimberBug** [CarGuo/GSYVideoPlayer#285]
如题，怎么设置视频的清晰度？

**Comment by CarGuo** [comment]
看demo SampleVideo，清晰度是外部实现的

**Comment by TimberBug** [comment]
用这个播放m3u8视频的时候在视频播放一段时间后自动暂停了，日志一直不停的在打印这个
![image](https://user-images.githubusercontent.com/18308932/27470409-551c51f8-5826-11e7-8add-9ff5b31d1ebb.png)这是什么情况？

**Comment by CarGuo** [comment]
感觉就像是M3u8的切片和ijk之间的荣村问题，你试过其他M3u8没？

**Comment by TimberBug** [comment]
别的M3U8的没有试过，这个问题我也就发现 了一次，那这个问题现在还没有解决的方法是吧？

**Comment by CarGuo** [comment]
如果是某些m3u8的问题，那么就是ijk的容错能力问题，这个目前还没有什么解决方法，除非修正m3u8源。

**Comment by TimberBug** [comment]
还有就是在刚开始是正常播放的情况下将网络给关掉，一段时间后，视频卡住，日志上也会一直打印这个

**Comment by CarGuo** [comment]
哦，那就是断网重连的情况，断网之后，再连网是需要做特殊处理的，原本的长连接ijk断开了，需要重新处理实例，这一块的异常处理下个版本增加

**Comment by TimberBug** [comment]
现在的这个版本有没有对网络断开后视频播放异常处理的方法呢？那些回调方法只是在刚启动时如果没网的话才会调用，在播放期间将网络断开后是不会回调的

**Comment by CarGuo** [comment]
onError

**Comment by TimberBug** [comment]
还有一个问题就是添加上混淆后，在打包的时候开启混淆就会报这个错误
![image](https://user-images.githubusercontent.com/18308932/27529622-ce201c16-5a87-11e7-9da8-bd3c08c664ea.png)，将混淆关闭后就可以打包成功，这是怎么回事？

**Comment by CarGuo** [comment]
不是很理解，不过混淆的话，可以在首页复制gsy的混淆配置
