### ISSUE TITLE
横竖屏状态异常

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2850]
## 问题描述：

从播放器横屏去到别的页面，然后别的页面切换了成了竖屏，然后finish掉那个页面，回到播放器，播放器变成竖屏了，但是也不是xml的那个竖屏，是另外一个，就像将播放器里面的横屏的那个xml拉成竖屏一样
如视频所示http://dev.wangrunxiang.com/device-2020-07-21-174826.mp4

切换是通过陀螺仪感应切换的

如果我想回来之后还是横屏的，或者即使不是横屏的，回来是竖屏的话，是自己的那个xml的样式
```
override fun getLayoutId(): Int {
        return if (mIfCurrentIsFullscreen) {
            R.layout.video_layout_kino_fullscreen
        } else R.layout.video_layout_kino
    }
```

**Comment by yefangqingchen** [comment]
你可以记录当前播放器是否横屏，在回来的时候，使用代码让播放器还原到之前的状态

**Comment by wangrunxiang** [comment]
@yefangqingchen 是可以这样子没错，也可以这么做，这么做也不太费事，但是，有几个问题吧，第一个，有个切换的过程，会有一些延迟也一些画面？  第二个，我想知道的是这种情况GSY框架有没有考虑到，想用更优雅的方式解决，或者说这仅仅是我用的姿势不对而已

**Comment by yefangqingchen** [comment]
1、设置setShowPauseCover否需要加载显示暂停的cover图片（或者暂停的时候获取当前进度的画面截图）
2、activity生命周期onPause时候记录当前播放进度videoPlayer.currentPositionWhenPlaying
3、记录当前播放器状态

等到activity onRestart 的时候在根据这些保存的值去设置播放器

**Comment by wangrunxiang** [comment]
@CarGuo 大佬有更好的方法吗？

**Comment by CarGuo** [comment]
自己外部做监听处理

**Comment by wangrunxiang** [comment]
@CarGuo 外部做监听然后怎么处理？可以详细说说吗？

**Comment by yefangqingchen** [comment]
说得应该是让你使用VideoAllCallBack去做外部监听
https://github.com/CarGuo/GSYVideoPlayer/wiki/VideoAllCallBack

**Comment by wangrunxiang** [comment]
@yefangqingchen @CarGuo AllCallBack的哪个方法能监听这种情况？

**Comment by yefangqingchen** [comment]
其实回到当前界面之后可以调用方法回到横屏。。。resolveByClick

**Comment by yefangqingchen** [comment]
其实回到当前界面之后可以调用方法回到横屏。。。
resolveByClick
startWindowFullscreen

**Comment by wangrunxiang** [comment]
所以那个使用横屏xml布局的竖屏的是叫竖屏？

**Comment by wangrunxiang** [comment]
其实为什么会出现这种情况？

**Comment by wangrunxiang** [comment]
VideoAllCallBack好像也没有resolveByClick方法

**Comment by wangrunxiang** [comment]
@CarGuo 大佬给一套官方指引？

**Comment by wangrunxiang** [comment]
我试了一下在onpause的时候记下来isIfCurrentIsFullscreen，在onresume的时候，判断记下来的isIfCurrentIsFullscreen为true的话，就startWindowFullscreen，没效果

**Comment by CarGuo** [comment]
我看下视频里，你返回的时候 activity 变成了竖直的，你需要判断后去旋转 activity 为横屏呀，比如调用下orientationUtils 的  resolveByClick

**Comment by wangrunxiang** [comment]
resolveByClick是旋转成横屏的吧，如果这个时候想要旋转成竖屏，有方法吗？

**Comment by wangrunxiang** [comment]
有和resolveByClick相对应的方法吗 @CarGuo @yefangqingchen

**Comment by CarGuo** [comment]
我这边测试情况是政策的，具体你只能靠自己了

**Comment by wangrunxiang** [comment]
行，前面的兄弟的讨论大概了解了
