### ISSUE TITLE
进度条小窗口预览

### ISSUE THREAD

**Issue by yefangqingchen** [CarGuo/GSYVideoPlayer#2852]
我想问下进度条小窗口预览这个demo在哪啊。？

**Comment by yefangqingchen** [comment]
额，找到了，在PreViewGSYVideoPlayer中，但是快速滑动的时候小窗口好像都是黑的。

**Comment by CarGuo** [comment]
因为用的是 Glide 去下载帧图片，会比较耗费资源。

**Comment by yefangqingchen** [comment]
使用Glide确实有点慢，有什么推荐的吗 /

**Comment by CarGuo** [comment]
系统的 MediaCodec 或者 服务器本身就切好了一批帧图给你
