### ISSUE TITLE
回调onPlayError

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2854]
## 问题描述：

播放一段m3u8视频：https://549-cn-north-4.cdn-vod.huaweicloud.com/asset/511543e80e1078e509b6790ff004f0b4/play_video/22c51acba2c5408b5a8d5f90f03e1f1e_0.m3u8

回调onPlayError，一直断点跟踪，跟踪到ExoPlayerImpl的handleEvent方法，走了ExoPlayerImplInternal.MSG_ERROR这个分支条件，查看了一下playbackError方法，detailMessage成员变量的值是
java.io.IOException: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH

没明白什么意思

**Comment by wangrunxiang** [comment]
@CarGuo

**Comment by CarGuo** [comment]
加解密有有问题呗

**Comment by wangrunxiang** [comment]
这个onPlayError回调的object应该是怎么看，好像不跟代码看不出来个所以然

**Comment by CarGuo** [comment]
onPlayError 没什么，就是简单告诉你 GG 了

**Comment by wangrunxiang** [comment]
那哪个接口有原因？

**Comment by CarGuo** [comment]
没有

**Comment by wangrunxiang** [comment]
那我们要怎么看是什么原因？

**Comment by CarGuo** [comment]
ijk 内核的你看 IjkMediaPlayer 的基类 IMediaPlayer

```
  int MEDIA_ERROR_UNKNOWN = 1;
    int MEDIA_ERROR_SERVER_DIED = 100;
    int MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK = 200;
    int MEDIA_ERROR_IO = -1004;
    int MEDIA_ERROR_MALFORMED = -1007;
    int MEDIA_ERROR_UNSUPPORTED = -1010;
    int MEDIA_ERROR_TIMED_OUT = -110;
```


Exo 内核看 IjkExo2MediaPlayer 的 onPlayerError \ onLoadError  \ onDrmSessionManagerError 等

**Comment by wangrunxiang** [comment]
IjkExo2MediaPlayer这个类中的IjkExo2MediaPlayer \ onLoadError \ onDrmSessionManagerError 方法体好像全都是空的？
@CarGuo

**Comment by wangrunxiang** [comment]
IjkExo2MediaPlayer怎么样能打印自己日志，我不想源码依赖？继承一个子类？继承了子类之后是哪个接口设置给框架?
@CarGuo

**Comment by CarGuo** [comment]
你可以自定义 PlayerManager ，你参考 demo 的 exo 目录，就可以自定义 exo 的 playermanager

**Comment by wangrunxiang** [comment]
我是写了个IjkExo2MediaPlayer的子类来复写onPlayerError \ onLoadError \ onDrmSessionManagerError，然后本来打算继承Exo2PlayerManager去复写他的initVideoPlayer方法，但是发现mediaplayer这个成员变量是私有的，无法在子类赋值，所以后面就只能复制一个Exo2PlayerManager出来，虽然说可以达到目的，但是有点不优雅，有更优雅的方式吗？

**Comment by CarGuo** [comment]
你继承 BasePlayerManager

**Comment by wangrunxiang** [comment]
本来Exo2PlayerManager也是继承BasePlayerManager，复制一份Exo2PlayerManager出来也就是等于继承了BasePlayerManager了

**Comment by CarGuo** [comment]
嗯嗯～其实就是这样呀，因为 mediaPlayer 设置了 private ，也就这样了
