### ISSUE TITLE
封面到播放的中间会出现短暂的黑屏，怎么解决呢

### ISSUE THREAD

**Issue by MYaoDan** [CarGuo/GSYVideoPlayer#2855]
封面到播放的中间会出现短暂的黑屏，怎么解决呢

_Originally posted by @liguoyue in https://github.com/CarGuo/GSYVideoPlayer/issues/409#issuecomment-563910900_
请问该如何解决

**Comment by liguoyue** [comment]
换了一个播放器



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MYaoDan <notifications@github.com&gt;
发送时间: 2020年7月22日 11:21
收件人: CarGuo/GSYVideoPlayer <GSYVideoPlayer@noreply.github.com&gt;
抄送: liguoyue <435264945@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[CarGuo/GSYVideoPlayer] 封面到播放的中间会出现短暂的黑屏，怎么解决呢 (#2855)





 
封面到播放的中间会出现短暂的黑屏，怎么解决呢
 
Originally posted by @liguoyue in #409 (comment)
 请问该如何解决

**Comment by MYaoDan** [comment]
> 换了一个播放器 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MYaoDan <notifications@github.com&gt; 发送时间: 2020年7月22日 11:21 收件人: CarGuo/GSYVideoPlayer <GSYVideoPlayer@noreply.github.com&gt; 抄送: liguoyue <435264945@qq.com&gt;, Mention <mention@noreply.github.com&gt; 主题: 回复：[CarGuo/GSYVideoPlayer] 封面到播放的中间会出现短暂的黑屏，怎么解决呢 (#2855) 封面到播放的中间会出现短暂的黑屏，怎么解决呢 Originally posted by @liguoyue in #409 (comment) 请问该如何解决 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你换的什么播放器啊？

**Comment by liguoyue** [comment]
你搜一下，dkplayer，不知道符合你要求不！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MYaoDan <notifications@github.com&gt;
发送时间: 2020年7月22日 11:26
收件人: CarGuo/GSYVideoPlayer <GSYVideoPlayer@noreply.github.com&gt;
抄送: liguoyue <435264945@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[CarGuo/GSYVideoPlayer] 封面到播放的中间会出现短暂的黑屏，怎么解决呢 (#2855)
