### ISSUE TITLE
回调 onClickStartError  导致的异常

### ISSUE THREAD

**Issue by wulileon** [CarGuo/GSYVideoPlayer#2856]
## 问题描述：

程序代码参考 demo 中 SimplePlayer.java

播放单个视频完成后,  点击播放按钮出现问题:
1. 由于抛出 onClickStartError 异常,  代码中对这个异常做了退出当前 播放的 activity 处理;
2. 当播放完成后, 点击播放按钮,  返回到上一个activity,   这个activity 出现 销毁重新创建的问题;
3. 跟踪发现,  库中 startButtonLogic() 方法中 判断状态逻辑有问题导致抛出  onClickStartError 异常, 然后继续执行  prepareVideo(),  而我的程序又结束activity 才导致错误
4. onClickStartError() 中不做任何处理没有这个异常发生;
 
## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4

## Demo中的复现步骤

Demo 不复现

问题代码：
```
    /**
     * 开始播放逻辑
     */
    protected void startButtonLogic() {
        if (mVideoAllCallBack != null && mCurrentState == CURRENT_STATE_NORMAL) {
            Debuger.printfLog("onClickStartIcon");
            mVideoAllCallBack.onClickStartIcon(mOriginUrl, mTitle, this);
        } else if (mVideoAllCallBack != null) {                                  //  此时状态为: CURRENT_STATE_AUTO_COMPLETE ,  抛 onClickStartError 异常
            Debuger.printfLog("onClickStartError");
            mVideoAllCallBack.onClickStartError(mOriginUrl, mTitle, this);
        }
        prepareVideo();
    }

```

**Comment by CarGuo** [comment]
Demo 不复现?????

**Comment by wulileon** [comment]
> Demo 不复现?????
 
demo 没有在 onClickStartError 中做 finish activity 动作, 所有不会复现,  但是库里面 GSYVideoView.startButtonLogic()  没有对 CURRENT_STATE_AUTO_COMPLETE 做判断.  

也就是说,   如果单个视频播放完成了,  点击播放按钮, 一定会抛一个 onClickStartError() 回调

**Comment by CarGuo** [comment]
这里不是有判断吗？

```
    protected void startButtonLogic() {
        if (mVideoAllCallBack != null && (mCurrentState == CURRENT_STATE_NORMAL
                || mCurrentState == CURRENT_STATE_AUTO_COMPLETE)) {
            Debuger.printfLog("onClickStartIcon");
            mVideoAllCallBack.onClickStartIcon(mOriginUrl, mTitle, this);
        } else if (mVideoAllCallBack != null) {
            Debuger.printfLog("onClickStartError");
            mVideoAllCallBack.onClickStartError(mOriginUrl, mTitle, this);
        }
        prepareVideo();
    }

```

**Comment by wulileon** [comment]
我看了一下 commit,  这个是在 #2766 修复的问题,  所以目前的 7.1.4 版本aar 还没有修复.   close 这个吧, 不好意思

**Comment by CarGuo** [comment]
还没发布，应该7月底或者8月初会更新
