### ISSUE TITLE
progressDialog在横竖屏切换时异常

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2857]
## 问题描述：

手指左右滑动显示progressdialog，但是不松开手指，然后切换横屏，出现异常
如视频所示：http://dev.wangrunxiang.com/device-2020-07-22-231840.mp4
试过在startWindowFullscreen中使用dismissProgressDialog()和videoPlayer.dismissProgressDialog()，还是有问题，只是概率小了而已

**Comment by CarGuo** [comment]
你在点击的时候去  dismiss ······

**Comment by wangrunxiang** [comment]
哪里点击？完全没有点击，是滑动的，滑动了之后手指不放开，然后旋转屏幕

**Comment by CarGuo** [comment]
哦，你说自动选择的，那就是 onConfigurationChanged 之类地方，源码就在那里，自己调试下就知道这么适配了～问题不大

**Comment by wangrunxiang** [comment]
这种根据陀螺仪旋转的叫自动选择？
