### ISSUE TITLE
How to disable/enable control view with StandardGSYVideoPlayer

### ISSUE THREAD

**Issue by Nak9009** [CarGuo/GSYVideoPlayer#2858]
How to disable/enable control view with StandardGSYVideoPlayer ?

**Comment by CarGuo** [comment]
like EmptyControlVideo ?

**Comment by Nak9009** [comment]
Yesh . But I want use toggle button to show control view and hide control view base on StandardGSYVideoPlayer.

**Comment by CarGuo** [comment]
you can override `onClickUiToggle`
