### ISSUE TITLE
大佬播放rtsp，音频是pcm_alaw，然后重现编译了os,依旧没有声音，请问是还要配置什么吗？

### ISSUE THREAD

**Issue by zijin2014** [CarGuo/GSYVideoPlayer#2859]
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_alaw"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_mulaw"

**Comment by CarGuo** [comment]
一般就是 

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_alaw"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_mulaw"

怀疑是不是没编译上·····

**Comment by zijin2014** [comment]
我在试一下

**Comment by zijin2014** [comment]
我删除了这些文件，编译后生成了，但是始终没有声音
![image](https://user-images.githubusercontent.com/9624595/88266242-77fdbb00-cd01-11ea-886a-902dff902e84.png)
是否是rtsp播放需要带声音，要开启什么？

**Comment by CarGuo** [comment]
木有，有测试 url 么

**Comment by zijin2014** [comment]
记录仪走局域网的，没法提供地址呢

**Comment by zijin2014** [comment]
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=nellymoser"
大佬是不是这个原因，我网上找到一个结果

**Comment by CarGuo** [comment]
Nellymoser 是独立的编码吧···

**Comment by zijin2014** [comment]
我改了这个也没效果，这是我的视频信息
![2a7a76e1f05446bd288fadfeccb11b7](https://user-images.githubusercontent.com/9624595/88355963-eb064080-cd98-11ea-8179-2ddf1fc07540.jpg)

**Comment by CarGuo** [comment]
类似问题只能你自己去调试了，issue 不属于 gsy 下的了哦～good luck
