### ISSUE TITLE
进度条小窗口预览怎么没有

### ISSUE THREAD

**Issue by AndMy** [CarGuo/GSYVideoPlayer#286]
进度条小窗口预览怎么没有？gif图片明明有的
每个视频都看过了，没有啊

**Comment by CarGuo** [comment]
有一个 https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer/src/main/java/com/shuyu/gsyvideoplayer/video/CustomGSYVideoPlayer.java  但是对本地视频还行，网络视频效果不好

**Comment by leveychen** [comment]
会自动抓取视频的某一帧，但是对于网络视频，预览图的出现时间很慢。将就用
