### ISSUE TITLE
播放直播源m3u8卡顿问题

### ISSUE THREAD

**Issue by hjzlzh123** [CarGuo/GSYVideoPlayer#2860]
请问我用so文件播放m3u8，卡顿严重，该用什么办法优化呢？（直播源：http://ivi.bupt.edu.cn/hls/cctv5phd.m3u8）

**Comment by CarGuo** [comment]
我这边测试这个链接，没有卡顿啊

**Comment by hjzlzh123** [comment]
![image](https://user-images.githubusercontent.com/30074082/88353916-d8d4d400-cd91-11ea-80d7-974451158aa0.png)
我编译了一个so文件，也尝试用了上面的so文件，两个so文件对ijkplayer的potion进行了配置，播放的时候也有卡顿，当然这也有可能网络问题造成卡顿，请问如果用了你的so文件，对ijkplayer直播的option有什么配置建议

**Comment by hjzlzh123** [comment]
![image](https://user-images.githubusercontent.com/30074082/88354214-cb6c1980-cd92-11ea-8a4b-5cca597aa80e.png)

上图是我的直播配置，请问有什么需要优化的吗

**Comment by CarGuo** [comment]
具体参数得你自己按照实际情况去调整，目前我这边测试是没问题～

**Comment by hjzlzh123** [comment]
好的，感谢




------------------&nbsp;原始邮件&nbsp;-----------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月4日(星期二) 下午2:12
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"祝磊"<1240993252@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 播放直播源m3u8卡顿问题 (#2860)





 
具体参数得你自己按照实际情况去调整，目前我这边测试是没问题～
