### ISSUE TITLE
duplicate definition of library class

### ISSUE THREAD

**Issue by coderLeng** [CarGuo/GSYVideoPlayer#2861]
## 问题描述：
![image](https://user-images.githubusercontent.com/15138573/88275844-a20aa980-cd10-11ea-8a83-ab75f6ed7b03.png)
打正式包的时候这两个类和android系统的重复了

## 问题机型/系统：

 真机 小米note2 Android7.0

## GSY依赖版本

 `implementation 'com.shuyu:GSYVideoPlayer:7.1.4'`

##Log
Reading library jar [C:\Users\zc\AppData\Local\Android\Sdk\platforms\android-29\android.jar]
Note: duplicate definition of library class [android.util.FloatProperty]
Note: duplicate definition of library class [android.util.IntProperty]

**Comment by CarGuo** [comment]
我这边测试正常
