### ISSUE TITLE
##我是自定义的GSY播放器全屏问题   我小屏 所有效果都可以实现 但是全屏后方法走完 ，不走我自定义UI 控件，因为我的广告是附在最外层的 小屏没问题 但是全屏的时候设置显示都不显示，楼主这是什么问题呢   而且控件我找出ID放到克隆参数里面也没有用

### ISSUE THREAD

**Issue by MyNameGty** [CarGuo/GSYVideoPlayer#2862]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
重载 cloneParams ，全屏方法和恢复小屏幕方法，看标准播放器全屏方法的内部实战。

外部获取要用player.getCurrentPlayer()

**Comment by MyNameGty** [comment]
> 重载cloneParams，全屏方法和恢复小屏幕方法，看标准播放器全屏方法的内部实战。
> 
> 外部获取要用player.getCurrentPlayer（）

有几个问题 1. 横屏之后有声音没画面   2.自己写的横屏 竖屏控件  点击以后 调用的也是GSY自带的方法   横屏切换竖屏 显示是竖屏状态 但是屏幕没有竖过来 清单文件啥的都检查了  下面这个是 自定义屏幕切换的按钮点击实现

if(GSYVideoManager.isFullState(activity)){
                        gsyVideo.onBackFullscreen();
                    }else{
                        orientationUtils = new OrientationUtils(activity,gsyVideo);
                        orientationUtils.resolveByClick();
                        gsyVideo.getCurrentPlayer().startWindowFullscreen(activity, true, true);
                    }

**Comment by CarGuo** [comment]
参考 demo 把·

**Comment by MyNameGty** [comment]
是不是全屏的时候需要一一处理

**Comment by MyNameGty** [comment]
GSY横屏播放的时候 上方覆盖的广告View 不显示   您遇见过吗

**Comment by CarGuo** [comment]
参考 StandardGSYVideoPlayer 的 cloneParams \ startWindowFullscreen

**Comment by MyNameGty** [comment]
我用了您的方法  View的 IsVisbile 已经是true 了 他其实已经隐藏显示出来了，但是看不到 是不是 GSY播放器不允许横屏的时候在他上面写View呢

**Comment by CarGuo** [comment]
GSY的View在横屏幕时是加到 DecorView 上，你可以这么理解

**Comment by MyNameGty** [comment]
那我如何在横屏的时候把整个屏幕 附上一层 View 显示广告呢

**Comment by CarGuo** [comment]
你直接区分横屏和竖屏的布局不就好了

**Comment by MyNameGty** [comment]
他是被覆盖住了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuyu Guo"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午3:44
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;; 
抄送: "1435692791"<1435692791@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CarGuo/GSYVideoPlayer] ##我是自定义的GSY播放器全屏问题   我小屏 所有效果都可以实现 但是全屏后方法走完 ，不走我自定义UI 控件，因为我的广告是附在最外层的 小屏没问题 但是全屏的时候设置显示都不显示，楼主这是什么问题呢  =?UTF-8?Q?_=E8=80=8C=E4=B8=94=E6=8E=A7=E4=BB=B6=E6=88=91=E6=89=BE=E5=87=BA





 
你直接区分横屏和竖屏的布局不就好了

**Comment by CarGuo** [comment]
我的意思就是类似 LandLayoutVideo ，在 

```
    @Override
    public int getLayoutId() {
        if (mIfCurrentIsFullscreen) {
            return R.layout.sample_video_land;
        }
        return R.layout.sample_video_normal;
    }
```

然后把广告放到 R.layout.sample_video_land 里面，通过配置去动态显示或者隐藏

**Comment by MyNameGty** [comment]
横屏的时候双击暂停要显示广告，我动态的设置显示隐藏  没有生效

**Comment by CarGuo** [comment]
你是外部设置？ 外部的话要 player.getCurrentPlayer().xxxxxxx

**Comment by MyNameGty** [comment]
竖屏没有问题就是横屏的时候不显示

**Comment by MyNameGty** [comment]
您说的是让我在changeUi这种方法里面处理UI变化是不

**Comment by MyNameGty** [comment]
@Override
public int getLayoutId() {
    if (mIfCurrentIsFullscreen) {
        return R.layout.sample_video_land;
    }
    return R.layout.sample_video_normal;
}
这个里面&nbsp; 我全屏的时候这个布局只写广告的代码可以吗
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 晚上6:06
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"1435692791"<1435692791@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] ##我是自定义的GSY播放器全屏问题   我小屏 所有效果都可以实现 但是全屏后方法走完 ，不走我自定义UI 控件，因为我的广告是附在最外层的 小屏没问题 但是全屏的时候设置显示都不显示，楼主这是什么问题呢  =?UTF-8?Q?_=E8=80=8C=E4=B8=94=E6=8E=A7=E4=BB=B6=E6=88=91=E6=89=BE=E5=87=BA





 
你是外部设置？ 外部的话要 player.getCurrentPlayer().xxxxxxx

**Comment by CarGuo** [comment]
我的意思，就是你在全屏布局里加广告ui，然后在需要的时候显示……

**Comment by MyNameGty** [comment]
我添加的 广告UI控件 是不是都需要克隆呀

**Comment by CarGuo** [comment]
cloneParams 是参数，startWindowFullscreen 是读取参数去设置，你看 StandardGSYVideoPlayer 这两个方法的源码

**Comment by MyNameGty** [comment]
克隆只需要克隆参数就可以了， 我广告显示 在 暂停状态的情况下 我在changeUiToPauseShow（）方法 判断他 mIfCurrentIsFullscreen 和 status 还是被覆盖了 


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 上午10:18
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"1435692791"<1435692791@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] ##我是自定义的GSY播放器全屏问题   我小屏 所有效果都可以实现 但是全屏后方法走完 ，不走我自定义UI 控件，因为我的广告是附在最外层的 小屏没问题 但是全屏的时候设置显示都不显示，楼主这是什么问题呢  =?UTF-8?Q?_=E8=80=8C=E4=B8=94=E6=8E=A7=E4=BB=B6=E6=88=91=E6=89=BE=E5=87=BA





 
cloneParams 是参数，startWindowFullscreen 是读取参数去设置，你看 StandardGSYVideoPlayer 这两个方法的源码

**Comment by CarGuo** [comment]
不是很理解你怎么操作出现问题····

**Comment by MyNameGty** [comment]
刚才摸索了一下 暂停的好了 还差刚打开的10秒广告&nbsp; &nbsp;暂停的我是在
@Override
protected void updateStartImage() {
    super.updateStartImage();
    if(mIfCurrentIsFullscreen){
        ViewGroup.LayoutParams layoutParams = list_ad_view_layout_small.getLayoutParams();
        layoutParams.width = ImageUtil.dp2px(activity, 264);
        layoutParams.height = ImageUtil.dp2px(activity, 160);
        list_ad_view_layout_small.setLayoutParams(layoutParams);
        if(mCurrentState == CURRENT_STATE_PAUSE){
            setViewShowState(list_ad_view_layout_small,VISIBLE);
            videoInfoBeen.advert.get(1).setAd(activity, (FrameLayout) list_ad_view_layout_small,11);
        }else if(mCurrentState == CURRENT_STATE_PLAYING){
            setViewShowState(list_ad_view_layout_small,GONE);
        }else{
            setViewShowState(list_ad_view_layout_small,GONE);
        }
    }else{
        ViewGroup.LayoutParams layoutParams = list_ad_view_layout_small.getLayoutParams();
        layoutParams.width = ImageUtil.dp2px(activity, 137);
        layoutParams.height = ImageUtil.dp2px(activity, 83);
        list_ad_view_layout_small.setLayoutParams(layoutParams);
    }
}



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuyu Guo"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 上午10:47
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;; 
抄送: "1435692791"<1435692791@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CarGuo/GSYVideoPlayer] ##我是自定义的GSY播放器全屏问题   我小屏 所有效果都可以实现 但是全屏后方法走完 ，不走我自定义UI 控件，因为我的广告是附在最外层的 小屏没问题 但是全屏的时候设置显示都不显示，楼主这是什么问题呢  =?UTF-8?Q?_=E8=80=8C=E4=B8=94=E6=8E=A7=E4=BB=B6=E6=88=91=E6=89=BE=E5=87=BA





 
不是很理解你怎么操作出现问题····
