### ISSUE TITLE
请问可以加一个类似抖音的预加载功能demo吗

### ISSUE THREAD

**Issue by clark2048** [CarGuo/GSYVideoPlayer#2863]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

**Comment by clark2048** [comment]
预加载下一个视频，只加载一部分大小。

**Comment by CarGuo** [comment]
简单的说可以参考 DetailDownloadPlayer ，或者 DetailExoListPlayer 里用的 ConcatenatingMediaSource
