### ISSUE TITLE
不用ListView如何支撑多任务

### ISSUE THREAD

**Issue by annpeter** [CarGuo/GSYVideoPlayer#2864]
## 问题描述：

不使用ListView，想要在Activity中同时播放多个不通的视频，开启了多个StandardGSYVideoPlayer，只有最后一个视频会显示，其它视频不会显示

## 问题机型/系统：

例如 真机 华为Honor 7X

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.4'
`

**Comment by CarGuo** [comment]
demo 中的 MultiSampleVideo
