### ISSUE TITLE
exo模式下开启了缓存，播放m3u8怎么设置下次进来不用重头开始播

### ISSUE THREAD

**Issue by cherysky** [CarGuo/GSYVideoPlayer#2865]
问题描述：
exo模式下开启了缓存，播放m3u8怎么设置下次进来不用重头开始播

问题机型/系统：
真机 小米note2 Android7.0

GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.1'
implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.1'

Demo中的复现步骤
   我在代码中设置了这三行：
   PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
   ExoSourceManager.setSkipSSLChain(true);
  CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
  然后在播放器初始化时设置：
  videoPlayer.setUp(url, true, "测试视频"); 
  这个url是m3u8格式的，我这样设置后进入播放一段视频退出，在进入又重新开始播，我想实现第二次进入从上次进度开始播，该怎么实现，在这些代码得基础上还需要添加什么吗

问题代码：(如果有)

**Comment by CarGuo** [comment]
setSeekOnStart

**Comment by cherysky** [comment]
> setSeekOnStart
我开启缓存后，框架会自动下载播放过得放在本地吧，如果我把指针拉动到之前播放过得位置，它会自动在本地进行解码播放么，我测试过发现往回拉它还是会加载好久才会播放

**Comment by CarGuo** [comment]
你直接看换成本地的片
