### ISSUE TITLE
多任务支持模式下 能否单独控制，每个播放视频的音量 或者其他实现思路

### ISSUE THREAD

**Issue by CrzGitHub** [CarGuo/GSYVideoPlayer#2866]
## 问题描述：

多任务支持模式下 能否单独控制，每个播放视频的音量 或者其他实现思路

## 问题机型/系统：

例如 真机 Android7

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## Demo中的复现步骤

Demo多任务支持中 每个视频的音量控制

**Comment by CarGuo** [comment]
通过manager 获取到对应 PlayerManager 里面的 mediaPlayer ，通过 setVolume

**Comment by CrzGitHub** [comment]
嗯嗯  昨天看大佬源码 已经实现  感谢大佬
