### ISSUE TITLE
GSYVideoManager onPause onResume問題

### ISSUE THREAD

**Issue by AttackPangHu** [CarGuo/GSYVideoPlayer#2868]
## GSY依赖版本   7.1.4
在首页的main主页，有两个fragment，两个fragment都有视频播放器，但是我在onPause，onPause里调用    GSYVideoManager.onPause();       GSYVideoManager.onResume();的时候，他们恢复的不是自己对应fragment的播放器，而是上次正在播放的播放器，请问这个怎么处理

**Comment by CarGuo** [comment]
默认情况下内核只有一个

**Comment by AttackPangHu** [comment]
那像這種情況怎麼解決了，就是暫停暫停對應的播放器，播放也播放對應的播放器。我目前的解決方法是按TAG去區分的，就是框架本身有對應的api或者是配置嗎？

**Comment by CarGuo** [comment]
不是很理解，默认情况下，播放内核只有一个，你暂停和恢复也只会是那一个。
如果你播放了新的，旧的自然就被释放，内核也只想新的播放链接。
除非你参考  demo 的 MultiSampleVideo ，不过我觉得和你场景不大一样

**Comment by AttackPangHu** [comment]
我知道，播放的時候，其他的是暫停的，這個是正常的。但是我們這裡有個需求，就是有A和B兩個fragment，A播放A1影片，B播放B1影片。然後我在A的onPause切換到C fragment，然後如果再從C切換到B fragment,這個時候B的onResume觸發，如果這個時候沒用調用B fragment的視頻列表的startPlay方法的話，這個時候onResume恢復的是A fragment的視頻播放。場景是這樣，這個問題已經解決了，我通過manager的單例的TAG去做區別，然後實現了自己的需求。框架沒問題
