### ISSUE TITLE
 当播放本地视频的时 会出现空指针异常

### ISSUE THREAD

**Issue by CrzGitHub** [CarGuo/GSYVideoPlayer#2869]
## 问题描述： 当播放本地视频的时候   文件路径/storage/emulated/0/Android/data/com.xxx.xxx/files/xxx.mp4
会出现空指针

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```
![image](https://user-images.githubusercontent.com/20065801/88745135-d69cbc00-d17b-11ea-8311-87885bb8d225.png)

## 问题log（如果有）

 W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
 W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:84)
 W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:607)
 W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
 W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:567)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
 W/System.err:     at android.os.Looper.loop(Looper.java:214)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

xxxxxxx

```

**Comment by CarGuo** [comment]
file:// + xx 

or

content:// + xxx

**Comment by CrzGitHub** [comment]
为什么必须是绝对路径？不能是相对的RUL呢？ 主要不太理解这里
