### ISSUE TITLE
请问一下如何隐藏进度条？用来播放实时监控的HLS流，不需要进度条

### ISSUE THREAD

**Issue by shouPol** [CarGuo/GSYVideoPlayer#2870]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
重写 getLayoutId 方法，参考 demo EmptyControlVideo

**Comment by shouPol** [comment]
感谢回复！我尝试一下这个方法。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 上午10:26
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"肖波"<864407702@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 请问一下如何隐藏进度条？用来播放实时监控的HLS流，不需要进度条 (#2870)





 
重写 getLayoutId 方法，参考 demo EmptyControlVideo
