### ISSUE TITLE
当播放url错误，比如url=0，的时候，播放页面返回按钮一直闪烁

### ISSUE THREAD

**Issue by gycold** [CarGuo/GSYVideoPlayer#2871]
## 问题描述：

当播放url错误，比如url=0，的时候，播放页面返回按钮一直闪烁，返回按钮无法获取焦点

## 问题机型/系统：

真机 华为V10 Android10.0

## GSY依赖版本

例如 `implementation 'com.shuyu:GSYVideoPlayer:7.1.4'`

## Demo中的复现步骤

Demo中的SimplePlayer页面打开后，将url设置为0会出现这个问题。

问题代码：(如果有)
```
String source1 = "0";
```

**Comment by CarGuo** [comment]
设计如此，你可以直接

       videoPlayer.getTitleTextView().setVisibility(View.GONE);
        //设置返回键
        videoPlayer.getBackButton().setVisibility(View.GONE););


然后用你自己的
