### ISSUE TITLE
播放Rtsp推流时(局域网),设置tcp,大概过两分多钟就会自动结束的问题

### ISSUE THREAD

**Issue by aicareles** [CarGuo/GSYVideoPlayer#2876]
## 问题描述：

播放Rtsp推流时(局域网),设置tcp,大概过两分多钟就会自动结束,控制台会输出FFP_MSG_BUFFERING_COMPLETE

## 问题机型/系统：

所有手机

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.4'

## 问题log（如果有）

FFP_MSG_BUFFERING_COMPLETE

**Comment by aicareles** [comment]
详细日志为:  IJKMEDIA: ffp_toggle_buffering: completed: OK
IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
IJKMEDIA: FFP_MSG_COMPLETED:

**Comment by CarGuo** [comment]
你试试置顶issue上的那个附件so

**Comment by aicareles** [comment]
> so

请问是哪个,没有看到

**Comment by aicareles** [comment]
> 你试试置顶issue上的那个附件so
请问是com.shuyu:gsyVideoPlayer-ex_so:7.1.5这个吗

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2112#issuecomment-529180154

**Comment by aicareles** [comment]
> [#2112 (comment)](https://github.com/CarGuo/GSYVideoPlayer/issues/2112#issuecomment-529180154)

很感谢,但下载了哪个so后放到项目中,依然还是上面那个问题,大概2分半钟就会结束,IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED,依然还是那个日志,发现跟[#4640](https://github.com/bilibili/ijkplayer/issues/4640)问题一样

**Comment by CarGuo** [comment]
这个没辙，为什么 tcp 会在 2分钟左右断流这个需要你自己和服务端调试去解决了～
