### ISSUE TITLE
7.1.5版本Could not find gsyvideoplayer-androidvideocache

### ISSUE THREAD

**Issue by wdeo3601** [CarGuo/GSYVideoPlayer#2877]
## 问题描述：

7.1.5版本集成时，编译报错：  
```
> Could not find gsyvideoplayer-androidvideocache.jar (com.shuyu:gsyvideoplayer-androidvideocache:7.1.5).
     Searched in the following locations:
         http://maven.aliyun.com/nexus/content/groups/public/com/shuyu/gsyvideoplayer-androidvideocache/7.1.5/gsyvideoplayer-androidvideocache-7.1.5.jar
```
## 问题机型/系统：

SM-G9500/Android9.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'`

## Demo中的复现步骤

build.gradle 集成时编译报错  

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
如下图和链接所示


https://bintray.com/carguo/GSYVideoPlayer/gsyvideoplayer-androidvideocache/7.1.5

![image](https://user-images.githubusercontent.com/10770362/89019023-44e5a800-d34f-11ea-81de-7764440101ab.png)

**Comment by wdeo3601** [comment]
> 如下图和链接所示
> 
> https://bintray.com/carguo/GSYVideoPlayer/gsyvideoplayer-androidvideocache/7.1.5
> 
> ![image](https://user-images.githubusercontent.com/10770362/89019023-44e5a800-d34f-11ea-81de-7764440101ab.png)

这个依赖是在 gsyVideoPlayer-java 中的，我应该不用单独加它的依赖呀

**Comment by CarGuo** [comment]
是啊，我是想告诉你，它是在的

**Comment by wdeo3601** [comment]
![image](https://user-images.githubusercontent.com/22436965/90082522-8d836500-dd42-11ea-990e-91927f7c6380.png)
@CarGuo maven 库走到这里后不往下接着走了，没走到 Jcenter，所以没有引入依赖成功，调整一下顺序可以了。。
