### ISSUE TITLE
如何配置缓存本地视频的大小

### ISSUE THREAD

**Issue by ollie100** [CarGuo/GSYVideoPlayer#2878]
在application 里这样配置可以吗？
     CacheFactory.setCacheManager(ProxyCacheManager.class);
        ProxyCacheManager.DEFAULT_MAX_SIZE = 512 * 4 * 1024 * 1024;
        HttpProxyCacheServer httpProxyCacheServer = ProxyCacheManager.instance().newProxy(getApplicationContext());

**Comment by CarGuo** [comment]
ProxyCacheManager.DEFAULT_MAX_SIZE = 512 * 4 * 1024 * 1024;这样可以
