### ISSUE TITLE
MP4v编码的MP4文件播放只有声音没有画面，主任~

### ISSUE THREAD

**Issue by kevin321happy** [CarGuo/GSYVideoPlayer#288]
avci编码的MP4都没问题,但是mp4v的视频只有声音,这种文件在谷歌浏览器打开也是只有声音的~

**Comment by CarGuo** [comment]
你难道就是qq上的那位？

**Comment by SuperZhouyong** [comment]
这个问题怎么处理啊、、、我也遇到了

**Comment by CarGuo** [comment]
试试ex

**Comment by SuperZhouyong** [comment]
ex 这个so 库和其他的so一起倒入，还是倒入ex库了其他的so库不需要倒入了
。

**Comment by CarGuo** [comment]
如果使用了ex的。就不用其他的so

**Comment by SuperZhouyong** [comment]
再问一个。。。很多时候我第一次都一直缓冲，但是就是进入不到视频播放中去（某些时候，能正常进入播放界面）都是一个链接
