### ISSUE TITLE
关于GSY支持的视频格式

### ISSUE THREAD

**Issue by ll201lw** [CarGuo/GSYVideoPlayer#2882]
## 问题描述：

在demo"打开video"更换播放链接为本地视频mpeg和mpg进行播放，界面黑屏，估计是不能播放这类格式视频，修改为mo4后可播放视频

## 问题机型/系统：android 5.1

Android板子

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## Demo中的复现步骤

Demo中的PlayActivity和SimpleActivity页面打开后会出现这个问题，其他界面暂未尝试。

问题代码：(如果有)
暂无

## 问题log（如果有）

暂无

**Comment by CarGuo** [comment]
使用第三种依赖
