### ISSUE TITLE
手机开启自动旋转功能，向右旋转屏幕，画面会倒置

### ISSUE THREAD

**Issue by 627219641** [CarGuo/GSYVideoPlayer#2884]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 vivo x21A

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.0-beta'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后会同样出现类似问题，但简单播放界面不会。
屏幕向右旋转，画面会跟随旋转，然后再倒置。

问题代码：(如果有)
无

## 问题log（如果有）

无

**Comment by CarGuo** [comment]
demo 测试正常，请使用最新版本

**Comment by 627219641** [comment]
> demo 测试正常，请使用最新版本

最新版貌似是正常的，就是不知道是啥原因导致的，由于项目不是android x，升级是最后的方案
