### ISSUE TITLE
在RecyclerView中怎么获取和设置item中的视频进度

### ISSUE THREAD

**Issue by lijinjiliangcha** [CarGuo/GSYVideoPlayer#2886]
## 问题描述：怎么设置播放进度

我是在RecyclerView中做了个视频列表，需求想要视频滑出去之后暂停，滑回来再按播放的时候能从上一次的进度继续播放。
查看了源码和别人的Issues，获取进度的我只找到了getCurrentPositionWhenPlaying()和seekOnStart()，前者没有找到相应的set方法，后者获取的时候总是为-1，这要怎么解决？

## 问题机型/系统：

真机 redmi note 7 pro Android 9

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.5'

## Demo中的复现步骤

Demo大概没做这个需求，进入视频列表页面，点击一个视频播放，然后滑出屏幕，再滑回来播放会重新开始

问题代码：(如果有)

**Comment by CarGuo** [comment]
getCurrentPositionWhenPlaying 需要在 release 之前获取

**Comment by lijinjiliangcha** [comment]
那我要调用哪个方法set回去呢？

**Comment by CarGuo** [comment]
是的
