### ISSUE TITLE
大佬，请问详情页播放这种非全屏布局如何自动旋转画面？

### ISSUE THREAD

**Issue by lolilicker** [CarGuo/GSYVideoPlayer#2887]
## 问题机型/系统：

小米5，一加5T

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'

目前部分视频方向会有问题，咱有方法可以按GSYVideoPlayer的比例自动旋转吗？自己实现的话请问有什么思路吗？

**Comment by CarGuo** [comment]
不是很理解你的问题？

**Comment by lolilicker** [comment]
![image](https://user-images.githubusercontent.com/9214151/89492730-dbe5b080-d7e4-11ea-9ea1-462681cb3fac.png)

就是这样，有办法让视频自动旋转填充GSYVideoPlayer吗？

**Comment by CarGuo** [comment]
你看 onInfo 回掉中是不是有角度信息
