### ISSUE TITLE
播放rtmp的时候，另一边推流停止了，播放器停在最后一帧，没有回调通知

### ISSUE THREAD

**Issue by luojialun** [CarGuo/GSYVideoPlayer#2891]
## 问题描述：

播放rtmp的时候，另一边推流停止了，播放器停在最后一帧，没有回调通知

## 问题机型/系统：
所有

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:4.1.0'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:4.1.0'

## Demo中的复现步骤

播放器播放rtmp地址，正常播放，然后停止推流，播放器停在最后一帧，没有回调onplayError，请问这种情况下，有什么回调通知可以知道这种情况吗？   一开始就拉不到rtmp地址流的时候，是有onplayError回调的，但若是中途停止了，没有会回调

**Comment by CarGuo** [comment]
推荐你一个思路，参考 https://github.com/CarGuo/GSYVideoPlayer/issues/2757#issuecomment-640343341  ，或者修改为 ex o 内核的试试
