### ISSUE TITLE
播放rtsp的时候播放一段时间后会暂停

### ISSUE THREAD

**Issue by qiandailu** [CarGuo/GSYVideoPlayer#2892]
## 问题描述：播放rtsp的时候播放一段时间后会暂停，这时候通过videoPlayer.getCurrentState()获取到的mCurrentState为CURRENT_STATE_AUTO_COMPLETE

XXXX发生了这样的问题！

## 问题机型/系统：创维电视机顶盒 android4.3  vivo手机android7
例如 真机 小米note2 Android7.0

## GSY依赖版本    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'
    //是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.5'
    //更多ijk的编码支持
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.5'

**Comment by CarGuo** [comment]
除了问题集锦中的设置 tcp ，剩下就是参考 https://github.com/CarGuo/GSYVideoPlayer/issues/2757#issuecomment-640343341 这个了

**Comment by qiandailu** [comment]
好的谢谢大佬。我搞了定时器判断自动停止就重制播放器。。
