### ISSUE TITLE
实现直播功能

### ISSUE THREAD

**Issue by lutao2599** [CarGuo/GSYVideoPlayer#2894]
现在要做直播和点播功能，直播不能有进度条或者不能拖动进度条，全屏也是这样要求；但是没有找到隐藏进度条或者禁止拖动进度条的API，请问该怎么解决？ 另外视频有重新播放功能吗，就是在播放过程中可以重新播放

**Comment by CarGuo** [comment]
看demo，基本是就是重载getLayoutId
