### ISSUE TITLE
播放m3u8直播流问题

### ISSUE THREAD

**Issue by lutao2599** [CarGuo/GSYVideoPlayer#2895]
在播放直播流时，遇到m3u8不能播放的问题，提示Protcol not found  请问该怎么解决？

**Comment by CarGuo** [comment]
请提供不能播放的测试 url

**Comment by lutao2599** [comment]
https://xhs-live-record.zhongguowangshi.com/record/live_xinhuashe/_XHS_xhmmlive1_nhd/20200810-100130_20200810-102429.m3u8


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 下午2:08
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 播放m3u8直播流问题 (#2895)





 
请提供不能播放的测试 url

**Comment by CarGuo** [comment]
我这边测试这个链接都可以播放啊

**Comment by lutao2599** [comment]
请问，你是用的ijk播放的吗？我尝试demo是可以播放的，我换成exo2可以播放了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 下午2:35
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 播放m3u8直播流问题 (#2895)





 
我这边测试这个链接都可以播放啊

**Comment by CarGuo** [comment]
是的，这个链接 exo2 也测试了可以

**Comment by lutao2599** [comment]
嗯，不知道我的怎么了！使用jik播放就提示 protocol not found


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 下午2:47
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 播放m3u8直播流问题 (#2895)





 
是的，这个链接 exo2 也测试了可以

**Comment by CarGuo** [comment]
那就不知道了，我这边测试是正常的～～

**Comment by lutao2599** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 下午2:54
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 播放m3u8直播流问题 (#2895)





 
那就不知道了，我这边测试是正常的～～
