### ISSUE TITLE
recyclerview头部添加video,当视频暂停时，滑出可视区域，再滑动回来，视频出现跳帧，黑屏现象？

### ISSUE THREAD

**Issue by MYaoDan** [CarGuo/GSYVideoPlayer#2898]
## 问题描述：
在7.1.4，系统内核发生了这样的问题：类似淘宝详情，recyclerview头部嵌套GSYVideoPlayer，当手动点击暂停，滑动recyclerview，将暂停的视频滑动出可视区域，然后再将视频活动回到可视区域，视频出现跳帧，黑屏，卡顿现象。

## 问题机型/系统：

 真机 android10.0

## GSY依赖版本

api 'com.shuyu:gsyVideoPlayer-java:7.1.4'

**Comment by CarGuo** [comment]
没有复现问题···
