### ISSUE TITLE
SIGABRT 

### ISSUE THREAD

**Issue by Tkorn** [CarGuo/GSYVideoPlayer#2899]
有人遇到这个问题吗？
GSYVideoPlayer 版本
{
    api 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    api 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
    api 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'
}
Anderoid 版本是6.0.1

#00 pc 000442b8 /system/lib/libc.so (tgkill+12) [armeabi-v7a]
--
2 #01 pc 00041ec5 /system/lib/libc.so (pthread_kill+32) [armeabi-v7a]
3 #02 pc 0001badf /system/lib/libc.so (raise+10) [armeabi-v7a]
4 #03 pc 00018c91 /system/lib/libc.so (__libc_android_abort+34) [armeabi-v7a]
5 #04 pc 00016784 /system/lib/libc.so (abort+4) [armeabi-v7a]
6 #05 pc 00008f93 /system/lib/libcutils.so (__android_log_assert+86) [armeabi-v7a]
7 #06 pc 0001bb85 /system/lib/libhwui.so [armeabi-v7a]
8 #07 pc 00018ecf /system/lib/libhwui.so [armeabi-v7a]
9 #08 pc 0001ac07 /system/lib/libhwui.so [armeabi-v7a]
10 #09 pc 0001dbf5 /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+80) [armeabi-v7a]
11 #10 pc 00010855 /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112) [armeabi-v7a]
12 #11 pc 000507ab /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+70) [armeabi-v7a]
13 #12 pc 000417c7 /system/lib/libc.so (__pthread_start(void*)+30) [armeabi-v7a]
14 #13 pc 00019313 /system/lib/libc.so (__start_thread+6) [armeabi-v7a]

1 android.os.MessageQueue.nativePollOnce(Native Method)
--
2 android.os.MessageQueue.next(MessageQueue.java:323)
3 android.os.Looper.loop(Looper.java:135)
4 android.app.ActivityThread.main(ActivityThread.java:5417)
5 java.lang.reflect.Method.invoke(Native Method)
6 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
7 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

**Comment by CarGuo** [comment]
请使用最新版本，并且log上也看不出是库的问题
