### ISSUE TITLE
点击全屏按钮旋转过来白屏

### ISSUE THREAD

**Issue by 7hundeR** [CarGuo/GSYVideoPlayer#290]
在MainActivity中放VIewPager，ViewPager中有个Fragment，Fragment中放RecyclerView，按照demo写，点击全屏按钮后，旋转过来后还是列表，然后当前item一片空白，有声音播放，求帮忙解决

**Comment by CarGuo** [comment]
配置Activity的manifest的，参考demo

**Comment by 7hundeR** [comment]
MainActivity配置了这两个属性
android:configChanges="orientation|screenSize"
android:screenOrientation="portrait"

**Comment by CarGuo** [comment]
参考demo的配置和设置

**Comment by 7hundeR** [comment]
弄明白了，绕糊涂了，item用StandardGSYVideoPlayer就行了，谢谢
