### ISSUE TITLE
小窗口关闭后调用clickStartIcon暂停播放 封面变为第一帧的了

### ISSUE THREAD

**Issue by LDJHXM** [CarGuo/GSYVideoPlayer#2900]
小窗口调用hideSmallVideo隐藏后再调用clickStartIcon()暂停播放 但是封面是第一帧的

**Comment by CarGuo** [comment]
Demo怎么复现

**Comment by LDJHXM** [comment]
就是监听scrollView滑动来显示隐藏小窗口 在点击隐藏小窗口的时候调用了hideSmallVideo()并没有暂停视频 所以手动调用了clickStartIcon() 在滑回去的时候发现视频的封面不是当前帧 而是开始设置的封面

**Comment by CarGuo** [comment]
不是很明白，hideSmallVideo 本来的设计就是不会暂停视频

**Comment by LDJHXM** [comment]
对呀 但是我现在需要暂停视频 因为点了×之后不暂停视频就会一直播放 所以hideSmallVideo隐藏小窗口之后怎么暂停播放  我现在是暂停播放后就不能继续播放了~不知道调哪个API

**Comment by CarGuo** [comment]
GSYVideoManager的onPause
