### ISSUE TITLE
列表详情切换问题

### ISSUE THREAD

**Issue by gaojunhuiBS** [CarGuo/GSYVideoPlayer#2901]
列表到详情要正常播放，但是从正在播放的详情回到列表，如何让列表继续播放？

**Comment by CarGuo** [comment]
这个你参考源码，不释放surface和播放内核就好了

**Comment by gaojunhuiBS** [comment]
> 这个你参考源码，不释放surface和播放内核就好了

现在我把您demo里面的SwitchListVideoActivity中的onDestroy方法都注掉了，从详情回到列表里，继续播放后，只有声音和进度，画面卡主了，如何回到列表后，继续正常播放，辛苦看一下。

**Comment by CarGuo** [comment]
画面卡主了了就是 surface 的创建和恢复而已，你看源码就知道了
