### ISSUE TITLE
播放RTSP流时，相同ip下不同端口，播放的都是第一次播放的地址

### ISSUE THREAD

**Issue by 18202810862** [CarGuo/GSYVideoPlayer#2902]
## 问题描述：

播放RTSP流时，相同ip下不同端口，播放的都是第一次播放的地址

## 问题机型/系统：

例如 真机 台电P10s android8.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.5'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.5'

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2112#issuecomment-510416452
