### ISSUE TITLE
直播问题

### ISSUE THREAD

**Issue by lutao2599** [CarGuo/GSYVideoPlayer#2903]
做直播播放器，播放的时候会出现进度条，很长时间不会重新播放，播放的视频格式的m3u8；请问该怎么解决？使用的版本是7.1.5，机型是华为荣耀HRY-AL00Ta，另外想让标题实现跑马灯效果，但是一直没效果，谢谢啦

**Comment by CarGuo** [comment]
没有明白

**Comment by lutao2599** [comment]
播放器显示的标题怎么让其滚动起来？我试了不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 下午2:54
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 直播问题 (#2903)





 
没有明白

**Comment by lutao2599** [comment]
大佬，还有个问题：就是视频在播放过程中会出现一直加载中....不会重新播放了，请问这个该怎么解决呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 下午2:54
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 直播问题 (#2903)





 
没有明白

**Comment by CarGuo** [comment]
你重载 getLayoutId 缓存自己的 UI 不就行了。
就是视频在播放过程中会出现一直加载中不就是网络问题么

**Comment by lutao2599** [comment]
但是我返回，重新进入就可以播放了，网络是好的！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 下午3:34
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 直播问题 (#2903)





 
你重载 getLayoutId 缓存自己的 UI 不就行了。
 就是视频在播放过程中会出现一直加载中不就是网络问题么

**Comment by lutao2599** [comment]
有个问题想咨询下，麻烦了！就是我重写了布局，然后标题右侧加了一些view，在竖屏的时候设置了数据，然后在全屏没有成功应用，请问该怎么解决？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 下午3:34
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 直播问题 (#2903)





 
你重载 getLayoutId 缓存自己的 UI 不就行了。
 就是视频在播放过程中会出现一直加载中不就是网络问题么

**Comment by CarGuo** [comment]
cloneParams  startWindowFullscreen  resolveNormalVideoShow  重写这三个方法

**Comment by lutao2599** [comment]
谢谢大佬，


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 下午4:41
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 直播问题 (#2903)





 
cloneParams  startWindowFullscreen  resolveNormalVideoShow  重写这三个方法

**Comment by lutao2599** [comment]
重写这三个方法后，里面的具体内容不知怎么写


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 下午4:41
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 直播问题 (#2903)





 
cloneParams  startWindowFullscreen  resolveNormalVideoShow  重写这三个方法

**Comment by CarGuo** [comment]
你参考  StandardGSYVideoPlayer 的这几个方式的实现···

另外可以看到 https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/GSYVIDEO_PLAYER_PROJECT_INFO.md

**Comment by lutao2599** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 下午4:54
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 直播问题 (#2903)





 
你参考  StandardGSYVideoPlayer 的这几个方式的实现···
 
另外可以看到 https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/GSYVIDEO_PLAYER_PROJECT_INFO.md
