### ISSUE TITLE
Demo raw方式 本地视频  无法播放

### ISSUE THREAD

**Issue by Ysrfengnull** [CarGuo/GSYVideoPlayer#2904]
下载此视频 https://test-static-public-log56-com.oss-cn-hangzhou.aliyuncs.com/kydd_app/video/login_video.mp4
放到demo raw 目录 替换 test.mp4

1.无法播放此视频
2.视频链接在线播放没问题
3.ios可以本地播放

大佬能否别急着close，之前提过问题，并没有解决，能否下载一下这个视频，自己试一下

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式

       GSYVideoManager.instance().enableRawPlay(getApplicationContext());

       ///exo 播放 raw
       String url = "rawresource://" + getPackageName() + "/" + R.raw.test5;



如上代码正常播放
