### ISSUE TITLE
播放直播时，播放之前封面不显示问题

### ISSUE THREAD

**Issue by lutao2599** [CarGuo/GSYVideoPlayer#2907]
## 问题描述：

 播放m3u8直播流的时候，播放开始前怎么显示封面，等播放开始了再让封面隐藏？

## 问题机型/系统：

例如 真机荣耀手机

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5`

**Comment by CarGuo** [comment]
不是很理解你的问题？？？

**Comment by lutao2599** [comment]
就是还没正式播放之前，能不能先用封面占位？一旦播放了，封面就隐藏？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 晚上6:31
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 播放直播时，播放之前封面不显示问题 (#2907)





 
不是很理解你的问题？？？

**Comment by lutao2599** [comment]
麻烦再问下：直播时，暂停后再点开始能不能拉取最新的播放？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 晚上6:31
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 播放直播时，播放之前封面不显示问题 (#2907)





 
不是很理解你的问题？？？

**Comment by androidTH** [comment]
自己覆盖在播放器上面就行了

**Comment by lutao2599** [comment]
好，谢谢！如果直播时暂停了，再点开始不让接着播放，而是拉取最新的直播数据，该怎么做？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月14日(星期五) 上午9:57
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 播放直播时，播放之前封面不显示问题 (#2907)





 
自己覆盖在播放器上面就行了
