### ISSUE TITLE
https双向认证

### ISSUE THREAD

**Issue by 867588763** [CarGuo/GSYVideoPlayer#2908]
## 问题描述：

https双向认证，有对外提供方法吗

## 问题机型/系统：

小米note2  Android7.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'`

## Demo中的复现步骤

```

**Comment by CarGuo** [comment]
木有，ijk模式没有，exo模式下只有忽略证书和默认的认证流程

**Comment by 867588763** [comment]
我拿到视频地址了，网络验证啥的本来也不是这个gsyVideoPlayer的事  感谢
