### ISSUE TITLE
请问视频源是旋转的，您对这种情况的处理代码在哪？想参考下，求大神指教

### ISSUE THREAD

**Issue by 529523346** [CarGuo/GSYVideoPlayer#291]

**Comment by CarGuo** [comment]
在GSYTextureView

**Comment by 529523346** [comment]
@CarGuo 您这是在得知视频旋转后对显示视频的处理吧，我想知道怎么获取视频的旋转信息?
else if (what == IMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED) {
            mRotate = extra;
            if (mTextureView != null)
                mTextureView.setRotation(mRotate);
        }
就是这个extra是怎么获得的？

**Comment by CarGuo** [comment]
ijk的onInfo
