### ISSUE TITLE
自己界面一个按钮点击实现竖屏全屏切换

### ISSUE THREAD

**Issue by scb7709** [CarGuo/GSYVideoPlayer#2911]
## 问题描述：

怎么自主实现竖屏全屏切换

## 问题机型/系统：

例如 真机 

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'`

## Demo中的复现步骤

因需要要实现广告界面，广告界面上有横竖切换的按钮，所以需要自主实现  视频的横竖切换。

**Comment by CarGuo** [comment]
参考 demo 

setAutoFullWithSize  true

setLockLand(false)

**Comment by scb7709** [comment]
不是 要自动横竖屏切换，是要我自己在我的界面上写了一个按钮，然后点击这个按钮实现横竖切换。也就是 我需要 手动实现横屏的代码 和回到竖屏的代码；

**Comment by CarGuo** [comment]
哦，那就是 startWindowFullscreen 和  resolveNormalVideoShow ，resolveNormalVideoShow 

resolveNormalVideoShow 因为是 protect ，你需要继承 player 之后自己写一个 public 的方法去调用 resolveNormalVideoShow 就好了。
