### ISSUE TITLE
播放器全屏后 会被刘海屏遮盖

### ISSUE THREAD

**Issue by bingdu0** [CarGuo/GSYVideoPlayer#2913]
请教大佬一个问题 ，为什么播放器全屏后会被刘海屏遮盖呢？Demo中没有这个问题，是做了什么配置吗？

**Comment by CarGuo** [comment]
源码里有 autoAdaptation 的方法吧

**Comment by bingdu0** [comment]
> 源码里有 autoAdaptation 的方法吧

有这个方法，但是我看Demo里面也没用的地方啊。

**Comment by CarGuo** [comment]
嗯，当 autoAdaptation 的时候才会。另外还有 AndroidManifest 的配置

**Comment by bingdu0** [comment]
> 嗯，当 autoAdaptation 的时候才会。另外还有 AndroidManifest 的配置

我的项目里面也没有用autoAdaption这个方法，而且我把Demo  AndroidManifest里面的<meta-data
     android:name="android.max_aspect"
     android:value="2.1" /> 删掉了， Demo也可以 我的项目还是不行，清单文件到底配置了什么？

**Comment by qweenhool** [comment]
我也遇到了，不知道是哪个设置有问题，楼主解决了吗？
