### ISSUE TITLE
怎样去除全屏状态下的这个小蓝条

### ISSUE THREAD

**Issue by xioxu** [CarGuo/GSYVideoPlayer#2918]
#2517  问题描述：

全屏后播放器下方仍然有个小蓝条
[可参考图 ](https://s1.ax1x.com/2020/08/19/d1vojK.png)

## 问题机型/系统：

NOX模拟器、Mi9

## GSY依赖版本

   implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'

## Demo中的复现步骤

直接使用的官方所说的打开就全屏的示例代码（StandardGSYVideoPlayer），的确打开时全屏，可下方那个小蓝条不知道怎样才能消除。

用videoPlayer.startWindowFullscreen(requireContext(),false,false)方法使用后直接我的各种按键都不起作用了，包括back按键。

**Comment by CarGuo** [comment]
重写 getLayoutId
