### ISSUE TITLE
2个视频页面来回跳转的问题

### ISSUE THREAD

**Issue by coolyunyun** [CarGuo/GSYVideoPlayer#2919]
## 问题描述：

当A activity在播放视频 urlA,此时跳转到 B activity，B activity上也需要播放视频 urlB，能否做到B页面返回A页面时候，A无缝衔接继续播放，目前我这边实测A页面会自动暂停。

## 问题机型/系统：

所有机型

## GSY依赖版本

例如 `implementation 'com.shuyu:GSYVideoPlayer:7.1.5'

## Demo中的复现步骤

A页面 播放视频  跳到B页面 也播放视频    再返回A页面，  A页面自动暂停了，通过代码继续播放做不到很流畅，会有暂停效果再继续，能否做到立刻继续。

代码：
我是通过如下方式继续在A页面播放的

@Override
    public void onResume() {
        super.onResume();
        //结果页如果播放视频  回到闲置页   播放器会自动停止   这里加判断  继续播放
        if (videoPlayer!=null){
            if (videoPlayer.getVisibility() == View.VISIBLE){
                if ( !videoPlayer.isInPlayingState())
                    videoPlayer.startPlayLogic();
            }
        }
    }

但效果不是很理想，会有闪烁感。 大概延迟了几百ms后才会继续播放，中间看上去会有一瞬间黑屏的感觉。

**Comment by CarGuo** [comment]
默认情况下只有一个视频内核，也就是播放一个新的旧的肯定会被释放，你看B站的也是这样，回来后会黑一下。
demo 里也有提供多开内核的例子，你可以参考。

**Comment by coolyunyun** [comment]
大佬，demo里提供多开内核的例子是  哪个按钮

**Comment by CarGuo** [comment]
ListMultiVideoActivity
