### ISSUE TITLE
7.1.5 版本 局部刷新一个item中的 CheckBox状态导致 播放器重新播放

### ISSUE THREAD

**Issue by liudaohong** [CarGuo/GSYVideoPlayer#2921]
通过 GSYVideoOptionBuilder 方式设置 Url   在局部刷新的时候会重新播放
 setUpLazy 方式  不会重新播放 但是在加载列表中 不会先显示封面图片 会等 加载完了视频才会显示 封面

**Comment by CarGuo** [comment]
这个不属于播放器的问题
