### ISSUE TITLE
使用onPause后再使用onResume视频不会播放，ui状态处于播放状态（CURRENT_STATE_PLAYING）

### ISSUE THREAD

**Issue by BaiShou** [CarGuo/GSYVideoPlayer#2923]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

首先调用
GSYVideoManager.onPause()
暂停，再使用
GSYVideoManager.onResume()
恢复播放，这时候UI状态处于播放状态，但是视频没有播放

## 问题机型/系统：

 真机 小米note3 Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'`

## Demo中的复现步骤

问题代码：(如果有)
```
GSYVideoView中onVideoPause
if (getGSYVideoManager() != null &&
                    getGSYVideoManager().isPlaying()) { 
判断不成立，但是 mCurrentState ==  CURRENT_STATE_PLAYING
导致 onVideoResume 也不能进行播放
```

**Comment by BaiShou** [comment]
我刚刚试了Demo复现了
在```SimplePlayer```只添加一个按钮进行页面跳转
```
public void pause(View view) {
        startActivity(new Intent(this, SimpleActivity.class));
    }
```

多跳几次就会出现，速度要快

**Comment by BaiShou** [comment]
链接: https://pan.baidu.com/s/1hAuY6JBVqLM38hbvHfjhEA 提取码: 532q
我录的视频

**Comment by CarGuo** [comment]
SimpleActivity 跳 SimpleActivity 是另外的情况，因为默认设置下播放内核只有一个，跳到新的播放器上旧的播放内核就释放了，这是正常情况，

所以如果你跳一个新的播放界面，回来你要 setSeekOnStart 然后 重新走 startPlayLogic

**Comment by BaiShou** [comment]
不是，随便跳一个页面都可以，再返回回去

**Comment by CarGuo** [comment]
我这边demo测试正常

**Comment by BaiShou** [comment]
链接: https://pan.baidu.com/s/1U2GatQMM-qvEGYUAnr6bvQ 提取码: t84h
我在SimplePlayer里面什么都没有改，只单纯加一个按钮跳页面

**Comment by CarGuo** [comment]
还是没能复现

**Comment by BaiShou** [comment]
操作步骤：进入播放器开始播放>立马跳其他页面>点击返回>立马又跳其他页面
这样重复几次就出现了，速度要快。
出现这样的情况，主要是播放把状态设置为正在播放中，但是播放内核这时候还没开始播放，点击暂停导致
```
if (getGSYVideoManager() != null &&
                    getGSYVideoManager().isPlaying()) {
```
判断不通过，UI没有变化

**Comment by CarGuo** [comment]
目前这种测试我还是没复现问题，不过说实话：`进入播放器开始播放>立马跳其他页面>点击返回>立马又跳其他页面` 这种场景暂时是不考虑针对优化

**Comment by BaiShou** [comment]
我这只是根据目前项目中出现的情况，单独换了一种思路复现出来的。个人感觉把
```
 setStateAndUi(CURRENT_STATE_PAUSE);
                mCurrentPosition = getGSYVideoManager().getCurrentPosition();
```
挪到判断外面，应该也是没有问题的。

目前我这边还碰见另外一种情况，还没定位出问题。画面卡住，但是进度条一直往前走，点击暂停再点播放，进度条又回到卡住的位置往前走，画面还是卡住

**Comment by CarGuo** [comment]
这么诡异的问题还真没看到····

**Comment by BaiShou** [comment]
确实诡异，主要出现 使用 GSYVideoManager 暂停和恢复播放。就会有几率视频没有播放，但是UI出于播放状态

**Comment by CarGuo** [comment]
如果可以期待你能 debug 出问题的点～～～

**Comment by fangyuan1994** [comment]
我也出现这问题，GSYVideoManager.onPause()后调用GSYVideoManager.onResume()，经常复现，作者解决了吗

**Comment by fangyuan1994** [comment]
> 目前这种测试我还是没复现问题，不过说实话：`进入播放器开始播放>立马跳其他页面>点击返回>立马又跳其他页面` 这种场景暂时是不考虑针对优化

不是快速跳转的问题，过一会跳转也会出现这个情况

**Comment by CarGuo** [comment]
@fangyuan1994 没有复现问题，问了几个他们也都没有

**Comment by LJYq** [comment]
这个问题你们有什么办法解决吗？我也遇到一样的情况，求解答，谢谢！

**Comment by OneupLee** [comment]
我遇到类似的问题，非全屏或者全屏状态下，弹出一个全局的悬浮窗（windowmanager实现的），关掉悬浮窗就会出现：
1.视频不在全屏：视频暂停，再切换到全屏，点击播放，视频播放一秒立即卡住，然后就再也没有反应，切换回小屏也一样
2.视在全屏：UI没有编导暂停状态，播放器状态为pause，点击播放按钮，播放器状态变为play，但是视频并没有播放，UI也没有变化，如果此时调用setData()然后start()，onVideoResume(boolean seek)方法会抛出异常 mpjni start: null mp

**Comment by LinPom** [comment]
我也遇到了类似的问题，我的是一个视频列表，如果列表中有视频处于播放状态，然后用户横竖屏的时候会自动切换全屏和非全屏，所以需要判断列表中的视频是否正在播放，刚开始我用videoPlayer.getCurrentState() == CURRENT_STATE_PLAYING来判断，但是经常出现明明列表中有视频在播放，但是getCurrentState()是0也就是CURRENT_STATE_NORMAL状态，后来我换成GSYVideoManager.instance().isPlaying()判断，能准确判断视频是否正在播放，但是如果这个时候切换全屏UI显示的状态又有问题，总之确实存在gsyVideoManager.isPlaying()和mCurrentState的值对应不上的情况

**Comment by SkyD666** [comment]
> 我这只是根据目前项目中出现的情况，单独换了一种思路复现出来的。个人感觉把
> 
> ```
>  setStateAndUi(CURRENT_STATE_PAUSE);
>                 mCurrentPosition = getGSYVideoManager().getCurrentPosition();
> ```
> 
> 挪到判断外面，应该也是没有问题的。
> 
> 目前我这边还碰见另外一种情况，还没定位出问题。画面卡住，但是进度条一直往前走，点击暂停再点播放，进度条又回到卡住的位置往前走，画面还是卡住

请问目前有解决方案吗？

**Comment by BaiShou** [comment]
> > 我这只是根据目前项目中出现的情况，单独换了一种思路复现出来的。个人感觉把
> > ```
> >  setStateAndUi(CURRENT_STATE_PAUSE);
> >                 mCurrentPosition = getGSYVideoManager().getCurrentPosition();
> > ```
> > 
> > 
> > 挪到判断外面，应该也是没有问题的。
> > 目前我这边还碰见另外一种情况，还没定位出问题。画面卡住，但是进度条一直往前走，点击暂停再点播放，进度条又回到卡住的位置往前走，画面还是卡住
> 
> 请问目前有解决方案吗？



> > 我这只是根据目前项目中出现的情况，单独换了一种思路复现出来的。个人感觉把
> > ```
> >  setStateAndUi(CURRENT_STATE_PAUSE);
> >                 mCurrentPosition = getGSYVideoManager().getCurrentPosition();
> > ```
> > 
> > 
> > 挪到判断外面，应该也是没有问题的。
> > 目前我这边还碰见另外一种情况，还没定位出问题。画面卡住，但是进度条一直往前走，点击暂停再点播放，进度条又回到卡住的位置往前走，画面还是卡住
> 
> 请问目前有解决方案吗？

你可以查一下视频资源是不是去缺少音频，我这个有点久了，我记得好像是视频中某一段没有音频源，补上一段空白音频源就行

**Comment by sanjinmr** [comment]
1. 各位兄弟们，我也遇见了这个问题，而且可以复现，我的版本是：com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.3-jitpack。
2. 复现场景：1）我在同一个页面，通过点击一个按钮来做resume和pause，我以2、3秒的频率点击按钮，很容易复现这个问题。

**Comment by CarGuo** [comment]
@sanjinmr  频繁点击还真的没针对处理

**Comment by sanjinmr** [comment]
我知道原因了。我是这样发现的。1. 首先，我使用GSY播放器播放一个视频，这个视频没有问题。然后我暂停。进入另外一个页面，用ExoPlayer播放一个音频（播放的时候内部发生了异常。如下：Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.aac.decoder）。然后估计GSY播放器如果页使用了Exo作为内核的话，因为上述异常，就会导致GSY中的播放状态和数据被破坏了。进而导致GSY播放进行恢复播放的时候不正常。

**Comment by hymlv** [comment]
> 还是没能复现

很好复现，再视频播放时候进行分享，分享到微信，留在微信，再关闭微信，返回到刚才播放的页面GSYVideoManager.onResume()执行了，但是页面却不能播放，UI显示也不正确无法重新播放，只有关闭页面再进入才正常。

**Comment by hymlv** [comment]
分享到微信后点开这个视频进行播放，再关闭微信，回到APP，问题就出现了

**Comment by pinguoooo** [comment]
我现有遇到的问题上总结了如下解决办法：
1. 试试在videoPlayer进行resume或者startPlay时给个postDelay()，延迟100-300多够了，让它有一点点反应时间；
2. 在有进行第三方sdk调用时如果发生多次弹窗关闭打开或者跳转到这Activity时，给出进行中的标志，让videoPlayer不要在Activity.onResume()中进行onVideoResume()或者startPlay操作，而是判断调用第三方这种情况是否完成后进行；
3. 如果使用了列表，进行了notifyDataSetChanged()，导致这种情况，需要使用局部刷新进行UI更新。

**Comment by CarGuo** [comment]
Closed by https://github.com/CarGuo/GSYVideoPlayer/issues/3602

**Comment by JasonDev324** [comment]
> 我现有遇到的问题上总结了如下解决办法：
> 
> 1. 试试在videoPlayer进行resume或者startPlay时给个postDelay()，延迟100-300多够了，让它有一点点反应时间；
> 2. 在有进行第三方sdk调用时如果发生多次弹窗关闭打开或者跳转到这Activity时，给出进行中的标志，让videoPlayer不要在Activity.onResume()中进行onVideoResume()或者startPlay操作，而是判断调用第三方这种情况是否完成后进行；
> 3. 如果使用了列表，进行了notifyDataSetChanged()，导致这种情况，需要使用局部刷新进行UI更新。

局部刷新怎么做

**Comment by liuwei-android** [comment]
同样的问题，只要跳转到其他页面在回来，onResume里执行onVideoResume()方法，但是getGSYVideoManager().isPlaying()还是为true，导致继续播放不了，上面说的延迟也不行，临时处理方式：记录下当前播放位置重新播放startPlayLogic()，加载的会稍微慢些。奇怪的是demo里确实没有这个问题，使用方式也没排查到问题。。。

**Comment by liuwei-android** [comment]
> 同样的问题，只要跳转到其他页面在回来，onResume里执行onVideoResume()方法，但是getGSYVideoManager().isPlaying()还是为true，导致继续播放不了，上面说的延迟也不行，临时处理方式：记录下当前播放位置重新播放startPlayLogic()，加载的会稍微慢些。奇怪的是demo里确实没有这个问题，使用方式也没排查到问题。。。

总算找到原因了：我的界面同时有Banner(内部也用了GSYVideo)和GSYVideo，同时banner也绑定了生命周期，就导致在onPause的时候banner内部也调用了全局的暂停方法
```
if (GSYVideoManager.instance().isPlaying) {
            GSYVideoManager.instance().stop()
        }
```
从而导致了在activity的onPause方法里，onVideoPause()->getGSYVideoManager().isPlaying()返回值始终为false，导致后面一系列的状态未更新，所以才会出现视频其实已经暂时了，但是暂停动画并没有播放，而mCurrentState仍为播放中，导致在onResume里无法去执行继续播放的动作
有同样问题的同学可以看看是否也有全局GSYVideoManager在使用！

**Comment by AivanUy** [comment]
通过debug 我发现 onResume 中调用 状态 player.currentPlayer?.currentState == CURRENT_STATE_PAUSE (5) ，而点击开始按钮 GSYVideoControlView 中的 clickStartIcon()  方法 中 mCurrentState == CURRENT_STATE_NORMAL (0)。显然 sdk 出了啥问题，我没深究，接口楼上大佬们都分析，直接创建个 AppBaseGSYPlayer 继承  StandardGSYVideoPlayer，返回自己定义个方法 ： fun clickStart(){
        clickStartIcon()
    }

在onResume里面直接调用：
 fun resumeOrSeek(player: AppBaseGSYPlayer?, seek: Long) {
        player?.let {
            if (player.currentPlayer?.currentState == GSYBaseVideoPlayer.CURRENT_STATE_PAUSE) {
                player.currentPlayer?.postDelayed({
                    player.seekOnStart = seek
                    player.clickStart()
                },500)
            }
        }
    }
