### ISSUE TITLE
activity, fragment可以播放视频，但是使用viewpager2上下滑动时有声音，无画面

### ISSUE THREAD

**Issue by lzy6** [CarGuo/GSYVideoPlayer#2924]
##问题描述：

activity, fragment可以播放视频，但是使用viewpager2上下滑动时有声音，无画面，exo，硬件加速我也都试过了，不行。使用的是demo里的无UI EmptyControlVideo(StandardGSYVideoPlayer),recyclerview是没问题的，它们用的是同一个adapter

## 问题机型/系统：

例如 真机 华为mate10pro Android10.0

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.5'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.5'

## Demo中的复现步骤

如果和demo中的实现方法一样是没问题的，但是我用了viewpager2

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
有声音没画面主要是 surface 的创建问题，这个需要你自己调下为什么 surface 会没有创建，你可以看 PlayerManager 的 setDiaplay ，跟踪下调用

**Comment by JasonDev324** [comment]
> 有声音没画面主要是 surface 的创建问题，这个需要你自己调下为什么 surface 会没有创建，你可以看 PlayerManager 的 setDiaplay ，跟踪下调用

同样出现了
