### ISSUE TITLE
小窗口点击

### ISSUE THREAD

**Issue by flyinggor** [CarGuo/GSYVideoPlayer#2925]
小窗口的点击事件重写哪个方法啊，是mTextureViewContainer的点击事件吗，没研究出来？

**Comment by flyinggor** [comment]
小窗口点击跳转全屏，大佬们可以分享下解决办法吗

**Comment by flyinggor** [comment]
@CarGuo

**Comment by CarGuo** [comment]
gsyVideoPlayer.setSmallVideoTextureView(new SmallVideoTouch(gsyVideoPlayer, marginLeft, marginTop));

**Comment by flyinggor** [comment]
> gsyVideoPlayer.setSmallVideoTextureView(new SmallVideoTouch(gsyVideoPlayer, marginLeft, marginTop));

这个怎么外部调用啊，这块我也发现了，可以在不集成model的情况下修改吗

**Comment by CarGuo** [comment]
你继承后直接重写这个原本调用的买的方法就好了，我记得是protect的，你override之后cv修改
