### ISSUE TITLE
使用IjkPlayerManager不能拿到正确的视频宽高,换了SystemPlayerManager能拿到正确的宽高

### ISSUE THREAD

**Issue by fengxiaocan** [CarGuo/GSYVideoPlayer#2927]
## 问题描述：

在使用GSYVideoGLViewSimpleRender3 做视频效果的时候发现了一些视频无法拿到正确的宽高,视频是横屏视频,但是宽高比却是竖屏的视频的比例,但是视频能够正常按照横屏视频播放.
我在设置setAutoFullWithSize(true)后,按全屏播放按钮居然是按照竖屏视频来切换成全屏!
我查看了源码,发现使用IjkPlayerManager不能拿到正确的视频宽高,切换了SystemPlayerManager就能拿到正确的宽高,并且设置setAutoFullWithSize(true)后按全屏播放按钮就能正确按照横屏视频来切换全屏播放了.
视频地址:http://video1.dgtle.com/backend%2F2020%2F3%2F0%2F%E6%88%91%E6%B2%A1%E6%9C%89%E7%BB%99%E4%B8%80%E5%8A%A08Pro%E5%81%9A%E8%AF%84%E6%B5%8B_%E5%8D%B4%E5%B8%A6%E7%9D%80%E5%AE%83%E6%BC%82%E6%B5%81.mp4_1080.mp4

## 问题机型/系统：

真机 小米9 Android 10

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.5'

## Demo中的复现步骤

1.PlayerFactory.setPlayManager(IjkPlayerManager.class);
2.Demo中使用任意一个播放器在onVideoSizeChanged()中获取宽高都不正确

问题代码：(如果有)
```
public class MainApplication extends Application{
     ...
     PlayerFactory.setPlayManager(IjkPlayerManager.class);
     //PlayerFactory.setPlayManager(SystemPlayerManager.class);//切换这个就能正确获取
     ...
}


public class HomeListVideo extends StandardGSYVideoPlayer {
    @Override
    public void onVideoSizeChanged() {
        super.onVideoSizeChanged();
        Log.e("video","width="+getCurrentVideoWidth()+" height="+getCurrentVideoHeight());
    }
}
```

## 问题log（如果有）

```
//使用IjkPlayerManager
E/video: width=1080 height=1920(错误)
//使用SystemPlayerManager
E/video: width=1080 height=607(实际)
```

**Comment by CarGuo** [comment]
如下所示三张图，因为这类视频 ijk 上还有 VideoSarNum 和 VideoSarDen  要计算的

![image](https://user-images.githubusercontent.com/10770362/91375438-50909580-e84d-11ea-8ce2-94bfbef36d98.png)
![image](https://user-images.githubusercontent.com/10770362/91375465-5be3c100-e84d-11ea-8f7f-9e38de8cb812.png)
![image](https://user-images.githubusercontent.com/10770362/91375470-5f774800-e84d-11ea-9acb-7b900cbd66a5.png)

**Comment by fengxiaocan** [comment]
好的,那我明白了,如果是这类视频的真实高度,我需要这样做对吗?

```
int realHeight = (int)(getCurrentVideoHeight()/((float) VideoSarNum/VideoSarDen));
```

**Comment by CarGuo** [comment]
你参考下 MeasureHelper 的实现就可以了～

**Comment by fengxiaocan** [comment]
ok!明白了!谢谢!
