### ISSUE TITLE
视频暂停之后再播放会重新播放

### ISSUE THREAD

**Issue by meanhan** [CarGuo/GSYVideoPlayer#2928]
视频暂停之后再播放会重新播放

真机 小米9  Android10

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## Demo中的复现步骤

参考 demo EmptyControlVideo  重写 getLayoutId 方法  自定义空白播放器布局
调用videoPlayer.onVideoPause(); 暂停之后 调用videoPlayer.onVideoResume()  视频会重头播放 而不是继续播放

**Comment by CarGuo** [comment]
参考问题集锦，或者切换到 exo 内核

**Comment by meanhan** [comment]
问题集锦中找到了答案   因为ijk的FFMPEG对关键帧问题。
