### ISSUE TITLE
Recyview 使用 SnapHelper 上下滑动视频，不能自动播放

### ISSUE THREAD

**Issue by lyy90** [CarGuo/GSYVideoPlayer#2929]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在Recyview 中我使用SnapHelper 来一页切换播放视频，第一个能播放，滑动到第二个就不能自动播放，往回也不能播放。
 scrollCalculatorHelper.onScroll(recyclerView, firstVisibleItem, lastVisibleItem, lastVisibleItem - firstVisibleItem);

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

问题代码：(如果有)
  //限定范围为屏幕一半的上下偏移180
        int playTop = CommonUtil.getScreenHeight(this)  - CommonUtil.dip2px(this, 180);
        int playBottom = CommonUtil.getScreenHeight(this) + CommonUtil.dip2px(this, 180);
        //自定播放帮助类
        scrollCalculatorHelper = new ScrollCalculatorHelper(R.id.video_item_player, playTop, playBottom);
@Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                switch (newState) {
                    case RecyclerView.SCROLL_STATE_IDLE://停止滚动
                        position = -1;
                        View view = snapHelper.findSnapView(layoutManager);
                        RecyclerView.ViewHolder viewHolder = recyclerView.getChildViewHolder(view);
                        scrollPosition = viewHolder.getLayoutPosition();
                        if (dynamicDetailDynamicAdapter != null && !StringUtils.isEmpty(dynamicDetailDynamicAdapter.getData().get(scrollPosition).getVideo())) {
                            viewDelegate.pageText.setVisibility(View.GONE);
                            //视频
                            firstVisibleItem =layoutManager.findFirstVisibleItemPosition();
                            lastVisibleItem = layoutManager.findLastVisibleItemPosition();
                            //这是滑动自动播放的代
                                scrollCalculatorHelper.onScroll(recyclerView, firstVisibleItem, lastVisibleItem, lastVisibleItem - firstVisibleItem);
                        } else {
                            //图片
                            viewDelegate.pageText.setVisibility(View.VISIBLE);
                            if (dynamicDetailDynamicAdapter.getData().get(scrollPosition).getDynamicFileList() != null && dynamicDetailDynamicAdapter.getData().get(scrollPosition).getDynamicFileList().size() > 0) {
                                String content =  + 1  + "/" + dynamicDetailDynamicAdapter.getData().get(scrollPosition).getDynamicFileList().size();
                                viewDelegate.pageText.setText(Html.fromHtml(content));
                            }
                        }
                        initData(dynamicDetailDynamicAdapter.getData().get(scrollPosition));
                        break;
                    case RecyclerView.SCROLL_STATE_DRAGGING://拖动
                        break;
                    case RecyclerView.SCROLL_STATE_SETTLING://惯性滑动
                        break;
                }

            }

## 问题log（如果有）

`

xxxxxxx

```

**Comment by CarGuo** [comment]
????

**Comment by lyy90** [comment]
我就是做抖音那种效果的，上下滑动视频不能自动播放

**Comment by CarGuo** [comment]
这种属于需求上的问题了吧···你用ViewPage或者RecyclerVIew或者ViewPage2 都行啊，自动播放逻辑你自己控制·······
