### ISSUE TITLE
关于视频画面被拉伸的问题请教

### ISSUE THREAD

**Issue by lucky-you** [CarGuo/GSYVideoPlayer#2931]
问题描述：
1.我的项目中有一个直播的功能，我采用本播放器来作为播放端。
2.直播推流使用的是七牛云SDK。
3.现在的问题是：七牛的直播流是竖屏录制的的，而播放器的高度是固定的230dp，这样就会导致在播放的时候，画面被压缩拉伸了，我尝试着改变GSYVideo.setShowType()方法来适应流画面，但是效果不理想，压缩依然比较严重。
4.已知七牛云推流过程中不能竖屏录制推横向流，且项目产品需求又不进行横屏录制，只能竖屏录制。
请问：在以上条件下，从播放端入手可以有那些方法来解决被画面压缩拉伸的问题？

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

配置代码：
1.七牛云相机录制配置代码：
public static CameraConfig getCameraConfig() {
        CameraConfig mCameraConfig = new CameraConfig();
        mCameraConfig.mFrontFacing = true;
        mCameraConfig.mSizeLevel = CameraStreamingSetting.PREVIEW_SIZE_LEVEL.MEDIUM;
        mCameraConfig.mSizeRatio = CameraStreamingSetting.PREVIEW_SIZE_RATIO.RATIO_16_9;
        mCameraConfig.mFocusMode = Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO;
        mCameraConfig.mIsFaceBeautyEnabled = true;
        mCameraConfig.mIsCustomFaceBeauty = false;
        mCameraConfig.mContinuousAutoFocus = true;
        mCameraConfig.mPreviewMirror = false;
        mCameraConfig.mEncodingMirror = false;
        return mCameraConfig;
    }
2.播放端VideoPlayer配置代码：
       //增加封面
        ImageView imageView = new ImageView(mContext);
        imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
        GlideUtils.loadObjectImage(mContext, roomInfoBean.getRoom().getBgImage(), imageView);
        //外部辅助的旋转，帮助全屏
        orientationUtils = new OrientationUtils(mContext, playVideoView);
        //初始化不打开外部的旋转
        orientationUtils.setEnable(false);
        GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_16_9);
        Map<String, String> header = new HashMap<>();
        header.put("ee", "33");
        header.put("allowCrossProtocolRedirects", "true");
        GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder();

**Comment by CarGuo** [comment]
你看 MeasureHelper 的源码
