### ISSUE TITLE
视频自动从头播放

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2933]
## 问题描述：

很多用户反馈说，视频播着播着从头播了，这一般是什么问题？我应该要在哪里打日志确认这个问题？
@CarGuo 大佬帮忙看看

**Comment by CarGuo** [comment]
如果用的是默认的 ijk 模式，你看看切换到  PlayerFactory.setPlayManager(Exo2PlayerManager.class); ，有可能编码出现兼容问题。

**Comment by wangrunxiang** [comment]
@CarGuo 用得是exo模式

**Comment by wangrunxiang** [comment]
m3u8的视频，只能用exo模式，但是不知道哪方便的问题，不知道从哪里下手

**Comment by CarGuo** [comment]
如果是默认 exo 模式下 m3u8 的话，基本上就是 ts 的兼容问题，你可以看看 exo 的 hls 的 package 下的代码

**Comment by wangrunxiang** [comment]
我们自己尝试复现了一下，发现和网络有点关系，我们接了个自己的弱网的wifi，比较容易复现，非弱网没有成功复现

**Comment by wangrunxiang** [comment]
有没有可能和弱网重试之类相关的有关系？

**Comment by CarGuo** [comment]
我依稀记得还真的有这个问题，弱网络加载不到，然后重新播放，具体你可以看  exo 的 hls 的 package 下的代码

**Comment by wangrunxiang** [comment]
@CarGuo 说一下大概的情况？

**Comment by wangrunxiang** [comment]
@CarGuo 我这里另外一个开源项目底层也是exoplayer的，好像没有这个问题，我们之前一直用的另外的开源项目，好像是没有这个问题  exo的hls的package下的代码，是哪方面的原因，可以具体说一下吗？

**Comment by wangrunxiang** [comment]
![image](https://user-images.githubusercontent.com/10829860/91700374-61703c80-eba8-11ea-8543-fc8d8aea4bf7.png)
这里好多个类，完全没有头绪

**Comment by CarGuo** [comment]
现在用的应该是 2.11.3 的 exo 版本，另外主要看 playlist 的解析，还有是不是用了 `ExoPlayerCacheManager` ?

**Comment by wangrunxiang** [comment]
暂时还没有剩androidx用不了2.11.3

**Comment by wangrunxiang** [comment]
@CarGuo androidx之前应该用哪个版本？

**Comment by CarGuo** [comment]
2.9.3 好像

**Comment by wangrunxiang** [comment]
对，我们就是用的2.9.3 是存在这个问题

**Comment by wangrunxiang** [comment]
@CarGuo 对，我们用了ExoPlayerCacheManager，具体代码是CacheFactory.setCacheManager(ExoPlayerCacheManager::class.java)
和使用cache有关系？
我这边看你在demo的注释是说「//exo缓存模式，支持m3u8，只支持exo」
那应该是支持m3u8和支持exo的？

**Comment by wangrunxiang** [comment]
录了个视频，大佬帮忙看看?
http://dev.wangrunxiang.com/device-2020-08-31-203026.mp4
@CarGuo 
有点怀疑是弱网重试逻辑，到了次数之后就重置？

**Comment by wangrunxiang** [comment]
@CarGuo

**Comment by wangrunxiang** [comment]
@CarGuo 大佬这个有解吗？

**Comment by CarGuo** [comment]
我这边暂时没什么思路

**Comment by wangrunxiang** [comment]
@CarGuo 没办法无限重试吗？

**Comment by wangrunxiang** [comment]
那如果换一种方式呢？如果回调onplayerror，记录下当前进度，然后重新start的时候，seekonStart这个进度可行吗？@CarGuo

**Comment by CarGuo** [comment]
这个你可以自己继承后试试

**Comment by wangrunxiang** [comment]
继承什么？
但是我研究了一下，onPlayError回调的时候，好像拿不到当前进度，拿到的都是0

**Comment by CarGuo** [comment]
你在 onError 方法里获取 ，super 之前试试

**Comment by LuckyYangs** [comment]
> 继承什么？
> 但是我研究了一下，onPlayError回调的时候，好像拿不到当前进度，拿到的都是0

我也遇到这种情况了，求教兄弟姊妹解决的

**Comment by LuckyYangs** [comment]
> 那如果换一种方式呢？如果回调onplayerror，记录下当前进度，然后重新start的时候，seekonStart这个进度可行吗？@CarGuo

我现在也遇到自动从头播放这种情况了，请教兄弟怎么解决的，感激不尽！

**Comment by wangrunxiang** [comment]
从头播放一般是播放错误，解决方法是找出是啥问题，然后解决
