### ISSUE TITLE
ViewPager2+Fragment  中 实习自动播放 再切换后 还是播放的上一个Fragment 中的 视频 

### ISSUE THREAD

**Issue by liudaohong** [CarGuo/GSYVideoPlayer#2934]
ViewPager2+Fragment  中 实习自动播放 再切换后 还是播放的上一个Fragment 中的 视频 
有什么解决办法  除了 再切换直接调用   GSYVideoManager.releaseAllVideos();  来解决 还有其它的办法吗？

**Comment by CarGuo** [comment]
其实就是和demo 里的自动播放一样，你看看demo里的实现就好了

**Comment by liudaohong** [comment]
自动播放 是解决的 就是搭配 TabLayout 和Fragment  的时候出的问题

**Comment by liudaohong** [comment]
1  
  @Override
    public void onPause() {
        super.onPause();
        if (contentType ==0) {
            GSYVideoManager.onPause();
        }
    }

2 
 @Override
    public void onResume() {
        super.onResume();
        if (contentType == 0) {
            GSYVideoManager.onResume();
        }
}


这是放在Fragment 中 的  内部通过MainScrollCalculatorHelper 来判断自动播放的

**Comment by CarGuo** [comment]
不是很理解你有什么问题

**Comment by liudaohong** [comment]
就是 一个ViewPager 中 放几个有自动播放的Fragment  会产生播放混乱 （控制播放 暂停是个单例）

**Comment by CarGuo** [comment]
这种情况不属于播放器的问题，这边只关心 set 之后 startPlayLogic

所以我说和自动播放的 RecyclerVIew 场景一样，就是播放新的旧的释放，你这个 issue 的问题主要在于代码实现，不在于库。
