### ISSUE TITLE
截屏问题

### ISSUE THREAD

**Issue by guangmingxiong9999** [CarGuo/GSYVideoPlayer#2935]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

 我想整个屏幕截屏，截屏后发现播放控件是黑色的，其他view正常
截屏代码 
 View dView = activity.getWindow().getDecorView();
        dView.setDrawingCacheEnabled(true);
        dView.buildDrawingCache();
        Bitmap bmp = dView.getDrawingCache();

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by guangmingxiong9999** [comment]
截屏图片  ![C341EB9C16B40B6CFFEE80C600F15ABF](https://user-images.githubusercontent.com/19978284/91681863-5c989200-eb82-11ea-8714-123148c5e2c0.jpg)

**Comment by CarGuo** [comment]
截图参考 DetailControlActivity
