### ISSUE TITLE
播放本地视频，并且开启缓存，会一直重复缓存，直到ROM占满

### ISSUE THREAD

**Issue by jizni** [CarGuo/GSYVideoPlayer#2936]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放本地视频，并且开启缓存，会一直重复缓存，直到ROM占满

## 问题机型/系统：

开发板 rt328 /Android7.1

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Demo中未复现

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
播放本地视频，并且开启缓存？？？？？
首先看是什么内核，然后播放的是 raw 还是 SD 卡的

**Comment by jizni** [comment]
使用exo 播放 raw，rawresource://的方式，另外我尝试了一下，应该和缓存无关，关闭和开启都会一直占用ROM

**Comment by CarGuo** [comment]
raw 用的是 RawResourceDataSource ，你看下源码就知道为什么了

**Comment by jizni** [comment]
好的，谢谢
