### ISSUE TITLE
全屏播放崩溃

### ISSUE THREAD

**Issue by zhaoweiguo5505** [CarGuo/GSYVideoPlayer#2938]
private ViewGroup getViewGroup() {
        return (ViewGroup) (CommonUtil.scanForActivity(getContext())).findViewById(Window.ID_ANDROID_CONTENT);
    }

找不到 ID_ANDROID_CONTENT

我用的是jetpack  全局只有一个activity  用的databing

**Comment by CarGuo** [comment]
为什么会没有呢？

**Comment by cl9211** [comment]
> ```
> private ViewGroup getViewGroup() {
>     return (ViewGroup) (CommonUtil.scanForActivity(getContext())).findViewById(Window.ID_ANDROID_CONTENT);
> }
> ```
> 
> 找不到 ID_ANDROID_CONTENT
> 
> 我用的是jetpack 全局只有一个activity 用的databing

你这个问题后来怎么解决的？我现在也出现，使用databinding，getViewGroup()空指针了

**Comment by QIMOU** [comment]
我也遇到了这个问题

**Comment by CarGuo** [comment]
我比较好奇为什么你们会没有 
```
    public static final int ID_ANDROID_CONTENT = com.android.internal.R.id.content;
```
