### ISSUE TITLE
视频加载问题

### ISSUE THREAD

**Issue by lihaodong** [CarGuo/GSYVideoPlayer#2939]
## 问题描述：

视频总时长变为0,停留在当前页面，无法再次播放

## 问题机型/系统：

例如 真机 vivo Android 9.0

## GSY依赖版本

`implementation 'com.shuyu:GSYVideoPlayer:7.1.5'`

##  截图地址
http://appcdn.yiboshi.com/image/WX20200901-105023@2x.png

**Comment by CarGuo** [comment]
？？？？

**Comment by lihaodong** [comment]
第一小节播放完毕，连播播放第二小节，偶尔会出现这个问题

**Comment by CarGuo** [comment]
没能复现，没辙啊······
