### ISSUE TITLE
音频焦点被抢占后播放器异常

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2941]
## 问题描述：

音频焦点被抢占后，播放器异常，视频总时长变成00：00，点击播放和暂停按钮都没有反应

## Demo中的复现步骤

如视频所示
http://dev.wangrunxiang.com/device-2020-09-03-150752.mp4

**Comment by CarGuo** [comment]
setReleaseWhenLossAudio

**Comment by wangrunxiang** [comment]
这个问题我通过复写onlossAudio，在方法里面暂停视频来实现，但是看了你这个接口好像更优雅一些。

但是无论是我自己解决的方式，还是说通过你的这个接口，有个问题是被别的app抢走了焦点了之后，点继续播放抢不回来了，而是两个音轨一起播放

**Comment by CarGuo** [comment]
你需要这句话 

mAudioManager.requestAudioFocus(onAudioFocusChangeListener, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);

**Comment by wangrunxiang** [comment]
在播放的时候加这句话？在哪个位置加这句话收敛一点？

**Comment by CarGuo** [comment]
默认情况下 mReleaseWhenLossAudio 和 这段代码是绑定的，你看 onVideoResume

**Comment by wangrunxiang** [comment]
没明白什么意思？确实这段代码在onVideoResume里面有，但是实际上是没有效果

**Comment by wangrunxiang** [comment]
在继续播放的时候并没有抢到焦点，而是两个音轨一起播放

**Comment by wangrunxiang** [comment]
GSYVideoControlView的clickStartIcon方法，当点击播放按钮的时候完全没有走到onVideoResume，是直接调用了getGSYVideoManager().start();

**Comment by wangrunxiang** [comment]
@CarGuo

**Comment by CarGuo** [comment]
····你可以继承然后添加自己相加的逻辑
