### ISSUE TITLE
抢占焦点问题，从全屏切换回来竖屏异常

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2943]
## 问题描述：

先上视频
http://dev.wangrunxiang.com/device-2020-09-04-190246.mp4

播放器设置了参数setReleaseWhenLossAudio(false)，看代码这个参数的作用是丢失焦点的时候，不释放，而是直接暂停。

一开始播放了酷狗音乐的歌，进去播放页的时候我们播放器抢占了焦点，音轨播放的是我们的视频，这时候酷狗音乐暂停，然后我们切换了全屏，没有异常，但是从全屏再切换回来竖屏的时候，酷狗也播放了，我们的视频也播放了。

分析了一下，有可能是酷狗抢占了焦点，或者是我们释放了焦点，我断点了一下GSYVideoView的onAudioFocusChangeListener
这个方法没有回调，也断点了一下GSYVideoView的所有mAudioManager.abandonAudioFocus方法，这个方法也没有调用到

**Comment by wangrunxiang** [comment]
这个时候我们把我们的视频点击暂停，酷狗也跟着暂停了

**Comment by CarGuo** [comment]
这个不属于gsy的问题了，策略问题，你可以自己继承后自定义，至于酷狗我们就更加干预不上了

**Comment by wangrunxiang** [comment]
应该是焦点的问题没处理完善吧？@CarGuo
