### ISSUE TITLE
有辦法取得ExoPlayer的getApplicationLooper嗎?

### ISSUE THREAD

**Issue by CiaShangLin** [CarGuo/GSYVideoPlayer#2944]
## 问题描述：

目前在做360度的撥放器，所以用了這個library https://github.com/ashqal/MD360Player4Android
主要是把videoPlayer的surfaceView set給他，所以我取得撥放器是用new出來的不是findViewById來的
因為這個原因所以我的layout要完全重畫，撥放器原生的layout會被吃掉
會發生這個Warn的原因是我用Handler(Loop.getMainLooper())去操作UI，所以才噴出
SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
問題是出在她說exoPlayer操作上要在同一個線程上
所以我需要拿到videoPlayer的looper設置到我的handler
但是在StandardGSYVideoPlayer的handler的looper都是null
也沒辦法轉型成ExoPlayer拿來取getApplicationLooper()
請問這個還有救嗎?
參考 : https://blog.csdn.net/ZPCrobot/article/details/105751176

## 问题机型/系统：
華碩zenfone4，android 8

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'

## 问题log（如果有）
SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread

**Comment by CarGuo** [comment]
你可以自定义 PlayerManager ，参考 demo exo 目录，自定义 PlayerManger 可以让你自定义 mediaPlayer 的模式～你就能操作你要的 Handler 了，模式情况下哎不支持的
