### ISSUE TITLE
7.1.5 版本 设置播放器的进度不能很准确改变播放的进度 有个 1s内的精度差

### ISSUE THREAD

**Issue by liudaohong** [CarGuo/GSYVideoPlayer#2948]
7.1.5 版本 设置播放器的进度不能很准确改变播放的进度 有个 1s内的精度差

**Comment by liudaohong** [comment]
又发现一个  精度差 设置进度 是 14369  但是回调进度是 8466

**Comment by CarGuo** [comment]
这和关键帧有关系 https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
