### ISSUE TITLE
6.0.3版本 视频被某些软件压缩后显示不正常

### ISSUE THREAD

**Issue by woshigaokun1314** [CarGuo/GSYVideoPlayer#2949]
## 问题描述：

 事情是这样的， 公司视频部门做出来的视频播放正常（类似抖音竖屏全屏视频，编解码器：Timecode，H.264，AAC），但为了节省流量开支 经过HandBrake 软件的压缩后（ 尺寸等比变小，编解码器：H.264，AAC）播放器播放视频就会宽度占满，高度变矮了，视频显示就是那种被压扁的赶脚，我尝试更换内核和各种播放type 啥的均无效果。小弟菜鸡也无他法了，大佬请指教。多谢！

## 问题机型/系统：

真机 华为nova Android7.0，同事的另一个华为不知道型号

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
只能说，还是最新 demo
