### ISSUE TITLE
关闭视频时，黑屏问题

### ISSUE THREAD

**Issue by One28Piece** [CarGuo/GSYVideoPlayer#295]
关闭视频时，releaseAllVideos调用onComplete会出现黑屏，要怎么处理？把onComplete注释后，多次开关视频会闪退

**Comment by CarGuo** [comment]
你用的是哪种模式？关闭视频黑屏是播放器正常需求

**Comment by One28Piece** [comment]
单个播放器放在fragment中，按demo设置封面延迟500ms就不会黑屏，但是感觉很奇怪,能不能关闭就直接退出，不现实封面？

**Comment by CarGuo** [comment]
demo中能复现吗？
