### ISSUE TITLE
兼容阿里云播放器内核v7.1.5问题

### ISSUE THREAD

**Issue by zhangpfan** [CarGuo/GSYVideoPlayer#2952]
## 问题描述：
阿里云播放器最新版本（v7.1.5）要求在创建播放器完成后，prepare前调用mediaPlayer.setSurface(surface);请问该如何兼容？

## 问题机型/系统：

无

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'

## Demo中的复现步骤

无

问题代码：(如果有)
```
阿里云demo地址：https://alivc-demo-cms.alicdn.com/versionProduct/sourceCode/playVideo/5.1.5/ApsaraVideo_videoPlay_v5.1.5_Android_20200722.zip?spm=a2c4g.11186623.2.12.7868d8e7eruQV5&file=ApsaraVideo_videoPlay_v5.1.5_Android_20200722.zip

参考：com.aliyun.player.alivcplayerexpand.widget.AliyunRenderView   setSurfaceType方法
```

## 问题log（如果有）

```

无

```

**Comment by CarGuo** [comment]
通过 IPlayerInitSuccessListener 大致上可以实现····

**Comment by ZhuSky** [comment]
@zhangpfan 阿里云内核的代码能借鉴一下嘛😂
