### ISSUE TITLE
使用C方式依赖，MPG格式播放失败

### ISSUE THREAD

**Issue by gonghuiyuan516** [CarGuo/GSYVideoPlayer#2954]
#2517  问题描述：
使用C方式依赖，MPG格式播放失败
测试地址：https://test-1254147817.cos.ap-shenzhen-fsi.myqcloud.com/%E9%98%BF%E6%82%A0%E6%82%A0-%E6%97%A7%E6%A2%A6%E4%B8%80%E5%9C%BA(%E5%9B%BD%E8%AF%AD).mpg

## 问题机型/系统：

 真机 华为Pad AGS-W09

## GSY依赖版本
  implementation 'com.shuyu:gsyVideoPlayer-java:7.1.6'
  implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.6'
  implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.6'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：

XML
<com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
        android:layout_width="match_parent"
        android:id="@+id/video_player"
        android:layout_height="match_parent" />
Activity 👍 
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        standardGSYVideoPlayer = findViewById(R.id.video_player);

        String source1 = "https://test-1254147817.cos.ap-shenzhen-fsi.myqcloud.com/%E9%98%BF%E6%82%A0%E6%82%A0-%E6%97%A7%E6%A2%A6%E4%B8%80%E5%9C%BA(%E5%9B%BD%E8%AF%AD).mpg";
        standardGSYVideoPlayer.setUp(source1, true, "测试视频");
    }

**Comment by CarGuo** [comment]
Video: mpeg2video, 1 reference frame, none
Audio: mp2, 48000 Hz, 2 channels, 384 kb/s

格式没支持，可以看下面两个链接

https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q

https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md
