### ISSUE TITLE
pad版 UI设计为横屏，点击全屏，再返回时，页面会变成竖屏，请问怎么保持横屏状态

### ISSUE THREAD

**Issue by gaoyuan117** [CarGuo/GSYVideoPlayer#2955]
## 问题描述：

pad版 UI设计为横屏且播放窗口初始是小窗口。点击全屏按钮进入全屏页面。
目前存在的问题是：全屏后，再返回时，页面会变成竖屏

## GSY依赖版本
com.shuyu:GSYVideoPlayer:7.1.3

**Comment by gaoyuan117** [comment]
写错了

**Comment by CarGuo** [comment]
这是因为 resolveByClick 方法，不要调用这个方法～

**Comment by gaoyuan117** [comment]
//        if (orientationUtils.getIsLand() != 1) {
//            //直接横屏
//            orientationUtils.resolveByClick();
//        }
这个方法我已经注释掉了.我看着是OrientationUtils.backToProtVideo();这个方法中有设置:setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);

**Comment by CarGuo** [comment]
嗯嗯，这个也是

**Comment by gaoyuan117** [comment]
请问,我应该调用哪一个方法呢....

**Comment by CarGuo** [comment]
OrientationUtils 主要是改变方向的，如果不需要可以不用调用

**Comment by ff-frida** [comment]
> 这是因为 resolveByClick 方法，不要调用这个方法～

具体是在act中，复写onBackPressed（）方法中。是否资源的同时，不要调用（videoPlayer.getFullscreenButton().performClick();）就好了。

**Comment by git-maven** [comment]
> 嗯嗯，这个也是，主要的逻辑在 OrientationUtils 的方法调用

请问是要重写哪个方法呢

**Comment by CarGuo** [comment]
增加支持横屏幕全屏和竖屏变化，屏幕不旋转例子：[SimpleActivity](./app/src/main/java/com/example/gsyvideoplayer/simple/SimpleActivity.java) [SimpleDetailActivityMode2](./app/src/main/java/com/example/gsyvideoplayer/simple/SimpleDetailActivityMode2.java)
