### ISSUE TITLE
设置GSYVideoType.TEXTURE后全屏问题

### ISSUE THREAD

**Issue by wen14701083** [CarGuo/GSYVideoPlayer#2957]
## 问题描述：
启动时调用 GSYVideoType.setRenderType(GSYVideoType.TEXTURE) 后，
点击全屏时，先黑屏一下，然后进入全屏界面；
退出全屏时，偶尔窗口闪动一下，类似界面缩放（从小到固定窗口）。
其他设置：
setAutoFullWithSize(true)
setShowFullAnimation(false)

## 问题机型/系统：
黑屏小米5、红米7、小米9、小米10
退出闪动小米5、红米7

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.4'

**Comment by CarGuo** [comment]
Demo ？？？项目默认就是 `GSYVideoType.TEXTURE` ，我在小米和红米上测试 demo 正常

**Comment by wen14701083** [comment]
不好意思，发错了……GSYVideoType.SUFRACE


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 晚上6:31
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"文开"<14701083@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 设置GSYVideoType.TEXTURE后全屏问题 (#2957)





 
Demo ？？？项目默认就是 GSYVideoType.TEXTURE ，我在小米和红米上测试 demo 正常

**Comment by CarGuo** [comment]
SUFRACE 我在 demo 也没有出现呀～你在哪里出现的？
