### ISSUE TITLE
离线视频可以播放，但是缓存目录是空的

### ISSUE THREAD

**Issue by cowoboy007** [CarGuo/GSYVideoPlayer#2958]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

离线状态可以播放视频。然后我去看下缓存目录，StorageUtils.getIndividualCacheDirectory
                (this.getApplicationContext()).getAbsolutePath()，也就是这个地址是空的。那视频去哪里了呢

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
你看 getProxyUrl 方法里面的  isCached

**Comment by cowoboy007** [comment]
file:///data/user/0/xx.xx.xx/cache/video-cache/  确实缓存了。但是这个地址并不是设置的。这是怎么回事，用的小米10，miui11

**Comment by cowoboy007** [comment]
/storage/emulated/0/Android/data/xxx.xxx.xx/cache/video-cache   这个是StorageUtils.getIndividualCacheDirectory
(this.getApplicationContext()).getAbsolutePath()的地址。但是缓存取出来的地址/data/user/0/xx.xx.xx/cache/video-cache/

**Comment by CarGuo** [comment]
你按照 getProxyUrl 里的逻辑就对了
