### ISSUE TITLE
视频播放期间将网络断开后调用哪个回调方法？设置onError方法不会被调用

### ISSUE THREAD

**Issue by TimberBug** [CarGuo/GSYVideoPlayer#296]
在视频播放期间，将网络断开不会调用设置的onError方法，只有在没网情况下启动播放的时候才会调用onError方法，那么，在视频播放期间将网络断开后调用哪个回调方法呢？

**Comment by CarGuo** [comment]
最终版本，切换网络的error内部catch了，你可以继承播放器，在super之前拦截

**Comment by TimberBug** [comment]
是直接继承播放器重写内部的方法吗？这个要怎么搞，有没有demo呢

**Comment by CarGuo** [comment]
是的，然后在super拿到状态。新版本有网络状态字段。
