### ISSUE TITLE
exo m3u8缓存问题

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2960]
## 问题描述：

我这边看了文档说的是m3u8在exo下不支持缓存，说是让我们在播m3u8的时候，setUp方法的cacheWithPlay参数设为false，但是我又看到代码里面有注释
CacheFactory.setCacheManager(ExoPlayerCacheManager::class.java) //exo缓存模式，支持m3u8，只支持exo
说的意思好像是m3u8在exo下是设置这个能支持缓存

所以看得有点懵逼

**Comment by CarGuo** [comment]
ExoPlayerCacheManager 是用了 ExoPlayer 独特的缓存机制，这个机制支持 m3u8 的缓存。
默认的 ProxyCache 不支持 m3u8 的缓存。

**Comment by wangrunxiang** [comment]
如果exo播放器有ExoPlayerCacheManager这一套的话，为啥要写一套ProxyCache？

**Comment by CarGuo** [comment]
ProxyCache 是另外一种模式
