### ISSUE TITLE
Sound Not Working

### ISSUE THREAD

**Issue by ixiDev** [CarGuo/GSYVideoPlayer#2962]
Hi . 
I have implement the StandardPlayer like as in [SimplePlayer](https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/simple/SimplePlayer.java) but video sound not working

**My dependencies** 
```
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.6'
implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.6'
```
any solution for this?
thanks

**Comment by CarGuo** [comment]
Could you provide a  test video link？
