### ISSUE TITLE
某些机型视频声音画面不同步

### ISSUE THREAD

**Issue by weifengteng** [CarGuo/GSYVideoPlayer#2965]
## 问题描述：

同一段视频，在红米Note4X、红米K20和华为P20Pro、P10Plus等机型上会出现画面渲染变慢，严重滞后于声音的现象，但是在华为P30、VivoXplay6、OnePlus7 Pro等机型上能正常播放，音画同步。
## 问题机型/系统：

例如 真机 红米Note4X、红米K20和华为P20Pro、P10Plus等

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

##视频链接

http://br2-pl-agv.autohome.com.cn/video-43/275DC65D2C7E5C19/2020-09-13/8AB39FED4A7853936F15C4841F4F2CE2-400.mp4?key=49F110E46D319A59CC129FA0B276C932&;amp;time=1599985861

另外：一开始我以为是码率太高导致的，后来发现码率基本相同的另外一个视频能正常播放~

**Comment by CarGuo** [comment]
切换到 exo 内核模式，或者使用问题集锦的 dropframe

**Comment by weifengteng** [comment]
音画不同步的视频是1080P的，换成高清视频音画就能正常同步播放

**Comment by weifengteng** [comment]
> 3、视频的分辨率和帧数是多少，机器是否支持的了

> 第3步可以通过尝试降低倍数：

`VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);`


这个frameDrop不起作用

**Comment by yunshuipiao** [comment]
可能不是视频的分辨率和帧数的问题，同一段视频用不同的播放器，gsyvideoplayer 和 dkplayer，前者切换有问题，后者没问题。
实现方式不一样。原因猜测：#2979

**Comment by CarGuo** [comment]
@yunshuipiao 默认的 ijk 播放器用的是 cpu 播放 ，所以会有这样的情况的。如果是低端机型建议切换到 exo 使用 mediacodec 播放
