### ISSUE TITLE
自定义render不能很好的扩展

### ISSUE THREAD

**Issue by sunpan3213** [CarGuo/GSYVideoPlayer#2969]
## 问题描述：

为啥不可以在播放的时候,切换render,我需要openGL自定义VertexShader和FragmentShader

## 问题机型/系统：

所有机型

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'

**Comment by sunpan3213** [comment]
需要帮助

**Comment by CarGuo** [comment]
就像 demo DetailFilterActivity 里的 resolveTypeUI ，框架支持自定义 Effect 也就是 getShader

**Comment by sunpan3213** [comment]
自定义的Effect getShader只是自定义了FragmentShader,而VertexShader并没有自定义,所以完成不了更复杂的渲染

**Comment by sunpan3213** [comment]
VertexShader要自定义 就得去extend GSYVideoGLViewBaseRender
去扩展这个,又有限制,不能在播放的时候去切换这些自定义的GSYVideoGLViewBaseRender

**Comment by sunpan3213** [comment]
说白了就是:本库在自定义Effect的时候,只是自定义了片元着色器(FragmentShader),而没有自定义顶点着色器(VertexShader)

**Comment by CarGuo** [comment]
是的，不过你可以自定义 Surface 的控件，比如demo 的 CustomRenderVideoPlayer ，自定义 addTextureView

**Comment by sunpan3213** [comment]
自定义addTextureView后,可以在播放的时候随时更改上面我说的那些?

**Comment by CarGuo** [comment]
你就可以自定义 implements IGSYRenderView ，也就是可以自己做一个  CustomTextureSurface extends GLSurfaceView implements IGSYRenderView

**Comment by sunpan3213** [comment]
行吧,有点难度。看完你的代码  ,还得研究openGL的语法,头大。
本库有没有现成的美白效果以及其他滤镜(LUT加载/直方图/峰值对焦/伪色彩/斑马纹/安全框/图像放大/灰度/单色/波形图)这些

**Comment by sunpan3213** [comment]
本库要是结合下GPUImage库 就好了,那边渲染效果多

**Comment by sunpan3213** [comment]
问下:setCustomRenderer为什么一定要在initRender之前。这样的话,我自定义GLSurface也没用啊,还是不能再播放的时候切换render

**Comment by CarGuo** [comment]
因为里调用的是   setRenderer(mRenderer);

**Comment by sunpan3213** [comment]
也就是说之所以不能随意切换render就是因为调用了serRenderer?  这个方法是必调么?

**Comment by CarGuo** [comment]
setRenderer 是  GLSurfaceView 的方法

**Comment by sunpan3213** [comment]
实在不行 我就放弃openGL吧 
本库能不能对RTSP数据实现用FFmpeg来做实时滤镜啊

**Comment by sunpan3213** [comment]
> setRenderer 是 GLSurfaceView 的方法

那不对啊,即使我自定义这些。还是绕不过 setRenderer(mRenderer)。那也还是不能随时切换render啊?我理解的对么

**Comment by sunpan3213** [comment]
我知道你为什么要在prepare之前初始化好render,因为你没设置rendermode,然后要手动去调requestRender

**Comment by sunpan3213** [comment]
已经解决了,必须通过修改源码  才好搞  不然去集成  很难改,  后期 建议把openGl抽出来  那样方便扩展
