### ISSUE TITLE
java.lang.ClassCastException: android.support.v7.widget.AppCompatImageView cannot be cast to moe.codeest.enviews.ENPlayView

### ISSUE THREAD

**Issue by LLhon** [CarGuo/GSYVideoPlayer#297]
`java.lang.ClassCastException: android.support.v7.widget.AppCompatImageView cannot be cast to moe.codeest.enviews.ENPlayView
	at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.updateStartImage(StandardGSYVideoPlayer.java:612)
	at com.video.LandLayoutVideo.updateStartImage(LandLayoutVideo.java:60)
	at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.changeUiToPlayingShow(StandardGSYVideoPlayer.java:478)
	at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setStateAndUi(StandardGSYVideoPlayer.java:231)
	at com.shuyu.gsyvideoplayer.GSYVideoPlayer.onInfo(GSYVideoPlayer.java:947)
	at com.shuyu.gsyvideoplayer.GSYVideoManager$7.run(GSYVideoManager.java:511)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5682)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)`

BugTags记录有很多机型都会出现这个问题, 如何解决?

**Comment by CarGuo** [comment]
log上说的，你看看哪些地方可能存在ImageView和ENView的转化有问题，一般是局部文件中的播放按键和项目默认的ENView不一样，你在getLayoutId是不是用了全屏和非全屏两种布局之类的。

**Comment by LLhon** [comment]
就是使用了你Demo里的LandLayoutVideo类,部分代码
` //这个必须配置最上面的构造才能生效
    @Override public int getLayoutId() {
        if (mIfCurrentIsFullscreen) {
            return R.layout.sample_video_land;
        }
        return R.layout.sample_video_normal;
    }

@Override protected void updateStartImage() {
        if (mIfCurrentIsFullscreen) {
            ImageView imageView = (ImageView) mStartButton;
            if (mCurrentState == CURRENT_STATE_PLAYING) {
                imageView.setImageResource(R.drawable.video_click_pause_selector);
            } else if (mCurrentState == CURRENT_STATE_ERROR) {
                imageView.setImageResource(R.drawable.video_click_play_selector);
            } else {
                imageView.setImageResource(R.drawable.video_click_play_selector);
            }
        } else {
            super.updateStartImage();
        }
    }`

**Comment by LLhon** [comment]
我觉得应该是某种情况下在横屏状态这个mStartButton变成了ImageView,所以强转出错

**Comment by CarGuo** [comment]
那你断点跟踪下，是哪个地方的强制转化出现了问题，demo中是否复现？如果是你这样说的，那就是mIfCurrentIsFullscreen没生效这样的可能性。话说，你manifest和demo一样配置了吗？

**Comment by LLhon** [comment]
manifest里播放视频的activity是必须要加上下面这个吗?
android:configChanges="orientation|keyboardHidden|screenSize"
android:screenOrientation="portrait"

**Comment by CarGuo** [comment]
是的，不然全屏或者选择的时候会导致activity重新构建

**Comment by LLhon** [comment]
好的, 我项目里少了这个. 谢谢,麻烦了
android:screenOrientation="portrait"

**Comment by LLhon** [comment]
测试了下,不是configChanges属性的问题.这个崩溃不是必现的,所以还难调试出来.

**Comment by CarGuo** [comment]
这种强制类型转化，只有可能什么地方出现在异常，导致全屏之类的标志位判断有问题，然后出现了强制转化有问题，所以吖，你可以用判断下类的类型咯，避免下。

**Comment by jinguangyue** [comment]
我也遇到了这个问题， 在使用LandLayoutVideo的时候， 原因就是在切换成全屏的时候 sample_video_land 这个布局文件里的start按钮是imageview的 然后强转成EnplayView的时候出现了强转错误， 解决方式就是把布局sample_video_land文件中的id 为start的mageview布局改成EnplayView布局， 并且在屏幕居中显示

<moe.codeest.enviews.ENPlayView
        android:id="@+id/start"
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:visibility="invisible"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:layout_gravity="center_vertical" />

这个时候肯定不会报错了， 但是还有个小问题是全屏暂停的时候按钮状态没变， 因为在LandLayoutVideo类里面更新的还是imageview, 这里将这个方法改成EnPlayView即可 

@Override
    protected void updateStartImage() {
        if (mIfCurrentIsFullscreen) {
            if(mStartButton instanceof ENPlayView){
                ENPlayView enPlayView = (ENPlayView) mStartButton;
                if (mCurrentState == CURRENT_STATE_PLAYING) {
                    enPlayView.pause();
//                    imageView.setImageResource(R.drawable.video_click_pause_selector);
                } else if (mCurrentState == CURRENT_STATE_ERROR) {
//                    imageView.setImageResource(R.drawable.video_click_play_selector);
                } else {
                    enPlayView.play();
//                    imageView.setImageResource(R.drawable.video_click_play_selector);
                }
            }
        } else {
            super.updateStartImage();
        }
    }
