### ISSUE TITLE
Application 中关闭ijk的log无效。

### ISSUE THREAD

**Issue by KunNiu** [CarGuo/GSYVideoPlayer#2971]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

Application 中设置了
IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
但是还无法关闭Ijk的日志。

## 问题机型/系统：

真机 一加5T & 华为 Mate20Pro

## GSY依赖版本
```
implementation "com.shuyu:gsyVideoPlayer-java:7.1.6"
implementation "com.shuyu:gsyVideoPlayer-armv7a:7.1.6"
implementation "com.shuyu:gsyVideoPlayer-arm64:7.1.6"
```

![image](https://user-images.githubusercontent.com/17312834/93991955-84fd6000-fdbf-11ea-92b3-e27cfe677633.png)

**Comment by CarGuo** [comment]
这个就是关闭了，基本上解析和播放中的信息都没有打印了，剩下的屏蔽不了

**Comment by DysaniazzZ** [comment]
@CarGuo 都关闭了但是还是会打印`V/IJKMEDIA: setDataSource: path xxx`，能否关闭呢？
