### ISSUE TITLE
如何更改单个播放器音量？

### ISSUE THREAD

**Issue by ZainCzy** [CarGuo/GSYVideoPlayer#2972]
## 问题描述：
播放多个视频时 如何控制其中某个播放器的音量 而不是整个设备音量

## 问题机型/系统：
真机 小米MIX2S Android11.0

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by CarGuo** [comment]
PlayerManager 有 setVolume 的接口
