### ISSUE TITLE
你好，能告诉我处理播放区域的宽高是在哪里处理的吗？

### ISSUE THREAD

**Issue by androidzhangjin** [CarGuo/GSYVideoPlayer#2974]
我模仿StandardGSYVideoPlayer，写了自己的MyVideoPlayer extends GSYVideoPlayer ，然后删除了其中返回键、底部、头部、全屏按钮、加载中弹窗，只保留暂停按钮、进度条，并且把进度条2.5s后隐藏的功能也屏蔽了。将原先的进度条下移到播放区域下面，免得挡住视频编辑。但是现在出问题了，手机拍照视频无法正常播放，原因是宽度和高度颠倒了。但是你的StandardGSYVideoPlayer是可以正常播放的，请问你处理视频宽高的逻辑在哪里？

**Comment by CarGuo** [comment]
不理解你的意思

**Comment by androidzhangjin** [comment]
我的是红米手机，竖屏拍摄了一个视频，宽度：1080，高度：1920，但是我通过代码获取的宽度：1920，高度：1080，最终播放的视频是一个正方形的，宽高都是1080，原因是播放区域是横的，宽1920，高1080，但是视频仍然是竖着的，所以高于1080的部分被截断了。最终显示的部分就是一个正方形。但是奇怪的是，我用StandardGSYVideoPlayer却没有这个问题，你能告诉我StandardGSYVideoPlayer是在哪里解决宽高颠倒的问题吗？

**Comment by CarGuo** [comment]
在 onInfo 回调里读取了 rotate 参数，然后在 MeasureHelper 里处理展示逻辑。
