### ISSUE TITLE
Fragment no longer exists for key f#0: unique id b6a7707d-5751-4ac5-a240-4ff7c8bcade7

### ISSUE THREAD

**Issue by yong396040003** [CarGuo/GSYVideoPlayer#2975]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

大佬请教一下，我viewpage2中嵌套recycleview,点击其中item打开悬浮播放，点击悬浮播放最大化，最大化横屏就报这个异常，请问怎么解决？

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不大理解的情况，可能你没有参考 demo 配置 manifest 之类的

**Comment by yong396040003** [comment]
recycleview放在fragment里面，全屏横屏就会报这个错，全屏竖屏不会报错，请问怎么解决？

**Comment by CarGuo** [comment]
参考 demo 配置 manifest 了没

**Comment by yong396040003** [comment]
ok,我的问题，我把config设置到了全局导致未生效，麻烦了，谢谢
