### ISSUE TITLE
关于播放过程中手动设置静音的问题

### ISSUE THREAD

**Issue by cjcj125125** [CarGuo/GSYVideoPlayer#2976]
## 问题机型/系统：

 真机 OPPO K5

## GSY依赖版本

   api 'com.shuyu:gsyVideoPlayer-java:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-armv7a:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-armv7a:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-arm64:7.1.6'
    api 'com.shuyu:GSYVideoPlayer-exo2:7.1.6'
使用的是默认内核

## Demo中的复现步骤

您好，我的需求是在播放视频过程中可以手动  开启/关闭 静音，但是使用
GSYVideoManager instance().setNeedMute(true)方法后无效，后查看issue后按照您的提示在
GSYVideoManager.instance().setPlayerInitSuccessListener 中设置静音有效，但是并不满足我在播放过程中开启关闭静音的需求，我查看了源码，尝试按照你说的方法再获取到IPlayerManager后使用IMediaPlayer的setVolume方法在播放过程中设置静音依然无效，特来请教，烦劳您看到之后指点一二，感激不尽！
问题代码：(如果有)
```
GSYVideoManager instance().setNeedMute(true)
GSYVideoManager.instance().setPlayerInitSuccessListener{
GSYVideoManager.instance().isNeedMute=true
}
```

## 问题log（如果有）
GSYVideoManager.instance().setPlayerInitSuccessListener
这里在设置静音可行，但是无法实现播放过程中多次 开启/关闭  静音，
另外指定播放进度setSeekOnStart方法有跳动问题，在源码里面已经看到了您的标注，希望给与解决思路，再次感谢

```

**Comment by CarGuo** [comment]
GSYVideoManager instance().setNeedMute(true) 本来就可以用啊，你看 demo 中 ListVideoActivity 和  RecyclerViewActivity 都有item静音，全屏有声音的效果

**Comment by cjcj125125** [comment]
和模式有关系吗？

**Comment by cjcj125125** [comment]
我看到了你代码是写在setVideoAllCallBack 的onPrepared方法里面的呀，但是我的需求是在播放过程中有一个按钮点击可以开启关闭静音，这个时候视频是可以继续播放的，请问应该怎么调用？

**Comment by CarGuo** [comment]
GSYVideoManager instance().setNeedMute(true)  是要在 onPrepared 之后调用才有效，也就是 prepare 成功后，你就可以直接调用，你看 ListVideoActivity 和 RecyclerViewActivity 不也是这样么····

**Comment by cjcj125125** [comment]
指定播放进度setSeekOnStart方法有跳动问题，这个怎么解决？求指点

**Comment by CarGuo** [comment]
切换到 exo 内核，或者参考问题集锦的精准 seek @cjcj125125
