### ISSUE TITLE
低端机多次横竖屏，声画不同步，黑屏问题

### ISSUE THREAD

**Issue by yunshuipiao** [CarGuo/GSYVideoPlayer#2979]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

低端机多次横竖屏，声画不同步，黑屏问题

## 问题机型/系统：

OPPO A59，Android 5.1 (5系统以下大概率出现)

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.6'`

## Demo中的复现步骤

Demo 中 第一个按钮 简单播放进入，第4个按钮 简单详情 进入开始播放，多次横竖屏 复现

问题原因：
切换到横屏后，每次需要新建播放器，同时创建GSYTextureView用来播放view，在低端机器初始化比较慢，多次就会黑屏。
全局替换   `GSYVideoType.setRenderType(GSYVideoType.SUFRACE` 也还是有问题。

```
    /**
     * 添加播放的view
     */
    public static GSYTextureView addTextureView(Context context, ViewGroup textureViewContainer, int rotate,
                                                final IGSYSurfaceListener gsySurfaceListener,
                                                final MeasureHelper.MeasureFormVideoParamsListener videoParamsListener) {
        if (textureViewContainer.getChildCount() > 0) {
            textureViewContainer.removeAllViews();
        }
        GSYTextureView gsyTextureView = new GSYTextureView(context);
        gsyTextureView.setIGSYSurfaceListener(gsySurfaceListener);
        gsyTextureView.setVideoParamsListener(videoParamsListener);
        gsyTextureView.setRotation(rotate);
        GSYRenderView.addToParent(textureViewContainer, gsyTextureView);
        return gsyTextureView;
    }
```
 
是否可以尝试复用同一个 player 来解决问题？

@CarGuo

**Comment by yunshuipiao** [comment]
同时请教一个问题，为什么使用两个播放器来做横竖屏切换的处理？

**Comment by CarGuo** [comment]
这里需要解释下的是不是两个播放器，而是两个 view 而已，PlayerManager 里的 Player 对象是不变的，只是用两个 View 来做状态切换。

另外你说的也是有的，GSYVideoHelper 做了这是， demo 里的  RecyclerView2Activity 和 ListVideo2Activity 就是用一个播放view 去做这个。

**Comment by yunshuipiao** [comment]
@CarGuo 那遇到的低端机的横竖屏切换，是否可以参考上述的两个 Activity ，用同一个播放view来处理？

**Comment by CarGuo** [comment]
@yunshuipiao 我这边测试的红米5和荣耀的老机器，都是测试没有问题的，如果再低的性能机器就不考虑兼容了。
如果你像使用同一个 view 的模式，你可以看 demo 的  demo 里的 `RecyclerView2Activity` 和 `ListVideo2Activity` ，他们就是用 `GSYVideoHelper ` 去实现的。

**Comment by yunshuipiao** [comment]
@CarGuo 我看了下demo，两个 Activity下播放，在 oppo A59 上横屏还是会存在同样的问题，我们还是需要兼容这部分机器。
同时在 dkplayer 里面，同样的情况不会出现。我看能不能把那边的做法搬过来用。
非常感谢回复。

**Comment by CarGuo** [comment]
@yunshuipiao 你切换到 exo 内核也会么？

另外我用 demo 试了在云测上找了 oppo  A53 上测试正常，详情你可以看附件，欢迎你的反馈。


[1601261781873968.mp4.zip](https://github.com/CarGuo/GSYVideoPlayer/files/5289712/1601261781873968.mp4.zip)

**Comment by yunshuipiao** [comment]
@CarGuo 我们一只用的 exo 的内核。demo里面也用的是exo的内核。

**Comment by yunshuipiao** [comment]
@CarGuo 可以加下您的联系方式讨论下吗？

**Comment by yunshuipiao** [comment]
[device-2020-09-28-113747.mp4.zip](https://github.com/CarGuo/GSYVideoPlayer/files/5289788/device-2020-09-28-113747.mp4.zip)
这是刚刚复现的视频，在上述页面下都会出现。
