### ISSUE TITLE
播放过程中手动设置播放位置

### ISSUE THREAD

**Issue by cjcj125125** [CarGuo/GSYVideoPlayer#2980]
## 问题描述：

在播放过程中跳转到指定位置，使用setSeekOnStart方法无效

## 问题机型/系统：

真机小米 9 SE

## GSY依赖版本

 api 'com.shuyu:gsyVideoPlayer-java:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-armv7a:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-armv7a:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-arm64:7.1.6'
    api 'com.shuyu:GSYVideoPlayer-exo2:7.1.6'

## Demo中的复现步骤

在需求中需要实现点击按钮跳转到指定位置播放，已经获取到了需要播放位置的时间戳，但是使用setSeekOnStart方法无效，查看源码后看到您说需要在startPlayLogic之前调用，这样的话体验不是很好，并且画面会闪烁，请教怎么解决？

问题代码：(如果有)
```
 playerView.seekOnStart = it.begin
```

## 问题log（如果有）

```

 

```

**Comment by CarGuo** [comment]
你可以在播放器 prepared 成功后，调用 player. getGSYVideoManager().seekTo(mCurrentPosition); 或者直接使用  GSYVideoManager.instance().seekTo();

**Comment by cjcj125125** [comment]
换了播放内核为EXO然后使用player. getGSYVideoManager().seekTo(mCurrentPosition); 完美解决了问题，非常感谢
