### ISSUE TITLE
ExoSourceManager.setExoMediaSourceInterceptListener问题

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2981]
## 问题描述：

我们使用了ExoSourceManager.setExoMediaSourceInterceptListener这个方法来定制里面的MediaSource,然后，我们把这个方法写在页面的Activity中，用匿名内部类的形式写在Activity中，然后会产生内存泄漏，我们在这个Activity的onDestory中释放掉这个listener，调用的是ExoSourceManager.resetExoMediaSourceInterceptListener()这个方法。
至此，内存泄漏解决。

但是，如果在这个基础上再启动一个播放器的页面，就是说这个Activity再start一次，现在栈里面有两个实例，栈顶的实例在展示，这个时候按back键，回调onDestory，ExoSourceManager.resetExoMediaSourceInterceptListener()是全局的，释放了引用。这个时候回到栈底的activity实例，这个时候就产生播放异常，getExoMediaSourceInterceptListener返回的也是null，也就是说自定义的MediaSource没生效。

这个问题，我注释掉resetExoMediaSourceInterceptListener，就没问题了。

这些情况下，有没有一些优雅的解决方案？

@CarGuo

**Comment by CarGuo** [comment]
ExoSourceManager.setExoMediaSourceInterceptListener 只能写在全局 Application 的

**Comment by wangrunxiang** [comment]
那何时resetExoMediaSourceInterceptListener

**Comment by CarGuo** [comment]
不需要其实，跟随 Application 就够了

**Comment by wangrunxiang** [comment]
如果放在Application的话，终究会影响启动速度，虽然微乎其微，还有其他方式吗？

**Comment by CarGuo** [comment]
开玩笑，不会影响启动速度的，这个只是一个 set 方法，只会在播放器开始时才会被调用执行到

**Comment by wangrunxiang** [comment]
额，虽然微乎其微，好吧，看来只有这样了
