### ISSUE TITLE
视频画面缓慢问题

### ISSUE THREAD

**Issue by HongWeiChen** [CarGuo/GSYVideoPlayer#2982]
## 问题描述：

视频画面很缓慢，视频时长只有18s，也确定只有18s，视频地址如下
https://1251093851.vod2.myqcloud.com/3f3edd0avodtransgzp1251093851/ebace3165285890807433738575/v.f162021.mp4
跟机型应该关系不大，用模拟器也是如此，内核用的是IJK，用的都是默认设置，没有其他的处理。

## 问题机型/系统：

真机：Vivo Z1

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.6'

## Demo中的复现步骤

使用
https://1251093851.vod2.myqcloud.com/3f3edd0avodtransgzp1251093851/ebace3165285890807433738575/v.f162021.mp4
此地址播放就可以复现，其他视频地址正常。

**Comment by CarGuo** [comment]
7280 × 4096 的分辨率·····

**Comment by HongWeiChen** [comment]
> 7280 × 4096 的分辨率·····

........
