### ISSUE TITLE
多个Activity实例问题

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2983]
## 问题描述：

我们的Activity继承GSYBaseActivityDetail，然后定制了里面的MediaStore，启动一个Activity实例，正常播放
但是，如果在这个基础上再启动一个播放器的页面，就是说这个Activity再start一次，现在栈里面有两个实例，栈顶的实例在展示，这个时候按back键，回调onDestory，这个时候就产生播放异常，甚至异常没有回调IjkExo2MediaPlayer的onLoadError和onPlayerError。

我猜测是否栈顶的实例在onDestory的时候，释放了一些什么资源是全局的，导致后续的栈底的activity不能正常resume。
定制MediaStore的代码已经挪到Application，这方面不影响。

操作如下视频
http://dev.wangrunxiang.com/device-2020-09-28-154013.mp4

**Comment by wangrunxiang** [comment]
麻烦大佬帮忙看看
@CarGuo @CarGuoSmall

**Comment by CarGuo** [comment]
这么说吧，默认只有一个播放内核，所以有新的播放的情况下，旧的应该就已经被 release 了，除非你需要多内核模式的播放器

**Comment by wangrunxiang** [comment]
@CarGuo 那如果是这种场景，应该怎么解决？
多内核模式？有对应接口吗？

还是说回来的时候，重新初始化然后播放视频？

**Comment by CarGuo** [comment]
一般是回来的时候，重新初始化然后播放视频会比较合适。
以为多开内核会很占用内存

**Comment by wangrunxiang** [comment]
重新初始化播放视频感觉还是比较麻烦的，因为onResume的时候，不知道是不是已经release了，有好的判断方式吗？
@CarGuo

**Comment by wangrunxiang** [comment]
多开内核会靠谱点？具体有接口吗？
@CarGuo

**Comment by wangrunxiang** [comment]
onresume回来的时候，有可能是从另一个播放页面回来，这时候有新的播放，回来的时候需要重新初始化，也有一种情况是，从一个普通的页面回来，或者从其他app回来，这个时候不会有新的播放覆盖原有的播放，这个时候不需要重新初始化。

但是问题是，这种状态不好判断，项目里面有这种相关的接口吗？

**Comment by CarGuo** [comment]
一般就是单个内核，onresume 的时候判断当前页面是否被释放了，是的话就重新setup 和 setSeekonStart 去播放

**Comment by wangrunxiang** [comment]
所以问题在不好判断是不是被释放了，有api吗？

**Comment by CarGuo** [comment]
你需要继承后重载里面的 onCompletion  方法，新的播放旧的VIew 会调用 onCompletion

**Comment by wangrunxiang** [comment]
所以是onCompletion回调的时候做个标志位，然后onresume的时候判断这个标志位？如果为true的话就重新初始化？
但是问题在于，也会有很多场景会回调onCompletion的，怎么区分开其他场景的onCompletion还是这种导致的onCompletion？

**Comment by CarGuo** [comment]
正常的结束还有  onAutoComplete

**Comment by wangrunxiang** [comment]
切集之类的那些场景也会有onAutoComplete？
有没有这个之外的场景是是只回调onCompletion的？

**Comment by CarGuo** [comment]
切集是 onCompletion，onAutoComplete 就是正常播放结束的

**Comment by wangrunxiang** [comment]
所以还是区分不开是切集还是说这个问题吧？
如果我在onCompletion的时候将标志位置为true，在onAutoComplete置为false的话，其实切集也是会触发onCompletion并且不会触发onAutoComplete的，我们在onresume的时候，区分不开是之前切过集还是被新开的一个播放页导致的问题，如果是新开一个播放页被抢走的话才要重新初始化，如果仅仅只是之前有切集的动作的话，是不需要重新初始化的

**Comment by CarGuo** [comment]
切集是你的手动行为，你可以记录到

**Comment by wangrunxiang** [comment]
手动切集可以记录，但是一般业务来说，手动切集场景很多，要考虑很多，然后就是还有自动切集，就是ListGSYVideoPlayer的自动切集就没那么好记录了，虽然说也有回调。总体来说真的特别复杂，能否考虑提供个api判断当做这个player实例是否和播放内核相关联的接口，或者有其他的方式？

**Comment by CarGuo** [comment]
em···我觉得，要不你自定义 PlayerManager 吧？？？

**Comment by wangrunxiang** [comment]
自定义PlayManager怎么操作？

**Comment by CarGuo** [comment]
PlayManager 就是内核，面直接操作的就是 MediaPlayer， 结合  GSYVideoManager 里你可以根据传入的 Tag 之类的去做处理

**Comment by wangrunxiang** [comment]
GSYVideoManager的setPlayTag这个接口？我看这个接口的注释好像有别的作用，说是『播放的tag，防止错位置，因为普通的url也可能重复』
