### ISSUE TITLE
列表静音播放，偶现开始播放时会有一瞬间的声音

### ISSUE THREAD

**Issue by KunNiu** [CarGuo/GSYVideoPlayer#2984]
## 问题描述：

再做列表播放，在onPrepared里面设置的静音，偶现会有开始播放时有一瞬间声音。

## 问题机型/系统：

1加 5T，华为Mate20Pro，1加7

## GSY依赖版本

implementation "com.shuyu:gsyVideoPlayer-java:7.1.6"
implementation "com.shuyu:gsyVideoPlayer-armv7a:7.1.6"
implementation "com.shuyu:gsyVideoPlayer-arm64:7.1.6"

## Demo中的复现步骤

再做列表播放，在onPrepared里面设置的静音，偶现会有开始播放时有一瞬间声音。
跑demo也会出现。
这个问题发生的概率很小，但必须要解决啊……

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setPlayerInitSuccessListener(new IPlayerInitSuccessListener() {
            ///播放器初始化成果回调
            @Override
            public void onPlayerInitSuccess(IMediaPlayer player, GSYModel model) {
                player.setVolume(0,0);
            }
        });
