### ISSUE TITLE
这种地址无法播放

### ISSUE THREAD

**Issue by yong396040003** [CarGuo/GSYVideoPlayer#2985]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
```

## 问题log（如果有）

```

https://shuixian.nihaozuida.com/share/7610db9e380ba9775b3c215346184a87这个地址播放就报这个错误，浏览器能正常打开

```

**Comment by CarGuo** [comment]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/10770362/94503807-e7c87e80-0239-11eb-83c6-889ef29bf4a0.png">
这是一个 html 链接······
