### ISSUE TITLE
跳转页面视频仍在播放

### ISSUE THREAD

**Issue by cjcj125125** [CarGuo/GSYVideoPlayer#2986]
## 问题描述：

视频播放页面正常播放，跳转页面后视频仍在播放，已进入其他页面，依旧可以听到声音

## 问题机型/系统：

小米9 SE 

## GSY依赖版本

   api 'com.shuyu:gsyVideoPlayer-java:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-armv7a:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-armv7a:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-arm64:7.1.6'

## Demo中的复现步骤

点击播放按钮，点击另一按钮跳转到其他页面

问题代码：(如果有)
```
 生命周期onResume()调用playerView.onVideoResume()
 生命周期onPause()调用playerView.onVideoPause()
 生命周期onDestroy()调用playerView.release()
```

## 问题log（如果有）

```
请问这个操作有问题吗？

```

**Comment by CarGuo** [comment]
？？？？我测试正常呀

**Comment by cjcj125125** [comment]
我也很奇怪，是有魔鬼附身？？另外问一下，setGSYVideoProgressListener 接口回调播放进度的时间是一秒一次，能否自定义更短时间回调一次？

**Comment by CarGuo** [comment]
startProgressTimer
cancelProgressTimer

要重写这两个方法
