### ISSUE TITLE
手动设置播放进度问题seekTo

### ISSUE THREAD

**Issue by cjcj125125** [CarGuo/GSYVideoPlayer#2988]
## 问题描述：
我先说一下使用场景吧，根据字幕的开始和结束时间重复播放视频对应的片段，先获取字幕的开始时间startTime和结束时间endTime,先调用playerView.gsyVideoManager.seekTo(startTime)和playerView.onVideoResume()开始播放视频，然后调用用RxJava的time方法设置延迟时间为endTime和startTime的时间差(正数)，当RxJava里面走complete方法时候(此时也就是视频播放到了endTime)再调用playerView.onVideoPause()和 playerView.gsyVideoManager.seekTo(startTime),以此循环就可以达到循环播放对应字幕的这段视频了，大部分时间没问题，但是有的时候同一段重复播放几次后播放到endTime时候却没有回到startTime重新播放(此时rxjava time方法运行正常)，查看日志看到如下错误，猜想是seekTo方法内部问题，特来请教。

## 问题机型/系统：

真机 小米9SE 10.0

## GSY依赖版本
```
    api 'com.shuyu:gsyVideoPlayer-java:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-armv7a:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-armv7a:7.1.6'
    api 'com.shuyu:gsyVideoPlayer-arm64:7.1.6'
```

## Demo中的复现步骤
手动设置seekTo的时间，重复播放该时间段视频
playerView.gsyVideoManager.seekTo(startTime)和playerView.onVideoResume()

问题代码：(如果有)
```
Rxjava的定时方法我也贴一下，希望大佬能给予指点，万分感谢！
OnComplete()方法回调到主线程，再继续走seekTo方法播放，重复多次后出现卡点不准确或直接跳过了endtime一直播放下去。

    private fun startCountDown(OnComplete: () -> Unit) {
        val t = endTime - startTime
        Logger.i("时间差：${t} 总时间：${playerView.duration}")
        autoPlay=Observable.timer(t, TimeUnit.MILLISECONDS)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .doOnComplete {
                Logger.i("订阅完成111111")
                OnComplete()
            }
            .doOnError {
                Logger.i("订阅出错111111")
                autoPlay?.dispose()
            }.subscribe()

    }


```

## 问题log（如果有）

```

video accurate_seek is error, is->drop_vframe_count=0, now = 91775877, pts = 12.000000

```

**Comment by CarGuo** [comment]
不大清楚你说的，你说用 rx 做延时，然后重新 seek 到开始？？？
