### ISSUE TITLE
视频预加载

### ISSUE THREAD

**Issue by yi1234** [CarGuo/GSYVideoPlayer#2996]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

视频预加载 在垂直的ViewPager 中 预加载视频 快速滑动列表 有时候会关闭打开网络 会偶然出现某些视频播放不了 怀疑是自己关闭了代理服务器 日志如下！

## 问题机型/系统：

例如 真机 小米6 Android9.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.6'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
2020-10-13 11:58:33.254 22564-7435/com.hhe.xiuxiumedia E/IJKMEDIA: http://127.0.0.1:43276/https%3A%2F%2Fpapergo.top%2F%2Fvideo%2F20200919%2F4da73e7787a50a77534a9d45394a2b07.mp4: Invalid data found when processing input
2020-10-13 11:58:33.254 22564-22564/com.hhe.xiuxiumedia E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
    
    [          1602561513.255 22564:23022 W/Failed to close socket on proxy side: {}. It seems client have already closed connectioshutdown failed: ENOTCONN (Transport endpoint is not connected)
2020-10-13 11:58:33.371 22564-7436/com.hhe.xiuxiumedia E/ProxyCache error: Error opening connection for https://papergo.top//video/20200919/4da73e7787a50a77534a9d45394a2b07.mp4 with offset 2277376. Version: 7.1.6
2020-10-13 11:58:33.372 22564-23731/com.hhe.xiuxiumedia E/HttpProxyCacheServer error: Error processing request. Version: 7.1.6
    
    [          1602561513.373 22564:23731 W/Failed to close socket on proxy side: {}. It seems client have already closed connectioshutdown failed: ENOTCONN (Transport endpoint is not connected)

**Comment by CarGuo** [comment]
有可能，正常现象····

**Comment by yi1234** [comment]
对于这种问题 还可能会出现蓝屏没有全部缓存 打开网络 也不会重新缓存这个视频  有优化的处理方案吗？

**Comment by yi1234** [comment]
之前我监听播放器播放出错 onPlayError 调用这个 GSYVideoManager.instance().clearCache(getContext(),null,url)  代码清缓存时可以重新缓存某些播放不了的视频 但是有时候会偶然出现闪退 Channel is unrecoverably broken and will be disposed!

**Comment by CarGuo** [comment]
就是缓存过程被打断或者继续之后，可能会出现坏档，这时候就无法继续缓存和播放了，只能说清除。
然后这种缓存是通过 Service 方式去做的，频繁处理确实可能导致问题，建议参考 Demo DetailDownloadPlayer ，针对提前缓存部分，自己用 http 每次批量先下载，快速滑动的时候不需要去播放视频

**Comment by yi1234** [comment]
谢谢，我尝试下。

**Comment by yi1234** [comment]
我现在处理的方式 是 当取消下载任务的时候 如果文件未下载完成。 调用GSYVideoManager.instance().clearCache(getContext(),null,url)  清除这个视频的缓存 就可以处理掉坏挡的情况了。 快速滑动会播放视频 但是我会停止对应url的下载任务  处理你说的 快速滑动的时候不需要去播放视频。

**Comment by yi1234** [comment]
我可以贴下代码 你帮看下这种处理预加载处理方式合理吗？

**Comment by yi1234** [comment]
`public class PreloadManager {

    private static PreloadManager sPreloadManager;


    public static PreloadManager getInstance() {
        if (sPreloadManager == null) {
            synchronized (PreloadManager.class) {
                if (sPreloadManager == null) {
                    sPreloadManager = new PreloadManager();
                }
            }
        }
        return sPreloadManager;
    }

    /**
     * 标识是否需要预加载
     */
    private boolean mIsStartPreload = true;

    /**
     * 开始预加载
     *
     * @param rawUrl 原始视频地址
     */
    public void addPreloadTask(String rawUrl, int position) {
        HttpProxyCacheServer proxyCacheServer = ProxyCacheManager.instance().newProxy(XiuXiuApp.getInstance().getApplicationContext());
        if (!proxyCacheServer.isCached(rawUrl)){
            RequestCall requestCall = OkHttpUtils.get().url(proxyCacheServer.getProxyUrl(rawUrl))
                    .build();

            PreloadTask task = new PreloadTask();
            task.mRawUrl = rawUrl;
            task.mPosition = position;
            task.mCacheServer = proxyCacheServer;
            task.requestCall = requestCall;
            KLog.d("addPreloadTask: " + position);
            PreloadTask preloadTask = mPreloadTasks.get(rawUrl);
            if(preloadTask == null){
                mPreloadTasks.put(rawUrl, task);
            }
            if (mIsStartPreload) {
                //开始预加载
                task.executeOn();
            }
        }

    }

  

    /**
     * 通过原始地址取消预加载
     *
     * @param rawUrl 原始地址
     */
    public void removePreloadTask(String rawUrl) {
        PreloadTask task = mPreloadTasks.get(rawUrl);
        if (task != null) {
            task.cancelAndShutDown();
            mPreloadTasks.remove(rawUrl);
        }
    }


    /**
     * 保存正在预加载的{@link RequestCall}
     */
    private LinkedHashMap<String, PreloadTask> mPreloadTasks = new LinkedHashMap<>();

    /**
     * 取消所有的预加载
     */
    public void removeAllPreloadTask() {
        Iterator<Map.Entry<String, PreloadTask>> iterator = mPreloadTasks.entrySet().iterator();
        while (iterator.hasNext()) {
            Map.Entry<String, PreloadTask> next = iterator.next();
            PreloadTask task = next.getValue();
            task.cancelAndShutDown();
            iterator.remove();
        }
    }



}

public class PreloadTask {
    /**
     * 原始地址
     */
    public String mRawUrl;

    /**
     * 列表中的位置
     */
    public int mPosition;
    /**
     * 下载请求call
     */
    RequestCall requestCall;

    /**
     * VideoCache服务器
     */
    public HttpProxyCacheServer mCacheServer;


    /**
     * 是否正在预加载
     */
    private boolean mIsExecuted;

    /**
     * 是否下载完成
     */
    private boolean isDownOver;

    /**
     * 将预加载任务提交到线程池，准备执行
     */
    public void executeOn() {
        //如果已经缓存就不在缓存了
        if (mCacheServer.isCached(mRawUrl)){
            return;
        }
        if (mIsExecuted) {
            return;
        }
        mIsExecuted = true;

        requestCall.execute(new MemoryCallBack() {
            @Override
            public void onError(Call call, Exception e, int id) {
            }

            @Override
            public void onResponse(Boolean response, int id) {
                requestCall.cancel();
                mCacheServer.shutdown();
                mIsExecuted = false;
                isDownOver = true;
            }
        });
    }

    /**
     * 取消预加载任务
     */
    public void cancel() {
        if (mIsExecuted) {
            requestCall.cancel();
        }
    }

    public void cancelAndShutDown(){
        if (mIsExecuted) {
            if(!isDownOver){
                GSYVideoManager.instance().clearCache(XiuXiuApp.getInstance(),null,mRawUrl);
            }
            requestCall.cancel();
            mCacheServer.shutdown();
        }
    }

}
 在viewPager里的适配器添加下载任务 和 移除下载任务 这里未贴完整代码
 @Override
    public Object instantiateItem(ViewGroup container, int position) {

        if (mCurTransaction == null) {
            mCurTransaction = fragmentManager.beginTransaction();
        }

        VideoPageFragment fragment = new VideoPageFragment();
        if (entityList != null && entityList.size() > 0) {
            Bundle bundle = new Bundle();
            if (position >= entityList.size()) {
                bundle.putSerializable(VideoPageFragment.ENTITY, entityList.get(position % entityList.size()));
            } else {
                bundle.putSerializable(VideoPageFragment.ENTITY, entityList.get(position));
            }
            bundle.putString(PreConst.type, type);
            fragment.setArguments(bundle);
        }

        PreloadManager.getInstance().addPreloadTask(UrlConstants.API_URI +  entityList.get(position).getContent(), position);
        mCurTransaction.add(container.getId(), fragment,
                makeFragmentName(container.getId(), position));
//        KLog.d("position = " +position);
        fragment.setUserVisibleHint(false);

        return fragment;
    }


    @Override
    public void destroyItem(ViewGroup container, int position, Object object) {
        if (mCurTransaction == null) {
            mCurTransaction = fragmentManager.beginTransaction();
        }
        PreloadManager.getInstance().removePreloadTask(UrlConstants.API_URI +  entityList.get(position).getContent());
        mCurTransaction.detach((Fragment) object);
        mCurTransaction.remove((Fragment) object);
    }

`  我是参考了https://github.com/Doikki/DKVideoPlayer/blob/master/dkplayer-sample/src/main/java/com/dueeeke/dkplayer/activity/list/tiktok/TikTok2Activity.java

**Comment by yi1234** [comment]
这是我处理预加载的思路

**Comment by aheadlcx** [comment]
就是缓存过程被打断或者继续之后，可能会出现坏档，这时候就无法继续缓存和播放了，只能说清除。
然后这种缓存是通过 Service 方式去做的，频繁处理确实可能导致问题，建议参考 Demo DetailDownloadPlayer ，针对提前缓存部分，自己用 http 每次批量先下载，快速滑动的时候不需要去播放视频
-----------------
@CarGuo  请教一下，为什么会出现坏档了。    @yi1234 这样预加载，效果会差了很多，有没有办法可以判断，是坏档么

**Comment by yoloaheadlcx** [comment]
就是缓存过程被打断或者继续之后，可能会出现坏档，这时候就无法继续缓存和播放了，只能说清除。
然后这种缓存是通过 Service 方式去做的，频繁处理确实可能导致问题，建议参考 Demo DetailDownloadPlayer ，针对提前缓存部分，自己用 http 每次批量先下载，快速滑动的时候不需要去播放视频
---------------
现在没有通过 Service 来做了，频繁缓存打断或者继续，现在是不是不会出现坏档这个情况了。
@CarGuo
