### ISSUE TITLE
ijk内核播放 出现广告

### ISSUE THREAD

**Issue by ZhuSky** [CarGuo/GSYVideoPlayer#2997]
## 问题描述：

使用ijk内核播放时，出现广告
视频地址：https://video.kssznuu.cn/20200807/TiqZwGQt/index.m3u8
![image](https://user-images.githubusercontent.com/18596232/95841242-b42c3f00-0d77-11eb-8677-3b91e0589476.png)
使用exo内核 就可以正常播放

## 问题机型/系统：

三星s8， android10

## GSY依赖版本

'com.shuyu:GSYVideoPlayer:7.1.6'

## Demo中的复现步骤

修改内核为 PlayerFactory.setPlayManager(IjkPlayerManager.class);
修改播放器地址为：https://video.kssznuu.cn/20200807/TiqZwGQt/index.m3u8

**Comment by ZhuSky** [comment]
@CarGuo

**Comment by CarGuo** [comment]
？？？？

**Comment by ZhuSky** [comment]
您可以试一下，这个比较纳闷，麻烦看一看

**Comment by clairelee826** [comment]
> 您可以试一下，这个比较纳闷，麻烦看一看

那个是m3u8里面的广告。。。

**Comment by ZhuSky** [comment]
这个播放广告的问题解决了
我原来使用的是api 'com.shuyu:GSYVideoPlayer:7.1.6'
修改为：api 'com.shuyu:gsyVideoPlayer-ex_so:7.1.6'
就可以播放，没有广告

还有一个问题ijk播放内核的header中为啥存在两份同样的参数？？
![image](https://user-images.githubusercontent.com/18596232/96369531-255f5e00-118d-11eb-9021-b57762b0a036.png)
比如上图的Useer-Agent，第一个就莫名其妙。第二个就更懵了，参数中还有“Useer-Agent”
![image](https://user-images.githubusercontent.com/18596232/96369504-ecbf8480-118c-11eb-927c-9d84a689a74f.png)

**Comment by ZhuSky** [comment]
@clairelee826

**Comment by ZhuSky** [comment]
@CarGuo

**Comment by ZhuSky** [comment]
问题已解决：主要是因为header的值前面需要加一个空格
[https://github.com/bilibili/ijkplayer/pull/4946](B站的issues)
另给大家放一个 看到的踩坑记录
https://www.jianshu.com/p/0ae5924cc7d6
