### ISSUE TITLE
为什么我项目里的MP4小视频链接在Demo上播放不了。。请楼主指导下。万分感谢！

### ISSUE THREAD

**Issue by dalelufei** [CarGuo/GSYVideoPlayer#3]
我在我的工程里用楼主的播放器，播放这个链接： http://www.ettwit.com:8080/file/download/?u_id=41&type=app&id=553
 会抛出：HttpProxyCacheServer error    com.danikula.videocache.ProxyCacheException: Error closing socket output stream这个异常

**Comment by CarGuo** [comment]
HttpProxyCacheServer error com.danikula.videocache.ProxyCacheException: Error closing socket output stream 这个异常是正常的异常，因为缓存会强行关闭接口，cacth住不崩溃就可以，但是你这个url不是视频啊，你在浏览器打开试试，点击后直接下载了一个100K的文件。

**Comment by CarGuo** [comment]
HttpProxyCacheServer error com.danikula.videocache.ProxyCacheException: Error closing socket output stream 这个异常是正常的异常，因为缓存会强行关闭接口，cacth住不崩溃就可以，但是你这个url的视频是什么格式的，目前测试过的是支持MP4和m3u8。

**Comment by CarGuo** [comment]
IJKMEDIA:  http://www.ettwit.com:8080/file/download/?u_id=41&type=app&id=553: No such file or directory

**Comment by CarGuo** [comment]
这是不是视频流信息吧，这个是FTP模式的下载吧？

**Comment by dalelufei** [comment]
这个url的视频是mp4格式的。 是数据流信息。是HTTP模式的下载的。

**Comment by CarGuo** [comment]
这个url的服务器不支持流媒体，你可以复制demo里的url试试，流媒体在播放器里打开是可以直接播放的

**Comment by dalelufei** [comment]
我在公司内网，拍小视频，上传，播放，能正常播放的了。 可是在外网，拍小视频，然后用播放器播放的时候，就会报这个错误。

**Comment by CarGuo** [comment]
目前可以知道的是这个url我这边打开是不支持流媒体模式的

**Comment by CarGuo** [comment]
要不就是视频的编码格式不支持

**Comment by CarGuo** [comment]
E/IJKMEDIA: stream 0, offset 0x30: partial file
11-25 15:00:43.786 27860-29664/com.example.gsyvideoplayer W/IJKMEDIA: Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 480x360, 227 kb/s): unspecified pixel format
                                                                      Consider increasing the value for the 'analyzeduration' and 'probesize' options

**Comment by CarGuo** [comment]
这个视频文件是经过特殊处理过的吗？

**Comment by dalelufei** [comment]
有进行压缩过。是我自己录制的小视频

**Comment by dalelufei** [comment]
https://github.com/mabeijianxi/small-video-record   我是用这个项目进行录制的视频。

**Comment by CarGuo** [comment]
https://github.com/Bilibili/ijkplayer/issues/1141  
https://github.com/Bilibili/ijkplayer/issues/2060
对应找到了ijkplayer的issuse，应该是在视频的头部那里没找到对应的信息。我测试了这个项目录制下来的原视频本地是可以播放的。

**Comment by dalelufei** [comment]
是的。。我在内网上进行测试。都能跑的通。也可以边缓存，边播放。 可是在外网环境下录制下来的视频，进行播放就会抛出异常。我们的外网，目前是用的阿里云。

**Comment by CarGuo** [comment]
确实很奇怪，如果把视频拉倒本地就可以播放，但是如果是在url的话就播放不了，表现出的是在解码的时候找不到格式···不过同样的视频，我传到我们这边的七牛服务器就可以播放····

```
Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 480x360, 227 kb/s):    unspecified pixel format 。

Consider increasing the value for the 'analyzeduration' and 'probesize' options。

```

http://ocgk7i2aj.bkt.clouddn.com/1e9175e4-5f70-419a-81c4-ef1d92ce286f

**Comment by CarGuo** [comment]
个人觉得是服务器端的问题。

**Comment by dalelufei** [comment]
我也很费解。。郁闷了老半天，。可是在本地自己搭的那个服务器上又没问题。

**Comment by CarGuo** [comment]
我把视频传到七牛上也没问题，问题应该是出在了它身上！-> http://www.ettwit.com:8080/file/download/?u_id=41&type=app&id=553

**Comment by dalelufei** [comment]
那现在的解决方案，只能是先把视频下载到本地，再进行播放了。  在demo里，该怎么取消缓存。播放本地文件。

**Comment by CarGuo** [comment]
videoPlayer.setUp(url, false, "");   
 boolean cacheWithPlay字段传false

**Comment by dalelufei** [comment]
好的。谢谢您！！！！

**Comment by CarGuo** [comment]
如果可以请关闭issue，(＾－＾)V

**Comment by dalelufei** [comment]
Ok 我可以加下您QQ吗，以后有问题可以一起交流下。。@.@

**Comment by CarGuo** [comment]
你用简书吗？我简信发给你。

**Comment by dalelufei** [comment]
好的。。我简书联系你。。我把issue关了。
