### ISSUE TITLE
自动跳转到上一次播放位置

### ISSUE THREAD

**Issue by zhangfeisysu** [CarGuo/GSYVideoPlayer#30]
请问下郭大大，如何才能在播放视频前，跳转到上一次退出时的播放位置，然后接着播放呢？

**Comment by CarGuo** [comment]
有setSeekOnStart这个接口  https://github.com/CarGuo/GSYVideoPlayer/wiki/GSYVideoPlayer 第13

**Comment by zhangfeisysu** [comment]
我昨天试过这个方法了，发现播放网络视频的时候会一直缓冲，然后并没有跳转到指定位置，而只是跳了几秒就结束了，不知为何

**Comment by CarGuo** [comment]
有url可以试试嘛？你在demo中试过没？因为有些视频的被压缩后关键帧太少，ffmepg在seek的时候，没办法过去。

**Comment by zhangfeisysu** [comment]
已经可以啦，是因为我传过去的是秒，但实际需要的是毫秒，单位搞错了。谢啦

**Comment by CarGuo** [comment]
thx
