### ISSUE TITLE
播放m3u8格式的优酷视频,在播放了大概七八分钟左右时画面卡住,播放时间和seekbar进度还在变化,是什么情况?

### ISSUE THREAD

**Issue by LLhon** [CarGuo/GSYVideoPlayer#300]
播放m3u8格式的优酷视频,在播放了大概七八分钟左右时画面卡住,播放时间和seekbar进度还在变化,是什么情况?

**Comment by TimberBug** [comment]
我也遇到这个问题了，播着播着画面卡住了，然后获取当前的播放进度和播放状态，打印出来播放进度还是在增加，播放状态也是显示正在播放的，也不知道怎么解决了

**Comment by TimberBug** [comment]
这个问题该怎么解决啊？有没有人回答一下，谢谢啦

**Comment by CarGuo** [comment]
我试着播了十几分钟，熊猫？究竟是熊猫没动还是画面卡住了？？

**Comment by TimberBug** [comment]
我这边是画面卡住了，进度条时间还在一直增加，获取到的当前播放进度也在增加改变，后台一直打印这个https://user-images.githubusercontent.com/18308932/27470409-551c51f8-5826-11e7-8add-9ff5b31d1ebb.png

**Comment by CarGuo** [comment]
试试 设置暂停图片为false看看，coverpause这个

**Comment by TimberBug** [comment]
嗯，好的，我先试试这个，试过之后再来反馈信息

**Comment by TimberBug** [comment]
好像这个方法也不管用啊，我调用这个方法setShowPauseCover设置为true，可是这个暂停的图片还会显示的，然后又出现如图所示的情况，画面卡住不动，红圈圈住的时间在改变
![image](https://user-images.githubusercontent.com/18308932/27900372-bc351250-6260-11e7-9958-48a8acfb9398.png)

**Comment by CarGuo** [comment]
目前发现有点像是就上的问题。正在看

**Comment by CarGuo** [comment]
因为我这边不会复现，所以很奇怪

**Comment by TimberBug** [comment]
现在是什么情况？有解决这个问题的方法没有？

**Comment by CarGuo** [comment]
目前木有复现，没找到问题的点

**Comment by yang0000meng** [comment]
优酷的m3u8视频10分左右这个问题就会出现。

**Comment by Android-Boys** [comment]
表示也遇到了这个问题，大佬
