### ISSUE TITLE
使用ViewPager+Fragment 做纵向滑动的问题

### ISSUE THREAD

**Issue by wangpingtaohn** [CarGuo/GSYVideoPlayer#3001]
ViewPager+Fragment 做纵向滑动
发现纵向没法滑动(ViewPager纵向滑动代码没问题，已使用普通的Fragment试过)，但是Fragment里加了gsyvideoplayer就没法纵向滑动，好像是GSYVideoControlView的onTouch方法拦截处理了。
GSYVideoControlView版本：6.0.3

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/ViewPager2Activity.java

参考 Demo 使用的 ViewPager2 测试正常，onTouch 里 return 的是 false

**Comment by wangpingtaohn** [comment]
> https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/ViewPager2Activity.java
> 
> 参考 Demo 使用的 ViewPager2 测试正常，onTouch 里 return 的是 false

好的，我试试
