### ISSUE TITLE
有声音，无画面

### ISSUE THREAD

**Issue by fangzhouguang** [CarGuo/GSYVideoPlayer#3004]
大神你好，最近做一个视频和图片轮播的需求，用的是viewPager和Fragment组合，VideoFragment可见时开始播放，退出时释放资源。第一次切换VideoFragment正常播放，但是第二次轮播到VideoFragment的时候，画面会正常显示1秒左右然后就变成了一个黑底中间一个播放按钮的初始页面了但是还有声音，如果手动点一下播放按钮又可以出现画面了，一直没找到解决方案，求指点

**Comment by CarGuo** [comment]
demo 有类似 ViewPager 的方案，参考 demo ，这种情况一般是 surface 没创建

**Comment by fangzhouguang** [comment]
demo里没有类似ViewPager的实例呢

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/a678e3170fb212d5119cd72835b249c0eae56dbe/app/src/main/java/com/example/gsyvideoplayer/ViewPager2Activity.java @fangzhouguang
