### ISSUE TITLE
旋转视频，出现卡顿，音画不同步问题

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#3006]
## 问题描述：

旋转卡顿

## 问题机型/系统：

5.0以下手机, 大部分出现旋转卡帧，音视频不同步的问题，底下进度在跑，但是画面不动的问题
比如Oppo A59

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

复现步骤如视频
http://dev.wangrunxiang.com/device-2020-09-28-113747.mp4

**Comment by CarGuo** [comment]
低端机型没有支持的计划了

**Comment by wangrunxiang** [comment]
支不支持是一回事，有办法解吗？我们可以自己拉源码改？

是不是这种两个view旋转的方案导致这个问题？我看其他的没有用两个view的框架是没有这个问题的。是否因为使用这种方案而无解？

@CarGuo

**Comment by CarGuo** [comment]
我这边测试了一台老的 oppo ，demo 没有发现什么问题。一般低端机还是用 exo 或者 mediaplayer 这种 mediacodec 的解码模式好一些···
