### ISSUE TITLE
大佬，请教个无缝切换的问题

### ISSUE THREAD

**Issue by 627219641** [CarGuo/GSYVideoPlayer#3007]
m3u8的视频，如何做到更新替换ts文件列表从而实现无缝切换的效果。比如默认是普清的，点击切换高清后，10s后（假设ts的切片时间是10秒）视频变成高清

**Comment by CarGuo** [comment]
其实就是切换了两个 URL ，然后可以用两个内核，当新的内核加载完了之后 seek 成功，旧的内核释放，并把当前 View 的 Surface 切换到新的内核上，只要时间戳位置 seek 的一样，基本上看起来就类似无缝。

**Comment by 627219641** [comment]
看了下demo的无缝切换，看起来还是有点跳帧，目前我这边的实现方式是开一个本地服务器，m3u8文件指向本地地址，当需要切换清晰度的时候，再由本地服务器将ts地址指向真正的ts文件。但目前遇到的问题是，播放器怎么监听切换播放了哪个ts文件。
