### ISSUE TITLE
请问大神，如何与Rxffmpeg配合使用？

### ISSUE THREAD

**Issue by design365** [CarGuo/GSYVideoPlayer#3008]
## 问题描述：

如何与Rxffmpeg配合使用？我的项目本身已经集成Rxffmpeg,但是看到GSYVideoPlayer集成时候还有ffmpeg的so，这样重复会不会导致兼容性或者包过大。

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by design365** [comment]
Rxffmpeg的so是经过精简的，去掉了不常用的编解码器，所以想使用Rxffmpeg的so，能减少包的大小，不知道GSYVideoPlayer如何与Rxffmpeg集成使用？

**Comment by CarGuo** [comment]
这个还真不兼容这样的方式·····
