### ISSUE TITLE
Onclick of fullscreen button video is jumping to next video in Listview

### ISSUE THREAD

**Issue by RudreshJR** [CarGuo/GSYVideoPlayer#301]
Onclick of fullscreen button video is jumping to next video in Listview and it is working fine when using recyclerview

**Comment by CarGuo** [comment]
Which Activity cause this issue in Demo？

**Comment by RudreshJR** [comment]
In demo it is working fine Im using code of ListVideoActivity.. Is there any different implementation for Listview and RecyclerView??

**Comment by CarGuo** [comment]
did you config you activity in Androidmanifest like demo？

**Comment by RudreshJR** [comment]
Yes im using these things
           android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Translucent"

**Comment by CarGuo** [comment]
I have no idea for it not revplay in demo
