### ISSUE TITLE
播放视频没有声音 有画面

### ISSUE THREAD

**Issue by rwyrwy123** [CarGuo/GSYVideoPlayer#3010]
测试视频地址 ：http://123.56.109.212:8035/users/bfe52074fba74247853caa764b522731/films/orig/aa4c3451-0468-452a-a189-bd064a1963e5-鹿鼎记下.mp4

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.6'
//是否需要ExoPlayer模式
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.6'
//更多ijk的编码支持
implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.6'

**Comment by CarGuo** [comment]
设置用 exo 模式内核，ac-3 ijk 内核对音频不兼容

**Comment by rwyrwy123** [comment]
我在application的onCreate方法设置了  PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)  还是没有声音

**Comment by rwyrwy123** [comment]
> 设置用 exo 模式内核，ac-3 ijk 内核对音频不兼容
我在application的onCreate方法设置了 PlayerFactory.setPlayManager(Exo2PlayerManager::class.java) 还是没有声音

**Comment by rwyrwy123** [comment]
@CarGuo 我在application的onCreate方法设置了 PlayerFactory.setPlayManager(Exo2PlayerManager::class.java) 还是没有声音

**Comment by CarGuo** [comment]
我在demo测试有声音阿

**Comment by rwyrwy123** [comment]
我下载了你的demo 测试了还是没有声音

**Comment by rwyrwy123** [comment]
SimplePlayer类文件 修改了 String source1 = "http://192.168.0.164:8008/users/bfe52074fba74247853caa764b522731/films/orig/aa4c3451-0468-452a-a189-bd064a1963e5-鹿鼎记下.mp4";
MainActivity类文件：R.id.change_core    changeCore.setText("EXO 内核");

**Comment by CarGuo** [comment]
exo 内核是和手机硬件解码有关心的， 我试了红米pro5没声音，但是华为p30pro有声音

**Comment by tujingwu** [comment]
> exo 内核是和手机硬件解码有关系的， 我试了红米pro5没声音，但是华为p30pro有声音

请问我这边使用最新版本在两台小米手机也出现这个情况，这个怎办呢。一台小米11(android 11)，一台小米4c(android 7.0)
