### ISSUE TITLE
taskShotPic在非UI线程调用后获取到的bitmap是全黑的

### ISSUE THREAD

**Issue by chenxiaojin** [CarGuo/GSYVideoPlayer#3011]
## 问题描述：

新起了一个线程调用taskShotPic方法获取当前截图， 返回的bitmap是全黑的。
这个方法耗时有点大，在UI线程调用会造成卡顿，所以新起了线程处理。 
这个应该怎么解决？

## 问题机型/系统：

中兴9000N ， Android 10

## GSY依赖版本

com.shuyu:gsyVideoPlayer-java:7.1.5

**Comment by CarGuo** [comment]
这个方法不能跨线程调用的，你看源码就知道

**Comment by chenxiaojin** [comment]
> 这个方法不能跨线程调用的，你看源码就知道

这个方法有点耗时，有什么其他好的解决方案吗

**Comment by CarGuo** [comment]
推荐你看源码是实现原理
