### ISSUE TITLE
如何清除播放器上最后一帧画面，使播放器画面重置为黑屏状态？

### ISSUE THREAD

**Issue by ZainCzy** [CarGuo/GSYVideoPlayer#3012]
## 问题描述：

Manager stop() 之后如何清除播放器上最后一帧画面 使播放器画面重置为黑屏状态？

## 问题机型/系统：

真机 小米MIX 2S

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by ZainCzy** [comment]
getGSYVideoManager().stop();
setDisplay(null);
执行上述代码之后 播放器上依然留有最后一帧画面

**Comment by privateNirvana** [comment]
可以考虑直接release播放器

**Comment by CarGuo** [comment]
释放播放器自然就黑屏了
