### ISSUE TITLE
使用arm64-v8格式andk播放视频崩溃

### ISSUE THREAD

**Issue by privateNirvana** [CarGuo/GSYVideoPlayer#3013]
经过测试使用Android11小米Pro使用arm64-v8格式播放视频会崩溃，demo可复现，退到arm64-v7a一切正常
崩溃地址异常  InAanwMRTVVrI8ZeePbWww==/lib/arm64/libijkffmpeg.so

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/97151278-44bc4380-17aa-11eb-888b-1b96db3e63c4.png)


如上图，我用 demo 配置了  abiFilters 'arm64-v8a' 在 Pixel Android 11 上测试，没发现问题
