### ISSUE TITLE
ijkplayer 里面的ffmpeg升级到4.X版本

### ISSUE THREAD

**Issue by YumikoAzu** [CarGuo/GSYVideoPlayer#3015]
## 问题描述：
ijkplayer 里面的ffmpeg升级到4.X版本，https://www.jianshu.com/p/54598b1d6adc

**Comment by CarGuo** [comment]
这个改动比较大，后续试试

**Comment by zhkrb** [comment]
ijkplayer 主分支已经更新4.0了，可以试试

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/commit/a1abe4a279bfa88d0b405780cf9ab9dbf0a9753d
