### ISSUE TITLE
小窗模式保存上次拖拽的位置

### ISSUE THREAD

**Issue by liuxiaoyidegaoyaguo** [CarGuo/GSYVideoPlayer#3018]
在抽象类GSYBaseVideoPlayer代码showSmallVideo()方法中，每次都会把GSYBaseVideoPlayer对象放到屏幕右下角的位置，当我把小窗移动后再次显示小窗并没有记录上一次小窗存在的位置。
我尝试继承GSYBaseVideoPlayer后重写showSmallVideo()方法实现了该功能，希望能在处理全屏和小屏幕逻辑的抽象类完成该操作。

**Comment by CarGuo** [comment]
按照之前思路么，这个属于需要自己自定义实现的逻辑了～
