### ISSUE TITLE
播放m3u8这种直播流数问题

### ISSUE THREAD

**Issue by zoulin0011234** [CarGuo/GSYVideoPlayer#302]
播放器刚刚播放器来还是没问题的，但是在播放一段时间之后就会出现暂停按钮不停在界面闪的问题，给用户的感觉就像慢放一样，测试很多个版本都是这个问题
ps：附上直播流地址："http://live.mudu.tv/watch/khz1rv.m3u8

**Comment by zoulin0011234** [comment]
相同网络下 相同的地址 IOS和PC端没有出现这个问题

**Comment by CarGuo** [comment]
你是直播的？

**Comment by zoulin0011234** [comment]
嗯  是直播流数据

**Comment by zoulin0011234** [comment]
但是刚刚进去开始了是没有问题，一般播放在5分钟以后才会出现

**Comment by CarGuo** [comment]
我试试，在demo中复现的？

**Comment by zoulin0011234** [comment]
之前我是用的1.59做的播放，测试的没问题，后来用户就反应了这个问题，昨天和前天我升级版本到了1.68还是这个问题，昨晚demo测试了后面也是这个样子

**Comment by zoulin0011234** [comment]
数据流应该是没问题的，我们公司的IOS和PC端直播都是播放没问题的（相同网络下）

**Comment by CarGuo** [comment]
我试试，我刚刚播放了8分钟目前还没遇到

**Comment by CarGuo** [comment]
播放按键那个会频繁出现，那是因为卡流了吧？网络不停的在有buffer

**Comment by zoulin0011234** [comment]
但是相同网络下面，一样的地址，其他播放平台都没问题呢

**Comment by CarGuo** [comment]
刚刚用4G播放了有10多分钟，挺正常的，用的是demo的detailplayer

**Comment by zoulin0011234** [comment]
行，谢谢大神，我在测试一下，感觉听苦逼的，这个问题弄3天了，今天重新继承了你的界面了，要写截屏功能

**Comment by zoulin0011234** [comment]
这里没办法给你上图 看不到效果
