### ISSUE TITLE
本地raw文件播放失败E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0) ijk内核，默认模式

### ISSUE THREAD

**Issue by leifu1107** [CarGuo/GSYVideoPlayer#3021]
## 问题描述：

本地raw文件播放失败E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0) ijk内核，默认模式
//注意，用ijk模式播放raw视频，这个必须打开
        GSYVideoManager.instance().enableRawPlay(applicationContext)  代码已添加,播放无效

切换成 系统内核模式 后可以正常播放

## 问题机型/系统：

例如 华为手机 Android9

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
