### ISSUE TITLE
开始播放的啥时候设置needMute=true声音并没禁止掉

### ISSUE THREAD

**Issue by liyanfang** [CarGuo/GSYVideoPlayer#3022]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

开始播放的啥时候设置needMute=true声音并没禁止掉

## 问题机型/系统：

例如 真机 小米8，android10，小米4c，android7

## GSY依赖版本

例如 com.shuyu:gsyVideoPlayer-java：6.0.3，
com.shuyu:GSYVideoPlayer-exo2：6.0.3

## Demo中的复现步骤

直接调用GSYVideoManager.instance().setNeedMute(true);方法设置，debug初始化initVideo(Message msg) 方法也有执行，needMute=true

```

**Comment by CarGuo** [comment]
参考demo，在 onPrepared 里面或者 GSYVideoManager.instance().setPlayerInitSuccessListener 的  onPlayerInitSuccess 回调里设置

**Comment by may7be** [comment]
onPlayerInitSuccess 并不会回调
