### ISSUE TITLE
设置横屏没有效果(orientationUtils.setEnable(true))

### ISSUE THREAD

**Issue by wangpingtaohn** [CarGuo/GSYVideoPlayer#3024]
Activity中直接使用播放
一.manifest文件：
`<activity android:name=".viewpager.VideoActivity"
       android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
       android:screenOrientation="portrait"/>`
二.Activity代码
`class VideoActivity : BaseActivity() {

    private var orientationUtils: OrientationUtils? = null
    
    private val TAG = "VideoActivity"

    private var isPlay = false

    private var isPause = false

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_video)

        initView()
    }

    private fun initView() {
        btn_set.setOnClickListener {
        }

        initVideo()

    }

    override fun onConfigurationChanged(newConfig: Configuration) {
        Log.d(TAG, "onConfigurationChanged_newConfig=" + newConfig.orientation)
        super.onConfigurationChanged(newConfig)

        detail_player.onConfigurationChanged(this, newConfig, orientationUtils, true, true)

        val ivCover = ImageView(this)
        ivCover.setImageResource(R.drawable.ic_gh_foward)

    }

    private fun initVideo() {
        Log.d(TAG, "initVideo=")
        //外部辅助的旋转，帮助全屏
        orientationUtils = OrientationUtils(this, detail_player)

        val realUrl = "http://1400163667.vod2.myqcloud.com/d1c8688cvodtranscq1400163667/919ff6b05285890806449061880/v.f30.mp4"

        val gsyVideoOption = GSYVideoOptionBuilder()
        gsyVideoOption
            .setIsTouchWiget(true)
            .setRotateViewAuto(false)
            .setLockLand(false)
            .setAutoFullWithSize(true)
            .setShowFullAnimation(false)
            .setNeedLockFull(true)
            .setUrl(realUrl)
            .setCacheWithPlay(false)
            .setVideoTitle("测试视频")
            .setVideoAllCallBack(object : GSYSampleCallBack() {
                override fun onPrepared(url: String?, vararg objects: Any) {
                    super.onPrepared(url, *objects)
                    //开始播放了才能旋转和全屏
                    Log.d(TAG, "initVideo_onPrepared")
                    orientationUtils!!.isEnable = true
                    isPlay = true
                }

                override fun onQuitFullscreen(url: String?, vararg objects: Any) {
                    super.onQuitFullscreen(url, *objects)
                    if (orientationUtils != null) {
                        orientationUtils!!.backToProtVideo()
                    }
                }
            }).setLockClickListener { view, lock ->
                if (orientationUtils != null) {
                    //配合下方的onConfigurationChanged
                    orientationUtils!!.isEnable = true
                }
            }.build(detail_player)

        detail_player.getFullscreenButton().setOnClickListener(object : View.OnClickListener {
            override fun onClick(v: View) {
                //直接横屏
                orientationUtils!!.resolveByClick()

                //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                detail_player.startWindowFullscreen(applicationContext, true, true)
            }
        })

    }

    override fun onPause() {
        detail_player.onVideoPause()
        super.onPause()
        isPause = true

    }

    override fun onResume() {
        detail_player.onVideoResume(false)
        super.onResume()
        isPause = false
    }

    override fun onDestroy() {
        super.onDestroy()
        if (isPlay) {
            detail_player?.release()
        }
        if (orientationUtils != null)
            orientationUtils!!.releaseListener()
    }`

**Comment by CarGuo** [comment]
不理解，你是需要什么？

**Comment by wangpingtaohn** [comment]
> 不理解，你是需要什么？

手机旋转横屏后，视频随着切成横屏。

**Comment by CarGuo** [comment]
demo 里不是有么···

**Comment by wangpingtaohn** [comment]
> demo 里不是有么···

按照使用说明orientationUtils!!.isEnable = true这么设置，但是没效果。您说的demo里有，与我上面的代码使用场景的是哪个类呢？能否劳烦贴下链接吗？

**Comment by CarGuo** [comment]
比如  PlayActivity 、DetailPlayer 等
