### ISSUE TITLE
ViewPager+fragment 横屏问题

### ISSUE THREAD

**Issue by wangpingtaohn** [CarGuo/GSYVideoPlayer#3025]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

场景描述：
1.viewPager+fragment 视频播放
2.每个fragment中各自有个一个处理屏幕旋转的OrientationUtils。
3.需求是每个fragment根据视频的信息设置是否可以自动旋转横竖屏。
问题：
只要有一个Fragment设置了：
orientationUtils!!.isEnable = true
其他Fragment再设置orientationUtils!!.isEnable = false，不再起作用。
每个Fragment及OrientationUtils各自维护的对象，所以不明白这种情况怎么处理。

## 问题机型/系统：

所有机型

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8'`

## Demo中的复现步骤

看了下，demo里没有这样的场景。所以没法在demo中复现。

问题代码：(如果有)
```
.setVideoAllCallBack(object : GSYSampleCallBack() {
                override fun onPrepared(url: String?, vararg objects: Any) {
                    Debuger.printfError("***** onPrepared **** " + objects[0])
                    Debuger.printfError("***** onPrepared **** " + objects[1])
                    super.onPrepared(url, *objects)
                    //开始播放了才能旋转和全屏
                    val auto = (myPos % 2 == 0) //这里模拟比如偶数个位true，奇数位false
                    orientationUtils!!.isEnable = auto //只要一个fragment设置为true后，这里其他的Fragment设置false不会生效了
                    isPlay = true
                    }
                }
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
orientationUtils 从外部传进入

**Comment by wangpingtaohn** [comment]
> orientationUtils 从外部传进入

意思是从Activity传入吗？但是实例化orientationUtils的时候是需要传入GSYBaseVideoPlayer的，而GSYBaseVideoPlayer是在每一个Fragment里的呢

**Comment by CarGuo** [comment]
GSYBaseVideoPlayer 用同一个  orientationUtils 就好了，因为你不会同一时间多个同时播放

**Comment by wangpingtaohn** [comment]
> GSYBaseVideoPlayer 用同一个 orientationUtils 就好了，因为你不会同一时间多个同时播放

嗯嗯，明白了，多谢指点！！

**Comment by wangpingtaohn** [comment]
已解决。多个Fragment复用同一个OrientationUtils即可
