### ISSUE TITLE
能否实现预下载

### ISSUE THREAD

**Issue by coolyunyun** [CarGuo/GSYVideoPlayer#3028]
## 问题描述：

目前有这样一个需求，打开app先进行资源下载，如已下载完成，播放的时候则直接播放下载好的资源，如正在下载，则播放的时候边下边播。如未下载，则正常边下边播。 请问可否实现。

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8`

大佬，目前是否支持。或该如何处理。

**Comment by CarGuo** [comment]
参考 demo 的 DetailDownloadPlayer ，可以提前下载，然后播放，不支持m3u8
