### ISSUE TITLE
本地视频mp4文件被app删掉

### ISSUE THREAD

**Issue by dovginka** [CarGuo/GSYVideoPlayer#303]
当我播放本地视频mp4文件的时候，app点击home键，然后在最近的任务中把app kill掉，视频文件竟然没有了，是不是被app给删到了？？？

**Comment by CarGuo** [comment]
这个你可以断点看看，在播放error的时候会删除本地缓存，这个地方有个判断的bug导致删除数据，下个版本修正

**Comment by CarGuo** [comment]
2.0.1
