### ISSUE TITLE
exo内核下播放该MP4有声音无画面，ijk内核播放没有问题

### ISSUE THREAD

**Issue by hehuiran** [CarGuo/GSYVideoPlayer#3032]
![mp4文件信息](https://user-images.githubusercontent.com/23009126/98095574-b9d3fb00-1ec5-11eb-9f38-006a4cb99391.png)

## 问题描述：

http://static.hnyequ.cn/yequ_iOS/4940735da1227890e6a261937223e0d2_828x1472.mp4
在demo中GSYApplication中PlayerFactory.setPlayManager(Exo2PlayerManager.class)设置exo内核，
该MP4文件在exo内核下有声音无画面，ijk内核下没有问题，查看视频和音频编码格式分别是h264和aac，应该都是可以播放的，
结果在exo下出现有声音无画面，麻烦大佬帮忙看看，实在是不知道为什么

## 问题机型/系统：

真机 小米8 Android10

## GSY依赖版本

   api('com.shuyu:gsyVideoPlayer-java:6.0.3') {
        exclude group: 'com.android.support'
    }
    api 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
    api 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'

## Demo中的复现步骤

Demo中的GSYApplication onCreate中设置
PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
        ExoSourceManager.setSkipSSLChain(true);

SimplePlayer中source1赋值为http://static.hnyequ.cn/yequ_iOS/4940735da1227890e6a261937223e0d2_828x1472.mp4

然后运行，跳转到SimplePlayer播放出现黑屏，但是有声音

**Comment by CarGuo** [comment]
我在 detailPlayer 用 exo 测试，有画面有声音啊

**Comment by hehuiran** [comment]
为什么我这边demo播放不出来，大佬播的是http://static.hnyequ.cn/yequ_iOS/4940735da1227890e6a261937223e0d2_828x1472.mp4这个地址吗？
大佬能留个邮箱吗？我把我的demo运行效果发给你看下

**Comment by hehuiran** [comment]
大佬，我刚才试了一下最新的demo，发现没问题，但是用以前的老版本的demo，播不出来，大佬知道是什么问题吗？因为我们项目目前还没有使用androidx，所以只能用6.0.3的，所以会有这个黑屏有声音的问题

**Comment by CarGuo** [comment]
不大清楚，6版本的太老了···
