### ISSUE TITLE
有Api动态修改返回键图标，播放按钮图标，暂停按钮图标，进度条颜色么？

### ISSUE THREAD

**Issue by itsgm** [CarGuo/GSYVideoPlayer#3033]
问题描述：
想动态修改返回键图标，播放按钮图标，暂停按钮图标，进度条颜色，有相关Api可以设置么？

**Comment by CarGuo** [comment]
直接通过 getLayoutId 重载布局，参考 NormalGSYVideoPlayer 和 LandLayoutVideo
