### ISSUE TITLE
播放ts的时候，一直在加载，大概需要加载整个文件大小，然后才正常播放，请问这个有什么参数优化

### ISSUE THREAD

**Issue by zijin2014** [CarGuo/GSYVideoPlayer#3034]
![image](https://user-images.githubusercontent.com/9624595/98196037-1d116c00-1f5e-11eb-8989-d4cddbc048b2.png)
![image](https://user-images.githubusercontent.com/9624595/98196072-2d294b80-1f5e-11eb-959d-59df530bd4d1.png)

**Comment by CarGuo** [comment]
编码和关键帧问题，这种推荐 `PlayerFactory.setPlayManager(Exo2PlayerManager.class);`
