### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by v7lin** [CarGuo/GSYVideoPlayer#3035]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

部分视频无法播放

```
https://tx.hls.huya.com/src/78941969-2579769454-11080025436149776384-3144993630-10057-A-0-1-imgplus_2000.m3u8?wsSecret=3e6b5903368d02d0c591a57a07940cca&wsTime=5f4ca52f&u=0&seqid=15987721445850596&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103
```

## 问题机型/系统：

真机 华为nova4 Android10.0

## GSY依赖版本

```gradle
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8'
```

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：
```
        GSYVideoOptionBuilder()
            .setIsTouchWiget(false)
//            .setIsTouchWigetFull(!isLiveVideo)
            .setUrl(videoUrl)
            .setPlayPosition(playPosition)
            .setCacheWithPlay(false)
            .setRotateViewAuto(true)
            .setLockLand(true)
            .setMapHeadData(header)
            .setShowFullAnimation(false)
            .setNeedLockFull(true)
            .build(this)
```

**Comment by CarGuo** [comment]
E/IJKMEDIA: https://tx.hls.huya.com/src/78941969-2579769454-11080025436149776384-3144993630-10057-A-0-1-imgplus_2000.m3u8?wsSecret=3e6b5903368d02d0c591a57a07940cca&wsTime=5f4ca52f&u=0&seqid=15987721445850596&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103: Server returned 403 Forbidden (access denied)

**Comment by v7lin** [comment]
thanks
