### ISSUE TITLE
setSeekOnStart方法有时候有1-15秒的跳动问题，大家怎么处理的

### ISSUE THREAD

**Issue by yefangqingchen** [CarGuo/GSYVideoPlayer#3036]
setSeekOnStart方法有时候有1-15秒的跳动问题，大家怎么处理的，有什么比较好的处理办法。。或者优化的办法

com.shuyu:GSYVideoPlayer:7.1.4 版本

**Comment by CarGuo** [comment]
使用 exo 内核或者问题集锦的 第6 或者 第20 ，这个主要关键帧问题，参考 https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
