### ISSUE TITLE
缓存保存了，播不出来

### ISSUE THREAD

**Issue by sunbest110** [CarGuo/GSYVideoPlayer#3037]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by sunbest110** [comment]
![图片](https://user-images.githubusercontent.com/12553543/98760347-12e3e780-240e-11eb-8392-106518582be2.png)
![图片](https://user-images.githubusercontent.com/12553543/98760387-21ca9a00-240e-11eb-8572-096950117475.png)
![图片](https://user-images.githubusercontent.com/12553543/98760424-3444d380-240e-11eb-9f8f-4cc817035455.png)
首先我视频下载下来，为了保持两个地址一致，设置了cache地址，也可以看到确实缓存了，然后断网，切换到下一个，黑屏了，播不出来

**Comment by CarGuo** [comment]
不是很理解你的问题，我这边测试是正常的

**Comment by sunbest110** [comment]
我专门测试了一下，我不下载后面的，然后看缓存是否是缓存到我截图那个文件夹下，测试是的，然后我就打开我的下载，播第一个的时候，我就下载后面三个，然后当现在完成后，也就是上面截图里面那四个MP4文件，然后这个时候，我断网，滑动到第二个，这时候按理说不是有缓存了吗，应该播的出来，可实际却是一片黑屏，什么也播不出？？？

**Comment by sunbest110** [comment]
就是我播第一个的时候，下载了后面几个，然后断网去播后面几个都播不出来

**Comment by CarGuo** [comment]
这个你调试 ProxyCache 不就知道了为什么匹配不上了么····是用的最新版本么？

**Comment by sunbest110** [comment]
我用的是7.1.6,播放缓存会调用这个ProxyCache里面的那个方法呢？

**Comment by CarGuo** [comment]
ProxyCacheManager 会调用 HttpProxyCacheServer ，之后会调用 HttpProxyCacheServer  的 getProxyUrl ，其中有  getCacheFile 和 appendToProxyUrl

**Comment by sunbest110** [comment]
![图片](https://user-images.githubusercontent.com/12553543/98904754-2ddd5700-24f5-11eb-93e9-2be8bce15796.png)
我使用这种模式切换视频，只有第一个视频回调了你说的那些方法，剩下的都没回调

**Comment by CarGuo** [comment]
那不对哟～比如 IjkPlayerManager 里的 initVideoPlayer ，打开 cache 应该每次都会走 cacheManager.doCacheLogic

**Comment by sunbest110** [comment]
我这个也打了断点，只有第一个走了这个doCacheLogic方法

**Comment by sunbest110** [comment]
我在有网的情况下切换每次都会回调那些方法，但是我只要断网，只有第一个会被调用

**Comment by sunbest110** [comment]
我发现一个问题，就是我把第二个视频换到第一的位置，缓存管用了，我猜测可能是我切换时候有问题！

**Comment by CarGuo** [comment]
这个你需要自己调试下 setUp 的 cache  或者 setCacheWithPlay 得到的 mCacheWithPlay

**Comment by sunbest110** [comment]
嗯，搞定了了
