### ISSUE TITLE
如何设置最大的缓存时间呢？

### ISSUE THREAD

**Issue by GhRyuJin** [CarGuo/GSYVideoPlayer#3039]
## 问题描述：

在播放暂停后会一直缓存视频，知道整个视频缓存完成，使用的是EXO。

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.3'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.3'

## 复现步骤

暂停后可以看到网络一直走，知道整个视频缓存完成

**Comment by CarGuo** [comment]
不支持配置缓存时间，如果你是设置了 proxyCache 的就会这样，不实用 proxyCache 不会的，你可以设置 ExoCache， CacheFactory.setCacheManager(ExoPlayerCacheManager.class);

**Comment by GhRyuJin** [comment]
谢谢，但是我在了Application#onCreate方法设置成PlayerFactory.setPlayManager(Exo2PlayerManager.class);，CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
还是一样的会一直缓存。我试试看使用不缓存的方式会不会加载快一点


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 下午2:17
收件人:&nbsp;"CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"Ryu Jin"<1250242270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 如何设置最大的缓存时间呢？ (#3039)





 
不支持配置缓存时间，如果你是设置了 proxyCache 的就会这样，不实用 proxyCache 不会的，你可以设置 ExoCache， CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
