### ISSUE TITLE
如何调视频宽高

### ISSUE THREAD

**Issue by wangpingtaohn** [CarGuo/GSYVideoPlayer#3041]
## 问题描述：

使用LandLayoutVideo不知道怎么设置一个竖屏的视频的宽度铺满屏幕
视频
url:http://1400163667.vod2.myqcloud.com/d1c8688cvodtranscq1400163667/281cda485285890809403450535/v.f30.mp4
目前效果：

![image](https://user-images.githubusercontent.com/3996768/99057486-cc8db480-25d6-11eb-8948-6a6cdd5ae075.png)

期望效果：
左右两边不留黑边，铺满这个屏幕宽度
![image](https://user-images.githubusercontent.com/3996768/99057112-4a04f500-25d6-11eb-81aa-3824842d8ad6.png)

## 问题机型/系统：

所有机型

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8'`

## Demo中的复现步骤

Demo中的detailPlayer页面，
1.修改布局问题：activity_detail_player.xml里的以下代码
```<com.example.gsyvideoplayer.video.LandLayoutVideo    
        android:id="@+id/detail_player"    
        android:layout_width="match_parent"    
        android:layout_height="match_parent" /> 把200改为match_parent  
```

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
GSYVideoType.setShowType

```
    //全屏裁减显示，为了显示正常 surface_container 和 CoverImageView 建议使用 FrameLayout 作为父布局
    public final static int SCREEN_TYPE_FULL = 4;
```

**Comment by wangpingtaohn** [comment]
> GSYVideoType.setShowType
> 
> ```
>     //全屏裁减显示，为了显示正常 surface_container 和 CoverImageView 建议使用 FrameLayout 作为父布局
>     public final static int SCREEN_TYPE_FULL = 4;
> ```

请问下，在LandLayoutVideo里使用使用MeasureHelper来设置GSYVideoType.setShowType的呢？没有找到相关的代码示例。
