### ISSUE TITLE
列表页跳转到详情页时，如何把列表页的状态带到详情页

### ISSUE THREAD

**Issue by wangpingtaohn** [CarGuo/GSYVideoPlayer#3043]
## 问题描述：

1.目前列表页用的是StandardGSYVideoPlayer，详情页用的是LandLayoutVideo
2.当从列表页点击进入详情页的时候，如何把列表页播放的状态(进度)带到详情页？

## 问题机型/系统：

全部机型

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8'`

## Demo中的复现步骤

Demo中没有类似的场景，SwitchVideo我工程里没有使用到。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
参考demo
