### ISSUE TITLE
在recyclerView使用多任务支持播放rtsp，配置关闭缓冲后无效，播放一会就缓冲中卡主

### ISSUE THREAD

**Issue by a454436646** [CarGuo/GSYVideoPlayer#3048]
## 问题描述：
在recyclerView使用多任务支持播放rtsp，配置关闭缓冲后无效，播放一会就缓冲中卡主

## 问题机型/系统：

A64平板

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.6'

## Demo中的复现步骤

在recyclerView使用同时播放控件播放多个rtsp流视频，播放一会会出现缓冲中的图标然后卡住

问题代码：
//多个播放时必须在setUpLazy、setUp和getGSYVideoManager()等前面设置
                vv.setPlayTag(TAG);
                vv.setPlayPosition(helper.getPosition());
//                boolean isPlaying = vv.getCurrentPlayer().isInPlayingState();
//                if (!isPlaying) {
                    vv.setUpLazy(item.getVideoUrl(), false, null, null, "这是title");
//                }
                //增加title
                vv.getTitleTextView().setVisibility(View.GONE);
                //设置返回键
                vv.getBackButton().setVisibility(View.GONE);

                //设置全屏按键功能
                vv.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        resolveFullBtn(vv);
                    }
                });

//                vv.setRotateViewAuto(true);
//                vv.setLockLand(true);
//                vv.setReleaseWhenLossAudio(false);
//                vv.setShowFullAnimation(true);
//                vv.setIsTouchWiget(false);
//                vv.setNeedLockFull(true);

                vv.setVideoAllCallBack(new GSYSampleCallBack() {
                    @Override
                    public void onQuitFullscreen(String url, Object... objects) {
                        super.onQuitFullscreen(url, objects);
                        fullKey = "null";
                    }

                    @Override
                    public void onEnterFullscreen(String url, Object... objects) {
                        super.onEnterFullscreen(url, objects);
                        vv.getCurrentPlayer().getTitleTextView().setText((String) objects[0]);
                        fullKey = vv.getKey();
                    }

                    @Override
                    public void onAutoComplete(String url, Object... objects) {
                        super.onAutoComplete(url, objects);
                    }
                });
                vv.startPlayLogic();

## 问题log
11-25 16:44:22.127 27181-27194/com.example.charge I/art: Background sticky concurrent mark sweep GC freed 19514(1685KB) AllocSpace objects, 7(140KB) LOS objects, 19% free, 17MB/22MB, paused 16.342ms total 102.713ms
11-25 16:44:39.119 27181-27192/com.example.charge D/IJKMEDIA: IjkMediaPlayer_native_finalize
11-25 16:44:39.119 27181-27192/com.example.charge D/IJKMEDIA: IjkMediaPlayer_release
11-25 16:44:39.119 27181-27192/com.example.charge D/IJKMEDIA: IjkMediaPlayer_native_finalize
11-25 16:44:39.119 27181-27192/com.example.charge D/IJKMEDIA: IjkMediaPlayer_release
11-25 16:44:39.137 27181-27194/com.example.charge I/art: Background partial concurrent mark sweep GC freed 16833(912KB) AllocSpace objects, 5(92KB) LOS objects, 40% free, 17MB/29MB, paused 2.134ms total 161.831ms
11-25 16:44:41.598 27181-31411/com.example.charge D/IJKMEDIA: FFP_MSG_BUFFERING_START:
11-25 16:44:42.047 27181-31403/com.example.charge D/IJKMEDIA: FFP_MSG_BUFFERING_START:

**Comment by CarGuo** [comment]
要配置 tcp，看问题集锦
