### ISSUE TITLE
录制视频

### ISSUE THREAD

**Issue by liangdongbo** [CarGuo/GSYVideoPlayer#3049]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

您好，这个怎么实现在视频播放的时候边播放边录制功能

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:GSYVideoPlayer:7.1.6'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
你可以看源码 ProxyCacheManager ，用的是在本地开了一个代理服务分发流。
