### ISSUE TITLE
暂停后清屏的问题

### ISSUE THREAD

**Issue by zoulin0011234** [CarGuo/GSYVideoPlayer#305]
要做一个截图的功能，我现在测试截图的代码已经没问题了，但是现在播放器在动态播放时候我没有办法截取图像，暂停后上面会悬浮暂停按钮，尝试调了
/**
 * 设置触摸显示控制ui的消失时间
 * @param dismissControlTime 毫秒，默认2500
 */
public void setDismissControlTime(int dismissControlTime)
 也不能消失，请问下 这个可以怎么设置下

**Comment by CarGuo** [comment]
你可以参考项目中的暂停截图是怎么获取的，有个cover的东西，应该和你需要的一样
