### ISSUE TITLE
关于7.1.8播放MP4时异常停止

### ISSUE THREAD

**Issue by DocHuangys** [CarGuo/GSYVideoPlayer#3051]
## 问题机型/系统：

例如 rockchip yx_rk3288 

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8'`

## Demo中的复现步骤

全屏播放，播放过程中异常终止程序
问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
11-26 15:56:09.389 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 1, sample 3253, dts 69354667
11-26 15:56:09.389 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 0, sample 1667, dts 69375000
11-26 15:56:09.389 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 1, sample 3254, dts 69376000
11-26 15:56:09.427 18803-21080/com.hpd.eclass D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
11-26 15:56:09.460 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 0, sample 1668, dts 69416667
11-26 15:56:09.460 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 1, sample 3254, dts 69376000
11-26 15:56:09.470 18803-21081/com.hpd.eclass D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
11-26 15:56:09.480 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 0, sample 1668, dts 69416667
11-26 15:56:09.480 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 1, sample 3255, dts 69397333
11-26 15:56:09.480 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 0, sample 1668, dts 69416667
11-26 15:56:09.480 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 1, sample 3256, dts 69418667
11-26 15:56:09.512 18803-21077/com.hpd.eclass D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
11-26 15:56:09.521 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 0, sample 1669, dts 69458333
11-26 15:56:09.521 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 1, sample 3256, dts 69418667
11-26 15:56:09.521 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 0, sample 1669, dts 69458333
11-26 15:56:09.521 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 1, sample 3257, dts 69440000
11-26 15:56:09.521 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 0, sample 1669, dts 69458333
11-26 15:56:09.521 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 1, sample 3258, dts 69461333
11-26 15:56:09.553 18803-21078/com.hpd.eclass D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
11-26 15:56:09.595 18803-21079/com.hpd.eclass D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
11-26 15:56:09.637 18803-21080/com.hpd.eclass D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
11-26 15:56:09.642 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 0, sample 1670, dts 69500000
11-26 15:56:09.642 18803-21068/com.hpd.eclass V/IJKMEDIA: stream 1, sample 3258, dts 69461333
11-26 15:56:09.660 18803-18803/com.hpd.eclass D/IJKMEDIA: ijkmp_pause()
11-26 15:56:09.660 18803-18803/com.hpd.eclass D/IJKMEDIA: ijkmp_pause()=0
11-26 15:56:09.660 18803-21066/com.hpd.eclass D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_PAUSE
11-26 15:56:09.725 18803-18803/com.hpd.eclass D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
11-26 15:56:09.725 18803-18803/com.hpd.eclass D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
11-26 15:56:09.725 18803-18803/com.hpd.eclass D/IJKMEDIA: ffpipeline_set_surface()
11-26 15:56:09.725 18803-18803/com.hpd.eclass D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
11-26 15:56:09.737 18803-18803/com.hpd.eclass D/ViewRootImpl: 1920<<<<<< BACK FROM relayoutnull
11-26 15:56:10.679 18803-18803/com.hpd.eclass D/ViewRootImpl: onDetachedFromWindow ungister contentObserver
11-26 15:56:15.807 18803-18815/com.hpd.eclass D/IJKMEDIA: IjkMediaPlayer_native_finalize
11-26 15:56:15.807 18803-18815/com.hpd.eclass D/IJKMEDIA: IjkMediaPlayer_release

**Comment by DocHuangys** [comment]
测试URL： http://118.24.115.116/userdata/media/%e8%b5%b5%e9%9b%b7-%e6%88%90%e9%83%bd(%e8%93%9d%e5%85%89).mp4

**Comment by CarGuo** [comment]
demo 测试正常，没有复现

**Comment by DocHuangys** [comment]
我再demo上也是偶尔复现了一次，在项目上必现，ijk和exo都试了，一样的activity代码，崩溃时logcat没有异常日志，这就给解决问题造成麻烦，无法确定是库的问题还是我代码的问题

**Comment by CarGuo** [comment]
我试了倒是没有崩溃，到那时出现问题的log看到是 `Stream ends prematurely at 71303168, should be 122524198` ，说明是流出现了问题，具体为什么会这样这个你要和服务端推流的服务对一下了

**Comment by DocHuangys** [comment]
还有个问题，为什么我设置了setCacheWithPlay（true）,一定要切换到exo内核才能播放，不然就出现http url的连接异常，导致不能播放呢？

**Comment by CarGuo** [comment]
这个就不知道了·····估计是load不到end什么的情况了，ijk 用的 ffmpeg ，软解码肯定存在某些兼容问题的

**Comment by DocHuangys** [comment]
哦哦，谢谢解答。

**Comment by DocHuangys** [comment]
再请问一下您，那个视频播放缓存策略有详解吗？或者我能自定义这个缓存策略吗？

**Comment by CarGuo** [comment]
继承 ICacheManager 可以实现自己的缓存逻辑

**Comment by DocHuangys** [comment]
好的，谢谢

**Comment by pczhu** [comment]
我也出现了。用Appium测一个用户流程。进入页面播放。然后退出。反复测试900次大概有1%的次数出现无任何log的crash 。真的是一点log也没有。我新建了一个没有任何业务代码，只带播放器的空页面。测试同样这个流程。不调用播放。500次无异常。调用播放。第三十次就crash了。= = 。真是见了鬼了。
