### ISSUE TITLE
RTSP播放問題

### ISSUE THREAD

**Issue by ArroWen2904** [CarGuo/GSYVideoPlayer#3052]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

您好 在使用後有幾點問題想請教該如何解決
封裝檔案的類型為MP4
視訊解碼器為H265
音訊解碼器為AAC

問題一：使用ijkplayer播放rtsp live streaming，暫停過後聲音與影像不同步
問題二：exoPlayer是否不支援上述格式進行rtsp播放 再輸入網址後點選播放無反應
問題三：使用ijkplayer在播放rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov的測試網址時，對進度條做拖拉的動作後，一直停留在loading，無法順利播放
問題四：可否於暫停後，直接做teardown將資源釋放，按下play重新連線？

## 问题机型/系统：

Samsung A715F/DS

## GSY依赖版本

    implementation 'com.shuyu:GSYVideoPlayer:7.1.8'
    implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.1'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.1'

## Demo中的复现步骤

使用下列程式碼播放

问题代码：(如果有)
```
    fun startRTSPByGSY(videoUrl: String) {
        CacheFactory.setCacheManager(ProxyCacheManager::class.java)
        video.setUp(videoUrl, true, "")
        video.titleTextView.visibility = View.GONE
        video.startPlayLogic()
    }

```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by ArroWen2904** [comment]
您好 想請問大老 問題可以重現嗎？
以及是否有相關的解法？

**Comment by ArroWen2904** [comment]
@CarGuo 請問大老這個有辦法解決嗎

**Comment by CarGuo** [comment]
1、试试最新版本 8.0.0，暂停后推荐重新播放连接，不要onresume
2、exo不支持 rtsp
3、不要用 seek 的动作行为

**Comment by ArroWen2904** [comment]
請問重新播放连接的部分我可以overwrite播放鍵的method嗎

**Comment by CarGuo** [comment]
startPlayLogic  你可以按照你的喜欢    Override


主要是重新连接部分，你可以需要判断下状态去重新播放
