### ISSUE TITLE
多指触摸空指针异常

### ISSUE THREAD

**Issue by sunxu3074** [CarGuo/GSYVideoPlayer#3056]
## 问题描述：

![image](https://user-images.githubusercontent.com/9284055/100713380-2d96f400-33ef-11eb-9717-f3e21555a12d.png)

## 问题机型/系统：

例如 真机 6.0到11都有出现这个问题。

## GSY依赖版本
def gsy_version_player_version = '7.1.4'
 // 点播播放器 GSYVideoPlayer
 implementation "com.shuyu:gsyVideoPlayer-java:$gsy_version_player_version"
 implementation "com.shuyu:gsyVideoPlayer-armv5:$gsy_version_player_version"
 implementation "com.shuyu:gsyVideoPlayer-armv7a:$gsy_version_player_version"

## Demo中的复现步骤

demo无复现，本地也未能复现，但在测试机上用多指操作时，会出现crash，生命周期执行到onResume()。

## 问题代码：(如果有)
> 无

## 问题log（如果有）

```

见问题描述

```

**Comment by sunxu3074** [comment]
另外之前显示的亮度和声音的弹窗也不显示了，两边竖滑没反应

**Comment by CarGuo** [comment]
大佬，这样的话我也没办法去浮现和跟踪问题哟·····

**Comment by sunxu3074** [comment]
> 大佬，这样的话我也没办法去浮现和跟踪问题哟·····

代码没变，主要是这个版本出现这个问题。定位在亮度和音量onTouch这个操作里。怀疑是不是gsyvideoplayer内置的依赖引用到了+这样的不稳定lib

**Comment by CarGuo** [comment]
onTouch 相关的逻辑其实没有第三方依赖其实

**Comment by sunxu3074** [comment]
> onTouch 相关的逻辑其实没有第三方依赖其实

我怕大哥引用androidx.appcompat:appcompat+这样的依赖哈哈 回滚到之前是没问题了 我慢慢回滚 然后定位一下问题 感谢大佬回复

**Comment by CarGuo** [comment]
哦哦，明白了，但是感觉应该可以这个没关系，期待你的回复

**Comment by sunxu3074** [comment]
```java
// BaseActivity
public void setContentView(@LayoutRes int layoutResID, boolean bindView) {
    initBaseView();
    rootView.addView(LayoutInflater.from(this).inflate(layoutResID, null)); // 之前是引用的applicationContext 改用activity解决了
}
```
谢谢大佬~~

**Comment by sunxu3074** [comment]
```java
// BaseActivity
public void setContentView(@LayoutRes int layoutResID, boolean bindView) {
    initBaseView();
    rootView.addView(LayoutInflater.from(this).inflate(layoutResID, null)); // 之前是引用的applicationContext 改用activity解决了
}
```

谢谢大佬~~
