### ISSUE TITLE
硬解有些视频黑屏几秒，就是声音播了几秒视频才从黑屏渲染出来，但如果手动拖进度会seekComplete 马上就会出画面，因此我想这应该重新绘制了，那有没有api可以自动手动调强制重新绘制来避免前几秒的黑屏呢

### ISSUE THREAD

**Issue by kyriej** [CarGuo/GSYVideoPlayer#3057]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请在最新的demo中测试复现，最好能提供测试url
