### ISSUE TITLE
播放器嵌套到AppBarLayout中使用

### ISSUE THREAD

**Issue by loveRose** [CarGuo/GSYVideoPlayer#306]
播放器嵌套到AppBarLayout中使用会出现getContext强转成Activity错误，并且全屏下使用的mContext也不能强转。
**解决办法：**在公用方法CommonUtil中定义如下工具：

> 
    public static Activity getActivityContext(Context cont) {
        if (cont == null)
            return null;
        else if (cont instanceof Activity)
            return (Activity) cont;
        else if (cont instanceof ContextWrapper)
            return scanForActivity(((ContextWrapper) cont).getBaseContext());

        return null;
    }

> 
并在播放器中使用getContext的地方添加判断

> if (getActivityContext(getContext()) != null) {
         //用getActivityConte(getContext()) 代替原来直接使用的getContext();
    }

> 
以上解决了竖直屏问题，接下来代码解决横屏问题，横屏的时候使用的是成员变量mContext,所以在GSYVideoPlayer类的构造方法里面加上如下：
> if (getActivityContext(context) != null) {
            init(getActivityContext(context));
        } else {
            init(context);
        }

> 
这样一来就解决了问题，可以放心使用了。但是会发现这个播放器不能自动隐藏控制键了，因为在自定义播放器里面有个DismissControlViewTimerTask任务类（该类作为成员变量可找到），他里面的run方法里有个判断条件

> context instanceof Activity

> 
我们需要把它去掉，并直接用上面的判断进行操作。
至此已经可以正常使用，该修改不影响原有功能

**Comment by CarGuo** [comment]
多谢建议😁，下个版本测试完善后补上！
