### ISSUE TITLE
“自动RECYCLER列表” 里面，recyclerView滑动会卡顿

### ISSUE THREAD

**Issue by RomanticHua** [CarGuo/GSYVideoPlayer#3060]
问题描述：
Demo中“**自动RECYCLER列表**”这个案例，recyclerView滑动的时候，有时候会卡顿。

问题机型/系统：
真机 小米10 Android 10 

 GSY依赖版本：
implementation 'com.shuyu:GSYVideoPlayer:8.0.0'

Demo中的复现步骤：
多滑动几次，很容易复现的。

**Comment by CarGuo** [comment]
不是很理解，有时候会卡顿不是正常情况么，你应该找到卡顿的点看看怎么优化嘛， demo 只是一种展示思路
