### ISSUE TITLE
自动滑动 滑动到上一条播放的item 会卡顿一下  跳转切换 onResume 恢复播放也会卡顿  

### ISSUE THREAD

**Issue by liuxixiang** [CarGuo/GSYVideoPlayer#3061]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
![image](https://user-images.githubusercontent.com/5679928/100993703-b39e7080-3590-11eb-81c0-caae4af33462.png)
https://s17.aconvert.com/convert/p3r68-cdx67/cjkwx-jgbsr.gif

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
感觉是很正常的播放前的 prepare

**Comment by liuxixiang** [comment]
https://vkceyugu.cdn.bspapp.com/VKCEYUGU-imgbed/e518a38f-3fb0-4451-8029-79b550027df8.mp4
这是视屏 会卡顿 不是很流畅

**Comment by liuxixiang** [comment]
怎么做到上滑到上一个视频 不怎么卡顿恢复到原来播放的位置

**Comment by liuxixiang** [comment]
> 感觉是很正常的播放前的 prepare

https://vkceyugu.cdn.bspapp.com/VKCEYUGU-imgbed/e518a38f-3fb0-4451-8029-79b550027df8.mp4
这是视屏 会卡顿 不是很流畅
怎么做到上滑到上一个视频 不怎么卡顿恢复到原来播放的位置

**Comment by CarGuo** [comment]
参考  demo 的 GSYExo2MediaPlayer ，使用 ConcatenatingMediaSource 来做列表播放，然后使用

CacheFactory.setCacheManager(ExoPlayerCacheManager.class); 做缓存
