### ISSUE TITLE
大佬，支持vtt字幕吗？

### ISSUE THREAD

**Issue by mhdtlmt** [CarGuo/GSYVideoPlayer#3062]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
你看demo 的字幕支持演示

**Comment by mhdtlmt** [comment]
> 你看demo 的字幕支持演示
![image](https://user-images.githubusercontent.com/59436499/101123445-db90e100-362f-11eb-89e9-db46b456dcb6.png)
找到了这个地方，不知道该如何扩展
