### ISSUE TITLE
进度条拖动问题

### ISSUE THREAD

**Issue by wangpingtaohn** [CarGuo/GSYVideoPlayer#3064]
## 问题描述：

1.拖动进度条后，显示的时间与播放的时候不一致，比如，把进度条拖到到00:54秒时，开始播放的时候，显示的是00:52秒，总会自动往回拽了2、3秒

## 问题机型/系统：

所有机型。

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8'`

## Demo中的复现步骤

Demo中的【简单播放】里的【简单直接播放】
问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
看问题集锦和issue 创建时那个链接说明，你就知道了，关键帧问题
