### ISSUE TITLE
RTSP 时移问题

### ISSUE THREAD

**Issue by maoqitian** [CarGuo/GSYVideoPlayer#3066]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

想请教一下是否有支持 RTSP 时移的办法，RTSP 时移支持是发生在 PLAY 动作添加请求参数，尝试设置 setMapHeadData(map) 不行
关键字段：
Range:播放时间支持两种格式，Range: npt=0.0-end或者Range:clock=20100318T021919.35Z-20100318T031919.80Z
例如：Range: clock=20201208T060000.00Z- 设置跳转时移位置
[参考链接](https://blog.csdn.net/myvest/article/details/80641799)

## 问题机型/系统：

烽火 MR820 电视盒子 Android 4.4

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
setMapHeadData 需要重新 setup 和 startplayLogic

**Comment by maoqitian** [comment]
val map = HashMap<String,String>()
map["Range"] = "20201208T160000Z-"
mVideoView.setUp(source3, false,null,map, "") 
mVideoView.startPlayLogic()
这样设置也不行

**Comment by CarGuo** [comment]
你看log和抓包，header 有没有发出发

**Comment by maoqitian** [comment]
我再尝试看看，感谢
