### ISSUE TITLE
暂停之后拖动seekbar，进度偶尔会回跳的问题

### ISSUE THREAD

**Issue by chenxiaodfasd** [CarGuo/GSYVideoPlayer#3068]
如题，拖动下面的进度条，再放开偶尔就会出现进度回跳一点点的情况
这种情况在暂停后再播放也会出现这个问题
因为我是做电视盒子开发，在电视上用遥控板按键进行小幅度进度跳转，在播放和暂停状态，这个现象变得更加明显
希望开发者大神解决一下这个问题哈

**Comment by CarGuo** [comment]
看问题集锦和新建 issue 上的链接，关键帧问题，设置精准 seek 或者 exo 内核

**Comment by chenxiaodfasd** [comment]
> 看问题集锦和新建 issue 上的链接，关键帧问题，设置精准 seek 或者 exo 内核

你好，实际上我是把你的项目跑在手机上，然后测试发现手动进度条会出现这个问题

**Comment by honglei92** [comment]
怎么设置精准seek

**Comment by CarGuo** [comment]
@honglei92 看问题集锦
