### ISSUE TITLE
如何实现预加载呢

### ISSUE THREAD

**Issue by cjk035** [CarGuo/GSYVideoPlayer#3069]
我在播放一个视频的同时，希望能预加载另一个视频

**Comment by CarGuo** [comment]
demo 中的 DetailExoListPlayer 或者 DetailDownloadPlayer

DetailExoListPlayer 使用的是 exo 的 ConcatenatingMediaSource

DetailDownloadPlayer 使用的是 proxycache ， 你可以外部去下载缓存
