### ISSUE TITLE
使用播放器播放海康视频摄像头的rtsp数据源报错：NO ROUTE TO HOST

### ISSUE THREAD

**Issue by xuganwen** [CarGuo/GSYVideoPlayer#3070]
## 问题描述：

使用播放器播放海康视频摄像头的rtsp数据源报错：NO ROUTE TO HOST。
视频地址：rtsp://admin:zaqwsx123456@192.168.40.181/cam/realmonitor?channel=1&subtype=1
不知道是啥原因，是因为地址中有@字符或者其他原因吗，请大神教一下如何解决？

## 问题机型/系统：

例如 真机 华为荣耀9i Android9.0

## GSY依赖版本

    val Gysplayer1="com.shuyu:gsyVideoPlayer-java:8.0.0"
    val Gysplayer2="com.shuyu:GSYVideoPlayer-exo2:8.0.0"
    val Gysplayer3="com.shuyu:gsyVideoPlayer-ex_so:8.0.0"

## Demo中的复现步骤

StandardGSYVideoPlayer点击播放失败，查看日志如下。

问题代码：(如果有)
```
List<VideoOptionModel> list = new ArrayList<>();
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 200000);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
        list.add(videoOptionModel);
        //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
//        String source1 = getIntent().getStringExtra("url");
        String source1 = "rtsp://admin:zaqwsx123456@192.168.40.181/cam/realmonitor?channel=1&subtype=1";
        videoPlayer.setUp(source1, true, "");
```

## 问题log（如果有）

```
2020-12-10 17:06:10.444 13390-13937/com.haocang.mangomax D/IJKMEDIA: FFP_MSG_FLUSH:
2020-12-10 17:06:10.444 13390-13938/com.haocang.mangomax I/IJKMEDIA: SDL_RunThread: [13938] ff_vout
2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax I/IJKMEDIA: SDL_RunThread: [13939] ff_read
2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax W/IJKMEDIA: remove 'timeout' option for rtmp.
2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax V/IJKMEDIA: Probing rtsp score:100 size:0
2020-12-10 17:06:10.446 13390-13939/com.haocang.mangomax D/IJKMEDIA: No default whitelist set
2020-12-10 17:06:13.598 13390-13939/com.haocang.mangomax E/IJKMEDIA: Connection to tcp://192.168.40.181:554?timeout=0 failed: No route to host
2020-12-10 17:06:13.598 13390-13939/com.haocang.mangomax E/IJKMEDIA: rtsp://admin:zaqwsx123456@192.168.40.181/cam/realmonitor?channel=1&subtype=1: No route to host

```

**Comment by xuganwen** [comment]
用VLC的Windows版播放器输入如上地址可以播放，是啥原因  唉唉唉

**Comment by CarGuo** [comment]
你这个是本地地址吧？有可以对外测试的嘛？

**Comment by xuganwen** [comment]
> 你这个是本地地址吧？有可以对外测试的嘛？

我也找了好久没找到可以播放的外部链接，想验证下是框架原因还是其他原因 ，不知道楼下有其他有缘人能提供个不

**Comment by xuganwen** [comment]
> 你这个是本地地址吧？有可以对外测试的嘛？

找了个外链可以播放：rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
但是向上面的这中地址中带用户名和密码鉴权的播放不了，大神知道如何解决么或者有方案么？对流媒体和socket的数据交换不了解 @CarGuo

**Comment by chenxihoulang** [comment]
我用demo测试:rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
这个视频地址,无法播放,请问是啥原因呢?

**Comment by xuganwen** [comment]
> 我用demo测试:rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
> 这个视频地址,无法播放,请问是啥原因呢?

  implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'

//是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:8.0.0'

//更多ijk的编码支持
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:8.0.0'
用这种方式依赖试试

**Comment by lakinqianlijain** [comment]
> > 我用demo測試：rtsp：//wowzaec2demo.streamlock.net/vod/mp4：BigBuckBunny_115k.mov
> > 這個視頻地址，無法播放，請問是啥原因呢？
> 
> 實現'com.shuyu：gsyVideoPlayer-java：8.0.0'
> 
> //是否需要ExoPlayer模式
> 實現'com.shuyu：GSYVideoPlayer-exo2：8.0.0'
> 
> //更多ijk的編碼支持
> 實現'com.shuyu：gsyVideoPlayer-ex_so：8.0.0'
> 用這種方式依賴試試

请问最后你怎么解决这个问题的呢？我也遇到了这个问题

**Comment by lakinqianlijain** [comment]
> ## 問題描述：
> 正在使用播放器播放海康視頻攝像頭的rtsp數據源報錯：
> 視頻地址：rtsp：// admin：zaqwsx123456@192.168.40.181/cam/realmonitor？channel = 1＆subtype = 1
> 不知道是啥原因，是因為地址中有@字符或者其他原因嗎，請大神教一下如何解決？
> 
> ## 問題樣本/系統：
> 例如真機華為榮耀9i Android9.0
> 
> ## GSY依賴版本
> ```
> val Gysplayer1="com.shuyu:gsyVideoPlayer-java:8.0.0"
> val Gysplayer2="com.shuyu:GSYVideoPlayer-exo2:8.0.0"
> val Gysplayer3="com.shuyu:gsyVideoPlayer-ex_so:8.0.0"
> ```
> 
> ## 演示中的複現步驟
> StandardGSYVideoPlayer單擊播放失敗，查看日誌如下。
> 
> 問題代碼：(如果有）
> 
> ```
> List<VideoOptionModel> list = new ArrayList<>();
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 200000);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
>         list.add(videoOptionModel);
>         //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
>         list.add(videoOptionModel);
>         GSYVideoManager.instance().setOptionModelList(list);
> //        String source1 = getIntent().getStringExtra("url");
>         String source1 = "rtsp://admin:zaqwsx123456@192.168.40.181/cam/realmonitor?channel=1&subtype=1";
>         videoPlayer.setUp(source1, true, "");
> ```
> 
> ## 問題log（如果有）
> ```
> 2020-12-10 17:06:10.444 13390-13937/com.haocang.mangomax D/IJKMEDIA: FFP_MSG_FLUSH:
> 2020-12-10 17:06:10.444 13390-13938/com.haocang.mangomax I/IJKMEDIA: SDL_RunThread: [13938] ff_vout
> 2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax I/IJKMEDIA: SDL_RunThread: [13939] ff_read
> 2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax W/IJKMEDIA: remove 'timeout' option for rtmp.
> 2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax V/IJKMEDIA: Probing rtsp score:100 size:0
> 2020-12-10 17:06:10.446 13390-13939/com.haocang.mangomax D/IJKMEDIA: No default whitelist set
> 2020-12-10 17:06:13.598 13390-13939/com.haocang.mangomax E/IJKMEDIA: Connection to tcp://192.168.40.181:554?timeout=0 failed: No route to host
> 2020-12-10 17:06:13.598 13390-13939/com.haocang.mangomax E/IJKMEDIA: rtsp://admin:zaqwsx123456@192.168.40.181/cam/realmonitor?channel=1&subtype=1: No route to host
> ```

你好，最终问题是怎么解决的呢？遇到了同样的问题

**Comment by lakinqianlijain** [comment]
> ## 問題描述：
> 正在使用播放器播放海康視頻攝像頭的rtsp數據源報錯：
> 視頻地址：rtsp：// admin：zaqwsx123456@192.168.40.181/cam/realmonitor？channel = 1＆subtype = 1
> 不知道是啥原因，是因為地址中有@字符或者其他原因嗎，請大神教一下如何解決？
> 
> ## 問題樣本/系統：
> 例如真機華為榮耀9i Android9.0
> 
> ## GSY依賴版本
> ```
> val Gysplayer1="com.shuyu:gsyVideoPlayer-java:8.0.0"
> val Gysplayer2="com.shuyu:GSYVideoPlayer-exo2:8.0.0"
> val Gysplayer3="com.shuyu:gsyVideoPlayer-ex_so:8.0.0"
> ```
> 
> ## 演示中的複現步驟
> StandardGSYVideoPlayer單擊播放失敗，查看日誌如下。
> 
> 問題代碼：(如果有）
> 
> ```
> List<VideoOptionModel> list = new ArrayList<>();
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 200000);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
>         list.add(videoOptionModel);
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
>         list.add(videoOptionModel);
>         //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
>         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
>         list.add(videoOptionModel);
>         GSYVideoManager.instance().setOptionModelList(list);
> //        String source1 = getIntent().getStringExtra("url");
>         String source1 = "rtsp://admin:zaqwsx123456@192.168.40.181/cam/realmonitor?channel=1&subtype=1";
>         videoPlayer.setUp(source1, true, "");
> ```
> 
> ## 問題log（如果有）
> ```
> 2020-12-10 17:06:10.444 13390-13937/com.haocang.mangomax D/IJKMEDIA: FFP_MSG_FLUSH:
> 2020-12-10 17:06:10.444 13390-13938/com.haocang.mangomax I/IJKMEDIA: SDL_RunThread: [13938] ff_vout
> 2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax I/IJKMEDIA: SDL_RunThread: [13939] ff_read
> 2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax W/IJKMEDIA: remove 'timeout' option for rtmp.
> 2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax V/IJKMEDIA: Probing rtsp score:100 size:0
> 2020-12-10 17:06:10.446 13390-13939/com.haocang.mangomax D/IJKMEDIA: No default whitelist set
> 2020-12-10 17:06:13.598 13390-13939/com.haocang.mangomax E/IJKMEDIA: Connection to tcp://192.168.40.181:554?timeout=0 failed: No route to host
> 2020-12-10 17:06:13.598 13390-13939/com.haocang.mangomax E/IJKMEDIA: rtsp://admin:zaqwsx123456@192.168.40.181/cam/realmonitor?channel=1&subtype=1: No route to host
> ```

你好，最终问题是怎么解决的呢？遇到了同样的问题

**Comment by xuganwen** [comment]
> > ## 問題描述：
> > 正在使用播放器播放海康視頻攝像頭的rtsp數據源報錯：
> > 視頻地址：rtsp：// admin：zaqwsx123456@192.168.40.181/cam/realmonitor？channel = 1＆subtype = 1
> > 不知道是啥原因，是因為地址中有@字符或者其他原因嗎，請大神教一下如何解決？
> > ## 問題樣本/系統：
> > 例如真機華為榮耀9i Android9.0
> > ## GSY依賴版本
> > ```
> > val Gysplayer1="com.shuyu:gsyVideoPlayer-java:8.0.0"
> > val Gysplayer2="com.shuyu:GSYVideoPlayer-exo2:8.0.0"
> > val Gysplayer3="com.shuyu:gsyVideoPlayer-ex_so:8.0.0"
> > ```
> > 
> > 
> > ## 演示中的複現步驟
> > StandardGSYVideoPlayer單擊播放失敗，查看日誌如下。
> > 問題代碼：(如果有）
> > ```
> > List<VideoOptionModel> list = new ArrayList<>();
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
> >         list.add(videoOptionModel);
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
> >         list.add(videoOptionModel);
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
> >         list.add(videoOptionModel);
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 200000);
> >         list.add(videoOptionModel);
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
> >         list.add(videoOptionModel);
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
> >         list.add(videoOptionModel);
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
> >         list.add(videoOptionModel);
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
> >         list.add(videoOptionModel);
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
> >         list.add(videoOptionModel);
> >         //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
> >         videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
> >         list.add(videoOptionModel);
> >         GSYVideoManager.instance().setOptionModelList(list);
> > //        String source1 = getIntent().getStringExtra("url");
> >         String source1 = "rtsp://admin:zaqwsx123456@192.168.40.181/cam/realmonitor?channel=1&subtype=1";
> >         videoPlayer.setUp(source1, true, "");
> > ```
> > 
> > 
> > ## 問題log（如果有）
> > ```
> > 2020-12-10 17:06:10.444 13390-13937/com.haocang.mangomax D/IJKMEDIA: FFP_MSG_FLUSH:
> > 2020-12-10 17:06:10.444 13390-13938/com.haocang.mangomax I/IJKMEDIA: SDL_RunThread: [13938] ff_vout
> > 2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax I/IJKMEDIA: SDL_RunThread: [13939] ff_read
> > 2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax W/IJKMEDIA: remove 'timeout' option for rtmp.
> > 2020-12-10 17:06:10.445 13390-13939/com.haocang.mangomax V/IJKMEDIA: Probing rtsp score:100 size:0
> > 2020-12-10 17:06:10.446 13390-13939/com.haocang.mangomax D/IJKMEDIA: No default whitelist set
> > 2020-12-10 17:06:13.598 13390-13939/com.haocang.mangomax E/IJKMEDIA: Connection to tcp://192.168.40.181:554?timeout=0 failed: No route to host
> > 2020-12-10 17:06:13.598 13390-13939/com.haocang.mangomax E/IJKMEDIA: rtsp://admin:zaqwsx123456@192.168.40.181/cam/realmonitor?channel=1&subtype=1: No route to host
> > ```
> 
> 你好，最终问题是怎么解决的呢？遇到了同样的问题

我这个是vpn网络问题，网管搞了一下映射就好了
