### ISSUE TITLE
点击全屏后，状态栏和action bar 仍然显示

### ISSUE THREAD

**Issue by ztisdashen** [CarGuo/GSYVideoPlayer#3071]
## 问题描述：

点击全屏后，状态栏和action bar 仍然显示

## GSY依赖版本
仅引入
implementation 'com.shuyu:GSYVideoPlayer:8.0.0'

## Demo中的复现步骤
代码与示例代码 SimpleDetailActivityMode2 和对应的布局文件一摸一样

[问题图片地址](https://sm.ms/image/u3jeHEJqPmI7hdM)

**Comment by CarGuo** [comment]
Demo正常，请参考 demo，配置AndroidManifet文件
