### ISSUE TITLE
好不容易把字幕加进去了，发现m3u8视频的字幕死活不显示，mp4什么的都ok了，请问下这是什么原因呢

### ISSUE THREAD

**Issue by mhdtlmt** [CarGuo/GSYVideoPlayer#3072]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
你说exo那个加字幕的source？？

**Comment by mhdtlmt** [comment]
> 你说exo那个加字幕的source？？

是的

**Comment by CarGuo** [comment]
这个你看一下 Debug  SingleSampleMediaPeriod 是不是正常工作就知道了

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/3106
