### ISSUE TITLE
提交Google Play审核后检测因含有广告SDK被拒绝

### ISSUE THREAD

**Issue by StoneCanFly** [CarGuo/GSYVideoPlayer#3074]
## 问题描述： 

提交Google Play审核后提示：违反家庭政策要求

我们检测到您的应用程序包含未经认证的广告SDK或未获批准用于面向儿童的服务的SDK。应用程序中使用的所有SDK都必须适合在面向儿童的服务中使用。此外，仅面向儿童的应用程序不得包含未获批准用于儿童导向服务的任何SDK，包括广告SDK。

我们这个版本就新加了这一个新库，然后我看源代码里面广告相关其实也就是GSYADVideoPlayer和GSYSampleADVideoPlayer，本质也是播放视频，然后也没看到什么广告SDK的引用，来这儿主要是向作者确认，顺便问下其他人有没有遇到过这样的问题？是怎么解决的

## GSY依赖版本
    implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:8.0.0'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:8.0.0'
    implementation 'com.shuyu:gsyVideoPlayer-arm64:8.0.0'

**Comment by CarGuo** [comment]
没有呢，外部依赖就是修改后的 ijkplayer ，exoplayer ，transitionseverywhere ，修改后的 androidvideocache 这些，如果硬要说有AD字眼的，那就是你发的 GSYADVideoPlayer和GSYSampleADVideoPlayer 这两个类名字了

**Comment by StoneCanFly** [comment]
不知道Google那边怎么分析的apk，我已经提交申诉了，看他们怎么说吧
