### ISSUE TITLE
请问Exo模式如何获取缓存进度?

### ISSUE THREAD

**Issue by foreverZou** [CarGuo/GSYVideoPlayer#3075]
## 问题描述：

请问Exo模式下如何获取缓存进度?

CacheFactory.setCacheManager(ExoPlayerCacheManager::class.java)
PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)

我试了
ExoPlayerCacheManager.setCacheAvailableListener()
IjkExo2MediaPlayer.setOnBufferingUpdateListener()
onBufferingUpdate()
都没有拿到回调,用ProxyCacheManager缓存也是.

## GSY依赖版本

 `implementation 'com.shuyu:GSYVideoPlayer:7.1.8'`
 `implementation 'com.google.android.exoplayer:exoplayer:2.12.1'`

**Comment by CarGuo** [comment]
Exo 不支持获取缓存进度，exo 缓存在本地的是很多的碎片文件部分

**Comment by foreverZou** [comment]
哦哦,我改用ProxyCacheManager吧.
