### ISSUE TITLE
how do you achieve lowest latency possible for RTMP streams?

### ISSUE THREAD

**Issue by andryan** [CarGuo/GSYVideoPlayer#3079]
hello,

how do you achieve lowest latency possible for RTMP streams?
can we achieve this test on the demo apk?

cheers,
Andryan

**Comment by CarGuo** [comment]
lowest latency support is more server-side logic

**Comment by andryan** [comment]
we have low latency (300ms) RTMP player from daniulive, but they seem to have closed down. we can confirm that server is already able to achieve this using daniu or ffplay, are there some buffer parameters I can use to achieve this on your player?

**Comment by CarGuo** [comment]
sorry , I have not idea
