### ISSUE TITLE
全屏后顶部时间栏不消失

### ISSUE THREAD

**Issue by nohavename** [CarGuo/GSYVideoPlayer#308]
mVideoPlay.startWindowFullscreen(this, true, true)，设置了隐藏statusbar，但是全屏之后顶部时间栏没有消失，返回键等顶部一部分布局显示在时间栏下面，有时候返回小屏，再全屏，顶部时间栏就不显示了，

**Comment by nohavename** [comment]
用的版本是com.shuyu:GSYVideoPlayer:1.6.8

**Comment by CarGuo** [comment]
demo上吗？有截图不？什么手机？

**Comment by nohavename** [comment]
demo上没有，我是按照DetailPlayer来设置的，不知道是不是哪里设置有问题，还望大神指教

**Comment by CarGuo** [comment]
你是继承了类似demo的AppcomatpActivity没？配置了AndroidManifest的Activity的configure没？

**Comment by nohavename** [comment]
![_20170706172513](https://user-images.githubusercontent.com/25943316/27939316-8be5740a-62f6-11e7-8633-95b30cf50bec.jpg)

**Comment by nohavename** [comment]
![_20170707093124](https://user-images.githubusercontent.com/25943316/27939420-1d32f32e-62f7-11e7-922c-e0a79b229997.jpg)

**Comment by nohavename** [comment]
按照demo来配置的，机型是红米

**Comment by nohavename** [comment]
有时候大小屏来回切换几次就可以了
