### ISSUE TITLE
如何获取网络视频地址对应的视频的音视频信息，比如采样率帧率等

### ISSUE THREAD

**Issue by chengwentao** [CarGuo/GSYVideoPlayer#3080]

**Comment by CarGuo** [comment]
IjkMediaPlayer 支持


                    float fpsOutput = mp.getVideoOutputFramesPerSecond();
                    float fpsDecode = mp.getVideoDecodeFramesPerSecond();
                    setRowValue(R.string.fps, String.format(Locale.US, "%.2f / %.2f", fpsDecode, fpsOutput));

                    long videoCachedDuration = mp.getVideoCachedDuration();
                    long audioCachedDuration = mp.getAudioCachedDuration();
                    long videoCachedBytes    = mp.getVideoCachedBytes();
                    long audioCachedBytes    = mp.getAudioCachedBytes();
                    long tcpSpeed            = mp.getTcpSpeed();
                    long bitRate             = mp.getBitRate();
                    long seekLoadDuration    = mp.getSeekLoadDuration();

**Comment by loyilin** [comment]
@CarGuo mp.getBitRate()一直是0怎么办
