### ISSUE TITLE
app不杀死时正常，退出app后重新进入 ，缓存重新下载

### ISSUE THREAD

**Issue by sunwinnie** [CarGuo/GSYVideoPlayer#3083]
## 问题描述：
缓存问题。播放视频时同时下载缓存，app未杀死情况下再次播放加载本地视频进行播放。而退出app再进入 播放就不使用本地的缓存而是直接再次通过网络下载，产生新的缓存文件。请帮忙分析下，我用demo 中的 视频地址 比如：http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4
不会出现这个问题。所以可能出现在视频编码或者视频链接请求头部分与加载缓存播放的逻辑不兼容。视频连接因为是本地服务器 放不了 见谅。麻烦分析下问题所在，或者指出加载缓存播放的代码处谢谢

![截图20201222171554](https://user-images.githubusercontent.com/29655735/102872602-e72b3700-447a-11eb-851a-e92662ac2926.png)

## 问题机型/系统：

所有机型

## GSY依赖版本

例如 `implementation 'com.shuyu:GSYVideoPlayer:7.1.8'`

**Comment by CarGuo** [comment]
不是很理解，默认的 proxycache 么？你可以看看缓存文件是不是存在，断点下 HttpProxyCacheServer 的 getProxyUrl

**Comment by sunwinnie** [comment]
谢谢 我跟进去看了之后发现 生成缓存名的 FileNameGenerator  不适合我的 文件路径，所以会每次生成不同的名称 ，请问怎么自定义FileNameGenerator

**Comment by CarGuo** [comment]
ProxyCacheManager 有静态方法 setFileNameGenerator
