### ISSUE TITLE
More than one file was found with OS independent path 'lib/armeabi-v7a/libijkplayer.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

### ISSUE THREAD

**Issue by timizhuoym** [CarGuo/GSYVideoPlayer#3084]
More than one file was found with OS independent path 'lib/armeabi-v7a/libijkplayer.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

请问这是什么原因导致的呢，看文档好像不需要下载.so包吧，也没找到

**Comment by CarGuo** [comment]
你的项目是不是依赖了 ijk ，和gsy 的ijk冲突了

**Comment by timizhuoym** [comment]
谢谢，解决了
