### ISSUE TITLE
Log日志开关

### ISSUE THREAD

**Issue by tangjian211085** [CarGuo/GSYVideoPlayer#3087]
能否加个Log日志开关，只在debug模式下才打印日志，且可控制是否需要打印日志

**Comment by CarGuo** [comment]
IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT); 
和 
Debuger.disable()

**Comment by tangjian211085** [comment]
谢谢

**Comment by tangjian211085** [comment]
刚刚自己也看到了，应该自己先多看看的

**Comment by workgithubly** [comment]
> Debuger.disable()

IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
和
Debuger.disable() 这两都设置了 还是疯狂打印 D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0

**Comment by Piscen** [comment]
jkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
和
Debuger.disable() 这两都设置了 还是疯狂打印 D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
