### ISSUE TITLE
自定义播放元件

### ISSUE THREAD

**Issue by ArroWen2904** [CarGuo/GSYVideoPlayer#3089]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

1. 若想在按下mStartButton的时候，先中断当前连线，再重新连线，那是否需要overWrite GSYVideoControlView内的clickStartButton method?
2. 播放元件的布局该如何更改，有无simple可作参考？
3. 预设的player有滑动以调整声音大小及亮度，请问该如何关闭这项功能？

## 问题机型/系统：

samsung A71

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:8.0.0'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:8.0.0'

## Demo中的复现步骤
无

问题代码：(如果有)
无

## 问题log（如果有）
无

**Comment by CarGuo** [comment]
直接继承后重载 getLayoutId ， showVolumeDialog 、updateStartImage 等方法就行了，比如 NormalGSYVideoPlayer \LandLayoutVideo 等
