### ISSUE TITLE
getCurrentPositionWhenPlaying这个函数在调整进度时会出现是0的情况

### ISSUE THREAD

**Issue by candrwow** [CarGuo/GSYVideoPlayer#309]
假设一个视频1小时，缓存到了10分钟，正在播放第3分钟，这时候移动进度到50分钟，会出现getCurrentPositionWhenPlaying=0的情况，暂时在这个情况下有这样的问题

**Comment by CarGuo** [comment]
你为seek的过程中，ijk在定位帧位置的时候，有点类似重新请求，这时候返回0代表着它还没过去到时长
