### ISSUE TITLE
全屏（竖屏的时候），目前发现华为手机（其他手机没有留心），底部进度条等会被遮挡

### ISSUE THREAD

**Issue by gslovemy** [CarGuo/GSYVideoPlayer#3090]
设置这个全屏主题属性 android:windowTranslucentNavigation为true的时候，部分手机发现底部进度条会别遮挡，目前手里的华为手机有这个问题mate 30,而谷歌亲儿子原生机（pixel）上没有这个问题.

**Comment by CarGuo** [comment]
不是很理解什么情况，有截图么》我这边在p30pro 上看demo 好像没什么问题

**Comment by gslovemy** [comment]
pixel上没有问题的，返回按钮，下面的进度条是正常展示的
![image](https://user-images.githubusercontent.com/13553809/103194758-8d63ba80-491b-11eb-995a-e14729618180.png)
我找了另外一个华为荣耀的手机（30s）,进度条在下面。
![image](https://user-images.githubusercontent.com/13553809/103194919-0d8a2000-491c-11eb-8325-c90c36ef97aa.png)

**Comment by CarGuo** [comment]
![WechatIMG609](https://user-images.githubusercontent.com/10770362/103200251-d15cbc80-4927-11eb-8ae2-1e1b9b012041.png)


如图所示，没有发现 30s 上有问题，也配置了 android:windowTranslucentNavigation

**Comment by gslovemy** [comment]
你可以下载一个xinhua news App，华为商店里面就有，版本2.2.0，在live tab下点开视频，全屏就可以复现

**Comment by CarGuo** [comment]
………这样的复现对我没意义啊😂

**Comment by gslovemy** [comment]
好吧，百思不得期解，那个locaiton_y不为0
