### ISSUE TITLE
关于日志

### ISSUE THREAD

**Issue by tangjian211085** [CarGuo/GSYVideoPlayer#3091]
![image](https://user-images.githubusercontent.com/24999527/103203643-59df5b00-4930-11eb-96f5-38e27cb3a2c3.png)

设置了  Debuger.disable();  //不允许打印日志， 但是上图的log依然还是打印出来了。。。是so里面打印的吗，我全局搜索，没搜索到相关的内容。另外，请问这个日志打印的字符串是拼接的吗？如果是拼接的，能不能做成类似这样呢？
if(canPrintLog){
    String log = "abc" + "edf";
    printlLog(.........);
}
避免在正式包情况下，播放视频时，如果字符串内容不同的话，不停的创建对象。
期待.........

**Comment by CarGuo** [comment]
`IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);`

**Comment by tangjian211085** [comment]
非常感谢，我真是一个菜鸟

**Comment by pcyfox** [comment]
IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT); 没什么卵用
