### ISSUE TITLE
请问滑动调节亮度的比例能否单独调整呢？

### ISSUE THREAD

**Issue by hjthjthjt** [CarGuo/GSYVideoPlayer#3094]
滑动快进比例可以用 setSeekRatio()，而滑动调节亮度和音量的似乎没有对应的方法（不知道是跟滑动快进共享还是……）

我个人体验觉得调节音量的调节比例还挺适合，但是调节亮度的时候不太顺手（主要是不能一下子把亮度拉到最高或者最低，手感跟国内视频平台的调节亮度很不一样，要多滑好几次才能达到目标亮度，每一次增加的亮度比例太少）

所以想请问一下是否有对应的方法呢？

**Comment by CarGuo** [comment]
继承后 override  touchSurfaceMove 方法， cv 源码，自己改改逻辑～～
