### ISSUE TITLE
EXO播放器可以处理前两秒丢帧黑屏问题吗？ijk可以直接跳过。exo会黑屏两秒，有声音没画面

### ISSUE THREAD

**Issue by xuzh2017** [CarGuo/GSYVideoPlayer#3095]
EXO播放器可以处理前两秒丢帧黑屏问题吗？ijk可以直接跳过。exo会黑屏两秒，有声音没画面

**Comment by xuzh2017** [comment]
demo上面也是同样的现象

**Comment by CarGuo** [comment]
亲，很遗憾的告诉您，exo 的 mediaCodec 不支持定制 ，在 dataSoucre 层面我觉得不大好做这一个，所以非常遗憾告诉您，不行～
