### ISSUE TITLE
大佬，ijk播放器播放m3u8直播流一会儿会画面卡住，没声音也没有任何log或者error打印。exo不会

### ISSUE THREAD

**Issue by xuzh2017** [CarGuo/GSYVideoPlayer#3096]
大佬，ijk播放器播放m3u8直播流一会儿会画面卡住，没声音也没有任何log或者error打印。exo不会，求救！！

**Comment by xuzh2017** [comment]
卡几分钟十几分钟又会继续播放，过一会儿又卡住

**Comment by CarGuo** [comment]
不大清楚问题，有测试 url 么，我这边试了正常，ijk 不行你就用 exo 内核呗，反正效果差不多。

**Comment by xuzh2017** [comment]
EXO会有丢帧黑屏的问题，所以没法换，这个问题[#3095](url)

**Comment by xuzh2017** [comment]
EXO会有丢帧黑屏的问题，所以没法换，这个问题[#3095](https://github.com/CarGuo/GSYVideoPlayer/issues/3095)

**Comment by CarGuo** [comment]
这就很尴尬了，我这边没复线问题

**Comment by xuzh2017** [comment]
应该就是这个问题[#3806](https://github.com/bilibili/ijkplayer/issues/3806)

**Comment by xwlcn** [comment]
同样有类似问题，貌似是ts链接网络卡了，然后就不能接着播放了，难道ijk没有重试机制？手动点击快进到某个时间点照样无法唤起继续播放，必须重新打开播放器。

**Comment by CarGuo** [comment]
@xwlcn 切到 exo 吧，ijk 的你要改需要自己调整 ffplay 里的逻辑
