### ISSUE TITLE
udp组播问题

### ISSUE THREAD

**Issue by DeepHopeW** [CarGuo/GSYVideoPlayer#3098]
## 问题描述：
udp组播  同步 和 断网重连

在播放udp组播视频的时候，刚开始播放的时候与实际播放进度大概有一秒左右延迟；随着播放时间增长 或者 存在的偶然的网络波动，都会导致播放进度与实际播放进度慢慢拉开。
通过暂停按钮 暂停播放后，发现视频是有缓存的，继续播放后会连着暂停时的时间点继续播放。

所以想能有什么方法，不进行缓存，或者减小缓存的时间，实现不管暂停多久，再从新播放后，跟实际视频的播放进度相差保持在一定时间内。

通过StandardGSYVideoPlayer 打开udp组播url播放视频
cacheWithPlay 设置为了false，其他VideoOptionModel 也尝试了一些，关于buffer cache什么的都有修改，但是一直没有达到目的。
        List<VideoOptionModel> list = new ArrayList<>();
        VideoOptionModel videoOptionModel;
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);//播放前的探测Size，默认是1M, 改小一点会出画面更快
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);//播放前的最大探测时间
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);//每处理一个packet之后刷新io上下文
        list.add(videoOptionModel);

        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 1000);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48 );
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);//硬件解码
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "reconnect", 5);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max_cached_duration", 1);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "fflags", "nobuffer");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "max-buffer-size", 0);
        list.add(videoOptionModel);

另外。。。还有个问题，就是断网后的重连机制，是不是只能通过监听网络变化后，再startPlayLogic 解决。

跪谢大佬！！

## 问题机型/系统：

华为m8平板  小米6等若干个（和机型应该关系不大）   android8  和android10 

## GSY依赖版本

 implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'
 implementation 'com.shuyu:gsyVideoPlayer-ex_so:8.0.0'

**Comment by CarGuo** [comment]
udp 的你这么说，我也不知道什么情况

断网后的重连机制，现在是只能通过监听网络变化后
