### ISSUE TITLE
关于视频显示比例的问题

### ISSUE THREAD

**Issue by ausboyue** [CarGuo/GSYVideoPlayer#3099]
## 问题描述：

视频显示比列这一块，作者列出几项比例或者自定义的比例，但是由于作者对MeasureHelper类作final处理，无法自定义完成对视频作宽固定，高裁剪（类似抖音，抖音是宽固定为屏幕宽，高度自适应裁剪）显示的处理，作者默认做的是高固定，宽裁剪的处理方式。希望作者能开放这样（宽固定，高裁剪）的显示类型功能。

## 问题机型/系统：

All

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## Demo中的复现步骤

All

问题代码：(如果有)

在MeasureHelper.java 188行左右代码，作者默认做的是高固定，宽裁剪的处理方式。

```java
        // for compatibility, we adjust size based on aspect ratio
        if (realWidth * height < width * mVideoHeight) {
            //Log.i("@@@", "image too wide, correcting");
            width = height * realWidth / mVideoHeight;
        } else if (realWidth * height > width * mVideoHeight) {
            //Log.i("@@@", "image too tall, correcting");
            height = width * mVideoHeight / realWidth;
        }
```

**Comment by CarGuo** [comment]
现在自定义的话，只能通过 SCREEN_TYPE_CUSTOM & setScreenScaleRatio 这两个

然后或者参考 CustomRenderVideoPlayer & CustomRenderView  直接自定义 render 层

**Comment by ausboyue** [comment]
OK
