### ISSUE TITLE
onPlayError()方法

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#31]
我需要在报错时，取到报错的当前播放时间点。能否可以取到？

**Comment by CarGuo** [comment]
接口有对应的获取当前时间的接口，请看wiki，如有实现上的细节问题，可以加入到qq群上面咨询哟。

**Comment by PiPiCaptain** [comment]
@CarGuo 
/**
 * 获取当前播放进度
 */
public int getCurrentPositionWhenPlaying()

这个方法在onPlayError()方法里，无法使用。因为你在回调onPlayError()前，已经将播放器释放掉了，所以我无法取到。

**Comment by CarGuo** [comment]
其实就是你重载播放器的话，重载onError，这样在super之前，你不就可以做你想要的保存了么？

**Comment by CarGuo** [comment]
如果可以，欢迎到群里讨论哟 😊
