### ISSUE TITLE
列表卡顿问题

### ISSUE THREAD

**Issue by kcufow** [CarGuo/GSYVideoPlayer#3100]
## 问题描述：
在列表中播放视频时，滑动列表至不可视视频自动关闭时，会有列表卡顿现象

## 问题机型/系统：

 真机 vivo iQOO  Android10.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'

## Demo中的复现步骤

Demo中的RECYCLER列表。

问题代码：

经过测试，是在GSYVideoManager.instance().listener()?.onCompletion()这句代码执行的时候会卡顿。我尝试在滑出的时候不调用release直接stop然后重置 GSYVideoManager.instance().playTag="" GSYVideoManager.instance().playPosition=-22，发现在列表中会有item的封面为黑色。这种问题是否有什么解法？

**Comment by CarGuo** [comment]
推测主要可能是 

                    releaseMediaPlayer();

这两个方法导致的，其中 releaseMediaPlayer 主要是释放 playerManager 和  cacheManager，推荐看看是 playerManager 还是 cacheManager， 个人觉得更多可能是 playerManager ，如果是  playerManager 的，可以看看比如 IjkPlayerManager or Exo2PlayerManager 里面，把对应的  mediaPlayer 处理到其他线程去释放（IjkExo2MediaPlayer 可能因为内部定义死了  Looper.getMainLooper() 没办法直接换现场，所以需要参考demo 直接把 IjkExo2MediaPlayer 也自定义了）

**Comment by kcufow** [comment]
好像并不是releaseMediaPlayer()导致的列表卡顿
`    recycler_view.addOnScrollListener(object :RecyclerView.OnScrollListener(){
            override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
                super.onScrolled(recyclerView, dx, dy)
                val playPosition = GSYVideoManager.instance().playPosition
                if (playPosition <0 || GSYVideoManager.instance().playTag!=SimpleRecyclerVideoAdapter.TAG) return
                val layoutManager = recyclerView.layoutManager
                if (layoutManager !is LinearLayoutManager) return

                val fvPosition = layoutManager.findFirstVisibleItemPosition()
                val lvPosition = layoutManager.findLastVisibleItemPosition()
                if (playPosition<fvPosition || playPosition>lvPosition){
                    if (GSYVideoManager.isFullState(activity)) return
                    GSYVideoManager.instance().stop()
                    GSYVideoManager.instance().listener()?.onCompletion()
                    GSYVideoManager.instance().playTag=""
                    GSYVideoManager.instance().playPosition=-22
                }
            }
        })`
我在滑出的时候并没有调用release，只是执行了GSYVideoManager.instance().listener()?.onCompletion()，也会有卡顿

**Comment by CarGuo** [comment]
`onCompletion()` 会调用 setStateAndUi(CURRENT_STATE_NORMAL) 从而触发 release

**Comment by kcufow** [comment]
感谢回复，感觉开线程做release操作还需要做同步处理。我看系统的videoView在完成时并没有做release操作会把release放在播放器打开时，我接下来会尝试修改一下release的逻辑看看能不能解决。再次感谢大佬！！！

**Comment by CarGuo** [comment]
除了这个，你还可以看看  setShowPauseCover(false); ，不过正常应该不影响，因为你没有进入 pasue 的话，应该不会生成暂停时的 bitmap 

另外就是停止播放时恢复封面图的时候了

除了这个我觉得好像就是只有 relase 了，其他真的没想法了

**Comment by kcufow** [comment]
修改了release的逻辑，列表已经没有卡顿了。感谢感谢！！！

**Comment by SuperKung** [comment]
> 修改了release的逻辑，列表已经没有卡顿了。感谢感谢！！！

@kcufow 您好，请问是怎么修改的

**Comment by kcufow** [comment]
> > 修改了release的逻辑，列表已经没有卡顿了。感谢感谢！！！
> 
> @kcufow 您好，请问是怎么修改的

单独聊吧，不太好写出来的

**Comment by SuperKung** [comment]
> > > 修改了release的逻辑，列表已经没有卡顿了。感谢感谢！！！
> > 
> > 
> > @kcufow 您好，请问是怎么修改的
> 
> 单独聊吧，不太好写出来的

@kcufow  好的，我的邮箱是kungsc666@outlook.com，方便的话可以给我发邮件，先谢谢您了

**Comment by dtboy1995** [comment]
> 修改了release的逻辑，列表已经没有卡顿了。感谢感谢！！！

请问，方案是什么，谢谢

**Comment by manbuxingkong** [comment]
> 修改了release的逻辑，列表已经没有卡顿了。感谢感谢！！！

你好，请问这个逻辑是怎么修改的，非常感谢

**Comment by RainwalkerDean** [comment]
我也想问问怎么修改滴

**Comment by pxpxp** [comment]
我也想问问怎么修改滴

**Comment by BBNO** [comment]
> 修改了release的逻辑，列表已经没有卡顿了。感谢感谢！！！

@kcufow  您好，请问是怎么修改的
