### ISSUE TITLE
引入依赖'com.shuyu:GSYVideoPlayer:8.0.0'报错

### ISSUE THREAD

**Issue by forhaodream** [CarGuo/GSYVideoPlayer#3101]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 ZTE B860AV1.1

## GSY依赖版本

例如 `compile'com.shuyu:GSYVideoPlayer:8.0.0'`

## Demo中的复现步骤

引入依赖后, 运行项目出现

问题代码：(如果有)
compile 'com.shuyu:GSYVideoPlayer:8.0.0'

## 问题log（如果有）

Execution failed for task ':app:mergeDebugResources'.
> C:\Users\MSI\.android\build-cache\99a96b70419c425b486870064f9988d3c14be1dd\output\res\font\roboto_medium_numbers.ttf:1:1: Error: Content is not allowed in prolog.

**Comment by CarGuo** [comment]
不是 gsy 项目问题
