### ISSUE TITLE
连续播放问题

### ISSUE THREAD

**Issue by ly469097645** [CarGuo/GSYVideoPlayer#3102]
## 问题描述：

需求是实现类似爱奇艺，腾讯视频这样的连续播放功能，我在onAutoComplete方法中执行了播放下一条视频的代码，如果在小屏模式下播放正常，会一集播放完成之后继续播放下一集，但是如果我是在点击放大（全屏）的情况下播放完了一集之后，onAutoComplete中的代码也会走，也调用了开始播放的方法，但是播放器不会播放，请问这个问题在哪

## 问题机型/系统：

Android studio模拟器（android r）
华为noval3（9.1.0）

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:8.0.0'

## Demo中的复现步骤

Demo中的SimpleDetailActivityMode1页面打开后，修改代码onAutoComplete方法中加入播放另外一段视频也会出现这个

##问题代码
    @Override
    public void onAutoComplete(String url, Object... objects) {
        List<CourseItemBean> data = mCourseVideoAdapter.getData();
        int current = mCourseVideoAdapter.getCurrent();
        if (current < mCourseVideoAdapter.getData().size() - 1) {
            current++;
            mCourseItemBean = data.get(current);
            mCourseVideoAdapter.setCurrent(current);
            startPlay(mCourseItemBean.getVideoUrl());
            LogUtils.e("播放完成了,跳转下一集");
        }
    }

   private void startPlay(String newUrl) {
        if (isPause) {
            return;
        }
        ImageView imageView = new ImageView(this);
        ImageUtils.setImage(this, newUrl, imageView, R.mipmap.pic_zwnr);
        mGsyVideoOptionBuilder.setUrl(newUrl)
                .setVideoTitle("")
                .build(mStandardGSYVideoPlayer);
        mStandardGSYVideoPlayer.startPlayLogic();
    }

**Comment by CarGuo** [comment]
参考 demo 的自定义 exo 或者用 ListGSYVideoPlayer

**Comment by ly469097645** [comment]
![image](https://user-images.githubusercontent.com/12133597/104433830-7c76a280-55c5-11eb-8587-a26f6c139be4.png)
不是那种纯列表滑动到播放，是这种也可以使用ListGSYVideoPlayer吗

**Comment by ly469097645** [comment]
不是那种滑动到就播放的那种列表，是这种也可以使用ListGSYVideoPlayer吗

https://user-images.githubusercontent.com/12133597/104434502-41c13a00-55c6-11eb-8ab2-b3d08bbe51b4.mp4

**Comment by ly469097645** [comment]
![Uploading 微信图片_20210113173217.png…]()

**Comment by ly469097645** [comment]
不是那种滑动到就播放的那种列表，是这种也可以使用ListGSYVideoPlayer吗

https://user-images.githubusercontent.com/12133597/104434949-cf048e80-55c6-11eb-8206-c850e3a85418.mp4

![111](https://user-images.githubusercontent.com/12133597/104435137-ffe4c380-55c6-11eb-8554-6ce66bf2e93c.png)

**Comment by CarGuo** [comment]
ListGSYVideoPlayer 就是用来给你做这种的，不是做那种滑动到就播放的那种列表
