### ISSUE TITLE
自动拼接 http://127.0.0.1:38452 的问题

### ISSUE THREAD

**Issue by HZHAndroid** [CarGuo/GSYVideoPlayer#3104]
有些时候，视频链接会自动拼接上 http://127.0.0.1:38452 导致播放失败，无论是 https 或 http ，都会出现这种情况；

**Comment by HZHAndroid** [comment]
HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :1

**Comment by CarGuo** [comment]
cache 设置为 false

**Comment by HZHAndroid** [comment]
cache 设置为 false，就没有缓存了，而且有部分视频播放，不了，必须切换其他内核才可以，反正每种内核都有部分视频播放不了；

**Comment by CarGuo** [comment]
什么内核播放不了什么视频，请提供对应的 url

**Comment by HZHAndroid** [comment]
// 系统 内核
PlayerFactory.setPlayManager(SystemPlayerManager.class);
// IJK 内核
        PlayerFactory.setPlayManager(IjkPlayerManager.class);
        这些情况都是一样的，要么有些链接系统内核能播放，IJK内核无法播放，要么 IJK内核可以播放，系统内核无法播放；

**Comment by CarGuo** [comment]
所以我说 什么内核播放不了什么视频，请提供对应内核不能播放的 url

**Comment by HZHAndroid** [comment]
链接给不了你，内网，给到你，你也访问不了，有部分视频播放不了，好像是可能是视频编码问题，浏览器下载，在电脑视频播放器，正常播放，在 GSYVideoPlayer，我要通过调用不同的内核，去尝试播放，然后播放的结果，就是我描述的那个

**Comment by HZHAndroid** [comment]
加入我动态切换内核，怎么让链接继续根据新切换的内核去访问资源？就是我切换内核后，需要调用其他方法吗？例如： GSYVideoManager.releaseAllVideos();

**Comment by CarGuo** [comment]
是的  GSYVideoManager.releaseAllVideos(); ，另外可以参考 https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
