### ISSUE TITLE
Ijk 内核播放本地 m3u8 包含网络 ts 分片地址问题

### ISSUE THREAD

**Issue by xwlcn** [CarGuo/GSYVideoPlayer#3105]
## 问题描述：

Ijk 内核播放本地 m3u8 包含网络 ts 分片地址，会报错：`E/IJKMEDIA: Protocol 'https' not on whitelist 'file,crypto'!`

## 问题机型/系统：

全系列

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:8.0.0'

## Demo中的复现步骤

Ijk 内核，视频源使用包含网络分片地址的本地`m3u8`，都会报如上错误

##解决方案
目前自己已经在官网找到了解决方案。并且在不修改`GSYVideoPlayer`源码的前提下临时解决了该问题，希望能够帮助同样遇到该问题的人吧，同时也希望作者大大能够在源码中修复此问题。

临时解决方案：
自定义`FixIjkPlayerManager`如下：
```
class FixIjkPlayerManager: IjkPlayerManager() {

    override fun initVideoPlayer(
        context: Context?,
        msg: Message?,
        optionModelList: MutableList<VideoOptionModel>?,
        cacheManager: ICacheManager?
    ) {
        super.initVideoPlayer(context, msg, optionModelList, cacheManager)
        (mediaPlayer as IjkMediaPlayer).setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "crypto,file,http,https,tcp,tls,udp")
    }
}
```
最后在使用的时候手动指定播放器内核：
> PlayerFactory.setPlayManager(FixIjkPlayerManager::class.java)

**Comment by CarGuo** [comment]
看问题集锦

```
VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", crypto,file,http,https,tcp,tls,udp);

```
