### ISSUE TITLE
EXO模式播放TS的时候 字幕显示不出来  MP4可以

### ISSUE THREAD

**Issue by MrLizhiguang** [CarGuo/GSYVideoPlayer#3106]
测试地址   视频地址: https://ops-aiops.oss-cn-hongkong.aliyuncs.com/vod/6049_41454_zuihoudefengzhizi2010_play.ts
                  字幕地址: http://sourcefile.32868.cc/srtfile/6049_41454_zuihoudefengzhizi2010_play_zh_CN.srt

**Comment by CarGuo** [comment]
这个你看一下 Debug 下 SingleSampleMediaSource 是不是正常工作就知道了 ，字幕是在 demo 里的 GSYExoSubTitlePlayer 的 SingleSampleMediaSource 部分设置的

**Comment by MrLizhiguang** [comment]
就是在GSYExoSubTitlePlayer 里面跑的 视频地址  是MP4的话 就正常

**Comment by CarGuo** [comment]
你看我上面的回复就知道了，自己调整下

**Comment by MrLizhiguang** [comment]
okok  谢谢  我看下

**Comment by MrLizhiguang** [comment]
不对啊  我也是单个 srt   只是视频  是TS

**Comment by MrLizhiguang** [comment]
你看我的测试地址

**Comment by CarGuo** [comment]
这个问题很简单，就是 setLanguage 在内部的 selectTextTrack 时，TextTrackScore 通过 getFormatLanguageScore 方法判断语言获取匹配不上

比如你把 demo 里的 setLanguage 的 en 改为  zh-CN

```
        Format textFormat = new Format.Builder()
                .setSampleMimeType(MimeTypes.APPLICATION_SUBRIP)
                .setSelectionFlags(C.SELECTION_FLAG_FORCED)
                .setLanguage("zh-CN").build();
```


甚至你干脆不设置 setLanguage

**Comment by MrLizhiguang** [comment]
是的  是的  问题没找对   谢谢博主

**Comment by pfyuan** [comment]
@MrLizhiguang   你那个字幕问题解决了吗
