### ISSUE TITLE
GSYExo2PlayerView 分屏播放

### ISSUE THREAD

**Issue by wuyihao99** [CarGuo/GSYVideoPlayer#3107]
需求要同时播放多个视频（每个都是循环的队列）ListGSYVideoPlayer在切换时候有明显的停顿黑屏，所以用GSYExo2PlayerView来实现无缝切换，但是同时播放多个功能要怎么加入到GSYExo2PlayerView来实现呢，需要修改哪些方法，请大佬教下

**Comment by CarGuo** [comment]
参考 MultiSampleVideo ，然后内核 PlayerManager 部分你可以继续自定义就行了
