### ISSUE TITLE
4k视频 播放有问题  exo花屏  ijk崩溃 两个视频时长都不对

### ISSUE THREAD

**Issue by MrLizhiguang** [CarGuo/GSYVideoPlayer#3108]
测试地址 https://ops-aiops.oss-cn-hongkong.aliyuncs.com/vod/311_620_Venom20184K_play.ts

**Comment by CarGuo** [comment]
我测试 ijk 没有崩溃，不过花屏和卡顿，很正常，因为ijk软解码4k只能靠cpu肯定顶不住


exo 用的是 MediaCodec，我这边机器华为p30pro没有卡顿和花屏，正常播放，这个是和设备的gpu也有关系！

时长问题你调试获取下就知道了，一般就是流的兼容问题

**Comment by MrLizhiguang** [comment]
已经搞好了 还得折腾下多音轨  再测试下
