### ISSUE TITLE
播放器是否默认支持播放多片段视频？

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#311]
播放器是否默认支持播放多片段视频？

假如没有支持，要自己编译so吗，还是哪里有已经编译好的？

**Comment by CarGuo** [comment]
ts分片吗？concat协议默认没支持，m3u8支持。如果需要concat需要额外编译

**Comment by renwfy** [comment]
m3u8，分片播放，是怎么处理的？

我可能还需要concat，要编译的话，改怎么处理

**Comment by renwfy** [comment]
求教啊，需要自己编译的话，是要编译那个？或者有编译好的吗

**Comment by CarGuo** [comment]
2.0.1
