### ISSUE TITLE
滑动快进问题

### ISSUE THREAD

**Issue by xwlcn** [CarGuo/GSYVideoPlayer#3111]
首先，看了下`API`，有个`setSeekRatio`方法设置滑动快进的比例。

但是现在的问题是：`Dialog`显示太慢（这个是代码中由deltaX决定的），计算`seek`的时候我猜是以按下时的位置开始计算的，因此当`deltaX`达到弹出`Dialog`的临界值时，实际上`seek`已经增长了很多了，用户体验非常不友好，效果就是，拖动快进出现`Dialog`时发现`seek`快进的值已经增加了十几二秒或者更多（我在模拟器上测试从开始拖动到出现`Dialog`，`seek`增长了30多秒）。

很多时候可能只需要快进那么几秒，这时明明是快进但又不得不往回拉，希望改进逻辑，以弹出`Dialog`时的位置开始增加`seek`的值，即出现`Dialog`时`seek`才从0开始增加，或者`deltaX`弹出`Dialog`的临界值改小一些（不建议，小了很有可能出现误触）。

如果有其他解决这个问题的办法望告知，谢谢。

**Comment by CarGuo** [comment]
有 setSeekRatio 方法，甚至你可以 override touchSurfaceMove 和 touchSurfaceMoveFullLogic 方法
