### ISSUE TITLE
观看电视直播（flv格式）一小会后黑屏，且无法继续观看

### ISSUE THREAD

**Issue by q88qaz** [CarGuo/GSYVideoPlayer#3112]
观看直播地址：
http://122.228.250.223/al.flv.huya.com/src/1394565191-1394565191-5989611887484993536-2789253838-10057-A-0-1-imgplus.flv?ali_dispatch_cold_stream=on&ali_redirect_ex_hot=0

Android端第一次观看可以播放一小会，之后黑屏，无法恢复，无法继续播放
但是，IOS端虽然会卡一下，但是卡顿结束后还是可以继续播放，也不会黑屏
依赖版本：8.0

**Comment by CarGuo** [comment]
我用 exo 内核测试你这个链接，正常。 PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
