### ISSUE TITLE
横屏固定区域播放，全屏播放后无法恢复为横屏固定区域

### ISSUE THREAD

**Issue by pengkongkong** [CarGuo/GSYVideoPlayer#3114]
## 问题描述：

在横屏固定区域播放，全屏播放后，再次恢复横屏固定区域播放，会强制变成竖屏，无法恢复为横屏固定区域播放

## 问题机型/系统：

例如 真机 小米9 Android10.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## Demo中的复现步骤

将Demo中的detailPlayer页面在配置文件设置为横屏，然后全屏，在恢复，会恢复成竖屏状态

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2955

**Comment by pengkongkong** [comment]
好的，麻烦了
