### ISSUE TITLE
EXO  如何实现音轨切换

### ISSUE THREAD

**Issue by MrLizhiguang** [CarGuo/GSYVideoPlayer#3115]
EXO模式下  如何实现音轨切换  还望作者指点下

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setPlayerInitSuccessListener(new IPlayerInitSuccessListener() {
            ///播放器初始化成果回调
            @Override
            public void onPlayerInitSuccess(IMediaPlayer player, GSYModel model) {
                if (player instanceof IjkExo2MediaPlayer) {
                    ((IjkExo2MediaPlayer) player).setTrackSelector(new DefaultTrackSelector());
                    ((IjkExo2MediaPlayer) player).setLoadControl(new DefaultLoadControl());
                }
            }
        });

**Comment by MrLizhiguang** [comment]
我自己找到了  谢谢哈
