### ISSUE TITLE
可以支持DTS音频编码格式吗

### ISSUE THREAD

**Issue by DIBIAOZUIQIANGTEAM** [CarGuo/GSYVideoPlayer#3123]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

可以支持DTS音频编码格式吗

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q 参考这个····和根目录的 .sh 文件

**Comment by DIBIAOZUIQIANGTEAM** [comment]
> ····

没看到DTS呀 这个难道不是音频编码方式？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md
