### ISSUE TITLE
Demo最高版本改到30 支持Android11 ,build 里面NDK支持添加"arm64-v8a"  ,视频播放崩溃

### ISSUE THREAD

**Issue by Anbinghui** [CarGuo/GSYVideoPlayer#3126]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

Demo最该适配版本改为30, NDK支持"arm64-v8a" ,播放视频崩溃

## 问题机型/系统：

OnePlus 8T

## Demo中的复现步骤

修改完上述配置以后播放视频崩溃

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
在 Android 11 上，你应该是需要配置，我这边测试ok：

```
  <application android:allowNativeHeapPointerTagging="false">
  ...
  </application>

```

or

```
<application>
    <meta-data android:name="io.sentry.ndk.enable" android:value="false" />
</application>
```

**Comment by Anbinghui** [comment]
解决了,谢谢大佬

**Comment by limuyang2** [comment]
导致此问题的原因如下，有兴趣的可以看看学习下：
https://source.android.google.cn/devices/tech/debug/tagged-pointers

**Comment by CarGuo** [comment]
@limuyang2 这个问题新版本修复很久了

**Comment by ipcjs** [comment]
ijkplayer似乎是在https://github.com/bilibili/ijkplayer/commit/e99d640e5fe94c65132379307f92d7180bcde8e7 修复的问题？

**Comment by CarGuo** [comment]
@ipcjs 很早就合并过咯
