### ISSUE TITLE
Erro: Auto Replay long video. 

### ISSUE THREAD

**Issue by HackJoues** [CarGuo/GSYVideoPlayer#313]
Hello, I have a problem. I'm playing a bigger video but, in some times the video in middle of reproduction, reloaded of the begin. 
And when I'm paused and minimize the app, the instance no keep, and replay the video of begin again. 
¿Any solution?

**Comment by CarGuo** [comment]
replay in demo？Is it convenient for you to provide video url?

**Comment by HackJoues** [comment]
Yes, I'm use the PlayActivity Screen. And the url, it's take of a server like Openload.

**Comment by CarGuo** [comment]
this case  ,I need video url  to recreate the problem

**Comment by HackJoues** [comment]
Look you get a video streaming link in the source code of this page, the link streaming its generate depending of the user's Ip. 
https://www.raptu.com/embed/FHEIL19JOT
In your browser enter to this url, and look the source code, and extract a link streaming. (360p,480p, or 720p) you choice.

**Comment by CarGuo** [comment]
ok，i will try to replay it .

**Comment by HackJoues** [comment]
And so. Can you check the issue? 

_Sent from my TCL 5015A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CarGuo** [comment]
sorry, i can't replay it
