### ISSUE TITLE
现在播放本地MP3文件会显示音乐专辑封面，这个如何去掉了

### ISSUE THREAD

**Issue by kyriej** [CarGuo/GSYVideoPlayer#3130]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
demo 怎么复现问题

**Comment by kyriej** [comment]
不是demo ，我是继承standardpalyer ,然后自定义视频layout，播音乐时会出现音乐封面，不过可以肯定的是这个封面不是我这边加上去的，我在切换比例时(比如 16:9 , 4: 3 ,centercrop 啥的)，那个封面比例也在变

**Comment by CarGuo** [comment]
有测试链接么？

**Comment by kyriej** [comment]
是本地的音乐文件，不是网络链接

**Comment by CarGuo** [comment]
你可以压缩成 zip 上传到 github

**Comment by kyriej** [comment]
我发网盘了，
链接: https://pan.baidu.com/s/1uaRWrYMeC7LXkBgHmOKfeA
 提取码: adws

**Comment by CarGuo** [comment]
我试了下，你还是参考 demo 的 AudioDetailPlayer 实现吧，如果不需要自定义封面，把 detailPlayer.loadCoverImage("", R.drawable.lololo); 屏蔽了就好
