### ISSUE TITLE
大神，您的这个播放器能弄个flutter版本吗？

### ISSUE THREAD

**Issue by iperfectapp** [CarGuo/GSYVideoPlayer#3131]
现在跟着您在学习flutter，这个播放器能做个flutter插件吗？

**Comment by CarGuo** [comment]
不存在的，因为没有 iOS 版的 GSY ，哈哈哈哈

**Comment by iperfectapp** [comment]
IJKPlayer好像可以跨平台，您看看这个
https://github.com/befovy/fijkplayer
不过没更新了

**Comment by CarGuo** [comment]
和 ijk 没关系，官方的 video_player 也支持播放，只是很多逻辑在 gsy 上有的，iOS 上要对应实现多一次太费时了

**Comment by iperfectapp** [comment]
谢谢您的回答

**Comment by iperfectapp** [comment]
请问您的GSY播放器能够播放这种文件吗？
[http://biezhi360.cn:99/ngys.aspx?vod_id=152600&vod_key=%E7%AC%AC01%E9%9B%86](url)

**Comment by CarGuo** [comment]
这个数据流有问题吧···播放不了

**Comment by iperfectapp** [comment]
![image](https://user-images.githubusercontent.com/3021764/107143900-901dea80-6972-11eb-968e-15e192980c71.png)
我用您的那三个so包替换掉它自带的就能够播放，不知道是怎么回事，我猜可能是二进制的编码方式

**Comment by huhu2008** [comment]
> IJKPlayer好像可以跨平台，您看看这个 https://github.com/befovy/fijkplayer 不过没更新了

这个和原生的有冲突怎么解决

**Comment by yangyxd** [comment]
但是，可以出一个只支持 android 的 flutter 插件啊
