### ISSUE TITLE
android 11 播放崩溃

### ISSUE THREAD

**Issue by huohuoyoyo** [CarGuo/GSYVideoPlayer#3132]
播放短视频时发生了这样的问题！

机型/系统：

真机 小米CC9 pro android 11
## GSY依赖版本

![image](https://user-images.githubusercontent.com/12482839/107169835-cf434e80-69f9-11eb-834d-7d7accd73a98.png)
已提交issues  给 bilibili ，B站回复已经fixed   但是还是出现崩溃的现象，你那边是否需要update

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/3126
