### ISSUE TITLE
第一次点击全屏按钮能够全屏，第二次就不能全屏

### ISSUE THREAD

**Issue by SkyD666** [CarGuo/GSYVideoPlayer#3133]
## 问题描述：

第一次点击全屏按钮能够全屏，然后再点击退出全屏按钮后退出全屏。再次点击全屏按钮，就不能全屏了；如果退出全屏是按的安卓的后退键则第二次就可以全屏。
![Screenshot_20210215_135542_com skyd imomoe](https://user-images.githubusercontent.com/32453770/107910908-5cf0e200-6f96-11eb-92d9-abf0a454177b.jpg)
![Screenshot_20210215_135547_com skyd imomoe](https://user-images.githubusercontent.com/32453770/107910919-611cff80-6f96-11eb-9e06-23545ef18f54.jpg)

## 问题机型/系统：

真机 HONOR V20 Android9.0

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:8.1.0'

## 问题代码：(如果有)
```
<activity
            android:name=".view.activity.PlayActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
            android:screenOrientation="portrait" />

getFullscreenButton().setOnClickListener {
            orientationUtils?.run { if (isLand != 1) resolveByClick() }
            player.startWindowFullscreen(this@PlayActivity, true, true)
        }
```

**Comment by SkyD666** [comment]
https://user-images.githubusercontent.com/32453770/107911159-dab4ed80-6f96-11eb-9293-62d8251fcc15.mp4


https://user-images.githubusercontent.com/32453770/107911166-dc7eb100-6f96-11eb-8ff9-8d077308b0c7.mp4

**Comment by CarGuo** [comment]
demo 没有发现问题

**Comment by SkyD666** [comment]
这是具体设置代码，另外我发现通过后退键退出全屏横屏mIsLand是0，通过全屏按钮退出mIsLand就是1

    private fun GSYVideoPlayer.startPlay(url: String = "", title: String = "") {
        //设置全屏按键功能,这是使用的是选择屏幕，而不是全屏
        fullscreenButton.setOnClickListener {
            orientationUtils?.run { resolveByClick() }
            avp_play_activity.startWindowFullscreen(this@PlayActivity, true, true)
        }
        //防止错位设置
        playTag = this.javaClass.simpleName
        //音频焦点冲突时是否释放
        isReleaseWhenLossAudio = false
        //增加封面
        val imageView = ImageView(this@PlayActivity)
        imageView.scaleType = ImageView.ScaleType.CENTER_CROP
        //imageView.loadImage(it.cover?.detail ?: "")
        thumbImageView = imageView
        //thumbImageView.setOnClickListener { switchTitleBarVisible() }
        //是否开启自动旋转
        isRotateViewAuto = false
        //是否需要全屏锁定屏幕功能
        isNeedLockFull = true
        //是否可以滑动调整
        setIsTouchWiget(true)
        //设置触摸显示控制ui的消失时间
        dismissControlTime = 5000
        //设置播放过程中的回调
        setVideoAllCallBack(VideoCallPlayBack())
        //设置播放URL
        if (url == "") {
            setUp(
                viewModel.animeEpisodeDataBean.videoUrl,
                false, viewModel.animeEpisodeDataBean.title
            )
        } else {
            setUp(url, false, title)
        }
        //开始播放
        startPlayLogic()
    }

**Comment by SkyD666** [comment]
另外，这个项目（https://github.com/VIPyinzhiwei/Eyepetizer）使用了您的播放器，我是从这个项目学习的，我发现这个项目播放视频也有这个问题

**Comment by CarGuo** [comment]
你参考demo吧，并且看最新版本

**Comment by SkyD666** [comment]
as gradle好几个小时一直执行不完

**Comment by CarGuo** [comment]
这个没辙，你可以参考 demo 是什么情况

**Comment by skyshenfu** [comment]
@SkyD666 兄弟你好 我也遇到了相同的问题 请问你最后解决了吗 谢谢

**Comment by SkyD666** [comment]
> @SkyD666 兄弟你好 我也遇到了相同的问题 请问你最后解决了吗 谢谢

最后通过让自己的Activity继承GSYBaseActivityDetail这个Activity解决的，对应Demo的Detail模式

**Comment by micki-zhou** [comment]
我也遇到这个问题了，我是这样解决的:
`fullscreenButton?.setOnClickListener {
                orientationUtils?.isLand = 0 // 加上这句代码就不会出现问题了
                orientationUtils?.resolveByClick()
                mDataBinding?.detailVideo?.startWindowFullscreen(this@DetailActivity, true, true)
            }`

**Comment by micki-zhou** [comment]
我也遇到这个问题了，我是这样解决的:
`
fullscreenButton?.setOnClickListener { orientationUtils?.isLand = 0 // 加上这句代码就不会出现问题了 orientationUtils?.resolveByClick() mDataBinding?.detailVideo?.startWindowFullscreen(this@DetailActivity, true, true) }

`

**Comment by micki-zhou** [comment]
同样的问题，全屏按钮的事件加上一句代码就可以了：
`orientationUtils?.isLand = 0`
