### ISSUE TITLE
提交google play审核显示HostnameVerifier漏洞

### ISSUE THREAD

**Issue by 11101b** [CarGuo/GSYVideoPlayer#3134]
## 问题描述：

你好，我的应用提交到google play被拒绝，提示HostnameVerifier漏洞，查找原因是 HttpUrlSource 不验证证书：
   ((HttpsURLConnection) connection).setHostnameVerifier(new HostnameVerifier() {
                    @Override
                    public boolean verify(String hostname, SSLSession session) {
                        return true;
                    }
                });
直接return truem被google检测为漏洞
## 问题机型/系统：

例如 真机 小米 mi 8

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.6

## Demo中的复现步骤

HttpUrlSource 中没验证证书直接return true

麻烦告知处理的方法，我将感激不尽，谢谢

**Comment by CarGuo** [comment]
7.1.6 的版本，已经把这部分逻辑挪出来了啊 https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/UPDATE_VERSION.md#716-2020-09-08

**Comment by hiphonezhu** [comment]
HttpUrlSource

8.1.0 还是 return true 的啊

**Comment by CarGuo** [comment]
8.1.1 fix
