### ISSUE TITLE
flv格式视频，横竖屏切换会黑屏

### ISSUE THREAD

**Issue by 123123woodman** [CarGuo/GSYVideoPlayer#3135]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

flv格式视频，横竖屏切换会闪黑屏

## 问题机型/系统：

例如 真机 米10

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的 输入url功能页面可复现

测试url
https://cp15-c120-2.play.bokecc.com/flvs/ca/QxDhY/uo9gP2ugJy-9.flv?t=1614095554&key=D7EA792DC95A72B8EE055DF613F88D6C&tpl=20&tpt=220

**Comment by 123123woodman** [comment]
最新版demo也是一样的，黑下屏

**Comment by CarGuo** [comment]
https://cp15-c120-2.play.bokecc.com/flvs/ca/QxDhY/uo9gP2ugJy-9.flv?t=1614095554&key=D7EA792DC95A72B8EE055DF613F88D6C&tpl=20&tpt=220    url无法播放

**Comment by 123123woodman** [comment]
新的https://cp15-c120-2.play.bokecc.com/flvs/ca/QxDhY/uo9gP2ugJy-9.flv?t=1614135874&key=1E8E69AB08FD7D254162927665619E33&tpl=20&tpt=220   视频有时效可以加个联系方式吗？

**Comment by CarGuo** [comment]
如下图录屏所示，没发现问题


https://user-images.githubusercontent.com/10770362/108939261-652ed880-768c-11eb-9ee3-00ac1cbb2620.mp4

**Comment by 123123woodman** [comment]
我拿了VIVO的也没事，但是我的米10确实有问题，我给你录个屏

**Comment by CarGuo** [comment]
@123123woodman  我这个是小米11录屏的

**Comment by 123123woodman** [comment]
https://user-images.githubusercontent.com/29570622/108941559-4c282680-7690-11eb-8d53-052983303b6a.mp4

**Comment by CarGuo** [comment]
偶尔黑一下的问题这个目前没什么办法

**Comment by 123123woodman** [comment]
好的，多谢
