### ISSUE TITLE
初始化设置横屏播放，播放的过程中点击屏幕后，状态栏显示后不自动消失

### ISSUE THREAD

**Issue by shiwobuhaoma** [CarGuo/GSYVideoPlayer#3136]
## 问题描述：

初始化设置横屏播放，播放的过程中点击屏幕后，状态栏显示后不消失，发生了这样的问题！

## 问题机型/系统：

真机 小米redmi note5 Android9.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8'`

**Comment by CarGuo** [comment]
不明白，如下图视频所示，没发现问题

https://user-images.githubusercontent.com/10770362/108940140-cefbb200-768d-11eb-9356-d68a7bf9f2ca.mp4
