### ISSUE TITLE
ViewPage2 上下滑动切换的时候，感觉会闪一下，交互不大好！

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#3139]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

ViewPage2 上下滑动切换的时候，感觉会闪一下，交互不大好！

## 问题机型/系统：

真机 小米9 Android10

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'`

## Demo中的复现步骤

demo ViewPage2 页面切换好像也有这种现象。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
没事，不好你自己改改就行了，加油～！！
