### ISSUE TITLE
缓存视频再打开的问题

### ISSUE THREAD

**Issue by candrwow** [CarGuo/GSYVideoPlayer#314]
当第一次播放完后，关闭应用，再次进入后，需要加载很久才能播放，缓存目录里只有一个mp4文件，我看到之前的issue里提到如果视频缓存成功后应该先判断是否缓存成功，成功则将url地址变更为本地缓存好的mp4，但是这个mp4的文件名是一个乱码形式的，无法确定哪个mp4对应原先那个地址

**Comment by CarGuo** [comment]
不是很理解你说呢，demo中会吗？缓存是根据url存在本地的，而且缓存完成和未完成的名字是两种。

**Comment by candrwow** [comment]
我是直接用的这个
final String url = "http://baobab.wdjcdn.com/14564977406580.mp4";
gsyVideoPlayer.setUp(url, true , new File(“公司路径xxx”，“”));
gsyVideoPlayer.startPlayLogic();
然后会出现缓存路径下缓存成功的mp4文件没有缩略图封面，第二次打开没有调用缓存，打开时加载动画持续十几秒，这时候wifi网络正常。如果此时关闭网络，播放一段时间后，视频播放停止无法播放。
是否在设置缓存时还需要配置其他呢

**Comment by candrwow** [comment]
缓存路径下有两个文件，一个是40多M的mp4文件，还有一个同名的.mp4.download文件，大小0.00B（0字节）。mp4文件可以用其他播放器打开

**Comment by candrwow** [comment]
E/IJKMEDIA: file:///storage/emulated/0/GSYVideo/f72ff659bfcfbfe8263d7c2bec807d51.mp4%20: No such file or directory 当在视频缓存调取的时候我看log里显示了这个，在这个目录下是有这个mp4文件的，然后使用过程中这里会有一些奇怪问题，黑屏但是有声音等等

**Comment by CarGuo** [comment]
如果是黑屏有声音，那是因为编码问题，你可以看看首页，有一个说明，然后下个版本准备增加编译好的so支持这个问题。

**Comment by candrwow** [comment]
@CarGuo ，可是在第一次播放时是可以正常播放的，只要目录下有了缓存的mp4或者.download文件，就一直提示No such file or directory,然后播放时视频就先加载十几秒左右然后从新需要网络才能播放

**Comment by candrwow** [comment]
@CarGuo 不好意思，我这边才注意到后缀有个空格，本地可以播放
