### ISSUE TITLE
怎么监听播放器的全屏切换状态？

### ISSUE THREAD

**Issue by q88qaz** [CarGuo/GSYVideoPlayer#3140]
use by StandardGSYVideoPlayer
或者全屏切换是否有事件回调？

**Comment by q88qaz** [comment]
场景是进入全屏后显示返回键
非全屏状态下播放时隐藏返回键

**Comment by ff-frida** [comment]
这位道友，issue没有使用模板啊。。。。。。。。。。。
```
// v 8.1.0 我也遇到类似问题。查看api发现，默认情况下是全屏隐藏虚拟键的。

GSYVideoControlView.java

/**
* 全屏隐藏虚拟按键，默认打开
*/
    public void setHideKey(boolean hideKey) {
        this.mHideKey = hideKey;
    }
```
自己控制这个方式，全屏的时候就不会隐藏了。

问题：【非全屏状态下播放时隐藏返回键】
这个自己处理就行，或者可以参考lib中的方法。

**Comment by q88qaz** [comment]
> 这位道友，issue没有使用模板啊。。。。。。。。。。。
> 
> ```
> // v 8.1.0 我也遇到类似问题。查看api发现，默认情况下是全屏隐藏虚拟键的。
> 
> GSYVideoControlView.java
> 
> /**
> * 全屏隐藏虚拟按键，默认打开
> */
>     public void setHideKey(boolean hideKey) {
>         this.mHideKey = hideKey;
>     }
> ```
> 
> 自己控制这个方式，全屏的时候就不会隐藏了。
> 
> 问题：【非全屏状态下播放时隐藏返回键】
> 这个自己处理就行，或者可以参考lib中的方法。

哥你误会了，我不是要隐藏底部导航按钮的返回键
我是要根据全屏状态来隐藏播放器内置在左上角的 【<】 返回键

**Comment by CarGuo** [comment]
VideoAllCallBack  onEnterFullscreen

**Comment by ff-frida** [comment]
> VideoAllCallBack onEnterFullscreen

谢谢提醒
