### ISSUE TITLE
rtsp 无法播放

### ISSUE THREAD

**Issue by aglszz** [CarGuo/GSYVideoPlayer#3143]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

rtsp 无法播放

## 问题机型/系统：
android7.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'

//是否需要ExoPlayer模式
implementation 'com.shuyu:GSYVideoPlayer-exo2:8.1.0'

//更多ijk的编码支持
implementation 'com.shuyu:gsyVideoPlayer-ex_so:8.1.0'

## Demo中的复现步骤

问题代码：(如果有)
```
        videoPlayer =  findViewById(R.id.video_player);
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp");
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video"); //根据媒体类型来配置
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1);  // 无限读
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
        list.add(videoOptionModel);
        //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
        String source1 ="rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov";
        videoPlayer.setUp(source1, true, "");
        videoPlayer.getTitleTextView().setVisibility(View.GONE);
        videoPlayer.startPlayLogic();
```

## 问题log（如果有）
02-26 09:55:58.443 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_native_setup
02-26 09:55:58.443 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: av_version_info: ff4.0--ijk0.8.8--20210205--001
02-26 09:55:58.443 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: ijk_version_info: k0.8.8-32-ge99d640e
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ffpipeline_create_from_android()
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_set_inject_opaque(0x200486)
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_set_inject_opaque()=void
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x200486)
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi V/IJKMEDIA: setDataSource: path rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_set_data_source(url="rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov")
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_set_data_source(url="rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov")=0
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setLoopCount
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(1)
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: moncleanup
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOption
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOption
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOption
02-26 09:55:58.444 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setOptionLong
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_setVolume
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ffpipeline_set_volume
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_prepareAsync
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_prepare_async()
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi W/IJKMEDIA: remove 'timeout' option for rtmp.
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: ===== versions =====
02-26 09:55:58.445 3415-3478/com.welsee.shipinceshi I/IJKMEDIA: SDL_RunThread: [3478] ff_msg_loop
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: ijkplayer    : k0.8.8-32-ge99d640e
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: FFmpeg       : ff4.0--ijk0.8.8--20210205--001
02-26 09:55:58.445 3415-3478/com.welsee.shipinceshi D/IJKMEDIA: message_loop
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: libavutil    : 56.14.100
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: libavcodec   : 58.18.100
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: libavformat  : 58.12.100
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: libswscale   : 5.1.100
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: libswresample: 3.1.100
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: ===== options =====
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: player-opts : loop                         = 1
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: player-opts : packet-buffering             = 0
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : ijkapplication               = 0xb8df0cf0
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : ijkiomanager                 = 0xb8bf5bc8
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : rtsp_transport               = tcp
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : rtsp_flags                   = prefer_tcp
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : allowed_media_types          = video
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : flush_packets                = 1
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : buffer_size                  = 1316
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : infbuf                       = 1
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : analyzemaxduration           = 100
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: format-opts : probesize                    = 10240
02-26 09:55:58.445 3415-3415/com.welsee.shipinceshi I/IJKMEDIA: ===================
02-26 09:55:58.448 3415-3478/com.welsee.shipinceshi D/IJKMEDIA: FFP_MSG_FLUSH:
02-26 09:55:58.448 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_prepare_async()=0
02-26 09:55:58.448 3415-3479/com.welsee.shipinceshi I/IJKMEDIA: SDL_RunThread: [3479] ff_vout
02-26 09:55:58.448 3415-3480/com.welsee.shipinceshi I/IJKMEDIA: SDL_RunThread: [3480] ff_read
02-26 09:55:58.448 3415-3480/com.welsee.shipinceshi W/IJKMEDIA: remove 'timeout' option for rtmp.
02-26 09:55:58.449 3415-3480/com.welsee.shipinceshi V/IJKMEDIA: Probing rtsp score:100 size:0
02-26 09:55:58.449 3415-3480/com.welsee.shipinceshi D/IJKMEDIA: No default whitelist set
02-26 09:55:58.463 3415-3480/com.welsee.shipinceshi E/IJKMEDIA: Failed to resolve hostname wowzaec2demo.streamlock.net: No address associated with hostname
02-26 09:55:58.463 3415-3480/com.welsee.shipinceshi E/IJKMEDIA: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov: I/O error
02-26 09:55:58.463 3415-3480/com.welsee.shipinceshi I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [3480]
02-26 09:55:58.463 3415-3478/com.welsee.shipinceshi D/IJKMEDIA: FFP_MSG_ERROR: 0
02-26 09:55:58.475 3415-3415/com.welsee.shipinceshi E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
02-26 09:55:58.506 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: IjkMediaPlayer_release
02-26 09:55:58.506 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
02-26 09:55:58.506 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ffpipeline_set_surface()
02-26 09:55:58.506 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
02-26 09:55:58.506 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_shutdown_l()
02-26 09:55:58.506 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: wait for read_tid
02-26 09:55:58.506 3415-3478/com.welsee.shipinceshi D/IJKMEDIA: message_loop exit
02-26 09:55:58.506 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: wait for video_refresh_tid
02-26 09:55:58.506 3415-3478/com.welsee.shipinceshi I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [3478]
02-26 09:55:58.509 3415-3479/com.welsee.shipinceshi I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [3479]
02-26 09:55:58.509 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_shutdown_l()=void
02-26 09:55:58.509 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_dec_ref(): ref=0
02-26 09:55:58.509 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_shutdown_l()
02-26 09:55:58.509 3415-3415/com.welsee.shipinceshi D/IJKMEDIA: ijkmp_shutdown_l()=void

```

**Comment by CarGuo** [comment]
测试链接

**Comment by aglszz** [comment]
不好意思哈  可以用  我的锅
