### ISSUE TITLE
rtsp延迟问题

### ISSUE THREAD

**Issue by aglszz** [CarGuo/GSYVideoPlayer#3144]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

rtsp播放  刚开始延迟 600毫秒  播放 一小时  延迟1.4秒  播放 2个小时  延迟3.2秒  播放时间越长延迟越高
  
## 问题机型/系统：

Android7.0

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:8.1.0'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:8.1.0'

## Demo中的复现步骤

问题代码：(如果有)
```

```

## 问题log（如果有）

```



```

**Comment by aglszz** [comment]
VideoOptionModel videoOptionMode05 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);//丢帧,太卡可以尝试丢帧    尝试 丢帧的话   这个1 代表什么意思呢   0-120    丢的越多延迟越低？

**Comment by aglszz** [comment]
V/ IJKMEDIA: ret=1 c=24 [$]
V/IJKMEDIA: id=2 len=332
V/IJKMEDIA: tcp_ read_ packet:
D/ I JKMEDIA: nal _unit_ type: 1, nal_ ref_ idc: 3
V/IJKMEDIA: ret=1 c=24 [$]
V/IJKMEDIA: id=0 len=1440
V/IJKMEDIA: tcp_ read_ packet:
V/IJKMEDIA: ret=1 c=24 [$]
V/IJKMEDIA: id=0 len=1440 
V/IJKMEDIA: tcp_ read_ packet:
V/IJKMEDIA: ret=1 c=24 [$]
V/ IJKMEDIA: id=0 len=1440
V/ IJKMEDIA: tcp_ read_ packet:
V/ IJKMEDIA: ret=1 c=24 [$]
V/ IJKMEDIA: id=0 len=1440
V/ IJKMEDIA: tcp_ read packet:
V/ IJKMEDIA: ret=1 c=24 [$]
V/ IJKMEDIA: id=0 len=1440
V/ IJKMEDIA: tcp_ read_ packet: 
V/I JKMEDIA: ret=1 c=24 , $ ]
V/ IJKMEDIA: id=0 len=1440
V/IJKMEDIA: tcp_ read packet:
V/IJKMEDIA: ret=1 c=24 [$]
V/IJKMEDIA: id=0 len=1440
V/IJKMEDIA: tcp_ read_ packet: 
V/IJKMEDIA: ret=1 c=24 [$]
V/IJKMEDIA: id=0 len=1440 
V/IJKMEDIA: tcp_ read_ packet: 
    这个日志怎么关闭打印  刷日志太快了

**Comment by youwenjie1987** [comment]
我在写一个 Wifi 热点连接的记录仪程序，rtsp 预览也遇到这个问题，积累延时。
我想这应该是可以配置的，但是由于对源码不熟，没有找到方法，请问你解决了吗？

**Comment by mihefan** [comment]
> 我在写一个 Wifi 热点连接的记录仪程序，rtsp 预览也遇到这个问题，积累延时。
> 我想这应该是可以配置的，但是由于对源码不熟，没有找到方法，请问你解决了吗？

积累延时，光靠配置参数是不够的。ff_player.c文件里有个函数video_refresh，它里面有个delay变量，把delay=0后，rtsp延时基本上可以一直维持在200ms左右。

**Comment by aglszz** [comment]
> 我在写一个 Wifi 热点连接的记录仪程序，rtsp 预览也遇到这个问题，积累延时。
> 我想这应该是可以配置的，但是由于对源码不熟，没有找到方法，请问你解决了吗？

private void init() {
        List<VideoOptionModel> list = new ArrayList<>();
        VideoOptionModel videoOptionMode01 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "fast", 1);//不额外优化
        list.add(videoOptionMode01);
        VideoOptionModel videoOptionMode02 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 200);//10240
        list.add(videoOptionMode02);
        VideoOptionModel videoOptionMode03 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);
        list.add(videoOptionMode03);
        VideoOptionModel videoOptionMode04 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);//是否开启缓冲
        list.add(videoOptionMode04);
        VideoOptionModel videoOptionMode05 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 30);//丢帧,太卡可以尝试丢帧
        list.add(videoOptionMode05);
        VideoOptionModel videoOptionMode06 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 1);
        list.add(videoOptionMode06);
        VideoOptionModel videoOptionMode07 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);//默认值48
        list.add(videoOptionMode07);
        VideoOptionModel videoOptionMode11 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max-buffer-size", 0);//最大缓存数
        list.add(videoOptionMode11);
        VideoOptionModel videoOptionMode12 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "min-frames", 2);//默认最小帧数2
        list.add(videoOptionMode12);
        VideoOptionModel videoOptionMode13 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max_cached_duration", 30);//最大缓存时长
        list.add(videoOptionMode13);
        VideoOptionModel videoOptionMode14 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "infbuf", 1);//是否限制输入缓存数
        list.add(videoOptionMode14);
        VideoOptionModel videoOptionMode15 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "fflags", "nobuffer");
        list.add(videoOptionMode15);
        VideoOptionModel videoOptionMode16 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");//tcp传输数据
        list.add(videoOptionMode16);
        VideoOptionModel videoOptionMode17 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzedmaxduration", 100);//分析码流时长:默认1024*1000
        list.add(videoOptionMode17);
        GSYVideoManager.instance().setOptionModelList(list);
    }




延迟 设置丢帧30     延迟大概在600ms    运行几个月了  没关过  现在还是 600ms

**Comment by oldTomatoCN** [comment]
> > 我在写一个 Wifi 热点连接的记录仪程序，rtsp 预览也遇到这个问题，积累延时。
> > 我想这应该是可以配置的，但是由于对源码不熟，没有找到方法，请问你解决了吗？
> 
> private void init() { List list = new ArrayList<>(); VideoOptionModel videoOptionMode01 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "fast", 1);//不额外优化 list.add(videoOptionMode01); VideoOptionModel videoOptionMode02 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 200);//10240 list.add(videoOptionMode02); VideoOptionModel videoOptionMode03 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1); list.add(videoOptionMode03); VideoOptionModel videoOptionMode04 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);//是否开启缓冲 list.add(videoOptionMode04); VideoOptionModel videoOptionMode05 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 30);//丢帧,太卡可以尝试丢帧 list.add(videoOptionMode05); VideoOptionModel videoOptionMode06 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 1); list.add(videoOptionMode06); VideoOptionModel videoOptionMode07 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);//默认值48 list.add(videoOptionMode07); VideoOptionModel videoOptionMode11 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max-buffer-size", 0);//最大缓存数 list.add(videoOptionMode11); VideoOptionModel videoOptionMode12 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "min-frames", 2);//默认最小帧数2 list.add(videoOptionMode12); VideoOptionModel videoOptionMode13 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max_cached_duration", 30);//最大缓存时长 list.add(videoOptionMode13); VideoOptionModel videoOptionMode14 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "infbuf", 1);//是否限制输入缓存数 list.add(videoOptionMode14); VideoOptionModel videoOptionMode15 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "fflags", "nobuffer"); list.add(videoOptionMode15); VideoOptionModel videoOptionMode16 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");//tcp传输数据 list.add(videoOptionMode16); VideoOptionModel videoOptionMode17 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzedmaxduration", 100);//分析码流时长:默认1024*1000 list.add(videoOptionMode17); GSYVideoManager.instance().setOptionModelList(list); }
> 
> 延迟 设置丢帧30 延迟大概在600ms 运行几个月了 没关过 现在还是 600ms

仁兄真是太棒了，我也遇到了延迟积累的问题，我尝试一下你的方式
