### ISSUE TITLE
能新增方法配置videoPlayer的显示比例吗

### ISSUE THREAD

**Issue by conghuahuadan** [CarGuo/GSYVideoPlayer#3145]
## 问题描述：

我知道可以通过GSYVideoType.setShowType配置显示比例，但是是针对全局的，希望能通过GSYVideoOptionBuilder或者videoPlayer对象配置

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'`

**Comment by CarGuo** [comment]
你可以参考demo 的 CustomRenderView  和 CustomRenderVideoPlayer ，自己添加自定义逻辑
