### ISSUE TITLE
请问自定义UI时加入TextureView，全屏下无法显示怎么办呢？

### ISSUE THREAD

**Issue by 631582579** [CarGuo/GSYVideoPlayer#3147]
## 问题描述：

请问自定义UI时加入TextureView，全屏下无法显示怎么办呢？我使用其他View是可以显示的

## 问题机型/系统：

例如 真机 一加6T Android 10

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:8.1.0'

## Demo中的复现步骤

重写了StandardGSYVideoPlayer，加入了自定的View组件TextureView，但是全屏状态下并不现实

**Comment by CarGuo** [comment]
player.getCurrentPlayer

或者看

startWindowFullscreen 、resolveNormalVideoShow cloneParams

**Comment by 631582579** [comment]
我了解过您说的相关方法的逻辑了的，不过我是重写的StandardGSYVideoPlayer的init方法开启摄像头并进行实时预览，按理说全屏切换时，在重新创建播放器对象时init方法都会被调用，不涉及参数的克隆。现在的问题是TextureView显示不了，摄像头是启动了的，我觉得可能是这个View显示的层次问题，但是在处理这个问题上我不是很有经验，麻烦大佬提点一下。
<img width="715" alt="QQ20210302-103323@2x" src="https://user-images.githubusercontent.com/79846449/109587987-f5fd2c80-7b42-11eb-9b55-47c47703ab2f.png">

**Comment by CarGuo** [comment]
你可以修改 renderType 设置成 Surface
