### ISSUE TITLE
播放错误后，点击播放器空白区域，底部的控制栏一闪而过

### ISSUE THREAD

**Issue by q88qaz** [CarGuo/GSYVideoPlayer#3152]
播放错误后，点击播放器空白区域，底部的控制栏一闪而过（闪一下就消失，立马出现，立马消失，立刻出现，立刻消失，）
希望说在playError之后，点击空白区域，底部的控制栏也能够按照设置好的消失时间到了之后才消失，而不要一闪而过

**Comment by CarGuo** [comment]
如果我们理解错，你 override onClickUiToggle 就可以了
