### ISSUE TITLE
边玩边换屏幕类型 | Change Screen Type while playing

### ISSUE THREAD

**Issue by LetrixZ** [CarGuo/GSYVideoPlayer#3153]
It is possible to change Screen Type while a video is playing? If yes, can you tell me how? Thanks.
This is what I'm trying:
```GSYVideoType.setShowType(GSYVideoType.{SCREEN_TYPE}```
It does change it only when view it's destroyed, but not in real time.

DeepL:
可以在播放视频时改变屏幕类型吗？如果可以，你能告诉我怎么做吗？谢谢。
这是我正在尝试的。
```GSYVideoType.setShowType(GSYVideoType.{SCREEN_TYPE}```
它只有在视图被破坏时才会改变，但在播放视频时不会。

**Comment by CarGuo** [comment]
In Demo ， `SampleVideo` call  `changeTextureViewShowType` & ` mTextureView.requestLayout()`  function after ` GSYVideoType.setShowType`

**Comment by LetrixZ** [comment]
It worked. Thanks.
