### ISSUE TITLE
viewpager2中播放多个视频后，SeekBar高度显示不正确

### ISSUE THREAD

**Issue by gangoogle** [CarGuo/GSYVideoPlayer#3154]
## 问题描述：

在viewpager2中使用StandardGSYVideoPlayer，播放一个视频后，滑动到下一个页面，下一个页面的播放器SeekBar的高度会出现错误
这个videoView应该是被viewholder复用了

## 问题机型/系统：

 真机 小米10 Android11
 真机  一加7Pro android 6

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'`

图片：
正常状态
https://ae01.alicdn.com/kf/U8c74575033644d4bb0e2485d4d26822fl.jpg
问题状态
https://ae01.alicdn.com/kf/Uf67633b19f2d45f3bce85f588e4d68b92.jpg

**Comment by CarGuo** [comment]
Demo 中的  ViewPager2Activity 没有复现

**Comment by gangoogle** [comment]
我得问题，可以关了

**Comment by gangoogle** [comment]
千万不要在onBindViewHolder里面再次设置progressDrawable
