### ISSUE TITLE
请问视频播放时，点击视频出现暂停弹窗和进度条的代码在哪里。？

### ISSUE THREAD

**Issue by mmy-wly** [CarGuo/GSYVideoPlayer#3156]
我看视频播放时，点击一下出现暂停按钮和进度条，双击则暂停显示进度条。  但我在自己的项目中只有双击有反应，单击没有反应。 是忘记加什么代码了吗

**Comment by CarGuo** [comment]
你要的是 StandardGSYVideoPlayer 里面的 onClickUiToggle?

**Comment by mmy-wly** [comment]
嗯嗯  不过我发现问题了，现在下载的代码  重载的onClickUiToggle带有MotionEvent参数，但实际应该是不需要带参数的，带参数报错我就直接注释掉了，所以单击没有出现进度条。我把参数去掉，运行正常，能显示进度条了~

另外我还想问问，视频可以循环播放吗。？播放结束后自动重头播放

**Comment by CarGuo** [comment]
onClickUiToggle 在 8.0 是带了 MotionEvent 的

循环播放有 isLoop 的参数呢
