### ISSUE TITLE
ExoPlayer内核播放4K视频花屏

### ISSUE THREAD

**Issue by bichao1986** [CarGuo/GSYVideoPlayer#3157]
## 问题描述：

现在我是在机顶盒上去播放本地的视频，本地的视频是通过云端下载的.
出现了一个问题，我用华为P40 PRO录视频，分辨率选择[16:9]4K，代码设置如下：
 PlayerFactory.setPlayManager(Exo2PlayerManager.class);
 GSYVideoType.enableMediaCodec();
 GSYVideoType.enableMediaCodecTexture();
然后Exo内核播放就出现了花屏，因为之前反复在IJK和Exo之间做过比较，最后选择的Exo内核，这个是不可以更改的，非4K的视频没问题，可以正常播放，但是一旦播放4K视频就会出现花屏，请问有啥办法么
![Uploading image.png…]()

## 问题机型/系统：

机顶盒 Android7.1.2

## GSY依赖版本

直接引入的代码库

## Demo中的复现步骤

https://redian-development.oss-cn-beijing.aliyuncs.com/media/resource/VID_20210303_110332.mp4这个是在线地址，可以下载播放试试，必须要用EXO的内核

**Comment by CarGuo** [comment]
很正常啊，exo 用的是 mediacodec ，硬解码，支不支持 4k 和硬件有关系，很正常
