### ISSUE TITLE
mpg视频文件播放不了

### ISSUE THREAD

**Issue by chenqiwax** [CarGuo/GSYVideoPlayer#3158]
## 问题描述：

发现有个mpg文件播放有声音无画面

## 问题机型/系统：

真机 乐视Letv X501 Android6.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'

//是否需要ExoPlayer模式
implementation 'com.shuyu:GSYVideoPlayer-exo2:8.1.0'

//更多ijk的编码支持
implementation 'com.shuyu:gsyVideoPlayer-ex_so:8.1.0'

## Demo中的复现步骤

Demo中的SimplePlayer页面打开那个mpg会出现有声音无画面的问题。

问题代码:
```
如果需要这个视频的话我可以发给你
```

**Comment by CarGuo** [comment]
https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
