### ISSUE TITLE
如何全局静音

### ISSUE THREAD

**Issue by dakexuan** [CarGuo/GSYVideoPlayer#3160]
6.0.3版本，在视频播放前设置GSYVideoManager.instance().setNeedMute(true)，视频加载完还是有声音播放，点击播放按钮重新播放也还是有声音播放，只有在视频播放过程中设置这个api才有效果，如何做到静音播放？就是播放前就设置静音。

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setPlayerInitSuccessListener 可以在初始化 onPlayerInitSuccess 的时候做强制类型转换，配置 设置静音
