### ISSUE TITLE
全屏切换导致MediaCodec重建

### ISSUE THREAD

**Issue by chfdeng** [CarGuo/GSYVideoPlayer#3161]
## 问题描述：

请问一下，播放rtsp直播流时进行全屏切换会导致Surface切换进而导致MediaCodec重新创建，创建后需到下一个I帧才能解码出帧，所以出现了几秒的黑屏，求教下有没有什么解决方案，感谢

## 问题机型/系统：

RK3288开发板/Android 5.1

**Comment by CarGuo** [comment]
测试Demo没有发现问题

**Comment by chfdeng** [comment]
是硬解，已经解决了，谢谢
