### ISSUE TITLE
关于怎么获取GSYVideoGLView的问题

### ISSUE THREAD

**Issue by KleinerFrosch** [CarGuo/GSYVideoPlayer#3162]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我需要对GSYVideoGLView进行一些配置，请问应该怎么获取到GSYVideoGLView

GSYVideoPlayer有办法获取到吗

**Comment by CarGuo** [comment]
参考 demo 的 CustomRenderVideoPlayer ，直接自定义就好了
