### ISSUE TITLE
webview 中能够嵌套你这个videoview么?

### ISSUE THREAD

**Issue by OvenCroc** [CarGuo/GSYVideoPlayer#3166]
大佬 你好 我想问一下 你的gsyplayer可以嵌套到webview中播放么, 就是说webview中播放视频的时候使用的是你的videoview显示, 而不是用webview自带的视频播放器, 如果可以的话应该怎么做呢?

**Comment by CarGuo** [comment]
如果我理解没错的话，应该可以
