### ISSUE TITLE
循环播放视频，有时出现黑屏

### ISSUE THREAD

**Issue by kkkkk5G** [CarGuo/GSYVideoPlayer#3167]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
需求为循环播放U盘视频，经过测试发现当播完视频后进行下一曲概率性出现无图像有声音的问题：查看logcat有如下打印：

![image](https://user-images.githubusercontent.com/16422884/110729356-88937f00-8259-11eb-977b-6d062793e57f.png)

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不大清楚你什么情况，但是建议直接参考 GSYExo2MediaPlayer 的 ConcatenatingMediaSource 做列表来出来列表的循环播放

**Comment by kkkkk5G** [comment]
> 不大清楚你什么情况，但是建议直接参考 Demo 的 GSYExo2MediaPlayer 的 ConcatenatingMediaSource 做列表来出来列表的循环播放

我测试发现是切换视频时会删除surfaceView重新添加造成的，已经通过复用surfaceview surface尝试解决；不知道会不会有什么问题

**Comment by bumbleben2486** [comment]
> 
> 
> > 不大清楚你什么情况，但是建议直接参考 Demo 的 GSYExo2MediaPlayer 的 ConcatenatingMediaSource 做列表来出来列表的循环播放
> 
> 我测试发现是切换视频时会删除surfaceView重新添加造成的，已经通过复用surfaceview surface尝试解决；不知道会不会有什么问题

你好，可以说下怎么“复用surfaceView”法么

**Comment by bumbleben2486** [comment]
我也有类似的问题，ListGSYVideoPlayer中的playNext（）方法，在全屏下调用，有时候会出现画面黑屏、声音正常播放的问题。

**Comment by bumbleben2486** [comment]
版本是7.1.4，报错的log：
1616037157.438 32294-32294/com.eda365.elecnest.an W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
