### ISSUE TITLE
进度条的跨度问题

### ISSUE THREAD

**Issue by android-1995** [CarGuo/GSYVideoPlayer#3169]
## 问题描述：

进度条的max为100，导致时间长的视频拖动跨度过大，不能准确调整进度，建议改为视频的秒数

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'`

## Demo中的复现步骤

Demo中的滤镜页面打开后会出现这个问题。

**Comment by CarGuo** [comment]
进度如果设置为秒数，那拖动起来才是难受的······你可以修改 mSeekRatio 来调整触摸拖动的比例，这个倒是真的。

**Comment by android-1995** [comment]
> 进度如果设置为秒数，那拖动起来才是难受的······你可以修改 mSeekRatio 来调整触摸拖动的比例，这个倒是真的。

不会吧，好像视频软件都是用的秒数呀，比如腾讯爱奇艺这些

**Comment by CarGuo** [comment]
并不是

**Comment by android-1995** [comment]
好吧 试了下腾讯不是秒数，爱奇艺是秒数
