### ISSUE TITLE
播放直播流有画面没有声音

### ISSUE THREAD

**Issue by xuzhiyong017** [CarGuo/GSYVideoPlayer#3170]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放视频有画面没有声音

## 问题机型/系统：

真机 荣耀V20 Android10.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后播放会出现这个问题。

问题代码：(如果有)
```
播放这个直播流地址 http://39.134.39.39/PLTV/88888888/224/3221226273/index.m3u8
```

## 问题log（如果有）

```


```

**Comment by xuzhiyong017** [comment]
这个流的音频是需要mp2解码     
音频格式： Stream #0:1: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 128 kb/s

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md#支持mp2
