### ISSUE TITLE
dome中在使用GSYExoSubTitleVideoView 锁屏按钮不显示

### ISSUE THREAD

**Issue by pfyuan** [CarGuo/GSYVideoPlayer#3172]
## 问题描述：
引用dome里面的GSYExoSubTitleVideoView  锁屏按钮不显示  这个是在哪儿可以控制的

```

**Comment by CarGuo** [comment]
锁屏按钮？你是说锁定屏幕旋转的？

**Comment by pfyuan** [comment]
就是锁住不让不让拖动  不显示title和进度条  那个 🔒图片   不显示

**Comment by pfyuan** [comment]
![1RE~WE8`W ~R_%GCRI_FHA5](https://user-images.githubusercontent.com/44466203/111094224-c5bb8200-8575-11eb-9b54-a888f81070db.png)

**Comment by CarGuo** [comment]
那个是 api ，setIsTouchWiget 和 setIsTouchWigetFull

**Comment by pfyuan** [comment]
对  就那个lock_screen  我设置了visibility="visible" 但是还是显示不出来  这是什么原因

**Comment by CarGuo** [comment]
你看源码里的 mLockScreen 对象就知道了， StandardGSYVideoPlayer  和 GSYVideoControlView 里面是动态设置的。
