### ISSUE TITLE
提交google play审核显示HostnameVerifier漏洞

### ISSUE THREAD

**Issue by hiphonezhu** [CarGuo/GSYVideoPlayer#3174]
8.1.0 还是返回的 true 啊
 
HttpUrlSource

 public boolean verify(String hostname, SSLSession session) {
                        return true;
                    }

**Comment by CarGuo** [comment]
收到，忘记对 cache 内的部分去掉了，只去掉了 exo

**Comment by hiphonezhu** [comment]
大概何时修复，这边等着上架用。

**Comment by CarGuo** [comment]
8.1.1 fix
