### ISSUE TITLE
手机出现有声无画

### ISSUE THREAD

**Issue by crazyzjw** [CarGuo/GSYVideoPlayer#3175]
## 问题描述：

在线播放链接:http://video.jianzhiweike.net/dsh/20201108/c4df2ca5f26b620044f79b153162e157_ud.mp4

有声音没画面

## 问题机型/系统：

真机 VIVO Z3ⅰ ,HWJDN2 Android 9,ble6797_6m_n Android 7.1.1

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'`

**Comment by crazyzjw** [comment]
卸载重装app又可以,过一会再看视频又是黑屏有声音

**Comment by CarGuo** [comment]
demo 怎么复现？有 url  吗？
