### ISSUE TITLE
8.1.1版本无法集成

### ISSUE THREAD

**Issue by SkyD666** [CarGuo/GSYVideoPlayer#3176]
## 问题描述：
8.1.1版本无法集成，8.1.0可以

Failed to resolve: gsyVideoPlayer-armv7a-8.1.1
Affected Modules: app
Failed to resolve: gsyvideoplayer-androidvideocache-8.1.1
Affected Modules: app
Unable to resolve dependency for ':app@debug/compileClasspath': Could not download gsyVideoPlayer-armv5-8.1.1.aar (com.shuyu:gsyVideoPlayer-armv5:8.1.1)
Show Details
Affected Modules: app
Failed to resolve: gsyVideoPlayer-java-8.1.1
Affected Modules: app
Unable to resolve dependency for ':app@debug/compileClasspath': Could not download gsyVideoPlayer-x86-8.1.1.aar (com.shuyu:gsyVideoPlayer-x86:8.1.1)
Show Details
Affected Modules: app
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not download gsyVideoPlayer-armv5-8.1.1.aar (com.shuyu:gsyVideoPlayer-armv5:8.1.1)
Show Details
Affected Modules: app
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download gsyVideoPlayer-armv5-8.1.1.aar (com.shuyu:gsyVideoPlayer-armv5:8.1.1)
Show Details
Affected Modules: app
Failed to resolve: gsyVideoPlayer-arm64-8.1.1
Affected Modules: app
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not download gsyVideoPlayer-x86-8.1.1.aar (com.shuyu:gsyVideoPlayer-x86:8.1.1)
Show Details
Affected Modules: app
Failed to resolve: gsyVideoPlayer-base-8.1.1
Affected Modules: app
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download gsyVideoPlayer-x86-8.1.1.aar (com.shuyu:gsyVideoPlayer-x86:8.1.1)
Show Details
Affected Modules: app

## 问题机型/系统：

例如 真机 荣耀V20

## GSY依赖版本

例如 `implementation 'com.shuyu:GSYVideoPlayer:8.1.1'`

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/111253690-9167c480-864e-11eb-8b92-8cf06ba02b3d.png)

如上图所示，可以正常依赖运行

**Comment by CarGuo** [comment]
如下图所示

![image](https://user-images.githubusercontent.com/10770362/111254505-3505a480-8650-11eb-911f-ff9a0d172a1d.png)




我尝试新建了一个项目，也正常依赖运行。

**Comment by SkyD666** [comment]
不知道是不是我的配置问题
repositories {
        google()
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url 'http://4thline.org/m2' }
        // 友盟
        maven { url 'https://dl.bintray.com/umsdk/release' }
    }

**Comment by SkyD666** [comment]
JitPack引入方法没问题，JCenter 引入报错

**Comment by CarGuo** [comment]
我这边试了两种方式都可以依赖，可能网络问题吧～
