### ISSUE TITLE
vivo 手机锁屏再解锁视频黑屏

### ISSUE THREAD

**Issue by Anbinghui** [CarGuo/GSYVideoPlayer#3177]
## 问题描述：

vivo手机,在视频播放过程中锁屏以后再解锁视频黑屏.
需求是视频暂停以后不自动播放,没有在onResume没有调用onVideoResume()
已经设置了setShowPauseCover(true);

## 问题机型/系统：

vivo  IQOO5  V2024A

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:8.1.1'`

## Demo中的复现步骤

Demo 修改SimplePlayer  删除onResume的重写

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
删除onResume的重写？？？？

**Comment by Anbinghui** [comment]
只是删除这句代码  
videoPlayer.onVideoResume();

扣不到数据的情况能设置回调吗,如果可以的话就能让他去显示封面View了

**Comment by CarGuo** [comment]
现在是在 showPauseCover 方法上这样去  mSurface.lockCanvas ，如果你想展示封面，你可能需要参考 Demo 的 SampleCoverVideo ，这样就可以自由操作 mCoverImage

**Comment by Anbinghui** [comment]
好的,感谢大佬,我去尝试一下
