### ISSUE TITLE
列表详情切换时画面静止，只有声音继续播放

### ISSUE THREAD

**Issue by LinPom** [CarGuo/GSYVideoPlayer#3179]
## 问题描述：

官方demo列表详情切换，在列表点击一个视频播放，再点击详情按钮进入详情页，此时画面停止了，只有声音在播放

## 问题机型/系统：

真机 OPPO R7Plusm 5.1.1
或者红米note 4x  6.0、vivo x7  5.1.1、乐视2  6.0（我没有这些机型，别人反馈的）

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## Demo中的复现步骤

Demo中的点击列表详情切换按钮进入 SwitchListVideoActivity，在别的测试机正常，但是在OPPO R7Plusm 5.1.1必现

问题代码：
暂时不知道问题在哪
感觉5.0的系统容易复现这个问题

**Comment by CarGuo** [comment]
不大清楚什么情况，我也没有这些机型，对于 5.0 的机型我这边已经不怎么去支持了

**Comment by LinPom** [comment]
就是demo里的列表详情切换，点进去，在列表里点击一个视频播放，使它处于播放状态，然后点击左边那个详情文字，进入详情页，此时画面静止不动，声音继续播放，5.0的机型不支持，可是红米note 4x 6.0的机型也存在这个问题

**Comment by CarGuo** [comment]
我这边测试了红米的，也没有发现这个问题

**Comment by LinPom** [comment]
好吧，我自己看吧

**Comment by CarGuo** [comment]
这么说吧，有声音没画面主要可能是 surface 没被设置进去，主要是对应的 PlayerManager 的 setDisplay 方法，你可以从这里看起

**Comment by LinPom** [comment]
好的
