### ISSUE TITLE
QQ群北纬90°胡乱踢人，就因为我提了一个内存泄漏问题！！！！ 大家交了5元入群费，就是这样对待群友吗？

### ISSUE THREAD

**Issue by JIanyag** [CarGuo/GSYVideoPlayer#3182]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

QQ群北纬90°胡乱踢人，就因为我提了一个内存泄漏问题！！！！
大家交了5元入群费，就是这样对待群友吗？

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
我加你好友了，你通过下呀

**Comment by JIanyag** [comment]
希望把胡乱踢人的管理员权限卸掉，不然有问题的群友一进去，然后提个问题，然后就把人飞了？我QQ:843180450

**Comment by CarGuo** [comment]
多谢兄弟理解
