### ISSUE TITLE
视频播放结束后，播放器不响应点击事件怎么搞？？？

### ISSUE THREAD

**Issue by q88qaz** [CarGuo/GSYVideoPlayer#3183]
if (mCurrentState == CURRENT_STATE_AUTO_COMPLETE) {
                onClickUiToggle(null);
            }

好家伙直接干没了

**Comment by q88qaz** [comment]
怎么问题没人回答？

**Comment by CarGuo** [comment]
demo 怎么复现问题？？？？不是很明白你需要什么
