### ISSUE TITLE
IjkPlayerManager，用AS自带模拟器播放本地视频报错

### ISSUE THREAD

**Issue by conghuahuadan** [CarGuo/GSYVideoPlayer#3185]
## 问题描述：
IjkPlayerManager，用AS自带模拟器播放本地视频报错
![image](https://user-images.githubusercontent.com/20864280/111874076-712d6200-89ce-11eb-96a9-eab820c9c324.png)

## 问题机型/系统：
AS自带模拟器

## GSY依赖版本
GSYVideoPlayer_8.1.1

问题代码：(如果有)
![image](https://user-images.githubusercontent.com/20864280/111874249-4263bb80-89cf-11eb-9ba9-ef4da8c0c6d1.png)

**Comment by CarGuo** [comment]
没有 scheme 的不支持播放

**Comment by conghuahuadan** [comment]
我觉得可以加下非空判断，这样就能正常播放了
![image](https://user-images.githubusercontent.com/20864280/112106098-2edf6d00-8be8-11eb-9416-70ebc11d9518.png)

**Comment by CarGuo** [comment]
@conghuahuadan  欢迎pr
