### ISSUE TITLE
提交Google play 提示用户安全漏洞  

### ISSUE THREAD

**Issue by pfyuan** [CarGuo/GSYVideoPlayer#3186]
该应用使用的软件含有用户安全漏洞，或允许在没有适当披露的情况下收集用户数据。

以下是您最近提交的问题清单和相应的APK版本。请尽快升级您的应用程序，并递增升级后的APK版本号。
漏洞 APK 版本过期日期
Vitamio

这些漏洞在Vitamio v.5.0和更高版本中得到了修复。你可以在这篇谷歌帮助中心的文章中找到更多信息和下一步的步骤。
 1 2016年3月14日

要确认您已经正确升级，请将您的应用程序的更新版本提交到Play Console，并在五个小时后检查以确保警告消失。

虽然这些漏洞可能不会影响到每一个使用该软件的应用，但最好保持对所有安全补丁的更新。确保更新应用中任何存在已知安全问题的库，即使你不确定这些问题与你的应用相关。
依赖
    implementation 'com.shuyu:gsyVideoPlayer-java:8.1.1'
    //是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:8.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:8.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-arm64:8.1.1'
//
提示让升级Vitamio版本

**Comment by CarGuo** [comment]
Vitamio 不是 gsy 项目的
