### ISSUE TITLE
请问可以实现 两个视频 在一个页面中 同时同进度播放吗？

### ISSUE THREAD

**Issue by Dreamstarring** [CarGuo/GSYVideoPlayer#3188]
## 问题描述：

我这边想实现两个视频同时播放，控制其中一个视频，连一个视频也会产生相应的变化（比如同时暂停，同时开始，播放进度始终一致）。

## 问题机型/系统：

真机 小米11 Android11

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

目前我的方法是在多视频列表播放的Adapter中holder的MultiSampleVideo中，重写回调函数那里去在暂停和开始同步，但是始终会有不到一秒的误差。请问可以实现更为精准的同步播放吗？

**Comment by CarGuo** [comment]
如果是同一个数据源的，然后显示两个画面的，推荐你用 GLSurfaceView 模式，比如 demo 里面的  GSYVideoGLViewCustomRender2 这种，改改就可以了，用 OpenGL 去做两个画面。

如果是两个数据源····就只能说是这样的

**Comment by Dreamstarring** [comment]
好的，谢谢啦！

**Comment by PiPiCaptain** [comment]
@Dreamstarring 兄弟，能发个例子出来吗
