### ISSUE TITLE
列表详情切换产生的bug

### ISSUE THREAD

**Issue by xiaofengff** [CarGuo/GSYVideoPlayer#3189]
#
## 问题描述：

demo里面列表详情切换好像有bug
1.点进去详情的时候画面会卡住声音在继续播放（如果这个时候切到后台再回到播放界面可以继续播放）。
2.从详情页面返回列表后，列表的视频播放直接播放结束。没有和详情的进度接上。

## 问题机型/系统：
 真机 三星s9+

## GSY依赖版本

https://user-images.githubusercontent.com/25995549/112081941-76053800-8bbf-11eb-9d19-5ce93def1bae.mp4

implementation 'com.shuyu:GSYVideoPlayer:8.1.1'

## Demo中的复现步骤

Demo中的列表详情切换会出现这个问题。

**Comment by CarGuo** [comment]
我这边测试了几台机器没有复现

**Comment by LinPom** [comment]
这跟我之前提的bug一模一样，列表详情切换确实存在bug,我之前是5.0的系统，楼主这个三星s9是8.0系统，版本和配置都不低了，我之前调试好像是详情页虽然调用setSurfaceToPlay方法addTextureView();但是列表的播放器执行了onSurfaceDestroyed把Surface清空了，所以画面卡住了；另外SwitchUtil里的sSwitchVideo是静态的，这很容易内存泄漏，用户在列表观看然后跳转到详情再回到列表这是一个很常见的场景，频繁操作几次很容易就OOM了，所以有更好的方式解决列表详情切换吗

**Comment by CarGuo** [comment]
问题是我这边测试了三星，也没出现问题和泄露

**Comment by xiaofengff** [comment]
> 这跟我之前提的bug一模一样，列表详情切换确实存在bug,我之前是5.0的系统，楼主这个三星s9是8.0系统，版本和配置都不低了，我之前调试好像是详情页虽然调用setSurfaceToPlay方法addTextureView();但是列表的播放器执行了onSurfaceDestroyed把Surface清空了，所以画面卡住了；另外SwitchUtil里的sSwitchVideo是静态的，这很容易内存泄漏，用户在列表观看然后跳转到详情再回到列表这是一个很常见的场景，频繁操作几次很容易就OOM了，所以有更好的方式解决列表详情切换吗

我是三星s9+ android10的系统

**Comment by CarGuo** [comment]
不要意思，我知道为什么了，因为我之前测试别的 bug 时，配置了 `GSYVideoType.setRenderType(GSYVideoType.SUFRACE);` ，而 GSYVideoType.SUFRACE 对应的 SurfaceView 模式在不同版本下可能会有不同效果，我刚刚重新提交了 demo ，应该可以了。默认是 TEXTURE 模式。 @xiaofengff
