### ISSUE TITLE
问个问题ijkplayer 如何连续播放多个视频

### ISSUE THREAD

**Issue by tianshaokai** [CarGuo/GSYVideoPlayer#319]
有三个视频地址
1 为广告 且不能拖动
2 为视频
3 还是广告切不能拖动

如何实现这三个视频 地址连续播放 且中间不会出现缓冲呢 并且能监听现在播放的是哪个视频呢

**Comment by CarGuo** [comment]
开启三个管理器管理ijkmediaplay，但是其实两个静音，只在需要的时候有声音。

**Comment by tianshaokai** [comment]
三个ijkmediaplay 好费劲啊

**Comment by tianshaokai** [comment]
你现在做的播放器支持广告播放吗，我看看你怎么做的啊

**Comment by CarGuo** [comment]
广告还没加上，要不就是列表模式播放，先广告狗视频。要不就是两个管理器播放，并不浪费，因为广告播放完了就释放了。

**Comment by tianshaokai** [comment]
你的意思是弄两个player 先缓冲，先start 广告，广告播完了，再start 第二个？？

**Comment by tianshaokai** [comment]
我们的程序 广告的 数量不一致，有可能前边两个广告，视频 最后 还有一个广告

**Comment by CarGuo** [comment]
你只要放一个广告管理器，广告一个接一个顺序加载即刻，一个是播放视频的
