### ISSUE TITLE
How to upgrde ExoPlayer to last version

### ISSUE THREAD

**Issue by ag2s20150909** [CarGuo/GSYVideoPlayer#3191]
def gsy_version = "8.1.1"
    implementation "com.shuyu:gsyVideoPlayer-java:$gsy_version"
    implementation ("com.shuyu:GSYVideoPlayer-exo2:$gsy_version") {exclude (group: "com.google.android.exoplayer")}
    def exo_version = "2.13.2"
    implementation "com.google.android.exoplayer:exoplayer:$exo_version"

我尝试过用上面的方法，但不能正常工作。
I tried the above method, but it didn't work.

**Comment by CarGuo** [comment]
not support exo 2.13.2  yet,   will support in  next version, 2.13 had api broken

**Comment by CarGuo** [comment]
8.1.2 support exo 2.13.2
