### ISSUE TITLE
请问怎么禁止快进?禁止用户拖动屏幕/进度条来改变进度?

### ISSUE THREAD

**Issue by dev-yangyang** [CarGuo/GSYVideoPlayer#3196]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

请问怎么禁止快进?禁止用户拖动屏幕/进度条来改变进度?

## 问题机型/系统：

-

## GSY依赖版本

-

## Demo中的复现步骤

-

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
setIsTouchWiget 和 setIsTouchWigetFull 来控制，如果想单独控制，继承后 override touchSurfaceMove 逻辑
