### ISSUE TITLE
 method SETUP failed: 461 Unsupported transport

### ISSUE THREAD

**Issue by 157356379** [CarGuo/GSYVideoPlayer#3197]
## 问题描述：

播放RTSP 流出现了 method SETUP failed: 461 Unsupported transport

## 问题机型/系统：

例如 友浩车载内屏  安卓5.1

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'
    //是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.0.1'
    //更多ijk的编码支持
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.0.1'

## Demo中的复现步骤

直接连接 就出现这个错误

## 问题log
    SETUP rtsp://192.168.100.107/11/trackID=0 RTSP/1.0
    Transport: RTP/AVP/TCP;unicast;interleaved=0-1
    CSeq: 3
    User-Agent: Lavf57.83.100
```

 E/IJKMEDIA: method SETUP failed: 461 Unsupported transport
 D/IJKMEDIA: CSeq: 3
 E/IJKMEDIA: rtsp://192.168.100.107:554/11: Protocol not supported

```

**Comment by CarGuo** [comment]
？？？？？？？？ 请提供测试url

**Comment by 157356379** [comment]
问题找到了   SETUP rtsp://192.168.100.107/11/trackID=0 RTSP/1.0
Transport: RTP/AVP/UDP;unicast;client_port=31380-31381
CSeq: 3
User-Agent: Lavf57.83.100 

Transport: RTP/AVP/UDP   这里 多了/UDP 用串口调试助手发的  视频源那边返回461 Unsupported transport  去掉就正常  这个是需要改IJK源码吗？
