### ISSUE TITLE
samba2.samba3

### ISSUE THREAD

**Issue by 151058580845** [CarGuo/GSYVideoPlayer#3198]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在播放samba2服务器上的视频时，显示连接不上

## 问题机型/系统：

安卓全部手机/android

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:8.1.1'

## Demo中的复现步骤

samba2和3版本，不能通过smb://进行访问，只能通过\192.168.0.43\共享文件夹1\jiazf\1604543341-videorecord-2020-11-5-10-29-1.mp4，，该网址在浏览器访问可正常播放视频，现在使用ijkplayer播放器，访问这个链接产生的错误是E/IJKMEDIA: \192.168.0.43\共享文件夹1\jiazf\1604543341-videorecord-2020-11-5-10-29-1.mp4: No such file or directory，我该在哪里配置让他能够访问，谢谢

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
smb:// 能不能支持我不记得了，但是  No such file or directory 你确定不是因为中文没有 decode 的问题？？

**Comment by 151058580845** [comment]
我使用浏览器访问，//:可以直接访问并播放视频，但是使用smb://播放不了
![image](https://user-images.githubusercontent.com/53112439/112776194-9cb8e800-9071-11eb-9c22-9c771658f059.png)
，使用smb://的网址，提示smb://admin:password@192.168.0.43/共享文件夹1/jiazf/1604543341-videorecord-2020-11-5-10-29-1.mp4: Connection timed out，我只是想知道有没有方法能配置//访问网址

**Comment by 151058580845** [comment]
这个问题出现在samba2和samba3协议上，因为samba1可以通过smb://访问

**Comment by CarGuo** [comment]
如果是协议没支持，应该是 protocol not found 之类的警告。
然后如果是路径带中文的，需要你记得把中文部分做个 decode

**Comment by 151058580845** [comment]
smb://admin:password@192.168.0.43/home/1604543293-videorecord-2020-11-5-10-28-13.mp4: Connection timed out
\\192.168.0.43\home\1604543293-videorecord-2020-11-5-10-28-13.mp4: No such file or directory
访问的是samba2下的同一个文件，两种访问方式

**Comment by CarGuo** [comment]
这么奇怪····那就是不支持了

**Comment by 151058580845** [comment]
好吧，我在想能不能实现打开文件流进行播放，请问有没有接口可以输入文件流的，不然应该就没法做了这个

**Comment by CarGuo** [comment]
smb 的我这边没特别处理，所以你如果需要可以自己配置支持，配置文件在根目录的两个 sh 文件
