### ISSUE TITLE
android 11 cpu arm64-v8a 初始化时发生崩溃

### ISSUE THREAD

**Issue by huohuoyoyo** [CarGuo/GSYVideoPlayer#3199]
问题描述：

android 11  cpu arm64-v8a 初始化时发生崩溃
 问题机型/系统：

 真机  Redmi K30i 5G， OPPO PDEM10
 android版本 Android 11,level 30

## GSY依赖版本

 implementation 'com.shuyu:GSYVideoPlayer:8.0.0'

![image](https://user-images.githubusercontent.com/12482839/112708268-f7c0d280-8eeb-11eb-9b1e-967d7e110f3d.png)

**Comment by CarGuo** [comment]
请看最新版本

**Comment by huohuoyoyo** [comment]
切换成8.1.1 版本 不能播放 一直在加载中
![image](https://user-images.githubusercontent.com/12482839/112776036-25835400-9071-11eb-9459-89e2bc427cf4.png)

**Comment by CarGuo** [comment]
这个是你 hostnameVerifier 方法传了 null 吧

**Comment by huohuoyoyo** [comment]
只是把项目的依赖版本变成8.1.1&nbsp;其他什么都没变&nbsp; 新版本有不一样的地方吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 上午9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] android 11 cpu arm64-v8a 初始化时发生崩溃 (#3199)





 
这个是你 hostnameVerifier 方法传了 null 吧

**Comment by huohuoyoyo** [comment]
只是用到最基本的模式  布局中添加播放控件  ProxyCacheManager.instance().setHostnameVerifier 这个方法没用用到

**Comment by CarGuo** [comment]
嗯嗯，因为 8.1.1 针对这个做了调整，为了适配 google play，刚好发布了 8.1.2 了 ，不用也不会影响使用，你可以更新下，其实 8.1.0 你也可以用

**Comment by Marx-Hong** [comment]
> 

你好，我也遇到这个问题，但我的是自己编的so（因为GSY的某些格式不支持），现在重新编，Android 11也是会有这个奔溃（/lib/arm64/libijkffmpeg.so (av_application_on_http_event+24)），想请教一下是什么问题引起的，该如何解决，谢谢

**Comment by Marx-Hong** [comment]
> 

你好，我也遇到这个问题，但我的是自己编的so（因为GSY的某些格式不支持），现在重新编，Android 11也是会有这个奔溃（/lib/arm64/libijkffmpeg.so (av_application_on_http_event+24)），想请教一下是什么问题引起的，该如何解决，谢谢

**Comment by CarGuo** [comment]
https://github.com/CarGuo/ijkplayer/commit/e99d640e5fe94c65132379307f92d7180bcde8e7 
@Marx-Hong

**Comment by Marx-Hong** [comment]
谢谢 @CarGuo
