### ISSUE TITLE
onClickStartError()方法

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#32]
当发生错误时，我需要怎样处理，播放器能在错误点重新播放？

**Comment by CarGuo** [comment]
如果错误了，点击的时候会在内部重新播放，在外部需要自动重新播放的话，请参考源码的内部处理，不过不建议在回调里自动重新播放，因为这可能造成死循环。

**Comment by PiPiCaptain** [comment]
@CarGuo 
我现在在外部并没有做任何处理。但点击，却报"播放地址无效"

**Comment by CarGuo** [comment]
到群里吧，然后把具体的问题截图下会好说明一些。
