### ISSUE TITLE
添加弹幕

### ISSUE THREAD

**Issue by ByHSH** [CarGuo/GSYVideoPlayer#320]
在自己的activity里面添加弹幕数据之后如何从横屏状态的播放器里面去显示弹幕呢?现在我一直获取的danmaView都是第一个view而不是横屏之后再次初始化的view,求大佬指点

**Comment by CarGuo** [comment]
demo不是有吗

**Comment by ByHSH** [comment]
我看了demo里面的danmaView在横屏的时候是横屏后初始化的view,但是我用到自己项目的时候需要把我自己的activity里面的一个popwindow的点击事件数据传到播放器,然后我用videoplay.setdanmu(data)(这个是我在videoplay中写的一个方法,传数据到videoplay),然后danmaview去addDanmu的时候还是第一次初始化的danmaview

**Comment by ByHSH** [comment]
大佬,能不能加我QQ767764309?

**Comment by ByHSH** [comment]
或者您给我一个邮箱,我们用邮件交流好么?github上面交流太慢了

**Comment by CarGuo** [comment]
你可以去群里问问看，申请进群。然后这个播放器的理念是继承重写，你可以看看怎么处理。
