### ISSUE TITLE
是否支持PCM格式音频源输入，并与视频做同步

### ISSUE THREAD

**Issue by robinfjb** [CarGuo/GSYVideoPlayer#3200]
## 问题描述：

是否支持PCM格式音频源输入，并与视频做同步

## 问题机型/系统：

HLTE229T

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.1'`

## Demo中的复现步骤

有个需求，视频源数据为rtsp，音频数据则用Audio api采集，此项目是否支持PCM格式音频源输入，并与视频做同步播放

问题代码：(如果有)
```
```

## 问题log（如果有）

```

```

**Comment by CarGuo** [comment]
不支持
