### ISSUE TITLE
使用exo内核的话必须使用IjkExo2MediaPlayer吗？不能使用StandardGSYVideoPlayer？

### ISSUE THREAD

**Issue by yudehai0204** [CarGuo/GSYVideoPlayer#3202]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

使用exo内核 无法播放 dash 流  使用的是StandardGSYVideoPlayer
代码中仅设置

        PlayerFactory.setPlayManager(Exo2PlayerManager().javaClass)
        CacheFactory.setCacheManager(ExoPlayerCacheManager().javaClass)

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
exo内核是 PlayerManager 和  StandardGSYVideoPlayer 没关系，可以用
