### ISSUE TITLE
Android6.0及以下系统机子出现1.5和2.0倍率播放卡顿

### ISSUE THREAD

**Issue by F1ReKing** [CarGuo/GSYVideoPlayer#3203]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

Android6.0及以下系统机子出现1.5和2.0倍率播放卡顿，用的是Exo2内核

## 问题机型/系统：

真机  Android6.0及以下系统的机子

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:8.1.2'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)

用的是setSpeedPlaying

**Comment by CarGuo** [comment]
没得办法得，Exo2 内核用的是 MediaCodec，望安好

**Comment by F1ReKing** [comment]
> 没得办法得，Exo2 内核用的是 MediaCodec，望安好

如果换成ijk内核 会不会不出现这问题

**Comment by CarGuo** [comment]
ijk 的话，你可以自己编译so来调整达到自己的需求
