### ISSUE TITLE
同时播放4-6个视频,如何优化请指点。

### ISSUE THREAD

**Issue by jackpanz** [CarGuo/GSYVideoPlayer#3205]
## 问题描述：

我项目需求一个界面同时播放4-6个视频，视频是正常版本，问题是手机发热量大和流量大。
我怎么可以优化发热量和流量大的问题。

现在用的是IK的模块
 
是流媒体数据

请问是否可以控制播放的帧数？可以提供代码？
怎么控制视频清晰度？可以提供代码？
能控制网络流量吗？可以提供代码？

<img src="https://user-images.githubusercontent.com/8186829/113463550-e41beb80-9458-11eb-8eb0-7eb8598ece0a.jpg" width = "400"  alt="" align=center />

谢谢

## 问题机型/系统：

one plus 7

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.2'`

**Comment by CarGuo** [comment]
这个没啥好说的，同时播放你只能视频本身的降低码率和帧数来维持，本身就是软解码了…

**Comment by jackpanz** [comment]
硬解码 用 PlayerFactory.setPlayManager(SystemPlayerManager.class); 发热量会不会好些

**Comment by zhanglq060** [comment]
这是产品需求问题了，非有这需求，首先视频要压缩控制大小，硬解码，直接exoplayer或系统播放器就行了吧。
还有你们产品和技术不沟通吗，没有实现成本吗，6个视频同时播放，眼珠子不花吗？
