### ISSUE TITLE
DEMO - "列表详情切换"视频播放异常

### ISSUE THREAD

**Issue by GooDong** [CarGuo/GSYVideoPlayer#3207]
## 问题描述：
"列表详情切换"
这个页面内，从列表切换到详情，视频播放异常（画面卡主了）

## 问题机型/系统：

例如 真机 魅族 MX5 5.1

## GSY依赖版本

Demo

## Demo中的复现步骤

Demo中的"列表详情切换"页面有这个问题。

##  日志
[mx5问题日志.txt](https://github.com/CarGuo/GSYVideoPlayer/files/6277639/mx5.txt)

**Comment by CarGuo** [comment]
测试小米11、红米5plus、华为 p30pro、模拟器 正常

**Comment by GooDong** [comment]
> 测试小米11、红米5plus、华为 p30pro、模拟器 正常

马蛋。。。那就是魅族坑我。。

**Comment by QzhangQ** [comment]
> 测试小米11、红米5plus、华为 p30pro、模拟器 正常

低版本的Android系统，就出现了画面卡出的情况

**Comment by CarGuo** [comment]
@QzhangQ  低版本已经不支持了，我这边测试基准最低最低 8.0 起步了
