### ISSUE TITLE
音轨选择

### ISSUE THREAD

**Issue by aaa597636603** [CarGuo/GSYVideoPlayer#3208]
你好作者，请问能添加一个音轨选择功能吗？谢谢

**Comment by CarGuo** [comment]
((IjkMediaPlayer)detailPlayer.getGSYVideoManager().getPlayer().getMediaPlayer()).selectTrack();
        ((IjkExo2MediaPlayer)detailPlayer.getGSYVideoManager().getPlayer().getMediaPlayer()).setTrackSelector();
