### ISSUE TITLE
danikula\videocache' exists but is a directory com.danikula.videocache.ByteArraySource

### ISSUE THREAD

**Issue by ff-frida** [CarGuo/GSYVideoPlayer#3209]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

项目中依赖了implementation 'com.danikula:videocache:2.7.1'
不过是其他模块的，现在项目联合开发中，当我引入了
com.shuyu:GSYVideoPlayer:8.1.2之后编译。
build\intermediates\javac\debug\compileDebugJavaWithJavac\classes\com\danikula\videocache' exists but is a directory
com.danikula.videocache.ByteArraySource
类重复了。全局搜索danikula:videocache中也有这个类而且同名同路径。

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:8.1.2'`

## Demo中的复现步骤

编译即可

问题代码：(如果有)
```
implementation 'com.danikula:videocache:2.7.1'
implementation 'com.shuyu:gsyvideoplayer-androidvideocache:8.1.2'
```

## 问题log（如果有）

```

build\intermediates\javac\debug\compileDebugJavaWithJavac\classes\com\danikula\videocache' exists but is a directory
com.danikula.videocache.ByteArraySource

```
我的疑问：
大佬你好，目前danikula:videocache，是公司其他项目组引入的，我无权修改。也就是无法把danikula:videocache替换成gsy提供的cache模块。
疑问1：gsy提供cache和danikula:videocache有什么区别吗。项目中并没有提供gsy：cache，目前是直接imp依赖的。
疑问2：我现在把danikula:videocache移除，替换gsy的cache编程成功了。（前面提到，我其实无权修改这个依赖的），我应该怎么办呢。有什么建议给我么。

**Comment by CarGuo** [comment]
比如
```
 implementation(dataDependencies.permissionsdispatcher) {
        // if you don't use android.app.Fragment you can exclude support for them
        exclude module: "support-v13"
    }
    ```
    可以用于  exclude module 掉对应的 module

然后 danikula:videocache 里有针对 ssl 的处理，还有 header 等其他方面的修改 ， 这个你可以看看。 最后如果不行，推荐你 fork 代码之后自己发布 maven 或者源码依赖

**Comment by ff-frida** [comment]
感谢回复，这个情况看来只要fork了，前一个项目我就是直接导入源码的。
还有就是com.shuyu:gsyvideoplayer-androidvideocache:8.1.2，这个库，希望大佬把库地址https://github.com/CarGuo/AndroidVideoCache也增加到文档，方便全部源码的寻找。
