### ISSUE TITLE
用LIstVideoUtil播放视频（小窗口播放那种） 快速滑倒其他页，发现视频播放错位

### ISSUE THREAD

**Issue by SiloSong** [CarGuo/GSYVideoPlayer#321]
近期用本项目做一个列表视频播放（有小窗口的），但是，滑动到其他页面，点击播放视频常常出现播放小窗口中正播放的视频，  最后自己在GsyVideoPlayer中添加了
public void setNewUrl(String url){
this.mUrl=url
this.mOriginUrl=url;
}
然后再ListVideoUtil的startPlay(String url) 中开始添加了 gsyVideoPlayer.setNewUrl(url) 就可以了
但是不知道为什么，是和是否有小窗口的判断有关吗？？
这样改有什么坏处吗？是否会影响内存？？

**Comment by CarGuo** [comment]
demo中复现吗？

**Comment by SiloSong** [comment]
是呢，大神，就是传到ListVideoUtils中startplay(String url) 中的url是一个地址， 到最后播放时候是  上一个 视频的 url ,测试好多天了，不知道其原理

**Comment by CarGuo** [comment]
demo中哪个ACtivity有这种问题？

**Comment by SiloSong** [comment]
是在Fragment中，RecyclerView适配的数据

**Comment by CarGuo** [comment]
我的意思是，demo中，对心哪个activity类页面有问题。比如detailplayer，比如ListVideoActivity，这样我好复现
