### ISSUE TITLE
播放rtsp问题

### ISSUE THREAD

**Issue by aglszz** [CarGuo/GSYVideoPlayer#3210]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在activity A播放rtsp视频流时 打开一个新的 activity  B，
A 调用了       
    @Override
    protected void onPause() {
        super.onPause();
        videoPlayer.onVideoPause();
    }

B 关闭后   A 调用  
 @Override
    protected void onResume() {
        super.onResume();
        videoPlayer.onVideoResume();
    }
mCurrentState开始变化  先是 CURRENT_STATE_PAUSE 
然后 变 CURRENT_STATE_PLAYING  在之后 变 CURRENT_STATE_AUTO_COMPLETE

最后是6  自动播放结束    应该是播放中才对    
这边  播放的是  监控摄像头的rtsp视频  不应该存在 自动播放结束才对  
跟源码  mCurrentState 变为2  之后onAutoCompletion  这个方法把 mCurrentState 设置成了6
 @Override
    public void onAutoCompletion() {
        setStateAndUi(CURRENT_STATE_AUTO_COMPLETE);

        mSaveChangeViewTIme = 0;
        mCurrentPosition = 0;

        if (mTextureViewContainer.getChildCount() > 0) {
            mTextureViewContainer.removeAllViews();
        }

        if (!mIfCurrentIsFullscreen)
            getGSYVideoManager().setLastListener(null);
        mAudioManager.abandonAudioFocus(onAudioFocusChangeListener);
        if (mContext instanceof Activity) {
            try {
                ((Activity) mContext).getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        releaseNetWorkState();

        if (mVideoAllCallBack != null && isCurrentMediaListener()) {
            Debuger.printfLog("onAutoComplete");
            mVideoAllCallBack.onAutoComplete(mOriginUrl, mTitle, this);
        }
        mHadPlay = false;
    }
![image](https://user-images.githubusercontent.com/27655065/114844354-4e476f80-9e0d-11eb-9c51-d02d24317021.png)

## 问题机型/系统：

Android7.0

## GSY依赖版本
    implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:8.1.0'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:8.1.0'

## Demo中的复现步骤

无

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
onAutoCompletion 说明断开链接结束了
