### ISSUE TITLE
如何实现双指放大视频的功能

### ISSUE THREAD

**Issue by SkyD666** [CarGuo/GSYVideoPlayer#3213]
## 问题描述：

如何实现双指放大视频的功能，类似于bilibili

## GSY依赖版本

例如 `com.shuyu:GSYVideoPlayer:8.1.0'`

**Comment by CarGuo** [comment]
你看底层的 GSYTextureRenderView ，你可以继承后修改 getTextureParams 方法或者 changeTextureViewShowType 等，其实就是 View 的放大。
