### ISSUE TITLE
继承StandardGSYVideoPlayer类，自定义的监听切横屏变null了

### ISSUE THREAD

**Issue by zp0511** [CarGuo/GSYVideoPlayer#3215]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

继承StandardGSYVideoPlayer，在类中自定义了个回调接口，当屏幕切换为横屏时，该回调被置为null了，再次切换竖屏可以正常监听。

## 问题机型/系统：

真机 小米6

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.2'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
cloneParams  \ resolveNormalVideoShow \ startWindowFullscreen ，看这三个方法在 StandardGSYVideoPlayer 的实现

还有可以关注下 player.getCurrentPlayer 的使用
