### ISSUE TITLE
调用 getGSYVideoManager().pause() 后  mCurrentState 的值还是 CURRENT_STATE_PLAYING状态，此时 mCurrentState 的值 不应该为 CURRENT_STATE_PAUSE状态吗？

### ISSUE THREAD

**Issue by manbuxingkong** [CarGuo/GSYVideoPlayer#3217]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

调用 getGSYVideoManager().pause() 后  mCurrentState 的值还是 CURRENT_STATE_PLAYING状态

## 问题机型/系统：

真机 华为P30  Android 9.0

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.3-jitpack'

## Demo中的复现步骤

SampleCoverVideo 类中添加 mTextureViewContainer 控件的点击监听

问题代码：(如果有)
 mTextureViewContainer.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (getGSYVideoManager().isPlaying()) {
                    getGSYVideoManager().pause();
             
                } else {
                    getGSYVideoManager().start();
           
                }
            }
        });
## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不是很理解什么问题

**Comment by manbuxingkong** [comment]
就是调用 getGSYVideoManager().pause()后在 updateStartImage() 函数中 mCurrentState 还是在播放中的状态 ，但是我已经调用暂停了

**Comment by CarGuo** [comment]
你的 GSYVideoView 里的 onVideoPause  没走？？ 除非是  CURRENT_STATE_PREPAREING

**Comment by manbuxingkong** [comment]
我在 onVideoPause函数打断点，没有走这个函数，我也奇怪调用getGSYVideoManager().pause()后为啥不回调这个函数

**Comment by manbuxingkong** [comment]
我从这打的断点
![微信图片_20210427170435](https://user-images.githubusercontent.com/33081035/116216375-23e5a280-a77b-11eb-82d7-fbb5f5a5aa4b.png)

**Comment by CarGuo** [comment]
我这边测试正常

**Comment by manbuxingkong** [comment]
我是在提供的demo里这样修改的
您可以试一下我这个代码
 mTextureViewContainer.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (getGSYVideoManager().isPlaying()) {
                    getGSYVideoManager().pause();
                } else {
                    getGSYVideoManager().start();
                }
            }
        });

![微信图片_20210427173631](https://user-images.githubusercontent.com/33081035/116220340-2a761900-a77f-11eb-9dd5-5205b4e5de64.png)

**Comment by manbuxingkong** [comment]
还是说我不能这样操作，我现在需求是和抖音的播放逻辑一致，点击暂停，再次点击开始

**Comment by CarGuo** [comment]
touchSurfaceDown \ touchSurfaceMove \ touchSurfaceUp \ onClickUiToggle \ touchDoubleUp \ touchLongPress 我觉得 override 这些方法应该满足你的需求吧？

**Comment by manbuxingkong** [comment]
我试试，感谢
