### ISSUE TITLE
视频播放  怎么关闭视频本身的旋转属性 

### ISSUE THREAD

**Issue by zzcoo** [CarGuo/GSYVideoPlayer#3218]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不是很理解你的问题，不过你需要的可以继承后 override onInfo 方法，在  what == getGSYVideoManager().getRotateInfoFlag()

**Comment by zzcoo** [comment]
修改mRotate 0或者180 不生效，视频画面还是上下颠倒的
@Override
    public void onInfo(int what, int extra) {
        if (what == getGSYVideoManager().getRotateInfoFlag()) {
            mRotate = 0;
            if (mTextureView != null) {
                mTextureView.setRotation(mRotate);
                LogUtils.i("onInfo getRotation:"+mTextureView.getRotation());
            }
        }else {
            super.onInfo(what,extra);
        }
    }

**Comment by CarGuo** [comment]
有参数 URL 没有
