### ISSUE TITLE
网络异常时卡顿崩溃

### ISSUE THREAD

**Issue by darrennight** [CarGuo/GSYVideoPlayer#3220]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

没有网络时毕现(wifi先但是路由器没有网络)，会导致卡顿崩溃

## 问题机型/系统：

试了好几款手机都有此问题

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

4-21 15:00:40.879  1488  5415 D ColorEapUtils:   native: #37 pc 000000000043e8ec  /apex/com.android.runtime/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at tv.danmaku.ijk.media.player.IjkMediaPlayer._release(Native method)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at tv.danmaku.ijk.media.player.IjkMediaPlayer.release(IjkMediaPlayer.java:704)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.release(IjkPlayerManager.java:185)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:573)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at android.os.Handler.dispatchMessage(Handler.java:107)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at android.os.Looper.loop(Looper.java:238)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at android.app.ActivityThread.main(ActivityThread.java:7864)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at java.lang.reflect.Method.invoke(Native method)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-21 15:00:40.879  1488  5415 D ColorEapUtils:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)
04-21 15:00:40.881  1488  1703 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1071 com.android.server.am.OppoExtraActivityManagerService.setKeyLockModeNormal:53 com.android.server.am.ActivityManagerService.killAppAtUsersRequest:10097 com.android.server.am.AppErrors.handleShowAnrUi:948 com.android.server.am.ActivityManagerService$UiHandler.handleMessage:1769

**Comment by CarGuo** [comment]
暂时没有复线，建议把 cache 设置为 false 测试，或者切换到 exo 模式内涵

**Comment by darrennight** [comment]
我这边只要网络出问题，这个问题基本是必现的，我再找下原因吧

**Comment by CarGuo** [comment]
先看下是不是 proxycache 引起的，把 cache 设置为 false  可以排除
然后看起来像是 release 的时候出现问题，那可以关注 releae 相关的位置
