### ISSUE TITLE
StandardVideoPlayer 全面屏情况下如何设置蒙层

### ISSUE THREAD

**Issue by yangmingchuan** [CarGuo/GSYVideoPlayer#3223]
看了以往的issues 没有发现和我一样的问题，需求：全面屏的情况下 显示一个继续播放  分享 转发之类的蒙层，隐藏掉 window里边的其他的 view。 我修改了smample_video中的布局，在外部添加了一个 蒙层View，我在监听onAutoComplete（）回调的时候 设置 ControlVideo 显示蒙层但是没有效果，请问谁遇到过这个情况怎么处理 和 顺利的绑定时间。半屏的蒙层我已经添加成功了

**Comment by cl9211** [comment]
你这个问题解决了吗？全屏设置蒙层不显示
