### ISSUE TITLE
镜像问题

### ISSUE THREAD

**Issue by aglszz** [CarGuo/GSYVideoPlayer#3225]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

如何实现镜像  rtsp流   播放就是镜像之后的画面   

## 问题机型/系统：

Android7.0

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:8.1.0'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:8.1.0'

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
使用   GSYVideoType.setRenderType(GSYVideoType.GLSURFACE); ，参考  DetailFilterActivity ，自定义你的 Effect
