### ISSUE TITLE
如何保存播放中的视频流

### ISSUE THREAD

**Issue by jmloveyou** [CarGuo/GSYVideoPlayer#3227]
## 问题描述：

XXXX发生了这样的问题！
我现在需要选择保存直播中的一个时间段内的视频，但是没有数据接口开放出来。可以给个建议吗？

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.16'`

**Comment by CarGuo** [comment]
不支持
