### ISSUE TITLE
编译自定义SO不支持RTSP地址切换问题

### ISSUE THREAD

**Issue by Movement123** [CarGuo/GSYVideoPlayer#3230]
## 问题描述：
大佬好，为了降低RTSP拉流的延时问题，所以我使用 [ex_so支持的视频编码和音频编码配置文件](https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh) ，编译出修改FFPENG源码自定义so，但是不能支持RTSP播放地址切换，报错：Server returned 404 Not Found
而使用[您项目中ex_so下的文件](https://github.com/CarGuo/GSYVideoPlayer/tree/master/gsyVideoPlayer-ex_so/libs/armeabi-v7a)，是可以正常切换RTSP地址的，[而且看您之前也遇到了类似问题](https://github.com/CarGuo/GSYVideoPlayer/issues/766)，所以想请教一下您的解决办法。

## 问题机型/系统：
基于Android 9.0  API 29 车机系统

**Comment by CarGuo** [comment]
你是不是用的不是 ijk 的现阶段 master 分支？我有点忘记我改过什么了，太久了····

**Comment by Movement123** [comment]
git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-android
cd ijkplayer-android
git checkout -B latest k0.8.8

./init-android.sh

cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

cd ..
./compile-ijk.sh all


我是用现在ijk官方给的编译方式编的。请问您还记得修改这种问题，是只需要改.sh文件就可以，还是也要对应修改ffmpeng的源码？

**Comment by CarGuo** [comment]
git checkout -B latest k0.8.8 去掉，现在 android11 上有个严重问题，需要用 master 才能修复，另外 sh 是改过，其他的还真不大记得了。
对了 master 的上面是 ffmpeg 4 了好像

**Comment by Movement123** [comment]
> git checkout -B latest k0.8.8 去掉，现在 android11 上有个严重问题，需要用 master 才能修复，另外 sh 是改过，其他的还真不大记得了。
> 对了 master 的上面是 ffmpeg 4 了好像

多谢大佬指点，可以切换了
