### ISSUE TITLE
怎么记录视频播放位置

### ISSUE THREAD

**Issue by lutao2599** [CarGuo/GSYVideoPlayer#3231]
大佬，请问怎么记录视频播放位置呢？下次进入可以续播

**Comment by CarGuo** [comment]
自己记，框架不存的

**Comment by lutao2599** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuyu ***@***.***&gt;; 
发送时间: 2021年4月26日(星期一) 下午5:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CarGuo/GSYVideoPlayer] 怎么记录视频播放位置 (#3231)





 
自己记，框架不存的，只提供 setSeekOnStart
