### ISSUE TITLE
暂停后再进行大小屏切换，会出现黑屏

### ISSUE THREAD

**Issue by F1ReKing** [CarGuo/GSYVideoPlayer#3234]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

同一个播放界面，暂停后再进行大小屏切换，会出现黑屏，希望能停留在暂停的最后一帧

## 问题机型/系统：

三星S9+ Android10

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## Demo中的复现步骤

问题代码：(如果有)

## 问题log（如果有）
 D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
 D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
 D/IJKMEDIA: ffpipeline_set_surface()
 D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
 W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
 D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
 D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffa4b620)
 D/IJKMEDIA: ffpipeline_set_surface()
 D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffa4b620)=void

正常播放时切换的日志是：
D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffa4bb40)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0xffa4bb40)=void
D/IJKMEDIA: ANativeWindow_setBuffersGeometry: w=1920, h=1080, f=(0x1) => w=640, h=360, f=RV32(0x32335652)

```

**Comment by CarGuo** [comment]
setShowPauseCover

**Comment by F1ReKing** [comment]
> setShowPauseCover

这个方法写入时机要放在哪，我有写了，没效果

**Comment by CarGuo** [comment]
一般是播放前， setRenderType 是默认的 TEXTURE 么？

**Comment by F1ReKing** [comment]
我目前也设置在播放钱，setRenderType用的是TEXTURE

Shuyu Guo ***@***.***> 于2021年4月28日周三 上午11:58写道：

**Comment by CarGuo** [comment]
https://user-images.githubusercontent.com/10770362/116344893-a886fe00-a819-11eb-880c-d1c5d8029d26.mp4

如上视频所示

**Comment by F1ReKing** [comment]
最终排查跟踪源码解决了，用了GsyVideoManager.instance().pause()去暂停视频播放，导致mCurrentState状态是没有赋值更新的，所以到showPauseCover判断就走不下去，最终采用Player对象去暂停就可以了

**Comment by CarGuo** [comment]
good ～
