### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by sangsais** [CarGuo/GSYVideoPlayer#3236]
## 问题机型/系统：

例如 真机 vivo Android10

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## 问题log（如果有）

E/IJKMEDIA:/storage/emulated/0/Android/data/com.xx.xx/files/video/1619613262234.mp4: No such file or directory

GSYVideoPlayer: Play Error /storage/emulated/0/Android/data/com.xx.xx/files/video/1619613262234.mp4

**Comment by ag2s20150909** [comment]
`android:requestLegacyExternalStorage="true"`

**Comment by CarGuo** [comment]
如果 file:// 不能用了，就用 content 打开，比如：

```
       intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType("video/*");
        startActivityForResult(intent, READ_REQUEST_CODE);
```
