### ISSUE TITLE
列表里播放视频滑出屏幕会卡顿

### ISSUE THREAD

**Issue by RainwalkerDean** [CarGuo/GSYVideoPlayer#3239]
## 问题描述：

在列表里中先播放item的video，当该item滑出屏幕范围，调用GSYVideoManager.releaseAllVideos()，列表会卡顿一下，列表fling下明显。提供的demo也有这样的问题

## 问题机型/系统：

荣耀v20 AndroidQ

## GSY依赖版本

`v8.1.3-jitpack`

**Comment by CarGuo** [comment]
看下历史issue
