### ISSUE TITLE
为什么播放页面继承了FragmentActivity崩溃

### ISSUE THREAD

**Issue by pricnehao** [CarGuo/GSYVideoPlayer#324]
集成FragmentActivity之后点击全屏崩溃

**Comment by CarGuo** [comment]
看Demo

**Comment by pricnehao** [comment]
好的 谢谢 对了  这个LandLayoutVideo 如何做到进入详情页就自动播放 我在进入的时候就调用startPlayLogic()方法 第一次会自动播放   但是下次再次进入 就不会自动播放了

**Comment by CarGuo** [comment]
不是很理解

**Comment by pricnehao** [comment]
就是进入一个页面 就开始播放    而不是进入点击播放  而且这个页面视频下面有其他布局

**Comment by CarGuo** [comment]
我理解应该就是像demo的playActivity

**Comment by pricnehao** [comment]
嗯嗯对的 但是不能用playActivity的那个组件  因为那样放大   下面的布局也会跟着转方向
