### ISSUE TITLE
多视频url在同一播放器里，分段播放，请问怎么处理

### ISSUE THREAD

**Issue by plmmanwu** [CarGuo/GSYVideoPlayer#3243]
现有多个视频地址，本质是一个连贯视频的分段，想在同一播放器里，拼成完整视频播放，请问怎么处理？只要效果达到就行

**Comment by ag2s20150909** [comment]
使用Exoplayer的ConcatenatingMediaSource concatenatedSource =
    new ConcatenatingMediaSource(firstSource, secondSource，...);
