### ISSUE TITLE
seekTo出现问题

### ISSUE THREAD

**Issue by Dreamstarring** [CarGuo/GSYVideoPlayer#3248]
## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

真机 小米11 Android11

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

想实现视频的短时快进和后退（即每次向前或者向后移动0.5s），我先get到了currentPosition,然后在此基础上加0.5s在用seekTo进行跳转。会有部分跳转出现一直显示同一帧的情况，显示的这一帧是当前时间之后的一帧，只有在多次快进到这一帧所在时间之后，才会恢复快进帧变化效果。请问是不是和关键帧有关系，可以有办法解决这样的问题吗？（我用的是ExoPlayer的内核，播放的视频是DASH格式）

**Comment by CarGuo** [comment]
Exo 的没有什么解决办法了，调整视频关键帧吧
