### ISSUE TITLE
请教一下，显示当前网络速度，要怎么做？

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#325]
如题。。。

**Comment by CarGuo** [comment]
有可以获取速度的接口，但是具体怎么实现需要你自己做

**Comment by PiPiCaptain** [comment]
@CarGuo 就是具体怎么实现，不是很清楚，能不能给个思路？

**Comment by CarGuo** [comment]
你具体业务需求是怎么样的？

**Comment by PiPiCaptain** [comment]
@CarGuo 就是在播放界面上，显示当前的网络速度，就只需要显示

**Comment by CarGuo** [comment]
最简单的，就是定时器，不过群里有人实现过，叫yyyy1iang，其实有很多种实现方式，这个挺简单的，你可以问问他吧。

**Comment by PiPiCaptain** [comment]
@CarGuo 嗯，解决了，谢谢

**Comment by PiPiCaptain** [comment]
@CarGuo 还有一个小问题，竖屏时没问题。但全屏时，我加个TextView就不显示了，全屏时，怎么处理？

**Comment by CarGuo** [comment]
参考全屏方法，重写

**Comment by PiPiCaptain** [comment]
@CarGuo 没找到文档或Demo

**Comment by CarGuo** [comment]
你调用全屏的那个方法，看一下他内部实现和注释你就知道了

**Comment by PiPiCaptain** [comment]
@CarGuo 完美解决，谢谢

**Comment by yang0000meng** [comment]
@PiPiCaptain 显示当前网络速度 怎么实现的，大侠能给出关键代码吗
