### ISSUE TITLE
使用exo播放HDR视频在有些设备上颜色会有问题，有办法先传SurfaceView，再初始化播放器吗。

### ISSUE THREAD

**Issue by leeManong** [CarGuo/GSYVideoPlayer#3255]
## 问题描述：

exo经过我的测试，只有在初始化的时候，同时设置setVideoSurface(),播放HDR视频时颜色就是正常的。
现在库的代码逻辑，IjkExo2MediaPlayer里setSurface()是在prepareAsyncInternal()后调用的，也就是播放器初始化准备好播放才设置的setVideoSurface()。
那么有办法可以先把SurfaceView传过去，然后prepareAsyncInternal()时直接setVideoSurfaceView(surfaceView)吗。

## 问题机型/系统：

使用的是小米盒子3

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.3-jitpack'

**Comment by leeManong** [comment]
已解决onPlayerInitSuccess()是早于prepareAsyncInternal()的。

**Comment by wanan666** [comment]
大神可以详细说说怎么解决hdr颜色不对的问题的吗

**Comment by leeManong** [comment]
> 大神可以详细说说怎么解决hdr颜色不对的问题的吗

留个邮箱 我发断代码给你。

**Comment by wanan666** [comment]
> > 大神可以详细说说怎么解决hdr颜色不对的问题的吗
> 
> 留个邮箱 我发断代码给你。

1753554887@qq.com,谢谢！

**Comment by Equalzys** [comment]
> > 大神可以详细说说怎么解决hdr颜色不对的问题的吗
> 
> 留个邮箱 我发断代码给你。

大佬，我也遇到颜色不正确了，能给个代码参考下吗？215766856@qq.com

**Comment by kyriej** [comment]
大佬同求一份代码

**Comment by wanan666** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 晚上11:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CarGuo/GSYVideoPlayer] 使用exo播放HDR视频在有些设备上颜色会有问题，有办法先传SurfaceView，再初始化播放器吗。 (#3255)




 
大佬同求一份代码

**Comment by zczcyc0201** [comment]
可以发我一份代码吗？遇到这个问题不知道如何解决，谢谢

**Comment by zczcyc0201** [comment]
zczcyc0201@126.com 这是我的邮箱 谢谢大佬

**Comment by leeManong** [comment]
> 可以发我一份代码吗？遇到这个问题不知道如何解决，谢谢

我是通过继承GSYVideoView，在getGSYVideoManager()方法中添加监听。
private boolean initVideoManager = false;
    @Override
    public GSYVideoViewBridge getGSYVideoManager() {
        if (!initVideoManager) {
            GSYVideoManager.instance().initContext(getContext().getApplicationContext());
            GSYVideoManager.instance().setPlayerInitSuccessListener(new IPlayerInitSuccessListener() {
                @Override
                public void onPlayerInitSuccess(IMediaPlayer player, GSYModel model) {
                     //这里判断是exo后，手动setSurfaceView
                    if (GSYVideoManager.instance().getPlayer() instanceof CustomExoPlayerManager) {
                        CustomExoPlayerManager playerManager = (CustomExoPlayerManager) GSYVideoManager.instance().getPlayer();
                        playerManager.setSurfaceView((GSYSurfaceView) mTextureView.getShowView());
                    }
                }
            });
            initVideoManager = true;
        }
        return GSYVideoManager.instance();
    }

**Comment by wanan666** [comment]
你邮箱多少



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月17日(周三) 晚上6:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CarGuo/GSYVideoPlayer] 使用exo播放HDR视频在有些设备上颜色会有问题，有办法先传SurfaceView，再初始化播放器吗。 (#3255)




  
可以发我一份代码吗？遇到这个问题不知道如何解决，谢谢
  
我是通过继承GSYVideoView，在getGSYVideoManager()方法中添加监听。
 private boolean initVideoManager = false;
 @OverRide
 public GSYVideoViewBridge getGSYVideoManager() {
 if (!initVideoManager) {
 GSYVideoManager.instance().initContext(getContext().getApplicationContext());
 GSYVideoManager.instance().setPlayerInitSuccessListener(new IPlayerInitSuccessListener() {
 @OverRide
 public void onPlayerInitSuccess(IMediaPlayer player, GSYModel model) {
 //这里判断是exo后，手动setSurfaceView
 if (GSYVideoManager.instance().getPlayer() instanceof CustomExoPlayerManager) {
 CustomExoPlayerManager playerManager = (CustomExoPlayerManager) GSYVideoManager.instance().getPlayer();
 playerManager.setSurfaceView((GSYSurfaceView) mTextureView.getShowView());
 }
 }
 });
 initVideoManager = true;
 }
 return GSYVideoManager.instance();
 }

**Comment by zczcyc0201** [comment]
> 你邮箱多少
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年5月17日(周三) 晚上6:40 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [CarGuo/GSYVideoPlayer] 使用exo播放HDR视频在有些设备上颜色会有问题，有办法先传SurfaceView，再初始化播放器吗。 (#3255) 可以发我一份代码吗？遇到这个问题不知道如何解决，谢谢 我是通过继承GSYVideoView，在getGSYVideoManager()方法中添加监听。 private boolean initVideoManager = false; @OverRide public GSYVideoViewBridge getGSYVideoManager() { if (!initVideoManager) { GSYVideoManager.instance().initContext(getContext().getApplicationContext()); GSYVideoManager.instance().setPlayerInitSuccessListener(new IPlayerInitSuccessListener() { @OverRide public void onPlayerInitSuccess(IMediaPlayer player, GSYModel model) { //这里判断是exo后，手动setSurfaceView if (GSYVideoManager.instance().getPlayer() instanceof CustomExoPlayerManager) { CustomExoPlayerManager playerManager = (CustomExoPlayerManager) GSYVideoManager.instance().getPlayer(); playerManager.setSurfaceView((GSYSurfaceView) mTextureView.getShowView()); } } }); initVideoManager = true; } return GSYVideoManager.instance(); } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

[zczcyc0201@126.com](mailto:zczcyc0201@126.com) 这是我的邮箱 谢谢大佬

**Comment by yangdong123** [comment]
> > 大神可以详细说说怎么解决hdr颜色不对的问题的吗
> 
> 留个邮箱 我发断代码给你。

347156807@qq.com 感谢
