### ISSUE TITLE
数据库冲突问题

### ISSUE THREAD

**Issue by 2523955396** [CarGuo/GSYVideoPlayer#3256]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我做了一个播放记录功能，使用的sqlite数据库，但是我发现在运行的过程中gsy播放器也会生成一个数据库，里面含有视频链接地址，但是这个数据库的存在让我的存储功能存储不了，我的逻辑是每500毫秒打开数据库然后存储进度，存储完后关闭。但是现在是有些时候可以存，存一段时间再用软件就存不了了，所以我不知道怎么处理这个，麻烦大佬说下办法

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
proxycache 里的逻辑是用于缓存视频的，你可以看看 DatabaseSourceInfoStorage

**Comment by 2523955396** [comment]
我用print.out每500毫秒获取播放器进度的时候会是0，但是开始的时候是对的，后面就不知道怎么获取就是0了，我写的逻辑是播放器进度大于1的时候数据库开始获取播放记录

**Comment by 2523955396** [comment]
大佬还在?

**Comment by CarGuo** [comment]
具体这类问题你自己调试呀，我这边没有代码没办法盲猜
