### ISSUE TITLE
打包的时候出现Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'. > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: tv/danmaku/ijk/media/player/annotations/AccessedByNative.class

### ISSUE THREAD

**Issue by yuanchenghao** [CarGuo/GSYVideoPlayer#326]

**Comment by CarGuo** [comment]
请提供下你的依赖gradle代码？

**Comment by yuanchenghao** [comment]
compile 'com.shuyu:GSYVideoPlayer:2.0.2'  就在主工程里加的这个 还需要别的么？

**Comment by yuanchenghao** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"
    dexOptions {
        jumboMode true
    }
    defaultConfig {
        applicationId "com.huxiangkeji.zhizhaoapp"
        minSdkVersion 17
        targetSdkVersion 24
        multiDexEnabled true
        versionCode 19
        versionName "1.5.8"
        ndk {
//            abiFilters 'armeabi', 'armeabi-v7a', 'armeabi-v8a', 'x86', 'x86_64', 'mips', 'mips64'
            abiFilters 'armeabi', 'armeabi-v7a', 'armeabi-v8a', 'x86'
        }

    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    signingConfigs {
        debug {
            storeFile file('yewen.jks')
            storePassword "123456"
            keyAlias "yewen"
            keyPassword "123456"
        }
    }
}


repositories {
    flatDir {
        dirs 'libs'
    }
    maven {
        url 'https://dl.bintray.com/wangyuwei/maven'
    }
}



dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.android.support:design:23.+'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.orangegangsters:swipy:1.2.3@aar'
    compile 'io.github.openfeign:feign-gson:9.3.1'
    compile 'com.jakewharton:butterknife:5.1.1'
    compile files('libs/SocialSDK_WeiXin_1.jar')
    compile 'cn.jiguang:jpush:2.1.8'
    compile 'com.jakewharton:butterknife:5.1.1'
    compile files('src/main/libs/afinal_0.5_bin.jar')
    compile files('libs/pldroid-rtc-streaming-1.0.1.jar')
    compile 'com.qiniu:happy-dns:0.2.8'
    compile 'com.qiniu.pili:pili-android-qos:0.8.13'
    compile files('libs/pldroid-player-1.3.2.jar')
    compile files('libs/pldroid-rtc-streaming-1.0.1.jar')
    compile 'com.android.support:multidex:1.0.1'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.4'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4'
    testCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4'
    compile files('libs/hyphenatechat_3.2.2.jar')
    compile files('libs/MobCommons-2016.1107.1809.jar')
    compile files('libs/SocialSDK_QQZone_3.jar')
    compile project(':bDIntegrationSDK_LibProject')
    compile files('libs/qiniu-android-sdk-7.3.2.jar')
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.squareup.okio:okio:1.11.0'
    compile 'com.library.tangxiaolv:telegramgallery:1.0.2'
    compile 'com.android.support:design:24.+'
    compile 'com.github.LuckSiege.PictureSelector:picture_library:v1.2.4'
    compile 'com.google.android.gms:play-services-appindexing:8.4.0'
    compile files('libs/universal-image-loader-1.9.4-with-sources.jar')
    compile files('libs/SocialSDK_WeiXin_2.jar')
    compile project(':splashview')
    compile project(':mnvideoplayerlibrary')
    compile 'com.umeng.analytics:analytics:latest.integration'
    compile files('libs/xUtils-2.6.14.jar')
    compile 'com.github.codbking:PickTime:v1.0.1'
    compile 'com.youth.banner:banner:1.4.9'
    compile 'com.commit451:PhotoView:1.2.4'
    compile 'com.zhy:okhttputils:2.6.2'
    compile 'com.shizhefei:ViewPagerIndicator:1.1.6'
    compile 'com.shuyu:GSYVideoPlayer:2.0.2'
}

**Comment by CarGuo** [comment]
你引用的mediaplayer有些多啊，你确定他们是不是也使用了ijkplayer并且版本不一样…

**Comment by yuanchenghao** [comment]
其他的没有用到ijkplayer  我这里有七牛直播的东西  我看看七牛

**Comment by yuanchenghao** [comment]
我知道了 是和七牛的冲突了 那我该怎么解决？我不知道七牛的ijkplayer 是什么版本

**Comment by CarGuo** [comment]
你可以看AS左下角，project模式下的 EXternal LIbraries。那里会走，其中0.8.1是gsy的

**Comment by yuanchenghao** [comment]
![Uploading image.png…]()
![qq 20170717142519](https://user-images.githubusercontent.com/15939940/28257273-0a18bf3c-6afc-11e7-8569-c4ea9421b9bd.png)
是引用的ijk不一样 怎么搞呢？

**Comment by CarGuo** [comment]
你的第一张图片挂了……

**Comment by yuanchenghao** [comment]
![image](https://user-images.githubusercontent.com/15939940/28257362-c0cbdca0-6afc-11e7-9dfc-8938b28300d6.png)

**Comment by yuanchenghao** [comment]
这个是七牛的 引用  删不掉  我怎么能忽略掉一个

**Comment by CarGuo** [comment]
虽然可以通过gradle过滤掉，但是过滤可能掉会导致七牛挂了。这个只能看你怎么取舍了，或者你可以看看github首页gsy的版本更新列表，找找对应的版本。或者clone源码，修改ijk版本。

**Comment by CarGuo** [comment]
问题集锦中有一个链接，跳转到简书的，和gradle相关，说过滤的。

**Comment by CarGuo** [comment]
excluded的调group

**Comment by yuanchenghao** [comment]
恩 我看看 我先过滤一下 试试两个都好不好使 不行就得clone 源码了

**Comment by yuanchenghao** [comment]
我的天   七牛的是ijk 0.4.3.12  是不是这两个里用到的ijk版本一致就能打包了？

**Comment by yuanchenghao** [comment]
过滤的话不行 他们的ijk升到0.7.4这个了  我不知道如果版本一致可不可以打包

**Comment by CarGuo** [comment]
4.3的……太老了…这个其实需要so和java版本一致，只升级java是不行的

**Comment by yuanchenghao** [comment]
好吧 谢谢大神了 他们着急要 我换一个播放器吧  我觉得我以后还会用到这个的  nice
