### ISSUE TITLE
全屏时断开wifi的UI不显示

### ISSUE THREAD

**Issue by zp0511** [CarGuo/GSYVideoPlayer#3260]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

大佬，麻烦问下。在自定义布局文件中，新增了WIFI断开连接时的UI。切换为全屏播放时，监听到WIFI断开时，要显示自定义断开wifi的UI，但是没有显示，是需要在哪里添加处理吗？类似于腾讯视频观看视频时，wifi断开了的提示。

## 问题机型/系统：

 真机 小米6

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
player.getCurrentPlayer 

另外看 

cloneParams 

startWindowFullscreen

这几个方法
