### ISSUE TITLE
更换到8.8.1 到播放界面就报空指针

### ISSUE THREAD

**Issue by pfyuan** [CarGuo/GSYVideoPlayer#3267]
这边ProxyCacheManager 报NullPointerException  
b.b.a.m.a(Preconditions.java:1)
2
b.b.a.g$b.a(HttpProxyCacheServer.java:6)
3
com.shuyu.gsyvideoplayer.e.c.a(ProxyCacheManager.java:26)
4
com.shuyu.gsyvideoplayer.e.c.b(ProxyCacheManager.java:3)
5
com.shuyu.gsyvideoplayer.e.c.b(ProxyCacheManager.java:4)
6
com.shuyu.gsyvideoplayer.e.c.cachePreview(ProxyCacheManager.java:1)
7
com.shuyu.gsyvideoplayer.b.cachePreview(GSYVideoBaseManager.java:2)
8
com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.isShowNetConfirm(GSYVideoControlView.java:2)
9
com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.clickStartIcon(GSYVideoControlView.java:25)
10
com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.onClick(GSYVideoControlView.java:5)
11
android.view.View.performClick(View.java:7870)
12
android.view.View.performClickInternal(View.java:7839)
13
android.view.View.access$3600(View.java:886)
14
android.view.View$PerformClick.run(View.java:29363)
15
android.os.Handler.handleCallback(Handler.java:883)
16
android.os.Handler.dispatchMessage(Handler.java:100)
17
android.os.Looper.loop(Looper.java:237)
18
android.app.ActivityThread.main(ActivityThread.java:7814)
19
java.lang.reflect.Method.invoke(Native Method)
20
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
21
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by CarGuo** [comment]
参考 demo ，demo 没出现问题，具体原因你自己查了
