### ISSUE TITLE
列表自动播放问题

### ISSUE THREAD

**Issue by pz-bottle** [CarGuo/GSYVideoPlayer#3268]
视频自动播放列表时，用的是demo中的自动播放工具，但是当我第一次进入列表页面时，如果第一个选项是视频不会自动播放，当滑动列表时，自动播放选项的工具不灵敏，滑到相应视频位置时不会自动播放。请问大佬这个问题有好的方案吗？

**Comment by CarGuo** [comment]
自动播放列表是在 demo 里，你自己修改就行了～具体你直接调整源码里的逻辑就行了
