### ISSUE TITLE
请教下如下报错是什么问题？

### ISSUE THREAD

**Issue by One28Piece** [CarGuo/GSYVideoPlayer#327]
播放器出现闪退，控制台报如下错误
java.lang.IllegalStateException: mpjni: start: null mp
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._start(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.start(IjkMediaPlayer.java:517)

**Comment by CarGuo** [comment]
播放器的so出现的异常崩溃了

**Comment by One28Piece** [comment]
是so文件的问题吗？最近出现的有点频繁，要如何处理？

**Comment by CarGuo** [comment]
之前也找过，没必先，不知道哪里出现了问题，咨询了ijk，他们也不确定…你用的是2.0.2吧？

**Comment by One28Piece** [comment]
用的是1.6.9

**Comment by One28Piece** [comment]
前几个版本也有遇到过这个问题，但是比较少，1.6.9出现的次数比较多，看控制台好像就是播放器的onVideoResume()那里出现的问题

**Comment by CarGuo** [comment]
可以看到外部已经判空了，但是内部还是null了，可以试试2.0.2的

**Comment by One28Piece** [comment]
好的，还有一个问题就是1.6.9的buffer状态需要手动点击才能触发，之前版本不需要手动点击
