### ISSUE TITLE
本地raw视频黑屏，无法播放，没有声音和画面，Demo的EmptyControlVideo也无法播放

### ISSUE THREAD

**Issue by li-xiaojun** [CarGuo/GSYVideoPlayer#3272]
## 问题描述：

本地raw视频黑屏，无法播放，没有声音和画面，Demo的EmptyControlVideo也无法播放
## 问题机型/系统：

华为mate20 android10

## GSY依赖版本

8.1.3
VideoView代码如下，直接拷贝的EmptyControlVideo
```
class NoControlVideoView : StandardGSYVideoPlayer {
    constructor(context: Context?, fullFlag: Boolean?) : super(context, fullFlag) {}
    constructor(context: Context?) : super(context) {}
    constructor(context: Context?, attrs: AttributeSet?) : super(context, attrs) {}

    override fun getLayoutId(): Int {
        return R.layout.empty_control_video
    }

    override fun touchSurfaceMoveFullLogic(absDeltaX: Float, absDeltaY: Float) {
        super.touchSurfaceMoveFullLogic(absDeltaX, absDeltaY)
        //不给触摸快进，如果需要，屏蔽下方代码即可
        mChangePosition = false

        //不给触摸音量，如果需要，屏蔽下方代码即可
        mChangeVolume = false

        //不给触摸亮度，如果需要，屏蔽下方代码即可
        mBrightness = false
    }

    protected fun touchDoubleUp() {
        //super.touchDoubleUp();
        //不需要双击暂停
    }
}
```
```
GSYVideoManager.instance().enableRawPlay(this)
videoView.setUp("android.resource://" + packageName + "/" + R.raw.unlogin, true, "")
videoView.startPlayLogic()
```

## 问题log（如果有）

```
E/IJKMEDIA: pipe:123: Invalid data found when processing input
 E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

```

**Comment by CarGuo** [comment]
//String url = "android.resource://" + getPackageName() + "/" + R.raw.test;
        //注意，用ijk模式播放raw视频，这个必须打开
        //GSYVideoManager.instance().enableRawPlay(getApplicationContext());

        ///exo 播放 raw
        //String url = "rawresource://" + getPackageName() + "/" + R.raw.test;

        ///exo raw 支持
        //String url =  RawResourceDataSource.buildRawResourceUri(R.raw.test).toString();

        //断网自动重新链接，url前接上ijkhttphook:
        //String url = "ijkhttphook:https://res.exexm.com/cw_145225549855002";

**Comment by li-xiaojun** [comment]
这就关了？我是照着的写的，demo的EmptyControlVideo也无法播放的

**Comment by CarGuo** [comment]
https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
