### ISSUE TITLE
如何源视频的尺寸？根据视频尺寸要显示隐藏一些东西，例如全屏按钮

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#3274]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

如何源视频的尺寸？根据视频尺寸要显示隐藏一些东西，例如全屏按钮

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
？？？

**Comment by renwfy** [comment]
就是当时正在播放的视频的尺寸，视频的宽高

**Comment by renwfy** [comment]
不好意思，标题少了几个字……

如何获取源视频的尺寸？根据视频尺寸要显示隐藏一些东西，例如全屏按钮

**Comment by CarGuo** [comment]
getCurrentVideoWidth 、 getCurrentVideoHeight、 getVideoSarNum、getVideoSarDen
