### ISSUE TITLE
m3u8格式播放不支持缓存吗？

### ISSUE THREAD

**Issue by mxdldev** [CarGuo/GSYVideoPlayer#3277]
缓存不支持m3u8\HLS，播放m3u8\HLS格式，需要cacheWithPlay为false
setUp(String url, boolean cacheWithPlay····)

经过测试如果cacheWithPlay设置为true，的确不能播放，能升级下吗？谢谢

**Comment by CarGuo** [comment]
用 exo 内核
PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
