### ISSUE TITLE
播放本地mp4文件，视频时长比较短的时候拖动进度条，立即会直接播放结束

### ISSUE THREAD

**Issue by shouPol** [CarGuo/GSYVideoPlayer#3278]
## 问题描述：

播放本地mp4文件，视频时长比较短，10多秒这样的。拖动进度条，立即会直接播放结束。不动进度条可以正常播放完成，只要拨动进度条，不管是往前还是往后，放开手后下一秒就直接完成了

## GSY依赖版本 
 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.14'`

**Comment by CarGuo** [comment]
关键帧问题，使用 [seek](https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md#6为什么拖动视屏会弹回来因为ijk的ffmpeg对关键帧问题)  解决或者切换到 exo 内核测试

**Comment by shouPol** [comment]
感谢大佬！经过大佬指点，有两种方式进行处理。如果ijk，加上下面（1）这段设置，这个设置只针对ijk内核。如果还不行的话换成exo内核，见（2）：
（1）ijk内核，在视频播放前加上此段设置使用精确seek
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

（2）在播放前切换成exo内核
 PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
