### ISSUE TITLE
视频快进问题

### ISSUE THREAD

**Issue by chuxiaokeAndroid** [CarGuo/GSYVideoPlayer#3279]
视频播放中，已播放2分钟。快进了三分钟，又播放了1分钟。请问有方法可以获取真正播放的时间吗，不算快进时间

**Comment by CarGuo** [comment]
player.getCurrentPlayer(). getGSYVideoManager().getCurrentPosition()

**Comment by chuxiaokeAndroid** [comment]
收到 ，多谢郭老师
