### ISSUE TITLE
Exo 内核播放 mp4，起播速度很慢，请问如何设置 Exo 的开始播放时的缓冲大小。

### ISSUE THREAD

**Issue by ssyijiu** [CarGuo/GSYVideoPlayer#3280]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

Exo 内核播放 mp4 的时候，起播延迟非常大，有将近 2000+ms，我们在浏览器测试了播放链接，其中从网络请求开始，到第一个 206 请求大概有 500ms，但是播放器的状态从 PREPAREING 到 PLAYING 有 1500ms，有的时候甚至会 2000ms，怀疑是播放器每次分片请求的数据过大导致，请问这个可以设置吗？

## 问题机型/系统：

Vivo S6

## GSY依赖版本

7.1.5

## Demo中的复现步骤

Demo 没问题。

问题代码：(如果有)
无

## 问题log（如果有）

```
HomeVideoPlayer: time = 1622791446579, state = 0
HomeVideoPlayer: time = 1622791447315, state = 1     // PREPAREING
HomeVideoPlayer: time = 1622791448629, state = 2   // PLAYING


HomeVideoPlayer: time = 1622791526160, state = 0
HomeVideoPlayer: time = 1622791527842, state = 1  // PREPAREING
HomeVideoPlayer: time = 1622791529251, state = 2  // PLAYING
```

**Comment by CarGuo** [comment]
我记得用 IjkExo2MediaPlayer 的 setLoadControl 可以，比如


        /*GSYVideoManager.instance().setPlayerInitSuccessListener(new IPlayerInitSuccessListener() {
            ///播放器初始化成果回调
            @Override
            public void onPlayerInitSuccess(IMediaPlayer player, GSYModel model) {
                if (player instanceof IjkExo2MediaPlayer) {
                    ((IjkExo2MediaPlayer) player).setTrackSelector(new DefaultTrackSelector());
                    ((IjkExo2MediaPlayer) player).setLoadControl(new DefaultLoadControl());
                }
            }
        });*/
