### ISSUE TITLE
m3u8格式的视频  播放  拖拽进度条会加载很长时间  加载成功了后还可能会跳动到其他位置

### ISSUE THREAD

**Issue by zp0511** [CarGuo/GSYVideoPlayer#3281]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

大佬 麻烦问下  m3u8格式的视频  播放  拖拽进度条会加载很长时间  加载成功了后还可能会跳动到其他位置  这个有什么好的解决方案吗

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:v8.1.3-jitpack'`

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请看问题集锦，或切换到 exo 的内核模式
