### ISSUE TITLE
调用onVideoPause()默认会执行seek(0)的问题

### ISSUE THREAD

**Issue by sanjinmr** [CarGuo/GSYVideoPlayer#3282]
## 复现步骤

只要调用onVideoPause()，必定会导致seek(0)

## 问题log：
D/IJKMEDIA: IjkMediaPlayer_seekTo
D/IJKMEDIA: ijkmp_seek_to(0)
D/IJKMEDIA: ijkmp_seek_to(0)=0

**Comment by CarGuo** [comment]
请提供测试链接

**Comment by sanjinmr** [comment]
最近加班比较忙。周末给你提供哈-------- 原始邮件 --------发件人： Shuyu Guo ***@***.***>日期： 2021年6月8日周二 下午1:40收件人： CarGuo/GSYVideoPlayer ***@***.***>抄送： SanJin ***@***.***>, Author ***@***.***>主    题： Re: [CarGuo/GSYVideoPlayer] 调用onVideoPause()默认会执行seek(0)的问题 (#3282)

请提供测试链接

**Comment by CarGuo** [comment]
closed no reply
