### ISSUE TITLE
播放时画面是否可以铺满全屏

### ISSUE THREAD

**Issue by darrennight** [CarGuo/GSYVideoPlayer#3288]
请问是否可以像短视频播放列表那样
竖向视频播放时画面是否可以铺满全屏
横向视频正常显示

**Comment by CarGuo** [comment]
//GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);
        //GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);
        //GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);

        //GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_CUSTOM);
        //GSYVideoType.setScreenScaleRatio(9.0f/16);


再没有适合的，你可以参考 Demo 使用 CustomRenderView 去自定义
