### ISSUE TITLE
倍速播放 之后 音调变高怎么解决? 想做到不变调

### ISSUE THREAD

**Issue by hongyang51** [CarGuo/GSYVideoPlayer#329]
倍速播放 之后 音调变了怎么解决? 想做到不变调

**Comment by CarGuo** [comment]
speed的时候，有另外一个可以设置打开的参数

**Comment by CarGuo** [comment]
setSpeed(float speed, boolean soundTouch)  true

**Comment by hongyang51** [comment]
66666 多谢厉害了! 我看ijk都看傻了快 我说这soundTouch 在哪里开启 还去调一堆参数 晕死了 原来 这有个开关 谢谢   @CarGuo
