### ISSUE TITLE
无法清除缓存

### ISSUE THREAD

**Issue by zhangmengjia** [CarGuo/GSYVideoPlayer#3290]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 提问前建议先看看： https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q

 问题描述：

  无法清除缓存  在onDestroy中调用清除缓存，但是在内存SD卡 —— android —— data —— 应用报名下 —— cache ——
 video-cache下仍能看到视频缓存

问题机型/系统：

荣耀v10  BKL-AL20

 GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.3-jitpack

## Demo中的复现步骤

问题代码：(如果有)
 GSYVideoManager.instance().clearAllDefaultCache(this)

**Comment by CarGuo** [comment]
我这边测试正常，你debug下是为什么呗

**Comment by zhangmengjia** [comment]
> 我这边测试正常，你debug下是为什么呗

请问您是怎么测的，demo上清除缓存后，是对应的目录下没有相应的视频了么?  还是说使用GSYVideoManager.instance().clearAllDefaultCache(this)  需要什么特别的设置？

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/121624274-cf388580-caa3-11eb-9f3c-ec55f6ee254c.png)

![image](https://user-images.githubusercontent.com/10770362/121624293-d6f82a00-caa3-11eb-96e7-6790ba23e20b.png)


就是 demo 点 Clear Cache 后，缓存就没了呀····然后看缓存接口和 api 都执行了新的 cache 操作，试了几次不管是 .download 和 mp4 都正常清除了，并且下次重新下载

具体你那里为什么还有，就要去看你的 debug 了

**Comment by zhangmengjia** [comment]
> ![image](https://user-images.githubusercontent.com/10770362/121624274-cf388580-caa3-11eb-9f3c-ec55f6ee254c.png)
> 
> ![image](https://user-images.githubusercontent.com/10770362/121624293-d6f82a00-caa3-11eb-96e7-6790ba23e20b.png)
> 
> 就是 demo 点 Clear Cache 后，缓存就没了呀····然后看缓存接口和 api 都执行了新的 cache 操作，试了几次不管是 .download 和 mp4 都正常清除了，并且下次重新下载
> 
> 具体你那里为什么还有，就要去看你的 debug 了
您是否真机测过呢？点击清除缓存，去设置里查看或者去对应目录下查看？

**Comment by zhangmengjia** [comment]
> > ![image](https://user-images.githubusercontent.com/10770362/121624274-cf388580-caa3-11eb-9f3c-ec55f6ee254c.png)
> > ![image](https://user-images.githubusercontent.com/10770362/121624293-d6f82a00-caa3-11eb-96e7-6790ba23e20b.png)
> > 就是 demo 点 Clear Cache 后，缓存就没了呀····然后看缓存接口和 api 都执行了新的 cache 操作，试了几次不管是 .download 和 mp4 都正常清除了，并且下次重新下载
> > 具体你那里为什么还有，就要去看你的 debug 了
> > 您是否真机测过呢？点击清除缓存，去设置里查看或者去对应目录下查看？

 public static void deleteFiles(File root) {
        File[] files = root.listFiles();
        if (files != null) {
            File[] var2 = files;
            int var3 = files.length;

            for(int var4 = 0; var4 < var3; ++var4) {
                File f = var2[var4];
                if (!f.isDirectory() && f.exists()) {
                    try {
                        f.delete();
                    } catch (Exception var7) {
                        var7.printStackTrace();
                    }
                }
            }
        }

    }
在我的荣耀测试机上 debug root.listFiles() 返回的是null

**Comment by zhangmengjia** [comment]
> > > ![image](https://user-images.githubusercontent.com/10770362/121624274-cf388580-caa3-11eb-9f3c-ec55f6ee254c.png)
> > > ![image](https://user-images.githubusercontent.com/10770362/121624293-d6f82a00-caa3-11eb-96e7-6790ba23e20b.png)
> > > 就是 demo 点 Clear Cache 后，缓存就没了呀····然后看缓存接口和 api 都执行了新的 cache 操作，试了几次不管是 .download 和 mp4 都正常清除了，并且下次重新下载
> > > 具体你那里为什么还有，就要去看你的 debug 了
> > > 您是否真机测过呢？点击清除缓存，去设置里查看或者去对应目录下查看？
> 
> public static void deleteFiles(File root) {
> File[] files = root.listFiles();
> if (files != null) {
> File[] var2 = files;
> int var3 = files.length;
> 
> ```
>         for(int var4 = 0; var4 < var3; ++var4) {
>             File f = var2[var4];
>             if (!f.isDirectory() && f.exists()) {
>                 try {
>                     f.delete();
>                 } catch (Exception var7) {
>                     var7.printStackTrace();
>                 }
>             }
>         }
>     }
> 
> }
> ```
> 
> 在我的荣耀测试机上 debug root.listFiles() 返回的是null

感觉是在荣耀测试机上缓存的目录和删除的目录不一致导致的

**Comment by CarGuo** [comment]
所以说不大清楚是什么情况

**Comment by zhangmengjia** [comment]
> 所以说不大清楚是什么情况

这不算是个bug么

**Comment by CarGuo** [comment]
我用demo测试了小米，华为，三星，都正常

**Comment by zhangmengjia** [comment]
> 我用demo测试了小米，华为，三星，都正常…所以你需要用demo测试为什么，怎么导致的，我才能知道怎么去调root.listFiles()

root.listFiles() 返回的是null  不是已经说明问题了么？删除的时候这个目录下并没有找到缓存的视频文件。。

**Comment by CarGuo** [comment]
问题在于，为什么呢？你用的也是 demo ，然后点了 demo 最底部的 clear cache ？？？ 我这边测试没出现问题，所以你要看下为什么没有，而缓存到哪里了？

**Comment by CarGuo** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/10770362/121648700-5dbffd80-caca-11eb-9691-cf11f3f32fbf.png">

<img width="827" alt="image" src="https://user-images.githubusercontent.com/10770362/121648780-729c9100-caca-11eb-8388-5923d638b4ca.png">

![image](https://user-images.githubusercontent.com/10770362/121648795-76c8ae80-caca-11eb-85c4-aa4d01806df5.png)


如上图，测试正常，荣耀

**Comment by zhangmengjia** [comment]
> > ![image](https://user-images.githubusercontent.com/10770362/121624274-cf388580-caa3-11eb-9f3c-ec55f6ee254c.png)
> > ![image](https://user-images.githubusercontent.com/10770362/121624293-d6f82a00-caa3-11eb-96e7-6790ba23e20b.png)
> > 就是 demo 点 Clear Cache 后，缓存就没了呀····然后看缓存接口和 api 都执行了新的 cache 操作，试了几次不管是 .download 和 mp4 都正常清除了，并且下次重新下载
> > 具体你那里为什么还有，就要去看你的 debug 了
> > 您是否真机测过呢？点击清除缓存，去设置里查看或者去对应目录下查看？
我debug看一下

> <img alt="image" width="807" src="https://user-images.githubusercontent.com/10770362/121648700-5dbffd80-caca-11eb-9691-cf11f3f32fbf.png">
> 
> <img alt="image" width="827" src="https://user-images.githubusercontent.com/10770362/121648780-729c9100-caca-11eb-8388-5923d638b4ca.png">
> 
> ![image](https://user-images.githubusercontent.com/10770362/121648795-76c8ae80-caca-11eb-85c4-aa4d01806df5.png)
> 
> 如上图，测试正常，荣耀

/data/user/0/com.example.gsyvideoplayer/cache/video-cache    默认的缓存路径，可是删除的时候返回null,查看手机文件管理在/data/user/0这个路径下，却没有com.example.gsyvideoplayer

**Comment by zhangmengjia** [comment]
> > > ![image](https://user-images.githubusercontent.com/10770362/121624274-cf388580-caa3-11eb-9f3c-ec55f6ee254c.png)
> > > ![image](https://user-images.githubusercontent.com/10770362/121624293-d6f82a00-caa3-11eb-96e7-6790ba23e20b.png)
> > > 就是 demo 点 Clear Cache 后，缓存就没了呀····然后看缓存接口和 api 都执行了新的 cache 操作，试了几次不管是 .download 和 mp4 都正常清除了，并且下次重新下载
> > > 具体你那里为什么还有，就要去看你的 debug 了
> > > 您是否真机测过呢？点击清除缓存，去设置里查看或者去对应目录下查看？
> > > 我debug看一下
> 
> > <img alt="image" width="807" src="https://user-images.githubusercontent.com/10770362/121648700-5dbffd80-caca-11eb-9691-cf11f3f32fbf.png">
> > <img alt="image" width="827" src="https://user-images.githubusercontent.com/10770362/121648780-729c9100-caca-11eb-8388-5923d638b4ca.png">
> > ![image](https://user-images.githubusercontent.com/10770362/121648795-76c8ae80-caca-11eb-85c4-aa4d01806df5.png)
> > 如上图，测试正常，荣耀
> 
> /data/user/0/com.example.gsyvideoplayer/cache/video-cache 默认的缓存路径，可是删除的时候返回null,查看手机文件管理在/data/user/0这个路径下，却没有com.example.gsyvideoplayer

确实删除不了，我这边不知道怎么上传图片，只能说下机型  荣耀v10  型号：BKL-AL20  android 版本：10   运行内存：6.0  
处理器：HiSilicon Kirin 970  屏幕 2160*1080

**Comment by zhangmengjia** [comment]
抱歉 我这边的问题
