### ISSUE TITLE
返回桌面再返回播放页面偶尔会重置

### ISSUE THREAD

**Issue by qq837890739** [CarGuo/GSYVideoPlayer#3292]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在播放页面点击暂停后或者直接Home键返回桌面，过一段时间再返回播放页，视频控件还是暂停状态没有重新播放，再点击播放按钮的时候会重头开始播放。挺容易重现的。

## 问题机型/系统：

一加7pro，Android 11 

## GSY依赖版本

例如 `com.shuyu:GSYVideoPlayer:8.1.2'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by qq837890739** [comment]
我看到有个老哥提了onVideoPause（）会seek（0）的问题，这个问题会不会也是onVideoPause（）引起的？

**Comment by qq837890739** [comment]
必现：在自己的app播放视频，再打开腾讯视频播放视频或者QQ音乐播放音乐，然后再回到自己的app

**Comment by qq837890739** [comment]
2021-06-10 19:30:01.704 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x70df5f9be0)
2021-06-10 19:30:01.704 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x70df5fb020)
2021-06-10 19:30:01.704 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x70df5f96d0)
报了这个错，应该是因为腾讯视频也是用的ijk的问题

**Comment by CarGuo** [comment]
腾讯视频播放视频或者QQ音乐播放音乐 肯定会重置啊，有一个叫 setReleaseWhenLossAudio 的方法····
