### ISSUE TITLE
StandardGSYVideoPlayer播放rtsp没有声音，so库以支持格式以及音频格式。

### ISSUE THREAD

**Issue by zhu528** [CarGuo/GSYVideoPlayer#3293]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我用StandardGSYVideoPlayer播放rtsp没有声音，用多任务播放器就会有声音。我自己重定义so库，以支持当前音频格式pcm_alaw。

## 问题机型/系统：

例如 真机 realme Android10

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.6'`

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不理解

**Comment by zhu528** [comment]
用demo中的播放器StandardGSYVideoPlayer或者是sampleVideo播放rtsp没有声音只有画面，但是我用demo中的多任务播放器播放rtsp流就有声音。

**Comment by zhu528** [comment]
so库我是重新定义，以支持rtsp和当前流的pcm_alaw音频格式。

**Comment by CarGuo** [comment]
不明白，我这边测试正常

**Comment by CarGuo** [comment]
closed no reply
