### ISSUE TITLE
关于代码问题

### ISSUE THREAD

**Issue by zhangmengjia** [CarGuo/GSYVideoPlayer#3294]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

普遍问题！

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.3-jitpack

## Demo中的复现步骤

问题代码：(如果有)
 
通过implementation依赖的库 ExoMediaSourceInterceptListener和你demo中的方法不一样，是否代码未更新？在我的集成项目中 清除缓存无效，demo有效的，不知道是不是和ExoMediaSourceInterceptListener有关系，我看了下代码，现在就application里面不一样，我是直接通过code下载的代码，运行的demo

## 问题log（如果有）

xxxxxxx

```

**Comment by CarGuo** [comment]
demo 里的新版本还没有发布

**Comment by zhangmengjia** [comment]
> demo 里的新版本还没有发布

ExoMediaSourceInterceptListener  这个接口的改动，和缓存清除有关系么？

**Comment by CarGuo** [comment]
这个是exo的，和默认proxy没关系

**Comment by zhangmengjia** [comment]
> 这个是exo的，和默认proxy没关系

咨询下您，我这边清除缓存无效，应该如何排查集成方面的问题？

**Comment by CarGuo** [comment]
排查下文件缓存的目录是否正确
然后排查下清除的目录和缓存的目录是否一致
最后看下清除不了是因为权限问题还是路径问题或者是系统兼容问题

**Comment by zhangmengjia** [comment]
> 排查下文件缓存的目录是否正确
> 然后排查下清除的目录和缓存的目录是否一致
> 最后看下清除不了是因为权限问题还是路径问题或者是系统兼容问题

缓存目录：/data/user/0/包名/cache/video-cache   删除目录：/storage/emulated/0/android/data/包名/cache/video-cache   目录不一致，但是我这边并没有指定目录，我用demo测试是可以的，就在自己的项目清除不了，这大概是什么原因呢？

**Comment by zhangmengjia** [comment]
> > 排查下文件缓存的目录是否正确
> > 然后排查下清除的目录和缓存的目录是否一致
> > 最后看下清除不了是因为权限问题还是路径问题或者是系统兼容问题
> 
> 缓存目录：/data/user/0/包名/cache/video-cache 删除目录：/storage/emulated/0/android/data/包名/cache/video-cache 目录不一致，但是我这边并没有指定目录，我用demo测试是可以的，就在自己的项目清除不了，这大概是什么原因呢？

缓存： this.cacheRoot = StorageUtils.getIndividualCacheDirectory(context);//这个应该是缓存的路径吧
删除： String path = StorageUtils.getIndividualCacheDirectory(context.getApplicationContext()).getAbsolutePath();

**Comment by zhangmengjia** [comment]
您好，这个目录不一致问题是您这边代码有改动，还是我这边配置有问题

**Comment by CarGuo** [comment]
demo 关于这一块，最近还真的没改动过
难道是 targetSDK 版本不同导致的？

你可以跟踪下 StorageUtils 的 getCacheDirectory  这个方法，是不是 demo 和 你的 app 获取出现不一样的路径

**Comment by zhangmengjia** [comment]
好的  再咨询您个问题，如何只让视频宽度拉满屏幕？

**Comment by CarGuo** [comment]
参考demo 可以自定义 CustomRenderView ，你可以自己调整  onMeasure

**Comment by zhangmengjia** [comment]
同样依赖的是 com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.3-jitpack，问什么demo和我的项目中对应的类，方法不太一样？
我的项目代码：
![企业微信截图_16238139314716](https://user-images.githubusercontent.com/20176275/122153443-96c6ec00-ce95-11eb-9704-1982b5688f7c.png)

demo项目中代码：
![企业微信截图_16238149863453](https://user-images.githubusercontent.com/20176275/122154682-15bd2400-ce98-11eb-9332-d5dcb4057ed0.png)

这是因为jcenter 原因么？这个jcenter 我去了也不行

**Comment by CarGuo** [comment]
Build.VERSION_CODES.P 就是 28 啊·····

**Comment by zhangmengjia** [comment]
![企业微信截图_16238272451830](https://user-images.githubusercontent.com/20176275/122173792-b8839b80-ceb4-11eb-875a-97f60c51fb76.png)  为什么demo返回的是null，我的app返回的不是null?这个是我这边有什么操作导致的么？

**Comment by CarGuo** [comment]
这里应该是我的问题了，属于历史遗留问题，我改改

**Comment by CarGuo** [comment]
fix release v8.1.5-jitpack
