### ISSUE TITLE
横屏全屏切换问题

### ISSUE THREAD

**Issue by LoveToEatGrapes** [CarGuo/GSYVideoPlayer#3295]
## 问题描述：

横屏视频列表，全屏播放后，无法切回横屏列表样式，只能切换成竖屏列表的样式。

## 问题机型/系统：

真机 OPPO  k3

## GSY依赖版本

'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.3-jitpack'

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/3114
