### ISSUE TITLE
切换exo内核后调用startplaylogic不会自动开始播放

### ISSUE THREAD

**Issue by wenwenwenzq** [CarGuo/GSYVideoPlayer#3297]
问题描述：
切换exo内核后调用startplaylogic视频不会播放，需要手动双击才可以播放

GSY依赖版本
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack

Demo中的复现步骤
    PlayerFactory.setPlayManager(Exo2PlayerManager.class);
 videoPlayer.startPlayLogic();     

问题代码
IjkExo2MediaPlayer.java第590行
  
  585 switch (playbackState) {
  586    case Player.STATE_BUFFERING:
           587 notifyOnInfo(IMediaPlayer.MEDIA_INFO_BUFFERING_START, buffer);
          588          isBuffering = true;
            589        break;
      590          case Player.STATE_READY:
           591         break;

解决方法
在ijkExo2MediaPlayer.java第590行后加入两句            
 585 switch (playbackState) {
            586    case Player.STATE_BUFFERING:
          587          notifyOnInfo(IMediaPlayer.MEDIA_INFO_BUFFERING_START, buffer);
          588          isBuffering = true;
           589         break;
           590     case Player.STATE_READY:
     591               **notifyOnPrepared()**;
     592                **start();**
        593            break;

**Comment by wenwenwenzq** [comment]
可能安卓studio分行了显示是590行，github中是是563行

**Comment by CarGuo** [comment]
怎么复现？我 demo 这边测试正常啊

**Comment by wenwenwenzq** [comment]
我找到问题了原因是我自己在395行附近加了几行代码，原本是来解决播放ts文件进度问题，但是后来加了个audioattributes导致获得了音频焦点视频自动暂停了，**删除我自己添加的加粗的代码就好了**
// 这段代码用来解决播放ts进度问题
 final DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory()
                                .setTsExtractorTimestampSearchBytes(1500 * TsExtractor.TS_PACKET_SIZE);                    
   mInternalPlayer = new SimpleExoPlayer.Builder(mAppContext, mRendererFactory,extractorsFactory)
                                .setLooper(Looper.myLooper())
                                .setTrackSelector(mTrackSelector)
                                .setLoadControl(mLoadControl).build();



  **final AudioAttributes audioAttributes = new AudioAttributes.Builder()
                         .setUsage(C.USAGE_MEDIA)
                        .setContentType(C.CONTENT_TYPE_MOVIE)
                         .build();
 mInternalPlayer.setAudioAttributes(audioAttributes, true);**
