### ISSUE TITLE
setUp()方法

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#33]
![5ab8f3fc-4590-4d83-9aca-709262ce54ee](https://cloud.githubusercontent.com/assets/22672329/21710370/16dbbb5e-d423-11e6-803e-6ed0776153cf.png)
如上图，我在setUp()方法里，加了一些我自己的业务进去。这些业务在播放器竖屏下是没有问题的，但点击全屏时，这些业务不见了。我需要做什么处理？

**Comment by CarGuo** [comment]
重载startWindowFullscreen放大，参看StandardGSYVideoPlayer或者ListGSYVideoPlayer等的重载方法下的处理，wiki上也说了，第六条[播放器的使用](https://github.com/CarGuo/GSYVideoPlayer/wiki/播放器使用)
