### ISSUE TITLE
监听快进或者快退

### ISSUE THREAD

**Issue by chuxiaokeAndroid** [CarGuo/GSYVideoPlayer#3300]
继承StandardGSYVideoPlayer， @Override
    public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {

    }
    @Override
    public void onStartTrackingTouch(SeekBar seekBar) {
    }

    @Override
    public void onStopTrackingTouch(SeekBar seekBar) {
    }这个三个方法不会走？？？？是用错方法了吗

**Comment by chuxiaokeAndroid** [comment]
我想监听快进或者快退了多长时间

**Comment by CarGuo** [comment]
这三个方法是 seekbar 的，还有触摸的

**Comment by chuxiaokeAndroid** [comment]
还有一个问题：我拖动进度条快进，然后一下子又回到我拖动之前的进度了，没有变化。这是咋回事

**Comment by CarGuo** [comment]
看问题集锦

**Comment by chuxiaokeAndroid** [comment]
public class GSYVideoPlayer extends StandardGSYVideoPlayer {

    public GSYVideoPlayer(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

    public GSYVideoPlayer(Context context) {
        super(context);
    }

    public GSYVideoPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public int getLayoutId() {
        return R.layout.video_layout_standard;
    }

    @Override
    protected void init(Context context) {
        super.init(context);
    }

    @Override
    public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
        LogUtil.e("播放进度========="+progress);
    }

    @Override
    public void onStartTrackingTouch(SeekBar seekBar) {
        LogUtil.e("播放进度---------"+seekBar.getProgress());
    }

    @Override
    public void onStopTrackingTouch(SeekBar seekBar) {
        LogUtil.e("播放进度！！！！！！！！！！" + seekBar.getProgress());
    }
}
这三个方法，我快进快退的时候，没走。求解

**Comment by chuxiaokeAndroid** [comment]
当触摸屏幕快进时 onProgressChanged这个方法的SeekBar seekBar, int progress, 这两个输出和实际快进多长时间不一致。。这是咋回事

**Comment by CarGuo** [comment]
未能理解你的描述😂
