### ISSUE TITLE
播放器起播的代码有个小的问题点

### ISSUE THREAD

**Issue by zkywalker** [CarGuo/GSYVideoPlayer#3301]
![image](https://user-images.githubusercontent.com/11813277/122532947-9aa06d00-d053-11eb-8ea3-577a0fa1eaf6.png)
我理解这个if代码是用来处理异常情况的，如果今日这个条件判断会触发准备=》然后handler异步准备完会调用start，条件判断外又直接调用了start，这个case应该会多次调用播放器的start方法，但是不确定会不会有问题。startAfterPrepared这个方法内同样还有这个问题

**Comment by CarGuo** [comment]
放心，问题不大

**Comment by zkywalker** [comment]
确实问题不大，正常是不会走这个if的，哪怕走了底下也try了。需要改下吗，我提个pr？
