### ISSUE TITLE
ExoPlayer无缝播放，其中有视频无音频

### ISSUE THREAD

**Issue by KAICW** [CarGuo/GSYVideoPlayer#3304]
## 问题描述：

使用自定义的ExoPlayer，实现无缝切换下一集功能，如果其中一个视频没有音频，该视频播放异常看上去像是倍速播放。

## 问题机型/系统：

 Android8.0

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.5-jitpack'

**Comment by CarGuo** [comment]
如果其中一个视频没有音频，那同步时钟可能存在问题····具体不大清楚
