### ISSUE TITLE
日志打印问题

### ISSUE THREAD

**Issue by workgithubly** [CarGuo/GSYVideoPlayer#3306]
## 问题描述：

在 Application 设置了
 IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
  Debuger.disable();

但还是疯狂打印
![image](https://user-images.githubusercontent.com/6802893/122878279-28d56580-d36a-11eb-8cad-51d50f3cb041.png)

**Comment by pcyfox** [comment]
说人话，听不懂

**Comment by pcyfox** [comment]
jkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
和
Debuger.disable() 这两都设置了 还是疯狂打印 D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
