### ISSUE TITLE
编译了ex_so的aar，但是放进项目中会报错，java.lang.UnsatisfiedLinkError: dlopen failed: library "libijkffmpeg.so" not found

### ISSUE THREAD

**Issue by qihaogao** [CarGuo/GSYVideoPlayer#3307]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：编译了加入eac3的so，在demo里运行正常，但是放到项目中就报：java.lang.UnsatisfiedLinkError: dlopen failed: library "libijkffmpeg.so" not found
其中编译so的ijk版本是0.8.8

XXXX发生了这样的问题！

## 问题机型/系统：

piexl2 android11

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.3'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
not found 你看你打包的 apk 里是不是没有就对了
