### ISSUE TITLE
播放m3u8时ts返回404后不能继续往后播放

### ISSUE THREAD

**Issue by daxiguaHello** [CarGuo/GSYVideoPlayer#3308]
## 问题描述：

我是第一次使用提问如果有格式不对的，希望不要删除，告诉我哪里格式不对。我下次更正。

我的问题：
播放m3u8文件时里面存在有些ts返回404，当遇到这种ts后就播放失败。
这个失败的ts后面还有其他ts是可以正常播放的（我用其他播放器测试过）。
请问这种我要如何修改代码？或者修改哪里。

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.3-jitpack

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
这个 exo 里就需要看 /com/google/android/exoplayer2/source/hls 下的解析逻辑

**Comment by daxiguaHello** [comment]
> 这个 exo 里就需要看 /com/google/android/exoplayer2/source/hls 下的解析逻辑 ， gsy 暂时没有做这个支持的计划

大佬，我下载的是8.1.3的这个工程，但是我没找到你说的his这个目录或者文件呢？是要单独去下载exoplayer2的源码吗？

**Comment by CarGuo** [comment]
hls 只是提供了一个 source 相关的逻辑，你可以自定义你自己的source ，然后通过ExoSourceManager.setExoMediaSourceInterceptListener 使用你的自定义

**Comment by daxiguaHello** [comment]
> setExoMediaSourceInterceptListener

我自定义了实现了打开、读取、关闭网络的这些函数，问题是返回404后播放器不会在调用到我自定义的open函数了，就是它停止了请求。我已经下载它源码修改实现了忽略404的地址，继续请求下一段ts地址。我现在不知道怎么集成到工程里面去。

我修改源码的位置：HlsChunkSource.java-->getNextChunk函数，如果有相同需求的朋友可以参考修改下这里。
......
    if (chunkMediaSequence < playlist.mediaSequence) {
      fatalError = new BehindLiveWindowException();
      return;
    }

    //判断当前获取的ts索引是否和上一次一样
    //如果一样就+1忽略掉
    if (chunkMediaSequence == count) {
      chunkMediaSequence += 1;
    }
    count = chunkMediaSequence;


    //关注这里是不是获取到ts  chunkMediaSequence 上面得到的索引
    @Nullable
    SegmentBaseHolder segmentBaseHolder = getNextSegmentHolder(playlist, chunkMediaSequence, partIndex);
......

**Comment by CarGuo** [comment]
ExoSourceManager.setExoMediaSourceInterceptListener  @daxiguaHello  这个方法

**Comment by daxiguaHello** [comment]
> setExoMediaSourceInterceptListener

我用到这个方法了，我做了重定向比如返回404的ts我重新去打开一个其他地址返回200的，但是还有问题，比如连续10个左右ts都是返回404，播放器直接停止播放失败。

**Comment by CarGuo** [comment]
很多方式，最简单的就是，你整套 hls 用源码依赖呀

**Comment by daxiguaHello** [comment]
> 很多方式，最简单的就是，你整套 hls 用源码依赖呀

大佬具体怎么操作呢？比如我现在要修改的几个类，有一个类在core这个库中，还有一个类在hls这个库中。现在想不到要怎么弄才能替换呢？大佬指教下。

**Comment by CarGuo** [comment]
主要是……你从source层开始啊，然后用到了哪个要改的，就一层一层复制出来新建一个就行了

**Comment by daxiguaHello** [comment]
> 主要是……你从source层开始啊，然后用到了哪个要改的，就一层一层复制出来新建一个就行了

大佬，我是这样做的，比如jar包中有一个类是com.google.android.exoplayer2.upstream包下的Loader.java，然后我在自己工程下也建立了一个和他一样的包名称，类名称，你说的是这种方式吗？

我试了这种方式有下面这个问题
代码会执行到我这新建的类中，但是我新加的代码不生效，我不知道为什么。
比如我在新建的Loader.java这个类中的任意一行新加一行Log.d打印函数，我确定这个位置的代码会被执行，但是这一行对应的还是源码中的那一行代码，并没有执行新加的打印日志。

**Comment by CarGuo** [comment]
建一个不一样的包名，你自己的，然后一个一个复制，都到你新的包名下，import 你自定义的类啊，这样才对
你包名一样导入用不了你的

**Comment by iuhni** [comment]
牛逼啊,正好解决了我的需求,大佬6666
