### ISSUE TITLE
屏幕解锁后播放器自动全屏

### ISSUE THREAD

**Issue by jimmyspace** [CarGuo/GSYVideoPlayer#3312]
设置整个界面横屏，锁屏然后解锁后播放器自动全屏，退出全屏，整个界面都变成竖屏了。

如何设置屏幕解锁后不全屏，界面保持横屏

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2955

**Comment by jimmyspace** [comment]
> #2955

不是那个问题

现在配置的是
return new GSYVideoOptionBuilder()
                .setThumbImageView(imageView)
                .setUrl(RTSP_URL)
                .setCacheWithPlay(true)
                .setVideoTitle("")
                .setIsTouchWiget(true)
                .setAutoFullWithSize(false)
                .setRotateViewAuto(false)
                .setLockLand(false)
                .setShowFullAnimation(false)//打开动画
                .setNeedLockFull(true)
                .setSeekRatio(1);

**正常运行没有打印 OrientationEventListener；**


**关闭屏幕后会有这个打印：D/OrientationEventListener: OrientationEventListener orientation**

**Comment by CarGuo** [comment]
不理解你的意思，在我看来就是这个问题，因为内部会调用转会竖屏的逻辑，哪里导致你变竖了修改对应的部分就好了

**Comment by jimmyspace** [comment]
> 不理解你的意思，在我看来就是这个问题，因为内部会调用转会竖屏的逻辑，哪里导致你变竖了修改对应的部分就好了
我这边本来设置APP横屏，可以正常跑rtsp推流，关闭屏幕后，再解锁屏幕，整个界面先变成竖屏，然后视频窗口变成全屏了，我这边没有做多余的操作（没有写竖屏和设置全屏的代码）

**Comment by jimmyspace** [comment]
> 不理解你的意思，在我看来就是这个问题，因为内部会调用转会竖屏的逻辑，哪里导致你变竖了修改对应的部分就好了

就是取消自动横竖屏

**Comment by CarGuo** [comment]
那其实就是前面发的链接 ，OrientationUtils 相关的逻辑啊
