### ISSUE TITLE
视频全屏问题

### ISSUE THREAD

**Issue by chuxiaokeAndroid** [CarGuo/GSYVideoPlayer#3314]
使用的StandardGSYVideoPlayer   gsyVideoOption
                .setIsTouchWiget(true)
                .setRotateViewAuto(false)
                .setLockLand(false)
                .setAutoFullWithSize(false)
                .setNeedLockFull(true)
                .setCacheWithPlay(false)
                .setShowFullAnimation(false)
                .setVideoAllCallBack(new GSYSampleCallBack() {
                    @Override
                    public void onPrepared(String url, Object... objects) {
                        super.onPrepared(url, objects);
                        //开始播放了才能旋转和全屏
                        orientationUtils.setEnable(videoPlayer.isRotateWithSystem());
                        isPlay = true;
                    }

                    @Override
                    public void onQuitFullscreen(String url, Object... objects) {
                        super.onQuitFullscreen(url, objects);
                        if (orientationUtils != null) {
                            orientationUtils.backToProtVideo();
                        }
                    }

                    @Override
                    public void onPlayError(String url, Object... objects) {
                        super.onPlayError(url, objects);
                        if (NetWorkUtil.isNetworkConnected(HelpActivity.this)) {
                            showToastMessage("当前视频播放失败");
                        } else {
                            showToastMessage(getString(R.string.no_network_details));
                        }
                    }
                }).setLockClickListener(new LockClickListener() {
            @Override
            public void onClick(View view, boolean lock) {
                if (orientationUtils != null) {
                    //配合下方的onConfigurationChanged
                    orientationUtils.setEnable(!lock);
                }
            }
        }).build(videoPlayer);

        videoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //直接横屏
                //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                videoPlayer.startWindowFullscreen(HelpActivity.this, true, true);
            }
        });

这种写法。界面是左边是列表，右边是播放器；点击第一个item，视频播放并全屏，然后退出全屏。点击第二个item，这个时候播放的视频是第一个item带的视频链接。  请问是缓存导致的问题吗

切换使用videoPlayer.getCurrentPlayer().setUp(model.getData().getWz(), true, "");

**Comment by chuxiaokeAndroid** [comment]
每次videoPlayer.getCurrentPlayer().setUp(model.getData().getWz(), true, "");加载的视频链接都不一样，为啥会这样呢

**Comment by CarGuo** [comment]
看着好像没问题，确定切换时url正常设置了？

**Comment by chuxiaokeAndroid** [comment]
package com.fx.correctonepc.help;


import android.content.res.Configuration;
import android.view.View;
import android.widget.LinearLayout;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.chad.library.adapter.base.BaseQuickAdapter;
import com.chad.library.adapter.base.listener.OnItemClickListener;
import com.fx.correctonepc.R;
import com.fx.correctonepc.api.ApiServer;
import com.fx.correctonepc.app.GlobalConstant;
import com.fx.correctonepc.base.AppActivity;
import com.fx.correctonepc.base.basePresenter.BasePresenterAbs;
import com.fx.correctonepc.base.basePresenter.BaseViewData;
import com.fx.correctonepc.base.observer.ProgressSubscriber;
import com.fx.correctonepc.base.observer.SubscriberOnNextListener;
import com.fx.correctonepc.dailyReport.DailyReportActivity;
import com.fx.correctonepc.help.model.HelpModel;
import com.fx.correctonepc.help.model.HelpVideoDetailsModel;
import com.fx.correctonepc.model.EduLearnRecordModel;
import com.fx.correctonepc.model.UploadFileModel;
import com.fx.correctonepc.signinSignout.SigninSignoutActivity;
import com.fx.correctonepc.signinSignout.model.SigninSignoutModel;
import com.fx.correctonepc.widget.GSYVideoPlayer;
import com.fxzx.common.api.request.Qequest;
import com.fxzx.common.base.bean.BaseModel;
import com.fxzx.common.util.CustomToast;
import com.fxzx.common.util.LogUtil;
import com.fxzx.common.util.NetWorkUtil;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.scwang.smartrefresh.layout.SmartRefreshLayout;
import com.scwang.smartrefresh.layout.api.RefreshLayout;
import com.scwang.smartrefresh.layout.listener.OnRefreshLoadMoreListener;
import com.shuyu.gsyvideoplayer.GSYVideoManager;
import com.shuyu.gsyvideoplayer.builder.GSYVideoOptionBuilder;
import com.shuyu.gsyvideoplayer.listener.GSYSampleCallBack;
import com.shuyu.gsyvideoplayer.listener.GSYVideoProgressListener;
import com.shuyu.gsyvideoplayer.listener.LockClickListener;
import com.shuyu.gsyvideoplayer.utils.GSYVideoType;
import com.shuyu.gsyvideoplayer.utils.OrientationUtils;
import com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer;

import org.json.JSONException;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import butterknife.BindView;
import io.reactivex.Observable;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.RequestBody;

/**
 * 使用帮助
 */
public class HelpActivity extends AppActivity implements BaseViewData, OnRefreshLoadMoreListener {
    @BindView(R.id.help_recycle)
    RecyclerView mHelp_recycle;
    @BindView(R.id.help_video_player)
    GSYVideoPlayer videoPlayer;
    @BindView(R.id.help_smartrefreshlayout)
    SmartRefreshLayout mfreshlayout;
    private HelpAdapter mAdapter;
    OrientationUtils orientationUtils;
    private boolean isPlay;
    private boolean isPause;
    private MPresenter presenter;
    private int page = 1, location = -1;

    @Override
    protected int getContentView() {
        return R.layout.activity_help;
    }

    @Override
    protected void initView() {
        mHelp_recycle.setLayoutManager(new LinearLayoutManager(this));
        mAdapter = new HelpAdapter();
        mHelp_recycle.setAdapter(mAdapter);
        mfreshlayout.setOnRefreshLoadMoreListener(this);
        presenter = new MPresenter();
        videoPlayer.getCurrentPlayer().getTitleTextView().setVisibility(View.GONE);
        //外部辅助的旋转，帮助全屏
        orientationUtils = new OrientationUtils(this, videoPlayer);
        //初始化不打开外部的旋转
        orientationUtils.setEnable(false);
        GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);
        GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder();
        gsyVideoOption
                .setIsTouchWiget(true)
                .setRotateViewAuto(false)
                .setLockLand(false)
                .setAutoFullWithSize(false)
                .setNeedLockFull(true)
                .setCacheWithPlay(false)
                .setShowFullAnimation(false)
                .setVideoAllCallBack(new GSYSampleCallBack() {
                    @Override
                    public void onPrepared(String url, Object... objects) {
                        super.onPrepared(url, objects);
                        //开始播放了才能旋转和全屏
                        orientationUtils.setEnable(videoPlayer.isRotateWithSystem());
                        isPlay = true;
                    }
                    @Override
                    public void onEnterFullscreen(String url, Object... objects) {
                        super.onEnterFullscreen(url, objects);
                    }

                    @Override
                    public void onPlayError(String url, Object... objects) {
                        super.onPlayError(url, objects);
                        if (NetWorkUtil.isNetworkConnected(HelpActivity.this)) {
                            showToastMessage("当前视频播放失败");
                        } else {
                            showToastMessage(getString(R.string.no_network_details));
                        }
                    }
                }).setLockClickListener(new LockClickListener() {
            @Override
            public void onClick(View view, boolean lock) {
                if (orientationUtils != null) {
                    //配合下方的onConfigurationChanged
                    orientationUtils.setEnable(!lock);
                }
            }
        }).build(videoPlayer);

        videoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //直接横屏
                //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                videoPlayer.startWindowFullscreen(HelpActivity.this, true, true);
            }
        });

    }

    @Override
    protected void initData() {
        page = 1;
        presenter.getHelpList(page, GlobalConstant.PAGE_SIZE);
    }

    @Override
    protected void addListener() {
        videoPlayer.setGSYVideoProgressListener(new GSYVideoProgressListener() {
            @Override
            public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
            }
        });
        mAdapter.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(@NonNull BaseQuickAdapter adapter, @NonNull View view, int position) {
                if (location == position)
                    return;
                presenter.getHelpInfo(mAdapter.getData().get(position).getId(), position);
            }
        });

    }

    @Override
    public void onLoadMore(RefreshLayout refreshLayout) {
        page++;
        presenter.getHelpList(page, GlobalConstant.PAGE_SIZE);
    }

    @Override
    public void onRefresh(RefreshLayout refreshLayout) {
        initData();
    }

    private class MPresenter extends BasePresenterAbs {
        /**
         * 视频列表
         */
        public void getHelpList(int page, int rows) {
            Map<String, Object> map = new HashMap<>();
            map.put("page", page);
            map.put("rows", rows);
            Observable<HelpModel> observable = Qequest.getInstance().create(ApiServer.class)
                    .getHelpList(getRequestBody(map));
            ProgressSubscriber subscriber = createSubscriber(new SubscriberOnNextListener() {
                @Override
                public void onNext(BaseModel baseModel) {
                    if (baseModel != null) {
                        HelpModel model = (HelpModel) baseModel;
                        if (model != null && !model.getData().isEmpty()) {
                            if (page == 1) {
                                mAdapter.setNewData(model.getData());
                            } else {
                                mAdapter.addData(model.getData());
                            }
                        } else {
                            if (page == 1) {
                                showNoDataView();
                            } else {
                                HelpActivity.this.page--;
                                CustomToast.of().show(getString(R.string.no_data));
                            }
                        }
                    } else {
                        showNoDataView();
                    }
                }

                @Override
                public boolean onError(Throwable e) {
                    finishLoadRefresh(mfreshlayout);
                    if (!NetWorkUtil.isNetworkConnected(HelpActivity.this)) {
                        showNetErrorView();
                    }
                    return true;
                }

                @Override
                public void onComplete() {
                    super.onComplete();
                    finishLoadRefresh(mfreshlayout);
                }
            }, HelpActivity.this);
            subscriberObservable(subscriber, observable);
        }

        /**
         * 播放视频
         */
        public void getHelpInfo(int id, int mPosition) {
            location = mPosition;
            Map<String, Object> map = new HashMap<>();
            map.put("id", id);
            Observable<HelpVideoDetailsModel> observable = Qequest.getInstance().create(ApiServer.class)
                    .getHelpInfo(getRequestBody(map));
            ProgressSubscriber subscriber = createSubscriber(new SubscriberOnNextListener() {
                @Override
                public void onNext(BaseModel baseModel) {
                    if (baseModel != null) {
                        HelpVideoDetailsModel model = (HelpVideoDetailsModel) baseModel;
                        if (model != null) {
                            mAdapter.setRefreshData(mPosition);
                            LogUtil.e("视频链接"+model.getData().getWz());
                            videoPlayer.getCurrentPlayer().onVideoReset();
                            videoPlayer.getCurrentPlayer().setUp(model.getData().getWz(), true, "");
                            videoPlayer.getCurrentPlayer().startPlayLogic();
                        }
                    }
                }

                @Override
                public boolean onError(Throwable e) {
                    CustomToast.of().show(e.getMessage());
                    return true;
                }

                @Override
                public void onComplete() {
                    super.onComplete();
                }
            }, HelpActivity.this);
            subscriberObservable(subscriber, observable);
        }

    }

    @Override
    public void onBackPressed() {
        if (orientationUtils != null) {
            orientationUtils.backToProtVideo();
        }
        if (GSYVideoManager.backFromWindowFull(this)) {
            return;
        }
        super.onBackPressed();
    }


    @Override
    protected void onPause() {
        videoPlayer.getCurrentPlayer().onVideoPause();
        super.onPause();
        isPause = true;
    }

    @Override
    protected void onResume() {
        videoPlayer.getCurrentPlayer().onVideoResume(false);
        super.onResume();
        isPause = false;
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (isPlay) {
            videoPlayer.getCurrentPlayer().release();
        }
        if (orientationUtils != null)
            orientationUtils.releaseListener();
    }


    /**
     * orientationUtils 和  detailPlayer.onConfigurationChanged 方法是用于触发屏幕旋转的
     */
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        //如果旋转了就全屏
        if (isPlay && !isPause) {
            videoPlayer.onConfigurationChanged(this, newConfig, orientationUtils, true, true);
        }
    }


    @Override
    protected int getContentTitle() {
        return 1;
    }

}   这是我类全部的代码   你看看

**Comment by chuxiaokeAndroid** [comment]
辛苦一下，郭老师看看我的代码。

**Comment by CarGuo** [comment]
@chuxiaokeAndroid  看着头晕，我的意思是

1、先确定点击播放第二个时， model.getData().getWz()  得到的是不是第二个 的 url
2、ListGSYVideoPlayer 其实也有类似的  setUp 和 startPlayLogic 逻辑，在  playNext 方法，你可以看看

**Comment by chuxiaokeAndroid** [comment]
model.getData().getWz() ，我打印了，是第二个url。
奇怪的是，只要不全屏，切换视频播放当前url就正常

**Comment by chuxiaokeAndroid** [comment]
等我明天，在咱们的demo里面修改一下我的需求。然后看看咋样，不行的话，我吧demo修改后的代码，给你qq发过去

**Comment by CarGuo** [comment]
我捋一下，是 全屏，退出全屏，然后用 videoPlayer.getCurrentPlayer() 去 setup ，play 之后就会有这问题？？
如果是你在非全屏的时候 seup & play ，其是不需要用  getCurrentPlayer() ，感觉好奇怪，没有 setup 成功？？断点挑一下看看就知道了

**Comment by chuxiaokeAndroid** [comment]
晚点我在试试，多谢郭老师的解答。

**Comment by chuxiaokeAndroid** [comment]
我加了一个两秒的延时就好了 先   videoPlayer.onVideoPause();  然后2s后切换视频

**Comment by CarGuo** [comment]
不是很明白为什么会这样····
