### ISSUE TITLE
IJK内核下播放视频有声音没画面

### ISSUE THREAD

**Issue by 756230883** [CarGuo/GSYVideoPlayer#3316]
问题描述：

使用IJK内核播放视频有声音没有画面 视频链接为 http://oss.dev.nbs.cn/M00/00/0F/rBSSXmDQL6KAbid7AmwUitLzFQo190.mp4

## 问题机型/系统：

真机 oppo reno3

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack'

## Demo中的复现步骤

demo切换到IJK内核 InputUrlDetailActivity页面 输入 http://oss.dev.nbs.cn/M00/00/0F/rBSSXmDQL6KAbid7AmwUitLzFQo190.mp4 这个视频连接后 有声音没有画面
SimpleDetailActivityMode2 页面视频链接换为 http://oss.dev.nbs.cn/M00/00/0F/rBSSXmDQL6KAbid7AmwUitLzFQo190.mp4 也是
有声音没有画面

**Comment by CarGuo** [comment]
https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q

**Comment by 756230883** [comment]
打开链接看了 没有我说的这种情况啊 大佬 具体该怎么处理呢 求讲解一下  谢谢

**Comment by 756230883** [comment]
> https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
必现的 大佬 有点着急 麻烦给个思路呗

**Comment by CarGuo** [comment]
都看了怎么就不理解我发意思呢····你看链接还不知道为什么没画面么？

```
2021-06-30 14:39:06.702 27941-28228/com.example.gsyvideoplayer I/IJKMEDIA: : Video: mpeg4, 1 reference frame (mp4v / 0x7634706D), none, 856x480 (0x0), 0/1, 1512 kb/s
2021-06-30 14:39:06.702 27941-28228/com.example.gsyvideoplayer I/IJKMEDIA: , SAR 1:1 DAR 107:60
```

你看 log 就知道是什么原因了啊，结合 readme 依赖方法看下···· mpeg 编码的要用 ex_so 的依赖
