### ISSUE TITLE
播放m3u8中有多画质地址，只能播放第一个第址

### ISSUE THREAD

**Issue by Gloud-Zhao** [CarGuo/GSYVideoPlayer#3317]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

m3u8中有多画质地址，只能播放第一个地址，也就是最低画质的地址，这里怎么设置一下？
## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。
下面是m3u8地址
http://yunstudy.koo6.cn/2018Videofile/2020/ACC80c31852f4d8e34dde2bf26584fb042a/ysyy_001/index.m3u8

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
我理解没错的话，其实就是 IjkPlayerManager 里的

public IjkTrackInfo[] getTrackInfo() {
        if (mediaPlayer != null) {
            return mediaPlayer.getTrackInfo();
        }
        return null;
    }

    public int getSelectedTrack(int trackType) {
        if (mediaPlayer != null) {
            return mediaPlayer.getSelectedTrack(trackType);
        }
        return -1;
    }

    public void selectTrack(int track) {
        if (mediaPlayer != null) {
            mediaPlayer.selectTrack(track);
        }
    }

    public void deselectTrack(int track) {
        if (mediaPlayer != null) {
            mediaPlayer.deselectTrack(track);
        }
    }

**Comment by Gloud-Zhao** [comment]
> 我理解没错的话，其实就是 IjkPlayerManager 里的
> 
> ```
> public IjkTrackInfo[] getTrackInfo() {
>         if (mediaPlayer != null) {
>             return mediaPlayer.getTrackInfo();
>         }
>         return null;
>     }
> 
>     public int getSelectedTrack(int trackType) {
>         if (mediaPlayer != null) {
>             return mediaPlayer.getSelectedTrack(trackType);
>         }
>         return -1;
>     }
> 
>     public void selectTrack(int track) {
>         if (mediaPlayer != null) {
>             mediaPlayer.selectTrack(track);
>         }
>     }
> 
>     public void deselectTrack(int track) {
>         if (mediaPlayer != null) {
>             mediaPlayer.deselectTrack(track);
>         }
>     }
> ```

是可以这么理解，但是在GSY中我不知道是不是用的正确，getTrackInfo就返回了null，后面就没办法再执行了

`IPlayerManager tIPlayerManager=PlayerFactory.getPlayManager();
                        if (tIPlayerManager instanceof IjkPlayerManager){
                            IjkPlayerManager tIjkPlayer= (IjkPlayerManager) tIPlayerManager;
                            IjkTrackInfo[] tIjkTrackInfo=tIjkPlayer.getTrackInfo();
                            if (null!=tIjkTrackInfo){
                                //这里返回了空
                            }
                        }`

**Comment by CarGuo** [comment]
如果获取不到，那就不支持内部多画切换了，Exo 的 track 部分我好像没开放出来，你可以考虑自定义自己的 PlayerManager
