### ISSUE TITLE
1.6.8demo 

### ISSUE THREAD

**Issue by nohavename** [CarGuo/GSYVideoPlayer#332]
1.6.8 demo中的DetailPlayer 在onPause()添加 detailPlayer.onVideoPause()，横屏播放，进入后台会崩溃，再显示的时候播放界面不是暂停界面

**Comment by CarGuo** [comment]
请参考使用GsyManager.onPa.onPause，应该是在Recycler的Activity有demo

**Comment by CarGuo** [comment]
请参考使用GsyManager.onPause，应该是在Recycler的Activity有demo
