### ISSUE TITLE
请问作者，如何宽度铺满，高度自适应。 

### ISSUE THREAD

**Issue by Newwaygo** [CarGuo/GSYVideoPlayer#3320]
请问作者，如何宽度铺满，高度自适应。

**Comment by CarGuo** [comment]
看 
 
https://github.com/CarGuo/GSYVideoPlayer/blob/6fff64ec9aad4b99a8c1ddcea886d3b1ca1189b7/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/GSYVideoType.java#L11

https://github.com/CarGuo/GSYVideoPlayer/blob/af3becf7c69e19da602185d00715d266f2b712e0/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/MeasureHelper.java 

你还可以通过 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/view/CustomRenderView.java 自定义

**Comment by Newwaygo** [comment]
看，不太懂啊，具体要改那个参数？
 SCREEN_TYPE_DEFAULT = 0;   这个 默认就是这个， 但是这个上下有黑边， 竖屏铺满的时候。

**Comment by CarGuo** [comment]
就是你可以参考 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/view/CustomRenderView.java  自己自定义 实现

**Comment by Newwaygo** [comment]
我直接用的这个 类 ，没看出有什么不同。https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/view/CustomRenderView.java

**Comment by CarGuo** [comment]
这个是 demo 里的呀，告诉你如果想要自定义的话，可以通过这样的方法自定义，比如 CustomTextureSurface 里用的就是默认的 measureHelper ，你加多自己想要的逻辑在 onMeasure 里就好了

**Comment by Newwaygo** [comment]
是要修改measureHelper 吗？ 但是measureHelper  是final 不能重写，如果复制出来，我感觉相关类都要改？

好像涉及的类很多？

**Comment by zhangqilu** [comment]
> 是要修改measureHelper 吗？ 但是measureHelper 是final 不能重写，如果复制出来，我感觉相关类都要改？
> 
> 好像涉及的类很多？
你这个解决了吗
