### ISSUE TITLE
视频播放过程中后台频繁GC

### ISSUE THREAD

**Issue by huochaifanfan** [CarGuo/GSYVideoPlayer#3321]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
视频播放过程中后台日志在频繁GC，播放一段时间后程序会变得比较卡
这个是打印的日志：Explicit concurrent copying GC freed 708152(20MB) AllocSpace objects, 9(17MB) LOS objects, 49% free, 20MB/41MB, paused 689us total 174.447ms

## 问题机型/系统：

华为Novi3

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:8.1.5-jitpack

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
有提供测试视频吗？

**Comment by huochaifanfan** [comment]
> 有提供测试视频吗？

视频连接30秒不播放就失效了，有个问题请教下，视频缓冲是缓存在内存中吗，比如当前播放进度是10%，缓冲进度是20%，内存缓冲的大小是怎么设置的，哪里可以看到代码。缓冲大小超过阈值的时候怎么处理的呀，谢谢指教

**Comment by CarGuo** [comment]
是的，就是缓冲一个块，而有新的块的时候，旧的就会清除，比如 seek 的时候，设置阈值这个你可以在问题集锦力找到，关于 Ijk 的配置的话

**Comment by Anbinghui** [comment]
频繁GC的原因是什么?我看GC日志是手动GC,但是看代码没发现那里有主动GC
