### ISSUE TITLE
视频跟声音对不上

### ISSUE THREAD

**Issue by RokenGGG** [CarGuo/GSYVideoPlayer#3323]
问题机型/系统：
主板rk3288 Android7.1.2
 运行内存2G

 GSY依赖版本
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack

直接使用的没有布局控件的view， 播放的时候声音跟视频对应不上

<xxxxxxxxx.view.EmptyControlVideo
        android:id="@+id/video_player"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerInParent="true"
        android:visibility="gone" />

public class EmptyControlVideo extends StandardGSYVideoPlayer {

    public EmptyControlVideo(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

    public EmptyControlVideo(Context context) {
        super(context);
    }

    public EmptyControlVideo(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public int getLayoutId() {
        return R.layout.empty_control_video;
    }

    @Override
    protected void touchSurfaceMoveFullLogic(float absDeltaX, float absDeltaY) {
        super.touchSurfaceMoveFullLogic(absDeltaX, absDeltaY);
        //不给触摸快进，如果需要，屏蔽下方代码即可
        mChangePosition = false;

        //不给触摸音量，如果需要，屏蔽下方代码即可
        mChangeVolume = false;

        //不给触摸亮度，如果需要，屏蔽下方代码即可
        mBrightness = false;
    }

    @Override
    protected void touchDoubleUp(MotionEvent e) {
        //super.touchDoubleUp();
        //不需要双击暂停
    }
}
[视频地址](https://yoye-ads.oss-cn-beijing.aliyuncs.com/prd/202106281018014508.mp4)

private void loadVideoView(){
        Glide.with(getActivity()).load(urlString).into(imageView);
        String uri = "/mnt/sdcard/ledian/abc.mp4";
        videoView.setUp(uri, true, "");
        videoView.setVideoAllCallBack(new VideoAllCallBack() {
            @Override
            public void onStartPrepared(String url, Object... objects) {
                Logger.e("onStartPrepared");
            }

            @Override
            public void onPrepared(String url, Object... objects) {
                Logger.e("onPrepared");
            }

            @Override
            public void onClickStartIcon(String url, Object... objects) {
                Logger.e("onClickStartIcon");
            }

            @Override
            public void onClickStartError(String url, Object... objects) {
                Logger.e("onClickStartError");
            }

            @Override
            public void onClickStop(String url, Object... objects) {
                Logger.e("onClickStop");
            }

            @Override
            public void onClickStopFullscreen(String url, Object... objects) {
                Logger.e("onClickStopFullscreen");
            }

            @Override
            public void onClickResume(String url, Object... objects) {
                Logger.e("onClickResume");
            }

            @Override
            public void onClickResumeFullscreen(String url, Object... objects) {
                Logger.e("onClickResumeFullscreen");
            }

            @Override
            public void onClickSeekbar(String url, Object... objects) {
                Logger.e("onClickSeekbar");
            }

            @Override
            public void onClickSeekbarFullscreen(String url, Object... objects) {
                Logger.e("onClickSeekbarFullscreen");
            }

            /**
             * 视频播放完成
             * @param url
             * @param objects
             */
            @Override
            public void onAutoComplete(String url, Object... objects) {
                Logger.e("onAutoComplete");
                EventBus.getDefault().post(new NextBannerEvent(NEXT_FRAGMENT, current));
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        getActivity().overridePendingTransition(R.anim.abc_fade_in, R.anim.abc_fade_out);
                    }
                }, 500);
            }

            @Override
            public void onComplete(String url, Object... objects) {
                Logger.e("onComplete");
                //EventBus.getDefault().post(new NextBannerEvent(BannerFaceActivity.NEXT_FRAGMENT, current));
            }

            @Override
            public void onEnterFullscreen(String url, Object... objects) {
                Logger.e("onEnterFullscreen");
            }

            @Override
            public void onQuitFullscreen(String url, Object... objects) {
                Logger.e("onQuitFullscreen");
            }

            @Override
            public void onQuitSmallWidget(String url, Object... objects) {
                Logger.e("onQuitSmallWidget");
            }

            @Override
            public void onEnterSmallWidget(String url, Object... objects) {
                Logger.e("onEnterSmallWidget");
            }

            @Override
            public void onTouchScreenSeekVolume(String url, Object... objects) {
                Logger.e("onTouchScreenSeekVolume");
            }

            @Override
            public void onTouchScreenSeekPosition(String url, Object... objects) {
                Logger.e("onTouchScreenSeekPosition");
            }

            @Override
            public void onTouchScreenSeekLight(String url, Object... objects) {
                Logger.e("onTouchScreenSeekLight");
            }

            @Override
            public void onPlayError(String url, Object... objects) {
                Logger.e("onPlayError");
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        EventBus.getDefault().post(new NextBannerEvent(NEXT_FRAGMENT, current));
                    }
                }, 3000);
            }

            @Override
            public void onClickStartThumb(String url, Object... objects) {
                Logger.e("onClickStartThumb");
            }

            @Override
            public void onClickBlank(String url, Object... objects) {
                Logger.e("onClickBlank");
            }

            @Override
            public void onClickBlankFullscreen(String url, Object... objects) {
                Logger.e("onClickBlankFullscreen");
            }
        });
        initTransition();
    }

    private void initTransition() {
        if (isTransition && Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            postponeEnterTransition();
            ViewCompat.setTransitionName(videoView, IMG_TRANSITION);
            addTransitionListener();
            startPostponedEnterTransition();
        } else {
            videoView.startPlayLogic();
        }
        imageView.setVisibility(View.GONE);
        videoView.setVisibility(View.VISIBLE);
    }

**Comment by CarGuo** [comment]
如果是 ijk 的播放模式，可以参考  https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md#12视频声音画面不同步 

如果是其它的话，只能处理硬件
