### ISSUE TITLE
有些视频没缓存完就播放完了，这是怎么回事？

### ISSUE THREAD

**Issue by ollie100** [CarGuo/GSYVideoPlayer#3325]
## 问题描述：

有些视频播放时候有在缓存，但是缓存到60%左右，视频就播完了。正常情况下一次再播这个视频是会恢复继续缓存的，但是有些时候出现再次播这个视频就不会进行缓存了，一直耗的是流量播放，进不了缓存。
请问是什么问题，帮忙解决下。用的androidVideoCache的缓存

**Comment by CarGuo** [comment]
不明白，如果缓存被判定为损坏，可能就会被clear ，或者播放过程中出现 Error

**Comment by ollie100** [comment]
就是第一次播放时候缓存文件进度只到60%左右就停止了，回调是视频播放完成。然后再次播放时候缓存就不会继续进行了。
视频播放过程没有出现error，是回调onAutoComplete的完成播放。
if (url.startsWith("http") && !url.contains("127.0.0.1") && !url.contains(".m3u8")) {
            LogUtils.dTag("DYCACHE","getProxy doCacheLogic cachePath ");
            HttpProxyCacheServer proxy = getProxy(context.getApplicationContext(), cachePath);
            if (proxy != null) {
                //此处转换了url，然后再赋值给mUrl。
                url = proxy.getProxyUrl(url);
                mCacheFile = (!url.startsWith("http"));
                LogUtils.dTag("DYCACHE", "getProxy doCacheLogic cachePath !null mCacheFile = "
                        +mCacheFile+" url = "+url);
                //注册上缓冲监听
                if (!mCacheFile) {
                    //能进到这里面缓存监听，但是实际收不到缓存的进度
                    proxy.registerCacheListener(this, originUrl);
                    LogUtils.dTag("DYCACHE","proxy");
                }
            }
        }

**Comment by ollie100** [comment]
能不能实现缓冲去掉，缓存多少播多少？

**Comment by qq837890739** [comment]
边播边缓存为什么是直接缓存完整个视频的？不应该是播放多少缓存多少吗？

**Comment by CarGuo** [comment]
@qq837890739  有两种缓存模式，一种是 proxy ，也就是类似迅雷边播放边缓存的，这种下载缓存和播放本身就没有关系。

另外是 exo 内核搭配 exocache 的模式，这种就是按照播放缓冲块内去缓存，但是这种缓存模式不支持到处独立视频，缓存的是一个一个的碎片

**Comment by qq837890739** [comment]
> @qq837890739 有两种缓存模式，一种是 proxy ，也就是类似迅雷边播放边缓存的，这种下载缓存和播放本身就没有关系。
> 
> 另外是 exo 内核搭配 exocache 的模式，这种就是按照播放缓冲块内去缓存，但是这种缓存模式不支持到处独立视频，缓存的是一个一个的碎片

我下载了demo，切换了内核，都是一次性缓存（下载）完整个视频的，其实缓存在本地不是为了省流量和无网观看吗？而且我发现即使缓存完了，但是拖动进度的时候还是会联网

**Comment by CarGuo** [comment]
@qq837890739  你都没看清我说的话·····

`PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式` 需要搭配 `CacheFactory.setCacheManager(ExoPlayerCacheManager.class);`


另外如果是完整缓存了，下次打开的时候换转成 file 的本地播放，所以就不会是 http 的请求了

**Comment by qq837890739** [comment]
> @qq837890739 你都没看清我说的话·····
> 
> `PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式` 需要搭配 `CacheFactory.setCacheManager(ExoPlayerCacheManager.class);`
> 
> 另外如果是完整缓存了，下次打开的时候换转成 file 的本地播放，所以就不会是 http 的请求了

好的，我也发现了，缓存完了下次打开才不会请求网络
