### ISSUE TITLE
如何在播放的时候让渲染控件背景透明

### ISSUE THREAD

**Issue by syusikoku** [CarGuo/GSYVideoPlayer#3327]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

你好，我在结合SwipeBackLayout使用的时候，想实现滑动的时候退出界面，想把后面的背景给设置成透明，不知道如何操作，可以给点建议吗？

## 问题机型/系统：

例如 华为Nova 7 5G

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.5'`

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/986
https://github.com/CarGuo/GSYVideoPlayer/issues/2729
