### ISSUE TITLE
弹幕如何根据视频速度自动调整

### ISSUE THREAD

**Issue by SkyD666** [CarGuo/GSYVideoPlayer#3329]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

弹幕如何根据视频速度自动调整，比如视频2倍速，弹幕也2倍速，视频0.5倍速，弹幕也0.5倍速

## 问题机型/系统：

无

## GSY依赖版本

例如 `implementation 'com.shuyu:GSYVideoPlayer:8.1.0'`

## Demo中的复现步骤

无

**Comment by CarGuo** [comment]
这个问题在这里  https://github.com/bilibili/DanmakuFlameMaster
