### ISSUE TITLE
如果视频状态是加载中，调用onVideoPause无效？

### ISSUE THREAD

**Issue by tangjiarao** [CarGuo/GSYVideoPlayer#333]
setup加载视频之后，此时视频加载中，马上调用onvideoPause无效，当视频加载完成就会播放

**Comment by CarGuo** [comment]
是的，你需要监听onPrepared回调，在里面做响应的处理。

**Comment by tangjiarao** [comment]
还有一个问题是当视频在播放过程中加载的时候，即调用changeUiToPlayingBufferingShow方法时，此时调用onvideoPause方法停止，会调用changeUiToPauseShow，显示停止的布局。但是可能刚好加载完成，此时会调用changeUiToPlayingShow，显示正常播放的布局。。

**Comment by CarGuo** [comment]
所以问题是？

**Comment by tangjiarao** [comment]
就是暂停时，布局会有一定几率显示成正常播放的布局，而非暂停的布局，能否让其暂停后，不再加载？

**Comment by CarGuo** [comment]
这个估计你需要继承后，重写onInfo，在缓冲结束后，super之前根据是否主动调用暂停去做处理
