### ISSUE TITLE
关于android 11 ijkplayer的问题

### ISSUE THREAD

**Issue by mathum** [CarGuo/GSYVideoPlayer#3336]
Process Name: 'com.hgsp.video'
Thread Name: 'ff_read'
pid: 32115, tid: 32278  >>> com.hgsp.video <<<
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0000000014000142
  x0   b4000074772c0400  x1   0000000000000001  x2   00000073e9488900  x3   0000000000001020
  x4   0000000014000142  x5   8080808080808080  x6   fefefefefefefeff  x7   7f7f7f7f7f7f7f7f
  x8   0101010101010101  x9   5cdeabe25eb9f593  x10  00000000ffffffff  x11  0000007477bcdab8
  x12  0000000000000003  x13  0000000000000000  x14  0000000000000070  x15  aaaaaaaaaaaaaaab
  x16  00000073f11a5388  x17  00000075105c1cf0  x18  00000073e69fa000  x19  00000073e9488900
  x20  b4000074772c0400  x21  b400007478529aa0  x22  b400007478529a40  x23  00000073e9489a68
  x24  0000000000000000  x25  0000007477093000  x26  0000000000000001  x27  00000000000fc000
  x28  00000073e9391000  x29  00000073e9489aa0  x30  00000073f0f506a0
  sp   00000073e94888c0  pc   0000000014000142  pstate 0000000000000000
  v0   00000000000000000000000000000000  v1   000000000000000043e0000000000000
  v2   0000000000000000c3e0000000000000  v3   00000000000000003ff0000000000000
  v4   80200802802008028020080280200802  v5   00000000000000000000000000000000
  v6   00000000000000000000000000000000  v7   80200802802008028020080280200802
  v8   00000000000000007ff8000000000000  v9   00000000000000003eb0c6f7a0b5ed8d
  v10  00000000000000003ff0000000000000  v11  00000000000000000000000000000000
  v12  00000000000000000000000000000000  v13  00000000000000000000000000000000
  v14  00000000000000000000000000000000  v15  00000000000000000000000000000000
  v16  40100401401004014010040140100401  v17  a00aa00aa00aa00aaaaaaaaaaaa00000
  v18  80200802802008028020080280200802  v19  000000000000000000000000ebad8083
  v20  000000000000000000000000ebad8084  v21  000000000000000000000000ebad8085
  v22  000000000000000000000000ebad8086  v23  000000000000000000000000ebad8087
  v24  000000000000000000000000ebad8088  v25  000000000000000000000000ebad8089
  v26  000000000000000000000000ebad808a  v27  000000000000000000000000ebad808b
  v28  000000000000000000000000ebad808c  v29  000000000000000000000000ebad808d
  v30  000000000000000000000000ebad808e  v31  002e0043003400420045003100330043
  fpsr 00000010  fpcr 00000000
    #00 pc 0000000001400142  [anon:dalvik-main space (region space)]
    #01 pc 00000000002c669c  /data/app/~~Bz8ItHMujZuEQnZddnl--g==/com.hgsp.video-_wevodidb86cK13DChd9tQ==/lib/arm64/libijkffmpeg.so (av_application_on_http_event+24)
--- --- ---
    --- --- --- ---

memory near x2:
    00000073e94888c0 00000073f0f50724 00000073f0f50714  $...s.......s...
    00000073e94888d0 b4000073f342e000 0000000000000000  ..B.s...........
    00000073e94888e0 b400007478529a40 b400007478529aa0  @.Rxt.....Rxt...
    00000073e94888f0 00000073f0f084d8 0000000000000000  ....s...........
    00000073e9488900 b400007478529a40 312f2f3a70747468  @.Rxt...http://1
    00000073e9488910 312e302e302e3732 682f39343538333a  27.0.0.1:38549/h
    00000073e9488920 2541332573707474 6174734632254632  ttps%3A%2F%2Fsta
    00000073e9488930 6e6169742d636974 6e7a746e2e617567  tic-tiangua.ntzn
    00000073e9488940 25706f742e74656e 3443463225764632  net.top%2Fv%2FC4
    00000073e9488950 3233453845373732 4444374433423131  277E8E3211B3D7DD
    00000073e9488960 4345463138363846 6d2e433442453133  F8681FEC31EB4C.m
    00000073e9488970 0000000000003470 0000000000000000  p4..............
    00000073e9488980 0000000000000000 0000000000000000  ................
    00000073e9488990 0000000000000000 0000000000000000  ................
    00000073e94889a0 0000000000000000 0000000000000000  ................
    00000073e94889b0 0000000000000000 0000000000000000  ................

memory near x3:
    0000000000001020 ---------------- ----------------  ................

memory near x4:
    0000000014000100 0000000000000000 0000000000000000  ................
    0000000014000110 0000000000000000 0000000000000000  ................
    0000000014000120 0000000000000000 0000000000000000  ................
    0000000014000130 0000000000000000 0000000000000000  ................
    0000000014000140 0000000000000000 0000000000000000  ................
    0000000014000150 0000000000000000 0000000000000000  ................
    0000000014000160 0000000000000000 0000000000000000  ................
    0000000014000170 0000000000000000 0000000000000000  ................
    0000000014000180 0000000000000000 0000000000000000  ................
    0000000014000190 0000000000000000 0000000000000000  ................
    00000000140001a0 0000000000000000 0000000000000000  ................
    00000000140001b0 0000000000000000 0000000000000000  ................
    00000000140001c0 0000000000000000 0000000000000000  ................
    00000000140001d0 0000000000000000 0000000000000000  ................
    00000000140001e0 0000000000000000 0000000000000000  ................
    00000000140001f0 0000000000000000 0000000000000000  ................

memory near x7:
    7f7f7f7f7f7f7f78 ---------------- ----------------  ................

memory near x8:
    0101010101010100 ---------------- ----------------  ................

memory near x9:
    5cdeabe25eb9f590 ---------------- ----------------  ................

memory near x10:
    00000000fffffff8 ---------------- ----------------  ................

memory near x11:
    0000007477bcda78 00000074785d8780 00000074785d8780  ..]xt.....]xt...
    0000007477bcda88 0000000000000000 0000000000000000  ................
    0000007477bcda98 0000000000000000 0000000000000000  ................
    0000007477bcdaa8 00000074785d2c60 00000074785d2c90  `,]xt....,]xt...
    0000007477bcdab8 00000074785d2cc0 00000074785d2cf0  .,]xt....,]xt...
    0000007477bcdac8 0000000000000000 0000000000000000  ................
    0000007477bcdad8 0000000000000000 0000000000000000  ................
    0000007477bcdae8 0000007478474fc0 00000073f342a000  .OGxt.....B.s...
    0000007477bcdaf8 00000073f342a040 00000073f342a080  @.B.s.....B.s...
    0000007477bcdb08 0000000000000000 0000000000000000  ................
    0000007477bcdb18 0000000000000000 0000000000000000  ................
    0000007477bcdb28 0000007479ffff60 0000007479ffffb0  `..yt......yt...
    0000007477bcdb38 00000073f3443000 00000073f3443050  .0D.s...P0D.s...
    0000007477bcdb48 0000000000000000 0000000000000000  ................
    0000007477bcdb58 0000000000000000 0000000000000000  ................
    0000007477bcdb68 0000000000000000 0000000000000000  ................

memory near x16:
    00000073f11a5348 00000075105c1480 0000007510ff8868  ..\.u...h...u...
    00000073f11a5358 0000007510b52198 0000007510628bb8  .!..u.....b.u...
    00000073f11a5368 000000751060223c 0000005917bc84fc  <"`.u.......Y...
    00000073f11a5378 0000007510612f40 000000751061fa38  @/a.u...8.a.u...
    00000073f11a5388 00000075105c1cf0 0000007510fe588c  ..\.u....X..u...
    00000073f11a5398 0000007510fdb230 00000075105c5518  0...u....U\.u...
    00000073f11a53a8 00000075105c776c 0000007510b52da4  lw\.u....-..u...
    00000073f11a53b8 00000075106119d0 000000751060a19c  ..a.u.....`.u...
    00000073f11a53c8 00000075106143bc 000000751061f68c  .Ca.u.....a.u...
    00000073f11a53d8 0000007510590e34 00000075105f7380  4.Y.u....s_.u...
    00000073f11a53e8 00000075105c7694 0000007510612340  .v\.u...@#a.u...
    00000073f11a53f8 0000007510620450 0000007510b51dbc  P.b.u.......u...
    00000073f11a5408 0000007510ff94e0 00000075105c518c  ....u....Q\.u...
    00000073f11a5418 000000751061d8b4 00000075105c1e60  ..a.u...`.\.u...
    00000073f11a5428 00000075105de4cc 0000007510620978  ..].u...x.b.u...
    00000073f11a5438 0000007510fe9140 0000007510ff8f3c  @...u...<...u...

memory near x17:
    00000075105c1cb0 b4fffee7d27d20e7 f8408423f8408402  . }.......@.#.@.
    00000075105c1cc0 b200d848cb0a0047 8a2800e4ca030045  G...H...E.....(.
    00000075105c1cd0 b4fffec6aa0400a6 cb03004017ffffd8  ............@...
    00000075105c1ce0 00000000d65f03c0 0000000000000000  .._.............
    00000075105c1cf0 b200c3e892402c04 5400082cf13fc09f  .,@.......?.,..T
    00000075105c1d00 cb080044a9400c02 cb080066b200d845  ..@.D...E...f...
    00000075105c1d10 ea250084b200d867 fa4008a08a2700c5  g.....%...'...@.
    00000075105c1d20 9a85308454000100 dac00c84d2800100  ...T.0..........
    00000075105c1d30 9a8033e0dac01084 d65f03c08b440c00  .....3....D..._.
    00000075105c1d40 d1004021927cec01 cb080044a9c20c22  ..|.!@.."...D...
    00000075105c1d50 aa060085cb080066 54000101ea081cbf  f..............T
    00000075105c1d60 cb080044a9410c22 aa060085cb080066  ".A.D...f.......
    00000075105c1d70 54fffea0ea081cbf b200d84591004021  .......T!@..E...
    00000075105c1d80 ea250084b200d867 fa4008a08a2700c5  g.....%...'...@.
    00000075105c1d90 9a85308454000120 dac00c84cb000020   ..T.0.. .......
    00000075105c1da0 dac0108491002005 8b440c009a853000  . .......0....D.

memory near x18:
    00000073e69f9fc0 0000000000000000 0000000000000000  ................
    00000073e69f9fd0 0000000000000000 0000000000000000  ................
    00000073e69f9fe0 0000000000000000 0000000000000000  ................
    00000073e69f9ff0 0000000000000000 0000000000000000  ................
    00000073e69fa000 0000000000000000 0000000000000000  ................
    00000073e69fa010 0000000000000000 0000000000000000  ................
    00000073e69fa020 0000000000000000 0000000000000000  ................
    00000073e69fa030 0000000000000000 0000000000000000  ................
    00000073e69fa040 0000000000000000 0000000000000000  ................
    00000073e69fa050 0000000000000000 0000000000000000  ................
    00000073e69fa060 0000000000000000 0000000000000000  ................
    00000073e69fa070 0000000000000000 0000000000000000  ................
    00000073e69fa080 0000000000000000 0000000000000000  ................
    00000073e69fa090 0000000000000000 0000000000000000  ................
    00000073e69fa0a0 0000000000000000 0000000000000000  ................
    00000073e69fa0b0 0000000000000000 0000000000000000  ................

memory near x19:
    00000073e94888c0 00000073f0f50724 00000073f0f50714  $...s.......s...
    00000073e94888d0 b4000073f342e000 0000000000000000  ..B.s...........
    00000073e94888e0 b400007478529a40 b400007478529aa0  @.Rxt.....Rxt...
    00000073e94888f0 00000073f0f084d8 0000000000000000  ....s...........
    00000073e9488900 b400007478529a40 312f2f3a70747468  @.Rxt...http://1
    00000073e9488910 312e302e302e3732 682f39343538333a  27.0.0.1:38549/h
    00000073e9488920 2541332573707474 6174734632254632  ttps%3A%2F%2Fsta
    00000073e9488930 6e6169742d636974 6e7a746e2e617567  tic-tiangua.ntzn
    00000073e9488940 25706f742e74656e 3443463225764632  net.top%2Fv%2FC4
    00000073e9488950 3233453845373732 4444374433423131  277E8E3211B3D7DD
    00000073e9488960 4345463138363846 6d2e433442453133  F8681FEC31EB4C.m
    00000073e9488970 0000000000003470 0000000000000000  p4..............
    00000073e9488980 0000000000000000 0000000000000000  ................
    00000073e9488990 0000000000000000 0000000000000000  ................
    00000073e94889a0 0000000000000000 0000000000000000  ................
    00000073e94889b0 0000000000000000 0000000000000000  ................

memory near x23:
    00000073e9489a28 b4000074773baa00 b4000074773baa10  ..;wt.....;wt...
    00000073e9489a38 00000073e9489cc0 00000074770709ac  ..H.s......wt...
    00000073e9489a48 b400007403c67000 0000007477093a28  .p..t...(:.wt...
    00000073e9489a58 b4000074773baa00 00000019773baa10  ..;wt.....;w....
    00000073e9489a68 b4000074785bb5b0 0000000000000000  ..[xt...........
    00000073e9489a78 0000000000000000 b40000747018af60  ........`..pt...
    00000073e9489a88 0000000000000000 0000000000000000  ................
    00000073e9489a98 0000000000000000 00000073e9489c50  ........P.H.s...
    00000073e9489aa8 0000007403827a20 b400007403c67008   z..t....p..t...
    00000073e9489ab8 b400007403c67020 00000073e9489cc0   p..t.....H.s...
    00000073e9489ac8 0000000000007d73 0000000000007d73  s}......s}......
    00000073e9489ad8 00000073e9489cc0 00000073e9489cc0  ..H.s.....H.s...
    00000073e9489ae8 00000073e9489ff8 00000000000fc000  ..H.s...........
    00000073e9489af8 00000073e9391000 7ff8000000000000  ..9.s...........
    00000073e9489b08 3eb0c6f7a0b5ed8d 3ff0000000000000  .......>.......?
    00000073e9489b18 0000000000000000 0000000000000000  ................

memory near x25:
    0000007477092fc0 6e6f69737265766e 747865746e6f6320  nversion context
    0000007477092fd0 000000000000000a 66203a6f65646956  ........Video: f
    0000007477092fe0 6172662074737269 646f63656420656d  irst frame decod
    0000007477092ff0 00000000000a6465 2066253d66666964  ed......diff=%f 
    0000007477093000 66253d6666696461 5f656c706d617320  adiff=%f sample_
    0000007477093010 2064253d66666964 2e30253d73747061  diff=%d apts=%0.
    0000007477093020 00000a6625206633 6320746f6e6e6143  3f %f...Cannot c
    0000007477093030 6173206574616572 74617220656c706d  reate sample rat
    0000007477093040 7265766e6f632065 20726f6620726574  e converter for 
    0000007477093050 69737265766e6f63 642520666f206e6f  conversion of %d
    0000007477093060 25207325207a4820 656e6e6168632064   Hz %s %d channe
    0000007477093070 6425206f7420736c 25207325207a4820  ls to %d Hz %s %
    0000007477093080 656e6e6168632064 000000000a21736c  d channels!.....
    0000007477093090 6d5f7265746e6563 6c6576656c5f7869  center_mix_level
    00000074770930a0 0000000000000000 6c706d61735f7661  ........av_sampl
    00000074770930b0 625f7465675f7365 69735f7265666675  es_get_buffer_si

memory near x27:
    00000000000fc000 ---------------- ----------------  ................

memory near x28:
    00000073e9390fc0 0000000000000000 0000000000000000  ................
    00000073e9390fd0 0000000000000000 0000000000000000  ................
    00000073e9390fe0 0000000000000000 0000000000000000  ................
    00000073e9390ff0 0000000000000000 0000000000000000  ................
    00000073e9391000 0000000000000000 0000000000000000  ................
    00000073e9391010 0000000000000000 0000000000000000  ................
    00000073e9391020 0000000000000000 0000000000000000  ................
    00000073e9391030 0000000000000000 0000000000000000  ................
    00000073e9391040 0000000000000000 0000000000000000  ................
    00000073e9391050 0000000000000000 0000000000000000  ................
    00000073e9391060 0000000000000000 0000000000000000  ................
    00000073e9391070 0000000000000000 0000000000000000  ................
    00000073e9391080 0000000000000000 0000000000000000  ................
    00000073e9391090 0000000000000000 0000000000000000  ................
    00000073e93910a0 0000000000000000 0000000000000000  ................
    00000073e93910b0 0000000000000000 0000000000000000  ................

memory near x29:
    00000073e9489a60 00000019773baa10 b4000074785bb5b0  ..;w......[xt...
    00000073e9489a70 0000000000000000 0000000000000000  ................
    00000073e9489a80 b40000747018af60 0000000000000000  `..pt...........
    00000073e9489a90 0000000000000000 0000000000000000  ................
    00000073e9489aa0 00000073e9489c50 0000007403827a20  P.H.s... z..t...
    00000073e9489ab0 b400007403c67008 b400007403c67020  .p..t... p..t...
    00000073e9489ac0 00000073e9489cc0 0000000000007d73  ..H.s...s}......
    00000073e9489ad0 0000000000007d73 00000073e9489cc0  s}........H.s...
    00000073e9489ae0 00000073e9489cc0 00000073e9489ff8  ..H.s.....H.s...
    00000073e9489af0 00000000000fc000 00000073e9391000  ..........9.s...
    00000073e9489b00 7ff8000000000000 3eb0c6f7a0b5ed8d  ...............>
    00000073e9489b10 3ff0000000000000 0000000000000000  .......?........
    00000073e9489b20 0000000000000000 0000000000000000  ................
    00000073e9489b30 0000000000000000 0000000000000000  ................
    00000073e9489b40 0000000000000000 0000000000000000  ................
    00000073e9489b50 0000000000000000 0000000000000000  ................

code around pc:
    0000000014000100 0000000000000000 0000000000000000  ................
    0000000014000110 0000000000000000 0000000000000000  ................
    0000000014000120 0000000000000000 0000000000000000  ................
    0000000014000130 0000000000000000 0000000000000000  ................
    0000000014000140 0000000000000000 0000000000000000  ................
    0000000014000150 0000000000000000 0000000000000000  ................
    0000000014000160 0000000000000000 0000000000000000  ................
    0000000014000170 0000000000000000 0000000000000000  ................
    0000000014000180 0000000000000000 0000000000000000  ................
    0000000014000190 0000000000000000 0000000000000000  ................
    00000000140001a0 0000000000000000 0000000000000000  ................
    00000000140001b0 0000000000000000 0000000000000000  ................
    00000000140001c0 0000000000000000 0000000000000000  ................
    00000000140001d0 0000000000000000 0000000000000000  ................
    00000000140001e0 0000000000000000 0000000000000000  ................
    00000000140001f0 0000000000000000 0000000000000000  ................

code around lr:
    00000073f0f50660 b40000a1f9400001 aa0103e0aa0003f3  ..@.............
    00000073f0f50670 f900027f97fffff8 910043ffa9407bf3  .........{@..C..
    00000073f0f50680 d10043ffd65f03c0 b40000a0f90003fe  .._..C..........
    00000073f0f50690 b4000064f9400804 d63f0080d2820403  ..@.d.........?.
    00000073f0f506a0 910043fff94003fe d14007ffd65f03c0  ..@..C...._...@.
    00000073f0f506b0 d100c3ffd10083ff 9100c3f3a90053f3  .........S......
    00000073f0f506c0 a9015bf5aa0003f4 aa0103f6aa1303e0  .....[..........
    00000073f0f506d0 52800001aa0203f5 f90013fed2820402  .......R........
    00000073f0f506e0 eb1f02df97f7c280 eb1f02bf1a9f17e1  ................
    00000073f0f506f0 2a0000201a9f17e0 b400015435000160  .... ..*`..5T...
    00000073f0f50700 aa1503e1aa1303e0 f8008416d2820002  ................
    00000073f0f50710 aa1403e0940002db aa1303e252800021  ........!..R....
    00000073f0f50720 a94053f397ffffd9 f94013fea9415bf5  .....S@..[A...@.
    00000073f0f50730 910083ff9100c3ff d65f03c0914007ff  ..........@..._.
    00000073f0f50740 d10083ffd14007ff a90053f3d10103ff  ..@..........S..
    00000073f0f50750 aa0003f4910103f3 aa1303e0a9015bf5  .........[......

stack:
    00000073e9488840:  0000000000000000 0000000000000000 
    00000073e9488850:  0000000000000000 0000000000000000 
    00000073e9488860:  0000000000000000 0000000000000000 
    00000073e9488870:  0000000000000000 0000000000000000 
    00000073e9488880:  0000000000000000 0000000000000000 
    00000073e9488890:  0000000000000000 0000000000000000 
    00000073e94888a0:  0000000000000000 0000000000000000 
    00000073e94888b0:  0000000000000000 0000000000000000 
    00000073e94888c0:  00000073f0f50724 00000073f0f50714   #sp
    00000073e94888d0:  b4000073f342e000 0000000000000000 
    00000073e94888e0:  b400007478529a40 b400007478529aa0 
    00000073e94888f0:  00000073f0f084d8 0000000000000000 
    00000073e9488900:  b400007478529a40 312f2f3a70747468 
    00000073e9488910:  312e302e302e3732 682f39343538333a 
    00000073e9488920:  2541332573707474 6174734632254632 
    00000073e9488930:  6e6169742d636974 6e7a746e2e617567 
    00000073e9488940:  25706f742e74656e 3443463225764632 
    00000073e9488950:  3233453845373732 4444374433423131 
    00000073e9488960:  4345463138363846 6d2e433442453133 
    00000073e9488970:  0000000000003470 0000000000000000 
    00000073e9488980:  0000000000000000 0000000000000000 
    00000073e9488990:  0000000000000000 0000000000000000 
    00000073e94889a0:  0000000000000000 0000000000000000 
    00000073e94889b0:  0000000000000000 0000000000000000 
    00000073e94889c0:  0000000000000000 0000000000000000 
    00000073e94889d0:  0000000000000000 0000000000000000 
    00000073e94889e0:  0000000000000000 0000000000000000 
    00000073e94889f0:  0000000000000000 0000000000000000 
    00000073e9488a00:  0000000000000000 0000000000000000 
    00000073e9488a10:  0000000000000000 0000000000000000 
    00000073e9488a20:  0000000000000000 0000000000000000 
    00000073e9488a30:  0000000000000000 0000000000000000 
    00000073e9488a40:  0000000000000000 0000000000000000 
    00000073e9488a50:  0000000000000000 0000000000000000 
    00000073e9488a60:  0000000000000000 0000000000000000 
    00000073e9488a70:  0000000000000000 0000000000000000 
    00000073e9488a80:  0000000000000000 0000000000000000 
    00000073e9488a90:  0000000000000000 0000000000000000 
    00000073e9488aa0:  0000000000000000 0000000000000000 
    00000073e9488ab0:  0000000000000000 0000000000000000 
    00000073e9488ac0:  0000000000000000 0000000000000000 
    00000073e9488ad0:  0000000000000000 0000000000000000 
    00000073e9488ae0:  0000000000000000 0000000000000000 
    00000073e9488af0:  0000000000000000 0000000000000000 
[DEBUG] reach max continuously zero line count: 24!
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

/data/app/~~Bz8ItHMujZuEQnZddnl--g==/com.hgsp.video-_wevodidb86cK13DChd9tQ==/lib/arm64/libijkffmpeg.so: (no build id)
/data/app/~~Bz8ItHMujZuEQnZddnl--g==/com.hgsp.video-_wevodidb86cK13DChd9tQ==/lib/arm64/libijksdl.so: c8387dbed4f7a79d30608b2d5d9ce6a768be4ebe
/data/app/~~Bz8ItHMujZuEQnZddnl--g==/com.hgsp.video-_wevodidb86cK13DChd9tQ==/lib/arm64/libumeng-spy.so: f997baddb2d7513a9134b95ec80dbb5f51dc2a54
/data/app/~~Bz8ItHMujZuEQnZddnl--g==/com.hgsp.video-_wevodidb86cK13DChd9tQ==/lib/arm64/libcrashsdk.so: 9ca3e3d40ebf28789a05bfeed7513668287a564e
/data/app/~~Bz8ItHMujZuEQnZddnl--g==/com.hgsp.video-_wevodidb86cK13DChd9tQ==/lib/arm64/libc++_shared.so: e9bcaa7efce852dbb45ab35ac1b87caf79e9a953
/data/app/~~Bz8ItHMujZuEQnZddnl--g==/com.hgsp.video-_wevodidb86cK13DChd9tQ==/lib/arm64/libijkplayer.so: 3b1931298170cd5bbce2258ce0d7d1c8a8190e56
/data/app/~~Bz8ItHMujZuEQnZddnl--g==/com.hgsp.video-_wevodidb86cK13DChd9tQ==/lib/arm64/libmmkv.so: d732cf62d22e672cfd09bf363073bb1bf0333324
/data/app/~~Bz8ItHMujZuEQnZddnl--g==/com.hgsp.video-_wevodidb86cK13DChd9tQ==/lib/arm64/lib39285EFA.so: (no build id)

请问作者遇到了吗

**Comment by CarGuo** [comment]
已经修复了，新版
