### ISSUE TITLE
如何获取精确到毫秒的当前播放时间

### ISSUE THREAD

**Issue by SkyD666** [CarGuo/GSYVideoPlayer#3340]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

如何获取精确到毫秒的当前播放时间

## 问题机型/系统：

HONOR V20

## GSY依赖版本

`implementation 'com.shuyu:GSYVideoPlayer:8.1.0'`

## Demo中的复现步骤

DanmakuVideoPlayer.java文件的136行onSeekComplete方法。获取当前时间用的是int time = mProgressBar.getProgress() * getDuration() / 100;   但是这个获取出来非常不精确（因为Progress只能是0-100），导致改变播放进度时，在第0至16秒都是相同的弹幕

问题代码：(如果有)
```
 @Override
    public void onSeekComplete() {
        super.onSeekComplete();
        int time = mProgressBar.getProgress() * getDuration() / 100;
        //如果已经初始化过的，直接seek到对于位置
        if (mHadPlay && getDanmakuView() != null && getDanmakuView().isPrepared()) {
            resolveDanmakuSeek(this, time);
        } else if (mHadPlay && getDanmakuView() != null && !getDanmakuView().isPrepared()) {
            //如果没有初始化过的，记录位置等待
            setDanmakuStartSeekPosition(time);
        }
    }

```

**Comment by CarGuo** [comment]
这个是 demo ，你自己控制修改就行了，比例模式你可以自己控制
