### ISSUE TITLE
列表播放调用notifyItemChanged时黑屏

### ISSUE THREAD

**Issue by ybZha** [CarGuo/GSYVideoPlayer#3342]
你好，在使用viewpager2列表时，调用 adapter.notifyItemChanged(position);时播放器黑屏并且显示了加载动画和mThumbImageViewLayout UI显示了，我尝试在holder的onBing拦截刷新，但还是不行，望指教
 ` public void onBind(final int position, Object videoModel) {
         int  playPosition = GSYVideoManager.instance().getPlayPosition();
        if (playPosition==position){
            //gsyVideoPlayer.setCurrentState(2);
            gsyVideoPlayer.changeUiToPlayingBufferingClear();
            gsyVideoPlayer.clickStartIcon();
            return;
        }
          gsyVideoOptionBuilder...  
    }`

**Comment by CarGuo** [comment]
应该是触发了 normal 的状态了
