### ISSUE TITLE
全局播放缩回窗口播放默认是竖屏请问能否取消强制

### ISSUE THREAD

**Issue by zcl947694252** [CarGuo/GSYVideoPlayer#3344]
## 问题描述：打开全屏播放后再次点击全屏按钮变回窗口播放 会将activity的横屏模式强制转为竖屏,请问有没有方法禁止全屏缩回后强制竖屏

XXXX发生了这样的问题！

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack'

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2955
