### ISSUE TITLE
播放当前视频，会有0.2左右播放上一个视频的声音

### ISSUE THREAD

**Issue by zhangmengjia** [CarGuo/GSYVideoPlayer#3345]
## 问题描述：

在项目中接入viewpager2列表，需求是外面是一个视频列表，点击进入viewpager2页面，当前点击的视频在viewpager2第一个位置。出现点击视频，进入viewpager2页面时 有时会有0.2s左右上一个视频的声音。

## 问题机型/系统：
Honor v10   BKL-AL20  android10
## GSY依赖版本
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack'

## Demo中的复现步骤

demo中没有这种需求

**Comment by CarGuo** [comment]
这个我也没什么想法，推荐你在上一个视频划出一点的时候，设置它静音

**Comment by zhangmengjia** [comment]
> 这个我也没什么想法，推荐你在上一个视频划出一点的时候，设置它静音

是返回上一级的视频list,再点击list列表其中的一个，会有上个视频的声音，返回的时候资源什么的都释放了，我再想是不是视频缓存的问题

**Comment by CarGuo** [comment]
如果释放了的话，你看 PlayerManager 是不是已经 release 了对应的 MediaPlayer ，因为我这边测试没发现问题

**Comment by zhangmengjia** [comment]
> 如果释放了的话，你看 PlayerManager 是不是已经 release 了对应的 MediaPlayer ，因为我这边测试没发现问题

上个视频的声音只有0.2s左右，然后就正常播放当前的视频了。我这边是点击视频list列表进入的是viewpager2页面

**Comment by zhangmengjia** [comment]
> 如果释放了的话，你看 PlayerManager 是不是已经 release 了对应的 MediaPlayer ，因为我这边测试没发现问题

你说的“PlayerManager 是不是已经 release 了对应的 MediaPlayer”，这个怎么看？

**Comment by CarGuo** [comment]
debug 对应的 PlayerManager 源码啊
