### ISSUE TITLE
关于播放腾讯云直播回访视频

### ISSUE THREAD

**Issue by chaofanxu** [CarGuo/GSYVideoPlayer#3346]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

利用StandardGSYVideoPlayer播放腾讯云直播的回放视频，发生了secondaryProgress  无法达到百分百 这样的问题！

## 问题机型/系统：

任何机型

## GSY依赖版本

      api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack'

## Demo中的复现步骤

Demo中的DetailNormalActivityPlayer页面打开后将getUrl()方法的rul 替换成“http://1500005109.vod2.myqcloud.com/6c9a32f7vodcq1500005109/9ced05fe3701925921350828152/playlist.m3u8”会出现这个问题。(注意看SeekBar或者ProgressBar的缓存进度条，无法达到百分百， 拖动到无缓冲的地方 ，播放时间不会变)

**Comment by CarGuo** [comment]
有些视频没办法显示 100%  是 ijk 下正常的已知问题， 但是拖动不会重新buffer ？这个不理解

**Comment by chaofanxu** [comment]
您有联系方式吗  我可以录个视频给您看看  这样比较好理解

**Comment by chaofanxu** [comment]
> 有些视频没办法显示 100% 是 ijk 下正常的已知问题， 但是拖动不会重新buffer ？这个不理解

您有联系方式吗 我可以录个视频给您看看 这样比较好理解

**Comment by CarGuo** [comment]
你可以直接上传附件到 issue 的，压缩成 zip
