### ISSUE TITLE
你好，关于自定义界面。

### ISSUE THREAD

**Issue by yovenny** [CarGuo/GSYVideoPlayer#335]
如果我想做成快手那样比较简洁的播放器的控制器，没有进度，声音，亮度调节，是不是我要自己写？
看下库的代码，好像不容易拓展。

是不是仿造一个？

**Comment by yovenny** [comment]
有个问题问下？
 GSYBaseVideoPlayer extends FrameLayout类似这个播放器view，ontouch reture false ,配合demo中的WebDetailActivity能使播放器+webview一起滚上去吗？
好像理论是可以？

**Comment by CarGuo** [comment]
是需要在这个基础上做一些兼容……这个后面我增加一个兼容吧，目前只能自己自己修改。
