### ISSUE TITLE
如何预缓存视频？

### ISSUE THREAD

**Issue by HalyangDream** [CarGuo/GSYVideoPlayer#3351]
## 问题描述：

类似抖音播放，为了提高视频播放的速度，想要预先缓存几个视频

## 问题机型/系统：

真题 Google Pixel3 Android 11

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'

## Demo中的复现步骤

可以开放缓存的代码吗？

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by HalyangDream** [comment]
已经解决啦

**Comment by xuyingke** [comment]
如果你通过 CacheFactory.setCacheManager(ProxyCacheManager.class); 设置了缓存。那么，你可以用 http 直接请求 url 来预缓存。

鉴于缓存目录的方法是私有的，得反射：

 Method getCacheFile = proxy.getClass()
                        .getDeclaredMethod("getCacheFile", String.class);
                getCacheFile.setAccessible(true);
                File cacheFile = (File) getCacheFile.invoke(proxy, proxyUrl);
              

如果你项目中之前没有用 HttpProxyCacheServer 那么上面就是答案了。否则看下面。↓

要注意的是 GSY 是用 ProxyCacheManager.getProxy(App.getInstance().getApplicationContext(), null) 来使用的。你获取 http 预加载时的 url 最好也用这个方法去获取缓存目录。

**Comment by HalyangDream** [comment]
> 如果你通过 CacheFactory.setCacheManager(ProxyCacheManager.class); 设置了缓存。那么，你可以用 http 直接请求 url 来预缓存。
> 
> 鉴于缓存目录的方法是私有的，得反射：
> 
> Method getCacheFile = proxy.getClass()
> .getDeclaredMethod("getCacheFile", String.class);
> getCacheFile.setAccessible(true);
> File cacheFile = (File) getCacheFile.invoke(proxy, proxyUrl);
> 
> 如果你项目中之前没有用 HttpProxyCacheServer 那么上面就是答案了。否则看下面。↓
> 
> 要注意的是 GSY 是用 ProxyCacheManager.getProxy(App.getInstance().getApplicationContext(), null) 来使用的。你获取 http 预加载时的 url 最好也用这个方法去获取缓存目录。

我使用就是默认的缓存目录；
我就是通过http直接请求url获取缓存的

**Comment by yuanhua0608** [comment]
> > 如果你通过 CacheFactory.setCacheManager(ProxyCacheManager.class); 设置了缓存。那么，你可以用 http 直接请求 url 来预缓存。
> > 鉴于缓存目录的方法是私有的，得反射：
> > Method getCacheFile = proxy.getClass()
> > .getDeclaredMethod("getCacheFile", String.class);
> > getCacheFile.setAccessible(true);
> > File cacheFile = (File) getCacheFile.invoke(proxy, proxyUrl);
> > 如果你项目中之前没有用 HttpProxyCacheServer 那么上面就是答案了。否则看下面。↓
> > 要注意的是 GSY 是用 ProxyCacheManager.getProxy(App.getInstance().getApplicationContext(), null) 来使用的。你获取 http 预加载时的 url 最好也用这个方法去获取缓存目录。
> 
> 我使用就是默认的缓存目录； 我就是通过http直接请求url获取缓存的

为什么我缓存目录里有视频了之后，还是没法直接加载视频呢？

**Comment by qulj** [comment]
> 已经解决啦

请教下是 用的什么方法呢？
