### ISSUE TITLE
4.4.2版本，循环播放时会黑屏闪一下

### ISSUE THREAD

**Issue by SvenScum** [CarGuo/GSYVideoPlayer#3353]
## 问题描述：

4.4.2版本，循环播放时会黑屏闪一下，有的机顶盒子不会，有的会

## 问题机型/系统：

真机，陕西机顶盒

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack'

**Comment by CarGuo** [comment]
4.4.2……这个真的没有支持的计划的！！！
加油，I have no idea
