### ISSUE TITLE
编译失败 Could not find net.butterflytv.utils:rtmp-client:3.1.0.

### ISSUE THREAD

**Issue by masite** [CarGuo/GSYVideoPlayer#3354]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

 Could not find net.butterflytv.utils:rtmp-client:3.1.0.

## 问题机型/系统：

华为

## GSY依赖版本

api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack'

## Demo中的复现步骤

编译时

Required by:
         project :app > com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.5-jitpack > com.google.android.exoplayer:extension-rtmp:2.14.0

```

**Comment by CarGuo** [comment]
google()
        mavenCentral()
