### ISSUE TITLE
能否支持rtsp边播边缓存功能

### ISSUE THREAD

**Issue by fynnkong** [CarGuo/GSYVideoPlayer#3356]
## 问题描述：

在rtsp流播放过程中，希望缓存流到本地，后期需要回放视频
在使用库过程中，发现并不支持rtsp rtmp等协议缓存,能否支持这些协议的缓存功能

## GSY依赖版本

    implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

**Comment by CarGuo** [comment]
不支持
