### ISSUE TITLE
设置视频从哪里开始播放，前几秒有跳动问题 请指教一下大佬

### ISSUE THREAD

**Issue by roger54920** [CarGuo/GSYVideoPlayer#3359]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

指定播放进度，在哪里开始播放，调用setSeekOnStart 此方法（有解释说：目前有时候前几秒有跳动问题，毫秒），跳动的次数也挺频繁的，有时候10秒以内，直接变为0秒 ，请问下怎么可以避免 跳动问题，或者通过什么方法能解决这个问题呢？请指教一下大佬

## 问题机型/系统：

 真机 Redmi Note 8 pro  Android10

## GSY依赖版本

例如 `implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/black"
    tools:context=".ui.home.GSYVideoPlayerActivity">
    <com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
        android:id="@+id/my_gsy"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
</LinearLayout>

public class GSYVideoPlayerActivity extends BaseActivity<ActivityGsyVideoPlayerBinding> {
    private OrientationUtils orientationUtils;
    private long videoProgress = 0;
    private boolean isPlaying = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    protected void initView() {
        super.initView();
        baseHandler = new Handler();
        viewBinding.myGsy.setUp(getIntent().getStringExtra("videoUrl"), true, getIntent().getStringExtra("videoTitle"));
        if (!TextUtils.isEmpty(getIntent().getStringExtra("videoProgress"))) {
            videoProgress = (long) (Double.parseDouble(getIntent().getStringExtra("videoProgress")) * 1000);
        }
        //从哪里开始播放 此处
        viewBinding.myGsy.setSeekOnStart(videoProgress);
        viewBinding.myGsy.startPlayLogic();
        //设置旋转
        orientationUtils = new OrientationUtils(this, viewBinding.myGsy);
        //设置全屏按键
        viewBinding.myGsy.getFullscreenButton().setImageResource(R.mipmap.icon_video_switch);
        viewBinding.myGsy.setEnlargeImageRes(R.mipmap.icon_video_switch);
        viewBinding.myGsy.setShrinkImageRes(R.mipmap.icon_video_switch);
        viewBinding.myGsy.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                orientationUtils.resolveByClick();
            }
        });
        viewBinding.myGsy.getBackButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(SystemUtils.isFastClick()){
                    returnHome();
                }
            }
        });
    }

    @Override
    protected void onPause() {
        super.onPause();
        viewBinding.myGsy.onVideoPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        ImmersionBar.with(this).titleBarMarginTop(viewBinding.myGsy).statusBarDarkFont(false).init();
        viewBinding.myGsy.onVideoResume();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (baseHandler != null) {
            baseHandler.removeCallbacksAndMessages(null);
        }
        GSYVideoManager.releaseAllVideos();
        if (orientationUtils != null)
            orientationUtils.releaseListener();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK && event.getAction() == KeyEvent.ACTION_DOWN) {
            returnHome();
            return true;
        }
        return super.onKeyDown(keyCode, event);
    }

    /**
     * 返回首页
     */
    private void returnHome() {
        intent = new Intent();
        double currentPositionWhenPlaying = viewBinding.myGsy.getCurrentPositionWhenPlaying();
        intent.putExtra("gsyVideoProgress", currentPositionWhenPlaying / 1000);
        setResult(Constants.TWO_HUNDRED, intent);
        finish();
    }

    @Override
    public void onBackPressed() {
        //先返回正常状态
        if (orientationUtils.getScreenType() == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
            viewBinding.myGsy.getFullscreenButton().performClick();
            return;
        }
        //释放所有
        viewBinding.myGsy.setVideoAllCallBack(null);
        super.onBackPressed();
    }
}

## 问题log（如果有）

```

## 调用的方法

```

**Comment by CarGuo** [comment]
问题集锦

**Comment by roger54920** [comment]
您好，我通过 问题集锦 里面的方法进行了修改，还是会出现之前的情况   
问题集锦的方法：
 VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", (int) videoProgress);
        vomlist = new ArrayList<>();
        vomlist.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(vomlist);



代码如下：
package com.example.jiuzhuclient.ui.home;

import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.os.Bundle;
import android.os.Handler;
import android.text.TextUtils;
import android.view.KeyEvent;
import android.view.View;

import androidx.recyclerview.widget.GridLayoutManager;

import com.example.jiuzhuclient.R;
import com.example.jiuzhuclient.base.BaseActivity;
import com.example.jiuzhuclient.databinding.ActivityGsyVideoPlayerBinding;
import com.example.jiuzhuclient.http.Constants;
import com.example.jiuzhuclient.utils.LogFactory;
import com.example.jiuzhuclient.utils.SystemUtils;
import com.gyf.immersionbar.ImmersionBar;
import com.shuyu.gsyvideoplayer.GSYVideoManager;
import com.shuyu.gsyvideoplayer.listener.GSYMediaPlayerListener;
import com.shuyu.gsyvideoplayer.listener.GSYVideoProgressListener;
import com.shuyu.gsyvideoplayer.listener.VideoAllCallBack;
import com.shuyu.gsyvideoplayer.model.VideoOptionModel;
import com.shuyu.gsyvideoplayer.utils.OrientationUtils;
import com.umeng.commonsdk.debug.I;
import com.youth.banner.util.BannerUtils;

import java.util.ArrayList;
import java.util.List;

import tv.danmaku.ijk.media.player.IMediaPlayer;
import tv.danmaku.ijk.media.player.IjkMediaPlayer;

/**
 * 课程视频播放
 */
public class GSYVideoPlayerActivity extends BaseActivity<ActivityGsyVideoPlayerBinding> {
    private OrientationUtils orientationUtils;
    private long videoProgress = 0;
    private boolean isPlaying = false;
    private List<VideoOptionModel> vomlist;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    protected void initView() {
        super.initView();
        viewBinding.myGsy.setUp(getIntent().getStringExtra("videoUrl"), true, getIntent().getStringExtra("videoTitle"));
        if (!TextUtils.isEmpty(getIntent().getStringExtra("videoProgress"))) {
            videoProgress = (long) (Double.parseDouble(getIntent().getStringExtra("videoProgress")) * 1000);
        }
        //从哪里开始播放
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", (int) videoProgress);
        vomlist = new ArrayList<>();
        vomlist.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(vomlist);
        viewBinding.myGsy.startPlayLogic();

        viewBinding.myGsy.setGSYVideoProgressListener(new GSYVideoProgressListener() {
            @Override
            public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
                if(videoProgress==currentPosition){
                    vomlist.clear();
                }
            }
        });
        //设置旋转
        orientationUtils = new OrientationUtils(this, viewBinding.myGsy);
        //设置全屏按键
        viewBinding.myGsy.getFullscreenButton().setImageResource(R.mipmap.icon_video_switch);
        viewBinding.myGsy.setEnlargeImageRes(R.mipmap.icon_video_switch);
        viewBinding.myGsy.setShrinkImageRes(R.mipmap.icon_video_switch);
        viewBinding.myGsy.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                orientationUtils.resolveByClick();
            }
        });
        viewBinding.myGsy.getBackButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(SystemUtils.isFastClick()){
                    returnHome();
                }
            }
        });
    }

    @Override
    protected void onPause() {
        super.onPause();
        viewBinding.myGsy.onVideoPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        ImmersionBar.with(this).titleBarMarginTop(viewBinding.myGsy).statusBarDarkFont(false).init();
        viewBinding.myGsy.onVideoResume();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        GSYVideoManager.releaseAllVideos();
        if (orientationUtils != null)
            orientationUtils.releaseListener();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK && event.getAction() == KeyEvent.ACTION_DOWN) {
            returnHome();
            return true;
        }
        return super.onKeyDown(keyCode, event);
    }

    /**
     * 返回首页
     */
    private void returnHome() {
        intent = new Intent();
        double currentPositionWhenPlaying = viewBinding.myGsy.getCurrentPositionWhenPlaying();
        intent.putExtra("gsyVideoProgress", currentPositionWhenPlaying / 1000);
        setResult(Constants.TWO_HUNDRED, intent);
        finish();
    }

    @Override
    public void onBackPressed() {
        //先返回正常状态
        if (orientationUtils.getScreenType() == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
            viewBinding.myGsy.getFullscreenButton().performClick();
            return;
        }
        //释放所有
        viewBinding.myGsy.setVideoAllCallBack(null);
        super.onBackPressed();
    }
}

**Comment by roger54920** [comment]
> 看问题集锦
您好，我通过问题集锦里面的方法进行了修改，还是会出现之前的情况
问题集锦的方法：
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", (int) videoProgress);
vomlist = 新的 ArrayList<>();
vomlist.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(vomlist);

代码如下：

/**

课程视频播放
*/
public class GSYVideoPlayerActivity extends BaseActivity {
private OrientationUtilsorientationUtils;
私人长视频Progress = 0;
私人布尔 isPlaying = false;
私人列表 vomlist；
@override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
}

@override
protected void initView() {
super.initView();
viewBinding.myGsy.setUp(getIntent().getStringExtra("videoUrl"), true, getIntent().getStringExtra("videoTitle"));
if (!TextUtils.isEmpty(getIntent().getStringExtra("videoProgress"))) {
videoProgress = (long) (Double.parseDouble(getIntent().getStringExtra("videoProgress")) * 1000);
}
//从哪里开始
playVideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", (int) videoProgress);
vomlist = 新的 ArrayList<>();
vomlist.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(vomlist);
viewBinding.myGsy.startPlayLogic();

 viewBinding.myGsy.setGSYVideoProgressListener(new GSYVideoProgressListener() {
     @Override
     public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
         if(videoProgress==currentPosition){
             vomlist.clear();
         }
     }
 });
 //设置旋转
 orientationUtils = new OrientationUtils(this, viewBinding.myGsy);
 //设置全屏按键
 viewBinding.myGsy.getFullscreenButton().setImageResource(R.mipmap.icon_video_switch);
 viewBinding.myGsy.setEnlargeImageRes(R.mipmap.icon_video_switch);
 viewBinding.myGsy.setShrinkImageRes(R.mipmap.icon_video_switch);
 viewBinding.myGsy.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
     @Override
     public void onClick(View v) {
         orientationUtils.resolveByClick();
     }
 });
 viewBinding.myGsy.getBackButton().setOnClickListener(new View.OnClickListener() {
     @Override
     public void onClick(View v) {
         if(SystemUtils.isFastClick()){
             returnHome();
         }
     }
 });
}

@override
protected void onPause() {
super.onPause();
viewBinding.myGsy.onVideoPause();
}

@override
protected void onResume() {
super.onResume();
ImmersionBar.with(this).titleBarMarginTop(viewBinding.myGsy).statusBarDarkFont(false).init();
viewBinding.myGsy.onVideoResume();
}

@override
protected void onDestroy() {
super.onDestroy();
GSYVideoManager.releaseAllVideos();
if (orientationUtils != null)
orientationUtils.releaseListener();
}

@override
public boolean onKeyDown(int keyCode, KeyEvent event) {
if (keyCode == KeyEvent.KEYCODE_BACK && event.getAction() == KeyEvent.ACTION_DOWN) {
returnHome();
返回真；
}
return super.onKeyDown(keyCode, event);
}

/**

返回首页
*/
private void returnHome() {
intent = new Intent();
double currentPositionWhenPlaying = viewBinding.myGsy.getCurrentPositionWhenPlaying();
intent.putExtra("gsyVideoProgress", currentPositionWhenPlaying / 1000);
setResult(Constants.TWO_HUNDRED, 意图);
结束（）;
}
@override
public void onBackPressed() {
//先返回正常状态
if (orientationUtils.getScreenType() == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
viewBinding.myGsy.getFullscreenButton().performClick();
返回;
}
//释放所有
viewBinding.myGsy.setVideoAllCallBack(null);
super.onBackPressed();
}
}

**Comment by roger54920** [comment]
> 看问题集锦
您好，我通过 问题集锦 里面的方法进行了修改，还是会出现之前的情况
问题集锦的方法：
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", (int) videoProgress);
vomlist = new ArrayList<>();
vomlist.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(vomlist);

代码如下：

/**

课程视频播放
*/
public class GSYVideoPlayerActivity extends BaseActivity {
private OrientationUtils orientationUtils;
private long videoProgress = 0;
private boolean isPlaying = false;
private List vomlist;
@override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
}

@override
protected void initView() {
super.initView();
viewBinding.myGsy.setUp(getIntent().getStringExtra("videoUrl"), true, getIntent().getStringExtra("videoTitle"));
if (!TextUtils.isEmpty(getIntent().getStringExtra("videoProgress"))) {
videoProgress = (long) (Double.parseDouble(getIntent().getStringExtra("videoProgress")) * 1000);
}
//从哪里开始播放
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", (int) videoProgress);
vomlist = new ArrayList<>();
vomlist.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(vomlist);
viewBinding.myGsy.startPlayLogic();

 viewBinding.myGsy.setGSYVideoProgressListener(new GSYVideoProgressListener() {
     @Override
     public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
         if(videoProgress==currentPosition){
             vomlist.clear();
         }
     }
 });
 //设置旋转
 orientationUtils = new OrientationUtils(this, viewBinding.myGsy);
 //设置全屏按键
 viewBinding.myGsy.getFullscreenButton().setImageResource(R.mipmap.icon_video_switch);
 viewBinding.myGsy.setEnlargeImageRes(R.mipmap.icon_video_switch);
 viewBinding.myGsy.setShrinkImageRes(R.mipmap.icon_video_switch);
 viewBinding.myGsy.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
     @Override
     public void onClick(View v) {
         orientationUtils.resolveByClick();
     }
 });
 viewBinding.myGsy.getBackButton().setOnClickListener(new View.OnClickListener() {
     @Override
     public void onClick(View v) {
         if(SystemUtils.isFastClick()){
             returnHome();
         }
     }
 });
}

@override
protected void onPause() {
super.onPause();
viewBinding.myGsy.onVideoPause();
}

@override
protected void onResume() {
super.onResume();
ImmersionBar.with(this).titleBarMarginTop(viewBinding.myGsy).statusBarDarkFont(false).init();
viewBinding.myGsy.onVideoResume();
}

@override
protected void onDestroy() {
super.onDestroy();
GSYVideoManager.releaseAllVideos();
if (orientationUtils != null)
orientationUtils.releaseListener();
}

@override
public boolean onKeyDown(int keyCode, KeyEvent event) {
if (keyCode == KeyEvent.KEYCODE_BACK && event.getAction() == KeyEvent.ACTION_DOWN) {
returnHome();
return true;
}
return super.onKeyDown(keyCode, event);
}

/**

返回首页
*/
private void returnHome() {
intent = new Intent();
double currentPositionWhenPlaying = viewBinding.myGsy.getCurrentPositionWhenPlaying();
intent.putExtra("gsyVideoProgress", currentPositionWhenPlaying / 1000);
setResult(Constants.TWO_HUNDRED, intent);
finish();
}
@override
public void onBackPressed() {
//先返回正常状态
if (orientationUtils.getScreenType() == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
viewBinding.myGsy.getFullscreenButton().performClick();
return;
}
//释放所有
viewBinding.myGsy.setVideoAllCallBack(null);
super.onBackPressed();
}
}

**Comment by kyriej** [comment]
用Exo ，精准定位

**Comment by CarGuo** [comment]
如果用 enable-accurate-seek 不行，就切换 PlayerFactory.setPlayManager(Exo2PlayerManager.class); 试试，如果还不行就是视频的关键帧有问题
