### ISSUE TITLE
视频播放时不息屏,无法遵从系统设置的息屏规则(特殊需求)

### ISSUE THREAD

**Issue by 985541238** [CarGuo/GSYVideoPlayer#3362]
## 问题描述：

这个问题是需求比较特殊,客户要求首页banner能轮播视频和图片,功能已经封装完成,播放器用的就是我们的gsyVideoPlayer
但是使用后有一个问题,当轮播图轮播到视频,系统的息屏规则就会失效(这里如果是普通的视频播放需求,肯定是正常的)但我这个因为在banner上播放比较特殊,如果不息屏,用户只要不退出首页 ,就会一直不息屏

现在想求助下,问下大佬们有没有相关的方法,让播放器遵从系统设置的息屏规则

**Comment by CarGuo** [comment]
不好意思，前两个星期手术住院了，如果是默认 IJKPlayerManager 的话，大概是方法：

 setScreenOnWhilePlaying(true);


因为这个方法导致的应该，这个可能需要你自定义 Manager 去自定义处理，比如你自定义一个  XXIjkPlayerManager ，然后 PlayerFactory.setPlayManager(XXIjkPlayerManager.class);

最后在设置 showDisplay 方法的后面加上  mediaPlayer.setScreenOnWhilePlaying(false); 方法
