### ISSUE TITLE
播放海康rtsp实时流有几秒的延迟, 而且这个延迟会随着播放越来越大,甚至到达十几二十秒

### ISSUE THREAD

**Issue by LyKevin** [CarGuo/GSYVideoPlayer#3363]
引用如下: 
 api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.3-jitpack'
  api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.3-jitpack'
设置如下:
        GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);
        GSYVideoType.setRenderType(GSYVideoType.TEXTURE);
 List<VideoOptionModel> list = new ArrayList<>();
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"max-buffer-size",2048);//最大缓冲大小,单位kb
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1024*4);
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"max_cached_duration", 1000*2);   //最大缓存时长
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 1000*4); //设置播放前的最大探测时间
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,"analyzeduration",50000); //设置播放前的探测时间 1,达到首屏秒开效果
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 1024*16);//播放前的探测Size，默认是1M, 改小一点会出画面更快
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1);//每处理一个packet之后刷新io上下文
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"reconnect",2);//播放重连次数
        list.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0);
        list.add(videoOptionModel);

**Comment by CarGuo** [comment]
￼具体支持的参数是怎么样，只能你自己调了，因为我这边也没办法帮你细节测试，也没有可以复现的办法

**Comment by lizhenf791** [comment]
请问这个问题解决了吗？最近我也遇到了同样的问题

**Comment by cs8** [comment]
同求

**Comment by the-xiongdanyu** [comment]
我也是遇到这种问题，找到原因是缓存时长过大导致的，把缓存时长调小

**Comment by oldTomatoCN** [comment]
> IjkMediaPlayer
靠呗，你倒是把代码铺上来啊
