### ISSUE TITLE
有声音，无画面

### ISSUE THREAD

**Issue by chenkexu** [CarGuo/GSYVideoPlayer#3364]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

有声音，无画面

## 问题机型/系统：
Android 11  小米11
## GSY依赖版本

  implementation 'com.google.android.exoplayer:exoplayer:2.12.1'

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
setScreenOnWhilePlaying(true) is ineffective for Surface

xxxxxxx

```

viewpager2 图片和视频循环轮播，切换到视频的时候直接播放，第一个是图片。最后一个是视频。从第一个图片直接切换到最后一个视频的时候，视频有声音，没有画面，提示setScreenOnWhilePlaying(true) is ineffective for Surface，
正常按顺序轮播没有问题。

demo中没有循环切换的情况。
 
这种surface无效的情况。如何判断，如何解决呢？

**Comment by CarGuo** [comment]
这个问题和这个log没关系，看不出来是什么问题。￼

Surface 你可以在使用的对应 PlayerManager 你去断点设置的那个方法
