### ISSUE TITLE
从后台切换回来无法继续播放？demo也不行

### ISSUE THREAD

**Issue by chenkexu** [CarGuo/GSYVideoPlayer#3365]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
场景：实现一个是自动播放的功能。从后台切换回来继续播放，但是我正在用其他app听歌，切换回来，由于其他app在播放音乐，导致我调用 GSYVideoManager.onPause(); 无法继续播放。

## 问题机型/系统：

例如 真机 小米11，Android11

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
   @Override
    public void onPause() {
        super.onPause();
        GSYVideoManager.onPause();
    }

    @Override
    public void onResume() {
        super.onResume();
        GSYVideoManager.onResume();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        GSYVideoManager.releaseAllVideos();
    }
```

## 问题log（如果有）

```

xxxxxxx


演示了一下demo中的无UI界面，当其他app正在播放音乐的时候，后台切换到前台 ，demo中也是直接黑屏，没有任何处理。


我这个app中，我的播放器是无UI播放器，只能自动播放。我这种情况，如何处理？如何判断当前播放被其他app阻断了
，并且让他自己重新播放？？ 如下demo中的视频

**Comment by CarGuo** [comment]
setReleaseWhenLossAudio
