### ISSUE TITLE
播放视频的界面如果有谷歌的视频广告，设置自动播放无效

### ISSUE THREAD

**Issue by MartinQAQ** [CarGuo/GSYVideoPlayer#3366]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放视频的界面如果有谷歌的视频广告，设置自动播放无效，感觉被枪占了播放焦点，这种情况该如何处理

## 问题机型/系统：

真机 锤子pro2 android 7.0

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack'

## Demo中的复现步骤

进入播放视频的界面，如果视频下方的谷歌广告正好是视频广告，这个时候就不会自动播放了
https://user-images.githubusercontent.com/19160642/131237778-878ff758-58f2-4178-bc19-937a6f6d46e7.mp4

**Comment by CarGuo** [comment]
setReleaseWhenLossAudio
