### ISSUE TITLE
如何获取当前播放器音量大小

### ISSUE THREAD

**Issue by q88qaz** [CarGuo/GSYVideoPlayer#3367]
如何获取当前播放器音量大小的值
而非系统全局媒体播放音量
顺便科普一下设置的方法是：PlayerFactory.getPlayManager().setVolume(float left, float right);
然而并没有getVolume()的方法…………o(╯□╰)o

**Comment by CarGuo** [comment]
是没有，默认都是1，你自己设置了多少自己保存
