### ISSUE TITLE
在全屏状态下setup一个视频时，setStateAndUi更改的控件id是非全屏下的控件id

### ISSUE THREAD

**Issue by tangjiarao** [CarGuo/GSYVideoPlayer#337]
假设我第一次setup一个视频，并切换至全屏状态，当视频播放完毕，在onautoCompletion方法下重新setup一个视频来播放。但此时setStateAndUi更改的控件id是非全屏下的控件id，导致全屏状态下的控件无法改变，且视频无法播放。

**Comment by CarGuo** [comment]
你需要操作全屏播放的对象，全屏播放对象会在callback中返回

**Comment by tangjiarao** [comment]
好的谢谢解决了

**Comment by riseLishan** [comment]
我也遇到了这个问题，想问下是哪个callback @tangjiarao @CarGuo
