### ISSUE TITLE
GSYVideoBaseManager.setTimeOut 重试后失效

### ISSUE THREAD

**Issue by SmartVive** [CarGuo/GSYVideoPlayer#3370]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

GSYVideoBaseManager.setTimeOut 设置之后，当第一次回调超时错误时,点击重新加载，第二次加载就不会再回调超时错误了

看了下源码问题应该在 cancelTimeOutBuffer方法是经过MediaHandler执行的 ，而startTimeOutBuffer 方法未经过MediaHandler执行，导致cancelTimeOutBuffer 执行延迟，startTimeOutBuffer 方法执行后 cancelTimeOutBuffer才执行

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack'

## Demo中的复现步骤

Demo中的SimplePlayer页面设置好setTimeOut后就能复现

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
按照之前的设定，还真没有对第二次重试这种情况做一些预期····

**Comment by SmartVive** [comment]
@CarGuo 
那有考虑支持吗，我测试了把startTimeOutBuffer方法 移动到MediaHandler的handMessage方法后执行是可行的

**Comment by CarGuo** [comment]
如果你测试可以，推荐你提一个pr ，我这边测试后合并下，最近手术住院休养ing……

**Comment by SmartVive** [comment]
@CarGuo 
好的，我这边提了pr了 #3372 ，祝早日康复

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/pull/3372 已经合并 ，com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-beta7 等依赖

**Comment by SmartVive** [comment]
com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-beta7 这个版本能直接依赖使用吗，直接使用会报错
Could not GET 'https://jitpack.io/com/github/CarGuo/gsyVideoPlayer-proxy_cache/v8.1.6-beta7/gsyVideoPlayer-proxy_cache-v8.1.6-beta7.pom'. Received status code 401 from server: Unauthorized

**Comment by SmartVive** [comment]
解决了，gsyVideoPlayer-proxy_cache 和 gsyVideoPlayer-base 这两个库还是依赖v8.1.5-jitpack就可以了

**Comment by CarGuo** [comment]
如下图所示，
    implementation "com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-beta7" 可以啊

![image](https://user-images.githubusercontent.com/10770362/132195574-5fe6ffbe-a612-44c0-9265-4c149ded48b5.png)

**Comment by SmartVive** [comment]
![1630923050(1)](https://user-images.githubusercontent.com/34232841/132201086-33039aff-5869-458a-97fe-06b700564bd5.png)
正常应该是11个模块，beta7只有8个模块，grade同步不会报错，但是编译会报错的

**Comment by CarGuo** [comment]
明白了，脚本配置少了， com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-beta8 应该可以了
