### ISSUE TITLE
请问支持RTSP和RTMP的直播流?

### ISSUE THREAD

**Issue by devzwy** [CarGuo/GSYVideoPlayer#338]
我这边播放不了RTSP的流

**Comment by devzwy** [comment]
E/IJKMEDIA: rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1: Protocol not found
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by CarGuo** [comment]
你用的是哪种so依赖？

**Comment by devzwy** [comment]
最常用的两种.以前没有搞过这个,求大神帮忙啊..

**Comment by CarGuo** [comment]
rtsp需要依赖的是ex so

**Comment by devzwy** [comment]
请问您这边有可以播放rtsp的demo吗?

**Comment by CarGuo** [comment]
你修改demo的so依赖

**Comment by devzwy** [comment]
跪求一份可以播放rtsp的so...

**Comment by CarGuo** [comment]
ex so就是…

**Comment by devzwy** [comment]
我只要在demo的build里打开compile 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v2.0.2' 的依赖就可以吗

**Comment by CarGuo** [comment]
把so的依赖。换成ex so的依赖

**Comment by devzwy** [comment]
目前更换后如下(build.gradle(gysVideoPlayer)):
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    //compile project(':gsyVideoPlayer-java')
    //compile project(':gsyVideoPlayer-armv5')
    //compile project(':gsyVideoPlayer-armv7a')
    //compile project(':gsyVideoPlayer-armv64')
    //compile project(':gsyVideoPlayer-x86')
    //compile project(':gsyVideoPlayer-x86_64')

    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    //compile project(':gsyVideoPlayer-ex_so')

    compile 'com.shuyu:gsyVideoPlayer-java:2.0.2'

//    compile 'com.shuyu:gsyVideoPlayer-armv5:2.0.2'
//    compile 'com.shuyu:gsyVideoPlayer-armv7a:2.0.2'
//    compile 'com.shuyu:gsyVideoPlayer-arm64:2.0.2'
//    compile 'com.shuyu:gsyVideoPlayer-x64:2.0.2'
//    compile 'com.shuyu:gsyVideoPlayer-x86:2.0.2'

    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    compile 'com.shuyu:gsyVideoPlayer-ex_so:2.0.2'
}

07-25 17:39:40.474 1250-1250/com.example.gsyvideoplayer V/AudioManager: playSoundEffect   effectType: 0
07-25 17:39:40.474 1250-1250/com.example.gsyvideoplayer V/AudioManager: querySoundEffectsEnabled...
07-25 17:39:40.474 1250-1250/com.example.gsyvideoplayer V/AudioManager: abandonAudioFocus...
07-25 17:39:40.474 1250-1250/com.example.gsyvideoplayer V/AudioManager: unregisterAudioFocusListener...
07-25 17:39:40.474 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_release
07-25 17:39:40.474 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
07-25 17:39:40.474 1250-1360/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
07-25 17:39:40.474 1250-1250/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToNormal
07-25 17:39:40.474 1250-1250/com.example.gsyvideoplayer V/AudioManager: abandonAudioFocus...
07-25 17:39:40.474 1250-1250/com.example.gsyvideoplayer V/AudioManager: unregisterAudioFocusListener...
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
07-25 17:39:40.484 1250-1250/com.example.gsyvideoplayer V/AudioManager: requestAudioFocus  streamType: 3  durationHint: 2
07-25 17:39:40.484 1250-1250/com.example.gsyvideoplayer V/AudioManager: registerAudioFocusListener...
07-25 17:39:40.484 1250-1250/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToPrepareingShow
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_release
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_native_setup
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170615--001
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: ijk_version_info: k0.8.1-1-g44915cd
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_create_from_android()
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d4004ae)
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque()=void
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x1d4004ae)
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer V/IJKMEDIA: setDataSource: path rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1")
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1")=0
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setLoopCount
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_volume
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_prepareAsync
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer W/IJKMEDIA: remove 'timeout' option for rtmp.
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: ===== versions =====
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: ijkplayer    : k0.8.1-1-g44915cd
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170615--001
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: libavutil    : 55.58.100
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: libavcodec   : 57.89.100
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: libavformat  : 57.71.100
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: libswscale   : 4.6.100
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: libswresample: 2.7.100
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: ===== options =====
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: player-opts : loop                         = 1
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkapplication               = 2037687408
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkiomanager                 = 2089774848
07-25 17:39:40.484 1250-1360/com.example.gsyvideoplayer I/IJKMEDIA: ===================
07-25 17:39:40.484 1250-2260/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [2260] ff_msg_loop
07-25 17:39:40.484 1250-2260/com.example.gsyvideoplayer D/IJKMEDIA: message_loop
07-25 17:39:40.484 1250-2260/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_FLUSH:
07-25 17:39:40.494 1250-2261/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [2261] ff_vout
07-25 17:39:40.494 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()=0
07-25 17:39:40.494 1250-2262/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [2262] ff_read
07-25 17:39:40.494 1250-2262/com.example.gsyvideoplayer W/IJKMEDIA: remove 'timeout' option for rtmp.
07-25 17:39:40.494 1250-2262/com.example.gsyvideoplayer E/IJKMEDIA: rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1: Protocol not found
07-25 17:39:40.494 1250-2262/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [2262]
07-25 17:39:40.494 1250-2260/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
07-25 17:39:40.494 1250-1360/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
07-25 17:39:40.504 1250-1360/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
07-25 17:39:40.504 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
07-25 17:39:40.504 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x1eb00005)
07-25 17:39:40.504 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_surface()
07-25 17:39:40.504 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x1eb00005)=void
07-25 17:39:40.514 1250-1250/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
07-25 17:39:40.514 1250-1250/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToError
07-25 17:39:40.514 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_release
07-25 17:39:40.514 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
07-25 17:39:40.514 1250-1250/com.example.gsyvideoplayer E/GSYVideoPlayer:  mCacheFile Local Error rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1
07-25 17:39:40.514 1250-1250/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Againrtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1
07-25 17:39:40.524 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_surface()
07-25 17:39:40.524 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
07-25 17:39:40.524 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
07-25 17:39:40.524 1250-2260/com.example.gsyvideoplayer D/IJKMEDIA: message_loop exit
07-25 17:39:40.524 1250-2260/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [2260]
07-25 17:39:40.524 1250-2261/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [2261]
07-25 17:39:40.524 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
07-25 17:39:40.524 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_dec_ref(): ref=0
07-25 17:39:40.524 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
07-25 17:39:40.524 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
07-25 17:39:40.524 1250-1360/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
07-25 17:39:40.524 1250-1360/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by devzwy** [comment]
报这样的错.
E/IJKMEDIA: rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1: Protocol not found
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E/GSYVideoPlayer: cancelTimeOutBuffer
E/GSYVideoPlayer:  mCacheFile Local Error rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1
E/GSYVideoPlayer: Link Or mCache Error, Please Try Againrtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1

**Comment by devzwy** [comment]
我将demo 中 openvideo中的清晰url换成了 rtsp的.String source1 = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
        String name = "普通";
        SwitchVideoModel switchVideoModel = new SwitchVideoModel(name, source1);

        String source2 = "rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1";
        String name2 = "清晰";

**Comment by devzwy** [comment]
跪求大神帮忙,感激不尽.

**Comment by CarGuo** [comment]
首先，如果依赖了exso就不用依赖其他so，然后rtsp等的需要cache在setup设置cache为false

**Comment by devzwy** [comment]
您好,不好意思又来麻烦您了.我设置了false还是无法播放.
这是我的播放代码:
  String source1 = "rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1";
        String name = "普通";
        SwitchVideoModel switchVideoModel = new SwitchVideoModel(name, source1);
        VideoOptionModel videoOptionModel =new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");//因为我们的流用的TCP的通道,看了您的其他issue后增加了这个代码.
        List<VideoOptionModel> l = new ArrayList<>();
        l.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(l);
        videoPlayer.setUp(source1, false, "111111");
这是依赖的库:
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    //compile project(':gsyVideoPlayer-java')
    //compile project(':gsyVideoPlayer-armv5')
    //compile project(':gsyVideoPlayer-armv7a')
    //compile project(':gsyVideoPlayer-armv64')
    //compile project(':gsyVideoPlayer-x86')
    //compile project(':gsyVideoPlayer-x86_64')

    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    //compile project(':gsyVideoPlayer-ex_so')

    compile 'com.shuyu:gsyVideoPlayer-java:2.0.2'

//    compile 'com.shuyu:gsyVideoPlayer-armv5:2.0.2'
//    compile 'com.shuyu:gsyVideoPlayer-armv7a:2.0.2'
//    compile 'com.shuyu:gsyVideoPlayer-arm64:2.0.2'
//    compile 'com.shuyu:gsyVideoPlayer-x64:2.0.2'
//    compile 'com.shuyu:gsyVideoPlayer-x86:2.0.2'

    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    compile 'com.shuyu:gsyVideoPlayer-ex_so:2.0.2'
}
这是异常信息:
E/IJKMEDIA: rtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1: Protocol not found
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19203]
D/IJKMEDIA: FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E/GSYVideoPlayer: cancelTimeOutBuffer
I/GSYVideoPlayer: changeUiToError
E/GSYVideoPlayer: Link Or mCache Error, Please Try Againrtsp://koudan125.6655.la:27210/dss/monitor/params?cameraid=1000004%240&substream=1

**Comment by devzwy** [comment]
您好,经过测试发现,可以播放rtmp 和 http 就是没办法播放rtsp

**Comment by CarGuo** [comment]
你的rtsp是tcp协议的吗？

**Comment by CarGuo** [comment]
视频编码和音频编码是？

**Comment by camelsmith** [comment]
你好CarGuo大，我也遇到了同样的问题，我的rtsp推流也是tcp协议的，请问要怎样解决才能播放

**Comment by CarGuo** [comment]
试试2.0.3的ex so

**Comment by asyncHyj** [comment]
@devzwy 你的问题，按照这个步骤解决了？
