### ISSUE TITLE
startWindowFullscreen使用疑问

### ISSUE THREAD

**Issue by crazyzjw** [CarGuo/GSYVideoPlayer#3380]
1. 固定activity横屏startWindowFullscreen进入全屏过程中的过渡占满背景的是黑色,如何修改
2. 固定activity横屏startWindowFullscreen进入全屏,再推出后自动旋转成竖屏

**Comment by CarGuo** [comment]
1、背景色我没记错的话，应该是 layout 里面的 color/black 和 surface_container ， 你可以 override getLayoutId 修改

2、https://github.com/CarGuo/GSYVideoPlayer/issues/2955

**Comment by crazyzjw** [comment]
> 1、背景色我没记错的话，应该是 layout 里面的 color/black 和 surface_container ， 你可以 override getLayoutId 修改
> 
> 2、#2955

第二个,有点看不懂什么意思 - -!!

**Comment by crazyzjw** [comment]
> 1、背景色我没记错的话，应该是 layout 里面的 color/black 和 surface_container ， 你可以 override getLayoutId 修改
> 
> 2、#2955

我继承了StandardGSYVideoPlayer 重写了布局文件,把黑色的都去掉,那过渡效果还是背景先黑色再拉大界面到全屏

**Comment by CarGuo** [comment]
剩下的黑色就是 Surface 上的黑色

**Comment by crazyzjw** [comment]
> 剩下的黑色就是 Surface 上的黑色



> 剩下的黑色就是 Surface 上的黑色

是需要自定义GSYRenderView处理这个过渡背景黑色问题?

**Comment by CarGuo** [comment]
怎么说呢，你可以参考 showPauseCover 的逻辑，或者在 mTextureViewContainer 上面添加多一个内容来控制颜色
