### ISSUE TITLE
大佬 咨询一下 ，暂停监听方法是啥？

### ISSUE THREAD

**Issue by ZhuSky** [CarGuo/GSYVideoPlayer#3382]
VideoAllCallBack 里没有关于视频暂停的监听
setStateAndUi一次暂停会调用多次，又不太符合
请问暂停监听是啥？

**Comment by ZhuSky** [comment]
//视频播放器 C 类型
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack'
    //是否需要ExoPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.5-jitpack'
    //更多ijk的编码支持
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.5-jitpack'

**Comment by CarGuo** [comment]
目前只有 setGSYStateUiListener 这个监听，不然你就 override onVideoPause() 和 onVideoResume(boolean seek) 这两个方法
