### ISSUE TITLE
横屏播放视频，播放广告，返回视频卡住

### ISSUE THREAD

**Issue by ZhuSky** [CarGuo/GSYVideoPlayer#3383]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

横屏播放视频下，跳转广告播放，广告播放后返回，页面卡住很久才能自动继续播放。
如果重新设置url 播放其他集数视频，直接黑屏，但是有声音。

## 问题机型/系统：

小米10Pro 

## GSY依赖版本

api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack'
//是否需要ExoPlayer模式
api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.5-jitpack'
//更多ijk的编码支持
api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.5-jitpack'

求哪位大佬知道为啥🥺指点小弟一下

https://user-images.githubusercontent.com/18596232/132903811-dec62505-8323-4013-846e-9bcbcad32ad6.mp4

**Comment by ZhuSky** [comment]
困惑好久了，求指点一下 🙏🙏🙏

**Comment by CarGuo** [comment]
不是很理解，但是如果需要重新 setup ，你调用的应该是 play.getCurrentPlayer().setup

**Comment by ZhuSky** [comment]
play.setup
 我是直接这么调用的
 继承NormalGSYVideoPlayer
 然后自定义的播放器，内部播放下一集的时候 
 release()
 setUp(xxx,xxx,xxx)
 startPlayLogic

 没有使用getCurrentPlayer()
 一定要用getCurrentPlayer()嘛？

**Comment by CarGuo** [comment]
是的，因为全屏和非全屏是两个切换的 view ，你需要通过  getCurrentPlayer() 去定位当前是哪一个

**Comment by ZhuSky** [comment]
👌 好的，我试试

**Comment by ZhuSky** [comment]
确实是getCurrentPlayer()的问题
加上后就可以了
🙏 多谢大佬
