### ISSUE TITLE
android studio 打包最新版报错

### ISSUE THREAD

**Issue by singleTree** [CarGuo/GSYVideoPlayer#3385]
环境 android stuio 4.0.1

classpath 'com.android.tools.build:gradle:4.0.0'
gradle-6.1.1-all.zip

## 1.问题描述：
ackage com.shuyu.gsyvideoplayer.armv64;

public final class BuildConfig {
  public static final boolean DEBUG = Boolean.parseBoolean("true");
  public static final String LIBRARY_PACKAGE_NAME = "com.shuyu.gsyvideoplayer.armv64";
  public static final String BUILD_TYPE = "debug";
  public static final int VERSION_CODE = 21;
  public static final String VERSION_NAME = "8.1.2";
  // Fields from build type: debug
  public static final String VERSION_NAME = "8.1.2";
}
**

> 会自动出现2个VERSION_NAM

**
第二问如图所示
![image](https://user-images.githubusercontent.com/13564957/133047164-57d207e9-be31-4d3d-87f7-aeb575032655.png)

红色表示找不到对应的包

**Comment by CarGuo** [comment]
![截屏2021-09-14 07 53 38](https://user-images.githubusercontent.com/10770362/133171800-80da775f-5e0b-4359-a5b8-2401cc358e0b.png)

如上图所示正常

Demo 应该是用的

https\://services.gradle.org/distributions/gradle-7.1.1-bin.zip


        classpath 'com.android.tools.build:gradle:4.2.2'

**Comment by singleTree** [comment]
![image](https://user-images.githubusercontent.com/13564957/133181657-eab9d2e8-39d4-499b-8422-d8a7d06eb07a.png)
感谢回答第二问题，第一个问题也是这个原因吗

**Comment by CarGuo** [comment]
是的，你 clone 下来后，不要修改版本

**Comment by singleTree** [comment]
我的android studio 版本较低，不支持那么高的版本。

**Comment by singleTree** [comment]
如果不想升级android stuido， 目前是4.0.1.     应该用以前的那个版本合适

**Comment by CarGuo** [comment]
那你把这段去掉

    buildTypes.all {
        it.buildConfigField "String", "VERSION_NAME", "\"${PROJ_VERSION}\""
    }

**Comment by singleTree** [comment]
去掉后又报了其他错误，这个项目是不是需要jdk11啊，我目前是jdk8
