### ISSUE TITLE
播放2k视频时画面和帧率被压缩了

### ISSUE THREAD

**Issue by 2799448671** [CarGuo/GSYVideoPlayer#3388]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by 2799448671** [comment]
海信的4k电视 我用videoview播放的时候画面和帧数都正常,用gsy播放就会感觉画面和帧率都被压缩了

**Comment by 2799448671** [comment]
我播放的是本地视频

**Comment by CarGuo** [comment]
切换到 exoplayer 内核，然后如果你的播放链接没有后缀，要不就是 setOverrideExtension 指定，要不就是链接有后缀

**Comment by CarGuo** [comment]
切换到 exo 内核，并注意，如果视频 url 本身不存在格式封装后缀，需要使用 setOverrideExtension 指定

**Comment by 2799448671** [comment]
> 切换到 exo 内核，并注意，如果视频 url 本身不存在格式封装后缀，需要使用 setOverrideExtension 指定

切换到EXO内核会黑屏无法播放

**Comment by CarGuo** [comment]
有测试链接提供么？ 黑屏太抽象了，你看看这个  https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q ，另外不是说了么：

**如果视频 url 本身不存在格式封装后缀，需要使用 setOverrideExtension 指定**

**Comment by wflian** [comment]
我也遇到了。播放下载好的本地文件。videoview播放很清晰，用gsy播放，会模糊一些，比如比较大的字 数显明显的锯齿

**Comment by CarGuo** [comment]
@wflian  GSYVideoType.setRenderType(GSYVideoType.SUFRACE);

**Comment by wflian** [comment]
> @wflian GSYVideoType.setRenderType(GSYVideoType.SUFRACE);

一样。看文字特别明显。videoview非常清晰。

**Comment by wflian** [comment]
> @wflian GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
可以了。必须系统内核+GSYVideoType.setRenderType(GSYVideoType.SUFRACE);

**Comment by wflian** [comment]
这个方式播放清洗，但是有一个静态图片切换的视频，视频播放的时候会抖动，videoview播放也会抖动，但是实际上这个视频是正常的，用其他模式播放又是正常
