### ISSUE TITLE
在android7.1的设备上播放的时候只显示视频第一帧

### ISSUE THREAD

**Issue by 2799448671** [CarGuo/GSYVideoPlayer#3389]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by 2799448671** [comment]
好像是视频被第一帧覆盖了 我播放一个竖屏的视频时如果设置成16:9的比例的话两边可以看到视频播放 但中间应该播放的视频不会动

**Comment by 2799448671** [comment]
刚把视频投上去的第一秒还可以看,但之后就会被不知道从视频第几秒截取的图片覆盖住

**Comment by 2799448671** [comment]
救命啊 今天要改完的

**Comment by 2799448671** [comment]
有声音但只有画面不会动

**Comment by CarGuo** [comment]
不大理解，我这边用demo测试正常
