### ISSUE TITLE
全屏软键盘不要抬起布局的处理

### ISSUE THREAD

**Issue by ilovexy2tom** [CarGuo/GSYVideoPlayer#3395]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在横屏下专门写了一套布局

布局中增加了EditText

**以下所有方法布局EditText都会顶起布局**

而此EditText无法处理为  android:windowSoftInputMode="stateHidden|adjustResize"

使用了fitsSystemWindows= ture 不起作用

EditText和ScrollView嵌套在同一布局中无效

EiitText设置为dialog里面弹出无效

Demo中没有找到和横屏键盘相关的部分

如何处理为EditText不顶起布局，遮挡布局

-----

注：如果用VideoView的横屏，则是可以的覆盖而不顶起的，因为VideoView的横屏的EditText仍然在activity的布局下

## 问题机型/系统：

红米k20 androi 10.0

## GSY依赖版本

例如  implementation 'com.shuyu:gsyVideoPlayer-java:8.1.2'

问题代码：(如果有)
```
    override fun getLayoutId(): Int {
        if (mIfCurrentIsFullscreen) {
            return R.layout.danmaku_layout_land
        }
        return R.layout.danmaku_layout_new

    }
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
因为 GSY 全屏的布局是在  Activity 的  Window.ID_ANDROID_CONTENT 上，和非全屏是两个 View 来着

**Comment by ilovexy2tom** [comment]
> 因为 GSY 全屏的布局是在  Activity 的  Window.ID_ANDROID_CONTENT 上，和非全屏是两个 View 来着

那activity的所有处理就无效了是吗？怎么处理呢？

**Comment by ilovexy2tom** [comment]
我的横屏布局，是写在你说的 Window.ID_ANDROID_CONTENT 上面的

**Comment by CarGuo** [comment]
全屏的时候，是把横屏的 View 添加到 Activity 下的 Window.ID_ANDROID_CONTENT 上，默认提供的 FrameLayout ，应该没什么问题啊

如下图两张图片所示


<img width="539" alt="image" src="https://user-images.githubusercontent.com/10770362/134463865-86c90493-c454-4d59-a6aa-ab8cbd7d6460.png">


![image](https://user-images.githubusercontent.com/10770362/134463984-64f36106-9cda-49e5-b85b-a422ef79fa5f.png)

**Comment by ilovexy2tom** [comment]
我不知道你的键盘为什么不是满屏，我的是满屏，满屏看不出来

所以我们的需求需要在EditText加这个属性

   android:imeOptions="flagNoExtractUi"

你加上试试，这个是半屏键盘，我这边这样就一定会顶起来了

**Comment by CarGuo** [comment]
这个不是很简单么，在 Activity 的 onCreate 添加 `getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_NOTHING);` 就可以了，我这边测试没有问题

**Comment by ilovexy2tom** [comment]
感谢大佬支持，解决了。

横竖屏我分别用SOFT_INPUT_ADJUST_RESIZE和SOFT_INPUT_ADJUST_NOTHING切换了一下

再监听了一下键盘高度控制了EditText的高度

应该之前一直是ADJUST_RESIZE
