### ISSUE TITLE
请问一下，列表切换全屏播放动画在哪修改？

### ISSUE THREAD

**Issue by RDSunhy** [CarGuo/GSYVideoPlayer#3396]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

想仿微信朋友圈那种的 点击列表中的视频 共享元素过渡 全屏展示 不知道如何下手 能提供个思路嘛？

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
如果你不需要，可以设置 setShowFullAnimation 为 false ，如果你要自定义，你可能需要 override startWindowFullscreen 方法和 backToNormal 方法
