### ISSUE TITLE
导入项目报错

### ISSUE THREAD

**Issue by 13297063206** [CarGuo/GSYVideoPlayer#3397]
F:\downloadDemo\GSYVideoPlayer-master\gsyVideoPlayer-armv64\build\generated\source\buildConfig\debug\com\shuyu\gsyvideoplayer\armv64\BuildConfig.java:19: ����: ������ BuildConfig�ж����˱��� VERSION_NAME
  public static final String VERSION_NAME = "8.1.2";

```

**Comment by CarGuo** [comment]
请确定 demo 项目的编码时 utf8 并且 gradle 配置和版本没有发生改变

**Comment by 13297063206** [comment]
utf8没问题，gradle版本确实改小了，因为这个7.11我报错，就改成5.63了

**Comment by Goooler** [comment]
你这应该还是编码问题，gradle 就别改小了，看着升级 AS 吧。

**Comment by CarGuo** [comment]
@13297063206  现在的 VERSION_NAME 是用新版本 gradle 的配置

**Comment by Goooler** [comment]
@CarGuo 我感觉 BuildConfig 默认还是不要让生成了，记得只有一个地方在用，只在那个模块生成好了。

**Comment by CarGuo** [comment]
@Goooler 是啊，现在用的就是你在 base.gradle 里面  buildTypes.all 生成的，只是如果 gradle 版本选了旧的话，它自己也会生成一个 VERSION_NAME ，所以会有冲突

**Comment by Goooler** [comment]
> @Goooler 是啊，现在用的就是你在 base.gradle 里面 buildTypes.all 生成的，只是如果 gradle 版本选了旧的话，它自己也会生成一个 VERSION_NAME ，所以会有冲突

不生成 VERSION_NAME 应该是新版 AGP 的行为变更，和 gradle 没关系。不过我已经在提交里面改掉了，改成默认不生成了。

**Comment by CarGuo** [comment]
@Goooler 是的，我的意思就是一些人下载 Demo 之后，会手动降低 AGP 导致

**Comment by Goooler** [comment]
> @Goooler 是的，我的意思就是一些人下载 Demo 之后，会手动降低 AGP 导致

我改成这样好了

![image](https://user-images.githubusercontent.com/10363352/134465836-4b13cdf8-2ff0-454d-8874-633c4452fec9.png)

**Comment by 13297063206** [comment]
你改了吗，我刷新好像还是原来的，可能没提交

**Comment by 13297063206** [comment]
好了，我跑起来了，我把这行代码注释了
 // it.buildConfigField "String", "VERSION_NAME", "\"${PROJ_VERSION}\""

**Comment by Goooler** [comment]
在 #3349 里面，还没合进去。

**Comment by 13297063206** [comment]
Duplicate class tv.danmaku.ijk.media.player.AbstractMediaPlayer found in modules jetified-GSYIjkJava-1.0.0-runtime.jar (com.github.CarGuo:GSYIjkJava:1.0.0) and jetified-media-release-runtime.jar (media-release.aar)
冲突了咋处理？

**Comment by 13297063206** [comment]
我打开黑屏的，啥情况？

**Comment by 13297063206** [comment]
就是进度条有变化但是没有图像

**Comment by 13297063206** [comment]
有声音

**Comment by 13297063206** [comment]
这个框架可以播放本地资源视频吗？
