### ISSUE TITLE
exo内核使用4g网播不了HLS视频 使用WIFI可以播放

### ISSUE THREAD

**Issue by AndroidStudioIde** [CarGuo/GSYVideoPlayer#3398]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

exo内核使用4g网播不了HLS视频 使用WIFI可以播放 ，另外如果重启手机的话4g可以播放，但是过一回之后用4g就播放不了了 

## 问题机型/系统：

例如 真机 红米k20 pro

## GSY依赖版本

'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.1.6-jitpack'

## Demo中的复现步骤

在demo中用exo内核 输入url地址（hls类型视频），4g网播放不了，切换到wifi秒播，另外如果重启手机的话4g可以播放，但是过一回之后用4g就播放不了了 

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
DNS运营商问题

**Comment by AndroidStudioIde** [comment]
该如何解决呢

**Comment by CarGuo** [comment]
运营商的 DNS 问题或者服务提供商的 DNS 有问题，导致你域名访问不上的话，你问我也没有

**Comment by AndroidStudioIde** [comment]
但是ijk内核可以播放啊

**Comment by AndroidStudioIde** [comment]
ijk内核4g wifi都能播

**Comment by CarGuo** [comment]
你不是说重启可以，然后又不可以么…ijk走得罪网络请求和exo不大一样，ijk完全没有做检验合法性的
