### ISSUE TITLE
ijk开硬解码横竖屏花屏，求解

### ISSUE THREAD

**Issue by AndroidStudioIde** [CarGuo/GSYVideoPlayer#3399]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

ijk软解码的时候播放部分视频过于卡顿(并且频繁横竖屏会导致一直黑屏),于是我开了硬解码，硬解码没有发现频繁横竖屏一直黑屏的问题，卡顿感也减弱了，但是横竖屏的时候会花屏一两秒

## 问题机型/系统：

真机 红米k20 pro

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.3'`

## Demo中的复现步骤

ijk软解码的时候播放部分视频过于卡顿(并且频繁横竖屏会导致一直黑屏),于是我开了硬解码，硬解码没有发现频繁横竖屏一直黑屏的问题，卡顿感也减弱了，但是横竖屏的时候会花屏一两秒

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by AndroidStudioIde** [comment]
如果ijk软解能解决频繁横竖屏会导致一直黑屏的问题的话，那解决软解的问题也可能，谢谢作者

**Comment by CarGuo** [comment]
我记得 demo 有一个叫 MediaCodecVideo 的，那个是你用 ijk 硬解码的最后希望了·····

**Comment by AndroidStudioIde** [comment]
问一下，整个app用一个内核好，还是俩内核来回切也没事儿，我怕一直切内核出问题来着

**Comment by CarGuo** [comment]
@AndroidStudioIde  切内核没事的，一般都是多内核适配不同场景
