### ISSUE TITLE
弱网络或无网下，播放器就会回调onError

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#34]
在弱网络或无网下，播放器就会回调onError。能否像bilibili客户端那样，弱网络或无网下，会一直请求视频

**Comment by CarGuo** [comment]
这个你可以试试弱网络环境关掉边拨边缓存，因为代理服务弱网络可以会比较差，然后ijk提供的估计没有bilibili那么好，因为它自己也说了，bilibili是一个闭源软件。
