### ISSUE TITLE
Any other way to set thumbimage to gsyvideoplayer in listview

### ISSUE THREAD

**Issue by RudreshJR** [CarGuo/GSYVideoPlayer#340]
I am using following code to set thumbimageview in listview.. It is taking more time to load and making listview scroll hard. Is there any other way to set thumbimage to gsyvideoplayer.

Imageview imageView = new ImageView(getActivity());
 imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
          
            if (m.getVideothumbnailUrl() != null) {

                Picasso.with(getActivity())

                        .load(m.getVideothumbnailUrl())
                        .resize(125, 125)
                        .placeholder(R.drawable.kt_talent)
                        .into(imageView);

          }
         
            viewHolder.gsyVideoPlayer.setThumbImageView(imageView);

**Comment by CarGuo** [comment]
you may need to use imageview cache in viewholder
