### ISSUE TITLE
AudioDetailPlayer无法播放

### ISSUE THREAD

**Issue by 13297063206** [CarGuo/GSYVideoPlayer#3400]
没找到播放本地视频的代码，是没有这个功能吗

**Comment by 13297063206** [comment]
我知道了，这个是音频类，但是里面没有找到播放本地视频的代码，是没有这个功能吗？

**Comment by 13297063206** [comment]
没找到播放本地视频的代码，是没有这个功能吗

**Comment by CarGuo** [comment]
播放本地视频，你可以看 Demo 的  DetailPlayer  的 onActivityResult 用 SAF 模式播放或者 file:///xxxx

**Comment by 13297063206** [comment]
我看过了，将文件放到raw下，用这个geturl函数，解开releasemediaplayer还是不行，不过我切换其他内核可以


| |
黄超
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年09月24日 14:22，Shuyu Guo 写道：

播放本地视频，你可以看 Demo 的 DetailPlayer 的 onActivityResult 用 SAF 模式播放或者 file:///xxxx

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CarGuo** [comment]
如果你是想播放 raw 的

        //String url = "android.resource://" + getPackageName() + "/" + R.raw.test;
        //注意，用ijk模式播放raw视频，这个必须打开
        GSYVideoManager.instance().enableRawPlay(getApplicationContext());

        ///exo 播放 raw
        //String url = "rawresource://" + getPackageName() + "/" + R.raw.test;

        ///exo raw 支持
        //String url =  RawResourceDataSource.buildRawResourceUri(R.raw.test).toString();
        
        
        
        
  如果是播放 SD 卡的，就是 SAF 模式播放或者 file:///xxxx
