### ISSUE TITLE
看直播的时候点了暂停按钮，再次点击后如何播放最新的，而不是接着暂停时候的播

### ISSUE THREAD

**Issue by ghm9527** [CarGuo/GSYVideoPlayer#3401]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
这就要看服务端是怎么支持的了，是不是可以通过控制 header 处理，或者执行 seek 处理，最后就是用无缝切换下播放内核解决，比如 Demo 的 `SmartPickVideo`，这样来实现切换新的播放

**Comment by alen252** [comment]
无缝切换内核有点麻烦，有没有简单的方法，感觉这是一个很普遍的场景
