### ISSUE TITLE
麻烦提供播放错误时的错误信息

### ISSUE THREAD

**Issue by dzl888** [CarGuo/GSYVideoPlayer#3404]
## 问题描述：

当视频播放出错时，会调用GSYSampleCallBack.onPlayError(url,objects)函数，但这样就只能知道播放出错了，不知道出了什么错，一般的视频播放器，错误回调函数都会有错误的原因返回，不知道您为什么把错误信息给屏蔽了不让我们获取，有时候知道错误信息还是有用的，比如404的时候，我们可以提示用户是因为视频不存在。麻烦增加一下错误信息，谢谢。

**Comment by CarGuo** [comment]
没有这个～sorry
