### ISSUE TITLE
有考虑过用 kotlin 重构这个库嘛

### ISSUE THREAD

**Issue by Goooler** [CarGuo/GSYVideoPlayer#3405]
如题。

**Comment by CarGuo** [comment]
完全没有，因为没有必要，就如谷歌很多底层库或者 exoplayer 都不会更改为 kotlin  一样～

**Comment by Goooler** [comment]
我觉得这应是个时间问题。

**Comment by CarGuo** [comment]
不会的，SDK 最大的根本就是尽可能适配更多的场景，而使用 java 会得到跟好的支持和适配。

kotlin 更适合作为开发过程中的工具，以为他的封装和语法糖更多更灵活和高效。

但是对于 SDK 来说这些都不是关键，并切出更好的支持之外，稳定性也是一大因素，切换到 kotlin 的成本并不会带来 SDK 的性能提升或者质的改变，长期的稳定性才是 SDK 的重要基础，所以整体切换到 Kotlin 并没有价值。
