### ISSUE TITLE
大佬，设置循环播放setLoop(true)后一直报error while seeking 是怎么回事呢

### ISSUE THREAD

**Issue by ghm9527** [CarGuo/GSYVideoPlayer#3406]

**Comment by CarGuo** [comment]
demo 哪里复现

**Comment by ghm9527** [comment]
我就是在弹幕DanmakuVideoPlayer中测试的，将其中播放的视频地址换成了公司内部的一个m3u8地址复现的

**Comment by CarGuo** [comment]
我测试没问题，如果可以请提供 url

**Comment by ghm9527** [comment]
大佬，我刚刚把地址以简书私信的方式发给您 了

**Comment by CarGuo** [comment]
感觉是编码兼容模式有问题

你切换到  `PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式` 然后如果链接最后面不是 m3u8  mp4 这样的结尾，记得 setOverrideExtension
