### ISSUE TITLE
库与media-release.aar冲突

### ISSUE THREAD

**Issue by 13297063206** [CarGuo/GSYVideoPlayer#3407]
Duplicate class tv.danmaku.ijk.media.player.pragma.Pragma found in modules jetified-GSYIjkJava-1.0.0-runtime.jar (com.github.CarGuo:GSYIjkJava:1.0.0) and jetified-media-release-runtime.jar (media-release.aar)

-------------------------
大神：怎么解决这个冲突

**Comment by 13297063206** [comment]
implementation('com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack') {
        exclude group: 'tv.danmaku.ijk' //guava
//        exclude group: 'tv.danmaku.ijk', module: 'media'
    }

**Comment by songsongtao** [comment]
> implementation('com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack') { exclude group: 'tv.danmaku.ijk' //guava // exclude group: 'tv.danmaku.ijk', module: 'media' }

有用吗
