### ISSUE TITLE
自定义exo 外挂字幕点击全屏后，当前那一条会消失

### ISSUE THREAD

**Issue by w13159584927** [CarGuo/GSYVideoPlayer#3408]
## 问题描述：

自定义exo 外挂字幕点击全屏后，当前那一条字幕会消失

## 问题机型/系统：

锤子 OS103 7.1.1

## GSY依赖版本

最新版

## Demo中的复现步骤

demo中视频点击播放后，在显示字幕时点击暂停，点击全屏按钮，切换全屏时当前的这条字幕会消失，后边再出现有字幕的内容才会显示出来。

**Comment by CarGuo** [comment]
设计如此·····

**Comment by w13159584927** [comment]
好的，感谢回答。
