### ISSUE TITLE
怎么让视频在点击的时候才去setup-url，而不是提前绑定。

### ISSUE THREAD

**Issue by plmmanwu** [CarGuo/GSYVideoPlayer#341]
另外为啥设置封面mVideoPlayer.setThumbImageView(imageView);这一个方法设置不上去，必须要
mVideoPlayer.setUp(url, false, null, "");一起设置才生效

**Comment by CarGuo** [comment]
请参考源码啊，不好意思现在注意到这个

**Comment by 50kg** [comment]
我也遇到了这个问题，请问楼主是怎么解决的，需要先设置url 封面才能显示。业务逻辑没有给url，点击播放的时候才请求去获取url @CarGuo @plmmanwu
