### ISSUE TITLE
全屏时滑出屏幕顶部的状态栏，会导致亮度或音量改变

### ISSUE THREAD

**Issue by SkyD666** [CarGuo/GSYVideoPlayer#3410]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

全屏时滑出屏幕顶部状态栏，会导致亮度或音量改变。
与这个问题类似#26

## 问题机型/系统：

例如 真机 HONOR V20 ANDROID 10

## GSY依赖版本

例如 `implementation "com.shuyu:GSYVideoPlayer:8.1.0"`

**Comment by CarGuo** [comment]
你可以重写 `override onTouch` 方法，或者 `touchSurfaceDown` 、`touchSurfaceMove` 和  `touchSurfaceUp` 方法，自己定义响应的区间
