### ISSUE TITLE
如何获取播放器  播放视频内容，自动拉伸以后的宽高

### ISSUE THREAD

**Issue by roger54920** [CarGuo/GSYVideoPlayer#3417]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

如何获取播放器  播放视频内容，自动拉伸以后的宽高
比如我手机屏幕是宽是：2264   高是：1036    ，视频本身的宽是：640   高是：368    ，放到视频播放器以后，自动进行了全屏拉伸显示 ，我该如何获取到  拉伸后视频的宽高 呢？

## 问题机型/系统：

例如 真机 小米pro 8

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/af3becf7c69e19da602185d00715d266f2b712e0/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/GSYVideoType.java#L11


https://github.com/CarGuo/GSYVideoPlayer/blob/af3becf7c69e19da602185d00715d266f2b712e0/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/MeasureHelper.java#L74
