### ISSUE TITLE
列表视频播放始终是一个视频

### ISSUE THREAD

**Issue by siasxiaoq** [CarGuo/GSYVideoPlayer#342]
ListVideo2Activity页面，ListVideoAdapter数据适配中播放的都是同一个视频，如果把视频播放的地址变成不同的，点击播放，然后下滑直到小屏播放，然后再点击任意的视频，播放的仍然是之前播放的视频
holder.playerBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                notifyDataSetChanged();
                //listVideoUtil.setLoop(true);
                listVideoUtil.setPlayPositionAndTag(position, TAG);
                final String url = "http://baobab.wdjcdn.com/14564977406580.mp4";
                final String url1 = "http://video.cnnb.com.cn/video/upload/common/201707/12304174831081770.mp4";
                if (position % 2 == 0) {
                    listVideoUtil.setTitle("title " + position);
                    listVideoUtil.startPlay(url);
                } else {
                    listVideoUtil.setTitle("title1 " + position);
                    listVideoUtil.startPlay(url1);
                }
                //listVideoUtil.setCachePath(new File(FileUtils.getPath()));

                //必须在startPlay之后设置才能生效
                //listVideoUtil.getGsyVideoPlayer().getTitleTextView().setVisibility(View.VISIBLE);
            }
        });

**Comment by CarGuo** [comment]
下个版本将修复

**Comment by CarGuo** [comment]
2.0.3
