### ISSUE TITLE
exo内核如何对播放器设置参数

### ISSUE THREAD

**Issue by AndroidStudioIde** [CarGuo/GSYVideoPlayer#3424]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 红米k20pro

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
如何对exo内核设置参数，比如说读取时间 缓存区大小等等
```

## 问题log（如果有）
如何对exo内核设置参数，比如说读取时间 缓存区大小等等

```

xxxxxxx

```

**Comment by CarGuo** [comment]
exo 没有这些暴露api ，你可以通过参考demo 的  GSYExoPlayerManager 自定义 PlayerManager  ，然后修改你需要的

**Comment by AndroidStudioIde** [comment]
同样的MP4 流媒体  ios播起来不卡，安卓很卡是怎么回事儿

**Comment by CarGuo** [comment]
Exo是用的MediaCodec，和系统硬件的解码能力有关系的

**Comment by AndroidStudioIde** [comment]
但是我看着像网络问题啊，进度条里边的白色条不动，缓冲不动
