### ISSUE TITLE
在低端定制机上播放花屏

### ISSUE THREAD

**Issue by qwwuyu** [CarGuo/GSYVideoPlayer#3426]
## 问题描述：

在定制系统Android4.2 (CPU:sun7i armeabi-v7a)上尝试用StandardGSYVideoPlayer三种模式播放mp4文件.
IjkPlayerManager无声音无画面.
SystemPlayerManager少量局部范围花屏.
Exo2PlayerManager稍多局部范围花屏.
如果使用MediaPlayer + SurfaceView播放则正常,同样的代码换个高端一点的定制机就没问题.
请问有什么好的设置么?

## 出现问题的视频流

很普通的mp4,这边几个mp4都一样.
视频流信息
编码格式:h264
视频码率:547 kbps
视频帧率:24 fps
显示比率: 1.50
分辨率:720x480
音频流信息
编码格式: aac
音频码率:64 kbps
音频位数:o bits
声道数:2 channels
采样数:48000 Hz

## 问题机型/系统：

定制系统Android4.2 (CPU:sun7i armeabi-v7a)

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:6.0.3'
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

**Comment by CarGuo** [comment]
MediaPlayer 的 loop 是 framwork 做的···我能怎么办···定制版的支持的 MediaCodec 有问题？？
