### ISSUE TITLE
2个及以上的界面同时播放视频，调用Release会被全部终止

### ISSUE THREAD

**Issue by HalyangDream** [CarGuo/GSYVideoPlayer#3428]
## 问题描述：
2个界面同时播放视频，其中一个调用GSYVideoManager.releaseAllVideos()，另一个界面就会出现视频被中止
比如：1. A界面在播放视频，这时候跳转到B界面
2. 然后B界面也播放视频
3.  B界面关闭，并调用GSYVideoManager.releaseAllVideos()，这时候A界面播放的视频也会被重置，这个应该怎么解决
## 问题机型/系统：
红米K40Pro 
 Android11

## GSY依赖版本
`implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

**Comment by CarGuo** [comment]
默认内核只有一个，as design

如果你需要同时播放多个，参考 MultiSampleVideo
