### ISSUE TITLE
Doubt to determine better decoding?

### ISSUE THREAD

**Issue by vipeweb** [CarGuo/GSYVideoPlayer#3443]
Hello I would just like to clear up some doubts I am deploying GSYVideoPlayer in an app that has many users the problem that most accesses in android set-box

some perform well with hardware acceleration for decoding others do not

I would like to know if there is any way to detect the best configuration

using the exoplayer engine, for live playback M3U8 HLS

settings to use
cacheWithPlay: false

  PlayerFactory.setPlayManager(Exo2PlayerManager.class);
CacheFactory.setCacheManager(ExoPlayerCacheManager.class);

I have doubts about the

enableMediaCodecTexture

is there any way to let the SOFTWARE decide the best?

enabled or disabled?

**Comment by CarGuo** [comment]
I'm not sure ·····

android:hardwareAccelerated="true" in application not work ？

your can used `view.isHardwareAccelerated()` or `canvas.isHardwareAccelerated()` System API ?
