### ISSUE TITLE
performance with elements inside the video player

### ISSUE THREAD

**Issue by VultDev** [CarGuo/GSYVideoPlayer#3444]
Hi, I have a problem with my project.
I'm using the exoplayer engine

PlayerFactory.setPlayManager(Exo2PlayerManager.class)

to play M3U8 hls live.
I have problems playing 1080p videos with android boxes
it happens that when I leave only the GSY player in a blank activity it runs fine, I'm using the Emptyvideo class

now inside an activity where I have
a tablayout inside Emptyvideo and a centralized recycleview
also inside EmptyVideo I get crashes only in 1080p.

is there any way of using Recycleview on top of the videoplayer element?

i auto hide with setAlpha after 6 seconds

**Comment by CarGuo** [comment]
I'm not sure what's wrong in your case  , could you provider crash log ?
