### ISSUE TITLE
Failed to resolve: com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack

### ISSUE THREAD

**Issue by androidHRTZ** [CarGuo/GSYVideoPlayer#3445]
1. 项目添加其它任何依赖都是正常的，添加这个依赖（implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack'）时候显示如下图失败。还有一个很奇怪的现象，现在新开的项目（默认Gradle之类的）每一个都显示这样
2. 最新版本Android Studio默认新开的项目都是有这样不行的情况，但是若用以前新开的项目，又可以正常运行，请问为什么呢，我排查很久实在找不出问题 谢谢

![image](https://user-images.githubusercontent.com/15447020/139542224-af1cd03e-0aae-4de9-bd14-3f068b11e77a.png)
![image](https://user-images.githubusercontent.com/15447020/139542233-27c3556a-e72c-4c89-9929-e1c8d2aa0672.png)
![image](https://user-images.githubusercontent.com/15447020/139542238-585d0670-9cb3-46d1-8e7c-4d5b90dde685.png)

**Comment by CarGuo** [comment]
allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url "https://jitpack.io" }
    }
}

**Comment by androidHRTZ** [comment]
> allprojects { repositories { google() mavenCentral() maven { url "https://maven.aliyun.com/repository/public" } maven { url "https://jitpack.io" } } }

感谢您的及时回复与帮助！ 我添加您说的后build起来依然是这情况，如下图
![image](https://user-images.githubusercontent.com/15447020/139563752-f163f935-7669-47c0-b471-8fc97fea0dd0.png)

**Comment by androidHRTZ** [comment]
现在我是新开一个全新的项目运行的结果如下图，没能发现什么问题 ，然而运行失败 谢谢
![image](https://user-images.githubusercontent.com/15447020/139563862-b07bd8d4-e093-421e-aac1-40f9592ad2c6.png)
![image](https://user-images.githubusercontent.com/15447020/139563971-9d6d07f7-154f-41ab-b949-2610768b0680.png)
![image](https://user-images.githubusercontent.com/15447020/139563976-3a3587eb-0602-412d-a26c-2e1e9b7f9030.png)
![image](https://user-images.githubusercontent.com/15447020/139563997-f1580293-76b4-491e-bb99-2145b4d7f58d.png)

**Comment by CarGuo** [comment]
90% 的时候网络问题，如果  maven { url "https://maven.aliyun.com/repository/public" }  也引用不到的话，那就只能开代理走梯子了 

如下图，我这里的 mac ，你可以在 win 上开了梯子之后，在全局的 gradle 配置对应的代理地址和端口，测试依赖和运行正常


![image](https://user-images.githubusercontent.com/10770362/139608310-ee977b95-6206-444f-8ab0-b5d67b2d98f8.png)

**Comment by CarGuo** [comment]
v8.1.7-release-jitpack

**Comment by Nick-QI** [comment]
我这边也碰到了这种情况，更换代理什么的都拉不下来。
换了种解决方式，希望后来人能看到，并对你有所帮助。（折腾我一天）
在 **settings.gradle> dependencyResolutionManagement > repositories** 中添加
**`   maven { url 'https://jitpack.io' }
        maven { url "https://maven.aliyun.com/repository/public" }`**

![image](https://user-images.githubusercontent.com/29225479/158927157-0415b348-0bcd-4d29-a314-d5b70e7f4dd2.png)

**Comment by shiyuzhe** [comment]
> 我这边也碰到了这种情况，更换代理什么的都拉不下来。 换了种解决方式，希望后来人能看到，并对你有所帮助。（折腾我一天） 在 **settings.gradle> dependencyResolutionManagement > repositories** 中添加 **` maven { url 'https://jitpack.io' } maven { url "https://maven.aliyun.com/repository/public" }`**
> 
> ![image](https://user-images.githubusercontent.com/29225479/158927157-0415b348-0bcd-4d29-a314-d5b70e7f4dd2.png)

有用，谢谢
