### ISSUE TITLE
播放器无法调整亮度

### ISSUE THREAD

**Issue by Yangqingchun** [CarGuo/GSYVideoPlayer#3449]
## 问题描述：

  播放器无法调整亮度，但可以调整音量，但两者都会显示进度条，显示当前亮度或者音量。

## 出现问题的视频流
 所有的视频播放都不能调整亮度

## 问题机型/系统：

Android8.0

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.8'

**Comment by Yangqingchun** [comment]
还发现调整亮度和音量的区域不是对称的，调整亮度的区域占了一大半，调整音量的区域只有接近边缘的一小部分

**Comment by Yangqingchun** [comment]
StandardGSYVideoPlayer用的是这个播放器

**Comment by CarGuo** [comment]
demo 哪里有这个问题？？？没发现啊

**Comment by CarGuo** [comment]
getWindow().getAttributes().screenBrightness

**Comment by Yangqingchun** [comment]
> getWindow().getAttributes().screenBrightness
![008E7656](https://user-images.githubusercontent.com/33993115/141233043-1ead7e44-b329-4355-a0b1-4fbb607c424f.jpg)
不太懂呀大佬..

**Comment by CarGuo** [comment]
baidu or google it
