### ISSUE TITLE
 AndroidX Media3 will be the new home for ExoPlayer

### ISSUE THREAD

**Issue by ag2s20150909** [CarGuo/GSYVideoPlayer#3452]
https://github.com/androidx/media
https://developer.android.com/jetpack/androidx/releases/media3?hl=zh-cn

Media3 是面向媒体支持库（包括 ExoPlayer）的新平台。首个 Alpha 版包含用于实现媒体用例的库的早期功能实现，包括： - ExoPlayer，适用于 Android 且易于自定义和扩展的应用级媒体播放器。- 用于公开和控制播放的媒体会话功能。这一新的会话模块使用与 ExoPlayer 相同的 Player 接口。- 用于构建媒体播放界面的界面组件。- 其他库中用于 ExoPlayer 的模块封装功能，例如通过 IMA SDK 插入广告。

如需了解详情，请参阅 Media3 GitHub 项目。

之前，ExoPlayer 托管在单独的 ExoPlayer GitHub 项目中。在 Media3 中，其软件包名称为 androidx.media3.exoplayer。我们计划在一段时间内继续维护和发布 ExoPlayer GitHub 项目，以便让应用有时间迁移到 Media3。Media3 取代了所有 ExoPlayer 模块，但旧版 media2 和 mediasession 扩展程序除外，后者已被新的 media3-session 模块取代。这可以实现播放器和媒体会话之间的直接集成，而无需使用适配器/连接器类。

**Comment by CarGuo** [comment]
Thx，看来后续有必要准备迁移到Media3

**Comment by lh1241698502** [comment]
[ExoPlayer][r2.19.0]，这个是最后的版本不再维护了，[AndroidX Media3 1.1.0 release](https://github.com/androidx/media/releases/tag/1.1.0)，以后在Androidx Media3上继续开发了

**Comment by CarGuo** [comment]
下版本更新
