### ISSUE TITLE
使用StandardGSYVideoPlayer,重写touchDoubleUp方法后，双击事件没有触发

### ISSUE THREAD

**Issue by Yangqingchun** [CarGuo/GSYVideoPlayer#3456]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ 没有办法触发双击事件，打断点也捕获不到这个事件

## 问题机型/系统：

Android8.0

## GSY依赖版本

直接将GSY作为Model引入到了项目里。

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：
//我就是在StandardGSYVideoPlayer类里添加了这个方法，是我的操作方式不对吗？
@Override
    protected void touchDoubleUp(MotionEvent e) {
        super.touchDoubleUp(e);
    }

**Comment by CarGuo** [comment]
demo 测试正常

**Comment by Yangqingchun** [comment]
> demo 测试正常

大佬，您用的是哪个Demo

**Comment by Yangqingchun** [comment]
> demo 测试正常

大佬，我发现我需要连续点击三次才会触发这个双击事件..我没有动过那一块的代码
