### ISSUE TITLE
怎么去配置允许测试人员去抓包呢

### ISSUE THREAD

**Issue by sd6352051** [CarGuo/GSYVideoPlayer#3458]
## GSY依赖版本

    implementation 'com.github.carguo.GSYvideoplayer:gsyVideoPlayer-java:v8.1.6-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv5:v8.1.6-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-arm64:v8.1.6-jitpack'

目前是无法抓包，我想在调试模式下允许抓包该怎么设置呢

**Comment by CarGuo** [comment]
ijkplayer 这类视频拉流并不是 http ，是基于 tcp 的 socket ，我记得 charles 只能抓 应用层，对于 TCP 不行，比如你用 wireshark
