### ISSUE TITLE
v8.1.6-jitpack 依赖无法下载

### ISSUE THREAD

**Issue by manza7014** [CarGuo/GSYVideoPlayer#3459]
## 问题描述：

v8.1.6-jitpack 依赖无法下载

## 原因：
https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/v8.1.6-jitpack/build.log 构建失败

**Comment by CarGuo** [comment]
v8.1.7-release-jitpack

**Comment by manza7014** [comment]
我知道v8.1.7-release-jitpack是可以用的，提issue之前都看过了。
想问下那之后1.8出来之后1.7也不行了么？要不停地跟着作者更新或者干脆用jar包？
公司有私服是可以的，在家办公拉不下来，不能因为这就不停的更新吧

**Comment by manza7014** [comment]
> v8.1.7-release-jitpack

我知道v8.1.7-release-jitpack是可以用的，提issue之前都看过了。
想问下那之后1.8出来之后1.7也不行了么？要不停地跟着作者更新或者干脆用jar包？
公司有私服是可以的，在家办公拉不下来，不能因为这就不停的更新吧
