### ISSUE TITLE
播放器播放时，导致ViewPager切换出现，过度动画

### ISSUE THREAD

**Issue by lvjiancong** [CarGuo/GSYVideoPlayer#3460]
## 问题描述：

播放器播放时，导致ViewPager切换出现，过度动画，停止播放的时候正常

## 问题机型/系统：

真机 红米K30，其他手机也都会

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

**Comment by lvjiancong** [comment]
https://user-images.githubusercontent.com/17497178/142975771-b60ab17a-b6c1-4e87-a34f-aead5c8a4a86.mp4

**Comment by CarGuo** [comment]
不是播放器的问题

**Comment by lvjiancong** [comment]
不是的，ViewPager我已重写了对应的setCurrentItem()方法，禁用掉了切换的动画，如下：
@Override
    public void setCurrentItem(int item) {
        super.setCurrentItem(item, false);
    }

    @Override
    public void setCurrentItem(int item, boolean smoothScroll) {
        super.setCurrentItem(item, false);
    }


但是，当视频播放的时候，还是会有切换的动画出来，当点击暂停播放的时候，又正常了

**Comment by CarGuo** [comment]
和播放器没关系，你想下就知道，播放器都拿不到你的  ViewPager
