### ISSUE TITLE
v8.1.6-jitpack 版本拉不下了，看编译日志报错了

### ISSUE THREAD

**Issue by sd6352051** [CarGuo/GSYVideoPlayer#3461]
https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/v8.1.6-jitpack/build.log

帮忙修复下吧

**Comment by CarGuo** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/10770362/142977172-16ce86b8-7944-48e8-b390-678d8945b6b8.png">

如上图所示，不是正常么？

**Comment by sd6352051** [comment]
https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-armv5/v8.1.6-jitpack/gsyVideoPlayer-armv5-v8.1.6-jitpack.aar

![image](https://user-images.githubusercontent.com/3098889/142977794-85a772e4-a3c2-48f9-9138-a73ae564c810.png)



我使用了下面几个
   ``` java
    implementation 'com.github.carguo.GSYvideoplayer:gsyVideoPlayer-java:v8.1.6-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv5:v8.1.6-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-arm64:v8.1.6-jitpack'
```
之前一直是好的，今天发现拉不下来了，看了jitpack上编译好像确实 failed 了

**Comment by CarGuo** [comment]
你点开看一下，成功的
