### ISSUE TITLE
倍数无效

### ISSUE THREAD

**Issue by 11101b** [CarGuo/GSYVideoPlayer#3465]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

设置倍数无效

## 出现问题的视频流

https://www.zositechc.cn/cloudstorage/signplaym3u8?uid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDA1OTY2ODEsInVpZCI6IjdaQjdWOEI1TEE0OEsxTUMxMTFBIn0.RuuVkDfneVP6r12LoFQkLJQvsbTiFWB60-HwqEi9CzU&channel=1&time=1638004623&sign=tktktktk

## 问题机型/系统：

例如 真机 小米9 Android11

## GSY依赖版本

例如 `implementation 'com.shuyu:GSYVideoPlayer:7.1.6'`

## Demo中的复现步骤

设置倍数无效

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
如果你用的是默认的 ijk 内核，倍速播放主要是以音频为同步时钟，所以如果倍数不支持一般都是因为音频的编码同步时钟兼容问题

**Comment by 11101b** [comment]
> 如果你用的是默认的 ijk 内核，倍速播放主要是为了同步时钟，所以如果倍数不正常，那是因为音频的编码同步一般支持问题

ok,了解，但是我的手机没升级android11之前倍数的正常的，这有什么可能的原因吗

**Comment by CarGuo** [comment]
如果是默认的 ijk 内核，你 setSpeed 的时候把 soundTouch 设置为 true 看看。

**Comment by 11101b** [comment]
> 如果是默认的 ijk 内核，你 setSpeed 的时候把 soundTouch 设置为真的看看。

感谢，但是我设置后依旧无效

**Comment by 11101b** [comment]
> 如果是默认的 ijk 内核，你 setSpeed 的时候把 soundTouch 设置为真的看看。

但是0.5倍却是有效的

**Comment by CarGuo** [comment]
感觉是系统问题，我这边测试 11 是正常的

**Comment by CarGuo** [comment]
目前我这边用 redmi note 10 pro 测试 android 11 正常，不过我是 miui 12.5.9 ，刚好有升级我升级试试，看是不是系统问题

**Comment by CarGuo** [comment]
升级完了 12.5.11，测试完了正常····

**Comment by androidHRTZ** [comment]
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.7-release-jitpack'
OPPO，Android 11系统，ColorOs V11.1
setSpeed(5f, true);
setSpeed(5f);
皆无效，请问为什么呢

**Comment by CarGuo** [comment]
只支持0.5-2

**Comment by victorfan336** [comment]
我的手机也出现了这个问题，红米k20，系统android11，也是0.5倍可以播放，1.25,1.5,2.0都设置后无效，请问这个问题解决了吗？ @CarGuo ，感觉不是个例呀，有人知道这个问题怎么解决吗？感谢。

**Comment by CarGuo** [comment]
@victorfan336 设置setspeed 的时候 soundtouch 打开

**Comment by CarGuo** [comment]
@victorfan336 设置setspeed 的时候 soundtouch 打开

**Comment by victorfan336** [comment]
> @victorfan336 设置setspeed 的时候 soundtouch 打开

setSpeed(2.0f, true)

soundtouch是打开的了

**Comment by lihaodong** [comment]
ELZ-AN00手机 android 12 版本
v8.1.6-jitpack 设置倍速大于1 无效
设置了setSpeed(2.0f, true)

**Comment by CarGuo** [comment]
同步时钟是音频，一般没有音频或者音频不兼容的情况下，是没办法倍数
