### ISSUE TITLE
Android 11使用倍速播放无效

### ISSUE THREAD

**Issue by BluePWhite** [CarGuo/GSYVideoPlayer#3466]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

小米11  Android 11

## GSY依赖版本

使用demo v8.1.7-beta3

## Demo中的复现步骤

demo上的视频播放 ， 使用 ijk内核倍速播放无效

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
已有 issue ，可见 https://github.com/CarGuo/GSYVideoPlayer/issues/3465 另外麻烦提供下机型，我这边用 redmi note 10 pro 测试 android 11 正常

**Comment by CarGuo** [comment]
升级完了 12.5.11，测试完了正常····
