### ISSUE TITLE
一个进度条控制多个任务 seekto 不同步问题

### ISSUE THREAD

**Issue by masterhan1991** [CarGuo/GSYVideoPlayer#3468]
我搜了下issue 好像没人遇到我这个问题
自定义的进度条 一个页面两个播放器 ，我想通过这一个进度条同时控制两个播放器，目前播放 暂停都是ok，但是当拖动进度条时，调用seekto后偶尔出现两个视频不同步的问题（大部分是同步的，偶尔是其中一个正常 另一个seekto的位置不对，因为测试准确性 所以两个视频的url目前是一致的），大佬分析这可能是哪里的问题。

**Comment by CarGuo** [comment]
不支持
