### ISSUE TITLE
视频缓冲时，不会自动出现视频缓冲的动画，需要手动点击才会出现

### ISSUE THREAD

**Issue by One28Piece** [CarGuo/GSYVideoPlayer#347]
视频缓冲时，不会自动出现ENDownloadView，需要手动点击才会出现，在缓冲时如何自动出现缓冲状态

**Comment by CarGuo** [comment]
demo中那个页面复现？

**Comment by One28Piece** [comment]
不是必现，有的视频会，请问下如何监听缓冲进度？

**Comment by CarGuo** [comment]
目前没有缓冲进度，需要的话你可以在onInfo回调中处理。

**Comment by arya122333** [comment]
想问一下为了实现打开视频的时候，不需要要点击就可以出现缓冲的动画怎么实现。
