### ISSUE TITLE
getGSYVideoManager().seekTo 方法快进不到准确时间

### ISSUE THREAD

**Issue by CupidLoud** [CarGuo/GSYVideoPlayer#3470]
播放一个50秒左右的mp4视频，getGSYVideoManager().seekTo快进不到准确时间位置， 误差有2秒～10秒。
请问如何提高快进精度

**Comment by CarGuo** [comment]
enable-accurate-seek 配置或者切换到 Exo2PlayerManager

**Comment by CupidLoud** [comment]
嗯嗯
