### ISSUE TITLE
释放问题

### ISSUE THREAD

**Issue by mzw0517** [CarGuo/GSYVideoPlayer#3471]
## 问题描述：

主界面有5个Fragment，通过show-hide的方式来控制。其中有一个抖音样式的视频Fragment（称为FragmentA）。但是在首页部分有一些视频分类选项，点击进去展示的UI和FragmentA一样，故直接复用了FragmentA。此时app内有两个地址不同的FragmentA的实例。当从分类FragmentA返回时，会在onDestroy()方法中调用GSYVideoManager.releaseAllVideos()。当回到主页然后点击底部tab切换到主页面的FragmentA，出现了黑屏。这肯定是视频内核被释放导致的。由于demo中都是重新进入一个新的页面，即使上个页面release了，下个页面肯定会重新创建。我的主页的FragmentA是一直存在的，不会重新创建实例。就是想请教一下有没有什么解决方案？

## 问题机型/系统：

华为P40 pro+

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)

**Comment by mzw0517** [comment]
。。。

**Comment by yuanhua0608** [comment]
兄弟，问题解决没有？遇到一样的问题
