### ISSUE TITLE
GSYVideoPlayer 播放不正确的rtmp流，会发生ANR

### ISSUE THREAD

**Issue by LemonNauyam** [CarGuo/GSYVideoPlayer#3472]
## 问题描述：

GSYVideoPlayer 播放不正确的rtmp流，会发生ANR

## 出现问题的视频流

不正确的流：rtmp://live.cctvcj.com/cctvcj/live1
正确的流：rtmp://liveplay.zhengguannews.cn/live/zzb

## 问题机型/系统：

真机 小米 11 Android 11

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的detailPlayer反复打开不正确的流：rtmp://live.cctvcj.com/cctvcj/live1后会出现这个问题。

**Comment by CarGuo** [comment]
使用 Exo2PlayerManager 播放 rtmp 试试
