### ISSUE TITLE
安全扫描到项目当前的libijkffmpeg.so库版本过低，请问有什么更新计划吗？项目当前版本是1.0.2q，最新版本是3.0.1

### ISSUE THREAD

**Issue by 99283817** [CarGuo/GSYVideoPlayer#3476]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请使用最新版本依赖

**Comment by 99283817** [comment]
最新版本的源码如何下载？

**Comment by CarGuo** [comment]
？？？

**Comment by 99283817** [comment]
😭😭 那我们确实是从网站下的源码，但确实是旧版本

**Comment by CarGuo** [comment]
那你可以从这个或者 gitee 下载新版的源码····
