### ISSUE TITLE
静音播放视频，不打断正在播放的音频

### ISSUE THREAD

**Issue by LFen** [CarGuo/GSYVideoPlayer#3477]
## 问题描述
手机后台有qq音乐正在播放音乐，打开自己的app后，列表有视频静音播放，且已经使用setNeedMute设置了静音，这个时候qq音乐还是会被打断，请问，有没有办法不打断后台的音乐而静音播放视频。

谢谢！

**Comment by LFen** [comment]
其实就是想在第三方音乐播放器播放音乐的同时静音播放视频。

**Comment by check0927** [comment]
同求这样的方式

**Comment by check0927** [comment]
主要是 音频焦点被抢占了，能不能让音频焦点不被调用

**Comment by CarGuo** [comment]
setReleaseWhenLossAudio
