### ISSUE TITLE
GSYVideoType.setShowType 可以在撥放後設置嗎?

### ISSUE THREAD

**Issue by CiaShangLin** [CarGuo/GSYVideoPlayer#3478]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
GSYVideoType.setShowType 可以在撥放後設置嗎?
在setUp之前設置GSYVideoType.setShowType的話會生效
但是影片撥放之後再做GSYVideoType.setShowType畫面沒有變化
目前處理方法是紀錄撥放的時間,然後在重新setUp設置duration
請問有沒有更好的方法?

## 出现问题的视频流
無

## 问题机型/系统：

三星A71 android11

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

问题代码：(如果有)
```
GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL)
```

## 问题log（如果有）

```



```

**Comment by CarGuo** [comment]
可以，可见 https://github.com/CarGuo/GSYVideoPlayer/blob/5aec851881fe034626fb6528929b61aba34b557d/app/src/main/java/com/example/gsyvideoplayer/video/SampleControlVideo.java#L239
