### ISSUE TITLE
有些视频播放变慢（没有设置播放速度）

### ISSUE THREAD

**Issue by SherlockGougou** [CarGuo/GSYVideoPlayer#3479]
## 问题描述：

ijk内核，有些视频播放变慢（没有设置播放速度）

## 出现问题的视频流
视频地址：
https://j1-common-bucket.s3.cn-northwest-1.amazonaws.com.cn/cs/2021/12/22/phgbFU1640166079881.mp4

## 问题机型/系统：

机顶盒，2G内存，Android 9

## GSY依赖版本

`
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.6-jitpack'
    // ExoPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.1.6-jitpack'
    // 更多的ijk编码支持
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.6-jitpack'
    // exo
    api('com.google.android.exoplayer:exoplayer:2.15.0') {
        exclude group: "com.android.support"
    }
`

## Demo中的复现步骤

Demo中的`InputUrlDetailActivity`页面指定这个URL`https://j1-common-bucket.s3.cn-northwest-1.amazonaws.com.cn/cs/2021/12/22/phgbFU1640166079881.mp4`会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by SherlockGougou** [comment]
切换到EXO问题和ijk一样，切换到系统内核反而速度会变快。

**Comment by SherlockGougou** [comment]
播放时的日志如下：
[slow.log](https://github.com/CarGuo/GSYVideoPlayer/files/7766438/slow.log)

**Comment by SherlockGougou** [comment]
视频是15s的，实际播放了24s才播放完毕。应该是盒子本身问题，在手机、电脑上播放没有问题。我想知道能不能解决。

**Comment by SherlockGougou** [comment]
GSYVideoType.enableMediaCodec();
打开硬解码好像可以解决。

**Comment by CarGuo** [comment]
是不是适配的码率比较高和帧率比较高？是的话是没办法解决的······ ijk 默认还可以试试问题集锦里的 dropframe

**Comment by SherlockGougou** [comment]
> 是不是适配的码率比较高和帧率比较高？是的话是没办法解决的······ ijk 默认还可以试试问题集锦里的 dropframe

那个视频码率最高在20M，帧率60，1080P的，是不是也不算太高？

**Comment by SherlockGougou** [comment]
![image](https://user-images.githubusercontent.com/17920617/147196055-3a16fbda-eb8e-4b00-9908-30cad94ff3b7.png)

**Comment by CarGuo** [comment]
肯定啦大哥，你是机顶盒，处理器和GPU估计都干不过来，正常 20M 的720P的都比较吃力了，你看B站为什么大会员才给 1080P 60 帧？

**Comment by SherlockGougou** [comment]
> 肯定啦大哥，你是机顶盒，处理器和GPU估计都干不过来，正常 20M 的720P的都比较吃力了，你看B站为什么大会员才给 1080P 60 帧？

好的大佬，您提到的设置丢帧设置，是以下这个方法吗？
```
mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1L);
```

**Comment by CarGuo** [comment]
```
VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

具体drop 多少你可以自己试试

**Comment by SherlockGougou** [comment]
好的，谢谢。
