### ISSUE TITLE
视频播放时，断开网络，视频继续播放，当缓存播放完以后播放器会回调onAutoComplete，不调用onPlayError

### ISSUE THREAD

**Issue by MrTrying** [CarGuo/GSYVideoPlayer#348]

**Comment by CarGuo** [comment]
哪个版本的？现在应该是有网络监听处理的

**Comment by MrTrying** [comment]
最新的，我直接使用的你的项目。网络监听确实是有，但是处理是不是有点问题
这是我断网之后的`debug  log`
![qq 20170803105606](https://user-images.githubusercontent.com/10009140/28903952-5beb7ce6-783a-11e7-8c0a-d337fd507aba.png)

**Comment by CarGuo** [comment]
以为是新构建了对象链接，旧的被释放了，不过会调到结束确实有些问题…

**Comment by MrTrying** [comment]
因为其他的播放器这种情况是会error的，或者有些重新联网之后是可以继续播放的
所以这个是不是考虑处理一下，我现在在没网的情况会直接提示设置网络并且暂停播放，避免了这个情况

**Comment by sanchibing** [comment]
这个是个问题，断网不能续播，没有办法解决

**Comment by tangjiarao** [comment]
好像我也遇到这个问题，我暂时是设置成从断网前的位置重新开始播放

**Comment by maolubin** [comment]
@CarGuo 哥，这个问题现在版本处理了吗
