### ISSUE TITLE
能否提供一下com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.7-release-jitpack 里面ijkplayer编译修改了哪部分

### ISSUE THREAD

**Issue by lemin616** [CarGuo/GSYVideoPlayer#3480]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by lemin616** [comment]
能否提供一下ff_ffplay_options.h，ff_ffplay.c，和 module.sh文件

**Comment by CarGuo** [comment]
sh脚本不就在根目录有吗？c文件我忘记我有没有放到github，你可以找找

**Comment by lemin616** [comment]
你好，ff_ffplay_options.h

> sh脚本不就在根目录有吗？c文件我忘记我有没有放到github，你可以找找

你好，ff_ffplay_options.h 和 ff_ffplay.c 我在GitHub没有找到， 我用module.sh编译so文件后引用播放ts视频seek后会灰屏，但是直接引用你们的so文件不会，我想看看那两个文件有什么区别

**Comment by lemin616** [comment]
> sh脚本不就在根目录有吗？c文件我忘记我有没有放到github，你可以找找


你好，ff_ffplay_options.h 和 ff_ffplay.c 我在GitHub没有找到， 我用module.sh编译so文件后引用播放ts视频seek后会灰屏，但是直接引用你们的so文件不会，我想看看那两个文件有什么区别

**Comment by CarGuo** [comment]
你用 module-lite-more.sh  和 module-lite.sh 试试？因为这两个文件在我另一台电脑，那台电脑我一般没带着

**Comment by lemin616** [comment]
> 你用 module-lite-more.sh 和 module-lite.sh 试试？因为这两个文件在我另一台电脑，那台电脑我一般没带着

module-lite.sh  这个文件都不支持rtsp  我用了module-lite-more.sh编译后 seek后灰屏，可以麻烦你有空的时候把ff_ffplay_options.h 和 ff_ffplay.c上传到Github吗

**Comment by lemin616** [comment]
> ff_ffplay_options.h 和 ff_ffplay.c

你好，我怀疑是我H265i硬解开启的有问题，我只要开硬解就黑屏，不开seek就灰屏，但是用你编译的so文件就能开H256硬解，可以麻烦告诉我H256硬解在编译so文件需要更改哪些地方吗
