### ISSUE TITLE
请问如何开启m3u8边播边缓存功能

### ISSUE THREAD

**Issue by Fans1994** [CarGuo/GSYVideoPlayer#3482]
问题描述：
我在BaseApplication中初始化
    PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
    CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
    ExoSourceManager.setSkipSSLChain(true);

想在播放页面进行缓存，但是这个方法已经找不到了。

 GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);模式下的cache支持

**Comment by CarGuo** [comment]
setSkipSSLChain 不需要，和缓存无关

**Comment by Fans1994** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
初始化的时候，只添加这两行 播放的时候就可以自动边播边缓存看吗？

**Comment by CarGuo** [comment]
是的，setup 或者配置的时候 cache 设置为true，但是exo的缓存不支持导出

**Comment by Fans1994** [comment]
知晓了，请问大佬现在最新的框架支持m3u8下载了吗？

**Comment by CarGuo** [comment]
支持方式和之前一样啊
