### ISSUE TITLE
横屏竖屏偶尔不能切换问题

### ISSUE THREAD

**Issue by oudengding** [CarGuo/GSYVideoPlayer#3484]
## 问题描述：
参照SimpleDetailActivityMode1，播放m3u8视频，使用Exo2内核

## 问题机型/系统：
真机 oppo ace2

## GSY依赖版本
 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.7-release-jitpack'

## Demo中的复现步骤
进入播放页点击播放，然后点击全屏按钮（或退出按钮），偶尔出现屏幕跳动，但视频不横屏的情况

问题代码：
参照 SimpleDetailActivityMode1

**Comment by CarGuo** [comment]
demo 没有复现，请注意 manifest 配置是否正常，并且代码设置对不对

**Comment by oudengding** [comment]
> demo 没有复现，请注意清单配置是否正常，并且代码设置对不对

我可以加一下你的qq，把录制的视频发给你看一下吗？
2843901270

**Comment by CarGuo** [comment]
你告诉我 demo 怎么复现更好一些

**Comment by oudengding** [comment]
public class PlayerVideoActivity extends GSYBaseActivityDetail<StandardGSYVideoPlayer> {

    private static final String KEY_CourseVideo = "courseVideo";

    private ActivityPlayerVideoBinding binding;
    private CourseVideo courseVideo;


    @Override
    protected void onDestroy() {
        super.onDestroy();
        binding = null;
        courseVideo = null;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityPlayerVideoBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        StatusBarUtil.setDarkMode(this);
        StatusBarUtil.setColor(this, Color.BLACK);

        courseVideo = getIntent().getParcelableExtra(KEY_CourseVideo);

        binding.detailPlayer.getBackButton().setOnClickListener(v -> finish());

        PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);

        initVideoBuilderMode();
    }

    @Override
    public StandardGSYVideoPlayer getGSYVideoPlayer() {
        return binding.detailPlayer;
    }

    @Override
    public GSYVideoOptionBuilder getGSYVideoOptionBuilder() {
        File cacheDir = new File(getExternalCacheDir(), AppConstants.VIDEO_CACHE_DIR);
        FileUtils.createDir(cacheDir);

        //封面
        ImageView imageView = new ImageView(this);
        loadCover(imageView, courseVideo.getCoverUrl());

        return new GSYVideoOptionBuilder()
                .setThumbImageView(imageView)
                .setNeedOrientationUtils(false)
                .setUrl(courseVideo.getVideoUrl())
                .setCacheWithPlay(true)
                .setVideoTitle(courseVideo.getTitle())
                .setThumbPlay(false)
                .setIsTouchWiget(true)
                .setRotateViewAuto(false)
                .setLockLand(false)
                .setShowFullAnimation(false)
                .setNeedLockFull(false)
                .setCachePath(cacheDir)
                .setSeekRatio(1);
    }

    @Override
    public void clickForFullScreen() {
    }

    @Override
    public boolean getDetailOrientationRotateAuto() {
        return false;
    }


    private void loadCover(ImageView imageView, String picUrl) {
        ColorDrawable defaultCover = new ColorDrawable(Color.BLACK);
        Glide.with(getApplicationContext())
                .load(picUrl)
                .error(defaultCover)
                .placeholder(defaultCover)
                .into(imageView);
    }
}

**Comment by oudengding** [comment]
<activity
            android:name=".ui.video.PlayerVideoActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
            android:screenOrientation="portrait" />

**Comment by CarGuo** [comment]
我的意思是你告诉我，我在 demo 里如何复现你的问题？

**Comment by oudengding** [comment]
> 我的意思是你告诉我，我在 demo 里如何复现你的问题？

这还真不好复现，我摸不着规律

**Comment by oudengding** [comment]
> > 我的意思是你告诉我，我在 demo 里如何复现你的问题？
> 
> 这还真不好复现，我摸不着规律

时有时无，最开始我以为是缓存的问题，但缓存完了也会偶尔出现

**Comment by oudengding** [comment]
https://user-images.githubusercontent.com/54766076/147438182-c78322a6-d3af-491c-9342-faaaad94364d.mp4

**Comment by CarGuo** [comment]
我主要是在 demo 没发现这个的问题，你看看你测试demo能不能出现，如果 demo 不出现就可能是其他问题

**Comment by CarGuo** [comment]
修改已经提交，下个版本发布～应该最近会更新
