### ISSUE TITLE
小米大部分机型设置1.0以上倍速无效

### ISSUE THREAD

**Issue by nealqpl** [CarGuo/GSYVideoPlayer#3489]
问题描述：
  小米机型setspeed设置倍速在1.0以上时无效

问题机型/系统：
  小米MIX3

GSY依赖版本

  com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.8-release-jitpack

修复代码：
  在IjkPlayerManager  82行增加如下代码：
      mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "soundtouch", 1);

![1640936713](https://user-images.githubusercontent.com/47093759/147810405-2a9e52a5-225e-44a7-abdb-3067be51aa31.png)

**Comment by CarGuo** [comment]
你在调用 setSpeed 的 api 时，有没有看到 `setSpeed(float speed, boolean soundTouch) ` 这个方式呢🤪

<img width="996" alt="image" src="https://user-images.githubusercontent.com/10770362/147810933-7dbab05f-d39b-4a37-bfbb-81bb6952f796.png">

**Comment by nealqpl** [comment]
小米的这个bug是必须在ijkmedia.prepare()前执行，你在setspeed里执行是无效的

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CarGuo** [comment]
如第二张图所示，你可以用在播放前设置，也可以通过gsy外部的option直接配置的哦！
