### ISSUE TITLE
退出全屏闪退

### ISSUE THREAD

**Issue by caowen** [CarGuo/GSYVideoPlayer#349]
在列表中播放视频点击全屏播放，退出全屏时闪退，初步排查跟设置的主题有关，
设置 windowIsTranslucent=true 退出全屏会有闪退

**Comment by CarGuo** [comment]
demo中哪个页面可以复现？

**Comment by caowen** [comment]
是我项目中的页面，问题已经解决了，是全屏屏幕旋转造成的

**Comment by 18833013313** [comment]
应该怎么解决啊
