### ISSUE TITLE
全屏播放切换资源黑屏有声音

### ISSUE THREAD

**Issue by liy452083759** [CarGuo/GSYVideoPlayer#3490]
## 问题描述：全屏播放完毕，继续播放下一个视频，有声音无画面黑屏；暂停播放按钮一直停留在画面中，点击播放按钮后，直接重新开始播放；
关键函数调用；
切换全屏：
orientationUtils.resolveByClick（）；
videoPlayer.startWindowFullscreen(this, true, true);
切换全屏后，等待播放完毕 onAutoComplete（）；
设置播放地址：
videoPlayer.setUp(source1, true, "测试视频5");
videoPlayer.startPlayLogic();
旋转：
  @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        //如果旋转了就全屏
        if (isPlay && !isPause) {
            danmakuVideoPlayer.onConfigurationChanged(this, newConfig, orientationUtils);
        }
    }
## 问题机型/系统：
例如 真机 华为p30等
## GSY依赖版本

    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.3-jitpack'
    //是否需要ExoPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.3-jitpack'

## Demo中的复现步骤

Demo中的DanmkuVideoActivity页面打开后增加播放结束回调设置播放地址播放下一首会出现这个问题。
目前能排除是view遮挡问题；

**Comment by liy452083759** [comment]
其他资源补充同样复现问题；https://res.exexm.com/cw_145225549855002

**Comment by CarGuo** [comment]
demo有播放下一个的例子，你看那个

**Comment by liy452083759** [comment]
还是能百分百复现；在播放结束后，只要不是直接在 onAutoCompletion()复写函数中设置播放地址，都能出现这个问题；通过《接口回调》，《onAutoComplete（）》《EventBus》方式调用setUp(）和startPlayLogic() ；都会出现

**Comment by liy452083759** [comment]
还是能百分百复现；在播放结束后，只要不是直接在 onAutoCompletion()复写函数中设置播放地址，都能出现这个问题；通过《接口回调》，《onAutoComplete（）》《EventBus》方式调用setUp(）和startPlayLogic() ；都会出现

**Comment by CarGuo** [comment]
demo ListGSYVideoPlayer的方式俺当时正常

**Comment by liy452083759** [comment]
demo ListGSYVideoPlayer如果通过回调的方式设置播放下一首也是有问题的

**Comment by liy452083759** [comment]
这个bug颠覆了我的认知

**Comment by liy452083759** [comment]
解决方法在所有需要获取播放器的地方getCurrentPlayer()
