### ISSUE TITLE
集成ex_so后播放mp4视频有声音无画面

### ISSUE THREAD

**Issue by androidforzhenghyc** [CarGuo/GSYVideoPlayer#3492]
## 问题描述：
1.按集成方式implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.8-release-jitpack'
//是否需要ExoPlayer模式
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.1.8-release-jitpack'
//更多ijk的编码支持
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.8-release-jitpack'
2.播放地址为:https://source.jinsubao.cn/shop/decorate/8/20211231_14c7c97ffc654085ba00e95295604e02.mp4
 编码格式是：AAC，H.264
3.控件使用
StandardGSYVideoPlayer playView = findViewById();
playView.setUpLazy("http://192.168.101.24:8030/shop/decorate/8/20211230_900877f513454c3daa5cfcfe45e270fb.mp4",true,null,null,null);
playView.startPlayLogic();
4.log主要看了IJKMEDIA
IJKMEDIA: ffp_toggle_buffering: completed: OK
IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
IJKMEDIA: FFP_MSG_COMPLETED:
IJKMEDIA: ffp_toggle_buffering: eof

结果：播放视频有声音无画面

**Comment by CarGuo** [comment]
测试，正常播放

**Comment by CarGuo** [comment]
测试 https://source.jinsubao.cn/shop/decorate/8/20211231_14c7c97ffc654085ba00e95295604e02.mp4 ，正常播放

**Comment by androidforzhenghyc** [comment]
> 测试https://source.jinsubao.cn/shop/decorate/8/20211231_14c7c97ffc654085ba00e95295604e02.mp4，正常播放，有画面

xml控件高度我给固定了
<com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
        android:id="@+id/playView"
        android:layout_width="match_parent"
        android:layout_height="150dp"
        android:layout_marginTop="@dimen/dp_10"
        android:layout_marginLeft="@dimen/dp_10"
        android:layout_marginRight="@dimen/dp_10"/>
我这边有通过playView.getTitleTextView().setVisibility(View.GONE);
                    playView.getBackButton().setVisibility(View.GONE);
移除左边返回按键以及标题，但是画面上还是存在返回按键，标题还有播放按钮。

**Comment by androidforzhenghyc** [comment]
我这边自己找下问题原因，直接放在一个Activity里可以正常播放。
目前现在不能播放是因为放在了Fragment->Fragment->RecyclerView的headView上
