### ISSUE TITLE
网安在检测报告中指出的问题：未使用编译器堆栈保护技术风险检测

### ISSUE THREAD

**Issue by androidjiajia** [CarGuo/GSYVideoPlayer#3494]
在进行app安全检测的时候指出的问题：

第1处：
文件：
lib/arm64-v8a/libijkffmpeg.so
第2处：
文件：
lib/armeabi-v7a/libijkffmpeg.so

建议开发者使用gcc编译时，使用以下参数gcc -o demo demo.c -fstack -protector -all；或者使用NDK编译SO文件时，在Android.mk文件中增加以下参数LOCAL_CFLAGS := -Wall -O2 -U_FORTIFY_SOURCE -fstack-protector-all。

**Comment by CarGuo** [comment]
not support
