### ISSUE TITLE
播放在线视频出错时无法退出全屏状态

### ISSUE THREAD

**Issue by dzl888** [CarGuo/GSYVideoPlayer#3496]
## 问题描述：

在播放一个有问题的在线视频时，最开始播放器出现一个圈表示正在加载视频，此时我按全屏按钮全屏，加载一段时间后，加载失败了，我按一下播放器，再次出现加载圈圈，但是这次出现只有一瞬间，我知道我视频是有问题的（应该是视频地址不对），此时我想返回上一个界面，点击我根本点击不到那个退出全屏的按钮，因为当我一点击屏幕的时候，就会出现加载的圈圈，应该是播放器会自动加载视频，但是圈圈瞬间就隐藏了（应该是加载失败了），同时播放控制条（包括退出全屏的按钮）也会一起隐藏，根本没有足够的时间让我去点那个退出全屏的按钮。总结问题就是，当点击屏幕后，出现控制条，但是控制条瞬间就又隐藏了，这是一个Bug，这样没办法去点控制台上的任何按钮了，导致无法退出全屏，具体操作效果可见这个gif演示图：![http://qiniu.android666.cn/play_error.gif](http://qiniu.android666.cn/play_error.gif)

## 出现问题的视频流

http://10.238.113.79:8087/rtp/150164.live.mp4   这是一个内部网络，外网应该访问不到的，但是应该也不影响问题的重现。

## 问题机型/系统：

任意Android手机!

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.6-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.6-jitpack'

## Demo中的复现步骤

播放有问题的在线视频时会出现这个问题。

## 问题log（如果有）

```

W/IJKMEDIA: No codec could be found with id 65542
A/IJKMEDIA: Failed to open file 'http://10.238.113.79:8087/rtp/150164.live.mp4' or configure filtergraph
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28131]
D/IJKMEDIA: FFP_MSG_FIND_STREAM_INFO:
D/IJKMEDIA: FFP_MSG_COMPONENT_OPEN:
D/IJKMEDIA: FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E/VideoPlayerActivity$onCreate: onPlayError: http://10.238.113.79:8087/rtp/150164.live.mp4
D/IJKMEDIA: IjkMediaPlayer_release

```

**Comment by dzl888** [comment]
效果图演示：![效果图演示](http://qiniu.android666.cn/play_error.gif)

**Comment by CarGuo** [comment]
已提交修复，下个版本 8.1.9 发布
