### ISSUE TITLE
播放有旋转角度视频，（270）视频显示有问题

### ISSUE THREAD

**Issue by liu445059658** [CarGuo/GSYVideoPlayer#3497]
## 问题机型/系统：

例如 真机 华为 nova7 se

## GSY依赖版本

例如 `implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack'`

## 问题描述

是用微信拍摄的，双手放大录制的视频，显示的画面很小居中，横向不能铺满， 视频旋转角度（270）测试出现的问题

## 问题视频地址

https://diasiatest-1301602006.cos.ap-shanghai.myqcloud.com/content/video/wx_camera_1641973699030.mp4

**Comment by liu445059658** [comment]
我是继承StandardGSYVideoPlayer重写了，xml布局也重新了，和这个有关系吗，还是有什么需要特别设置的吗

**Comment by liu445059658** [comment]
![image](https://user-images.githubusercontent.com/73976282/149255794-96afb2e9-a665-4f43-92f9-3bf82d1b08e9.png)
还是不行

**Comment by CarGuo** [comment]
不知道什么情况么，我这边demo测试正常····

**Comment by liu445059658** [comment]
好了，谢谢作者

**Comment by liu445059658** [comment]
声音好像有点问题，带上蓝牙耳机，没有声音，而是从听筒发出声音
