### ISSUE TITLE
大佬 我自定义了api弹幕解析器 全屏的时候我该在什么时机把数据set给全屏的videoplayer？

### ISSUE THREAD

**Issue by RDSunhy** [CarGuo/GSYVideoPlayer#3498]
我再cloneParams里赋值 打断点发现进入全屏时init先执行的 init的时候执行的弹幕初始化 但是全屏情况下弹幕数据是null 

小屏播放没问题 全屏播放就没数据了 我该再什么时机给全屏数据？

**Comment by CarGuo** [comment]
demo不就是有弹幕的示例吗？

**Comment by RDSunhy** [comment]
demo中通过网络下载的那块不生效
![image](https://user-images.githubusercontent.com/44076669/149715388-db5a045b-25f6-429d-bb88-22205b54eda5.png)
这块的链接我改了一个能正常访问的

然后注释掉这里 
![image](https://user-images.githubusercontent.com/44076669/149715420-248c6136-b27e-41f6-9506-ea8344a3396c.png)

提示弹幕文件下载成功了 但是弹幕不显示

**Comment by RDSunhy** [comment]
https://comment.bilibili.com/205245882.xml 这个是链接 和demo中xml的格式一样的

**Comment by CarGuo** [comment]
具体你要自己调试看看，因为这个只是 demo 的示例，我简单测试了下，是可以的，如下图


![image](https://user-images.githubusercontent.com/10770362/149759524-c002c7d7-e683-48fc-8252-b25ed8b1a407.png)
