### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by oujunjun** [CarGuo/GSYVideoPlayer#350]
I merged PlayActivity into my own project and so on got the runtime error and the single video play activity just quit.
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
logcat says:
08-03 12:51:06.781 10004-10004/com.example.jun.s I/art: Late-enabling -Xcheck:jni
08-03 12:51:06.855 10004-10017/com.example.jun.s E/HAL: load: id=gralloc != hmi->id=gralloc
08-03 12:51:06.948 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:07.423 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:07.484 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_1_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_1_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:07.551 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:07.620 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:07.698 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:07.786 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:07.856 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:07.935 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:08.040 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:08.108 10004-10004/com.example.jun.s W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/com.example.jun.s-1/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.example.jun.s-1@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
08-03 12:51:08.138 10004-10004/com.example.jun.s I/InstantRun: starting instant run server: is main process
08-03 12:51:08.238 10004-10004/com.example.jun.s I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
08-03 12:51:08.282 10004-10004/com.example.jun.s W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-03 12:51:08.459 10004-10004/com.example.jun.s I/HwCust: Constructor found for class android.widget.HwCustTextViewImpl
08-03 12:51:08.509 10004-10004/com.example.jun.s I/HwCust: Constructor found for class android.widget.HwCustTextViewImpl
08-03 12:51:08.701 10004-10068/com.example.jun.s I/System: core_booster, getBoosterConfig = false
08-03 12:51:08.717 10004-10004/com.example.jun.s E/Minikin: getFamilyForChar iscover: 0
08-03 12:51:08.764 10004-10070/com.example.jun.s E/HAL: load: id=gralloc != hmi->id=gralloc
08-03 12:51:08.765 10004-10070/com.example.jun.s I/OpenGLRenderer: Initialized EGL, version 1.4
08-03 12:51:08.839 10004-10004/com.example.jun.s W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
I feel like something went wrong of the resource files I copied from your demo project, but I cannot figure out.

It's OK to run your demo project independently.

Thank you.

**Comment by oujunjun** [comment]
I googled a lot about "failed execv dex2oat", and find no avail, please try to help me, thank you.

**Comment by CarGuo** [comment]
I not sure if your apk

**Comment by CarGuo** [comment]
I'm not sure if your application is super 64K You need multidex。and do you set ndkfilter？

**Comment by oujunjun** [comment]
I didn't set any super 64K or ndkfilter, it's my test program, I'm just trying to call PlayActivity and use the single vedio player from my project and I sopied some of your java src including res files.

**Comment by CarGuo** [comment]
I hava no idea for not repaly in demo

**Comment by oujunjun** [comment]
Thank you.
I created an empty project and try to merge your single video play activity into my own project, still got the same problem, can I send my clean project src to you, you might see what's happen by just running it, thanks for your time.

Everything is fine to run your demo project alone in my Android Studio Environment.

**Comment by oujunjun** [comment]
I put my project onto my github which name is "hello" (https://github.com/oujunjun/hello), hope you can checkout and see what's the problem, I think you can find out by just a single run, I'm a beginner. Thank you.

**Comment by CarGuo** [comment]
ok，I will have a try。

**Comment by CarGuo** [comment]
I simply modified your code for run success，you can try it by this url ：http://git.oschina.net/shuyu1991/hello

**Comment by oujunjun** [comment]
Thank you! PlayActivity is ok now, I can watch the demo video!
