### ISSUE TITLE
沉浸状态栏 的问题。

### ISSUE THREAD

**Issue by bingdu0** [CarGuo/GSYVideoPlayer#3500]
## 问题描述：

列表播放，如果一个Activity 设置了沉浸装态栏。当调用mVideoPlayer.startWindowFullscreen(mContext, true, true) 这个方法全屏的时候，就会造成全屏的布局到了装态栏的区域，如左上角的返回键，左下角的播放键 ，都在状态栏区域。

## 问题机型/系统：

真机 华为mate20 pro 

## GSY依赖版本

`implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.8-release-jitpack'`

## Demo中的复现步骤

Demo中的SimpleListVideoActivityMode1顶部加一个带颜色的导航栏，然后沉浸状态栏。这时候从列表上点击全屏按钮，全屏的布局就会到状态栏区域。沉浸状态栏用的是gyf-dev/ImmersionBar 框架。

**Comment by CarGuo** [comment]
所以 startWindowFullscreen 不是有两个 boolean 值吗？
