### ISSUE TITLE
Custom size GSYTextureView

### ISSUE THREAD

**Issue by dokhacchung98** [CarGuo/GSYVideoPlayer#3501]
Hello, I have problem with change size of the video. When first i open the video, player is black screen, but when i rerender the player, player work normal with picture. I logged and see "setRefreshRate view com.shuyu.gsyvideoplayer.render.view.GSYTextureView width: 0 and height: 0".

This is xml file
![image](https://user-images.githubusercontent.com/15797477/150321378-fcf905b5-9d12-4e6f-90a9-6aa2c3b138e8.png)

I try resize with this code in the custom video view, but this not working
![image](https://user-images.githubusercontent.com/15797477/150321652-41ef41a8-37e4-492b-8971-35ba86b0b9b4.png)

Please take me the solution. Thanks

**Comment by CarGuo** [comment]
`CustomRenderView` in demo or   `GSYVideoType.setShowType(SCREEN_TYPE_CUSTOM)` and  `GSYVideoType.setScreenScaleRatio`

![image](https://user-images.githubusercontent.com/10770362/150449871-69dd47b8-ad42-4410-b3d8-9c67aad8bc1d.png)

**Comment by dokhacchung98** [comment]
It not work. I tried CustimRenderView, and change LayoutParams on onPrepared. But when first view render, video is black screen,. When i try rerender with change size video (2dp) then video is work normal. Like video

https://user-images.githubusercontent.com/15797477/150464558-8b0e622c-2611-4f6a-8642-aabcd79c752d.mp4

.

**Comment by CarGuo** [comment]
I'm not sure what you mean ， but surface add when video prepared success .

**Comment by dokhacchung98** [comment]
@CarGuo  It means is multiple players at the same time. I set each video in a different position and one tag. but when the first rendered video, every video is a black screen but sound work.  When I click the button for set size video, the video works. So I need to change the size of the GSYTextureRenderView for the first time.

**Comment by CarGuo** [comment]
like `SampleControlVideo` in Demo ? 

Function  :   `mTextureView.invalidate()` or `mTextureView.requestLayout()`
