### ISSUE TITLE
关于全屏按钮的一个问题

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#3502]
我重写了getLayoutId设置了布局，全屏按钮的id用的也是原id:fullscreen。但是显示的是默认的全屏按钮图标，我又这样写：
  @Override
    public boolean setUp(String url, boolean cacheWithPlay, File cachePath, String title) {
        if (super.setUp(url, cacheWithPlay, cachePath, title)) {
     
            if (mIfCurrentIsFullscreen) {
                if (mFullscreenButton != null)
                    mFullscreenButton.setImageResource(getShrinkImageRes());
            } else {
                if (mFullscreenButton != null)
                    mFullscreenButton.setImageResource(getEnlargeImageRes());
            }
            return true;
        }
        return false;
    }
一开始是可以改变图标,但是我点了切换横屏 再切换回来 又变成了默认的全屏按钮 请问这是问什么 该怎么解决呢

**Comment by CarGuo** [comment]
override getShrinkImageRes()  & getEnlargeImageRes
