### ISSUE TITLE
M3U8 里面的地址没有urlencode ，加载失败

### ISSUE THREAD

**Issue by Sabirjan** [CarGuo/GSYVideoPlayer#3503]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:14
#EXTINF:13.396533,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.0.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.1.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.2.ts
#EXTINF:12.500000,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.3.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.4.ts
#EXTINF:12.500000,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.5.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.6.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.7.ts
#EXTINF:12.500000,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.8.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.9.ts
#EXTINF:12.500000,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.10.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.11.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.12.ts
#EXTINF:12.500000,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.13.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.14.ts
#EXTINF:12.500000,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.15.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.16.ts
#EXTINF:8.333333,
一年级【语文（统编版）】i u ü y w（第二课时）.m3u8.17.ts
---------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/7404699/151112017-585e1ff8-d4b6-4620-bc3e-eae5b0468304.png)

这种m3u8内容 无法播放

这个地址是没问题的，google chrome 下载成功，
切换了 三种内核，都不行。

**Comment by CarGuo** [comment]
三种内核都不行，说明不符合标准，不兼容😉
