### ISSUE TITLE
127.0.0.1链接的视频无法缓存

### ISSUE THREAD

**Issue by KobeKomi** [CarGuo/GSYVideoPlayer#3506]
因为进行了p2p代理所以所有视频url都是包含127.0.0.1的，发现无法缓存视频，请问怎么解决

**Comment by CarGuo** [comment]
不支持，因为本地缓存用的就是127代理

**Comment by KobeKomi** [comment]
> 不支持，因为本地缓存用的就是127代理

源码的地址能不能改动，改动会有影响吗？

**Comment by CarGuo** [comment]
@KobeKomi  你可以改 ProxyCache 里的对应逻辑，不改源码，你可以直接自定义 CacheManager 设置进去就可以了

**Comment by KobeKomi** [comment]
> @KobeKomi 你可以改 ProxyCache 里的对应逻辑，不改源码，你可以直接自定义 CacheManager 设置进去就可以了

好的，谢谢

**Comment by AinialJing** [comment]
![Image](https://github.com/user-attachments/assets/ecaa97f4-3e64-44ad-83f6-2e514b06d7c1)直接继承ProxyCacheManager，重写了doCacheLogic，移除掉对127.0.0.1的判断，无法播放了，是什么原因

**Comment by AinialJing** [comment]
原始路径是：http://127.0.0.1:10001/file/download?id=1208934&path=%2Fdata%2Fsafe%2F59%2Fvideo%2Fk4u9_mmexport1739160771150.mp4
经过代理路径变成：http://127.0.0.1:43927/http://127.0.0.1:10001/file/download?id=1208934&path=%2Fdata%2Fsafe%2F59%2Fvideo%2Fk4u9_mmexport1739160771150.mp4无法播放了，如此该如何解决呢？
