### ISSUE TITLE
安卓10华为手机 播放视频，有时候放着放着突然黑频了，不知道是怎么回事

### ISSUE THREAD

**Issue by amituofozhu** [CarGuo/GSYVideoPlayer#3508]
依赖版本  implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.7-release-jitpack

**Comment by CarGuo** [comment]
我这边不复现这个问题啊····需要你用 Demo 提供复现场景，黑屏时还有声音还是没有？ 如果是停止播放和是不是播放器挂了还是链接断了，网络问题还是视频源问题。

如果是有声音那是不是 surface 出现了问题
