### ISSUE TITLE
请问我参照recycleview2 中例子在项目中动态添加视频总是报错

### ISSUE THREAD

**Issue by hyr0318** [CarGuo/GSYVideoPlayer#351]
<img width="1001" alt="1" src="https://user-images.githubusercontent.com/15108892/28917917-f2ff4876-7879-11e7-8953-d91df301f100.png">

<img width="1056" alt="2" src="https://user-images.githubusercontent.com/15108892/28917930-fe889d28-7879-11e7-943b-b6de07276381.png">

**Comment by CarGuo** [comment]
你这是传入的view有父类
