### ISSUE TITLE
视频无法播放403

### ISSUE THREAD

**Issue by 50kg** [CarGuo/GSYVideoPlayer#3516]
视频流：https://player.novipnoad.com/vod/hls/1629648741673_1ggff2qfftf1.m3u8

ijk时间轴不对，exo播放错误

已经忽略证书
ExoSourceManager.setSkipSSLChain(true);

已设置m3u8
setOverrideExtension("m3u8");

已关闭缓存
setUp(videoUrl, false, title);

版本是v8.1.9-release

demo也是同样的问题，感谢

**Comment by CarGuo** [comment]
你不是提过 issue 了么之前，https://github.com/CarGuo/GSYVideoPlayer/issues/3512 ， 让你后台把问题改了，或者 setExoMediaSourceInterceptListener 自定义  DataSource 忽略 403

**Comment by 50kg** [comment]
不是同一个错误呀老大 555

**Comment by CarGuo** [comment]
你不是写了 403 ？
