### ISSUE TITLE
开始播放缓冲时候黑屏，请问如何解决

### ISSUE THREAD

**Issue by androidHRTZ** [CarGuo/GSYVideoPlayer#3517]
问题：开始播放缓冲时候黑屏，请问如何能够快速播放，如下面的图，谢谢！
代码设置：PlayerFactory.setPlayManager(Exo2PlayerManager.class);
URL：https://test.media.aibeijiayuan.com/1599623914552.mp4
出现问题机型：全部安卓手机都会
依赖：com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.7-release-jitpack

![image](https://user-images.githubusercontent.com/15447020/156564314-a2769263-fba2-4b75-9380-a7b9cd5a46bf.png)

**Comment by CarGuo** [comment]
快不快和视频源有关系，可以看 https://juejin.cn/post/7057132141875822622
