### ISSUE TITLE
建议：自定义layoutId，没有时间进度，也可以更新底部时间进度条

### ISSUE THREAD

**Issue by goodluckier** [CarGuo/GSYVideoPlayer#3518]
看了代码GSYVideoControlView的setProgressAndTime方法，发现没有mProgressBar时，不更新mBottomProgressBar，能否分开设置更新。
因为列表视频不显示mProgressBar。

**Comment by CarGuo** [comment]
其实你可以直接 override resetProgressAndTime 方法，因为他是 protected 的，如果需要定制的情况～
