### ISSUE TITLE
mp4 有声音没画面

### ISSUE THREAD

**Issue by zhouyong0330** [CarGuo/GSYVideoPlayer#352]
刚开始弄视屏，还是个新手，播放MP4有声音没有画面，请求这个怎么解决

**Comment by CarGuo** [comment]
使用exso，详情依赖方式看github首页

**Comment by zhouyong0330** [comment]
嗯，谢谢，刚开始弄视屏，这个编码什么的还不是很清楚，我引入了这个so，但是好像冲突了。

Error:Execution failed for task ':app:transformNative_libsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libijkplayer.so
	File1: D:\androidDemo\video\GSYVideoPlayer-master\app\build\intermediates\exploded-aar\com.shuyu\gsyVideoPlayer-armv7a\2.0.2\jni
	File2: D:\androidDemo\video\GSYVideoPlayer-master\app\build\intermediates\exploded-aar\com.shuyu\gsyVideoPlayer-ex_so\2.0.2\jni

**Comment by CarGuo** [comment]
根据github上的模式引用，不要重复了

**Comment by zhouyong0330** [comment]
谢谢了，已经解决

**Comment by whbbbay** [comment]
请问怎么解决的

**Comment by zhouyong0330** [comment]
只引用这两个
 compile 'com.shuyu:gsyVideoPlayer-java:2.0.2'

    compile 'com.shuyu:gsyVideoPlayer-ex_so:2.0.2'

**Comment by whbbbay** [comment]
谢谢

**Comment by caopeng000** [comment]
这个问题确实存在不好复现出来，就是加载mp4视频的时候，是有声音，无画面，请问怎么解决的，或者是我应该关注哪方面log信息呢，谢谢
