### ISSUE TITLE
你好，请问怎么播放支持加密后的m3u8格式

### ISSUE THREAD

**Issue by Alan668899** [CarGuo/GSYVideoPlayer#3522]
## 问题描述：

你好，请问怎么设置支持加密后的m3u8格式

## 问题机型/系统：
真机 小米6s Android9

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

问题代码：M3u8文件为加密的播放不了，里面不是ts链接地址

**Comment by Alan668899** [comment]
> 

不是，就是加密了，需要解密在在播放怎么弄
本来的hls链接，也就是m3u8文件是
#EXTM3U
#EXT-X-TARGETDURATION:10

#EXTINF:9.009,
http://media.example.com/first.ts
#EXTINF:9.009,
http://media.example.com/second.ts
#EXTINF:3.003,
http://media.example.com/third.ts
#EXT-X-ENDLIST
这样的，但m3u8 aes加密了的怎么播放呀

**Comment by CarGuo** [comment]
你的意思是 m3u8 文件本身自己加密了，不是 ts 加密了？如果是这种情况，推荐你把 m3u8 本地解密之后在播放

**Comment by Alan668899** [comment]
是的，那怎么播放本地m3u8文件呀

**Comment by CarGuo** [comment]
```
VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", crypto,file,http,https,tcp,tls,udp);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by Alan668899** [comment]
aes128也能播放
