### ISSUE TITLE
oppo设备在移动数据线播放弹出“你当前正在使用移动网络，继续播放将消耗流量”提示。

### ISSUE THREAD

**Issue by RiceRichhonour** [CarGuo/GSYVideoPlayer#3525]
## 问题描述：

oppo设备在移动数据线播放弹出“你当前正在使用移动网络，继续播放将消耗流量”的弹窗提示。

该弹窗很影响用户体验。请问可否关闭掉该提示。

任意的mp4视频流均可重现。

## 问题机型/系统：

oppo reno5 pro+   Android11  

## GSY依赖版本

    implementation 'com.github.carguo.GSYvideoplayer:gsyVideoPlayer-java:v8.1.7-release-jitpack'

**Comment by CarGuo** [comment]
有api，我记得关键词是show wifi xxxx

**Comment by CarGuo** [comment]
isShowNetConfirm
