### ISSUE TITLE
有一台机型出现问题

### ISSUE THREAD

**Issue by crazyzjw** [CarGuo/GSYVideoPlayer#3527]
## GSY依赖版本

  implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack'

这是bugly的上报..

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/12543049/157626801-9102e547-fc01-49df-a24e-1921d4e0c37c.png">

**Comment by CarGuo** [comment]
有没有配置ndk过滤？

**Comment by crazyzjw** [comment]
> 有没有配置ndk过滤？

配置了的...

**Comment by CarGuo** [comment]
那就很奇怪了，加载不到so，很可能是崩溃后导致的二次崩溃…

**Comment by crazyzjw** [comment]
> 

是的,我也比较纳闷..线上就那台手机会这样..

**Comment by CarGuo** [comment]
按照我的经验 ，这种log一般出现在某些场景崩溃后，导致的二次启动崩溃····感觉如果你从这个 so 丢失场景入手感觉不现实

**Comment by crazyzjw** [comment]
> 

get
