### ISSUE TITLE
请问是否支持录像功能，将视频录像

### ISSUE THREAD

**Issue by nanihaikeyi** [CarGuo/GSYVideoPlayer#3528]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不支持

**Comment by ag2s20150909** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

exoplayer https://github.com/brookmg/ExoRecord

**Comment by nanihaikeyi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ILoveLin** [comment]
大佬博主,以后会添加录像功能吗?我现在使用的VLC能实现截图,录像功能,但是感觉太笨重了,想使用博主的开源播放器,但是没录像,很难受(使用场景需要这个功能),所以很纠结换不换

**Comment by nanihaikeyi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
