### ISSUE TITLE
水印文字倾斜角度及文字虚化问题

### ISSUE THREAD

**Issue by yykou** [CarGuo/GSYVideoPlayer#3529]
## 问题描述：

⚠️ 水印文字倾斜角度问题

## 问题机型/系统：

所有系统均如此

## GSY依赖版本

最新demo基础上改造

问题代码：(如果有)
        //水印效果 参考的是demo中DetailFilterActivity 类改修结果
        binding.detailPlayer.measure(0, 0);
        Log.i("TAG", "onCreate: Width" + binding.detailPlayer.getMeasuredWidth());
        Log.i("TAG", "onCreate: Height" + binding.detailPlayer.getMeasuredHeight());
        Log.i("TAG", "onCreate: dp2px(350)" + dp2px(350));

        Bitmap bitmap = Watermark.createMirrorBitmap(Watermark.drawTextToBitmap(this, Watermark.getViewBitmap(binding.detailPlayer), "我是水印"));
//        Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher);
        mGSYVideoGLViewCustomRender = new GSYVideoGLViewCustomRender();
        mCustomBitmapIconEffect = new BitmapIconEffect(bitmap, screenWidth, binding.detailPlayer.getMeasuredHeight(), 0.6f);
        mGSYVideoGLViewCustomRender.setBitmapEffect(mCustomBitmapIconEffect);
        binding.detailPlayer.setCustomGLRenderer(mGSYVideoGLViewCustomRender);
        binding.detailPlayer.setGLRenderMode(GSYVideoGLView.MODE_LAYOUT_SIZE);

水印图单独保存 示例：
![image](https://user-images.githubusercontent.com/21016582/157795898-8d0b89e6-71f6-4907-9a61-887103f0b454.png)

效果图展示
![image](https://user-images.githubusercontent.com/21016582/157795861-3b6febc3-ed28-4b4c-91f5-aa9f3ed84647.png)

**Comment by yykou** [comment]
图一是想要的最终效果，文字不应该被虚化和角度转换，目前实际是图二的效果，麻烦问下大佬 这个要怎么进行改正？

**Comment by CarGuo** [comment]
这种具体实现你去网上找吧 ，我没有这种场景所以不是很了解，sorry
