### ISSUE TITLE
APIbug clearCache(Context context, File cachePath, String url)

### ISSUE THREAD

**Issue by yk007** [CarGuo/GSYVideoPlayer#3531]
@Override
    public void clearCache(Context context, File cachePath, String url) {
        if (TextUtils.isEmpty(url)) {
            String path = StorageUtils.getIndividualCacheDirectory
                    (context.getApplicationContext()).getAbsolutePath();
            FileUtils.deleteFiles(new File(path));
        } else {
            FileNameGenerator md5FileNameGenerator = new Md5FileNameGenerator();
            if (ProxyCacheManager.fileNameGenerator != null) {
                md5FileNameGenerator = ProxyCacheManager.fileNameGenerator;
            }
            String name = md5FileNameGenerator.generate(url);
            if (cachePath != null) {
                String tmpPath = cachePath.getAbsolutePath() + File.separator + name + ".download";
                String path = cachePath.getAbsolutePath() + File.separator + name;
                CommonUtil.deleteFile(tmpPath);
                CommonUtil.deleteFile(path);
            } else {
                String pathTmp = StorageUtils.getIndividualCacheDirectory
                        (context.getApplicationContext()).getAbsolutePath()
                        + File.separator + name + ".download";
                String path = StorageUtils.getIndividualCacheDirectory
                        (context.getApplicationContext()).getAbsolutePath()
                        + File.separator + name;
                CommonUtil.deleteFile(pathTmp);
                CommonUtil.deleteFile(path);
            }
        }
    }
当自定义了cachePath并且url传null时
会执行
    if (TextUtils.isEmpty(url)) {
            String path = StorageUtils.getIndividualCacheDirectory
                    (context.getApplicationContext()).getAbsolutePath();
            FileUtils.deleteFiles(new File(path));
        }
只会去应用内缓存目录去删除缓存，没有去指定的cachePath目录下删除文件
很简单的一个小问题，望修复

**Comment by CarGuo** [comment]
cachePath != null 不就是了么？？？

**Comment by yk007** [comment]
当url为空时进入的是if (TextUtils.isEmpty(url)) {
String path = StorageUtils.getIndividualCacheDirectory
(context.getApplicationContext()).getAbsolutePath();
FileUtils.deleteFiles(new File(path));
} 
这个分支，只会从默认缓存目录清理文件

**Comment by yk007** [comment]
![aaa](https://user-images.githubusercontent.com/10070069/159463057-a09248f2-7ae9-4c94-8f61-799f4db09c90.png)

**Comment by CarGuo** [comment]
明白了
