### ISSUE TITLE
播放回调优化

### ISSUE THREAD

**Issue by GHRLHF** [CarGuo/GSYVideoPlayer#3533]
## 问题描述：

⚠️ 播放回调优化
视频播放设置了setLooping(true) 循环播放，但是在StandardGSYVideoPlayer的 changeUiToXX 方法打印时 只会开始走一次changeUiToNormal  然后缓冲时走changeUiToPlayingBufferingShow 以及每次再次播放走changeUiToPlayingBufferingShow，
像 changeUiToCompleteXX 方法没有回调
请问是否有其他回调方法 告知本次播放已完成

https://user-images.githubusercontent.com/14348239/158506070-94bed3fb-0259-4dd6-bfd7-3c25e53b729f.mp4

### ❗❗❗⚠️⚠️⚠️这个很重要！！！！没有问题流的问题无法处理复现⚠️⚠️⚠️❗❗❗
暂无视频流

## 问题机型/系统：
全部

## GSY依赖版本
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack

## Demo中的复现步骤

问题代码：(如果有)

**Comment by GHRLHF** [comment]
循环播放时 播放完成一次会再次加载一次 走changeUiToPlayingBufferingShow 导致加载动画闪现一次 是否有其他机制或回调方法告知本次播放(包含缓冲加载)完成，不需要再次显示加载动画。感谢！

**Comment by CarGuo** [comment]
切换到  Exo2PlayerManager 呢？
