### ISSUE TITLE
视频会稍微被拉伸

### ISSUE THREAD

**Issue by raqusty** [CarGuo/GSYVideoPlayer#3537]
问题描述：
竖屏全屏播放的时候，视频稍微被横向拉伸

出现问题的视频流
http://pic-sk.oss-cn-shenzhen.aliyuncs.com/test/chat/video/202203/17/170d8013b606f0373c8719f248f50e1d

![微信图片_20220321153159](https://user-images.githubusercontent.com/13335326/159220347-7d1577d4-9aa8-4dfc-b13e-a69dbf8e2591.jpg)
![微信图片_20220321153601](https://user-images.githubusercontent.com/13335326/159220364-eb7152b3-9630-4f25-8c0e-8731b12411a3.jpg)

## 问题机型/系统：
OPPO Reno Android 11

GSY依赖版本
implementation 'gsyVideoPlayer-java:v8.1.9-release-jitpack

Demo中的复现步骤
使用com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer这个类的话，就会出现这个问题
使用com.shuyu.gsyvideoplayer.video.LandLayoutVideo这个类的话，就没有问题

问题代码：
video_view.setUp(url,true,"")
video_view.startPlayLogic()

<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/rootView">

    <com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</RelativeLayout>

发现问题是：
R.layout.video_layout_standard 的xml 中 surface_container id使用的控件是 RelativeLayout，如果替换成 FrameLayout 就没有问题了
具体是什么导致的bug，没有细看

[最后，这个库很棒]

**Comment by CarGuo** [comment]
哈哈哈，文档里有写的，如下图所示：

![image](https://user-images.githubusercontent.com/10770362/160736927-b884f984-3303-428e-986f-5ce96609d5fb.png)
