### ISSUE TITLE
想在进度条上加锚点

### ISSUE THREAD

**Issue by mackkill** [CarGuo/GSYVideoPlayer#354]
如标题，想给进度条上加锚点，就是特点时刻显示一张或多张图片，能否给点思路，谢谢了。

**Comment by CarGuo** [comment]
具体是怎么样？有效果图参考吗？

**Comment by mackkill** [comment]
![image](https://user-images.githubusercontent.com/9410727/29016985-58edbc48-7b87-11e7-9dbe-246b05be99c3.png)
就类似这种，在某些时段插入一张图片显示在进度条上方，不知道能否看清？

**Comment by CarGuo** [comment]
这个你可以自定义进度条，继承原本的进度条实现，我怎么记得群里有人实现过

**Comment by mackkill** [comment]
楼主麻烦问下这个可以禁用旋转吗？就是全屏也是竖屏不会变横屏，我看文档里面设置如下：
orientationUtils = new OrientationUtils(this, picGSYVideoPlayer);
        //初始化不打开外部的旋转
        orientationUtils.setEnable(false);

        picGSYVideoPlayer.startPlayLogic();
        picGSYVideoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                picGSYVideoPlayer.startWindowFullscreen(PreViewActivity.this, true, true);
            }
        });
但是没有效果，而且横屏后actionbar都没隐藏，屏幕下面会有一块黑区域。。。

**Comment by CarGuo** [comment]
首先确定你的manifest配置正确的，然后对应的隐藏bar在全屏接口的时候有对应参数。禁止旋转有个setAutoRxxx旋转的接口，然后setland之类的接口表示全屏后不横屏，具体看源码中的。

**Comment by mackkill** [comment]
嗯，明白了，设置以下三个就可以了；不过希望文档上能说明下，因为文档只提到了下面两个的配合使用，具体不研究还真不清楚。。。还有建议下有些数值定义成常量会方便阅读些，例如mIsLand。当然这只是个人的建议，最后还是感谢楼主的开源~~~
        orientationUtils.setEnable(false);
        videoPlayer.setRotateViewAuto(false);
        videoPlayer.setLockLand(false);
