### ISSUE TITLE
急，视频显示比例 有宽度全屏，高度自适应这种吗

### ISSUE THREAD

**Issue by zhangqilu** [CarGuo/GSYVideoPlayer#3541]
你好 ，视频显示比例 有宽度全屏，高度自适应这种吗？谢谢

**Comment by CarGuo** [comment]
GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_CUSTOM);
GSYVideoType.setScreenScaleRatio(16.0f/9);

或者参考 Demo 的  CustomRenderView

**Comment by zhangqilu** [comment]
GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_CUSTOM);
GSYVideoType.setScreenScaleRatio(9.0f/16);
这样会被拉伸，这个没有现成解决方案吗

**Comment by zhangqilu** [comment]
> GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_CUSTOM); GSYVideoType.setScreenScaleRatio(9.0f/16);
> 
> 或者参考 Demo 的 CustomRenderView

1.GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_CUSTOM);
GSYVideoType.setScreenScaleRatio(9.0f/16);
这样会被拉伸，这个没有现成解决方案吗
2.参考 Demo 的 CustomRenderView
这个在demo中没有具体的例子
哥能帮忙说说具体怎么设置吗
