### ISSUE TITLE
为什么列表切换视频的时候要先releaseMediaPlayer，再调用initVideoPlayer重新初始化IMediaPlayer呢？能否列表中只有初始化一次IMediaPlayer，切换视频的时候使用不同的视频资源再继续播放呢？

### ISSUE THREAD

**Issue by fmtjava** [CarGuo/GSYVideoPlayer#3544]
## 问题描述：

为什么列表切换视频的时候要先releaseMediaPlayer，再调用initVideoPlayer重新初始化IMediaPlayer呢？能否列表中只有初始化一次IMediaPlayer，切换视频的时候使用不同的视频资源再继续播放，这样实现是否更好？

**Comment by CarGuo** [comment]
不能，建议参考 https://juejin.cn/post/7057132141875822622
