### ISSUE TITLE
GSYVideoView  clearCurrentCache()  NullPointerException 

### ISSUE THREAD

**Issue by Holla-Chris** [CarGuo/GSYVideoPlayer#3546]
## 问题描述：
bug收集后台收集了一些线上用户的NullPointerException，我们无法复现该问题
项目中没有主动调用clearCurrentCache()方法的地方

## 问题机型/系统：
V2026 Android11.0
vivo 1904   Android11.0
CPH2185 Android10.0
CPH2083 Android9.0
vivo 1816  Android8.1.0
vivo 1612 Android7.0
HOT 4 Pro Android6.0
等。。。

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.6'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.6'

## Demo中的复现步骤
不清楚复现步骤

## 问题log（如果有）
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference

com.shuyu.gsyvideoplayer.video.base.GSYVideoView.clearCurrentCache (GSYVideoView.java:745)
com.shuyu.gsyvideoplayer.video.base.GSYVideoView.deleteCacheFileWhenError (GSYVideoView.java:573)
com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onError (GSYVideoView.java:684)
com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.onError (GSYVideoControlView.java:299)
com.shuyu.gsyvideoplayer.GSYVideoBaseManager$5.run (GSYVideoBaseManager.java:305)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:233)
android.app.ActivityThread.main (ActivityThread.java:7225)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:499)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:962)

**Comment by CarGuo** [comment]
考虑是否属于二次崩溃的log

**Comment by Holla-Chris** [comment]
感觉不像，如果是二次崩溃，应该会有等量或者相近数量的crash，但这个问题在我们所有问题中排名第一，其它无出其右。能否在contains前判断下mUrl是否为空？（虽然我不清楚mUrl会在什么情况为空）

**Comment by CarGuo** [comment]
但是 745 行是   if (getGSYVideoManager().isCacheFile() && mCache) {

也即是 getGSYVideoManager() == null 的时候···我不是很明白什么时候 getGSYVideoManager() 会是 null ，除了出现 crash 的时候····

**Comment by Holla-Chris** [comment]
您看错版本了吧

    /**
     * 清除当前缓存
     */
    public void clearCurrentCache() {
        if (getGSYVideoManager().isCacheFile() && mCache) {
            //是否为缓存文件
            Debuger.printfError("Play Error " + mUrl);
            mUrl = mOriginUrl;
            getGSYVideoManager().clearCache(mContext, mCachePath, mOriginUrl);
        } else if (mUrl.contains("127.0.0.1")) {  // ***745行***
            getGSYVideoManager().clearCache(getContext(), mCachePath, mOriginUrl);
        }

    }

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/162709890-06ebc8ac-944b-4f7e-a98f-5585283a8871.png)

**Comment by Holla-Chris** [comment]
Thanks for the reply!

**Comment by tribbianiwang** [comment]
> 但是 745 行是 if (getGSYVideoManager().isCacheFile() && mCache) {
> 
> 也即是 getGSYVideoManager() == null 的时候···我不是很明白什么时候 getGSYVideoManager() 会是 null ，除了出现 crash 的时候····

麻烦问下745行看起来像是”判断“播放中的url是否已经缓存“并且“是否播边边缓冲”，为什么表示“ getGSYVideoManager() == null ”?
