### ISSUE TITLE
如何实现进度条只允许向前拖动（回看），不允许向后拖动（快进）功能？

### ISSUE THREAD

**Issue by a1782680475** [CarGuo/GSYVideoPlayer#3547]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
你需要自己重写 seekbar 的功能，然后 getLayoutId 里使用你的自己 seekbar

或者你 override onStopTrackingTouch 方法，然后自己重写逻辑判断

**Comment by a1782680475** [comment]
Thank u

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Shuyu ***@***.***>
发送时间: 2022年4月11日 11:09
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [CarGuo/GSYVideoPlayer] 如何实现进度条只允许向前拖动（回看），不允许向后拖动（快进）功能？ (Issue #3547)


你需要自己重写 seekbar 的功能，然后 getLayoutId 里使用你的自己 seekbar

或者你 override onStopTrackingTouch 方法，然后自己重写逻辑判断

―
