### ISSUE TITLE
进度监听

### ISSUE THREAD

**Issue by zhouyong0330** [CarGuo/GSYVideoPlayer#355]
我想要监听播放进度，拿到总进度和当前进度。我试了下重写setProgressAndTime（）方法，在小屏的时候可以监听到，全屏之后就监听不到了，全屏应该是刷新页面l，导致我的监听重置了，我想知道有没有集成进去的现成的监听方法？求告知

**Comment by CarGuo** [comment]
不是很理解，不过如果你想要你的自定义设置在全屏和非全屏同时生效，那么参考startFull那个方法的内部实现，继承后增加自定义操作。
