### ISSUE TITLE
url 图片1080*1440加载拉伸

### ISSUE THREAD

**Issue by BruceWu16** [CarGuo/GSYVideoPlayer#3552]
左右拉伸了 , 下面是视频地址 , 在浏览器播放没问题 , 在app上就拉伸了
http://cdn1.purechat.in/6162f836fbc8aa18363d5f92/20220222/video/1645484317222.mp4

**Comment by CarGuo** [comment]
如下图，测试正常

<img width="883" alt="image" src="https://user-images.githubusercontent.com/10770362/164427047-d013c9ac-6887-4443-ba82-304ab370b193.png">

**Comment by BruceWu16** [comment]
拉伸了 , 重写video_layout_standard 布局里面的RelativeLayout  surface_container 改成  FrameLayout 就正常了
