### ISSUE TITLE
请问如何修改可以支持2、4、8倍数播放

### ISSUE THREAD

**Issue by liangdongbo** [CarGuo/GSYVideoPlayer#3553]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

您好，请问如何修改可以支持2、4、8倍数播放

## 问题机型/系统：

例如 真机 

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.6'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
只支持 0.5-2 ，超过的 MediaCodec 暂时不支持，IJKPlayer 部分你可能需要自己修改 AVFilter 相关
