### ISSUE TITLE
是否有类似源码中switchTargetView的方法

### ISSUE THREAD

**Issue by dengzhao7053** [CarGuo/GSYVideoPlayer#3554]
您好 我想请教下PlayerView中有这样的方法，来切换指定播放器的视图。
/**
   * Switches the view targeted by a given {@link Player}.
   *
   * @param player The player whose target view is being switched.
   * @param oldPlayerView The old view to detach from the player.
   * @param newPlayerView The new view to attach to the player.
   */
  public static void switchTargetView(
      Player player, @Nullable PlayerView oldPlayerView, @Nullable PlayerView newPlayerView) 

我有一个这样的需求，同个界面同时播放两个不同视频，但是分为主播放视图，和副播放视图，我想使用你的开源库，怎样动态去切换这两个播放器的视图呢（就是让这两个播放器播放的内容调换一下）？如果我想加的话 应该加在哪里呢

**Comment by CarGuo** [comment]
如果我理解没错的话，通过调用 Manager 的 setDisplay 可以实现类似的效果

**Comment by dengzhao7053** [comment]
> 

目前多任务播放我用的MultiSampleVideo。
我通过PlayerManager的showDisplay(final Message msg)方法，将副PlayerView的surface set给主PlayerView  主PlayerView原视频还在播放，但是界面一直闪,，闪的画面里有副PlayerView的视频画面，然后副PlayerView暂停不播了。不知道我讲清楚没，

**Comment by dengzhao7053** [comment]
> 如果我理解没错的话，通过调用每个播放器的 Manager 的 setDisplay 可以实现类似的效果

目前多任务播放我用的MultiSampleVideo。
我通过PlayerManager的showDisplay(final Message msg)方法，将副PlayerView的surface set给主PlayerView 主PlayerView原视频还在播放，但是界面一直闪,，闪的画面里有副PlayerView的视频画面，然后副PlayerView暂停不播了。不知道我讲清楚没，

**Comment by CarGuo** [comment]
是否考虑在 setDisplay 的时候，顺便把 Manager 也切换了？
