### ISSUE TITLE
RecyclerVie切全屏时全屏显示不全 

### ISSUE THREAD

**Issue by abneryan** [CarGuo/GSYVideoPlayer#3555]
## 问题描述：

RecyclerView 中item 当切到全屏时会出现屏幕的一部分显示空白
![2](https://user-images.githubusercontent.com/16166235/164953279-f7a021e9-2143-4b6b-9b02-16e905f8405a.png)

## 问题机型/系统

：
![4](https://user-images.githubusercontent.com/16166235/164953137-4092c986-86df-4b8f-aa00-24e4b3cab1f7.png)

- 

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'`

**Comment by CarGuo** [comment]
请看demo的配置

**Comment by abneryan** [comment]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/16166235/165010421-f6e3dc7a-835f-4655-a528-cd5ce94b6d31.png">

<img width="826" alt="image" src="https://user-images.githubusercontent.com/16166235/165010458-3843810f-4bd7-48a6-bb60-86bd4975c3d0.png">

<img width="884" alt="image" src="https://user-images.githubusercontent.com/16166235/165010474-8c0fe7d3-ed62-4e9f-93fc-819a4497e299.png">
这些是我manifest清单文件中配置信息，该问题不是必现的，一旦出现之后只有杀死进程才能恢复，请帮忙排查一下，谢谢！！！

**Comment by CarGuo** [comment]
没能复现

**Comment by abneryan** [comment]
您的demo里确实没能复现出来

**Comment by CarGuo** [comment]
是啊，不能复现我也没办法……

**Comment by abneryan** [comment]
源码中我看是这里进行播放器的宽高计算的，我debug 拿出来的宽高也是正常的，出现我的这种情况，我应该从哪些方便着手分析那，希望您能给一些建议，谢谢！
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/16166235/165429627-7b9a7062-cb1a-4dfd-beb9-7e608a774fb7.png">

**Comment by CarGuo** [comment]
出现类似问题，我怀疑要不就是被系统回收导致没有回复，要不就是什么地方 crash 恢复导致这个情况，具体没有复现方法我也猜测不出来
