### ISSUE TITLE
添加依赖v8.2.0-release-jitpack版本后报错

### ISSUE THREAD

**Issue by wangpingtaohn** [CarGuo/GSYVideoPlayer#3556]
## 问题描述：

项目添加implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.2.0-release-jitpack'后，编辑报错，报错如下：
`
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\ebb8ac50284e1ee9c93a52d79ac9fac0\res\values\values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.

`

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.2.0-release-jitpack'

## Demo中的复现步骤

问题代码：(如果有)
```

```

## 问题log（如果有）

```

`Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\ebb8ac50284e1ee9c93a52d79ac9fac0\res\values\values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.
`

```

**Comment by CarGuo** [comment]
没看出来这个错和gsy的关系

**Comment by bigbiglemon** [comment]
@wangpingtaohn 我想应该是某个版本中升级了compileSdkVersion，你可以尝试一下将项目compileSdkVersion升级到31+

**Comment by CarGuo** [comment]
complie 版本是 31现在

**Comment by Hacker1248084491** [comment]
工程中 自己的代码或者引入的第三方库中 androidx.core:core-ktx 和androidx.core:core 这两个库版本在1.7.0及以上  complie版本不是31  就会报这个错

**Comment by CarGuo** [comment]
androidx.core:core-ktx 和 androidx.core:core 可以通过 gradle 强行指定为自己版本，但是  complie 需要 31 现在

**Comment by wangpingtaohn** [comment]
把complie 改为31，不报错了
