### ISSUE TITLE
自定义缓存层，ProxyCacheManager 调整默认视频缓存大小

### ISSUE THREAD

**Issue by 24suixinsuoyu** [CarGuo/GSYVideoPlayer#3559]
## 问题描述：

机器是一款大屏的广告机，需求是自动播放、循环播放一段视频。使用GSYVideoPlayer已实现该需求。

现在新的需求是，产品设计会输出更高清的视频文件（1.6G左右）。而我们默认的视频文件大小是512M，所以需要自定义缓存层更改默认缓存视频文件的大小。

研究项目之后，请问下面处理是否正确？

1. 设置缓存管理器：CacheFactory.setCacheManager(new ProxyCacheManager())
2. 自定义实现 ProxyCacheManager：其中，默认缓存大小变量 DEFAULT_MAX_SIZE 由 512 * 1024 * 1024 改为 2 * 1024 * 1024 * 1024（2G）

## 问题机型/系统：

43英寸广告机平板，Android 9.0系统

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.9-release-jitpack'

## Demo中的复现步骤

无

## 问题log（如果有）

无

**Comment by CarGuo** [comment]
是的，设置 ProxyCacheManager 的 DEFAULT_MAX_SIZE 就可以，可以设置更大，具体看你需要

**Comment by 24suixinsuoyu** [comment]
实际操作的时候刚刚发现，如果把 DEFAULT_MAX_SIZE 改为2G大小，即：2 * 1024 * 1024 * 1024，这个值正好是2的31次幂。而 DEFAULT_MAX_SIZE 的数据类型是 int，int取值的最大值正好是 （2的31次幂 - 1）。所以IDE提示：“This operation has led to an overflow"，即超出取值范围。

多数情况下，机器的磁盘都有几十G，所以2G的缓存大小是可以接受的、而且产品需求可能设计如此甚至更甚。所以，我的想法是把 DEFAULT_MAX_SIZE 的数据类型改成 long，大佬看下是否OK？是否需要我这边提一个PR？

**Comment by 24suixinsuoyu** [comment]
另外，还有一个相关的问题，除了 DEFAULT_MAX_SIZE，还有一个限制变量是 DEFAULT_MAX_COUNT，即最大的缓存文件数量。看代码可知，如果设置DEFAULT_MAX_COUNT为一个大于0的值，那么优先走 builder.maxCacheFilesCount(DEFAULT_MAX_COUNT) 逻辑、而非 builder.maxCacheSize(DEFAULT_MAX_SIZE) 逻辑。

那么，当 DEFAULT_MAX_COUNT 大于0时，每个缓存文件的大小是多少呢？是默认的512M吗？

**Comment by CarGuo** [comment]
@24suixinsuoyu 这个确实是个问题，我改下，这里应该是 long 而不是 int 
另外我记忆中，DEFAULT_MAX_COUNT 的话，是不限制大小的，你可以直接设置 DEFAULT_MAX_COUNT 来达到要求

**Comment by 24suixinsuoyu** [comment]
> @24suixinsuoyu 这个确实是个问题，我改下，这里应该是 long 而不是 int 另外我记忆中，DEFAULT_MAX_COUNT 的话，是不限制大小的，你可以直接设置 DEFAULT_MAX_COUNT 来达到要求

明白，我的意思是，设置了 ```DEFAULT_MAX_COUNT``` 之后，比如20，那么总共有20个缓存文件，那么每个缓存文件的大小又是多少呢？还是512M吗
