### ISSUE TITLE
如何监听全屏返回键，求告知

### ISSUE THREAD

**Issue by zhouyong0330** [CarGuo/GSYVideoPlayer#356]

**Comment by zhouyong0330** [comment]
我找到了如何监听全屏模式下监听返回键d方法，分享一下
final GSYBaseVideoPlayer gsyBaseVideoPlayer = video_item_player.startWindowFullscreen(context,false,true);
        gsyBaseVideoPlayer.getBackButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                video_item_player.clearFullscreenLayout();
                video_item_player.setStandardVideoAllCallBack(null);
                video_item_player.releaseAllVideos();
            }
        });

**Comment by CarGuo** [comment]
good!
