### ISSUE TITLE
自动播放出现的无法完整播放的问题

### ISSUE THREAD

**Issue by RiceRichhonour** [CarGuo/GSYVideoPlayer#3562]
## 问题描述：

我从fragment的list列表跳转到独立的activity 视频播放界面进行播放，播放几秒（5-10s）后就走了回调的 onComplete方法，未能完整播放，再次手动进行点击播放就能完整播放。

把跳转逻辑写到activity界面，或者一些fragment界面（比如设置分享），就可以跳转而且完整播放

## 出现问题的视频流
 https://locallimit.us.sinaimg.cn/o0/CLsZUIrllx07VyFhzYcU01041200aKC10E010.mp4?label=mp4_ld&template=640x360.25.0&trans_finger=6006a648d0db83b7d9951b3cee381a9c&ori=0&ps=1BThihd3VLAY5R&Expires=1650942591&ssig=iWzGScTqgI&KID=unistore,video

## 问题机型/系统：

华为mate30pro  2.0鸿蒙系统，测试小米魅族oppo机器无此问题。

## GSY依赖版本

implementation 'com.github.carguo.GSYvideoplayer:gsyVideoPlayer-java:v8.1.7-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-arm64:v8.1.7-release-jitpack'

代码：
```
startActivity(new Intent(getActivity(), ActivityVideoViews.class));


 detail_player.setUpLazy(videoUrl, true, null, null, "")

       detail_player.fullscreenButton.setOnClickListener(View.OnClickListener {
           detail_player.startWindowFullscreen(this, false, true)
       })

       //是否根据视频尺寸，自动选择竖屏全屏或者横屏全屏
       detail_player.isAutoFullWithSize = true
       //音频焦点冲突时是否释放
       detail_player.isReleaseWhenLossAudio = false
       //全屏动画
       detail_player.isShowFullAnimation = true

       detail_player.post {
           detail_player.startPlayLogic()      
       }

```

谢谢，希望得到解答

**Comment by RiceRichhonour** [comment]
不设置自动播放也会出现该问题

**Comment by CarGuo** [comment]
Demo 测试没发现播放有什么问题

**Comment by RiceRichhonour** [comment]
> Demo 测试没发现播放有什么问题

我一时也难以定位到问题所在，在项目的一些界面跳过去就不存在此问题，一些fragment跳过去就有这个问题，播放5-10s停止了，直接oncompete了。而且只在鸿蒙里面出现，代码也写得很简单了。

用隔壁的jiaozi不存在这个问题，但是我不太想用那个。

**Comment by CarGuo** [comment]
你可以试试 demo 怎么复现，我怀疑是在生命周期使用 Manager  上有问题。
因为默认只有一个内核，也就是只有一个播放器，是不是什么地方 release 了或者什么操作，导致了跳过去的页面播放释放了，默认 Manager 也是单例

**Comment by RiceRichhonour** [comment]
好的，感谢，我排查一下问题吧，其实在播放的界面，为了排除这些所有的生命周期方法我也都注释掉了，只保存最基本的播放api，应该还是跟来自哪儿的跳转有关，我再排查排查，感谢你的回复。

**Comment by RiceRichhonour** [comment]
> 你可以试试 demo 怎么复现，我怀疑是在生命周期使用 Manager 上有问题。 因为默认只有一个内核，也就是只有一个播放器，是不是什么地方 release 了或者什么操作，导致了跳过去的页面播放释放了，默认 Manager 也是单例

已经定位到问题，是fragment列表也有视频播放，因此我在onstop加入了realsevideo操作，在鸿蒙系统里面这个操作居然还影响了下个界面的视频播放，，，是我没想到的，十分感谢
