### ISSUE TITLE
播放的时候怎么替换的默认的 User-Agent ,

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#3564]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

//这样设置User-Agent 好像没生效
List<VideoOptionModel> list = new ArrayList<>();
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "User-Agent", "Mozi");
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

//setup的时候设置 headmap,会出现两个 User-Agent

![image](https://user-images.githubusercontent.com/6526280/165884968-4e04ef0f-2976-4c72-b00a-165aea62686f.png)

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

最新demo

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
切换到 Exo2PlayerManager ，然后用 https://github.com/CarGuo/GSYVideoPlayer/blob/54dd101fcdd7b49e61ab613c3ee7e2c0c06e3ca7/app/src/main/java/com/example/gsyvideoplayer/GSYApplication.java#L60
