### ISSUE TITLE
视频库不支持mkv格式的视频播放，需要做什么操作吗

### ISSUE THREAD

**Issue by youlongxifeng** [CarGuo/GSYVideoPlayer#3565]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ 视频库不支持mkv格式的视频播放

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.2.0-release-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
播放mkv格式的视频没有声音。
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
如果发现不支持，可以直接修改so，自己编译新的

**Comment by youlongxifeng** [comment]
如果编译一个全部都支持的so文件麻烦吗?您老多少酬劳可以帮我做一下，我实在玩不下来。
