### ISSUE TITLE
作者你好,Exoplayer无缝切换效果的例子能不能换成SystemPlayerManager系统播放器

### ISSUE THREAD

**Issue by excellenttank** [CarGuo/GSYVideoPlayer#3566]
你好,机器RK3229

用了Demo中的ExoPlayer无缝切换效果的例子播放本地4K视频时卡顿 ,

之前测试的系统的PlayerFactory.setPlayManager(SystemPlayerManager.class);播4K视频不卡顿,但是没有无缝切换效果,

想问下ExoPlayer中的无缝切换能不能换播放器换成SystemPlayerManager这个系统播放器,或者说是哪个设置没有设置好,

已经设置硬解

**Comment by excellenttank** [comment]
还有就是AVI格式的支持，还需要按照https://github.com/CarGuo/GSYVideoPlayer/issues/1206中的方式编译码 替换其中的zip没有效果 branch-avi怎么没看到这个分支

**Comment by CarGuo** [comment]
哦，branch-avi 之类的分支因为之前项目占用体积等原因，清理掉了，那个也是软解码的 so 库实现而已····· 无缝切换换成SystemPlayerManager 有为什么问题吗？

**Comment by excellenttank** [comment]
> 哦，branch-avi 之类的分支因为之前项目占用体积等原因，清理掉了，那个也是软解码的 so 库实现而已····· 无缝切换换成SystemPlayerManager 有为什么问题吗？

Demo中的自定义Exo是不是不支持Avi怎么才能支持呢，

**Comment by excellenttank** [comment]
然后Exo设置这个无效 .setOverrideExtension("avi");
![image](https://user-images.githubusercontent.com/16424424/166888134-38e4671e-4a45-42c6-a4a8-862c2a1ff8f4.png)

**Comment by CarGuo** [comment]
74fd85e7403d5cb2fbf68159d4027e72ec551ec1 avi 的是这个提交，走 ijk 的

**Comment by excellenttank** [comment]
> [74fd85e](https://github.com/CarGuo/GSYVideoPlayer/commit/74fd85e7403d5cb2fbf68159d4027e72ec551ec1) avi 的是这个提交，走 ijk 的

现有的Exo模式怎么才能支持avi播放，或者有没有AviExtractor

**Comment by CarGuo** [comment]
https://github.com/google/ExoPlayer/pull/9915
