### ISSUE TITLE
播放网络视频时使用缓存，多次seek会出现缓冲过的不播放

### ISSUE THREAD

**Issue by Equalzys** [CarGuo/GSYVideoPlayer#3568]
所有机型

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:v8.2.0-release-jitpack'`

## Demo中的复现步骤

配置使用：IjkPlayerManager+ProxyCacheManager；

1、播放一个网络视频，如：https://rr2---sn-q0c7rn76.googlevideo.com/videoplayback?expire=1652198423&ei=tzd6YpTHELaekwaOgYGgCg&ip=2001%3A470%3A1f04%3A726%3A%3A438&id=o-ADDWKCy6NgZwK39I5hj_8saaXNXliYDc-7ongAe0C9Cq&itag=22&source=youtube&requiressl=yes&mh=Tl&mm=31%2C26&mn=sn-q0c7rn76%2Csn-5uaeznr6&ms=au%2Conr&mv=m&mvi=2&pl=57&initcwndbps=82500&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1096.469&lmt=1647049160206142&mt=1652176128&fvip=5&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgdJAel5lervpaG1XYkdYPBWpt9cRF8y_FKhx_nI1_fhUCIQCB888RTZUxxBQqn1xtbBozD554F591rScakIG9bwNPLA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJNsPhLgv386dm8wCgumJ-oQj-7SS3qz2XOUvyYIabbKAiEArXLgQRLQN4yBSZqPVzu_GfVYt159B8MXfDbiHbCBT4Y%3D

2、播放，等待缓冲一段时间，比如缓冲10秒；
3、seek到大于10秒，比如2分钟，会正常出现等待；
4、再次seek到之前缓冲过的0-10秒，比如5秒，就会出现不再播放的问题；

**Comment by CarGuo** [comment]
你的了解我播放不了，但是我用demo测试，正常

**Comment by Equalzys** [comment]
> 你的了解我播放不了，但是我用demo测试，正常

随便找个长点的视频，seek距离缓冲远点，再seek回来就会复现，demo视频加载的太快了

**Comment by Equalzys** [comment]
> 你的了解我播放不了，但是我用demo测试，正常

而且这个bug是androidvideovache库的bug

**Comment by Equalzys** [comment]
> 配置使用：IjkPlayerManager+ProxyCacheManager；

dmeo里application配置：IjkPlayerManager+ProxyCacheManager；
进入SimpleActivity-> SimplePlayer页面，  String source1 = "http://video.cdn.aizys.com/zzx3.9g.mkv";

**Comment by CarGuo** [comment]
如下视频所示，正常

https://user-images.githubusercontent.com/10770362/167798481-f974b562-6640-47b0-b64d-99e22c6f3f9f.mp4

**Comment by Equalzys** [comment]
> 如下视频所示，正常
> 
>  1652255746668232.mp4

https://user-images.githubusercontent.com/17246251/167801081-738cc532-9584-4f59-8eb8-59222a7ae293.mp4

**Comment by Equalzys** [comment]
> > 如下视频所示，正常
> > 1652255746668232.mp4
> 
>  Record_2022-05-11-16-08-12_f6f1ca16758004fdc944f9a540e9845e.mp4

此时就会出现不管怎么seek都不会播放，只能退出页面重新播放

**Comment by CarGuo** [comment]
cache 时的 buffer 是会这样的，设计如此，问题在与你视频的编排有问题，seek 一些 buffer 太久，导致上一个 buffer 一致没完成，下一个 buffer 肯定不会生效，我测试我这边的长视频，seek 一般几秒内的可以找到关键帧

**Comment by Equalzys** [comment]
> cache 时的 buffer 是会这样的，设计如此，问题在与你视频的编排有问题，seek 一些 buffer 太久，导致上一个 buffer 一致没完成，下一个 buffer 肯定不会生效，我测试我这边的长视频，seek 一般几秒内的可以找到关键帧

不是关键帧的问题，是processRequest时seek超过了已缓存20%时isUseCache还是为true导致继续下载，而不是直接使用网络数据

**Comment by CarGuo** [comment]
就是视频有问题，导致  request.rangeOffset 不对，我测试 https://res.exexm.com/cw_145225549855002 每次 seek 只会触发一次  processRequest



简单说，你的链接每次拖动，都会有下面如图这样的请求情况

![image](https://user-images.githubusercontent.com/10770362/168049712-e5095696-afbf-41cd-ba17-a4406bd2edac.png)

但是我测试的视频，只会有如下的情况

![image](https://user-images.githubusercontent.com/10770362/168049887-6a119728-cd3f-4a2e-99bb-32d6f633fc7d.png)


所以和 cache 实现没关系

**Comment by Equalzys** [comment]
> 就是视频有问题，导致 request.rangeOffset 不对，我测试 https://res.exexm.com/cw_145225549855002 每次 seek 只会触发一次 processRequest
> 
> 简单说，你的链接每次拖动，都会有下面如图这样的请求情况
> 
> ![image](https://user-images.githubusercontent.com/10770362/168049712-e5095696-afbf-41cd-ba17-a4406bd2edac.png)
> 
> 但是我测试的视频，只会有如下的情况
> 
> ![image](https://user-images.githubusercontent.com/10770362/168049887-6a119728-cd3f-4a2e-99bb-32d6f633fc7d.png)
> 
> 所以和 cache 实现没关系

那出现这种情况应该怎么解决？不能兼容吗？用户又不知道是他视频的问题...

**Comment by CarGuo** [comment]
是的，我这边是不会对类似这种情况去做兼容

**Comment by Equalzys** [comment]
> 是的，我这边是不会对类似这种情况去做兼容

解决了，就是AndroidVideoCache库的长度int long的强转问题，修改后可正常播放了；
1、HttpProxyCache.java::89行 -> newSourceNoCache.open((int) offset);改为newSourceNoCache.open(offset)；
2、 
HttpUrlSource.java::190行
```
if (offset > 0) {
                if (offset > Integer.MAX_VALUE) {
                    String ofs = String.valueOf(offset);
                    long ofr = offset;
                    if (ofs.contains(".")) {
                        ofr = Long.valueOf(ofs.substring(0, ofs.indexOf(".")));
                    }
                    connection.setRequestProperty("Range", "bytes=" + ofr + "-");
                } else {
                    connection.setRequestProperty("Range", "bytes=" + (int)offset + "-");
                }
            }
```

首先很感谢您做出的开源贡献，但是我没用您的播放器...，我只是来参考下你这边缓存是怎么解决的；
不知道您发现没，您对出现的问题开始出现排斥了，而不是积极的去解决问题；我敢肯定在开源初期，您一直保持着积极的态度，出现新的issues肯定是去排查解决的，而不是现在这种类似于甩锅的态度（可能我感觉错了哈）；

还是感谢您在百忙之中回答我的问题~~~ 谢谢~

**Comment by CarGuo** [comment]
可以可以，如果有精力，欢迎提交一个pr，因为现在项目很多，我并不会完全的去处理所有问题。

开源的意义在于交流，而不是我提供服务去解决问题，共建才是开源的目的和核心。
