### ISSUE TITLE
视频添加水印文字翻转问题

### ISSUE THREAD

**Issue by yueyueyue123** [CarGuo/GSYVideoPlayer#3571]
GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);
Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.mipmap.large_icon);
 GSYVideoGLViewCustomRender mGSYVideoGLViewCustomRender = new GSYVideoGLViewCustomRender();
 BitmapIconEffect mCustomBitmapIconEffect = new BitmapIconEffect(bitmap, dp2px(50), dp2px(50), 0.7f);
 mGSYVideoGLViewCustomRender.setBitmapEffect(mCustomBitmapIconEffect);
 videoPlayer.setCustomGLRenderer(mGSYVideoGLViewCustomRender);
  videoPlayer.setGLRenderMode(GSYVideoGLView.MODE_RENDER_SIZE);
 问题描述：
水印图片中的文字翻转

问题机型/系统：

例如 华为mate40 pro

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的DetailFilterActivity 重复出现此问题

**Comment by CarGuo** [comment]
demo 问题自己调整 GL 代码，这里只是示例
