### ISSUE TITLE
悬浮窗视频播放问题

### ISSUE THREAD

**Issue by jiqianwen** [CarGuo/GSYVideoPlayer#3573]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

请教，目前在做来电秀应用，使用悬浮窗播放视频的时候，因为是来电触发悬浮窗，部分手机出现这个错误 

AudioManager: requestPkg in Dispatcher is null

请问该怎么解决？我现在的处理办法是延迟500ms再开始播放是正常的，但是不知道在其他手机会不会有问题

**Comment by CarGuo** [comment]
AudioManager 相关，我猜测是和电话来的时候，系统对于 AudioManager 的分配和  request 上机制不同，具体我没有深究过···

**Comment by jiqianwen** [comment]
> AudioManager 相关，我猜测是和电话来的时候，系统对于 AudioManager 的分配和 request 上机制不同，具体我没有深究过···

那有没有临时的解决办法，视频是静音播放的，AudioManager其实可以无视，播放视频的时候要是有个api设置跳过AudioManager检测应该可行？

**Comment by CarGuo** [comment]
override `startPrepare` 和 `onVideoResume` 试试

**Comment by jiqianwen** [comment]
> override `startPrepare` 和 `onVideoResume` 试试

重写这两个方法之后应该做什么操作？ 我昨天跟着demo里悬浮窗重写过，还是一样的错误

**Comment by CarGuo** [comment]
重写这两个方法，去掉 AudioManager. request   的逻辑

**Comment by jiqianwen** [comment]
> 重写这两个方法，去掉 AudioManager. request 的逻辑

好的，我试下，感谢
