### ISSUE TITLE
播放不了http-flv格式

### ISSUE THREAD

**Issue by KunPengZheng** [CarGuo/GSYVideoPlayer#3577]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：播放不了http-flv格式

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米10

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.2.0-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.2.0-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.2.0-release-jitpack'

## Demo中的复现步骤

  xml布局：com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer

  fragment中的逻辑代码：

        //ijk内核，默认模式
        PlayerFactory.setPlayManager(IjkPlayerManager::class.java)
        //代理缓存模式，支持所有模式，不支持m3u8等，默认
        CacheFactory.setCacheManager(ProxyCacheManager::class.java)

        val source1 =
            "https://cn-gdfs-dx-live-02.bilivideo.com/live-bvc/518639/live_7734200_bs_1348183_1500.flv?cdn=cn-gotcha01&expires=1652933894&len=0&oi=1947570633&pt=web&qn=150&trid=10000cbcb13d42a0410ba7b19c98172eecb7&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=f57f7af1a956cd63d98dd026bbcefc26&ptype=0&src=57345&sl=3&source=one&sid=69322&sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44&order=1
        binding.player.setUp(source1, false, "测试视频"
        //增加title
        binding.player.getTitleTextView().setVisibility(View.INVISIBLE)
        //设置返回键
        binding.player.getBackButton().setVisibility(View.INVISIBLE)
        ///不需要屏幕旋转
        binding.player.setNeedOrientationUtils(false)
        binding.player.startPlayLogic();

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

2022-05-19 13:06:59.693 6585-7919 E/IJKMEDIA: https://cn-gdfs-dx-live-02.bilivideo.com/live-bvc/518639/live_7734200_bs_1348183_1500.flv?cdn=cn-gotcha01&expires=1652933894&len=0&oi=1947570633&pt=web&qn=150&trid=10000cbcb13d42a0410ba7b19c98172eecb7&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=f57f7af1a956cd63d98dd026bbcefc26&ptype=0&src=57345&sl=3&source=one&sid=69322&sk=2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44&order=1: Server returned 403 Forbidden (access denied)
2022-05-19 13:06:59.745 6585-6585  E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

xxxxxxx

```

**Comment by CarGuo** [comment]
403 Forbidden (access denied)


你先确定为什么不能访问，需要什么 header 之类的？

然后测试
            .setOverrideExtension("flv")
和
PlayerFactory.setPlayManager(Exo2PlayerManager.class);

**Comment by KunPengZheng** [comment]
问题：ViewPager2中的item为fragment，当在一个item中暂停后，滑动到另外的item，出现了有声音无画面的问题。以下是我在fragment中的代码：

 private fun initPlayer() {
        val source1 = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
        binding.player.setUp(source1, false, "")
        //增加title
        binding.player.getTitleTextView().setVisibility(View.INVISIBLE)
        //设置返回键
        binding.player.getBackButton().setVisibility(View.INVISIBLE)
        //是否需要显示流量提示,默认true
        binding.player.setNeedShowWifiTip(false)


       // 一些ui的现实和隐藏
        binding.player.xxx()

        //是否可以滑动调整
        binding.player.setIsTouchWiget(false)
        //不需要屏幕旋转
        binding.player.setNeedOrientationUtils(false)
        //是否需要覆盖拓展类型，目前只针对exoPlayer内核模式有效
        binding.player.setOverrideExtension("flv")


        binding.player.setSeekOnStart(0)
        binding.player.startPlayLogic()
    }

    override fun onPause() {
        super.onPause()
        binding.player.onVideoPause();
    }

    override fun onResume() {
        super.onResume()
        binding.player.onVideoResume();
    }

    override fun onDestroyView() {
        super.onDestroyView()
        //释放所有
        binding.player.setVideoAllCallBack(null);
        GSYVideoManager.releaseAllVideos();
    }

**Comment by KunPengZheng** [comment]
问题：ViewPager2中的item为fragment，不知道什么的处罚条件，出现了有声音无画面的问题。以下是我在fragment中的代码：

// 这是初始化配置
  //EXOPlayer内核，支持格式更多
        PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)
        //exo缓存模式，支持m3u8，只支持exo
        CacheFactory.setCacheManager(ExoPlayerCacheManager::class.java)

private fun initPlayer() {
val source1 = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
binding.player.setUp(source1, false, "")
//增加title
binding.player.getTitleTextView().setVisibility(View.INVISIBLE)
//设置返回键
binding.player.getBackButton().setVisibility(View.INVISIBLE)
//是否需要显示流量提示,默认true
binding.player.setNeedShowWifiTip(false)

   // 一些ui的现实和隐藏
    binding.player.xxx()

    //是否可以滑动调整
    binding.player.setIsTouchWiget(false)
    //不需要屏幕旋转
    binding.player.setNeedOrientationUtils(false)
    //是否需要覆盖拓展类型，目前只针对exoPlayer内核模式有效
    binding.player.setOverrideExtension("flv")


    binding.player.setSeekOnStart(0)
    binding.player.startPlayLogic()
}

override fun onPause() {
    super.onPause()
    binding.player.onVideoPause();
}

override fun onResume() {
    super.onResume()
    binding.player.onVideoResume();
}

override fun onDestroyView() {
    super.onDestroyView()
    //释放所有
    binding.player.setVideoAllCallBack(null);
}

**Comment by KunPengZheng** [comment]
有个别的视频播放不了，使用setVideoAllCallBack后在onPlayError发现没有回调，请问我需要通过什么方法能获取到播放失败的会调从而进行自己的ui操作

**Comment by CarGuo** [comment]
看demo和问题集锦
