### ISSUE TITLE
Exoplayer 内核切换音轨，没用

### ISSUE THREAD

**Issue by lyy90** [CarGuo/GSYVideoPlayer#3578]
## 问题描述：

Exoplayer 内核切换音轨，音轨没有切换

## 问题机型/系统：

例如 定制机顶盒

## GSY依赖版本

例如 最新的GSY版本，我导入是最新的源代码

## Demo中的复现步骤
Exoplayer  我设置了对音轨的获取，但是切换的时候没用

问题代码：(如果有)
```
初始化

  GSYVideoManager.instance().setPlayerInitSuccessListener { player, model ->
            ///播放器初始化成果回调
            if (player is IjkExo2MediaPlayer) {
                /// 自定义你的
                (player as IjkExo2MediaPlayer).trackSelector = DefaultTrackSelector()
                (player as IjkExo2MediaPlayer).loadControl = DefaultLoadControl()
            }
        }

动态切换音轨的地方


    /**
     * 切换音轨具体方法
     */
    fun switchTrackSpecificMethod(trackValue: Int?) {
        val player: IPlayerManager? = GSYVideoManager.instance().player
        if (player != null && player.mediaPlayer != null) {
            var trackSelector: DefaultTrackSelector = DefaultTrackSelector()
            val mappedTrackInfo: MappedTrackInfo? =
                GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).trackSelector.currentMappedTrackInfo
            if (mappedTrackInfo != null) {
                for (i in 0 until mappedTrackInfo.rendererCount) {
                    val rendererTrackGroups = mappedTrackInfo.getTrackGroups(i)
                    if (C.TRACK_TYPE_AUDIO == mappedTrackInfo.getRendererType(i)) { //判断是否是音轨
                        for (groupIndex in 0 until rendererTrackGroups.length) {
                            val trackGroup = rendererTrackGroups[groupIndex]
                            Log.d("checkAudio2", trackGroup.getFormat(0).toString())
                        }
                    }
                }

                val rendererTrackGroups = mappedTrackInfo.getTrackGroups(1).get(0).getFormat(0)
                val rendererTrackGroups1 = mappedTrackInfo.getTrackGroups(1).get(1).getFormat(0)
                Log.d("音轨1", "当前音轨：${rendererTrackGroups}")
                Log.d("音轨2", "当前音轨：${rendererTrackGroups1}")
                if (isSwitch) {
                    isSwitch = false
//                    GSYVideoManager.instance().setPlayerInitSuccessListener { player, _ ->
//                        ///播放器初始化成果回调
//                        if (player is IjkExo2MediaPlayer) {
//                            val parameters = trackSelector.parameters.buildUpon()
//                                .setSelectionOverride(1, mappedTrackInfo.getTrackGroups(1), SelectionOverride(0, 0)).build()
//                            trackSelector.parameters = parameters
//                            (player as IjkExo2MediaPlayer).trackSelector = trackSelector
//                            (player as IjkExo2MediaPlayer).loadControl = DefaultLoadControl()
//                        }
//                    }
                    val parameters = trackSelector.parameters.buildUpon()
                                .setSelectionOverride(1, mappedTrackInfo.getTrackGroups(1), SelectionOverride(0, 0)).build()
                            trackSelector.parameters = parameters
                    Log.d("aa",trackSelector.parameters.toString())
                    GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).trackSelector = trackSelector
                    GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).loadControl = DefaultLoadControl()


                } else {
                    isSwitch = true
                    val parameters = trackSelector.parameters.buildUpon()
                        .setSelectionOverride(1, mappedTrackInfo.getTrackGroups(1), SelectionOverride(1, 0)).build()
                    trackSelector.parameters = parameters
                    Log.d("aa",trackSelector.parameters.toString())
                    GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).trackSelector = trackSelector
                    GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).loadControl = DefaultLoadControl()
                }
            }
            if (selectedSongViewModel?.isPlayStatus() == true) {
                //暂停歌曲
                StarSocketProcessor.sendSwitchPauseMsg(true)
            }
            //原唱伴唱切换
            StarSocketProcessor.sendSwitchTrackMsg(trackValue == EnumCentralSwitch.TRACK_ORIGINAL.value)

        }
    }
## 问题log（如果有）
上面的音轨也能打印出来，就是插入的时候不对

**Comment by CarGuo** [comment]
不是很理解，哪里有问题？

**Comment by lyy90** [comment]
我用exo player 切换音轨，没起作用，是不是我的方法用错啊

**Comment by CarGuo** [comment]
是否有测试链接？

**Comment by lyy90** [comment]
https://aliyuncdnsaascloud.xjhktv.com/video/A%20Lin%2B%E5%80%AA%E5%AD%90%E5%86%88-%E4%B8%8D%E5%B1%91%E5%AE%8C%E7%BE%8E%5B%E5%9B%BD%5D%5B1080P%5D.mp4

**Comment by lyy90** [comment]
有的

**Comment by lyy90** [comment]
fun switchTrackSpecificMethod(trackValue: Int?) {
        val player: IPlayerManager? = GSYVideoManager.instance().player
        if (player != null && player.mediaPlayer != null) {
            var trackSelector: DefaultTrackSelector = DefaultTrackSelector()
            val mappedTrackInfo: MappedTrackInfo? =
                GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).trackSelector.currentMappedTrackInfo
            if (mappedTrackInfo != null) {
                for (i in 0 until mappedTrackInfo.rendererCount) {
                    val rendererTrackGroups = mappedTrackInfo.getTrackGroups(i)
                    if (C.TRACK_TYPE_AUDIO == mappedTrackInfo.getRendererType(i)) { //判断是否是音轨
                        for (groupIndex in 0 until rendererTrackGroups.length) {
                            val trackGroup = rendererTrackGroups[groupIndex]
                            Log.d("checkAudio2", trackGroup.getFormat(0).toString())
                        }
                    }
                }

                val rendererTrackGroups = mappedTrackInfo.getTrackGroups(1).get(0).getFormat(0)
                val rendererTrackGroups1 = mappedTrackInfo.getTrackGroups(1).get(1).getFormat(0)
                Log.d("音轨1", "当前音轨：${rendererTrackGroups}")
                Log.d("音轨2", "当前音轨：${rendererTrackGroups1}")
                if (isSwitch) {
                    isSwitch = false
                    val parameters = trackSelector.parameters.buildUpon()
                        .setSelectionOverride(1, mappedTrackInfo.getTrackGroups(1),
                            DefaultTrackSelector.SelectionOverride(0, 0)
                        ).build()
                    Log.e("aa","parameters1==="+parameters.getSelectionOverride(1,mappedTrackInfo.getTrackGroups(1)))
                    Log.e("aa","parameters1==="+mappedTrackInfo.getTrackGroups(1).get(0).getFormat(0).toString())
                    trackSelector.parameters = parameters
                    GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).defaultTrackSelector = trackSelector
                    GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).loadControl = DefaultLoadControl()


                } else {
                    isSwitch = true
                    val parameters = trackSelector.parameters.buildUpon()
                        .setSelectionOverride(1, mappedTrackInfo.getTrackGroups(1),
                            DefaultTrackSelector.SelectionOverride(1, 0)
                        ).build()
                    Log.e("aa","parameters2==="+parameters.getSelectionOverride(1,mappedTrackInfo.getTrackGroups(1)))
                    Log.e("aa","parameters2==="+mappedTrackInfo.getTrackGroups(1).get(1).getFormat(0).toString())
                    trackSelector.parameters = parameters
                    GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).defaultTrackSelector = trackSelector
                    GSYVideoManager.getIjkExo2MediaPlayer(player.mediaPlayer).loadControl = DefaultLoadControl()
                }
            }
            if (selectedSongViewModel?.isPlayStatus() == true) {
                //暂停歌曲
                StarSocketProcessor.sendSwitchPauseMsg(true)
            }
            //原唱伴唱切换
            StarSocketProcessor.sendSwitchTrackMsg(trackValue == EnumCentralSwitch.TRACK_ORIGINAL.value)

        }
    }

**Comment by lyy90** [comment]
这是我新改的还是不行

**Comment by CarGuo** [comment]
我这边测试 https://github.com/CarGuo/GSYVideoPlayer/blob/2166054dae27c9e3f636f868907f0c4248e7c025/app/src/main/java/com/example/gsyvideoplayer/DetailPlayer.java#L255 

用你的视频，两个音轨切换正常，一个有人声，一个只有伴奏

**Comment by lyy90** [comment]
好的，谢谢大佬，我还想问下默认的视频，exoplayer 加载视频要加载时间很长，怎么优化？有思路吗？

**Comment by CarGuo** [comment]
不会很长啊，我测试的挺快的，包括你那个链接
