### ISSUE TITLE
Rtsp直播流断开后，没有任何回调方法来判断是否播放失败？？

### ISSUE THREAD

**Issue by dovginka** [CarGuo/GSYVideoPlayer#358]
gsyvideopalyer：165
我自己搭了一个rtsp的服务器，当直播正在播放时，我把服务器给断电，StandardVideoAllCallBack中不执行任何方法，这是一个bug吧，如果我想捕捉这个错误，请问该怎么做呢？

**Comment by CarGuo** [comment]
服务器端电？如果出错会走OnError

**Comment by dovginka** [comment]
不会走的

**Comment by dovginka** [comment]
断电后不执行任何回调，视频页也不会发生改变，就如同视频卡死一样

**Comment by CarGuo** [comment]
这个我这边还没什么条件能重现···

**Comment by dovginka** [comment]
能加下qq吗，咱们私聊吧，我的qq:1049315335

**Comment by dovginka** [comment]
能扩大群吗，我想进群讨论一下

**Comment by TuringHuang** [comment]
我也想问这个问题，主播端断开推流后，播放器拉不到流，不走onError()，也不走onComplete()，只在onInfo(）里面返回一个701,但是网络不好的时候也会返回701，这样我怎么判断是网络差拉不到流还是主播下播了呢

**Comment by CarGuo** [comment]
701是缓冲开始！
