### ISSUE TITLE
m3u8拖动快退到起始的时候会跳回原来的位置，发现原来是拖动到起始位置后面position变成负数了

### ISSUE THREAD

**Issue by wangdadao2012** [CarGuo/GSYVideoPlayer#3580]
## 问题描述：

播放m3u8拖动快退到起始的时候会跳回原来的位置，发现原来是拖动到起始位置后面position变成负数了

## 出现问题的视频流

https://video.xintujing.cn/d0f2f304vodtranscq1251091601/e27f66955285890796832323682/v.f230.m3u8

## 问题机型/系统：

虚拟机 android 11 google APIs x86_64

## GSY依赖版本

v8.2.0

## Demo中的复现步骤

拖动的起始时间UI上显示了负数(如：-1:-20)，如果是m3u8则会跳回原来的位置，其他的则会从00:00开始播放，发现源码对于拖动到结束是做了判断的(position不会大于总时长)，希望作者能改一下这个小问题

**Comment by CarGuo** [comment]
这个，不是特别理解
复现步骤
现象
期望结果是？

**Comment by wangdadao2012** [comment]
@CarGuo 
![F33CC](https://user-images.githubusercontent.com/30767266/169754050-4c1e3a57-fc41-4540-bfac-869bec7e719b.gif)

复现步骤：播放m3u8视频，先触摸屏幕中间右划快进到11:59分钟，然后左滑快退，当退到起始时间(即00:00)的时候，继续左滑

现象：当退到起始时间(即00:00)的时候，继续左滑，时间成了负数(如：-1:-20)；松手后，屏幕中间进度条消失，，底部进度条会 
看到从00:00跳回了原来的位置，(不是m3u8的会正常跳到00:00的位置开始播放)

期望结果：左滑快退，当退到起始时间(即00:00)的时候，继续左滑，时间为00:00不要为负数，松手后从00:00开始播放

**Comment by CarGuo** [comment]
ui 问题已解决，但是 seekto 问题，需要特殊处理，

推荐你 override touchSurfaceUp 方法，然后把 cv 逻辑，把屏蔽代码打开

```
            try {
//                如果是 m3u8 可能会需要这个
//                if(mSeekTimePosition == 0) {
//                    mSeekTimePosition = 1;
//                }
                getGSYVideoManager().seekTo(mSeekTimePosition);
            } catch (Exception e) {
                e.printStackTrace();
            }
```

**Comment by wangdadao2012** [comment]
> ui 问题已解决，但是 seekto 问题，需要特殊处理，
> 
> 推荐你 override touchSurfaceUp 方法，然后把 cv 逻辑，把屏蔽代码打开
> 
> ```
>             try {
> //                如果是 m3u8 可能会需要这个
> //                if(mSeekTimePosition == 0) {
> //                    mSeekTimePosition = 1;
> //                }
>                 getGSYVideoManager().seekTo(mSeekTimePosition);
>             } catch (Exception e) {
>                 e.printStackTrace();
>             }
> ```

好的，谢谢
