### ISSUE TITLE
已经有缓存，但是每次播放的时候，还是要loading一下才能播放

### ISSUE THREAD

**Issue by jimdaxu** [CarGuo/GSYVideoPlayer#3583]
请问一下，为什么已经有缓存，但是每次播放的时候，还是要loading一下才能开始播放？不能一点击就无缝播放。

**Comment by CarGuo** [comment]
Prepare 到加载首帧，另外就有缓存还得缓冲…不同编码不同压缩率也都不一样 https://juejin.cn/post/7057132141875822622

**Comment by jimdaxu** [comment]
好的，谢谢回复。那为什么demo那边 DetailExoListPlayer 多视频自动切换到下一个视频的时候不用缓冲呢？

**Comment by CarGuo** [comment]
我记得他用的是 ConcatenatingMediaSource ，有预加载的逻辑

**Comment by chenkexu** [comment]
> 

如何播放到首帧呢？我这也遇到了这个问题，已经缓存成功了，还是会loading一下，再播放
