### ISSUE TITLE
v8.1.9以及之后的版本会导致edittext的inputType失效

### ISSUE THREAD

**Issue by simons216** [CarGuo/GSYVideoPlayer#3584]
edittext在xml配置的inputtype 为number||phone都失效了，经排查是gsyVideo导致的

**Comment by CarGuo** [comment]
不懂，怎么导致的？？？

**Comment by simons216** [comment]
我也很纳闷，为啥会导致edittext的inputtype失效。
Android Studio Chipmunk | 2021.2.1，compileSdk 32 targetSdk 32
创建一个新的项目测试，导入了这个版本后edittext 的inputtype就会失效

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.2.0-release-jitpack'------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] v8.1.9以及之后的版本会导致edittext的inputType失效 (Issue #3584)





 
不懂，怎么导致的？？？

**Comment by mafeigao** [comment]
确实会导致edittext的inputtype失效，我也出现这个问题了，楼主怎么解决的？我看问题已经close了
