### ISSUE TITLE
2.0版本无法引入

### ISSUE THREAD

**Issue by crazyzjw** [CarGuo/GSYVideoPlayer#3586]
implementation 'androidx.core:core-ktx:1.7.0'
 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.2.0-release-jitpack'

根据之前关闭的issues

`Execution failed for task ':app:checkJzDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).`

升级了compileSdkVersion 31
但是编译会报如下错误

<img width="567" alt="image" src="https://user-images.githubusercontent.com/12543049/170235131-bd92bfe2-d243-42f8-8461-d8eeed499897.png">

**Comment by CarGuo** [comment]
你这个是 kapt 的问题，和gsy没关系

**Comment by crazyzjw** [comment]
> 你这个是 kapt 的问题，和gsy没关系

但是room只支持kapt,那就没办法同时一起使用了?

**Comment by CarGuo** [comment]
Room要用kapt 也和gsy木关系😃
