### ISSUE TITLE
GSYVideoControlView.class line 856, 参数是不是设置错了？

### ISSUE THREAD

**Issue by asd7227600** [CarGuo/GSYVideoPlayer#359]
类GSYVideoControlView的第856行处：

```
public int getEnlargeImageRes() {
    return this.mShrinkImageRes == -1?drawable.video_enlarge:this.mEnlargeImageRes;
}
```

为EnlargeImage设置时判断的是ShrinkImage。。。这是可能是有误？

所以设置了Shrink以后，会报错，因为判断的是Shrink，去取EnlargeImage的时候是初始化值-1

**Comment by CarGuo** [comment]
哦哦，还真是，不过这里推荐这两个是成对设置的，所大和小应该都会有。哈哈哈，不过这里代码逻辑上确实有问题。感谢！

**Comment by CarGuo** [comment]
fix
