### ISSUE TITLE
 pad 横向从全屏返回小屏应该调用什么方法?

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#3590]
![image](https://user-images.githubusercontent.com/36412910/170968786-f8185b5b-c01d-412c-8914-9785809072f1.png)
如图

**Comment by CarGuo** [comment]
showSmallVideo ?

**Comment by darkrevier** [comment]
> showSmallVideo ?

就是正常的切换全屏，返回全屏，不是小窗口模式。不需要旋转屏幕。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2955#issuecomment-917915962

**Comment by darkrevier** [comment]
ok 3Q~
