### ISSUE TITLE
怎么禁止屏幕所有触摸点击事件

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#3591]
目前有个需求是付费视频试看结束后，不允许点击触摸响应(包括顶部控制栏，底部控制栏seekbar拖拽，播放按钮等。不允许触摸屏幕滑动音量，亮度）怎么有什么好的方法吗

**Comment by CarGuo** [comment]
setIsTouchWiget 和 setIsTouchWigetFull 吧

**Comment by darkrevier** [comment]
这样就会设置每一个控件禁止点击触摸。。有没有统一的视频渲染的ViewGroup设置可点击可触摸呢？

**Comment by CarGuo** [comment]
那你需要override对应的方法自己做自定义了
