### ISSUE TITLE
咨询一下连续剧缓存这种 应该怎么处理？

### ISSUE THREAD

**Issue by ZhuSky** [CarGuo/GSYVideoPlayer#3592]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

类似腾讯视频的连续剧缓存功能，缓存多集。
不知道exo支持这样的吗？（m3u8、mp4、等视频多种格式）
🙏🙏🙏

## 问题机型/系统：

小米10Pro

## GSY依赖版本

api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.2.0-release-jitpack'
api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.2.0-release-jitpack'
api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.2.0-release-jitpack'

**Comment by CarGuo** [comment]
参考demo的 exo/  目录下，用 ConcatenatingMediaSource ，并且参考 CacheFactory.setCacheManager(ExoPlayerCacheManager.class);  的 ExoPlayerCacheManager.class ，剩下你自己努力了

如果是非 m3u8 ，也可以用 CacheFactory.setCacheManager(ProxyCacheManager.class); ，参考demo 的 DetailDownloadPlayer 提前下载
