### ISSUE TITLE
v8.1.3版本 无法下载....

### ISSUE THREAD

**Issue by zhaobinsir** [CarGuo/GSYVideoPlayer#3594]
## 问题描述：
老版本v8.1.3 无法下载

## GSY依赖版本
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.3-jitpack'

**Comment by CarGuo** [comment]
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-proxy_cache:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-x86:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-x86_64:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-base:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv64:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv5:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:8.1.3-jitpack


8.1.3 用这个试试
