### ISSUE TITLE
有可以讲解一下屏幕旋转控制手动和跟随系统设置的文章吗

### ISSUE THREAD

**Issue by liy452083759** [CarGuo/GSYVideoPlayer#3596]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ 屏幕旋转禁止后,手动切换的屏幕旋转,禁止失效跟随系统禁止旋转失效问题该如何控制

## GSY依赖版本
'com.github.carguo.GSYvideoplayer:gsyVideoPlayer-java:v8.3.0-release-jitpack'

**Comment by CarGuo** [comment]
你看 `OrientationUtils` 和  `GSYBaseVideoPlayer` 的 `onConfigurationChanged` 相关源码就行了
