### ISSUE TITLE
 problem with void onPlayError

### ISSUE THREAD

**Issue by vipeweb** [CarGuo/GSYVideoPlayer#3597]
I made a function called init() where I pass as a parameter an ID where it locates the stream with id located on my server..

the problem occurs when onPlayError is triggered

it calls again my init(id); to be a form of quick retry..

so far everything is working normally

the problem happens that after several attempts

the inherited id becomes different normally from a previous attempt of a stream that has been played before

so the init which should be X

starts to be Y <--

Y= a stream that has been played before
that is no longer part of

init(id); because another integer parameter has already been passed

but somehow it passes to retrieve a value that has already been used before

I tried to solve it in different ways but it still persists.

can anybody help me?

 public synchronized  void init(int id) {
        videoPlayer.clearCurrentCache();
        videoPlayer.release();
        String url_Srv =  "http://myserverstream.com/";
        txt_Velocidade.setText("");
        connectados.setText("");
        Uri target = Uri.parse(url_Srv + "livestream/" + account.getUsername() + "/" + account.getPassword() + "/" + id + ".m3u8");
        PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
        videoPlayer.setUp(target.toString(), false, account.getUltimoCanal());
        videoPlayer.setNeedShowWifiTip(false);
        GSYVideoType.enableMediaCodec();
        boolean codec = GSYVideoType.isMediaCodec();
        GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
        String StatusCodec = "";
        if (codec) {
            StatusCodec = "MediaCodec enabled";
        } else {
            StatusCodec = "MediaCodec disabled";
        }
        LoadControl loadControl = new DefaultLoadControl.Builder()
                .setAllocator(new DefaultAllocator(true, 16))
                .setBufferDurationsMs(CanaisApp.VideoPlayerConfig.MIN_BUFFER_DURATION,
                        15000,
                        7000,
                        7000)
                .setTargetBufferBytes(-1)
                .setPrioritizeTimeOverSizeThresholds(true).createDefaultLoadControl();
        GSYVideoManager
                .instance()
                .setPlayerInitSuccessListener(new IPlayerInitSuccessListener() {
                    ///播放器初始化成果回调，可用于播放前的自定义设置
                    @Override
                    public void onPlayerInitSuccess(IMediaPlayer player, GSYModel model) {
                        if (player instanceof IjkExo2MediaPlayer) {
                            ((IjkExo2MediaPlayer) player).setTrackSelector(new DefaultTrackSelector());
                            ((IjkExo2MediaPlayer) player).setLoadControl(loadControl);
                        }
                    }
                });
        videoPlayer.setVideoAllCallBack(new GSYSampleCallBack(){
            @Override
            public synchronized  void onPlayError(String url, Object... objects) {
                super.onPlayError(url, objects);
                videoPlayer.release();
               init(id);

            }
        });
        ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                return null;
            }
            @Override
            public DataSource.Factory getHttpDataSourceFactory(String userAgent, @Nullable TransferListener listener, int connectTimeoutMillis, int readTimeoutMillis, Map<String, String> mapHeadData, boolean allowCrossProtocolRedirects) {
                //如果返回 null，就使用默认的
                GSYExoHttpDataSourceFactory factory = new GSYExoHttpDataSourceFactory(User, listener,
                        connectTimeoutMillis,
                        readTimeoutMillis, true);
                factory.setDefaultRequestProperties(mapHeadData);
                return factory;
            }
        });
        videoPlayer.startPlayLogic();
    }

**Comment by CarGuo** [comment]
I'm not sure what your problem is, but I guess you don't have  override `cloneParams` method
