### ISSUE TITLE
当视频暂停时，如何不让播放器继续进行缓存进度

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#3599]
现在的情况是，当我把视频暂停后,我的底部进度条还在进行缓存一部分进度。我想视频暂停，就直接停止视频缓存进度，应该如何处理啊

**Comment by CarGuo** [comment]
如果是 cache 的缓存，不支持，除了 shutdown 直接关闭，没有暂停支持
