### ISSUE TITLE
fork过来安装缺少这个方法

### ISSUE THREAD

**Issue by 201216323** [CarGuo/GSYVideoPlayer#36]
D:\Administrator\Github\GSYVideoPlayer\gsyVideoPlayer\src\main\java\com\shuyu\gsyvideoplayer\GSYVideoPlayer.java
Error:(1191, 63) 错误: 找不到符号
符号:   方法 getTcpSpeed()
位置: 类 IjkMediaPlayer

**Comment by CarGuo** [comment]
getTcpSpeed没有，你的ijk是哪个版本的？现在是 tv.danmaku.ijk.media:ijkplayer-java:0.7.6

**Comment by 201216323** [comment]
是我的版本问题，，下个你写的的源码，导了好长时间才导进来，
