### ISSUE TITLE
使用hilt后，点击全屏播放出现强转类型报错

### ISSUE THREAD

**Issue by goIntoAction** [CarGuo/GSYVideoPlayer#3600]
## 问题log

06-15 12:04:33.735   488   488 E AndroidRuntime: java.lang.ClassCastException: dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper cannot be cast to android.app.Activity
06-15 12:04:33.735   488   488 E AndroidRuntime: 	at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.startWindowFullscreen(GSYBaseVideoPlayer.java:634)
06-15 12:04:33.735   488   488 E AndroidRuntime: 	at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.startWindowFullscreen(StandardGSYVideoPlayer.java:364)
 

我们自己项目代码使用下面代码去获取activity
tailrec fun Context?.getActivity(): Activity? =
    this as? Activity ?: (this as? ContextWrapper)?.baseContext?.getActivity()

**Comment by CarGuo** [comment]
已经修复，下个版本发布～之前其实一直有这类处理，后来忘记普及了
