### ISSUE TITLE
一个播放器，需要按顺序播放多个视频的时候，cpu占用率过高

### ISSUE THREAD

**Issue by alen252** [CarGuo/GSYVideoPlayer#3601]
## 问题描述：

一个Activity里面有一个播放器，但是需要安装顺序播放多个视频，播放第一个视频CPU占用率正常，播放到第二个视频的时候CPU占用率增加，并且不会自动降下来。已经在播放第二个视频的时候调用了release方法，还是不行。初始化第二个视频的时候是调用setUp更换视频源。

## 出现问题的视频流

本地视频或者Demo里面的网络视频

## 问题机型/系统：
荣耀10

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:8.1.2'

问题代码：
Demo里面的LIST列表那个Activity可以复现

![image](https://user-images.githubusercontent.com/13713307/174514356-3e961b72-9dd7-4c9c-b003-b17bbcddcda7.png)

**Comment by CarGuo** [comment]
好像我这边测试正常·······如下图是我的波动图
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/10770362/174275699-418c6fd7-4fbb-49e5-8ebc-3d27ecc93456.png">

**Comment by alen252** [comment]
跟视频源也有关系 播放列表第二个视频 CPU增加挺多的

**Comment by CarGuo** [comment]
那肯定有关系啊，不同视频的封装，解码和压缩都不一样，肯定会有不同的占用，正常使用之后都会有明显的释放
