### ISSUE TITLE
在有视频播放的界面，拉起支付宝支付导致播放状态异常

### ISSUE THREAD

**Issue by jiqianwen** [CarGuo/GSYVideoPlayer#3602]
拉起支付宝支付首先触发onPause  然后又会触发onResume导致视频状态变为播放中，但是这时候其实还没跳转到支付宝，等真正跳转到支付宝的时候，再返回回来视频就卡在那了，因为回到应用重新触发onResume的时候应用状态是播放中

**Comment by CarGuo** [comment]
这个是我的问题？？？

**Comment by jiqianwen** [comment]
![微信图片_20220616110535](https://user-images.githubusercontent.com/26268908/173984015-6d2d1fde-16b2-4d4a-b499-a4f34c9589bb.png)

![QQ截图20220616112204](https://user-images.githubusercontent.com/26268908/173984196-32c22d95-107a-494f-9782-b947b191b98e.png)


您看一下这个生命周期的回调，最后跳转到支付宝之前确实是暂停状态，但是回到app内触发onReume的时候，状态却是播放中了

**Comment by jiqianwen** [comment]
您看一下这个生命周期的回调，最后跳转到支付宝之前确实是暂停状态，但是回到app内触发onReume的时候，状态却是播放中了，导致不会继续播放

![QQ截图20220616112204](https://user-images.githubusercontent.com/26268908/173984313-a8930514-6f57-43e7-ba88-4d1e2803529f.png)

![QQ截图20220616111941](https://user-images.githubusercontent.com/26268908/173984324-9a710b42-ca58-4826-82d3-1ca5944f6fa8.png)

**Comment by CarGuo** [comment]
不知道你那边什么情况，我这边测试正常，在正常 pause 和 resume 的情况下

**Comment by jiqianwen** [comment]
如果是打断点调试就不会有问题

**Comment by CarGuo** [comment]
我这边测试，正常前后台切换没问题

**Comment by pinguoooo** [comment]
本人之前有遇到过在`recyclerView`使用`notifyDataSetChanged()`会出现在播放但是没画面（后面使用局部UI刷新解决），还有两个视频播放器进行数据克隆（自己重写的方法），Video布局快速的进行 pause 和 resume 操作之后经常会出现，但是打断点就没事（最后使用延迟播放解决）。
根据现有的状况分析，你要不试试下面的方法：
1. 可以试试让video进行resume或者startPlay时给个`postDelay()`，延迟100多够了;
2. 在调用支付方法后，给出个标志isPaying（或者看alipay 有没有支付中这个状态，有的话更准确），表示当前在进行支付过程中，然后在`onResume()`中进行视频恢复时排除isPaying情况，转而在支付成功或者支付失败后再进行video的resume操作，isPaying复位；
3. 是在没办法，在调用支付之前储存当前videoPlayer播放进度，或者整个videoPlayer，onResume中进行克隆参数(相当于数据恢复)，需要重写videPlayer的`cloneParams()`方法，外部使用可见性置为public或者内部使用仍使用protected，不然无法使用。

我估计第1和第3这两种方法不好实现，因为总是会受到支付宝多次弹窗跳转的影响，建议尝试的顺序就是1-2-3了，不然太花时间。

**Comment by jiqianwen** [comment]
> 本人之前有遇到过在`recyclerView`使用`notifyDataSetChanged()`会出现在播放但是没画面（后面使用局部UI刷新解决），还有两个视频播放器进行数据克隆（自己重写的方法），Video布局快速的进行 pause 和 resume 操作之后经常会出现，但是打断点就没事（最后使用延迟播放解决）。 根据现有的状况分析，你要不试试下面的方法：
> 
> 1. 可以试试让video进行resume或者startPlay时给个`postDelay()`，延迟100多够了;
> 2. 在调用支付方法后，给出个标志isPaying（或者看alipay 有没有支付中这个状态，有的话更准确），表示当前在进行支付过程中，然后在`onResume()`中进行视频恢复时排除isPaying情况，转而在支付成功或者支付失败后再进行video的resume操作，isPaying复位；
> 3. 是在没办法，在调用支付之前储存当前videoPlayer播放进度，或者整个videoPlayer，onResume中进行克隆参数(相当于数据恢复)，需要重写videPlayer的`cloneParams()`方法，外部使用可见性置为public或者内部使用仍使用protected，不然无法使用。
> 
> 我估计第1和第3这两种方法不好实现，因为总是会受到支付宝多次弹窗跳转的影响，建议尝试的顺序就是1-2-3了，不然太花时间。

感谢回复，我目前就是用的你说的第二种方法来控制了，加一个临时变量来跳过支付中状态

**Comment by pinguoooo** [comment]
不客气，一起进步

**Comment by Hynsn** [comment]
各位大佬，问题还没解决吧？issue先别关呀

**Comment by JasonDev324** [comment]
上述问题 都无效啊，最基本的场景，RecyclerView里放播放器，点击启动一个新页面，返回，播放器恢复不了

**Comment by YanYanLun** [comment]
目前我也遇到了，onVideoResume恢复播放执行后又会马上执行onVideoPause，没找到具体为什么会执行onVideoPause的原因
