### ISSUE TITLE
VP8编码视频,用IJK播放无声音有画面,已使用gsyVideoPlayer-ex_so:v8.3.0(已附上资源)

### ISSUE THREAD

**Issue by yangjieK** [CarGuo/GSYVideoPlayer#3604]
## 问题描述：
VP8编码视频,用IJK无法播放声音,画面有.

## 出现问题的视频流
[链接：https://pan.baidu.com/s/13CQith6dCaOPQTW4bt-2JA](https://pan.baidu.com/s/13CQith6dCaOPQTW4bt-2JA)
提取码：yapn

## GSY依赖版本

api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.0-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.0-release-jitpack'

**Comment by CarGuo** [comment]
看音频编码你就知道为什么
