### ISSUE TITLE
请教一下，详情页关闭时切换到悬浮窗播放如何实现无缝切换

### ISSUE THREAD

**Issue by RDSunhy** [CarGuo/GSYVideoPlayer#3605]
悬浮窗效果已经实现了，但是每次切到悬浮窗的时候都会重新加载一会，可以实现无缝切换吗？求大佬指点下思路。

**Comment by CarGuo** [comment]
参考demo的PlayPickActivity

**Comment by RDSunhy** [comment]
我指的是 切换到全局悬浮窗 不是那种列表；全局悬浮窗参考demo 写了一个 FloatVideoPlayer，用全局悬浮窗承载的。

**Comment by CarGuo** [comment]
一样的， PlayPickActivity 里切换清晰度一样的逻辑
