### ISSUE TITLE
请问下，使用改框架可以播放wss://协议的视频流？

### ISSUE THREAD

**Issue by bingoloves** [CarGuo/GSYVideoPlayer#3606]
目前测试小程序和web端可以直接播放wss://xx的地址。 如果可以，能否提供下使用示例，谢谢

**Comment by CarGuo** [comment]
用 websocket 播放视频概念完全不一样，你是通过 websocket 传数据然后外部做解码，目前框架支持到 StreamDataSourceProvider 的状态，你可以自己看看
