### ISSUE TITLE
如何缓存完整个视频再播放

### ISSUE THREAD

**Issue by LinMaris** [CarGuo/GSYVideoPlayer#3607]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
我看过很多issue, 

现在已知的是我们上传到服务器的视频, 最好是下载完再播放, 否则边播边缓存会大概率播放失败

目前用的是 Exo2PlayerManager 和 ExoPlayerCacheManager , 如果采用边播边缓存, 还是会存在下载失败的情况

我这边推测是视频源的问题, 目前想强制让视频缓存完再播放, 但是AndroidVideoCache和SimpleCache好像不能直接这样操作.

## 问题机型/系统：

真机 小米9s Android11.0

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

这是EXO的一个bug, 目前没找到解决办法
```

[surfacetexture-0-5116-5] setmaxdequeuedbuffercount: requested buffer count 2 is less than minimum 3

```

**Comment by CarGuo** [comment]
你不用 ExoPlayerCacheManager ，用默认的 proxy cache 不行？

**Comment by LinMaris** [comment]
> 你不用 ExoPlayerCacheManager ，用默认的 proxy cache 不行？

这是数据源
https://iot.kdcx-nplus.com/water-web/file//localFile/water-web/2022-06-17/system1655456401736.mp4

如果用默认的 proxy cache, 会经常出现播放失败的提示.

**Comment by CarGuo** [comment]
没复现，因为 proxy cache 就是简单的 http socket 拉流

**Comment by Marx-Hong** [comment]
我也遇到了，用proxy cache缓存的视频就前十秒钟能播，后面全是卡死的
