### ISSUE TITLE
在副屏Presentation里，进入播放状态，ui不会自己隐藏

### ISSUE THREAD

**Issue by GodFan4** [CarGuo/GSYVideoPlayer#3608]
## 问题描述：

在副屏Presentation里，进入播放状态，ui不会自己隐藏

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.0-release-jitpack

**Comment by CarGuo** [comment]
所以为什么不隐藏呢？

**Comment by GodFan4** [comment]
> 所以为什么不隐藏呢？

在Activity里使用的时候，进入播放状态后，播放按钮和进度条会自动隐藏，点击后再显示出来。
在Presentation里就不行，进入播放状态后，播放按钮和进度条一直在显示
是要重写changeUiToPlayingShow方法吗

**Comment by GodFan4** [comment]
> 主要是我这边没有副屏幕设备，所我才问你，为什么会不隐藏？

Runnable dismissControlTask = new Runnable() {
        @Override
        public void run() {
            if (mCurrentState != CURRENT_STATE_NORMAL
                    && mCurrentState != CURRENT_STATE_ERROR
                    && mCurrentState != CURRENT_STATE_AUTO_COMPLETE) {
                if (**getActivityContext()** != null) {
                    Log.d(TAG,"getActivityContext() != null");
                    hideAllWidget();
                    setViewShowState(mLockScreen, GONE);
                    if (mHideKey && mIfCurrentIsFullscreen && mShowVKey) {
                        hideNavKey(mContext);
                    }
                }
                if (mPostDismiss) {
                    postDelayed(this, mDismissControlTime);
                }
            }
        }
    };

getActivityContext()一直是null，所以就没有隐藏

**Comment by CarGuo** [comment]
说起来，新版对 getActivityContext 做了调整，你可以试试   v8.3.1-release-jitpack

**Comment by GodFan4** [comment]
> 说起来，新版对 getActivityContext 做了调整，你可以试试 v8.3.1-release-jitpack

public static Activity getActivityContext(Context context) {
        if (context == null)
            return null;
        else if (context instanceof Activity)
            return (Activity) context;
        else if (context instanceof TintContextWrapper)
            return scanForActivity(((TintContextWrapper) context).getBaseContext());
        else if (context instanceof ContextWrapper)
            return scanForActivity(((ContextWrapper) context).getBaseContext());

        return null;
    }

和v8.3.0-release-jitpack一样呀

**Comment by CarGuo** [comment]
所以你的 context 究竟是什么
？

**Comment by GodFan4** [comment]
> 所以你的 context 究竟是什么 ？

Presentation，是个Dialog

**Comment by CarGuo** [comment]
明白了，一直没反应过来，已经提交，你可以用 demo 测试下，如果可以我再发个小小版本

**Comment by GodFan4** [comment]
> 明白了，一直没反应过来，已经提交，你可以用 demo 测试下，如果可以我再发个小小版本

可以了，感谢

**Comment by CarGuo** [comment]
v8.3.2-release-jitpack
