### ISSUE TITLE
我现在无法在onPrepared获取AudioSessionId,请问该怎么解决?

### ISSUE THREAD

**Issue by qm921** [CarGuo/GSYVideoPlayer#3609]
## 问题描述：

我现在想做一个随声音变化的动画，这个时候需要用到AudioSessionId,我现在使用demo中的无控制播放界面来播放音乐，继承的是StandardGSYVideoPlayer，我现在无法在onPrepared获取AudioSessionId,请问该怎么解决?

## 问题机型/系统：

 真机 红米k30尊享版

## GSY依赖版本

    //视频播放器
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.8-release-jitpack'
    //是否需要ExoPlayer模式
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.1.8-release-jitpack'
    //更多 ijk 的编码支持
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.8-release-jitpack'

## Demo中的复现步骤

我现在使用demo中的无控制播放界面来播放音乐，继承的是StandardGSYVideoPlayer，我现在无法在onPrepared获取AudioSessionId

问题代码：(如果有)
```
            LogUtil.d(
                "获取session2",
                "${
                    GSYVideoManager.instance().getCurPlayerManager().getMediaPlayer()
                        .getAudioSessionId()
                }"
            )
            LogUtil.d("获取session21", "${gsyVideoManager.player.mediaPlayer.audioSessionId}")
```

获取的全是0

```

**Comment by CarGuo** [comment]
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/10770362/174928025-da5e08f4-7b1c-40cd-a0b0-a134f5bea657.png">

应该 exo 的默认有问题，已经修改，下版本发布

**Comment by qm921** [comment]
> <img alt="image" width="1316" src="https://user-images.githubusercontent.com/10770362/174928025-da5e08f4-7b1c-40cd-a0b0-a134f5bea657.png">
> 
> 应该 exo 的默认有问题，已经修改，下版本发布
好的

**Comment by CarGuo** [comment]
已经发布 v8.3.1-release-jitpack

**Comment by qm921** [comment]
> 已经发布 v8.3.1-release-jitpack

👌🏻
