### ISSUE TITLE
v1.6.8 bug:MP4格式，部分机型有时候播放过程中会自动暂停，然后再点播放就重新开始

### ISSUE THREAD

**Issue by 18710891669** [CarGuo/GSYVideoPlayer#361]

**Comment by CarGuo** [comment]
这种情况有点像是网络切换或者中断了

**Comment by wlxfxy** [comment]
我也出现了这种情况

**Comment by CarGuo** [comment]
最新版本？

**Comment by wlxfxy** [comment]
也是1.6.8版本，mp4视频播放几分钟之后就会暂停一下

**Comment by MIkeeJY** [comment]
E/ProxyCache error: Error opening connection for http://v11-dy.ixigua.com/2904ea69c3be86ca1dc35581662ecf25/5aa258cc/video/m/220d6267b3771764167a894321e779ef7921154c04300006dd534d3556d/ with offset 993004. Version: 4.1.0
E/HttpProxyCacheServer error: Error processing request. Version: 4.1.0
E/IJKMEDIA: Stream ends prematurely at 991232, should be 18446744073709551615
E/IJKMEDIA: Option ijkiomanager not found.
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: stream 0, offset 0x33db: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 0, offset 0x33db: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: stream 1, offset 0x3268: partial file
E/IJKMEDIA: av_read_frame error: unknown
