### ISSUE TITLE
悬浮播放无缝切换

### ISSUE THREAD

**Issue by bingdu0** [CarGuo/GSYVideoPlayer#3610]
## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤
我用demo中的SmartPickVideo ，在右上角加了一个悬浮窗的按钮，参考了FloatingVideo实现了悬浮播放，然后SmartPickVideo和FloatingVideo这两个 怎么才能实现无缝切换呢？

**Comment by CarGuo** [comment]
切换的逻辑在于不释放 Manager ，切换 Surface ，如果是同一个视频的话，参考  demo 的 switchplay 目录
SmartPickVideo  是用于同一个控件 切换不同视频
