### ISSUE TITLE
关于播放器内核的问题

### ISSUE THREAD

**Issue by Yangqingchun** [CarGuo/GSYVideoPlayer#3612]
## 问题描述：

⚠️ 大佬，我之前遇到过那种视频播放很卡的情况，把播放器内核换成EXO后，确实可以了，但我有一个疑问就是，我查资料发现EXO应该是没有默认内核IJK强大的，它只支持硬解码，而IJK可以软硬编解码，但感觉在Issues里边的问题中，你建议大家在遇到视频播放问题的时候，就切换成EXO内核试一下，可以简单说一下这其中的奥妙吗大佬..

## 出现问题的视频流

无

## 问题机型/系统：

Android 12

## GSY依赖版本

忘记了

**Comment by CarGuo** [comment]
因为 EXO 是系统 MediaCodec 支持，所以播放会更稳定，系统级支持，就是这么简单
