### ISSUE TITLE
我现在想做一个随声音变化的动画，我现在使用demo中的无控制播放界面来播放音乐，继承的是StandardGSYVideoPlayer，我现在无法在获取播放状态,请问该怎么解决?

### ISSUE THREAD

**Issue by qm921** [CarGuo/GSYVideoPlayer#3614]
## 问题描述：

我现在想做一个随声音变化的动画，我现在使用demo中的无控制播放界面来播放音乐，继承的是StandardGSYVideoPlayer，我现在无法在获取播放状态,请问该怎么解决?

## 问题机型/系统：

例如 真机 红米K30尊享版 Android11

## GSY依赖版本

    //视频播放器
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.2-release-jitpack'
    //是否需要ExoPlayer模式
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.2-release-jitpack'
    //更多 ijk 的编码支持
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.2-release-jitpack'

## Demo中的复现步骤

我通过控制网速，在网速不好的时候我试着拿到播放器是不是处于等待（缓冲的状态），我拿不到播放器的状态

问题代码：(如果有)
override fun getCurrentState(): Int {

        if (mCurrentState == CURRENT_STATE_PREPAREING || mCurrentState == CURRENT_STATE_PLAYING_BUFFERING_START) {
            setViewShowState(loading_net_speed_tv, VISIBLE)

            loading_net_speed_tv.text = netSpeedText
            LogUtil.d("加载中走者里了","${1111111111111}")
        } else {
            setViewShowState(loading_net_speed_tv, INVISIBLE)

            audio_lav.playAnimation()
            LogUtil.d("加载中走者里了","${222222222222}")
        }
        return mCurrentState
    }

我重写方法也试过了也不行
 override fun getGSYStateUiListener(): GSYStateUiListener {
        return super.getGSYStateUiListener()
    }

**Comment by CarGuo** [comment]
不懂你的意思

**Comment by qm921** [comment]
> 我现在使用demo中的无控制播放界面来播放音乐

我现在使用demo中的无控制播放界面来播放视频或者音乐，怎么样才能获取到播放器的缓冲的状态

**Comment by CarGuo** [comment]
mCurrentState == CURRENT_STATE_PLAYING_BUFFERING_START

**Comment by qm921** [comment]
> mCurrentState == CURRENT_STATE_PLAYING_BUFFERING_START

我再这两个方法里面写都没有走日志
> ```
>     if (mCurrentState == CURRENT_STATE_PREPAREING || mCurrentState == CURRENT_STATE_PLAYING_BUFFERING_START) {
>         setViewShowState(loading_net_speed_tv, VISIBLE)
> 
>         loading_net_speed_tv.text = netSpeedText
>         LogUtil.d("加载中走者里了","${1111111111111}")
>     } else {
>         setViewShowState(loading_net_speed_tv, INVISIBLE)
> 
>         audio_lav.playAnimation()
>         LogUtil.d("加载中走者里了","${222222222222}")
>     }
>     return mCurrentState
> }
> ```
> 
> 
>     
>   
> 
> 我重写方法也试过了也不行
> override fun getGSYStateUiListener(): GSYStateUiListener {
> return super.getGSYStateUiListener()
> }

**Comment by CarGuo** [comment]
我测试正常，不知道你什么意思

**Comment by qm921** [comment]
> 我测试正常，不知道你什么意思

可以贴一下你的代码么？[捂脸][捂脸][捂脸][捂脸]

**Comment by CarGuo** [comment]
你 override setStateAndUi
