### ISSUE TITLE
视频暂停播放，恢复播放进度丢失

### ISSUE THREAD

**Issue by SunSeekerX** [CarGuo/GSYVideoPlayer#3617]
## 问题描述：

视频暂停播放，恢复播放进度丢失，调用得是 onVideoPause 和 onVideoResume 

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.1-release-jitpack'

**Comment by CarGuo** [comment]
请提供出现问题的测试链接
或者你测试
onVideoResume(false)
