### ISSUE TITLE
Amdroid 12 发生多次闪退

### ISSUE THREAD

**Issue by EthanChenccc** [CarGuo/GSYVideoPlayer#3618]
## 问题描述：

⚠️Android 12发生多次闪退

## 问题机型/系统：

真机 荣耀60 Android12  三星 Galaxy S10(SM-G9730)  Android12  

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0'`

## Demo中的复现步骤

app进入视频播放页直接闪退。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（bugly上报的就这2行）

#00 pc 00280f88 /data/app/~~RL0TdylOdAXd_l0Hie6kYA==/com.dodolive.app-NbYOe6wH4MgtPgbKhGkeng==/base.apk (ff_hevc_sao_band_filter_neon_8+99)

#01 pc 00276e59 /data/app/~~RL0TdylOdAXd_l0Hie6kYA==/com.dodolive.app-NbYOe6wH4MgtPgbKhGkeng==/base.apk (ff_hevc_sao_band_filter_neon_8_wrapper+76)

xxxxxxx

```

**Comment by CarGuo** [comment]
没有有用信息

**Comment by EthanChenccc** [comment]
大佬 bugly就只看到这个错误呀 

pc 00280f88 /data/app/~~UfIGXHbpq_QJ8X_rwqdiWg==/com.dodolive.app-P-8tQSrGB7qX0_CBZS0NTg==/base.apk (ff_hevc_sao_band_filter_neon_8+99)

pc 00276e59 /data/app/~~UfIGXHbpq_QJ8X_rwqdiWg==/com.dodolive.app-P-8tQSrGB7qX0_CBZS0NTg==/base.apk (ff_hevc_sao_band_filter_neon_8_wrapper+76)

**Comment by EthanChenccc** [comment]
cpu架构是arm64-v8a

**Comment by CarGuo** [comment]
所以说没有有用信息

**Comment by sangsais** [comment]
你是不是打包的32位apk安装包，可以打个32根64的包，分别在你那2台手机上运行看看。

**Comment by EthanChenccc** [comment]
> 



> 你是不是打包的32位apk安装包，可以打个32根64的包，分别在你那2台手机上运行看看。

嗯 目前项目只配置了v7   abiFilters 'armeabi-v7a'  估计是这个问题，那些崩溃的都是用户的手机暂时没法测试
