### ISSUE TITLE
播放器流量播放时，dialog提示窗口在，屏幕中显示不完整

### ISSUE THREAD

**Issue by Thank4** [CarGuo/GSYVideoPlayer#3619]
## 问题描述：播放器流量播放时，dialog提示窗口在，屏幕中显示不完整。

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

AS中模拟器  android 12  PIXEL 3A XL ,屏幕尺寸1080 X 2160

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.2-release-jitpack'

    //是否需要ExoPlayer模式
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.2-release-jitpack'

    //是否需要AliPlayer模式
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-aliplay:v8.3.2-release-jitpack'

    //更多ijk的编码支持
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.2-release-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
页面布局
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="@color/white"
    xmlns:tools="http://schemas.android.com/tools"
    >
    <com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
        android:id="@+id/detail_player"
        android:layout_width="match_parent"
        android:layout_height="200dp"/>
</LinearLayout>
```

##图片

![1656378427068](https://user-images.githubusercontent.com/15935984/176065462-5d299c2c-0ff8-4ee3-8430-84bdf8ccf58d.jpg)
![QQ20220628-091022](https://user-images.githubusercontent.com/15935984/176065479-a0d95002-e4e8-4683-a6c8-909181b0c2f8.png)
![QQ20220628-091041](https://user-images.githubusercontent.com/15935984/176065625-6855fac3-e24a-49dc-9918-a681855cd78b.png)

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
请在真机上复习问题
