### ISSUE TITLE
RTSP protocol not found

### ISSUE THREAD

**Issue by oujunjun** [CarGuo/GSYVideoPlayer#362]
### Hi, when I replace the demo video address with my own camera's RTSP address, it does not play and logcat says:

08-09 16:40:01.692 14180-14865/com.example.jun.s I/IJKMEDIA: ===== versions =====
08-09 16:40:01.692 14180-14865/com.example.jun.s I/IJKMEDIA: ijkplayer    : k0.8.1-1-g44915cd
08-09 16:40:01.692 14180-15608/com.example.jun.s I/IJKMEDIA: SDL_RunThread: [15608] ff_msg_loop
08-09 16:40:01.692 14180-14865/com.example.jun.s I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170615--001
08-09 16:40:01.692 14180-14865/com.example.jun.s I/IJKMEDIA: libavutil    : 55.58.100
08-09 16:40:01.693 14180-14865/com.example.jun.s I/IJKMEDIA: libavcodec   : 57.89.100
08-09 16:40:01.693 14180-14865/com.example.jun.s I/IJKMEDIA: libavformat  : 57.71.100
08-09 16:40:01.693 14180-14865/com.example.jun.s I/IJKMEDIA: libswscale   : 4.6.100
08-09 16:40:01.693 14180-14865/com.example.jun.s I/IJKMEDIA: libswresample: 2.7.100
08-09 16:40:01.693 14180-14865/com.example.jun.s I/IJKMEDIA: ===== options =====
08-09 16:40:01.693 14180-14865/com.example.jun.s I/IJKMEDIA: player-opts : loop                         = 1
08-09 16:40:01.693 14180-14865/com.example.jun.s I/IJKMEDIA: format-opts : ijkapplication               = 368626017216
08-09 16:40:01.693 14180-14865/com.example.jun.s I/IJKMEDIA: format-opts : ijkiomanager                 = 368628310272
08-09 16:40:01.693 14180-14865/com.example.jun.s I/IJKMEDIA: ===================
08-09 16:40:01.706 14180-15611/com.example.jun.s I/IJKMEDIA: SDL_RunThread: [15611] ff_vout
08-09 16:40:01.707 14180-14865/com.example.jun.s W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
08-09 16:40:01.709 14180-15612/com.example.jun.s I/IJKMEDIA: SDL_RunThread: [15612] ff_read
08-09 16:40:01.710 14180-15612/com.example.jun.s W/IJKMEDIA: remove 'timeout' option for rtmp.
08-09 16:40:01.711 14180-15612/com.example.jun.s E/IJKMEDIA: rtsp://admin:admin@192.168.1.10:554/cam/realmonitor?channel=1&subtype=1: Protocol not found
08-09 16:40:01.711 14180-15612/com.example.jun.s I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15612]
08-09 16:40:01.711 14180-14865/com.example.jun.s E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
08-09 16:40:01.719 14180-15608/com.example.jun.s I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15608]
08-09 16:40:01.727 14180-15611/com.example.jun.s I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15611]
                                                             
                                                             
                                                             [ 08-09 16:40:01.854  2883: 2883 E/         ]
                                                             process stopped due to unexpected signal 13
08-09 16:40:03.655 14180-14180/com.example.jun.s I/AudioManager: abandonAudioFocus
08-09 16:40:03.659 14180-14180/com.example.jun.s I/AudioManager: abandonAudioFocus
08-09 16:40:03.662 14180-14180/com.example.jun.s I/AudioManager: requestAudioFocus() status : 1
08-09 16:40:03.662 14180-14180/com.example.jun.s I/AudioManager: requestAudioFocus() apk    : com.example.jun.s
08-09 16:40:03.664 14180-14865/com.example.jun.s I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170615--001
08-09 16:40:03.664 14180-14865/com.example.jun.s I/IJKMEDIA: ijk_version_info: k0.8.1-1-g44915cd
08-09 16:40:03.665 14180-14865/com.example.jun.s W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
08-09 16:40:03.665 14180-14865/com.example.jun.s W/IJKMEDIA: remove 'timeout' option for rtmp.
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: ===== versions =====
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: ijkplayer    : k0.8.1-1-g44915cd
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170615--001
08-09 16:40:03.665 14180-15651/com.example.jun.s I/IJKMEDIA: SDL_RunThread: [15651] ff_msg_loop
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: libavutil    : 55.58.100
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: libavcodec   : 57.89.100
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: libavformat  : 57.71.100
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: libswscale   : 4.6.100
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: libswresample: 2.7.100
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: ===== options =====
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: player-opts : loop                         = 1
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: format-opts : ijkapplication               = 368626787936
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: format-opts : ijkiomanager                 = 368626017168
08-09 16:40:03.665 14180-14865/com.example.jun.s I/IJKMEDIA: ===================
08-09 16:40:03.668 14180-15652/com.example.jun.s I/IJKMEDIA: SDL_RunThread: [15652] ff_vout
08-09 16:40:03.668 14180-15653/com.example.jun.s I/IJKMEDIA: SDL_RunThread: [15653] ff_read
08-09 16:40:03.668 14180-15653/com.example.jun.s W/IJKMEDIA: remove 'timeout' option for rtmp.
08-09 16:40:03.668 14180-15653/com.example.jun.s E/IJKMEDIA: rtsp://admin:admin@192.168.1.10:554/cam/realmonitor?channel=1&subtype=1: Protocol not found
08-09 16:40:03.668 14180-15653/com.example.jun.s I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15653]
08-09 16:40:03.669 14180-14865/com.example.jun.s E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
08-09 16:40:03.683 14180-14865/com.example.jun.s W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
08-09 16:40:03.687 14180-15651/com.example.jun.s I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15651]
08-09 16:40:03.688 14180-15652/com.example.jun.s I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15652]

### Whereas VLC player can play the rtsp video, why it says protocal not found, your project says support RTSP protocol.

Thanks for your time.

xiexie 猫大人

**Comment by CarGuo** [comment]
2.0.4可以播放rtsp，然后问题是？

**Comment by oujunjun** [comment]
电脑没装输入法，手机打字不太喜欢，麻烦你了
我刚下载2.0.4编译运行还是同样的问题，logcat说，protocol not found，日志里面有，其他没发现什么有价值的log。
但我用手机VLC player可以播放自己的摄像头视频的地址。

谢谢!

**Comment by CarGuo** [comment]
你用的是exso吗？只有ex的so才支持rtsp喔

**Comment by oujunjun** [comment]
我没修改你的代码，下载下来直接运行就找不到protocol，怎么设置exso呢?另外我还不知道如何查看旧的ISSUE，这样就不用你重复回答同样的问题了。

**Comment by oujunjun** [comment]
我是直接下载整个2.0.4项目运行的，我再REBUILD和清除CACHE看看

**Comment by oujunjun** [comment]
invalidate cache和rebuild还是同样问题

**Comment by CarGuo** [comment]
demo里默认使用的是普通so，你可以看看依赖，换成ex so的依赖。

**Comment by oujunjun** [comment]
好了，多谢猫大人!

**Comment by jj8401** [comment]
@oujunjun 你好，我想问下你是修改的什么文件可以播放 rtsp 流

**Comment by asyncHyj** [comment]
@jj8401 同问，你搞定了吗？
