### ISSUE TITLE
不能支持avi格式吗？

### ISSUE THREAD

**Issue by yyy000112** [CarGuo/GSYVideoPlayer#3620]
## 问题描述：

⚠️AVI格式无法播放

### [❗❗❗⚠️⚠️⚠️这个很重要！！！！没有问题流的问题无法处理复现⚠️⚠️⚠️❗❗❗]
https://zhongkeyishu.oss-cn-hangzhou.aliyuncs.com/zkys/62baa398e4b0b6ec317c0512.avi
E/IJKMEDIA: http://127.0.0.1:42505/https%3A%2F%2Fzhongkeyishu.oss-cn-hangzhou.aliyuncs.com%2Fzkys%2F62baa398e4b0b6ec317c0512.avi: Invalid data found when processing input

## 问题机型/系统：

例如 真机 

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.1-release-jitpack

## Demo中的复现步骤

无法播放

**Comment by kaikaifly** [comment]
我也是这个问题，avi无法播放，请问解决了吗
