### ISSUE TITLE
releaseAllVideos之后开启新页面视频播放会遇到问题

### ISSUE THREAD

**Issue by itsgm** [CarGuo/GSYVideoPlayer#3622]
问题描述：
A界面正在播放视频，把A界面finish掉，调用releaseAllVideos，
跳转到B界面开启一个新视频播放，这个时候B界面一直黑屏播放不了

如果B界面调用播放视频延时500毫秒，就可以正常播放了，这个怎么处理比较好？

**Comment by CarGuo** [comment]
postDelay 一下
