### ISSUE TITLE
GSYVideoBaseManager.java 下的 mTimeOutRunnable run方法体内空指针异常

### ISSUE THREAD

**Issue by bytebubbles** [CarGuo/GSYVideoPlayer#3625]
## 问题描述：
java.lang.NullPointerException
Attempt to invoke interface method 'void com.shuyu.gsyvideoplayer.listener.GSYMediaPlayerListener.onError(int, int)' on a null object reference

GSYVideoBaseManager.java 下的 mTimeOutRunnable run方法体内空指针异常
![image](https://user-images.githubusercontent.com/33546683/177093193-6a7dde65-bc60-44ed-9642-73dd7c04d248.png)

## GSY依赖版本

`com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.0.0`

## Demo中的复现步骤

GSYVideoManager.instance().setTimeOut(5000, true) //延时设置 true
弱引用 listener 被回收时
 
问题代码：(如果有)
```
private Runnable mTimeOutRunnable = new Runnable() {
        @Override
        public void run() {
            if (listener != null) {
                Debuger.printfError("time out for error listener");
                listener().onError(BUFFER_TIME_OUT_ERROR, BUFFER_TIME_OUT_ERROR);
            }
        }
};

@Override
public GSYMediaPlayerListener listener() {
        if (listener == null)
            return null;
        return listener.get();
}
```

## 问题log（如果有）

```

07-03 19:32:17.613 23690 23690 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.shuyu.gsyvideoplayer.listener.GSYMediaPlayerListener.onError(int, int)' on a null object reference

```

**Comment by CarGuo** [comment]
listener 不是有 null 判断么？

**Comment by CarGuo** [comment]
哦哦，你一说我就看到了， if (listener != null) ，这个 listener 少了 ()

**Comment by CarGuo** [comment]
已提交修复，下个版本发布
