### ISSUE TITLE
魅族18  点击全屏后，点击取消全屏，界面异常

### ISSUE THREAD

**Issue by zhangqilu** [CarGuo/GSYVideoPlayer#3627]
## 问题描述：

Demo中的点击简单播放，简单详情1，点击全屏后点击取消全屏，界面显示异常。其他机型测试正常。

## 问题机型/系统：

 真机 魅族18   Android  11

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.1-release-jitpack'

## Demo中的复现步骤

Demo中的点击简单播放，简单详情1，点击全屏后点击取消全屏，界面显示异常。

**Comment by CarGuo** [comment]
异常原因是什么？魅族目前没机器了，毕竟它都没快没了

**Comment by CarGuo** [comment]
我这边是没看到能复现的情况

**Comment by zhangqilu** [comment]
你用的是魅族18 吗

**Comment by CarGuo** [comment]
如下视频所示，没有魅族18，用的魅族16pro



https://user-images.githubusercontent.com/10770362/177236453-3f61ce52-aee8-4773-a8d5-34c9c71aabe2.mp4

**Comment by zhangqilu** [comment]
![image](https://user-images.githubusercontent.com/10182667/177237580-ff3e2f06-7dd0-423b-a92e-f1b9d3344cae.png)
这个是腾讯WeTest 可以免费用90分钟 ，有魅族18 ，我测试其他魅族机型是好的。有空帮忙看看，谢谢。

**Comment by CarGuo** [comment]
如果是特殊机型问题，就不是 GSY 考虑的问题了，如果你发现了是什么是什么问题，可以提供个参考，GSY不会针对某个机型去做适配
