### ISSUE TITLE
有没有判断视频缓存完的方法，我用的是DanmakuVideoPlayer，请教大佬

### ISSUE THREAD

**Issue by lyy90** [CarGuo/GSYVideoPlayer#3629]
问题描述：
我用的是Exoplayer 内核啊，我用的androidvideocache 缓存，我怎么获取缓存视频完的进度，因为我要在视频缓存完，开启视频下载功能。

出现问题的视频流
在线测试
https://aliyuncdnsaascloud.xjhktv.com/video/382100.mp4
问题机型/系统：
例如 定制版机顶盒

GSY依赖版本
例如 最新的源代码导入

Demo中的复现步骤
有没有判断视频缓存完的方法，我用的是DanmakuVideoPlayer，请教大佬

**Comment by CarGuo** [comment]
isCacheFile 的 api

**Comment by lyy90** [comment]
我想动态更新，每次重新播放，都会出来进度条。

**Comment by CarGuo** [comment]
isCacheFile 判断，clearCache 清理，其他不支持
