### ISSUE TITLE
setDismissControlTime 接口全屏下设置无效

### ISSUE THREAD

**Issue by mackkill** [CarGuo/GSYVideoPlayer#363]
如题：调用这个接口在全屏下会失效，getDismissControlTime返回数值没问题。

/**
     * 设置触摸显示控制ui的消失时间
     *
     * @param dismissControlTime 毫秒，默认2500
     */
    public void setDismissControlTime(int dismissControlTime) {
        this.mDismissControlTime = dismissControlTime;
    }

**Comment by CarGuo** [comment]
在全屏下确实有问题，下个版本修复

**Comment by CarGuo** [comment]
2.0.5
