### ISSUE TITLE
自定义布局，并且自己实现横屏布局遇到了问题

### ISSUE THREAD

**Issue by Matchas-xiaobin** [CarGuo/GSYVideoPlayer#3631]
## 问题描述：

我仅仅只用这个库播放视频，UI界面完全由我自己处理，包括旋转屏幕到横屏模式，所以我继承了StandardGSYVideoPlayer去掉了默认的部分UI，然后旋转屏幕时的处理是把这个控件直接从当前布局remove，然后重新activity.setContentView方法设置了一个横屏专用的布局，然后把这个控件addView(view, 0)这样的方式加到我的布局里，然后如果视频正在播放的情况下，是不会有问题的，但是如果视频处于暂停播放的时候，旋转屏幕后控件add到新布局里，暂停播放时的停留那一帧画面会消失，播放器直接是显示黑色的背景，请问下大佬，我应该如何在不触发继续播放的情况下让那一帧画面保留或者重新显示出来？

补充：activity 设置了 android:configChanges="uiMode|orientation|screenSize"，处理横竖屏切换是在onConfigurationChanged中手动处理的，所以没有触发重建activity

## 出现问题的视频流

我想应该不需要视频说明。

## 问题机型/系统：

任意手机

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.2-release-jitpack

## Demo中的复现步骤

无

问题代码：(如果有)

无

## 问题log（如果有）

无

**Comment by CarGuo** [comment]
setShowPauseCover true

**Comment by Matchas-xiaobin** [comment]
> setShowPauseCover true

可以了，完美解决，谢谢大佬！
