### ISSUE TITLE
连续播放#3102补充

### ISSUE THREAD

**Issue by Vicent9920** [CarGuo/GSYVideoPlayer#3632]
问题描述：
需求是实现类似爱奇艺，腾讯视频这样的连续播放功能，我在onAutoComplete方法中执行了播放下一条视频的代码，如果在小屏模式下播放正常，会一集播放完成之后继续播放下一集，但是如果我是在点击放大（全屏）的情况下播放完了一集之后，onAutoComplete中的代码也会走，也调用了开始播放的方法，但是播放器不会播放，请问这个问题在哪

问题机型/系统：
Android studio模拟器（android r）
华为noval3（9.1.0）

GSY依赖版本
implementation 'com.shuyu:GSYVideoPlayer:8.0.0'

Demo中的复现步骤
Demo中的SimpleDetailActivityMode1页面打开后，修改代码onAutoComplete方法中加入播放另外一段视频也会出现这个

##问题代码
@OverRide
public void onAutoComplete(String url, Object... objects) {
List data = mCourseVideoAdapter.getData();
int current = mCourseVideoAdapter.getCurrent();
if (current < mCourseVideoAdapter.getData().size() - 1) {
current++;
mCourseItemBean = data.get(current);
mCourseVideoAdapter.setCurrent(current);
startPlay(mCourseItemBean.getVideoUrl());
LogUtils.e("播放完成了,跳转下一集");
}
}

private void startPlay(String newUrl) {
if (isPause) {
return;
}
ImageView imageView = new ImageView(this);
ImageUtils.setImage(this, newUrl, imageView, R.mipmap.pic_zwnr);
mGsyVideoOptionBuilder.setUrl(newUrl)
.setVideoTitle("")
.build(mStandardGSYVideoPlayer);
mStandardGSYVideoPlayer.startPlayLogic();
}
补充：当A列表播放完成需要再直接播放B列表时，A列表需要播放完成时才能通过接口获取B列表，是不是就不能播放了？

**Comment by CarGuo** [comment]
player. getCurrentPlayer()
例如   ((ListGSYVideoPlayer) binding.detailPlayer.getCurrentPlayer()).playNext();
