### ISSUE TITLE
ijkplayer播放u盘视频,拔出后闪退

### ISSUE THREAD

**Issue by zhengjiong** [CarGuo/GSYVideoPlayer#3633]
### 问题描述：
使用ijkplayer硬解播放本地U盘视频的时候,在自定义VideoView中的setProgressAndTime打印如下日志:
`System.out.println("BufferedPercentage=" + getGSYVideoManager().getBufferedPercentage());`
`getGSYVideoManager().getBufferedPercentage()`始终输出是0, 试过`ExoPlayerCacheManager`或者默认的`ProxyCacheManager`都输出为0, 平时正常播放都没有任何问题, 但是测试喜欢播放的时候直接拔出U盘,导致app直接闪退, 目前我的做法是监听U盘拔出的事件来暂停或者释放播放器,但是还没来得及释放就已经崩溃了
 
如果换成exoplayer的话就没有这个问题, 我试过在setProgressAndTime打印getGSYVideoManager().getBufferedPercentage(), 发现视频会被缓冲一段时间,播放中拔出U盘就不会导致这个问题, 请问这个问题如果非要使用ijk来播避免U盘拔出时闪退应该怎么处理呢?

### 出现问题的视频流:
U盘视频

### GSY依赖版本:
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.2-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.2-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.2-release-jitpack'

**Comment by CarGuo** [comment]
ijk 模式暂时无法解决这个流突发异常的情况，从 so 处 crash 你在 java 层获取没用

**Comment by zhengjiong** [comment]
> ijk 模式暂时无法解决这个流突发异常的情况，从 so 处 crash 你在 java 层获取没用

ijk模式支持缓冲一段视频吗,  怎么设置呢

**Comment by CarGuo** [comment]
缓冲只有按照块缓冲，要是缓冲太大，内存会受不了

**Comment by zhengjiong** [comment]
> 

需要怎么设置呢  我想试一试

**Comment by CarGuo** [comment]
你在问题集锦里搜索 buffer_size

**Comment by zhengjiong** [comment]
👌

**Comment by zhengjiong** [comment]
设置ijk缓冲之后也没有什么用, 拔出U盘还是立马闪退

**Comment by CarGuo** [comment]
我没有说设置能解决这个问题，前面我都说了这个不支持

**Comment by zhengjiong** [comment]
> 

好的 谢谢
