### ISSUE TITLE
如何通过GSYVideoManager获取当前播放器的速度speed

### ISSUE THREAD

**Issue by SkyD666** [CarGuo/GSYVideoPlayer#3635]
## 问题描述：

只看到setSpeed方法了，没找到getSpeed方法
![2022-07-13 181207_112](https://user-images.githubusercontent.com/32453770/178709759-3da81932-4f43-45aa-9b95-fe982263412e.png)

**Comment by SkyD666** [comment]
主要是这块代码不在播放器内部，而设置速度是在播放器内设置的，比较难搞

**Comment by CarGuo** [comment]
没什么难搞的，demo 里的 DetailControlActivity 不就是这样设置切换的？你设置进去的状态自己找个地方保存就好了

**Comment by SkyD666** [comment]
另外想问一下，aliplayer是不是没有armeabi的
