### ISSUE TITLE
倍速播放问题

### ISSUE THREAD

**Issue by lihaodong** [CarGuo/GSYVideoPlayer#3636]
## 问题描述：

倍速播放大于1，切换无效，
已使用 setSpeed(float speed, boolean soundTouch)，不起作用

## 出现问题的视频流

 和视频流无关系

## 问题机型/系统：

荣耀magic3

## GSY依赖版本
  1.目前依赖 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack'
  2.下载了提供的最新版本的APK也不行

## 问题相关
  经过测试提供的APK，IJK内核有问题，切换原生或者Exo的没有问题。暂时先切为EXO了

**Comment by CarGuo** [comment]
ijk 同步时钟是音频，如果是兼容问题，soundTouch 如果 true 了还无效，那说明真的不支持
