### ISSUE TITLE
关于自定义的内核

### ISSUE THREAD

**Issue by Thank4** [CarGuo/GSYVideoPlayer#3638]
## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by CarGuo** [comment]
你可以参考 demo 里的 exo 目录下的自定义实现 https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exo

或者 

https://github.com/CarGuo/GSYVideoPlayer/commit/6d50fa33a34ee52913637f6365494a0d29d7782c

**Comment by Thank4** [comment]
> 你可以参考 demo 里的 exo 目录下的自定义实现 https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exo
> 
> 或者
> 
> [6d50fa3](https://github.com/CarGuo/GSYVideoPlayer/commit/6d50fa33a34ee52913637f6365494a0d29d7782c)

thank u，CarGuo
