### ISSUE TITLE
Exoplayer 内核顺序播放多个视频，200多个视频，播放到123个视频的时候，会黑屏，重播当前视频，只有声音，没有画面

### ISSUE THREAD

**Issue by lyy90** [CarGuo/GSYVideoPlayer#3639]
问题描述：
Exoplayer 内核顺序播放多个视频，200多个视频，播放到123个视频的时候，会黑屏，重播当前视频，只有声音，没有画面

出现问题的视频流
在线高清MV
问题机型/系统：
例如 定制机顶盒

GSY依赖版本
例如 最新的GSY版本，我导入是最新的源代码

Demo中的复现步骤
Exoplayer 内核顺序播放多个视频，200多个视频，播放到123个视频的时候，会黑屏，重播当前视频，只有声音，没有画面

问题代码：(如果有)
 初始化播放器控件
  binding!!.videoPlayer.shrinkImageRes = R.drawable.custom_shrink
        binding!!.videoPlayer.enlargeImageRes = R.drawable.custom_enlarge
        binding!!.videoPlayer.setSelectedSongViewModel(selectedSongViewModel, owner)
        binding!!.videoPlayer.setVoiceListModel(voiceListModel, owner)
        binding!!.videoPlayer.setmainViewModel(mainViewModel, owner)
        //外部辅助的旋转，帮助全屏
        mOrientationOption = OrientationOption()
        orientationUtils =
            OrientationUtils(outerContext as Activity?, binding!!.videoPlayer, mOrientationOption)
        //初始化不打开外部的旋转
        orientationUtils!!.isEnable = true
        binding!!.videoPlayer.setIsTouchWiget(true)
        //关闭自动旋转
        binding!!.videoPlayer.isRotateViewAuto = false
        binding!!.videoPlayer.isLockLand = false
        //设置 seek 的临近帧。
        binding!!.videoPlayer.isReleaseWhenLossAudio = false
        if (binding!!.videoPlayer != null && binding!!.videoPlayer.isInPlayingState) {
            if (binding!!.videoPlayer.gsyVideoManager.player != null) {
                if (binding!!.videoPlayer.gsyVideoManager.player is Exo2PlayerManager) {
                    (binding!!.videoPlayer.gsyVideoManager.player as Exo2PlayerManager).setSeekParameter(
                        SeekParameters.NEXT_SYNC
                    )
                }
            }
        }
  我在歌曲自动播放完就自动播放下一首歌
    override fun onAutoComplete(url: String?, vararg objects: Any?) {
                super.onAutoComplete(url, objects)
                getSwitchSong(type)
            }

**Comment by CarGuo** [comment]
定制机顶盒问题只能你自己处理，你可以在播放结束的时候主动调用release并且暂时200ms来播放下一个试试…
不过还是那句话，机顶盒上的问题只能你自己处理

**Comment by lyy90** [comment]
好的，大佬，
