### ISSUE TITLE
Exo视频出现OOM

### ISSUE THREAD

**Issue by ly469097645** [CarGuo/GSYVideoPlayer#3644]
## 问题描述：

更换为Exo内核之后，出现了OOM

## 问题机型/系统：

真机 realme RMX3231 android 11

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.1-release-jitpack'

## 问题log

![image](https://user-images.githubusercontent.com/12133597/180115876-c3e5ccd1-2800-46ac-8dc5-6fb846b98e9a.png)

**Comment by CarGuo** [comment]
如何复现
