### ISSUE TITLE
视频小窗+悬浮播放的问题

### ISSUE THREAD

**Issue by hponiang** [CarGuo/GSYVideoPlayer#3645]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
你好
请问我想实现视频播放时可以选择小窗悬浮模式，跳转到别的页面或退到后台仍可以播放，再点击视频还可以再回到该原始页面播放，怎么实现比较好

**Comment by CarGuo** [comment]
demo WindowActivity 里有，回到原页面切换逻辑你需要自己做，具体就是切换下 Surface ，这部分逻辑可以参考 SwitchDetailActivity

**Comment by hponiang** [comment]
好的，谢谢，我先研究一下，大佬速度真快，已给你赞助了一杯咖啡

**Comment by hponiang** [comment]
看了一天源码，大致梳理清了，有个重点GSYVideoBaseManager是单例模式，默认同一时间只能控制一个 video ui，可以在切换小浮窗时将当前 video 存到lastListener里，后续恢复主页面播放时可以再恢复监听
