### ISSUE TITLE
m3u8怎么设置边播边下的最大时间

### ISSUE THREAD

**Issue by ZiiQ18** [CarGuo/GSYVideoPlayer#3646]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不支持

**Comment by ZiiQ18** [comment]
> 不支持

可以自定义缓存改吗？

**Comment by CarGuo** [comment]
你可以尝试实现自己的  `ICacheManager`  ， 现在 exo 用的是自带默认的 SimpleCache 的逻辑
