### ISSUE TITLE
横竖屏切换，播放按钮变形

### ISSUE THREAD

**Issue by LIBYER** [CarGuo/GSYVideoPlayer#3648]
![image](https://user-images.githubusercontent.com/22723315/180685316-c810dc0f-3e31-497c-915e-b945faffe53b.png)

**Comment by CarGuo** [comment]
切换过程中变形正常

**Comment by LIBYER** [comment]
这个能解决嘛，担心后面测试或者UI提这个bug过来。

**Comment by CarGuo** [comment]
你关闭切换动画呗
