### ISSUE TITLE
SystemPlayerManager 全屏和常规窗口切换出现短暂声音播放

### ISSUE THREAD

**Issue by ZDZN** [CarGuo/GSYVideoPlayer#3649]
## 问题描述：

使用 SystemPlayerManager 系统播放器，播放过程中暂停，暂停后进行全屏与常规窗口切换，会出现短暂的声音播放；
使用其他内核不会出现该问题

## 出现问题的视频流

Demo 简单播放->简单列表1->第二个视频

其实第一个视频也会，但因为第一个视频没有背景声音、持续声音不长，刚好暂时的时间点没声音，就听不出

## 问题机型/系统：

例如 真机 Oppo FindX Android10

## GSY依赖版本

例如 `com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.1-release-jitpack`

## Demo中的复现步骤

1、进入 demo 后切换为系统内核；
2、打开 Demo 简单播放->简单列表1->第二个视频
3、点击播放，在声音比较频密的位置暂停（背景声音比较大、声音持续时间比较长的位置）
4、暂停后进行全屏与常规窗口切换，切换过程中会出现短暂声音播放；

**Comment by CarGuo** [comment]
这么奇怪？？ 问题是这时候也没有看到有触发它播放的地方啊·····

**Comment by CarGuo** [comment]
👆 机缘巧合发现问题，已经修复

**Comment by CarGuo** [comment]
实际问题 [mediaPlayer setSpeed](https://github.com/CarGuo/GSYVideoPlayer/commit/f8d7a1907b5a2e9206d8654da757537812393f0b)  的时候，会触发自动播放，下版本发布
