### ISSUE TITLE
封面背景如果不是黑色，标准播放器界面顶部会有一个文本为Ijkplaer-exo的titlebar闪一下

### ISSUE THREAD

**Issue by TuringHuang** [CarGuo/GSYVideoPlayer#365]
我用你这个标准播放器做直播拉流播放器，封面设置为别的，然后背景没有设置成黑色，进入界面后，大概5秒钟的时间，播放器顶部的那个titlebar虽然看不到，但是会让顶部有阴影，然后5秒钟后会自己隐藏，这个titlebar怎么去掉呢

**Comment by CarGuo** [comment]
不是很理解，demo中会吗？
