### ISSUE TITLE
使用ijk内核，无法播放本地的raw视频

### ISSUE THREAD

**Issue by ly469097645** [CarGuo/GSYVideoPlayer#3650]
## 问题描述：

使用ijk内核，无法播放本地的raw视频

## 出现问题的视频流

https://user-images.githubusercontent.com/12133597/180755376-ad2a7053-d36c-4785-b5fc-2f6a998cfb60.mp4

## 问题机型/系统：

真机 redmi k40

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.1-release-jitpack'

## Demo中的复现步骤

将上面的视频放到raw目录下，放到demo中的简单播放中后黑屏无法播放

问题代码：(如果有)
GSYVideoManager.instance().enableRawPlay(context)
var url = "android.resource://" + context.packageName + "/" + R.raw.a_0900121656061212745
videoPlayer.setUp(url, false, "")

**Comment by ly469097645** [comment]
![QQ截图20220725202454](https://user-images.githubusercontent.com/12133597/180777107-4a24d80c-4332-4bbc-903d-0ecd857de14d.png)

在demo中的SimplePlayer尝试播放raw中的视频也是失败的

**Comment by CarGuo** [comment]
demo 里的 raw 资源测试可以播放，黑屏无法播放你要看你的编码是什么，为什么黑屏

**Comment by ly469097645** [comment]
demo中只有一个可以播的，其他的好像也是都不行

**Comment by ly469097645** [comment]
大佬回复下呗，ijk的播放本地的raw，demo中detailplay有个test5.mp4也是不能播放，这个除了格式和视频长短有关系吗，如果本地是个4秒左右的视频会导致播放失败吗，错误一直是（-10000，0）

**Comment by CarGuo** [comment]
都说了要看编码…

**Comment by ly469097645** [comment]
看了编码了，demo里的视频都是hevc的，但是唯独test5.mp4无法播放，我也把我的本地视频转成hevc了，但是也是播不了
