### ISSUE TITLE
RecyclerView列表展示获取视频地址并播放第一次不走回调

### ISSUE THREAD

**Issue by lucky-you** [CarGuo/GSYVideoPlayer#3652]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

列表展示，点击item1获取视频地址成功后播放不走回调，点击item2获取视频地址成功后播放才会走回调，但返回的数据确实item1的，后一次返回的是前一个的数据。

## 问题机型/系统：

三星 S8 andorid 9.0 

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.7-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-arm64:v8.1.7-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:v8.1.7-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-x86:v8.1.7-release-jitpack'

## Demo中的复现步骤

问题代码：(如果有)
 smallVideoHelper.setPlayPositionAndTag(position, TAG);
getRecyclerBaseAdapter().notifyDataSetChanged();
 gsySmallVideoHelperBuilder.setUrl(data);
gsySmallVideoHelperBuilder.setPlayPosition(position);
 smallVideoHelper.startPlay();
 CameraVideoView mCameraVideoView = (CameraVideoView) smallVideoHelper.getGsyVideoPlayer();
gsySmallVideoHelperBuilder.setVideoAllCallBack(new SampleCoverListener() {
            @Override
            public void onPrepared(String url, Object... objects) {
                super.onPrepared(url, objects);
                int gsyPosition = smallVideoHelper.getPlayPosition();
                String mDeviceCode = deviceItem.deviceCode;
                ZhoLogUtils.i(" onPrepared 加载成功 position:" + gsyPosition + "--- farmName:" + deviceItem.farmName);
                mCameraVideoView.setDeviceCode(mDeviceCode);
                onGetVideoCover(mCameraVideoView, mDeviceCode);
            }
}

## 问题log（如果有）

![log](https://user-images.githubusercontent.com/22268878/180904355-a9e1268b-8fab-4825-9c74-9f68da947b7f.jpg)

**Comment by CarGuo** [comment]
demo 哪里有问题？
