### ISSUE TITLE
倍速播放能改成二倍速以上吗

### ISSUE THREAD

**Issue by writeabug** [CarGuo/GSYVideoPlayer#3655]
依赖
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.3-release-jitpack'

使用的是ijkplayer内核，想要将倍速播放调整为三倍速，发现上限只有2倍速，这个有办法在代码里修改掉吗

**Comment by CarGuo** [comment]
自己修改ijk相关实现
