### ISSUE TITLE
这个mpeg2视频用exo能播放, 为什么ijk软硬解却不能, 已经使用了ex_so

### ISSUE THREAD

**Issue by zhengjiong** [CarGuo/GSYVideoPlayer#3656]
### 问题描述：
使用exo模式播放该视频可以正常播放该视频,打印该视频的format信息如下:
VideoFormat(1/256, null, null, video/mpeg2, null, -1, null, [192, 168, -1.0], [-1, -1]) 
切换为ijk硬解或软件模式后, 点击播放报如下错误:
tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

### 出现问题的视频流:
本地视频:
下载地址(很小只有8mb):
 https://pan.baidu.com/s/1U0_Dyk1jN_KZn6S4dCTcbQ?pwd=7ia9 提取码: 7ia9

### GSY依赖版本:
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.3-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.3-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.3-release-jitpack'

**Comment by CarGuo** [comment]
因为只支持了 
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mpegps"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mpegts"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mpegvideo"

**Comment by zhengjiong** [comment]
> 

自己编译的话, 需要打开哪些呢, 我看module-lite-more.sh中好像没有mpeg2相关的

**Comment by CarGuo** [comment]
我试了下你的视频，是的视频问题不在于视频编码，在于音频编码 ac3 ，parser not found for codec ac3
例如增加 export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ac3"

**Comment by zhengjiong** [comment]
> 我试了下你的视频，是的视频问题不在于视频编码，在于音频编码 ac3 ，parser not found for codec ac3 例如增加 export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ac3"

好的 非常感谢  我去试一下
