### ISSUE TITLE
加载flv视频监控非常卡顿

### ISSUE THREAD

**Issue by liqiaoshen61** [CarGuo/GSYVideoPlayer#3658]
**问题描述**：
播放下面的url加载时间较长，在播放1-3秒后，又进入长时间的加载，甚至会停止播放，需要再点击播放。
我想知道是什么参数没有配置的问题，还是说视频流本身的问题。
如果是参数问题，请问应该如何配置。

**出现问题的视频流**
https://dt-video.jie-xin.com:8700/live/GDT0297ae_1_0_jw.flv

**问题机型/系统**：
华为CMR-w09平板  系统：鸿蒙2.0.0

**GSY依赖版本**
com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.1-release-jitpack

**加载代码**

        vb.gsyView.setUp((videoUrl), false, "")
        //增加title
        vb.gsyView.titleTextView.visibility = View.VISIBLE
        //设置返回键
        vb.gsyView.backButton.visibility = View.VISIBLE
        //是否可以滑动调整(进度、亮度、音量)
        vb.gsyView.setIsTouchWiget(false)
        //设置旋转
        orientationUtils = OrientationUtils(this, vb.gsyView)
        //全屏按钮
        vb.gsyView.fullscreenButton.setOnClickListener {
            orientationUtils!!.resolveByClick()
        }
        GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_DEFAULT)
        //设置返回按键功能
        vb.gsyView.backButton.setOnClickListener {
            onBackPressed()
        }
        vb.gsyView.startPlayLogic()

**Comment by CarGuo** [comment]
HttpDataSource$HttpDataSourceException: Unable to connect

IJKMEDIA: https://dt-video.jie-xin.com:8700/live/GDT0297ae_1_0_jw.flv: End of file
