### ISSUE TITLE
请问一下怎么修改module.sh来达到支持其他视频格式。

### ISSUE THREAD

**Issue by Basakerone** [CarGuo/GSYVideoPlayer#366]
按照作者的自定义编译SO方法以可以编译，但是module-default.sh编译后，SO很大。作者你这个很小，想根据module-lite-hevc.sh里面去添加对其他格式的支持，但是不知道怎么改。。。去了ijkplayer那边也是一头雾水。能说一下怎么改吗？

**Comment by CarGuo** [comment]
现在的github包含了两个修改的module的脚本，你可以看看对比参考下

**Comment by Basakerone** [comment]
不好意思，看了一下作者你的两个.sh文件，more的貌似增加concat、rtsp、crypto、mpeg等。是不是export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mkv"这种嘛?

**Comment by CarGuo** [comment]
有容器协议，编码协议等，你可以看看 http://blog.csdn.net/leixiaohua1020/article/details/18893769

**Comment by Basakerone** [comment]
谢谢作者，我看了一下我这个本地视频.mkv他的视频编码是AVC（H264） 音频是 AAC,然后感觉module-lite-more里面支持这些协议和编解码的，但是播放不了，请问是什么问题。

**Comment by Basakerone** [comment]
http://static.answeryou.cn/sp.mkv  （视频地址，七牛）
我在作者你的module-lite-more.sh中加入了
--enable-muxer=matroska
--enable-muxer=matroska_audio
--enable-demuxer=matroska
（ijkplayer里看到的，编译后替换了EX_SO库里面的全部SO文件,但是并没有播放成功）
作者麻烦你提供一下mkv和rmvb的支持代码可以吗？麻烦作者了。

**Comment by Basakerone** [comment]
已解决，谢谢作者耐心解答

**Comment by xiaoshen9404** [comment]
@Basakerone 
请问你是怎么修改脚本的，我现在mkv也没有播放成功

**Comment by zerorooot** [comment]
https://zerorooot.github.io/2021/02/11/ijkplayer%E7%BC%96%E8%AF%91/
