### ISSUE TITLE
请问一下，minsdk升级的19的原因是什么？

### ISSUE THREAD

**Issue by LIBYER** [CarGuo/GSYVideoPlayer#3661]
## 问题描述：
请问一下，minsdk升级的19的原因是什么？是因为某些库要求19吗？
项目要求最低17，如果导源码，降低到17，引用以下依赖，会有什么兼容性问题吗
    implementation project(":gsyVideoPlayer-java")
    implementation project(":gsyVideoPlayer-proxy_cache")
    implementation project(":gsyVideoPlayer-exo_player2")
    implementation project(":gsyVideoPlayer-base")

**Comment by CarGuo** [comment]
不大记得，但是应该可以
