### ISSUE TITLE
焦点暂时丢失后暂停播放,然后重新获取焦点之后没有恢复播放

### ISSUE THREAD

**Issue by zhengjiong** [CarGuo/GSYVideoPlayer#3662]
### 问题描述：
焦点暂时丢失后暂停播放,然后重新获取焦点之后没有恢复播放, 请 问这个是因为源码中使用AUDIOFOCUS_GAIN_TRANSIENT请求焦点, 而不是使用AUDIOFOCUS_GAIN造成的吗? 应该怎么处理呢?

### 测试步骤
对手机智能语音说话的时候会回调onAudioFocusChangeListener,这个时候收到的是AUDIOFOCUS_LOSS_TRANSIENT, 然后我们会暂停播放,然后当智能语音说话结束的时候也会回调, 但是这个时候GSYVideoView接收到的focusChange是AudioManager.AUDIOFOCUS_GAIN_TRANSIENT,  源码中并没有处理这个, 就无法恢复播放

### 出现问题的视频流:
本地视频:

### GSY依赖版本:
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.3-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.3-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.3-release-jitpack'

**Comment by zhengjiong** [comment]
[AUDIOFOCUS_GAIN]的使用场景：应用需要聚焦音频的时长会根据用户的使用时长改变，属于不确定期限。例如：多媒体播放或者播客等应用。
[AUDIOFOCUS_GAIN_TRANSIENT]的使用场景：应用只需短暂的音频聚焦，但包含了不同响应情况，例如：电话、QQ、微信等通话应用。

**Comment by zhengjiong** [comment]
我自己测试了一下如果请求焦点使用的是AUDIOFOCUS_GAIN的话, 在暂时丢失焦点后重新获取焦点的时候, focusChange为AudioManager.AUDIOFOCUS_GAIN

**Comment by zhengjiong** [comment]
源码中的requestAudioFocus 第三个参数是不是应该修改为AUDIOFOCUS_GAIN

**Comment by CarGuo** [comment]
有一个 setReleaseWhenLossAudio 的 api
