### ISSUE TITLE
Exo内核硬解码播放视频绿屏闪烁

### ISSUE THREAD

**Issue by Yangqingchun** [CarGuo/GSYVideoPlayer#3665]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

使用EXO内核播放视频时，开启硬解码，切换到全屏后，开始绿屏闪烁，此时返回到正常大小播放同样也会绿屏闪烁，但向前或向后调整一下播放进度后就可以正常播放了

## 出现问题的视频流

任何视频都会出现

## 问题机型/系统：

Android12

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 30);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
//        开启硬解码渲染
        GSYVideoType.enableMediaCodec();
        GSYVideoType.enableMediaCodecTexture();

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
exo不用配置默认就是硬解码，配不配置没用

**Comment by Yangqingchun** [comment]
> exo不用配置默认就是硬解码，配不配置没用

用IJK开启硬解码是不是也没有用呢，我切换成IJK后还是用上边的代码开启硬解码渲染，感觉播放视频没有什么变化..

**Comment by CarGuo** [comment]
我测试没发现问题，猜测可能是你视频兼容问题
