### ISSUE TITLE
偶现tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

### ISSUE THREAD

**Issue by crazyzjw** [CarGuo/GSYVideoPlayer#3667]
偶现tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)就直接走onPlayError,重新播放又正常...出现几率高

## 问题机型/系统：

真机 华为/一加 android11都会出现

## GSY依赖版本

```
   def gsy_video_version = 'v8.3.3-release-jitpack'
    implementation "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:$gsy_video_version"
    implementation "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-arm64:$gsy_video_version"
    implementation "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:$gsy_video_version"
```

## 问题log（如果有）

<img width="603" alt="image" src="https://user-images.githubusercontent.com/12543049/184317316-d9878ec7-b8fd-4829-b368-9b4c726d727c.png">

**Comment by CarGuo** [comment]
比如出现网络断了，或者波动，导致原本链接断开，缓冲播完了，就有可能出现这样的情况

**Comment by crazyzjw** [comment]
> 比如出现网络断了，或者波动，导致原本链接断开，缓冲播完了，就有可能出现这样的情况

最近升级框架之后,这个情况经常触发了,是因为setCacheWithPlay(false)导致情况更容易出现吗?,回调后都要重新播放了

**Comment by CarGuo** [comment]
感觉和你升级版本应该没关系，不过false和true确实影响拉流的来源

**Comment by liudaohong** [comment]
我也遇到了，也是这个版本 。 而且出现这个错误后 ，再来播放这个视频  就需要清楚缓存才能正常播放了
