### ISSUE TITLE
GSYVideoBaseManager中的initVideo为private无法修改流程，单要修改播放器为单例且不希望每次release掉播放器，就无法实现

### ISSUE THREAD

**Issue by microzhang715** [CarGuo/GSYVideoPlayer#3668]
## 问题描述：

⚠️
1、GSYVideoBaseManager中的initVideo为private无法修改流程，单要修改播放器为单例且不希望每次release掉播放器，就无法实现，除非把代码拷贝出来，然后再继承修改
GSYVideoBaseManager中大部分方法都是proteted 或者 public可以方便复写，唯独initVideo是private，导致无法复写，降低了灵活性

2、GSYVideoBaseManager中的MediaHandler建议放在非主线程，这样可以对性能有一定的优化，否则低端机上主线程繁忙时候，会导致播放器的消息通道卡顿，从而导致播放器性能大幅度降低

## 建议对上述问题进行修复

```
// 私有方法
private void initVideo(Message msg) {}

// 主线程Handler
mMediaHandler = new MediaHandler((Looper.getMainLooper()));
mainThreadHandler = new Handler();

```

**Comment by CarGuo** [comment]
因为必须是单例，就算多个同时播放也不会有复用通一个内核的说法，流链接每次都需要重置。
Handler那个是有原因的，具体时间比较久远了：

**Comment by microzhang715** [comment]
GSYVideoBaseManager确实是单例的，但是这个单例对象仅限管理对象，该管理对象里面所持有的播放器并非单例对象，而是每次播放都会构建一个新的播放器对象，播放器对象反复构建和销毁，尤其是构建存在初始化流程，每次初始化都会消耗大量的资源，从而导致低端机上使用的时候效率低下的问题

**Comment by CarGuo** [comment]
所以你觉得内核是可以不释放复用？

**Comment by microzhang715** [comment]
嗯，是的 stop掉播放器后，重新设置url 然后 prepare+start来复用播放能力，不清楚我这样的理解对不对，我自己验证了一下Demo是没有问题的，这样可以避免播放器反复创建销毁的操作。
当然这种做法主要是希望再低端机上提高播放的性能而设计的
