### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by hardyio** [CarGuo/GSYVideoPlayer#3669]
## 问题描述：

DEMO自定义EXO支持字幕里设置的url失效
http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4

## 出现问题的视频流

如上

## 问题机型/系统：

Web端

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.3.0'`

## Demo中的复现步骤

如题

```

**Comment by CarGuo** [comment]
这个自己换个流链接就好了
