### ISSUE TITLE
音量放大

### ISSUE THREAD

**Issue by wflian** [CarGuo/GSYVideoPlayer#3670]
有办法增强放大音量吗？比如：setVolume（2.0,2.0） ，音量放大两倍

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/af3becf7c69e19da602185d00715d266f2b712e0/gsyVideoPlayer-base/src/main/java/com/shuyu/gsyvideoplayer/player/IPlayerManager.java#L44
