### ISSUE TITLE
demo中简单详情2-非全屏下暂停视频，然后点击全屏后点击暂停键继续播放，只有声音视频还是暂停不会动了

### ISSUE THREAD

**Issue by pengjunshan** [CarGuo/GSYVideoPlayer#3673]
demo中简单详情2-非全屏下暂停视频，然后点击全屏后点击暂停键继续播放，只有声音视频还是暂停不会动了；反之-全屏状态下暂停视频，点击非全屏后再点击暂停键继续播放，只有声音，视频不动。

**Comment by CarGuo** [comment]
没有复现问题

**Comment by SmartVive** [comment]
我这边也有这样问题，demo中简单详情1，v8.2.0没问题，v8.3.0开始的

**Comment by pengjunshan** [comment]
可能是最新版本的有这个问题吧，没试其它版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 下午5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] demo中简单详情2-非全屏下暂停视频，然后点击全屏后点击暂停键继续播放，只有声音视频还是暂停不会动了 (Issue #3673)





 
我这边也有这样问题，demo中简单详情1，v8.2.0没问题，v8.3.0开始的

**Comment by SmartVive** [comment]
是GSYVideoView中193行代码canvas = mSurface.lockHardwareCanvas();的问题，可以先重写成使用mSurface.lockCanvas方法解决

**Comment by CarGuo** [comment]
所有设备版本？这个应该是只在高版本下才会调用

**Comment by SmartVive** [comment]
机器是android10的能复现，代码是大于等于android6.0就运行此方法了，也不算高版本吧。

**Comment by pengjunshan** [comment]
大佬们 这个怎么解决呢 这也是个比较严重的问题啊

**Comment by CarGuo** [comment]
setShowPauseCover 为 false

**Comment by pengjunshan** [comment]
多谢大佬！setShowPauseCover 为 false 试了 可以解决， 就是有点小瑕疵 暂停后放大或缩小播放器会黑屏

**Comment by CarGuo** [comment]
Lock hareware 在一些机器上会卡死 surface 的 buffer ，这个是我没有想到的，下个版本更新处理

**Comment by pengjunshan** [comment]
好 多谢开源 会继续关注的
