### ISSUE TITLE
SIGABRT

### ISSUE THREAD

**Issue by itsgm** [CarGuo/GSYVideoPlayer#3674]
问题描述：
#87002 SIGABRT
#00 pc 0003d854 /system/lib/libc.so (tgkill+12) [armeabi-v7a::3ce72113e60b837f1c1164921b9bdf3c]

问题机型/系统：
我们的设备都是5.1.1系统，出现这个错误比较多，我看bugly跟踪数据都是在播放视频页面出现的

GSY依赖版本
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.0-release-jitpack'
使用的ExoPlayer内核

 问题log（如果有）
bugly报错信息：
1
#00 pc 0003d854 /system/lib/libc.so (tgkill+12) [armeabi-v7a::3ce72113e60b837f1c1164921b9bdf3c]
2
#01 pc 00016dad /system/lib/libc.so (pthread_kill+52) [armeabi-v7a::3ce72113e60b837f1c1164921b9bdf3c]
3
#02 pc 000179bf /system/lib/libc.so (raise+10) [armeabi-v7a::3ce72113e60b837f1c1164921b9bdf3c]
4
#03 pc 00014165 /system/lib/libc.so (__libc_android_abort+36) [armeabi-v7a::3ce72113e60b837f1c1164921b9bdf3c]
5
#04 pc 000124ec /system/lib/libc.so (abort+4) [armeabi-v7a::3ce72113e60b837f1c1164921b9bdf3c]
6
#05 pc 00007bc9 /system/lib/libcutils.so (__android_log_assert+88) [armeabi-v7a::2dfe9c1490631de269854de55016d739]
7
#06 pc 0005b25f /system/lib/libstagefright.so (android::ACodec::ExecutingState::submitRegularOutputBuffers()+202) [armeabi-v7a::34b1a7473bcf78c5e7153b5748256135]
8
#07 pc 0005b933 /system/lib/libstagefright.so (android::ACodec::ExecutingState::submitOutputBuffers()+4) [armeabi-v7a::34b1a7473bcf78c5e7153b5748256135]
9
#08 pc 0005b959 /system/lib/libstagefright.so (android::ACodec::ExecutingState::resume()+12) [armeabi-v7a::34b1a7473bcf78c5e7153b5748256135]
10
#09 pc 00060793 /system/lib/libstagefright.so (android::ACodec::IdleToExecutingState::onOMXEvent(OMX_EVENTTYPE, unsigned int, unsigned int)+158) [armeabi-v7a::34b1a7473bcf78c5e7153b5748256135]
11
#10 pc 0005f3cb /system/lib/libstagefright.so (android::ACodec::BaseState::onOMXMessage(android::sp<android::AMessage> const&)+342) [armeabi-v7a::34b1a7473bcf78c5e7153b5748256135]
12
#11 pc 0005f619 /system/lib/libstagefright.so (android::ACodec::BaseState::onMessageReceived(android::sp<android::AMessage> const&)+84) [armeabi-v7a::34b1a7473bcf78c5e7153b5748256135]
13
#12 pc 0005fb9d /system/lib/libstagefright.so (android::ACodec::LoadedToIdleState::onMessageReceived(android::sp<android::AMessage> const&)+108) [armeabi-v7a::34b1a7473bcf78c5e7153b5748256135]
14
#13 pc 0000b879 /system/lib/libstagefright_foundation.so (android::AHierarchicalStateMachine::handleMessage(android::sp<android::AMessage> const&)+44) [armeabi-v7a::2f1f07da665ce5b4eb3f6317866bf218]
15
#14 pc 00056afb /system/lib/libstagefright.so [armeabi-v7a::34b1a7473bcf78c5e7153b5748256135]
16
#15 pc 0000c603 /system/lib/libstagefright_foundation.so (android::ALooperRoster::deliverMessage(android::sp<android::AMessage> const&)+166) [armeabi-v7a::2f1f07da665ce5b4eb3f6317866bf218]
17
#16 pc 0000bf85 /system/lib/libstagefright_foundation.so (android::ALooper::loop()+220) [armeabi-v7a::2f1f07da665ce5b4eb3f6317866bf218]
18
#17 pc 00010519 /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112) [armeabi-v7a::3fd13949c18a7d751ea7a4219b56f472]
19
#18 pc 00010089 /system/lib/libutils.so [armeabi-v7a::3fd13949c18a7d751ea7a4219b56f472]
20
#19 pc 0001659b /system/lib/libc.so (__pthread_start(void*)+30) [armeabi-v7a::3ce72113e60b837f1c1164921b9bdf3c]
21
#20 pc 000144c3 /system/lib/libc.so (__start_thread+6) [armeabi-v7a::3ce72113e60b837f1c1164921b9bdf3c]
22
java:
23
[Failed to get Java stack]

跟踪数据：
7808-24 01:22:21.489 1339 1339 D EventLogger: loading [false]
--
7908-24 01:22:22.184 1339 1339 D EventLogger: loading [true]
8008-24 01:22:22.191 1339 1339 D EventLogger: loading [false]
8108-24 01:22:22.832 1339 1339 D EventLogger: loading [true]
8208-24 01:22:22.836 1339 1339 D EventLogger: loading [false]
8308-24 01:22:23.492 1339 1339 D EventLogger: loading [true]
8408-24 01:22:23.493 1339 1339 D EventLogger: loading [false]
8508-24 01:23:14.521 1339 9481 D ACodec : [OMX.google.aac.decoder] saw output EOS
8608-24 01:23:15.038 1339 1339 D EventLogger: state [191.34, E]
8708-24 01:23:15.095 1339 9479 D MediaCodecInfo: NoSupport [sizeAndRate.support, 3640x2048x25.000001907348633] [OMX.rk.video_decoder.avc, video/avc] [VSD242, st-tx3288-ah-00, TX, 22]
8808-24 01:23:15.095 1339 9479 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640033, video/avc] [OMX.google.h264.decoder, video/avc] [VSD242, st-tx3288-ah-00, TX, 22]
8908-24 01:23:15.097 1339 9497 I OMXClient: Using client-side OMX mux.
9008-24 01:23:15.101 1339 9497 E ACodec : [OMX.rk.video_decoder.avc] storeMetaDataInBuffers failed w/ err -1010
9108-24 01:23:15.337 1339 1339 D EventLogger: videoSizeChanged [3640, 2048]
9208-24 01:23:15.339 1339 1339 D ViewRootImpl: 1366<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=897 sim=#20 ty=1 fl=#81810580 wanim=0x7f13000a vsysui=0x1706 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.banu.interactivetoken=android.os.BinderProxy@781a636}
9308-24 01:23:15.392 1339 9479 D MediaCodecInfo: NoSupport [sizeAndRate.support, 3640x2048x25.000001907348633] [OMX.rk.video_decoder.avc, video/avc] [VSD242, st-tx3288-ah-00, TX, 22]
9408-24 01:23:15.392 1339 9479 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640033, video/avc] [OMX.google.h264.decoder, video/avc] [VSD242, st-tx3288-ah-00, TX, 22]
9508-24 01:23:15.392 1339 1339 I ExoPlayerImpl: Release e7ccc68 [ExoPlayerLib/2.17.1] [VSD242, st-tx3288-ah-00, TX, 22] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
9608-24 01:23:15.408 1339 1339 I ExoPlayerImpl: Init 29b01f98 [ExoPlayerLib/2.17.1] [VSD242, st-tx3288-ah-00, TX, 22]
9708-24 01:23:15.482 1339 1339 D EventLogger: state [0.07, B]
9808-24 01:23:15.482 1339 1339 D EventLogger: loading [true]
9908-24 01:23:15.647 1339 9505 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.4D4029, video/avc] [OMX.google.h264.decoder, video/avc] [VSD242, st-tx3288-ah-00, TX, 22]
10008-24 01:23:15.647 1339 1339 D EventLogger: Tracks [
10108-24 01:23:15.647 1339 1339 D EventLogger: Renderer:0 [
10208-24 01:23:15.647 1339 1339 D EventLogger: Group:0, adaptive_supported=N/A [
10308-24 01:23:15.647 1339 1339 D EventLogger: ]
10408-24 01:23:15.647 1339 1339 D EventLogger: ]
10508-24 01:23:15.647 1339 1339 D EventLogger: Renderer:1 [
10608-24 01:23:15.647 1339 1339 D EventLogger: Group:0, adaptive_supported=N/A [
10708-24 01:23:15.647 1339 1339 D EventLogger: ]
10808-24 01:23:15.647 1339 1339 D EventLogger: ]
10908-24 01:23:15.647 1339 1339 D EventLogger: ]
11008-24 01:23:15.648 1339 9507 I OMXClient: Using client-side OMX mux.
11108-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.avc
11208-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.m4v
11308-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.h263
11408-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.flv1
11508-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.m2v
11608-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.rv
11708-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.vp8
11808-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.vc1
11908-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.wmv3
12008-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.vp6
12108-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.hevc
12208-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.mjpeg
12308-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.avc.secure
12408-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_decoder.vp9
12508-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_encoder.avc
12608-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: declares component OMX.rk.video_encoder.vp8
12708-24 01:23:15.728 1339 9507 I libstagefrighthw: OMX IL core libOMX_Core.so: contains 16 components
12808-24 01:23:15.729 1339 9507 D ACodec : MEDIA_MIMETYPE_AUDIO_AAC sampleRate 48000 wifidisplay_flag 0 info b83a3ac0
12908-24 01:23:15.731 1339 9508 I SoftAAC2: limiting to stereo output
13008-24 01:23:15.742 1339 9508 I SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
13108-24 01:23:15.753 1339 9505 I AudioTrack: minFrameCount: 4458, afFrameCount=1024, minBufCount=4, sampleRate=48000, afSampleRate=44100, afLatency=92
13208-24 01:23:15.802 1339 1339 D EventLogger: state [0.39, R]
13308-24 01:23:15.802 1339 1339 D EventLogger: state [0.40, true, I]
13408-24 01:23:15.821 1339 9512 I OMXClient: Using client-side OMX mux.
13508-24 01:23:15.825 1339 9512 E ACodec : [OMX.rk.video_decoder.avc] storeMetaDataInBuffers failed w/ err -1010
13608-24 01:23:15.946 1339 9512 F ACodec : frameworks/av/media/libstagefright/ACodec.cpp:5481 CHECK_EQ( mCodec->mOMX->fillBuffer(mCodec->mNode, info->mBufferID),(status_t)OK) failed: -2147483648 vs. 0
13708-24 01:23:16.764 1339 1353 I art : Background sticky concurrent mark sweep GC freed 57768(2MB) AllocSpace objects, 6(195KB) LOS objects, 0% free, 167MB/167MB, paused 797us total 553.827ms
13808-24 01:23:16.875 1339 1353 I art : Background partial concurrent mark sweep GC freed 4056(210KB) AllocSpace objects, 1571(97MB) LOS objects, 18% free, 70MB/86MB, paused 620us total 109.769ms

**Comment by CarGuo** [comment]
低版本定制设备问题自行处理

**Comment by itsgm** [comment]
> 低版本定制设备问题自行处理

大佬，麻烦问一下，这个应该从哪方面入手处理？从我代码层次入手，还是厂家系统层次入手处理。

**Comment by CarGuo** [comment]
MediaCodec 入手
