### ISSUE TITLE
8.3.4版本依赖问题

### ISSUE THREAD

**Issue by billsuki** [CarGuo/GSYVideoPlayer#3678]
**我的compileSdkVersion 和targetSdkVersion都是29 ，依赖了8.3.4版本后，然后build，就会出现以下问题**

One or more issues found when checking AAR metadata values:

Dependency 'androidx.appcompat:appcompat:1.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-29'

Dependency 'androidx.appcompat:appcompat-resources:1.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-29'

Dependency 'androidx.emoji2:emoji2-views-helper:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-29'

Dependency 'androidx.emoji2:emoji2:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-29'

Dependency 'androidx.media:media:1.4.3' requires 'compileSdkVersion' to be set to 30 or higher.
Compilation target for module ':app' is 'android-29'

Dependency 'androidx.core:core:1.7.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-29'

Dependency 'androidx.lifecycle:lifecycle-process:2.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-29'

Dependency 'androidx.lifecycle:lifecycle-runtime:2.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-29'

**因为项目要求，只能使用android-29不能升级到31**

然后我在build.gralde里面添加

configurations.all {
            resolutionStrategy { force 'androidx.appcompat:appcompat:1.3.0' }
        }
        
        

**问题减少了，但是还有部分问题**

One or more issues found when checking AAR metadata values:

Dependency 'androidx.media:media:1.4.3' requires 'compileSdkVersion' to be set to 30 or higher.
Compilation target for module ':app' is 'android-29'

Dependency 'androidx.core:core:1.7.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-29'

**Comment by CarGuo** [comment]
compileSdkVersion 升 30 ，targetSdkVersion 还是 29

![image](https://user-images.githubusercontent.com/10770362/187625126-43e46379-7e82-472a-a90a-420239c6c434.png)
