### ISSUE TITLE
视频播放黑屏

### ISSUE THREAD

**Issue by yzgt** [CarGuo/GSYVideoPlayer#3682]
## 问题描述：
使用的是EmptyControlVideo播放视频，在当前页打开新的activity, 然后返回，视频播放被中止并且黑屏

## 出现问题的视频流

普通mp4视频，http://file1.shpsz.cn/industry/62b93234e81b46918b0e0e758ec73bae.mp4

## 问题机型/系统：

所有机型

## GSY依赖版本

v8.2.0-release-jitpack

## Demo中的复现步骤

在当前页打开新的activity, 然后返回

问题代码：(如果有)

 @Override
    public void onPause() {
        super.onPause();
        videoPlay.onVideoPause();
    }

    @Override
    public void onResume() {
        super.onResume();
        videoPlay.onVideoResume();
    }

 videoPlay.setNeedOrientationUtils(false);
        videoPlay.setLooping(true);
        videoPlay.setVisibility(View.VISIBLE);
        videoPlay.startPlayLogic();
        videoPlay.setVideoAllCallBack(new GSYSampleCallBack() {
            @Override
            public void onPrepared(String url, Object... objects) {
                super.onPrepared(url, objects);
                //开始播放了才能旋转和全屏
//                ivTopBg.setVisibility(View.GONE);
//                videoPlay.setVisibility(View.VISIBLE);
            }
        });

**Comment by CarGuo** [comment]
没有复现
