### ISSUE TITLE
8.3.4-release版本的exo引入会导致camerax的库的出错

### ISSUE THREAD

**Issue by lodgkk** [CarGuo/GSYVideoPlayer#3685]
出错的信息:Cannot access class 'com.google.common.util.concurrent.ListenableFuture'. Check your module classpath for missing or conflicting dependencies,去掉引入exo恢复正常

**Comment by CarGuo** [comment]
那不属于 GSY 问题

**Comment by lodgkk** [comment]
exo的版本能控制吗

**Comment by CarGuo** [comment]
你可以自己 gradle exclude 或者 force  自己要的版本
