### ISSUE TITLE
setUp方法问题

### ISSUE THREAD

**Issue by liuhuicheng** [CarGuo/GSYVideoPlayer#3688]
## 问题描述：

setUp方法中的 cacheWithPlay 参数为 false的时候 视频播放失败,ture的时候可以播放 ，但是拖动进度条会有问题

## 出现问题的视频流

 MP4格式的腾讯云链接  内部链接不方便放出来

## 问题机型/系统：

华为p30

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack

## 问题log（如果有）

tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by CarGuo** [comment]
没有链接我也不知道

**Comment by liuhuicheng** [comment]
内部链接 实在抱歉不能放出来，昨天又调试了下  内部网络情况下有这个问题，切换网络之后解决了。
内部网络情况下 ，cacheWithPlay 为true 是下载到本地播放的本地视频，所有才会有上面的问题，也就是说内部网络可以下载但是不能在线播放，但是我比较困惑的是ios是可以在线播放的

**Comment by xiuyuantech** [comment]
https://v7.dious.cc/share/t7UAbByhy15KAQoc 像这种链接视频也无法播放，但是在浏览器中可以

**Comment by CarGuo** [comment]
@xiuyuantech  大哥，你确定你这个不是一个网页？？？？？？？都是 DPlayer 了······

![image](https://user-images.githubusercontent.com/10770362/190049462-095ecde3-acf7-4395-aa5a-3f45adf62782.png)

**Comment by CarGuo** [comment]
> 内部链接 实在抱歉不能放出来，昨天又调试了下 内部网络情况下有这个问题，切换网络之后解决了。
> 内部网络情况下 ，cacheWithPlay 为true 是下载到本地播放的本地视频，所有才会有上面的问题，也就是说内部网络可以下载但是不能在线播放，但是我比较困惑的是ios是可以在线播放的

具体我也不好猜， 有没有可能是SSL证书问题？
