### ISSUE TITLE
关于进度条跳动的问题

### ISSUE THREAD

**Issue by lybill** [CarGuo/GSYVideoPlayer#3689]
`
val videoOptionModel =
                VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1)
            val list: MutableList<VideoOptionModel> = ArrayList()
            list.add(videoOptionModel)
            GSYVideoManager.instance().optionModelList = list
`

我是默认的ijkplayer，并且这个代码我是设置了，但是在拖动进度条的时候，还是会往后回退一帧左右，但是在surfaceview滑动修改进度的时候，为什么就没有这个回退的问题？照理说，这是同样都是通过seekTo方法来修改视频进度的？

**Comment by CarGuo** [comment]
surfaceview滑动和进度条滑动调用接口一样啊，唯一不同的可能是输入参数的区别？？

**Comment by billsuki** [comment]
> surfaceview滑动和进度条滑动调用接口一样啊，唯一不同的可能是输入参数的区别？？


https://user-images.githubusercontent.com/13043256/191160706-d361645c-1781-4710-a275-cbd5e347afa3.mp4

我也没有理解是为什么会有这个问题，这是我测试的视频的link：https://vd4.bdstatic.com/mda-ji0a03qgr6ythc43/v1-cae/sc/mda-ji0a03qgr6ythc43.mp4

**Comment by chaopengTan** [comment]
我也遇到了这个问题，我采用切换内核模式来解决，你或许可以试试
PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
