### ISSUE TITLE
同时播放 每次打开直播流都不是最新的直播流 是上次看过的时间

### ISSUE THREAD

**Issue by pengjunshan** [CarGuo/GSYVideoPlayer#3699]
同时播放  1.每次打开直播流都不是最新的 是上次看过的时间；2.播放时暂停 然后点击全屏后是黑屏

**Comment by CarGuo** [comment]
1、不理解，播放器没有做多余处理
2、setShowPauseCover true

**Comment by pengjunshan** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月21日(星期五) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] 同时播放 每次打开直播流都不是最新的直播流 是上次看过的时间 (Issue #3699)





 
1、不理解，播放器没有做多余处理
 2、setShowPauseCover true
