### ISSUE TITLE
GSYVideoManager类里IjkMediaPlayer对象问题

### ISSUE THREAD

**Issue by zhongyuanwu** [CarGuo/GSYVideoPlayer#37]
GSYVideoManager类里IjkMediaPlayer对象在构造方法中生成了一次，为什么还要在initIJKPlayer（）方法里在new一次，不这样还不能播放视频，为什么

**Comment by CarGuo** [comment]
构造方法里的其实并没有怎么用到，实际上是init的那个才是用到的，这样也可以方便释放视频的状态，方便管理吧，外带还能支持切换播放器的类型。

**Comment by zhongyuanwu** [comment]
但是我测试了 在init方法里 IjkMediaPlayer对象已经有了，如果这么说，可以把构造方法里的去掉吗

**Comment by CarGuo** [comment]
是的，如果你需要去掉的话
