### ISSUE TITLE
v8.1.3-jitpack JitPack status error，Could not build

### ISSUE THREAD

**Issue by FengYuanBiao** [CarGuo/GSYVideoPlayer#3700]

**Comment by CarGuo** [comment]
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-proxy_cache:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-x86:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-x86_64:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-base:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv64:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv5:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:8.1.3-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:8.1.3-jitpack
