### ISSUE TITLE
仿抖音视频播放

### ISSUE THREAD

**Issue by nizhege** [CarGuo/GSYVideoPlayer#3702]
## 如题

```
郭神，想做一个仿抖音的播放页面，怎么设置点击屏幕就暂停，再点击就播放，下方进度条怎么可以一直显示秒数不显示缩略进度条呢，打扰了

```

**Comment by CarGuo** [comment]
override getLayoutId 和 onClickUiToggle 、touchDoubleUp

**Comment by nizhege** [comment]
> override getLayoutId 和 onClickUiToggle 、touchDoubleUp

好的 我去试试 感谢指导！
