### ISSUE TITLE
从ijk 切换到 aliplayer播放器后，本地视频播放异常

### ISSUE THREAD

**Issue by check0927** [CarGuo/GSYVideoPlayer#3704]
从ijk 切换到 aliplayer播放器后，本地视频播放异常
Link Or mCache Error, Please Try Again android.resource://com.***.***/2131755031

**Comment by CarGuo** [comment]
aliplayer 目前应该不支持 raw 播放

**Comment by check0927** [comment]
那如果要播放本地视频有其他方式支持吗？

**Comment by check0927** [comment]
> aliplayer当前应该不支持原始播放


那如果要播放本地视频有其他方式支持吗？

**Comment by CarGuo** [comment]
具体看阿里云播放器文档
