### ISSUE TITLE
CommonUtil类的scanForActivity()方法，有些使用场景不一定是在Activity中，使用此方法会报空指针

### ISSUE THREAD

**Issue by Leney** [CarGuo/GSYVideoPlayer#3706]
目前我使用的场景是：在Service中开启副屏 Presentation
调用到GsyBaseVideoPlayer类中的getCurrentPlayer()方法，进而调用getFullWindowPlayer()，使用到了CommonUtil类的scanForActivity()方法：
![image](https://user-images.githubusercontent.com/9280041/200545618-066a4273-a7ff-4844-a6c3-a88fa553ea06.png)

不过我的问题目前是通过这样调解决了：
![image](https://user-images.githubusercontent.com/9280041/200545799-0512f8e9-6f07-48f8-a613-095d3c161e00.png)

仅仅是来反馈下这个问题，^_^!!

**Comment by Leney** [comment]
补一下报错信息
![image](https://user-images.githubusercontent.com/9280041/200546996-917f34ae-b042-41b2-b7bf-cd2e82fc3d1e.png)

**Comment by Leney** [comment]
版本：8.1.2

**Comment by CarGuo** [comment]
如下图，不是应该有这个判断么？
<img width="797" alt="image" src="https://user-images.githubusercontent.com/10770362/200775100-9820bec0-c919-44ca-997f-5423e9471b91.png">
