### ISSUE TITLE
Could not find GSYVideoPlayer-aliplay-v8.3.4-release-jitpack.aar 

### ISSUE THREAD

**Issue by ZhuSky** [CarGuo/GSYVideoPlayer#3708]
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/18596232/201159309-949deba8-438b-452f-b94a-30c908f3d6a4.png">
为啥拉取不到ali 的这个包了？

**Comment by CarGuo** [comment]
alipay 需要用这个 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-aliplay:8.3.4-release-jitpack' ，不知道为什么 jitpack 又抽风了

**Comment by ZhuSky** [comment]
api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'
    //是否需要ExoPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.4-release-jitpack'
    //更多ijk的编码支持
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.4-release-jitpack'
    
    
    @CarGuo 这些也都要换嘛？

**Comment by CarGuo** [comment]
只换alipay就好了
