### ISSUE TITLE
使用Aliplayer 日志中出现需要license的日志

### ISSUE THREAD

**Issue by check0927** [CarGuo/GSYVideoPlayer#3709]
+-----------------------------------------------------------------------------------------------+
                                                                                                    |---------------------------------- license is invalid!!! --------------------------------------|
                                                                                                    |---------------------- Please provide correct license key before play, ------------------------|
                                                                                                    |------ you can visit 'https://help.aliyun.com/document_detail/434250.html' for more info. -----|
                                                                                                    +-----------------------------------------------------------------------------------------------+

**Comment by check0927** [comment]
是不是需要去购买阿里云播放器的收费包？
不购买的话能正常使用Aliplayer的播放器吗？

**Comment by CarGuo** [comment]
我记得阿里云播放器确是需要 license ，主要就是对应阿里云流服务，有流服务就有 license ，需不需要付费就不大清楚了

**Comment by zohaibmushwani** [comment]
AliFrameWork             I  [30103293] [] :Ffmpeg version v4.3.1.7.2
AliFrameWork             W  [30103293] [PlayerJNI] :JNI_OnLoad
aio_stat                 I  Aio_stat_JNI_OnLoad [env: -1683749696]
AliFrameWork             I  [30103293] [analytics] :mReporter:0x7f77f80260
AliFrameWork             W  [30103293] [licenseManager] :NoDefaultLicense
AliFrameWork             I  [30103293] [] :setWorkPath :/data/app/com.mashwani.curveview-2/lib/arm64/
aio_stat                 I  AioStat SetApplicationContext [context: -540828328]
AliFrameWork             W  [30103293] [cloud_config_manager] :cloud config request: appid=com.mashwani.curveview, sdk_version=5.5.6.0, brand_name=OPPO, device_name=android, os_version=7.1.1, device_id=e354ef0dd985436babffbc044d098f44, network_type=2
AliFrameWork             I  [30103293] [analytics] :mReporter:0x7f77f80ec0
AliFrameWork             I  [30103293] [crashMonitor] :crash monitor allow capture : 1
AliFrameWork             I  [30103293] [crashMonitor] :crashMonitor iTraceId : aliyun-player-sdk, crashDir : /storage/emulated/0/Android/data/com.mashwani.curveview/cache/crashdir, sdkVersion : 5.5.6.0, sdkBuildId : 30103293, sdkBuildTime : 230531113533
AliFrameWork             I  [30103293] [analytics] :mReporter:0x7f77f81100
AliFrameWork             I  [30103293] [analytics] :eventCode:5007, name: string:ci_av * 1.0 *||* ci_bi * 30103293 *||* ci_bt * 230531113533 *||* ci_ii * aliyun-player-sdk *||* ci_st * player-standard *||* ci_sv * 5.5.6.0 ret:0
AliFrameWork             I  [30103293] [AVPBase] :API_IN:setConvertURLCb
AliFrameWork             I  [30103293] [NativeBase] :java_SetLoop(0)
AliFrameWork             I  [30103293] [AVPBase] :API_IN:SetLoop 0
AliFrameWork             I  [30103293] [JavaJniUrlPlayer] :java_SetDataSource_UrlSource(/data/user/0/com.mashwani.curveview/files//data/user/0/com.mashwani.curveview/temp/input2131820553.mp4)
AliFrameWork             I  [30103293] [NativeBase] :java_Prepare()
AliFrameWork             I  [30103293] [AVPBase] :API_IN:prepareActually
AliFrameWork             I  [30103293] [analytics] :eventCode:1003, name:GET_URL string:it * urlsource *||* pa * {"bitstream":""} ret:0
AliFrameWork             I  [30103293] [licenseManager] :license check sdk start
AliFrameWork             E  [30103293] [licenseManager] :Please provide correct license key before play, you can visit 'https://help.aliyun.com/document_detail/434250.html' for more info.
AliFrameWork             E  [30103293] [AVPBase] :license check failed when prepare
AliFrameWork             W  [30103293] [AVPBase] :API_OUT:sendVodError 536948736: license authorization failed, you can visit 'https://help.aliyun.com/document_detail/434250.html' for more info.
libc-netbsd              D  [getaddrinfo]:  hostname=cloud-config-service.rtc.aliyuncs.com;  servname=443;  app_pid=11079;  app_uid=10474;  ai_flags=0;  ai_family=0; ai_socktype=1 from prox result 0
AliFrameWork             I  [30103293] [analytics] :eventCode:4001, name:ERROR string:encryption_info * {"keyUrl":""} *||* error_code * 20013000 *||* error_msg * license authorization failed, you can visit 'https://help.aliyun.com/document_detail/434250.html' for more info. *||* rsi *  *||* vt * -1 ret:0
AliFrameWork             I  [30103293] [NativeBase] :AliyunCorePlayer callback --> StatusChanged(7)
AliFrameWork             E  [30103293] [NativeBase] :AliyunCorePlayer callback --> VodErrorCallback(536948736, license authorization failed, you can visit 'https://help.aliyun.com/document_detail/434250.html' for more info.) requestid =  
AliFrameWork             E  [30103293] [SaasErrorCodeMap] :not mapped errorCode : 536948736 
AliFrameWork             I  [30103293] [NativeBase] :java_SetView(0x0)
AliFrameWork             I  [30103293] [AVPBase] :API_IN:SetView 0x0
AliFrameWork             I  [30103293] [NativeBase] :java_Stop()
AliFrameWork             I  [30103293] [AVPBase] :API_IN:Stop
AliFrameWork             I  [30103293] [analytics] :eventCode:2012, name:STOP string:abr_info *  *||* cost * 1699332141834 *||* stream_info *  *||* vdi * [] *||* vt * -1 ret:0
AliFrameWork             I  [30103293] [NativeBase] :java_Release()
AliFrameWork             I  [30103293] [AVPBase] :API_IN:Stop
AliFrameWork             I  [30103293] [AVPBase] :API_IN:Stop
AliFrameWork             I  [30103293] [] :player count 0
AliFrameWork             I  [30103293] [AVPBase] :~AVPBase 0x7f78106c00 cost 0
libc-netbsd              D  [getaddrinfo]:  hostname=videocloud.cn-hangzhou.log.aliyuncs.com;  servname=443;  app_pid=11079;  app_uid=10474;  ai_flags=0;  ai_family=0; ai_socktype=1 from prox result 0
