### ISSUE TITLE
有部分用户画面倒置

### ISSUE THREAD

**Issue by kiddkyd1412** [CarGuo/GSYVideoPlayer#3711]
## 问题描述：

用的是exo2内核，开发的是一个tv端的app，100个用户中，有3个左右，出现视频倒置（弹幕没倒置）的现象。
不知有没有简单的处理方案？没的话，只能加一个旋转功能给用户手动设置。

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.4-release-jitpack'

**Comment by CarGuo** [comment]
我猜没有

**Comment by renwfy** [comment]
https://user-images.githubusercontent.com/6526280/223317034-fc0658d3-008b-4c6c-b3d0-f195ef63fc43.mp4
