### ISSUE TITLE
View或者Activity转成Bitmap问题

### ISSUE THREAD

**Issue by pengjunshan** [CarGuo/GSYVideoPlayer#3712]
View中包含咱的视频播放器，View转Bitmap后，图片中的视频为空白

**Comment by CarGuo** [comment]
因为 surfaceview 和 textureView 啊·····

**Comment by pengjunshan** [comment]
那有办法可以解决吗 截图获取bitmap




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月22日(星期二) 上午10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer] View或者Activity转成Bitmap问题 (Issue #3712)





 
因为 surfaceview 和 textureView 啊·····

**Comment by CarGuo** [comment]
Player.taskShotPic
