### ISSUE TITLE
关于文件格式的支持

### ISSUE THREAD

**Issue by GHHMBird** [CarGuo/GSYVideoPlayer#3715]
经过本人测试，目前发现播放视频rmvb，wmv格式文件的时候无法正常播放，播放音频wav，mid格式的时候无法正常播放，不知道是我是用的有问题还是目前还没兼容这些格式呢？我使用的是PlayerFactory.setPlayManager(IjkPlayerManager::class.java)这个内核

**Comment by GHHMBird** [comment]
当然，目前发现能支持的格式也很多，视频支持：mp4,mkv,flv,mov,avi;音频支持mp3,m4a,flac,aac

**Comment by CarGuo** [comment]
在这：
https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh
https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite.sh
