### ISSUE TITLE
弹幕的demo希望作者能完善一下，有个小bug

### ISSUE THREAD

**Issue by kiddkyd1412** [CarGuo/GSYVideoPlayer#3719]
由于当前弹幕的demo，弹幕是一准备好，就输出的，并不会等待视频开始。
如果视频不是自动播放，而是需要点击开始的话。这时候弹幕就会提前出现。
至于为什么demo里看不出弹幕提前出现，那是因为layout里，弹幕组件的下面是一个黑色全屏大小的组件，因此弹幕被遮挡了。如果按了格式化代码的话，layout会重新排列组件的顺序，就会发现这个问题。

希望作者可以完善一下，在视频播放后，再start弹幕。（尝试过自己改动demo，但是技术比较渣，搞不成 -_-||）

**Comment by CarGuo** [comment]
弹幕 demo 问题可以直接去官方的 github 那边咨询～～，我这边只是提供一个小小的实例展示
