### ISSUE TITLE
ios视频分辨率倒置 导致的视频竖屏播放时宽高计算异常

### ISSUE THREAD

**Issue by d342784178** [CarGuo/GSYVideoPlayer#372]
现象:
ios录制的视频分辨率倒置 但在qq,ios中均正常播放 
但是在android使用框架竖屏播放时 出现显示异常 具体就是宽高计算不正确
![image](https://user-images.githubusercontent.com/10826372/29323337-2b8a9e82-8213-11e7-9390-0ce70cdfeb8d.png)
这个是视频链接：https://zh-files.oss-cn-qingdao.aliyuncs.com/20170808223928mJ1P3n57.mp4

分析:
当播放ios的视频
而且当播放ios视频时 由于rotation=90 导致GSYTextureView的onMeasure的宽高也倒转了
举个例子 手机分辨率是1080*1920  当为竖屏时 由于rotation=90 此时onMeasure的宽高变为了1920*1080 导致视频显示异常
而当手机横屏时 由于此时手机分辨率也变为1920*1080 此时视频显示正常
原因:
rotation属性有其本身的含义 而视频的rotation应该独立一个属性 而不是通过手动修改view的rotation属性

![image](https://user-images.githubusercontent.com/10826372/29323259-ec28b58a-8212-11e7-91fb-33654f14f420.png)

**Comment by CarGuo** [comment]
不是很理解你说的，视频的旋转属性需要修改view来适应是因为渲染的底层没处理所以需要顶层处理，ijk需开启硬解码会在底层处理。而且这个url目前2.0.4demo中播放正常

**Comment by CarGuo** [comment]
![screenshot_2017-08-16-08-46-55-124_com example gsyvideoplayer](https://user-images.githubusercontent.com/10770362/29342840-cf519740-825f-11e7-8ca5-7fea03618f14.png)
并没有发现异常

**Comment by d342784178** [comment]
你竖屏试过吗? ios录制的视频比如是480*640的 使用框架播放就会出现宽高不正常

**Comment by CarGuo** [comment]
没发现有问题

**Comment by d342784178** [comment]
需要特殊的设置吗 你说要开硬解码是吗?
我在使用的时候出现了这种问题 可能是哪里的原因?

**Comment by wonxll** [comment]
我也遇到这个问题。。手机竖着，然后视频是横着的（1280 * 720）播放的时候，宽高是正方形的。。。

**Comment by CarGuo** [comment]
@wonxll 请提供url
