### ISSUE TITLE
关于导包版本号冲突问题

### ISSUE THREAD

**Issue by pichsy** [CarGuo/GSYVideoPlayer#3720]
此库

    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'

引入后一直提报错
报错1：
The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
Dependency: androidx.appcompat:appcompat:1.4.0.
报错2：
Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/sywub/.gradle/caches/transforms-2/files-2.1/b15ce0b1a4e79d15b42adb0a05cd5845/jetified-kotlin-stdlib-jdk8-1.6.21.jar (version 1.6)
    C:/Users/sywub/.gradle/caches/transforms-2/files-2.1/654363f46b29a1a5faa64dad57e52e90/jetified-kotlin-stdlib-jdk7-1.6.21.jar (version 1.6)
    C:/Users/sywub/.gradle/caches/transforms-2/files-2.1/5ef7c9c0b21635605896e2adc420e7f4/jetified-kotlin-reflect-1.5.20.jar (version 1.5)
    C:/Users/sywub/.gradle/caches/transforms-2/files-2.1/d8cb8c42be27c780e0f1985e94aa3607/jetified-kotlin-stdlib-1.6.21.jar (version 1.6)
    C:/Users/sywub/.gradle/caches/transforms-2/files-2.1/9fcbbab06486622138fc2cca5d1b180c/jetified-kotlin-stdlib-common-1.6.21.jar (version 1.6)

去掉 后项目就能运行
我项目中
 androidx库版本
 api 'androidx.appcompat:appcompat:1.3.1'
 api  "androidx.core:core-ktx:1.6.0"
 kotlin版本 ext.kotlin_version = "1.5.10"
 
希望不要强制我更新到最新库，会引起项目其他不兼容问题。
希望 上传maven时去掉  其对androidx系列 库的强制引用

**Comment by CarGuo** [comment]
需要 compileSdkVersion 31 ，如图

![image](https://user-images.githubusercontent.com/10770362/205533658-39045d66-6672-49db-80c1-943140e4f6b8.png)

![image](https://user-images.githubusercontent.com/10770362/205533646-d3fb45c9-8bdd-4c40-9ffe-aa9547a830eb.png)


Dependency 的版本问题你可以自己依赖时 exclude
