### ISSUE TITLE
打包后报错

### ISSUE THREAD

**Issue by AndersonCodeArt** [CarGuo/GSYVideoPlayer#3727]
打包后出现以下错误：

![image](https://user-images.githubusercontent.com/76779830/209774208-aee9f656-b604-472a-8d3a-6e50d4707200.png)

**Comment by AndersonCodeArt** [comment]
runtime.cc:669] Runtime aborting...
                                                                                                    runtime.cc:669] Dumping all threads without mutator lock held
                                                                                                    runtime.cc:669] All threads:
                                                                                                    runtime.cc:669] DALVIK THREADS (100):
                                                                                                    runtime.cc:669] "main" prio=10 tid=1 Runnable
                                                                                                    runtime.cc:669]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x7172a4e8 self=0xb400007487e9bc00
                                                                                                    runtime.cc:669]   | sysTid=11486 nice=-10 cgrp=default sched=0/0 handle=0x752c74f4f8
                                                                                                    runtime.cc:669]   | state=R schedstat=( 1709953066 63608480 1881 ) utm=142 stm=28 core=7 HZ=100
                                                                                                    runtime.cc:669]   | stack=0x7fea323000-0x7fea325000 stackSize=8188KB
                                                                                                    runtime.cc:669]   | held mutexes= "abort lock" "mutator lock"(shared held)
                                                                                                    runtime.cc:669]   native: #00 pc 000000000056a79c  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+144)
                                                                                                    runtime.cc:669]   native: #01 pc 0000000000685a48  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+368)
                                                                                                    runtime.cc:669]   native: #02 pc 00000000006a3e7c  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+924)
                                                                                                    runtime.cc:669]   native: #03 pc 000000000069da0c  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+520)
                                                                                                    runtime.cc:669]   native: #04 pc 000000000069cc10  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1468)
                                                                                                    runtime.cc:669]   native: #05 pc 00000000006352b8  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2204)
                                                                                                    runtime.cc:669]   native: #06 pc 0000000000016bc4  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+80)
                                                                                                    runtime.cc:669]   native: #07 pc 0000000000016184  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+368)
                                                                                                    runtime.cc:669]   native: #08 pc 0000000000458898  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2524)
                                                                                                    runtime.cc:669]   native: #09 pc 000000000048b900  /apex/com.android.art/lib64/libart.so (art::JNI<false>::GetFieldID(_JNIEnv*, _jclass*, char const*, char const*)+1400)
                                                                                                    runtime.cc:669]   native: #10 pc 0000000000188208  /data/app/~~H9N3jk0XRRnIapav2jYOMQ==/com.chan.cwallpaper-pj7eEL-6tjdKPWyQQFmzcg==/lib/arm64/libsaasCorePlayer.so (JavaCacheConfig::init(_JNIEnv*)+136)
                                                                                                    runtime.cc:669]   native: #11 pc 0000000000181eb0  /data/app/~~H9N3jk0XRRnIapav2jYOMQ==/com.chan.cwallpaper-pj7eEL-6tjdKPWyQQFmzcg==/lib/arm64/libsaasCorePlayer.so (initJavaInfo(_JNIEnv*)+40)
                                                                                                    runtime.cc:669]   native: #12 pc 000000000018228c  /data/app/~~H9N3jk0XRRnIapav2jYOMQ==/com.chan.cwallpaper-pj7eEL-6tjdKPWyQQFmzcg==/lib/arm64/libsaasCorePlayer.so (JNI_OnLoad+80)
                                                                                                    runtime.cc:669]   native: #13 pc 000000000045c754  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+3120)
                                                                                                    runtime.cc:669]   native: #14 pc 00000000000051fc  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+424)
                                                                                                    runtime.cc:669]   at java.lang.Runtime.nativeLoad(Native method)
                                                                                                    runtime.cc:669]   at java.lang.Runtime.nativeLoad(Runtime.java:1121)
                                                                                                    runtime.cc:669]   at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
                                                                                                    runtime.cc:669]   - locked <0x03b4f377> (a java.lang.Runtime)
                                                                                                    runtime.cc:669]   at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    runtime.cc:669]   at java.lang.System.loadLibrary(System.java:1656)
                                                                                                    runtime.cc:669]   at com.aliyun.utils.NativeLoader.a(NativeLoader.java:17)
                                                                                                    runtime.cc:669]   - locked <0x0b441be4> (a java.lang.Class<com.aliyun.utils.NativeLoader>)
2022-12-28 15:25:25.262 11486-11486 chan.cwallpape          pid-11486                            A  runtime.cc:669]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
                                                                                                    runtime.cc:669]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
                                                                                                    runtime.cc:669]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    runtime.cc:669]   at java.lang.Thread.run(Thread.java:920)
                                                                                                    runtime.cc:669] 
                                                                                                    runtime.cc:669] "CrashSDKNormalHandler" prio=5 tid=71 Native
                                                                                                    runtime.cc:669]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x15193f10 self=0xb4000073ccfa5800
                                                                                                    runtime.cc:669]   | sysTid=11635 nice=0 cgrp=default sched=0/0 handle=0x73bf740cb0
                                                                                                    runtime.cc:669]   | state=S schedstat=( 1149843 1262709 13 ) utm=0 stm=0 core=4 HZ=100
                                                                                                    runtime.cc:669]   | stack=0x73bf63d000-0x73bf63f000 stackSize=1039KB
                                                                                                    runtime.cc:669]   | held mutexes=
                                                                                                    runtime.cc:669]   native: #00 pc 00000000000dbd3c  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+12)
                                                                                                    runtime.cc:669]   native: #01 pc 0000000000017ea8  /system/lib64/libutils.so (android::Looper::pollInner(int)+184)
                                                                                                    runtime.cc:669]   native: #02 pc 0000000000017d84  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116)
                                                                                                    runtime.cc:669]   native: #03 pc 0000000000154680  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48)
                                                                                                    runtime.cc:669]   at android.os.MessageQueue.nativePollOnce(Native method)
                                                                                                    runtime.cc:669]   at android.os.MessageQueue.next(MessageQueue.java:340)
                                                                                                    runtime.cc:669]   at android.os.Looper.loopOnce(Looper.java:168)
                                                                                                    runtime.cc:669]   at android.os.Looper.loop(Looper.java:299)
                                                                                                    runtime.cc:669]   at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    runtime.cc:669] 
                                                                                                    runtime.cc:669] "CrashSDKBkgdHandler" prio=4 tid=72 Native
                                                                                                    runtime.cc:669]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x15193ff8 self=0xb4000073ccfa7400
                                                                                                    runtime.cc:669]   | sysTid=11636 nice=10 cgrp=default sched=0/0 handle=0x73bf636cb0
                                                                                                    runtime.cc:669]   | state=S schedstat=( 23025570 3786044 39 ) utm=1 stm=0 core=5 HZ=100
                                                                                                    runtime.cc:669]   | stack=0x73bf533000-0x73bf535000 stackSize=1039KB
                                                                                                    runtime.cc:669]   | held mutexes=
                                                                                                    runtime.cc:669]   native: #00 pc 00000000000dbd3c  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+12)
                                                                                                    runtime.cc:669]   native: #01 pc 0000000000017ea8  /system/lib64/libutils.so (android::Looper::pollInner(int)+184)
                                                                                                    runtime.cc:669]   native: #02 pc 0000000000017d84  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116)
                                                                                                    runtime.cc:669]   native: #03 pc 0000000000154680  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48)
                                                                                                    runtime.cc:669]   at android.os.MessageQueue.nativePollOnce(Native method)
                                                                                                    runtime.cc:669]   at android.os.MessageQueue.next(MessageQueue.java:340)
                                                                                                    runtime.cc:669]   at android.os.Looper.loopOnce(Looper.java:168)
                                                                                                    runtime.cc:669]   at android.os.Looper.loop(Looper.java:299)
                                                                                                    runtime.cc:669]   at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    runtime.cc:669]

**Comment by CarGuo** [comment]
非gsy问题
