### ISSUE TITLE
提一个小bug

### ISSUE THREAD

**Issue by panzhenglian** [CarGuo/GSYVideoPlayer#3728]
GSYVideoView 类中的 setUp(String url, boolean cacheWithPlay, File cachePath, Map<String, String> mapHeadData, String title) 方法，是播放点击时，prepareVideo()自动触发的,但是在 prepareVideo()方法中，将  this.mMapHeadData 传入了setUp 方法中，
setUp 方法中，将this.mMapHeadData.clear(),同时又操作 this.mMapHeadData.addAll(mapHeadData),这样做没有任何意义，因为他们是持有的同一个对象引用，导致 head必然被清空，代码改动很小，我已经在本地改动了。

**Comment by CarGuo** [comment]
setUpLazy 才回会 prepareVideo 时的 setUp 操作吧？ setUpLazy 已经弃用了其实

<img width="641" alt="image" src="https://user-images.githubusercontent.com/10770362/210289576-7dc5724e-51f6-4cea-808a-63029b6b41e4.png">
