### ISSUE TITLE
获取传感器的目的是什么？

### ISSUE THREAD

**Issue by swanfly** [CarGuo/GSYVideoPlayer#3729]
隐私合规检测不通过，提示：APP向用户明示SDK的收集使用规则，但未见清晰明示GSYVideoPlayer,fb.j.initVideoPlayer,md.e.onClick获取传感器等的目的方式范围，用户同意隐私政策后，SDK存在GSYVideoPlayer,fb.j.initVideoPlayer,md.e.onClick获取传感器的行为。
<img width="866" alt="image" src="https://user-images.githubusercontent.com/5317370/209791671-293adab8-4caf-41fe-b4c9-19095a7b0a4c.png">

**Comment by CarGuo** [comment]
屏幕旋转啊
