### ISSUE TITLE
按Home键切B站问题

### ISSUE THREAD

**Issue by tanghongxiang** [CarGuo/GSYVideoPlayer#373]
视频播放中的时候按Home键切到B站播放视频，再切回己应用，怎么让他继续播放呢？

**Comment by CarGuo** [comment]
有对应继续播放接口，参考demo

**Comment by tanghongxiang** [comment]
恩，我试了，那个继续播放的方法是暂停状态才继续播放，我看从B站切回来后播放状态是0，没有走继续播放代码，强制继续播放直接就报错了，我看demo是重头播放。。
