### ISSUE TITLE
MeasureHelper可能的一个逻辑error

### ISSUE THREAD

**Issue by may7be** [CarGuo/GSYVideoPlayer#3731]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

![image](https://user-images.githubusercontent.com/24719809/210052878-2b1ba501-0db2-4764-bce5-e9214c602df0.png)
这块displayAspectRatio是不是sar计算重复了？

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
  default:
                        displayAspectRatio = (float) realWidth / (float) mVideoHeight;
                        if (mVideoSarNum > 0 && mVideoSarDen > 0)
                            displayAspectRatio = displayAspectRatio * mVideoSarNum / mVideoSarDen;
                        break;
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
这部分是在 shouldBeWider 生效的时候， realWidth 和 widthSpecSize 去做一个 min ，而 displayAspectRatio 是另外一个计算

**Comment by CarGuo** [comment]
你主要看 realWidth 和 displayAspectRatio 的使用位置就行了

**Comment by may7be** [comment]
行吧，我先fork下。
