### ISSUE TITLE
个别Android系统 直接使用Path 作为地址时 SystemPlayer 无法播放

### ISSUE THREAD

**Issue by YanJkCode** [CarGuo/GSYVideoPlayer#3732]
## 问题描述：
   个别Android系统 直接使用相对路径比如 /storage/emulated/0/video/测试视频.mp4  的路径时会出现无法访问文件 No content provider 但是 实际问题和这个报错没有关系 
   自己使用系统播放器测试  如果使用
            Uri uri = Uri.parse("file://" + videoInfo.getPath());
            videoView.setVideoURI(uri);
   可以正常的播放视频

   如果使用   videoView.setVideoPath( videoInfo.getPath() );  或  videoView.setVideoPath( "file://" + videoInfo.getPath() ); 
   均无法播放视频
   项目需要  只能使用系统播放器
   请问有什么可以解决这个问题的办法吗? 或有什么办法可以直接使用Uri进行路径解析吗?

## 问题机型/系统：

   Lenovo投影仪 小新T100

## GSY依赖版本
    使用了2种版本去测试这个问题 都没法解决
    刚开始使用的版本:
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack'
    之后使用的版本:
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack'

**Comment by CarGuo** [comment]
用  SAF 路径打开播放试试
