### ISSUE TITLE
局部高斯模糊

### ISSUE THREAD

**Issue by nealqpl** [CarGuo/GSYVideoPlayer#3734]
## 问题描述：
             可以做到局部区域高斯模糊吗？比如我只想横屏模式下模糊底部宽度铺满高度60dp的区域
     
## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'

**Comment by CarGuo** [comment]
自己改改demo 的 GL 例子
