### ISSUE TITLE
EXO内核m3u8格式视频播放到无音频数据的位置时画面暂停

### ISSUE THREAD

**Issue by windseamless** [CarGuo/GSYVideoPlayer#3736]
## 问题描述：
     EXO内核m3u8格式视频播放到无音频数据的位置时画面暂停
     说明： 由于项目支持静音录制功能，当开启后，本地视频录制时不会打包音频数据到ts，然后将带有音频数据的ts和无音频数据的ts上传到云端，app拿到这些混合ts生成的m3u8地址播放时，有音频的部分可以正常播放，当播放到无音频数据的位置时，播放就自动停止了。

## 出现问题的视频流
     本地录制的，不方便提供

## 问题机型/系统：
     所有设备

## GSY依赖版本

implementation ‘com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack’

**Comment by CarGuo** [comment]
不支持

**Comment by windseamless** [comment]
> 不支持

是否可以通过修改源码的方式使其支持呢？目前尝试修改后仍未解决，如能修改望指点下该从哪里入手呢

**Comment by CarGuo** [comment]
EXO 内核的核心之一是 MediaCodec  ，所以除非你修改 Framework ，或者给 Exo 接入 FFmpeg 实现，不然 Exo 上没什么修改的可能，推测可能和解码时的同步时钟有关系，同步时钟用的是音频编码。
