### ISSUE TITLE
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-jitpack' 引用失败

### ISSUE THREAD

**Issue by Andjdd** [CarGuo/GSYVideoPlayer#3737]
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-jitpack'  安装失败 
        <com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer
            android:id="@+id/detail_player"
            android:layout_width="match_parent"
            android:layout_height="@dimen/post_media_height" /> 这个没法引用

**Comment by CarGuo** [comment]
缺少log

**Comment by Andjdd** [comment]
574808086
***@***.***



&nbsp;KotlinDslScriptsParameter(correlationId=32949568183000, scriptFiles=[]) =&gt; StandardKotlinDslScriptsModel(scripts=[], commonModel=CommonKotlinDslScriptModel(classPath=[], sourcePath=[], implicitImports=[]), dehydratedScriptModels={}) - took 0.001 secs






   
Failed to resolve: com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.3-jitpack Show in Project Structure dialog Affected Modules: app 







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月10日(星期二) 晚上6:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer]     implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-jitpack' 引用失败 (Issue #3737)





 
缺少log

**Comment by CarGuo** [comment]
粘贴完整log或者关键信息啊，你贴的都没用

**Comment by Andjdd** [comment]
Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
&gt; Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
&nbsp; &nbsp;&gt; Could not find com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.3-jitpack.
&nbsp; &nbsp; &nbsp;Required by:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;project :app


Possible solution:
&nbsp;- Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
&nbsp; 你发布的群里面我耶发了的没回复。。。





574808086
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CarGuo/GSYVideoPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月10日(星期二) 晚上6:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CarGuo/GSYVideoPlayer]     implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-jitpack' 引用失败 (Issue #3737)





 
粘贴完整log或者关键信息啊，你贴的都没用

**Comment by CarGuo** [comment]
唉，你还是没找到关键 log

**Comment by Andjdd** [comment]
可以了，如果我想播放rtmp 这种实时推送的流 视频用那个方式请指教下

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class); 这个
