### ISSUE TITLE
如何设置rtmp 流播放 一进去就自动播放

### ISSUE THREAD

**Issue by Andjdd** [CarGuo/GSYVideoPlayer#3738]
1、如何设置rtmp 流播放 一进去就自动播放
2、发现播放一会会自动暂停？
3、播放中的卡顿处理？

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class); 会更稳定一些

**Comment by Andjdd** [comment]
好的，现在就是 如何设置我进入当前界面 就让rtmp 流自动播放的方式？

**Comment by Andjdd** [comment]
现在发现很卡顿 ，这个卡顿原因又那些情况哦

**Comment by CarGuo** [comment]
> 好的，现在就是 如何设置我进入当前界面 就让rtmp 流自动播放的方式？

startPlayLogic
