### ISSUE TITLE
GSYVideoType.SUFRACE模式下，旋转画面会黑屏

### ISSUE THREAD

**Issue by kiddkyd1412** [CarGuo/GSYVideoPlayer#3739]
## 问题描述：

Exo模式，GSYVideoType.SUFRACE模式。
执行demo中一样的旋转代码，画面会黑屏，但是视频还有声音。Texture模式就没问题。

## 问题机型/系统：

夜神模拟器安卓5

## GSY依赖版本

   implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.4-release-jitpack'

## Demo中的复现步骤

问题代码：(如果有)
```
mTextureView.setRotation(mRotate);
mTextureView.requestLayout();
```

**Comment by CarGuo** [comment]
真机测试正常，模拟器问题不处理
