### ISSUE TITLE
请问支持HLS视频格式吗？？

### ISSUE THREAD

**Issue by leoncoding** [CarGuo/GSYVideoPlayer#374]

**Comment by CarGuo** [comment]
具体什么协议什么容器格式。

**Comment by dovginka** [comment]
@CarGuo 我也在做hls,我的是4个rtsp的直播流转成hls播放的，你说的什么协议什么容器格式是什么意思，如果要播放hls,我应该怎么做呢？

**Comment by CarGuo** [comment]
hls 基于http理论上是没问题的，主要是支持的格式是什么。然后hls记得设置为cache false

**Comment by leoncoding** [comment]
m3u8,想做视频加密然后在线解密播放
