### ISSUE TITLE
自定义GsyVideoManager

### ISSUE THREAD

**Issue by ly469097645** [CarGuo/GSYVideoPlayer#3740]
## 问题描述：

由于线上频繁的出现ijk的so包加载失败的问题，所以想规避掉这种崩溃，对于ijk加载失败的情况下视频就不进行播放保证用户可以正常使用，参照demo中的CustomVideoManager自定义了一个manager，但是使用上了之后视频无法播放，也收不到播放回调，请问这个如何处理

## 问题机型/系统：
红米 k40

## GSY依赖版本
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'

问题代码：(如果有)
![image](https://user-images.githubusercontent.com/12133597/212812163-19075878-42bb-4760-9655-f5b7554505f9.png)
![image](https://user-images.githubusercontent.com/12133597/212812221-a5f68d98-4c4a-477e-9908-e1c5eb42b55f.png)

**Comment by CarGuo** [comment]
这样？

```
    @Override
    public GSYVideoViewBridge getGSYVideoManager() {
        GSYVideoManager.instance().initContext(getContext().getApplicationContext());
        return GSYVideoManager.instance();
    }
```

**Comment by ly469097645** [comment]
是的，目前就是这么写的，但是视频播放成功之后也听到声音了，但是loading的界面一直在

**Comment by ly469097645** [comment]
找到原因了，需要用单例
