### ISSUE TITLE
如何获取视频在控件中播放时的实际大小而不是原视频大小？

### ISSUE THREAD

**Issue by nokiafen** [CarGuo/GSYVideoPlayer#3741]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不是很理解，如果你是说画面大小，那么你获取控件大小不就是了～

**Comment by nokiafen** [comment]
嗯 这个当视频是铺满控件的情况下确实是。当视频没铺满的情况下去计算封面的大小的话就比较麻烦了。可能宽度等于控件大小 高度有空出来的。如果能拿到视频在控件里面实际大小（黑边间隙不计算在内），处理起来就方便多了。这可能是处理封面大小（封面大小位置与视频内容重叠）一种较为简单的处理方法。

**Comment by CarGuo** [comment]
那你可以通过 mTextureView 的  mShowView 参数去获取

**Comment by nokiafen** [comment]
好的，我等下试试 ths.
