### ISSUE TITLE
固定大小之后，有未知的黑色线条

### ISSUE THREAD

**Issue by ly469097645** [CarGuo/GSYVideoPlayer#3742]
## 问题描述：

在XML中给播放器设置一个固定的宽高，加载视频之后，上下两边会出现一个黑色的线条，并且这个线条可以超出设置的宽度之外，这个线条要如何才能去除

## 问题机型/系统：
红米K40

## GSY依赖版本
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'

## Demo中的复现步骤
打开Demo中的SimplePlayer类，在它对应的XML中将视频控件的宽高改为250dp，将父控件RelativeLayout的背景色改为白色，或者#EBF0F9，可以明显的看到上下以及中间，都有一个横着的线条在视频宽高之外

问题代码：(如果有)
截图可能不太明显，如果看不清可能要大佬按照复现步骤试一下

![微信图片_20230118165749](https://user-images.githubusercontent.com/12133597/213127753-039a2f12-7f74-40f3-9cba-8a96e30a717e.jpg)

![微信图片_20230118165809](https://user-images.githubusercontent.com/12133597/213127797-9c290213-fc41-476f-978a-2a8ee9aa1e6f.jpg)

![微信图片_20230118165801](https://user-images.githubusercontent.com/12133597/213127846-d3716c5a-3f4d-477f-873f-68589cc77062.jpg)

**Comment by ly469097645** [comment]
![image](https://user-images.githubusercontent.com/12133597/213133750-339059d6-a861-4f47-9e58-e46058eb8e04.png)

**Comment by CarGuo** [comment]
没有
![image](https://user-images.githubusercontent.com/10770362/213135876-70b67e72-cc83-452f-9435-2ed4860c05a1.png)

**Comment by ly469097645** [comment]
截图看不出来，然后这个颜色和那个颜色比较接近可能，背景色值成  #666666   或者  #ffffff  或者  #EBF0F9 ，仔细看能明显的看到，注意看我圈出来的那个位置是真的有，我换了三台手机都能看到

**Comment by CarGuo** [comment]
试了，没看到你所说的颜色
