### ISSUE TITLE
如何播放视频和音频资源分离的视频？

### ISSUE THREAD

**Issue by 1250422131** [CarGuo/GSYVideoPlayer#3745]
## 问题描述：

我正在做一个播放B站视频的播放功能，但是现在这个视频的视频和音频是分开的，我就有两个URL，我不太清楚要如何使用GSYVideoPlayer来播放这样的视频，我得让视频和音频是同步播放的。
我知道B站的视频是有flv的，但是最近砍掉了这个格式的大部分画质选择，这使得我得想办法改用播放音频和视频分离的文件。

## GSY依赖版本

 ` api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack'`

## 视频资源API
https://api.bilibili.com/x/player/playurl?bvid=BV1RY411Z7qC&cid=889244324&qn=64&fnval=4048&fourk=1

## 视频资源Url
https://api.bilibili.com/x/player/playurl?bvid=BV1RY411Z7qC&cid=889244324&qn=64&fnval=4048&fourk=1
资源地址如下图
![image](https://user-images.githubusercontent.com/52126790/215680901-88e20ce5-1459-4125-957c-26a15a25ee8b.png)

**Comment by CarGuo** [comment]
不支持，上层没这个能力，简单说你可以直接播放无音频视频，然后在同步播放因为文件，但是这涉及到同步时钟去做音画同步的问题，底层上是可以在解码的时候根据包排序后，利用音频做同步时钟来同步画面····
目前来看 GSY 不支持这种模式
