### ISSUE TITLE
sdk版本问题

### ISSUE THREAD

**Issue by zhuying** [CarGuo/GSYVideoPlayer#3747]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

麻烦问下 必须sdk是33吗 我用30会提示让我用大于30版本的 ，我用的8.3.4

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
Dependency 'androidx.appcompat:appcompat-resources:1.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.emoji2:emoji2-views-helper:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.emoji2:emoji2:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.core:core:1.7.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

xxxxxxx

```

**Comment by CarGuo** [comment]
是的 compileSdkVersion 需要 31 ，如下图


![](https://user-images.githubusercontent.com/10770362/187625126-43e46379-7e82-472a-a90a-420239c6c434.png)
