### ISSUE TITLE
横竖屏切换

### ISSUE THREAD

**Issue by jzh1996** [CarGuo/GSYVideoPlayer#3749]
## 问题描述：

覆盖在播放器上面的一层布局在切换全屏后不显示，竖屏正常显示。因为不同的地方播放器上的控件不同，所以自定义播放器布局时只加了基础的控件，有一些特殊功能控件是在XML中覆盖到播放器上的，我看了DEMO没有相关的示例，请问有方法解决吗

## 出现问题的视频流
无

## 问题机型/系统：
所有系统

## GSY依赖版本

 `implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack'`

## Demo中的复现步骤
无

问题代码：(如果有)
无

## 问题log（如果有）

无

**Comment by CarGuo** [comment]
LandLayoutVideo 类似你的需求，其他自己摸索了

**Comment by plm778** [comment]
@jzh1996 请问解决了吗，我也有一样的问题
