### ISSUE TITLE
minSdk 16以下的支持？

### ISSUE THREAD

**Issue by westlinkin** [CarGuo/GSYVideoPlayer#375]
目前minSdk 定到了16，大概是因为用到了16以上才有的api，（全屏支持？）有没有考虑过支持16以下的设备呢？因为看到了ijkplayer是最低支持到api 9的，需要用的高级api使用其他土办法实现，或者用ijk内置的mediaPlayer来实现

**Comment by CarGuo** [comment]
目前还不行
