### ISSUE TITLE
可有好的方法设置外挂字幕与视频延迟时间的同步?

### ISSUE THREAD

**Issue by XiaoRanLiu3119** [CarGuo/GSYVideoPlayer#3750]
## 问题描述：

⚠️ 下载的字幕与片源时间不匹配,发现mxplayer中貌似有这个功能,暂未找到相关api,大佬可有好的方法?

只能想到最笨的方法取字幕文件流,修改每段的开始结束时间

![图片](https://user-images.githubusercontent.com/62411322/216287357-94827620-cced-4213-bdc7-7fe78b67e233.png)

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
只有这个了 https://github.com/google/ExoPlayer/issues/854
