### ISSUE TITLE
全屏返回键逻辑问题

### ISSUE THREAD

**Issue by RainTang1** [CarGuo/GSYVideoPlayer#3752]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

根据Demo中SwitchPlay实现了打开小窗切换Surface 再返回详情页再次切换Surface 导致全屏后Layout上的返回键无效 物理返回键正常
 不切换Surface则这个按钮是正常逻辑可以返回 打断点查看到自定义VideoManager中的backFromWindowFull的oldF获取为Null 大佬知道是怎么造成的吗 或者提供一下解决思路

## 问题机型/系统：

例如 真机 三星S22U Android13

## GSY依赖版本

`implementation ['com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.7-release-jitpack'`](url)

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```
![1675604378069](https://user-images.githubusercontent.com/21236197/216823387-b532c136-27af-41f7-8731-056b37206d6b.jpg)

https://user-images.githubusercontent.com/21236197/216823737-4a3fc35b-0ed3-4513-8b1c-ca5fdfd8732f.mp4

**Comment by CarGuo** [comment]
因为全屏是通过这个id添加到根 content 上的

**Comment by RainTang1** [comment]
我已经重写了getFullId和getSmallId 还是不行  还需要重写什么才能让ID添加到根content吗?

**Comment by CarGuo** [comment]
我的意思是，你完全可以不用这个方法，自己写一个啊，里面的对象你都可以拿到
