### ISSUE TITLE
快进、快退限制倍速有点低，最高倍速只能达到2倍速。

### ISSUE THREAD

**Issue by yuyingfeng1989** [CarGuo/GSYVideoPlayer#3753]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

通过setSpeedPlaying(speed, true)方法设置倍速，设置快进倍速大于2f无效，低于2倍倍速设置有效，请问播放倍速大小能否自定义。

## 出现问题的视频流

String url = "http://200024424.vod.myqcloud.com/200024424_709ae516bdf811e6ad39991f76a4df69.f20.mp4"

## 问题机型/系统：

三星 Andriod11

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack'

## Demo中的复现步骤

正常开启视频播放后设置逐渐添加倍速，当倍速超过2倍后，设置大于2倍速度无效

问题代码：(如果有)
```
btFastForward.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                 speedValue++;
                videoPlayer.setSpeedPlaying(speedValue, true);
            }
        });
        btRewind.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                speedValue--;
                videoPlayer.setSpeedPlaying(speedValue, true);
            }
        });
```

## 问题log（如果有）

```

暂无

```

**Comment by CarGuo** [comment]
不支持

**Comment by yuyingfeng1989** [comment]
能否修改快进倍速，能达到快进3、4倍或更高呢。
