### ISSUE TITLE
如何调整视频上下位置

### ISSUE THREAD

**Issue by goodluckier** [CarGuo/GSYVideoPlayer#3755]
## 问题描述：
1、视频位置默认是居中的，怎么调整上下位置。
2、怎么在视频下方加view，比如全屏、静音之类的。
如图

## 问题机型/系统：

真机 小米11 Android13

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.3.4'`

## 示例截图
![image](https://user-images.githubusercontent.com/3511727/218385673-043c6358-7e40-436f-aa4f-3d7de74f1fab.png)

**Comment by CarGuo** [comment]
override  getLayoutId ，返回你自己的布局，参考 SampleControlVideo
