### ISSUE TITLE
DEMO中ListNormalAdapter开启缓存路径new File(FileUtils.getTestPath())后，无法缓存和播放视频

### ISSUE THREAD

**Issue by flylancoco** [CarGuo/GSYVideoPlayer#3756]
## 问题机型/系统：

 小米 Android12

## GSY依赖版本

当前版本

## Demo中的复现步骤

Demo中的ListNormalAdapter打开holder.gsyVideoPlayer.setUp(url, true, new File(FileUtils.getTestPath()), "这是title")；注释会出现这个问题。

![image](https://user-images.githubusercontent.com/15763795/218666838-37020463-e319-4383-ae8c-80eec4dbd724.png)

**Comment by CarGuo** [comment]
已经提交修改，外部存储和系统沙盒逻辑限制导致
