### ISSUE TITLE
请问下，播放实时视频流的时候，可以截图，那有没有录制视频的API呢或者方法，没找到！

### ISSUE THREAD

**Issue by liuzhihua520** [CarGuo/GSYVideoPlayer#3758]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by liuzhihua520** [comment]
就是想自定义 截取一段实时视频，如果有的话最好；没有的话只能调用系统自带的相机去做相关操作了

**Comment by CarGuo** [comment]
没有录制视频的API，推荐你用系统录屏 API

**Comment by liuzhihua520** [comment]
ok
