### ISSUE TITLE
视频每次都需要下载，关闭网络后无法播放

### ISSUE THREAD

**Issue by yangzhanlong** [CarGuo/GSYVideoPlayer#3759]
问题描述：

视频每次都需要下载，关闭网络后无法播放，如果我想第一次下载就保存到本地，翻页的时候，拿本地的去播放，而不是通过网络下载去播放。

GSY依赖版本：
api "com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack"

Demo中的复现步骤：
VIEWPAGER2列表，翻页

问题log（如果有）：
无

**Comment by CarGuo** [comment]
cacheWithPlay 设置为true
