### ISSUE TITLE
rtsp不能播放，使用的是第三种依赖缓存已经设置为flase

### ISSUE THREAD

**Issue by wumingXL** [CarGuo/GSYVideoPlayer#376]
rtsp不能播放，使用的是第三种依赖缓存已经设置为flase
地址为rtsp://video.fjtu.com.cn/vs01/flws/flws_01.rm
错误信息为 E/IJKMEDIA: Option ijkapplication not found.
手机型号华为荣耀8，系统Android7.0

**Comment by CarGuo** [comment]
这个不是错误信息，这个只是ijk一定会打印出来的log。目前和几的用户测试，他们都是可以正常播放

**Comment by wumingXL** [comment]
请问是直接用的demo加载的吗，需不需要改动其他配置之类的，我现在是在项目中测试的，我去拿demo实验一下

**Comment by CarGuo** [comment]
你可以去群里问问，具体demo也需要修改下低依赖第三种

**Comment by wumingXL** [comment]
我申请加群了2次，都没有通过，我现在加一下，劳烦通过一下

**Comment by wumingXL** [comment]
还是不能播放地址为：rtsp://cloud.easydarwin.org:554/stream0.sdp
点播的这个地址可以播放rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov
log为
08-17 11:16:42.207 3593-3593/com.example.gsyvideoplayer V/AudioManager: playSoundEffect   effectType: 0
08-17 11:16:42.207 3593-3593/com.example.gsyvideoplayer V/AudioManager: querySoundEffectsEnabled...
                                                                        
                                                                        --------- beginning of system
08-17 11:16:42.225 3593-3593/com.example.gsyvideoplayer D/ExitTransitionCoordinator: notifyComplete isReadyToNotify= false mSharedElementNotified= false mListener= android.app.SharedElementCallback$1@5d45c01
08-17 11:16:42.235 3593-3593/com.example.gsyvideoplayer D/HwCust: Create obj success use class android.app.HwCustActivityImpl
08-17 11:16:42.235 3593-3593/com.example.gsyvideoplayer D/HwCust: Create obj success use class android.app.HwCustHwWallpaperManagerImpl
08-17 11:16:42.236 3593-3593/com.example.gsyvideoplayer V/ActivityThread: ActivityThread,callActivityOnCreate
08-17 11:16:42.240 3593-3593/com.example.gsyvideoplayer D/HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f0900df, context : com.example.gsyvideoplayer.PlayActivity@9dff379, Nhwext : 0, get Blur : disable
08-17 11:16:42.240 3593-3593/com.example.gsyvideoplayer D/HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f0900df, context : com.example.gsyvideoplayer.PlayActivity@9dff379, Nhwext : 0, get Blur : disable
08-17 11:16:42.247 3593-3593/com.example.gsyvideoplayer V/AudioManager: unregisterAudioFocusListener...
08-17 11:16:42.247 3593-3593/com.example.gsyvideoplayer I/AudioManager: abandonAudioFocus
08-17 11:16:42.247 3593-3593/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToNormal
08-17 11:16:42.255 3593-3593/com.example.gsyvideoplayer D/ActivityThread: add activity client record, r= ActivityRecord{70a5f58 token=android.os.BinderProxy@32ddd41 {com.example.gsyvideoplayer/com.example.gsyvideoplayer.PlayActivity}} token= android.os.BinderProxy@32ddd41
08-17 11:16:42.257 3593-3593/com.example.gsyvideoplayer I/HwPointEventFilter: do not support AFT because of no config
08-17 11:16:42.271 3593-3629/com.example.gsyvideoplayer D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-17 11:16:42.279 3593-3593/com.example.gsyvideoplayer D/ExitTransitionCoordinator: notifyComplete isReadyToNotify= true mSharedElementNotified= false mListener= android.app.SharedElementCallback$1@5d45c01
08-17 11:16:42.291 3593-3593/com.example.gsyvideoplayer D/EnterTransitionCoordinator: onTakeSharedElements mIsReadyForTransition= true mSharedElementsBundle= Bundle[{IMG_TRANSITION=Bundle[{shared_element:screenBottom=432.0, shared_element:translationZ=0.42134106, shared_element:screenLeft=48.0, shared_element:screenRight=408.0, shared_element:elevation=6.0, shared_element:screenTop=288.0, shared_element:bitmap=android.graphics.Bitmap@402c7b3}]}] mListener= android.app.SharedElementCallback$1@5d45c01
08-17 11:16:42.621 3593-3593/com.example.gsyvideoplayer V/AudioManager: requestAudioFocus  streamType: 3  durationHint: 2
08-17 11:16:42.621 3593-3593/com.example.gsyvideoplayer V/AudioManager: registerAudioFocusListener...
08-17 11:16:42.624 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_release
08-17 11:16:42.624 3593-3593/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToPreparingShow
08-17 11:16:42.624 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_native_setup
08-17 11:16:42.624 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170710--001
08-17 11:16:42.624 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: ijk_version_info: k0.8.1-28-gd0cb038
08-17 11:16:42.624 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_create_from_android()
08-17 11:16:42.624 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque(0x846)
08-17 11:16:42.624 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque()=void
08-17 11:16:42.624 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x846)
08-17 11:16:42.625 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
08-17 11:16:42.625 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
08-17 11:16:42.625 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
08-17 11:16:42.625 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
08-17 11:16:42.625 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
08-17 11:16:42.625 3593-4051/com.example.gsyvideoplayer V/IJKMEDIA: setDataSource: path rtsp://192.168.101.5:554/stream0.sdp
08-17 11:16:42.625 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="rtsp://192.168.101.5:554/stream0.sdp")
08-17 11:16:42.625 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="rtsp://192.168.101.5:554/stream0.sdp")=0
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setLoopCount
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_volume
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_prepareAsync
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer W/IJKMEDIA: remove 'timeout' option for rtmp.
08-17 11:16:42.626 3593-4204/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [4204] ff_msg_loop
08-17 11:16:42.626 3593-4204/com.example.gsyvideoplayer D/IJKMEDIA: message_loop
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: ===== versions =====
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: ijkplayer    : k0.8.1-28-gd0cb038
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170710--001
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: libavutil    : 55.58.100
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: libavcodec   : 57.89.100
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: libavformat  : 57.71.100
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: libswscale   : 4.6.100
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: libswresample: 2.7.100
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: ===== options =====
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: player-opts : loop                         = 1
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkapplication               = -430504144
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkiomanager                 = -552013304
08-17 11:16:42.626 3593-4204/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_FLUSH:
08-17 11:16:42.626 3593-4051/com.example.gsyvideoplayer I/IJKMEDIA: ===================
08-17 11:16:42.627 3593-4205/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [4205] ff_vout
08-17 11:16:42.627 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()=0
08-17 11:16:42.627 3593-4208/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [4208] ff_read
08-17 11:16:42.627 3593-4208/com.example.gsyvideoplayer W/IJKMEDIA: remove 'timeout' option for rtmp.
08-17 11:16:42.634 3593-4051/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
08-17 11:16:42.634 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
08-17 11:16:42.634 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0xc51c0900)
08-17 11:16:42.634 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_surface()
08-17 11:16:42.634 3593-4051/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0xc51c0900)=void

**Comment by CarGuo** [comment]
哦，之前没看清楚，是不支持sdp协议的，你可以试试tcp

**Comment by CarGuo** [comment]
https://github.com/Bilibili/ijkplayer/issues/2741
