### ISSUE TITLE
viewpager2 列表，视频播放每个Item都有一个播放器，是否可以优化？

### ISSUE THREAD

**Issue by yangzhanlong** [CarGuo/GSYVideoPlayer#3760]
问题描述：

viewpager2 列表，视频播放每个Item都有一个播放器，这样每个Item都会创建一个播放器，这样是否内存会爆涨，是否可以优化？

GSY依赖版本：
api "com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack"

Demo中的复现步骤：
VIEWPAGER2列表，翻页

<img width="759" alt="image" src="https://user-images.githubusercontent.com/6387629/219998945-79544f33-1a3d-42b5-a250-5076d5202dfd.png">

问题log（如果有）：
无

**Comment by CarGuo** [comment]
No，每个 Item 并不会创建一个播放器，只有一个 View 在哪里而已，只有播放的时候才会创建，新的创建旧的就会release ，所以并不会同时存在多个播放核心。
另外或者你也可以参考demo里的 GSYVideoHelper ，做一些调整，构建单个 view  切换？

**Comment by yangzhanlong** [comment]
> No，每个 Item 并不会创建一个播放器，只有一个 View 在哪里而已，只有播放的时候才会创建，新的创建旧的就会release ，所以并不会同时存在多个播放核心。 另外或者你也可以参考demo里的 GSYVideoHelper ，做一些调整，构建单个 view 切换？

对，我看的就是翻页的时候，会执行releae和创建，那么这样不断翻页就会不断地创建和释放哦？？，这样不会有问题么？

**Comment by CarGuo** [comment]
不会，只要不因为release 而 block 的话，一般不会有什么问题，当然你也可以考虑用两个 GSYVideoHelper  来维护切换和预加载
