### ISSUE TITLE
aliplay模式代码开启混淆后崩溃

### ISSUE THREAD

**Issue by darrennight** [CarGuo/GSYVideoPlayer#3763]
播放下面url崩溃

播放链接：https://baidu.sd-play.com/20230206/APODMcTg/index.m3u8
在demo工程，开启minifyEnabled true
设置模式PlayerFactory.setPlayManager(AliPlayerManager::class.java)

 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'

 //是否需要ExoPlayer模式
 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.4-release-jitpack'

 //是否需要AliPlayer模式
 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-aliplay:8.3.4-release-jitpack'

 //根据你的需求ijk模式的so
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-arm64:v8.3.4-release-jitpack'
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:v8.3.4-release-jitpack'

设备：oppo Android11

日志：是我本项目的日志，GSY的demo也是同样问题

03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] Runtime aborting...
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] Dumping all threads without mutator lock held
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] All threads:
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] DALVIK THREADS (189):
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] "main" prio=10 tid=1 Runnable
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x7244a578 self=0xb4000072ea210800
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | sysTid=21335 nice=-10 cgrp=default sched=0/0 handle=0x7371bd1500
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | state=R schedstat=( 6411172774 261710686 2077 ) utm=587 stm=53 core=7 HZ=100
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | stack=0x7ffcf1e000-0x7ffcf20000 stackSize=8192KB
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | held mutexes= "abort lock" "mutator lock"(shared held)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #00 pc 000000000049f310  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+140)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #01 pc 00000000005abf58  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+376)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #02 pc 00000000005c94e0  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+924)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #03 pc 00000000005c3420  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+528)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #04 pc 00000000005c25ec  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1920)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #05 pc 000000000055da38  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1864)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #06 pc 0000000000013988  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #07 pc 0000000000012fb4  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+320)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #08 pc 000000000038568c  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2572)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #09 pc 0000000000385704  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+108)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #10 pc 00000000003773e8  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+144)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #11 pc 00000000003769c0  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckInstance(art::ScopedObjectAccess&, art::(anonymous namespace)::ScopedCheck::InstanceKind, _jobject*, bool)+472)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #12 pc 0000000000375510  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+564)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #13 pc 0000000000374b60  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+612)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #14 pc 000000000037bb60  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::GetFieldIDInternal(char const*, _JNIEnv*, _jclass*, char const*, char const*, bool)+692)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #15 pc 0000000000188208  /data/app/~~vwd7HK0-TCjXZENsqyJecw==/com.tiantian.boxmovie-o8W93gR-0bactudyAe4gvg==/lib/arm64/libsaasCorePlayer.so (JavaCacheConfig::init(_JNIEnv*)+136)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #16 pc 0000000000181eb0  /data/app/~~vwd7HK0-TCjXZENsqyJecw==/com.tiantian.boxmovie-o8W93gR-0bactudyAe4gvg==/lib/arm64/libsaasCorePlayer.so (initJavaInfo(_JNIEnv*)+40)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #17 pc 000000000018228c  /data/app/~~vwd7HK0-TCjXZENsqyJecw==/com.tiantian.boxmovie-o8W93gR-0bactudyAe4gvg==/lib/arm64/libsaasCorePlayer.so (JNI_OnLoad+80)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #18 pc 000000000038964c  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+3348)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #19 pc 000000000000516c  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+416)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at java.lang.Runtime.nativeLoad(Native method)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at java.lang.Runtime.nativeLoad(Runtime.java:1131)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at java.lang.Runtime.loadLibrary0(Runtime.java:1085)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   - locked <0x0b19a44b> (a java.lang.Runtime)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at java.lang.System.loadLibrary(System.java:1664)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at com.aliyun.utils.NativeLoader.loadPlayer(NativeLoader.java:15)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   - locked <0x06fbfe28> (a java.lang.Class<com.aliyun.utils.NativeLoader>)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at com.aliyun.player.nativeclass.NativeExternalPlayer.<clinit>(NativeExternalPlayer.java:16)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at com.aliyun.player.nativeclass.NativeExternalPlayer.setContext(NativeExternalPlayer.java:25)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at com.aliyun.player.AliPlayerFactory.createAliPlayer(AliPlayerFactory.java:71)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at com.aliyun.player.AliPlayerFactory.createAliPlayer(AliPlayerFactory.java:51)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at com.shuyu.aliplay.AliMediaPlayer$1.run(AliMediaPlayer.java:309)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at android.os.Handler.handleCallback(Handler.java:938)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at android.os.Handler.dispatchMessage(Handler.java:99)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at android.os.Looper.loop(Looper.java:263)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at android.app.ActivityThread.main(ActivityThread.java:8292)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at java.lang.reflect.Method.invoke(Native method)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] "Signal Catcher" prio=10 tid=5 WaitingInMainSignalCatcherLoop
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x12ec22d0 self=0xb4000072dff6f800
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | sysTid=21355 nice=-20 cgrp=default sched=0/0 handle=0x72d63fbcc0
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | state=S schedstat=( 806875 0 4 ) utm=0 stm=0 core=7 HZ=100
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | stack=0x72d6304000-0x72d6306000 stackSize=995KB
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | held mutexes=
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #00 pc 00000000000c5ea8  /apex/com.android.runtime/lib64/bionic/libc.so (__rt_sigtimedwait+8)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #01 pc 0000000000086dd0  /apex/com.android.runtime/lib64/bionic/libc.so (sigwait+68)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #02 pc 0000000000583b08  /apex/com.android.art/lib64/libart.so (art::SignalCatcher::WaitForSignal(art::Thread*, art::SignalSet&)+428)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #03 pc 0000000000582700  /apex/com.android.art/lib64/libart.so (art::SignalCatcher::Run(void*)+272)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #04 pc 00000000000da278  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #05 pc 000000000007a448  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   (no managed stack frames)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] "perfetto_hprof_listener" prio=10 tid=7 Native (still starting up)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x0 self=0xb4000072cd5c6800
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | sysTid=21356 nice=-20 cgrp=default sched=0/0 handle=0x72d42fdcc0
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | state=S schedstat=( 577814 813177 9 ) utm=0 stm=0 core=6 HZ=100
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | stack=0x72d4206000-0x72d4208000 stackSize=995KB
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | held mutexes=
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #00 pc 00000000000c5224  /apex/com.android.runtime/lib64/bionic/libc.so (read+4)
03-02 17:20:14.173 14659 22147 D InvokeUniqueMethodUtils: getTopScreenIsFull= true
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #01 pc 00000000000180bc  /apex/com.android.art/lib64/libperfetto_hprof.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ArtPlugin_Initialize::$_29> >(void*)+280)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #02 pc 00000000000da278  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #03 pc 000000000007a448  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   (no managed stack frames)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] "ADB-JDWP Connection Control Thread" prio=10 tid=8 WaitingInMainDebuggerLoop
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x12ec2348 self=0xb4000072d846e800
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | sysTid=21357 nice=-20 cgrp=default sched=0/0 handle=0x72d41ffcc0
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | state=S schedstat=( 3698439 821459 14 ) utm=0 stm=0 core=5 HZ=100
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | stack=0x72d4108000-0x72d410a000 stackSize=995KB
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | held mutexes=
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #00 pc 00000000000c6568  /apex/com.android.runtime/lib64/bionic/libc.so (__ppoll+8)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #01 pc 0000000000084398  /apex/com.android.runtime/lib64/bionic/libc.so (poll+92)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #02 pc 0000000000009efc  /apex/com.android.art/lib64/libadbconnection.so (adbconnection::AdbConnectionState::RunPollLoop(art::Thread*)+828)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #03 pc 0000000000008578  /apex/com.android.art/lib64/libadbconnection.so (adbconnection::CallbackFunction(void*)+1508)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #04 pc 00000000000da278  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #05 pc 000000000007a448  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   (no managed stack frames)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] "Jit thread pool worker thread 0" prio=5 tid=9 Native
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x12ec23c0 self=0xb4000072cd5db800
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | sysTid=21359 nice=0 cgrp=default sched=0/0 handle=0x7286540d00
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | state=S schedstat=( 2619143942 423685360 1956 ) utm=205 stm=56 core=6 HZ=100
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | stack=0x7286442000-0x7286444000 stackSize=1023KB
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | held mutexes=
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #00 pc 000000000007550c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #01 pc 00000000001af800  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+148)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #02 pc 00000000005cb208  /apex/com.android.art/lib64/libart.so (art::ThreadPool::GetTask(art::Thread*)+120)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #03 pc 00000000005ca4ac  /apex/com.android.art/lib64/libart.so (art::ThreadPoolWorker::Run()+144)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #04 pc 00000000005c9f7c  /apex/com.android.art/lib64/libart.so (art::ThreadPoolWorker::Callback(void*)+192)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #05 pc 00000000000da278  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   native: #06 pc 000000000007a448  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   (no managed stack frames)
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655] "HeapTaskDaemon" prio=5 tid=10 WaitingForTaskProcessor
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x12ec37e8 self=0xb4000072cd5ed000
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | sysTid=21360 nice=4 cgrp=default sched=0/0 handle=0x72851fbcc0
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | state=S schedstat=( 537751752 191788751 339 ) utm=48 stm=5 core=6 HZ=100
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | stack=0x72850f8000-0x72850fa000 stackSize=1043KB
03-02 17:20:14.173 21335 21335 F antian.boxmovi: runtime.cc:655]   | held mutexes=

**Comment by CarGuo** [comment]
-keep class com.shuyu.alipay.** {*;}
-keep interface com.shuyu.alipay.**
