### ISSUE TITLE
请教下，播放时候屏幕翻转是什么问题。

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#3768]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

部分电视盒子上，从6.0.3开始就有这个问题。

## 问题机型/系统：

魔百盒

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

视频现象

https://user-images.githubusercontent.com/6526280/223328976-7dbefd5b-bc5e-4748-9422-3860268dbe64.mp4

**Comment by CarGuo** [comment]
看起来像是开了重力旋转？？？？             .setRotateViewAuto(false) 和   orientationUtils.setEnable(false); 试试？看你整个界面的翻转了···
