### ISSUE TITLE
为什么打开一个电视直播的流要很长时间，我这里平均八九秒

### ISSUE THREAD

**Issue by guojiadui** [CarGuo/GSYVideoPlayer#377]

**Comment by CarGuo** [comment]
rtsp貌似ijk确实不是很快

**Comment by wsw87201326** [comment]
那使用什么播放RTSP的很快?只需要支持RTSP的

**Comment by CarGuo** [comment]
vlc试试

**Comment by ZhanRu** [comment]
@guojiadui 我也遇到了 试试加入下面的设置 ：

        // 设置缓冲大小，提高出图速度
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0));
        list.add(new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0));
        list.add(new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48));
        list.add(new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 8));
        list.add(new VideoOptionModel(1, "analyzemaxduration", 100));
        list.add(new VideoOptionModel(1, "probesize", 10240));
        list.add(new VideoOptionModel(1, "flush_packets", 1));
        list.add(new VideoOptionModel(4, "packet-buffering", 0));
        list.add(new VideoOptionModel(4, "framedrop", 1));
        GSYVideoManager.instance().setOptionModelList(list);
