### ISSUE TITLE
播放m3u8视频流时 调节seekBar后异常

### ISSUE THREAD

**Issue by misszhouhaiyang** [CarGuo/GSYVideoPlayer#3770]
## 问题描述：

播放m3u8视频流时，调节seekBar进度后，视频显示加载中，最后自动结束，提示播放完成
![image](https://user-images.githubusercontent.com/45926868/223358402-0eac2d2e-e122-46f9-9acd-f2ae2a13b7cc.png)
![image](https://user-images.githubusercontent.com/45926868/223359212-986ac8b2-e2d9-4a38-abee-3343e9b95112.png)

## 出现问题的视频流

https://b-1f16844d.kinesisvideo.us-west-2.amazonaws.com/hls/v1/getHLSMasterPlaylist.m3u8?SessionToken=CiD68Fza5YQZxqMF3ARFe7KsixvA6o2dAtqxJbxvmZ7oHBIQrraigpTZ_rSrHdpBZYrDPBoZwxxvhEczt2-KUCcsziqGMcz51mvHB9KIsyIgpSwreiIXrQSttjWZpgXP2FUfSY0NW80jW-OBTZPZnCA~
视频流有时间限制 已经失效

## 问题机型/系统：

android 7.0  模拟机

## GSY依赖版本
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack'

## Demo中的复现步骤
播放m3u8视频流时，调节seekBar进度后，视频显示加载中，最后自动结束，提示播放完成

问题代码：(如果有)

## 问题log（如果有）

视频流10分钟左右会失效，可后续加上有效视频流

**Comment by CarGuo** [comment]
默认 ijk 可以尝试

```
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

或者切换到 EXO 测试，另外 exo 下还有 SeekParameters.NEXT_SYNC 可以配置

```
 //设置 seek 的临近帧。
if(detailPlayer.getGSYVideoManager().getPlayer() instanceof Exo2PlayerManager) {
    ((Exo2PlayerManager) detailPlayer.getGSYVideoManager().getPlayer()).setSeekParameter(SeekParameters.NEXT_SYNC);
    Debuger.printfError("***** setSeekParameter **** ");
}
```

**Comment by misszhouhaiyang** [comment]
OKOK谢谢郭大
