### ISSUE TITLE
安全漏洞扫描写死邮箱地址问题

### ISSUE THREAD

**Issue by lyw2019AAA** [CarGuo/GSYVideoPlayer#3773]
## 问题描述：

公司的安全漏洞扫描发现有写死的邮箱地址，danikula@gmail.com 这个邮箱是在com.danikula.videocache.HttpUrlSource.java类中119行，能否麻烦帮忙删除一下。

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer:6.0.3'`

问题代码：(如果有)
```
com.danikula.videocache.HttpUrlSource.java 类中119行

```

**Comment by CarGuo** [comment]
v8.3.5-release-jitpack
