### ISSUE TITLE
我在您的demo上换成rtsp开头的地址，视频播放不出来

### ISSUE THREAD

**Issue by gentlemanJie** [CarGuo/GSYVideoPlayer#3775]
![image](https://user-images.githubusercontent.com/93319215/225231444-3790ae16-a5a3-4445-a570-382f2efa4748.png)
![image](https://user-images.githubusercontent.com/93319215/225231565-ab5bc10a-771b-42ba-b023-a1143397f3f9.png)
![image](https://user-images.githubusercontent.com/93319215/225231671-15032fdd-1ea7-4da0-9b33-72da488fd4cf.png)

**Comment by CarGuo** [comment]
改第三种依赖，ex_so

**Comment by gentlemanJie** [comment]
&quot;:gsyVideoPlayer-ex_so&quot;只依赖这个就可以了么？&nbsp;


杰仔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月15日(星期三) 下午3:21
收件人: "CarGuo/GSYVideoPlayer";
抄送: "Author";
主题: Re: [CarGuo/GSYVideoPlayer] 我在您的demo上换成rtsp开头的地址，视频播放不出来 (Issue #3775)





 
改第三种依赖，ex_so
 
&mdash;

**Comment by gentlemanJie** [comment]
![image](https://user-images.githubusercontent.com/93319215/225265127-edbfbe73-7a2b-41f7-bbcb-079617aa690f.png)
你好，我添加这个几个依赖，只有画面没有声音，请问下是什么问题呢？

**Comment by gentlemanJie** [comment]
问题找到了，谢谢
