### ISSUE TITLE
横屏播放视频，视频没有相对整个手机屏幕居中

### ISSUE THREAD

**Issue by luoxiong94** [CarGuo/GSYVideoPlayer#3777]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
官方demo，横屏的话，视频没有相对整个手机屏幕居中，竖屏正常。
```

## 问题log（如果有）

![7011f436ea947087e7b254f87c10a79](https://user-images.githubusercontent.com/16216657/225511223-40a022bd-df6a-4a5d-8e1e-0c65514be6bd.png)

**Comment by CarGuo** [comment]
不理解你的截图

**Comment by luoxiong94** [comment]
> 
横屏状态下， 视频画面相对于整个手机没有居中，而是偏右了点，右上红色矩形框长度== 左上红色矩形框长度。

**Comment by CarGuo** [comment]
是否因为有虚拟按键导致？

**Comment by luoxiong94** [comment]
不是，就是横屏的时候，视频没居中显示，竖屏正常，上面截图就是demo里的简单详情1

**Comment by CarGuo** [comment]
你没备注机型，我想了下，才理解应该是你用的是挖孔屏手机，版本可以是 P 以上，所以会有这样如下图的情况：

![image](https://user-images.githubusercontent.com/10770362/226783692-96b660b7-d7d4-41dc-ac2a-6b20f768607b.png)

```java
        //允许window 的内容可以上移到刘海屏状态栏
        if (getWindow() != null && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            WindowManager.LayoutParams lp = getWindow().getAttributes();
            lp.layoutInDisplayCutoutMode =
                WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;
            getWindow().setAttributes(lp);
        }
```

你在你的 activity 加上这个代码就可以了

![image](https://user-images.githubusercontent.com/10770362/226784912-6169adf2-7e67-4eb3-9b13-1ff7d3744625.png)

**Comment by luoxiong94** [comment]
谢谢， 我手机上小米8， 小米11u，都没完全居中。
