### ISSUE TITLE
请问onError()方法中what = -10000|-72|0|-192,代表什么意思？？

### ISSUE THREAD

**Issue by dovginka** [CarGuo/GSYVideoPlayer#378]

**Comment by dovginka** [comment]
今天播放视频的时候遇到了一些错误，请问作者，什么情况下回执行onError方法，有错误码清单吗？

**Comment by CarGuo** [comment]
ijk没有提供，不过-10000一般都是流出来问题，协议不支持，编码不支持等问题吧

**Comment by CarGuo** [comment]
int MEDIA_INFO_UNKNOWN = 1;
    int MEDIA_INFO_STARTED_AS_NEXT = 2;
    int MEDIA_INFO_VIDEO_RENDERING_START = 3;
    int MEDIA_INFO_VIDEO_TRACK_LAGGING = 700;
    int MEDIA_INFO_BUFFERING_START = 701;
    int MEDIA_INFO_BUFFERING_END = 702;
    int MEDIA_INFO_NETWORK_BANDWIDTH = 703;
    int MEDIA_INFO_BAD_INTERLEAVING = 800;
    int MEDIA_INFO_NOT_SEEKABLE = 801;
    int MEDIA_INFO_METADATA_UPDATE = 802;
    int MEDIA_INFO_TIMED_TEXT_ERROR = 900;
    int MEDIA_INFO_UNSUPPORTED_SUBTITLE = 901;
    int MEDIA_INFO_SUBTITLE_TIMED_OUT = 902;

    int MEDIA_INFO_VIDEO_ROTATION_CHANGED = 10001;
    int MEDIA_INFO_AUDIO_RENDERING_START = 10002;
    int MEDIA_INFO_MEDIA_ACCURATE_SEEK_COMPLETE = 10100;

    int MEDIA_ERROR_UNKNOWN = 1;
    int MEDIA_ERROR_SERVER_DIED = 100;
    int MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK = 200;
    int MEDIA_ERROR_IO = -1004;
    int MEDIA_ERROR_MALFORMED = -1007;
    int MEDIA_ERROR_UNSUPPORTED = -1010;
    int MEDIA_ERROR_TIMED_OUT = -110;

**Comment by CarGuo** [comment]
MEDIA_ERROR_UNSUPPORTED = -1010,
 MEDIA_ERROR_TIMED_OUT   = -110,
 MEDIA_ERROR_IJK_PLAYER  = -10000,
