### ISSUE TITLE
全屏状态下语音焦点被抢占时，播放器状态不同步

### ISSUE THREAD

**Issue by lybill** [CarGuo/GSYVideoPlayer#3780]
`protected void onLossTransientAudio() {
        try {
            this.onVideoPause();
        } catch (Exception var2) {
            var2.printStackTrace();
        }

    }`

就是上面这代码有问题
在全屏状态下，焦点被抢占了，onVideoPause()的对象还是非全屏状态下的播放器，导致了全屏播放器虽然视频暂停了，但是显示的还是显示"播放中"的状态，mCurrentState的值也出现问题了

解决办法：
需要重写这个方法，改成
`GSYVideoManager.instance().listener().onVideoPause();`

**Comment by CarGuo** [comment]
收到
