### ISSUE TITLE
集成 GSYVideoPlayer发现的问题，作者大大看是否可以优化一下

### ISSUE THREAD

**Issue by lybill** [CarGuo/GSYVideoPlayer#3781]
1，设置为系统默认播放器(SystemPlayerManager + Surfaceview + 硬解)的时候，封面隐藏后,播放器总是先黑屏一小段时间，然后才会出现视频的第一帧，我看了应该是封面隐藏的时机不对，解决方案：[黑屏解决](https://blog.csdn.net/qq_25135601/article/details/77941787?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-0-77941787-blog-109052500.pc_relevant_3mothn_strategy_and_data_recovery&spm=1001.2101.3001.4242.1&utm_relevant_index=3)

2，预加载，其实为了视频秒开，在视频未播放器先加载一定数量的数据

3，播放器的release，stop这些方法的处理目前都是主线程，容易在性能不好机器表现不是那么好，是否可以换到子线程，并且是唯一的子线程，既可以解决同步问题，也可以解决ui性能问题

4，（使用的是ExoPlayer测试）断网后，当缓冲的数据没有后，很容易走onError，设置了timeout比较长的时间也很快就error，也就是说重连超时不大管用，然后重新联网后也不会重新加载播放，是否可以添加这个需求进去，作为可选项

5，播放器在viewpager里面，频繁且快速切换页面，经过onPause和onResume，播放器容易出现状态不同步，需要手动强制的设置状态setUiAndStatue才行

**Comment by CarGuo** [comment]
1、 什么事机
2、可以一定程度支持，比如多播或者预下载部分、甚至是 exoplayer 模式下的 list 播放 source 也有预加载，demo 有例子
3、不行
4、因为断网需要重连，当前链路直接就没了，所以你需要重新播放，播放前自己设置个 offset
5、不懂为什么引起的

**Comment by lybill** [comment]
> 1、 什么事机 2、可以一定程度支持，比如多播或者预下载部分、甚至是 exoplayer 模式下的 list 播放 source 也有预加载，demo 有例子 3、不行 4、因为断网需要重连，当前链路直接就没了，所以你需要重新播放，播放前自己设置个 offset 5、不懂为什么引起的

1，我看了demo里面的sampleCoverVideo，是在surfaceCreate的时候就把封面隐藏了，但是这个时候视频的第一帧往往还没有渲染(硬解)出来，而是在MediaPlayer.OnPreparedListener的what == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START的时候，才真正的硬解出第一帧，这里有一个时间间隔，就会导致黑屏

3，为什么不能放在子线程？这个是有什么理由的吗？我看了有些开源的播放器，的确是可以把这些操作放子线程的

4，这个从技术层面可能不大对，而是从体验或者需求层面去优化更好理解，我看了b站和腾讯视频的播放器，他们断网后可以做到加载相对长的时间，并且重新联网后，可以继续播放，但是GsyVideoPlayer会很快onError，并且要手动去点击才能继续播放，我目前处理是跟你说的处理方式一样，在网络变更的广播那里恢复播放 setSeekOnStart && startPlayLogic，并且把一些状态下取消广播的操作给移除掉，改动的还比较大

**Comment by CarGuo** [comment]
1、明白了， 不过 SampleCoverVideo 是 Demo 的，应该不需要在 lib 坐什么改动。

3、因为它们本身对应的操作的底层逻辑本身就不在主线程上，特别这是为了兼容多种播放器，比如exoplayer后来的版本强制了 create 和调用的线程比如在同一个，以前的版本是可以create和调用不在一个

4、所以可以自己做， demo 里提供了无缝切换新内核的例子（清晰度），比如网络环境发生变化的场景就适用

**Comment by lybill** [comment]
> 1、明白了， 不过 SampleCoverVideo 是 Demo 的，应该不需要在 lib 坐什么改动。
> 
> 3、因为它们本身对应的操作的底层逻辑本身就不在主线程上，特别这是为了兼容多种播放器，比如exoplayer后来的版本强制了 create 和调用的线程比如在同一个，以前的版本是可以create和调用不在一个
> 
> 4、所以可以自己做， demo 里提供了无缝切换新内核的例子（清晰度），比如网络环境发生变化的场景就适用

3，我看了其他一些播放器，他们是可以放在子线程里面去做处理的，并且是同一个子线程，所以是不需要担心在不同线程调用的问题https://github.com/bytedance/AlphaPlayer/blob/master/android/alpha_player/src/main/java/com/ss/ugc/android/alpha_player/controller/PlayerController.kt

4，虽然自己改动也只是勉强的效果，还没有测试是否有问题，我是判断mCurrentStatus为error的时候，才恢复播放，也没办法确定这个error是否因为网络引起的error还是其他原因引起的

**Comment by CarGuo** [comment]
3、 这个就不讨论了，你没理解我的意思

4、这个你用无缝切换是可以实现你要的效果的，具体你根本不需要关心什么 error ，网络状态发生变化就可以切换，因为一定会断了原本的链路，具体细节的话，可能你如果要结合 wifi - 蜂窝 需要弹出提示，就可能要自己在网络状态变化那里记录一个 flag ，用于 error 时提示加载，你内部 new 一个新内核准备好然后切换 surface 是可以做到无感。
大概就这样了

**Comment by yoloaheadlcx** [comment]
2，预加载，其实为了视频秒开，在视频未播放器先加载一定数量的数据
-------------
@CarGuo  你好，这个问题，支持不初始化播放器，加载某个 MP4 的部分数据吗

**Comment by CarGuo** [comment]
支持，参考demo DetailDownloadPlayer
