### ISSUE TITLE
大佬,compileSdk 是不是要求的太高了点,33啊

### ISSUE THREAD

**Issue by leenickcode** [CarGuo/GSYVideoPlayer#3783]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ compileSdk 是不是要求的太高了点,33啊

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.5-release-jitpack'

## 问题log（如果有）
Dependency 'com.google.android.exoplayer:exoplayer-common:2.18.4' requires libraries and applications that
      depend on it to compile against version 33 or later of the
      Android APIs.
```

xxxxxxx

```

**Comment by CarGuo** [comment]
参看这个 https://github.com/CarGuo/GSYVideoPlayer/issues/3747#issuecomment-1411419285
