### ISSUE TITLE
是否可以实现播放packet数据流

### ISSUE THREAD

**Issue by cdck** [CarGuo/GSYVideoPlayer#3786]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ 项目中后台回调的视频数据`callback_videodecode(int isKeyframe, int w, int h, byte[] packet, long pts, byte[] codecdata)`，请问库是否有这种播放方式，我在demo中没有找到，是否可以实现？请教一下怎么实现。

**Comment by CarGuo** [comment]
ijk 默认模式下有人提交过元数据播放支持，具体你可以参考下，自己写个类似 StandardVideoPlayer 的对接应该可以，我猜


https://github.com/CarGuo/GSYVideoPlayer/pull/3582/files#diff-94b345da362b41150d798f49b1a97dc506a3275132caab5c17ad5bbe5f11f052

**Comment by cdck** [comment]
谢谢，我试试
