### ISSUE TITLE
播放时添加Header遇到的问题

### ISSUE THREAD

**Issue by xiaoowuu** [CarGuo/GSYVideoPlayer#3787]
## 问题描述：

使用AliPlayer添加Header没有效果
使用IjkPlayer添加Cookie，Cookie值会自动拼接`Cookie:`在开头

## 出现问题的视频流

与链接无关

## 问题机型/系统：

与机型无关

## GSY依赖版本

    //完整版引入
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.5-release-jitpack'
    //是否需要AliPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-aliplay:v8.3.5-release-jitpack'
    //是否需要ExoPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.5-release-jitpack'

## 添加Header代码

```kotlin
                val header = mutableMapOf<String, String>()
                header["User-Agent"] =
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.54"
                header["Cookie"] =
                    " __aysid=1680072710496nof; __ayscnt=1; xlly_s=1; P_ck_ctl=EA3E9E77FDBB4614290F0D00D6972C87; P_sck=P/Z2CxTfLZ+BJezvQHt3PW1s094iKyMEpfsFI/BsaDjdcyXjoZLIgnxtrKAL+mHJM0yAZuSOKZhPRX8oWNnFbYGPmTeKr9O3lfNq9ZtLRMUSZODbNKY+OTtzXpocNqW/MAKsA/yQ2u3CcBp5aM4Ttw==; P_gck=NA|vdDlQ4wSiKI07GCXoblCxQ==|NA|1680075143179; P_pck_rm=dhk12B+ae76014977e0823ZBKf2bPvkTPgNNoTyj5BKu1X85v/whXsHVujvfRmpw7KfMPSEV4/aXEk2xNAPw0PwGQfB5x7LQW8ztfGLYuzhRKEu3moEooOU+e8y5hyfZoSdY56/5Ki3T6OigmQ1O67/6GLBKZduzifKh0g==_V2; disrd=04053; P_F=1; _m_h5_tk=7aecbc1cb8d9e284b5103305e633ad51_1680082060452; _m_h5_tk_enc=659717418f0f22b7fd470332aa16a5da; __arycid=dc-3-00; __arcms=dc-3-00; __arpvid=16800785347175UQnEJ-1680078534731; __aypstp=12; __ayspstp=12; __ayvstp=35; __aysvstp=35; tfstk=cowFBN9nt9BFcbrRkADz7YY5cqwdajZ3qdojtaF0aKG2LHkZuscpyc4EkcoWbUch.; l=fBNd2IfuLVuvJzSoBO5CPurza7793IRb4sPzaNbMiIEGa1WdMF117OCsmdXkydtjgT1AXetzMXYO0dLHR3AcBlLdu4OxYy4nnxmXZeVh.; isg=BDEx4ZR48eNHWFsJdsFXw0UXQL3LHqWQct2eNRNGv_gXOlGMW2qEYh9YXM5c8j3I"
                if (cacheWithPlay) {
                    cacheFile = File(cacheFolder ?: CacheDir.videoCachePath("default"))
                }
                return super.setUp(playUrl, cacheWithPlay, cacheFile, header, title)
```

## 抓包截图
>AliPlayer
![Screenshot_20230329_184715](https://user-images.githubusercontent.com/25601944/228511452-5375332f-1763-40c4-b5de-1a0502d47619.png)

>IjkPlayer
![Screenshot_20230329_185053](https://user-images.githubusercontent.com/25601944/228511379-db50ab2c-9b81-4eef-87a9-3432d95c249a.png)

**Comment by CarGuo** [comment]
如下图所示，是我测试的 ijk 和 exoplayer 抓包之后的情况

<img width="604" alt="image" src="https://user-images.githubusercontent.com/10770362/230311463-f379ea4c-ca5f-4b0f-b9ea-3822033d9a7e.png">

<img width="441" alt="image" src="https://user-images.githubusercontent.com/10770362/230312277-2aa73b84-2243-41f5-9c17-7d7698e6bf41.png">
