### ISSUE TITLE
点击触摸显示和隐藏逻辑

### ISSUE THREAD

**Issue by Basakerone** [CarGuo/GSYVideoPlayer#379]
mLoadingProgressBar当视频正在加载中点击旁边区域会把控件隐藏掉（此时视频还没加载成功）有时候mCurrentState 一直处于 CURRENT_STATE_PREPAREING 导致mLoadingProgressBar一直不隐藏了。。

**Comment by Basakerone** [comment]
还有就是setUp（str,false,null）关闭缓存后，缓冲白条还是在增加。

**Comment by CarGuo** [comment]
不是很理解第二条？？？关闭缓存？会走缓冲的吖

**Comment by Basakerone** [comment]
0.0，我的问题，我理解成关闭缓存连缓冲都关闭了。。
