### ISSUE TITLE
更新到8.3.5后部分视频会报错CHECK(def.nBufferSize >= size) failed

### ISSUE THREAD

**Issue by kiddkyd2** [CarGuo/GSYVideoPlayer#3791]
## 问题描述：
升级到8.3.5后，用电视播放部分视频，会报这个错误CHECK(def.nBufferSize >= size) failed。估计是内存不足？我用模拟器就没问题。现在我降级回8.3.4，就没问题了。所以。。。

## 问题机型/系统：

小米电视3

## GSY依赖版本
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.5-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.5-release-jitpack'

**Comment by CarGuo** [comment]
默认模式？？？

**Comment by CarGuo** [comment]
从这我推测是 Exoplayer 爆出来的问题，这可能是因为播放的视频超出了当然设备的支持，似乎是大缓冲区之类的问题

**Comment by CarGuo** [comment]
https://github.com/google/ExoPlayer/issues/1140
https://github.com/google/ExoPlayer/issues/6433

具体和那个视频封装的格式兼容有关系，这一次新版本里确实升级了 exo 的内核，但是这个报错应该是 MediaCodec 底层的，可能是例如 extractor.getTrackFormat 的时候出现问题，具体你的 log 上我也看不出来
