### ISSUE TITLE
特殊支持的  ijkplayer 构建包，可以从这里获取

### ISSUE THREAD

**Issue by CarGuo** [CarGuo/GSYVideoPlayer#3792]
因为某些特殊支持的构建包，不会添加到正式发布的分支里，这里提供入口

播放RTSP直播提示400，重定向导致无法播放问题： https://github.com/CarGuo/GSYVideoPlayer/issues/2112#issuecomment-510416452

M3U8 带上特殊图片无法播放问题：https://github.com/CarGuo/GSYVideoPlayer/issues/3776#issuecomment-1491209798

**Comment by CarGuo** [comment]
16k：https://github.com/CarGuo/GSYVideoPlayer/tree/master/16kpatch

**Comment by oldpan1310** [comment]
M3U8 带上特殊图片无法播放问题，使用url链接无法播放，但是将m3u8文件和所有切片(伪装的图片)下载到本地，更换资源路径，使用exo模式就可正常播放，这个是什么原因？
