### ISSUE TITLE
设置 isLooping 后，没有播放完成的回调，有什么比较好的方法知道播放完成了吗？

### ISSUE THREAD

**Issue by hust-twj** [CarGuo/GSYVideoPlayer#3793]
如题，设置 isLooping=true 后，onAutoComplete 不会回调了，导致无法知道视频是否播放完成。

看了 issue，可以设置 GSYVideoProgressListener 监听，但有个问题是，不同长度的视频最后一次回调进度不一样，比如，对于时长 2s 的视频，最后一次回答的进度可能是 60%。这种方式感觉不是很可靠。

不知道有没有什么比较好的方式监听播放完成？

**Comment by CarGuo** [comment]
没有
