### ISSUE TITLE
手机竖屏时，点击全屏后，偶尔会出现左边黑色半透明

### ISSUE THREAD

**Issue by bear123445** [CarGuo/GSYVideoPlayer#3796]
## 问题描述：

手机竖屏时，播放器正常，点击全屏后，全屏页面偶尔会出现左边黑色半透明。
播放器，不设置封面图，使用的是继承ListGSYVideoPlayer，可以播放多个剧集。

## 问题机型/系统：

小米note2，vivo X Note

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:8.1.2

问题图片我上传一下。
![问题图片](https://user-images.githubusercontent.com/44198548/232951670-3d50b296-687d-4a1e-b0a0-349223072936.png)

**Comment by CarGuo** [comment]
不理解

**Comment by bear123445** [comment]
加了很多自己的内容，但是这个左边黑色半透明的内容，明显不是我加的内容，但是会偶尔出现，还不是必现。

**Comment by CarGuo** [comment]
那我也不知道怎么复线问题啊·······这····

**Comment by bear123445** [comment]
哎。我继续找问题，不知道有没有人遇到一样的问题
