### ISSUE TITLE
如何设置视频的虚化背景图？

### ISSUE THREAD

**Issue by XutongGithub** [CarGuo/GSYVideoPlayer#3797]
## 问题描述：

使用场景，横屏时播放竖版小视频，这时候视频周围是黑色的背景，如何把黑色背景换成虚化背景图片呢？

示例图片：
![DB7D3ACD89A9AF9138FE7ADF2F537A05](https://user-images.githubusercontent.com/13117057/233305820-766872d5-9268-4587-8d4c-a68cf681ad0a.jpg)

## 问题机型/系统：

真机 华为P30

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.5'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.5'

**Comment by CarGuo** [comment]
参考 https://github.com/CarGuo/GSYVideoPlayer/blob/af3becf7c69e19da602185d00715d266f2b712e0/app/src/main/java/com/example/gsyvideoplayer/effect/GSYVideoGLViewCustomRender4.java

**Comment by XutongGithub** [comment]
背景可以设置一张虚化图片吗 @CarGuo

**Comment by CarGuo** [comment]
可以，你自己写 GL

**Comment by XutongGithub** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/13117057/233888684-066f652d-b1cc-4807-ba0a-e9977dead82d.png">
这个demo有嘛

**Comment by CarGuo** [comment]
> 参考 https://github.com/CarGuo/GSYVideoPlayer/blob/af3becf7c69e19da602185d00715d266f2b712e0/app/src/main/java/com/example/gsyvideoplayer/effect/GSYVideoGLViewCustomRender4.java

@XutongGithub  不就是上面发的的这个么
