### ISSUE TITLE
 Unable to receive RTP payload type 96 without an SDP file describing it

### ISSUE THREAD

**Issue by james-gan** [CarGuo/GSYVideoPlayer#3799]
## 问题描述：

通过模拟 rtp流  ffmpeg -re -i 222.h264 -vcodec copy -f rtp rtp://192.168.31.150:5004>test_rtp_h264.sdp
播放rtp 时提示没SDP 代码已经加上了SDP描述啊
![image](https://user-images.githubusercontent.com/50664779/234335008-5bc67ba8-2c0f-48d9-bd49-2e4c0bea4d75.png)

代码已经加上了SDP的配置 
        String source1 = "rtp://192.168.31.150:5004";   
        videoPlayer.setUp(source1, true, "测试视频");   //这是设置的播放地址，配置SDP如下图
![image](https://user-images.githubusercontent.com/50664779/234336091-c6d9acfa-fad9-4755-b4b8-a1a870fb4f77.png)

## 问题机型/系统：
 真机 小米note2

**Comment by CarGuo** [comment]
服务端流配置问题，你在 ijk 写入没用，在流端描述

http://bashell.nodemedia.cn/archives/about-sdp-when-streaming-in-rtp-using-ffmpeg.html
