### ISSUE TITLE
demo在安卓7.0 api25下面运行有问题，会报libijkfmpeg.so text relocations 这个问题咋解决啊

### ISSUE THREAD

**Issue by seavman** [CarGuo/GSYVideoPlayer#38]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'. /data/app/com.example.gsyvideoplayer-1/lib/x86/libijkffmpeg.so has text relocations. This is wasting memory and prevents security hardening. Please fix. 这个直接导致了视频播放器语音和画面不在一同步了

**Comment by CarGuo** [comment]
降低你的target sdk等到23试试。

**Comment by seavman** [comment]
使用的就是您在github上面的demo，target sdk是22  在api23上面运行是正常的，就api25出问题了，不知道为啥

**Comment by CarGuo** [comment]
模拟器还是真机？

**Comment by seavman** [comment]
模拟机上面，android Emulator Nexus_5_API_25

**Comment by CarGuo** [comment]
这个最好试试真机，模拟器不怎么靠谱。

**Comment by seavman** [comment]
哎，真机没有刷到25的机子，T_T

**Comment by CarGuo** [comment]
![wechatimg1](https://cloud.githubusercontent.com/assets/10770362/21922266/ac5a44ea-d9a8-11e6-8364-503ba6eead68.jpeg)
刚刚下载了25的虚拟机，跑demo没问题哩～～～上图！这个还真的有可能你的虚拟机不大支持
