### ISSUE TITLE
播放器中显示的有返回键，切换全屏再切回来，返回键就消失了

### ISSUE THREAD

**Issue by wlxfxy** [CarGuo/GSYVideoPlayer#380]
用demo试过了，也是这样，用的最新版本，求解-_-

**Comment by CarGuo** [comment]
demo中哪个页面？？？

**Comment by CarGuo** [comment]
如果还有问题，可以直接隐藏点原本的，然后自己在布局上加上自己的

**Comment by wlxfxy** [comment]
WebDetailActivity中的，我设置webPlayer.getBackButton().setVisibility(View.VISIBLE)让其显示，切换全屏之后又消失了

**Comment by CarGuo** [comment]
onQuitFullscreen回调里再设置对应的title和back显示

**Comment by wlxfxy** [comment]
OK
