### ISSUE TITLE
播放大视频抛出异常

### ISSUE THREAD

**Issue by 15534408044** [CarGuo/GSYVideoPlayer#3803]
## 问题描述：

使用Exo/Ijk内核播放大视频抛出异常，1G以下没有问题。怀疑是服务器端返回range导致的，帮忙分析以下

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.3-release-jitpack'

    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.3-release-jitpack'

## Demo中的复现步骤

Demo也是一样的现象

## 问题log（如果有）
exo内核
服务器端日志
![图片](https://user-images.githubusercontent.com/44149326/236135279-2d30a73c-ec08-40ec-9edf-07242b6978b5.png)
App抛出的异常
![图片](https://user-images.githubusercontent.com/44149326/236135523-070ee88d-7c1e-4528-b332-dee48ef134dd.png)

ijk内核
服务器端日志
![图片](https://user-images.githubusercontent.com/44149326/236137032-bc0ba393-060d-4cdf-8b57-f09a241133df.png)
App抛出的异常
![图片](https://user-images.githubusercontent.com/44149326/236137389-36169450-a6e4-4cca-a5b7-bd4823cd0bf0.png)

**Comment by CarGuo** [comment]
看不出来

**Comment by 15534408044** [comment]
> 看不出来

![图片](https://user-images.githubusercontent.com/44149326/236174624-e6ad7c7a-0574-4733-a5da-fa26d866cd4d.png)
这个视频大小是5.83G，点击播放后返回的range:bytes=5816244894-  ,这种格式没问题嘛，我是小白不太清除，麻烦解惑。。但ios用ijkplayer可以播出来

**Comment by CarGuo** [comment]
有测试 url 嘛？

**Comment by 15534408044** [comment]
> 有测试 url 嘛？

我可以给你一个我测试用的Apk，你得先连接下我的设备，然后给你个url就可以用了

**Comment by 15534408044** [comment]
安装完这个apk后点击下第一个跳转到首页，然后用这个url：http://127.0.0.1:8384/rest/files/119/Video_97986.MP4

**Comment by CarGuo** [comment]
爱莫能助

**Comment by xuecq236** [comment]
大佬，您有时间的时候帮忙看一下，给个分析思路就行。主要现在基于这个库自定义了好多UI。。

**Comment by 15534408044** [comment]
视频总大小是：5825963530

**Comment by 15534408044** [comment]
![图片](https://user-images.githubusercontent.com/44149326/236391508-57b41d1b-f66c-4263-bb0b-4afbe627b50a.png)
视频总大小是：5825963530     第一次request range 大概是5821746274    两者相差大概是4M，但我们服务器这里每次contentlength只有3M。帮忙分析下是不是这个问题
![图片](https://user-images.githubusercontent.com/44149326/236391917-f9f030ab-a225-4dda-904e-34f01dbeb903.png)

**Comment by CarGuo** [comment]
具体特殊定制业务，我这边无法帮你分析，我只解决通用性质的问题，正常数据流，正常协议，正常封装，正常编码 ，对于特殊化的问题和自定义逻辑实现，只能你自己解决了～加油～！
