### ISSUE TITLE
播放视频流时占用内存会增加100多M

### ISSUE THREAD

**Issue by misszhouhaiyang** [CarGuo/GSYVideoPlayer#3804]
## 问题描述：

播放视频流时占用内存会增加100多M
![07960bfce51105917e7db85bfc783ea](https://github.com/CarGuo/GSYVideoPlayer/assets/45926868/38efa265-ddb4-4ca6-8a58-24de9f7ae0be)

## 出现问题的视频流

http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8

## 问题机型/系统：

android 7.0 模拟机 

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:v8.3.4-release-jitpack`

## Demo中的复现步骤

请问一下如何优化这个播放时内存占用过多的问题，谢谢

**Comment by misszhouhaiyang** [comment]
默认使用的软解码 IJK内核

**Comment by CarGuo** [comment]
没有
