### ISSUE TITLE
使用的exoplayer,已经通过simplecache缓存到本地了,怎么把缓存的视频导出到sd卡里面

### ISSUE THREAD

**Issue by sceneren** [CarGuo/GSYVideoPlayer#3811]
如题

**Comment by CarGuo** [comment]
simplecache 的格式不适合导出，如下图，存储格式是分块分段的非标准格式

![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/96dd3880-d83f-489c-9628-63f3467d4069)


![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/671dbb53-8dfd-4a95-9be9-9a02e1ed1dbd)

**Comment by sceneren** [comment]
是的,我就是在想能不能把缓存的分块的文件导出成一个完整的视频文件,如果缓存里没有就去下载

**Comment by sceneren** [comment]
好的 感谢

**Comment by lookdczar** [comment]
mark 有类似的需求
