### ISSUE TITLE
希望增加点击“开始播放”按钮回调方法，用来在点击播放按钮后，先处理项目的逻辑，然后再处理SDK播放逻辑

### ISSUE THREAD

**Issue by swanfly** [CarGuo/GSYVideoPlayer#3815]
或者修改GSYSampleCallBack#onStartPrepared返回类型为boolean
public void onStartPrepared(String url, Object... objects) {

}
改为：
public boolean onStartPrepared(String url, Object... objects) {
   return true;
}
onStartPrepared(...)返回为false时，不要处理播放逻辑

**Comment by CarGuo** [comment]
你 override  `clickStartIcon`  或者 `startButtonLogic` 方法就好了

**Comment by swanfly** [comment]
谢谢
