### ISSUE TITLE
关于ffmpeg版本的问题

### ISSUE THREAD

**Issue by 756230883** [CarGuo/GSYVideoPlayer#3818]
大佬您好  我看7.1.8版本的时候 已经将ijk  ffmpeg的版本升级到了4.0 
我们项目中使用的是 8.1.3版本中gsyVideoPlayer-ex_so 里的so库  被扫出FFmpeg版本低于3.3.2版本 请问这是什么情况呢

**Comment by CarGuo** [comment]
不知道，如下图

<img width="1353" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/48da3909-d4e3-4140-b4fa-becc4899d438">
