### ISSUE TITLE
在GSYVideoView中的init方法调用设置参数无效

### ISSUE THREAD

**Issue by Key-CN** [CarGuo/GSYVideoPlayer#3819]
## 问题描述：

在子类的init中设置一些参数会无效，比如setIsTouchWiget，setNeedShowWifiTip，setDismissControlTime等，未全部测试
在init走完之后，手动去设置，是有效的

## 出现问题的视频流

init流程如图
<img width="1031" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/23090834/81b057c9-74da-4ae4-8650-26dcd7009732">
<img width="467" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/23090834/5c3a267b-e2a9-4489-8c4f-30f7d9bf5447">

## 问题机型/系统：

所有机型

## GSY依赖版本

v8.3.5

**Comment by CarGuo** [comment]
你是不是用着 GSYVideoOptionBuilder ？

**Comment by Key-CN** [comment]
我确实有跟踪到这些值的赋值地方有GSYVideoOptionBuilder的build，但是我并没有使用，除非是默认在什么地方有调用，我的使用方式是 extends StandardGSYVideoPlayer，然后直接findViewById开始使用了，并没有调用GSYVideoOptionBuilder的build的地方，那我再跟一下看看

**Comment by Key-CN** [comment]
<img width="676" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/23090834/c93b9608-071f-4732-b3b6-f58f7e1eb4aa">
我打了断点并没有走进这个方法。
而且GSYVideoHelper中的startPlay()，虽然调用了build，但是这里的值应该也是在我赋值之后的了，很奇怪，我现在完全找不到这个值在什么地方被修改的。

**Comment by CarGuo** [comment]
我也不理解， 我大概理解的场景就是 View 构建完之后， 在  GSYVideoHelper or  GSYVideoOptionBuilder  的  build 调用可能会有这样的情况导致重置
