### ISSUE TITLE
求助啊,视频只有声音,没有图像?

### ISSUE THREAD

**Issue by ZengHongHua** [CarGuo/GSYVideoPlayer#382]
这是视频地址:http://www.ppbar.com.cn/20170817/797a9a10-10db-4d38-b07a-0a9dbce37bd0.mp4
这个视频下载下来是正常的,在网页上也没图像,不知道是不是少了什么编码设置呢?
下面是设置的属性,还有什么要设置的吗
final String url = Config.URL_SHARE + shareInfo.getVedioPath();

        //默认缓存路径
        holder.gsyVideoPlayer.setUp(url, true, null, title);

        //增加title
        holder.gsyVideoPlayer.getTitleTextView().setVisibility(View.VISIBLE);
        holder.gsyVideoPlayer.getTitleTextView().setText(title);

        //设置返回键
        holder.gsyVideoPlayer.getBackButton().setVisibility(View.GONE);

        //设置全屏按键功能
        holder.gsyVideoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                resolveFullBtn(holder.gsyVideoPlayer);
            }
        });
        holder.gsyVideoPlayer.setRotateViewAuto(true);
        holder.gsyVideoPlayer.setLockLand(true);
        holder.gsyVideoPlayer.setPlayTag("123456");
        holder.gsyVideoPlayer.setShowFullAnimation(true);
        //循环
        //gsyVideoPlayer.setLooping(true);
        holder.gsyVideoPlayer.setNeedLockFull(true);
        //gsyVideoPlayer.setSpeed(2);
        holder.gsyVideoPlayer.setPlayPosition(position);

**Comment by CarGuo** [comment]
使用第三种依赖模式

**Comment by CarGuo** [comment]
ex so

**Comment by CarGuo** [comment]
如果还不行具体看看视频编码是什么

**Comment by ZengHongHua** [comment]
改为第3种,可以了,确实是编码问题,多谢大佬
