### ISSUE TITLE
能否升级下依赖库（okhttp androidx 阿里云播放器... 等等），很多都是老版本了

### ISSUE THREAD

**Issue by jyh149129** [CarGuo/GSYVideoPlayer#3821]
如题

**Comment by CarGuo** [comment]
okhttp 等基本都没在库里使用，只是demo，无所谓

**Comment by dengyunlin** [comment]
> okhttp 等基本都没在库里使用，只是demo，无所谓

AliyunPlayer 都升到7.2.0 了，能否升级一下

**Comment by CarGuo** [comment]
@dengyunlin  ok，下个版本更新，主要是因为aliyun之前是第三方 pr 过来的，所以没太注意
