### ISSUE TITLE
exo模式下播放某个音频会出现播放进度大于总时长的情况

### ISSUE THREAD

**Issue by 756230883** [CarGuo/GSYVideoPlayer#3822]
## 问题描述：

exo模式下播放某个音频会出现播放进度大于总时长的情况

## 出现问题的视频流

https://oss.nbs.cn/M00/22/E4/wKhkDmPZ1uSAJWFwAlYRLUW4gK0892.mp3

## 问题机型/系统：

例如 真机 华为p30 pro

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.5-release-jitpack

## Demo中的复现步骤

在demo中  “输入URl” 输入此音频地址
![fbf44ed8a4291b69bb236318d0046cc](https://github.com/CarGuo/GSYVideoPlayer/assets/9440937/2ac49614-b931-474c-879e-a4c404f7c6c0)

**Comment by CarGuo** [comment]
无解
