### ISSUE TITLE
请问如何能获得exo的ExoPlaybackException异常？

### ISSUE THREAD

**Issue by kiddkyd2** [CarGuo/GSYVideoPlayer#3824]
## 问题描述：

我想获得exo的具体异常，而不是总是弹出source error。根据exo的源码来看，ExoPlayer类下有一个getPlayerError的方法，可以返回异常。请问怎么可以获得这个东西呢？

我试过通过重写setVideoAllCallBack(new GSYSampleCallBack()里面的onPlayError(String url, Object... objects)，但是这个地方获得的是objects[1]这个播放器，不知怎么可以通过这个属性来获得我要的ExoPlaybackException类型异常。

我也试过重写Player.Listener里面的onPlayerError(PlaybackException error)，但是出错后，并没有进入这个监听。

## GSY依赖版本

 `com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.4-release-jitpack'`

**Comment by CarGuo** [comment]
已经提交支持，下版本发布

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/commit/fe5e69e7af366ab8b8479a78f8eeedec2e87ad29
