### ISSUE TITLE
Custom screenshot

### ISSUE THREAD

**Issue by darcheville** [CarGuo/GSYVideoPlayer#3825]
Hi,

thank you for this wonderful library.
I would like to make a screenshot of the video view currently on the screen of type StandardGSYVideoPlayer, the method taskShotPic works very well, but sends me the entire surface of the video as a bitmap. I only want to have the part of the video contained in the phone window (the pinch to zoom sometimes causes the video to go beyond the limits of the screen). If I try to use Bitmap.createBitmap(rootView.width, rootView.height, Bitmap.Config.ARGB_8888) I have my ui on the bitmap but the video on the bitmap is black. Is there a parameter to have the video displayed on the bitmap when I use Bitmap.createBitmap(rootView.width, rootView.height, Bitmap.Config.ARGB_8888) please?

thank you in advance for your return

**Comment by CarGuo** [comment]
I am not very sure about the issue scene, but I understand that because the video is drawn on the surface, you can only extract the image from the surface
