### ISSUE TITLE
小米平板闪屏，其他机型正常

### ISSUE THREAD

**Issue by mxdldev** [CarGuo/GSYVideoPlayer#3828]
小米平板 MI PAD 3  
android 版本：7.0
MIUI版本：10.2
开始播放就一直闪屏，全屏之后播放正常，退出全屏模式播放也是正常的，不知道是怎么回事？

**Comment by CarGuo** [comment]
不理解

**Comment by mxdldev** [comment]
> 不理解

就是播放画面一直闪烁，全屏播放正常，退出全屏播放正常

**Comment by CarGuo** [comment]
设置 GSYVideoType.setRenderType(GSYVideoType.SUFRACE); 试试？

**Comment by mxdldev** [comment]
> 设置 GSYVideoType.setRenderType(GSYVideoType.SUFRACE); 试试？

谢谢大佬 ，好了

**Comment by hanling0** [comment]
我也遇到这个问题 了 设置 GSYVideoType.setRenderType(GSYVideoType.SUFRACE); 也没用
