### ISSUE TITLE
使用Demo，测试m3u8有画面没声音，如何解决

### ISSUE THREAD

**Issue by yecaler** [CarGuo/GSYVideoPlayer#3831]
## 问题描述：

使用Demo，测试m3u8有画面没声音，如何解决

## 出现问题的视频流

http://dbiptv.sn.chinamobile.com/PLTV/88888888/224/3221226395/1.m3u8

## 问题机型/系统：

  HUAWEI nova youth

## GSY依赖版本

git 最新版运行的

## Demo中的复现步骤

修改视频地址后，有画面，没有声音

**Comment by CarGuo** [comment]
链接打不开，没有声音确定你的视频音频编码是什么
