### ISSUE TITLE
如何实现左侧上下滑动调节音量

### ISSUE THREAD

**Issue by HeyBean-X** [CarGuo/GSYVideoPlayer#3833]
## 问题描述：

 右侧滑动可调节亮度，但是在左侧滑动为什么还是调节亮度。我想实现左侧滑动调节音量 请问要如何实现 谢谢~

## 问题机型/系统：

所有设备

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:8.1.2'

**Comment by CarGuo** [comment]
override touchSurfaceMove / touchSurfaceMoveFullLogic
