### ISSUE TITLE
下载到本地以后编译失败

### ISSUE THREAD

**Issue by wuxueshuan** [CarGuo/GSYVideoPlayer#3834]
下载了zip包以后在本地使用studio打开编译的时候报以下错误，没有截全一共9个这种的，这怎么就解决！！

Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':gsyVideoPlayer-base:generateDebugRFile'.
> Could not resolve all files for configuration ':gsyVideoPlayer-base:debugCompileClasspath'.
   > Could not download GSYIjkJava-1.0.0.aar (com.github.CarGuo:GSYIjkJava:1.0.0)
      > Could not get resource 'https://jitpack.io/com/github/CarGuo/GSYIjkJava/1.0.0/GSYIjkJava-1.0.0.aar'.
         > Could not GET 'https://jitpack.io/com/github/CarGuo/GSYIjkJava/1.0.0/GSYIjkJava-1.0.0.aar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not download DanmakuFlameMaster-0.9.25.aar (com.github.CarGuo.DanmakuFlameMaster:DanmakuFlameMaster:0.9.25)
      > Could not get resource 'https://jitpack.io/com/github/CarGuo/DanmakuFlameMaster/DanmakuFlameMaster/0.9.25/DanmakuFlameMaster-0.9.25.aar'.
         > Could not GET 'https://jitpack.io/com/github/CarGuo/DanmakuFlameMaster/DanmakuFlameMaster/0.9.25/DanmakuFlameMaster-0.9.25.aar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download ndkbitmap-armv7a-0.9.25.aar (com.github.CarGuo.DanmakuFlameMaster:ndkbitmap-armv7a:0.9.25)
      > Could not get resource 'https://jitpack.io/com/github/CarGuo/DanmakuFlameMaster/ndkbitmap-armv7a/0.9.25/ndkbitmap-armv7a-0.9.25.aar'.
         > Could not GET 'https://jitpack.io/com/github/CarGuo/DanmakuFlameMaster/ndkbitmap-armv7a/0.9.25/ndkbitmap-armv7a-0.9.25.aar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download ndkbitmap-x86-0.9.25.aar (com.github.CarGuo.DanmakuFlameMaster:ndkbitmap-x86:0.9.25)
      > Could not get resource 'https://jitpack.io/com/github/CarGuo/DanmakuFlameMaster/ndkbitmap-x86/0.9.25/ndkbitmap-x86-0.9.25.aar'.
         > Could not GET 'https://jitpack.io/com/github/CarGuo/DanmakuFlameMaster/ndkbitmap-x86/0.9.25/ndkbitmap-x86-0.9.25.aar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download ndkbitmap-armv5-0.9.25.aar (com.github.CarGuo.DanmakuFlameMaster:ndkbitmap-armv5:0.9.25)
      > Could not get resource 'https://jitpack.io/com/github/CarGuo/DanmakuFlameMaster/ndkbitmap-armv5/0.9.25/ndkbitmap-armv5-0.9.25.aar'.
         > Could not GET 'https://jitpack.io/com/github/CarGuo/DanmakuFlameMaster/ndkbitmap-armv5/0.9.25/ndkbitmap-armv5-0.9.25.aar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download GSYIjkJava-1.0.0.aar (com.github.CarGuo:GSYIjkJava:1.0.0)
      > Could not get resource 'https://jitpack.io/com/github/CarGuo/GSYIjkJava/1.0.0/GSYIjkJava-1.0.0.aar'.
         > Could not GET 'https://jitpack.io/com/github/CarGuo/GSYIjkJava/1.0.0/GSYIjkJava-1.0.0.aar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

**Comment by CarGuo** [comment]
你那边网络问题，我这边刚点了链接，都是正常存在的包

<img width="383" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/5029c6af-22ab-41fd-996e-130128c3da5d">
