### ISSUE TITLE
兼容androidTV老版本，去除androidx，手动改代码 使用android.support，最高可以到哪个版本。

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#3835]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

大佬，有个需求，要兼容androidTV老版本，想直接代码引入，手动改代码用android.support，最高可以用哪个版本改。

**Comment by CarGuo** [comment]
7.0 开始的 androidx ， https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/UPDATE_VERSION.md
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/e1e057f7-fd1c-4df5-b65e-74e06ffcec88)
