### ISSUE TITLE
Flutter集成原生SDK，原生SDK封装了播放器，在列表里面滑动到视频位置，开始播放视频，视频会跑到页面最顶部和最上面，挡住底部view，不播放视频就没有问题，请问这可能是什么原因导致？

### ISSUE THREAD

**Issue by TeamCircleSDK** [CarGuo/GSYVideoPlayer#3836]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

Flutter集成原生SDK，原生SDK封装了播放器，在列表里面滑动到视频位置，开始播放视频，视频会跑到页面最顶部和最上面，挡住底部view，不播放视频就没有问题，请问这可能是什么原因导致？

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.5-release-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不知道，sdk 没考虑过 flutter 场景，flutter 场景播放视频建议 ffi 或者外界纹理

**Comment by TeamCircleSDK** [comment]
建议 ffi 或者外界纹理，请问这个有代码参考或者链接吗？

**Comment by CarGuo** [comment]
官方的 video_player 就是用 外界纹理 Texture

**Comment by TeamCircleSDK** [comment]
SampleCoverVideo在onLayout加上判断就解决了这个问题，但又出现视频有声音没画面
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/114135053/00d24dfe-8f72-483a-b997-804a9f5f8aa1)
