### ISSUE TITLE
日志打印问题

### ISSUE THREAD

**Issue by Piscen** [CarGuo/GSYVideoPlayer#3839]
IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
        Debuger.disable()；
设置了不顶用，找了一圈，好多人都有这个问题，但是解决了以后都不说人话，到底怎么设置？？？？

**Comment by CarGuo** [comment]
正常官方提供的就是   `IjkMediaPlayer.native_setLogLevel(IJK_LOG_SILENT);` ， 对应就是 `IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);` ，如果你觉得不行，可以参考 https://github.com/CarGuo/GSYVideoPlayer/issues/881

**Comment by Piscen** [comment]
所以其实是编译的so文件问题？
