### ISSUE TITLE
# main(1) java.lang.IllegalStateException mpjni: seekTo: null mp

### ISSUE THREAD

**Issue by jinguangyue** [CarGuo/GSYVideoPlayer#384]
1 tv.danmaku.ijk.media.player.IjkMediaPlayer.seekTo(Native Method)
--
2 com.shuyu.gsyvideoplayer.GSYVideoPlayer.onTouch(GSYVideoPlayer.java)
3 com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.onTouch(StandardGSYVideoPlayer.java)
4 android.view.View.dispatchTouchEvent(View.java:10082)
5 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2646)
6 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2320)
7 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2652)
8 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
9 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2652)
10 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
11 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2652)
12 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
13 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2652)
14 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
15 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2652)
16 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
17 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2652)
18 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
19 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2652)
20 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
21 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2652)
22 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
23 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:438)
24 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1820)
25 android.app.Activity.dispatchTouchEvent(Activity.java:3224)
26 android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java)
27 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:392)
28 android.view.View.dispatchPointerEvent(View.java:10306)
29 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4914)
30 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4693)
31 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4195)
32 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4255)
33 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4214)
34 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4363)
35 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4222)
36 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4420)
37 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4195)
38 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4255)
39 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4214)
40 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4222)
41 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4195)
42 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6761)
43 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6735)
44 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6696)
45 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6868)
46 android.view.ViewRootImpl$ColorWindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8127)
47 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
48 android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
49 android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
50 android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6835)
51 android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6891)
52 android.view.Choreographer$CallbackRecord.run(Choreographer.java:878)
53 android.view.Choreographer.doCallbacks(Choreographer.java:690)
54 android.view.Choreographer.doFrame(Choreographer.java:619)
55 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:864)
56 android.os.Handler.handleCallback(Handler.java:751)
57 android.os.Handler.dispatchMessage(Handler.java:95)
58 android.os.Looper.loop(Looper.java:185)
59 android.app.ActivityThread.main(ActivityThread.java:6473)
60 java.lang.reflect.Method.invoke(Native Method)
61 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
62 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)

**Comment by CarGuo** [comment]
这个问题真心郁闷，ijk底层空了外层却不知道，而且没办法复现。

**Comment by CarGuo** [comment]
新版本内部加了catch
