### ISSUE TITLE
列表滑动无缝播放下一集

### ISSUE THREAD

**Issue by AlceZhang** [CarGuo/GSYVideoPlayer#3841]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
你好,问下，我现在使用的是m3u8的视频格式，为了实现抖音类似的效果，所以我使用是ConcatenatingMediaSource方式来实现无缝切换下一集，但是上滑时，如何将上一个视频放入到下一个使用容器显示？
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
不是很理解，我这边不处理实际业务需求

**Comment by AlceZhang** [comment]
不好意思，有点着急，不是描述的很清楚。首先我这边用的是ViewPager2来实现的（全屏），使用ConcatenatingMediaSource方式来无缝切换下一集，当我滑动列表时，调用了next()方法播放下一集，但并不是在我当前显示的页面播放，而是在离屏的那个页面进行了下一集播放。我想请教下，如何将下一集的内容显示在我当前的页面或者如何将mSurface切换到当前显示页面，还是有其他方式，不知道此番描述是否清楚，望回复~

**Comment by CarGuo** [comment]
简单来说这个实现不合理，你调用 next 的地方是在上一页的 view ，按照这个思路 gsy 上是无法支持你这种实现

**Comment by AlceZhang** [comment]
好的，感谢您的及时回复，已知晓。为了实现滑动无缝切换（预加载），已经试过了DetailDownloadPlayer方式与DetailExoListPlayer ，因为现使用是M3u8，所以DetailDownloadPlayer方式的代理缓存不支持。DetailExoListPlayer 方式又满足不了需要，所以现在只剩下多播放器来实现嘛

**Comment by CarGuo** [comment]
新版本你更新了一个 DetailDownloadExoPlayer ，可以大概了解下

**Comment by AlceZhang** [comment]
已使用。感谢~

**Comment by AlceZhang** [comment]
你好，再次打扰。现在使用DetailDownloadExoPlayer 方式缓存m3u8，但是我看缓存的文件大小都只有4kb左右看状态就提示缓存成功了。第一个问题，针对m3u8的视频，都是缓存这么大小嘛？ 第二个问题，后面缓存中更多的出现缓存失败，异常提示 ”IllegalStateException  Task failed: null:56c6bd9cd341bd6fc18a37debe8e2b48, false“

**Comment by CarGuo** [comment]
exo 的缓存是分很多分片区完成的，不会是和源文件一样，至于错误从log上看不出来，目前这个 demo 只是一个示例参考，具体可能需要你自己调试下，比如用它的 Service 模式

**Comment by AlceZhang** [comment]
是的，m3u8是分很多分片完成的。但是我还有一个疑问，m3u8不支持setCacheWithPlay(true)的设置，我的理解是当设置了setCacheWithPlay（true）时，会先根据这个设置缓存的路径读取缓存文件，如果没有则请求网络。但是m3u8设置setCacheWithPlay后会无法播放，我看此方法的注释也是不支持m3u8。所以，它的如何去读取缓存的呢？注释：已设置 ：    PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)
CacheFactory.setCacheManager(ExoPlayerCacheManager::class.java)

**Comment by CarGuo** [comment]
不，我的意思是，ExoPlayerCacheManager 就算是一个mp4文件，它也会分成无数小段落进行缓存

**Comment by AlceZhang** [comment]
哦，那就缓存模式区别，跟文件类型无关。但我这还是没有针对M3u8格式文件的预缓存方式实现方式。楼上你说使用 Service 模式方式，是指DownloadService嘛？还有请教下，您觉得针对m3u8格式的文件，做一个类似抖音的效果，为了流畅，使用预加载，gsy有什么比较组合的模式嘛？（这几天我把各种缓存方式都看了一遍，好像对MP4合适的比较友好）

**Comment by CarGuo** [comment]
m3u8 其实不适合类似（抖音）模式做缓存，因为你考虑一下，如果其中某个 ts 异常，或者缓存出现 seek ，然后来回切换的时候，这个就很尴尬。

抖音模式主要是提前缓存视频的前几秒内容，你需要一个额外的全局拉流服务来做这个，DownloadService 开一个 Serivice 的方式会更稳定，并且不受其他影响

**Comment by AlceZhang** [comment]
了解，学习了，谢谢您这几日及时的反馈与耐心的解答，受益匪浅。
