### ISSUE TITLE
使用setuplazy设置数据源时，封面图不会显示

### ISSUE THREAD

**Issue by jyh149129** [CarGuo/GSYVideoPlayer#3842]
看源码setuplazy并没有切换ui的动作，是bug还是设计就是如此？谢谢！
版本： 8.4.0

**Comment by CarGuo** [comment]
参考 demo 的 SampleCoverVideo 来实现封面图逻辑

**Comment by jyh149129** [comment]
@CarGuo 还有个问题使用setuplazy设置数据源，切换为全屏时，标题文字不会显示
