### ISSUE TITLE
提问：关于自定义内核 内核是View 而不是Surface

### ISSUE THREAD

**Issue by ZhuSky** [CarGuo/GSYVideoPlayer#3846]
第三方播放内核是View形式返回，请问BasePlayerManager 有支持View形式加入嘛？

我看目前showDisplay 返回的是surface 而不是ViewGroup

**Comment by CarGuo** [comment]
没有，第三方接入参考 https://github.com/CarGuo/GSYVideoPlayer/tree/master/gsyVideoPlayer-aliplay

**Comment by ZhuSky** [comment]
感谢大佬
