### ISSUE TITLE
使用Exo内核，在android TV上播放M3U8视频每几秒就要卡顿缓冲

### ISSUE THREAD

**Issue by BushLee** [CarGuo/GSYVideoPlayer#3847]
你好，

问题描述：

使用Exo内核，在android TV上播放M3U8视频每几秒就要卡顿缓冲，但是在电脑网页和android statuio模拟其上都不会卡，能确定的是我的电脑的网速绝对没有电视环境块。

出现问题的视频流

https://top.qoqkkhy.com/202307/21/7pc3PMc0rZ3/video/index.m3u8

问题机型/系统：

电视是海信电视，android版本：9 api 28，模拟器版本：api 34

GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.4.0-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.4.0-release-jitpack'

问题代码：(如果有)

（集成自StandardGSYVideoPlayer做了一些点击监听）
SunGSYVideoPlayer videoPlayer = (SunGSYVideoPlayer)findViewById(R.id.video_player);
PlayerFactory.setPlayManager(Exo2PlayerManager.class);
CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_16_9);
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
GSYVideoType.enableMediaCodecTexture();

最后问题：

我翻看了issue里面关于卡的问题，您给出的基本都是换EXO内核，然后由的说是使用surface+打开硬解码，我都设置了，但是放到电视上就是不停的卡，感觉就是缓冲的很少几秒，播放完在缓冲就会卡。想咨询一下是否是什么更好的解决办法。

关于复现：

问题就是在电视上运行的时候就会出现，在模拟器上问题就很少卡顿。

**Comment by CarGuo** [comment]
EXO 内核，我见到来说，用的就是 MediaCodec ，MediaCodec不是特别严谨来说，用的就是硬解码， 硬解码 严格来说，就是和你设备硬件有关系
