### ISSUE TITLE
多次重复操作 会导致需要点击开始开始播放按钮

### ISSUE THREAD

**Issue by mynameisliuyurong** [CarGuo/GSYVideoPlayer#3848]
## GSY依赖版本  8.3.5
多次重复操作（开始播放 -退出页面-点击其他类型的播放器） 重复操作   会导致 之后需要点击两次播放按钮才可以正常播放。
复现 在demo 上  华为 小米

视频是在demo上复现的。

https://github.com/CarGuo/GSYVideoPlayer/assets/30228287/7405768c-2386-4abf-9a7f-602cbd784116

**Comment by CarGuo** [comment]
因为 release 有时候会有个时间差，具体类似 https://github.com/CarGuo/GSYVideoPlayer/issues/2475#issuecomment-567336200 ，出现暂停的可能性可以调试是否 onPrepared 之后，触发了  `!mStartAfterPrepared ` ，setStateAndUi(CURRENT_STATE_PAUSE); 就三处地方调用
