### ISSUE TITLE
Demo中的WebDetailActivity播放视频后，退出然后再进入，出现内存泄露，请看截图

### ISSUE THREAD

**Issue by chunca** [CarGuo/GSYVideoPlayer#385]
![screenshot_2017-08-20-11-15-37-514_com example gs](https://user-images.githubusercontent.com/13847079/29491792-131254ba-8599-11e7-8c6e-bb7cb539451d.png)

**Comment by chunca** [comment]
使用的版本：    compile 'com.shuyu:gsyVideoPlayer-java:2.0.4'
    compile 'com.shuyu:gsyVideoPlayer-armv5:2.0.4'
    compile 'com.shuyu:gsyVideoPlayer-armv7a:2.0.4'

**Comment by CarGuo** [comment]
请尝试2.0.5
