### ISSUE TITLE
设置isLooping是true，播放2s时长的视频，从startPlayLogic到onPrepared方法用了11s

### ISSUE THREAD

**Issue by darrenfantasy** [CarGuo/GSYVideoPlayer#3850]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
使用Exo2PlayerManager，
设置isLooping是true，播放2s时长的视频，从startPlayLogic到onPrepared方法用了11s的时间，感觉这块有问题，如果不设置isLooping，则从startPlayLogic到onPrepared方法用了3s的时间

## 问题机型/系统：

真机 小米6

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.4-release-jitpack'

**Comment by CarGuo** [comment]
引文关键帧，2s视频，出了网络 cdn 影响因素，更多是视频是因为解码需要的 GOP 有问题导致，建议你可以看下： https://juejin.cn/post/7057132141875822622

**Comment by darrenfantasy** [comment]
有几点疑问：
使用Exo2PlayerManager，不使用isLooping属性，差不多3s能加载出来，使用isLooping需要11s差不多。
使用SystemPlayerManager,不管是否使用isLooping属性，差不多2s能加载出来。
因为我这个是在启动app的时候就启动，是否有可能受到其他资源占用影响。
我们可以在子线程去做setPlayManager，setUp和startPlayLogic处理吗？

**Comment by darrenfantasy** [comment]
设置最大缓冲时长，exoplayer默认好像60s；如果设置了循环播放，即使视频数据只有15s, 内存中也是加载60s数据的。（解决： MediaPeriodQueue#MAXIMUM_BUFFER_AHEAD_PERIODS 修改为2，最多只填充2个视频数据）

**Comment by CarGuo** [comment]
> 有几点疑问：
> 使用Exo2PlayerManager，不使用isLooping属性，差不多3s能加载出来，使用isLooping需要11s差不多。
> 使用SystemPlayerManager,不管是否使用isLooping属性，差不多2s能加载出来。
> 因为我这个是在启动app的时候就启动，是否有可能受到其他资源占用影响。
> 我们可以在子线程去做setPlayManager，setUp和startPlayLogic处理吗？

用 isLooping 和不用 isLooping，区别在于 exo 都设置了一个 setRepeatMode 选项，system 和 exo 核心都是 mediacodec 所以在加载行为会是一样的，区别在于 system 的 mediaplayer 是直接设置的 loop （native call） ，但是 exo 的 setRepeatMode 是通过一个内部 handler queue 去实现

**Comment by CarGuo** [comment]
> MAXIMUM_BUFFER_AHEAD_PERIODS

MAXIMUM_BUFFER_AHEAD_PERIODS 默认是 100 ，并且是他是 final ，不可以修改的

![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/5bdac039-b43c-4896-987a-5caf5bc9ce35)

![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/6e1acfd1-48b1-46fd-a38d-8e47e1ec2038)

**Comment by darrenfantasy** [comment]
> 
嗯，现在遇到就是设置了isLooping后变慢了，不知道有什么解决方案

**Comment by CarGuo** [comment]
具体为什么慢我也盲猜不出来，2s 的视频或者你还是用 system 模式吧

**Comment by darrenfantasy** [comment]
> 具体为什么慢我也盲猜不出来，2s 的视频或者你还是用 system 模式吧

System的加载快，但是真实播放起来效果还是exo的好，system播起来看着有点卡🤣
