### ISSUE TITLE
Error pinging server (attempts: 3, max timeout: 280)

### ISSUE THREAD

**Issue by GostGrimmy** [CarGuo/GSYVideoPlayer#3851]
⚠️
在使用了exo内核，读取dash视频后出现
```Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, report at https://github.com/danikula/AndroidVideoCache/issues/134. Default proxies are: [DIRECT]```

然后视频无法播放
好像本项目依赖库com.danikula:videocache有点问题
但不清楚怎么解决

**Comment by CarGuo** [comment]
dash 不支持 videocache 模式，把 cache 设置为 false 试试

**Comment by GostGrimmy** [comment]
好的，谢谢
