### ISSUE TITLE
如何获取播放视频的实际大小

### ISSUE THREAD

**Issue by androidforzhenghyc** [CarGuo/GSYVideoPlayer#3853]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我这边需要根据视频的实际大小来展示不同的页面效果，
如果通过通过currentVideoWidth和currentVideoHeight得到的1080*1080，但是视频实际的大小应该是720*1080（就是指画面的宽，不包含黑边的宽度，ios获取到的就是720*1080）.
查看往期的issue时，有提到用mShowView去获取，但是获取时机要在什么时候呢，我在VideoAllCallBack的onPrepared里是null的

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.4-release-jitpack'

## Demo中的复现步骤

问题代码：(如果有)

**Comment by CarGuo** [comment]
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/d47b1462-b805-4d25-9262-b798f21de556)

![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/a472832c-2c1c-4d62-9783-efc0a22612f5)

目前都是通过播放内核返回的

**Comment by androidforzhenghyc** [comment]
> ![image](https://user-images.githubusercontent.com/10770362/260674346-d47b1462-b805-4d25-9262-b798f21de556.png)
> 
> ![image](https://user-images.githubusercontent.com/10770362/260674409-a472832c-2c1c-4d62-9783-efc0a22612f5.png)
> 
> 目前都是通过播放内核返回的，你用的什么内核

用的IjkPlayerManager内核

**Comment by androidforzhenghyc** [comment]
那我要在什么时机去获取才是准确的呢？

**Comment by CarGuo** [comment]
IjkPlayerManager 内核，那



            GSYVideoManager.instance().getVideoWidth();
            GSYVideoManager.instance().getCurrentVideoWidth();


就是内核里读取到的大小啊，你有测试链接没

**Comment by androidforzhenghyc** [comment]
> IjkPlayerManager 内核，那
> 
> ```
>         GSYVideoManager.instance().getVideoWidth();
>         GSYVideoManager.instance().getCurrentVideoWidth();
> ```
> 
> 就是内核里读取到的大小啊，你有测试链接没，时机一般是 onPrepared

http://192.168.101.24:8030/article/18/20230614_1d50f6ae4a0c428da1d7c167f6f1f074.mp4 
大佬可以用这个测试看看。
 我用 GSYVideoManager.instance().getVideoWidth();
 GSYVideoManager.instance().getCurrentVideoWidth();
拿到的都是1080-1080

**Comment by CarGuo** [comment]
192.168 ····· 你这是内网地址···

**Comment by androidforzhenghyc** [comment]
> 192.168 ····· 你这是内网地址···

大佬我错了，
https://source.jinsubao.cn/article/74/20230803_54363386a05241ae9f8943a405f3c9a4.mp4
这个是线上视频

**Comment by androidforzhenghyc** [comment]
> 192.168 ····· 你这是内网地址···

-。- 不过好像不是同一个视频，大佬可以看看

**Comment by CarGuo** [comment]
如⬇️三张图，没发现问题啊

<img width="853" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/dee774d0-2b4a-462f-a2e8-b32244586354">


<img width="1179" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/d2840b50-193c-4678-93c5-17bc37887771">

<img width="241" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/72f2d4d4-1f0e-4c78-b888-c014ab5384ba">

**Comment by androidforzhenghyc** [comment]
> 如⬇️三张图，没发现问题啊
> 
> <img alt="image" width="853" src="https://user-images.githubusercontent.com/10770362/260874985-dee774d0-2b4a-462f-a2e8-b32244586354.png"> <img alt="image" width="1179" src="https://user-images.githubusercontent.com/10770362/260875113-d2840b50-193c-4678-93c5-17bc37887771.png"> <img alt="image" width="241" src="https://user-images.githubusercontent.com/10770362/260875521-72f2d4d4-1f0e-4c78-b888-c014ab5384ba.png">

我把那个有问题的视频地址给大佬
https://sourcedm.jinsubao.cn/article/3/20230816_20bb51d88bd842d08d31a5832b8e1bcb.mp4
视频下载下来看本地尺寸是1080-1080的，但是画面的尺寸是720-1080(大概哈)，画面的尺寸是指这个视频是竖屏的，不算黑边的尺寸

**Comment by CarGuo** [comment]
如图  1080 x 2332 啊 ，你新给的那个链接


<img width="862" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/2fd8edef-bb8a-4625-9005-7ec7d08c68e1">

**Comment by androidforzhenghyc** [comment]
> https://sourcedm.jinsubao.cn/article/3/20230816_20bb51d88bd842d08d31a5832b8e1bcb.mp4

=。= 好吧，估计可能是之前测试的时候视频资源有问题，后面有问题，我再咨询大佬
