### ISSUE TITLE
如何播放本机视频？

### ISSUE THREAD

**Issue by EmptyPages** [CarGuo/GSYVideoPlayer#3857]
本机的视频文件如何播放，现在一般只能获取到本机文件的Uri，但是没有看到gsy有相关api方法支持

**Comment by CarGuo** [comment]
看 demo 的 DetailPlayer https://github.com/CarGuo/GSYVideoPlayer/blob/91cfb7132387ac241c6fdc26bf810ffc5df2d658/app/src/main/java/com/example/gsyvideoplayer/DetailPlayer.java#L588
