### ISSUE TITLE
最新版demo播放这个视频卡顿，音画面不同步，ijk内核

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#3860]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

最新版demo播放这个视频卡顿，音画面不同步，ijk内核。

## 出现问题的视频流

**以下视频流 ，如果视频流地址失效了，可以从这里再获取**  ：http://106.14.121.90:8013/api/play/get

https://bj29-hz.cn-hangzhou.data.alicloudccp.com/ZO9qtXFv%2F990625012%2F6505ad5e4af8ba75d0a144ea869721eac948e38f%2F6505ad5e5e1c62e71fa64d7fb5bceb43635a98e3?di=bj29&dr=831631603&f=650d5c444b85fb24895f4f54a2f5faded1938d31&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5aDLtnOpap1xfO%2BWmfm0WI0TrxKhZHO1Tz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNQ2nCWCTqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABAOMYRDs6BCUxZXKFWYLhaAmstF5cHsfkQjeTpo0%2BpqPRctDhQeVOoKcR8UVb1uHUbIR4c0X%2BYG4ofyEtXoS2kwf2JS9J3WjIzLnpT%2Fr5WhzdAg0cRO3vNitdQHsHmNURbFIDvl%2Blge6Yot838sf6pbmPgSVrzFHo9uweCH48CeogAA%3D%3D&u=254808010963075794&x-oss-access-key-id=STS.NU6eczHuTr1UXAW5baB3fjTe7&x-oss-expires=1695375304&x-oss-signature=KAlQWwCtaMqEY0qeH9joUMqC%2BFSSusnz44rtze73QP4%3D&x-oss-signature-version=OSS2

## 问题机型/系统：

例如 真机 小米9

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.4.0'`

## Demo中的复现步骤

简单视频播放，填入上面视频流即可复现

**Comment by CarGuo** [comment]
你和这个是 webm （mkv） 格式？目前看起来是分辨率太高了，导致软解码 cpu 跟不上，硬解码因为 hevc 和其他 encoder 解析不出来

   /// 开启后设备可能会无法硬解码 hevc
    VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-hevc", 1);


  ///这个不起作用
  VideoOptionModel videoOptionModel2 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);

**Comment by renwfy** [comment]
我试试大佬说的，

另外还有什么方案吗，网络上有的播放器可以流程播，

**Comment by renwfy** [comment]
现在都在支持高清4k视频流，上面这个是阿里云盘的高清源

**Comment by CarGuo** [comment]
目前奇怪的地方是，我的设备硬解码应该是支持 h265 的
，但是不知道为何会是如下情况
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/b5a45bd1-ed86-4ec1-bea1-e7d14ce81b6d)


建议转换为 Mp4 的 4k 然后使用 Exo2PlayerManager 模式内核 的硬解码试试，应该可以解决问题

**Comment by renwfy** [comment]
建议转换为 Mp4 的 4k  ？  

求教这是怎么操作，GSYVideoPlayer 支持着功能，还是怎么操作？

**Comment by CarGuo** [comment]
GSY 不支持，你需要自己后台转换

**Comment by renwfy** [comment]
后台转换 代价有点大，只能先放弃这类视频了
