### ISSUE TITLE
加载实时视频流显示出画面比较慢

### ISSUE THREAD

**Issue by yuyingfeng1989** [CarGuo/GSYVideoPlayer#3863]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

加载实时视频显示画面比较慢，大概需要8秒才会显示出视频，用PC加载同一实时视频1秒左右就能加载出来，请问需要在哪里进行修改，能够让视频能够更快加载出画面。

## 出现问题的视频流
视频流：rtmp://47.243.112.208:19350/realTime/00000000018000414348_2

## 问题机型/系统：

例如 真机 三星手机，华为手机 Android11系统

## GSY依赖版本

原生引入SDK库：gsyVideoPlayer-java`    gsyVideoPlayer-base

## Demo中的复现步骤
每次加载都需要等待8秒左右才能显示视频

问题代码：(如果有)

采用默认播放配置进行播放实时视频

## 问题log（如果有）

```



```

**Comment by CarGuo** [comment]
看问题集锦，自己调调参数

**Comment by yuyingfeng1989** [comment]
参数尝试了一些，好像都没什么效果，请问下重点集中在那几个参数上进行修改，我也看了下问题紧急好像与我这个情况相似的没看到，辛苦指引下，谢谢。

**Comment by yuyingfeng1989** [comment]
不知道是不是我修改的参数没有修改到正确的位置，还是没有找对地方修改，目前依然加载比较慢，但是加载其他非直播视频加载比较快。
