### ISSUE TITLE
这个怎么实现，长按快进播放，长按时左右拖动切换倍数

### ISSUE THREAD

**Issue by AlanTse1314** [CarGuo/GSYVideoPlayer#3866]
![7A703AF8-5852-4BDF-9AD3-D5163416632D](https://github.com/CarGuo/GSYVideoPlayer/assets/88262891/96eb224a-89c8-429e-b772-210d3049edba)

https://github.com/CarGuo/GSYVideoPlayer/assets/88262891/96eb224a-89c8-429e-b772-210d3049edba

**Comment by CarGuo** [comment]
touchLongPress 和  touchSurfaceMove 自己 override 自定义
