### ISSUE TITLE
java.lang.NoClassDefFoundError: com.shuyu.gsyvideoplayer.GSYVideoManager

### ISSUE THREAD

**Issue by ljhUncle** [CarGuo/GSYVideoPlayer#387]
java.lang.NoClassDefFoundError: com.shuyu.gsyvideoplayer.GSYVideoManager
android 4.4 报上面的错误，作者知道什么原因吗，谢谢 @CarGuo @PureDark

**Comment by CarGuo** [comment]
看看是否超了64K方法数量或者打包问题，这是编译打包的问题

**Comment by PureDark** [comment]
不是、我就提交过一次PR，为啥每次都要at我、

**Comment by WooYu** [comment]
@ljhUncle 怎么 解决的这个问题

**Comment by ali-bagheri** [comment]
I too have this issues.

**Comment by ali-bagheri** [comment]
i use blew library.

https://repo.spring.io/libs-release/com/shuyu/GSYVideoPlayer/6.0.3/
https://repo.spring.io/libs-release/com/shuyu/gsyVideoPlayer-java/6.0.3/
https://repo.spring.io/libs-release/com/shuyu/gsyVideoPlayer-base/6.0.3/

if used proguard:

# gsy videoplayer
-keep class com.shuyu.gsyvideoplayer.** { *; }
-keep class com.shuyu.gsyvideoplayer.video.** { *; }

but i have problem.

**Comment by CarGuo** [comment]
@ali-bagheri 

-keep class com.shuyu.gsyvideoplayer.video.** { *; }
-dontwarn com.shuyu.gsyvideoplayer.video.**
-keep class com.shuyu.gsyvideoplayer.video.base.** { *; }
-dontwarn com.shuyu.gsyvideoplayer.video.base.**
-keep class com.shuyu.gsyvideoplayer.utils.** { *; }
-dontwarn com.shuyu.gsyvideoplayer.utils.**
-keep class tv.danmaku.ijk.** { *; }
-dontwarn tv.danmaku.ijk.**

-keep public class * extends android.view.View{
    *** get*();
    void set*(***);
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}
