### ISSUE TITLE
拉流播放时，拖动进度条，会一直卡在加载界面，如何解决？

### ISSUE THREAD

**Issue by YuQi9797** [CarGuo/GSYVideoPlayer#3871]
## 问题描述：

⚠️ 播放拉流视频时，如果有意拖动进度条，会一直卡在加载界面。 如果只是单纯播放视频，而不是去拖动进度条就啥事儿没有，也能看视频。

请问有谁知道如何解决吗？

**Comment by CarGuo** [comment]
拉流视频的时候你隐藏进度条和停止手势 seek 呗

**Comment by YuQi9797** [comment]
> 拉流视频的时候你隐藏进度条和停止手势 seek 呗

请问在哪里进行设置隐藏即手势seek？ 麻烦指明下 ， 感谢！

**Comment by CarGuo** [comment]
setIsTouchWiget false ，然后 getLayoutId 自己布局里去掉进度条就好了

**Comment by YuQi9797** [comment]
> getLayoutId

作者您好，目前我设置了：
```
mBinding.videoPlayerView.setIsTouchWiget(false);
mBinding.videoPlayerView.setIsTouchWigetFull(false);
```
关于隐藏进度条，原生的是否能够去掉？  还是说我必须去自定义一个类去继承GSYVideoControlView，然后使用`dismissProgressDialog` ?

**Comment by CarGuo** [comment]
Demo 有个 EmptyControlVideo ，你参考下
