### ISSUE TITLE
如果服务器没办法配置，那么你可以通过ijkplayer的ffplay定制修改，主要是buffer，追帧，同步等

### ISSUE THREAD

**Issue by oldTomatoCN** [CarGuo/GSYVideoPlayer#3873]
如果服务器没办法配置，那么你可以通过ijkplayer的ffplay定制修改，主要是buffer，追帧，同步等

_Originally posted by @CarGuo in https://github.com/CarGuo/GSYVideoPlayer/issues/1910#issuecomment-476449093_
            
请问这里服务器配置具体指的什么？

**Comment by CarGuo** [comment]
很多，举个例子：

优化服务器策略

播放器接入服务器请求数据的时间点的视频不一定是关键帧，那么需要等到下一个关键帧的到来，如果关键帧的周期是 2s 的话，那么等待的时间可能会在 0~2s 的范围内，这段等待的时间会影响首屏的加载时间。
如果服务器有缓存，则播放端在接入的时候，服务器可以向前找最近的关键帧发给播放端，这样就可以省去等待的时间，可以大大的减少首屏的加载时间。

具体可见： https://www.zhihu.com/tardis/bd/art/519132587?source_id=1001



另外还有不同芯片不同网络环境，提供不同码率适配，配置视频源  GOP 长度，逻辑上优化策略，比如选择性丢帧，不影响编码画质的前提下减轻传输体积。
