### ISSUE TITLE
R8full Mode开启导致无法播放

### ISSUE THREAD

**Issue by asker517** [CarGuo/GSYVideoPlayer#3874]
AGP8.0+  R8fullMode 默认开启之后,在调用```PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式```时会因为```SystemPlayerManager```被混淆,可能是r8fullMode会移除无用默认构造器导致无法被创建

混淆规则理论上应该要添加对应混淆规则
-keep class com.shuyu.gsyvideoplayer.player.** {*;}

**Comment by CarGuo** [comment]
ok ，已经补充
