### ISSUE TITLE
返回页面黑屏问题

### ISSUE THREAD

**Issue by xxxnnnxxxnnn** [CarGuo/GSYVideoPlayer#3875]
师傅您好，我发现了一个bug，在app播放的过程中，直接返回桌面，打开其它视频播放软件，播放视频后，再次返回我的app，此时视频播放器为黑屏状态，且无法正常播放。此问题不仅只有我的app会出现，我测试过您提供的demo也是存在同样的问题，希望您能给出解决方案，谢谢！

**Comment by CarGuo** [comment]
setReleaseWhenLossAudio(false);
