### ISSUE TITLE
加载中滑动到后台无法播放

### ISSUE THREAD

**Issue by xxxnnnxxxnnn** [CarGuo/GSYVideoPlayer#3877]
## 问题描述：
师傅您好，我在使用GSYVideoPlayer播放视频的时候，进度条拉动后触发加载，在加载的时候快速把app滑到后台，即不可见的状态，然后返回app，此时播放状态为暂停状态，请问有解决方案让他不暂停吗？

**Comment by CarGuo** [comment]
确定是否调用了 onVideoPause

**Comment by xxxnnnxxxnnn** [comment]
您好，搜索发现是有调用,是不能调用吗？

**Comment by xxxnnnxxxnnn** [comment]
师傅您好，确定调用了onVideoPause，我现在已经将调用代码注释了，如果我不调用是否有其他问题出现？

还有一个问题，当我双击暂停后，再次双击播放时，如果双击的是播放器的左边，亮度会降低到最低，如果是播放器的右边双击就是把声音降低到了最低，请问有解决方案吗？

**Comment by CarGuo** [comment]
自己看demo 是 api 文档
