### ISSUE TITLE
关于在ViewPager2中进行滑动，滑出和滑入之后进行暂停/恢复的问题

### ISSUE THREAD

**Issue by ForeverYoungWJ** [CarGuo/GSYVideoPlayer#3878]
## 问题描述：

ViewPager2中，每个容器里都放了一个播放器，继承StandardGSYVideoPlayer，首次加载完vp2，监听vp2滑动回调事件，在第一个item中先点击播放，然后滑到第二个item，此时将第一个item中正在播放的进行暂停，然后在第二个item中点击播放，再次滑回第一个item，此时点击播放的时候，没有从上一次暂停的地方继续播放，而是重新开始播放了，希望从上一次的播放位置继续播放

## 出现问题的视频流

PlayerFactory.setPlayManager(SystemPlayerManager::class.java)

## 问题机型/系统：

无关机型/系统

## GSY依赖版本

"com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.4.0-release-jitpack"

问题代码：(如果有)

VP2的适配器代码：

class BannerImageAdapter(
    val context: Context, mData: List<BannerInfoResult>
) : BannerAdapter<BannerInfoResult, RecyclerView.ViewHolder?>(mData) {

    companion object {
        const val TAG = "BannerImageAdapter"
    }

    init {
        PlayerFactory.setPlayManager(SystemPlayerManager::class.java)
        GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL)
    }

    override fun getItemViewType(position: Int): Int {
        return 3//getRealData().elementAtOrNull(position)?.bannerType?.toInt() ?: BannerType.IMAGE.type
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
        return if (viewType == BannerType.IMAGE.type) {
            val imageView = ImageView(parent.context)
            val params = ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT
            )
            imageView.layoutParams = params
            imageView.scaleType = ImageView.ScaleType.CENTER_CROP
            BannerImageHolder(imageView)
        } else {
            BannerVideoHolder(
                DataBindingUtil.inflate(
                    LayoutInflater.from(parent.context),
                    R.layout.list_item_mall_good_detail_video_banner,
                    parent,
                    false
                )
            )
        }
    }

    override fun onBindView(
        holder: RecyclerView.ViewHolder?, data: BannerInfoResult, position: Int, size: Int
    ) {
        if (holder is BannerImageHolder) {
            holder.imageView.let {
                Glide.with(context).load(data.mediaUrl).placeholder(
                    if (isMall) {
                        R.drawable.ic_mall_banner_img_placeholder
                    } else {
                        R.drawable.ic_community_banner_img_placeholder
                    }
                ).into(it)
            }
        } else {
            val videoHolder = holder as BannerVideoHolder
            videoHolder.dataBinding.detailVideoBanner.apply {
                playPosition = position
                playTag = TAG
                loadCoverImage(data.mediaUrl)
                setUpLazy(data.videoUrl, true, null, null, "")
            }
        }
    }
}

class BannerImageHolder(view: View) : RecyclerView.ViewHolder(view) {
    var imageView: ImageView = view as ImageView
}

class BannerVideoHolder(var dataBinding: ListItemMallGoodDetailVideoBannerBinding) :
    RecyclerView.ViewHolder(dataBinding.root)

---------------监听VP2滑动----------------

override fun onPageSelected(position: Int) {
                    if (GSYVideoManager.instance().playTag == BannerImageAdapter.TAG) {
                        (banner.getViewPager()?.getChildAt(0) as? RecyclerView)?.layoutManager?.let { layoutManager ->
                            val videoView = layoutManager.findViewByPosition(previousPosition)?.findViewById<DetailBannerVideo>(R.id.detailVideoBanner)
                            videoView?.let {
                                // 如果上一个在播放中，就执行暂停
                                if (videoView.currentState == CURRENT_STATE_PLAYING) {
                                    videoView.currentPlayer.onVideoPause()
                                }
                            }
                             //  更新上一个item的position
                            val currentItem = banner.getViewPager()?.currentItem
                            currentItem?.let {
                                previousPosition = currentItem
                            }
                        }
                    }
                }

请问大佬，该如何解决？能否提供个思路？非常感谢

**Comment by CarGuo** [comment]
setSeekOnStart 

如果是默认播放内核模式，还可以用



注意，这个是全局地设置，设置之后如果不需要需要清除这个item。
```
VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", startPosition);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
```
