### ISSUE TITLE
关于播放过程中，网络异常，网络恢复后，没有从上次的进度继续播放，而是重新开始播放了

### ISSUE THREAD

**Issue by ForeverYoungWJ** [CarGuo/GSYVideoPlayer#3879]
## 问题描述：

关于播放过程中，网络异常，网络恢复后，没有从上次的进度继续播放，而是重新开始播放了

## 出现问题的视频流
IjkPlayerManager

## GSY依赖版本
implementation "com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.4.0-release-jitpack"

看了demo中模拟了这种情况，demo在网络恢复正常之后，点播放按钮也是重新开始播放了，并没有从上次中断的地方接着播放，大佬有没有解决方案

**Comment by CarGuo** [comment]
需要你自己在异常时记录为止，恢复时重新设置 setSeekOnStart  ，如果是网络环境发生改变的，内部会通过 createNetWorkState 里的监听，然后在 error 时 netWorkErrorLogic
