### ISSUE TITLE
一段时间播放后手机开始发烫，该怎么解决？

### ISSUE THREAD

**Issue by lk2017** [CarGuo/GSYVideoPlayer#3881]
您好！我们做了类似抖音的功能，播放10多分钟后，手机开始发烫。我开始以为是代码的写法上存在问题，后来我用demo中最普通的方式进行单个循环播放，播放时去掉了存本地以此来模拟一直拉流的过程，结果10多分钟后手机同样开始发烫，该怎么解决这一问题？不胜感激。

**Comment by CarGuo** [comment]
很正常，根据视频码率的不同，播放内核和播放模式的不同，设备硬件支持的不同，软解码和硬解码的配置不同，都会有不同的能耗情况，发热属于正常现象。

尝试降低视频码率，开启硬解码等方式大概会有所缓解，但是发热这个，你开微信小程序或者UC玩一段时间都可能会发烫
