### ISSUE TITLE
m3u8视频  ijk内核播放失败，exo内核可以播放

### ISSUE THREAD

**Issue by jzh1996** [CarGuo/GSYVideoPlayer#3882]
## 问题描述：

m3u8视频  ijk内核播放失败，exo内核可以播放

## 出现问题的视频流

https://m3u8.wenluedu.com/8DLJ81FQSV3i3QjpTGXr-1697549784.m3u8?pm3u8/0&e=1698144552&token=z2wdwl6QcFSlrRtYwowaIez7sxqv1YUETTrCK1LG:e4UFluhZHvA5C6a26OpeSkKR6uo=

## 问题机型/系统：

华为mate50 小米11 vivo OPPO都有这个问题

## GSY依赖版本

8.4.0-release-jitpack

## Demo中的复现步骤
header头中加入Proof：f1219041bec5b3094e72d5eb019923ba

问题代码：(如果有)

## 问题log（如果有）
Error when loading first segment 'https://m3u8.wenluedu.com/m3u8/1697550174/cm-000000.ts?e=1698180652&token=z2wdwl6QcFSlrRtYwowaIez7sxqv1YUETTrCK1LG:QpwVyC34k9kLAHyMN8S2jo9x6-0

https://m3u8.wenluedu.com/iYW401nbYFWYp67Iums4-1697550174.m3u8?pm3u8/0&e=1698144651&token=z2wdwl6QcFSlrRtYwowaIez7sxqv1YUETTrCK1LG:JPwFCVozZ51KP2wXcBn2BprdZPE=: Invalid data found when processing input
E  Error (-10000,0)

**Comment by CarGuo** [comment]
crypto+https://m3u8.wenluedu.com/m3u8/1697549784/cm-000000.ts?e=1698182178&token=z2wdwl6QcFSlrRtYwowaIez7sxqv1YUETTrCK1LG:AxBalg3ZH3GbIPMFg1nAm2RP3eQ' for reading


Failed to open segment 0 of playlist 0


初步看起来，是因为解密 key 的 https://push.chamiedu.com/video/auth/check ，需要 Proof：f1219041bec5b3094e72d5eb019923ba ，而 ijkplayer 对于 x-key 的请求，没有添加 header ，所以获取不到，所以目前看来是因为解密失败，这个需要你自己改 ijk 的动态库去适配，或者调整你 x-key  的策略

**Comment by jzh1996** [comment]
麻烦问下有相关的示例代码或者文章吗
