### ISSUE TITLE
RTMP直播流关闭，收不到回调

### ISSUE THREAD

**Issue by larryluo1212** [CarGuo/GSYVideoPlayer#3883]
## 问题描述：

播放RTMP直播流，如果直播流关闭，收不到回调

## 出现问题的视频流
//本地RTMP流
 String url = "rtmp://10.0.2.2:1935/live1/room";

## 问题机型/系统：

Android 13,OPPO X3 Pro

## GSY依赖版本

  //视频播放
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.4.0-release-jitpack'

    //是否需要ExoPlayer模式
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.4.0-release-jitpack'

    //根据你的需求ijk模式的so
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:v8.4.0-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-x86:v8.4.0-release-jitpack'

## Demo中的复现步骤
直播流是我本地搭建的流媒体本地拉取，推送一个本地的MP4，比如说20s，视频结束后，拉去的视频卡在最后一帧，我希望直播结束，有一个回调比如是setVideoAllCallBack里面的onComplete之类的，然后我在这个回调关闭activity或者展示其他的UI

问题代码：(如果有)
  //本地流
        String url = "rtmp://10.0.2.2:1935/live1/room";

        //true 缓存视频
        binding.videoPlayer.setUp(url, false, "");
        binding.videoPlayer.setGSYStateUiListener(new GSYStateUiListener() {
            @Override
            public void onStateChanged(int state) {
                Log.e(TAG,"onStateChanged 11111111 " + state);
            }
        });
        binding.videoPlayer.setVideoAllCallBack(new GSYSampleCallBack(){

            @Override
            public void onPlayError(String url, Object... objects) {
                super.onPlayError(url, objects);
                stopAnim();
                Log.e(TAG,"onPlayError 11111111");
                binding.videoPlayer.setVisibility(View.GONE);
                binding.liveInfo.setVisibility(View.VISIBLE);
            }

            @Override
            public void onPrepared(String url, Object... objects) {
                super.onPrepared(url, objects);
                stopAnim();
            }

            @Override
            public void onStartPrepared(String url, Object... objects) {
                super.onStartPrepared(url, objects);
                startAnim();
            }

            @Override
            public void onAutoComplete(String url, Object... objects) {
                super.onAutoComplete(url, objects);
                Log.e(TAG,"onAutoComplete 11111111");
                binding.videoPlayer.setVisibility(View.GONE);
                binding.liveInfo.setVisibility(View.VISIBLE);
            }

            @Override
            public void onComplete(String url, Object... objects) {
                super.onComplete(url, objects);
                Log.e(TAG,"onComplete 11111111");
                binding.videoPlayer.setVisibility(View.GONE);
                binding.liveInfo.setVisibility(View.VISIBLE);
            }

        });
        binding.videoPlayer.startPlayLogic();

使用的是无控制UI的EmptyControlVideo，因为是直播，所以不需要控制按钮
public class EmptyControlVideo extends StandardGSYVideoPlayer {

    public EmptyControlVideo(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

    public EmptyControlVideo(Context context) {
        super(context);
    }

    public EmptyControlVideo(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public int getLayoutId() {
        return R.layout.empty_control_video;
    }

    @Override
    protected void touchSurfaceMoveFullLogic(float absDeltaX, float absDeltaY) {
        super.touchSurfaceMoveFullLogic(absDeltaX, absDeltaY);
        //不给触摸快进，如果需要，屏蔽下方代码即可
        mChangePosition = false;

        //不给触摸音量，如果需要，屏蔽下方代码即可
        mChangeVolume = false;

        //不给触摸亮度，如果需要，屏蔽下方代码即可
        mBrightness = false;
    }

    @Override
    protected void touchDoubleUp(MotionEvent e) {
        //super.touchDoubleUp();
        //不需要双击暂停
    }
}

## 问题log（如果有）

无

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2891#issuecomment-670289750
