### ISSUE TITLE
播放绿幕视频的时候，有没有办法，把绿幕换成透明背景？

### ISSUE THREAD

**Issue by wflian** [CarGuo/GSYVideoPlayer#3885]
## 问题log（如果有）
播放绿幕视频的时候，有没有办法，把绿幕换成透明背景？

**Comment by CarGuo** [comment]
不能

**Comment by wflian** [comment]
透明背景 这个功能有吗？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/3327#issuecomment-878000066
