### ISSUE TITLE
调用release后，不会黑屏，保持了显示播放最后一个画面

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#3886]
## 问题描述：

使用了GSYSampleADVideoPlayer，播放器调用release后，不会黑屏，保持了显示播放最后一个画面。理论上，应该会黑屏才对吧

## 问题机型/系统：

真机 华为 mate 30 pro、真机 vivo Z1

## GSY依赖版本

`implementation 'com.shuyu:GSYVideoPlayer:8.1.2'`

我想要release后黑屏的效果，但居然不会黑屏

**Comment by CarGuo** [comment]
应该是某个情况下 surface 没有释放，所以lock了最后一帧
