### ISSUE TITLE
playback speed limit

### ISSUE THREAD

**Issue by zohaibmushwani** [CarGuo/GSYVideoPlayer#3887]
Hi, I tried to speed up the video using this library it has a max of 2.0x I need 10x speed is this possible to increase the limit?

I am developing the front end for slow-motion curve view module in android, the video needs to be played segment by segment, and the change of speed will occur after the time taken by the segment in their associated speed.
if any alternative solution anyone can suggest.
Thanks in advance

**Comment by CarGuo** [comment]
No support, this is related to the synchronization clock. Currently, audio is used as the synchronization clock

**Comment by zohaibmushwani** [comment]
I have developed a custom curve view that provides speed values, and I'm using an FFmpeg wrapper in an Android application to apply these speed values to video segments. The primary goal is to enable variable playback speed for video segments in our front-end application. I've explored a few options, and I'm urgently seeking a solution due to a specific challenge I'm facing.

1. ExoPlayer: I initially considered ExoPlayer, which offers a wide range of playback speeds, from 0.1x to 10x. However, I encountered an issue where I couldn't change the speed beyond a certain point. Specifically, I observed an error related to the operating rate in the logs.

2. IJKPlayer with DKVideoPlayer: I also tried using the DKVideoPlayer, which relies on the IJKPlayer framework. However, I found that it has a maximum speed limit of 6x and also cannot set the speed as urgently required.

3. GSYVideoPlayer with IJKPlayer: Another framework I experimented with is GSYVideoPlayer, which also employs IJKPlayer. However, GSYVideoPlayer's maximum playback speed range is limited to 2.0x. I even attempted to integrate ExoPlayer within GSYVideoPlayer, but the same speed issue persisted as with the original Media3 SDK.

In light of these challenges, I'm seeking advice or a solution that would allow me to achieve variable video playback speeds in real-time. Your assistance in resolving this matter would be greatly appreciated.

**Comment by CarGuo** [comment]
I think you can only modify the support through the source code of ijkplayer, because Media3 and ExoPlayer used MediaCodec.

Ijkplayer is based on ffmpeg, and you can modify the synchronous clock mode of the source code to support magic modification. By sacrificing the experience, I currently do not have the requirement to achieve 10x on the playback end
Editors may need to, but players generally support 2x, up to 4x
