### ISSUE TITLE
依赖完成，编译过程中提示v4包发生冲突。视频中的v4包可以改吗？？？

### ISSUE THREAD

**Issue by zjsa** [CarGuo/GSYVideoPlayer#389]
Error:Execution failed for task ':social_sdk_library_JDPlazz:compileReleaseJavaWithJavac'. > Could not expand ZIP 'D:\zjh\proj.android-studio\social_sdk_library_JDPlazz\libs\android-support-v4.jar'.

**Comment by zjsa** [comment]
尝试compile ('com.shuyu:GSYVideoPlayer:2.0.4'){
        exclude group: "com.android.support", module: "support-v4"
    }
exclude v4包，编译通过，运行之后，崩溃了

**Comment by CarGuo** [comment]
崩溃log是？
