### ISSUE TITLE
请教下关于播放本地m3u8文件的 一些问题

### ISSUE THREAD

**Issue by zhhach123** [CarGuo/GSYVideoPlayer#3890]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：  
      目前有个需求需要播放移动硬盘里的M3U8本地文件，加密的key和ts文件都存在了移动硬盘里，需求是不能修改移动硬盘中的文件，只能读取，目前m3u8文件格式如下：
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:18
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="http://127.0.0.1:8040/encrypt.key",IV=0xf1f135c20ba510a732edeefa9499cd55
#EXTINF:13.080000,
0.ts

这种格式的该如何定位到这个encrypt.key的文件路径呢

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/3522

**Comment by zhhach123** [comment]
你好，我按上面的问题设置好了参数，但仍然无法播放
`  PlayerFactory.setPlayManager(IjkPlayerManager.class);
        videoPlayer = (StandardGSYVideoPlayer) findViewById(R.id.video_player);
        String source1 = Environment.getExternalStorageDirectory() + "/genwoxueyufa12/01/index.m3u8";
        VideoOptionModel videoOptionModel =
            new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "crypto,file,http,https,tcp,tls,udp");
        VideoOptionModel videoOptionModel2 =
            new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_extensions", "ALL");
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        list.add(videoOptionModel2);
        GSYVideoManager.instance().setOptionModelList(list);`
这是参数设置的代码
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:18
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="file://storage/emulated/0/genwoxueyufa12/encrypt.key",IV=0xf1f135c20ba510a732edeefa9499cd55
#EXTINF:13.080000,
0.ts
`
这是m3u8的文件
`2023-11-22 14:27:37.148 14843-15324 IJKMEDIA                com.example.gsyvideoplayer           I  HLS request for url '/storage/emulated/0/genwoxueyufa12/01/0.ts', offset 0, playlist 0
2023-11-22 14:27:37.148 14843-15324 IJKMEDIA                com.example.gsyvideoplayer           I  Opening 'file://storage/emulated/0/genwoxueyufa12/encrypt.key' for reading
2023-11-22 14:27:37.152 14843-15324 IJKMEDIA                com.example.gsyvideoplayer           E  Unable to open key file file://storage/emulated/0/genwoxueyufa12/encrypt.key
2023-11-22 14:27:37.152 14843-15324 IJKMEDIA                com.example.gsyvideoplayer           I  Opening 'crypto:/storage/emulated/0/genwoxueyufa12/01/0.ts' for reading
2023-11-22 14:27:37.152 14843-15324 IJKMEDIA                com.example.gsyvideoplayer           W  Failed to open segment 0 of playlist 0`
报错Unable to open key file
