### ISSUE TITLE
RTMP直播流断网重连

### ISSUE THREAD

**Issue by larryluo1212** [CarGuo/GSYVideoPlayer#3895]
## 问题描述：

做直播，RTMP协议，部分客户手机看直播的时候看一会有时候播放会停止，画面就不动了，重新进入就可以了，我猜测是网络抖动导致，尝试直播的时候关闭网络，画面停止，但是恢复网络后没有重新播放直播，请教大佬在哪里可以处理异常重连？

翻了一下issue，到ijkplayer项目下面，找到可以使用ijkhttphook处理断网重连，但是我在url前面加上，直播流没有播放，去掉就可以播放，我搜索了一下，大佬源码里面设置了监听

<img width="773" alt="Pasted Graphic" src="https://github.com/CarGuo/GSYVideoPlayer/assets/49664952/dcf3a2d8-a2c4-4c3f-b6f6-125238e9b593">

<img width="1021" alt="Pasted Graphic 1" src="https://github.com/CarGuo/GSYVideoPlayer/assets/49664952/7121b6bc-5cc1-408d-bcf4-42bb3cc3580a">

## 出现问题的视频流
[
## 问题机型/系统：

OPPO X3 Pro ，Android13

## GSY依赖版本

` implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.4.0-release-jitpack'`

## Demo中的复现步骤
<img width="892" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/49664952/9472845d-3de1-4cf5-84d3-c89c3b8845b1">

**Comment by CarGuo** [comment]
有没有一种可能，就说一种可能····· ijkhttphook，里面的 http 说的是 http 协议·····

**Comment by larryluo1212** [comment]
> RTMP

是的，大佬是对的，RTMP里面短线重连有办法吗

**Comment by CarGuo** [comment]
建议你参考我这个，然后断网了，新建一个 manager 做无缝替换，类似 SmartPickVideo 里面那样


![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/f3ac2839-10b9-43ef-ab19-a3c7c2059474)
