### ISSUE TITLE
网络视频地址不能播放，浏览器可以正常播放

### ISSUE THREAD

**Issue by liudouliangliu** [CarGuo/GSYVideoPlayer#3898]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

网络视频地址不能播放，浏览器可以正常播放

## 出现问题的视频流

https://oss.hanentropy.com:38612/buckets/objects/downloads?secret=5xr4HpYNCXr50Eaj49kxqv7vSsj51sL6jGJbXi6L%2B6YtrfSR%2Fr358GZsaFb4axA7

## 问题机型/系统：

所有真机

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.5.0-release-jitpack
com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:v8.5.0-release-jitpack

**Comment by CarGuo** [comment]
<img width="1383" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/b6da5f1a-225e-413c-97cd-98cc6a802079">

你这个视频的容器编码，音频编码和视频编码是啥？ 看起来不是正常的兼容模式

<img width="667" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/4f4923ea-37d0-45f4-98b5-5431a828194e">


建议你整为 MP4 容器协议，播放 H264 应该没问题，而且视频看起来没有 Audio ，目前这个状态无法兼容播放
