### ISSUE TITLE
部分机型播放视频时长信息加载完毕，视频却没有播放

### ISSUE THREAD

**Issue by lihaodong** [CarGuo/GSYVideoPlayer#3899]
## 问题描述：

部分机型播放视频时长信息加载完毕，视频却没有播放。由于是线上出现，尝试复线无法复线，视频流也是mp4的。

## 出现问题的视频流
https://source.yiboshi.com/CourseWareMp4/faebc1838655541701a64a415c138b70_sd.mp4

## 问题机型/系统：

ViVO X10 Pro

## GSY依赖版本
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.5-release-jitpack'
    //是否需要ExoPlayer模式
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.4.0-release-jitpack'

## 出现问题的录屏
http://q35xuko5t.bkt.clouddn.com/QQ%E8%A7%86%E9%A2%9120231209194628.mp4

**Comment by lihaodong** [comment]
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.5-release-jitpack'
//是否需要ExoPlayer模式
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.5-release-jitpack'

**Comment by CarGuo** [comment]
这么抽象，我也不知道怎么看啊，理论上，如果加载出时长，说明 header 等信息解析成功，无法播放，可能是解码音视频的时候出错了

**Comment by lihaodong** [comment]
目前想的是换个内核试试。问题通过录屏看出来是有问题，最近几天出的问题都是vivo手机，官网真机模拟也没有问题

**Comment by CarGuo** [comment]
可以去找网上云真机调试下看看说明问题
