### ISSUE TITLE
建议在init mediaplayer的时候，可以自己设置option选项

### ISSUE THREAD

**Issue by blackbbc** [CarGuo/GSYVideoPlayer#39]
某些视频需要将safe选项变成0才能播放：
IjkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "safe", 0)
您已经把mediaPlayer封装好了
但是能不能提供一个函数用以在初始化mediaplayer的时候设置option呢

**Comment by CarGuo** [comment]
嗯，我后面看看怎么加上合适。

**Comment by CarGuo** [comment]
今天更新的版本已经加上。
