### ISSUE TITLE
关于切页面回来从头播放的问题

### ISSUE THREAD

**Issue by zhuyu1022** [CarGuo/GSYVideoPlayer#3900]
## 问题描述：

竖屏时暂停，再横屏时点击暂停，切到其他页面再切回来，视频从头播放了

## GSY依赖版本

V8.5.0

## Demo中的复现步骤
1、点击带控制demo
2、点击播放，播放个十秒左右
3、再点击暂停
4、点击全屏
5、切到后台
6、在切回来，从头播放了

http://pan.bozedu.net/index.php?share/file&user=108&sid=7mPGE5Hx

问题代码：(如果有)
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/24352070/b338e6af-ecb3-4d68-8ff1-5751b8317ea4)

打断点发现这个位置的 mCurrentPosition  拿到的是0

**Comment by zhuyu1022** [comment]
更正一下，关于问题代码部分我描述错了，不是拿到的是0 ，是不走这个判断所以是0，因为视频处于暂停状态，getGSYVideoManager().isPlaying()为false，我觉得mCurrentPosition的值，不应该判断视频是否是播放状态吧？

**Comment by CarGuo** [comment]
临时解决方式，继承 player  ，override  cloneParams ，例如：

    @Override
    protected void cloneParams(GSYBaseVideoPlayer from, GSYBaseVideoPlayer to) {
        super.cloneParams(from, to);
        SampleControlVideo sf = (SampleControlVideo) from;
        SampleControlVideo st = (SampleControlVideo) to;
        st.mCurrentPosition =  sf.mCurrentPosition;
    }
