### ISSUE TITLE
全屏状态下切换视频 黑屏 

### ISSUE THREAD

**Issue by 912334508** [CarGuo/GSYVideoPlayer#3901]
## 问题描述：

orientationUtils.resolveByClick(); 全屏后 切换视频 出现黑屏的情况 UI也卡住  demo中试过全屏下切换也会出现异常 无法播放

## 出现问题的视频流

任何视频

## 问题机型/系统：

三星 s22u os 13

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.5.0-release-jitpack'

## Demo中的复现步骤

切换到横屏全屏 在切换另一个视频

**Comment by CarGuo** [comment]
demo 的  DetailListPlayer 测试正常

**Comment by CarGuo** [comment]
Demo  DetailListPlayer 测试正常，比如在 onCreate 加入以下代码，播放，全屏，等一会，正常

     new Handler().postDelayed(new Runnable() {
         @Override
         public void run() {
             ((ListGSYVideoPlayer)binding.detailPlayer.getCurrentPlayer()).playNext();
         }
     }, 5000);
