### ISSUE TITLE
库无法引入到项目中

### ISSUE THREAD

**Issue by octobergld** [CarGuo/GSYVideoPlayer#3903]
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.5.0-release-jitpack'

也不报错，不知道为什么

在libraries下没又找到

我尝试胡乱写一个版本号，还是不报错
第一次遇到这样的情况，查看各种日志也没有报错信息，怎么解决

**Comment by CarGuo** [comment]
不理解····测试正常

![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/bed7305f-1fe0-487d-a9e9-4dddfcb656f2)
