### ISSUE TITLE
exo模式解析视频时长失败，无法快进

### ISSUE THREAD

**Issue by allentown521** [CarGuo/GSYVideoPlayer#3904]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

exo模式解析视频时长失败（显示-12:55），也无法快进

## 出现问题的视频流

(https://video.twimg.com/amplify_video/1734290524079603712/vid/avc1/1280x708/XMxnpskKGmX1YVoc.mp4?tag=14)

## 问题机型/系统：
真机 一加ace2和模拟器 Android13

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.5.0'`

## Demo中的复现步骤

(https://video.twimg.com/amplify_video/1734290524079603712/vid/avc1/1280x708/XMxnpskKGmX1YVoc.mp4?tag=14)会出现这个问题。
![微信图片_20231216215530](https://github.com/CarGuo/GSYVideoPlayer/assets/69662387/818f2bac-ffbc-4219-93a6-2272eeefc854)

**Comment by CarGuo** [comment]
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/ea510890-c4f9-46f3-bbf1-f94498068fca)

**Comment by allentown521** [comment]
这个视频（包括很多twitter上的视频都是这个问题）在浏览器打开没问题（这个地址需要翻墙），用libmpv（mpv android）打开也没问题，但是exoplayer就不行；你这日志应该是没翻墙时测试的吧？

**Comment by CarGuo** [comment]
哦，你这个视频需要用梯子啊，我看你描述没说就没注意到·····我这边demo测试正常，exo 模式下：

![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/21327631-dd0d-4f56-b00f-63b1c5366063)

**Comment by allentown521** [comment]
那就很奇怪了，我试了coloros13和oneui5.1 都是android13系统，都无法正确读取时长；你这个模拟器版本是多少？试试这个地址呢：https://[video.twimg.com/amplify_video/1730054339388149760/vid/avc1/1280x720/zg6GsvHQKW7bgsnD.mp4?tag=14](https://video.twimg.com/amplify_video/1730054339388149760/vid/avc1/1280x720/zg6GsvHQKW7bgsnD.mp4?tag=14)

**Comment by allentown521** [comment]
另外我注意到你这个界面和我测试的不一样，我测试的是“输入URL”那个界面，你这是哪个？我去试试看

**Comment by allentown521** [comment]
我知道了，你用的是DETAIL界面，是不是把视频保存到本地了？用输入URL那个界面，直接流式播放

Shuyu Guo ***@***.***> 于2023年12月18日周一 10:19写道：

**Comment by CarGuo** [comment]
没有，都是在线播放的，模拟器是 13 ，真机是小米

**Comment by allentown521** [comment]
你可以试下这个地址：https://video.twimg.com/amplify_video/1730054339388149760/vid/avc1/1280x720/zg6GsvHQKW7bgsnD.mp4?tag=14

我和你同一个页面，读取出来的时长不对，也不能快进，实际是6:37，chrome浏览器可以正确读取；
但是如果我把该视频下载到手机，还是这个界面，从本地选这个视频，一切都是正常的


![56df9b3e55c4dd62bc774877d05b307](https://github.com/CarGuo/GSYVideoPlayer/assets/69662387/32c11abe-2a75-444f-b27d-dcc38916c76c)
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/69662387/7d003feb-d02a-439f-8a9e-6b4ceced4965)

**Comment by allentown521** [comment]
纠正下，快进好像还是正常的。主要是时长不对，每次加载获取的时长还不一样，但是都不对
![5ce6dd58d32615d59c5e23b0fe9a5ee](https://github.com/CarGuo/GSYVideoPlayer/assets/69662387/530139b4-9753-4ef9-8987-81cf363ec1ae)


我似乎找到原因了，用慢一点的vpn节点就会出现这个情况，如果用速度快的vpn节点就正常；
不知道从技术上是否能解释这种情况

**Comment by CarGuo** [comment]
不是很理解，节点问题理论上不应该影响到 package 的完整性，除非你的 vpn 里对数据做了一些 rewrite ，例如去广告什么的

**Comment by allentown521** [comment]
抱歉，今天卸载重新安装了所以用的还是默认的ijk，以上反馈的结果都是次模式的。我切换成exo以后，还是有问题，时长不对，也无法快进
![Screenshot_2023-12-18-18-29-01-80_f6f1ca16758004fdc944f9a540e9845e](https://github.com/CarGuo/GSYVideoPlayer/assets/69662387/0df0966d-3d17-40f2-9525-140df0a416a8)
![Screenshot_2023-12-18-18-23-27-86_f6f1ca16758004fdc944f9a540e9845e](https://github.com/CarGuo/GSYVideoPlayer/assets/69662387/3dac6079-0046-45f9-bfab-798b3d5f02bf)
这是我评论中反馈的两个视频地址

**Comment by CarGuo** [comment]
神奇，但是我测试的 exo 模式下确实没出现问题····如下视频所示

https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/a1f0c62c-3421-4030-80a6-7f595126e3e0

**Comment by CarGuo** [comment]
我感觉应该是 MeidaCodec 的问题，而不是 exo 的问题，体现在于我这边没有复现，所以更多可能是设备 MeidaCodec 相关
