### ISSUE TITLE
缓存部分内容后 暂停缓存 这个缓存的文件可以播放吗

### ISSUE THREAD

**Issue by iamlfc** [CarGuo/GSYVideoPlayer#3905]
## 问题描述：

通过HttpProxyCacheServer下载一部分视频后(并未全部缓存完),  停止缓存，这一部分缓存的文件在播放该视频的时候可以用来播放吗？ 如果可以的话  处理逻辑应该参考是那个类呀？

## 出现问题的视频流

https://tongweizhizao.oss-cn-guangzhou.aliyuncs.com/video/20231030/4b9b4da09fb2ec47cf3976cd0b342b35.mp4

## 问题机型/系统： 

 真机 小米8 Android11

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.4.0-release-jitpack'

**Comment by CarGuo** [comment]
demo DetailDownloadPlayer
