### ISSUE TITLE
在线视频网页可以播放，播放器无法播放

### ISSUE THREAD

**Issue by liudouliangliu** [CarGuo/GSYVideoPlayer#3906]
## 问题描述：

在线视频网页可以播放，播放器无法播放

## 出现问题的视频流

https://oss.hanentropy.com:38612/buckets/objects/downloads?secret=5xr4HpYNCXr50Eaj49kxqv7vSsj51sL6jGJbXi6L%2B6YtrfSR%2Fr358GZsaFb4axA7

## 问题机型/系统：

所有机型

## GSY依赖版本

 `implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:v8.4.0-release-jitpack'
 `implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.4.0-release-jitpack'

**Comment by CarGuo** [comment]
<img width="673" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/434582b1-ebb8-4feb-b8c0-ea126381cde3">

如上图片所示，这个我记得我回复过，视频没有带音频，ijk需要音频轨道做同步时钟，另外你也可以切到  Exo2PlayerManager 内核也可以播放
