### ISSUE TITLE
使用demo的DetailListPlayer，添加了startPlayLogic，只有第一次点击才会自动播放，之后重进都无法自动播放

### ISSUE THREAD

**Issue by iLovT** [CarGuo/GSYVideoPlayer#3907]
## 问题描述：

完全使用demo，只在DetailListPlayer的onCreate方法最后面添加了binding.detailPlayer.startPlayLogic();
预想：每次进入都能自动播放；
结果：只有第一次点击才会自动播放，返回后再点击就无法自动播放了

## 出现问题的视频流

原demo视频

## 问题机型/系统：

android studio模拟器 pixel-3a api34  x86_64

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:v8.5.0-release-jitpack'`

## Demo中的复现步骤

点击“DETAIL列表模式，切换下一集”，播放后返回重新点击

**Comment by CarGuo** [comment]
看看你的 demo 里的  ListGSYVideoPlayer 是不是少了：
 
    @Override
    protected void releaseVideos() {
        /// fix https://github.com/CarGuo/GSYVideoPlayer/issues/3892
        super.onCompletion();
        super.releaseVideos();
    }

这个需要下个版本更新修复，你可以继承后自己 Override
