### ISSUE TITLE
isInPlayingState()获取播放状态不更新

### ISSUE THREAD

**Issue by kkouer** [CarGuo/GSYVideoPlayer#3908]
## 问题描述： 

在使用设置VideoOptionModel 参数 **rtsp_transport** 值为 **udp** 时候 默认播放器StandardGSYVideoPlayer 获取  isInPlayingState()失效 ,即使视频流已经断开 isInPlayingState() 还是不变化,依旧为播放状态,从而无法设置断开视频后的重连动作.

## 出现问题的视频流  :

播放本地设备的RTSP视频流

## 问题机型/系统：

真机  云卓 H16Pro 遥控器 Android 7.1.2

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.4.0-release-jitpack'

## Demo中的复现步骤

每次断开视频流后状态不更新 一直为播放状态.

问题代码：(如果有)
```
无
```

## 问题log（如果有）

无
```

**Comment by CarGuo** [comment]
因为没触发类似 onCompletion
