### ISSUE TITLE
com.shuyu.gsyvideoplayer.video.ListGSYVideoPlayer,隐藏所有的控件，播放开始，播放中以及播放结束所有的控件

### ISSUE THREAD

**Issue by xubiao520** [CarGuo/GSYVideoPlayer#3909]
com.shuyu.gsyvideoplayer.video.ListGSYVideoPlayer,隐藏所有的控件，播放开始，播放中以及播放结束所有的控件

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/775ca70b1e25f0da4233d6b50c38c91c75451c28/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java#L15

**Comment by xubiao520** [comment]
我用的是ListGSYVideoPlayer这个控件，没有用[GSYVideoPlayer/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java](https://github.com/CarGuo/GSYVideoPlayer/blob/775ca70b1e25f0da4233d6b50c38c91c75451c28/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java#L15)

**Comment by CarGuo** [comment]
这是让你你参考 [EmptyControlVideo.java](https://github.com/CarGuo/GSYVideoPlayer/blob/775ca70b1e25f0da4233d6b50c38c91c75451c28/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java#L15) 的实现

**Comment by xubiao520** [comment]
我布局用的是ListGSYVideoPlayer这个，我怎么屏蔽所有ui，我又没有直接用[EmptyControlVideo.java](https://github.com/CarGuo/GSYVideoPlayer/blob/775ca70b1e25f0da4233d6b50c38c91c75451c28/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java#L15)
