### ISSUE TITLE
有个小问题需要修复下，全屏模式滑动声音和亮度的区域不对等

### ISSUE THREAD

**Issue by RogerFong13** [CarGuo/GSYVideoPlayer#391]
GSYVideoControlView类touchSurfaceMoveFullLogic方法，mBrightness = (mDownX < mScreenWidth * 0.5f) && noEnd，这个判断里因为是竖屏所以mScreenWidth应该改成mScreenHeight哈。

**Comment by CarGuo** [comment]
好的👌，下个版本修改下

**Comment by CarGuo** [comment]
2.0.5
