### ISSUE TITLE
仿抖音、快手缓存下一个视频

### ISSUE THREAD

**Issue by dyzgihthub** [CarGuo/GSYVideoPlayer#3911]
您好，想做一个功能，就想快手还有抖音那样的列表，播放当前视频的时候，可以缓存下面的几个视频。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailDownloadPlayer.java
