### ISSUE TITLE
视频有画面没有声音，麻烦看看需要怎么处理？不会编译SO库，求大神解决

### ISSUE THREAD

**Issue by Ahuangshang** [CarGuo/GSYVideoPlayer#3913]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：视频有画面没有声音

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 出现问题的视频流 ：
http://zteres.sn.chinamobile.com:6060/000000001000/6000000001000022586/1.m3u8?channel-id=wasusyt&Contentid=6000000001000022586&livemode=1&stbId=3

## 问题机型/系统：
真机小米14，小米6，小米平板等

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.5.0-release-jitpack'
    //是否需要ExoPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.5.0-release-jitpack'
    //更多ijk的编码支持
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.5.0-release-jitpack'

## Demo中的复现步骤

任何地方播放这个流都没有声音，官方demo也没有声音

## 其他说明：下载片段ts文件用电脑播放器获取文件音视频信息如下
视频: MPEG4 Video (H264) 1920x1080 25.00fps [Video - AVC (H.264), High Profile, Level 4.0, 1920x1080, 25.000 fps (0100,e0,00)]
音频: MPEG Audio 48000Hz 立体声 192Kbps [Audio - MPEG1 - Layer 2, 48.0 kHz, 2 chn, 192.0 kbit/s (0101,c0,00)]
字幕 [No subtitles]
视频画面： 1920 x 1080 (画面比例 16:9)
时间长度： 00:00:10
文件尺寸： 10089KB (10331728 bytes)
文件类型： 媒体文件(.ts)

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
我没记错的话，你这个是 MPEG-1 Layer II （ MP2） 的音频格式（就是那个熟悉的 MP3 - MPEG-1 Audio Layer III ），所以你需要自己编译 so ，例如：

    --enable-encoder=mp2 
    --enable-decoder=mp2 
    --enable-muxer=mp2 
    --enable-decoder=mp2float 
    --enable-encoder=mp2fixed

**Comment by Ahuangshang** [comment]
没有编译过呀，哪里有教程吗？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/BUILD_SO.md

**Comment by Ahuangshang** [comment]
能帮我编译一个支持 MP2的so文件吗？我确实不会编译
