### ISSUE TITLE
播放 m3u8 ，想使用自己的加密key，请问这样这只 mediasource 是否正确

### ISSUE THREAD

**Issue by mlxiaoxiao** [CarGuo/GSYVideoPlayer#3914]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.5.0-release-jitpack'
    //是否需要ExoPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.5.0-release-jitpack'
   //更多ijk的编码支持
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.5.0-release-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
        ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @OptIn(markerClass = UnstableApi.class) @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                Log.i(TAG, "getMediaSource: -> " + dataSource);
                Uri hlsUri = Uri.parse(dataSource);
                int contentType = Util.inferContentType(hlsUri);
                switch (contentType) {
                    case C.CONTENT_TYPE_HLS:{

                        DataSource.Factory dataSourceFactory = new DefaultHttpDataSource.Factory();
                        MediaSource hlsMediaSource = new HlsMediaSource.Factory(dataSourceFactory)
                                // create custom HlsPlaylistParserFactory
                                .setPlaylistParserFactory(new CustomHlsPlaylistParserFactory())
                                .createMediaSource(MediaItem.fromUri(hlsUri));
                        return hlsMediaSource;
                    }
                }
                return null;
            }
....
}
```

## 问题log（如果有）
目前是不能正确播放的，log 显示
ExoPlayerImplInternal: Playback error
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: Source error
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:701)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:673)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:103)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:227)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:   Caused by: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 404
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:436)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.source.chunk.DataChunk.load(DataChunk.java:93)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:417)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-06 22:25:02.639 16267 17711 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:919)
xxxxxxx

```
CustomHlsPlaylistParserFactory 参考的是 
https://juejin.cn/post/7122375055912206367

请帮忙看一下，不胜感激

注：目前加密活着不加密的m3u8 都可以正常播放，至少想替换成自己的可以的时候出现 问题

**Comment by CarGuo** [comment]
自定义的 TAG_KEY  是拿到的一个 fullSegmentEncryptionKeyUri  和 segmentEncryptionIV 吧，解码的部分是在 HlsChunkSource - HlsMediaChunk 的 Aes128DataSource

**Comment by mlxiaoxiao** [comment]
尝试着解决了一下，是  fullSegmentEncryptionKeyUri 设置的问题，使用了服务器发过来的一个地址，解析正常了，但是key放在本地使用解析就报错，英国是路径获取的问题。感谢大佬帮助
