### ISSUE TITLE
请问想要停止播放的话，调用 GSYVideoManager.releaseAllVideos() 就可以吗

### ISSUE THREAD

**Issue by mlxiaoxiao** [CarGuo/GSYVideoPlayer#3915]
我通过点击创建播放视频，每次退出的时候，都掉用了  GSYVideoManager.releaseAllVideos() 

但是连续播放大概16 个的时候，再次点击就无法播放视频了

问题代码：(如果有)

## 问题log（如果有）

log1 
1-09 15:02:20.788 15689 18506 I MediaCodec: CreateByComponentName(), name = OMX.qcom.video.decoder.avc
01-09 15:02:20.788 15689 18506 I MediaCodec: new MediaCodec()
01-09 15:02:20.788  1565 11340 I OMX-VDEC-1080P: component_init: OMX.qcom.video.decoder.avc : fd=-1
01-09 15:02:20.788  1565 11340 E OMX-VDEC-1080P: Omx_vdec::Comp Init Returning failure, errno 12
01-09 15:02:20.788  1565 11340 E OMX-VDEC-1080P: eventfd_write failed for fd: -1, errno = 9, force stop async_thread
01-09 15:02:20.788  1565 11340 E OMX-VDEC-1080P: Invalid input: -1
01-09 15:02:20.788  1565 11340 I OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=-1
01-09 15:02:20.789 15689 18506 I ACodec  : new ACodec()
01-09 15:02:20.789  1565 11340 E media.codec: Failed to allocate omx component 'OMX.qcom.video.decoder.avc'  err=InsufficientResources(0x80001000)
01-09 15:02:20.790 15689 18527 E ACodec  : Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
01-09 15:02:20.790 15689 18527 E ACodec  : signalError(omxError 0xfffffff4, internalError -12)
01-09 15:02:20.790 15689 18527 D IAtlas  : IAtlas::init CallingPid 15689
01-09 15:02:20.790 15689 18526 E MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 1
01-09 15:02:20.790 15689 18527 D IAtlas  : IAtlas::init this 0x7ab3d39390
01-09 15:02:20.790  1521 29725 D AtlasService: setEvent what:256 val EventID,203,ClientPid,15689,ReportLevel,0,omxError,0xfffffff4,internalError,-12 : length 79
01-09 15:02:20.790  1521  1575 D AtlasService: handleMessage what:256 sValue EventID,203,ClientPid,15689,ReportLevel,0,omxError,0xfffffff4,internalError,-12
01-09 15:02:20.790  1521  1575 D AtlasService: cliensCount 1
01-09 15:02:20.790  1521  1575 D AtlasService: notify EVENT_DATA_FEEDBACK to client
01-09 15:02:20.790  3963 15281 D OppoAtlas_jni: JNIAtlasListener::notify msg 256 ext1 0 ext2 0

log2
01-09 15:02:20.794 15689 18504 W MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer: Failed to initialize decoder: OMX.qcom.video.decoder.avc
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:   android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at android.media.MediaCodec.native_setup(Native Method)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at android.media.MediaCodec.<init>(MediaCodec.java:1864)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at android.media.MediaCodec.createByCodecName(MediaCodec.java:1842)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter$Factory.createCodec(SynchronousMediaCodecAdapter.java:76)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:115)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1179)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1087)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:593)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1544)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1163)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1029)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:849)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:974)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1079)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:529)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at android.os.Handler.dispatchMessage(Handler.java:103)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at android.os.Looper.loop(Looper.java:227)
01-09 15:02:20.795 15689 18504 W MediaCodecRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
01-09 15:02:20.795 15689 18504 E MediaCodecVideoRenderer: Video codec error

```
作者大大能否帮忙看下

**Comment by CarGuo** [comment]
额··· 我这边测试没有复现这个问题

**Comment by mlxiaoxiao** [comment]
播放不同的视频，就是视频是个列表，点击 进入播放，返回的是，关闭播放view，掉用了 GSYVideoManager.releaseAllVideos()

好像是掉用了Exo2PlayerManager 才出现的，为了支持 m3u8 设置了 

        PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
 尝试了一起只播放mp4 的版本好像没有这个问题 

搜了一下相关的问题 Failed to initialize OMX.qcom.video.encoder.avc, error 0xfffffff4
https://blog.csdn.net/look_up_at/article/details/99864814
不知道是不是和这个相关，个人感觉有点像，好像哪里没释放掉。可是找不到地方。

**Comment by CarGuo** [comment]
我感觉可能是释放没成功，你断点看看
Exo2PlayerManager 下的  mediaPlayer.release(); 
IjkExo2MediaPlayer  下的 mInternalPlayer.release();

是不是每次调用  GSYVideoManager.releaseAllVideos 都会被执行

**Comment by mlxiaoxiao** [comment]
好的。我试一下

**Comment by CarGuo** [comment]
那就很奇怪了·····release 调用了····居然没释放么·····

**Comment by mlxiaoxiao** [comment]
这个issue 先不要关闭，我研究一下，发现问题提在这里。

**Comment by CarGuo** [comment]
ok，只要有活跃就不关

**Comment by mlxiaoxiao** [comment]
这边改动过代码之后，这个问题没发复现了。非常的奇怪，
之前做的两个改动，一个是没有设置 URL 就掉用了startplaylogic，另外一个重复调用了startplaylogic, 即 onPageSelected 中 掉用了 播放，同时触发了网络函数，回调之后有再次调用了播放函数（两次调用中间触发了 releaseAllVideos）。只改动了这两个地方，但是还原回去，就无法重现了。非常的奇怪。

**Comment by CarGuo** [comment]
这么诡异………
