### ISSUE TITLE
怎么获取当前播放的视频的音频分贝大小

### ISSUE THREAD

**Issue by guominfang** [CarGuo/GSYVideoPlayer#3917]
## 问题描述：

使用了这个库来播放视频，自定义了界面，想在界面上添加一个，音频跳动的动画，想法获取当前视频的播放过程的音频的分贝来控制动画，但是目前好像没有找到方法来获取当前播放的视频的音频分贝大小，请求该库是否有支持这个？

## GSY依赖版本

`    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.4.0-release-jitpack'`

**Comment by CarGuo** [comment]
你想要实现的逻辑，必须能获取到原始音频的 pcm 数据，或者你可以直接试试用 AudioRecord 录制系统声音然后去做 pcm 数据分析
