### ISSUE TITLE
NetInfoModule监听网络状态卡UI

### ISSUE THREAD

**Issue by KamiNoYuki** [CarGuo/GSYVideoPlayer#3919]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

NetInfoModule监听网络状态，在监听到WIFI断开时，会卡UI几秒

## 出现问题的视频流

无

## 问题机型/系统：

黑鲨1(SKR-A0)，android10

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.5.0-release-jitpack'

## Demo中的复现步骤

无

问题代码：(如果有)
```
private val netInfoModule by lazy {
        NetInfoModule(this) {
            viewModel.currentNetworkType.value = networkStateFormat(it)
        }
    }

private fun networkStateFormat(netState: String) =
        when (netState) {
            "NONE" -> R.string.net_state_no_connected.string(this)
            "MOBILE" -> R.string.net_state_mobile.string(this)
            else -> netState
        }
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
没发现有问题
