### ISSUE TITLE
EXO或者system内核，使用TextureView播放4K高帧率视频亮度很低不可调

### ISSUE THREAD

**Issue by yvone1991** [CarGuo/GSYVideoPlayer#3921]
1、GSYVideoType.setRenderType(GSYVideoType.TEXTURE);这种类型播放4K高帧率会很黑
2、使用GSYVideoType.setRenderType(GSYVideoType.SURFACE);方式播放正常，但是会有surfaceview堆叠问题，我们的需求是多个播放器随意堆叠，有层级关系。屏幕上多个播放窗口随意打乱，点哪个哪个就置顶到最前面。。这种情况下用surfaceview不合适，画面层级关系会乱掉。

目前没有有效的配置，用了官网demo下来去播放，也是textureview很黑。。surfaceview对我们来说又不适用。。。

ps：有没有可能是硬件问题导致的色彩空间模式不一样哈

**Comment by CarGuo** [comment]
这个无解，textureview 确实会有色彩问题，清晰度不够

**Comment by yvone1991** [comment]
> 这个无解，textureview 确实会有色彩问题，清晰度不够，在一些设备上

嗯，我们将demo 发给芯片厂商看了，定制化的设备一些常用功能是会有适配问题

**Comment by yvone1991** [comment]
> TextureView缺少对HDR的支持，你可以将源视频转换成SDR.
> 
> https://medium.com/androiddevelopers/android-hdr-migrating-from-textureview-to-surfaceview-part-1-how-to-migrate-6bfd7f4b970e
> 
> https://medium.com/androiddevelopers/android-hdr-migrating-from-textureview-to-surfaceview-part-2-dealing-with-color-washout-60d57d0ab129

太感谢了，这正是我需要的
