### ISSUE TITLE
继承弹幕播放器后 全屏状态下 无法播弹幕问题

### ISSUE THREAD

**Issue by 912334508** [CarGuo/GSYVideoPlayer#3924]
## 问题机型/系统：
三星 s22u

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.5.0-release-jitpack'

## Demo中的复现步骤

问题代码：(如果有)
  /**
     * 开始播放弹幕
     */
    private void onPrepareDanmaku(DanmakuVideoPlayer gsyVideoPlayer) {
        Log.e("onPrepareDanmaku", gsyVideoPlayer.getDanmakuView() + "   " + !gsyVideoPlayer.getDanmakuView().isPrepared() + "   " + gsyVideoPlayer.getParser() + "  " + gsyVideoPlayer.getDanmakuContext());
        if (gsyVideoPlayer.getDanmakuView() != null && !gsyVideoPlayer.getDanmakuView().isPrepared() && gsyVideoPlayer.getParser() != null) {
            gsyVideoPlayer.getDanmakuView().prepare(gsyVideoPlayer.getParser(), gsyVideoPlayer.getDanmakuContext());

        }
    }

## 问题log（如果有）

onPrepareDanmaku        com.hdzr.video_yygs                  E  master.flame.danmaku.ui.widget.DanmakuView{181154f V.ED..... ......I. 0,0-0,0 #7f0a00ef app:id/danmu}   true   null  null

我打印了 gsyVideoPlayer.getParser()  gsyVideoPlayer.getDanmakuContext()   旋转后这两个属性为null   我想这可能是导致旋转后无法播放弹幕的问题

**Comment by CarGuo** [comment]
demo 不是正常么····？？？
