### ISSUE TITLE
文档稍微更新下

### ISSUE THREAD

**Issue by Reginer** [CarGuo/GSYVideoPlayer#3925]
非常感谢开源
因为是先看的文档，https://github.com/CarGuo/GSYVideoPlayer/wiki 这个链接下，这个类对应的是哪个？
项目全局搜也没搜到 CustomGSYVideoPlayer

![image](https://github.com/CarGuo/GSYVideoPlayer/assets/12568257/74a1c18f-538f-4ad3-b482-dcdfbc6675e7)

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/PreViewGSYVideoPlayer.java
