### ISSUE TITLE
播放器开始播放后点击暂停，手机息屏功能失效

### ISSUE THREAD

**Issue by 77trump** [CarGuo/GSYVideoPlayer#3926]
## 问题描述：

播放器在点击开始播放后，再点击暂停播放，在此时会出现手机息屏功能失效的情况，这个现象在竖屏或者横屏均存在，但是控制台并没有报错信息。

## 出现问题的视频流

这个打开任意一个视频，然后点击暂停，手机在到达息屏时间不会息屏

## 问题机型/系统：

真机 HUAWEI LYA-ALO0 

## GSY依赖版本

PROJ_VERSION=8.1.2

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)

无

## 问题log（如果有）

无

**Comment by CarGuo** [comment]
什么内核

**Comment by 77trump** [comment]
![1](https://github.com/CarGuo/GSYVideoPlayer/assets/150900423/dfda469d-3b9b-42c0-a36a-b889c1d752e3)

**Comment by CarGuo** [comment]
((Activity) getActivityContext()).getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

((Activity) mContext).getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

exo 的话，可以在播放和暂停的时候，可以参考上诉代码。调用 addFlags 和 clearFlags 试试

**Comment by 77trump** [comment]
感谢作者，可以啦
