### ISSUE TITLE
播放地址可能为空，为空时点击播放按钮，会一直加载

### ISSUE THREAD

**Issue by yecaler** [CarGuo/GSYVideoPlayer#3927]
## 问题描述：

有个按钮，按钮配置点击后播放视频，但是配置的播放地址可能为空，点击按钮后，因为地址为空，视频控件会显示播放图标，然后点击视频播放器的播放图标，会一直转圈加载。如何设置？

## 出现问题的视频流

无

## 问题机型/系统：
Xiaomi Mi 10

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.4.0-release-jitpack'

**Comment by CarGuo** [comment]
extends 继承后自己判断下，空的话就不要播放
