### ISSUE TITLE
如何可以监听player的onKey?

### ISSUE THREAD

**Issue by hellfire1980** [CarGuo/GSYVideoPlayer#393]
定机盒子只能监听onKey的KeyPad，求助

**Comment by CarGuo** [comment]
你在外部监听key应该和播放器没有太多关系吧？

**Comment by hellfire1980** [comment]
我想外部监听keypadcod 接受到keycode_dpad_center时就暂停onVideoPause(),再接受多一此就播放onVideoResume。

**Comment by CarGuo** [comment]
我觉得你的你意思就是onTouch和OnClick的逻辑，你需要外部监听key之后，转化为view的onclick和touch事件吧？

**Comment by hellfire1980** [comment]
恩，应该是把：D 好比用遥控来控制播放，暂停，快进。 那么要如何做到？

**Comment by CarGuo** [comment]
这个需要你外部监听，然后转化实现，比如暂停，播放的接口都有，seekTo也有
