### ISSUE TITLE
8.5.0版本，拉取rtsp流无声音

### ISSUE THREAD

**Issue by zh0102** [CarGuo/GSYVideoPlayer#3930]
配置相关

 /**此中内容：优化加载速度，降低延迟 */
        val list: MutableList<VideoOptionModel> = ArrayList()
        val videoOptionModel1 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp")
        val videoOptionModel2 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_flags", "prefer_tcp")
        val videoOptionModel3 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 20000)
        //根据媒体类型来配置
        val videoOptionModel4 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_media_types", "video")
        val videoOptionModel5 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "buffer_size", 1316)
        val videoOptionModel6 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "infbuf", 1) // 无限读
        val videoOptionModel7 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzemaxduration", 100)
        val videoOptionModel8 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240)
        val videoOptionModel9 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "flush_packets", 1)
        //  关闭播放器缓冲，这个必须关闭，否则会出现播放一段时间后，一直卡主，控制台打印 FFP_MSG_BUFFERING_START
        val videoOptionModel10 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 0)
        val videoOptionModel11 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "opensles", 0);

        val videoOptionModel12 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_timeout", -1)

        val videoOptionModel13 =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "fflags", "nobuffer")
        val videoOptionModel14 = VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzedmaxduration", 100) //分析码流时长:默认1024*1000

        list.add(videoOptionModel1)
        list.add(videoOptionModel2)
        list.add(videoOptionModel3)
        list.add(videoOptionModel4)
        list.add(videoOptionModel5)
        list.add(videoOptionModel6)
        //list.add(videoOptionModel7)
        list.add(videoOptionModel8)
        list.add(videoOptionModel9)
        list.add(videoOptionModel10)
        list.add(videoOptionModel11)
        list.add(videoOptionModel12)
        list.add(videoOptionModel13)
        list.add(videoOptionModel14)
        GSYVideoManager.instance().optionModelList = list

音频格式AAC

**Comment by CarGuo** [comment]
没有测试视频无法分析

**Comment by janecer** [comment]
> 没有测试视频无法分析

大佬，可以支持app获取 设备的地址（rtsp）,然后实时直播吗？
