### ISSUE TITLE
GSYVideoPlayer-exo_player2:8.5.0-release-jitpack无法通过jitpack下载

### ISSUE THREAD

**Issue by amixuse** [CarGuo/GSYVideoPlayer#3931]
## 问题描述：
GSYVideoPlayer-exo_player2:8.5.0-release-jitpack无法通过jitpack下载
配置jitpack仓库后，其他工件都可正常下载，独这个无法下载。
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/5195458/f8561a85-cadc-40a8-985b-797aa0f746c5)
```

**Comment by CarGuo** [comment]
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/06c541d9-9c63-434d-90b4-05d135968f9e)
