### ISSUE TITLE
大佬，咨询一下，这个库有没有根据RTMP视频流的分辨率来切换渲染比例的？

### ISSUE THREAD

**Issue by dingliufan** [CarGuo/GSYVideoPlayer#3934]
## 问题描述：

不是问题，只是个咨询，库贼拉好用，star了很长时间了，之前也给很多开发朋友推荐，因为确实很香。这次项目又用到了，是想问大佬一个问题，可能是我太菜没有看懂文档，您的这个库有没有根据RTMP视频流的分辨率来切换渲染比例的？或者获取RTMP视频流的分辨率？因为领导提的功能完成之后发现，后台数据提供过来的视频流 有的是16:9，有的是4:3，但是设置了渲染比例之后，另一个比例的视频流就会变形，但是后台的人说他们也无法给到这个视频流的分辨率，因为是数据是一直变动的，不可能每一个都打开去看一眼，老板又不想让用户横屏看播放，所以想来问问您是否有做相关的操作。

## 出现问题的视频流

因为只是咨询，没有出现问题，所以没有出问题的视频流

## GSY依赖版本

 `implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.5.0-release-jitpack'`

**Comment by CarGuo** [comment]
不是很理解，默认的 SCREEN_TYPE_DEFAULT  不就是根据视频分辨率自己显示比例的么

**Comment by dingliufan** [comment]
好的，我的问题。抱歉抱歉，是否可以4:3的往上一点显示呢？现在是居中显示。自定义或者别的？

**Comment by CarGuo** [comment]
//GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_CUSTOM);
        //GSYVideoType.setScreenScaleRatio(9.0f/16);

可以参考这个
