### ISSUE TITLE
在banner里面使用StandardGSYVideoPlayer播放出现有声音，但是画面不变的情况

### ISSUE THREAD

**Issue by qingshang2022** [CarGuo/GSYVideoPlayer#3935]
目前有2个问题求助，先说场景，是做一个banner用途，banner里面使用了一个viewpager2，然后使用一个子类继承StandardGSYVideoPlayer，版本8.3.4 。在不停滑动的情况下，出现有声音但是画面是黑屏的情况下。请问这种怎么解决。还有一个就是设置了预加载，边下边播等，每次切换都有黑屏1-2s后才加载出来。这个有办法解决吗 谢谢

**Comment by CarGuo** [comment]
1、 问题肯定出现在 textureview 或者 surfaceview 的 surface 没有创建或者创建了没正确设置的 playermange 里，可以自己 debug 下问题。

2、切换等待这个没办法，但是你可以参考demo 的无缝切换，用切换 manager 的方式来做，或者优化视频本身的编码来实现秒开的可能。
