### ISSUE TITLE
EXO或者IJK内核播放时会断流

### ISSUE THREAD

**Issue by tszyyx8** [CarGuo/GSYVideoPlayer#3937]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

EXO或者IJK内核播放一段时间后会出现断流，无法继续播放，并且是不定时出现，比如影片播放到第10分钟的时候无法继续播放了，然后重新刷新开始重新看，也许到15分钟才出现这个问题了，此问题阿里内核正常。

## 出现问题的视频流

已删除

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.4.0-release-jitpack'

## Demo中的复现步骤

播放切片资源时播放一段时间后会出现断流，无法继续播放

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
如果是不规律出现的话，我也很难定位问题，理论上出现断流，如果不是网络链路问题，那么基本就是兼容性（解析导致内存异常，累积泄漏等等），比如非标准的格式，或者加了伪装的图船托管，具体不好猜，只能你调试的时候，看看什么原因报错断了，然后针对去复现

**Comment by zhangjie920222** [comment]
我也遇到这种问题（其实基本大部分原因还是视频流的问题）但是阿里内核的处理是选择丢帧，对用户来说体验更好点，比较不会播放失败。所以大佬，可以帮忙改成用阿里内核选择丢帧来处理吗？

**Comment by tszyyx8** [comment]
> 如果是不规律出现的话，我也很难定位问题，理论上出现断流，如果不是网络链路问题，那么基本就是兼容性（解析导致内存异常，累积泄漏等等），比如非标准的格式，或者加了伪装的图船托管，具体不好猜，只能你调试的时候，看看什么原因报错断了，然后针对去复现

你好，请问gsy有提供获取ts状态码的函数吗？

**Comment by CarGuo** [comment]
@zhangjie920222 ijk 的丢帧外部配制只有问题集锦的固定模式，其实如果你看过我一些文章，我也有做过一些对非标准的图床伪装的加解密解析的so版本，但是其实对于sdk没有意义，非标的东西支持没办法规范化，没有约束就不通用，需要的时候还是自己定制的好

**Comment by CarGuo** [comment]
@tszyyx8 我记得好像没有

**Comment by zhangjie920222** [comment]
> @zhangjie920222 ijk 的丢帧外部配制只有问题集锦的固定模式，其实如果你看过我一些文章，我也有做过一些对非标准的图床伪装的加解密解析的so版本，但是其实对于sdk没有意义，非标的东西支持没办法规范化，没有约束就不通用，需要的时候还是自己定制的好

嗯嗯。谢谢

**Comment by 50kg** [comment]
我也遇到了，请问exo或者ijk出现error可以选择丢帧吗？

**Comment by CarGuo** [comment]
没有 @50kg
