### ISSUE TITLE
能否再阿里云仓库升级下，目前阿里云仓库8.1.2

### ISSUE THREAD

**Issue by wangqiaoguang** [CarGuo/GSYVideoPlayer#3938]
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/14883128/7a6e1fb3-4d6a-443d-800e-9662bc69ba3b)

**Comment by CarGuo** [comment]
问题是阿里云的 maven 不是我发的啊，阿里云估计是拉的以前 jcenter 的版本吧，目前只有 jitpack 上是我自己发的
