### ISSUE TITLE
视频播放回到完成错误

### ISSUE THREAD

**Issue by litaoyuan** [CarGuo/GSYVideoPlayer#3939]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在详情页面，播放视频，在离开页面时，onPause 里面调用onVideoPause，接着去播放抖音视频，GSYVideoPlaye 的onComplete回调会马上触发，显示播放完成了
## 问题机型/系统：

华为mate60Pro 

## GSY依赖版本
    implementation 'com.shuyu:GSYVideoPlayer:8.1.0'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
因为这时候视频已经被 release 释放掉了，如果你不想触发，可以配置 setReleaseWhenLossAudio false
