### ISSUE TITLE
常见问题的issues2347的地址打不开了

### ISSUE THREAD

**Issue by yanxudong1** [CarGuo/GSYVideoPlayer#3941]
https://github.com/CarGuo/GSYVideoPlayer/issues/2347

**Comment by CarGuo** [comment]
哇擦，还真的不见了，奇怪，可以看 https://github.com/CarGuo/GSYVideoPlayer/issues/3264#issuecomment-845054396 提到的

https://github.com/CarGuo/GSYVideoPlayer/blob/b7704d41e57cc6c78127b83f42aac15485910992/app/src/main/java/com/example/gsyvideoplayer/video/SampleCoverVideo.java#L166
