### ISSUE TITLE
进度条拖动异常

### ISSUE THREAD

**Issue by AndyYw** [CarGuo/GSYVideoPlayer#3942]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放m3u8,拖动视频进度条会弹回来。已按问题集锦设置如下：
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
还是没用。切换内核也没用用

## 出现问题的视频流
(可能大佬看到的时候过期了。。)
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:15
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MAP:URI="https://cdn-idlespacetech-private.revolo.cn/videos/P030232110003/P0302321100035449a44b8de442dbb88226d23365fa6d/init.mp4?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWlkbGVzcGFjZXRlY2gtcHJpdmF0ZS5yZXZvbG8uY24vdmlkZW9zL1AwMzAyMzIxMTAwMDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzA5NjM0MzgzfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=sYfvgCPHT4P3V4Ye3rWHqxSKGms71mZMsU~1Ku022Chynf6nlNK38BJSuAcbi5ECH7xMOqG-lhFISyzTmuBTnWHwUKGmYIZBcQqGwvJn8x4YXZ9rBk3BrHJXIPwTjHVu5RSPyv2ZgHJhFlgggVfL9EN1yJyjKC~eGbHZGbwivxCHh1bGw9lVLtg~wDQjCfQTjmgKUOUQiaVYx0g3sd0TrAp~qZDvxFIRmkOSYseWj6a09rhA5D0sZnSWmR01O-Ohit8DWpUGJ2ad9YpDEsw-jz4B1UtJveY3YfdsjNHLzaUcYcVPVdLrYoDK0YthhkZsqJV--GX~7t2RmXQkZBFoNA__&Key-Pair-Id=K2EJHWBSDQIY66"
#EXTINF:5.394,
https://cdn-idlespacetech-private.revolo.cn/videos/P030232110003/P0302321100035449a44b8de442dbb88226d23365fa6d/stream0.m4s?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWlkbGVzcGFjZXRlY2gtcHJpdmF0ZS5yZXZvbG8uY24vdmlkZW9zL1AwMzAyMzIxMTAwMDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzA5NjM0MzgzfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=sYfvgCPHT4P3V4Ye3rWHqxSKGms71mZMsU~1Ku022Chynf6nlNK38BJSuAcbi5ECH7xMOqG-lhFISyzTmuBTnWHwUKGmYIZBcQqGwvJn8x4YXZ9rBk3BrHJXIPwTjHVu5RSPyv2ZgHJhFlgggVfL9EN1yJyjKC~eGbHZGbwivxCHh1bGw9lVLtg~wDQjCfQTjmgKUOUQiaVYx0g3sd0TrAp~qZDvxFIRmkOSYseWj6a09rhA5D0sZnSWmR01O-Ohit8DWpUGJ2ad9YpDEsw-jz4B1UtJveY3YfdsjNHLzaUcYcVPVdLrYoDK0YthhkZsqJV--GX~7t2RmXQkZBFoNA__&Key-Pair-Id=K2EJHWBSDQIY66
#EXTINF:5.396,
https://cdn-idlespacetech-private.revolo.cn/videos/P030232110003/P0302321100035449a44b8de442dbb88226d23365fa6d/stream1.m4s?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWlkbGVzcGFjZXRlY2gtcHJpdmF0ZS5yZXZvbG8uY24vdmlkZW9zL1AwMzAyMzIxMTAwMDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzA5NjM0MzgzfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=sYfvgCPHT4P3V4Ye3rWHqxSKGms71mZMsU~1Ku022Chynf6nlNK38BJSuAcbi5ECH7xMOqG-lhFISyzTmuBTnWHwUKGmYIZBcQqGwvJn8x4YXZ9rBk3BrHJXIPwTjHVu5RSPyv2ZgHJhFlgggVfL9EN1yJyjKC~eGbHZGbwivxCHh1bGw9lVLtg~wDQjCfQTjmgKUOUQiaVYx0g3sd0TrAp~qZDvxFIRmkOSYseWj6a09rhA5D0sZnSWmR01O-Ohit8DWpUGJ2ad9YpDEsw-jz4B1UtJveY3YfdsjNHLzaUcYcVPVdLrYoDK0YthhkZsqJV--GX~7t2RmXQkZBFoNA__&Key-Pair-Id=K2EJHWBSDQIY66
#EXT-X-ENDLIST

## 问题机型/系统：

samsung android 13

## GSY依赖版本

'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.5.0-release-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by AndyYw** [comment]
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:15
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MAP:URI="https://cdn-idlespacetech-private.revolo.cn/videos/P030232110003/P0302321100035449a44b8de442dbb88226d23365fa6d/init.mp4?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWlkbGVzcGFjZXRlY2gtcHJpdmF0ZS5yZXZvbG8uY24vdmlkZW9zL1AwMzAyMzIxMTAwMDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzA5NjM3Mzg1fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=PkMkG-inD7uVla2uhPJw72tLGZOuAm4YHXYZYGtVsb8Bfc7wEtAtPCZvyPnh3~3AsM6zj1Kf0MhFNT1K306L5I0pZFscZ-I36-JnlTqcOhCrdzegaVlOZLe7jh67bo9pNHpdsEHPEFBfwhgXgwKcbeW9DYFHvNVi8uBAs1RcCIyF0yit4Wlnh-j6Cw1P7LOTfyUXHCZOmkIXG~0c4wRWnTy3u1w4dPT1DSba6nnwJkW0r86L7OkDuwjzWeq1YUm~plfkU3PYEOLFGJXQve70MRNtmnq~QzKpkwSbjeigRYlaAQGJkrKooPchjbQEJEdMqVw9msN9flDGe8x7Y274tQ__&Key-Pair-Id=K2EJHWBSDQIY66"
#EXTINF:5.394,
https://cdn-idlespacetech-private.revolo.cn/videos/P030232110003/P0302321100035449a44b8de442dbb88226d23365fa6d/stream0.m4s?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWlkbGVzcGFjZXRlY2gtcHJpdmF0ZS5yZXZvbG8uY24vdmlkZW9zL1AwMzAyMzIxMTAwMDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzA5NjM3Mzg1fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=PkMkG-inD7uVla2uhPJw72tLGZOuAm4YHXYZYGtVsb8Bfc7wEtAtPCZvyPnh3~3AsM6zj1Kf0MhFNT1K306L5I0pZFscZ-I36-JnlTqcOhCrdzegaVlOZLe7jh67bo9pNHpdsEHPEFBfwhgXgwKcbeW9DYFHvNVi8uBAs1RcCIyF0yit4Wlnh-j6Cw1P7LOTfyUXHCZOmkIXG~0c4wRWnTy3u1w4dPT1DSba6nnwJkW0r86L7OkDuwjzWeq1YUm~plfkU3PYEOLFGJXQve70MRNtmnq~QzKpkwSbjeigRYlaAQGJkrKooPchjbQEJEdMqVw9msN9flDGe8x7Y274tQ__&Key-Pair-Id=K2EJHWBSDQIY66
#EXTINF:5.396,
https://cdn-idlespacetech-private.revolo.cn/videos/P030232110003/P0302321100035449a44b8de442dbb88226d23365fa6d/stream1.m4s?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWlkbGVzcGFjZXRlY2gtcHJpdmF0ZS5yZXZvbG8uY24vdmlkZW9zL1AwMzAyMzIxMTAwMDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzA5NjM3Mzg1fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=PkMkG-inD7uVla2uhPJw72tLGZOuAm4YHXYZYGtVsb8Bfc7wEtAtPCZvyPnh3~3AsM6zj1Kf0MhFNT1K306L5I0pZFscZ-I36-JnlTqcOhCrdzegaVlOZLe7jh67bo9pNHpdsEHPEFBfwhgXgwKcbeW9DYFHvNVi8uBAs1RcCIyF0yit4Wlnh-j6Cw1P7LOTfyUXHCZOmkIXG~0c4wRWnTy3u1w4dPT1DSba6nnwJkW0r86L7OkDuwjzWeq1YUm~plfkU3PYEOLFGJXQve70MRNtmnq~QzKpkwSbjeigRYlaAQGJkrKooPchjbQEJEdMqVw9msN9flDGe8x7Y274tQ__&Key-Pair-Id=K2EJHWBSDQIY66
#EXT-X-ENDLIST

**Comment by CarGuo** [comment]
如果都没有，有没有可能·····是适配本身的帧排列有问题···找不到关键帧

**Comment by AndyYw** [comment]
好的 多谢大佬。
