### ISSUE TITLE
关于调用seekTo实现视频倒放的效果

### ISSUE THREAD

**Issue by guochenchn** [CarGuo/GSYVideoPlayer#3944]
请教一下，我们有一个功能是实现视频倒放，有一定的条件触发，比如刚开始是正常播放，触发条件后就从当前位置倒放，我用的是seekTo这个函数，比如用5秒钟的时间倒放20秒的视频，我是分了100步倒放，也就是50毫秒调用seekTo一次，每次后退200毫秒视频，出现了卡顿，有没有比较好的方式解决

**Comment by CarGuo** [comment]
关于这个我只能说，seekto不适合做这个事情，因为seekto会触发清空buffer的行为

**Comment by guochenchn** [comment]
你有没有比较好的建议实现这一功能呢？感谢🙏
