### ISSUE TITLE
亮度调节dialog全屏显示不全

### ISSUE THREAD

**Issue by dd9000901** [CarGuo/GSYVideoPlayer#3949]
问题描述：

当横屏并全屏隐藏状态栏和底部导航栏的时候，调节亮度dialog时，显示不全。

## 问题机型/系统：

三星s21

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.6.0-release-jitpack'

 

问题代码：(如果有)
 就是全屏以后设置了可以滑动改变亮度

**Comment by dd9000901** [comment]
![Uploading 1111.jpg…]()

**Comment by CarGuo** [comment]
override showBrightnessDialog 方法，自己按照需要调整下位置或者样式就可以了

**Comment by anonyein** [comment]
> override showBrightnessDialog 方法，自己按照需要调整下位置或者样式就可以了

我也有这个问题，而且看起来还是挺多的
