### ISSUE TITLE
请问能获取到退出全屏的回调吗

### ISSUE THREAD

**Issue by dd9000901** [CarGuo/GSYVideoPlayer#3950]
问题描述：
进入普通播放视频，然后点击全屏，然后在点击退出全屏变成普通播放，退出全屏完成后能得到回调吗
 

 

 GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.6.0-release-jitpack'

**Comment by CarGuo** [comment]
VideoAllCallBack

大佬，多看文档和源码，不要什么都问，大家都是程序员，开源的东西自己多看下
