### ISSUE TITLE
继承了StandardGSYVideoPlayer，自定义播放器添加了UI横屏的时候修改UI状态没有反应

### ISSUE THREAD

**Issue by dd9000901** [CarGuo/GSYVideoPlayer#3954]
问题描述：

继承了StandardGSYVideoPlaye的一个播放器，我添加了一个ImageView，但是我要在接口返回一个Boolean的时候并且在横屏的时候才显示或者不显示，现在我在class MatchVideoPlayer : StandardGSYVideoPlayer {}里面写了一个方发  
  /**
     * 开播或者关播的消息  ,是否进入全屏
     */
    fun  broadcasting(show:Boolean,enter:Boolean){} 
在接口返回的时候我保存了一个Boolean值，在横屏的时候我要根据这个Boolean值来显示或者隐藏这个ImageView，现在我在横屏的时候调用了    fun  broadcasting(show:Boolean,enter:Boolean)这个方法
    fun  broadcasting(show:Boolean,enter:Boolean){
        isBroadcasting=show
        isFullscreen=enter
        if(isBroadcasting){
            if(lltNoLiveNew!=null){
                lltNoLiveNew?.visibility= GONE
            }
        }else{
            if(lltNoLiveNew!=null){
                lltNoLiveNew?.visibility= VISIBLE
            }
        }

但是修改了没有效果，请问我想在切换横屏的时候修改我添加的view 的状态，而且要保存我穿进去参数的状态要怎么实现

 

## GSY依赖版本
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.6.0-release-jitpack'
 

 
```

**Comment by CarGuo** [comment]
看 cloneParams 和 startWindowFullscreen 和 getCurrentPlayer 的用法

**Comment by dd9000901** [comment]
> 查看cloneParams和startWindowFullscreen和getCurrentPlayer的用法
大佬我看了一下·~确实没有看懂你这个。能请问一下~~首先怎么能接口回去到保存在播放器界面，然后怎么在切换横屏的时候把我保存的那个Boolean值来判断进行修改控件的状态谢谢了
