### ISSUE TITLE
横屏的情况切换url   播放黑屏，但是有声音，切换竖屏是正常播放。但是只要在横屏切换的话会黑屏

### ISSUE THREAD

**Issue by dd9000901** [CarGuo/GSYVideoPlayer#3958]
问题描述：

横屏的情况切换url   播放黑屏，但是有声音，切换竖屏是正常播放。但是只要在横屏切换的话会黑屏
需求是我进入一个界面播放详情以后 就一个url进行播放，然后切换到横屏，通过长连接收到一个新的url，当前没有退出横屏
      mDatabind.videoPlayer.release()， setUp(anchor?.playUrl, false, "")设置了这个播放也释放了，加载成功后横屏就黑屏了，但是声音还是正常在播放，退出横屏以后竖屏是正常的。
谢谢大佬能帮忙一下吗

**Comment by CarGuo** [comment]
看 demo ，demo 没问题就说明你用的有问题。

**Comment by dd9000901** [comment]
demo的url是一个list·,现在我的需求是只是一个url然后修改url

**Comment by dd9000901** [comment]
已经解决了这个问题~~应该是播放模式引起的如果选择了ExoPlayer模式就会出现黑屏，但是声音在播放。如果选择其他播放模式比如ijk内核，默认模式就对了。但是demo里面没有复现，不知道为什么原因
