### ISSUE TITLE
m3u8加密了如何处理???

### ISSUE THREAD

**Issue by hua2319** [CarGuo/GSYVideoPlayer#396]

**Comment by CarGuo** [comment]
具体加密是怎么加密的？如果是header校验就加上header即可

**Comment by hua2319** [comment]
通过m3u8返回EXT-X-KEY的URL做校验,这个URL中有方法添加参数吗?

**Comment by hua2319** [comment]
EXT-X-KEY的URL是一个获取key的接口

**Comment by CarGuo** [comment]
如果是m3u8的解析后获取解密，目前还真不支持

**Comment by hua2319** [comment]
不支持解析本地的m3u8文件吗? ?我传本地的报如下错误:
IJKMEDIA: Protocol 'http' not on whitelist 'file,crypto'!
IJKMEDIA: file://storage/emulated/0/bipbopall.m3u8: Invalid argument

**Comment by CarGuo** [comment]
crypto协议是支持的，本地也支持，你这个貌似是http不在白名单？

**Comment by hua2319** [comment]
有解决的办法吗?

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setOptionModelList()创建一个对象给 new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "crypto,file,http,https,tcp,tls,udp"); 设置

**Comment by hua2319** [comment]
可以了,谢谢!!!

**Comment by hua2319** [comment]
hls+file://storage/emulated/0/bipbopall.m3u8; 把本地地址改成这样也是可以的

**Comment by chaoDream** [comment]
同问如果加密的m3u8文件的key是本地文件报
Unable to open key file file://storage/emulated/0/Android/data/com.dongao.mobile.universities/files/Download/playOnline/3984_7644/keyText.txt
这个怎么解决？

**Comment by tydqcjj** [comment]
> 
> 
> GSYVideoManager.instance().setOptionModelList()创建一个对象给 new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "crypto,file,http,https,tcp,tls,udp"); 设置

我试过了，还是播放不了加密的m3u8视频。
文件里面是 AES-128 加密。
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:14
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="key.key"
#EXTINF:5.120000,
index0.ts
#EXTINF:13.040000,
请问怎么设置？
