### ISSUE TITLE
覆写updateStartImage方法，换图无效

### ISSUE THREAD

**Issue by DumboTF** [CarGuo/GSYVideoPlayer#3960]
覆写了 updateStartImage方法，换播放按钮的图，没有效果...

    @Override
    protected void updateStartImage() {
//        super.updateStartImage();
//        可自定义播放按钮样式
        if (mStartButton instanceof ENPlayView) {
            ENPlayView enPlayView = (ENPlayView) mStartButton;
            enPlayView.setDuration(500);
            if (mCurrentState == CURRENT_STATE_PLAYING) {
                enPlayView.play();
            } else if (mCurrentState == CURRENT_STATE_ERROR) {
                enPlayView.pause();
            } else {
                enPlayView.pause();
            }
        } else if (mStartButton instanceof ImageView) {
            ImageView imageView = (ImageView) mStartButton;
            if (mCurrentState == CURRENT_STATE_PLAYING) {
                imageView.setImageResource(R.drawable.video_click_pause_selector2);
            } else if (mCurrentState == CURRENT_STATE_ERROR) {
                imageView.setImageResource(R.drawable.video_click_error_selector2);
            } else {
                imageView.setImageResource(R.drawable.video_click_play_selector2);
            }
        }
    }

**Comment by CarGuo** [comment]
参考  NormalGSYVideoPlayer 啊，你的 getLayoutId 里的 button 不对吧

**Comment by DumboTF** [comment]
感谢大佬，是我大意了。
另外seekTo这个方法，应该在哪个时机调用？需求是记录播放位置，下次进来后续播，我现在调用seek之后，还是会从头播放

**Comment by CarGuo** [comment]
setSeekOnStart

**Comment by DumboTF** [comment]
有效 可以了

**Comment by DumboTF** [comment]
公司想着列表切换播放视频的时候，流畅一点，我现在用的 new CacheHelper().preCacheVideo()方法，滑动的时候去preCache当前position-1 和 +1的视频。
1、这样会导致重复加载相同的url吗，
2、有没有提供什么方法可以实现。
我记得之前看到过提供预加载（1,3）这种前1个后3个 ，但是现在找不到了
