### ISSUE TITLE
从指定位置播放对有的视频不起作用

### ISSUE THREAD

**Issue by shenyunmeng0519** [CarGuo/GSYVideoPlayer#3962]
视频源：http://172.100.100.225:11117//affile//securitytraining//20240327//202403271522//c5276b4f-ac67-4344-bab4-d662b3467f56.mp4
val videoOptionModel =
            VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "seek-at-start", mCurrentPosition.toInt())
        val list: MutableList<VideoOptionModel> = ArrayList()
        list.add(videoOptionModel)
        GSYVideoManager.instance().optionModelList = list
这个方式和setSeekOnStart方法都试了，设置了播放位置毫秒，但是还是从头开始播放

**Comment by shenyunmeng0519** [comment]
依赖：    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.5-release-jitpack'

**Comment by CarGuo** [comment]
链接无法加载

**Comment by shenyunmeng0519** [comment]
是我们内网的视频，需要连个vpn，大大方便连下不？步骤：下载EasyConnect软件，服务器地址：https://vpn.zditec.com
账号：shenyunmeng 密码：Yun236711@

**Comment by CarGuo** [comment]
不方便

**Comment by shenyunmeng0519** [comment]
别的视频都好使，这个是个19秒的视频，是不是视频帧有问题，测试说ios是可以指定位置播放的

**Comment by shenyunmeng0519** [comment]
换了Exo内核好使了
