### ISSUE TITLE
电视盒子上使用SystemPlayerManager，并设置GSYVideoType.GLSURFACE时，无法播放视频

### ISSUE THREAD

**Issue by wei-gong** [CarGuo/GSYVideoPlayer#3963]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我需要在电视盒子上使用GLSurfaceView播放本地存储中的视频并应用一些openGL效果，前期我通过GLSurfaceView+MediaPlayer的方式简单实现了该功能。为了支持更多的视频，我引入了GSYVideoPlayer，并使用SystemPlayerManager + GSYVideoType.GLSURFACE来达到同样的目的。但是当我在手机上测试通过后，在电视盒子上测试时发现视频没有画面只有声音。

ps: 我尝试切换到IJKPlayerManager来播放，发现播放非常卡顿，我猜测是由于电视盒子的性能（1G+8G）不足以支持IJKPlayer。

## 问题机型/系统：

中国联通电视盒子 Android 9

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.6.0-release-jitpack'

## Demo中的复现步骤
1. 使用SystemPlayerManager：PlayerFactory.setPlayManager(SystemPlayerManager.class);
2. 设置GSYVideoType.GLSURFACE渲染方式：GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);
3. 设置一个简单的自定义渲染器： videoPlayer.setCustomGLRenderer(new MyGLRenderer());

问题代码：(如果有)
```
 PlayerFactory.setPlayManager(SystemPlayerManager.class);
GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);
```

## 问题log（如果有）

```
没有异常的log日志。

```

**Comment by wei-gong** [comment]
在电视盒子上，我自己通过GLSurfaceView+MediaPlayer的方式是可以正常播放的，但是换成GSYVideoPlayer的SystemPlayerManager、GSYVideoType.GLSURFACE后，却无法播放了。

**Comment by CarGuo** [comment]
排除法
1、切换到  SystemPlayerManager +  GSYVideoType.SURFACE
2、切换到 Exo + GSYVideoType.GLSURFACE
3、SystemPlayerManager +  GSYVideoType.GLSURFACE 然后不设置 render 
看看什么情况，我这边没场景去复线你的问题····

**Comment by wei-gong** [comment]
> 排除法 1、切换到 SystemPlayerManager + GSYVideoType.SURFACE 2、切换到 Exo + GSYVideoType.GLSURFACE 3、SystemPlayerManager + GSYVideoType.GLSURFACE 然后不设置 render 看看什么情况，我这边没场景去复线你的问题····

1. 切换到 SystemPlayerManager + GSYVideoType.SURFACE ：视频正常播放
2. 切换到 Exo + GSYVideoType.GLSURFACE： 不设置render，视频正常播放；设置render，视频画面正常播放5秒，之后画面卡死，声音正常；
3. SystemPlayerManager + GSYVideoType.GLSURFACE 然后不设置 render：没有画面，有声音

**Comment by CarGuo** [comment]
2 不设置  render  居然和 3 不设置 render 不一样····· 底层都是 MediaCodec ···· 这么神奇···

试一下 setGLRenderMode(GSYVideoGLView.MODE_RENDER_SIZE)  有没有用

还有 调整里面的 setEGLContextClientVersion 试试（直接跑 demo 工程，源码修改）


另外可以 debug 例如 GSYVideoGLViewSimpleRender 类似 onDrawFrame、onSurfaceCreated、onSurfaceChanged 是否没有正常调用

**Comment by wei-gong** [comment]
> 2 不设置 render 居然和 3 不设置 render 不一样····· 底层都是 MediaCodec ···· 这么神奇···
> 
> 试一下 setGLRenderMode(GSYVideoGLView.MODE_RENDER_SIZE) 有没有用
> 
> 还有 调整里面的 setEGLContextClientVersion 试试（直接跑 demo 工程，源码修改）
> 
> 另外可以 debug 例如 GSYVideoGLViewSimpleRender 类似 onDrawFrame、onSurfaceCreated、onSurfaceChanged 是否没有正常调用

是的，我一直是在demo工程的源码中修改进行测试的，目前SystemPlayerManager依然没有办法正常工作。
但是我使用ExoPlayer时，定位到了无法正常播放的原因，问题出在我自定义的Renderer中，onFrameAvailable方法实现上，我没有添加synchronized同步块，加上之后就能正常工作了。

**Comment by CarGuo** [comment]
那就用 ExoPlayer 内核吧，ExoPlayer 基本和 System 大岔不差，现在是 androidx 的 media3
