### ISSUE TITLE
CacheHelper.download 下载报错 java.lang.IllegalStateException

### ISSUE THREAD

**Issue by DumboTF** [CarGuo/GSYVideoPlayer#3965]
startDownloadExo(videoUrl, context);
下载报错
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/8540930/4908cca5-e0a8-45a2-b2af-85882fed17e7)

![image](https://github.com/CarGuo/GSYVideoPlayer/assets/8540930/b1640e89-a96c-4c32-baeb-9dff86a0549c)

**Comment by CarGuo** [comment]
Assertions.checkState(!released);  的时候 release 不为 false
