### ISSUE TITLE
音视频播放不同步

### ISSUE THREAD

**Issue by zhuzhulove123** [CarGuo/GSYVideoPlayer#3971]
格式 : MPEG-4
格式档次 : Base Media
编解码器ID : isom
文件大小 : 19.6 MiB
时长 : 4mn 0s
总体码率 : 684 Kbps
编码软件 : Lavf56.40.101
分辨率(横纵比) : 1440x810(16:9)

**Comment by zhuzhulove123** [comment]
用的ijk播放器，播放不同步，是因为分辨率和 码率的问题吗？

**Comment by CarGuo** [comment]
一般不同步，可以切换到 exo 内核或者问题集锦里的丢帧

**Comment by zhuzhulove123** [comment]
用了exo也反馈 有点不同步 只是比ijk好一点，ijk播放速度可以调节，exo模式播放速度设置就不行

**Comment by zhuzhulove123** [comment]
用了exo也反馈 有点不同步 只是比ijk好一点，这个是视频本身的问题吗？如果是怎么修改

**Comment by CarGuo** [comment]
可以再试试系统内核，看起来像是硬件支持比较差：

1、音视频码率太高
2、设备硬件太拉开

**Comment by zhuzhulove123** [comment]
使用系统播放内核，视频不是从0秒播放，感觉是从 4秒左右开始播放，这个是什么问题
