### ISSUE TITLE
Activity中切换Fragment被释放问题导致状态错乱控制失效

### ISSUE THREAD

**Issue by Hynsn** [CarGuo/GSYVideoPlayer#3973]
## 问题描述：

在Acitivity和Fragment中都使用ListGSYVideoPlayer时，播放控制失效

## 出现问题的视频流

fock了一个仓库，在hynson_test分支可以复现到。
https://github.com/Hynsn/GSYVideoPlayer.git 

## 问题机型/系统：

任意机型

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.6.0'`

## Demo中的复现步骤

Demo中简单播放 -》轮播简单播放3 -》点击替换-》返回，Activity中的ListGSYVideoPlayer暂停播放、进度拖动均失效。
Demo中增加了日志打印 参考示例

辛苦大佬抽空看看，目前需求统一使用ListGSYVideoPlayer才能满足。
尝试了两种方案都不太可行

```
fun isRelease(): Boolean {
        return gsyVideoManager.player.mediaPlayer == null
}
```
1. 判断播放器被释放，重新startPlayLogic
2. 判断播放器被释放，重置状态setStateAndUi(CURRENT_STATE_NORMAL);

上面方案最后的状态是一致加载。

#3240 
原因还是默认情况下播放内核只有一个，轮播和单波还是有点区别StandardGSYVideoPlayer倒是无上述问题。

**Comment by CarGuo** [comment]
不是很理解你的问题，我感觉就是 onCompletion 没有调用到还是？？？

**Comment by Hynsn** [comment]
> 不是很理解你的问题，我感觉就是 onCompletion 没有调用到还是？？？

调用到了，这种场景播放器状态错误和控制失效了，你可以切分支跑了看一下。

**Comment by CarGuo** [comment]
没很理解你的场景，如果你需要多个，可以尝试 demo 的  MultiSampleVideo

**Comment by Hynsn** [comment]
> 没很理解你的场景，如果你需要多个，可以尝试 demo 的 MultiSampleVideo

现象录屏如下，暂时没考虑用MultiSampleVideo。
https://github.com/CarGuo/GSYVideoPlayer/assets/13035957/603d5102-6559-47fc-9b8d-5220e23cdc0a

**Comment by Hynsn** [comment]
> 不用 MultiSampleVideo， 那么基本上就是用过就会被释放了，返回后你需要重新实例化构建，本质上还是单个内核····

主要是 StandardGSYVideoPlayer是这个场景正常的，可能轮播稍微复杂一点

**Comment by CarGuo** [comment]
但是 list 的，最多就是 onCompletion、onAutoCompletion 和 releaseVideos  这几个的区别啊，特别是 releaseVideos 因为  #3892 所以多加了  super.onCompletion();

**Comment by Hynsn** [comment]
> 但是 list 的，最多就是 onCompletion、onAutoCompletion 和 releaseVideos 这几个的区别啊，特别是 releaseVideos 因为 #3892 所以多加了 super.onCompletion();

是的，我有看过这个issue。所以我就觉得StandardGSYVideoPlayer哪里没处理好

**Comment by CarGuo** [comment]
有可能出现问题的，也就是上面三个方法

**Comment by Hynsn** [comment]
> 有可能出现问题的，也就是上面三个方法

        Log.i(TAG, "onCompletion: 1 mPlayPosition=" + mPlayPosition + ",size=" + mUriList.size());
        if (mPlayPosition < (mUriList.size())) {
            mAudioManager.abandonAudioFocus(onAudioFocusChangeListener);
            return;
        }
        Log.i(TAG, "onCompletion: 2");
还是这里的问题，对比了onCompletion、onAutoCompletion 和 releaseVideos这三个方法都加了log，确实发现打印不一样。我现在的做法是增加一个set方法更新mPlayPosition值，这种业务场景就手动调一下让它满足条件调super.onCompletion()。
大佬有没有好的解决办法尼。

**Comment by CarGuo** [comment]
onAutoCompletion 和  onCompletion 的区别，主要还是前者是播放完自动结束，后者是被动结束，具体我感觉还是要看你的业务需要

**Comment by Hynsn** [comment]
> onAutoCompletion 和 onCompletion 的区别，主要还是前者是播放完自动结束，后者是被动结束，具体我感觉还是要看你的业务需要

我先关闭了，看看库里面能不能兼容一下这种场景。
