### ISSUE TITLE
特殊视频无法播放问题

### ISSUE THREAD

**Issue by HelloJokerWord** [CarGuo/GSYVideoPlayer#3974]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

https://www.haycomma.top/peach/video/b22538f31c0400f8b63098bc15f971b6.mp4
该视频我用demo 默认 exo模式去播放，播放只有声音，画面黑屏。

## 出现问题的视频流
https://www.haycomma.top/peach/video/b22538f31c0400f8b63098bc15f971b6.mp4
https://www.haycomma.top/peach/video/1280477898e366e6c52110a158b0972b.mov

## 问题机型/系统：

任意真机即可 

## GSY依赖版本
demo最新版本

## Demo中的复现步骤

Demo中 SimplePlayer init方法  source1替换下上面url播放即可

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
看起来是编码兼容问题，另外这个视频的 start time 也很奇怪 ·····
<img width="627" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/c4393cb7-f34c-4615-b095-24eaded2dbca">

**Comment by CarGuo** [comment]
目前看起来 ijk 模式下是正常的，也符合 VLC 一样的情况，都是利用 ffmpeg 解码支持，而 exo 是通过 MeidaCodec 解码支持的，这部分可定制化修改不高，基本上也就那这样了

**Comment by HelloJokerWord** [comment]
> 目前看起来 ijk 模式下是正常的，也符合 VLC 一样的情况，都是利用 ffmpeg 解码支持，而 exo 是通过 MeidaCodec 解码支持的，这部分可定制化修改不高，基本上也就那这样了

好的，谢谢大佬指导，哈哈
