### ISSUE TITLE
加载一个链接多次请求接口

### ISSUE THREAD

**Issue by cc519348051** [CarGuo/GSYVideoPlayer#3976]
## 问题描述：一个链接加载的过程 多次请求了接口

![966652895539513d551c678690af59f](https://github.com/CarGuo/GSYVideoPlayer/assets/13284047/866580e1-f7fa-4249-b8c4-10f5cb69adb2)

总共请求了4次 两次200 两次206  每次都是什么情况能帮忙分析下吗？

## 出现问题的视频流

https://cdn-testing-ali-2.crushonfeature.com/kvwghxr8fsxse5t881o8vrrhz3ln?auth_key=1714377916-0-0-59f14ffba7c06d919a8f97973bc694bb&amp;Expires=1714377916&amp;KeyName=brave-storage-private-cdn-signing-key&amp;Signature=eEdQ93aG2jLkfrNrRANsVCZBbts

## 问题机型/系统：

Android 9; VOG-AL00  模拟器 真机也是如此

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.5.0'`

## Demo中的复现步骤

直接加载这个链接

问题代码：(如果有)
     mPlayer.setUp("https://cdn-testing-ali-2.crushonfeature.com/kvwghxr8fsxse5t881o8vrrhz3ln?auth_key=1714377916-0-0-59f14ffba7c06d919a8f97973bc694bb&amp;Expires=1714377916&amp;KeyName=brave-storage-private-cdn-signing-key&amp;Signature=eEdQ93aG2jLkfrNrRANsVCZBbts", true, "");
        mPlayer.setLooping(true);

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
<img width="343" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/2307261a-7af0-4a40-89e8-4e163b93954e">

**Comment by cc519348051** [comment]
@CarGuo https://cdn-testing-ali-2.crushonfeature.com/kvwghxr8fsxse5t881o8vrrhz3ln?auth_key=1714377916-0-0-59f14ffba7c06d919a8f97973bc694bb&amp;Expires=1714377916&amp;KeyName=brave-storage-private-cdn-signing-key&amp;Signature=eEdQ93aG2jLkfrNrRANsVCZBbts我这里链接可以直接打开的 没有报错

**Comment by CarGuo** [comment]
不清楚，我这边是打不开链接
