### ISSUE TITLE
有个功能上的问题需要咨询下

### ISSUE THREAD

**Issue by ail36413** [CarGuo/GSYVideoPlayer#3978]
如果我要实现一个截取画面80%的来播放，起始坐标可以自定义，要如何实现呢？
   /**
     * 设置滤镜效果
     */
    public void setEffectFilter(GSYVideoGLView.ShaderInterface effectFilter) 

    /**
     * GL模式下的画面matrix效果
     *
     * @param matrixGL 16位长度
     */
    public void setMatrixGL(float[] matrixGL) 

    /**
     * 自定义GL的渲染render
     */
    public void setCustomGLRenderer(GSYVideoGLViewBaseRender renderer)
    用这三个哪个方法比较好？还是有更简单的办法呢

**Comment by CarGuo** [comment]
简单点，参考 demo 的 CustomRenderView ，自定义渲染层

**Comment by ail36413** [comment]
这种方式的话，起点坐标能实时变化吗？就是我要一直改变这个80%画面的位置

**Comment by CarGuo** [comment]
那你还是用 OpenGL 去实现吧
