### ISSUE TITLE
关于在Flutter 中全屏播放器的问题

### ISSUE THREAD

**Issue by liuchuancong** [CarGuo/GSYVideoPlayer#3979]
## 问题描述：在flutter中使用AndroidView 在切换全屏和非全屏的时候 该AndroidView 会被重新创建，如何在全屏和非全屏切换。
在新的页面重新初始化该播放器并调用builder或者setup方法进行继续播放，是一个思路 但是初始化了两个播放器 很多设置都需要设置

请问有更好的方法吗

https://pub-web.flutter-io.cn/packages/gsy_video_player

**Comment by CarGuo** [comment]
额···· gsy 本身就没考虑过支持 flutter ····· 又没有 iOS ，支持毫无意义···如果你真想支持，那也不是用  AndroidView 的方式，更多应该用外界纹理方式去接入 playermanager

**Comment by liuchuancong** [comment]
好的

**Comment by liuchuancong** [comment]
@CarGuo 请问我已经用texture集成了播放器，并且使用 setDisplay方法设置了surface,但是视频并不显示，只有声音，并且没有任何报错，进行热更新的时候视频会显示一帧在手机上，且不变化，可以帮我看看吗？
(代码点这里查看)[https://github.com/liuchuancong/gsy_video_player/blob/f3b042514f924fabea12e09076f81c74fd3a93fb/android/src/main/kotlin/com/alizda/gsy_video_player/GsyVideoPlayer.kt#L56]
