### ISSUE TITLE
开始播放后，出现软件崩溃，偶尔不崩溃，不崩溃时播放器正常播放。

### ISSUE THREAD

**Issue by MR-mingrui** [CarGuo/GSYVideoPlayer#3980]
## 问题描述：

开始播放后，出现软件崩溃，偶尔不崩溃，不崩溃时播放器正常播放。

## 出现问题的视频流

http://vjs.zencdn.net/v/oceans.mp4

## 问题机型/系统：

真机 小米Mi10 Android7.0

## GSY依赖版本

    //基础包
    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'
    //是否需要ExoPlayer模式
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.4'
    //更多ijk的编码支持
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.4'

## Demo中的复现步骤

继承并重写播放器，增加了一个按钮功能，如文件所示。

fragment 页面的播放器点击开始播放后会出现这个问题。

问题代码：
```
[SampleVideo.zip](https://github.com/CarGuo/GSYVideoPlayer/files/15285891/SampleVideo.zip)

```

## 问题log：

```

xiaomi/umi/umi:13/TKQ1.221114.001/V816.0.3.0.TJBCNXM:user/release-keys
#00 pc000000000014001c3[anon:dalvik-main space(region space)]

```

**Comment by CarGuo** [comment]
非 gsy demo 复线问题请自行调试解决
![a08bc48c46f28e30aaeb2b5f4043e305](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/aa0e7a3c-8065-4167-906d-a3949bb95d1b)

**Comment by MR-mingrui** [comment]
抱歉，安卓调试不太会使用，平时都是用日志打印看问题具体出在哪儿，这个崩溃让我的日志打印大法失效了，实在不知道是哪里的问题，所以只附上了手机报错时的信息TT。
我使用的是demo 中的 SimpleDetailActivityMode2.java 模板，只是移植到了 Fragment 中，然后播放器类继承之后也只是增加了一个按钮。

**Comment by MR-mingrui** [comment]
抱歉，安卓调试不太会使用，平时都是用日志打印看问题具体出在哪儿，这个崩溃让我的日志打印大法失效了，实在不知道是哪里的问题，所以只附上了手机报错时的信息TT。
我使用的是demo 中的 SimpleDetailActivityMode2.java 模板，只是移植到了 Fragment 中，然后播放器类继承之后也只是增加了一个按钮。



> 非 gsy demo 复现问题请自行调试解决 ![编号：A08bc48c46f28e30aaeb2b5f4043e305](https://private-user-images.githubusercontent.com/10770362/329893167-aa0e7a3c-8065-4167-906d-a3949bb95d1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTU2NTUsIm5iZiI6MTcxNTU5NTM1NSwicGF0aCI6Ii8xMDc3MDM2Mi8zMjk4OTMxNjctYWEwZTdhM2MtODA2NS00MTY3LTkwNmQtYTM5NDliYjk1ZDFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMzA5YjM3YWRmNWZhZDk0ZDBmMDBhOTczZWQwODIwMWQyYmE1YTdmM2M1NmYyNWRhMjFkZWJiMjIzZjZmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0qrfAMUw1NS2bAEdn1-A6kVoEhBYmaeAVjjB3aMxIbo)

**Comment by MR-mingrui** [comment]
@CarGuo 我似乎没有找到对 SampleVideo.java 这个播放器进行调用的 demo，拜托可否指条明路？TT

**Comment by lm-rui** [comment]
@CarGuo 今天试了官方demo：SimplePlayer.java。无论是这个demo，还是我前面上传的改过的demo，都遇到了同样的问题和报错。
![PixPin_2024-05-14_22-49-18](https://github.com/CarGuo/GSYVideoPlayer/assets/94375515/022ea107-e8c0-4b40-8893-bc02c61f3106)

**Comment by lm-rui** [comment]
已解决，跟代码没关系。
解决方法：引入最新的依赖。
