### ISSUE TITLE
有些链接不能播放

### ISSUE THREAD

**Issue by Ahuangshang** [CarGuo/GSYVideoPlayer#3982]
## 问题描述：

不能正常播放，但是集成VLC播放器可以正常播放

## 出现问题的视频流

(http://cfss.cc/cdn/hy/11352960.flv)

## 问题机型/系统：
 真机 所有手机

## GSY依赖版本

'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.6.0-release-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

Connection reset by peer

**Comment by CarGuo** [comment]
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/57919dba-1ea0-488c-ba75-6f135058bd02)
你网络有问题吧

**Comment by Ahuangshang** [comment]
不是的，播放了几分钟后就不能播放了

**Comment by CarGuo** [comment]
你的log  Connection reset by peer ，就是网络问题····· 这种播着播放不能播的，只能你自己配合服务端定位
