### ISSUE TITLE
建议手势功能添加

### ISSUE THREAD

**Issue by 280867678** [CarGuo/GSYVideoPlayer#3986]
建议添加手势操作如下：
1：长按快进播放，松手正常播放
2:双指捏合缩放或放大画面且显示缩放比例，双指移动，画面也移动
3：双击屏幕三分之一左侧倒退10秒，右侧快进10秒，中间则暂停或播放
以上参考mxplayer播放器
4：长按时左右移动切换播放倍数默认长按倍数2.0
参考迅雷播放器

**Comment by CarGuo** [comment]
自己 override onTouch 或者 参考demo 复写 gestureDetector

**Comment by uaoan** [comment]
看我主页 我写了 [GSYPlayer](https://github.com/uaoan/GSYPlayer.git)   
@280867678
