### ISSUE TITLE
关于鼠标的超级奇葩的问题

### ISSUE THREAD

**Issue by ail36413** [CarGuo/GSYVideoPlayer#3989]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

我在一个android盒子上面使用StandardGSYVideoPlayer播放本地视频，当我移动鼠标的时候（只移动不点击）视频播放就是非常的卡，一停下来就正常；如果我使用android自带的MediaPlayer + TextureView播放的话，则不存在这个问题。请问您这边是有监听了什么事件吗？

## 出现问题的视频流

所有视频

## 问题机型/系统：

Android主板机

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.6.0-release-jitpack'

## Demo中的复现步骤

随便播放也会出现

**Comment by CarGuo** [comment]
鼠标····不大确定，或者是出发了 onTouch 里的事件导致？

**Comment by ail36413** [comment]
只引入gsyVideoPlayer-java，只用系统内核播放，只播放本地文件（大于4G）
经过多天多设备测试发现问题如下：
1.MediaPlayer + TextureView播放基本秒开， 使用本库打开慢很多
2.关于移动鼠标引起卡顿的问题，经过测试发现在这个RK3566的设备上，本库播放的时候比系统播放更消耗内存，移动鼠标移动的时候使用的一点点内存，引起系统内存不够使用，导致整个系统卡顿

**Comment by CarGuo** [comment]
因为系统播放器用的是 MeidaCodec ，大部分时候适配硬解码，所以对性能比较好
而 ijk 这种 so 库 ，软解码，基本靠的是 CPU 算力适配，所以会很吃资源

**Comment by ail36413** [comment]
使用本库的时候，我也是只引入gsyVideoPlayer-java，只用系统内核播放哦。

**Comment by CarGuo** [comment]
说起来，我这边刚好也是有 RK3566 的设备，不过是触摸屏的，测试还挺正常的

**Comment by ail36413** [comment]
不知道哦。在移动设备上是正常的，在这边rk3566设备上测试的话，明显能看出这个播放初始化的黑屏时间，比系统方法直接播更久
