### ISSUE TITLE
支持 DisplayManager 将图像输出到 type-c (DP)/HDMI

### ISSUE THREAD

**Issue by read8873** [CarGuo/GSYVideoPlayer#3994]
## 问题描述：

支持 DisplayManager 将图像输出到 type-c (DP)/HDMI.
这将大大节省手机电池并扩展 GSYVideoPlayer  的使用范围（例如，通过 type-c 将手机连接到 XR 耳机/电视）。

## 出现问题的视频流

可参考 vlc 相关实现
https://developer.android.com/reference/android/hardware/display/DisplayManager
https://code.videolan.org/search?group_id=9&nav_source=navbar&project_id=36&repository_ref=master&search=DisplayManager&search_code=true

## 问题机型/系统：

例如 真机 小米Android13.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
欢迎 pr
