### ISSUE TITLE
有Buffering監聽的方法嗎？

### ISSUE THREAD

**Issue by CiaShangLin** [CarGuo/GSYVideoPlayer#3997]
## 问题描述：

有可以監聽Buffering緩衝觸發的時候監聽嗎？
找了一圈沒找到比較直觀的
目前感覺比較接近的只有這兩個
changeUiToPlayingBufferingShow，changeUiToPlayingBufferingClear

GSYSampleCallBack這個也沒有緩衝觸發

GSYMediaPlayerListener有嘗試設置過但好像沒有觸發到onBufferingUpdate

有類似ExoPlayer的addListener{
 override fun onPlaybackStateChanged(state: Int) {
                super.onPlaybackStateChanged(state)
                when (state) {
                    Player.STATE_BUFFERING{
                        
                    }
                }
            }
}
嗎？

感謝

## 出现问题的视频流

無

## 问题机型/系统：

無

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

無

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
setGSYStateUiListener 里的 CURRENT_STATE_PLAYING_BUFFERING_START 和 CURRENT_STATE_PLAYING  或者 override  onInfo `what == MediaPlayer.MEDIA_INFO_BUFFERING_START`  、`what == MediaPlayer.MEDIA_INFO_BUFFERING_END`

**Comment by CiaShangLin** [comment]
感謝大佬撥空回答
