### ISSUE TITLE
使用demo切换成系统内核，使用DetailListPlayer播放视频，横竖屏切换会导致自动播放

### ISSUE THREAD

**Issue by CharlesMing** [CarGuo/GSYVideoPlayer#3999]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ 切换成系统内核，视频播放完毕再切换横竖屏，会导致视频无画面播放

## 问题机型/系统：

 真机 Pixel4 Android13系统

## GSY依赖版本

 `com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.6.0-release-jitpack'`

## Demo中的复现步骤

运行demo，在DetailListPlayer播放了一个本地文件，路径如下(手动导入)：/storage/emulated/0/Android/data/com.example.gsyvideoplayer/files/Download/20220322_162255_0041_N_A.MP4,播放前，在第一个页面切换为系统内核，进入DetailListPlayer开始播放，然后横屏，等待或者手动拖到快结束位置，等待播放器自动播放完成，切回到竖屏，此时会自动播放，但是画面显示的是封面图，能听到声音；同理，竖屏播放完毕切换横屏也是一样的现象，使用其他内核无异常，帮忙分析一下是什么原因导致

问题代码：(如果有)
```
无
```

## 问题log（如果有）

```
无
```

**Comment by CarGuo** [comment]
老问题，因为播放结束后，切换 surface 的时候，mediaPlayer 其实并没有 release ，而系统MediaPlayer 有个奇怪设定，就算播放结束了，你给它个 setSurface ，它就会自己又动起来····· 解决方式：

```java

                @Override
                public void onAutoComplete(String url, Object... objects) {
                    super.onAutoComplete(url, objects);
                    IPlayerManager playerManager = binding.detailPlayer.getGSYVideoManager().getPlayer();
                    if (playerManager instanceof SystemPlayerManager) {
                        playerManager.release();
                    }
                }

                @Override
                public void onComplete(String url, Object... objects) {
                    super.onComplete(url, objects);
                    IPlayerManager playerManager = binding.detailPlayer.getGSYVideoManager().getPlayer();
                    if (playerManager instanceof SystemPlayerManager) {
                        playerManager.release();
                    }
                }
```

**Comment by CarGuo** [comment]
👆提交已经修复问题，实际问题 [mediaPlayer setSpeed](https://github.com/CarGuo/GSYVideoPlayer/commit/f8d7a1907b5a2e9206d8654da757537812393f0b)  的时候，会触发自动播放，下版本发布

**Comment by CharlesMing** [comment]
好的，感谢！！
