### ISSUE TITLE
机型Huawei H60-L12  Android 4.4内存泄漏问题

### ISSUE THREAD

**Issue by sugarkawhi** [CarGuo/GSYVideoPlayer#40]
![Uploading FB9CE3C10A9A7846DCD1D17E49D2C5FB.jpg…]()

**Comment by sugarkawhi** [comment]
AudioManager泄漏  
在GSYVideoPlayer中
`mAudioManager = (AudioManager)this.getContext().getSystemService("audio");`
改为
`mAudioManager = (AudioManager)this.getContext().getApplicationContext().getSystemService("audio");`
可修复。

**Comment by sugarkawhi** [comment]
图片一致上传不成功....

**Comment by CarGuo** [comment]
这个泄露一直知道，你完全测试过吗？我这边在很久前测试过，修改为如此也是会发生。而查阅显示，这个泄露并太大问题，可以自行忽略。

**Comment by sugarkawhi** [comment]
如果是原来那样写，播放几个视频后就会内存溢出，CPU占用300M。改完之后，几乎没有内存溢出，内存占用100M。
就在Huawei H60 上有这个问题，其他测试机没问题。
所以这个泄漏在个别机型上可能会有不小的问题。

**Comment by CarGuo** [comment]
好吧，这样的，那我修改下吧，因为我在魅族上怎么改都不行

**Comment by PiPiCaptain** [comment]
@CarGuo 
![11111](https://cloud.githubusercontent.com/assets/22672329/21917148/9ab7852c-d980-11e6-8802-590a49d27622.png)
这个问题，好像的确比较严重，我才点了二次这个界面，就有546KB内存泄漏了

**Comment by CarGuo** [comment]
如果你点开右边的加号去看，就会发现这个其实是因为系统原因，个人用了这么久没什么影响的，像楼上的特殊机型就不清楚了。

**Comment by sugarkawhi** [comment]
个别机型的问题 Huawei H60 每次都是几M的泄漏
的确是系统问题 打开描述也有提到 在M后有修复
修改后 这个问题在我这测试没有出现 你可以先自己修改一下试试 @PiPiCaptain

**Comment by PiPiCaptain** [comment]
@sugarkawhi 我现在是像修复WebView泄漏一样，为视频的Activity新开一个进程，onDestroy时杀死这个进程

**Comment by PiPiCaptain** [comment]
@sugarkawhi 因为我的APP，是收费才能用的。项目很大，界面很多，而且逻辑也复杂。不解决这些内存泄漏，会扣绩效

**Comment by CarGuo** [comment]
update by v1.5.7

**Comment by PiPiCaptain** [comment]
@sugarkawhi @CarGuo 
刚刚试了一下，无论是WebView或者是GSYVideoPlayer，如果是用Fragment加载，好像就不会泄漏了，起码Leaks不会提示。Activity回收，Fragment必定会回收，跟Fragment生命周期有关？

**Comment by PiPiCaptain** [comment]
@sugarkawhi @CarGuo 
有什么看法？

**Comment by CarGuo** [comment]
@PiPiCaptain 个人觉得，是刚好出现！哈哈，因为fragment上的context获取的，那个context还是activity的，其实是一样的，这个泄漏主要是系统的bug导致，所以个人觉得都是一样。
