### ISSUE TITLE
请教m3u8 自动刷新 切片的问题

### ISSUE THREAD

**Issue by w651441914** [CarGuo/GSYVideoPlayer#4002]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

m3u8文件中的切片只返回了一部分，比如完成的m3u8播放时长是4分钟  ，再开始播放的时候切片只有1分钟，是否可以在播放过程中自动刷新后续切片

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.5-release-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
HLS 本身就支持直播模式·····

**Comment by w651441914** [comment]
您好，我有设置  PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);   但是在播放的时候首次加载m3u8 假如有1分钟   播放一分钟过程中并没有自动更新后续的 切片  是我哪里没设置对吗？ 求教，感谢您的回复

**Comment by w651441914** [comment]
抱歉 是服务器端文件切片的问题
