### ISSUE TITLE
视频列表，需要对为展示过的视频预加载缓存，该掉哪个方法呢？

### ISSUE THREAD

**Issue by KeShiJie** [CarGuo/GSYVideoPlayer#4004]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ 视频列表，需要对为展示过的视频预加载缓存，该掉哪个方法呢？

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
/**
     清除缓存

     @param cacheDir 缓存目录，为空是使用默认目录
     @param url      指定url缓存，为空时清除所有
     */
    public void clearDefaultCache(Context context, @Nullable File cacheDir, @Nullable String url) {
