### ISSUE TITLE
与【com.danikula:videocache】依赖冲突的尴尬问题

### ISSUE THREAD

**Issue by KeQian** [CarGuo/GSYVideoPlayer#4006]
private const val version="v8.6.0-release-jitpack"
     const val videoPalyer= "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:$version"
 
   api(Deps.gsyVideo.videoPalyer){
        exclude("com.github.CarGuo.GSYVideoPlayer","gsyvideoplayer-androidvideocache")
//        exclude("com.danikula","videocache")
    }

以上是我的引用：

问题描述：
gsyvideoplayer-androidvideocache 中包含和 com.danikula:videocache 一样的代码，com.danikula:videocache又不能去掉，排除掉gsyvideoplayer-androidvideocache ，GSYVideoPlayer又不能正常播放。

**Comment by CarGuo** [comment]
还是有点不一样，但是 gsy 的理论上是可以兼容com.danikula的，建议 排除 com.danikula

**Comment by CarGuo** [comment]
因为要要改一些东西，所以就fork过来修改了，它六年没改过了······类似这样处理

  implementation('com.example.library:library-a:1.0.0') {
        exclude group: 'com.example.library', module: 'module-to-exclude'
    }


  implementation('com.example.library:library-a:1.0.0') {
        exclude group: 'com.example.library', module: 'module-to-exclude'
    }
