### ISSUE TITLE
关于继承StandardGSYVideoPlayer重写onError方法的问题

### ISSUE THREAD

**Issue by cnhuz** [CarGuo/GSYVideoPlayer#4007]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在一些设备上，运行一段时间后，有概率会触发onError，不做处理的话，会出现视频停止播放的问题（黑屏），以下是遇到onError做的处理，现在遇到what：4003，extra：1时，这种处理不能恢复正常播放，想请教下大佬一般怎么处理会更好，也想知道这些错误码代表什么，翻了好久没翻到错误码说明。使用的是EXOPlayer内核。
```
    override fun onError(what: Int, extra: Int) {
        LogHelper.e(TAG,"onError---$what---$extra")
        onVideoReset()
        mTmpManager?.releaseMediaPlayer()
        post {
            setUp(url, false, null, "")
            startPlayLogic()
        }
        ...
    }
```

## 问题机型/系统：

真机，3288定制板 Android7.0

## GSY依赖版本

`implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.5.0-release-jitpack'`

`implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.5.0-release-jitpack'`

## Demo中的复现步骤

无

问题代码：无

## 问题log（如果有）

无

**Comment by CarGuo** [comment]
public static final int ERROR_CODE_DECODING_FAILED = 4003;


<img width="1012" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/309ee00e-d1f1-44b5-91a9-df7cc4777482">
