### ISSUE TITLE
请问怎么像IjkMediaPlayer一样传入Surface播放

### ISSUE THREAD

**Issue by baboony** [CarGuo/GSYVideoPlayer#4009]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
这是我从vcamsx拉的代码 目前想把IjkMediaPlayer改成gsyvideoplayer 但我看源码都是传入Context（vcamsx是虚拟摄像头项目：https://github.com/iiheng/VCAMSX）
    fun playRTMPStream(holder: SurfaceHolder, rtmpUrl: String) {
            ijkMediaPlayer = IjkMediaPlayer().apply {
                try {
                    // 硬件解码设置,0为软解，1为硬解
                    setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 0)
                    setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1)
                    setOption(
                        IjkMediaPlayer.OPT_CATEGORY_PLAYER,
                        "mediacodec-handle-resolution-change",
                        1
                    )

                    // 缓冲设置
                    setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1)
                    setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0)
                    setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec_mpeg4", 1)
                    setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "analyzemaxduration", 100L)
                    setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "probesize", 1024L)
                    setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "flush_packets", 1L)
                    setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "packet-buffering", 1L)
                    setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1L)

                    // 错误监听器
                    setOnErrorListener { _, what, extra ->
                        Log.e("IjkMediaPlayer", "Error occurred. What: $what, Extra: $extra")
                        Toast.makeText(context, "直播接收失败$what", Toast.LENGTH_SHORT).show()
                        true
                    }

                    // 信息监听器
                    setOnInfoListener { _, what, extra ->
                        Log.i("IjkMediaPlayer", "Info received. What: $what, Extra: $extra")
                        true
                    }

                    // 设置 RTMP 流的 URL
                    dataSource = rtmpUrl

                    // 设置视频输出的 SurfaceHolder
                    setDisplay(holder)

                    // 异步准备播放器
                    prepareAsync()

                    // 当播放器准备好后，开始播放
                    setOnPreparedListener {
                        Toast.makeText(context, "直播接收成功，可以进行投屏", Toast.LENGTH_SHORT)
                            .show()
                        start()
                    }
                } catch (e: Exception) {
                    Log.d("vcamsx", "播放报错$e")
                }
            }

    }

## 出现问题的视频流
rtmp://liteavapp.qcloud.com/live/liteavdemoplayerstreamid

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
Surface 是在 View UI 层传入给 Manager 最终传入 PlayerManager ，如下图参考

![](https://raw.githubusercontent.com/CarGuo/GSYVideoPlayer/master/img/StructureChart2.jpg)

**Comment by baboony** [comment]
对不起，我不太明白；请问有示例吗
