### ISSUE TITLE
全屏不显示缩略图

### ISSUE THREAD

**Issue by cwyrzz** [CarGuo/GSYVideoPlayer#401]
横屏全屏，播放完毕状态下，不显示缩略图

**Comment by CarGuo** [comment]
是不会

**Comment by cwyrzz** [comment]
可否添加支持呢？

**Comment by CarGuo** [comment]
你可以继承后增加

**Comment by cwyrzz** [comment]
好的，还有个问题想请教一下，我进去界面就自动播放，调用startPlayLogic()，怎样让它进去播放不显示暂停按钮，和进度条这些位置，应该重写哪里？

**Comment by CarGuo** [comment]
看一下有一个tooglexxx之类的方法，或者源码中显示小屏幕的实现。

**Comment by cwyrzz** [comment]
好的，解决了，再问下，双击播放双击暂停是哪个方法

**Comment by cwyrzz** [comment]
找到了
