### ISSUE TITLE
循环播放LOOP 动态设置，无法取消 循环，

### ISSUE THREAD

**Issue by GuoFeilong** [CarGuo/GSYVideoPlayer#4010]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放视频的时候，设置播放器为循环播放，当前视频开始循环播放，
然后动态的修改播放器为取消循环，但是播放器，loop变量修改之后，没有生效，一直还在循环。

## 出现问题的视频流

无
## 问题机型/系统：

三星
## GSY依赖版本

gsy_video_player_version = "v8.6.0-release-jitpack"

## Demo中的复现步骤

demo中没有类似的操作。

![image](https://github.com/CarGuo/GSYVideoPlayer/assets/12525861/e6c26b37-7155-47b9-89c7-3f29df2e79e6)

点击小节循环，此时播放器变成循环播放，没有问题，

我再次点击取消 循环的时候，循环状态无法退出，一直在循环。

问题代码：(如果有)
```
<img width="1013" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/12525861/b4572e69-b42a-46f7-be1c-ebc039663256">
继承了 标准播放器，自定义了一个 循环，按钮，点击循环按钮，动态切换播放器循环状态。

取消循环无法生效

```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by GuoFeilong** [comment]
动态修改了loop之后，必须重新调用prepare 才能把参数 更新到播放器的实现类里面，要不然该外面的变量 ，他只改的是上层的 值，播放器内部的值是没有刷新的。

**Comment by GuoFeilong** [comment]
但是如果 手动调用 prepare的话，会刷新播放器，体验不是太好。比如博到一半，从头开始了。

**Comment by GuoFeilong** [comment]
内部GSY GSYModel 的值 无法修改。如果不调用 startPrepare

**Comment by GuoFeilong** [comment]
<img width="1076" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/12525861/91415a7e-4b45-4802-9a6a-65259da2371e">
如何动态修改 GSY model 中的值，且不用重新初始化呢。

**Comment by GuoFeilong** [comment]
<img width="999" alt="image" src="https://github.com/CarGuo/GSYVideoPlayer/assets/12525861/01cd5cf2-56a0-48bc-bd08-77d2cc91f074">

看了下源码，没有找到合适的刷新 GSY 的时机，所以只能通过这种非正规的模式，去修改 EXO底层 播放器 真正的播放模式，

如果作者看到了请回复下，是不是我使用的姿势有问题，还是说这块 确实有问题，就是先开启循环，后 在取消循环，取消不了。
我目前用 反射 暂时解决了这个问题。

**Comment by CarGuo** [comment]
非常简单···· Player.getGSYVideoManager().getPlayer().getMediaPlayer()

**Comment by GuoFeilong** [comment]
谢谢 老歌。。我删除反射的代码。。。
