### ISSUE TITLE
使用exo特有缓存下载支持，下载监听 download.contentLength会返回-1

### ISSUE THREAD

**Issue by Zhangxd77** [CarGuo/GSYVideoPlayer#4017]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

问题1 ：点击开始缓存，先输出四次download -1，然后会输出download 185118630，这是不是不太对，有问题
不太明白疑惑请教：若已设置边播边缓存，是不是就不需要开始就缓存功能也会缓存？

## 问题机型/系统：

例如 真机 小米11

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:v9.0.0'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

download -1

```

**Comment by CarGuo** [comment]
不要在意，能正常缓存下来就好了，在 exo 模式搭配 exo 缓存模式，配置了 cache true 就行了
