### ISSUE TITLE
Demo双击暂停、播放无效

### ISSUE THREAD

**Issue by SMask** [CarGuo/GSYVideoPlayer#402]
Android 5.0.2 红米Note2
Demo双击暂停、播放无效

**Comment by CarGuo** [comment]
哪个页面？双击只有在已经播放才会生效

**Comment by SMask** [comment]
任意一个界面
首先，播放按钮、进度条、全屏按钮等等，这几个先叫做 “控制界面” 吧；
那么当控制界面显示的时候双击暂停、播放都是正常的；
但是当控制界面隐藏的时候，那么双击暂停、播放好像就有问题了。。。
不知道这样说 明不明白 = =

**Comment by CarGuo** [comment]
了解了，是在控制层消失的时候，双击有问题了！

**Comment by SMask** [comment]
对头~就是双击播放/暂停 和 单击显示/隐藏控制层 应该相互独立互不干扰~

**Comment by CarGuo** [comment]
嗯嗯，下个版本更新

**Comment by CarGuo** [comment]
2.0.6更新

**Comment by SMask** [comment]
现在双击的时候，控制层会闪现一下
应该是也触发单击事件了吧 = =
看代码双击换成 GestureDetector 的 onDoubleTap了
那么单击也换成 GestureDetector 的 onSingleTapConfirmed 吧
这样单击和双击就不会冲突了- -

**Comment by CarGuo** [comment]
单击那一块的逻辑还有有点麻烦和其他问题，需要后面在撸一撸。

**Comment by SMask** [comment]
原来如此  干巴爹

**Comment by a1018875550** [comment]
双击与单击事件的冲突还是没有解决呀
