### ISSUE TITLE
StandardGSYVideoPlayer 不支持 PIP吗？

### ISSUE THREAD

**Issue by leviluo** [CarGuo/GSYVideoPlayer#4021]
使用系统PIP，enterPictureInPictureMode 之后，StandardGSYVideoPlayer会被重新init？

**Comment by leviluo** [comment]
那个体验不如原生的PIP

**Comment by leviluo** [comment]
> demo 里的倒是有 window 浮窗实现，你可以看看，可以参考它的实现 WindowActivity

那个体验不如原生的PIP

**Comment by CarGuo** [comment]
哦，你要系统的啊，那不是更简单····  onPause 和  AndroidManifest 声明下就好了啊

**Comment by CarGuo** [comment]
👆 如上提交

**Comment by leviluo** [comment]
> 👆 如上提交

另外一个bug，PIP模式下，点击关闭按钮，视频还在继续播放

**Comment by CarGuo** [comment]
我只是给你指出方向，不是帮你完成需求

**Comment by leviluo** [comment]
> 我只是给你指出方向，不是帮你完成需求

哦哦，辛苦大佬了
