### ISSUE TITLE
G711a音频建议加到ex-so ffmpeg配置中

### ISSUE THREAD

**Issue by HadisNZL** [CarGuo/GSYVideoPlayer#4023]
![WX20240827-124343@2x](https://github.com/user-attachments/assets/663056bb-53c3-4cbe-9f01-e2176f098fc5)
G711a音频建议加到ex-so ffmpeg配置中，即，export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_alaw"，export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-encoder=pcm_alaw"，因为嵌入式设备输出此音频能减小压力，对于一些初学者，也减少了编译

**Comment by CarGuo** [comment]
编译了一个 arm64 支持

**Comment by HadisNZL** [comment]
效率，感谢楼主
