### ISSUE TITLE
关于ijkplayer 16k编译疑惑，请教楼主问题，

### ISSUE THREAD

**Issue by HadisNZL** [CarGuo/GSYVideoPlayer#4024]
<img width="1087" alt="image" src="https://github.com/user-attachments/assets/55bc1480-9868-4f2e-934e-eab3208cf926">
第一个问题？：
基于拉下来的ijk源码，修改了上图所说，那么其源码中C代码有需要改“ 4096 搭配 mmap 、sysconf ，0x1000等相关地方”吗，如您第二篇文章所说的，简单粗暴的搜索，我费好大劲，汗，没有搜出来，所以问问您是不是只改第一张图配置即可；
第二个问题？：
也是16k相关，关于配置ffmpeg编解码时，module.sh,需要加export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --extra-cflags=-DFFMPEG_PAGE_SIZE=16384"吗；
您是过来人，请您给指点下，

**Comment by CarGuo** [comment]
针对 IJK
1、没有修改 mmap 、sysconf 的地方
2、主要是修改脚本，各种 mk 文件 和 sh 文件配置 ，这里的 patch 就是 git 的 diff patch ，基于 ijk master 可用

**Comment by HadisNZL** [comment]
感谢楼主
