### ISSUE TITLE
目前发现两个问题：setSeekOnStart和滑动界面调进度

### ISSUE THREAD

**Issue by penghang88** [CarGuo/GSYVideoPlayer#4026]
1.使用setSeekOnStart（time）时，播放器会先播放开始的视频大概零点几秒，再加载设置的time时间点的视频。现象就是像卡了一下，不知道如何解决。
2.如果滑动界面调节进度（不是滑动下面的进度条），不能像滑动底部进度条一样，可以多次滑动。滑动一次后，会加载，再滑动的话就不行了。底部进度条滑动，就算是在加载，也可以滑动，滑动后视频能正常播放。这个也不知道如何解决。

**Comment by CarGuo** [comment]
1、设定如此
2、setSeekRatio
