### ISSUE TITLE
ijkplayer so放到module里，运行时出现以下错误，gradle版本是3.3

### ISSUE THREAD

**Issue by petersom** [CarGuo/GSYVideoPlayer#403]
so放在其中一个module的jni目录，运行时会出现以下错误，
gradle是2.3.3
com.android.tools.build:gradle:2.3.3

Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDevDebug'.

com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libijkplayer.so
File1: C:\Users\E1\AndroidStudio\branches_sdk\app\build\intermediates\exploded-aar\tv.danmaku.ijk.media\ijkplayer-armv7a\0.7.9\jni
File2: C:\Users\E1\AndroidStudio\[project]\[module]\build\intermediates\bundles\default\jni
请问有人遇到过这问题吗？
[https://github.com/Bilibili/ijkplayer/issues/3500](url)

**Comment by CarGuo** [comment]
不理解，gsy的问题？？

**Comment by petersom** [comment]
不是，比如我把gsy放到一个module， 然后so文件也是在这个module里的jni目录中，然后编译整个project的时候就会报这个错
Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDevDebug'.

com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libijkplayer.so
File1: C:\Users\E1\AndroidStudio\[XXX]\app\build\intermediates\exploded-aar\tv.danmaku.ijk.media\ijkplayer-armv7a\0.7.9\jni

**Comment by CarGuo** [comment]
为什么so是放在jni？jni下是放源码吖，难道你gradle配置的了路径？？

**Comment by petersom** [comment]
是的  不过我gsy升级到最新之后，app gradle加入以下配置正常了，还是十分感谢！
packagingOptions {

        exclude 'lib/armeabi/libijk**'
        exclude 'lib/armeabi-v7a/libijk**'
        exclude 'lib/x86/libijk**'
    }
