### ISSUE TITLE
播放国标28181没有声音   是否支持国标28181视频流播放？

### ISSUE THREAD

**Issue by IronMan111** [CarGuo/GSYVideoPlayer#4030]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）
播放国标28181没有声音   是否支持国标28181视频流播放？

## ⚠️提问前建议先看看： https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
播放国标28181没有声音   是否支持国标28181视频流播放？

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题
是否支持国标28181的所有视频流

### ❗❗❗⚠️⚠️⚠️这个很重要！！！！没有问题流的问题无法处理复现⚠️⚠️⚠️❗❗❗
我们公司测试机都没有声音 小米10 

## GSY依赖版本
 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.4.0-release-jitpack'

**Comment by CarGuo** [comment]
·音频编码和视频编码是什么

**Comment by wsdydeni** [comment]
> ·音频编码和视频编码是什么

还在更新维护，牛蛙牛蛙
