### ISSUE TITLE
Unable to Find `EmptyControlVideo` in GSYVideoPlayer

### ISSUE THREAD

**Issue by Usman-Click** [CarGuo/GSYVideoPlayer#4031]
Hello,

I'm using GSYVideoPlayer (version `v9.0.0-release-jitpack`) and wanted to use the `EmptyControlVideo` class for a minimal control interface. However, I can't find this class in the library.

I've checked the documentation but couldn't locate it. Could you clarify if this class has been removed, renamed, or replaced?

Here’s the code I attempted:

```java
EmptyControlVideo emptyControlVideo = findViewById(R.id.empty_control_video);
emptyControlVideo.setUp(videoUrl, true, "Video Title");
emptyControlVideo.startPlayLogic();
```

Thanks for your assistance!

**Comment by CarGuo** [comment]
in demo : https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/EmptyControlVideo.java

**Comment by Usman-Click** [comment]
Thanks :)
