### ISSUE TITLE
Demo 代码ViewPager2Activity 不断的滑动切换视频自动播放，线程数飙升

### ISSUE THREAD

**Issue by VK2012** [CarGuo/GSYVideoPlayer#4033]
## 问题描述：

使用源码Demo 代码ViewPager2Activity ，不断的滑动切换视频自动播放，android profiler 查看cpu native线程数飙升

## 问题机型/系统：

华为p40 鸿蒙4.0

## Demo中的复现步骤

Demo中的ViewPager2Activity ，不断的滑动切换视频自动播放。android profiler 查看cpu  线程数

[
![screenshot-20241009-180802](https://github.com/user-attachments/assets/30280c86-1abc-4ee2-88b8-c06796c131cb)
](url)

**Comment by VK2012** [comment]
引用版本implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v9.0.0-release-jitpack' 同样有这个问题

**Comment by CarGuo** [comment]
AS Designs
