### ISSUE TITLE
 在使用ViewPager2Activity的仿抖音上下滑列表的时候如何添加播放当前视频预加载下一个视频呢

### ISSUE THREAD

**Issue by zhouzitao** [CarGuo/GSYVideoPlayer#4034]
## 问题描述：

在使用ViewPager2Activity的仿抖音上下滑列表的时候如何添加播放当前视频预加载下一个视频呢

**Comment by CarGuo** [comment]
给一个方向：你自定义source，例如 exoplayer 里的 ConcatenatingMediaSource2  ，可以 addMediaSource，另外他也有预加载我记得

或者直接一批视频直接用一个 Manager ，类似 Demo 里 SmartPickVideo 的 mTmpManager 那样去做每一批列表视频播放时的切换
