### ISSUE TITLE
ViewPager2 上下滑动列表中如何实现预加载下一个视频或者实现预加载两个到三个视频

### ISSUE THREAD

**Issue by zhouzitao** [CarGuo/GSYVideoPlayer#4036]
## 问题描述：

求助大佬Demo中ViewPager2 上下滑动列表中如何实现预加载下一个视频或者实现预加载两个到三个视频

## 问题机型/系统：

 真机 realme Android11

## GSY依赖版本

例如  implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v9.0.0-release-jitpack'

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/4034 这里不是回复给你了么，如果你想更简单的思路，考虑 DetailDownloadPlayer ， 或者 DetailDownloadExoPlayer ，提前下载一部分
