### ISSUE TITLE
大佬，有个问题咨询一下，Fragment嵌套俩Fragment，内部都是用的您的仿抖音上下滑动，fragment左右滑动，onpause和onresume直接乱了

### ISSUE THREAD

**Issue by dingliufan** [CarGuo/GSYVideoPlayer#4039]
## 问题描述：

Fragment嵌套俩Fragment，内部都是用的您的仿抖音上下滑动，fragment左右滑动，onpause和onresume中的GSYVideoManager.onPause()、GSYVideoManager.onResume(false)会给错，就是可能我划到左边的界面，显示暂停状态，但是右边的声音开始出现了，因为左边的走了GSYVideoManager.onResume(false)，会让右边的开始播放,点击播放可以正常播，但还是希望可以滑动暂停，滑回来播放这种方式

## 问题机型/系统：

例如 真机 Rradmi 5A android7.1.2

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v9.0.0-release-jitpack'

**Comment by CarGuo** [comment]
不解决具体需求问题
