### ISSUE TITLE
StandardGSYVideoPlayer上方view的OnClickListener一直被自动触发

### ISSUE THREAD

**Issue by TrcMiX** [CarGuo/GSYVideoPlayer#4043]
同一个界面在StandardGSYVideoPlayer上覆盖了一些view，在播放过程中，这些view的点击事件一直被自动触发是怎么回事。issues没搜到类似的问题。

**Comment by CarGuo** [comment]
额···demo 我试了下没浮现问题啊

**Comment by TrcMiX** [comment]
找到问题了，是李跳跳一直在自动点击
