### ISSUE TITLE
v2.0.5 最新版本点击全屏报空指针异常：

### ISSUE THREAD

**Issue by 18710891669** [CarGuo/GSYVideoPlayer#405]

**Comment by 18710891669** [comment]
![default](https://user-images.githubusercontent.com/15627485/29802715-b3a6ccc8-8ca9-11e7-99e4-9d30e3e25e61.png)

**Comment by CarGuo** [comment]
custom播放类？这个类目前没有维护了，参考demo中的继承实现

**Comment by 18710891669** [comment]
还有个问题  之前版本设置完播放url后如果是wifi情况下，调用detailPlayer.startPlayLogic();直接播放了   现在v2.0.5，点击详情可以实现自动播放么？

**Comment by CarGuo** [comment]
播放逻辑没变啊…
