### ISSUE TITLE
各位大佬有做过视频双指放大、单指移动的功能吗？需要在那个类里做修改？

### ISSUE THREAD

**Issue by zhangkun0018** [CarGuo/GSYVideoPlayer#4050]
各位大佬，在仿抖音列表播放视频时，有做过双指放大、单指移动的功能吗？

**Comment by CarGuo** [comment]
加了个简单例子，没做任何优化， https://github.com/CarGuo/GSYVideoPlayer/blob/f6b5e36dae5593c13e1f8befde47efe48bae806e/app/src/main/java/com/example/gsyvideoplayer/video/LandLayoutVideo.java#L71 可以参考作为入手点

**Comment by zhangkun0018** [comment]
谢谢
