### ISSUE TITLE
H265编码的链接播放黑屏但有声音

### ISSUE THREAD

**Issue by Liyl520hub** [CarGuo/GSYVideoPlayer#4052]
## 问题描述：

项目视频播放升级使用H265编码，播放的时候画面黑屏，但是有声音，用demo最新版（10.0.0）播放也是黑屏有声音。
这个链接用ffplay播放是没有问题的，可以看到画面。
<img width="902" alt="image" src="https://github.com/user-attachments/assets/311c45fe-330c-4112-a606-9f295a867e37">

## 出现问题的视频流

http://106.58.167.201:18090/meeting-live/za2eQf.flv  或者 rtmp://106.58.167.201:1936/meeting-live/za2eQf

## 问题机型/系统：

真机 小米MIX4  Android14

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-java:v10.0.0'
    //是否需要ExoPlayer模式
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-exo2:v10.0.0'
    //是否需要AliPlayer模式
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-aliplay:v10.0.0'
    //更多ijk的编码支持
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-ex_so:v10.0.0'

## Demo中的复现步骤

Demo中的【输入URL】输入上面的链接播放，就可以复现

**Comment by CarGuo** [comment]
如图，你的视频：

<img width="666" alt="image" src="https://github.com/user-attachments/assets/163d6a00-10d5-454f-a94a-3cd34f570332">

如图，正常 h265 视频：

https://avtshare01.rz.tu-ilmenau.de/avt-vqdb-uhd-1/test_1/segments/water_netflix_750kbps_720p_59.94fps_hevc.mp4

<img width="646" alt="image" src="https://github.com/user-attachments/assets/95c7d943-f906-4236-9d6f-ae96c9ee1da7">

**Comment by Liyl520hub** [comment]
您的意思是该链接的视频流非H265编码是吗？这个实时分析视频流工具是什么？大佬可否告知一下，感谢~

**Comment by CarGuo** [comment]
目前我看 ff 的log ，写的是找不到可以解码的 format  格式，我测试正常 hevc 的格式是可以播放的，用的 gsyVideoPlayer-ex_so 的 so

**Comment by Liyl520hub** [comment]
是说的这些错误日志是吧？貌似解决这个问题智能修改视频流的源头？我们播放器可以适配吗？
is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.

If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)

Could not find codec parameters for stream 1 (Video: none, none): unknown codec
    Consider increasing the value for the 'analyzeduration' and 'probesize' options

**Comment by CarGuo** [comment]
你这个应该不是直播流，其实你正常把视频封装 mp4，理论上 hevc 是不会有什么问题

**Comment by Liyl520hub** [comment]
我问了一下，这个视频流确实是直播流，用ffmpeg推的，而且只用了flv包装格式。

**Comment by CarGuo** [comment]
哦，直播的 h265 需要到  FFMpeg 6.1  之后才支持有我记得，另外系统 mediacodec 我记得也是不支持的

**Comment by Liyl520hub** [comment]
那就是说需要升级版本才有可能正常播放？

**Comment by CarGuo** [comment]
嗯，你需要自己升级 FFMpeg 版本

**Comment by Liyl520hub** [comment]
好的，感谢大佬
