### ISSUE TITLE
从v9.0.0升级到v10.0.0后编译失败

### ISSUE THREAD

**Issue by hust-twj** [CarGuo/GSYVideoPlayer#4054]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

从 v9.0.0-release-jitpack 升级到 v10.0.0 后，工程编译失败。问题截图：
![image](https://github.com/user-attachments/assets/92aae1b0-6993-4612-8e14-95f77495b4e2)

## GSY依赖版本

例如 `implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v10.0.0`

**Comment by CarGuo** [comment]
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/f8192141-3910-4b1f-af41-869a72cc8177">


implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-java:v10.0.0'

 //是否需要ExoPlayer模式
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-exo2:v10.0.0'

 //是否需要AliPlayer模式
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-aliplay:v10.0.0'

 //根据你的需求ijk模式的so
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-arm64:v10.0.0'
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-armv7a:v10.0.0'
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-armv5:v10.0.0'
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-x86:v10.0.0'
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-x64:v10.0.0'

**Comment by CarGuo** [comment]
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-java:v10.0.0'


不是。

**Comment by hust-twj** [comment]
> implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-java:v10.0.0
> 
> implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v10.0.0
> 
> 你看下有什么不同？

感谢。我还以为只改变了版本号，大小写也变了。。
