### ISSUE TITLE
大佬 exo2字幕功能不好使啊 demo好像就是有bug的 字幕显示的不是实际的链接

### ISSUE THREAD

**Issue by benwangdroid** [CarGuo/GSYVideoPlayer#4057]
demo就有bug  换什么字幕链接都显示的同一个

**Comment by CarGuo** [comment]
更细了新的 demo ，可以看看，之前那个是 m3u8 问题

**Comment by benwangdroid** [comment]
感谢 mp4能正常显示字幕了   m3u8换了几个language还是不行

**Comment by CarGuo** [comment]
刚重新更新了下例子，因为之前测试 m3u8 内嵌字幕解析的时候没注意，这里 demo 的 m3u8 加上外挂字幕，是存在两个 text track 的，所以如果要显示外挂的，需要切换下，具体看刚提交的 demo

![image](https://github.com/user-attachments/assets/0ab9da86-134f-47b6-9713-3ab860a49c39)
