### ISSUE TITLE
Demo中ViewPager2列表视频全屏问题

### ISSUE THREAD

**Issue by ordinaryX** [CarGuo/GSYVideoPlayer#4061]
## 问题描述：

Demo中ViewPager2列表页，播放第一个视频，点击全屏，这时并没有真正进入全屏，而是页面反转为横屏。如图
![Screenshot_20241123_161958](https://github.com/user-attachments/assets/bdad15b2-87da-401b-8db3-5a325550b7f6)
![Screenshot_20241123_162017](https://github.com/user-attachments/assets/4884eda5-0392-456f-96a6-b8d48ecc7bfa)

请问这个是正常的吗？是否应该是视频进入全屏播放的状态。

## 问题机型/系统：

真机 vivo neo5 Android14

## GSY依赖版本

10.0.0 release demo

**Comment by CarGuo** [comment]
看 demo
