### ISSUE TITLE
gsyvideoplayer-exo2 jetpack版本无法同步到本地

### ISSUE THREAD

**Issue by chenzhenpeng** [CarGuo/GSYVideoPlayer#4066]
gsyvideoplayer-exo2无法同步到本地，jetpack 版本的一直无法同步成功，其他的几个正常

**Comment by CarGuo** [comment]
目前这几个版本测试正常，jitpack 近段时间一直存在丢包问题 ：https://github.com/jitpack/jitpack.io/issues/6645 ：

https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyvideoplayer-exo2/v10.0.0/gsyvideoplayer-exo2-v10.0.0.aar

https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-ex_so/v8.5.0-release-jitpack/gsyVideoPlayer-ex_so-v8.5.0-release-jitpack.aar

https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-ex_so/v9.0.0-release-jitpack/gsyVideoPlayer-ex_so-v9.0.0-release-jitpack.aar


所以才迁移一份支持到 Github package ：

https://github.com/CarGuo/GSYVideoPlayer/packages/2297500

**Comment by lyb5834** [comment]
> 目前这几个版本测试正常，jitpack 近段时间一直存在丢包问题 ：[jitpack/jitpack.io#6645](https://github.com/jitpack/jitpack.io/issues/6645) ：
> 
> https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyvideoplayer-exo2/v10.0.0/gsyvideoplayer-exo2-v10.0.0.aar
> 
> https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-ex_so/v8.5.0-release-jitpack/gsyVideoPlayer-ex_so-v8.5.0-release-jitpack.aar
> 
> https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-ex_so/v9.0.0-release-jitpack/gsyVideoPlayer-ex_so-v9.0.0-release-jitpack.aar
> 
> 所以才迁移一份支持到 Github package ：
> 
> https://github.com/CarGuo/GSYVideoPlayer/packages/2297500

你好，`v8.3.4-release-jitpack` 这版本的 `ex_so` 也丢包了，无法获取

**Comment by CarGuo** [comment]
@lyb5834  尽量用新版本或者依赖 github package 的， jitpack 之前有过一段时间疯狂丢包

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/4144
