### ISSUE TITLE
返回键设置不显示

### ISSUE THREAD

**Issue by 18710891669** [CarGuo/GSYVideoPlayer#407]
![default](https://user-images.githubusercontent.com/15627485/29812663-ef90581e-8cd9-11e7-8033-5b97f001cd9d.png)

**Comment by CarGuo** [comment]
这一块目前有bug，下个版本修复，你可以继承后实现自己的返回按键，或者参考https://github.com/CarGuo/GSYVideoPlayer/issues/380

**Comment by CarGuo** [comment]
2.0.6更新
