### ISSUE TITLE
Android中ijkplayer支持ffmpeg命令行的功能，

### ISSUE THREAD

**Issue by HadisNZL** [CarGuo/GSYVideoPlayer#4074]
楼主大人：小白有个问题  比如
String[] cmd = new String[]{"ffmpeg", "-i", inputPath,        // 输入文件
//                    "-c:v", "copy",         // 复制视频流
                    "-c:a", "aac",          // 转换音频为 AAC
//                    "-b:a", "128k",         // 设置音频比特率为 128 kbps
                    outPath              // 输出文件路径
            };
   FFmpegCmd.FFmpegExec(cmd)；
直接调用jni桥接的cmd命令就能转码，就行电脑端一点，一个命令就完事了，我有个h265和g711a的mp4视频，我想把g711a转成aac然后跟h265输出mp4，可能功力浅显，ffmpeg内部搞不明白，这样做的好处就是省了再集成ffmpeg，能不能有时间出一期，

**Comment by CarGuo** [comment]
不支持，因为就是 ffplay 播放而已

**Comment by HadisNZL** [comment]
哦哦，明白了，感觉您说的对，方向有点偏了，感谢指点
