### ISSUE TITLE
startWindowFullscreen()方法

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#41]
![c9e4e123-cd4b-403a-b770-c884f3be026f](https://cloud.githubusercontent.com/assets/22672329/21884933/68cb31f2-d8f0-11e6-9a71-8b0691fceb16.png)
如上图，我重写了startWindowFullscreen，但是全屏时，没有接着横屏的时间点播放。这个怎么搞？

**Comment by CarGuo** [comment]
请查阅首页链接的相关问题集锦，参考demo，配置好你的manifest。
