### ISSUE TITLE
多个页面集成播放器，跳转问题

### ISSUE THREAD

**Issue by SMask** [CarGuo/GSYVideoPlayer#414]
比如
A ,B两个Activity，都集成了StandardGSYVideoPlayer
并集成以下方法

    @Override
    protected void onPause() {
        super.onPause();
        GSYVideoManager.onPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        GSYVideoManager.onResume();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        GSYVideoPlayer.releaseAllVideos();
    }

如果A点击开始播放，在 “视频正在播放” 或者 “视频暂停” 的状态下，
此时点击跳转B，那么A页面会暂停一下再从头继续播放，
关闭B返回A，A的进度当然也丢失了。

目测好像是GSYVideoManager单例的问题？
不知道有没有什么好的解决办法...

能像微博那样也行

**Comment by CarGuo** [comment]
你可以在跳转的时候，记录当前位置，然后下次回来的时候设置开始播放的偏移量，有对应的设置接口，这样播放的时候就可以从偏移量开始播放了。

**Comment by WalkingRoy** [comment]
因为不能有多个视频实例，我现在就遇到两种页面间的跳转：

1.简单的，像这样：A -> B -> A 
2.复杂的：A -> B -> C -> D -> C -> B -> A 
A，D 为视频播放页面，B，C 为普通页面，为了回到 A 后能再重新播放到暂停时的位置，需要增加需要额外的变量来维护，虽说实现不难，但仅仅一直靠变量来维护，代码可阅读性感觉最后会变差。

3.彼此两个视频播放界面，也可能是不同类型的播放器，EXO 与 IKJ Player 两种。
