### ISSUE TITLE
能否取得视频宽高或者比例

### ISSUE THREAD

**Issue by cwyrzz** [CarGuo/GSYVideoPlayer#415]
您好，请问能否取得视频宽高或者比例

**Comment by CarGuo** [comment]
可以，GSYVideoManager有接口

**Comment by cwyrzz** [comment]
竖屏的视频，获取宽高不对，宽度比高度还要大

**Comment by CarGuo** [comment]
因为可能存在rotation属性

**Comment by cwyrzz** [comment]
可否获取其rotation属性

**Comment by CarGuo** [comment]
已经获取了，看GSYManager的onInfo和GSYVideoView的onInfo

**Comment by cwyrzz** [comment]
那我应该如何获取正确的宽高比

**Comment by CarGuo** [comment]
在info回调中判断宽高

**Comment by cwyrzz** [comment]
虽然不知道如何在info判断宽高，不过需求已解决，谢谢
