### ISSUE TITLE
怎么使用UDP发送请求？

### ISSUE THREAD

**Issue by dev-fancyluo** [CarGuo/GSYVideoPlayer#416]
默认的TCP发送请求连接RTMP直播老是会断线

**Comment by dev-fancyluo** [comment]
当我故意使连接错误的时候，会报 Cannot open connection tcp://live.hkstv.hk.lxdns.co:1935
可以知道是使用tcp连接的，那么我想使用UDP进行连接该怎么设置？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh  ex的编辑脚本，udp目前没有disable，不过也没有enable，你可以试试udp能不能直接使用，如果不行你可以重新编译下试试加上
```
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=udp"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-protocol=tcp"
```

http://blog.csdn.net/qq372848728/article/details/62170288 这里也有相关介绍，然后如果想设置option，GSYVideoManager也有对应接口

**Comment by dev-fancyluo** [comment]
我这里没编译环境呢，您能不能更新一下支持？

**Comment by CarGuo** [comment]
这个目前不在计划内
