### ISSUE TITLE
视频向右旋转的时候 怎么是反方向的 

### ISSUE THREAD

**Issue by Leekalun** [CarGuo/GSYVideoPlayer#417]
视频在向右旋转的时候，全屏方向却是反的，只有左侧的方向是对的

**Comment by CarGuo** [comment]
不是很理解，详细描述下？如果是手机向右放，顺时针那些，听筒在右边，画面就向右那是对的。

**Comment by Leekalun** [comment]
就是听筒 听筒顺时针时，进度条朝上，也就是整个视频是倒过来的，而听筒逆时针的时候一切正常

**Comment by CarGuo** [comment]
没在demo中发现问题。
