### ISSUE TITLE
进入后台已经  再返回来 视频会resume,但是跳转再finish回来 却不行

### ISSUE THREAD

**Issue by Leekalun** [CarGuo/GSYVideoPlayer#418]
@Override
    protected void onPause() {
        super.onPause();
//        GSYVideoManager.onPause();
        mPalyer.onVideoPause();
        isPause = true;
        Log.e("pause", "pause");

    }

    @Override
    protected void onResume() {
        super.onResume();
//        GSYVideoManager.onResume();
        mPalyer.onVideoResume();
        isPause = false;

    }

都设置了的,而且我的不是列表，

**Comment by CarGuo** [comment]
你跳过去的页面也有播放视频？

**Comment by Leekalun** [comment]
没有的， 跳过去就是一个评论界面，没有视频。  按home键再返回来  是可以继续播放的，就是跳转finish后 不行

**Comment by CarGuo** [comment]
你看跳转后有没有触发REsume

**Comment by Leekalun** [comment]
打断点 是触发了的,home后台就行  很奇怪

**Comment by CarGuo** [comment]
你试试demo

**Comment by CarGuo** [comment]
或者第二个界面有音频类型的抢占？你在demo上家个跳转试试
