### ISSUE TITLE
关于全屏显示缩略图

### ISSUE THREAD

**Issue by cwyrzz** [CarGuo/GSYVideoPlayer#419]
我希望全屏播放完后可以显示缩略图，请问如何继承，重写什么方法，求点思路

**Comment by CarGuo** [comment]
这个继承播放器后，在全屏接口生成一个用于显示封面图的空间设置给全屏播放器就可以；或者继承后在你的布局的封面图布局下直接加上imageview，然后在全屏接口里设置传递显示封面。

**Comment by cwyrzz** [comment]
您好，可不可以具体一点，全屏接口是哪一个？怎样传递？

**Comment by CarGuo** [comment]
SampleCoverVideo，新增加了一个demo。参考下

**Comment by cwyrzz** [comment]
按照您这个写了，没效果

**Comment by cwyrzz** [comment]
您可不可以在StandardGSYVideoPlayer中加上让全屏播放完毕后也显示缩略图啊

**Comment by CarGuo** [comment]
StandardGSYVideoPlayer不考虑内置
