### ISSUE TITLE
使用ijkplayer在android tv上播放视频，比原声的videoview失真

### ISSUE THREAD

**Issue by zhangfeisysu** [CarGuo/GSYVideoPlayer#42]
使用ijkplayer在android tv上播放视频，比原声的videoview失真。字幕和画面会有明显的锯齿，但是原声的就不会。我打开了硬件解码，也没有解决问题，请楼主赐教啊~

**Comment by CarGuo** [comment]
没有在tv上试过，手机上目前没发现什么问题，难道是因为tv上的屏幕尺寸很大所以看起来很明显了？如果有机会的可以试试。

**Comment by zhangfeisysu** [comment]
经研究发现，是TextureView的原因。对比了官方demo，里面用SurfaceView就没有这个问题。所以如果能优化TextureView的抗锯齿功能，应该就能解决问题了。目前我用的是mTextureView.setScaleX(1.00001f);这个方法来缓解，但我觉得并不是特别好，期待楼主高见。

**Comment by CarGuo** [comment]
目前好像除了 textureView.setScaleX(1.00001f);，还找到什么比较好的方案。
