### ISSUE TITLE
视频插入广告

### ISSUE THREAD

**Issue by weinierfei** [CarGuo/GSYVideoPlayer#420]
请问在视频任意位置插入广告,作者有啥实现思路没?

**Comment by weinierfei** [comment]
@CarGuo 求助

**Comment by CarGuo** [comment]
这一块在规划中，任意位置这个还需要处理音频冲突，只能说暂时没什么好的想法。其实可以这样，在加ADManager，然后在播放ui上多一个Texture，广告的AD时候通过ADManager播放和加载广告的，实现切换隐藏，只要把Audio冲突那块同步下就好。

**Comment by weinierfei** [comment]
感谢回复,我自己在试试哈
