### ISSUE TITLE
在线播放MP4一段时间后会停止，然后报下面的错误，是什么原因呢

### ISSUE THREAD

**Issue by wlxfxy** [CarGuo/GSYVideoPlayer#421]
E IJKMEDIA: stream 1, offset 0x1f4197a: partial file
 E IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
 E IJKMEDIA: Invalid NAL unit size (2135 > 1636).
 E IJKMEDIA: Error splitting the input into NAL units.
 E IJKMEDIA: stream 1, offset 0x1f41b44: partial file
 E IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
 I IJKMEDIA: ffp_toggle_buffering: error: -104
 E IJKMEDIA: stream 1, offset 0x1f42049: partial file
 D IJKMEDIA: FFP_MSG_ERROR: 0
 E tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
 E IJKMEDIA: av_read_frame error: ffffff98(�,�,�,�): unknown
 D IJKMEDIA: IjkMediaPlayer_release

**Comment by CarGuo** [comment]
看不出来

**Comment by CarGuo** [comment]
一般这种情况都是网络断了或者切换网络
