### ISSUE TITLE
部分视频文件无法播放

### ISSUE THREAD

**Issue by heygays** [CarGuo/GSYVideoPlayer#423]
【http://cn-scnc3-dx.acgvideo.com/vg3/6/b7/21652256-1-64.flv?expires=1504513200&platform=html5&ssig=jkp-gJdoUtNCZV2FQCt95Q&oi=3663205980&nfa=NyAaDcVdPuzqmvAn0iNuaA==&dynamic=1&hfa=2073962571&hfb=M2Y2ZWYwZjM2YmRiYmY5MDljYTBiOWE2ZmEwYjJmYTM=】比如这个链接(“【】之内”),在浏览器打开的话会提示下载,按理说播放器应该直接可以播放才对呀,但是无法播放!这是啥原因呢?

**Comment by CarGuo** [comment]
403 Forbidden http://cn-scnc3-dx.acgvideo.com/vg3/6/b7/21652256-1-64.flv?expires=1504513200&platform=html5&ssig=jkp-gJdoUtNCZV2FQCt95Q&oi=3663205980&nfa=NyAaDcVdPuzqmvAn0iNuaA==&dynamic=1&hfa=2073962571&hfb=M2Y2ZWYwZjM2YmRiYmY5MDljYTBiOWE2ZmEwYjJmYTM=

**Comment by heygays** [comment]
链接有时间限制,这是最新的, http://cn-scnc2-dx.acgvideo.com/vg5/5/ea/21652256-1-64.flv?expires=1504574400&platform=html5&ssig=fIQap6gBnWlF7F5ZZLDtlg&oi=3663205980&nfa=NyAaDcVdPuzqmvAn0iNuaA==&dynamic=1&hfa=2074008393&hfb=M2Y2ZWYwZjM2YmRiYmY5MDljYTBiOWE2ZmEwYjJmYTM=
