### ISSUE TITLE
视频没有重力感应

### ISSUE THREAD

**Issue by lhxx225** [CarGuo/GSYVideoPlayer#425]
设置了gsyVideoPlayer.setRotateViewAuto(true)和android:configChanges="orientation|screenSize|keyboardHidden"但是还是只能靠点击切换横竖屏

**Comment by CarGuo** [comment]
手机系统是否没有打开重力，如果没有需要设置不跟随系统的接口

**Comment by lhxx225** [comment]
打开了，我用的jiecao都能重力感应

**Comment by CarGuo** [comment]
参加demo
