### ISSUE TITLE
重力感应全屏问题

### ISSUE THREAD

**Issue by mackkill** [CarGuo/GSYVideoPlayer#426]
目前有个页面是顶部是视屏播放器，下面一个Recyclerview，底部置底一行评论输入框；当开启重力感应旋转横屏后底部的Recyclerview和评论框还是存在。想通过监听回调来隐藏，但是发现重力感应的情况下不会触发回调。想咨询下楼主有什么好的解决方案？多谢了。

**Comment by mackkill** [comment]
配置了呀，就是从demo拷贝的：
<activity android:name=".model.details.VideoDetailActivity"
                  android:configChanges="orientation|keyboardHidden|screenSize"
                  android:screenOrientation="portrait"
                  android:theme="@style/Theme.AppCompat.Translucent"/>
还有哪些需要注意的吗？

**Comment by mackkill** [comment]
上面没显示出代码~~~
<activity android:name=".model.details.VideoDetailActivity"
                  android:configChanges="orientation|keyboardHidden|screenSize"
                  android:screenOrientation="portrait"
                  android:theme="@style/Theme.AppCompat.Translucent"/>

**Comment by mackkill** [comment]
`<activity android:name=".model.details.VideoDetailActivity"
                  android:configChanges="orientation|keyboardHidden|screenSize"
                  android:screenOrientation="portrait"
                  android:theme="@style/Theme.AppCompat.Translucent"/>`

**Comment by CarGuo** [comment]
参考demo吧
