### ISSUE TITLE
请问全屏的时候，有隐藏虚拟键吗？

### ISSUE THREAD

**Issue by yovenny** [CarGuo/GSYVideoPlayer#428]
现在确认华为7.0和moto z play 全屏都没有隐藏虚拟键，这种效果怎么调用？

**Comment by yovenny** [comment]
setHideKey

**Comment by yovenny** [comment]
设置后不行，不知道原因，是api调用不兼容吗

**Comment by CarGuo** [comment]
我这边的nexus6和三星没出现，如果可以还麻烦你那边调试下，看哪里出了问题😄😄

**Comment by yovenny** [comment]
用错了呢，用了demo的playActivity没有调hideKey&showKey😄😄
