### ISSUE TITLE
播放视频画面声音不一致导致当前时间显示溢出

### ISSUE THREAD

**Issue by tangjiarao** [CarGuo/GSYVideoPlayer#429]
不知道是网络原因还是什么，播放视频的时候会画面比声音慢，声音的播放完了，画面还在继续，导致当前的时间即使大于视频总长度，依然会逐秒增加。

**Comment by CarGuo** [comment]
模拟器还是真机？视频分辨率是？demo中出现吗？试试问题集锦中的降低帧率

**Comment by tangjiarao** [comment]
真机红米   分辨率1920x1080   demo也出现，并不是播放demo中的网址。DetailPlayer测试的。

**Comment by tangjiarao** [comment]
http://v1qn.hnjk.net/e9_256.mp4 视频

**Comment by CarGuo** [comment]
试过设置掉帧播放吗？参考问题集锦中
