### ISSUE TITLE
加载m3u8网络视频地址时进度条滚动偶尔失灵，视频播放不受影响

### ISSUE THREAD

**Issue by tokiii** [CarGuo/GSYVideoPlayer#43]
增加一点：加载网络视频速度慢，同等网络情况下和苹果作对比

**Comment by CarGuo** [comment]
如果是感觉加载慢的，请关闭缓存，设置缓存为false试试，然后进度条失灵未能重现，如果是拖动后失效，这有可能和视频那个时间戳的关键帧有关系，或者是操作问题导致。
