### ISSUE TITLE
视频详情 播放一半或者播放结束  按返回键，然后重新打开另一个视频，有时候播放一会会自动暂停，点击播放按钮又重头开始播放

### ISSUE THREAD

**Issue by 18710891669** [CarGuo/GSYVideoPlayer#430]
分析原因：  是按下返回键时，详情页activity还销毁  没执行onDestroy()方法，  然后返回到主界面再次打开另一个视频播放时，详情页activity又执行了onDestroy(),  所以会出现上述现象   有没有更友好的方法解决

**Comment by CarGuo** [comment]
你可以log上看看，自动理论上是不存在的

**Comment by CarGuo** [comment]
DetailControlActivity 你可以试试
