### ISSUE TITLE
关于封面图顶部阴影

### ISSUE THREAD

**Issue by johnzhang2016** [CarGuo/GSYVideoPlayer#433]
尊敬的作者你好，对视频设置了封面图后，顶部有一段过度的阴影。
这部分的阴影可以改变的吗？做成无阴影效果，或者是全局的阴影效果可以的吗？
谢谢~

**Comment by CarGuo** [comment]
不是很理解，有截图不？

**Comment by ygeng** [comment]
设置封面图以后顶部有这个阴影
![image](https://user-images.githubusercontent.com/13791355/40220168-c66c4eee-5aaa-11e8-8374-d4938260f195.png)

**Comment by ygeng** [comment]
这个好像是显示标题和返回按钮的那个布局

**Comment by CarGuo** [comment]
video_title_bg.xml的问题导致的，布局中top的layout background 是 
        android:background="@drawable/video_title_bg"

所以你可以在你的项目drawable里重写一个video_title_bg.xml覆盖就好了
