### ISSUE TITLE
进入视频详情调用  detailPlayer.startPlayLogic();视频自动播放，再次跳进视频详情界面，同时之前的视频详情finish，视频不会自动播放，除非点一下播放按钮才可以播放，是因为上一个activity，我没有停止播放，所以再次进入，不会自动播放吗

### ISSUE THREAD

**Issue by riseLishan** [CarGuo/GSYVideoPlayer#436]
进入视频详情调用  detailPlayer.startPlayLogic();视频自动播放，再次跳进视频详情界面，同时之前的视频详情finish，视频不会自动播放，除非点一下播放按钮才可以播放，是因为上一个activity，我没有停止播放，所以再次进入，不会自动播放吗

**Comment by CarGuo** [comment]
你需要释放了之前的。才能播放新的。
