### ISSUE TITLE
三星S8（分辨率：2560*1440） 全屏模式播放（videoType是全屏裁剪显示）情况下，视频显示不全，不适配

### ISSUE THREAD

**Issue by 18710891669** [CarGuo/GSYVideoPlayer#437]

**Comment by CarGuo** [comment]
裁剪肯定不全啊·····

**Comment by 18710891669** [comment]
GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);
但是videoType不设置全屏裁剪模式的话   播放器上下有黑边

**Comment by CarGuo** [comment]
所以你需要的是？？？

**Comment by 18710891669** [comment]
去掉上下黑边情况下  能不能适配屏幕  2560*1440遮挡了字幕

**Comment by CarGuo** [comment]
你的视频分辨率不是这个比例的，要如何做到又没有黑边有不裁剪？？？那就是视频拉伸变形填满了而已。视频源的比例和手机比例不一致，要么黑边，要么裁剪，要么拉伸

**Comment by 18710891669** [comment]
明白了  3q
