### ISSUE TITLE
我用了你编译的so文件，为什么不支持https

### ISSUE THREAD

**Issue by ywqyunshan** [CarGuo/GSYVideoPlayer#44]
我用了你编译的so文件，为什么不支持https

**Comment by CarGuo** [comment]
你是说demo不支持，还是把so拷贝到你工程不支持？？？有对应log吗？这个so是基于ijk 0.7.6的，对应的java等版本也要升级到76喔

**Comment by ywqyunshan** [comment]
谢谢，已经解决，是替换了我原来的so文件，项目clean 后，重新build没问题了
