### ISSUE TITLE
好像更改不了全屏按钮的图片？

### ISSUE THREAD

**Issue by tangjiarao** [CarGuo/GSYVideoPlayer#440]
是我调用的时机不对吗，看了代码是要在setUp之前调用。
我在LandLayoutVideo 的初始化调用无法更改。
public LandLayoutVideo(Context context, Boolean fullFlag) {
        super(context, fullFlag);
        initviews();
    }

    public LandLayoutVideo(Context context) {
        super(context);
        initviews();
    }

    public LandLayoutVideo(Context context, AttributeSet attrs) {
        super(context, attrs);
        initviews();
    }
    private void initviews() {
        mADTextView =(TextView)findViewById(R.id.ad_tv);
        mErrorTextView =(TextView)findViewById(R.id.error_tv);
        mADImageView =(ImageView)findViewById(R.id.ad_iv);
        setShrinkImageRes(R.drawable.video_shrink);
        setEnlargeImageRes(R.drawable.video_enlarge);
        Log.d("XX",this+" 初始化");
    }

在activity 调用也是无法更改
detailPlayer.setShrinkImageRes(R.drawable.video_shrink);
detailPlayer.setEnlargeImageRes(R.drawable.video_enlarge);

**Comment by CarGuo** [comment]
参考下DanmkuVideoActivity

**Comment by tangjiarao** [comment]
图片不能同名好像。
