### ISSUE TITLE
Attempt to invoke interface method 'void com.shuyu.gsyvideoplayer.listener.GSYMediaPlayerListener.onAutoCompletion()' on a null object reference

### ISSUE THREAD

**Issue by stayinxing** [CarGuo/GSYVideoPlayer#441]
Attempt to invoke interface method 'void com.shuyu.gsyvideoplayer.listener.GSYMediaPlayerListener.onAutoCompletion()' on a null object reference

崩溃

**Comment by CarGuo** [comment]
请在demo中复现
