### ISSUE TITLE
关于播放器圆角设置问题

### ISSUE THREAD

**Issue by mackkill** [CarGuo/GSYVideoPlayer#444]
如题，项目有需求需要设置成圆角的样式，当我把封面图、根视图都设置成圆角后；发现播放的时候又回到了直角？在网上也没找到对应的设置方法。希望楼主能解答下，感谢~~

**Comment by CarGuo** [comment]
你说的是整个播放器圆角？？

**Comment by mackkill** [comment]
嗯。。。

**Comment by CarGuo** [comment]
这个使用自己的自定义布局实现，全屏和非全屏两个布局。

**Comment by mackkill** [comment]
这个我就是自定义的，但是设置完后，点击播放时还是变成了直角，也就是只有背景和封面能设置成圆角，播放器没法设。。？

**Comment by mackkill** [comment]
嗯，现在主要的问题是播放的时候 圆角设置无效，就相当于要给播放器设置一个圆角，不知道这个可不可以？

**Comment by CarGuo** [comment]
其实主要还是渲染层TextureView没圆角

**Comment by mackkill** [comment]
嗯，多谢楼主指点。已经解决了，这里附上方法（有不好的地方希望提点意见）：
1、GSYRenderView类中暴露 获取 mShowView的方法；
2、GSYVideoView 类中 onVideoSizeChanged方法里面 定义一个抽象方法供外部继承。
3、最后在外部继承的类里面调用楼下的方法：

**Comment by mackkill** [comment]
public class TextureVideoViewOutlineProvider extends ViewOutlineProvider {
    private float mRadius;
 
    public TextureVideoViewOutlineProvider(float radius) {
        this.mRadius = radius;
    }
 
    @Override
    public void getOutline(View view, Outline outline) {
        Rect rect = new Rect();
        view.getGlobalVisibleRect(rect);
        int leftMargin = 0;
        int topMargin = 0;
        Rect selfRect = new Rect(leftMargin, topMargin,
                rect.right - rect.left - leftMargin, rect.bottom - rect.top - topMargin);
        outline.setRoundRect(selfRect, mRadius);
    }
}

调用：
mVideoView.setOutlineProvider(new TextureVideoViewOutlineProvider(radius));
mVideoView.setClipToOutline(true);

**Comment by adminqqz** [comment]
需要源码集成吗？我硬是没成功

**Comment by g19980115** [comment]
@AdminQQZ  我直接在`SampleControlVideo`里面加的这个代码，可以了，上面那个`TextureVideoViewOutlineProvider`类也要改一下
```Java
 @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);
        if (!mIfCurrentIsFullscreen) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                this.setOutlineProvider(new TextureVideoViewOutlineProvider(UIUtil.dip2px(getActivityContext(), 8)));
                this.setClipToOutline(true);
            }
        }
    }
```

```Java
public class TextureVideoViewOutlineProvider extends ViewOutlineProvider {
    private float mRadius;

    public TextureVideoViewOutlineProvider(float radius) {
        this.mRadius = radius;
    }

    @Override
    public void getOutline(View view, Outline outline) {
        Rect selfRect = new Rect(0, 0,
                view.getMeasuredWidth(), view.getMeasuredHeight());
        outline.setRoundRect(selfRect, mRadius);
    }
}
```

**Comment by SuperKung** [comment]
最简单的方法是直接套个cardView，也可以实现

**Comment by ichtj** [comment]
@SuperKung good

**Comment by Arisono** [comment]
@亲测有效。直接套一个CardView.   感谢@SuperKung 提供的思路
<androidx.cardview.widget.CardView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:cardCornerRadius="@dimen/dip_8"
            app:cardElevation="0dp"
            app:cardUseCompatPadding="false">
            <*****************************************.VideoPlayer
                android:id="@+id/videoplayer"
                android:visibility="gone"
                android:background="@drawable/shape_mine_item_bg1"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:controller_layout_id="@layout/video_player_control_view"
                app:resize_mode="fill" />
        </androidx.cardview.widget.CardView>
