### ISSUE TITLE
关于清晰度文本显示细节问题

### ISSUE THREAD

**Issue by jarylan** [CarGuo/GSYVideoPlayer#445]
您好，我发现 demo 里有个细节问题； 如果您有空的话可以查阅一下；  
细节 1 ： 清晰度文字默认显示为“标准”，并未从传入资源里获取；
细节 2 ： 非全屏选择清晰度后，旋转为全屏还是显示的“标准” ； 全屏旋转为非全屏也是如此；
只是文本显示问题，视频资源播放等其他逻辑是正确的。

**Comment by CarGuo** [comment]
thx，新demo已经更新

**Comment by wsyzj92** [comment]
我下载最新版的demo还是有这个问题
