### ISSUE TITLE
GSYVideoPlayer 2.0.6    调用清理的方法 内存不被释放  

### ISSUE THREAD

**Issue by wukuiqing49** [CarGuo/GSYVideoPlayer#448]
一个全屏的播放页面  是用recycleview做的    列表播放   调用返回按钮销毁这个列表的activity   然后 播放的资源.release();  各种 但是 资源不销毁.

**Comment by CarGuo** [comment]
demo中？

**Comment by wukuiqing49** [comment]
搬得demo的代码   把 url  切换成了   本地视频地址

**Comment by LangQiang** [comment]
同问 列表中每播放一个视频 java层内存稳定增长4到5M  但是同一个视频在列表中播放 就不会增长, 是不是这个增长的内存是视频的缓存呢  怎么释放呢 @CarGuo
