### ISSUE TITLE
播放器偶然出现IllegalStateException异常

### ISSUE THREAD

**Issue by zhangfeisysu** [CarGuo/GSYVideoPlayer#45]
at tv.danmaku.ijk.media.player.IjkMediaPlayer._pause(Native Method)
W/System.err( 3111):    at tv.danmaku.ijk.media.player.IjkMediaPlayer.pause(IjkMediaPlayer.java:514)
W/System.err( 3111):    at com.shuyu.gsyvideoplayer.GSYVideoPlayer.onVideoPause(GSYVideoPlayer.java:432)

**Comment by CarGuo** [comment]
看不出什么问题。可能是操作的时候，播放器被释放或者没初始化的时候调用了暂停。
