### ISSUE TITLE
播放本地视频网络状态

### ISSUE THREAD

**Issue by Sunyee** [CarGuo/GSYVideoPlayer#450]
播放本地视频，如果不是wifi状态下也会提示使用数据，是否继续播放。这个在哪里可以开启或关闭播放时的网络监听。

**Comment by CarGuo** [comment]
哪个版本的

**Comment by Sunyee** [comment]
2.0.6

**Comment by CarGuo** [comment]
demo中试试，demo我发现，你传的本地视频路径是？

**Comment by Sunyee** [comment]
一个本地视频路径，不是uri，是字符串
  /storage/emulated/0/xxxx/xxx/xxxx.mp4
这种

**Comment by CarGuo** [comment]
因为目前本地是通过file开头判断的
