### ISSUE TITLE
关于MP4格式视频点击seekbar或者滑动屏幕快进的问题

### ISSUE THREAD

**Issue by BeforeFuture** [CarGuo/GSYVideoPlayer#451]
我播放的是MP4格式的，正常自动播放没问题。
但是点击seekbar或者滑动屏幕快进，会出现屏幕一直处于那个缓冲小图标，等了很长时间也没有继续播放，请问有对应解决办法吗？

**Comment by CarGuo** [comment]
哪个版本？可以提供url试试吗

**Comment by CarGuo** [comment]
试试问题集锦中的精准seekto

**Comment by BeforeFuture** [comment]
url是内网的。。。。。

**Comment by BeforeFuture** [comment]
你说的是这两个吗？
15、m3u8拖动seek之后，加载很长时间

https://github.com/Bilibili/ijkplayer/issues/2874

https://github.com/CarGuo/GSYVideoPlayer/issues/252

**Comment by CarGuo** [comment]
不是。首页的问题集锦那个进去的

**Comment by BeforeFuture** [comment]
看了问题集锦中的内容，不是太明白需要具体在哪些地方加入什么内容。。。

**Comment by CarGuo** [comment]
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
