### ISSUE TITLE
大神,关于自定义效果

### ISSUE THREAD

**Issue by Leekalun** [CarGuo/GSYVideoPlayer#454]
![image](https://user-images.githubusercontent.com/23419925/30414552-c4ba14c0-9956-11e7-886b-a7c8c310301a.png)

大神， 我想做一个无网状态的显示，播放到一半 断网了显示如， 正常窗口 已经解决了，但是全屏的不知道怎么做，求指教。要将显示的逻辑放到哪个方法呢

**Comment by CarGuo** [comment]
全屏的时候是切换了播放控件，你可以参考demo中入sampleVideo等类里，将自定义参数也同步到全屏之类的

**Comment by yuanchenghao** [comment]
怎么加？求助
