### ISSUE TITLE
视频播放到1:40的时候卡顿

### ISSUE THREAD

**Issue by Chenayi** [CarGuo/GSYVideoPlayer#459]
视频播放到1:40的时候会出现卡顿情况，并且可拖动的进度条区域会一直显示，触摸消失马上又显示，触摸消失马上又显示...

**Comment by CarGuo** [comment]
不是很理解

**Comment by cwyrzz** [comment]
http://www.biggar.cn//public//File//member_video//201709//18//59bf9d3220fd8.mp4
视频链接，您试试，进去播放不要动，大概等到1:40左右就会出现情况

**Comment by CarGuo** [comment]
看起来像是视频源的问题

**Comment by cwyrzz** [comment]
这不能说视频源有问题吧，播放器能不能做优化啊，因为ios那边是没事的

**Comment by cwyrzz** [comment]
您好，我们这边后台上传的都是这种视频格式呢，您看能不能对播放器做下优化处理，兼容一下视频源，因为ios那边的播放器是没有这个问题

**Comment by CarGuo** [comment]
你可以把域名缓存ip和端口试试先

**Comment by CarGuo** [comment]
目前看来还是视频源的问题，因为播放器走的是ffmpeg，表现和ios不一样是正常的

**Comment by cwyrzz** [comment]
把域名缓存ip和端口？这具体要怎么弄？

**Comment by cwyrzz** [comment]
您好，您那边也看看一下有没有办法优化处理一下，兼容一下吧，谢谢

**Comment by CarGuo** [comment]
mp4文件的帧序列问题，会导致不停的seek，这个属于ffmpeg层级的问题，你失踪exo模式试试咯，一般mediacodec模式的和ffmpeg模式的是不一样

**Comment by cwyrzz** [comment]
您好，请问下exo模式要怎么开启，具体代码是？

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER);

但是exo目前在该项目里优化比较一般，你可以试试

**Comment by cwyrzz** [comment]
试了下，老是走onPlayError（）回调，还是不怎么好

**Comment by cwyrzz** [comment]
这个问题我只能暂时不处理了，希望作者后面能想到好的方法优化兼容一下，谢谢

**Comment by june5753** [comment]
有遇到类似的情况，同样的视频源 （mp4格式的），手机上可以正常播放无卡顿，在极米盒子上播放一段时间后会出现卡顿和 音视频不同步问题，在线和离线播放都会出现。

**Comment by CarGuo** [comment]
楼上你这个问题，可以试试
 
``` 
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50); List<VideoOptionModel> list = new ArrayList<>(); list.add(videoOptionModel); GSYVideoManager.instance().setOptionModelList(list);

其中具体的掉帧系数可以自行调试
```
