### ISSUE TITLE
一个小问题 

### ISSUE THREAD

**Issue by junchenChow** [CarGuo/GSYVideoPlayer#46]
在recyclerview中的demo 播放完毕之后点击上锁之后会出现一些问题 作者可以看看demo～

**Comment by CarGuo** [comment]
没发现呢，是哪个recyclerView?

**Comment by junchenChow** [comment]
recyclerview2 的问题稍微严重一点  退出全屏还是之前那个奇怪的样子  就是视频真正播放完毕了之后 你再去点击上锁 然后再解锁 这个时候 ui就出问题了 可能是touch事件有地方没判断好 怎么点都是之前上锁的样子

**Comment by junchenChow** [comment]
还有一个小问题 应该是我自己的问题 我继承了StandardGSYVideoPlayer 写了一个重载了一下布局 里面的控件没有删改 没有改源码 其他的都是好的 就是底部的seekbar 拖动不了 打了下断点mHadPlay始终都是false然后就进行不下去了。是不是我调用的姿势不对 求指教。
![gsy1](https://cloud.githubusercontent.com/assets/13553319/22059085/608fe6b2-dda6-11e6-834a-491911eba3bd.png)
![gsy2](https://cloud.githubusercontent.com/assets/13553319/22059107/7928a416-dda6-11e6-852f-a3d5f3bc2469.png)
![gsy3](https://cloud.githubusercontent.com/assets/13553319/22059137/9bf66f78-dda6-11e6-86f3-2ab4c6cd9439.png)

**Comment by CarGuo** [comment]
原来是那个锁定触摸，我理解成那个锁屏幕了，这个我改一下。至于继承后seekbar拖动不了，这个只能说那个seekbar的id是不是一致的，seekbar上面是不是还有东西阻挡了触摸，或者你重新增加了什么逻辑，这个我还真不好说，现在是在seekbar拖动后的回调的stopdrag里面做逻辑的。

**Comment by junchenChow** [comment]
seekbar的相关的都没有改  id我改了肯定就报错了 我就是在stopDrag里面打的断点发现mHadPlay一直都是false 逻辑也没有改 就是单纯的继承了重载了一下布局。

**Comment by CarGuo** [comment]
mHadPlay在初始化和release的时候是false，在onPrepared的时候是true，全屏的时候会把这个状态也附值给全屏播放器。
