### ISSUE TITLE
楼主，出现一个问题，需要帮忙一下'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)

### ISSUE THREAD

**Issue by qq781548819** [CarGuo/GSYVideoPlayer#460]
'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)

**Comment by CarGuo** [comment]
现象是？

**Comment by qq781548819** [comment]
rtsp流的格式无法播放，后台给的测试流协议是rtsp://admin:Admin12345@linktime3.zapto.org:8052/cam/realmonitor?channel=1&subtype=1

求作者指点下，或帮忙，谢谢，由衷感激

现象是：黑屏，无声音，一直显示加载进度条

log是：

09-19 22:42:53.614 24748-24748/com.smart.smarthub I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170811--001
09-19 22:42:53.614 24748-24748/com.smart.smarthub I/IJKMEDIA: ijk_version_info: k0.8.1-42-g0b5ddef
09-19 22:42:53.619 24748-24748/com.smart.smarthub I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170811--001
09-19 22:42:53.619 24748-24748/com.smart.smarthub I/IJKMEDIA: ijk_version_info: k0.8.1-42-g0b5ddef
09-19 22:42:53.621 24748-25120/com.smart.smarthub I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170811--001
09-19 22:42:53.621 24748-25120/com.smart.smarthub I/IJKMEDIA: ijk_version_info: k0.8.1-42-g0b5ddef
09-19 22:42:53.622 24748-25120/com.smart.smarthub W/IJKMEDIA: remove 'timeout' option for rtmp.
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: ===== versions =====
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: ijkplayer    : k0.8.1-42-g0b5ddef
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170811--001
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: libavutil    : 55.58.100
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: libavcodec   : 57.89.100
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: libavformat  : 57.71.100
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: libswscale   : 4.6.100
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: libswresample: 2.7.100
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: ===== options =====
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: format-opts : ijkapplication               = -863534880
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: format-opts : ijkiomanager                 = -893205992
09-19 22:42:53.622 24748-25120/com.smart.smarthub I/IJKMEDIA: ===================
09-19 22:42:53.623 24748-25126/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25126] ff_msg_loop
09-19 22:42:53.623 24748-25128/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25128] ff_read
09-19 22:42:53.623 24748-25128/com.smart.smarthub W/IJKMEDIA: remove 'timeout' option for rtmp.
09-19 22:42:53.625 24748-25127/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25127] ff_vout
09-19 22:42:53.625 24748-25114/com.smart.smarthub I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170811--001
09-19 22:42:53.625 24748-25114/com.smart.smarthub I/IJKMEDIA: ijk_version_info: k0.8.1-42-g0b5ddef
09-19 22:42:53.626 24748-25114/com.smart.smarthub W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
09-19 22:42:53.626 24748-25114/com.smart.smarthub W/IJKMEDIA: remove 'timeout' option for rtmp.
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: ===== versions =====
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: ijkplayer    : k0.8.1-42-g0b5ddef
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170811--001
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: libavutil    : 55.58.100
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: libavcodec   : 57.89.100
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: libavformat  : 57.71.100
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: libswscale   : 4.6.100
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: libswresample: 2.7.100
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: ===== options =====
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: player-opts : loop                         = 1
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: format-opts : ijkapplication               = -499742848
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: format-opts : ijkiomanager                 = -850470736
09-19 22:42:53.626 24748-25114/com.smart.smarthub I/IJKMEDIA: ===================
09-19 22:42:53.627 24748-25138/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25138] ff_read
09-19 22:42:53.627 24748-25138/com.smart.smarthub W/IJKMEDIA: remove 'timeout' option for rtmp.
09-19 22:42:53.627 24748-25136/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25136] ff_msg_loop
09-19 22:42:53.628 24748-25137/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25137] ff_vout
09-19 22:42:53.643 24748-25114/com.smart.smarthub W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
09-19 22:42:53.982 24748-25138/com.smart.smarthub I/IJKMEDIA: Add dns cache hostname = 184.72.239.149, ip = 
09-19 22:42:54.122 24748-25128/com.smart.smarthub I/IJKMEDIA: Add dns cache hostname = 184.72.239.149, ip = 
09-19 22:42:54.610 24748-25138/com.smart.smarthub W/IJKMEDIA: 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
09-19 22:42:54.613 24748-25138/com.smart.smarthub W/IJKMEDIA: 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
09-19 22:42:55.653 24748-25138/com.smart.smarthub W/IJKMEDIA: 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
09-19 22:42:55.658 24748-25138/com.smart.smarthub W/IJKMEDIA: 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
09-19 22:42:56.123 24748-25128/com.smart.smarthub W/IJKMEDIA: 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
09-19 22:42:56.124 24748-25128/com.smart.smarthub W/IJKMEDIA: 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
09-19 22:42:56.322 24748-25138/com.smart.smarthub E/IJKMEDIA: Option ijkapplication not found.
09-19 22:43:00.855 24748-25128/com.smart.smarthub W/IJKMEDIA: 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
09-19 22:43:00.859 24748-25128/com.smart.smarthub W/IJKMEDIA: 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
09-19 22:43:02.082 24748-25128/com.smart.smarthub E/IJKMEDIA: Option ijkapplication not found.
09-19 22:43:06.376 24748-25138/com.smart.smarthub W/IJKMEDIA: UDP timeout, retrying with TCP
09-19 22:43:11.919 24748-25138/com.smart.smarthub I/IJKMEDIA: max_frame_duration: 10.000
09-19 22:43:11.919 24748-25138/com.smart.smarthub I/IJKMEDIA: Input #0, rtsp, from 'rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov':
09-19 22:43:11.920 24748-25138/com.smart.smarthub I/IJKMEDIA:   Metadata:
09-19 22:43:11.920 24748-25138/com.smart.smarthub I/IJKMEDIA:     title           : 
09-19 22:43:11.920 24748-25138/com.smart.smarthub I/IJKMEDIA: BigBuckBunny_175k.mov
09-19 22:43:11.920 24748-25138/com.smart.smarthub I/IJKMEDIA:   Duration: 
09-19 22:43:11.923 24748-25138/com.smart.smarthub I/IJKMEDIA: 00:09:56.46
09-19 22:43:11.923 24748-25138/com.smart.smarthub I/IJKMEDIA: , start: 
09-19 22:43:11.923 24748-25138/com.smart.smarthub I/IJKMEDIA: 0.000000
09-19 22:43:11.923 24748-25138/com.smart.smarthub I/IJKMEDIA: , bitrate: 
09-19 22:43:11.923 24748-25138/com.smart.smarthub I/IJKMEDIA: N/A
09-19 22:43:11.924 24748-25138/com.smart.smarthub I/IJKMEDIA:     Stream #0:0
09-19 22:43:11.924 24748-25138/com.smart.smarthub I/IJKMEDIA: : Audio: aac, 48000 Hz, stereo, fltp
09-19 22:43:11.924 24748-25138/com.smart.smarthub I/IJKMEDIA:     Stream #0:1
09-19 22:43:11.924 24748-25138/com.smart.smarthub I/IJKMEDIA: : Video: h264, yuv420p(progressive), 240x160
09-19 22:43:11.924 24748-25138/com.smart.smarthub I/IJKMEDIA: , 
09-19 22:43:11.924 24748-25138/com.smart.smarthub I/IJKMEDIA: 24 fps, 
09-19 22:43:11.924 24748-25138/com.smart.smarthub I/IJKMEDIA: 24 tbr, 
09-19 22:43:11.924 24748-25138/com.smart.smarthub I/IJKMEDIA: 90k tbn, 
09-19 22:43:11.924 24748-25138/com.smart.smarthub I/IJKMEDIA: 48 tbc
09-19 22:43:11.926 24748-25138/com.smart.smarthub I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
09-19 22:43:11.926 24748-25138/com.smart.smarthub I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
09-19 22:43:11.955 24748-25138/com.smart.smarthub I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
09-19 22:43:11.956 24748-25138/com.smart.smarthub I/IJKMEDIA: audio_session_id = 11665
09-19 22:43:11.956 24748-25138/com.smart.smarthub I/IJKMEDIA: AudioCodec: avcodec, aac
09-19 22:43:11.956 24748-25161/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25161] ff_aout_android
09-19 22:43:11.956 24748-25162/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25162] ff_audio_dec
09-19 22:43:11.960 24748-25138/com.smart.smarthub I/IJKMEDIA: VideoCodec: avcodec, h264
09-19 22:43:11.963 24748-25138/com.smart.smarthub W/IJKMEDIA: fps: 24.000000 (normal)
09-19 22:43:11.964 24748-25138/com.smart.smarthub W/IJKMEDIA: fps: 24.000000 (normal)
09-19 22:43:11.966 24748-25172/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25172] ff_video_dec
09-19 22:43:11.995 24748-25114/com.smart.smarthub I/tv.danmaku.ijk.media.player.IjkMediaPlayer: Info: MEDIA_INFO_VIDEO_RENDERING_START
09-19 22:43:12.141 24748-25128/com.smart.smarthub W/IJKMEDIA: UDP timeout, retrying with TCP
09-19 22:43:12.318 24748-24755/com.smart.smarthub I/art: Do partial code cache collection, code=50KB, data=62KB
09-19 22:43:12.319 24748-24755/com.smart.smarthub I/art: After code cache collection, code=50KB, data=62KB
09-19 22:43:12.319 24748-24755/com.smart.smarthub I/art: Increasing code cache capacity to 256KB
09-19 22:43:12.826 24748-25137/com.smart.smarthub W/IJKMEDIA: func_display_overlay_l: NULL native_window
09-19 22:43:12.942 24748-25126/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25126]
09-19 22:43:12.942 24748-25136/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25136]
09-19 22:43:12.947 24748-25127/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25127]
09-19 22:43:12.950 24748-25137/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25137]
09-19 22:43:12.967 24748-25128/com.smart.smarthub W/IJKMEDIA: Could not find codec parameters for stream 1 (Video: h264, none, 240x160): unspecified pixel format
                                                              Consider increasing the value for the 'analyzeduration' and 'probesize' options
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: max_frame_duration: 10.000
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: Input #0, rtsp, from 'rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov':
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA:   Metadata:
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA:     title           : 
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: BigBuckBunny_175k.mov
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA:   Duration: 
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: 00:09:56.46
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: , start: 
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: 0.000000
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: , bitrate: 
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: N/A
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA:     Stream #0:0
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: : Audio: aac, 48000 Hz, stereo, fltp
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA:     Stream #0:1
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: : Video: h264, none, 240x160
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: , 
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: 90k tbr, 
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: 90k tbn, 
09-19 22:43:12.967 24748-25128/com.smart.smarthub I/IJKMEDIA: 180k tbc
09-19 22:43:12.968 24748-25128/com.smart.smarthub I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
09-19 22:43:12.968 24748-25128/com.smart.smarthub I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
09-19 22:43:12.975 24748-25128/com.smart.smarthub I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
09-19 22:43:12.975 24748-25128/com.smart.smarthub I/IJKMEDIA: audio_session_id = 11673
09-19 22:43:12.975 24748-25128/com.smart.smarthub I/IJKMEDIA: AudioCodec: avcodec, aac
09-19 22:43:12.975 24748-25185/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25185] ff_audio_dec
09-19 22:43:12.976 24748-25184/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25184] ff_aout_android
09-19 22:43:12.978 24748-25128/com.smart.smarthub I/IJKMEDIA: VideoCodec: avcodec, h264
09-19 22:43:12.978 24748-25128/com.smart.smarthub W/IJKMEDIA: fps: 90000.000000 (normal)
09-19 22:43:12.978 24748-25128/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25128]
09-19 22:43:12.978 24748-25195/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25195] ff_video_dec
09-19 22:43:12.978 24748-25185/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25185]
09-19 22:43:12.979 24748-25184/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25184]
09-19 22:43:12.979 24748-25195/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25195]
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170811--001
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: ijk_version_info: k0.8.1-42-g0b5ddef
09-19 22:43:12.982 24748-25120/com.smart.smarthub W/IJKMEDIA: remove 'timeout' option for rtmp.
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: ===== versions =====
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: ijkplayer    : k0.8.1-42-g0b5ddef
09-19 22:43:12.982 24748-25201/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25201] ff_msg_loop
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170811--001
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: libavutil    : 55.58.100
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: libavcodec   : 57.89.100
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: libavformat  : 57.71.100
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: libswscale   : 4.6.100
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: libswresample: 2.7.100
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: ===== options =====
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: format-opts : ijkapplication               = -863534880
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: format-opts : ijkiomanager                 = -893205944
09-19 22:43:12.982 24748-25120/com.smart.smarthub I/IJKMEDIA: ===================
09-19 22:43:12.982 24748-25202/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25202] ff_vout
09-19 22:43:12.983 24748-25203/com.smart.smarthub I/IJKMEDIA: SDL_RunThread: [25203] ff_read
09-19 22:43:12.983 24748-25203/com.smart.smarthub W/IJKMEDIA: remove 'timeout' option for rtmp.
09-19 22:43:12.983 24748-25203/com.smart.smarthub I/IJKMEDIA: Hit DNS cache hostname = 184.72.239.149
09-19 22:43:12.984 24748-25138/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25138]
09-19 22:43:12.984 24748-25162/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25162]
09-19 22:43:12.989 24748-25161/com.smart.smarthub I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [25161]

**Comment by CarGuo** [comment]
播放前加入这段代码试试
```
       VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);

```

**Comment by qq781548819** [comment]
i love you ,作者老大！！ @CarGuo
