### ISSUE TITLE
播过开头会卡一次

### ISSUE THREAD

**Issue by jiutianxuanyao** [CarGuo/GSYVideoPlayer#462]
问题描述：
1、监控直播流hls，ts
2、有人看，请求后，后台才开始转码，没有人看时，停止3分钟，后台停止转码，会保存三个片段9秒
3、再次观看时，先播放保存的9秒，然后播放实时码流，实时码流播放9秒后会卡一次，目前不知道是什么原因造成的，求指教，谢谢。

**Comment by CarGuo** [comment]
这个我也爱莫能助。。。

**Comment by jiutianxuanyao** [comment]
好的，谢谢。
