### ISSUE TITLE
EmptyControlVideo暂停报错

### ISSUE THREAD

**Issue by TigerYh** [CarGuo/GSYVideoPlayer#463]
EmptyControlVideo 无UI播放器   添加暂停恢复代码
`    @Override
    protected void onPause() {
        super.onPause();
        videoPlayer.onVideoPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        videoPlayer.onVideoResume();
    }`

使用时会报错 
`java.lang.IllegalArgumentException: width and height must be > 0
 android.graphics.Bitmap.createBitmap(Bitmap.java:815)
 android.graphics.Bitmap.createBitmap(Bitmap.java:794)
 android.graphics.Bitmap.createBitmap(Bitmap.java:761)
 com.shuyu.gsyvideoplayer.GSYRenderView.initCover(GSYRenderView.java:67)
 com.shuyu.gsyvideoplayer.video.base.GSYTextureRenderView.initCover(GSYTextureRenderView.java:168)
 com.shuyu.gsyvideoplayer.video.base.GSYVideoView.updatePauseCover(GSYVideoView.java:212)
 com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.changeUiToPauseShow(StandardGSYVideoPlayer.java:467)
 com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.resolveUIState(GSYVideoControlView.java:748)
 com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setStateAndUi(GSYVideoControlView.java:346)
 com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onVideoPause(GSYVideoView.java:413)
 com.juzhi.dvrapp.activity.DevicePlayActivity.onPause(DevicePlayActivity.java:50)
 android.app.Activity.performPause(Activity.java:6082)
 android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1305)
 android.app.ActivityThread.performPauseActivity(ActivityThread.java:3403)
 android.app.ActivityThread.performPauseActivity(ActivityThread.java:3376)
 android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3351)
 android.app.ActivityThread.access$1000(ActivityThread.java:167)
 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
 android.os.Handler.dispatchMessage(Handler.java:111)
 android.os.Looper.loop(Looper.java:194)
 android.app.ActivityThread.main(ActivityThread.java:5536)
 java.lang.reflect.Method.invoke(Native Method)
 java.lang.reflect.Method.invoke(Method.java:372)
 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)`

**Comment by CarGuo** [comment]
视频的宽高等于0？

**Comment by CarGuo** [comment]
如果不是视频，设置setShowPauseCover为false

**Comment by TigerYh** [comment]
是视频 播放时 点击home键  进入后台  会报这个错
