### ISSUE TITLE
请问一下为什么播放时长大于总时长？

### ISSUE THREAD

**Issue by wushangjun** [CarGuo/GSYVideoPlayer#465]
比如说：视频的总时长显示10:00，但是播放时候播到了10:50秒左右

**Comment by CarGuo** [comment]
一般是视频的文件信息问题，有流url吗

**Comment by wushangjun** [comment]
现在是播放本地的mp4视频的。在其他播放器能正常播放

**Comment by CarGuo** [comment]
ffmpeg的播放和mediacodec的播放模式有点不一样，最好可以提供流测试下

**Comment by wushangjun** [comment]
刚刚用demo试了一下。播放本地视频就会出现这种情况的，把本地视频上传到了服务器用url播放就没有问题。http://cdn01.gddc.net.cn//uploads//20170920//a10097d7a6b102073aabd0a8b6648b08.mp4

**Comment by CarGuo** [comment]
我刚刚在手机上下载了这个视频，然后用demo本地播放，没出息这个问题。
