### ISSUE TITLE
第一次播放报错，然后再点击播放按钮就正常

### ISSUE THREAD

**Issue by HuangJAndroid** [CarGuo/GSYVideoPlayer#467]
HttpUrlSource: Error fetching info from http://baobab.wdjcdn.com/14564977406580.mp4
                                                                          java.net.SocketException: Connection reset

**Comment by CarGuo** [comment]
demo中哪个页面？没重现

**Comment by HuangJAndroid** [comment]
新创建的项目，复制一下就这错

**Comment by CarGuo** [comment]
没办法在demo中重现，很难定位问题
