### ISSUE TITLE
大佬,貌似2.0.8不支持hls了,我退回到2.0.6就可以了

### ISSUE THREAD

**Issue by heygays** [CarGuo/GSYVideoPlayer#468]
视频链接:https://mp4.512wx.com/20170913/BMjtymlT/index.m3u8?sign=0f5af1fbb9d3b7a28ac1e729480bf521f102f06a4505c47b027315aba9d5e2ce40dc5074c12083d5ffbc914eee75a743

**Comment by CarGuo** [comment]
2.0.8可以播，hls的，我刚刚试了，在demo的detailPlayer页面试了你的链接， 你要关了cacheWithPlay为false哟。
