### ISSUE TITLE
多个不同界面存在播放器，又能相互跳转

### ISSUE THREAD

**Issue by WalkingRoy** [CarGuo/GSYVideoPlayer#469]
因为不能有多个视频实例，我现在就遇到两种页面间的跳转：

1.简单的，像这样：A -> B -> A
2.复杂的：A -> B -> C -> D -> C -> B -> A
A，D 为视频播放页面，B，C 为普通页面，为了回到 A 后能再重新播放到暂停时的位置，需要增加需要额外的变量来维护，虽说实现不难，但仅仅一直靠变量来维护，代码可阅读性感觉最后会变差。

3.两个视频播放界面，也可能是不同类型的播放器，EXO 与 IKJ Player 两种。

4.当然限制一个播放器实例能更好的维护系统资源，这也算是取舍。

**Comment by CarGuo** [comment]
只能说😂深表同情
