### ISSUE TITLE
土豆解析出来的m3u8地址播放不了。。。

### ISSUE THREAD

**Issue by tokiii** [CarGuo/GSYVideoPlayer#47]
视频地址：http://vr.tudou.com/v2proxy/v2.m3u8?it=249426936&st=3&pw=
苹果端可以直接播放。。求助大神。
LOG：
01-19 16:25:14.030 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_release
01-19 16:25:14.030 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_setVolume
01-19 16:25:14.031 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_release
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_native_setup
01-19 16:25:14.035 12771-13395/com.rmj.asmr I/IJKMEDIA: av_version_info: ff3.2--ijk0.7.5--20161205--001
01-19 16:25:14.035 12771-13395/com.rmj.asmr I/IJKMEDIA: ijk_version_info: k0.7.5-21-gaffc5fd
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: ffpipeline_create_from_android()
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_set_inject_opaque(0x1008a6)
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_set_inject_opaque()=void
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
01-19 16:25:14.035 12771-13395/com.rmj.asmr V/IJKMEDIA: setDataSource: path http://vr.tudou.com/v2proxy/v2.m3u8?it=249426936&st=3&pw=
01-19 16:25:14.035 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_set_data_source(url="http://vr.tudou.com/v2proxy/v2.m3u8?it=249426936&st=3&pw=")
01-19 16:25:14.036 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_set_data_source(url="http://vr.tudou.com/v2proxy/v2.m3u8?it=249426936&st=3&pw=")=0
01-19 16:25:14.036 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-19 16:25:14.036 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_setLoopCount
01-19 16:25:14.036 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_setVolume
01-19 16:25:14.036 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
01-19 16:25:14.036 12771-13395/com.rmj.asmr D/IJKMEDIA: ffpipeline_set_volume
01-19 16:25:14.036 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
01-19 16:25:14.036 12771-13395/com.rmj.asmr W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
01-19 16:25:14.036 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_prepareAsync
01-19 16:25:14.036 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_prepare_async()
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: ===== versions =====
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: ijkplayer    : k0.7.5-21-gaffc5fd
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: FFmpeg       : ff3.2--ijk0.7.5--20161205--001
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: libavutil    : 55.34.100
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: libavcodec   : 57.64.100
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: libavformat  : 57.56.100
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: libswscale   : 4.2.100
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: libswresample: 2.3.100
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: ===== options =====
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: player-opts : loop                         = 1
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: format-opts : ijkapplication               = 547721374816
01-19 16:25:14.036 12771-13395/com.rmj.asmr I/IJKMEDIA: ===================
01-19 16:25:14.037 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_prepare_async()=0
01-19 16:25:14.037 12771-14191/com.rmj.asmr I/IJKMEDIA: SDL_RunThread: [14191] ff_msg_loop
01-19 16:25:14.037 12771-14191/com.rmj.asmr D/IJKMEDIA: message_loop
01-19 16:25:14.038 12771-14191/com.rmj.asmr D/IJKMEDIA: FFP_MSG_FLUSH:
01-19 16:25:14.038 12771-14192/com.rmj.asmr I/IJKMEDIA: SDL_RunThread: [14192] ff_vout
01-19 16:25:14.038 12771-14193/com.rmj.asmr I/IJKMEDIA: SDL_RunThread: [14193] ff_read
01-19 16:25:14.040 12771-14193/com.rmj.asmr I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
01-19 16:25:14.043 12771-13395/com.rmj.asmr W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
01-19 16:25:14.043 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
01-19 16:25:14.043 12771-14193/com.rmj.asmr I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
01-19 16:25:14.043 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7f82dfdbb8)
01-19 16:25:14.043 12771-13395/com.rmj.asmr D/IJKMEDIA: ffpipeline_set_surface()
01-19 16:25:14.043 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7f82dfdbb8)=void
01-19 16:25:14.061 12771-14193/com.rmj.asmr I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
01-19 16:25:14.074 12771-14193/com.rmj.asmr W/IJKMEDIA: HTTP error 403 Forbidden
01-19 16:25:14.074 12771-14193/com.rmj.asmr I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
01-19 16:25:14.074 12771-14193/com.rmj.asmr E/IJKMEDIA: http://vr.tudou.com/v2proxy/v2.m3u8?it=249426936&st=3&pw=: Server returned 403 Forbidden (access denied)
01-19 16:25:14.074 12771-14193/com.rmj.asmr I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [14193]
01-19 16:25:14.074 12771-14191/com.rmj.asmr D/IJKMEDIA: FFP_MSG_ERROR: 0
01-19 16:25:14.075 12771-13395/com.rmj.asmr E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
01-19 16:25:14.075 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_release
01-19 16:25:14.075 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
01-19 16:25:14.075 12771-13395/com.rmj.asmr D/IJKMEDIA: ffpipeline_set_surface()
01-19 16:25:14.075 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
01-19 16:25:14.075 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_shutdown_l()
01-19 16:25:14.075 12771-14191/com.rmj.asmr D/IJKMEDIA: message_loop exit
01-19 16:25:14.075 12771-14191/com.rmj.asmr I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [14191]
01-19 16:25:14.079 12771-14192/com.rmj.asmr I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [14192]
01-19 16:25:14.079 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_shutdown_l()=void
01-19 16:25:14.079 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_dec_ref(): ref=0
01-19 16:25:14.079 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_shutdown_l()
01-19 16:25:14.079 12771-13395/com.rmj.asmr D/IJKMEDIA: ijkmp_shutdown_l()=void
01-19 16:25:14.079 12771-13395/com.rmj.asmr D/IJKMEDIA: IjkMediaPlayer_setVolume

**Comment by CarGuo** [comment]
m3u8 请关闭边拨边缓存。设置为false。

**Comment by CarGuo** [comment]
首页问题详解第五条

**Comment by tokiii** [comment]
videoPlayer.setUp("http://vr.tudou.com/v2proxy/v2.m3u8?it=249426936&st=3&pw=", false, "测试视频");

**Comment by tokiii** [comment]
我调用的是这个，其他类似优酷的m3u8是可以的

**Comment by CarGuo** [comment]
那估计是这个M3u8对应的视频合适不支持

**Comment by tokiii** [comment]
应该是，已经放弃了

2017-01-19 18:33 GMT+08:00 Shuyu Guo <notifications@github.com>:

**Comment by tokiii** [comment]
谢谢大神解答

2017-01-20 0:16 GMT+08:00 wiki wwi <wheheee@gmail.com>:
