### ISSUE TITLE
摄像头的rtsp无法播放

### ISSUE THREAD

**Issue by cyzgbw** [CarGuo/GSYVideoPlayer#473]
楼主，您好，我们通过运行demo（2.0.4/2.0.8），可以正常播放部分rtsp流，但是有部分摄像头传回的tcp的rtsp流无法播放。
楼主可以提供一个邮箱地址，我们将源发给您帮忙看一下吗？

**Comment by CarGuo** [comment]
359369982@qq.com

**Comment by cyzgbw** [comment]
已经发送到您邮箱了，请查收。

**Comment by CarGuo** [comment]
好的👌🏻我晚上看一下！

**Comment by CarGuo** [comment]
你好，你发的两个链接目前貌似连接不上，不过你可以试试问题集锦中的第十七试试，我昨晚链接上了第二个但是貌似没帧数据

**Comment by cyzgbw** [comment]
感谢楼主，使用第17个方法后可以连接了。
