### ISSUE TITLE
视频播放时显示黑屏，无声音

### ISSUE THREAD

**Issue by WooYu** [CarGuo/GSYVideoPlayer#476]
http://xy2-1251668577.file.myqcloud.com/outfile_mv_1504159734833.mp4

![qq 20170926180011](https://user-images.githubusercontent.com/10032892/30854545-94097aa4-a2e4-11e7-8f6b-2984830dc922.png)

您好！上面那个视频播放时显示黑屏，无声音。现在使用的方式c导入的依赖，我看那种音频格式是支持的。我已经查看过相关issue,查不出什么原因来，能够帮忙看下吗？

**Comment by CarGuo** [comment]
Video: mpeg2video (mp4v / 0x7634706D), none(progressive), 360x360, 368 kb/s

mpeg2格式未做支持，支持合适详见根目录的module-lite-more.sh

**Comment by WooYu** [comment]
http://m.blog.csdn.net/Xiong_IT/article/details/78066995这里有编译好的so文件。
