### ISSUE TITLE
有没有接口，可以屏蔽全屏功能。

### ISSUE THREAD

**Issue by zidanpiaoguo** [CarGuo/GSYVideoPlayer#477]
如果recyclerview 在一个fragment 中，就会出现bug, 因为我是两层fragment 嵌套，recyclerview 在最里面的fragment ,全屏就只是放大最内部的Fragment 大小

**Comment by CarGuo** [comment]
这里的全屏使用的是activity的content布局，和在哪个地方没关系，你确定你是用的是normal模式的？

**Comment by zidanpiaoguo** [comment]
就是因为他是在里面的fragment ，我不知道你全屏在哪里使用了他的父类布局，能告诉我一下吗？我现在全屏，只是充满了最里面的那个fragment ,而不是整个界面，还有，如果我在界面上加了一个头部字幕，怎么可以播放时，让他和下面的进度条一起隐藏，暂停，在和进度条一样再出来呢。

**Comment by zidanpiaoguo** [comment]
listVideoUtil.setFullViewContainer(videoFullContainer); 应该是这个方法设置的吧，但是如果是fragment 中videoFullContainer的大小是受fragment 局限了。我试了强制的拿父类的view，返回就会有问题。他会找不到目标，而白屏，卡死。

**Comment by CarGuo** [comment]
用另外一种方式，不用utils的

**Comment by CarGuo** [comment]
嵌套太深的，最好我们普通模式的
