### ISSUE TITLE
布局里面有Toolbar，全屏的时候，状态栏和Toolbar也还是现实，再点一次全屏就真的全屏了！

### ISSUE THREAD

**Issue by lmdiloveu** [CarGuo/GSYVideoPlayer#478]
布局里面有Toolbar，全屏的时候，状态栏和Toolbar也还是现实，再点一次全屏就真的全屏了！怎么解决

**Comment by CarGuo** [comment]
不是很理解，你调用全屏接口的时候，设置了隐藏没？

**Comment by lmdiloveu** [comment]
解决了，布局把toolbar和Player放在同一个Scrollview就可以了！
