### ISSUE TITLE
视频播放完，能否停留在最后一帧？

### ISSUE THREAD

**Issue by liulance** [CarGuo/GSYVideoPlayer#479]
目前视频播放完就黑屏了，能否设置播放完停留在最后一帧？？

**Comment by CarGuo** [comment]
你继承播放器，在播放结束的回调里做处理，比如不要释放播放器之类的

**Comment by liulance** [comment]
@CarGuo 我把GSYVideoView 里面的onAutoCompletion 方法拷贝出来了，把
if (mTextureViewContainer.getChildCount() > 0) {
            mTextureViewContainer.removeAllViews();
        }
这句话注释了，但是没用，请问应该怎么处理，才能停留在最后一帧呢？
谢谢

**Comment by CarGuo** [comment]
一般是继承播放器，然后最简单的就是
@Override
 public void onAutoCompletion() {
  if (mNotReleaseWhenComplete) {  return;  }  super.onAutoCompletion();  }

**Comment by RockyQu** [comment]
@CarGuo 打扰了，@override
public void onAutoCompletion() {
if (mNotReleaseWhenComplete) { return; } super.onAutoCompletion(); }
这种方式播放mp4的能停在最后一帧，但是播放m3u8的视频时就不行了，最后还是会黑屏，请问这如何处理，有什么思路可以讲讲吗？谢谢

**Comment by jarvan11** [comment]
> 一般是继承播放器，然后最简单的就是 @OverRide public void onAutoCompletion() { if (mNotReleaseWhenComplete) { return; } super.onAutoCompletion(); }

@CarGuo 大佬，按照这个方法，是停留在最后的前一秒（比如视频总长度20秒，最后停留在19秒），不是最后一帧，什么原因呢

**Comment by HeQuanLi** [comment]
> > 一般是继承播放器，然后最简单的就是 [@OverRide](https://github.com/OverRide) public void onAutoCompletion() { if (mNotReleaseWhenComplete) { return; } super.onAutoCompletion(); }
> 
> [@CarGuo](https://github.com/CarGuo) 大佬，按照这个方法，是停留在最后的前一秒（比如视频总长度20秒，最后停留在19秒），不是最后一帧，什么原因呢

我也遇到了 你解决了吗？
