### ISSUE TITLE
关于onAutoComplete()回调的问题

### ISSUE THREAD

**Issue by gyxian9** [CarGuo/GSYVideoPlayer#48]
我现在想实现一个videoView播放我一个string数组里面的视频地址的视频
我就在onAutoComplete这个回调里面再
videoView.setUp(urls[index],true,null,"");
然后startPlayLogic

 //播放完了
            @Override
            public void onAutoComplete(String s, Object... objects) {
                Log.d("tag","index:"+index);
                //Log.d("tag","string:"+s);这是缓存地址
                if(index != urls.length -1){
                    index ++;
                }else{
                    index = 0;
                }
                videoView.setUp(urls[index],true,null,"");
                startVideo();
            }
然后LOG发现我的index是有递增，这个s地址
![image](https://cloud.githubusercontent.com/assets/9998810/22179903/32d715ea-e09b-11e6-87a9-a055ed6a17aa.png)
算不算同一个视频？如果不算那为什么我不能在这个方法内继续播放下一个视频？
先谢谢大大！新年快乐

**Comment by CarGuo** [comment]
有一叫ListGSYVideoPlayer的，你可以参考，就是播放一个列表的

**Comment by gyxian9** [comment]
好的谢谢
