### ISSUE TITLE
getCurrentPositionWhenPlaying问题

### ISSUE THREAD

**Issue by ChasingWord** [CarGuo/GSYVideoPlayer#480]
activity退出，在onPause的时候调用videoPlayer.getCurrentPositionWhenPlaying()获取的时间为0，请问在哪里调用才可以？

**Comment by CarGuo** [comment]
这个是当然播放的时间，播放中可以调用

**Comment by CarGuo** [comment]
如果你是继承了那个activity的，就在super之前调用

**Comment by ChasingWord** [comment]
我在你demo的PlayActivity的onPause()的super之前调用的，就是得到0。还有：是退出activity的时候得到0，按了切换应用程序键的话就能得到时间，就不懂为什么了

**Comment by ChasingWord** [comment]
不好意思，知道了，PlayActivity的onBackPressed方法重写了，里面有releaseAllVideos释放资源，所以onPause就得不到时间了
