### ISSUE TITLE
视频缓存问题

### ISSUE THREAD

**Issue by a1227308812** [CarGuo/GSYVideoPlayer#481]
![94v2 hg0ni61n5 pocjt](https://user-images.githubusercontent.com/21053292/30945971-c982f836-a433-11e7-9504-fa2e4facc3b8.png)

![f5e53c22a7e51949d84c4a64d6182df9](https://user-images.githubusercontent.com/21053292/30946004-0db56656-a434-11e7-84f1-443a85f93c87.jpg)

我设置了缓存路径  但是最后却只创建了一个这个名字file文件，但是大小为0，请问这是上什么情况啊

**Comment by a1227308812** [comment]
是整个视频都已经播放完成之后了 ，但是缓存文件大小也还是为零，用HttpProxyCacheServer去缓存就可以，但是我只能设置最后缓存文件的名字，和第一级的文件夹名字  他会自动给我添加两层文件夹，（一层http：的文件夹和一层视频ip地址名称的文件夹），我现在不想要他这两层自动添加的文件夹怎么办啊，播放器自带的设置缓存文件名称的这个功能有没法缓存视频

**Comment by CarGuo** [comment]
参考demo的ListNormalAdapter，里面有注释。
