### ISSUE TITLE
楼主请问下支持ape/flac音频格式么

### ISSUE THREAD

**Issue by liupeng110** [CarGuo/GSYVideoPlayer#482]

**Comment by liupeng110** [comment]
我自己按官网上流程编译了一个  好像不行
不知道是哪里的问题
你的这个
compile 'com.shuyu:gsyVideoPlayer-java:2.0.8' 

compile 'com.shuyu:gsyVideoPlayer-ex_so:2.0.8' 

支持ape/flac么

**Comment by CarGuo** [comment]
我印象中貌似没编译支持这种，你可以看看github首页的muodue-litec-more.sh的文件

**Comment by liupeng110** [comment]
好的，多谢 
我想做个音乐播放器
要是编译个 发布出来 弄个jcenter  那种就方便多了

**Comment by liupeng110** [comment]
我按照这个 这个编译的 
If you prefer less codec/format for smaller binary size (include hevc function)
cd config
rm module.sh
ln -s module-lite-hevc.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg.sh clean

**Comment by liupeng110** [comment]
我又看了一边  好惨，编译错了  
看到个include就用了 真是业务不熟害死人
应该用这个
If you prefer more codec/format
cd config
rm module.sh
ln -s module-default.sh module.sh
cd android/contrib
# cd ios
sh compile-ffmpeg.sh clean

**Comment by CarGuo** [comment]
你可以看我github首页，有编译教程
