### ISSUE TITLE
ActionBar默认不显示的情况，全屏再竖屏就会显示ActionBar

### ISSUE THREAD

**Issue by yueshao6800** [CarGuo/GSYVideoPlayer#485]
项目在BaseActivity就已经吧ActionBar给隐藏了，标题栏是另外加的通用标题栏，全屏再返回竖屏状态，就会用两个标题栏出现，在BaseActivity中已经隐藏的ActionBar就会出现

**Comment by yueshao6800** [comment]
我的解决方法：
   在 startWindowFullscreen(final Context context, final boolean actionBar, final boolean statusBar) 
        this.mActionBarShow = CommonUtil.getActionBarState(context);
保留初始状态系统的ActionBar有没有显示，
在恢复
    protected void resolveNormalVideoShow(View oldF, ViewGroup vp, GSYVideoPlayer gsyVideoPlayer)
里面判断：
if(mActionBarShow) {
            showSupportActionBar(mContext, mActionBar, mStatusBar);
        }else {//默认没有显示ActionBar，恢复时候就不要显示
            showSupportActionBar(mContext, mActionBarShow, mStatusBar);
        }

**Comment by CarGuo** [comment]
主要是，如果你没有actionbar的话，那么全屏接口是不需要设置actionbar那个接口为false

**Comment by yueshao6800** [comment]
全屏的时候确实不需要设置actionbar的，不过全屏再恢复竖屏，默认是会显示actionBar的

**Comment by CarGuo** [comment]
全屏接口这个actionbar这个标志位，是如果你的页面有actionbar就设置为true，如果没有或者已经隐藏了，就设置为false。

**Comment by yueshao6800** [comment]
//第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
detailPlayer.startWindowFullscreen(BaseVideoPlayerActivity.this, true, true);
嗯嗯，这个位置之前理解错了，没有ActionBar直接传false就好了
