### ISSUE TITLE
发现在TV上使用很多都不兼容

### ISSUE THREAD

**Issue by DOVE-PH** [CarGuo/GSYVideoPlayer#486]
目前发现的问题，测试版本4.4：
1、遥控器完全没反应（可能需要自己处理按键事件？）
2、摇控增减音量，视频声音没变化，不会随系统音量（调到最小音量，视频竟是都不会变）
3、视频有明显锯齿感，用其它播放器试没问题（好像有人反映过这问题了？）

**Comment by CarGuo** [comment]
锯齿你可以换别SurfaceView模式试试，tv上的需要自己修改
