### ISSUE TITLE
两指放大图像？可能吗？

### ISSUE THREAD

**Issue by KnIfER** [CarGuo/GSYVideoPlayer#489]
想要像快手那样的放大功能。

**Comment by CarGuo** [comment]
这个不在考虑范围

**Comment by KnIfER** [comment]
在的在的在的

**Comment by askskysun** [comment]
@KnIfER 哥们你实现了么

**Comment by askskysun** [comment]
@CarGuo 要实现这个双指缩放功能，能不能提供一下实现思路

**Comment by CarGuo** [comment]
重载后再touch中拦截，然后对render做scale

**Comment by askskysun** [comment]
我想实现双指缩放，能不能提供接口，设置自定义比例
 /**
     * 显示比例
     * 注意，GSYVideoType.setShowType是全局静态生效，除非重启APP。
     */
    private void resolveTypeUI() {
        if (!mHadPlay) {
            return;
        }
        if (mType == 1) {
            mMoreScale.setText("16:9");
            GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_16_9);
        } else if (mType == 2) {
            mMoreScale.setText("4:3");
            GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_4_3);
        } else if (mType == 3) {
            mMoreScale.setText("全屏");
            GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);
        } else if (mType == 4) {
            mMoreScale.setText("拉伸全屏");
            GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);
        } else if (mType == 0) {
            mMoreScale.setText("默认比例");
            GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_DEFAULT);
        }

        changeTextureViewShowType();
        if (mTextureView != null)
            mTextureView.requestLayout();
        mSwitchSize.setText(mTypeText);
    }
