### ISSUE TITLE
关于自定义

### ISSUE THREAD

**Issue by yuanchenghao** [CarGuo/GSYVideoPlayer#490]
您好大神，我想问一下播放完成后的UI如何自定义，或者具体的思路是什么样的？

**Comment by yuanchenghao** [comment]
还有啊  如何停留在最后一帧 ？

**Comment by CarGuo** [comment]
首先，layoutId你是可以自己返回的，所以可以继承播放器，返回你的id，然后在重载的autocomplete的回调里做你想做的，只需要注意，因为全屏和非全屏是两个UI同步切换，你需要参考源码做一些同步处理。关于最后一帧有多种实现，其中类似这样，继承播放器，然后
@Override
 public void onAutoCompletion() {
  if (mNotReleaseWhenComplete) {  return;  }  super.onAutoCompletion();  }

**Comment by yuanchenghao** [comment]
新手不是太懂  我在onAutoComplete里显示了这个view 半屏可以 全屏的时候没显示出来 怎么同步处理？能详细点儿么

**Comment by CarGuo** [comment]
这个同步你可能需要加一个标志位，然后在全屏和恢复非全屏的接口重载中传递。然后除了在结束的时候显示，在重载的init方法里也通过判断标志位来处理是否显示。
