### ISSUE TITLE
横屏播放时切换节目会黑屏，有声音无画面，点击back回到竖屏直接播放器退出。

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#491]
运行环境：
StandardGSYVideoPlayer
版本：
    ijkplayer = '0.8.1'
    DanmakuFlameMaster = '0.6.4'
    transitionseverywhere = '1.7.0'
    GSYVideoPlayer:v2.0.2

红米Note4X

**Comment by Wangct23** [comment]
在Demo示例中的 MORE TYPE 可以复现
添加了一行代码：
`@Override
            public void onAutoComplete(String url, Object... objects) {
                super.onAutoComplete(url, objects);
                detailPlayer.startPlayLogic();
            }`

**Comment by CarGuo** [comment]
为什么要添加这个？

**Comment by Wangct23** [comment]
因为要按照播放列表来播放，但是列表是动态的，可能会变化。所以在播放完成或者播放过程中可能要随时切换节目(不会很频繁)。在横屏时切换节目，就黑屏了。只有声音没画面，而且在点击 back返回竖屏后，播放器直接就退出了。竖屏没这个问题。
我试过在切节目之前先回到竖屏，然后释放掉播放器，但是效果依然不理想，会引入新的更诡异的情况。
时间紧迫，这个问题已经弄了两天了，现在还没有完美的方案。
'''
if (livePlayer.isIfCurrentIsFullscreen()) {
                    onBackPressed();
                }
                GSYVideoManager.instance().releaseMediaPlayer();
'''
期待解决方案。。。

**Comment by CarGuo** [comment]
只有声音没有画面可能是渲染view释放了。

**Comment by Wangct23** [comment]
有什么办法可以解决吗？这个问题确实挺明显的，而且是必现问题。
还有就是，在没有画面的状态下回到竖屏，播放器就崩了，连声音也没有了。 @CarGuo

**Comment by CarGuo** [comment]
抱歉，理解错你的问题了，你在complete那里添加的应该是
detailPlayer.getCurrentPlayer().startPlayLogic();

**Comment by Wangct23** [comment]
按照 @CarGuo 的方法，解决问题。

    detailPlayer.getCurrentPlayer().startPlayLogic();

多谢[抱拳]
