### ISSUE TITLE
全屏后按钮点击没反应

### ISSUE THREAD

**Issue by cwyrzz** [CarGuo/GSYVideoPlayer#494]
添加了一个按钮，全屏后点击没反应，应该如何处理？

**Comment by CarGuo** [comment]
点击的方法添加位置是？？最好是继承播放控件，在重载方法中添加点击。

**Comment by cwyrzz** [comment]
![1](https://user-images.githubusercontent.com/16788723/31324573-ab18e296-ace6-11e7-82a6-b5c8e536cfce.png)
![2](https://user-images.githubusercontent.com/16788723/31324578-b1159360-ace6-11e7-9d53-22b15d21ef93.png)

**Comment by CarGuo** [comment]
明白了，需要重载全屏方法，把这个监听传给给全屏对象，具体参考demo中的实现。

**Comment by cwyrzz** [comment]
![33](https://user-images.githubusercontent.com/16788723/31324642-732ef8b0-ace7-11e7-8051-0a148df9e2e8.png)
这里要怎么写？或者具体是哪个demo？

**Comment by CarGuo** [comment]
强制类型转换成你的啊，然后赋值你的回调呀

**Comment by cwyrzz** [comment]
![444](https://user-images.githubusercontent.com/16788723/31326651-bb4cf494-acfb-11e7-8e16-66876dbf5ed3.png)
可以响应到事件了，但是在回调中调用播放视频，横屏的时候不起作用

**Comment by CarGuo** [comment]
detailPlayer.getCurrentPlayer().startPlayLogic();

**Comment by cwyrzz** [comment]
OK
