### ISSUE TITLE
一些视频播放黑屏只有声音没有图像

### ISSUE THREAD

**Issue by xuancao** [CarGuo/GSYVideoPlayer#496]
在播放的时候只有声音没有图像什么的，好像是你这个库用的ijkMediaplayer的原因，但是用androidMediaPalyer和ijkExoMediaplayer不会出现的呢，怎么处理？
测试链接：http://otdupykeh.bkt.clouddn.com/%E8%A7%86%E9%A2%916.mp4 这个链接在浏览器中无法显示，但是用后面两种是可以显示的

**Comment by sunkeding** [comment]
+1部分网络视频只有声音没有图像

**Comment by CarGuo** [comment]
首先确定视频的video编码是什么？其次可以试试ex so的

**Comment by sunkeding** [comment]
试试ex so的话有代码参考吗？https://cdn.leoao.com/freshman.mp4此链接黑屏

**Comment by CarGuo** [comment]
单独依赖原创仓 java 和 ex_so

**Comment by loveJYQ** [comment]
楼主解决了没有！求教 demo单独播放没问题，集成到项目里面就有声音没画面，试过在项目里面简化成只播放还是有问题。demo依赖的是 compile 'com.shuyu:GSYVideoPlayer:2.0.4'

**Comment by xuancao** [comment]
解决了，单独依赖了 ex_so

**Comment by xuancao** [comment]
看看是不是你依赖包有问题，试试      compile 'com.shuyu:gsyVideoPlayer-ex_so:2.0.0'
