### ISSUE TITLE
我对英文存在误解 setThumbImageView 是代表设置封面还是什么缩略图？

### ISSUE THREAD

**Issue by crazies** [CarGuo/GSYVideoPlayer#498]
我找到了一个叫cover的 但是发现也不对，我蒙逼了

**Comment by crazies** [comment]
是明白了，貌似这就是封面图，那么怎么控制 一直显示封面 又怎么控制 加载完成就隐藏封面，我这里有2方面需求，我发现状态太多了，有点蒙逼 不知道要复写哪些方法 ，而且主要是一个控件共用的。两套逻辑

**Comment by crazies** [comment]
一个界面可能是需要持久的封面也可能会需要之需要加载过程的封面

**Comment by crazies** [comment]
changeUiToCompleteClear  changeUiToCompleteShow changeUiToClear changeUiToPlayingBufferingClear  changeUiToPlayingBufferingShow 这么多状态头大。

**Comment by crazies** [comment]
changeUiToClear 是啥意思。

**Comment by CarGuo** [comment]
你看demo的那个SampleCoverVideo，然后没去判断，继承一些方法，至于显示隐藏，你可以参考https://github.com/CarGuo/GSYVideoPlayer/issues/495
