### ISSUE TITLE
怎么回事，所有视频播放，暂停后重新播放会失败一次然后再播放又重新从头开始播放了

### ISSUE THREAD

**Issue by crazies** [CarGuo/GSYVideoPlayer#499]
这是哪里的问题，是不是你们的老版本有过这样的问题呢

**Comment by CarGuo** [comment]
有url没

**Comment by crazies** [comment]
看qq私聊

**Comment by crazies** [comment]
已解决，老版本bug

**Comment by ywp0919** [comment]
我现在有个老项目里面用了com.shuyu:GSYVideoPlayer:1.6.5这个版本也出现这种情况了，但不是所有视频都会出现，只是偶然出现这种情况，请问一下这是因为老版本存在的问题么？ @crazies @CarGuo
