### ISSUE TITLE
initVideoBuilderMode一直报空指针

### ISSUE THREAD

**Issue by M0X0M** [CarGuo/GSYVideoPlayer#508]
Android，getGSYVideoPlayer，getGSYVideoOptionBuilder这两个参数都不为Null，但是就是报空指针

**Comment by CarGuo** [comment]
不是很理解

**Comment by M0X0M** [comment]
视频地址需要最开始进去就给吗，还是能请求数据以后再给

**Comment by M0X0M** [comment]
全屏的按钮图标是在哪里切换的

**Comment by CarGuo** [comment]
看demo的弹幕activity
