### ISSUE TITLE
Demo中的BindView没有

### ISSUE THREAD

**Issue by 1042933551** [CarGuo/GSYVideoPlayer#51]

**Comment by CarGuo** [comment]
什么意思？？

**Comment by 1042933551** [comment]
我把demo的源码全部复制到自己的工程中，然后发现没有BindView这个类,就是那个注解的

**Comment by CarGuo** [comment]
这个是没有butterKnidnife

**Comment by 1042933551** [comment]
什么？？缺少BindView，demo跑不起来

**Comment by 1042933551** [comment]
可以提供一下butterKnidnife吗？？

**Comment by CarGuo** [comment]
这个就不清楚了，demo没有问题，你这个缺少的就是butterKnidnife这个工具库！

**Comment by 1042933551** [comment]
好吧。。还有个问题，我使用listview然后使用播放器播放视频，当listview的item滑动出屏幕的时候，播放器就被释放了，怎么办。。搞了一下午，麻烦了T.T

**Comment by CarGuo** [comment]
有两种实现方式，你可以参考listVIew2那种！

**Comment by 1042933551** [comment]
遇到问题了，列表全屏需要设置listVideoUtil.setFullViewContainer(videoFullContainer);//设置全屏显示的viewGroup
如果viewGroup在布局的内部，那么点击全屏按钮后，无法达到全屏的效果，布局外部的控件会显示出来。
demo中的列表显示只有listview，如果我在listview下面或上面添加控件，那么全屏的时候这些控件不会隐藏。

**Comment by 1042933551** [comment]
ListVideoUtil里面没有暂停播放的方法，列表播放的时候如何暂停播放？
