### ISSUE TITLE
请问，有人实现了，视频无缝切换的效果吗？

### ISSUE THREAD

**Issue by Likarl** [CarGuo/GSYVideoPlayer#512]
两个视频之间切换的黑屏现象，项目经理死活都不让用，说是VLC上的视频切换就没有黑屏的现象。希望有实现的大佬，不吝赐教啊

**Comment by CarGuo** [comment]
你说的无缝，是切换的时候呈现什么状态的？

**Comment by Likarl** [comment]
从视觉上来看，上一个视频的最后一帧与下一个视频的第一帧是连续的，中间没有黑屏的状态。或者说有一个过渡的画面来欺骗用户。

**Comment by CarGuo** [comment]
下个版本应该会支持类似的功能，这几天看看能否完成

**Comment by Likarl** [comment]
非常感谢！

**Comment by a1onexiang2** [comment]
请问：多段视频视为一个整体应该怎么做？是属于无缝切换的范畴吗？

**Comment by CarGuo** [comment]
M3u8或者concat

**Comment by CarGuo** [comment]
SmartPickVideo 新版本demo

**Comment by zung** [comment]
无缝切换我按照SmartPickVideo写了，我把一个完整视频分成6段，并且帧没有重叠的，可以完美实现无缝切换，根本看不出来是分割的视频片段，和完整视频一模一样。
    但是，切换时的音效怎么取消掉，我没找到。
    最后我想问，无缝切换的原理是什么，能简单说下吗？

**Comment by cucygh** [comment]
我们在web上对mp4实现了无缝切换，可以参考https://github.com/bytedance/xgplayer/tree/master/packages/xgplayer-mp4
