### ISSUE TITLE
比较急的问题1

### ISSUE THREAD

**Issue by riseLishan** [CarGuo/GSYVideoPlayer#516]
在视频横屏播放完后，我在onAutoComplete方法里调用了detailPlayer.setUp()和detailPlayer.getCurrentPlayer().startPlayLogic()方法，但是一直播放的是第一个视频，不是我在onAutoComplete里再次调用detailPlayer.setUp()的新url的视频，竖屏没有问题，是好的

**Comment by CarGuo** [comment]
detailPlayer.getCurrentPlayer().xxxxxx

**Comment by loveRose** [comment]
老哥，你可以看看，这个横屏实际上是把你当前的播放器复制一份重新加载到了横屏模式的View里面，所以你找找那个横屏监听的地方就知道了
