### ISSUE TITLE
比较急的问题2

### ISSUE THREAD

**Issue by riseLishan** [CarGuo/GSYVideoPlayer#517]
横屏时自定义的UI是有效的，切换为横屏时却无效，目前不知道在哪修改横屏视频，望大神赐教，谢谢！！！

**Comment by CarGuo** [comment]
看demo

**Comment by loveRose** [comment]
老哥，你可以看看，这个横屏实际上是把你当前的播放器复制一份重新加载到了横屏模式的查看里面，所以你找找那个横屏监听的地方就知道了
