### ISSUE TITLE
关于GSYTextureView

### ISSUE THREAD

**Issue by junchenChow** [CarGuo/GSYVideoPlayer#52]
hi 作者大大 新年好呀～
关于GSYTextureView 有个疑问，项目既然是基于节操的来二次开发的 GSYTextureView 为什么不直接用节操的那一套。
因为我之前也是用过节操 小屏的时候 我的view 宽度matchParent高度wrapContent 节操的视频控件会自动计算高度 视频内容很完美的填充进去了 而且视频内容也没有明显拉伸的痕迹。
但是咱们这个项目 高度貌似还是有些问题 只能写死高度 不同分辨率的手机 会有不同程度的左右黑边 填充不了整个view。
不知道是不是节操以前版本也是这个样子 我之前用的是节操5.3的版本 他里面用的mediaplay来做底层的。

**Comment by CarGuo** [comment]
节操的以前没有做针对视屏旋转的角度处理，所以这里需要对其作处理。至于视频自动调整高度这个需求，因为比较低频所以就没有做对应的处理了。

**Comment by junchenChow** [comment]
能不能在demo里面加一个例子 动态调整一下高度 能让视频完整的填充view ～
