### ISSUE TITLE
B站视频同样的地址在ios能播放，android播不了，附地址

### ISSUE THREAD

**Issue by plmmanwu** [CarGuo/GSYVideoPlayer#520]
"url": "https://cn-zjwz-cmcc-v-09.acgvideo.com/vg0/4/05/25266980-1.mp4?expires=1508476500&platform=pc&ssig=1MHS7Srl3Jphkz13-HUWqg&oi=2015071626&nfa=iKQJtLw3Fy5f05Q/mDvFYw==&dynamic=1&hfa=2077903311&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=",
		"header": {
			"Referer": "https://www.bilibili.com/video/av11672133/",
			"User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1"
		}

-

**Comment by plmmanwu** [comment]
设置代码：
 mapHeadData.put("Referer", bean.getHeader().getReferer());
            mapHeadData.put("User-Agent", bean.getHeader().getUserAgent());
            setUp(mUrl, true, null, mapHeadData, "");

**Comment by CarGuo** [comment]
cache设置false

**Comment by plmmanwu** [comment]
还是不行，放原始demo里面跑的日志：
10-20 14:01:06.954 15163-15328/com.example.gsyvideoplayer E/IJKMEDIA: https://cn-zjwz-cmcc-v-09.acgvideo.com/vg0/4/05/25266980-1.mp4?expires=1508476500&platform=pc&ssig=1MHS7Srl3Jphkz13-HUWqg&oi=2015071626&nfa=iKQJtLw3Fy5f05Q/mDvFYw==&dynamic=1&hfa=2077903311&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=: Server returned 403 Forbidden (access denied)
10-20 14:01:06.954 15163-15260/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
10-20 14:01:06.954 15163-15163/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
10-20 14:01:06.964 15163-15260/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
10-20 14:01:06.964 15163-15163/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Againhttps://cn-zjwz-cmcc-v-09.acgvideo.com/vg0/4/05/25266980-1.mp4?expires=1508476500&platform=pc&ssig=1MHS7Srl3Jphkz13-HUWqg&oi=2015071626&nfa=iKQJtLw3Fy5f05Q/mDvFYw==&dynamic=1&hfa=2077903311&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=
10-20 14:01:08.054 15163-15260/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by plmmanwu** [comment]
header没加的话才会报403，现在加了还是一样。

**Comment by CarGuo** [comment]
这个目前看是403，至于需要检验的是哪些，问问你们ios端
