### ISSUE TITLE
3gp格式有声音，没画面

### ISSUE THREAD

**Issue by lqfsharks** [CarGuo/GSYVideoPlayer#523]
在 demo 中，将DetailPlayer类的播放路径替换为如下：
String url = "https://tshimage.teshehui.com/goods/video/201701/020100397287/main_video15087308953138528.3gp";

现象：有声音，没画面
备注：MP4格式可以正常播放，上述链接的视频没有问题（浏览器下载后可以正常播放）

请问上述问题是什么原因，怎么解决？

**Comment by CarGuo** [comment]
so没做3gp支持，详细请看问题集锦
