### ISSUE TITLE
有时会播放中断

### ISSUE THREAD

**Issue by Mitaxing** [CarGuo/GSYVideoPlayer#524]
D/IJKMEDIA: ANativeWindow_setBuffersGeometry: w=1280, h=720, f=(0x1) => w=1000, h=560, f=RV32(0x32335652)
D/IJKMEDIA: ijkmp_pause()
D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_PAUSE
D/IJKMEDIA: ijkmp_pause()=0

**Comment by CarGuo** [comment]
什么情况下可以重现？

**Comment by Mitaxing** [comment]
您好，现在使用的情况是两个页面：1、电影详情页播放预告片；2、电影播放页面播放正片。
当正片播放完成后，回到详情页重新播放预告片时，会发生暂停的情况，但是获取播放状态还是CURRENT_STATE_PLAYING播放中。

**Comment by CarGuo** [comment]
两个页面之间的切换你需要处理的比较多，因为release是一个内部异步操作。你可以再一个页面播放，使用列表播放模式，这样会好些

**Comment by Mitaxing** [comment]
嗯嗯，感谢您的建议
