### ISSUE TITLE
播放网络出错回调执行有问题

### ISSUE THREAD

**Issue by JinJieGu** [CarGuo/GSYVideoPlayer#525]
播放时断开网络，如果拖动进度条或者等视频播放到未缓冲的进度，VideoView不会调用onError回调而是进度条自动跳到最后？

**Comment by CarGuo** [comment]
有测试url没，或者参考demo的detailPlayer页面的注释，加上断网自动重连的头

**Comment by JinJieGu** [comment]
搞定，多谢。唯一的瑕疵就是断网重连是，拖动seekbar进度是无效的，可以任意拖动
