### ISSUE TITLE
清除缓存的问题（清除不了）

### ISSUE THREAD

**Issue by Luk0513** [CarGuo/GSYVideoPlayer#526]
用 GSYVideoManager。clearAllDefaultCache(Context context)；没有作用，缓存文件还在;用 GSYVideoPlayer。clearCurrentCache报空指针错误；（自定义的缓存地址）

**Comment by CarGuo** [comment]
你都自定义路径了，你就外部删除就好啦

**Comment by Luk0513** [comment]
我想知道为啥不成功嘛 ，这也算一个bug啊

**Comment by Luk0513** [comment]
刚刚试了吧 demo的示例改成自定义的缓存地址，清除缓存也是没有用

**Comment by CarGuo** [comment]
我在demo中设置是没问题的，只有一种情况就是播放的时候缓存完全了，不再是临时文件的时候，需要下次播放的时候再用clearCurrentCache才能清除

**Comment by Luk0513** [comment]
原来如此
