### ISSUE TITLE
大佬，如何禁用自动旋转呀

### ISSUE THREAD

**Issue by huaidan615924233** [CarGuo/GSYVideoPlayer#528]
想要旋转手机不自动切换横竖屏，只有点击全屏按钮的时候切换，该怎么做呢？
manifest里面已经设置了竖屏，并且加上webPlayer.setRotateViewAuto(false);这段代码之后仍然会自动切换，该如何解决？

**Comment by CarGuo** [comment]
外部还有一个OrientationUtils，要关闭设置enable为false

**Comment by huaidan615924233** [comment]
仍然没用

**Comment by CarGuo** [comment]
你死用了demo的WebDetailPlayer吧？继承了BaseActivity的那种？在base中onPrapared中，默认会设置为true

**Comment by huaidan615924233** [comment]
原来是这样，多谢
