### ISSUE TITLE
是否支持倍速播放呢？

### ISSUE THREAD

**Issue by buaashuai** [CarGuo/GSYVideoPlayer#529]
项目中遇到需要多倍速度播放的问题，不知是否能够支持呢

**Comment by CarGuo** [comment]
支持

**Comment by ltpostbox** [comment]
@CarGuo  6.0以下 倍速播放 存在变调问题  跪求解决方法！

**Comment by ltpostbox** [comment]
@CarGuo 作者  设置了 setSpeed(2f, true)  在Android5.1版本上 还是存在变调问题哇
