### ISSUE TITLE
print video stream urls at the logcat

### ISSUE THREAD

**Issue by OsamaDroidEgypt** [CarGuo/GSYVideoPlayer#530]
10-25 17:57:02.726 18086-18086/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToPreparingShow
10-25 17:57:02.726 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_native_setup
10-25 17:57:02.726 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170829--001
10-25 17:57:02.726 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: ijk_version_info: k0.8.1-62-ge1d04bd
10-25 17:57:02.726 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_create_from_android()
10-25 17:57:02.726 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque(0x2007ba)
10-25 17:57:02.726 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque()=void
10-25 17:57:02.726 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x2007ba)
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer V/IJKMEDIA: setDataSource: path http://127.0.0.1:34445/http%3A%2F%2F9890.vod.myqcloud.com%2F9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:34445/http%3A%2F%2F9890.vod.myqcloud.com%2F9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4")
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:34445/http%3A%2F%2F9890.vod.myqcloud.com%2F9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4")=0
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setLoopCount
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_volume
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_prepareAsync
10-25 17:57:02.727 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: ===== versions =====
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: ijkplayer    : k0.8.1-62-ge1d04bd
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: libavutil    : 55.58.100
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: libavcodec   : 57.89.100
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: libavformat  : 57.71.100
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: libswscale   : 4.6.100
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: libswresample: 2.7.100
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: ===== options =====
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: player-opts : loop                         = 1
10-25 17:57:02.728 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkapplication               = -1461699664
10-25 17:57:02.729 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkiomanager                 = -1461377024
10-25 17:57:02.729 18086-18302/com.example.gsyvideoplayer I/IJKMEDIA: ===================
10-25 17:57:02.729 18086-18328/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [18328] ff_msg_loop
10-25 17:57:02.729 18086-18328/com.example.gsyvideoplayer D/IJKMEDIA: message_loop
10-25 17:57:02.732 18086-18328/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_FLUSH:
10-25 17:57:02.733 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()=0
10-25 17:57:02.734 18086-18332/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [18332] ff_read
10-25 17:57:02.735 18086-18332/com.example.gsyvideoplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
10-25 17:57:02.735 18086-18331/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [18331] ff_vout
10-25 17:57:02.737 18086-18332/com.example.gsyvideoplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
10-25 17:57:02.737 18086-18332/com.example.gsyvideoplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
10-25 17:57:02.795 18086-18302/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
10-25 17:57:02.795 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
10-25 17:57:02.795 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x96e03530)
10-25 17:57:02.795 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_surface()
10-25 17:57:02.795 18086-18302/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x96e03530)=void
10-25 17:57:02.802 18086-18101/com.example.gsyvideoplayer D/EGL_emulation: eglMakeCurrent: 0xb3b05240: ver 2 0 (tinfo 0xb3b03210)
10-25 17:57:05.682 18086-18332/com.example.gsyvideoplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
10-25 17:57:06.539 18086-18328/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_OPEN_INPUT:
10-25 17:57:06.540 18086-18332/com.example.gsyvideoplayer E/IJKMEDIA: Option ijkiomanager not found.
10-25 17:57:06.566 18086-18328/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_FIND_STREAM_INFO:
10-25 17:57:06.566 18086-18332/com.example.gsyvideoplayer I/IJKMEDIA: max_frame_duration: 10.000
10-25 17:57:06.566 18086-18332/com.example.gsyvideoplayer I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://127.0.0.1:34445/http%3A%2F%2F9890.vod.myqcloud.com%2F9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4':

**Comment by CarGuo** [comment]
next verison provide api

**Comment by OsamaDroidEgypt** [comment]
@CarGuo  doesn't there any way to prevent that log I can do?!

**Comment by CarGuo** [comment]
see dev branch now

**Comment by DysaniazzZ** [comment]
```
 IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
Debuger.disable();
```
After adding the config, the log still exists: `V/IJKMEDIA: setDataSource: path xxxx`
@CarGuo
