### ISSUE TITLE
怎么播放本地SD卡内视频文件？

### ISSUE THREAD

**Issue by justlkn** [CarGuo/GSYVideoPlayer#532]
怎么播放本地SD卡内视频文件？没有找到相应方法，请告知，谢谢！

**Comment by CarGuo** [comment]
传本地路径就行了

**Comment by justlkn** [comment]
好的，已解决，谢谢

**Comment by chigang** [comment]
为什么我传了SD卡路径不管事,穿网络地址播放没问题
 private String url = SDPATH + "/Download/w.mp4";
