### ISSUE TITLE
从视频播放activity跳到新activity，正在播放的视频暂停返回该activity后视频可以继续播放 ，需要在播放视频的onDestroy里做什么操作

### ISSUE THREAD

**Issue by riseLishan** [CarGuo/GSYVideoPlayer#534]
从视频播放activity跳到新activity，正在播放的视频暂停返回该activity后视频可以继续播放 ，需要在播放视频的onDestroy里做什么操作

**Comment by CarGuo** [comment]
和ondestory没关系啊

**Comment by riseLishan** [comment]
我是用的这种方法 videoPlayer.setUp(list, true, "测试视频");播放视频的，跳转到新的activity再返回视频总是从开始播放，怎么控制才能返回这个activity从上次播放的地方开始播放，

**Comment by riseLishan** [comment]
@CarGuo 我是用的这种方法 videoPlayer.setUp(list, true, "测试视频");播放视频的，跳转到新的activity再返回视频总是从开始播放，怎么控制才能返回这个activity从上次播放的地方开始播放，

**Comment by Luk0513** [comment]
跳转的时候暂停视频播放 并记录播放进度（文档里有获取进度的方法），跳回来的时候检查一遍是否有进度，有就seekto（）到该播放进度开始播放
