### ISSUE TITLE
怎么播放assets或者raw中的视频啊？

### ISSUE THREAD

**Issue by love1699** [CarGuo/GSYVideoPlayer#536]
请问一下，怎么播放assets或者raw中的视频啊？

**Comment by CarGuo** [comment]
不支持

**Comment by shuaimango** [comment]
大神能支持么

**Comment by shuaimango** [comment]
节操支持哦，望大佬实现

**Comment by CarGuo** [comment]
//String url = "android.resource://" + getPackageName() + "/" + R.raw.test;
        //注意，用ijk模式播放raw视频，这个必须打开
        //GSYVideoManager.instance().enableRawPlay(getApplicationContext());

**Comment by shuaimango** [comment]
String videoUrl = "android.resource://" + getActivity().getPackageName() + "/" + videoDetail.videoRes;
        //注意，用ijk模式播放raw视频，这个必须打开
        GSYVideoManager.instance().enableRawPlay(getActivity().getApplicationContext());
        jz_video.setUp(videoUrl, true, videoDetail.subject);//StandardGSYVideoPlayer

播放报错如下：
11-21 18:16:57.128 7837-7970/com.example.myapplication E/IJKMEDIA: pipe:49: Invalid data found when processing input
11-21 18:16:57.143 7837-7837/com.example.myapplication E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by CarGuo** [comment]
你看demo，可以正常播放

**Comment by shuaimango** [comment]
jz_video.setUp(videoUrl, false, videoDetail.subject);
cacheWithPlay设置成false就可以播放本地视频了，设置true会出现如上错误。找了好久问题，后来同志引以为戒
