### ISSUE TITLE
放网络视频时,播放的时间超过了,视频总时长

### ISSUE THREAD

**Issue by ghZyh0804** [CarGuo/GSYVideoPlayer#540]
放网络视频时,播放的时间超过了,视频总时长,视频链接: 
http://7xjmzj.com1.z0.glb.clouddn.com/20171026175005_JObCxCE2.mp4

这个链接在PC端与ijkplayer  官方demo播放测试没问题,但是在这个项目中播放时间会比视频时长多出4,5秒

**Comment by CarGuo** [comment]
我在demo中没发现问题啊？18s的视频，你是在demo中哪里测试？

**Comment by ghZyh0804** [comment]
对呀..但是播放时间会超过18s.

**Comment by CarGuo** [comment]
我在机器人播放，没复现
