### ISSUE TITLE
请问一下，先是小屏播放，之后竖屏全屏播放应该怎么处理，看demo都是直接横屏全屏的

### ISSUE THREAD

**Issue by SiberiaDante** [CarGuo/GSYVideoPlayer#541]

**Comment by CarGuo** [comment]
设置island和autoRotationo接口，如果是detailplayer模式的，还需要设置外部的OrientationUtils

**Comment by CarGuo** [comment]
新修改demo  DetailMoreTypeActivity 和 DetailControlActivity 为竖屏全屏

**Comment by SiberiaDante** [comment]
感谢大神
