### ISSUE TITLE
Error：E/IJKMEDIA: 本地SD卡MP4: Permission denied

### ISSUE THREAD

**Issue by JianHaoZhangHB** [CarGuo/GSYVideoPlayer#542]
报错：10-30 19:01:48.844 21988-22088/com.example.mrhao.fingermapdemo E/IJKMEDIA: /storage/emulated/0/Video/林俊杰 - 可惜没如果 - 剧场版.mp4: Permission denied
10-30 19:01:48.850 21988-22044/com.example.mrhao.fingermapdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by chigang** [comment]
动态权限加了么
