### ISSUE TITLE
播放本地视频有声音但是黑屏，电脑、手机自带播放器可以打开

### ISSUE THREAD

**Issue by JianHaoZhangHB** [CarGuo/GSYVideoPlayer#543]
已经依赖了这两个但是还是黑屏。
compile 'com.shuyu:gsyVideoPlayer-java:2.1.1'
compile 'com.shuyu:gsyVideoPlayer-ex_so:2.1.1'
是不是除了依赖以外，还有什么操作。

**Comment by CarGuo** [comment]
具体看视频的编码是什么协议

**Comment by JianHaoZhangHB** [comment]
是H263格式的视频编码

**Comment by CarGuo** [comment]
有测试url么？

**Comment by JianHaoZhangHB** [comment]
我播放的是本地视频

**Comment by CarGuo** [comment]
需要测试文件，你可以上传个

**Comment by JianHaoZhangHB** [comment]
大神，怎么上传测试文件？

**Comment by CarGuo** [comment]
你可以上传到百度云，分享个链接给我之类的

**Comment by CarGuo** [comment]
首页你可以用demo测试会不会有问题

**Comment by JianHaoZhangHB** [comment]
把我的本地视频上传到百度云，然后把连接分享给你？

**Comment by JianHaoZhangHB** [comment]
我用Demo试一试去
