### ISSUE TITLE
url 后缀没有.mp4 播放不了

### ISSUE THREAD

**Issue by wqandroid** [CarGuo/GSYVideoPlayer#546]
http://47.94.182.49:80/huche/yihaokejito/chatfiles/5909abe0-bdf6-11e7-b94d-a111aa5cb975
 这个url在浏览器打开下载，文件名修改成.mp4 就可以播放了，但是用你们的播放器播放不了这个url ！
这个视频文件地址是环信的视频文件地址

**Comment by CarGuo** [comment]
IJKMEDIA: Stream ends prematurely at 48, should be 2730272
 IJKMEDIA: av_read_frame error: unknownIJKMEDIA: stream 1, offset 0x13b: partial fileIJKMEDIA: av_read_frame error: unknown
log上看是就有问题
