### ISSUE TITLE
Fragment中监听手机键返回时退出全屏不起作用

### ISSUE THREAD

**Issue by SiberiaDante** [CarGuo/GSYVideoPlayer#547]
if (orientationUtils != null) {
                orientationUtils.backToProtVideo();
            }

**Comment by SiberiaDante** [comment]
是设置了横屏全屏，然后想返回键退出全屏；

**Comment by CarGuo** [comment]
这个参考demo吧。返回事件是否从activity传递到Fragment

**Comment by SiberiaDante** [comment]
这是我Fragment中大返回代码
 public boolean onBackPressed() {
        videoView.getBackButton().setVisibility(View.GONE);
        SDLogUtil.d(TAG, "__________________back1_______________");
        if (hadIntercept) {
            hadIntercept = false;
            if (orientationUtils != null) {
                SDLogUtil.d(TAG, "__________________back2_______________");
                orientationUtils.backToProtVideo();
            }
            return true;
        } else {
            hadIntercept = true;
            SDLogUtil.d(TAG, "__________________back3_______________");
            return false;
        }
    }
按下返回键时，back2 log走了，但是不会退出横屏全屏状态，我看您demo的返回键退出全屏就是这样写的啊，麻烦指导一下，谢谢大神了

**Comment by CarGuo** [comment]
哪个页面的demo？？

**Comment by SiberiaDante** [comment]
感谢大神，看到你Fragment的Demo了，怪我，没仔细看demo，谢谢大神了
