### ISSUE TITLE
播放M3u8时手势seek有时候会提示seek到00：00，但实际seek是无效的

### ISSUE THREAD

**Issue by JinJieGu** [CarGuo/GSYVideoPlayer#549]
![image](https://user-images.githubusercontent.com/11242805/32215860-315635dc-bdf1-11e7-85ca-5517d7906a5e.png)
播放M3u8时手势seek有时候会提示seek到00：00，但实际并没有seek到00：00.

测试url：https://media6.smartstudy.com/ae/07/3997/2/dest.m3u8，demo里的url也是一样的

**Comment by CarGuo** [comment]
IJKMEDIA: https://media6.smartstudy.com/ae/07/3997/2/dest.m3u8: error while seeking  因为M3u8是多切片组合，这个组成协议，关键帧等有关
