### ISSUE TITLE
关于播放视频设置静音的问题

### ISSUE THREAD

**Issue by dreamofwarmcolor** [CarGuo/GSYVideoPlayer#550]
视频类型设置为IJKEXOPLAYER，调用静音方法无效，默认的类型就可以。

**Comment by CarGuo** [comment]
是的，exo不支持

**Comment by dreamofwarmcolor** [comment]
@CarGuo 但是我使用IJKPlayer，调用seekto方法跳转会不精准，使用EXOPlayer就没什么问题，有什么好的解决办法吗？

**Comment by CarGuo** [comment]
可以尝试以下设置

VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);

**Comment by dreamofwarmcolor** [comment]
@CarGuo 厉害了，多谢大佬提供的办法，3Q！
