### ISSUE TITLE
要让视频暂停的问题咨询

### ISSUE THREAD

**Issue by cancanw** [CarGuo/GSYVideoPlayer#551]
我想问一下，调用哪个方法可以让视频先准备好，然后点击播放的时候就直接可以播放了，因为我们的没有视频播放之前的那个图片，所以直接播放的话会有一段时间的黑屏。
我试了下面的方法，但是开始播放之后没有暂停，有没有什么方法能满足我这个需求的？求助～
 emptyControlVideo.setUp(resumevideo, true, "");
                emptyControlVideo.startPlayLogic();
                emptyControlVideo.onVideoPause();

**Comment by CarGuo** [comment]
继承播放器，重载onPrepared方法，参考源码中onPrepared的实现。
