### ISSUE TITLE
全屏和退出全屏的图标怎么换？

### ISSUE THREAD

**Issue by cancanw** [CarGuo/GSYVideoPlayer#555]

**Comment by CarGuo** [comment]
返回自己的自定义布局和重写接口，或者参考DanmkuVideoActivity

**Comment by cancanw** [comment]
可以再稍微提示一下关键代码在哪儿么，求助求助

**Comment by cancanw** [comment]
搞定
//使用自定义的全屏切换图片，!!!注意xml布局中也需要设置为一样的
        //必须在setUp之前设置
        danmakuVideoPlayer.setShrinkImageRes(R.drawable.custom_shrink);
        danmakuVideoPlayer.setEnlargeImageRes(R.drawable.custom_enlarge);
