### ISSUE TITLE
列表播放的情况下怎么使用重力感应切换横屏播放

### ISSUE THREAD

**Issue by traywangjun** [CarGuo/GSYVideoPlayer#556]
列表播放的情况下怎么使用重力感应切换横屏播放

**Comment by CarGuo** [comment]
和详情模式差不多，稍微做一些调整

**Comment by traywangjun** [comment]
列表的播放器对象是在适配器里 我是需要把适配器里的播放器对象回调到Activity里处理旋转的操作么

**Comment by traywangjun** [comment]
能给个思路么

**Comment by CarGuo** [comment]
更新下demo， ListVideoActivity 和 ListNormalAdapter

**Comment by traywangjun** [comment]
ok，我也实现了 我是把StandardGSYVideoPlayer对象回调到activity里处理
