### ISSUE TITLE
可以开放AndroidVideoCache设置缓存大小和缓存文件个数的接口吗？

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#557]
如题

**Comment by CarGuo** [comment]
你可以创建一个单例的proxy设置进去GSYVideoManager

**Comment by Wangct23** [comment]
在Application中如下设置，好像不起作用。还是一路狂缓存，直到把整个视频下载结束为止。
`
private HttpProxyCacheServer proxy;
    private final int MAX_VIDEO_CACHE_SIZE = 40 * 1024 * 1024; //40MB视频缓存

    public static HttpProxyCacheServer getProxy(Context context) {
        MyApplication app = (MyApplication) context.getApplicationContext();
        return app.proxy == null ? (app.proxy = app.newProxy()) : app.proxy;
    }

    private HttpProxyCacheServer newProxy() {
        return new HttpProxyCacheServer.Builder(this)
                .maxCacheSize(MAX_VIDEO_CACHE_SIZE)
                .cacheDirectory(StorageUtils.getIndividualCacheDirectory(this))
                .build();
    }

    private void _initVideoCache() {
        GSYVideoManager.instance().setProxy(getProxy(this));
    }

`

**Comment by Wangct23** [comment]
log中有这样一行提示：
W/HttpProxyCacheServer: Failed to close socket on proxy side: shutdown failed: ENOTCONN (Transport endpoint is not connected). It seems client have already closed connection.

**Comment by Wangct23** [comment]
http://cdn-media.jingzong.org/mp4/02/02-041/02-041-0503.mp4

**Comment by Wangct23** [comment]
如下图片所示，header应该没有赋值，不知道是不是这个问题导致的。
<img width="1046" alt="header" src="https://user-images.githubusercontent.com/17804057/32331562-3c1d6104-bfb1-11e7-962a-0adc7b3e8bd3.png">

**Comment by Wangct23** [comment]
昨天晚上我用AndroidVideoCache测试了一下，发现是AndroidVideoCache没有提供相应功能导致的。
和GSY没有关系。
不好意思。
