### ISSUE TITLE
视频有画面没有声音改怎么处理？

### ISSUE THREAD

**Issue by TimberBug** [CarGuo/GSYVideoPlayer#559]
通过这种方式集成后
![image](https://user-images.githubusercontent.com/18308932/32313764-6cb8f944-bfdf-11e7-9e5f-b29ed954022d.png)
，视频有的播放正常，有的只有画面没有声音，有声音的视频编码格式：
![image](https://user-images.githubusercontent.com/18308932/32313845-bf4f6396-bfdf-11e7-80eb-f0fe3b00abc3.png)
没有声音的视频编码格式：
![image](https://user-images.githubusercontent.com/18308932/32313866-d3084830-bfdf-11e7-85f3-71cae503fd5a.png)
是不是这个音频的编码格式的原因造成的？要怎么解决呢？

**Comment by CarGuo** [comment]
是编码问题，你可以看项根目录有两个.sh文件，叫xxxxmore.sh的就是目前支持的最多编码。如果想要支持更多。可以参考首页的编译教程，在sh上增加需要支持的格式

**Comment by TimberBug** [comment]
那个编译教程上说的是需要安装什么软件进行编译吗？是编译整个项目然后修改这个.sh文件吗？

**Comment by CarGuo** [comment]
教程有说

**Comment by TimberBug** [comment]
这个编码格式能不能最近给添加进去支持呢？

**Comment by CarGuo** [comment]
目前没有新增加其他格式的支持

**Comment by Mellowang001** [comment]
没有声音的问题怎么解决，我是小白看不懂上面怎么操作

**Comment by CarGuo** [comment]
你先确认你的音频编码是什么，然后确认是不是代码里有没有   setNeedMute(true)  ，有的话去掉 @Mellowang001  
如果是音频编码不支持，可以切换 PlayerManager 尝试

**Comment by Mellowang001** [comment]
咋切换playermanager，视频我是直接用外链放上去的直接是个链接，应该是编码问题

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager ，看文档 @Mellowang001

**Comment by Mellowang001** [comment]
太难为我玛卡巴卡了😂 看不懂啊
