### ISSUE TITLE
为什么报这个错误啊   java.lang.UnsatisfiedLinkError: com.facebook.imagepipeline.memory.NativeMemoryChunk

### ISSUE THREAD

**Issue by Lyl521** [CarGuo/GSYVideoPlayer#56]

**Comment by CarGuo** [comment]
log显示不是播放器的，是facebook的图片加载

**Comment by Lyl521** [comment]
嗯嗯好的我再看看

**Comment by CarGuo** [comment]
有可能是超过了64K限制，可以看看你的拆包是不是配置正确之类

**Comment by Lyl521** [comment]
我导入依赖不好用。一直gradie。没有反应。就和你demo一样的做法。

**Comment by CarGuo** [comment]
因为gradle下载的时候会先把所有支持库下载下来，其实对应的所有版本入armbi armbiv7 arm64 x86 x86_64合起来是比较大的，jitpack下载aar的速度有时候挺慢的，如果你有比较好的vpn，开l2tp协议下载会快一些。如果觉得慢可以直接克隆库或者https下载，之后本地依赖。
