### ISSUE TITLE
onVideoResume方法定位不准确

### ISSUE THREAD

**Issue by tangjiarao** [CarGuo/GSYVideoPlayer#564]
版本2.0.7
暂停后使用onVideoResume方法，不能从原来停止的地方开始播放，会提前几秒播放，如果视频只有十几秒的话，在前十秒的地方暂停再播放的话，就会变成重新开始播放

**Comment by CarGuo** [comment]
一般是视频关键帧太少问题，ffmpeg和mediacodec当时不一样
可以尝试以下设置

VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
如果还不行那就没办法了

**Comment by tangjiarao** [comment]
好的谢谢，暂时是能解决了，能不能问问这个配置加上去是什么意思呢？

**Comment by CarGuo** [comment]
开启精准seek，但是有时候可能seek比较耗费时间
