### ISSUE TITLE
这个m3u8 怎么播不了？

### ISSUE THREAD

**Issue by kungfucop** [CarGuo/GSYVideoPlayer#569]
https://www.dailymotion.com/cdn/manifest/video/x64mjej.m3u8?auth=1510119859-2562-aczrzl81-03e35b2f90f05fe6d06c8e86293c7650
debug信息：
 E/GSYVideoPlayer: Link Or mCache Error, Please Try Againhttps://www.dailymotion.com/cdn/manifest/video/x64mjej.m3u8?auth=1510119859-2562-aczrzl81-03e35b2f90f05fe6d06c8e86293c7650
11-05 21:57:05.834 13569-13826/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [13826]
11-05 21:57:05.834 13569-13810/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
11-05 21:57:05.834 13569-13810/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_dec_ref(): ref=0
11-05 21:57:05.834 13569-13810/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
11-05 21:57:05.835 13569-13810/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
11-05 21:57:05.837 13569-13810/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
11-05 21:57:05.837 13569-13810/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by CarGuo** [comment]
首先M3u8要关闭cache，然后我刚刚试了，提示连接超时， E/IJKMEDIA: https://www.dailymotion.com/cdn/manifest/video/x64mjej.m3u8?auth=1510119859-2562-aczrzl81-03e35b2f90f05fe6d06c8e86293c7650: Connection timed out

**Comment by kungfucop** [comment]
谢谢这么快回复！
这个是新的：https://proxy-30.sv6.dailymotion.com/sec(c167f5f6987a44005be7d21e2e0f2ac3)/video/990/765/370567099_mp4_h264_aac_ld_5.m3u8#cell=sv6

这个链接的m3u8 打开是这样：

`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:6
#EXTINF:3.000,
/sec(c167f5f6987a44005be7d21e2e0f2ac3)/frag(1)/video/990/765/370567099_mp4_h264_aac_ld_5.ts
#EXTINF:3.000,
/sec(c167f5f6987a44005be7d21e2e0f2ac3)/frag(2)/video/990/765/370567099_mp4_h264_aac_ld_5.ts
#EXTINF:3.000,
/sec(c167f5f6987a44005be7d21e2e0f2ac3)/frag(3)/video/990/765/370567099_mp4_h264_aac_ld_5.ts
#EXTINF:3.000,
/sec(c167f5f6987a44005be7d21e2e0f2ac3)/frag(4)/video/990/765/370567099_mp4_h264_aac_ld_5.ts
#EXT-X-ENDLIST
`

每一段都可以下载：比如第一段：
https://proxy-30.sv6.dailymotion.com/sec(c167f5f6987a44005be7d21e2e0f2ac3)/frag(1)/video/990/765/370567099_mp4_h264_aac_ld_5.ts

这有可能是m3u8格式都问题吗？

谢谢

**Comment by CarGuo** [comment]
好像这个链接也失效了，如果已经设置了cache为false，还播放不出来的，可以看下视频和音频的编码是什么，如果是支持的编码，那应该就是m3u8的协议组合问题，现在支持格式比较多的是ex so，具体可查阅首页的https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh
