### ISSUE TITLE
全屏播放黑屏，有声音，小屏没有问题

### ISSUE THREAD

**Issue by JinJieGu** [CarGuo/GSYVideoPlayer#570]
# 问题描述：要实现自动播放下一个视频的功能，小屏表现正常，全屏只出现声音却没有画面。
# 关键实现代码：
public void onAutoComplete(String url, Object... objects) {
                        super.onAutoComplete(url, objects);
                     detailPlayer.setUrl("ijkhttphook:http://baobab.wdjcdn.com/14564977406580.mp4");
                    }
                    

 public void setUrl(String url){
        mOriginUrl = url;
        startPlayLogic();
    }
# 机型：魅族 M1 E
 **已经使用了ex_so**

**Comment by CarGuo** [comment]
detailPlayer.getCurPlayer().setUrl("ijkhttphook:http://baobab.wdjcdn.com/14564977406580.mp4");
}

**Comment by JinJieGu** [comment]
@CarGuo 这个方法已经没有了啊

**Comment by CarGuo** [comment]
getCurrentPlayer

**Comment by JinJieGu** [comment]
恩，是的，但是没有setUrl方法，用setup可以吗

**Comment by CarGuo** [comment]
可以！话说不是有ListGSYVideoPlayer么

**Comment by JinJieGu** [comment]
Ok，Get it！Thank U
