### ISSUE TITLE
视频播放只有画面没有声音，在浏览器是有声音的

### ISSUE THREAD

**Issue by yichenweimei** [CarGuo/GSYVideoPlayer#571]
地址如下：http://vodrzliknfx.vod.126.net/vodrzliknfx/b26d2b69-8e36-4e79-9209-0b98a62e4c2e.mp4

**Comment by CarGuo** [comment]
音频编码是？一般这样的是音频编码不支持，目前默认只支持aac mp3等，不支持amr，mp2之类的

**Comment by yichenweimei** [comment]
支持wav吗？

**Comment by CarGuo** [comment]
我记得应该没有https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh

**Comment by yichenweimei** [comment]
怎么可以让他支持wav格式的呢

**Comment by CarGuo** [comment]
参考首页重新编译so！在.sh文件的基础上增加wav，然后使用编译好的so，不依赖远程so
