### ISSUE TITLE
你好，在接入的时候遇到一个问题：从Fragment列表（自动播放列表）跳转到Activity中播放视频，返回之后自动播放成功，但是画面是黑屏

### ISSUE THREAD

**Issue by cpMark** [CarGuo/GSYVideoPlayer#572]
没有跳转之前列表是正常播放的，而且返回之后滚动到别的条目再滚动回来也是正常的

**Comment by CarGuo** [comment]
1、列表播放的时候跳到activity继续播放，返回的时候可能列表的标志位存在问题，导致渲染层没有创建。
目前这种类型场景还没有试过。

**Comment by cpMark** [comment]
那我应该怎么处理，在返回的生命周期中重置标志位吗？

**Comment by cpMark** [comment]
@CarGuo 那我应该怎么处理，在返回的生命周期中重置标志位吗？

**Comment by cpMark** [comment]
@CarGuo 大神已经解决了，做了一个延迟就正常了，应该是返回列表页的时候渲染还没完成所以是黑屏
