### ISSUE TITLE
视频播放只有声音没有画面

### ISSUE THREAD

**Issue by pangjia1991** [CarGuo/GSYVideoPlayer#574]
只有有一个视频只有声音没有画面，其他的视频都有画面而且能正常播放，而且都是mp4格式的

**Comment by CarGuo** [comment]
视频编码是什么？请尝试exso

**Comment by 13242418950** [comment]
我也遇到这个问题,有些视频播放只有声音没图像,

**Comment by CarGuo** [comment]
确定视频编码，不是只是mp4这种容器协议，而是h264，mpeg等，如果是mpeg的可以使用exso

**Comment by 13242418950** [comment]
这是这个视频的编码信息,

视频
ID                                       : 1
文件格式                                     : MPEG-4 Visual
格式简介                                     : Simple@L3
格式设置, BVOP                               : 否
格式设置, QPel                               : 否
格式设置, GMC                                : No warppoints
格式设置, Matrix                             : Default (H.263)
编码设置ID                                   : 20
长度                                       : 43秒 0 ms
码率                                       : 4 070 kb/s
画面宽度                                     : 1 280像素
画面高度                                     : 720像素
画面比例                                     : 16:9
帧率模式                                     : 恒定
帧率                                       : 25.000 FPS
色彩空间                                     : YUV
色度抽样                                     : 4:2:0
位深度                                      : 8位
扫描方式                                     : 逐行扫描
压缩模式                                     : 有损压缩
bits/(pixel*frame)(数据密度)                 : 0.177
大小                                       : 20.9 MiB (97%)
编码函数库                                    : ZJMedia MPEG Encoder
编码日期                                     : UTC 1970-01-01 00:00:00
标记日期                                     : UTC 1970-01-01 00:00:00

**Comment by 13242418950** [comment]
还有个问题,ex_so里面是包括x64和x86的库,而我只需要armv5,armv7a这个怎么能分离出来了?

**Comment by 13242418950** [comment]
换了ex_so搞定!就是ex_so里面包括x64,x86而我只需要armv5,armv7a,只能下下来本地编译,要是能分开就更好了,还是非常感谢指导!

**Comment by CarGuo** [comment]
可以直接gradle的ndk过滤，参考demo，这样打包只会打包指定的

**Comment by 13242418950** [comment]
ok,多谢大佬指教
