### ISSUE TITLE
最新版本不支持本地avi格式文件播放啊？需要自己手动编译ijk然后替换so吗？

### ISSUE THREAD

**Issue by duhang324** [CarGuo/GSYVideoPlayer#575]
最新版本不支持本地avi格式文件播放啊？需要自己手动编译ijk然后替换so吗？

**Comment by CarGuo** [comment]
是的

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1206 aiv

**Comment by tangjian211085** [comment]
@duhang324  请问你知道怎么编译ijk吗？能否教教我

**Comment by duhang324** [comment]
@tangjian211085 修改ijk的momodule-lite.sh, 加入avi的支持
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=msrle"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=r10k"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=r210"

然后编译就可以了，替换其中的so就可以播放avi文件
