### ISSUE TITLE
hi 使用WebDetailDemo中的PreViewGSYVideoPlayer

### ISSUE THREAD

**Issue by huaidan615924233** [CarGuo/GSYVideoPlayer#577]
hi 使用WebDetailDemo的时候，在小屏界面正常播放完毕之后，点击全屏按钮，进入全屏之后的进度条旁边的时间为0了，该怎么解决呢

**Comment by CarGuo** [comment]
demo中能复现？好像没复现

**Comment by huaidan615924233** [comment]
可以复现的，使用WebDetailActivity，你滑动到最后，然后等他自己播放完毕，再点击全屏，进去之后时间显示是00

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/586
