### ISSUE TITLE
请问 ListVideoUtil 这个类为何被废弃了？废弃后它的替代方案呢？

### ISSUE THREAD

**Issue by drakeet** [CarGuo/GSYVideoPlayer#579]
你好，感谢分享和开源这个项目，它看起来很棒！但我在使用过程中发现如题这么一个疑问，没有找到相关文档和说明，麻烦能否解答下，谢谢！

GSYVideoPlayer 版本：2.1.1

**Comment by drakeet** [comment]
我看到 sample 中仍然在使用这个废弃类，如果能提供废弃理由和替代方案就好了。

**Comment by drakeet** [comment]
抱歉，找到相关文档了：

https://github.com/CarGuo/GSYVideoPlayer/blob/1afe55df10ffc67e22911d665b65567f2fae5e6c/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/utils/ListVideoUtil.java#L28-L36

不过并没有说得很清楚...

**Comment by CarGuo** [comment]
因为这个类能实现的功能直接使用更方便，只是目前不再维护这个类了。
