### ISSUE TITLE
点击播放，会崩溃

### ISSUE THREAD

**Issue by voler-JHL** [CarGuo/GSYVideoPlayer#582]
W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7f5d9c0b48)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7f5d9c0b48)=void
A/art: art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0x82
A/art: art/runtime/java_vm_ext.cc:470]     string: '�{]'
A/art: art/runtime/java_vm_ext.cc:470]     input: '0x10 <0x82> 0x7b 0x5d 0x7f'
A/art: art/runtime/java_vm_ext.cc:470]     in call to NewStringUTF
A/art: art/runtime/java_vm_ext.cc:470] "Thread-44" prio=5 tid=52 Runnable
A/art: art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x130df3a0 self=0x7f58bfb800
A/art: art/runtime/java_vm_ext.cc:470]   | sysTid=23523 nice=0 cgrp=default sched=0/0 handle=0x7f5d7b8450
A/art: art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 2397657 306563 3 ) utm=0 stm=0 core=1 HZ=100
A/art: art/runtime/java_vm_ext.cc:470]   | stack=0x7f5d6be000-0x7f5d6c0000 stackSize=1005KB
A/art: art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
A/art: art/runtime/java_vm_ext.cc:470]   native: #00 pc 00000000004cb730  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+220)
A/art: art/runtime/java_vm_ext.cc:470]   native: #01 pc 00000000004cb72c  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+216)
A/art: art/runtime/java_vm_ext.cc:470]   native: #02 pc 000000000049e750  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+480)
A/art: art/runtime/java_vm_ext.cc:470]   native: #03 pc 0000000000324eac  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1164)
A/art: art/runtime/java_vm_ext.cc:470]   native: #04 pc 0000000000325168  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+116)
A/art: art/runtime/java_vm_ext.cc:470]   native: #05 pc 0000000000105168  /system/lib64/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+152)
A/art: art/runtime/java_vm_ext.cc:470]   native: #06 pc 0000000000105854  /system/lib64/libart.so (_ZN3art11ScopedCheck14CheckUtfStringEPKcb+808)
A/art: art/runtime/java_vm_ext.cc:470]   native: #07 pc 000000000010224c  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+1152)
A/art: art/runtime/java_vm_ext.cc:470]   native: #08 pc 00000000000fcd7c  /system/lib64/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+620)
A/art: art/runtime/java_vm_ext.cc:470]   native: #09 pc 000000000005fb08  /data/app/live.bein.tarek.beinlive-1/lib/arm64/libijksdl.so (J4AC_android_os_Bundle__putString__withCString__catchAll+116)
A/art: art/runtime/java_vm_ext.cc:470]   native: #10 pc 0000000000023d08  /data/app/live.bein.tarek.beinlive-1/lib/arm64/libijkplayer.so (???)
A/art: art/runtime/java_vm_ext.cc:470]   native: #11 pc 000000000001a014  /data/app/live.bein.tarek.beinlive-1/lib/arm64/libijkplayer.so (inject_callback+20)
A/art: art/runtime/java_vm_ext.cc:470]   native: #12 pc 0000000000324a10  /data/app/live.bein.tarek.beinlive-1/lib/arm64/libijkffmpeg.so (av_application_on_tcp_did_open+200)
A/art: art/runtime/java_vm_ext.cc:470]   (no managed stack frames)
A/art: art/runtime/java_vm_ext.cc:470] 
A/art: art/runtime/runtime.cc:422] Runtime aborting...
A/art: art/runtime/runtime.cc:422] 
A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12d70b80 self=0x7f7aa25800
A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 57564527 239195992 498 ) utm=2 stm=3 core=3 HZ=100
A/art: art/runtime/runtime.cc:422]   kernel: binder_thread_read+0xf9c/0x1164
A/art: art/runtime/runtime.cc:422]   kernel: binder_ioctl+0x28c/0x710
A/art: art/runtime/runtime.cc:422]   native: #00 pc 00000000000785e8  /system/lib64/libc.so (__ioctl+4)
A/art: art/runtime/runtime.cc:422]   native: #02 pc 0000000000055cb4  /system/lib64/libbinder.so (_ZN7android14IPCThreadState14talkWithDriverEb+256)
A/art: art/runtime/runtime.cc:422]   native: #08 pc 0000000000075f20  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
A/art: art/runtime/runtime.cc:422] "Profile Saver" prio=5 tid=11 Native
A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 13665360 1320053 16 ) utm=1 stm=0 core=6 HZ=100
A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x88/0x94
A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xcc/0x47c
A/art: art/runtime/runtime.cc:422]   native: #00 pc 000000000001c12c  /system/lib64/libc.so (syscall+28)
A/art: art/runtime/runtime.cc:422]   | held mutexes=
A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x88/0x94
A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xcc/0x124
A/art: art/runtime/runtime.cc:422]   at sun.misc.Unsafe.park(Unsafe.java:325)
A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:519)
A/art: art/runtime/runtime.cc:422]   | sysTid=23091 nice=0 cgrp=default sched=0/0 handle=0x7f61ce6450
A/art: art/runtime/runtime.cc:422]   | stack=0x7f61be4000-0x7f61be6000 stackSize=1037KB
A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x88/0x94
A/art: art/runtime/runtime.cc:422]   kernel: futex_wait+0xec/0x200
A/art: art/runtime/runtime.cc:422]   kernel: SyS_futex+0xf0/0x168
A/art: art/runtime/runtime.cc:422]   native: #02 pc 00000000003b6b98  /system/lib64/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadElibNS_11ThreadStateE+668)
A/art: art/runtime/runtime.cc:422]   at java.lang.Thread.parkFor$(Thread.java:2127)
A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201)
A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:438)
A/art: art/runtime/runtime.cc:422]   | sysTid=23093 nice=-10 cgrp=default sched=0/0 handle=0x7f61be1450
A/art: art/runtime/runtime.cc:422]   (no managed stack frames)
A/art: art/runtime/runtime.cc:422] "pool-1-thread-1" prio=5 tid=21 Waiting
A/art: art/runtime/runtime.cc:422]   native: #00 pc 000000000001c12c  /system/lib64/libc.so (syscall+28)
A/art: art/runtime/runtime.cc:422]   native: #03 pc 0000000000000980  /system/framework/arm64/boot.oat (Java_java_lang_Object_wait__JI+140)
A/art: art/runtime/runtime.cc:422]   native: #00 pc 00000000000784fc  /system/lib64/libc.so (__epoll_pwait+8)
A/art: art/runtime/runtime.cc:422]   native: #02 pc 00000000000184d8  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+160)
A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12e2e670 self=0x7f629ae800
A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 8047655 13392136 59 ) utm=0 stm=0 core=1 HZ=100
A/art: art/runtime/runtime.cc:422]   | state=S schedstat=( 60912135 50566407 140 ) utm=6 stm=0 core=7 HZ=100
A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xcc/0x124
A/art: art/runtime/runtime.cc:422]   kernel: do_futex+0xcc/0x47c
A/art: art/runtime/runtime.cc:422]   kernel: el0_svc_naked+0x24/0x28
A/art: art/runtime/runtime.cc:422]   native: #02 pc 00000000003b6b88  /system/lib64/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadElibNS_11ThreadStateE+652)
A/art: art/runtime/runtime.cc:422]   - waiting on <0x0a00a12f> (a java.lang.Object)
A/art: art/runtime/runtime.cc:422]   - locked <0x0a00a12f> (a java.lang.Object)
A/art: art/runtime/runtime.cc:422] "Picasso-Idle" prio=5 tid=29 Waiting
A/art: art/runtime/runtime.cc:422]   | sysTid=23110 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0x7f60005450
A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
A/art: art/runtime/runtime.cc:422]   kernel: SyS_futex+0xf0/0x168
A/art: art/runtime/runtime.cc:422]   native: #02 pc 000000000003e8a8  /system/lib64/libhwui.so (???)
A/art: art/runtime/runtime.cc:422] "hwuiTask2" prio=5 tid=31 Native
A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x88/0x94
A/art: art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c7ff60 self=0x7f71574e00
A/art: art/runtime/runtime.cc:422]   native: #03 pc 0000000000000980  /system/framework/arm64/boot.oat (Java_java_lang_Object_wait__JI+140)
A/art: art/runtime/runtime.cc:422]   - locked <0x0cd278c5> (a java.lang.Object)
A/art: art/runtime/runtime.cc:422]   at java.lang.Object.wait!(Native method)
A/art: art/runtime/runtime.cc:422]   | stack=0x7f5ddd9000-0x7f5dddb000 stackSize=1037KB
A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x88/0x94
A/art: art/runtime/runtime.cc:422]   kernel: futex_wait+0xec/0x200
A/art: art/runtime/runtime.cc:422]   native: #00 pc 000000000001c12c  /system/lib64/libc.so (syscall+28)
A/art: art/runtime/runtime.cc:422]   native: #00 pc 000000000001c12c  /system/lib64/libc.so (syscall+28)
A/art: art/runtime/runtime.cc:422]   | sysTid=23163 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0x7f5dbcc450
A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
A/art: art/runtime/runtime.cc:422]   | sysTid=23187 nice=0 cgrp=default sched=0/0 handle=0x7f5ceb4450
A/art: art/runtime/runtime.cc:422]   kernel: __switch_to+0x88/0x94
A/art: art/runtime/runtime.cc:422] 
A/art: art/runtime/runtime.cc:422]   at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
A/art: art/runtime/runtime.cc:422]   native: #02 pc 00000000003b6b88  /system/lib64/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadElibNS_11ThreadStateE+652)
A/art: art/runtime/runtime.cc:422]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
A/art: art/runtime/runtime.cc:422]   kernel: futex_wait_queue_me+0xcc/0x124
A/art: art/runtime/runtime.cc:427]   native: #07 pc 000000000010224c  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+1152)
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 23523 (Thread-44)

        [ 11-10 14:38:51.898   629:  629 W/         ]
        debuggerd: handling request: pid=23033 uid=10392 gid=10392 tid=23523
Application terminated.

**Comment by CarGuo** [comment]
请在demo中复现
