### ISSUE TITLE
播放器复用问题

### ISSUE THREAD

**Issue by wwhelloworld** [CarGuo/GSYVideoPlayer#585]
多个fragment都放置播放器，播放会相互串扰

**Comment by drakeet** [comment]
+1

**Comment by CarGuo** [comment]
你多个fragment需要用多个不用的tag和position组合判断，至于播放是只能一个处于播放中的

**Comment by drakeet** [comment]
只能有一个在播放，那么其余能否保持暂停视频画面？

**Comment by CarGuo** [comment]
目前需要自己做对应逻辑，因为实际上真实播放器只有一个，播放UI通过播放共享播放器，如果要另外一个处于暂停，你需要继承播放器，在被释放的回调里拦截下来释放，然后记录播放位置，判断是否播放过，然后设置对应的UI，在再次点击播放的时候，通过setSeekOnStart，然后再次续播等等，一些细节会比较多。

**Comment by jarkeet** [comment]
简直了，只能有一个播放器， 播放另一个视频，上一个播放器就被释放了。想要前一个视频接着播放，得提前纪录播放点，然后判断继续播放后定位上次纪录的时间点播放

**Comment by CarGuo** [comment]
@jarkeet 播放器默认情况下都是一个内核，你看其他app就知道。当然demo里也提供了多个内核的实现方式，这样会增加内存和网络的额外消耗。

另外也有用两个内核自己做管理的，现在playermanager都可以自己自定义
