### ISSUE TITLE
引入后提示合并失败

### ISSUE THREAD

**Issue by dengyuhan** [CarGuo/GSYVideoPlayer#587]
我项目里已经有libmp3lame和ffmpeg.
单独引入ijk库可以编译成功.
但引入gsyVideoPlayer就会编译失败.

![image](https://user-images.githubusercontent.com/17588779/32760021-4f9a2aee-c927-11e7-9cd7-2958886f6982.png)
![image](https://user-images.githubusercontent.com/17588779/32760605-fa97a140-c929-11e7-8ad3-97c91bd3c636.png)
![image](https://user-images.githubusercontent.com/17588779/32760662-406d3f36-c92a-11e7-907e-58554213962f.png)
![image](https://user-images.githubusercontent.com/17588779/32760667-4b0ba464-c92a-11e7-8180-a23372a7ca3f.png)

**Comment by CarGuo** [comment]
你可以引用gsy的java和ijk的so
