### ISSUE TITLE
TalkingData上关于播放器IllegalStateException 错误统计出现了很多

### ISSUE THREAD

**Issue by junchenChow** [CarGuo/GSYVideoPlayer#59]
这个出现的比较多
`java.lang.IllegalStateException: mpjni: seekTo: null mp
	tv.danmaku.ijk.media.player.IjkMediaPlayer.seekTo(Native Method)
	com.shuyu.gsyvideoplayer.GSYVideoPlayer.onTouch(Proguard:638)
	com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.onTouch(Proguard:291)
	android.view.View.dispatchTouchEvent(View.java:8590)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2513)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2157)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
	com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2493)
	com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1806)
	android.app.Activity.dispatchTouchEvent(Activity.java:2832)
	android.support.v7.view.i.dispatchTouchEvent(Proguard:71)
	android.support.v7.view.i.dispatchTouchEvent(Proguard:71)
	com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2454)
	android.view.View.dispatchPointerEvent(View.java:8807)
	android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4662)
	android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4520)
	android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
	android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
	android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
	android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4190)
	android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
	android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4247)
	android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
	android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
	android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
	android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
	android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
	android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6463)
	android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6437)`

**Comment by CarGuo** [comment]
seekTo 的时候播放器还没有创建，这个需要看你使用的过程出现了什么问题？个人使用过程中没有遇到。

**Comment by junchenChow** [comment]
我也没碰到过  这是线上版本统计出的崩溃日志

**Comment by CarGuo** [comment]
未能重现，close
