### ISSUE TITLE
播放视频拉伸问题

### ISSUE THREAD

**Issue by fenghebaiyang** [CarGuo/GSYVideoPlayer#590]
在Demo中通过InputUrlDetailActivity播放864*480分辨率的视频时会出现拉伸的现象，自己的一个解决办法是修改GSYRenderView中的getTextureParams方法返回WRAP_CONTENT.

**Comment by CarGuo** [comment]
有url可以提供下测试吗？

**Comment by fenghebaiyang** [comment]
抱歉，刚刚忘记了 
http:\/\/dqsj-m3u8-test.cn-bj.ufileos.com\/m3u8\/movieKung.Fu.Panda.3.2016.1080p.HC.WEBRip.x264.AAC2.0-STUTTERSHIT_480p.m3u8

**Comment by CarGuo** [comment]
不好意思现在才回复，我再demo中试了没拉伸啊

**Comment by fenghebaiyang** [comment]
我测试的机型是小米4和S7Edge，用Demo中的InputUrlDetailActivity中全屏播放时，会把视频拉伸为满屏播放，然后正常情况，视频不应该为满屏，上下应该有黑边的。 我在公车群里，我发截图给你看看吧。

**Comment by CarGuo** [comment]
你的视频就是16:9的，全屏肯定铺满…

**Comment by fenghebaiyang** [comment]
这个视频不是16：9的

**Comment by CarGuo** [comment]
我把视频下载下来后，用手机自带播放器播放其中的切片，也是满屏的。

**Comment by CarGuo** [comment]
这是测试得到的结果数据，看起来没有什么问题

| 状态     | 功能                                       |
| ------ | -------------------------------|
| 视频大小是 ： 864x480|比例 9:5 1.80000|
|按照小米手机分辨率 ： 1920x1080 | 比例 16:9   1.77777|
|全屏demo中计算得到的最终显示大小: 1920x1066| 比例 10:5.55  1.8011 |
