### ISSUE TITLE
非全屏的时候怎么让下面的进度条一直显示呢

### ISSUE THREAD

**Issue by chen-krolser** [CarGuo/GSYVideoPlayer#591]
在非全屏的情况下像让进度条一直显示，就把进度条放到播放视屏下面了，然后在重写的init()里面判断非全屏的时候调用setViewShowState()让进度条显示，但是进去的时候没有显示，要点播放后才能显示，而且再次点击屏幕的时候还是会消失，不知道要怎么设置

**Comment by CarGuo** [comment]
参考源码中的standradgsyvideoplayer
