### ISSUE TITLE
请问下怎么认证 Digest authentication 呢

### ISSUE THREAD

**Issue by davy445** [CarGuo/GSYVideoPlayer#592]
11-15 16:15:20.770 6405-6490/com.example.gsyvideoplayer V/IJKMEDIA: line='WWW-Authenticate: Basic realm="48ea6362afe8"'
11-15 16:15:20.770 6405-6490/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=0d []
11-15 16:15:20.770 6405-6490/com.example.gsyvideoplayer V/IJKMEDIA: ret=1 c=0a [
                                                                    ]
11-15 16:15:20.770 6405-6490/com.example.gsyvideoplayer V/IJKMEDIA: line=''
11-15 16:15:20.770 6405-6490/com.example.gsyvideoplayer E/IJKMEDIA: **method OPTIONS failed: 401 Unauthorized**
11-15 16:15:20.770 6405-6490/com.example.gsyvideoplayer D/IJKMEDIA: CSeq: 2
                                                                    WWW-Authenticate: Digest realm="48ea6362afe8",nonce="5a0bf798cbcf61815e00", stale="FALSE"
                                                                    WWW-Authenticate: Basic realm="48ea6362afe8"
11-15 16:15:20.780 6405-6490/com.example.gsyvideoplayer E/IJKMEDIA: rtsp://101.88.234.9:50554/unicast/c45/s0/live/forward: Server returned 401 Unauthorized (authorization failed)
11-15 16:15:20.780 6405-6490/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6490]
11-15 16:15:20.780 6405-6488/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
11-15 16:15:20.780 6405-6437/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

一直都是401..地址是这个rtsp://admin:Huasu1234@101.88.234.9:50554/unicast/c45/s0/live/forward

**Comment by CarGuo** [comment]
怎么认证你应该付去服务后台吧，添加哪些header校验
