### ISSUE TITLE
demo中有几个视频播放不了 进度转完就回到点击播放的那个样式了。

### ISSUE THREAD

**Issue by justziyang** [CarGuo/GSYVideoPlayer#597]
webDetail那个功能点开播放不了，其他还有几个也播不了。

**Comment by CarGuo** [comment]
请提供url

**Comment by justziyang** [comment]
http://baobab.wdjcdn.com/14564977406580.mp4

**Comment by CarGuo** [comment]
这个视频可以播放，不过有些奇怪一些网络环境拉不回，我试了用移动4G可以，联通4G拉不回，估计是DNS等之类的问题
