### ISSUE TITLE
截图lastListener 这里判断空然后没判断好，如果说视频没有设置循环播放退出的时候按back键就会空指针

### ISSUE THREAD

**Issue by LinForStudy** [CarGuo/GSYVideoPlayer#6]
![image](https://cloud.githubusercontent.com/assets/18901958/20701874/270beab2-b650-11e6-9ce1-f273ec017e2f.png)

**Comment by CarGuo** [comment]
back是返回键吗？请问一下具体是空指针是那个地方空指针导致crash？

**Comment by CarGuo** [comment]
我好想大致上理解了，奇怪为什么我这边没出现呢，我修改一下哈

**Comment by CarGuo** [comment]
已经更新1.3.1，如果可以了请close，thx
