### ISSUE TITLE
快进快出会造成主线程ui阻塞

### ISSUE THREAD

**Issue by tz-xiaomage** [CarGuo/GSYVideoPlayer#60]
进入视频页面自动开始播放，立马退出页面，调用销毁，整个页面会卡顿，等到日志打印销毁成功后，才正常

**Comment by tz-xiaomage** [comment]
![image](https://cloud.githubusercontent.com/assets/12270504/22876237/9e09b00e-f20a-11e6-97ee-9219688d93c8.png)

卡完之后会打印这些日志

**Comment by CarGuo** [comment]
demo中会卡顿？

**Comment by tz-xiaomage** [comment]
重复多次才出现，可能你没发现，我是完全用demo的，没改动任何东西

**Comment by tz-xiaomage** [comment]
例如我的A页面是个list，点击list item进入视频播放页，且主动调用播放，再立马按返回键，重复多次后，A页面卡住没法滑动，日志会等打印出视频销毁后才不卡，如果你重现不了，那可以忽略我这个问题，我只是提个问题而已，现在我换成了别的播放器，没这个问题

**Comment by CarGuo** [comment]
确实没发现呢。因为我这边是自己项目中使用，也是经常会有这个使用的情况，请问下可以提供下问题的机型吗？

**Comment by tz-xiaomage** [comment]
已知的线上小米5、vivox5v、小米note1、三星、google kit
