### ISSUE TITLE
怎么根据playTag或者url获取缓存的文件路径?

### ISSUE THREAD

**Issue by dengyuhan** [CarGuo/GSYVideoPlayer#601]
我设置了缓存的文件夹路径
也设置了PlayTag
但是缓存后的文件名不是按url来的，那该怎么获取到缓存后的文件路径

**Comment by CarGuo** [comment]
参考这个

    /**
     * 删除url对应默认缓存文件
     */
    public static void clearDefaultCache(Context context, String url) {
        Md5FileNameGenerator md5FileNameGenerator = new Md5FileNameGenerator();
        String name = md5FileNameGenerator.generate(url);
        String pathTmp = StorageUtils.getIndividualCacheDirectory
                (context.getApplicationContext()).getAbsolutePath()
                + File.separator + name + ".download";
        String path = StorageUtils.getIndividualCacheDirectory
                (context.getApplicationContext()).getAbsolutePath()
                + File.separator + name;
        CommonUtil.deleteFile(pathTmp);
        CommonUtil.deleteFile(path);

    }
