### ISSUE TITLE
这个URL地址的视频，开启缓存后无法播放

### ISSUE THREAD

**Issue by Arirus** [CarGuo/GSYVideoPlayer#602]
作者你好，http://103.233.191.21/riak/riak-bucket/6469ac502e813a4c1df7c99f364e70c1.mp4 这个地址的视频正常是可以播放的，但是开启缓存后，无法播放。日志打出  W/HttpProxyCacheServer: Failed to close socket on proxy side: shutdown failed: ENOTCONN (Transport endpoint is not connected). It seems client have already closed connection.
但是使用原版的AndroidVideoCache是可以播放并缓存的，不知道出的什么问题。

**Comment by CarGuo** [comment]
看起来问题有点奇怪，因为这流socket流一直拉不完，已经几百M还在拉，导致拉回的流分给播放器播放有问题

**Comment by Arirus** [comment]
会不会是由于缓存造成的，没开启缓存的时候是好的

**Comment by CarGuo** [comment]
就是socket缓存框架在拉流的时候，一直没拉到底，看起来就像是hls的直播流一样

**Comment by itkrly** [comment]
@CarGuo 我也遇到了这个问题，请问有什么解决方案吗？视频地址：http://img.xxwei.cn/%E6%97%A0%E9%94%A1%E7%BB%8F%E6%96%B9%E8%AE%BA%E5%9D%9B/01-2018.8.18%E9%A6%96%E5%B1%8A%E5%85%A8%E5%9B%BD%E7%BB%8F%E6%96%B9%E5%AE%9E%E6%88%98%E8%AE%BA%E5%9D%9B%E5%88%98%E6%96%B9%E6%9F%8F1.mp4
![image](https://user-images.githubusercontent.com/15819777/56570388-6e147600-65ed-11e9-9298-4a031fe57dec.png)
