### ISSUE TITLE
用Demo的“输入URL”功能播放rtsp协议视频，无法播放

### ISSUE THREAD

**Issue by hansionit** [CarGuo/GSYVideoPlayer#603]
Log：E/GSYVideoPlayer: Link Or mCache Error, Please Try Againrtsp://192.168.0.1:554/livestream/12

**Comment by asyncHyj** [comment]
@CarGuo 在demo中使用"输入网址URL"功能中，想使用rtsp。能否指点一下，如何切换成exso？

**Comment by CarGuo** [comment]
把so的依赖去掉，替换成ex的so
