### ISSUE TITLE
ViewPager 嵌套Fragment

### ISSUE THREAD

**Issue by wangxiaojiao** [CarGuo/GSYVideoPlayer#606]
ViewPager `嵌套Fragment滑动后点击全屏按钮横屏播放，全屏后再点击全屏按钮不能竖屏
 望大神指点

Activity中的代码只是view pager的设置

`  private void initFragement(){
        for (int i=0;i<15;i++){
            fragments.add(new PlayerFragment());
        }
    }
    private void initViewPager(){
        FragmentManager manager = getSupportFragmentManager();
        adapter = new ViewPagerFragementAdapter(manager,fragments);
        vp.setAdapter(adapter);
    }`

Fragment中的代码

       ` public class PlayerFragment extends Fragment implements VideoAllCallBack {
    private Context mContext;
    private OrientationUtils orientationUtils;
    protected boolean isPlay;

    protected boolean isPause;
    private StandardGSYVideoPlayer gsyVideoPlayer;

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        mContext=context;
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return View.inflate(mContext,R.layout.video_fragment_layout,null);
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        initView(view);
    }
    private void initView(View view){
        gsyVideoPlayer = (StandardGSYVideoPlayer) view.findViewById(R.id.video_player);
        initPlayer();
    }
    private void initPlayer() {
        //增加title
        gsyVideoPlayer.getTitleTextView().setVisibility(View.GONE);
        //设置返回键
        gsyVideoPlayer.getBackButton().setVisibility(View.GONE);
        orientationUtils = new OrientationUtils(getActivity(), gsyVideoPlayer);
        orientationUtils.setEnable(false);
        if (gsyVideoPlayer.getFullscreenButton() != null) {
            gsyVideoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    //直接横屏
                    orientationUtils.resolveByClick();
                    //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                    gsyVideoPlayer.startWindowFullscreen(getActivity(), false, true);
                }
            });
        }
        gsyVideoPlayer.setVideoAllCallBack(this);
        gsyVideoPlayer.setShowFullAnimation(false);
        gsyVideoPlayer.setUp("http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4",true,null,"标题");
    }

    @Override
    public void onResume() {
        super.onResume();
        gsyVideoPlayer.getCurrentPlayer().onVideoResume();
        isPause = false;
    }

    @Override
    public void onPause() {
        super.onPause();
        gsyVideoPlayer.getCurrentPlayer().onVideoPause();
        isPause = true;
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        //如果旋转了就全屏
        if (isPlay && !isPause) {
            gsyVideoPlayer.onConfigurationChanged(getActivity(), newConfig, orientationUtils);
        }
    }
    @Override
    public void onDestroy() {
        super.onDestroy();
        if (isPlay) {
            gsyVideoPlayer.getCurrentPlayer().release();
        }
        if (orientationUtils != null)
            orientationUtils.releaseListener();
    }

    @Override
    public void onPrepared(String url, Object... objects) {
        if (orientationUtils == null) {
            throw new NullPointerException("initVideo() or initVideoBuilderMode() first");
        }
        //开始播放了才能旋转和全屏
        orientationUtils.setEnable(true);
        isPlay = true;

    }
    @Override
    public void onQuitFullscreen(String url, Object... objects) {
        if (orientationUtils != null) {
            orientationUtils.backToProtVideo();
        }
    }

    @Override
    public void onClickStartIcon(String url, Object... objects) {

    }

    @Override
    public void onClickStartError(String url, Object... objects) {

    }

    @Override
    public void onClickStop(String url, Object... objects) {

    }

    @Override
    public void onClickStopFullscreen(String url, Object... objects) {

    }

    @Override
    public void onClickResume(String url, Object... objects) {

    }

    @Override
    public void onClickResumeFullscreen(String url, Object... objects) {

    }

    @Override
    public void onClickSeekbar(String url, Object... objects) {

    }

    @Override
    public void onClickSeekbarFullscreen(String url, Object... objects) {

    }

    @Override
    public void onAutoComplete(String url, Object... objects) {

    }

    @Override
    public void onEnterFullscreen(String url, Object... objects) {

    }

    @Override
    public void onQuitSmallWidget(String url, Object... objects) {

    }

    @Override
    public void onEnterSmallWidget(String url, Object... objects) {

    }

    @Override
    public void onTouchScreenSeekVolume(String url, Object... objects) {

    }

    @Override
    public void onTouchScreenSeekPosition(String url, Object... objects) {

    }

    @Override
    public void onTouchScreenSeekLight(String url, Object... objects) {

    }

    @Override
    public void onPlayError(String url, Object... objects) {

    }

    @Override
    public void onClickStartThumb(String url, Object... objects) {

    }

    @Override
    public void onClickBlank(String url, Object... objects) {

    }

    @Override
    public void onClickBlankFullscreen(String url, Object... objects) {

    }
}
`

**Comment by CarGuo** [comment]
这个和嵌套在哪里没关系，请参考demo。

**Comment by xuywei** [comment]
这个问题我也复现了，全屏返回不能返回，一般先竖屏再返回到原大小，可是竖屏之后没返回原大小，我的测试机手机必现概率90%了，全屏返回修复一下策略吧，能直接返回不，别横向，是不是跟陀螺仪太灵敏的缘故
