### ISSUE TITLE
点击全屏先暂停，全屏之后再播放如何做

### ISSUE THREAD

**Issue by huaidan615924233** [CarGuo/GSYVideoPlayer#608]
点击全屏时候调用了onVideoPause，然后在startWindowFullscreen（）方法或者在cloneParams（）方法中设置onVideoResume想要恢复播放都不起作用
有些手机性能偏低，全屏切换会出现卡顿，所以想要先暂停一下再播放，该如何解决呢

**Comment by CarGuo** [comment]
onResume的时候要先getcurrentplayer

**Comment by huaidan615924233** [comment]
有加，会卡顿，并且切换全屏之后播放按钮的状态改变不过来
