### ISSUE TITLE
进度条自定义没效果

### ISSUE THREAD

**Issue by chen-krolser** [CarGuo/GSYVideoPlayer#610]
GSYVideoOptionBuilder中的设置进度条样式.setBottomShowProgressBarDrawable（）没效果
用player中的方法进度条也没变化

**Comment by gyymz1993** [comment]
今天遇见同样的问题，不过知道怎么解决了，你要用的地方重写楼主的方法，然后不实现父类的方法就可以了。

**Comment by chen-krolser** [comment]
我自定义的播放器继承那个standerGSYVideoPlayer类，然后重写了.setBottomShowProgressBarDrawable（）方法，然后在调用的时候还是没效果啊

**Comment by CarGuo** [comment]
你可以直接返回自己的布局样式
