### ISSUE TITLE
请问怎么设置ijkplayer的log

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#613]
我这里一打开视频播一会儿就会疯狂打印下面这样的信息，影响调试。谢谢啦
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT)

**Comment by Wangct23** [comment]
刚刚在GSYApplication中看到。想来关掉issue就看到作者回复了。
太及时了，感谢。

**Comment by workgithubly** [comment]
> GSYVideoManager.instance().setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT)

这么设置了 但是并没有效果
