### ISSUE TITLE
普通详情页视频播放增加按钮，切换横屏后怎么获取横屏的按钮？

### ISSUE THREAD

**Issue by haiguihuang** [CarGuo/GSYVideoPlayer#615]
普通详情页的视频播放增加个按钮，横屏的按钮怎么获取？现在貌似只能获取竖屏时候的。。就差这个问题了。

**Comment by CarGuo** [comment]
player.getCurrentPlayer()

**Comment by haiguihuang** [comment]
。。还有提示吗，LandLayoutVideo 中重写了这方法，咸鱼还是不会用唉。

**Comment by CarGuo** [comment]
player.getCurrentPlayer()获取到的就是当前的播放前，全屏是获取到的是全屏的，非全屏获取到的就是非全屏的，这时候获取到得播放器可以做强制类型转换为你当前播放器
