### ISSUE TITLE
Is A-B Loop possible?

### ISSUE THREAD

**Issue by KnIfER** [CarGuo/GSYVideoPlayer#622]

**Comment by CarGuo** [comment]
you must do it youselft ， like ListGSYVideoPlayer

**Comment by KnIfER** [comment]
but it involves accurate time seeking.

**Comment by CarGuo** [comment]
i m not sure what you mean😂

**Comment by KnIfER** [comment]
就是你设置ab循环一句话，结果循环了一句半的话。。而且时间a还不准确😂

**Comment by CarGuo** [comment]
fix like https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exo

use

ConcatenatingMediaSource and LoopingMediaSource
