### ISSUE TITLE
播放多视频时，永远是最后一个加载的可以播放，现在GSYVideoPlayer 支持多视频播放吗？

### ISSUE THREAD

**Issue by zzp880303** [CarGuo/GSYVideoPlayer#624]
![tim 20171130134433](https://user-images.githubusercontent.com/11313833/33415907-c4799796-d5d4-11e7-99c0-0cd6dfbc1512.png)

**Comment by CarGuo** [comment]
不支持多视频同时播放

**Comment by zzp880303** [comment]
后期有添加多视频的可能吗？
