### ISSUE TITLE
切换全屏竖屏时，屏幕会向屏幕顶端缩进一些再下来全屏，全屏退出时，屏幕也是向最顶端缩进一些再下来，很影响观感效果

### ISSUE THREAD

**Issue by tiefeiniu** [CarGuo/GSYVideoPlayer#625]

**Comment by CarGuo** [comment]
增加主题样式
        <item name="android:windowTranslucentStatus">true</item>
    </style>
在顶层布局增加
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorPrimary"
    android:clipToPadding="false"
    android:fitsSystemWindows="true">

实现的沉浸式状态栏就可以解决。参考我的另一个项目
https://github.com/CarGuo/DragPhotoView

 或者
也可以设置全屏接口statusbar为false
