### ISSUE TITLE
一进来就点击播放，还未播放就快速退出这个播放界面，在上一个activity发现视频在播放

### ISSUE THREAD

**Issue by tiefeiniu** [CarGuo/GSYVideoPlayer#626]

**Comment by CarGuo** [comment]
不是很理解，你需要在退出的时候释放视频，如果你需要的话？

**Comment by nohavename** [comment]
我也遇到了这样的问题,我用的是fragment,在视频开始播放还在加载过程中,我调用了暂停方法,然后切换到其它的fragment,过一段时间,差不多几秒钟,有视频播放的声音,也就是说,切换fragment时调用的暂停方法未生效

**Comment by CarGuo** [comment]
楼上这种情况是有可能的，因为加载中使用暂停是无法生效的，你可以在开始播放的回调里，根据当前fragment的状态再次去暂停它

**Comment by nohavename** [comment]
多谢大神，问题已解决，Thank you very much
