### ISSUE TITLE
关于视频title问题

### ISSUE THREAD

**Issue by gaoshan12312** [CarGuo/GSYVideoPlayer#627]
不管设置显示或不显示title，title父布局的阴影一直存在（非全屏状态下）。通过getparent拿到title的父布局，设置为gone，父布局阴影一直存在，请问如何让title父布局隐藏呢？

**Comment by CarGuo** [comment]
不是很理解，demo中会？？？

**Comment by gaoshan12312** [comment]
对，在demo里也是这样。设置了 gsyVideoPlayer.getTitleTextView().setVisibility(View.GONE);
title虽然不显示了，但是其所在的topcontainer的父布局的阴影一直存在。每个item顶部都会有个阴影，看起来很怪。

**Comment by CarGuo** [comment]
你说的是activity上的actionbar？？？

**Comment by chen-krolser** [comment]
那个阴影布局不是title的那个textview，是一个linearlayout布局中包含标题布局，那个linear布局中的背景色是设置成了阴影效果的，linearlayout的id是layout_top,代码中对应的应该是mTopContainer，可以试试重新设置那个背景

**Comment by gaoshan12312** [comment]
嗯，自己自定义布局，修改了下背景色就好了。
