### ISSUE TITLE
视频播放完毕后不能滑动

### ISSUE THREAD

**Issue by meixinxicun** [CarGuo/GSYVideoPlayer#628]
1、视频播放完毕当前时间停留在最后一秒，但是视频画面没有停留在最后一秒
2、视频播放完毕后不能滑动进度条
3、没有thumbImageView的时候能不能自动获取视频第一帧画面，且总时间能不能自动显示出来（现在是开始播放后才能显示总时间）

**Comment by CarGuo** [comment]
1、因为播放结束后就释放了，如果有需要停留在最后一秒请继承后处理，继承后参考源码的ListGSYVideoPlyer
2、播放结束后不能拖动也是默认设置如果，如果播放结束后有这样的需求，请继承后处理。
3、获取封面请参考demo的如SampleCoverVdieo，最后没播放肯定没时间，你到没获取视频信息，除非你服务端给你返回时间
