### ISSUE TITLE
不支持分段视频播放，不是轮播

### ISSUE THREAD

**Issue by hutianfeng** [CarGuo/GSYVideoPlayer#63]
希望大神加入分段视频播放功能

**Comment by CarGuo** [comment]
不是很理解，详细需求是怎么样的？

**Comment by hutianfeng** [comment]
就是一个完整的视频被分成几个连续小视频，现在只能获取每个小视频的url,现在需求是，通过一组分段的视频url播放视频，就是轮播，但要做出像只有一个url播放完整视频的操作

**Comment by CarGuo** [comment]
那么只能建议你把切片合成m3u8格式，然后温馨提示，m3u8目前不支持边播边录。

**Comment by hutianfeng** [comment]
目前需求只需要播放即可，请问如何把第三方的分片url合成m3u8格式

**Comment by CarGuo** [comment]
ffpmeg其實可以配置支持播放放分片，只是需要你重新编译so，编译的流程我github首页有，你可以在module配置上，参考这个issue
https://github.com/Bilibili/ijkplayer/issues/490，和这个http://www.jianshu.com/p/ea794a357b48，可以帮助到你。
至于m3u8的合成，可以通过ffpmeg命令或者第三方工具，

**Comment by CarGuo** [comment]
请参考- https://github.com/CarGuo/GSYVideoPlayer/issues/64
