### ISSUE TITLE
播放优酷的m3u8视频时 会暂停，底部的时间会继续走，并且不报playerror 错误

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#631]
播放优酷的m3u8视频时 会暂停，底部的时间会继续走，并且不报playerror 错误
需要解决的问题：
1.视频暂停时 时间也暂停。
2.怎么监听视频是否暂停了。
3.优酷的m3u8视频地址有时间限制，贴出来也没用，有些视频会这样，不是所有。

**Comment by CarGuo** [comment]
不是很理解场景，如果没有测试url比较麻烦。
这个底层有对一些playerror做了拦截，你可以继承后找做拦截监听，如果是ijkmediaplayer层的ffmepg没有返回，那么可能就需要考虑服务端问题。毕竟m3u8突然间一个切片失效的话。

**Comment by Greathfs** [comment]
这个我最近也遇到了 拿到优酷m3u8地址时 可能会画面卡住 然后下面的进度条继续走 也就是通过获取getCurrentPosition()这个值是一直增加的 并且会超过整个的视频长度后还继续走 同样不执行playError()状态 因为什么都是正常的 就是画面卡住了 没声音
