### ISSUE TITLE
遇到了ENDownloadView内存泄漏的问题

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#634]
has leaked:
* GC ROOT android.media.AudioTrack.mInitializationLooper
* references android.os.Looper.mThread
* references thread java.lang.Thread.localValues (named 'main')
* references java.lang.ThreadLocal$Values.table
* references array java.lang.Object[].[99]
* references android.animation.ValueAnimator$AnimationHandler.mAnimations
* references java.util.ArrayList.array
* references array java.lang.Object[].[2]
* references android.animation.ValueAnimator.mUpdateListeners
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* references moe.codeest.enviews.ENDownloadView$3.this$0 (anonymous implementation of android.animation.ValueAnimator$AnimatorUpdateListener)
* references moe.codeest.enviews.ENDownloadView.mContext
* leaks  instance

* Retaining: 4.3 KB.
* Reference Key: 56562be9-41ae-4910-bacf-2e936ae41db0
* Device: samsung Verizon SM-G920V zerofltevzw
* Android Version: 6.0.1 API: 23 LeakCanary: 1.5.4 74837f0
* Durations: watch=5210ms, gc=186ms, heap dump=3845ms, analysis=27147ms

[leaked_info.txt](https://github.com/CarGuo/GSYVideoPlayer/files/1525532/leaked_info.txt)

**Comment by CarGuo** [comment]
我记得是处理过的了，居然还有场景会出现？具体是哪种场景下？

**Comment by Wangct23** [comment]
我是在自己的项目中用的，具体场景是 播放过程中返回 到上一层页面。在onDestroy中已经release了。

**Comment by Wangct23** [comment]
集成进来的是 2.1.1 版本

**Comment by Wangct23** [comment]
@CarGuo 您那边有复现吗？

**Comment by CarGuo** [comment]
貌似没在demo中复现
