### ISSUE TITLE
设置视频任意比率

### ISSUE THREAD

**Issue by liulance** [CarGuo/GSYVideoPlayer#636]
您好，请问下怎么设置视频的任意比率，现在里面有4：3，16：9，我们的需求可能是这中间的任意比率，宽度是充满全屏，高度是不固定的，请问该怎么设置呢？谢谢

**Comment by CarGuo** [comment]
这个高度不固定的你需要动态调整控件高度？？？
设置比例和显示方式项目里已经有对应的接口了，至于wrap content的方法，你需要继承播放器后对renderview做处理，因为内部默认都是match parent的

**Comment by liulance** [comment]
嗯，我现在需要设置播放器宽高，让画面充满播放器，而不是有黑边，是需要对renderview 做处理吗？能说说具体怎么弄吗？谢谢

**Comment by CarGuo** [comment]
使用SCREEN_MATCH_FULL模式，然后动态调整你的宽高就可以了

**Comment by liulance** [comment]
好的，解决了，谢谢
