### ISSUE TITLE
录制的视频H264编码的mp4无法在线播放，本地可以，在线播放时间直接跳到末尾

### ISSUE THREAD

**Issue by YinWeiLF** [CarGuo/GSYVideoPlayer#637]
异常如下：Could not find codec parameters for stream 0 (Video: h264, 1 reference frame (avc1 / 0x31637661), none(left), 640x480, 1/180000, 1294 kb/s): unspecified pixel format
                                                            Consider increasing the value for the 'analyzeduration' and 'probesize' options

**Comment by CarGuo** [comment]
这个应该是流的问题

**Comment by YinWeiLF** [comment]
自定义录制的视频不能播放，手机自带的相机录制的可以播放，怀疑是录制的问题，可是试了你推荐的那个录制上传之后也是一样的问题

**Comment by CarGuo** [comment]
录制的视频编码和音频编码是？

**Comment by YinWeiLF** [comment]
H264 和AAC

**Comment by CarGuo** [comment]
如果是这样的格式没理由播放不了，播放不了不在乎流问题和格式问题，你用的是哪个第三方库录制的？？？

**Comment by YinWeiLF** [comment]
https://github.com/CJT2325/CameraView

https://github.com/CarGuo/VideoRecord 
以上两个都不行,ε=(´ο｀*))

**Comment by CarGuo** [comment]
第二个录制的可以播放啊···

**Comment by YinWeiLF** [comment]
在本地都是可以播放的，但是放到线上就不可以了，我试了下，放到百度网盘里面也都是不能播放

**Comment by CarGuo** [comment]
不能播放的log是？提供一个url方便吗？
