### ISSUE TITLE
设置静音问题

### ISSUE THREAD

**Issue by liulance** [CarGuo/GSYVideoPlayer#639]
GSYVideoManager里面333行这里，每次都设置为有声音，是不是应该传needMute这个变量呢，这样方便继承播放器的时候，在外面更改是否静音，现在设置为静音后，播放下一个视频，声音又打开了
![image](https://user-images.githubusercontent.com/22095781/33600413-21a46776-d9e4-11e7-9fbb-bc91ee3cb646.png)

**Comment by CarGuo** [comment]
不是很理解， 不过这个你可以继承后做对应的设置逻辑处理即可，比如在prepare的时候就传入false，因为没有开发播放是不会有声音的，默认设置有声音，是个人觉得比较方便
