### ISSUE TITLE
一个视频，多个视频片段问题

### ISSUE THREAD

**Issue by ruzhan123** [CarGuo/GSYVideoPlayer#64]
我看到这几行代码：
`    private void initIJKPlayer(Message msg) {
        mediaPlayer = new IjkMediaPlayer();
        mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
        try {
            mediaPlayer.setDataSource(((GSYModel) msg.obj).getUrl(), ((GSYModel) msg.obj).getMapHeadData());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }`

目前只支持网络url吗？
我现在遇到一个url返回多个视频片段，我需要手动拼成m3u8文件，然后怎么样才能播放呢

**Comment by Qrilee** [comment]
哈哈，我也遇到了这方面的问题，可以手动去拼接成m3u8，但是没有什么好的方法去播放这个文件

**Comment by CarGuo** [comment]
你只能是拼成m3u8，播放器处理这样的逻辑不是很合理呢～

**Comment by ruzhan123** [comment]
@CarGuo 通过concat协议解决了

**Comment by hhyyzz** [comment]
@CarGuo 这个播放器支持任意格式的视频文件吗？

**Comment by mahmoudelfeel** [comment]
How did you solve it by concat ?

**Comment by ruzhan123** [comment]
@mahmoudelfeel 
[https://github.com/ruzhan123/PlayerDemo/blob/master/app/src/main/assets/test.concat](url)
