### ISSUE TITLE
关于加载缩略图消失问题

### ISSUE THREAD

**Issue by liulance** [CarGuo/GSYVideoPlayer#640]
您好，请问下，视频加载中的时候，如何让视频的缩略图不消失呢？现在demo中加载的时候，缩略图都是消失了，视频会黑一下。我现在想加载的时候，loading在缩略图上，视频有画面了，缩略图才消失，群里面问了下没人回答，只能在这里提问了，麻烦了，谢谢！

**Comment by CarGuo** [comment]
如果我记得没错，应该是在standardVideoPlayer下的mThumbImageViewLayout相关的，你可以继承后，重载所有的changexxxxxx的方法，然后设置
