### ISSUE TITLE
列表刷新，正在播放的视频暂停黑屏了

### ISSUE THREAD

**Issue by liulance** [CarGuo/GSYVideoPlayer#642]
您好，不好意思又麻烦您了，问下，在列表中调用  notifyDataSetChanged();正在播放的视频黑掉了，这个是怎么回事，能否保证刷新的时候，继续播放，谢谢了

**Comment by CarGuo** [comment]
这个不属于播放器问题吧？比如你更新的是重新走了setup和startplay之类的
