### ISSUE TITLE
关于视频GSYMediaPlayerListener相关的监听

### ISSUE THREAD

**Issue by xuefengyuan** [CarGuo/GSYVideoPlayer#643]
设置了监听也没有调用，Demo中看到有相应的监听实现，但在自定义View层没有看到调用。这是里面设置监听的时候哪里覆盖了还是？

**Comment by CarGuo** [comment]
监听参考demo中的SampleListener

**Comment by xuefengyuan** [comment]
GSYMediaPlayerListener 问的是这个监听回调，外部传进去的，没用，看了下源码里肌有好几个地方被重新设置了，不知道是不是这个原因。

**Comment by CarGuo** [comment]
不是很理解你说呢，这个回调是主要是在内部使用的，将Manager的状态分法发View，而demo里的唯一外部设置的是用于无缝切换的时候创建新的Manager才使用的，而其他时候使用的回调是VideoAllCallBack
