### ISSUE TITLE
全屏切换时遇到内存泄漏问题

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#644]
![image](https://user-images.githubusercontent.com/17804057/33694112-40763a0a-db31-11e7-87a1-12360a5ca368.png)
在华为的4.2.2版本的手机上出现的情况，性能比较低。
出现场景是，做一次全屏切换，back到上一层Activity，然后就出现泄漏了。

**Comment by CarGuo** [comment]
具体泄露的是什么？？

**Comment by CarGuo** [comment]
这个一般不会再这种情况下泄露，只是单纯旋转的话，你配置了manifest没？，配置了在旋转才不会重新构建

**Comment by Wangct23** [comment]
@CarGuo 
在高配的手机上没发现过这问题，在低端手机首次发现。之前在下层Activity配置了manifest，需要把最底层的Activity也配置了试试看么？

**Comment by CarGuo** [comment]
要的，底层activity也要的，你可以输出看所以activity有没有重新走onCreate

**Comment by Wangct23** [comment]
@CarGuo 从最底层的Activity开始加上，就没再复现了。
