### ISSUE TITLE
直播流rtmp的，播放时有画面没声音，在电脑上用VLC播放是有声音的。

### ISSUE THREAD

**Issue by Demidong** [CarGuo/GSYVideoPlayer#645]
如果用HLS.也是有声音的

**Comment by Demidong** [comment]
当播放其对应的音频流时，logcat如下：
Failed to open file 'rtmp://wuhan51.rt1.gensee.com/4b46c24f0f4846b2a3826ee148978849_83161_0_8802174621_1512614595_c3d60424/audio' or configure filtergraph
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by Demidong** [comment]
目前这个音频解码格式为Codec : Speex Audio。这种格式是不是不支持？是否配置下格式就可以使其支持呢？

**Comment by CarGuo** [comment]
speex现在没有支持，如果要支持需要重新编译so，编译方法首页有，你可以使用根目录的xxxxmorexxx.sh文件作为基础去增添

**Comment by Demidong** [comment]
有点蒙圈。大神可否在下个版本发布的时候支持下。

**Comment by CarGuo** [comment]
这个自己打包so后替换使用自己的so，不依赖远程so就可以了，打包so不麻烦的，参考首页教程
