### ISSUE TITLE
如何去除左上角的暂停播放按钮？

### ISSUE THREAD

**Issue by shadowline** [CarGuo/GSYVideoPlayer#646]
![qq 20171205170640](https://user-images.githubusercontent.com/2800735/33695492-9be4afdc-db38-11e7-8322-b02e004a858b.jpg)
![2](https://user-images.githubusercontent.com/2800735/33695584-01277b68-db39-11e7-92f3-dad2a32454fe.jpg)

**Comment by CarGuo** [comment]
不是很理解，你这个是demo中的？
如果你不需要你就在自定义布局中去掉即可
