### ISSUE TITLE
在recycleview中视频四周都留有黑边的问题。

### ISSUE THREAD

**Issue by gaoshan12312** [CarGuo/GSYVideoPlayer#648]
在recycleview的item中播放视频，有的视频四周都有黑边。请问这怎么解决呢？我也有尝试设置设置播放type，设置比例啥的，但是效果都不是很理想。不要求填充四个边，起码要得有两个边填充，这怎么搞呢？
还有视频的黑边有点影响观看体验，自己可以自定义视频黑边么？（类似其他APP的黑边填充成毛玻璃的效果），还请指教，谢谢~

**Comment by CarGuo** [comment]
直接设置全屏拉伸或者全屏裁剪试试

**Comment by CarGuo** [comment]
至于毛玻璃那种，你你可以看看demo中的，有类似的GSYVideoGLViewCustomRender2在这个基础上加上高斯滤镜，高斯滤镜demo也有

**Comment by gaoshan12312** [comment]
ok，谢谢
