### ISSUE TITLE
如何配置点击小锁头锁定屏幕之后不再跟随屏幕旋转

### ISSUE THREAD

**Issue by wei120698598** [CarGuo/GSYVideoPlayer#649]
系统设置屏幕自动旋转

如何配置达到锁定屏幕后视频不再跟随屏幕旋转的效果

**Comment by CarGuo** [comment]
你在onPause中对播放器设置autorotate false和外部旋转工具utils为关闭？

**Comment by wei120698598** [comment]
没起作用啊？我觉得这个框架默认应该将这个功能加上，因为主流的都是锁定后就只能点击解锁，否则什么都不能干

**Comment by wei120698598** [comment]
![image](https://user-images.githubusercontent.com/12169314/33747459-0d6e04ee-dbfe-11e7-902e-18405eb84d78.png)
解决了

**Comment by chailijun** [comment]
66666，碰到同样的问题，用同样的方法已解决（同样的配方，同样的效果）
