### ISSUE TITLE
下载你的demo运行之后，播放flv格式的视频时是没有声音的。

### ISSUE THREAD

**Issue by 604481157** [CarGuo/GSYVideoPlayer#65]
下载你的demo运行之后，另外播放flv格式的视频时是没有声音的。应该如何优化？

**Comment by CarGuo** [comment]
flv没声音是因为没有支持对应的音频格式，你需要看你的flv是的音频格式是什么，群里我记得有人处理过，因为我这边打包的so是趋向于通用的so，对于一些编码格式是默认去掉的，如果需要支持对应的音频编码格式，可以自己在ijk的编译时候moudle加上。上次那位的音频格式是wav。
