### ISSUE TITLE
视频播放进度条跳动问题

### ISSUE THREAD

**Issue by coolxtc** [CarGuo/GSYVideoPlayer#650]
视频播放切换到全屏，暂停后退出全屏，点击开始按钮后进度条和当前的播放时间都会有跳动

比如第六秒暂停，点击开始后进度条和显示的时间会跳到九秒，然后再跳回去。但是视频播放没有问题，不会跳帧。不同机型上的表现情况不同，有的跳的快有的跳的慢。魅族mx4上跳的比较慢，现象较明显

**Comment by coolxtc** [comment]
使用demo中的播放器也有同样问题

**Comment by coolxtc** [comment]
还有一种触发情况 暂停后播放也会偶现上述问题，不过全屏切换后跳动的概率比较大

**Comment by coolxtc** [comment]
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list);
这个关键帧的属性已经设置过了，只能解决拖动问题，好像对描述的问题没有太多用

**Comment by CarGuo** [comment]
这个确实是对seek时候有用。至于暂停播放的问题，因为寻找关键帧，确实会有可能偏移，ijk的ffmepg不可避免会有这种情况，

**Comment by coolxtc** [comment]
@CarGuo 那个偏移的程度经过测试感觉和暂停的时间成正相关，暂停时间越久，偏移量越大

**Comment by CarGuo** [comment]
理论上这个是没关系的

**Comment by coolxtc** [comment]
@CarGuo 这个问题在demo中可以复现，我看了代码，原因是暂停后点击播放按钮的时候，先调用了GSYVideoControlView里面的cancelProgressTimer();方法，然后再次开启刷新进度条和进度文本的ProgressTimerTask任务。就会去重新通过GSYVideoManager.instance().getMediaPlayer().getCurrentPosition();方法获取进度位置，从而导致了进度信息有闪烁现象。至于getCurrentPosition这个方法获取数据的不对的问题我查找不到原因，如果有空的话，希望能抽空帮忙看一下。

**Comment by CarGuo** [comment]
闪烁和获取的问题我在跟下，主要还是获取的问题复现难度问题

**Comment by coolxtc** [comment]
如果手机上显示不明显的话，可以通过打日志的模式跟踪setTextAndProgress()方法，应该可以在log里面获取到跳动的那次时间。复现的话我这边用的mx4或者红米note4x机型，可以在视频播放切换到全屏，暂停后退出全屏，然后点击开始按钮观察log里面的输出。十分感谢跟进！

**Comment by ZHBoy** [comment]
进度条闪烁的这个问题，在视频时长较短的时候会更容易复现，

**Comment by CarGuo** [comment]
确实有看到，目前看下怎么优化比较好吧
