### ISSUE TITLE
视频播放 点击弹出控制界面时 视频播放变卡了

### ISSUE THREAD

**Issue by Greathfs** [CarGuo/GSYVideoPlayer#651]
现在是我在播放视频时 控制界面右侧需要有剧集列表 用的RecyclerView实现的,但是弹出控制界面后,明显感觉视频播放变卡了

**Comment by coolxtc** [comment]
感觉你在主线程做了耗时操作吧

**Comment by CarGuo** [comment]
不是很理解，没有发现这样的问题。

**Comment by Greathfs** [comment]
![image](https://user-images.githubusercontent.com/18097997/33752028-023f2c26-dc1a-11e7-9bff-b468dbc947f0.png)

大概界面就是这样的 点击后弹出控制界面 我们放的是电视剧 右侧是剧集列表

**Comment by Greathfs** [comment]
@coolxtc 控制界面有些东西的确是在主线程更新的 但是UI的更新只能在主线程啊 有什么好的解决办法吗 控制界面的图就在上面

**Comment by coolxtc** [comment]
@Greathfs 解决了吗？查原因的话可以每个更新ui的方法之间都打下log看看输出时间，找到是哪个地方比较耗时，然后针对性的进行处理

**Comment by Greathfs** [comment]
@coolxtc 找到了一个方法,就是底部和右侧的控制界面不共存,暂时是解决了卡顿的问题了,但是感觉没有真正解决这个问题
