### ISSUE TITLE
在fragment中全屏后按返回键，activity也被finish掉了

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#653]
public boolean onBackPressed() {
        if (StandardGSYVideoPlayer.backFromWindowFull(getActivity())) {
            return true;
        }
        return false;
    }
全屏状态下 StandardGSYVideoPlayer.backFromWindowFull(getActivity())为false

**Comment by CarGuo** [comment]
你需要在activity级别处理分发返回按键事件
