### ISSUE TITLE
竖屏点击全屏后，再点击关闭全屏后，界面没有返回竖屏，是什么原因？

### ISSUE THREAD

**Issue by jlertele** [CarGuo/GSYVideoPlayer#655]
![image](https://user-images.githubusercontent.com/11385515/33765376-832d23d6-dc53-11e7-92fa-2bae0b3b200e.png)

**Comment by jlertele** [comment]
就是退出了全屏播放界面，显示了原来的界面，但界面的控件依旧是横屏显示，没有返回竖屏显示

**Comment by CarGuo** [comment]
参考demo中的，可能是config之类的

**Comment by jlertele** [comment]
找到原因了，是因为setNeedLockFull(true)了，thx

**Comment by jlertele** [comment]
另外必须设置setLockLand(true)，才能正确恢复竖屏状态

**Comment by CarGuo** [comment]
good
