### ISSUE TITLE
setDialogProgressColor函数无效，设置颜色后，触摸进度条的字体颜色依旧是蓝色

### ISSUE THREAD

**Issue by jlertele** [CarGuo/GSYVideoPlayer#657]
对demo中的播放器也设置过，也是没有改变触摸改变进度时，对应的进度时间的字体颜色。
查看源码似乎也没有什么特别的地方，难道是R.layout.video_progress_dialog的原因？

**Comment by jlertele** [comment]
找到原因了，是没有再全屏逻辑时，做自定义UI样式应用到全屏处理

**Comment by mrsongindezhou** [comment]
楼主怎么解决的，我也遇到了这个问题，给进度条设置颜色无效

**Comment by jlertele** [comment]
在切换全屏样式时，同时应用你的自定义样式
