### ISSUE TITLE
How do I separate resolution HLS video with this library?

### ISSUE THREAD

**Issue by mdtuyen** [CarGuo/GSYVideoPlayer#659]
I'm playing hls video with androi TV and it have feature map video with multiple track as 1080/720/480/audio....

As I see in Demo of Exoplayer I can debug to see it.

Please help me how to track it with this library.

**Comment by CarGuo** [comment]
you can get Real Player by `(IjkMediaPlayer) GSYVideoManager.instance().getMediaPlayer();`
or  `(IjkExoMediaPlayer) GSYVideoManager.instance().getMediaPlayer();`  

defualt type is IjkMediaPlayer

 `GSYVideoManager.instance().setVideoType()` change it

example:
IjkMediaPlayer had getTrackInfo() getSelectedTrack() selectTrack() deselectTrack() api
