### ISSUE TITLE
你好，请问对于m3u8 你是如何判断不进行的videocache缓存的？

### ISSUE THREAD

**Issue by XiaMengjian** [CarGuo/GSYVideoPlayer#66]
你好，请问对于m3u8 你是如何判断不进行的videocache缓存的,能指点一下吗，谢谢

**Comment by CarGuo** [comment]
这个外部判断，如果是m3u8，你就在setUp的时候设置cache为false

**Comment by XiaMengjian** [comment]
但是我的url 并不是真实的url，需要进行跳转后才会发现是m3u格式的

**Comment by CarGuo** [comment]
你给播放器的必须是流媒体链接
