### ISSUE TITLE
如何播放多段视频 手动拼接ffconcat 不管用

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#663]
具体步骤
添加引用     
compile 'com.shuyu:gsyVideoPlayer-java:2.1.1'
compile 'com.shuyu:gsyVideoPlayer-ex_so:2.1.1'
在demo PlayActivity 中
生成aaa.ffconcat 调用地址：file:///data/user/0/com.example.gsyvideoplayer/files/a.ffconcat
内容为：
`ffconcat version 1.0
file 'http://42.236.121.144/sohu/v1/Tms3TmwUTCCAqllTXwlZkUIMuTW1bAXvy24dbAfHqM14wmfcymcAr.mp4?k=UHmS7Y&p=XWPIWho70ScAZMoUoTWCr&r=TmI20LscWOo70Sc2ZDASqTPGRDetWYoioMycY&q=OpC7hW7IWJodRD64WhdSotE7ZD6XfJXsWJbHZYeHfhAsvmbcWJeOfhdXWDdSqD2sWO6SqF2sY&cip=182.124.85.191'
duration 300
file 'http://42.236.121.157/sohu/v1/TmXiTmPdqEIm0GWiuEfCW8bmWEdADEWDWEfdbSdF5m47fFoGRMNiNw.mp4?k=8aPcIf&p=XWPIWho70ScAZMoUoTWCr&r=TmI20LscWOo70Sc2ZDASqTPGRDetWYoioMycY&q=OpCAhW7IWJodRD64WhdSotE7ZD6XfJXsWJbHZYeHfhAsvmbcWJeOfhdXWDASqD2sWO6SqF2sY&cip=182.124.85.191'
duration 300
file 'http://42.236.121.150/sohu/v1/TmoBTmPGqAI20TEVTEd3y6W1yTC3gE42hVvIaJ6xABgXpxWsm3UtUw.mp4?k=gspkkY&p=XWPIWho70ScAZMoUoTWCr&r=TmI20LscWOo70Sc2ZDASqTPGRDetWYoioMycY&q=OpCUhW7IWJodRD64WhdSotE7ZD6XfJXsWJbHZYeHfhAsvmbcWJeOfhdXWDASqD2sWO6SqF2sY&cip=182.124.85.191'
duration 300`
无法播放 点击开始就暂停了，无法播放 ，具体多段视频怎么拼接呀
 视频网址 有时间限制，这里只是参考。

**Comment by yang0000meng** [comment]
duration 300 file  是单独一行。

**Comment by CarGuo** [comment]
使用的是exso么？

**Comment by yang0000meng** [comment]
谢谢回复。
实在官方的demo中  更改PlayActivity
添加引用
  //compile project(':gsyVideoPlayer')
    compile project(':gsyVideoPlayer-java')
    compile project(':gsyVideoPlayer-ex_so')
具体代码
`  source1="file:///data/user/0/com.example.gsyvideoplayer/files/a.ffconcat";
        String name = "普通";
        SwitchVideoModel switchVideoModel = new SwitchVideoModel(name, source1);

        List<SwitchVideoModel> list = new ArrayList<>();
        list.add(switchVideoModel);
        //list.add(switchVideoModel2);

        videoPlayer.setUp(list, false, "测试视频");`
日志怎么看呢？

**Comment by yang0000meng** [comment]
贴出全部日志吧
`12-13 07:25:38.042 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_release
12-13 07:25:38.043 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
12-13 07:25:38.043 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_surface()
12-13 07:25:38.043 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
12-13 07:25:38.043 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
12-13 07:25:38.043 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
12-13 07:25:38.043 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_dec_ref(): ref=0
12-13 07:25:38.044 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
12-13 07:25:38.044 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
12-13 07:25:38.046 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_native_setup
12-13 07:25:38.046 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170829--001
12-13 07:25:38.046 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: ijk_version_info: k0.8.1-62-ge1d04bd
12-13 07:25:38.046 5615-5615/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToPreparingShow
12-13 07:25:38.046 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_create_from_android()
12-13 07:25:38.047 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque(0x2007d2)
12-13 07:25:38.051 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque()=void
12-13 07:25:38.051 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x2007d2)
12-13 07:25:38.055 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
12-13 07:25:38.055 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
12-13 07:25:38.055 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
12-13 07:25:38.056 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
12-13 07:25:38.057 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
12-13 07:25:38.057 5615-6718/com.example.gsyvideoplayer V/IJKMEDIA: setDataSource: path file:///data/user/0/com.example.gsyvideoplayer/files/a.ffconcat
12-13 07:25:38.057 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="file:///data/user/0/com.example.gsyvideoplayer/files/a.ffconcat")
12-13 07:25:38.057 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="file:///data/user/0/com.example.gsyvideoplayer/files/a.ffconcat")=0
12-13 07:25:38.057 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
12-13 07:25:38.060 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setLoopCount
12-13 07:25:38.060 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(1)
12-13 07:25:38.060 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: moncleanup
12-13 07:25:38.060 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
12-13 07:25:38.060 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
12-13 07:25:38.061 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_volume
12-13 07:25:38.061 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
12-13 07:25:38.061 5615-6718/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-13 07:25:38.062 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_prepareAsync
12-13 07:25:38.062 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()
12-13 07:25:38.062 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: ===== versions =====
12-13 07:25:38.062 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: ijkplayer    : k0.8.1-62-ge1d04bd
12-13 07:25:38.062 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
12-13 07:25:38.062 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: libavutil    : 55.58.100
12-13 07:25:38.063 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: libavcodec   : 57.89.100
12-13 07:25:38.063 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: libavformat  : 57.71.100
12-13 07:25:38.063 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: libswscale   : 4.6.100
12-13 07:25:38.070 5615-6738/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [6738] ff_msg_loop
12-13 07:25:38.070 5615-6738/com.example.gsyvideoplayer D/IJKMEDIA: message_loop
12-13 07:25:38.070 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: libswresample: 2.7.100
12-13 07:25:38.070 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: ===== options =====
12-13 07:25:38.070 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: player-opts : loop                         = 1
12-13 07:25:38.070 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkapplication               = -1888298528
12-13 07:25:38.071 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkiomanager                 = -1880237312
12-13 07:25:38.074 5615-6718/com.example.gsyvideoplayer I/IJKMEDIA: ===================
12-13 07:25:38.074 5615-6738/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_FLUSH:
12-13 07:25:38.077 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()=0
12-13 07:25:38.086 5615-6740/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [6740] ff_vout
12-13 07:25:38.091 5615-6741/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [6741] ff_read
12-13 07:25:38.091 5615-6741/com.example.gsyvideoplayer D/IJKMEDIA: Setting default whitelist 'file,crypto'
12-13 07:25:38.093 5615-6741/com.example.gsyvideoplayer V/IJKMEDIA: Probing concat score:100 size:858
12-13 07:25:38.093 5615-6741/com.example.gsyvideoplayer D/IJKMEDIA: Format concat probed with size=2048 and score=100
12-13 07:25:38.093 5615-6741/com.example.gsyvideoplayer E/IJKMEDIA: Unsafe file name 'http://42.236.121.144/sohu/v1/Tms3TmwUTCCAqllTXwlZkUIMuTW1bAXvy24dbAfHqM14wmfcymcAr.mp4?k=eDGPuK&p=XWPIWho70ScAZMoUoTWCr&r=TmI20LscWOo70Sc2ZDASqTPGRDetWYoioMycY&q=OpC7hW7IWJodRD64WhdSotE7ZD6XfJXsWJbHZYeHfhAsvmbcWJeOfhAOfJvSqD2sWGASqF2sY&cip=182.124.85.191&a=.mp4'
12-13 07:25:38.101 5615-6718/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
12-13 07:25:38.102 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
12-13 07:25:38.102 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x8e732530)
12-13 07:25:38.102 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_surface()
12-13 07:25:38.102 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x8e732530)=void
12-13 07:25:38.110 5615-6741/com.example.gsyvideoplayer D/IJKMEDIA: Statistics: 858 bytes read, 0 seeks
12-13 07:25:38.110 5615-6741/com.example.gsyvideoplayer E/IJKMEDIA: file:///data/user/0/com.example.gsyvideoplayer/files/a.ffconcat: Operation not permitted
12-13 07:25:38.113 5615-6738/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
12-13 07:25:38.115 5615-6718/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
12-13 07:25:38.115 5615-6741/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6741]
12-13 07:25:38.181 5615-5615/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
12-13 07:25:38.181 5615-5615/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToError
12-13 07:25:38.182 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_release
12-13 07:25:38.182 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
12-13 07:25:38.182 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_surface()
12-13 07:25:38.182 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
12-13 07:25:38.182 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
12-13 07:25:38.183 5615-5615/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Againfile:///data/user/0/com.example.gsyvideoplayer/files/a.ffconcat
12-13 07:25:38.183 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: wait for read_tid
12-13 07:25:38.184 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: wait for video_refresh_tid
12-13 07:25:38.184 5615-6738/com.example.gsyvideoplayer D/IJKMEDIA: message_loop exit
12-13 07:25:38.184 5615-6738/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6738]
12-13 07:25:38.192 5615-6740/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6740]
12-13 07:25:38.194 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
12-13 07:25:38.195 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_dec_ref(): ref=0
12-13 07:25:38.195 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
12-13 07:25:38.195 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
12-13 07:25:38.195 5615-6718/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
12-13 07:25:38.196 5615-6718/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
12-13 07:25:39.863 1302-1335/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 3040202 , only wrote 2888640
12-13 07:27:48.727 1318-1318/? I/perfprofd: profile collection skipped (running in emulator)`

**Comment by CarGuo** [comment]
试试在开始播放前设置
```
VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,"safe",0);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

**Comment by yang0000meng** [comment]
添加 VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,"safe",0); 

又报以下错误
12-13 09:00:50.797 12936-13320/com.example.gsyvideoplayer E/IJKMEDIA: ffconcat:///data/user/0/com.example.gsyvideoplayer/files/a.ffconcat: Protocol not found
查询说是协议不受支持， 在官方demo中添加以下引用
//compile project(':gsyVideoPlayer')
    compile project(':gsyVideoPlayer-java')
    compile project(':gsyVideoPlayer-ex_so')

这样不就支持了吗

换成 concat:///data/user/0/com.example.gsyvideoplayer/files/a.concat 同样报: Protocol not found错误

**Comment by CarGuo** [comment]
开头的协议有问题吧，你这是本地文件

**Comment by yang0000meng** [comment]
[https://github.com/Bilibili/ijkplayer/issues/211](url) 协议不是这个吗？ 
例如这个是文件地址
/data/user/0/com.example.gsyvideoplayer/files/a.ffconcat
这个是具体内容
ffconcat version 1.0
file 'http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4'
duration 300
file 'http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4'
duration 300
file 'http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4'
duration 300

添加引用
  compile 'com.shuyu:gsyVideoPlayer-java:2.1.1'
    compile 'com.shuyu:gsyVideoPlayer-ex_so:2.1.1'

实现代码
	String source1="file:///data/user/0/com.example.gsyvideoplayer/files/a.ffconcat";
        String name = "普通";
        SwitchVideoModel switchVideoModel = new SwitchVideoModel(name, source1);

        List<SwitchVideoModel> list = new ArrayList<>();
        list.add(switchVideoModel);

        List<VideoOptionModel> listVideoOptionModel = new ArrayList<>();
        VideoOptionModel videoOptionModel =  new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT,"safe",0);
        listVideoOptionModel.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(listVideoOptionModel);
        videoPlayer.setUp(list, false, "测试视频");
这哪里不对呀，能否给个例子，总是不正确

这个代码报这个错误
12-13 10:08:58.754 1205-1752/com.example.gsyvideoplayer E/IJKMEDIA: Protocol 'http' not on whitelist 'file,crypto'!
12-13 10:08:58.756 1205-1752/com.example.gsyvideoplayer E/IJKMEDIA: Impossible to open 'http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4'
12-13 10:08:58.756 1205-1752/com.example.gsyvideoplayer D/IJKMEDIA: Statistics: 664 bytes read, 0 seeks
12-13 10:08:58.756 1205-1752/com.example.gsyvideoplayer E/IJKMEDIA: file:///data/user/0/com.example.gsyvideoplayer/files/aa.ffconcat: Invalid argument
12-13 10:08:58.756 1205-1750/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
12-13 10:08:58.757 1205-1713/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by yang0000meng** [comment]
VideoOptionModel videoOptionModel2 =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto");
       再添加个这就好了，唉，送算可以了

**Comment by yang0000meng** [comment]
ffconcat version 1.0
file 'http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4'
duration 308
file 'http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4'
duration 308
file 'http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4'
duration 308

播放这个每次到3分多就会跳转下一段视频。

**Comment by maolubin** [comment]
@yang0000meng 帅哥解决了吗，求教育

**Comment by yang0000meng** [comment]
@maolubin  可以了 https://github.com/Bilibili/ijkplayer/issues/490 看这个  记得添加这个VideoOptionModel videoOptionModel2 =
new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto");

**Comment by renwfy** [comment]
@yang0000meng ,能贴一段代码吗，你播放之前的设置

**Comment by renwfy** [comment]
这个是我的错误提示：

07-16 11:22:58.341 22139-22389/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-16 11:22:58.341 22139-22389/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_prepareAsync
    ijkmp_prepare_async()
07-16 11:22:58.341 22139-22389/com.example.gsyvideoplayer I/IJKMEDIA: ===== versions =====
    ijkplayer    : k0.8.8
    FFmpeg       : ff3.4--ijk0.8.7--20180103--001
    libavutil    : 55.78.100
    libavcodec   : 57.107.100
    libavformat  : 57.83.100
    libswscale   : 4.8.100
    libswresample: 2.9.100
    ===== options =====
    player-opts : loop                         = 1
    format-opts : ijkapplication               = 2022153344
    format-opts : ijkiomanager                 = 1998416272
    format-opts : protocol_whitelist           = rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto
    ===================
07-16 11:22:58.351 22139-22660/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [22660] ff_msg_loop
07-16 11:22:58.351 22139-22660/com.example.gsyvideoplayer D/IJKMEDIA: message_loop
07-16 11:22:58.351 22139-22389/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()=0
07-16 11:22:58.351 22139-22660/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_FLUSH:
07-16 11:22:58.351 22139-22663/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [22663] ff_read
07-16 11:22:58.351 22139-22663/com.example.gsyvideoplayer D/IJKMEDIA: Opening '/storage/emulated/0/GSYVideo/TT/aa.ffconcat' for reading
07-16 11:22:58.351 22139-22663/com.example.gsyvideoplayer V/IJKMEDIA: Probing concat score:100 size:305
07-16 11:22:58.351 22139-22663/com.example.gsyvideoplayer D/IJKMEDIA: Format concat probed with size=2048 and score=100
07-16 11:22:58.351 22139-22663/com.example.gsyvideoplayer E/IJKMEDIA: Unsafe file name 'http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4'
07-16 11:22:58.351 22139-22663/com.example.gsyvideoplayer D/IJKMEDIA: Statistics: 305 bytes read, 0 seeks
07-16 11:22:58.351 22139-22663/com.example.gsyvideoplayer E/IJKMEDIA: /storage/emulated/0/GSYVideo/TT/aa.ffconcat: Operation not permitted
07-16 11:22:58.351 22139-22660/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
07-16 11:22:58.351 22139-22389/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
07-16 11:22:58.351 22139-22663/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [22663]
07-16 11:22:58.351 22139-22662/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [22662] ff_vout
07-16 11:22:58.361 22139-22139/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
07-16 11:22:58.361 22139-22389/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_release
    ijkmp_set_android_surface(surface=0x0)
    ffpipeline_set_surface()
    ijkmp_set_android_surface(surface=0x0)=void
    ijkmp_shutdown_l()
07-16 11:22:58.361 22139-22660/com.example.gsyvideoplayer D/IJKMEDIA: message_loop exit
07-16 11:22:58.361 22139-22660/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [22660]
07-16 11:22:58.361 22139-22389/com.example.gsyvideoplayer D/IJKMEDIA: wait for read_tid
    wait for video_refresh_tid
07-16 11:22:58.361 22139-22139/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToError
07-16 11:22:58.361 22139-22139/com.example.gsyvideoplayer E/GSYVideoPlayer: Play Error /storage/emulated/0/GSYVideo/TT/aa.ffconcat
07-16 11:22:58.361 22139-22662/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [22662]
07-16 11:22:58.361 22139-22389/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
    ijkmp_dec_ref(): ref=0
    ijkmp_shutdown_l()
    ijkmp_shutdown_l()=void
07-16 11:22:58.361 22139-22139/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Again /storage/emulated/0/GSYVideo/TT/aa.ffconcat
    mCache Link /storage/emulated/0/GSYVideo/TT/aa.ffconcat
07-16 11:22:58.361 22139-22389/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
07-16 11:22:58.361 22139-22389/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by yang0000meng** [comment]
@renwfy  增加 这个
初始化基本参考demo  https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailADPlayer.java
1.记得添加这个VideoOptionModel videoOptionModel2 =
new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto");
2.把组合内容 保持   aaa.concat 
3.路径传给播放器，就行了。
大体就这样。
代码好多类 不方便贴。

**Comment by AndSync** [comment]
个人总结一下 首先和Demo中PlayActivity关系不大并且这个还有一点误导性，这个里面把几个url添加到了一个列表中
````
List<SwitchVideoModel> list = new ArrayList<>();
        list.add(switchVideoModel);
        list.add(switchVideoModel2);
````
这是为了切换清晰度用的 可以看setUp代码里面还是取的其中某一个url，我们需要做的是传给播放器一个contact格式的url，让他播放就行
因此来讲我们要做的是
1、把分段视频信息写入文件xxx.concat 名字随意，这里感觉duration应该弄成小数，误差会小一点
````
ffconcat version 1.0
file 'file:///storage/emulated/0/test_live_recoder.mp4'
duration 20.3
file 'file:///storage/emulated/0/test_live_recoder1.mp4'
duration 4.4
file 'file:///storage/emulated/0/test_live_recoder2.mp4'
duration 1
````
2、注意上面的文件路径，最终传递给播放器的格式如下
````
file:///storage/emulated/0/xxx.concat
````
3、在初始化播放器时候加上代码
````
 List<VideoOptionModel> listVideoOptionModel = new ArrayList<>();
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "safe", 0);
        VideoOptionModel videoOptionModel2 =
            new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist",
                "rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto");
        listVideoOptionModel.add(videoOptionModel);
        listVideoOptionModel.add(videoOptionModel2);
        GSYVideoManager.instance().setOptionModelList(listVideoOptionModel);
````
可以贴一个完整版的初始化代码
````
private void initVideoPlayer() {
        //增加封面
        ImageView imageView = new ImageView(this);
        imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
        imageView.setImageResource(R.mipmap.img_load_default);

        //增加title
        detailPlayer.getTitleTextView().setVisibility(View.GONE);
        detailPlayer.getBackButton().setVisibility(View.GONE);

        //外部辅助的旋转，帮助全屏
        orientationUtils = new OrientationUtils(this, detailPlayer);
        //初始化不打开外部的旋转
        orientationUtils.setEnable(false);

        List<VideoOptionModel> listVideoOptionModel = new ArrayList<>();
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "safe", 0);
        VideoOptionModel videoOptionModel2 =
            new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist",
                "rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto");
        listVideoOptionModel.add(videoOptionModel);
        listVideoOptionModel.add(videoOptionModel2);
        GSYVideoManager.instance().setOptionModelList(listVideoOptionModel);

        GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder();
        gsyVideoOption.setIsTouchWiget(true)
            .setRotateViewAuto(false)
            .setLockLand(false)
            .setAutoFullWithSize(true)
            .setShowFullAnimation(false)
            .setNeedLockFull(true)
            .setUrl(concatPath)
            .setCacheWithPlay(true)
            .setVideoAllCallBack(new GSYSampleCallBack() {
                @Override
                public void onPrepared(String url, Object... objects) {
                    super.onPrepared(url, objects);
                    //开始播放了才能旋转和全屏
                    orientationUtils.setEnable(true);
                    isPlay = true;
                }

                @Override
                public void onQuitFullscreen(String url, Object... objects) {
                    super.onQuitFullscreen(url, objects);
                    if (orientationUtils != null) {
                        orientationUtils.backToProtVideo();
                    }
                }
            })
            .setLockClickListener(new LockClickListener() {
                @Override
                public void onClick(View view, boolean lock) {
                    if (orientationUtils != null) {
                        //配合下方的onConfigurationChanged
                        orientationUtils.setEnable(!lock);
                    }
                }
            })
            .build(detailPlayer);

        detailPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //直接横屏
                orientationUtils.resolveByClick();
                //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
                detailPlayer.startWindowFullscreen(context, true, true);
            }
        });
        detailPlayer.startPlayLogic();
    }
````

**Comment by AndSync** [comment]
本人遇到的问题 不同来源的视频 放在一起播放的时候
1、后面视频会变慢，可能帧率不一样
2、部分视频方向会发生旋转
3、有些视频无法播放（手机上可以播放），如ffmpeg将图片转成的视频
不知道如何解决 有没有相关的要求？ 比如要统一帧率 、分辨率等等

**Comment by yang0000meng** [comment]
我记得介绍要求 分段视频格式必须统一
问题2是不是开启了视频自动旋转功能。
问题3 引入方法是否支持其他格式
支持其他格式协议的（mpeg，rtsp, concat、crypto协议）
A、B普通版本支持263/264/265等，对于mpeg编码会有声音无画面情况。 C 引入的so支持mpeg编码和其他补充协议，但是so包相对变大。

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

//是否需要ExoPlayer模式
implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'

//更多ijk的编码支持
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

**Comment by 125L** [comment]
**@AndSync**

合并多个播放地址，按照你的方法可以正常播放。但是对于防盗链的视频地址，无法进行合并播放，请问有解决办法吗。加入header也不行。单个视频地址防盗链也可以正常播放。用了合并防盗链视频就不能播放了。
