### ISSUE TITLE
avi格式视频，获取的视频总时长为0

### ISSUE THREAD

**Issue by xuefengyuan** [CarGuo/GSYVideoPlayer#664]
GSYVdieoView源码中的，这里获取出来的为0，没有异常
/**
     * 获取当前总时长
     */
    public int getDuration() {
        int duration = 0;
        try {
            duration = (int) GSYVideoManager.instance().getMediaPlayer().getDuration();
        } catch (IllegalStateException e) {
            e.printStackTrace();
            return duration;
        }
        return duration;
    }
总时长为0，导致进度条一进来就加载完了。

**Comment by CarGuo** [comment]
如果是未prepared的或者暂停中的，有可能获取出来为0

**Comment by xuefengyuan** [comment]
就是播放中的状态，打日志出来，总时长也返回的是0.播放进度时间是正常的。

**Comment by CarGuo** [comment]
有测试url？

**Comment by xuefengyuan** [comment]
http://av.hanfugou.com/video/android/2017/11/12/adcbbe0725b04f44820be43ae7e3ab4d.avi
这是测试的URL时长比较短只有11秒

**Comment by CarGuo** [comment]
```
I/IJKMEDIA: Input #0, m4v, from '/storage/emulated/0/GSYVideo/22222.avi':
I/IJKMEDIA:   Duration: 
I/IJKMEDIA: N/A
I/IJKMEDIA: , start: 
I/IJKMEDIA: 0.000000
I/IJKMEDIA: , bitrate: 
I/IJKMEDIA: N/A
I/IJKMEDIA:     Stream #0:0
I/IJKMEDIA: : Video: mpeg4, 1 reference frame, yuv420p(left), 640x352 [SAR 1:1 DAR 20:11], 0/1
I/IJKMEDIA: , 
I/IJKMEDIA: 23 tbr, 
I/IJKMEDIA: 1200k tbn, 
I/IJKMEDIA: 23 tbc
I/IJKMEDIA: VideoCodec: avcodec, mpeg4
W/IJKMEDIA: fps: 23.000000 (normal)
I/IJKMEDIA: SDL_RunThread: [8593] ff_video_dec
```

从ffmpeg解码出来的信息看，确实如此，看起来是这个视频编码的问题

**Comment by xuefengyuan** [comment]
那我再找别的视频资源看下，有后续问题我再补充

**Comment by xuefengyuan** [comment]
测试了几个.avi格式的视频，都是获取不到视频总时长，可以考虑添加一个设置总时长的方法么？

**Comment by CarGuo** [comment]
我想起来了，avi的容器协议当前so没支持，之所以能播放是因为视频编码是mpeg4的，所以解析出来了，但是avi协议没正确解析，你可以看看根目录的两个.sh文件，应该是没有

--enable-demuxer=avi"

**Comment by xuefengyuan** [comment]
是没有，我现在直接用的源码引用了，加了个设置视频总时长的方法。因为我的是自己服务器有返回总时长，所以添加这个方法后就可以不用走下面了。
后续可以把avi格式的协议加上哈。

**Comment by xuefengyuan** [comment]
郭神，现在的SO库播放AVI格式的声音也没有，只有画面

**Comment by CarGuo** [comment]
主要还是如果你需要avi的容器协议，还是需要打包包含avi的so

**Comment by xuefengyuan** [comment]
包含avi格式的so，自己拿你开源的配置，添加了avi的配置，出来的包是只有声音，没有图像。
# ./configure --list-demuxers
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-demuxers"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=aac"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=concat"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=data"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=flv"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=hls"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=latm"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=live_flv"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=loas"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=m4v"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mov"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mp3"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mpegps"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mpegts"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mpegvideo"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=hevc"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=avi"
只在这下面添加了avi支持

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite-more.sh  这个配置上

**Comment by xuefengyuan** [comment]
好的，有时间再打包测试下了，现在用的是module-defalut的配置，打出来的包有点大了。
