### ISSUE TITLE
编译时没有报错,但是已运行就会报下面这个错

### ISSUE THREAD

**Issue by Rose-cwy** [CarGuo/GSYVideoPlayer#665]
Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libijkplayer.so'

**Comment by CarGuo** [comment]
你依赖的是哪些？？？

**Comment by Rose-cwy** [comment]
完整版引入

**Comment by CarGuo** [comment]
可以贴出你引用的代码吗？写了看起来是ijk的引用重复了。

**Comment by Rose-cwy** [comment]
应该是引用重复了,再新的Demo里就好了
