### ISSUE TITLE
为什么同样的视频比例，其中有的会被拉伸呢？

### ISSUE THREAD

**Issue by gaoshan12312** [CarGuo/GSYVideoPlayer#666]
http://video.7k.cn/app_video/20171202/6c8cf3ea/v.m3u8.mp4，
http://video.7k.cn/app_video/20171213/276d8195/v.m3u8.mp4。
这两个视频地址，是放在recycleview上的，第一个正常显示，第二个为什么把视频拉伸横向播放了呢？

**Comment by CarGuo** [comment]
http://video.7k.cn/app_video/20171202/6c8cf3ea/v.m3u8.mp4


 Video: h264, 1 reference frame (avc1 / 0x31637661), yuv420p(left), 606x1080 (608x1088) [SAR 405:404 DAR 9:16], 0/1, 88 kb/s


http://video.7k.cn/app_video/20171213/276d8195/v.m3u8.mp4  


Video: h264, 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1920x1080 (1920x1088) [SAR 37:117 DAR 592:1053], 0/1, 1811 kb/s

第二个视频解析出来的宽高是横屏的

**Comment by gaoshan12312** [comment]
那第二个视频可以实现像第一个视频的那种播放效果呢，因为第二个视频地址在浏览器上播放，是按竖向播放的。

**Comment by CarGuo** [comment]
这个是由ffmpeg解析出来的大小，只能说源问题。

**Comment by may7be** [comment]
> 这个是由ffmpeg解析出来的大小，只能说源问题。

@CarGuo 即使是源url的宽高有问题，能不能像systemManager正常播放，而不被拉伸和裁剪？
