### ISSUE TITLE
m3u8 内部片段 重定向是否支持

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#668]
例如 m3u8片段里一个：
#EXTINF:8,
http://dx.data.video.qiyi.com/videos/v0/20171128/74/cf/9e654ea7adb705bd4523f15cda19c3a5.ts?qdv=1&qypid=852367200_04022000001000000000_4&start=0&end=3370476&hsize=38666&tag=0&v=&contentlength=2261452&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1513245152508&qd_ip=2ae7f121&qd_p=2ae7f121&qd_k=0c79a0d2d980d636b17c1e0254c5b4b9&qd_sc=facc34af1027727a51b00a9c0bc42f24

打开后http 头里有重定向 
Location: http://61.240.130.132/videos/v0/20171128/74/cf/9e654ea7adb705bd4523f15cda19c3a5.ts?dis_k=0508fee7675edb30a31483b0d174f35df&dis_t=1513245152&dis_dz=CNC-HeNan&dis_st=43&src=iqiyi.com&uuid=iloveiqiyi&z=zhengzhou6_cnc&end=3370476&qd_k=0c79a0d2d980d636b17c1e0254c5b4b9&tag=0&contentlength=2261452&v=&qd_p=2ae7f121&qd_ip=2ae7f121&start=0&qd_vip=0&qypid=852367200_04022000001000000000_4&qd_src=3_31_312&hsize=38666&qd_uid=&qdv=1&qd_tm=1513245152508
这样才是正确的地址 
请问如何修改可以支持这种方式呢

**Comment by CarGuo** [comment]
普通http是支持的，但是m3u8内部解析出来的不确定
