### ISSUE TITLE
播放视频源指定大小部分

### ISSUE THREAD

**Issue by tigericon** [CarGuo/GSYVideoPlayer#669]
我有一个视频源是由两个1280×720组成的，就是1280×1440的数据  ，我现在想分为上下两个1280×720的视频播放，请问有什么思路？

**Comment by CarGuo** [comment]
不是很理解

**Comment by tigericon** [comment]
我自己做出来了  就是openGL 修改顶点  显示视频的一半

**Comment by ail36413** [comment]
> 我自己做出来了 就是openGL 修改顶点 显示视频的一半

如何实现的？方便说下吗。
