### ISSUE TITLE
这个播放器支持rtmp 断线重连吗？

### ISSUE THREAD

**Issue by CodeBreadha** [CarGuo/GSYVideoPlayer#67]
请问，这个播放器支持rtmp 断线重连吗，或者ijkplayer 本身支持吗，如果要支持，我们需要调哪个接口？

**Comment by bruceshu** [comment]
同问，我了解到ijkplayer是不支持断网重连的，如果要做断网重连，请问如何检测播放器未收到流信息？

**Comment by CarGuo** [comment]
ijk是不支持的，断网重连的话，你需要在断网的时候，或者error的时候，记录下当前的getCurrentPositionWhenPlaying保存下位置，然后在重新播放之前setSeekOnStart

**Comment by mejealousy** [comment]
你好，请问，我看到 error 回调方法被触发时，返回的 code 是 -10000，但是看 ijkplayer 的作者说这并不能代表什么，
https://github.com/Bilibili/ijkplayer/issues/1309，所以是只能在 error 时，自己再去检测网络状态了吗？然后记录下当前的getCurrentPositionWhenPlaying保存下位置，然后在重新播放之前setSeekOnStart

**Comment by mejealousy** [comment]
你好，error 方法回调时返回的 code，为什么没有通过 onPlayError 方法传递出来？这样设计是考虑到什么吗？

**Comment by mejealousy** [comment]
@CarGuo 
你好，error 方法回调时返回的 code，为什么没有通过 onPlayError 方法传递出来？这样设计是考虑到什么吗？

**Comment by bruceshu** [comment]
@CarGuo 如果是直播呢，断网恢复后，只需要调用openVideo重新初始化播放器就可以吗？

**Comment by CarGuo** [comment]
断线之后，如果需要继续播放，需要重新创建播放器，对应的其实就是startPlayLogic
