### ISSUE TITLE
Detail模式未加载完成返回后没有停止加载任务

### ISSUE THREAD

**Issue by RamboPan** [CarGuo/GSYVideoPlayer#672]
点击Detail模式，点击播放，在未加载好点击返回时，没有停止加载，回主界面能听到之前视频加载好的声音，感觉返回没有释放掉之前的资源吧。

**Comment by CarGuo** [comment]
demo中？？？
调用了释放没？

**Comment by CarGuo** [comment]
fix 2.1.2

**Comment by RamboPan** [comment]
前两天忙着打杂，忘了回。
没有看完你的源码，不知道你退出Activity的时候有没有一个通用的设置调用释放。
我新手一般都是做在虚拟返回按键上。-_-！
