### ISSUE TITLE
HttpUrlSource如何替换成OkHttpUrlSource 

### ISSUE THREAD

**Issue by weiyf** [CarGuo/GSYVideoPlayer#673]
GSYVideoManager.instance().setProxy(HttpProxyCacheServer->HttpProxyCacheServerClients->HttpProxyCache->HttpUrlSource)

只能一个一个重写？

**Comment by CarGuo** [comment]
Manager有` setProxy `接口

**Comment by CarGuo** [comment]
你实现一个自己的proxy，默认setup之前调用设置自己的可以
