### ISSUE TITLE
怎么让播放器播放时跳转到其他Activity又返回后继续之前的播放？

### ISSUE THREAD

**Issue by lingchen52** [CarGuo/GSYVideoPlayer#675]
我正在activity A看视频,突然接收到一条消息跳转到了activity B,过了几分钟finish掉activity B回到了activity A,怎么让视频继续从之前暂停的位置继续播放？我的处理代码如下
`
 @Override
    protected void onPause() {
        super.onPause();
        whenPlaying = mStandardGSYVideoPlayer.getCurrentPositionWhenPlaying();
        if(mStandardGSYVideoPlayer.getCurrentState() == GSYVideoPlayer.CURRENT_STATE_PLAYING){
            mStandardGSYVideoPlayer.onVideoPause();
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
//        if(mStandardGSYVideoPlayer.getCurrentState() == GSYVideoPlayer.CURRENT_STATE_PAUSE){
//        mStandardGSYVideoPlayer.setUp(url, false, null, "");
//        mStandardGSYVideoPlayer.setPlayPosition(playPosition);
        mStandardGSYVideoPlayer.seekTo(whenPlaying);
        mStandardGSYVideoPlayer.startPlayLogic();
//            mStandardGSYVideoPlayer.onVideoResume();
//        }
    }

    private static int playPosition = 0;
    private static int whenPlaying = 0;

    @Override
    protected void onStop() {
        super.onStop();
        whenPlaying = mStandardGSYVideoPlayer.getCurrentPositionWhenPlaying();
//        playPosition = mStandardGSYVideoPlayer.getPlayPosition();
//        if(mStandardGSYVideoPlayer.getCurrentState() == GSYVideoPlayer.CURRENT_STATE_PLAYING){
            mStandardGSYVideoPlayer.onVideoPause();
//        }
    }

    @Override
    protected void onDestroy() {
        mStandardGSYVideoPlayer.release();
        upload();
        super.onDestroy();
    }`
但这么处理没啥用，返回后黑屏

**Comment by CarGuo** [comment]
onstop可以不用，只用设置onresume和onpause，参考demo

**Comment by lingchen52** [comment]
我试过只用onresume和onpause，还是不行

**Comment by lingchen52** [comment]
改成这样也没用
`    @Override
    protected void onPause() {
        super.onPause();
        mStandardGSYVideoPlayer.onVideoPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mStandardGSYVideoPlayer.onVideoResume();
    }

    @Override
    protected void onStop() {
        super.onStop();
    }

    @Override
    protected void onDestroy() {
        mStandardGSYVideoPlayer.release();
        upload();
        super.onDestroy();
    }`
我跳转到activity B也是在播放视频，返回时activity A显示的是暂停状态，但我点播放按钮就一直在加载播放不出来

**Comment by CarGuo** [comment]
不是很清楚具体的原因，你可以参考demo 的DetailControlActivity

**Comment by lingchen52** [comment]
我打算换一种思路来处理，在跳转到activity B时记录下当前播放位置，返回时重新初始化播放器，再seek到之前记录的位置播放，seekTo()怎么用我还不清楚，望指点

**Comment by CarGuo** [comment]
不需要重新初始化，demo中的DetailControlActivity里不是就带有跳转暂停返回播放吗？

**Comment by lingchen52** [comment]
没看到啊

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/DetailControlActivity.java   

```
jump.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                JumpUtils.gotoControl(DetailControlActivity.this);
                //startActivity(new Intent(DetailControlActivity.this, MainActivity.class));
            }
        });
```
你运行下demo就可以看到效果，这里的Activity继承了`GSYBaseActivityDetail `，看下源码就知道OnPause和OnResume的实现

**Comment by lingchen52** [comment]
看了源码，但为啥我直接用下面这段代码没作用呢
` @Override
    protected void onPause() {
        super.onPause();
        mStandardGSYVideoPlayer.onVideoPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mStandardGSYVideoPlayer.onVideoResume();
    }`

**Comment by CarGuo** [comment]
这就不清楚了，我只能说参考demo实现😂

**Comment by lingchen52** [comment]
这是日志
12-19 17:17:57.392 18954-19128/com.iptv.dmm I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
12-19 17:17:57.392 18954-19128/com.iptv.dmm D/IJKMEDIA: Continuity check failed for pid 0 expected 3 got 2
12-19 17:17:57.392 18954-19128/com.iptv.dmm D/IJKMEDIA: Continuity check failed for pid 260 expected 3 got 2
12-19 17:17:57.688 18954-18954/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
12-19 17:17:57.688 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
12-19 17:17:57.688 18954-18954/com.iptv.dmm D/IJKMEDIA: ffpipeline_set_surface()
12-19 17:17:57.688 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
12-19 17:17:57.712 18954-19127/com.iptv.dmm W/IJKMEDIA: func_display_overlay_l: NULL native_window
12-19 17:17:58.004 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_stop()
12-19 17:17:58.004 18954-19126/com.iptv.dmm D/IJKMEDIA: message_loop exit
12-19 17:17:58.004 18954-19126/com.iptv.dmm I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19126]
12-19 17:17:58.004 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_stop()=0
12-19 17:17:58.004 18954-18954/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_release
12-19 17:17:58.004 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
12-19 17:17:58.004 18954-18954/com.iptv.dmm D/IJKMEDIA: ffpipeline_set_surface()
12-19 17:17:58.004 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
12-19 17:17:58.004 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_shutdown_l()
12-19 17:17:58.004 18954-18954/com.iptv.dmm D/IJKMEDIA: wait for read_tid
12-19 17:17:58.004 18954-19128/com.iptv.dmm I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19128]
12-19 17:17:58.004 18954-19132/com.iptv.dmm I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19132]
12-19 17:17:58.012 18954-19127/com.iptv.dmm I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19127]
12-19 17:17:58.012 18954-19131/com.iptv.dmm I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19131]
12-19 17:17:58.012 18954-19138/com.iptv.dmm I/IJKMEDIA: convert image convert_frame_count = 0
12-19 17:17:58.012 18954-19138/com.iptv.dmm I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19138]
12-19 17:17:58.016 18954-18954/com.iptv.dmm D/IJKMEDIA: Statistics: 1095312 bytes read, 0 seeks
12-19 17:17:58.016 18954-18954/com.iptv.dmm D/IJKMEDIA: Statistics: 400 bytes read, 0 seeks
12-19 17:17:58.016 18954-18954/com.iptv.dmm D/IJKMEDIA: wait for video_refresh_tid
12-19 17:17:58.016 18954-18954/com.iptv.dmm E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb94ab690)
12-19 17:17:58.016 18954-18954/com.iptv.dmm E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb8e129e0)
12-19 17:17:58.016 18954-18954/com.iptv.dmm E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb8de5880)
12-19 17:17:58.016 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_shutdown_l()=void
12-19 17:17:58.016 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_dec_ref(): ref=0
12-19 17:17:58.016 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_shutdown_l()
12-19 17:17:58.016 18954-18954/com.iptv.dmm D/IJKMEDIA: ijkmp_shutdown_l()=void
12-19 17:18:07.568 18954-18983/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_native_finalize
12-19 17:18:07.568 18954-18983/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_release
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_release
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_native_setup
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170829--001
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: ijk_version_info: 
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ffpipeline_create_from_android()
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d40050a)
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_inject_opaque()=void
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x1d40050a)
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setOptionLong
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setOptionLong
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setOptionLong
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
12-19 17:18:43.284 18954-19046/com.iptv.dmm V/IJKMEDIA: setDataSource: path http://192.168.1.109:9080/stream/vod/行星地球二01.mp4
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_data_source(url="http://192.168.1.109:9080/stream/vod/行星地球二01.mp4")
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_data_source(url="http://192.168.1.109:9080/stream/vod/行星地球二01.mp4")=0
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setOptionLong
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setLoopCount
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(1)
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: moncleanup
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setVolume
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ffpipeline_set_volume
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
12-19 17:18:43.284 18954-19046/com.iptv.dmm W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_prepareAsync
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_prepare_async()
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: ===== versions =====
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: ijkplayer    : 
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: libavutil    : 55.58.100
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: libavcodec   : 57.89.100
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: libavformat  : 57.71.100
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: libswscale   : 4.6.100
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: libswresample: 2.7.100
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: ===== options =====
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: player-opts : mediacodec                   = 1
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: player-opts : mediacodec-auto-rotate       = 1
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: player-opts : mediacodec-handle-resolution-change = 1
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: player-opts : loop                         = 1
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: format-opts : ijkapplication               = -1194957440
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: format-opts : ijkiomanager                 = -1193298016
12-19 17:18:43.284 18954-19046/com.iptv.dmm I/IJKMEDIA: ===================
12-19 17:18:43.284 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_prepare_async()=0
12-19 17:18:43.284 18954-19159/com.iptv.dmm I/IJKMEDIA: SDL_RunThread: [19159] ff_read
12-19 17:18:43.284 18954-19159/com.iptv.dmm D/IJKMEDIA: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
12-19 17:18:43.284 18954-19159/com.iptv.dmm I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
12-19 17:18:43.284 18954-19159/com.iptv.dmm I/IJKMEDIA: Hit DNS cache hostname = 192.168.1.109
12-19 17:18:43.284 18954-19159/com.iptv.dmm I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
12-19 17:18:43.284 18954-19158/com.iptv.dmm I/IJKMEDIA: SDL_RunThread: [19158] ff_vout
12-19 17:18:43.284 18954-19157/com.iptv.dmm I/IJKMEDIA: SDL_RunThread: [19157] ff_msg_loop
12-19 17:18:43.284 18954-19157/com.iptv.dmm D/IJKMEDIA: message_loop
12-19 17:18:43.284 18954-19157/com.iptv.dmm D/IJKMEDIA: FFP_MSG_FLUSH:
12-19 17:18:43.292 18954-19159/com.iptv.dmm I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
12-19 17:18:43.292 18954-19159/com.iptv.dmm D/IJKMEDIA: request: GET /stream/vod/行星地球二01.mp4 HTTP/1.1
                                                        User-Agent: Lavf/57.71.100
                                                        Accept: */*
                                                        Range: bytes=0-
                                                        Connection: close
                                                        Host: 192.168.1.109:9080
                                                        Icy-MetaData: 1
12-19 17:18:43.292 18954-18983/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_native_finalize
12-19 17:18:43.292 18954-18983/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_release
12-19 17:18:43.296 18954-19046/com.iptv.dmm W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
12-19 17:18:43.296 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
12-19 17:18:43.296 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_android_surface(surface=0x1e800005)
12-19 17:18:43.296 18954-19046/com.iptv.dmm D/IJKMEDIA: ffpipeline_set_surface()
12-19 17:18:43.296 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_android_surface(surface=0x1e800005)=void
12-19 17:19:43.336 18954-19159/com.iptv.dmm I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
12-19 17:19:43.336 18954-19159/com.iptv.dmm E/IJKMEDIA: http://192.168.1.109:9080/stream/vod/行星地球二01.mp4: End of file
12-19 17:19:43.336 18954-19159/com.iptv.dmm I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19159]
12-19 17:19:43.336 18954-19157/com.iptv.dmm D/IJKMEDIA: FFP_MSG_ERROR: 0
12-19 17:19:43.336 18954-19046/com.iptv.dmm E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
12-19 17:19:43.352 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_release
12-19 17:19:43.352 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
12-19 17:19:43.352 18954-19046/com.iptv.dmm D/IJKMEDIA: ffpipeline_set_surface()
12-19 17:19:43.352 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
12-19 17:19:43.352 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_shutdown_l()
12-19 17:19:43.352 18954-19046/com.iptv.dmm D/IJKMEDIA: wait for read_tid
12-19 17:19:43.352 18954-19046/com.iptv.dmm D/IJKMEDIA: wait for video_refresh_tid
12-19 17:19:43.352 18954-19157/com.iptv.dmm D/IJKMEDIA: message_loop exit
12-19 17:19:43.352 18954-19157/com.iptv.dmm I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19157]
12-19 17:19:43.356 18954-19158/com.iptv.dmm I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19158]
12-19 17:19:43.356 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_shutdown_l()=void
12-19 17:19:43.356 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_dec_ref(): ref=0
12-19 17:19:43.356 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_shutdown_l()
12-19 17:19:43.356 18954-19046/com.iptv.dmm D/IJKMEDIA: ijkmp_shutdown_l()=void
12-19 17:19:43.360 18954-19046/com.iptv.dmm D/IJKMEDIA: IjkMediaPlayer_setVolume
