### ISSUE TITLE
感觉卡

### ISSUE THREAD

**Issue by kuangzhe** [CarGuo/GSYVideoPlayer#677]
下载了个demo，手机跑了一下，滑动列表卡顿厉害

**Comment by CarGuo** [comment]
没发现，哪个列表滑动卡了？没播放也滑动卡？

**Comment by renkchina** [comment]
播放，本地3G大小高清视频的时候，有些卡顿。声音断断续续。

**Comment by kuangzhe** [comment]
没有播放也卡,列表快速滑动就会卡顿一下

**Comment by CarGuo** [comment]
这个估计是设置的封面图问题，demo中

**Comment by CarGuo** [comment]
@renkchina   试试问题集锦中的丢帧处理，具体系数可以设置25 之类的试试

**Comment by kuangzhe** [comment]
@CarGuo  我把设置封面的代码注掉还是卡顿

**Comment by kuangzhe** [comment]
有时候会卡顿1,2秒

**Comment by renkchina** [comment]
@CarGuo 丢帧数设置，这个在哪里开始调用呢？还有，我只是想在高清大文件播放时才设置丢帧。其他情况下 不想设置又怎么处理呢？

**Comment by CarGuo** [comment]
列表卡顿问题同705 issue

**Comment by CarGuo** [comment]
列表卡顿问题同705 issue

**Comment by CarGuo** [comment]
列表卡顿问题同705 issue
