### ISSUE TITLE
视频播放

### ISSUE THREAD

**Issue by gyymz1993** [CarGuo/GSYVideoPlayer#680]
进入视频播放  如果视频没加载出来  我就跳转了下个页面   就会出现在另个页面出现视频的声音

等于说那个时候opause无效  有什么可以调用的方法吗

**Comment by gyymz1993** [comment]
不能直接调用destory的方法，我需要返回之后继续播放，到跳转之后暂定，有什么方法可以调用的吗

**Comment by CarGuo** [comment]
你用的是2.1.2版本吗

**Comment by gyymz1993** [comment]
是的呢，需要更新解决吗

**Comment by gyymz1993** [comment]
我现在的版本2.1.1,我等下更新下试试
