### ISSUE TITLE
播放m3u8流，播放器加载后，首次点击播放，会播放出错。第二次点击播放才能加载成功。

### ISSUE THREAD

**Issue by jlertele** [CarGuo/GSYVideoPlayer#681]
以下为视频链接：
http://o8ap2cw2n.bkt.clouddn.com/%5B%E5%BE%90%E4%BD%B3%E8%8E%B9%5D%E6%9C%80%E5%88%9D%E7%9A%84%E8%AE%B0%E5%BF%86_bd.mp4?avvod/m3u8/s/960x640/vb/64k

**Comment by CarGuo** [comment]
m3u8请关闭边播边缓存
