### ISSUE TITLE
可否监听播放进度或者获取当前播放进度

### ISSUE THREAD

**Issue by mxfeng** [CarGuo/GSYVideoPlayer#682]

**Comment by jlertele** [comment]
目前我是重写 onProgressChanged(SeekBar seekBar, int progress, boolean fromUser)回调方法，自己做回调方法处理，建议暴露一个进度监听接口出来。@CarGuo

**Comment by CarGuo** [comment]
fix 2.1.3

**Comment by dong1208401589** [comment]
videoPlayer.getCurrentPlayer().setGSYVideoProgressListener()

**Comment by LittleStart-007** [comment]
if (mGSYVideoProgressListener != null && mCurrentState == CURRENT_STATE_PLAYING) {
            mGSYVideoProgressListener.onProgress(progress, secProgress, currentTime, totalTime);
        }

我在监听视频播放完成后,自动关闭页面. 用了上面监听器,查看源代码,发现监听器只有在播放状态下才会回调.所以无法监听播放结束.(实测中,有几率坚挺到.)
