### ISSUE TITLE
如何设置默认全屏

### ISSUE THREAD

**Issue by chengqiuxia** [CarGuo/GSYVideoPlayer#685]
全屏的设置首次进来都是默认尺寸，需要点击之后才能设置全屏吗？

**Comment by CarGuo** [comment]
不是很理解，可以说下场景吗？

**Comment by chengqiuxia** [comment]
嗯，好的，非常感谢了~场景是这样：视频的来源是手机，可能大小不一，播放的界面的尺寸是固定的。所以需要一开始播放就全屏展示。我尝试过在构造中传true，使用setIfCurrentIsFullscreen为true 都没有效果，我看demo中提到是视频按原来尺寸播放后，再修改默认比例为全屏。  我尝试一初始化就设置全屏，使用demo中设置屏幕比例全屏的方法，但是我测试的结果是视频需要按照原尺寸播放后设置才有效果。就像请教一下，怎么设置视频直接显示全屏。

**Comment by CarGuo** [comment]
还是有点不理解，你的全屏是一进来播放页面，视频就全屏(横屏)显示，然后可以退出全屏恢复detail模式？

还是铺满画面？？

**Comment by chengqiuxia** [comment]
一进来是播放页面，竖屏播放，永远按照播放列表播放不退出。是给一个户外展示屏上做的应用。

**Comment by CarGuo** [comment]
类似demo PlayActivity那种？

**Comment by chengqiuxia** [comment]
是的，什么附加功能也没有，只有播放，但是视频必须全屏

**Comment by CarGuo** [comment]
GSYVideoType 显示比例的设置不可以？？？

**Comment by chengqiuxia** [comment]
嗯，我又分析了下，试了一下GSYVideoType是可以的，之前设置的时候位置放错了。谢啦

**Comment by zhiguo-ren** [comment]
一进来就全屏播放，并禁止竖屏切换，禁止拖动进度的需求。
