### ISSUE TITLE
应用级别悬浮窗问题

### ISSUE THREAD

**Issue by lh911002** [CarGuo/GSYVideoPlayer#688]
你好，集成这个库以后实现视频悬浮窗getActivityContext因为拿不到值就会崩溃，有什么解决方法可以支持应用级别悬浮窗么

**Comment by lh911002** [comment]
@CarGuo

**Comment by CarGuo** [comment]
你可以继承后重写getActivityContext()的返回，不过可能有点麻烦，在判断上。
你用的那个库试下你的悬浮窗，我试试做兼容

**Comment by CarGuo** [comment]
新版本demo中以增加支持 WindowActivity 和 FloatingVideo
