### ISSUE TITLE
亮度调节dialog被遮住了一半

### ISSUE THREAD

**Issue by Shana9** [CarGuo/GSYVideoPlayer#690]
用nexus5出现的问题，横屏（全屏）播放下小太阳只显示了一点，感觉像是被虚拟按键遮住似得

**Comment by CarGuo** [comment]
demo吗？可以上传下截图不？

**Comment by Shana9** [comment]
![screenshot_2017-12-22-17-05-20 1](https://user-images.githubusercontent.com/22065256/34292269-3c0a49a0-e73b-11e7-8797-7021065ad221.png)

**Comment by CarGuo** [comment]
你可以继承后重写 `showBrightnessDialog   `方法调整下位置试试

**Comment by Shana9** [comment]
好的 我试试

**Comment by anjiuzhe** [comment]
偏移是因为localLayoutParams.x不是从屏幕边缘算起的，包含了状态栏的距离。重写方法修改即可。
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/30287547/187055748-0de384e9-3c22-4f41-9cd9-4fcbda035c31.png">
