### ISSUE TITLE
自然播放至34秒左右后changeUiToPlayingBufferingShow和changeUiToPlayingShow不停的调用

### ISSUE THREAD

**Issue by Drrino** [CarGuo/GSYVideoPlayer#696]
测试工具：tv模拟器 6.0和夏普电视 4.2
视频url：http://cls.cdn.jushihuyu.com:8090/vod/26_34466.m3u8
从第一秒播放至30多秒changeUiToPlayingBufferingShow和changeUiToPlayingShow不停调用形成mLoadingProgressBar和mBottomContainer界面抖动
===============================================================
12-25 07:31:54.484 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingBufferingShow
12-25 07:31:54.503 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingShow
12-25 07:31:54.640 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingBufferingShow
12-25 07:31:54.642 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingShow
12-25 07:31:54.749 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingBufferingShow
12-25 07:31:54.771 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingShow
12-25 07:31:55.012 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingBufferingShow
12-25 07:31:55.014 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingShow
12-25 07:31:55.149 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingBufferingShow
12-25 07:31:55.154 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingShow
12-25 07:31:55.155 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingBufferingShow
12-25 07:31:55.186 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingShow
12-25 07:31:55.186 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingBufferingShow
12-25 07:31:55.186 23024-23024/com.childreantv E/GSYVideoPlayer: changeUiToPlayingShow
==================================================================
E/GSYVideoPlayer: changeUiToPlayingShow
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 7, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 8, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 5, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 5, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 5, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 5, nal_ref_idc: 3
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
D/IJKMEDIA: ffp_toggle_buffering_l: start
W/AudioTrack: releaseBuffer() track 0x983af800 disabled due to previous underrun, restarting
D/IJKMEDIA: FFP_MSG_BUFFERING_START:
E/GSYVideoPlayer: changeUiToPlayingBufferingShow
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: PAT:
V/IJKMEDIA: PMT: len 32
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: SDT:
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: PAT:
V/IJKMEDIA: PMT: len 32
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: ffp_toggle_buffering_l: end
D/IJKMEDIA: FFP_MSG_BUFFERING_END:
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
E/GSYVideoPlayer: changeUiToPlayingShow
D/IJKMEDIA: ffp_toggle_buffering_l: start
D/IJKMEDIA: FFP_MSG_BUFFERING_START:
E/GSYVideoPlayer: changeUiToPlayingBufferingShow
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: ffp_toggle_buffering_l: end
D/IJKMEDIA: FFP_MSG_BUFFERING_END:
E/GSYVideoPlayer: changeUiToPlayingShow
D/IJKMEDIA: ffp_toggle_buffering_l: start
D/IJKMEDIA: FFP_MSG_BUFFERING_START:
D/IJKMEDIA: ffp_toggle_buffering_l: end
D/IJKMEDIA: FFP_MSG_BUFFERING_END:
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
E/GSYVideoPlayer: changeUiToPlayingBufferingShow
E/GSYVideoPlayer: changeUiToPlayingShow
D/IJKMEDIA: ffp_toggle_buffering_l: start
D/IJKMEDIA: FFP_MSG_BUFFERING_START:
D/IJKMEDIA: ffp_toggle_buffering_l: end
D/IJKMEDIA: FFP_MSG_BUFFERING_END:
E/GSYVideoPlayer: changeUiToPlayingBufferingShow
E/GSYVideoPlayer: changeUiToPlayingShow
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 6, nal_ref_idc: 0
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 3
D/IJKMEDIA: ct_type:0 pic_struct:0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1100 pes_code=0x1c0
V/IJKMEDIA: pid=1011 pes_code=0x1e0
D/IJKMEDIA: ct_type:0 pic_struct:0
D/IJKMEDIA: ffp_toggle_buffering_l: start
D/IJKMEDIA: FFP_MSG_BUFFERING_START:
D/IJKMEDIA: ffp_toggle_buffering_l: end
W/AudioTrack: releaseBuffer() track 0x983af800 disabled due to previous underrun, restarting
D/IJKMEDIA: FFP_MSG_BUFFERING_END:
E/GSYVideoPlayer: changeUiToPlayingBufferingShow
E/GSYVideoPlayer: changeUiToPlayingShow

**Comment by CarGuo** [comment]
一般出现这种问题，不是nds解析问题，就是分片的帧序列和ijk的同步不兼容

**Comment by Drrino** [comment]
那这个有解决的方案嘛。。。

**Comment by CarGuo** [comment]
很遗憾，目前木有，看后面升级ffmpeg能否解决

**Comment by CarGuo** [comment]
fix by  GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);
