### ISSUE TITLE
新版本打包后运行闪退

### ISSUE THREAD

**Issue by cwyrzz** [CarGuo/GSYVideoPlayer#698]
新版本，直接运行没问题，打包后运行闪退，so文件没加载成功

**Comment by cwyrzz** [comment]
java.lang.UnsatisfiedLinkError:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.biggar.biggar-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.biggar.biggar-1/lib/arm, /data/app/cn.biggar.biggar-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]] couldn't find "libijkffmpeg.so"
--

**Comment by CarGuo** [comment]
要删除旧的demo app

**Comment by CarGuo** [comment]
demo会吗？

**Comment by cwyrzz** [comment]
您好，demo没试，我现在用回2.1.1版本就没事了，用2.1.3的打包后apk体积会少了2m，估计是so文本没打包进去，我也不知道为什么

**Comment by CarGuo** [comment]
![](http://osvlwlt4g.bkt.clouddn.com/2017-12-27/1514339091194.jpg) 

这边所有的so都发布了，可以用as的包分析工具看看是什么没有打包成功

**Comment by cwyrzz** [comment]
好的，我看看，谢谢

**Comment by cwyrzz** [comment]
我把so文件下载下来放进我项目里就可以了，不知道我这边为什么使用引用的方法打包不进去
