### ISSUE TITLE
 如上图求解决

### ISSUE THREAD

**Issue by LinForStudy** [CarGuo/GSYVideoPlayer#7]
![image](https://cloud.githubusercontent.com/assets/18901958/20702564/4d9fd8ca-b653-11e6-8e80-7a9f5acc9b86.png)

**Comment by CarGuo** [comment]
这个地方应该是我在某个装下判空没处理好，稍等下哈。

**Comment by CarGuo** [comment]
已经更新1.3.1，如果可以了请close，thx

**Comment by LinForStudy** [comment]
OK
