### ISSUE TITLE
关于播放器无法获取到视频总时长问题

### ISSUE THREAD

**Issue by loveRose** [CarGuo/GSYVideoPlayer#70]
GSYPreViewManager.instance().getMediaPlayer().getDuration()，返回结果为0，无论在视频加载中还是播放中等任何状态。。。

**Comment by loveRose** [comment]
已经尝试了 m3u8 和 mp4格式获取总时长均为0

**Comment by CarGuo** [comment]
总时长不是在这里获取的，况且GSYPreViewManage并不是播放管理器，是预览管理器。时长获取接口文档中有，请在视频onPrepare之后获取

**Comment by loveRose** [comment]
好的，谢谢啦


发自网易邮箱大师
在2017年02月21日 23:29，Shuyu Guo 写道：

总时长不是在这里获取的，况且GSYPreViewManage并不是播放管理器，是预览管理器。时长获取接口文档中有，请在视频onPrepare之后获取

**Comment by CarGuo** [comment]
抽象类GSYVideoPlayer下有
```
   /**
     * 获取当前总时长
     */
    public int getDuration()
```

**Comment by loveRose** [comment]
嗯，最终查看使用了  videoPlayer.getDuration()获取得到，该videoPlayer即为GSYVideoPlayer的对象
