### ISSUE TITLE
E/IJKMEDIA I/O error

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#703]
`
E/IJKMEDIA: https://api.ciguang.tv/avideo/play?num=02-041-0014&type=flv&v=1&client=android: I/O error
`
手机型号  H60-L03
处理器 Hisilicon Kirin 920
Android 版本 4.4.2

更多详细信息：
I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170829--001
I/IJKMEDIA: ijk_version_info: k0.8.1-62-ge1d04bd
W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
I/IJKMEDIA: ===== versions =====
I/IJKMEDIA: ijkplayer    : k0.8.1-62-ge1d04bd
I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
I/IJKMEDIA: libavutil    : 55.58.100
I/IJKMEDIA: libavcodec   : 57.89.100
I/IJKMEDIA: libavformat  : 57.71.100
I/IJKMEDIA: libswscale   : 4.6.100
I/IJKMEDIA: libswresample: 2.7.100
I/IJKMEDIA: ===== options =====
I/IJKMEDIA: player-opts : loop                         = 1
I/IJKMEDIA: format-opts : ijkapplication               = 2097252784
I/IJKMEDIA: format-opts : ijkiomanager                 = 2064760320
I/IJKMEDIA: ===================
 I/IJKMEDIA: SDL_RunThread: [15819] ff_msg_loop
 I/IJKMEDIA: SDL_RunThread: [15821] ff_vout
 I/IJKMEDIA: SDL_RunThread: [15822] ff_read
 I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
 I/IJKMEDIA: Hit DNS cache hostname = api.ciguang.tv
 I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
 I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
 E/IJKMEDIA: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
 I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
I/PRETTY_LOGGER: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────
 E/IJKMEDIA: https://api.ciguang.tv/avideo/play?num=02-041-0014&type=flv&v=1&client=android: I/O error
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15822]
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15819]
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [15821]

**Comment by CarGuo** [comment]
http://api.ciguang.tv/avideo/play?num=02-041-0491&type=flv&v=1&client=android

这个url我再demo中播放正常

**Comment by Wangct23** [comment]
@CarGuo 找到问题了，是从 http**# s**://api.ciguang.tv/  切换到   http://api.ciguang.tv/ 引起的。但是具体的原因是什么还没弄清楚。

**Comment by Wangct23** [comment]
找到问题了，是从 http**s**://api.ciguang.tv/ 切换到 http://api.ciguang.tv/ 引起的。但是具体的原因是什么还没弄清楚。

**Comment by huangjingqiang** [comment]
@CarGuo http,https切换播放不了。我播放器都释放了，为什么还是播不了
