### ISSUE TITLE
E/IJKMEDIA:  Server returned 400 Bad Request

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#704]
`
E/IJKMEDIA: http://api.ciguang.tv/avideo/play?num=02-041-0491&type=flv&v=1&client=android: Server returned 400 Bad Request
`

播放视频，提示如上错误，但是用VLC可以播放

更多参考信息：
I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170829--001
I/IJKMEDIA: ijk_version_info: k0.8.1-62-ge1d04bd
W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
I/IJKMEDIA: ===== versions =====
I/IJKMEDIA: ijkplayer    : k0.8.1-62-ge1d04bd
I/IJKMEDIA: FFmpeg       : ff3.3--ijk0.8.0--20170829--001
I/IJKMEDIA: libavutil    : 55.58.100
I/IJKMEDIA: libavcodec   : 57.89.100
I/IJKMEDIA: libavformat  : 57.71.100
I/IJKMEDIA: libswscale   : 4.6.100
I/IJKMEDIA: libswresample: 2.7.100
I/IJKMEDIA: ===== options =====
I/IJKMEDIA: player-opts : loop                         = 1
I/IJKMEDIA: format-opts : ijkapplication               = 547577104960
I/IJKMEDIA: format-opts : ijkiomanager                 = 548212819200
I/IJKMEDIA: ===================
/IJKMEDIA: SDL_RunThread: [6977] ff_msg_loop
/IJKMEDIA: SDL_RunThread: [6978] ff_vout
/IJKMEDIA: SDL_RunThread: [6979] ff_read
/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
/IJKMEDIA: Hit DNS cache hostname = api.ciguang.tv
/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
W/IJKMEDIA: HTTP error 400 Bad Request
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
E/IJKMEDIA: http://api.ciguang.tv/avideo/play?num=02-041-0491&type=flv&v=1&client=android: Server returned 400 Bad Request
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6979]
 E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6977]
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6978]
 W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface

**Comment by CarGuo** [comment]
http://api.ciguang.tv/avideo/play?num=02-041-0491&type=flv&v=1&client=android   

这个url我再demo中播放正常

**Comment by CarGuo** [comment]
http://api.ciguang.tv/avideo/play?num=02-041-0491&type=flv&v=1&client=android  该URLdemo在播放正常

**Comment by Wangct23** [comment]
@CarGuo 找到问题了，是从 https://api.ciguang.tv/ 切换到 http://api.ciguang.tv/ 引起的。但是具体的原因是什么还没弄清楚。

**Comment by grenlight** [comment]
@Wangct23 我也碰到了同样的问题，你最后是如何解决的？

**Comment by 9h0st** [comment]
@Wangct23 遇到同样的问题
