### ISSUE TITLE
用RecyclerView列表，滑动列表卡顿

### ISSUE THREAD

**Issue by fuchaothb** [CarGuo/GSYVideoPlayer#705]
经过测试 在adapter中设置地址video.setUp(data.v_link, true, data.v_title)  滑动列表就会卡顿，有什么办法解决吗

**Comment by CarGuo** [comment]
在播放之前setup，不过这里你需要继承播放器，然后重载onClick，拦截下点击播放，然后点击的时候增加setup

**Comment by fuchaothb** [comment]
如果在播放之前设置 我测试发现 设置setThumbImageView() 将无效 ，播放器将黑屏，没有背景图片

**Comment by CarGuo** [comment]
这是因为底层在init的时候设置了 setVisibility GONE， 如果没有setup的时候就不会走setuixxx方法，所以简单的时候你重载init对 mThumbImageViewLayout 设置可视

**Comment by CarGuo** [comment]
fix 3.0.0
