### ISSUE TITLE
播放rtmp直播出现异常

### ISSUE THREAD

**Issue by MediaTzz** [CarGuo/GSYVideoPlayer#707]
GSYVideoGLViewSimpleRender类渲染过程每次调用createProgram，存在失败的情况，造成后续使用时出现异常，屏蔽后正常，请问一下，onSurfaceCreated 中已经创建，在每次渲染时创建一次的有特殊的原因吗？ 能屏蔽这句吗，谢谢

`
protected void initDrawFrame()
 {
//        mProgram = createProgram(getVertexShader(), getFragmentShader());
        GLES20.glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        GLES20.glClear(GLES20.GL_DEPTH_BUFFER_BIT
                | GLES20.GL_COLOR_BUFFER_BIT);
        GLES20.glUseProgram(mProgram);
        checkGlError("glUseProgram");
}
`

**Comment by CarGuo** [comment]
这个你可以继承后使用自己的render，重在后去掉，主要是一些原因，如果你去掉没问题可以去掉。

**Comment by MediaTzz** [comment]
辛苦了，多谢。

**Comment by CarGuo** [comment]
如果你不需要滤镜效果的话，用普通模式会好一些，这里主要是懒的在每次切换的时候去重新创建顶点等，所以就每次绘制的时候创建了，倒是可以优化下
