### ISSUE TITLE
小窗口点击全屏闪退

### ISSUE THREAD

**Issue by wtwt91** [CarGuo/GSYVideoPlayer#71]
player.startWindowFullscreen(ProgramDetailActivity.this, true, true);，小窗口执行这个方法，会闪退；
 java.lang.NullPointerException: Attempt to write to field 'boolean com.shuyu.gsyvideoplayer.video.CustomGSYVideoPlayer.mOpenPreView' on a null object reference
麻烦问一下是因为什么呢

**Comment by CarGuo** [comment]
CustomGSYVideoPlayer是测试类，请看github的文档还有源码上的注释，另外小窗口点击全屏群里有人已经实现过，如果无特殊需求，请使用standard播放器。

**Comment by flyinggor** [comment]
小窗口点击怎么操作的，可以分享一下吗
