### ISSUE TITLE
当在加载视频和播放视频时滑动超级卡顿

### ISSUE THREAD

**Issue by ncworm** [CarGuo/GSYVideoPlayer#710]
我用的是demo中的listview列表，直接拿过来用了。播放的视频一卡一卡的，滑动会卡顿，这是为什么呢

**Comment by ncworm** [comment]
glide 4.1.1

**Comment by CarGuo** [comment]
demo中是否复现？

**Comment by ncworm** [comment]
demo中还是挺顺畅的，我是直接应用的总成依赖。我拉过来时，在列表中播放时，一卡一卡的，滑动列表也会有点卡

**Comment by CarGuo** [comment]
不能在demo复现没办法定位

**Comment by CarGuo** [comment]
fix 3.0.0
