### ISSUE TITLE
导入ex_so包的问题

### ISSUE THREAD

**Issue by gaoshan12312** [CarGuo/GSYVideoPlayer#712]
我导入了ex_so包。build里面配置是：
 compile 'com.shuyu:GSYVideoPlayer:2.1.3'
  compile 'com.shuyu:gsyVideoPlayer-ex_so:2.1.3'
然后ndk过滤是：
 ndk {
            abiFilters 'armeabi-v7a', 'x86'
        }
但是运行时候出现这个问题：
More than one file was found with OS independent path 'lib/x86/libijkplayer.so

**Comment by gaoshan12312** [comment]
网上查了是因为重复导入了so，系统不知道用哪一个的问题。这个该怎么解决呢？

**Comment by CarGuo** [comment]
你把第一个依赖加上-java

**Comment by hhuas** [comment]
![image](https://user-images.githubusercontent.com/43979226/59582571-4502f400-910b-11e9-9473-1e52c5320c26.png)
![image](https://user-images.githubusercontent.com/43979226/59582642-78de1980-910b-11e9-8cab-41c22a7c1181.png)

打release包的时候exoplayer2的依赖和腾讯直播aar包版本冲突了，怎么解决啊
![image](https://user-images.githubusercontent.com/43979226/59582699-af1b9900-910b-11e9-9e72-0f2da8ec10e5.png)
这样也没有用

**Comment by wangyikai1234567** [comment]
你好，大佬。我也遇到这个问题了 但是我加上 -java后，报错 
 - https://dl.google.com/dl/android/maven2/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.pom
  - https://dl.google.com/dl/android/maven2/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.jar
  - https://jcenter.bintray.com/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.pom
  - https://jcenter.bintray.com/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.jar
  - https://repo.maven.apache.org/maven2/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.pom
  - https://repo.maven.apache.org/maven2/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.jar
  - https://jitpack.io/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.pom
  - https://jitpack.io/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.jar
  - https://maven.google.com/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.pom
  - https://maven.google.com/com/shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.jar
  - http://192.168.6.133:8888/nexus/content/repositories/WdMobile/com.shuyu/GSYVideoPlayer-java/6.0.3/ivy-6.0.3.xml
  - http://192.168.6.133:8888/nexus/content/repositories/WdMobile/com.shuyu/GSYVideoPlayer-java/6.0.3/GSYVideoPlayer-java-6.0.3.jar
这些打开后全都是404

**Comment by wangyikai1234567** [comment]
已经处理好了！

**Comment by teller110** [comment]
咋处理的，告诉一下方法@wangyikai1234567

**Comment by hhuas** [comment]
正常使用这个控件，不需要依赖太多的包，我记得是依赖的第二种方式，选择第一条就可以，不过支持的视频格式比较少，然后再依赖第几条来的，你看文档，文档里说了，对于视频格式的支持方式发自我的华为手机-------- 原始邮件 --------发件人： teller110 <notifications@github.com>日期： 2019年11月4日周一 晚上7:04收件人： CarGuo/GSYVideoPlayer <GSYVideoPlayer@noreply.github.com>抄送： hhuas <1364504460@qq.com>, Comment <comment@noreply.github.com>主    题： Re: [CarGuo/GSYVideoPlayer] 导入ex_so包的问题 (#712)咋处理的，告诉一下方法@wangyikai1234567

**Comment by hhuas** [comment]
引入方案c的第一条 java和第三条ijk 更多编码支持就ok了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "teller110"<notifications@github.com&gt;; 
发送时间: 2019年11月4日(星期一) 晚上7:04
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;; 
抄送: "hech"<1364504460@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [CarGuo/GSYVideoPlayer] 导入ex_so包的问题 (#712)




咋处理的，告诉一下方法@wangyikai1234567
