### ISSUE TITLE
求教recyclerview中的其中一个视频想要放大，但不是全屏

### ISSUE THREAD

**Issue by wudilun** [CarGuo/GSYVideoPlayer#715]
视频并不需要全屏，只是覆盖掉整个recyclerview，怎么处理？

**Comment by CarGuo** [comment]
参考demo源码中原本已经有的recyclerview2activity，然后把承接的全屏container位置在布局中调整一下就可以

**Comment by wudilun** [comment]
@CarGuo 一定要getRecyclerBaseAdapter().notifyDataSetChanged();才能出画面吗，不然画面刷新不出来

**Comment by CarGuo** [comment]
不是很理解，这个不是播放器的范畴吧？

**Comment by wudilun** [comment]
@CarGuo 我自己写的IJK的播放器，使用ListVideoUtil的放大屏幕的逻辑，会黑屏很长时间，等到调用onPrepared重新加载，而GSYVideoPlayer直接能全屏播放，有哪里要注意吗

**Comment by CarGuo** [comment]
你是否开启了硬解码？？

**Comment by wudilun** [comment]
开启硬解码了

**Comment by CarGuo** [comment]
开启也硬解码的话这个问题无法避免。
如果是软解码也出现，那么看看是不都你的texuture在全屏切换的时候没有成功重新设置到ijk中

**Comment by wudilun** [comment]
@CarGuo 

01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_stop()
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_stop()=0
01-08 16:59:00.308 30311-30360/com.nbpt.www.videodemo D/IJKMEDIA: message_loop exit
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
01-08 16:59:00.308 30311-30360/com.nbpt.www.videodemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30360]
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ffpipeline_set_surface()
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: IjkMediaPlayer_release
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ffpipeline_set_surface()
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_shutdown_l()
01-08 16:59:00.308 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: wait for read_tid
01-08 16:59:00.315 30311-30361/com.nbpt.www.videodemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30361]
01-08 16:59:00.338 30311-30362/com.nbpt.www.videodemo E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
01-08 16:59:00.449 30311-30362/com.nbpt.www.videodemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30362]
01-08 16:59:00.451 30311-30929/com.nbpt.www.videodemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30929]
01-08 16:59:00.456 30311-30928/com.nbpt.www.videodemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30928]
01-08 16:59:00.457 30311-30935/com.nbpt.www.videodemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30935]
01-08 16:59:00.470 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: Statistics: 497485 bytes read, 0 seeks
01-08 16:59:00.470 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: Deleting stream...
01-08 16:59:00.471 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: wait for video_refresh_tid
01-08 16:59:00.471 30311-30311/com.nbpt.www.videodemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb92dd6a0)
01-08 16:59:00.471 30311-30311/com.nbpt.www.videodemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb90206c0)
01-08 16:59:00.471 30311-30311/com.nbpt.www.videodemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb9318128)
01-08 16:59:00.472 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_shutdown_l()=void
01-08 16:59:00.472 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_dec_ref(): ref=0
01-08 16:59:00.472 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_shutdown_l()
01-08 16:59:00.472 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_shutdown_l()=void
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: IjkMediaPlayer_native_setup
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo I/IJKMEDIA: av_version_info: ff3.3--ijk0.8.0--20170710--001
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo I/IJKMEDIA: ijk_version_info: k0.8.1-10-g36ba72d
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ffpipeline_create_from_android()
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_inject_opaque(0x652)
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_inject_opaque()=void
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x652)
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(3)
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: moncleanup
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo V/IJKMEDIA: setDataSource: path rtmp://live.hkstv.hk.lxdns.com/live/hks
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_data_source(url="rtmp://live.hkstv.hk.lxdns.com/live/hks")
01-08 16:59:00.481 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_data_source(url="rtmp://live.hkstv.hk.lxdns.com/live/hks")=0
01-08 16:59:00.482 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
01-08 16:59:00.482 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbeb31020)
01-08 16:59:00.482 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ffpipeline_set_surface()
01-08 16:59:00.482 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbeb31020)=void
01-08 16:59:00.482 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: IjkMediaPlayer_prepareAsync
01-08 16:59:00.482 30311-30311/com.nbpt.www.videodemo D/IJKMEDIA: ijkmp_prepare_async()


看日志切换全屏，是每次都会stop，重新设置surface
