### ISSUE TITLE
没有用流量播放时，弹框提醒当前使用的网络类型么？

### ISSUE THREAD

**Issue by a1018875550** [CarGuo/GSYVideoPlayer#717]
如题？求解，谢谢

**Comment by CarGuo** [comment]
有啊，demo中不是有么，4g时弹出提示框，如果开启了缓存，那么本地缓存完全的时候就不提示了。

**Comment by a1018875550** [comment]
现在遇到的问题是，用```VideoPlayer.startPlayLogic();```自动播放，就没有了

**Comment by CarGuo** [comment]
你继承后重载这个方法，之后在super前参考源码判断就可以了
