### ISSUE TITLE
关于ListGSYVideoPlayer监听问题

### ISSUE THREAD

**Issue by loveRose** [CarGuo/GSYVideoPlayer#72]
如何监听ListGSYVideoPlayer 自动序列播放中的单节播放完毕？就像第一个url的视频播放完成接着自动播放第二条url视频，需要监听到第一条播放完成的监听回调，目前只有第二条加载完毕的onPrepared回调，而onAutoComplete这个方法应该是指的整个list全部播放完毕回调吗？不应该啊，现在打Log和Debug都查到没有执行这个方法

**Comment by CarGuo** [comment]
onAutoCompletion在ListGSYVideoPlayer里面却是整个播放完结了才回调，因为只有super之后，才会触发底层的回调出来，但是如果走了super，那么播放器的内部资源回开始释放！！！！

这里提个建议吧，这个播放器很大程度适合做继承，你可以看到弹幕的那个播放器，就是一个继承的例子。对于你这个需求，你只要写一个播放器，继承了ListGSYVideoPlayer，重载onAutoCompletion，在super之前，你就可以先把方法回调出去。

最后提个醒，因为全屏是在逻辑播放器之间切换，所有如果有什么自定义操作，请千万记得，在startWindowFullscreen的时候也要给全屏播放器做对应的处理，详细页可以参考弹幕播放器DanmakuVideoPlayer

**Comment by loveRose** [comment]
好的，谢谢了
