### ISSUE TITLE
视频暂时的时候，会继续缓存吗？

### ISSUE THREAD

**Issue by sharememories** [CarGuo/GSYVideoPlayer#720]

**Comment by CarGuo** [comment]
会的

**Comment by nikolamakin** [comment]
那请问作者，如何让视频暂停的时候停止缓存？比如如下使用场景：
教程视频，播放2分钟之后提示开通会员才能观看。在提示的时候，停止缓存，以免给用户带来额外的流量损耗。开通会员回来之后可继续观看。请作者指点一下。感谢。祝：作者身体倍棒吃嘛嘛香。

**Comment by CarGuo** [comment]
这个只能说，通过服务器，在请求的时候设置header的range

**Comment by nikolamakin** [comment]
但是请求的range 如何控制字节数，使返回的数据可以播放呢？

**Comment by CarGuo** [comment]
其实个人建议，从安全角度或者实现角度，比较好的是服务端根据用户去判断返回你试看的数据，开通会员后，再返回完整数据。
因为别人可以很容易的在App端修改你的头。

**Comment by nikolamakin** [comment]
那返回试看数据，怎么给用户完整数据的视频时长？好让用户知道完整视频的时间。

**Comment by dylanZk1** [comment]
@nikolamakin 很简单啊，修改视频数据的metaData部分，把时间改成完整视频的时长，反正都是流形式
