### ISSUE TITLE
多个mp4片段拼接的文件：  file:开头的 不能缓存，如何开启缓存。

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#721]
例如：file://***/abc.concat
abc.concat 文件内容如下
ffconcat version 1.0
file http://www.baidu.com/1.mp4
duration 300
file http://www.baidu.com/2.mp4
duration 300
发现设置 cache=true 缓存不会开启。

setUp里有如下代码：
if (cacheWithPlay &&( url.startsWith("http") || url.startsWith("file")) && !url.contains("127.0.0.1") && !url.contains(".m3u8")) {
            HttpProxyCacheServer proxy = GSYVideoManager.getProxy(getActivityContext().getApplicationContext(), cachePath);
            //此处转换了url，然后再赋值给mUrl。
            url = proxy.getProxyUrl(url);
            mCacheFile = (!url.startsWith("http"));
            //注册上缓冲监听
            if (!mCacheFile && GSYVideoManager.instance() != null) {
                proxy.registerCacheListener(GSYVideoManager.instance(), mOriginUrl);
            }
        } else if (!cacheWithPlay && (!url.startsWith("http") && !url.startsWith("rtmp")
                && !url.startsWith("rtsp") && !url.contains(".m3u8"))) {
            mCacheFile = true;
        }

这种文件如何开启缓存呢，或者自己怎么实现缓存呢。

**Comment by CarGuo** [comment]
多分配的concat和m3u8不支持缓存到本地，这个如果你要自己实现，那么简单的思路是你要处理文件下载逻辑，然后对每个切换的url做管理，针对每个url缓存
