### ISSUE TITLE
紧急

### ISSUE THREAD

**Issue by mahmoudelfeel** [CarGuo/GSYVideoPlayer#723]
Fatal Exception: java.lang.RuntimeException: glDrawArrays: glError 1282
       at com.shuyu.gsyvideoplayer.render.glrender.GSYVideoGLViewBaseRender.checkGlError(Unknown Source)
       at com.shuyu.gsyvideoplayer.render.glrender.GSYVideoGLViewSimpleRender.initPointerAndDraw(Unknown Source)
       at com.shuyu.gsyvideoplayer.render.glrender.GSYVideoGLViewSimpleRender.onDrawFrame(Unknown Source)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1582)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1267)

HUAWEI Mate 8
Api 24

当玩家加载时点击退出活动

**Comment by CarGuo** [comment]
不理解，demo复现？

**Comment by mahmoudelfeel** [comment]
对不起，我不会说中文
i am using your demo app on ( DetailFilterActivity )
to load this video from youtube 

[https://redirector.googlevideo.com/videoplayback?sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&itag=22&initcwndbps=162500&signature=8EB1B38AE8597F405959D3AE6385770DC56B7C1E.1DB74296F0BE55E34E7C5FD907CC43D67F7B634E&mm=31&mn=sn-n4v7sn76&ipbits=0&ratebypass=yes&ip=2600%3A3c01%3A%3Af03c%3A91ff%3Afe24%3Ab564&key=yt6&requiressl=yes&source=youtube&lmt=1515480634999944&dur=344.630&expire=1515625919&mime=video%2Fmp4&mt=1515604238&pl=64&mv=m&id=o-AAMaAYEsL1e1oZm9YXuphN5m10uXDum7RRvKvPL5XzJk&ei=X0lWWpeUC8iw-wPl-4Yw&ms=au](url)

it kept loading on HUAWEI Mate 8 
it works on other mobiles but on  HUAWEI Mate 8  it doesn't work

the crashed happened when i pressed the back button while it was loading

**Comment by CarGuo** [comment]
sorry， i don't this device. 

you can try again by demo in dev branch.

where to call checkGLError leads to this error

**Comment by mahmoudelfeel** [comment]
okay it happened on another device too with the same log

Cant you just avoid making a crash with your method and just log the error ?

**Comment by CarGuo** [comment]
so easy, you can extend `GSYVideoGLViewSimpleRender.class` and override checkGlError.
then `detailPlayer.setCustomGLRenderer(mGSYVideoGLViewCustomRender);` like demo

**Comment by mahmoudelfeel** [comment]
Thank you !
