### ISSUE TITLE
如果使用PreViewGSYVideoPlayer来播放视频,会导致整个app所有图片无法加载

### ISSUE THREAD

**Issue by liugongce** [CarGuo/GSYVideoPlayer#725]
如果使用PreViewGSYVideoPlayer来播放视频,打开进度图小图预览,会导致整个app所有图片无法加载.好像是资源占用过高,具体原因不明,在一段时间后会恢复

**Comment by CarGuo** [comment]
看源码就知道啦，我在哪里用glide下载100帧预览，你可以修改下参数试试
