### ISSUE TITLE
广告显示

### ISSUE THREAD

**Issue by java02014** [CarGuo/GSYVideoPlayer#726]
视屏的列表播放的暂停广告和全屏播放的暂停广告显示，大神有什么好的思路吗？

**Comment by CarGuo** [comment]
你在暂停的显示一层新的view不久好了么

**Comment by java02014** [comment]
就是说里面没有提供相应的广告布局什么的

**Comment by CarGuo** [comment]
没有，你继承后，返回你自己的布局就可以

**Comment by java02014** [comment]
ok

**Comment by SkySeparationSong** [comment]
怎么做的能告知下嘛,谢谢,小窗口的时候暂停可以显示广告,可是全屏就没有

**Comment by 748297973** [comment]
> 怎么做的能告知下嘛,谢谢,小窗口的时候暂停可以显示广告,可是全屏就没有
@SkySeparationSong 解决了吗
