### ISSUE TITLE
怎么支持 AVI 格式？

### ISSUE THREAD

**Issue by a1018875550** [CarGuo/GSYVideoPlayer#728]
感谢

**Comment by CarGuo** [comment]
参考首页的so编译教程，修改根目录下的.sh文件

**Comment by a1018875550** [comment]
该项目用的ijkplayer是最新 的版本么？

**Comment by CarGuo** [comment]
0.84

**Comment by a1018875550** [comment]
为什么作者不提供这些so呢？

**Comment by CarGuo** [comment]
因为只提供常用so，支持的格式越多会导致so越发庞大，目前so和java的依赖是分开的，只需要添加上自己想支持的so，依赖java也可以工作。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1206   avi
