### ISSUE TITLE
youku

### ISSUE THREAD

**Issue by mahmoudelfeel** [CarGuo/GSYVideoPlayer#729]
How to play sliced video  from youku site in one video from concat ?
  ffconcat version 1.0
file 1
 duration 395.0
 file 2
   duration 386.0
file 3
  duration 391.0
file 4
  duration 271.0

**Comment by CarGuo** [comment]
use ex_so，set cache false

**Comment by mahmoudelfeel** [comment]
okay i did what you said but it wont load i checked url m3u8 file and the duration is  ( - 1 ) ??

so i used a parsing concat which return a link like this 

(   01-14 16:29:28.516 32354-32354/com.bloomer.videoScreenShot I/asdsa: Asdsa/data/user/0/com.bloomer.videoScreenShot/cache/http://v.youku.com/v_show/id_XMzI5MjcxNDk1Mg==.html?spm=a2hcm.20010061.m_100892.5~5~5~5!2~A/http://v.youku.com/v_show/id_XMzI5MjcxNDk1Mg==.html?spm=a2hcm.20010061.m_100892.5~5~5~5!2~A_2
}

`ParsingTask parsingTask = new ParsingTask(this);
        parsingTask.setOnImageRead(new ParsingTask.OnUrlRead() {
            @Override
            public void onRead(Boolean isValid, String videoLink) {
                GSYVideoOptionBuilder gsyVideoOptionBuilder = new GSYVideoOptionBuilder()
                     .setIsTouchWiget(true)
                     .setRotateViewAuto(false)
                     .setLockLand(false)
                     .setShowFullAnimation(false)
                     .setNeedLockFull(true)
                     .setSeekRatio(1)
                     .setUrl("")
                     .setCacheWithPlay(false)
                     .setVideoTitle(videoLink);


                gsyVideoOptionBuilder.build(((videoView) player));
                player.getFullscreenButton().setVisibility(View.INVISIBLE);
               player.startPlayLogic();
                GSYVideoManager.instance().setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
            }
        });
        parsingTask.execute("http://v.youku.com/v_show/id_XMzI5MjcxNDk1Mg==.html");`

this code if from this library [ParsingPlayer](https://github.com/TedaLIEz/ParsingPlayer) 

it uses IJKplayer  and it works there

but doesnt work in GSYVideoPlayer 

do you know why ?
