### ISSUE TITLE
设置循环播放的时候如何判断是否播放过一次了

### ISSUE THREAD

**Issue by jinguangyue** [CarGuo/GSYVideoPlayer#73]

**Comment by CarGuo** [comment]
抽象类中有一个mHadPlay，不过是一个protected，你可以通过继承播放器后回调出来。

**Comment by CarGuo** [comment]
或者你在onPrepared的时候，自己外部做个判断。

**Comment by jinguangyue** [comment]
你好 我的意思是视频播放到了结尾之后循环播放从头开始播了 再次播放到中间某个位置了 怎么去判断视频播放到了结尾 就是说用户已经看过了一次视频 onPrepared只能说明加载完了吧？

**Comment by CarGuo** [comment]
ijk的播放到底的complete回调的设置了循环之后，是不会走的。所以如果你想要做到这个需求，那么你只能从gsy的底层，进度条那一块，或者自己手动循环播放，参考ListGSYVideoPlayer，在结束的时候不释放而且重新播放，这样你就知道了。

**Comment by jinguangyue** [comment]
好的 多谢
