### ISSUE TITLE
滤镜模式切换崩溃

### ISSUE THREAD

**Issue by tigericon** [CarGuo/GSYVideoPlayer#730]
在滤镜切换的时候会崩溃 华为mate9  使用的dev分支 ， 用小米手机就没有问题，  这个能解决下吗？ 
![image](https://user-images.githubusercontent.com/19162145/34906248-971ff5e0-f8a4-11e7-98b1-60b482306618.png)

**Comment by CarGuo** [comment]
fix 3.0.0
