### ISSUE TITLE
获取视频第一帧

### ISSUE THREAD

**Issue by kerwin1321** [CarGuo/GSYVideoPlayer#732]
如何获取网络视频的第一帧或者缩略图

**Comment by CarGuo** [comment]
参考demo https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/SampleCoverVideo.java

**Comment by ykbjson** [comment]
大佬，本地视频和普通格式的视频你那个截图方法是可以的，但是m3u8格式的视频就没辙了，求大神给个解决方案啊，谢谢。
