### ISSUE TITLE
这个框架可以不可以先缓存完毕之后再执行播放了？

### ISSUE THREAD

**Issue by LiqiNew** [CarGuo/GSYVideoPlayer#735]
这个框架可以不可以先缓存完毕之后再执行播放了？还有缓存的机制是？是缓存在本地还是？如果有缓存，项目kill掉之后再启动。还会去请求网络缓存吗？

**Comment by CarGuo** [comment]
缓存是代理分流，由一个后台server负责拉流保存到本地，同事分发给播放器，如果已经缓存的可以直接播放，

然后如果你需要先下载再播放，你无非就是直接下载然后调用播放器播放本地而已。

**Comment by LiqiNew** [comment]
谢谢作者的解惑。渴望进作者你的群。

**Comment by LiqiNew** [comment]
谢谢作者的解惑。那你的框架提供下载视频的方法没？还是说我要自己去下载？渴望进作者你的群。

**Comment by CarGuo** [comment]
说真的，群里其实是大多数人吐槽和水的，实际上回答问题的不多，哈哈，下载的话你最好你可以参考使用GSYVideoManager源码的代理设置方法，然后去自己用代码去下载这个url

**Comment by LiqiNew** [comment]
那意思还是得需要自己去下载啦。为什么不提供一个下载方法了？反正你这个框架已经是重量级了。那么就让他的功能更多一点，那样对使用者也方便很多。

**Comment by CarGuo** [comment]
因为这个功能不是很常用，也因为比较重量级了，现在正在继续拆分模块

**Comment by LiqiNew** [comment]
建议模块化一点。但是拆分的话，这个也是一个艰巨的任务呀。

**Comment by LiqiNew** [comment]
作者大大，我能不能加你QQ。你的QQ需要答案，你也不方便在这里告知。所以你加我的QQ吧。我的QQ是543945827。我有些疑问想找讨论一下。

**Comment by CarGuo** [comment]
加了，虽然我不经常在

**Comment by fengjian123** [comment]
@LiqiNew 你这个问题解决了么？我有个需求也是，先缓存到本地，然后可以播放本地视频文件，如果不主动点击下载缓存，就只能每次网络播放了。
