### ISSUE TITLE
能写一个rtsp协议简单使用的demo吗？

### ISSUE THREAD

**Issue by bigzhulove** [CarGuo/GSYVideoPlayer#737]
能写一个rtsp协议简单使用的demo吗？
比较小白，按照第三种引入方式
compile 'com.shuyu:gsyVideoPlayer-java:3.0.0'
compile 'com.shuyu:gsyVideoPlayer-ex_so:3.0.0'

**Comment by CarGuo** [comment]
没什么区别啊，引用后，你替换url就可以

**Comment by bigzhulove** [comment]
现在可用播放了，只是播几秒钟就一直停留在加载视频的界面，用您项目中的给的url播放正常
 我使用的地址  rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov

**Comment by CarGuo** [comment]
rtsp用的什么协议？可以试试设置tcp的配置

**Comment by bigzhulove** [comment]
怎么配置？
看到您问题里面有段这样设置，表示不太明白，请求解惑！
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOphtionModel);
GSYVideoManager.instance().setOptionModelList(list);

**Comment by CarGuo** [comment]
这个就是设置的，然后还需要服务端支持

**Comment by bigzhulove** [comment]
我们用的大华流媒体服务器管理摄像头，
                           服务端需要怎么支持？
                           能具体点吗？

**Comment by bigzhulove** [comment]
这是使用代码截图
![default](https://user-images.githubusercontent.com/20509302/34978277-af011d52-fad8-11e7-82f5-da3ebd9b6272.png)

**Comment by CarGuo** [comment]
不清楚大华流媒体使用的协议。
