### ISSUE TITLE
GSYVideoView

### ISSUE THREAD

**Issue by gyymz1993** [CarGuo/GSYVideoPlayer#738]
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at com.shuyu.gsyvideoplayer.render.GSYRenderView.initCover(GSYRenderView.java:77)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at com.shuyu.gsyvideoplayer.video.base.GSYTextureRenderView.initCover(GSYTextureRenderView.java:184)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.updatePauseCover(GSYVideoView.java:212)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at com.onetouch.view.StandardVideoPlayer.changeUiToPauseShow(StandardVideoPlayer.java:515)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.resolveUIState(GSYVideoControlView.java:748)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setStateAndUi(GSYVideoControlView.java:346)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onVideoPause(GSYVideoView.java:420)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at itbour.onetouchshow.base.BaseVideoPlayActivity.onPause(BaseVideoPlayActivity.java:224)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.app.Activity.performPause(Activity.java:6831)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3761)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3738)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3712)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3686)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.app.ActivityThread.-wrap16(ActivityThread.java)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.os.Looper.loop(Looper.java:160)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6207)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
01-13 14:45:52.420 26800 26800 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)

**Comment by CarGuo** [comment]
？？？
