### ISSUE TITLE
替换项目中的IMediaPlayer播放bug

### ISSUE THREAD

**Issue by androidTH** [CarGuo/GSYVideoPlayer#740]
把你的项目中GSYVideoManager类中的IMediaPlayer换成金山的播放器后，点击暂停，再横屏，播放不出来画面。然后再竖屏返回，正常播放。这个问题一直没有解决，可否看下。可以把修改后的源码发你。邮箱：

**Comment by CarGuo** [comment]
横屏的时候有声音没画面么？不知道金山的播放器的输出是怎么样的，这个描述看起来是设置的Surface没有在切换的时候替换成功

**Comment by androidTH** [comment]
@CarGuo 是的就是没有替换成功。这个问题不知道为啥没替换成功。

**Comment by androidTH** [comment]
@CarGuo 可否帮忙看下。

**Comment by CarGuo** [comment]
我觉得这个问题和我之前的exo1类似，你看看我原来exo1的切换逻辑

**Comment by androidTH** [comment]
@CarGuo exo1在哪里？

**Comment by CarGuo** [comment]
最新版本的playmanager下

**Comment by androidTH** [comment]
@CarGuo ok，我看下。

**Comment by androidTH** [comment]
@CarGuo if (mediaPlayer != null && mediaPlayer.getDuration() > 30
                    && mediaPlayer.getCurrentPosition() < mediaPlayer.getDuration()) {
                mediaPlayer.seekTo(mediaPlayer.getCurrentPosition() - 20);
            }是这段代码吗？

**Comment by CarGuo** [comment]
exo1在seek的时候，会重置surface

**Comment by androidTH** [comment]
@CarGuo 金山播放器不行

**Comment by CarGuo** [comment]
这就奇怪了，如果不行那么播放中后台返回前台也会有问题，因为推到后台再返回前台也会触发surface的释放和更新

**Comment by androidTH** [comment]
确实有你说的情况。我看了好几个开源的播放器，换成金山的就没有这样的情况，所以还是你源码那个部分写的有问题。

**Comment by CarGuo** [comment]
不是很理解，因为在项目中我现在用着ijk，exo，系统播放器都没有问题。

**Comment by androidTH** [comment]
加我扣扣吧，943417116
