### ISSUE TITLE
2个相同的界面同时存在,第二个界面播放视频,然后返回到第一个界面,第一个界面显示异常

### ISSUE THREAD

**Issue by xuqinghao1991** [CarGuo/GSYVideoPlayer#741]
2个相同的界面
当前界面(第一个Activity)启动了当前界面(第二个Activity),第二个Activity播放视频,然后结束第二个Activity返回到第一个Activity,第一个Activity显示第二个界面的数据(只是播放器区域)?请问怎么修改?谢谢

**Comment by CarGuo** [comment]
你finish的时候没有释放播放器？？？

**Comment by xuqinghao1991** [comment]
@Override
    protected void onDestroy() {
        GSYVideoManager.instance().releaseMediaPlayer();
        EventBus.getDefault().unregister(this);
        mPagerTitle = null;
        if (videoPresenter != null) {
            videoPresenter.onDestroy();
        }
        super.onDestroy();
    }

**Comment by CarGuo** [comment]
你录一个视频分享个url上来看看？

**Comment by xuqinghao1991** [comment]
[E:\IMG_0049.mp4](url)

**Comment by xuqinghao1991** [comment]
http://v.youku.com/v_show/id_XMzMyNjI0OTIyOA==.html?spm=a2h3j.8428770.3416059.1

**Comment by CarGuo** [comment]
哦，这个现象可以参考demo的 DetailControlActivity，他就有跳转demo，他继承的基类里，是这样处理的。

```
 @Override
    protected void onPause() {
        super.onPause();
        getGSYVideoPlayer().getCurrentPlayer().onVideoPause();
        isPause = true;
    }

    @Override
    protected void onResume() {
        super.onResume();
        getGSYVideoPlayer().getCurrentPlayer().onVideoResume();
        isPause = false;
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (isPlay) {
            getGSYVideoPlayer().getCurrentPlayer().release();
        }
        if (orientationUtils != null)
            orientationUtils.releaseListener();
    }
```
