### ISSUE TITLE
mp4播放不了

### ISSUE THREAD

**Issue by csh159** [CarGuo/GSYVideoPlayer#742]
![c_ h ts6wt9 syxc xs](https://user-images.githubusercontent.com/4157414/35019275-f953027a-fb60-11e7-8200-b0023f99743e.png)，
下面是MP4的地址：http://js.a.yximgs.com/udata/W_8_UAn4tpgi8_zh.mp4

**Comment by csh159** [comment]
![s_5_ g_ _lrpck mx6e npm](https://user-images.githubusercontent.com/4157414/35019880-362cf57c-fb64-11e7-8569-9d4c8fd49bd9.png)

**Comment by csh159** [comment]
![s_5_ g_ _lrpck mx6e npm](https://user-images.githubusercontent.com/4157414/35019897-4517f4ce-fb64-11e7-82ad-336d33fc5410.png)

**Comment by csh159** [comment]
![s_5_ g_ _lrpck mx6e npm](https://user-images.githubusercontent.com/4157414/35019961-b436e05e-fb64-11e7-8a57-688f6f0f91a4.png)

**Comment by CarGuo** [comment]
是的，ijk 确实修改了mp4读取帧的方式，可能是音频或者视频的读取没找到适配的，可以切换到exo2试试。

**Comment by csh159** [comment]
@CarGuo ex02怎么切换？谢谢

**Comment by CarGuo** [comment]
看最新demo的gsyapplication，如果是exo2配合surfaceview会好一些，具体切换也在application，就是surfaceview对全屏动画的切换支持不好。

**Comment by csh159** [comment]
看到了，谢谢！
