### ISSUE TITLE
加载时间长

### ISSUE THREAD

**Issue by HigherPlace** [CarGuo/GSYVideoPlayer#743]
求教一个问题，加载rtmp视频流的黑屏时间很长要才能够缩短呢

**Comment by CarGuo** [comment]
https://github.com/Bilibili/ijkplayer/issues/2970  

https://github.com/Bilibili/ijkplayer/issues/3820

https://github.com/Bilibili/ijkplayer/issues/2812

以上等等，其中setOption对应GSY中的如下VideoOptionModel 
```
VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
```

最多只能通过设置option解决，现在，或者你还可以选择去修改so源码。其他的没有什么办法。
