### ISSUE TITLE
全屏情况下如果横向手机就会消失全屏的view

### ISSUE THREAD

**Issue by chengzhijun0706** [CarGuo/GSYVideoPlayer#748]
@CarGuo 
![image](https://user-images.githubusercontent.com/13751034/35088846-01f6df0e-fc70-11e7-87b9-4c857554cf63.png)
![image](https://user-images.githubusercontent.com/13751034/35088868-15753422-fc70-11e7-9a08-3d1444e49cbf.png)
![image](https://user-images.githubusercontent.com/13751034/35088883-2438c3c0-fc70-11e7-9619-6dbbc59f4a31.png)
这个页面已经加了android:screenOrientation="portrait"
可是在全屏下如果横屏后,这个页面就一直可以横竖切换了
需求是列表只会纵向,全屏情况下会横竖屏切换
整个界面是一个recyleview

**Comment by CarGuo** [comment]
demo中哪个页面复现

**Comment by chengzhijun0706** [comment]
解决了,加了这个就好了,谢谢了
android:configChanges="keyboardHidden|orientation|screenSize"

**Comment by chengzhijun0706** [comment]
但是还是很奇怪,下面的列表在横屏的时候重新绘制了,但是为什么全屏的view没有重新绘制呢
