### ISSUE TITLE
播放黑屏为什么啊？有声音，没画面

### ISSUE THREAD

**Issue by csh159** [CarGuo/GSYVideoPlayer#75]

**Comment by CarGuo** [comment]
请参考github首页的问题详解。有声音没画面，首先确定是否开启了硬解码，然后确定视频的编码格式是否支持。

**Comment by csh159** [comment]
用的是示例中的播放地址也会黑屏，有声音没画面

**Comment by CarGuo** [comment]
不是很理解，demo可以正常运行。

**Comment by csh159** [comment]
![screenshot_2017-02-24-09-52-33-244_com example gs](https://cloud.githubusercontent.com/assets/4157414/23287206/f9f278e6-fa76-11e6-836c-6aee04014bee.png)
播放是上面的样子

**Comment by CarGuo** [comment]
没重现，可以正常运行播放。

**Comment by CarGuo** [comment]
没重现过，可以正常运行播放呢。请问下是使用模拟器还是真机？

**Comment by csh159** [comment]
真机的

**Comment by csh159** [comment]
不过我是从AS转到了eclipse

**Comment by CarGuo** [comment]
那对应的as下远程依赖的那么库你有依赖吗？我记得群里有人移植过，可以正常运行。

**Comment by csh159** [comment]
都依赖了（exo,cache,transition动画，ijkplayer,log,弹幕）这几个依赖库

**Comment by CarGuo** [comment]
你的情况很可能是textureView显示有问题

**Comment by csh159** [comment]
晕死啊，我没用你里面自带的例子，自己单独写了个activity播放视频就可以播放，这是为什么？

**Comment by CarGuo** [comment]
这样啊，有可能是Activity的兼容动画打开，或者Activity继承的AppCompatActivity支持包的问题？

**Comment by csh159** [comment]
我也感觉是，播放这一块我分离出来一个libary,示例引用这个库，然后就播放不了！哈哈，感谢了！研究一下怎么用(*^__^*)

**Comment by loveRose** [comment]
这个问题我来回到吧，查看你的配置文件中 application节点是否定义了该属性 hardwareAccelerated
如果定义了  请把他设为 true ，该节点意思是当前app是否使用硬件加速。 android:hardwareAccelerated="true"

**Comment by liwenpeng12** [comment]
hardwareAccelerated
如果定义了 请把他设为 true   感谢
