### ISSUE TITLE
您好，关于 Speex 解码的问题。

### ISSUE THREAD

**Issue by autismbug92** [CarGuo/GSYVideoPlayer#751]
请教下，nellymoser 的音频编码格式，通过编译 ijkplayer 库实现了。
Speex 的编解码库支持，需要额外的编译 Speex 库。
网络上找了很久资料，自己也尝试了去根据 openSSL 的脚本去编 Speex 的编译脚本。
但是遇到问题，编译不出来。
如果您知道如何编译支持 Speex 的so 方法的话，能不能指教一下，谢谢~

**Comment by CarGuo** [comment]
你应该找ffpemg的 speex支持。
像是 
```
 --enable-libspeex 
```
这种，因为ijk编译的时候去去掉了多余编码，你需要在module.sh中把speex相关解码打开

**Comment by autismbug92** [comment]
还是搞不出来，speex 编译脚本写不对。

**Comment by autismbug92** [comment]
感觉网络上，关于 Android ijkplayer speex 编译的资料很少。

**Comment by CarGuo** [comment]
你应该找的是ffmpeg的speex
