### ISSUE TITLE
可以实现直播视频边播边录的功能吗？

### ISSUE THREAD

**Issue by y2653904** [CarGuo/GSYVideoPlayer#752]
大神，可以实现直播视频点击录制和点击停止的功能吗？自定义缓存路径的格式是怎样的？

**Comment by CarGuo** [comment]
直播不支持边播边录制。

**Comment by y2653904** [comment]
原生的ijkplayer支持吗？大神，有什么思路吗？

**Comment by CarGuo** [comment]
不支持，两个思路，一个你对播放的每一帧和音频数据试试解析保存。
一个就是用录屏。

**Comment by y2653904** [comment]
录屏是不是只支持5.0以上的啊？好像还不能实现区域录制啊？

**Comment by CarGuo** [comment]
这个就看你自己的需求了
