### ISSUE TITLE
關於IJKPlayer是否可以播放Youtube的視頻

### ISSUE THREAD

**Issue by Kevin1ee** [CarGuo/GSYVideoPlayer#754]
E/IJKMEDIA: https://www.youtube.com/watch?v=Isvqg90LhqM: Invalid data found when processing input
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E/GSYVideoPlayer: cancelTimeOutBuffer
E/GSYVideoPlayer: Link Or mCache Error, Please Try Again https://www.youtube.com/watch?v=Isvqg90LhqM

嘗試使用Demo的Url播放去播放Youtube的視頻,日志如上.
最近在調研可以播放Youtube視頻的播放器,請教大佬們是否有做過這樣的嘗試?

**Comment by CarGuo** [comment]
因为某些大家都知道的原因，我是播放不了油管的视频

**Comment by Kevin1ee** [comment]
已经找到处理方式了,通过解析油管的真实地址达到播放的效果

**Comment by XiongKe94** [comment]
> 已经找到处理方式了,通过解析油管的真实地址达到播放的效果

你怎么解析YouTube的真实播放URL的?
