### ISSUE TITLE
播放画面卡顿是需要设置什么么？

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#756]
播放有些视频，ios端可以，说明视频本身应该没问题，但是我这播放起来一顿一顿的

**Comment by CarGuo** [comment]
和视频的帧数，分辨率等都有关系，还和视频源本身编码有关，可以试试切换为EXO2模式试试

**Comment by i2863CookieZJ** [comment]
我发现个问题，直接调用播放器不会卡顿，但是我重新设置setStandardVideoAllCallBack后，所有视频都卡顿
videoPlayer.setStandardVideoAllCallBack(new SampleListener() {
            //加载成功，objects[0]是title，object[1]是当前所处播放器（全屏或非全屏）
            @Override
            public void onPrepared(String url, Object... objects) {
                MediaManager me = MediaManager.getIntance();
                if (me.isPlay()) {
                    me.release();
                    me.getTextView().endAnimation();
                    //恢复时间
                    me.getTextView().setContent(me.getContentBean().getBrokeNews().getAudioDuration());
                }
            }

            //点击了开始按键播放，objects[0]是title，object[1]是当前所处播放器（全屏或非全屏）
            @Override
            public void onClickStartIcon(String url, Object... objects) {
                MediaManager me = MediaManager.getIntance();
                if (me.isPlay()) {
                    me.release();
                    me.getTextView().endAnimation();
                    //恢复时间
                    me.getTextView().setContent(me.getContentBean().getBrokeNews().getAudioDuration());
                }
            }

        });
我在列表页上点击播放视频就去关闭音频播放，想要这样的效果，我这样写是否有问题，造成了卡顿

**Comment by CarGuo** [comment]
这个就不清楚了，看下能否在demo复现。个人怀疑是哪个地方导致列表一直更新
