### ISSUE TITLE
播放视频卡顿

### ISSUE THREAD

**Issue by CleverSJX** [CarGuo/GSYVideoPlayer#757]
播放器代码
public class GSYVideoComponent extends StandardGSYVideoPlayer implements LifeCycle {

    private ComponentArgs args;

    private List<QrCodeResource> qrCodeResourceList = new ArrayList<>();

    private int current = 0;

    public GSYVideoComponent(Context context, int alignTop, int alignLeft, int width, int height) {
        super(context);
        args = new ComponentArgs(alignTop, alignLeft, width, height);
        setLayoutParams(args.layoutParams);
        this.setVideoAllCallBack(new MyVideoAllCallBack());
    }

    public void setQrCodeResource(List<QrCodeResource> list) {
        this.qrCodeResourceList = list;
    }

    public void start() {
        //清空记录
        for (QrCodeResource res : qrCodeResourceList) {
            JZVideoPlayer.clearSavedProgress(getContext(), res.resPath);
        }

        //设置路径
        this.setUp(qrCodeResourceList.get(0).resPath, false, "");
        //模拟播放
        this.startPlayLogic();
    }

    private void startNext() {
        current++;
        if (current > qrCodeResourceList.size() - 1) {
            current = 0;
        }
        //设置路径
        this.setUp(qrCodeResourceList.get(current).resPath, false, "");
        //模拟播放
        this.startPlayLogic();
    }

    @Override
    public void onComponentDestroy() {
        this.release();
        this.setStandardVideoAllCallBack(null);
        GSYVideoPlayer.releaseAllVideos();
    }

    @Override
    public void onComponentResume() {
    }

    @Override
    public void onComponentPause() {
    }

    @Override
    public int getLayoutId() {
        return R.layout.empty_control_video;
    }

    @Override
    protected void touchSurfaceMoveFullLogic(float absDeltaX, float absDeltaY) {
        super.touchSurfaceMoveFullLogic(absDeltaX, absDeltaY);
        //不给触摸快进，如果需要，屏蔽下方代码即可
        mChangePosition = false;

        //不给触摸音量，如果需要，屏蔽下方代码即可
        mChangeVolume = false;

        //不给触摸亮度，如果需要，屏蔽下方代码即可
        mBrightness = false;
    }

    @Override
    protected void touchDoubleUp() {
        //super.touchDoubleUp();
        //不需要双击暂停
    }

    class MyVideoAllCallBack implements VideoAllCallBack {

        @Override
        public void onPrepared(String url, Object... objects) {

        }

        @Override
        public void onClickStartIcon(String url, Object... objects) {

        }

        @Override
        public void onClickStartError(String url, Object... objects) {

        }

        @Override
        public void onClickStop(String url, Object... objects) {

        }

        @Override
        public void onClickStopFullscreen(String url, Object... objects) {

        }

        @Override
        public void onClickResume(String url, Object... objects) {

        }

        @Override
        public void onClickResumeFullscreen(String url, Object... objects) {

        }

        @Override
        public void onClickSeekbar(String url, Object... objects) {

        }

        @Override
        public void onClickSeekbarFullscreen(String url, Object... objects) {

        }

        @Override
        public void onAutoComplete(String url, Object... objects) {
            startNext();
        }

        @Override
        public void onEnterFullscreen(String url, Object... objects) {

        }

        @Override
        public void onQuitFullscreen(String url, Object... objects) {

        }

        @Override
        public void onQuitSmallWidget(String url, Object... objects) {

        }

        @Override
        public void onEnterSmallWidget(String url, Object... objects) {

        }

        @Override
        public void onTouchScreenSeekVolume(String url, Object... objects) {

        }

        @Override
        public void onTouchScreenSeekPosition(String url, Object... objects) {

        }

        @Override
        public void onTouchScreenSeekLight(String url, Object... objects) {

        }

        @Override
        public void onPlayError(String url, Object... objects) {
            startNext();
            Logger.e("视频播放错误 %s", url);
        }

        @Override
        public void onClickStartThumb(String url, Object... objects) {

        }

        @Override
        public void onClickBlank(String url, Object... objects) {

        }

        @Override
        public void onClickBlankFullscreen(String url, Object... objects) {

        }
    }
}

创建代码
private void createVideoComponent(JsonObject component) {
        int[] size = getComponentSize(component);
        GSYVideoComponent videoComponent = new GSYVideoComponent(mContext, size[0], size[1], size[2], size[3]);

        List<QrCodeResource> videos = new ArrayList();
        JsonObject param = component.get("param").getAsJsonObject();
        JsonArray resArray = param.get("res") == null ? null : param.get("res").getAsJsonArray();
        if (resArray == null) {
            //创建一个提示文本
            addHintTextView(size, NOT_RES);
            return;
        }
        for (int i = 0; i < resArray.size(); i++) {
            QrCodeResource video = new QrCodeResource();
            JsonObject res = resArray.get(i).getAsJsonObject();
            String resourceLocalPath = res.get("resourceLocalPath").getAsString();
            video.resPath = resourceLocalPath;
            String qrCodeLocalPath = res.get("qrCodeLocalPath") == null ? null : res.get("qrCodeLocalPath").getAsString();
            if (qrCodeLocalPath != null) {
                JsonObject qrcode = res.get("qrcode").getAsJsonObject();
                int logoLeft = qrcode.get("x").getAsInt();
                int logoTop = qrcode.get("y").getAsInt();
                video.codePath = qrCodeLocalPath;
                video.left = logoLeft;
                video.top = logoTop;
            }
            videos.add(video);
        }

        List<QrCodeResource> existResource = getExistResource(videos);
        if (existResource.size() > 0) {
            videoComponent.setQrCodeResource(videos);
            videoComponent.start();
            addView(videoComponent);
        } else {
            //创建一个提示文本
            addHintTextView(size, NOT_RES);
        }
    }

**Comment by CarGuo** [comment]
卡顿是怎么样的卡顿法？什么情况下触发的卡顿？demo中要怎么复现

**Comment by CleverSJX** [comment]
这个视频 播放器来很卡 http://s.swao.cn/o_1c4gm8o1nniu1had13bk1t0l1rq64m.mov 你试一下  我是在4.4.2的电视设备上播放的

**Comment by CleverSJX** [comment]
就是一卡一卡的

**Comment by CarGuo** [comment]
我把视频下载下来本地播放之后发现并不会，不过一分40秒的视频186M，大概最少需要一秒1.8M/S的缓冲，我用网络播放的现象看起来是网络卡····

**Comment by CleverSJX** [comment]
我是下载到本地播放的  我7.0的手机上播放不卡顿  这个4.4电视上卡顿 都是下载到本地播放的

**Comment by CarGuo** [comment]
那你可以试试问题集锦中的丢帧处理，试试丢帧25到30之间的参数看看，不过对于5.0以下的，已经不怎么想去支持了。

**Comment by CarGuo** [comment]
不过我个人觉得也和硬件状态有关系，高清高帧率的源，毕竟解码和渲染对于硬件依赖也挺大的。

**Comment by CleverSJX** [comment]
还是之前的视频 我把视屏压缩了 只有15M 还是卡顿   http://s.swao.cn/o_1cb9e0749eit58h1u6d1sir1jrj6e.mp4
