### ISSUE TITLE
切换至横屏时一定几率报空指针错误

### ISSUE THREAD

**Issue by Leu-Z** [CarGuo/GSYVideoPlayer#758]
1、使用StandardGSYVideoPlayer作为播放控件
2、使用orientationUtils.resolveByClick();调整成横屏，一定几率报空指针,getDuration();
3、红米note3，5.0.2。

**Comment by CarGuo** [comment]
demo中哪个页面可复现

**Comment by Leu-Z** [comment]
demo中未出现，因为demo里没有用StandardGSYVideoPlayer作为播放控件的例子

**Comment by CarGuo** [comment]
demo中所有的都是继承与StandardGSYVideoPlayer

**Comment by Leu-Z** [comment]
应该是没有设置android:configChanges="orientation|keyboardHidden|screenSize"的原因，这种情况下会一定几率出现这个问题
