### ISSUE TITLE
切换至横屏后orientationUtils.getScreenType()获取的依然是竖屏状态

### ISSUE THREAD

**Issue by Leu-Z** [CarGuo/GSYVideoPlayer#759]
1、使用StandardGSYVideoPlayer作为播放控件
2、使用orientationUtils.resolveByClick();调整成横屏，之后按返回键走到onBackPressed()方法内，orientationUtils.getScreenType()获取到依旧是竖屏状态，无法区分横竖屏。
3、红米note3，5.0.2。

**Comment by CarGuo** [comment]
请参考demo，你这个应该是manifest没有配置，然后状态可以通过player.getCurrentPlayer().isIfCurrentIsFullscreen()去判断

**Comment by Leu-Z** [comment]
感谢，是没有设置android:configChanges="orientation|keyboardHidden|screenSize"的原因
