### ISSUE TITLE
视频用4G流量播放时，会弹出一个没有按键的提示框。

### ISSUE THREAD

**Issue by zidanpiaoguo** [CarGuo/GSYVideoPlayer#760]
麻烦修复一下，在下面弹出一个toast  或者加一个确定，取消按钮

**Comment by CarGuo** [comment]
？？？

**Comment by zidanpiaoguo** [comment]
就是在流量播放的时候会弹出一个

**Comment by zidanpiaoguo** [comment]
就是流量播放，中间会弹出一个框说，您当前正在使用移动网络，然后也没有确定键。没法继续播放

**Comment by zidanpiaoguo** [comment]
我找了半天，也不知道你在哪里写了那个提示框。

**Comment by zidanpiaoguo** [comment]
就是提示： 您当前正在使用移动网络，继续播放将消耗流量，好像在左下角有一个确定键，但是看不见/

**Comment by zidanpiaoguo** [comment]
我找到问题了，你用的系统的AlertDialog。 而这个dialog 会收到application 的style影响，我把他的theme 设置成了白色，你那个AlertDialog 也会受到影响，变成了白色。如果博主有时间，可以重写一个dialog .不要用系统的。

**Comment by CarGuo** [comment]
你继承播放器，重写showwifixxxxx那个方法就好了
