### ISSUE TITLE
上面是播放器,下面是视频列表,,点击列表里的某个视频进行播放该调用哪个方法?

### ISSUE THREAD

**Issue by xuqinghao1991** [CarGuo/GSYVideoPlayer#762]
是detailPlayer.startPlayLogic();这个吗?

**Comment by CarGuo** [comment]
点击的时候setup之后播放

**Comment by xuqinghao1991** [comment]
您的意思是
detailPlayer.setUp(url, true, 0);
直接调用这个方法就行了?

**Comment by CarGuo** [comment]
点击需要播放的item时，对player重新setup，之后调用startplaylogic
