### ISSUE TITLE
 line='RTSP/1.0 404 Not Found'

### ISSUE THREAD

**Issue by YinWeiLF** [CarGuo/GSYVideoPlayer#766]
E/IJKMEDIA: method OPTIONS failed: 404 Not Found ，对于不同的rtsp地址，来回切换一下就出现这个错误，必须重新启动app才能解决

**Comment by CarGuo** [comment]
不是很理解，来回切换？？每次切换播放，都需要setup之后重新startplaylogic

**Comment by YinWeiLF** [comment]
是这样的，例如：我有两个rtsp的播放列表，我先选择其中一个列表中任意一个地址播放，可以播放，然后我退出当前列表，选择另一个rtsp的列表就报这个错误了

**Comment by CarGuo** [comment]
在demo中需要怎么复现？

**Comment by CarGuo** [comment]
初步怀疑是服务端的问题，因为用两个rtsp，一个你的，一个其他的可以正常切换。
rtsp://cloud.easydarwin.org:554/stream0.sdp

**Comment by YinWeiLF** [comment]
嗯，但是在vlc这类软件中来回切换是没有问题的，哎，让我很郁闷

**Comment by CarGuo** [comment]
可以和服务端调试下为什么会有404，我也很奇怪，就算是tcp链接，在release之后再setup之后播放应该没问题。主要还是为什么是404

**Comment by YinWeiLF** [comment]
这个是海康的摄像头rtsp的请求方式，服务器就是摄像头nvr，没有办法看日志。我现想因为是重启（彻底退出）之后再看另一个也没有问题了，那么是不是这之间有什么东西没有释放干净？

**Comment by CarGuo** [comment]
是很奇怪，目前还没明白，为何之外这两个url下会出现，而退出以后却不会

**Comment by YinWeiLF** [comment]
测试了一下，ijkplayer 是没有这个问题的

**Comment by CarGuo** [comment]
ijkplayer的demo？你用的哪个so？也是"rtsp_transport", "tcp"么？

**Comment by CarGuo** [comment]
ijkplayer的demo？你用的哪个so？也是"rtsp_transport", "tcp"么？

**Comment by YinWeiLF** [comment]
嗯 是的，应该不是so库的问题，我替换了你的demo中的so，还是一样的，是不是哪个小地方没有处理好？

**Comment by CarGuo** [comment]
或者你可以换多一个不是相似的url，看起来是在解析的时候没接触路径，但是目前还没看出来什么问题

**Comment by CarGuo** [comment]
刚刚一不小心点错了

**Comment by CarGuo** [comment]
刚刚我是了，并非退出之后就可以播放。
而是解析了第一个url之后，无论如何都解析不到第二个url，rtsp的404我依稀记得是解析问题。
我是在这种场景下测试，打开页面播放第一个url之后，退出再进入播放第二个url，第二个url无论如何都解析不出来，但是第一个url一直可以。
至于ijkdemo我等下试试看看

**Comment by YinWeiLF** [comment]
嗯 不是退出，是杀死进程，彻底结束应用之后才可以。我试了半天，想找到个简单的解决方案，不想替换使用ijkplayer，那样改动太大。

**Comment by CarGuo** [comment]
我在ijk demo中测试，也是一样的。
我是在SampleMediaListFragment中，mAdapter.addItem加上两个url，播放第一个之后退出，点击播放第二个，一样出现问题。

**Comment by YinWeiLF** [comment]
咦，我这边测试没有问题啊，`        mAdapter.addItem("rtsp://ajj:ajj12345678@218.21.217.122:65522/h264/ch15/sub/av_stream", "bipbop basic master playlist");
        mAdapter.addItem("rtsp://ajj:12345678@218.21.217.122:65523/h264/ch40/sub/av_stream", "bipbop basic 400x300 @ 232 kbps");`

**Comment by CarGuo** [comment]
也是设置了tcp吗？我用最新的demo播放第一个之后再播放第二个会出现unknown的弹框


https://stackoverflow.com/questions/11203953/why-do-i-get-rtsp-1-0-404-not-found

下面是解析出来的信息
```
 SDP:
                                                                        v=0
                                                                        o=- 1109162014219182 0 IN IP4 0.0.0.0
                                                                        s=HIK Media Server V3.0.1
                                                                        i=HIK Media Server Session Description : standard
                                                                        e=NONE
                                                                        c=IN c=IN IP4 0.0.0.0
                                                                        t=0 0
                                                                        a=control:*
                                                                        a=range:npt=now-
                                                                        m=video 0 RTP/AVP 96
                                                                        i=Video Media
                                                                        a=rtpmap:96 H264/90000
                                                                        a=fmtp:96 profile-level-id=4D0014;packetization-mode=0;sprop-parameter-sets=Z00AFJWoWCWQ,aO48gA==
                                                                        a=control:trackID=video
                                                                        a=Media_header:MEDIAINFO=494D4B48010100000400000100000000000000000000000000000000000000000000000000000000;
                                                                        a=appversion:1.0
```

**Comment by YinWeiLF** [comment]
是so库不支持，找个支持rtsp的库就好了

**Comment by CarGuo** [comment]
你的意思是当前gsy的so库对rtsp的支持不完全？貌似我是记得我没处理sdp相关的，你有找到相关的么？

**Comment by YinWeiLF** [comment]
[armeabi.zip](https://github.com/CarGuo/GSYVideoPlayer/files/1662420/armeabi.zip)
[armeabi-v7a.zip](https://github.com/CarGuo/GSYVideoPlayer/files/1662421/armeabi-v7a.zip)
[x86.zip](https://github.com/CarGuo/GSYVideoPlayer/files/1662422/x86.zip)
替换下找个试试？

**Comment by CarGuo** [comment]
其实如果有编译脚本配置更好

**Comment by CarGuo** [comment]
下个版本我看看把--enable-demuxer=sdp加上试试

**Comment by YinWeiLF** [comment]
嗯，这会确定了 应该是so库的问题，刚才又测试了一下，替换一下就没有问题了

**Comment by CarGuo** [comment]
嗯嗯，下个版本我更新下so支持sdp，到时候如果没问题我更新下issue

**Comment by YinWeiLF** [comment]
嗯嗯

**Comment by CarGuo** [comment]
话说你上次的这个so原出处时哪里？我想看看它的编译脚步

**Comment by CarGuo** [comment]
看起来像是还是解析的问题，不同于http与https之间切换的dns_cache问题，目前还没找到问题所在，如有时间可以劳烦告知下该so的出处吗？ @YinWeiLF

**Comment by YinWeiLF** [comment]
从这里下载的：http://download.csdn.net/download/a872822645/9889790

**Comment by CarGuo** [comment]
thx

**Comment by Movement123** [comment]
@CarGuo 请问大佬，除了加上sdp，还需要修改什么地方？
