### ISSUE TITLE
全屏时旋转手机先返回竖屏然后才返回全屏，怎样不返回竖屏呢

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#769]
全屏时旋转手机先返回竖屏然后又在返回全屏，怎样不返回竖屏呢
 onConfigurationChanged 如下代码：

 public void onConfigurationChanged(Configuration newConfig) {

     
       if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            orientationUtils.setIsLand(0);
            orientationUtils.resolveByClick();
        } else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT) {
            orientationUtils.setIsLand(0);
            orientationUtils.resolveByClick();
        }
        super.onConfigurationChanged(newConfig);

    }

**Comment by CarGuo** [comment]
参考demo

**Comment by yang0000meng** [comment]
demo 中好像没有相关代码。
请问下，可否说一下那个demo 
不知道是否说清楚我的问题，全屏时开启旋转功能， 
在旋转手机时，
竖着手机会切换到竖屏状态，
然后会自动切换到横屏状态。
我想让它 不切换，还是横屏，没有竖屏那一闪。

**Comment by CarGuo** [comment]
不是很理解，如果不需要竖屏再变全屏的话，demo中已经有了，你现在的情况是demo中的哪个页面会出现
