### ISSUE TITLE
关于进度条样式问题

### ISSUE THREAD

**Issue by loveRose** [CarGuo/GSYVideoPlayer#77]
提一个小建议，发现进度条在播放的时候 会根据前面时间的文字变化而进行动态移位调整，这应该是一个布局方面没注意的地方，应该将进度条俩端时间TextView的宽度固定

**Comment by CarGuo** [comment]
请问有对应截图吗？目前没发现这样的问题，因为播放的时间长度是不固定的，所以没设置，有可能到达三位数。

**Comment by loveRose** [comment]
并不是播放时间长度这个，而是比如秒钟是 01 与秒钟是 02 这二个字符所占位置会有所不同，因为TextView的宽度是包裹内容，内容变化  必定会引起整个宽度的调整，而进度条肯定是挨着TextView的，如TextView进行调整，进度条必定前移或后移动些许，这个截图没有，但是可以仔细观察得出来的
