### ISSUE TITLE
能不能实现跟西瓜视频那种效果

### ISSUE THREAD

**Issue by lingkongzhihe** [CarGuo/GSYVideoPlayer#770]
列表中播放，点击正在播放的视频视频不间断的播放动画移动到顶部，视频下面再出现其他布局这种效果

**Comment by CarGuo** [comment]
可以，不过目前还没有对应demo，如果有需要可能你需要参考源码或者等一段时候我加上这个demo，最近比较忙

**Comment by hongyang51** [comment]
@lingkongzhihe 同志 @CarGuo 你们实现了吗?

**Comment by CarGuo** [comment]
更新最新demo， 在 列表详情切换 item可以看到类似效果。
https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/switchplay
