### ISSUE TITLE
设置播放速率时会变调!

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#771]
第一次打开视频 设置播放速率时会变调 视频声音变尖
当关闭视频后 第二次打开该视频后 设置播放速率声调就正常 没有第一次尖锐
是什么情况;

**Comment by CarGuo** [comment]
souchtouch设置了吗？

**Comment by Born-alone** [comment]
你 Demo 里的 mSoundTounch 默认是 false 我设置播放速率的时候设置成 true 了

**Comment by Born-alone** [comment]
还是跟刚刚情况一样 把那个 mSoundTounch 值默认设置成 true 也是一样的表现

**Comment by CarGuo** [comment]
```
/**
     * 播放速度
     */
    public void setSpeed(float speed)
    /**
     * 播放速度
     *
     * @param speed      速度
     * @param soundTouch 是否对6.0下开启变速不变调
     */
    public void setSpeed(float speed, boolean soundTouch)

    /**
     * 播放中生效的播放数据
     *
     * @param speed
     * @param soundTouch
     */
    public void setSpeedPlaying(float speed, boolean soundTouch) 
```

**Comment by Born-alone** [comment]
customizeControlVideo.setSpeedPlaying(speed, true); 
我用的就是你Demo中的这个方法呀 情况都是一样的

**Comment by CarGuo** [comment]
你现在用的是gsy的哪个版本？依赖是？运行的系统版本是？我这边demo正常

**Comment by Born-alone** [comment]
依赖的 ： com.shuyu:GSYVideoPlayer:2.1.0
运行系统是 : MX5 5.1版本

**Comment by CarGuo** [comment]
有测试url么？我试试看，不过我这边目前只有6.0和8.0的机器

**Comment by CarGuo** [comment]
或者你用最新的demo在这个机器上试试。

**Comment by Born-alone** [comment]
http://120.132.18.193:8080/vod/2017/12/22/1513910320525459.mp4 这个是URL
我先把最新的更新下来 编译试试

**Comment by CarGuo** [comment]
我试了是不会变调，不过有一个问题，就是一般是>=0.5 - <=2.0，在2.0下感觉声音不连续，不过1.5下还行

**Comment by Born-alone** [comment]
能直接发一个新的Apk给我嘛 这边AS版本编译有点问题?

**Comment by CarGuo** [comment]
DetailControlActivity

[app-debug.zip](https://github.com/CarGuo/GSYVideoPlayer/files/1667134/app-debug.zip)

**Comment by Born-alone** [comment]
zip 
加载不出来.

**Comment by CarGuo** [comment]
可以下载的

**Comment by Born-alone** [comment]
apk好像损坏了 试了两个魅族手机都装不上

**Comment by Born-alone** [comment]
//是否不变调
protected boolean mSoundTouch = false; 
你这个是默认设置6.0以下变调？

**Comment by CarGuo** [comment]
是的
