### ISSUE TITLE
请问一下，支持直播吗？

### ISSUE THREAD

**Issue by jingzz1** [CarGuo/GSYVideoPlayer#773]
支持像 映客直播 那种视频类型的播放吗？

**Comment by CarGuo** [comment]
支持直播，hls，rtsp，rtmp等使用，依赖ex so即可

**Comment by jingzz1** [comment]
引入ex之后，还需要再引入armv7a吗？

**Comment by CarGuo** [comment]
不需要，就是java和exso

**Comment by jingzz1** [comment]
刚刚下载了demo看了一下，功能好齐全，而且使用很方便，谢谢博主分享，哈。
对了，没看到可以自定义操作控件的demo，请问是不是不支持自定义操作控件？

**Comment by jingzz1** [comment]
找到了，继承需要用到的播放器，然后重写getLayoutId() 方法，谢谢博主分享
