### ISSUE TITLE
最小版本兼容问题

### ISSUE THREAD

**Issue by xicong** [CarGuo/GSYVideoPlayer#774]
lib最低版本16  我项目14
按照提示加了tools:overrideLibrary="com.shuyu.gsyvideoplayer.lib"还有提示错误

Error:java.lang.RuntimeException: Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.shuyu:gsyVideoPlayer-java:3.0.0] C:\Users\a\.gradle\caches\transforms-1\files-1.1\gsyVideoPlayer-java-3.0.0.aar\69f715115ad55784f6d6fd9b3f518e51\AndroidManifest.xml as the library might be using APIs not available in 14

**Comment by CarGuo** [comment]
是的，现在的是16，如果你是14的话，就用tools:overrideLibrary去覆盖吧，已经没打算支持16以下的。

**Comment by CarGuo** [comment]
是的，现在的是16，如果你是14的话，就用tools:overrideLibrary去覆盖吧，已经没打算支持16以下的。

**Comment by xicong** [comment]
使用了那个方法覆盖了之后还提示

Error:java.lang.RuntimeException: Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.shuyu:gsyVideoPlayer-java:3.0.0] C:\Users\a.gradle\caches\transforms-1\files-1.1\gsyVideoPlayer-java-3.0.0.aar\69f715115ad55784f6d6fd9b3f518e51\AndroidManifest.xml as the library might be using APIs not available in 14

这个异常，不知道是什么原因那？麻烦指导一下

**Comment by CarGuo** [comment]
提示什么你加上什么就好了，比如
```
    <uses-sdk tools:overrideLibrary="com.shuyu.gsyvideoplayer.lib,com.shuyu.gsyvideoplayer,tv.danmaku.ijk.media.exo2,com.google.android.exoplayer2.ext.rtmp,com.shuyu.gsyvideoplayer.ex_so,shuyu.com.androidvideocache,net.butterflytv.rtmp_client"/>
```

**Comment by xicong** [comment]
好的，已经好了，谢谢，之前没注意里面有好几个lib，我只覆盖了一个所以有那个错误
