### ISSUE TITLE
开启全屏动画时，切换小屏幕，视频会上移一小块，然后就被标题栏遮住了。我还设置了一个右下角全屏的图标

### ISSUE THREAD

**Issue by iammasir** [CarGuo/GSYVideoPlayer#776]

**Comment by CarGuo** [comment]
请在demo中复现

**Comment by iammasir** [comment]
在DetailPlayer页面中，把.setShowFullAnimation(true)这样设置之后，从全屏切换回小屏幕就会导致播放的view上移，然后部分被遮盖住。

**Comment by iammasir** [comment]
还有个小问题，同样是在这个界面。seekbar上的那个白色圆球在开始和最后位置的时候，没有在那个轴上边，而是脱离了。这样看起来那个球和轴之间在开始和最后是没有接触的

**Comment by CarGuo** [comment]
```
开启全屏动画时，切换小屏幕，视频会上移一小块，然后就被标题栏遮住了。
```
这个问题，我再demo的DetailPlayer中，把setShowFullAnimation为true没重新出什么问题，可以截图看下吗？
然后seekbar首位不在上面也截图吗？我这边没看到这样的问题

**Comment by iammasir** [comment]
![Uploading QQ图片20180205181950.jpg…]()

**Comment by iammasir** [comment]
![qq 20180205181950](https://user-images.githubusercontent.com/20549531/35799724-9c38e406-0aa1-11e8-9b2e-7434be1fb198.jpg)

**Comment by iammasir** [comment]
![qq 20180205181944](https://user-images.githubusercontent.com/20549531/35799732-a4906a98-0aa1-11e8-93c5-12c4cc56586b.jpg)

**Comment by iammasir** [comment]
第一个图片你看，有一部分被遮住了。第二个原点和进度条脱离了
