### ISSUE TITLE
急！视频经后台压缩后播放黑屏只有声音

### ISSUE THREAD

**Issue by Neils320** [CarGuo/GSYVideoPlayer#778]
急！视频经后台压缩后播放黑屏只有声音
为了实现播放是切换清晰度，后台压缩将视频进行压缩
原视频
http://139.159.210.108:8787/resources/resource/699/2017171312175414672.mp4
压缩后
http://139.159.210.108:8787/resources/resource/699/2017171312175414672.512.mp4
使用demo播放压缩后视频出现黑屏只有声音
使用ijkplay进行播放没有问题
请教一下！急！

**Comment by Neils320** [comment]
将so文件替换还是出现

**Comment by Neils320** [comment]
硬解也同样

**Comment by Neils320** [comment]
http://139.159.210.108:8787/resources/resource/699/2017171312175414672.mp4
http://139.159.210.108:8787/resources/resource/699/2017171312175414672.128.mp4

**Comment by Neils320** [comment]
GSYTextureRenderView中的SurfaceTextureListener onSurfaceTextureUpdated没有回调

**Comment by CarGuo** [comment]
请在demo中使用ex so测试

**Comment by Neils320** [comment]
可以了，粗心没看到，麻烦了谢谢
