### ISSUE TITLE
How to make it full screen and then make it small screen?

### ISSUE THREAD

**Issue by Farrukh381** [CarGuo/GSYVideoPlayer#781]
my app design is like youtube so i how to do add everything custom controls....

**Comment by CarGuo** [comment]
change demo `InputUrlDetailActivity`  like this

```
detailPlayer.setLockClickListener(new LockClickListener() {
            @Override
            public void onClick(View view, boolean lock) {
                /*if (orientationUtils != null) {
                    //配合下方的onConfigurationChanged
                    orientationUtils.setEnable(!lock);
                }*/
                onBackPressed();
                detailPlayer.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        int size = CommonUtil.dip2px(InputUrlDetailActivity.this, 150);
                        detailPlayer.showSmallVideo(new Point(size, size), true, true);
                        orientationUtils.setEnable(false);
                    }
                }, 500);
            }
        });
```

**Comment by CarGuo** [comment]
I think what you need is
```
 @Override
    public void onBackPressed() {

        if (orientationUtils != null) {
            orientationUtils.backToProtVideo();
        }

        if (GSYVideoManager.backFromWindowFull(this)) {
            return;
        }
        super.onBackPressed();
    }

```
don't forget ConfigurationChanged and manifest set acitvity like demo
```
  @Override
    public void onConfigurationChanged(Configuration newConfig) 
```

**Comment by Farrukh381** [comment]
cannot reslove backFromWindowFull method

**Comment by CarGuo** [comment]
sorry， `GSYVideoManager.backFromWindowFull(this)` is in dev
try this
```
  @Override
    public void onBackPressed() {

        if (orientationUtils != null) {
            orientationUtils.backToProtVideo();
        }

        if (StandardGSYVideoPlayer.backFromWindowFull(this)) {
            return;
        }
        super.onBackPressed();
    }

```

**Comment by Farrukh381** [comment]
thanks that issue is resolved now......but still facing few issues 
1)when the player on fullscreen, my custom controls which i added on player are hidden.....how can make them visible on full screen too.....(controls are chromecast icon,custom back button)

2) when screen on normal view, how can get the click listener or touch listener of player because default controls are hidden or shown on touch.....i want to hide or show my custom controls too....so i need to figure what is that touch or click listener

3) when video starts a ads popup because we have implemented an ad on video startup.....but the video get paused when ads i shown i want that it should not paused...


Great work and highly appreciated....i hope you will help in fixing these issues 
Thanks

**Comment by CarGuo** [comment]
1、you may need override `cloneParams` ,`startWindowFullscreen` , ` resolveNormalVideoShow`  method like sound code，see `SampleControlVideo`  in demo，because full screen player is clone from normal.
you can extend StandardGSYVideoPlayer and override `getLayoutId` to your custom ui.

“...ad on video startup.....but the video get paused when ads i shown i want that it should not paused...”
i not sure what you mean

**Comment by Farrukh381** [comment]
1) i mean that when the ads open it pause the player .....when ad is closed player dont resume itself 
ads open at start of stream.........http://prntscr.com/i83l3m
http://prntscr.com/i83ljk  .............player dont resume itself after ad is closed

2) i want to access the touch or click listener of player in my activity, it will resolve all my issues ..... i have figure out other things 

Thanks for you great help

**Comment by Farrukh381** [comment]
Any help on this?

**Comment by CarGuo** [comment]
i think next version will resolve it

**Comment by Farrukh381** [comment]
i want to access the touch or click listener of player.....just give some clue how to do that

**Comment by Farrukh381** [comment]
please provide some help on this because its a very big issue for me

**Comment by CarGuo** [comment]
see in newest demo like detailADPlayer2  or ListADVideoActivity
