### ISSUE TITLE
有些手机自己拍的视频 播放后进度条不停地后退

### ISSUE THREAD

**Issue by king19910525** [CarGuo/GSYVideoPlayer#782]
有些手机自己拍的视频 华为P9  可能是拍的质量较高，播放后进度条不停地后退，还会显示进度条和播放按钮  最后竟然出现播放时长 超过高总时长

**Comment by CarGuo** [comment]
可以提供url测试下么？

**Comment by king19910525** [comment]
现在测试环境 ，内网看不了，等发到外网再联系你吧，能给个联系方式吗？

**Comment by CarGuo** [comment]
到时候github上回复就可以

**Comment by king19910525** [comment]
好的

**Comment by fvaryu** [comment]
@king19910525  我有出现过这个问题  好像是视频分辨率太大的原因 @CarGuo
