### ISSUE TITLE
打开在线直播的视频流，按Home键后再回到app中，视频无法恢复播放

### ISSUE THREAD

**Issue by CharlieZheng** [CarGuo/GSYVideoPlayer#787]

**Comment by hardgit** [comment]
菜鸟上路，开始播放，暂停播放API是哪个？

**Comment by CarGuo** [comment]
新增加方法，onResume不seekto

**Comment by Totomiz** [comment]
Home键退出后，在进入app,我这是有声音，进度条也在走，但是画面没有动，重写了onVideoResume（），其中调用 onVideoResume(false); 没解决问题，还是我设置有误呢
