### ISSUE TITLE
如何使用 按键(遥控器) 对 ui 的控制 。例如在 TV 

### ISSUE THREAD

**Issue by xie123** [CarGuo/GSYVideoPlayer#788]
1. 图1  的这里 我想把 界面显示出来 ， 手动调用
  clickStartIcon();
   onClickUiToggle();
界面并没有 随着出现。

![image](https://user-images.githubusercontent.com/7463283/35569161-54984f78-0606-11e8-89f6-25060cccee4b.png)

**Comment by xie123** [comment]
按道理讲， 在onClickUiToggle() 中明明调用了ui 的状态 改变 的方法

**Comment by xie123** [comment]
然后点击事件就是有用

**Comment by CarGuo** [comment]
这个只能说你自己断点跟踪什么情况了

**Comment by xie123** [comment]
哎， 没有办法 源码看完 了，都不懂 ，没有办法 强行模拟触摸事件
