### ISSUE TITLE
请问可以在嵌套的子Fragment中使用播放器嘛？

### ISSUE THREAD

**Issue by yangxiaobinhaoshuai** [CarGuo/GSYVideoPlayer#79]
总是报java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity;

stack 定位这一行
    ((Activity)this.getContext()).getWindow().addFlags(128);

点进去看prepare方法需要给activity窗口添加flag 会把conext强转Activity

**Comment by CarGuo** [comment]
可以，你的fragment所在的activity是什么？参考demo中的activity，推荐v7支持包的那个。
