### ISSUE TITLE
使用StandardGSYVideoPlayer,怎么设置进入Activity之后立即播放,无需点播放按钮

### ISSUE THREAD

**Issue by Kevin1ee** [CarGuo/GSYVideoPlayer#790]
如何判断视频已经缓冲完毕,是可以播放的状态,没有看到相应的回调?

**Comment by CarGuo** [comment]
startplaylogic播放。
VideoAllCallBack 的 onPrepared是准备好了

**Comment by o03150** [comment]
@CarGuo 暂停和恢复的回调在哪?VideoAllCallBack 只有点击按钮的回调
