### ISSUE TITLE
自定义布局中有两个开始按钮,如何解决？

### ISSUE THREAD

**Issue by bingdu0** [CarGuo/GSYVideoPlayer#795]
自定义布局中有两个开始按钮，中间一个，左下角一个，但是id=“@+id/start” 只能写一个，怎么解决？

**Comment by CarGuo** [comment]
继承，参考源码增加多一个

**Comment by CarGuo** [comment]
继承，参考源码增加多一个

**Comment by bingdu0** [comment]
继承哪个类？有demo吗？

**Comment by CarGuo** [comment]
一般继承StandardGSYVideoPlayer，然后返回你自己的布局，然后加上你自己的id的控件逻辑
