### ISSUE TITLE
通过 IJKEXOPLAYER2 播放视频 横竖屏切换 黑屏 播放错误

### ISSUE THREAD

**Issue by yiShanXin** [CarGuo/GSYVideoPlayer#797]
## 小米手机问题
    
     1.  红米 系统版本4.4    黑屏
     2.  小米4  6.0.1  反复几次横竖屏切换 黑屏
  `E/GSYVideoPlayer: onConfigurationChanged 2
02-02 16:09:19.450 15241-20423/com.example.gsyvideoplayer E/BufferQueueProducer: [SurfaceTexture-0-15241-43] queueBuffer: BufferQueue has been abandoned
02-02 16:09:19.450 15241-20423/com.example.gsyvideoplayer E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
02-02 16:09:19.450 15241-20423/com.example.gsyvideoplayer E/ACodec: queueBuffer failed in onOutputBufferDrained: -19
02-02 16:09:19.450 15241-20423/com.example.gsyvideoplayer E/ACodec: signalError(omxError 0x80001001, internalError -19)
02-02 16:09:19.453 15241-20422/com.example.gsyvideoplayer E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
02-02 16:09:19.457 15241-20414/com.example.gsyvideoplayer E/ExoPlayerImplInternal: Internal runtime error.
                                                                                   java.lang.IllegalStateException
                                                                                       at android.media.MediaCodec.native_setSurface(Native Method)
                                                                                       at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1797)
                                                                                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:841)
                                                                                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:369)
                                                                                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:336)
                                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessagesInternal(ExoPlayerImplInternal.java:839)
                                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:342)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
02-02 16:09:19.458 15241-15256/com.example.gsyvideoplayer E/EventLogger: playerFailed [20.71]
                                                                         com.google.android.exoplayer2.ExoPlaybackException
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                          Caused by: java.lang.IllegalStateException
                                                                             at android.media.MediaCodec.native_setSurface(Native Method)
                                                                             at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1797)
                                                                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:841)
                                                                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:369)
                                                                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:336)
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessagesInternal(ExoPlayerImplInternal.java:839)
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:342)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61) 
02-02 16:09:19.466 15241-20423/com.example.gsyvideoplayer E/Surface: getSlotFromBufferLocked: unknown buffer: 0x96e03720`

  怎么排查问题呢，感谢

**Comment by CarGuo** [comment]
demo中哪个页面复现

**Comment by CarGuo** [comment]
EXO的使用 GSYVideoType.setRenderType(GSYVideoType.SUFRACE);

**Comment by yiShanXin** [comment]
首先感谢回复具体参数设置，如果通过SUFRACE 去设置，前后台切换 DetailPlayer 视频继续播放，但是进度一直在缓冲中 而且当前播放进度也不会变

**Comment by CarGuo** [comment]
前后台切换 DetailPlayer 视频继续播放，进度一直在缓冲中??? 不是很理解 GSYVideoType.setRenderType(GSYVideoType.SUFRACE); 是一个全局设置，一般在Application中设置。
一直缓冲和设置渲染没有关系

**Comment by yiShanXin** [comment]
代码改动   Application   初始化 
   1.  EXO 播放  
   2. SUFRACE
   播放一个  hls 链接
   我尝试测试下常用case 也许没有太大关系，我只是描述下，设置SUFRACE后该项目引起的一个问题 ！没有任何其他意思
    ![device-2018-02-05-103912.png](https://i.loli.net/2018/02/05/5a77c3e13b474.png)

**Comment by yiShanXin** [comment]
reply " onResume的时候会进度变为一直缓冲，实际视频在播放"
    貌似和 hls 没关系，图中是一个hls 点播资源，我用项目自带demo 播放的mp4 , 按照参数设置后，也复现，以上是周末自己尝试实验得到的问题 ，有疑问就想问问lz！

**Comment by yiShanXin** [comment]
如下图: 前后台切换，此刻视频正在播放 
![device-2018-02-05-105554.png](https://i.loli.net/2018/02/05/5a77c8c56d5f5.png)

**Comment by CarGuo** [comment]
我这边直接demo运行没发现这个问题，不是很理解你这个问题。前后台切换就是暂停和继续播放。

**Comment by yiShanXin** [comment]
看着个这个小视频吧，注意第二次 前后台切换，当前视频播放的时间 和当前播放进度 以及缓冲进度
  https://www.dropbox.com/s/0liuqtbkrwj2r12/device-2018-02-05-111126.mp4?dl=0

**Comment by CarGuo** [comment]
打不开这个视频

**Comment by yiShanXin** [comment]
https://pan.baidu.com/s/1ggtAR1D

**Comment by yiShanXin** [comment]
[device-2018-02-05-111126.mp4.zip](https://github.com/CarGuo/GSYVideoPlayer/files/1694251/device-2018-02-05-111126.mp4.zip)

**Comment by CarGuo** [comment]
你是3.0.0的版本？我这边试了正常，看起来像是MEDIA_INFO_BUFFERING_END没回调到
```
@Override
    public void onInfo(int what, int extra) {
        if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START) {
           
        } else if (what == MediaPlayer.MEDIA_INFO_BUFFERING_END) {
         }
```

**Comment by yiShanXin** [comment]
项目默认版本 (3.0.0)
     我就改了  gradle配置,   gradle:2.3.+
      `classpath 'com.android.tools.build:gradle:2.3.+'`

**Comment by CarGuo** [comment]
和 gradle版本不会有什么关系
你是用
```
GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
```
这个模式是吧，你可以看看GSYVideoView.java下的
```
    @Override
    public void onInfo(int what, int extra) 
```
在buffer结束的时候是否没有调用
对应IjkExo2MediaPlayer.java下有

```
@Override
    public void onPlayerStateChanged(boolean playWhenReady, int playbackState) 
```

**Comment by yiShanXin** [comment]
回调日志
`02-05 16:34:21.511 3438-3470/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = false, playbackState = 2
02-05 16:34:21.890 3438-3470/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = false, playbackState = 3
02-05 16:34:21.890 3438-3438/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = true, playbackState = 3
02-05 16:34:36.673 3438-3438/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = false, playbackState = 3
02-05 16:34:41.672 3438-3470/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = false, playbackState = 2
02-05 16:34:41.672 3438-3438/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = true, playbackState = 2
02-05 16:34:42.179 3438-3470/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = true, playbackState = 3
02-05 16:35:43.411 3438-3438/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = false, playbackState = 3
02-05 16:35:45.726 3438-3470/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = false, playbackState = 2
02-05 16:35:45.729 3438-3438/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = true, playbackState = 2
02-05 16:35:46.267 3438-3470/com.example.gsyvideoplayer E/IjkExo2MediaPlayer: onPlayerStateChanged: playWhenReady = true, playbackState = 3
`

**Comment by CarGuo** [comment]
最后的 playbackState = 3 应该是会通知缓冲结束的，
```
 notifyOnInfo(IMediaPlayer.MEDIA_INFO_BUFFERING_END, mInternalPlayer.getBufferedPercentage());
```

可以看下是mIsBuffering或者在外层的if是不是哪里不会导致没有回调出来。

**Comment by CarGuo** [comment]
找到问题了，是onInfo下的 mBackUpPlayingBufferState ， exo2回调出来导致backup的时候mCurrentState有几率是buffering的，然后导致保存下来的状态还是buffering，所以缓存结束了还显示缓冲

**Comment by CarGuo** [comment]
目前继承播放器。重载可解决。
```
@Override
    public void onInfo(int what, int extra) {
        if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START) {
            mBackUpPlayingBufferState = mCurrentState;
            //避免在onPrepared之前就进入了buffering，导致一只loading
            if (mHadPlay && mCurrentState != CURRENT_STATE_PREPAREING && mCurrentState > 0)
                setStateAndUi(CURRENT_STATE_PLAYING_BUFFERING_START);

        } else if (what == MediaPlayer.MEDIA_INFO_BUFFERING_END) {
            if (mBackUpPlayingBufferState != -1) {
                if (mBackUpPlayingBufferState == CURRENT_STATE_PLAYING_BUFFERING_START) {
                    mBackUpPlayingBufferState = CURRENT_STATE_PLAYING;
                }
                if (mHadPlay && mCurrentState != CURRENT_STATE_PREPAREING && mCurrentState > 0)
                    setStateAndUi(mBackUpPlayingBufferState);

                mBackUpPlayingBufferState = -1;
            }
        } else if (what == IMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED) {
            mRotate = extra;
            Debuger.printfLog("Video Rotate Info " + extra);
            if (mTextureView != null)
                mTextureView.setRotation(mRotate);
        }
    }
```

**Comment by yiShanXin** [comment]
恩 ！ 发现问题就行，我主要是看小窗口的实现思路

**Comment by yiShanXin** [comment]
现象: 通过 IJKEXOPLAYER2 播放视频  横竖屏切换 黑屏
           红米 系统版本4.4    黑屏  
   配置

   GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);
   GSYVideoType.setRenderType(GSYVideoType.SUFRACE);  
    
   DetailPlayer 界面  ，横竖屏切换重复 2次 [必现]

**Comment by CarGuo** [comment]
最新demo复现？我这边没法重现

**Comment by yiShanXin** [comment]
最新 Demo 
   播放的是 mp4 资源 ，非网络问题  视频如下


[device-2018-03-07-113950.zip](https://github.com/CarGuo/GSYVideoPlayer/files/1787686/device-2018-03-07-113950.zip)

**Comment by yangfeng1994** [comment]
层主的这种情况，我也遇到了，但是重置了那个方法，还是没有解决。

**Comment by yang0000meng** [comment]
我这边也遇到
在加载过程中，加载速度为0kb 
（已经屏蔽竖屏）
 全屏和普通切换几次 最后会卡死在竖屏不能返回

**Comment by CarGuo** [comment]
fix 5.0.0-beta

**Comment by yangfeng1994** [comment]
您好，我也遇到了，这样虽然已经修复了，
       GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2); //EXO 2 播放内核
        GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
但是视频播放开始会黑屏一下，不知道是不是我设置封面的原因。

**Comment by CarGuo** [comment]
更新到5.0.0 beta，把surface模式去掉

**Comment by CarGuo** [comment]
@yangfeng1994 参考demo的SampleCoverVideo

**Comment by yangfeng1994** [comment]
谢谢回复，我写了两个自定义的播放器，一个是能全屏的，一个是不能全屏的，列表非全屏的我用了您的方法，引起封面不消失，但是我在onPrepared  的时候，我调用   if (mThumbImageViewLayout != null && mThumbImageViewLayout.getVisibility() == VISIBLE) {
            mThumbImageViewLayout.setVisibility(INVISIBLE);
        } 
是可以的。
在列表全屏的 也是引起封面不消失。有可能是因为我重写了挺多方法的原因引起的。我等下代码贴一下。

**Comment by yangfeng1994** [comment]
public class SampleGSYVideo extends StandardGSYVideoPlayer implements GSYVideoProgressListener {


    public SelectableRoundedImageView mCoverImage;
    private TextView mTvHint;
    private LottieAnimationView mLoadingView;
    public ImageView mIvStartButton;
    private SoybeanContentInfoPlus mData;
    private boolean isUploadValidPlay;//视频是否上传过
    private String mDomain;

    public String getDomain() {
        return mDomain;
    }

    public void setDomain(String domain) {
        this.mDomain = domain;
    }

    //亮度文本
    protected ProgressBar mBrightnessDialogProgressBar;

    public SampleGSYVideo(Context context, Boolean fullFlag) {
        super(context, fullFlag);
    }

    public SampleGSYVideo(Context context) {
        super(context);
    }

    public SampleGSYVideo(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    protected void init(Context context) {
        super.init(context);
        mCoverImage = findViewById(R.id.thumbImage);
        mTvHint = findViewById(R.id.tv_flow_hint);
        mLoadingView = findViewById(R.id.lottie_loading);
        mIvStartButton = findViewById(R.id.iv_start);
        mLoadingView.setAnimation("anim/soybean_anim_video_loading.json");
        if (mThumbImageViewLayout != null &&
                (mCurrentState == -1 || mCurrentState == CURRENT_STATE_NORMAL || mCurrentState == CURRENT_STATE_ERROR)) {
            mThumbImageViewLayout.setVisibility(VISIBLE);
        }
        setGSYVideoProgressListener(this);
    }

    @Override
    public void onInfo(int what, int extra) {
        if (what == MediaPlayer.MEDIA_INFO_BUFFERING_START) {
            mBackUpPlayingBufferState = mCurrentState;
            //避免在onPrepared之前就进入了buffering，导致一只loading
            if (mHadPlay && mCurrentState != CURRENT_STATE_PREPAREING && mCurrentState > 0)
                setStateAndUi(CURRENT_STATE_PLAYING_BUFFERING_START);

        } else if (what == MediaPlayer.MEDIA_INFO_BUFFERING_END) {
            if (mBackUpPlayingBufferState != -1) {
                if (mBackUpPlayingBufferState == CURRENT_STATE_PLAYING_BUFFERING_START) {
                    mBackUpPlayingBufferState = CURRENT_STATE_PLAYING;
                }
                if (mHadPlay && mCurrentState != CURRENT_STATE_PREPAREING && mCurrentState > 0)
                    setStateAndUi(mBackUpPlayingBufferState);

                mBackUpPlayingBufferState = -1;
            }
        } else if (what == IMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED) {
            mRotate = extra;
            Debuger.printfLog("Video Rotate Info " + extra);
            if (mTextureView != null)
                mTextureView.setRotation(mRotate);
        }
    }


    public void loadCoverImage() {
        RequestOptions options = new RequestOptions().placeholder(R.drawable.qy_drawable_radius_cover_default)
                .error(R.drawable.qy_drawable_radius_cover_default);
        if (null != mData) {
            String cover = mData.getCover();
            cover = String.format("%s%s", getDomain(), cover);
            Glide.with(mContext).load(cover).apply(options).into(mCoverImage);
        } else {
            Glide.with(mContext)
                    .load(R.drawable.qy_drawable_radius_cover_default)
                    .into(mCoverImage);
        }
    }

    public SoybeanContentInfoPlus getData() {
        return mData;
    }

    public SampleGSYVideo setData(SoybeanContentInfoPlus mData) {
        this.mData = mData;
        return this;
    }

    public void setUploadValidPlay(boolean uploadValidPlay) {
        isUploadValidPlay = uploadValidPlay;
    }

    public boolean getUploadValidPlay() {
        return isUploadValidPlay;
    }

    @Override
    protected void cloneParams(GSYBaseVideoPlayer from, GSYBaseVideoPlayer to) {
        super.cloneParams(from, to);
        SoybeanContentInfoPlus mFromData = null;
        boolean mIsUploadValidPlay = false;
        if (from instanceof SampleGSYVideo) {
            SampleGSYVideo mFrom = (SampleGSYVideo) from;
            mFromData = mFrom.getData();
            mIsUploadValidPlay = mFrom.getUploadValidPlay();
        }
        if (to instanceof SampleGSYVideo) {
            ((SampleGSYVideo) to).setData(mFromData);
            ((SampleGSYVideo) to).setUploadValidPlay(mIsUploadValidPlay);
        }
    }

    @Override
    public int getLayoutId() {
        return R.layout.simp_gsy_video;
    }

    @Override
    protected int getProgressDialogLayoutId() {
        return R.layout.gsy_video_progress_dialog;
    }

    @Override
    protected int getVolumeLayoutId() {
        return R.layout.gsy_video_volume_dialog;
    }

    @Override
    protected int getBrightnessLayoutId() {
        return R.layout.gsy_video_brightness;
    }

    @Override
    protected int getBrightnessTextId() {
        return R.id.app_video_brightness;
    }

    @Override
    public GSYBaseVideoPlayer startWindowFullscreen(Context context, boolean actionBar, boolean statusBar) {
        GSYBaseVideoPlayer gsyBaseVideoPlayer = super.startWindowFullscreen(context, actionBar, statusBar);
        SampleGSYVideo sampleCoverVideo = (SampleGSYVideo) gsyBaseVideoPlayer;
        sampleCoverVideo.loadCoverImage();
        return gsyBaseVideoPlayer;
    }

    @Override
    public void onBackFullscreen() {
        super.onBackFullscreen();
        dismissBrightnessDialog();
        dismissProgressDialog();
        dismissVolumeDialog();
    }

    @Override
    public int getEnlargeImageRes() {
        return R.drawable.soybean_ic_video_full_screen;
    }

    @Override
    public int getShrinkImageRes() {
        return R.drawable.soybean_ic_video_exit_full_screen;
    }

    @Override
    public void startPlayLogic() {
        super.startPlayLogic();
    }

    /**下方两个重载方法，在播放开始前不屏蔽封面*/
    @Override
    public void onSurfaceUpdated(Surface surface) {
        super.onSurfaceUpdated(surface);
        if (mThumbImageViewLayout != null && mThumbImageViewLayout.getVisibility() == VISIBLE) {
            mThumbImageViewLayout.setVisibility(INVISIBLE);
        }
    }

    @Override
    protected void setViewShowState(View view, int visibility) {
        if (view == mThumbImageViewLayout && visibility != VISIBLE) {
            return;
        }
        super.setViewShowState(view, visibility);
    }


    @Override
    protected void updateStartImage() {
        super.updateStartImage();
        if (mStartButton instanceof FrameLayout) {
            if (mCurrentState == CURRENT_STATE_PLAYING) {
                mIvStartButton.setImageResource(R.drawable.soybean_small_video_pause);
            } else if (mCurrentState == CURRENT_STATE_ERROR) {
                mIvStartButton.setImageResource(R.drawable.soybean_ic_video_btn_play_default);
            } else {
                mIvStartButton.setImageResource(R.drawable.soybean_ic_video_btn_play_default);
            }
        }
        if (mTvHint.getVisibility() == VISIBLE) {
            mTvHint.setVisibility(GONE);
        }
    }

    @Override
    public void onError(int what, int extra) {
        if (mNetChanged) {
            mNetChanged = false;
            netWorkErrorLogic();
            if (mVideoAllCallBack != null) {
                mVideoAllCallBack.onPlayError(mOriginUrl, mTitle, this);
            }
            return;
        }
        if (what != 38 && what != -38) {
            setStateAndUi(CURRENT_STATE_ERROR);
            deleteCacheFileWhenError();
            if (mVideoAllCallBack != null) {
                mVideoAllCallBack.onPlayError(mOriginUrl, mTitle, this);
            }
        }
    }

    /**
     * 视频播放出错
     */
    public void changeUiToShowError() {
        if (null == mIvStartButton || null == mTvHint) {
            return;
        }
        mIvStartButton.setImageResource(R.drawable.soybean_ic_video_btn_play_error);
        if (!NetworkUtils.isNetworkConnected(getContext())) {
            mTvHint.setText("网络连接错误，请检查网络");
        } else {
            mTvHint.setText("T T 加载失败了");
        }
        mTvHint.setVisibility(VISIBLE);
    }

    @Override
    protected void netWorkErrorLogic() {
        super.netWorkErrorLogic();
        mIvStartButton.setImageResource(R.drawable.soybean_ic_video_btn_play_error);
        mTvHint.setText("网络连接错误，请检查网络");
        mTvHint.setVisibility(VISIBLE);
    }

    /**
     * 全部准备好，视频开始播放
     */
    @Override
    public void onPrepared() {
        super.onPrepared();
        if (mThumbImageViewLayout != null && mThumbImageViewLayout.getVisibility() == VISIBLE) {
            mThumbImageViewLayout.setVisibility(INVISIBLE);
        }
        if (null != mLoadingView) {
            mLoadingView.playAnimation();
        }
        StatisticsManager.getInstance().uploadIncidentStatistics(mContext, "soybean_video_play");
        postVideoPlay();
    }

    @Override
    protected void changeUiToNormal() {
        super.changeUiToNormal();
        inVisibleTopContainer();
        if (null != mLoadingView) {
            mLoadingView.pauseAnimation();
        }
    }

    @Override
    protected void changeUiToPreparingShow() {
        super.changeUiToPreparingShow();
        inVisibleTopContainer();
        if (null != mLoadingView) {
            mLoadingView.playAnimation();
        }
    }

    @Override
    protected void changeUiToPlayingShow() {
        super.changeUiToPlayingShow();
        inVisibleTopContainer();
        if (null != mLoadingView) {
            mLoadingView.pauseAnimation();
        }
    }

    @Override
    protected void changeUiToPauseShow() {
        super.changeUiToPauseShow();
        inVisibleTopContainer();
        if (null != mLoadingView) {
            mLoadingView.pauseAnimation();
        }
    }

    @Override
    protected void changeUiToPlayingBufferingShow() {
        super.changeUiToPlayingBufferingShow();
        inVisibleTopContainer();
        if (null != mLoadingView) {
            mLoadingView.playAnimation();
        }
    }

    @Override
    protected void changeUiToCompleteShow() {
        super.changeUiToCompleteShow();
        inVisibleTopContainer();
        if (null != mLoadingView) {
            mLoadingView.pauseAnimation();
        }
    }

    @Override
    protected void changeUiToError() {
        super.changeUiToError();
        if (null != mLoadingView) {
            mLoadingView.pauseAnimation();
        }
    }

    @Override
    protected void changeUiToPrepareingClear() {
        super.changeUiToPrepareingClear();
        if (null != mLoadingView) {
            mLoadingView.pauseAnimation();
        }
    }

    @Override
    protected void changeUiToPlayingBufferingClear() {
        super.changeUiToPlayingBufferingClear();
        if (null != mLoadingView) {
            mLoadingView.playAnimation();
        }
    }

    @Override
    protected void changeUiToClear() {
        super.changeUiToClear();
        if (null != mLoadingView) {
            mLoadingView.pauseAnimation();
        }
    }

    @Override
    protected void changeUiToCompleteClear() {
        super.changeUiToCompleteClear();
        if (null != mLoadingView) {
            mLoadingView.pauseAnimation();
        }
    }

    @Override
    protected void showBrightnessDialog(float percent) {
        if (mBrightnessDialog == null) {
            View localView = LayoutInflater.from(getActivityContext()).inflate(getBrightnessLayoutId(), null);
            if (localView.findViewById(getBrightnessTextId()) instanceof ProgressBar) {
                mBrightnessDialogProgressBar = localView.findViewById(getBrightnessTextId());
            }
            mBrightnessDialog = new Dialog(getActivityContext(), R.style.video_style_dialog_progress);
            mBrightnessDialog.setContentView(localView);
            mBrightnessDialog.getWindow().addFlags(8);
            mBrightnessDialog.getWindow().addFlags(32);
            mBrightnessDialog.getWindow().addFlags(16);
            mBrightnessDialog.getWindow().setLayout(-2, -2);
            WindowManager.LayoutParams localLayoutParams = mBrightnessDialog.getWindow().getAttributes();
            localLayoutParams.gravity = Gravity.TOP | Gravity.RIGHT;
            localLayoutParams.width = getWidth();
            localLayoutParams.height = getHeight();
            int location[] = new int[2];
            getLocationOnScreen(location);
            localLayoutParams.x = location[0];
            localLayoutParams.y = location[1];
            mBrightnessDialog.getWindow().setAttributes(localLayoutParams);
        }
        if (!mBrightnessDialog.isShowing()) {
            mBrightnessDialog.show();
        }
        int brightnessPercent = (int) (percent * 100);
        if (mBrightnessDialogProgressBar != null) {
            mBrightnessDialogProgressBar.setProgress(brightnessPercent);
        }
    }


    @Override
    protected void dismissBrightnessDialog() {
        if (mBrightnessDialog != null) {
            mBrightnessDialog.dismiss();
            mBrightnessDialog = null;
        }
    }

    /**
     * 在小屏状态下，隐藏顶部的标题阴影部分
     */
    private void inVisibleTopContainer() {
        if (!mIfCurrentIsFullscreen) {
            if (null != mTopContainer) {
                mTopContainer.setVisibility(INVISIBLE);
            }
        }
    }

    /**
     * 视频播放时，发送事件给后台,进行统计
     * type 为6，是太更多视频，推荐播放的
     */
    private void postVideoPlay() {
        if (null == mData) {
            return;
        }
        APIManager.postADDContentBrowse(mData.getIdInt(), 0, 6, new LocalObserver((LocalActivity) null));
    }

    /**
     * @param progress
     * @param secProgress
     * @param currentPosition
     * @param duration
     */
    @Override
    public void onProgress(int progress, int secProgress, int currentPosition, int duration) {
        if (progress >= 50) {
            if (!isUploadValidPlay) {
                StatisticsManager.getInstance().uploadIncidentStatistics(mContext, "soybean_video_valid_play");
                isUploadValidPlay = true;
            }
        }
    }
}

这个是我自定义的播放器里面的   


  /**
     * 初始化视频播放器
     *
     * @param helper
     * @param item
     */
    private void initVideo(BaseViewHolder helper, SoybeanContentInfoPlus item) {
        SampleGSYVideo sampleGSYVideo = helper.getView(R.id.gsy_video);
        RequestOptions options = new RequestOptions().placeholder(R.drawable.qy_drawable_radius_cover_default)
                .error(R.drawable.qy_drawable_radius_cover_default);
        String cover = item.getCover();
        cover = String.format("%s%s", getDomain(), cover);
        Glide.with(mContext).load(cover).apply(options).into(sampleGSYVideo.mCoverImage);
        gsyVideoOptionBuilder = new GSYVideoOptionBuilder();
        sampleGSYVideo.setThumbPlay(true);
        sampleGSYVideo.setData(item);
        //防止错位，离开释放
        sampleGSYVideo.initUIState();
        String url = item.getContent();
        if (TextUtils.isEmpty(url)) {
            url = "http://www.baidu.com";
        }
        gsyVideoOptionBuilder
                .setIsTouchWiget(false)
                .setDismissControlTime(2000)
                .setAutoFullWithSize(true)
                .setShowPauseCover(true)//设置暂停显示封面，可能会引起部分手机oom
                .setUrl(url)
                .setSetUpLazy(true)//lazy可以防止滑动卡顿
                .setVideoTitle(item.getTitle())
                .setCacheWithPlay(false)
                .setRotateViewAuto(false)
                .setLockLand(true)
                .setPlayTag(TAG)
                .setShowFullAnimation(false)
                .setNeedShowWifiTip(false)
                .setNeedLockFull(true)
                .setPlayPosition(helper.getLayoutPosition())
                .setVideoAllCallBack(new GSYSampleCallBack() {
                    @Override
                    public void onEnterFullscreen(String url, Object... objects) {
                        super.onEnterFullscreen(url, objects);
                        VideoPlayListActivity.isIfCurrentIsFullscreen = true;
                        if (null == sampleGSYVideo) {
                            return;
                        }
                        GSYVideoManager.instance().setNeedMute(false);
                        sampleGSYVideo.getCurrentPlayer().getTitleTextView().setText(item.getTitle());
                    }

                    @Override
                    public void onQuitFullscreen(String url, Object... objects) {
                        super.onQuitFullscreen(url, objects);
                    }

                    @Override
                    public void onAutoComplete(String url, Object... objects) {
                        super.onAutoComplete(url, objects);
                        if (null == sampleGSYVideo) {
                            return;
                        }
                        sampleGSYVideo.setUploadValidPlay(false);
                        if (!playBoolean) {
                            return;
                        }
                        if (sampleGSYVideo.isIfCurrentIsFullscreen()) {
                            GSYVideoManager.backFromWindowFull(mContext);
                            sampleGSYVideo.postDelayed(() -> {
                                VideoPlayListActivity.isIfCurrentIsFullscreen = false;
                                onAutoComplete();
                            }, 1000);
                        } else {
                            onAutoComplete();
                        }
                    }

                    /**
                     * 视频播放完成的回调
                     */
                    private void onAutoComplete() {
                        if (null != mAutoCompleteListener) {
                            mAutoCompleteListener.onAutoCompletion(sampleGSYVideo.getPlayPosition());
                        }
                    }

                    @Override
                    public void onPlayError(String url, Object... objects) {
                        super.onPlayError(url, objects);
                        if (null == sampleGSYVideo) {
                            return;
                        }
                        sampleGSYVideo.changeUiToShowError();
                    }
                }).build(sampleGSYVideo);

        //增加title
        sampleGSYVideo.getTitleTextView().setVisibility(View.GONE);

        //设置返回键
        sampleGSYVideo.getBackButton().setVisibility(View.GONE);

        //设置全屏按键功能
        sampleGSYVideo.getFullscreenButton().setOnClickListener(v -> {
            resolveFullBtn(sampleGSYVideo);
        });
    }

这个是adapter里面的。
