### ISSUE TITLE
内存泄漏能看看不，

### ISSUE THREAD

**Issue by LinForStudy** [CarGuo/GSYVideoPlayer#8]
![image](https://cloud.githubusercontent.com/assets/18901958/20739169/7480a7f8-b6f3-11e6-97bc-4138d4cd3fc1.png)

**Comment by CarGuo** [comment]
嗯嗯，我看一下。

**Comment by CarGuo** [comment]
1.3.3更新了，修复了一些泄漏问题，不过有一个AudioManager的问题偶尔可能会出现泄漏，说是系统的一些机制问题，不过不影响使用，后面再看看怎么修复。

**Comment by CarGuo** [comment]
如果可以了，请close哟！

**Comment by LinForStudy** [comment]
OK 感谢
