### ISSUE TITLE
关于H265解析的问题

### ISSUE THREAD

**Issue by juvenileHHY** [CarGuo/GSYVideoPlayer#80]
您好，我播放H265编码的4K视频和1080P的都有问题，播放卡顿严重，跳转进度花屏，我去ijk的issues中查看了一下说是移除了对h265的支持，不知道您重新编译的so库中是否添加了支持，如果添加了支持那这种卡顿该怎么解决呢？（也尝试过硬解的开启，没有效果）

**Comment by CarGuo** [comment]
我的so有对应支持，话说如果是模拟器就不用说了一定会这样的，如果是真机的话，可以看看降低帧数等办法，你可以看看github首页的问题集锦 12、视频声音画面不同步，还有手机的ijk问题集锦链接，4K和1080如果帧数高的话，对手机来说负荷比较大，so是已经编译了H265的

**Comment by juvenileHHY** [comment]
是真机，您说的几种办法我会去尝试一下，感谢回复O(∩_∩)O~
