### ISSUE TITLE
太多log了,

### ISSUE THREAD

**Issue by hugo519277308** [CarGuo/GSYVideoPlayer#801]
请问: 这些log 怎么关闭
02-05 15:02:57.989 16508-16542/com.example.gsyvideoplayer V/IJKMEDIA: stream 1, sample 1292, dts 30000181
02-05 15:02:57.989 16508-16542/com.example.gsyvideoplayer V/IJKMEDIA: stream 0, sample 899, dts 29962400
02-05 15:02:57.989 16508-16542/com.example.gsyvideoplayer V/IJKMEDIA: stream 1, sample 1293, dts 30023401
02-05 15:02:57.989 16508-16542/com.example.gsyvideoplayer V/IJKMEDIA: stream 0, sample 899, dts 29962400
02-05 15:02:57.989 16508-16542/com.example.gsyvideoplayer V/IJKMEDIA: stream 1, sample 1294, dts 30046621
02-05 15:02:57.989 16508-16542/com.example.gsyvideoplayer V/IJKMEDIA: stream 0, sample 899, dts 29962400
02-05 15:02:58.018 16508-16567/com.example.gsyvideoplayer D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
02-05 15:02:58.018 16508-16567/com.example.gsyvideoplayer D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
02-05 15:02:58.050 16508-16568/com.example.gsyvideoplayer D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0

**Comment by CarGuo** [comment]
```
GSYVideoManager.instance().setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
```

**Comment by zung** [comment]
> ```
> GSYVideoManager.instance().setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
> ```

没有setLogLevel这个方法

**Comment by CarGuo** [comment]
@zung 新版本 IjkPlayerManager. setLogLevel
