### ISSUE TITLE
暂停、播放问题！

### ISSUE THREAD

**Issue by wangtaoT** [CarGuo/GSYVideoPlayer#802]
onVideoPause()暂停后，onVideoResume()播放，会从开头重新加载！

**Comment by CarGuo** [comment]
DEMO中哪个页面会出现这个问题？

**Comment by wangtaoT** [comment]
我是自己想控制视频的暂停、播放。

**Comment by CarGuo** [comment]
不是很理解，如果是有问题，请在demo中复现，这样我才能定位问题。
