### ISSUE TITLE
视频全屏后进度条出现剧烈抖动

### ISSUE THREAD

**Issue by chengzhijun0706** [CarGuo/GSYVideoPlayer#803]
如果视频是的竖屏状态下没有问题,屏幕旋转时,就会出现剧烈的抖动
![image](https://user-images.githubusercontent.com/13751034/35792815-ef49a8fa-0a89-11e8-8f6f-275b4aa5ab28.png)

**Comment by CarGuo** [comment]
剧烈抖动？demo中哪个页面复现？怎么抖动情况？如果可以麻烦录制一个小视频，压缩成rar之后上传个附件

**Comment by chengzhijun0706** [comment]
[1517813993.mp4.zip](https://github.com/CarGuo/GSYVideoPlayer/files/1694227/1517813993.mp4.zip)
就是这种情况,在没有点全屏之前是正常的,全屏之后就会发生抖动

**Comment by CarGuo** [comment]
我在demo中没有重现这个现象

**Comment by chengzhijun0706** [comment]
![image](https://user-images.githubusercontent.com/13751034/35793802-24a772ee-0a8e-11e8-8d73-c8cc27bb3ccd.png)
[CustomStandardVideoPlayer.java.zip](https://github.com/CarGuo/GSYVideoPlayer/files/1694279/CustomStandardVideoPlayer.java.zip)
这是我的自定义的播放器和 使用的地方,您帮看看有什么问题,谢谢,您的demo确实没有复现,但在我这里几乎是必现的,谢谢,大佬

**Comment by CarGuo** [comment]
没看出来，一般设置这个的位置是在 setProgressAndTime这个方法

**Comment by chengzhijun0706** [comment]
我也找到了那个方法,看log也是没有问题的,但是还是出现了
就是进度条和原始的宽度不一致时候就会出现,大神有什么思路么

**Comment by CarGuo** [comment]
从你提供的代码中我是没看出什么问题

**Comment by chengzhijun0706** [comment]
问题解决了,但是好奇怪
![image](https://user-images.githubusercontent.com/13751034/35796739-74fb2394-0a98-11e8-815d-58d8f7818b1c.png)
我吧这个注释了,吧样式直接写到了xml里就好使了
![image](https://user-images.githubusercontent.com/13751034/35796782-921b8c98-0a98-11e8-89b7-f0697b0291eb.png)

不知道为啥呢
