### ISSUE TITLE
我想视频播放进度显示到毫秒，大佬能不能提供下实现思路

### ISSUE THREAD

**Issue by xiaofei-dev** [CarGuo/GSYVideoPlayer#804]
如题

**Comment by CarGuo** [comment]
继承播放器，重载 `protected void setProgressAndTime(int progress, int secProgress, int currentTime, int totalTime) `

**Comment by xiaofei-dev** [comment]
感谢作者大大解答，好好把主体代码撸了一遍，现在清晰多了~
