### ISSUE TITLE
如何判断是否已经缓存到本地？

### ISSUE THREAD

**Issue by nikolamakin** [CarGuo/GSYVideoPlayer#806]
如何能获取gsyvideoplayer的缓存路径 和 是否已经缓存的状态，有没有什么好办法能在listview里就直接判断视频已经缓存？

**Comment by CarGuo** [comment]
参考源码中的这两个，如果你是使用默认的
```
 /**
     * 删除默认所有缓存文件
     */
    public static void clearAllDefaultCache(Context context)

    /**
     * 删除url对应默认缓存文件
     */
    public static void clearDefaultCache(Context context, String url) 


```

**Comment by nikolamakin** [comment]
我仿照StandardGSYVideoPlayer 写一个自己的继承
public  abstract class VideoPlayer extends GSYVideoPlayer {

    protected StandardVideoAllCallBack mStandardVideoAllCallBack;
....
里面的代码都一样，该替换的已经替换

但是点击APP里的播放按钮就闪退，难道我的继承方式不对？

**Comment by CarGuo** [comment]
那得看闪退的log是什么

**Comment by nikolamakin** [comment]
java.lang.ClassCastException: com.shuyu.gsyvideoplayer.video.NormalGSYVideoPlayer cannot be cast to cc.makin.VideoPlayer

VideoPlayer是我模仿StandardGSYVideoPlayer写的类

**Comment by CarGuo** [comment]
NormalGSYVideoPlayer 不能强制转化为 VideoPlayer啊，你看看哪里使用了NormalGSYVideoPlayer 的强制转化

**Comment by CarGuo** [comment]
NormalGSYVideoPlayer 不能强制转化为 VideoPlayer啊，你看看哪里使用了NormalGSYVideoPlayer 的强制转化

**Comment by nikolamakin** [comment]
找到问题了，建议作者还是增加这方面的回调吧，你看我写个继承各种莫名其妙的问题
