### ISSUE TITLE
播放没有画面，只有声音，所有按钮无法点击，进来帮我看看，谢谢

### ISSUE THREAD

**Issue by nikolamakin** [CarGuo/GSYVideoPlayer#807]
videoplayer = new MyVideoPlayer(this);

videoplayer.findViewById(R.id.videoview);

播放没有画面，只有声音，所有按钮无法点击
我注释了videoplayer.findViewById(R.id.videoview);但是一样的效果
难道videoplayer.findViewById(R.id.videoview); 压根就没有加载？
我看了所有的文件例子，都是@bind 这样绑定id 的？希望作者给一下这方面的解答。谢谢

**Comment by CarGuo** [comment]
不是理解，如果有需要自定义请参考demo，如果有问题请在demo复现。

**Comment by nikolamakin** [comment]
videoplayer.findViewById(R.id.videoview); 能这样使用吗，我看了你的例子没有这样使用的，但是我自己的写的继承类，只能new 了，但是不知道怎么绑定video id
