### ISSUE TITLE
设置了列表滚动监听，视频切换全屏会暂停播放，能否，麻烦大神指点一下给点提示，还有判断了播放完成就退出全屏，也无效

### ISSUE THREAD

**Issue by xicong** [CarGuo/GSYVideoPlayer#810]
![image](https://user-images.githubusercontent.com/11675597/35914457-4a21897c-0c3e-11e8-8355-52be5fdddaa4.png)
![image](https://user-images.githubusercontent.com/11675597/35914485-63f70e62-0c3e-11e8-8033-97f65be9ca08.png)
![image](https://user-images.githubusercontent.com/11675597/35914523-7c35aea2-0c3e-11e8-8124-a168863cce34.png)

之前按提示取消列表监听进全屏进度不会出现问题但是列表会出现错乱

**Comment by CarGuo** [comment]
我只能说参考demo，  detailPlayer.getCurrentPlayer().isIfCurrentIsFullscreen() 可以判断
