### ISSUE TITLE
clone到本地怎么就出现冲突了

### ISSUE THREAD

**Issue by triplesky** [CarGuo/GSYVideoPlayer#812]
![image](https://user-images.githubusercontent.com/6504772/35959092-fd0daa02-0cde-11e8-8d96-87903632d121.png)

**Comment by CarGuo** [comment]
demo？

**Comment by lingkf123** [comment]
是的，我也出现了同样个错误

**Comment by lingkf123** [comment]
试了很多方法demo都跑不起来

**Comment by CarGuo** [comment]
我这么运行正常，你是Android 3.0.1 build:gradle:3.0.1 的环境吧？
试试修改gsyVideoPlayer这个模块下的依赖

```
api project(':gsyVideoPlayer-java')
api project(':gsyVideoPlayer-armv5')
api project(':gsyVideoPlayer-armv7a')
api project(':gsyVideoPlayer-armv64')
api project(':gsyVideoPlayer-x86')
api project(':gsyVideoPlayer-x86_64')

```

**Comment by CarGuo** [comment]
我再一个新环境重新clone了项目，直接运行，没问题。 Android Studio 3.0.1

**Comment by yangwhat** [comment]
api project(':gsyVideoPlayer-java')
    api project(':gsyVideoPlayer-armv5')
    api project(':gsyVideoPlayer-armv7a')
    api project(':gsyVideoPlayer-armv64')
    api project(':gsyVideoPlayer-x86')
    api project(':gsyVideoPlayer-x86_64')

    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    //api project(':gsyVideoPlayer-ex_so')

//    api "com.shuyu:GSYVideoPlayer:$gsyVideoVersion"

果然这样改之后就ok了
