### ISSUE TITLE
进度条小窗口预览（测试）。功能API

### ISSUE THREAD

**Issue by askskysun** [CarGuo/GSYVideoPlayer#813]
在哪里？

**Comment by askskysun** [comment]
在哪里？

**Comment by CarGuo** [comment]
demo PreViewGSYVideoPlayer

**Comment by CarGuo** [comment]
怎么说呢。你可以看看源码，这个功能目前来说还不是很好，还在选择方案中，目前还没有什么特别体验好的方案，以前还有一个旧的方案，是CustomGSYVideoPlayer，不过目前没有维护，后面看看再寻找下上面实现逻辑比较好

**Comment by askskysun** [comment]
PreViewGSYVideoPlayer 需要依赖glide4
我用的是
 implementation 'com.android.support:appcompat-v7:26.0.0-beta1'
一旦依赖 
  implementation 'com.github.bumptech.glide:glide:4.4.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'
就会报错
 java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;II)Landroid/support/v4/graphics/TypefaceCompat$TypefaceHolder; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.hero.gsyvideoplayerdemo-1/base.apk)

**Comment by CarGuo** [comment]
请参考demo
