### ISSUE TITLE
请问接入的是ijk哪个版本库

### ISSUE THREAD

**Issue by Will-ZJ** [CarGuo/GSYVideoPlayer#816]

**Comment by CarGuo** [comment]
0.8.4

**Comment by Will-ZJ** [comment]
谢谢，我是做iOS的，我发现你们这个支持H265的，很棒，我想iOS这个版本应该也支持吧？

**Comment by CarGuo** [comment]
你可以直接用这个项目里的so，大致分为ex_so下的so，和普通so两种，ex_so目录下的so多支持了加密，rtmp，rtsp，mepg等格式
