### ISSUE TITLE
请问支持边播放边录像功能吗

### ISSUE THREAD

**Issue by bypain** [CarGuo/GSYVideoPlayer#819]
请问支持边播放边录像功能吗？随录随停

**Comment by CarGuo** [comment]
这个………没有😂

**Comment by bypain** [comment]
@CarGuo 大佬有啥思路吗？我想根据你这个进行扩展😂

**Comment by CarGuo** [comment]
边播放边录像，这个目前还真没有什么思路···你的录像是录屏么··还是对其中一段视频截取

**Comment by bypain** [comment]
@CarGuo 是对其中一段视频截取

**Comment by CarGuo** [comment]
目前没有什么思路，这样的需求

**Comment by hardgit** [comment]
我也遇到这种需求了，也没思路￣□￣｜｜

**Comment by CarGuo** [comment]
如果不需要声音的，可以一帧一帧的把画面保存下载合成，音频方便比较麻烦，毕竟音频解码你要在底层ffmepg处去处理。
