### ISSUE TITLE
自定义播放器如何传递自定义参数

### ISSUE THREAD

**Issue by EvlinLee** [CarGuo/GSYVideoPlayer#82]
需要在自定义播放器里打开DialogFragment，怎么调用getSupportFragmentManager。

**Comment by CarGuo** [comment]
播放器里不开打dialogFragment，你的需求应该是播放器所在的activity或者fragment打开～～比如播放器里有一个按键，点击后回调到fragment去弹出

**Comment by EvlinLee** [comment]
@CarGuo 这个问题解决了。不过还有一个问题，当横屏时就无法显示activity的DialogFragment了

**Comment by CarGuo** [comment]
是的，横屏是依附在win层上的
