### ISSUE TITLE
Error:(46, 0) Gradle DSL method not found: 'api()' 

### ISSUE THREAD

**Issue by xuefeiyao** [CarGuo/GSYVideoPlayer#820]
demo在android-studio2.3.2中报这个错，如果不更新android-studio版本到3.+版本，怎么解决?

**Comment by CarGuo** [comment]
修改为运来的compile啊，然后修改会gradle 2.2.3，去掉google仓库

**Comment by xuefeiyao** [comment]
解决了，多谢大佬指点。
