### ISSUE TITLE
播放多段视频时，是否支持边播边缓存功能

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#826]
本地有优先播放本地文件

**Comment by CarGuo** [comment]
多段视频？concat或者m3u8吗？这种多分片的不支持

**Comment by maolubin** [comment]
@CarGuo 是的concat，sdk不是集成了AndroidVideoCache，能不能结合使用啊

**Comment by CarGuo** [comment]
不行，因为多个分片在缓存了seek上使用AndroidVideoCache会比较麻烦
