### ISSUE TITLE
退出全屏后显示不全的问题补充过了，但没收到回复

### ISSUE THREAD

**Issue by iammasir** [CarGuo/GSYVideoPlayer#828]
[https://github.com/CarGuo/GSYVideoPlayer/issues/776](url)

**Comment by CarGuo** [comment]
请尝试下最新的demo。一般都是因为`startWindowFullscreen`和`onConfigurationChanged`的时候不匹配等问题，现在的onConfigurationChanged也增加了 boolean hideActionBar, boolean hideStatusBar等方法
