### ISSUE TITLE
有没有ScrollView嵌套ListView播放列表的例子

### ISSUE THREAD

**Issue by MirrorFlower** [CarGuo/GSYVideoPlayer#831]
如题

**Comment by CarGuo** [comment]
没有，不过是单独在list播放或者嵌套中播放，没有太大区别

**Comment by MirrorFlower** [comment]
额额  ListView滚动监听那一块不受影响吗  因为ScrollView嵌套了ListView  我的ListView重写了

**Comment by MirrorFlower** [comment]
我试了一下Demo的ListVideo2Activity和ListVideoAdapter  发现点击播放后直接白屏显示 播放不出来   ListView重写了  增加的这个方法：
@Override  
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {  
        int expandSpec = MeasureSpec.makeMeasureSpec(Integer.MAX_VALUE >> 2,MeasureSpec.AT_MOST);
        super.onMeasure(widthMeasureSpec, expandSpec);  
    }

**Comment by CarGuo** [comment]
这个需要你跟踪一下是渲染层在的surface没创建，还是播放直接失败了

**Comment by MirrorFlower** [comment]
大佬你好 我再问一下  如何获取视频的第一帧  然后作为视频的封面呢？

**Comment by CarGuo** [comment]
参考demo SampleCoverVideo
