### ISSUE TITLE
怎么将视频播放时充满？

### ISSUE THREAD

**Issue by hardgit** [CarGuo/GSYVideoPlayer#832]
视频播放的时候有边距没有充满怎么解决？怎么将视频拉伸充满...

**Comment by CarGuo** [comment]
GSYVideoType

**Comment by hardgit** [comment]
我这边是一个视频列表，不点击播放按钮，怎么让它滑到哪 播放 哪个视频？

**Comment by CarGuo** [comment]
参考demo AutoPlayRecyclerViewActivity

**Comment by hardgit** [comment]
我看了一下大概就只有一个帮助类和Activity中的调用还有滑动监听，我直接copy过来了，为什么会没有反应呢？有什么需要注意的吗？我用的CustomGSYVideoPlayer播放器类。

**Comment by CarGuo** [comment]
这个就不是很清楚了，我只能说参考demo吧···
