### ISSUE TITLE
播放器在没有视频地址情况下，多次点击播放器按钮之后播放按钮和返回键消失，变为黑屏状态

### ISSUE THREAD

**Issue by xuefeiyao** [CarGuo/GSYVideoPlayer#833]
如题

**Comment by CarGuo** [comment]
没有视频地址···为什么要去播放？？？如果有这类特殊需求，继承后重载即可，比如重载`prepareVideo()`或者`startPrepare()`等判断

**Comment by hardgit** [comment]
@CarGuoSmall 在适配器中怎么重载这两个方法？

**Comment by CarGuo** [comment]
适配器？？？ 你要继承你使用的播放器，才能重载这两个方法，然后再你使用的地方替换为你继承后实现的类
