### ISSUE TITLE
本地视频

### ISSUE THREAD

**Issue by lingkf123** [CarGuo/GSYVideoPlayer#834]
请问要如何播放本地视频呢

**Comment by CarGuo** [comment]
file:///xxxx

**Comment by lingkf123** [comment]
嗯，控制模式和详情模式，本质区别是啥呢，控制模式下那个旋转镜像等三个是不是不能隐藏起来

**Comment by lingkf123** [comment]
现在有个问题，我本地放了一个视频，这个时候把对应的url传进去，这个时候如果设备没有网络，会提示当前找不到网络

**Comment by CarGuo** [comment]
可以看下源码，如果url设置是file开头的  `mUrl.startsWith("file")` 应该不会弹出提示，你也可以继承重载@
protected void showWifiDialog() 做判断处理

**Comment by lingkf123** [comment]
嗯，我用这样拼接的url肯定是不会以file开头，Environment.getExternalStorageDirectory().getAbsolutePath()，另外控制模式下那个旋转镜像等三个是不是不能隐藏起来

**Comment by CarGuo** [comment]
demo中的是例子，给你参考的，你想怎么实现都想，比如布局是通过重写getLayoutId实现的。

**Comment by lingkf123** [comment]
好的，谢谢

**Comment by chigang** [comment]
哥们怎么写的啊 private String url = SDPATH + "/Download/w.mp4";
我这样写,有加载图片,没有视频播放啊
