### ISSUE TITLE
全屏时，5.0扩散动画位置计算不准确

### ISSUE THREAD

**Issue by NFLeo** [CarGuo/GSYVideoPlayer#835]
三星s7，其他手机还没试，位置会偏上一点，大概50dp左右

**Comment by CarGuo** [comment]
demo吗？可以录个视频看下，全屏效果还和是否隐藏actionbar和statubar有关，因为如果没有actionbar但是设置了需要隐藏actionbar也会产生偏差

**Comment by NFLeo** [comment]
嗯，是demo。视频我不方便录。直接运行demo，打开多类型视频，然后全屏切换就有这个问题了
