### ISSUE TITLE
seekTo不准确,只能跳到关键帧吗

### ISSUE THREAD

**Issue by the-mok** [CarGuo/GSYVideoPlayer#837]
seekTo不准确,只能跳到关键帧吗,能不能seekto到准确的时间点position

**Comment by CarGuo** [comment]
请看问题集锦

**Comment by the-mok** [comment]
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);
设置了之后关键帧到播放点那一段时间的视频变成了一段黑屏....请问有其它方案吗

**Comment by CarGuo** [comment]
目前没有

**Comment by CupidLoud** [comment]
请问关于此问题的问题集锦在哪？

**Comment by CarGuo** [comment]
@CupidLoud  enable-accurate-seek 配置或者切换到 Exo2PlayerManager
