### ISSUE TITLE
更新一下ijkplayer版本到0.8.8

### ISSUE THREAD

**Issue by lingchen52** [CarGuo/GSYVideoPlayer#838]
ijkplayer已更新到0.8.8版本，我自己编译好了SO文件，但gsyvideoplayer里依赖的还是ijkplayer0.8.4的版本，望尽快更新

**Comment by CarGuo** [comment]
dev分支已经编译好0.8.8的了，估计在3月份左右才会发布，如果你着急需要替换，你可以自己依赖0.8.8的，然后 exclude ijk相关的试试
compile('com.xxxx.xxxx:1.1.0') {
    exclude group: 'x x x x', module: 'xxxx'
}

**Comment by CarGuo** [comment]
已经更新
