### ISSUE TITLE
fragment中的listview 列表播放

### ISSUE THREAD

**Issue by AmberWhiteSky** [CarGuo/GSYVideoPlayer#839]
我的需求是fragment中的listview 列表播放，我应该看哪个部分呢？fragment 播放还是listview列表播放？麻烦大佬指点迷津。

**Comment by CarGuo** [comment]
和在哪里播放没什么关系，demo只是给你参考，项目支持在任何地方播放

**Comment by AmberWhiteSky** [comment]
感谢大佬回复。已经解决了。
