### ISSUE TITLE
请指教，关于更多机型适配问题

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#84]
金立、乐视、Vivo、OPPO这些手机，不知道作者有没有测试过。根据我们运营人员的反馈，这些机型的用户，经常会在播放过程中报错。如何能适配更多机型？请指教

**Comment by CarGuo** [comment]
配置so的过滤，播放器最有可能就是so的适配问题，一般设置了so的过滤就会更好一些，适配是永无止境的，如果你需要灵活，你可以配置动态so加载，根据机型下载so去适配，至于播放中出错，因为so支持的主要是 h264、h265，aac的格式视频，需要更多格式你可以自己去下载ijk源码配置module.sh去编译so增加更多支持，github首页有编译教程，不然你就需要规定好视频的格式。最后就是视频的分辨率和帧数，如果手机支持比较差，那么高分辨率和高帧数会导致卡顿甚至挂掉，github首页的问题集锦最后也有说到对应的处理。

**Comment by PiPiCaptain** [comment]
@CarGuo 感谢，学习了，我尝试一下

**Comment by PiPiCaptain** [comment]
@CarGuo 我觉得我这边第三点是最有可能的。如果视频源不变，这个类库能做降低分辨率和帧数的处理么？谢谢

**Comment by CarGuo** [comment]
问题集锦中有dropframe的介绍，你也可以查找一些关于ijk的option，其实就是对应ffmepg的选项配置去添加，最后友情提醒，非必需情况下不要开始硬解码，硬解码的兼容缺失最可能有问题。

**Comment by PiPiCaptain** [comment]
VideoOptionModel videoOptionModel =
        new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);

结构函数里的三个参数，分别代表什么？还有这段代码，要在setUp()方法之后才能调用么？

**Comment by CarGuo** [comment]
framedrop ，字面上的意思，丢帧  drop frames when cpu is too slow

**Comment by PiPiCaptain** [comment]
@CarGuo 感谢
