### ISSUE TITLE
有个问题反馈下

### ISSUE THREAD

**Issue by lingkf123** [CarGuo/GSYVideoPlayer#840]
播放本地视频有个问题，我看了下源代码，必须是以file开头的才认为是本地的视频，假如我现在需要播放手机里特定某个位置的视频，这个时候得到的文件路径肯定不是以file开头的，这就是个bug了

**Comment by CarGuo** [comment]
不是bug，本地特定位置的视频file:///开头并没问题，比如你获取到的路径，encode为file开头的，这并没有什么问题，也不会有什么问题，对你而言可能就是不能直接使用获取到的路径，需要做一次encode
