### ISSUE TITLE
请问，怎么在代码里设置播放和暂停？

### ISSUE THREAD

**Issue by jingzz1** [CarGuo/GSYVideoPlayer#848]
需要代码控制播放暂停停止等操作，请问要怎么做？

**Comment by CarGuo** [comment]
有多重方法，具体看demo的 DetailPlayer的onPause和onReume
或者ListVideoActivity的onPause和onReume

**Comment by jingzz1** [comment]
进入界面之后自动播放，我按你的onReume方法写，然后没用

**Comment by CarGuo** [comment]
startPlayLogic();

**Comment by jingzz1** [comment]
解决了，谢谢。
还有一个问题，我想让标题滚动，所以自定义的VideoPlayer 里设置了 mTitleTextView.setSelected(true)，虽然可以滚动了，但总是滚动一点就跳回开头，是因为原代码里有哪个部分一直在执行mTitleTextView.setText()吗？

**Comment by CarGuo** [comment]
具体自定义可以继承后自行处理，比如自定义布局等等
