### ISSUE TITLE
Android 8.0系统！

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#849]
你好 请问这个库兼容了Android 8.0系统嘛。
在Android 8.0手机上播放视频或者播放直播都很卡顿 加载很慢，是什么原因呢？

**Comment by CarGuo** [comment]
兼容啊，你是什么手机，我目前在android 8.0上华为没有问题，不过模拟器上卡是很正常的

**Comment by Born-alone** [comment]
华为Mate 10 播放起来加载很慢 时间久了就会ANR 是不是因为我开了边播边缓存？

**Comment by CarGuo** [comment]
最新demo吗？我在华为荣耀9青春版没发现呢，你跑的demo哪个页面？

**Comment by Born-alone** [comment]
不是最新的jar  项目里用的是2.1.0版本 
 项目里的用的Demo里第二个(CONTROL)页面!

**Comment by CarGuo** [comment]
你试试最新的demo直接跑看看。旧版本以前在华为有gl的问题，不过control页面应该没关系啊。看看新demo是否复现。

**Comment by Born-alone** [comment]
在8.0系统的模拟器上跑了一下最新的Demo和自己的项目  不会卡顿呀

**Comment by CarGuo** [comment]
你在华为Mate 10 上跑demo呢？

**Comment by Born-alone** [comment]
那个手机没试 这个问题是同事反映的 没有真机测试.

**Comment by CarGuo** [comment]
如果有机会跑跑最新demo看看
