### ISSUE TITLE
可以自定义userAgent么

### ISSUE THREAD

**Issue by zengqingf** [CarGuo/GSYVideoPlayer#851]

**Comment by CarGuo** [comment]
可以，设置mapheader

**Comment by zengqingf** [comment]
感谢回复，不过有点好奇怪，抓包工具竟然抓不到demo的播放视频的请求，难道不是用的http(s)  ？

**Comment by zengqingf** [comment]
已经成功的加上了User-Agent，但是通过抓包的数据来看，在header中出现了两次User-Agent

**Comment by zengqingf** [comment]
看了ijk的一个issue中的描述，User-Agent有单独的设置方法[https://github.com/Bilibili/ijkplayer/issues/3851](url)

**Comment by zengqingf** [comment]
然后我尝试了下面这两种情况，exo2失败，系统播放器成功，什么都不设置默认的情况下会出现两次User-Agent，希望大神日后完善一下哈，播放器做的不错，赞一个
GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2); //EXO 2 播放内核
GSYVideoManager.instance().setVideoType(this, GSYVideoType.SYSTEMPLAYER); //系统播放器

**Comment by CarGuo** [comment]
哦，你需要设置option的话，对应得是

**Comment by CarGuo** [comment]
/*VideoOptionModel videoOptionModel =


                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);


        List<VideoOptionModel> list = new ArrayList<>();


        list.add(videoOptionModel);


        videoOptionModel =


                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");


        list.add(videoOptionModel);


        GSYVideoManager.instance().setOptionModelList(list);*/

类似这种

**Comment by zengqingf** [comment]
已成功，感谢大神的指导，跪拜
