### ISSUE TITLE
使用mideaRecorder录制视频 播放画面出错

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#852]
我使用mideaRecorder录制15s的视频，使用浏览器播放时正确的，但是使用GSYVideoPlayer播放只有前4秒左右的画面就卡住不动了，但是声音是对的，配置如下。
  mMediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
  mMediaRecorder.setVideoSource(MediaRecorder.VideoSource.SURFACE);
  mMediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);
  mMediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.H264);
  mMediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
  mMediaRecorder.setVideoEncodingBitRate(2500000);
  mMediaRecorder.setVideoFrameRate(20);
  mMediaRecorder.setVideoSize(mPreviewSize.getWidth(), mPreviewSize.getHeight());
求指教。

**Comment by CarGuo** [comment]
有测试url吗

**Comment by i2863CookieZJ** [comment]
http://images-cdn.adun.ccsobey.com//86a5e8a9-973b-411e-a561-ca7f70138ea5.mp4 
你看看有什么问题

**Comment by CarGuo** [comment]
我在demo中试了，使用exo内核解析不了该视频
用mediaplayer内核播放的时候画面是静止的
用ijk内核播放的时候，到了7秒钟画面静止。
我怀疑是视频的帧序列存在问题。

我下载到手机本地播放，直接点开播放画面是静止的。

**Comment by i2863CookieZJ** [comment]
我发现这样设置比特率后mMediaRecorder.setVideoEncodingBitRate(1*1024*1024); ijk是可以播发的，但是其他就播不了了

**Comment by i2863CookieZJ** [comment]
1*1024*1024

**Comment by i2863CookieZJ** [comment]
1 * 1024 * 1024

**Comment by CarGuo** [comment]
https://github.com/CarGuo/VideoRecord/blob/master/app/src/main/java/com/shuyu/videorecord/RecordActivity.java   很久前我使用的录制，你可以看看

**Comment by i2863CookieZJ** [comment]
多谢，我参考一下  我使用的是camera2
