### ISSUE TITLE
播放器传参改变ui应该怎么弄

### ISSUE THREAD

**Issue by Drrino** [CarGuo/GSYVideoPlayer#853]
![image](https://user-images.githubusercontent.com/14050360/36784696-54876282-1cbb-11e8-82c0-35faaa0597a6.png)
能接收到isCollect值  但不能改变imageview

**Comment by Drrino** [comment]
在activity中使用类似于videoPlayer.getTitleTextView()的方法也无效

**Comment by CarGuo** [comment]
继承吧，有意者ui会在初始化之类的时候设置，所以一般自定义可以继承，然后实现你的逻辑或者返回自己的布局

**Comment by Drrino** [comment]
![image](https://user-images.githubusercontent.com/14050360/36785747-db9d5d50-1cbe-11e8-9142-2c2d5bcc6519.png)
我这边继承了  请问这个播放器应该怎么在初始化前传值呢？

**Comment by CarGuo** [comment]
init就是初始化啊，你需要初始化前传值是？不是很理解场景

**Comment by Drrino** [comment]
我需要通过id查询数据库的id是哪种类型  来判断控件加载什么样的图片
 改变控件的图片好像只能在init里面改变  我想咨询下如何在播放器初始化前传参数进去判断

**Comment by hardgit** [comment]
借标题一用 ==！怎么隐藏所有的虚拟按键？ @CarGuo

**Comment by CarGuo** [comment]
看全屏代码中，就有隐藏虚拟按键

**Comment by hardgit** [comment]
哪个进度条呢？

**Comment by hardgit** [comment]
进度条和时间也要隐藏，

**Comment by hardgit** [comment]
还是没有弄明白进度条和时间怎么隐藏。还有就是怎么修改哪个返回按钮？ @CarGuo

**Comment by CarGuo** [comment]
继承，返回你自己的布局，或者重载init中修改按键的显示。要自定义隐藏这个两个，你需要看Standard播放控件的源码，比如changexxxx哪些方法，还有看看源码中的定时器在触摸显示很隐藏。
总之，继承，重载是核心

**Comment by hardgit** [comment]
谢谢，我试试！

**Comment by sinduanan** [comment]
> ![image](https://user-images.githubusercontent.com/14050360/36784696-54876282-1cbb-11e8-82c0-35faaa0597a6.png) 能接收到isCollect值 但不能改变imageview

请问这个最后是咋解决的   看其他issue也没明白该怎么搞
