### ISSUE TITLE
播放一个MP4的url视频，处于极长时间加载状态；

### ISSUE THREAD

**Issue by woshijinlei** [CarGuo/GSYVideoPlayer#854]
这是videoplayer自身问题还是其他问题啊；

**Comment by CarGuo** [comment]
有测试url吗？这得看是什么情况，比如dns解析，网络情况，视频问题等等。你可以先把视频放到本地播放，看看能否播放成功

**Comment by woshijinlei** [comment]
http://cj2.ttkhj.3z.cc/cyt.php?type=cytyun&url=/guochuang/0221/022101_cyt.mp4
他是能够播放，但是加载两三分钟播放2秒钟这样的情况；
我不清楚是不是GSYVideoPlayer自身的原因不？

**Comment by handsome51jia** [comment]
@woshijinlei 你这个是服务器的问题，我用电脑上的potplayer播放你的视频，都卡的不行

**Comment by woshijinlei** [comment]
thanks
