### ISSUE TITLE
support包重复了？

### ISSUE THREAD

**Issue by lpslpsl** [CarGuo/GSYVideoPlayer#855]
拉下项目的时候发现有，22.2.1和24.2.0的support包和support-core-ui等库。

**Comment by CarGuo** [comment]
不影响，打包只会打包一种

**Comment by lpslpsl** [comment]
按照812的修改了下。还是在报Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
呢

**Comment by CarGuo** [comment]
就是修改为本地api 本地module 依赖，没什么特别的啊，修改依赖后clean下再编译，没发现什么问题。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/856
