### ISSUE TITLE
直接编译报错

### ISSUE THREAD

**Issue by mycold** [CarGuo/GSYVideoPlayer#856]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/shuyu/gsyvideoplayer/lib/BuildConfig;
需要去除几个library引用吗

**Comment by CarGuo** [comment]
使用 Android Studio 3.x版本

或者参考

https://github.com/CarGuo/GSYVideoPlayer/issues/812

**Comment by SiXuManYan** [comment]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/shuyu/gsyvideoplayer/lib/BuildConfig;
Error:com.android.dex.DexException: Multiple dex files define Lcom/shuyu/gsyvideoplayer/lib/BuildConfig;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/shuyu/gsyvideoplayer/lib/BuildConfig;

同样，在运行demo时报错，参照了 #812 但还是没解决

**Comment by CarGuo** [comment]
不要存在重复依赖

**Comment by SiXuManYan** [comment]
疏忽了，现在改好了，谢谢作者~

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    api project(':gsyVideoPlayer-java')
    api project(':gsyVideoPlayer-armv5')
    api project(':gsyVideoPlayer-armv7a')
    api project(':gsyVideoPlayer-armv64')
    api project(':gsyVideoPlayer-x86')
    api project(':gsyVideoPlayer-x86_64')

    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    //api project(':gsyVideoPlayer-ex_so')

//   使用 api project 时。注释下面这些，避免重复重复依赖  start...
//    api "com.shuyu:GSYVideoPlayer:$gsyVideoVersion"

//    api "com.shuyu:gsyVideoPlayer-java:$gsyVideoVersion"
//    api "com.shuyu:gsyVideoPlayer-armv5:$gsyVideoVersion"
//    api "com.shuyu:gsyVideoPlayer-armv7a:$gsyVideoVersion"
//    api "com.shuyu:gsyVideoPlayer-arm64:$gsyVideoVersion"
//    api "com.shuyu:gsyVideoPlayer-x64:$gsyVideoVersion"
//    api "com.shuyu:gsyVideoPlayer-x86:$gsyVideoVersion"

//   使用 api project 时。注释下面这些，避免重复重复依赖 end...

    //更多配置版so，增加了concat,rtsp,mpeg，crypto
    //api "com.shuyu:gsyVideoPlayer-ex_so:$gsyVideoVersion"


    //compile fileTree(dir: 'libs', include: ['*.jar'])
    //compile "com.shuyu:gsyVideoPlayer-java:$gsyVideoVersion"
    //compile "com.shuyu:gsyVideoPlayer-armv5:$gsyVideoVersion"
    //compile "com.shuyu:gsyVideoPlayer-armv7a:$gsyVideoVersion"
    //compile "com.shuyu:gsyVideoPlayer-arm64:$gsyVideoVersion"
    //compile "com.shuyu:gsyVideoPlayer-x64:$gsyVideoVersion"
    //compile "com.shuyu:gsyVideoPlayer-x86:$gsyVideoVersion"




}
