### ISSUE TITLE
进度拖动问题

### ISSUE THREAD

**Issue by sarayyyy** [CarGuo/GSYVideoPlayer#857]
视频进度拖动的时候还是会会弹几秒，已经设置过`    VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
    List<VideoOptionModel> list = new ArrayList<>();
    list.add(videoOptionModel);
    GSYVideoManager.instance().setOptionModelList(list);`

但是没有用

**Comment by CarGuo** [comment]
ijkplayer是ffmpeg找关键帧的，如果很介意这种情况，切换到EXO内核模式下试试

**Comment by sarayyyy** [comment]
请问一下要怎么切换呢

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);

//EXO2 对 texture 不如surface支持好，所以如果对动画等没要求，同时可以切换到
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);

这个设置可以在Application级别设置，因为是全局的

**Comment by sarayyyy** [comment]
好的 谢谢大神  试过这种已经没这个进度会弹问题了
想问一下用EXO的内核其他会有什么不好的地方吗

**Comment by sarayyyy** [comment]
额~我发现切换之后EXO内核之后没有缓存进度了唉  这个要怎么解决呢

**Comment by CarGuo** [comment]
EXO 内核的必须配合surface模式比较稳定，对动画效果等方面支持可能不是很好，不支持rtsp等。
没有白色的缓存进度？？是否开启了边播边缓存？如果边播边缓存如今完全的话，是不会有白色的进度的。
你也可以断点源码看看、有没走对应的缓存回调。

**Comment by sarayyyy** [comment]
排查了一下发现切换成EXO内核后在 GSYVideoManager中的onBufferingUpdate没有执行，用IJK它就跑进去了，onBufferingUpdate方法是在什么时候回调的呢

**Comment by CarGuo** [comment]
GSYVideoBaseManager的onBufferingUpdate，也就是IMediaPlayer的OnBufferingUpdateListener。
再进去就是EXO2PlayerManager下的IjkExo2MediaPlayer

**Comment by sarayyyy** [comment]
可是我看imediaPlayer中缓存监听已经设置进去了啊  为什么没有调用呢  感觉很奇怪啊

**Comment by CarGuo** [comment]
我看了下，好像是因为exo2和EXo1有一些区别，然后我做继承实现的时候，没做notifyOnBufferingUpdate，应该是我的问题

**Comment by sarayyyy** [comment]
你之前版本不是还有一个EXO1嘛  我用的是1   也不行啊  那这个要怎么改啊

**Comment by CarGuo** [comment]
这个，继承播放控件，在定时器里，自己通过getBufferedPercentage()获取试试吧，可以试试重载setProgressAndTime方法，在里面获取

**Comment by sarayyyy** [comment]
额 我的意思是要在哪里去实现onBufferingUpdate的回调呢

**Comment by sarayyyy** [comment]
我好像知道了。。。谢谢大神！

**Comment by sarayyyy** [comment]
真的好谢谢大神啊  我要去给你的简书赞赏！！！

**Comment by CarGuo** [comment]
😊ཽ😊ཽ😊ཽ
