### ISSUE TITLE
有demo apk体验么

### ISSUE THREAD

**Issue by microshow** [CarGuo/GSYVideoPlayer#861]
建议上传个demo apk下载地址呀

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/releases/download/v4.1.0/app-release.apk

**Comment by microshow** [comment]
@CarGuo   6、背景铺满模糊播放demo上好像木有体现？
对了 这个库能实现类似抖音的效果么

**Comment by CarGuo** [comment]
嗯，在demo代码里，没设置

**Comment by microshow** [comment]
@CarGuo 在代码的哪个位置呢  谢谢

**Comment by microshow** [comment]
@CarGuo  这个库 能获取到解码后的每一桢图片么 ，想对其处理

**Comment by CarGuo** [comment]
gl模式可以，滤镜就是这么处理的。
