### ISSUE TITLE
加载视频中点退出 播放器没有销毁 还会播放视频

### ISSUE THREAD

**Issue by SuperHanMr** [CarGuo/GSYVideoPlayer#863]
视频正在加载中  然后关闭当前页面 或者跳转其他页面 播放器还在运行 能听见声音
加载完成 则没有这种问题

**Comment by CarGuo** [comment]
demo中哪里复现？

**Comment by Kevin1ee** [comment]
@SuperHanMr ，解决了没？可以的话说下解决方案

**Comment by qq798863415** [comment]
@SuperHanMr ，兄弟，问题解决了没？可以的话说下解决方案

**Comment by CarGuo** [comment]
你们用的什么版本？

onDestory的时候调用  GSYVideoManager.releaseAllVideos(); 应该是没有问题的。
至于加载中跳转其他页面，源码中应该已经做了处理
