### ISSUE TITLE
RecycleView 无法像demo中那样自动播放

### ISSUE THREAD

**Issue by SiXuManYan** [CarGuo/GSYVideoPlayer#865]
相关配置环境，请您点一下 #864 
参照了 AutoPlayRecyclerViewActivity ，使用了 ScrollCalculatorHelper ，控件选择是 StandardGSYVideoPlayer

**Comment by CarGuo** [comment]
我看了下，没看出具体问题，如果可以还请参考demo

**Comment by SiXuManYan** [comment]
好的 我再排查一下
