### ISSUE TITLE
你好，能设置预加载吗。

### ISSUE THREAD

**Issue by githeer** [CarGuo/GSYVideoPlayer#869]
我是详情页想预加载，点击直接开始播放。顶部栏能底部栏的消失时间在哪定义呢

**Comment by CarGuo** [comment]
预加载这个需要你继承后自定义了，目前没有内置这个功能。
至于第二个问题

/**
     * 设置触摸显示控制ui的消失时间
     *
     * @param dismissControlTime 毫秒，默认2500
     */
    public void setDismissControlTime(int dismissControlTime)

**Comment by ncworm** [comment]
预加载是继承StandardGSYVideoPlayer吗？好像没有对于这个的操作

**Comment by CarGuo** [comment]
预加载现在是这样的情况，是继承StandardGSYVideoPlayer，你可以看看，有一个方法是
```
 /**
     * 准备成功之后立即播放
     *
     * @param startAfterPrepared 默认true，false的时候需要在prepared后调用startAfterPrepared()
     */
    public void setStartAfterPrepared(boolean startAfterPrepared)
```
但是问题在于，调用之后其实会对界面有一些操作，所以你需要继承后做一些细节的调整

**Comment by feng88724** [comment]
如何开启预加载？  

产品类似抖音，是一个视频列表，希望在当前视频播放的情况下，下一个视频先预加载。直接调用 prepareVideo() 会对影响当前播放的视频，导致播放的视频错误。

**Comment by ZJLeBron** [comment]
> 如何开启预加载？
> 
> 产品类似抖音，是一个视频列表，希望在当前视频播放的情况下，下一个视频先预加载。直接调用 prepareVideo() 会对影响当前播放的视频，导致播放的视频错误。

请问大佬解决这个问题了吗？

**Comment by liangnansheng** [comment]
> > 如何开启预加载？
> > 产品类似抖音，是一个视频列表，希望在当前视频播放的情况下，下一个视频先预加载。直接调用 prepareVideo() 会对影响当前播放的视频，导致播放的视频错误。
> 
> 请问大佬解决这个问题了吗？

请问大佬有解决方案了吗
