### ISSUE TITLE
请问demo里播放m3u8格式的点播视频不能seekTo有解决办法吗

### ISSUE THREAD

**Issue by tangr2015** [CarGuo/GSYVideoPlayer#871]

**Comment by CarGuo** [comment]
有些不能seekto的 
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list);

如果这个也不能解决，那没什么办法

**Comment by tangr2015** [comment]
还是不行，不过还是非常感谢！

**Comment by CarGuo** [comment]
如果不介意动画和兼容性，可以试试切换成exo2播放内核。
        GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2); //EXO 2 播放内核
        GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
