### ISSUE TITLE
横竖屏切换保存状态 更新UI！

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#873]
你好 请问一下横竖屏切换时更新UI 是在哪里处理？ 
现在的场景是我设置播放倍率按钮跟进度条和播放时长在同一个父布局里 横竖屏切换时也需要保存状态并更新UI

**Comment by CarGuo** [comment]
demo LandLayoutVideo 类似。
然后切换的ui处理，在源码的的GSYBaseVideoPlayer。继承处理逻辑类似demo的DanmakuVideoPlayer：startWindowFullscreen、resolveNormalVideoShow方法。

**Comment by Born-alone** [comment]
我用的还是 2.1版本的  只看到这个方法startWindowFullscreen

**Comment by Born-alone** [comment]
找到了 两个方法在不同的类
