### ISSUE TITLE
哥，我弹幕是分页获取的

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#879]
我竖屏取到前100条，转到横屏我咋同步啊，我还是得继续分页取的

**Comment by CarGuo** [comment]
你看demo的弹幕，横竖屏是怎么做同步的。两个播放器之后怎么同步的，你可以统一弹幕流的单例入口，在转给弹幕层咯

**Comment by CarGuo** [comment]
这个不属于该项目考虑范围，弹幕模块本来就是独立于播放的
