### ISSUE TITLE
视频播放问题！

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#880]
你好 当我视频播放到某一个时间段 暂停后切换到后台   
使用酷狗播放了会歌曲( 使用腾讯视频看视频 及 微信听语音无影响 )  
再次切换回Demo时 还在之前播放的页面 但是之前已播放的时长已经清空了 得从新开始播放 这是什么原因呢？

**Comment by Born-alone** [comment]
好的 刚测试了一下 setReleaseWhenLossAudio 设置为 false 可以了 
但是我项目里使用的是 2.1 版本  可能得改一下了

**Comment by Born-alone** [comment]
你好 项目中 我把使用的代码更新到最新的版本了  
调用 setReleaseWhenLossAudio(boolean releaseWhenLossAudio)  这个 设置为 false  
播放音乐后回到播放页 之前播放的还是会清空 得从头播 
会是什么原因呢！

**Comment by CarGuo** [comment]
DEMO 复现？
