### ISSUE TITLE
日志关闭无效

### ISSUE THREAD

**Issue by askskysun** [CarGuo/GSYVideoPlayer#881]
在application 中执行代码 GSYVideoManager.instance().setLogLevel(0);
还是会不断刷日志：
03-08 15:02:41.079 30562-31509/cn.ibingli.test D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
03-08 15:02:41.080 30562-31509/cn.ibingli.test D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-08 15:02:41.120 30562-31510/cn.ibingli.test D/IJKMEDIA: nal_unit_type: 9, nal_ref_idc: 0
03-08 15:02:41.120 30562-31510/cn.ibingli.test D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 0

**Comment by CarGuo** [comment]
GSYVideoManager.instance().setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);

**Comment by lz-ang** [comment]
GSYVideoManager.instance().setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);没有这个方法setLogLevel

**Comment by CarGuo** [comment]
IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT); @lz-ang

**Comment by Zaki0826** [comment]
设置这个还是会继续打印的。

**Comment by Zaki0826** [comment]
设置这个还是会继续打印log，还有解决办法吗？

**Comment by CarGuo** [comment]
@Zaki0826 打印的x是什么log

**Comment by Zaki0826** [comment]
> @Zaki0826 打印的x是什么log

nal_unit_type: 1, nal_ref_idc: 0
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 2

不停的打印这个

**Comment by Zaki0826** [comment]
> @Zaki0826 打印的x是什么log

@CarGuo 还是不停的打印这个。

nal_unit_type: 1, nal_ref_idc: 0
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 2
nal_unit_type: 1, nal_ref_idc: 2

**Comment by Zaki0826** [comment]
问题已解决。自己问题，多出代码没更改到。
