### ISSUE TITLE
切换播放速率变调问题！

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#884]
/**
     * 播放速度
     * 
     * @param speed      速度
     * @param soundTouch 是否对6.0下开启变速不变调
     */
    public void setSpeed(float speed, boolean soundTouch) {
        this.mSpeed = speed;
        this.mSoundTouch = soundTouch;
        if (getGSYVideoManager().getMediaPlayer() != null) {
            getGSYVideoManager().setSpeed(speed, soundTouch);
        }
    }
我的手机是MX5 Android系统5.0 的  soundTouch 这个状态不管设置什么 设置播放速率都会变调  
公司测试机是华为Mate9 Android系统7.0 oundTouch 这个状态不管设置什么 设置播放速率都不会变调 
请问怎么设置 才能适配所有系统 在设置播放速率的情况下不会变调！

**Comment by CarGuo** [comment]
@Override
    public void setSpeed(float speed, boolean soundTouch) 这个方法，需要在播放前设置才有效。


 public void setSpeedPlaying(float speed, boolean soundTouch) 这个是播放器设置

**Comment by Born-alone** [comment]
/**
     * 播放中生效的播放数据
     *
     * @param speed
     * @param soundTouch
     */
    public void setSpeedPlaying(float speed, boolean soundTouch) {
        setSpeed(speed, soundTouch);
        if (getGSYVideoManager().getMediaPlayer() != null) {
            if (getGSYVideoManager().getMediaPlayer() instanceof IjkMediaPlayer) {
                IjkMediaPlayer ijkMediaPlayer = (IjkMediaPlayer) getGSYVideoManager().getMediaPlayer();
                try {
                    ijkMediaPlayer.setSpeed(speed);
                    ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "soundtouch", (soundTouch) ? 1 : 0);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }
是呀 看Demo里 调用 setSpeedPlaying（）方法还是会调用  setSpeed（）
我按照Demo里的设置的 
/**
     * 显示比例
     * 注意，GSYVideoType.setShowType是全局静态生效，除非重启APP。
     */
    private void resolveTypeUI() {
        if (speed == 1) {
            speed = 1.5f;
        } else if (speed == 1.5f) {
            speed = 2f;
        } else if (speed == 2) {
            speed = 0.5f;
        } else if (speed == 0.5f) {
            speed = 0.25f;
        } else if (speed == 0.25f) {
            speed = 1;
        }
        changeSpeed.setText("播放速度：" + speed);
        detailPlayer.setSpeedPlaying(speed, false);
    }
都是这样的问题

**Comment by CarGuo** [comment]
setSpeedPlaying(float speed, boolean soundTouch) 播放中设置和播放器设置不一样，播放器设置的会直接获取player去设置option，setSpeed接口只会保存option，在播放开始时设置进去。

我这边在播放过程中，调用setSpeedPlaying(float speed, boolean soundTouch) 表现正常

**Comment by Born-alone** [comment]
好吧 我跑的Demo 调用 setSpeedPlaying(float speed, boolean soundTouch)  不管设置什么状态 都会变调 （Android 5.0  MX5 手机 ） 在7.0的手机表现正常

**Comment by Born-alone** [comment]
你好 刚刚找了一个5.1.1系统的模拟器测试了 调用setSpeedPlaying(float speed, boolean soundTouch) soundTouch不管设置为true 或 false 都会变调

**Comment by Born-alone** [comment]
这个问题该怎么解决

**Comment by CarGuo** [comment]
如果这么久没什么办法了

**Comment by Born-alone** [comment]
额 好吧  我再看看
