### ISSUE TITLE
可以把几个视频地址连接起来成一个视频播放吗？

### ISSUE THREAD

**Issue by askskysun** [CarGuo/GSYVideoPlayer#887]

**Comment by CarGuo** [comment]
concat协议或者m3u8都支持

**Comment by askskysun** [comment]
相关api在哪里呢

**Comment by CarGuo** [comment]
没有api，就是不同设置uri

**Comment by askskysun** [comment]
在代码中设置播放url是这样的  list的0是普通，1是清晰。。。播放时只播放list其中一个uri。那我怎样传入一个uri集合，一次连续播放每个uri呢。
List<SwitchVideoModel> list = new ArrayList<>();
        list.add(switchVideoModel);
            videoPlayer.setUp(list, true, "病例视频");

**Comment by CarGuo** [comment]
分片一般都是m3u8或者concat协议，你可以让服务端处理。
