### ISSUE TITLE
加载m3u8格式的速度很慢，得等十几秒

### ISSUE THREAD

**Issue by wtwt91** [CarGuo/GSYVideoPlayer#89]
如题，加载m3u8格式的速度很慢，得等十几秒，已经关闭了缓存
请问如何提高速度呢

**Comment by CarGuo** [comment]
这个和m3u8没太大关系

**Comment by wtwt91** [comment]
是不是播放器需要设置什么呢，感觉时间有点久，用JieCaoVideoPlayer加载一样的链接，很快的

**Comment by Wangct23** [comment]
我加载m3u8，秒进
