### ISSUE TITLE
设置缓存之后有的视频地址是MP4格式的但是报错~

### ISSUE THREAD

**Issue by MIkeeJY** [CarGuo/GSYVideoPlayer#891]
E/ProxyCache error: Error opening connection for http://v11-dy.ixigua.com/e061b3d6645e883e5070ef8671c5078b/5aa25b64/video/m/2206afb3353b40943aab854f45a254b9150115443e5000101ada9651200/ with offset 1367806. Version: 4.1.0

报错黑屏 而且不走onPlayError 的回调如何处理？

**Comment by CarGuo** [comment]
你得看mp4的视频编码和音频编码是什么，还有报错log

**Comment by MIkeeJY** [comment]
编码 H.264，AAC 设置缓存会出错...

**Comment by MIkeeJY** [comment]
@CarGuo 还有如果出现这种情况怎么监听回调啊？ 这个只会走onAutoComplete 不会走onPlayError

**Comment by CarGuo** [comment]
看起来是服务端和ijk兼容问题，你可以试试exo模式下看看
