### ISSUE TITLE
com.android.support:support-annotations:27.0.0 报错

### ISSUE THREAD

**Issue by handsome51jia** [CarGuo/GSYVideoPlayer#894]
Error:(29, 13) Failed to resolve: com.android.support:support-annotations:27.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:E:/workspace/yuzhoutai/dianying/dianying/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by handsome51jia** [comment]
我已经解决了，我的android studio 还是很古老的版本 2.2.2，本来想更新到3.1的，网上说，更新之后各种错误，有点怕怕就没有更新。这个包只有在google仓库中能找到，jcenter找不到。所以要在根目录下的build.gradle文件加点东西

如果你的android studio版本是3.0以上，加入下面东西
buildscript {                 
    repositories {
        google()
        jcenter()
    }
    dependencies {            
        classpath 'com.android.tools.build:gradle:3.0.1'

    }
}

allprojects {  //注意，要在这里加，别在buildscript里面加
    repositories {
        google()
        jcenter()
    }
}

如果你的android studio是3.0以下版本，加入下面东西
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
这样的话就可以支持大于26以上的support包了，解决此问题原文链接
https://stackoverflow.com/questions/47164768/failed-to-resolve-com-android-supportappcompat-v727-dependency-error

**Comment by CarGuo** [comment]
good！
