### ISSUE TITLE
怎么添加http请求头？

### ISSUE THREAD

**Issue by CloudGorgeous** [CarGuo/GSYVideoPlayer#896]
IjkMediaPlayer ijkMediaPlayer=new IjkMediaPlayer();
ijkMediaPlayer.setOption(OPT_CATEGORY_FORMAT, "headers", "xxxxxxx");
这样怎么不好使呢

**Comment by CarGuo** [comment]
setup的时候，这个mapheader，如果要设置useragent的，搜索下以前的issue

**Comment by CloudGorgeous** [comment]
多谢大神~这个问题解决了，但是加了http请求头以后用glide获取视频内的帧做封面的时候，显示的是加载失败的图片，这个您知道怎么解决吗？ @CarGuo

**Comment by CarGuo** [comment]
glide获取视频内的帧做封面，这个你得去看看glide加载的时候如何设置头
