### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method headerInjector

### ISSUE THREAD

**Issue by xmjharry** [CarGuo/GSYVideoPlayer#897]
java.lang.NoSuchMethodError: No virtual method headerInjector

**Comment by CarGuo** [comment]
demo中怎么复现这个问题？

**Comment by xmjharry** [comment]
我实在自己的项目中直接 compile 'com.shuyu:GSYVideoPlayer:4.1.0' 报的错误

**Comment by CarGuo** [comment]
headerInjector 这个应该是videocache的，估计要不就是方法数超过64k导致，要不就是你那边也有videocache之类的包冲突

**Comment by xmjharry** [comment]
我看了下External Libraries，只有一个com.danikula:videocache-2.7.0。至于方法数超过64K已经用MultiDexApplication解决。出现这个问题也是很诡异，目前setCacheWithPlay(false) 可以解决。

**Comment by CarGuo** [comment]
应该是com.shuyu:gsyvideoplayer-androidvideocache：xxxx

**Comment by xmjharry** [comment]
嗯 ，解决了，是我弄错了，谢谢哈。
