### ISSUE TITLE
rtmp直播 调用 videoPlayer.onVideoPause();后再重新播放就没有声音，除非重启app

### ISSUE THREAD

**Issue by askskysun** [CarGuo/GSYVideoPlayer#899]

**Comment by askskysun** [comment]
请问这个问题在哪里  我调用relaease，再播放也是没有声音

**Comment by CarGuo** [comment]
demo中怎么复现？
暂停之后，直播应该用这个恢复
```
/**
  * 恢复暂停状态
  *
  * @param seek 是否产生seek动作,直播设置为false
  */
 public static void onResume(String key, boolean seek)
```

**Comment by askskysun** [comment]
是在init调用 以下方法造成的，另外rtmp视频调用onpause后调用onresume是不能播放的，demo中可以重现。必须调用重新init才能播放。
VideoOptionModel videoOptionModel =
                    new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 10240);
            List<VideoOptionModel> list = new ArrayList<>();
            list.add(videoOptionModel);
            //第三个参数设置延迟  越低延迟越低   原来100   单位ms
            videoOptionModel =
                    new VideoOptionModel(1, "analyzemaxduration", 5);
            list.add(videoOptionModel);
            GSYVideoManager.instance().setOptionModelList(list);

**Comment by CarGuo** [comment]
直播要调用这个
```
/**
  * 恢复暂停状态
  *
  * @param seek 是否产生seek动作,直播设置为false
  */
 public static void onResume(String key, boolean seek)
```
