### ISSUE TITLE
请问如何在播放前跳转到指定位置?

### ISSUE THREAD

**Issue by Crystalbye** [CarGuo/GSYVideoPlayer#9]
指定位置 貌似没暴露这个方法

**Comment by CarGuo** [comment]
GSYVideoManager.instance().getMediaPlayer().seekTo(mSeekTimePosition);在prepare之后是可以，不过并不是很好，等会刚好要更新，我加上吧~

**Comment by Crystalbye** [comment]
好的 刚试了试在onPrepared里调用确实生效了 谢谢
