### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by ziabo** [CarGuo/GSYVideoPlayer#900]
大佬能不能做成那种有基础版和高级版的,比如基础版就保留横竖屏切换   调亮度  调声音  调进度这些基本功能,这样的话安装包就会小很多,多谢啦

**Comment by CarGuo** [comment]
其实呢，代码部分并不大，还不如一个so大，主要大小还是在so，所以目前区分了普通版so和进阶版exso，你还可以使用ijk最简版so，so才是占据项目大小的元凶。
你可以通过项目的问题集锦中，使用ndk过滤来使得编译的包体积减小，比如只打包v7a包。
