### ISSUE TITLE
我新自定义的ui，小屏播放好使，全屏的时候，就不管用了。

### ISSUE THREAD

**Issue by CloudGorgeous** [CarGuo/GSYVideoPlayer#901]
比如说我新添了一个分享的按钮，在小屏的 时候可以点击，但是全屏的时候，这个按钮点了，但是根本不走点击事件，这种情况怎么处理呢

**Comment by CarGuo** [comment]
因为小屏到全屏是一个同步切换，所以你需要参考demo，在全屏方法和恢复全屏方法中做同步，你看看demo的video目录下，应该都有注释。

**Comment by CloudGorgeous** [comment]
@Override
    public GSYBaseVideoPlayer startWindowFullscreen(Context context, boolean actionBar, boolean statusBar) {
        GSYBaseVideoPlayer gsyBaseVideoPlayer = super.startWindowFullscreen(context, actionBar, statusBar);
        if (gsyBaseVideoPlayer != null) {
            StandardGSYVideoPlayer gsyVideoPlayer = (StandardGSYVideoPlayer) gsyBaseVideoPlayer;
            gsyVideoPlayer.setLockClickListener(mLockClickListener);
            gsyVideoPlayer.setNeedLockFull(isNeedLockFull());
            initFullUI(gsyVideoPlayer);
            //比如你自定义了返回案件，但是因为返回按键底层已经设置了返回事件，所以你需要在这里重新增加的逻辑
        }
        return gsyBaseVideoPlayer;
    }
是照着这个写吗？那写了个接口回调，在这里把点击事件回调到activity里了，还是不行

**Comment by CloudGorgeous** [comment]
@CarGuo

**Comment by CarGuo** [comment]
你如果只是想把这里的按键点击回调到外面，那你可以直接重载init方法，然后直接写view.setonclickxxx，在onClick里把回调触发。

然后再重载cloneParams，把to 复制到from就好了

**Comment by CloudGorgeous** [comment]
把to复制到from是啥意思？

    @Override
    protected void cloneParams(GSYBaseVideoPlayer from, GSYBaseVideoPlayer to) {
        super.cloneParams(from, to);

    }
@CarGuo

**Comment by CloudGorgeous** [comment]
我一直是小屏点击事件好使，全屏不好使的

**Comment by CloudGorgeous** [comment]
@CarGuo 换过去了，但是现在按全屏按钮，是直接把页面翻成横屏的了，视频下面的内容还在……

**Comment by CloudGorgeous** [comment]
@CarGuo  大神，好了，解决了，是因为我继承的是ListGSYVideoPlayer，改成继承StandardGSYVideoPlayer就好了
