### ISSUE TITLE
急急急，列表播放的一个大问题

### ISSUE THREAD

**Issue by Angelvzp** [CarGuo/GSYVideoPlayer#902]
用您的Demo，当把所有的activity的android:theme="@style/Theme.AppCompat.Light.NoActionBar"，或者其他的没有ActionBar的theme，点击列表视频的最后一个item，播放后，点击全屏，就会黑屏出现播放按钮，不能接着播放。

**Comment by CarGuo** [comment]
你就試試全屏方法 actionbar 设置为false

**Comment by Angelvzp** [comment]
试了，也不好使

**Comment by CarGuo** [comment]
在demo中哪个页面怎么复现

**Comment by Angelvzp** [comment]
你把manifests中的RecyclerViewActivity中设置成android:theme="@style/Theme.AppCompat.Light.NoActionBar"没有actionbar，就会出现

**Comment by Angelvzp** [comment]
你好，你那边出现了么？

**Comment by CarGuo** [comment]
没有出现问题，按照如下设置，demo点击最后一个正常全屏

![default](https://user-images.githubusercontent.com/10770362/37327113-f055d6d0-26cf-11e8-98e8-04ee00e2f132.jpg)

**Comment by Angelvzp** [comment]
不好意思落了一步，你把你截图那个setShowFullAnimation(ture)变成setShowFullAnimation(false)就会复现，我试了好几次，都出现了问题

**Comment by Angelvzp** [comment]
列表的最后一个视频点击播放后，然后在全屏

**Comment by CarGuo** [comment]
也没有····如附件图片所示。


[效果.zip](https://github.com/CarGuo/GSYVideoPlayer/files/1805941/default.zip)

**Comment by CarGuo** [comment]
standardGSYVideoPlayer.startWindowFullscreen(context, false, true);  这个修改为false修改了吗

**Comment by Angelvzp** [comment]
改了，很确定

**Comment by CarGuo** [comment]
只能说你可以看看log，或者跟踪下代码，看看那个位置导致的，因为出现你说的黑屏停止，只有可能哪个地方触发了他重置了，比如RecyclerVIewActivity的onScrolled中，或者其他地方
