### ISSUE TITLE
找不到水印的demo在哪里，能给我说一下下不

### ISSUE THREAD

**Issue by Average77** [CarGuo/GSYVideoPlayer#903]

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/effect/GSYVideoGLViewCustomRender.java

**Comment by Average77** [comment]
高斯模糊的时候只能全部都模糊吗？能只模糊一小块吗？ @CarGuo

**Comment by CarGuo** [comment]
这个需要你会一点OpenGL的处理，可以的，不过需要你自己计算就是

**Comment by Average77** [comment]
能提供一下思路吗 @CarGuo

**Comment by CarGuo** [comment]
比如你可以看demo中有两个GSYVideoGLViewCustomRender4，其实就是两个绘制层，你需要将第二个绘制层的画面进行裁剪，然后再固定和第一层一样的位置，然后对齐高斯模糊···这是比较笨的做法。
如果高级一些，你估计需要自定义渲染层，现在项目是支持自定义你自己的渲染层的，在参考源码定义自己的渲染层，然后通过openGL计算对需要高斯的区域进行处理。

**Comment by Average77** [comment]
好的，谢谢哥，我琢磨琢磨 @CarGuo
