### ISSUE TITLE
急急急！大佬这个问题怎么解决。

### ISSUE THREAD

**Issue by DavaLc** [CarGuo/GSYVideoPlayer#904]
引入项目com.shuyu:GSYVideoPlayer:4.1.0
里面的v7包版本是22  
api   22  中  是这个    import android.suport.v7.internal.view.ContextThemeWrapper
我的项目 api是27    
v7包
api  27中  是这个  import  android.suport.v7.view.ContextThemeWrapper
那个类是  com.shuyu.gsyvideoplayer.utils.CommonUtil 。
项目编译不报错，运行报错。提示找不到 ContextThemeWrapper这个类

**Comment by CarGuo** [comment]
你看看错误的位置是哪里，目前保证传入的context是activity，就不会有这个问题。下个版本升级v7支持包

**Comment by DavaLc** [comment]
谢谢大佬，问题解决了。从一开始，就找错方向了。ps：大佬不玩qq吗？群里可热闹了。

**Comment by CarGuo** [comment]
@DavaLc QQ在pc上不了，被禁了，哈哈哈

**Comment by DavaLc** [comment]
大佬，如果只有一个fragment ，像demo里那么写没有问题。
但是多个fragment 还是会出现刚刚的报错。
  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.internal.view.ContextThemeWrapper"

我是这么添加的fragment

/**
     * 获取到fragment集合
     * @return
     */
    private ArrayList<Fragment> getFragments() {
        fragments.add(HotDramaFragment.newInstance());
        fragments.add(FilmFanFragment.newInstance());
        fragments.add(MessageFragment.newInstance());
        fragments.add(MyFragment2.newInstance());
        return fragments;
    }
    /**
     * 设置默认的fragment
     */
    public void setDefaultFragment() {
        setBottomView(0);
    }

    //设置底部导航栏的改变
    private void setBottomView(int i) {
        rljIv.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.tab_chat_2));
        rljTv.setTextColor(ContextCompat.getColor(this, R.color.color_888888));
        ysmIv.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.tab_fans_2));
        ysmTv.setTextColor(ContextCompat.getColor(this, R.color.color_888888));
        xsIv.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.tab_news_2));
        xsTv.setTextColor(ContextCompat.getColor(this, R.color.color_888888));
        myIv.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.tab_user_2));
        myTv.setTextColor(ContextCompat.getColor(this, R.color.color_888888));


        if (i == 0) {
            rljIv.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.tab_chat_1));
            rljTv.setTextColor(ContextCompat.getColor(this, R.color.color_f06868));
        } else if (i == 1) {
            if (mainLll.getVisibility()== View.GONE){
                showFooter();
            }
            ysmIv.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.tab_fans_1));
            ysmTv.setTextColor(ContextCompat.getColor(this, R.color.color_f06868));
        } else if (i == 2) {
            if (mainLll.getVisibility()==View.GONE){
                showFooter();
            }
            xsIv.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.tab_news_1));
            xsTv.setTextColor(ContextCompat.getColor(this, R.color.color_f06868));
        } else if (i == 3) {
            if (mainLll.getVisibility()==View.GONE){
                showFooter();
            }
            myIv.setImageDrawable(ContextCompat.getDrawable(this, R.drawable.tab_user_1));
            myTv.setTextColor(ContextCompat.getColor(this, R.color.color_f06868));
        }

        showFragment(i);

    }
    private int lastPosition = -1;//最后选择的位置
    private int curIndex = -1;// 当前选中的左侧菜单的下标
    //展示fragment
    public void showFragment(int index){
        if(index == lastPosition)
            return;
        FragmentManager fm = getSupportFragmentManager();
        FragmentTransaction trx = fm.beginTransaction();
        if(curIndex != -1)
            trx.hide(fragments.get(curIndex));


        if (!fragments.get(index).isAdded()) {
            trx.add(R.id.layFrame, fragments.get(index),
                    "fragment_" + index);
        }
        trx.show(fragments.get(index)).commitAllowingStateLoss();
        curIndex = index;
    }

    public void hideFooter(){
        mainLll.setVisibility(View.GONE);
    }
    public  void  showFooter(){
        mainLll.setVisibility(View.VISIBLE);
    }

**Comment by CarGuo** [comment]
多个fragment你试试用viewpager去承载
