### ISSUE TITLE
走到视频缓存那里报错了

### ISSUE THREAD

**Issue by CloudGorgeous** [CarGuo/GSYVideoPlayer#907]
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:136)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at com.danikula.videocache.HttpUrlSource.getMime(HttpUrlSource.java:190)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:60)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:40)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:230)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:51)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:332)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-13 08:55:09.704 31971-423/com.test.test2 W/System.err:     at java.lang.Thread.run(Thread.java:761)

    private void fetchContentInfo() throws ProxyCacheException {
        HttpURLConnection urlConnection = null;
        InputStream inputStream = null;
        try {
            urlConnection = openConnection(0, 10000);
            long length = getContentLength(urlConnection);
            String mime = urlConnection.getContentType();
            inputStream = urlConnection.getInputStream();//================到这一行报错
           this.sourceInfo = new SourceInfo(sourceInfo.url, length, mime);
            this.sourceInfoStorage.put(sourceInfo.url, sourceInfo);
        } catch (IOException e) {
            HttpProxyCacheDebuger.printfError("Error fetching info from " + sourceInfo.url, e);
        } finally {
            ProxyCacheUtils.close(inputStream);
            if (urlConnection != null) {
                urlConnection.disconnect();
            }
        }
    }

在detaillistvideo不报错，在list自动播放就报这个错，同一个视频，都加了useragent

**Comment by CarGuo** [comment]
看看是http什么错误，对于两个demo，播放控件逻辑没什么区别。

**Comment by CloudGorgeous** [comment]
好了，谢谢大神！可能是刚才那个链接不稳定，换了一个没事儿了
