### ISSUE TITLE
请问:为什么在fragment中播放会黑屏,activity则不会

### ISSUE THREAD

**Issue by o03150** [CarGuo/GSYVideoPlayer#908]
activityA启动activityB,
activityB中是一个viewPager,每一页是一个播放页fragment,结果是有声音无画面

**Comment by CarGuo** [comment]
一般有声音无画面的话，基本都是surface没构建成功

**Comment by o03150** [comment]
问题找到了,并不是fragment问题,而是我根布局是自定义的viewGroup,可以上下滑动的,雷士viewpager,只有上下两页,但是把StandardGSYVideoPlayer当成第一页就无法显示,是不是无法把StandardGSYVideoPlayer当成一个子控件放到自定义的viewGroup吗?

**Comment by o03150** [comment]
问题我找到了,我把StandardGsyPlayer放在自定义的ViewGroup,在onLayout时我加了一个判断,如果View尺寸没有变化就不重新布局,但是视频播放的时候好像每一帧都调用重新布局,因为view尺寸没有变化,所以后面重新布局也被过滤了,导致黑屏. 每刷新一帧就需要重新布局,不大合理吧@CarGuo

**Comment by CarGuo** [comment]
并不会每一帧都要刷新布局，播放的渲染层，其实是在点击播放的时候，才动态添加进去的，播放结束剔除，渲染层的布局也是代码添加计算的，所以没播放前是没有渲染层存在的。

黑屏的原因一般是创建的渲染层，没有处罚在onSurfaceAvailable回调，导致没构建出Surface去给ffmpeg绘制。
或者是渲染层在构建的时候，父布局有问题。

**Comment by o03150** [comment]
的确是,我的布局要调用到第六次才创建StandardGsyPlayer渲染层,也就是等到动态添加进去时重新布局,才会创建渲染层,允悲,这样我要放在自定义ViewGroup要怎么处理好呢?,我是测量几个子View,先整体布局一次,然后动态添加渲染层,在onLayout做个判断再重新布局一次吗?

**Comment by CarGuo** [comment]
渲染层是在GSYTextureRenderView的addTextureView方法下添加的，然后回调onSurfaceAvailable出来，你可以看看究竟哪里导致的问题。
如果有需要，继承后，重写addTextureView也可以

**Comment by o03150** [comment]
好的,感谢回答
