### ISSUE TITLE
布局问题

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#909]
GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL); 我设了后，
截图需要获得宽高，   MeasureHelper这个类里
   int width = View.getDefaultSize(mVideoWidth, widthMeasureSpec);
        int height = View.getDefaultSize(mVideoHeight, heightMeasureSpec);
        if (mCurrentAspectRatio == GSYVideoType.SCREEN_MATCH_FULL) {
           /* width = widthMeasureSpec;
            height = heightMeasureSpec;*/     }

widthMeasureSpec heightMeasureSpec 都是负的，导致了奔溃

**Comment by CarGuo** [comment]
demo中哪里复现

**Comment by maolubin** [comment]
设了就能复现，带控制DEMO，截图

**Comment by maolubin** [comment]
@CarGuo

**Comment by CarGuo** [comment]
确实，失策了，目前你可以参考demo，将代码拷贝出去，使用你自己的自定义渲染层。
参考
CustomTextureSurface
CustomRenderView
CustomRenderVideoPlayer
这三个类。记得用GSYTextureView的源码，因为TextureView才支持截图。
修改为如下就可以了。
```
  @Override
    public int getSizeH() {
        return getHeight();
    }

    @Override
    public int getSizeW() {
        return getWidth();
    }

```
下个版本将修改这个问题。

**Comment by maolubin** [comment]
if (mCurrentAspectRatio == GSYVideoType.SCREEN_MATCH_FULL) {
/* width = widthMeasureSpec;
height = heightMeasureSpec;*/  我目前把这注释了

**Comment by CarGuo** [comment]
只要能解决你目前问题就可以
