### ISSUE TITLE
视频被压扁了

### ISSUE THREAD

**Issue by hxzpp** [CarGuo/GSYVideoPlayer#910]
当我用这个m3u8流播放的时候（http://livecdn1.news.cn/Live_MajorEvent01Phone/manifest.m3u8），发现视频的画面有轻微的压扁了，应该2边补黑边才对哦。

**Comment by CarGuo** [comment]
你可以试试用 GSYVideoType.setShowType(xxx);去调整下，默认是会补黑边，根据视频返回比例去做调整的

**Comment by hxzpp** [comment]
试过了，没起效果

**Comment by hxzpp** [comment]
用节操播放器可以默认补黑边

**Comment by CarGuo** [comment]
你在demo的DetailControlActivity中，播放的时候点击默认比例，修改显示比例是可以调整的，我这边在demo中调整没发现什么问题，比如16:9

**Comment by hxzpp** [comment]
这个视频的真实比例是4：3的，用默认的模式，其实是有一点压缩的，只是看着不太明显

**Comment by CarGuo** [comment]
估计计算有一点偏差吧，你可以试试自定义渲染层去调整，参demo
CustomTextureSurface
CustomRenderView
CustomRenderVideoPlayer
这三个类。不过建议用GSYTextureView的源码，因为TextureView配合ijk的显示效果好一些。

**Comment by hxzpp** [comment]
我发现，如果我把MeasureHelper的doMeasure方法的95行  if (widthSpecMode == View.MeasureSpec.AT_MOST && heightSpecMode == View.MeasureSpec.AT_MOST) {这句话注释掉，视频就可以正常了，其他视频也正常了，

**Comment by hxzpp** [comment]
不知道有没有副作用，还请指导下

**Comment by CarGuo** [comment]
这是指定布局只在都是wrap_content的情况下才走这里，默认内部添加显示，在添加render的时候，是使用了match_parent，不过这个也是可以使用你自定义渲染层的时候处理。如果视频没有旋转角度的问题，一般你这样修改也没有问题

**Comment by hxzpp** [comment]
经过多次试验，有些视频获取的宽和高是不准确的，需要处理下就完美了， 
@Override
    public int getCurrentVideoHeight() {
        if (mVideoParamsListener != null) {
            if (getVideoSarNum() > 0 && getVideoSarDen() > 0)
                return mVideoParamsListener.getCurrentVideoWidth()*getVideoSarNum()/getVideoSarDen();
            else
                return mVideoParamsListener.getCurrentVideoHeight();
        }
        return 0;
    }

用这段代码，得到的视频高度才是真实的视频高度，效果非常好

**Comment by hxzpp** [comment]
比如http://livecdn1.news.cn/Live_MajorEvent01Phone/manifest.m3u8这个视频流，获取的宽高是720：400，但是实际的是533：400，经常上面这段代码处理下，就能得到正确的视频，就不会压缩了，你看下，能不能采用。

**Comment by CarGuo** [comment]
这个估计还得和视频旋转角度一起算上
