### ISSUE TITLE
哥，默认用的哪个播放器

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#912]
//GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER); //EXO 1 播放内核，弃用
        //GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2); //EXO 2 播放内核
        //GSYVideoManager.instance().setVideoType(this, GSYVideoType.SYSTEMPLAYER); //系统播放器

**Comment by CarGuo** [comment]
IJKPLAYER
