### ISSUE TITLE
哥，每次全屏，那个全屏video是每次新创建的吗

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#913]
那我返回小屏时，在那个全屏video中怎么监听呢

**Comment by maolubin** [comment]
监听，要返回到小屏了

**Comment by CarGuo** [comment]
你多看看源码吧

**Comment by maolubin** [comment]
@CarGuo 哥真没多少时间了，马上要出版本了，跪求指导

**Comment by CarGuo** [comment]
是重新创建，你看demo中有到全屏和到小屏之间的同步

**Comment by maolubin** [comment]
@CarGuo  但是startWindowFullscreen resolveNormalVideoShow这2方法都是在小屏video回调的啊

**Comment by maolubin** [comment]
@CarGuo 哦，明白了，resolveNormalVideoShow 这里面我操作全屏video的逻辑，会自动销毁全屏video的把

**Comment by CarGuo** [comment]
其实原理就是两个直接显示层控件的同步切换。
播放内核不变的情况下，将小屏幕A的控件状态和回调，clone出一个全屏的播放控件B。
将全屏控件的显示渲染设置到播放内核中，替换到小屏幕A。
恢复全屏的时候，销毁B，将B的状态同步回A，将A再设置回播放内核

**Comment by maolubin** [comment]
@CarGuo 大神就是牛啊
