### ISSUE TITLE
fragment列表里播放有画面没声音，而且demo里也是这样的.大佬这个怎么解决

### ISSUE THREAD

**Issue by DavaLc** [CarGuo/GSYVideoPlayer#914]
fragment列表里播放有画面没声音，而且demo里也是这样的。从fragment列表跳到全屏没有问题，有声音有界面。大佬这个怎么解决

**Comment by CarGuo** [comment]
demo里有些列表，设置了列表静音，你看源码注释就知道了

**Comment by DavaLc** [comment]
谢谢大佬，解决了。
