### ISSUE TITLE
哥，你那个悬浮FloatWindow

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#915]
我可以加动画吗，几秒后缩小至右下方，我想做个广告浮层放张图片

**Comment by maolubin** [comment]
@CarGuo 明天就要演示，真是焦头烂额了

**Comment by CarGuo** [comment]
FloatWindow 是另外一个库，这里只是作为demo演示，我也没太久深究，理论上是没什么问题的。
