### ISSUE TITLE
倍速播放问题

### ISSUE THREAD

**Issue by yyfBlog** [CarGuo/GSYVideoPlayer#916]
在倍速播放时 会在某一刻卡顿， 类似缓冲的感觉，且声音会比视频提早结束，播放的是本地视频，
设置如下
        mRealModeVideoView.setSpeed(1.5f, true);
        mRealModeVideoView.setUp(“本地URL”", false, "aaaa");
        mRealModeVideoView.setLooping(true);
        GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);
        mRealModeVideoView.startPlayLogic();

log日志如下：
 V/IJKMEDIA: stream 0, sample 4525, dts 150833333
         V/IJKMEDIA: stream 1, sample 6496, dts 150813605
         V/IJKMEDIA: stream 0, sample 4525, dts 150833333
        V/IJKMEDIA: stream 1, sample 6497, dts 150836825
         V/IJKMEDIA: stream 0, sample 4526, dts 150866667
        V/IJKMEDIA: stream 1, sample 6497, dts 150836825
         V/IJKMEDIA: stream 0, sample 4526, dts 150866667
         V/IJKMEDIA: stream 1, sample 6498, dts 150860045
         V/IJKMEDIA: stream 0, sample 4526, dts 150866667
        V/IJKMEDIA: stream 1, sample 6499, dts 150883265
        D/IJKMEDIA: ffp_toggle_buffering_l: start
         D/IJKMEDIA: FFP_MSG_BUFFERING_START:
        / D/IJKMEDIA: ffp_toggle_buffering_l: end
        D/IJKMEDIA: FFP_MSG_BUFFERING_END:
       V/IJKMEDIA: stream 0, sample 4527, dts 150900000
        V/IJKMEDIA: stream 1, sample 6499, dts 150883265
        V/IJKMEDIA: stream 0, sample 4527, dts 150900000
        V/IJKMEDIA: stream 1, sample 6500, dts 150906485
        D/IJKMEDIA: ffp_toggle_buffering_l: start
       D/IJKMEDIA: FFP_MSG_BUFFERING_START:
       D/IJKMEDIA: ffp_toggle_buffering_l: end
       D/IJKMEDIA: FFP_MSG_BUFFERING_END:
        V/IJKMEDIA: stream 0, sample 4528, dts 150933333
        V/IJKMEDIA: stream 1, sample 6500, dts 150906485
        V/IJKMEDIA: stream 0, sample 4528, dts 150933333
        V/IJKMEDIA: stream 1, sample 6501, dts 150929705
        V/IJKMEDIA: stream 0, sample 4528, dts 150933333
        V/IJKMEDIA: stream 1, sample 6502, dts 150952925
        V/IJKMEDIA: stream 0, sample 4529, dts 150966667
        V/IJKMEDIA: stream 1, sample 6502, dts 150952925
        V/IJKMEDIA: stream 0, sample 4529, dts 150966667
        V/IJKMEDIA: stream 1, sample 6503, dts 150976145
       D/IJKMEDIA: ffp_toggle_buffering_l: start
        D/IJKMEDIA: FFP_MSG_BUFFERING_START:
        D/IJKMEDIA: ffp_toggle_buffering_l: end
        D/IJKMEDIA: FFP_MSG_BUFFERING_END:
       V/IJKMEDIA: stream 0, sample 4530, dts 151000000
       V/IJKMEDIA: stream 1, sample 6503, dts 150976145
       V/IJKMEDIA: stream 0, sample 4530, dts 151000000
       V/IJKMEDIA: stream 1, sample 6504, dts 150999365
       V/IJKMEDIA: stream 0, sample 4530, dts 151000000
       V/IJKMEDIA: stream 1, sample 6505, dts 151022585
       D/IJKMEDIA: ffp_toggle_buffering_l: start
       D/IJKMEDIA: FFP_MSG_BUFFERING_START:
       D/IJKMEDIA: ffp_toggle_buffering_l: end
       D/IJKMEDIA: FFP_MSG_BUFFERING_END:
       V/IJKMEDIA: stream 0, sample 4531, dts 151033333
       V/IJKMEDIA: stream 1, sample 6505, dts 151022585
       V/IJKMEDIA: stream 0, sample 4531, dts 151033333
       V/IJKMEDIA: stream 1, sample 6506, dts 151045805
       V/IJKMEDIA: stream 0, sample 4532, dts 151066667
       V/IJKMEDIA: stream 1, sample 6506, dts 151045805
       V/IJKMEDIA: stream 0, sample 4532, dts 151066667
       V/IJKMEDIA: stream 1, sample 6507, dts 151069025
       D/IJKMEDIA: ffp_toggle_buffering_l: start
        D/IJKMEDIA: FFP_MSG_BUFFERING_START:
       D/IJKMEDIA: ffp_toggle_buffering_l: end
        D/IJKMEDIA: FFP_MSG_BUFFERING_END:
        V/IJKMEDIA: stream 0, sample 4533, dts 151100000
        V/IJKMEDIA: stream 1, sample 6507, dts 151069025
        V/IJKMEDIA: stream 0, sample 4533, dts 151100000
        V/IJKMEDIA: stream 1, sample 6508, dts 151092245
        V/IJKMEDIA: stream 0, sample 4533, dts 151100000
        V/IJKMEDIA: stream 1, sample 6509, dts 151115465
       D/IJKMEDIA: ffp_toggle_buffering_l: start
        D/IJKMEDIA: FFP_MSG_BUFFERING_START:
       D/IJKMEDIA: ffp_toggle_buffering_l: end
        D/IJKMEDIA: FFP_MSG_BUFFERING_END:
       V/IJKMEDIA: stream 0, sample 4534, dts 151133333
       V/IJKMEDIA: stream 1, sample 6509, dts 151115465
       V/IJKMEDIA: stream 0, sample 4534, dts 151133333
       V/IJKMEDIA: stream 1, sample 6510, dts 151138685
       V/IJKMEDIA: stream 0, sample 4535, dts 151166667
       V/IJKMEDIA: stream 1, sample 6510, dts 151138685
       V/IJKMEDIA: stream 0, sample 4535, dts 151166667
       V/IJKMEDIA: stream 1, sample 6511, dts 151161905
       V/IJKMEDIA: stream 0, sample 4535, dts 151166667
       V/IJKMEDIA: stream 1, sample 6512, dts 151185125
       D/IJKMEDIA: ffp_toggle_buffering_l: start
       D/IJKMEDIA: FFP_MSG_BUFFERING_START:
       D/IJKMEDIA: ffp_toggle_buffering_l: end
       D/IJKMEDIA: FFP_MSG_BUFFERING_END:
        V/IJKMEDIA: stream 0, sample 4536, dts 151200000
        V/IJKMEDIA: stream 1, sample 6512, dts 151185125
        V/IJKMEDIA: stream 0, sample 4536, dts 151200000
       D/IJKMEDIA: ffp_toggle_buffering_l: start
        D/IJKMEDIA: FFP_MSG_BUFFERING_START:
        D/IJKMEDIA: ffp_toggle_buffering_l: end
        D/IJKMEDIA: FFP_MSG_BUFFERING_END:
        V/IJKMEDIA: stream 0, sample 4537, dts 151233333
        V/IJKMEDIA: stream 0, sample 4538, dts 151266667
        V/IJKMEDIA: stream 0, sample 4539, dts 151300000
        V/IJKMEDIA: stream 0, sample 4540, dts 151333333
       V/IJKMEDIA: stream 0, sample 4541, dts 151366667

**Comment by CarGuo** [comment]
soundTouch为true模式下确实会存在这种可能，你试试问题集锦中的丢帧试试，25之类的系数看看

**Comment by yyfBlog** [comment]
丢帧后，没有问题了，感谢！
