### ISSUE TITLE
是否考虑支持通过颜色查找表来自定义滤镜

### ISSUE THREAD

**Issue by dengyuhan** [CarGuo/GSYVideoPlayer#917]
是否考虑支持通过颜色查找表来自定义滤镜

![image](https://user-images.githubusercontent.com/17588779/37388662-5c049dae-279c-11e8-912b-367f09ac5208.png)

**Comment by CarGuo** [comment]
不是很理解你的意思

**Comment by dengyuhan** [comment]
设计师一般是给滤镜的颜色二维图，解析这个图来达到自定义滤镜的效果，后续会考虑支持这个吗

**Comment by CarGuo** [comment]
应该不会，更多是直接OpenGL指定代码去处理，你说的这个方面目前不是我的领域
