### ISSUE TITLE
列表播放视频问题

### ISSUE THREAD

**Issue by YangShaoXiong** [CarGuo/GSYVideoPlayer#919]
1、一个滚动自动播放的视频列表，当有视频在自动播放时，切到后台，这时候视频暂停播放，再切回到前台，这时视频恢复播放，但是视频又重新加载了一遍。查看源码发现![](http://ww1.sinaimg.cn/mw690/bcb60a8dly1fpcix3k73pj218k0lfaah.jpg)
不明白作者为什么在视频暂停后，恢复播放的时候去执行seekto，而不是直接start()来恢复播放。

2、如果我把GSYVideoManager.onResume(false)中的参数设置成false，那么上述说的问题是解决了，但是又出现了一个新的问题，就是如果我的视频列表有item在播放视频，这时候我点击item，跳转到另一个页面，发现视频列表中的视频还在播放，我确定我在onPause方法中执行了GSYVideoManager.onPause()。

希望作者在百忙之中看下，提前谢谢，祝工作愉快。

**Comment by CarGuo** [comment]
第一个问题是因为，有些场景需要seek如实现重新加载链接，不然会无法继续播放。

第二个问题，你执行了onPause还继续播放，这个目前不大清除情况···不过demo中就有这样的场景，你可以试试，目前看来是没问题。

**Comment by YangShaoXiong** [comment]
我又试了一遍，确实是我写的问题。打扰！多谢解答
