### ISSUE TITLE
视频太大，超过1G了显示播放地址无效，该怎么办？

### ISSUE THREAD

**Issue by QueryGad** [CarGuo/GSYVideoPlayer#92]
视频太大，超过1G了显示播放地址无效，该怎么办？跪求解答

**Comment by CarGuo** [comment]
有链接吗？

**Comment by QueryGad** [comment]
http://200036379.vod.myqcloud.com/200036379_0a16a610ffff11e6897b4f91b042649d.f20.mp4用web可以播放，集成您的控制器就不行了。

**Comment by QueryGad** [comment]
http://200036379.vod.myqcloud.com/200036379_0a16a610ffff11e6897b4f91b042649d.f20.mp4这个链接  大概有一个多G就播放不了了，传了个720P的电影我试了试也播不出来！

**Comment by XXiaoQing** [comment]
我尝试在demo中是能够播放的，但是在快进或者快退（向左或者向右滑动）的时候有的问题

**Comment by QueryGad** [comment]
用哪个控件  我用的是项目中介绍的最基本那个StandardGSYVideoPlayer

**Comment by XXiaoQing** [comment]
你使用demo试试看吧，我随便找了个改下地址就能播放
