### ISSUE TITLE
大哥，问一下啊，怎么实现 进入播放页，当点击播放按钮时如果用户未登录，则跳到登录页，否则正常播放

### ISSUE THREAD

**Issue by bby0856** [CarGuo/GSYVideoPlayer#920]
detailPlayer.getStartButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (isLoggin){
                    //跳登录页
                }else{
                    //正常播放  这里怎么处理呢
                }
            }
        });

**Comment by CarGuo** [comment]
这个属于业务逻辑，不属于我的问题范围吧，你如果需要，继承后实现即可

**Comment by bby0856** [comment]
嗯，好的，需要继承哪些呢
