### ISSUE TITLE
请问有记录当前播放时长 下次播放该视频时继续从上次暂停的时间节点播放吗？

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#921]

**Comment by CarGuo** [comment]
没有我，这个功能你自己记录下就可以实现了，本身提供有setSeekOnStart接口

**Comment by lihong01** [comment]
退出播放时  可以调用一个api服务器保存播放时长   在另一个api返回回来     setSeekOnStart（“上次播放时长”）  @Born-alone
