### ISSUE TITLE
关于监听事件

### ISSUE THREAD

**Issue by Average77** [CarGuo/GSYVideoPlayer#922]
我现在的需求是 我们播放的视频是需要解析出来的，大概需要几秒时间才能解析出视频url，然后要监听到用户点了播放按钮，然后我们开始解析。
但是现在是如果不放一个url的话，VideoAllCallBack这个监听根本不走，如果先随便放url的话，说不定我们还没解析出来呢，然后那个url就开始播放了。
所以说就形成了一个矛盾，我们想获取点击播放按钮的监听然后解析出url，但是这个监听必须要有一个url才可以
你有什么解决办法吗？

**Comment by CarGuo** [comment]
你继承后，点击播放按钮走你的解析逻辑，之后在setup然后播放咯。或者服务端帮你走转发，或者你本地做一个代理service，做请求转发，都行

**Comment by Average77** [comment]
但是不setup的话根本不走监听

**Comment by CarGuo** [comment]
继承后你需要什么都可以重载啊，基本都是保护方法

**Comment by Average77** [comment]
那我要重载哪个方法比较合适呢？ @CarGuo

**Comment by Average77** [comment]
知道了，重载clickStartIcon（），谢谢大神
