### ISSUE TITLE
目前对滤镜，跟GL不是很明白

### ISSUE THREAD

**Issue by yovenny** [CarGuo/GSYVideoPlayer#923]
计划去看ffmpeg，请问滤镜、GL模式是调用ffmpeg命令吗，实时渲染视频输出吗？，有没有相关的文章或者关键字贴一下。但为什么渲染后的视频不能保存？

**Comment by yovenny** [comment]
好久没看更新功能挺多的，简书那篇文章有更新相关功能的说明吗？谢谢大佬

**Comment by yovenny** [comment]
GL 指的是openGL吗？

**Comment by CarGuo** [comment]
GL是指支持openGL的GLSurfaceView，这里的GL模式是对每一显示的帧渲染。文章很久没更新过了。
