### ISSUE TITLE
视频播放之前会黑一下

### ISSUE THREAD

**Issue by 371784711** [CarGuo/GSYVideoPlayer#926]
Q：
1.设置了封面，封面消失后，会黑一下再播放，很小的视频也是这样
2.能否自主控制封面的消失时间或者能否监听到视频从prepare到开始播放的状态，再然封面图片做延时消失，这样看起来会不会比较流畅
麻烦抽空帮忙看下，谢谢了 Tky!

**Comment by CarGuo** [comment]
这个你继承后，参考源码在哪里去除封面，可重新实现部分自定义逻辑。

**Comment by zsfzbc** [comment]
我和你一样的问题, 请问你是怎么解决的?
