### ISSUE TITLE
能不能直接跳到视频的某个时间点开始播放

### ISSUE THREAD

**Issue by askskysun** [CarGuo/GSYVideoPlayer#927]
调用setUp后直接调用seekTo没有用，还是从0开始播

**Comment by askskysun** [comment]
我在onpare之后再调用seekto没问题了 谢谢啦

**Comment by lihong01** [comment]
GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder();
        gsyVideoOption .setSeekOnStart(playTime)
                                   ...
                                 .build(detailPlayer);

**Comment by askskysun** [comment]
我在onpare之后再调用seekto会加载好久好像要缓存到跳转的时间才能播。
但是我像下面这样直接调用会报空指针    
GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder();
            gsyVideoOption.setSeekOnStart(currentVideoTime)
                             .build(videoPlayer);
            init();     //与demo中方法一致

**Comment by CarGuo** [comment]
setSeekOnStart或者问题集锦中的方法都可以实现
