### ISSUE TITLE
RTSP格式的不能播放，请大神帮忙重新编译SO文件，谢谢。

### ISSUE THREAD

**Issue by sanchibing** [CarGuo/GSYVideoPlayer#93]
RTSP格式的不能播放，请大神帮忙重新编译SO文件，谢谢。
现在主要用于摄像头播放。

**Comment by CarGuo** [comment]
RTSP目前没有支持，需要的话你要自己编译下so，在module.sh中配置上然后编译，编译的方法首页有

**Comment by sanchibing** [comment]
好的，谢谢，还有一个问题就是我们这一个断网的时间不会自动重新连接播放，这一个能解决不，谢谢

**Comment by CarGuo** [comment]
断网重连这一块你在ijkplayer的issue里找到很多答案
