### ISSUE TITLE
E/IJKMEDIA: Stream ends prematurely at 79146984, should be 467805871

### ISSUE THREAD

**Issue by wtuesta** [CarGuo/GSYVideoPlayer#930]
Good morning everyone has a problem, I hope you can give me some help please.
I have this problem:
E/IJKMEDIA: Stream ends prematurely at 79146984, should be 467805871
E/IJKMEDIA: stream 1, offset 0x4b7ba24: partial file
E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
E/IJKMEDIA: stream 1, offset 0x4b7bbe9: partial file
E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown

![error](https://user-images.githubusercontent.com/18019817/37557005-1c890e6c-29cc-11e8-9798-8e3dff0b8cfd.png)

Please, can someone help me with this problem?

I'm trying to do this, but there is no property, how can I do something similar?
mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect", 1);

Thanks from Peru!

**Comment by wtuesta** [comment]
I'm trying to do this, but there is no property, how can I do something similar?
mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect", 1);

**Comment by CarGuo** [comment]
Stream ends prematurely at 79146984, should be 467805871 
 look like video source error , or the network is unstable.
