### ISSUE TITLE
播放某些MP4文件黑屏，但是有声音

### ISSUE THREAD

**Issue by risechen** [CarGuo/GSYVideoPlayer#933]
http://p4qwant9x.bkt.clouddn.com/pc_1521113116117.mp4，这个是视频链接，使用的是StandardGSYVideoPlayer

**Comment by CarGuo** [comment]
使用ex so试试

**Comment by risechen** [comment]
你的意思是换成ex的播放器？

**Comment by risechen** [comment]
这个要怎么换成ex的

**Comment by CarGuo** [comment]
替换依赖的so为ex_so
