### ISSUE TITLE
PlayEmptyControlActivity播放界面都没有的么？

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#934]
不是纯播放的界面吗?我这播放界面都没有是什么情况

**Comment by CarGuo** [comment]
这个就是没有任何控制ui的，只有播放渲染界面的页面。你可以换一个url，有可能旧的url失效了

**Comment by i2863CookieZJ** [comment]
依旧不行哟。

**Comment by i2863CookieZJ** [comment]
![qq 20180320164648](https://user-images.githubusercontent.com/23622439/37644360-84288f04-2c5e-11e8-9b39-26ff279a6446.png)

这里只走else哟

**Comment by i2863CookieZJ** [comment]
![qq 20180320164648](https://user-images.githubusercontent.com/23622439/37644457-db3115b4-2c5e-11e8-8bbe-3fd85884ae13.png)
这个不走else 所以不能播

**Comment by CarGuo** [comment]
这个应该是带动画效果打开页面导致的吧

**Comment by i2863CookieZJ** [comment]
应该是 走if 但是addtransitionListener()也不走
