### ISSUE TITLE
播放速率改变有些视频没有效果

### ISSUE THREAD

**Issue by q990609179** [CarGuo/GSYVideoPlayer#935]
例如http://p20tpjy2y.bkt.clouddn.com/JHRN0107.mp4，这个链接的视频改变速率没有效果。

**Comment by q990609179** [comment]
找到原因了，是因为视频没有声音，我合了一个音频进去就可以改变速率了，但还有没有别的解决方法呀？求解！！

**Comment by CarGuo** [comment]
ijk是以音频为基准去变得，没音频没办法
