### ISSUE TITLE
硬解情况下，无缝切换出现画面卡住native_dequeueOutputBuffer

### ISSUE THREAD

**Issue by 1325679717** [CarGuo/GSYVideoPlayer#936]
java.lang.IllegalStateException
03-10 17:43:17.681 935-1154/com.example.gsyvideoplayer W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
03-10 17:43:17.681 935-1154/com.example.gsyvideoplayer W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)

**Comment by CarGuo** [comment]
硬解码不支持无缝
