### ISSUE TITLE
需要按两次才能播放视频

### ISSUE THREAD

**Issue by Average77** [CarGuo/GSYVideoPlayer#937]
加了header的视频，有的点第一次不播放，只有第二次点播放按钮才播放，这是为什么呢？

**Comment by CarGuo** [comment]
demo复现？可以看看log

**Comment by whj33** [comment]
我也遇到了这个问题
        VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "headers", "Referer: http://www.bilibili.com");
        List<VideoOptionModel> list1 = new ArrayList<>();
        list1.add(videoOptionModel);
        videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user-agent",  "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");
        list1.add(videoOptionModel);
        GSYVideoManager.instance().setOptionModelList(list1);

这个是添加进去的header    https://www.bilibili.com/video/av20868275/?spm_id_from=333.334.chief_recommend.17麻烦您帮忙看一下

**Comment by whj33** [comment]
下面是URL

**Comment by CarGuo** [comment]
header请在setup的时候，同时添加到mapheader里

**Comment by Average77** [comment]
多谢大神，解决了~万分感谢
