### ISSUE TITLE
播放本地视频失败

### ISSUE THREAD

**Issue by Icando26** [CarGuo/GSYVideoPlayer#94]
不能播放本地的视频，但是网络的是可以的，怎么回事呢 ？

**Comment by CarGuo** [comment]
请在demo中参数，并且请保证路径正常，本地视频和网络是不是同一个？

**Comment by Icando26** [comment]
就是下到里手机的视频，但是不能播放啊 -10000

**Comment by CarGuo** [comment]
不能播放可能是视频的格式不支持，比如视频格式或者音频格式。或者视频损坏，或者路径不对。
