### ISSUE TITLE
关于自定义UI，如何实现小屏和大屏中UI不一致

### ISSUE THREAD

**Issue by KafukaChen** [CarGuo/GSYVideoPlayer#941]
列表中播放视频，如何实现，比如，小屏模式下进度条不显示，或者下面的layout_bottom整个不显示，切换到大屏的时候显示layout_bottom

**Comment by CarGuo** [comment]
继承后自定义就可以了，你可以参考https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/GSYSampleADVideoPlayer.java  这里就是某种情况下会屏蔽进度条。 然后结合 https://github.com/CarGuo/GSYVideoPlayer/blob/master/app/src/main/java/com/example/gsyvideoplayer/video/LandLayoutVideo.java 

其实最简单的就是用 LandLayoutVideo 这个，然后返回两个布局，一个有底部，一个没有底部试试。

**Comment by KafukaChen** [comment]
谢谢，LandLayoutVideo的确简单方便许多。还有几个问题想要请教下，1：我下的项目是去年的，今天重下了一个，结果运行的时候报Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/shuyu/gsyvideoplayer/lib/BuildConfig;这个错误；2：我发现有些url的地址播放起来，底部的两个进度条都撑不满，右边空出一部分不加载，但是视频播放时完整的，不知道是不是时长问题；3：现在有个需求是在列表中播放时，不管点击播放button还是封面都能直接开启大屏播放，我找到的确有点击封面播放的api，但是点击直接大屏播放不知道怎么实现，求指教

**Comment by CarGuo** [comment]
1、因为demo中依赖重复了，你可以更新下，现在应该好了
2、你如果说是缓冲的进度没办法到100%，那是因为ijk的解析有时候缓冲确实不会到100%
3、点击直接大屏，你可以看看调用播放和全屏两个方法。

**Comment by KafukaChen** [comment]
问题解决！！！不过还有些小问题，怎么更改视频默认缩放比例呢？集成基类后在init（）中
        GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);
        changeTextureViewShowType();
        if (mTextureView != null){
            Log.d(TAG, "setScaleType: 4444");
            mTextureView.requestLayout();
        }
不起作用的，改不了播放比例，因为mTextureView 还是null的

**Comment by KafukaChen** [comment]
还有，设置了封面，但是加载的时候仍然是黑屏加载，怎么把封面显示出来

**Comment by CarGuo** [comment]
GSYVideoType.setShowType()是修改渲染比例，是全局生效的，至于封面问题，你可以继承后参考源码

**Comment by KafukaChen** [comment]
上面的问题都解决了。我想借鉴demo中的RecyclerView自动播放的例子，但是有问题，1、如果视频是第一个并且已经显示在屏幕内了，是一定不会播放的。2、因为我的不是全视频，也有图片的item，但是视频滑出屏幕后视频不会停止播放。3、视频自动播放极难触发，我的item比较大，基本上一条就占了快一屏，基本上要移动到特定的位置才有可能触发，不知道是要修改哪些参数

**Comment by CarGuo** [comment]
1、第一个都如果要自定播放，你直接打开页面后默认开始播放0位置的视频就可以了。
2、这个问题你要看看计算位置之类的
3、这个你还是得demo源码调整参数，因为这个只是demo中一种实现逻辑的参考
