### ISSUE TITLE
添加完header以后第一次不能播放，第二次才可以

### ISSUE THREAD

**Issue by whj33** [CarGuo/GSYVideoPlayer#942]
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "headers", "Referer: http://www.bilibili.com");
List list1 = new ArrayList<>();
list1.add(videoOptionModel);
videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user-agent", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");
list1.add(videoOptionModel);
GSYVideoManager.instance().setOptionModelList(list1);
这个是添加进去的header

 https://www.bilibili.com/video/av20868275/?spm_id_from=333.334.chief_recommend.17
这个是URL

麻烦您帮忙看一下

**Comment by whj33** [comment]
@CarGuo

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/937
