### ISSUE TITLE
进度条精度问题

### ISSUE THREAD

**Issue by o03150** [CarGuo/GSYVideoPlayer#943]
protected void setProgressAndTime(int progress, int secProgress, int currentTime, int totalTime)
这个方法返回的数据是不是不精确啊,比如底部进度条ottomProgressBar缓存进度secProgress,有时候缓存完成了,但没充满进度条,
我看到代码seekBar判断了94,这是根据什么来的,一旦最后返回的secProgress小于94,进度条就不能填满了
progress,secProgress每次结束返回的都没100,怎么解决 
`if (secProgress > 94) secProgress = 100;
        if (secProgress != 0 && !mCacheFile) {
            mProgressBar.setSecondaryProgress(secProgress);
    

        if (mBottomProgressBar != null) {
            if (progress != 0) mBottomProgressBar.setProgress(progress);
            if (secProgress != 0 && !mCacheFile)
                mBottomProgressBar.setSecondaryProgress(secProgress);
        }`

**Comment by o03150** [comment]
getGSYVideoManager().getMediaPlayer().getCurrentPosition();
播放器返回的进度貌似不一定的,比如3000ms,最后返回一般都是2900+ms

**Comment by CarGuo** [comment]
没办法到100是ijk播放内核的老问题了

**Comment by o03150** [comment]
mediaplayer有这问题吗?
