### ISSUE TITLE
视频播放不出来

### ISSUE THREAD

**Issue by Average77** [CarGuo/GSYVideoPlayer#944]
## 问题描述：

播放bilibili的视频源，加了bilibili的header，然后有的能播，有的不能播，想知道这种 http error 454是什么原因导致的

## 问题log（如果有）

03-21 11:04:37.124 27888-28048/com.test.test2 V/IJKMEDIA: header='HTTP/1.1 454 '
03-21 11:04:37.124 27888-28048/com.test.test2 V/IJKMEDIA: http_code=454
03-21 11:04:37.124 27888-28048/com.test.test2 W/IJKMEDIA: HTTP error 454 
03-21 11:04:37.124 27888-28048/com.test.test2 I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
03-21 11:04:37.125 27888-28048/com.test.test2 E/IJKMEDIA: http://upos-hz-mirroross.acgvideo.com/upgcxcode/14/09/19480914/19480914-1-16.mp4?e=ig8euxZM2rNcNbU3hwdVtWR17bdVhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IB5QK==&deadline=1521637185&dynamic=1&gen=playurl&oi=1928525859&os=oss&platform=html5&rate=58000&trid=c66a33cd4552418da888fc5984bea9de&uipk=5&uipv=5&um_deadline=1521637185&um_sign=df0880e3cb03d33ac1f949b3f6d3b5ba&upsig=b27634cc64bfe5b11941ce5c8ca5e91b: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
03-21 11:04:37.125 27888-28048/com.test.test2 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28048]
03-21 11:04:37.125 27888-28046/com.test.test2 D/IJKMEDIA: FFP_MSG_ERROR: 0
03-21 11:04:37.126 27888-27938/com.test.test2 E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

```

**Comment by CarGuo** [comment]
header如果在log上看到成功加上的话，还是没能越过反盗链，那也没办法

**Comment by Average77** [comment]
问视频解析那边，他们说“加了header，有部分手机或者电视盒，设置后，底层不一定生效的。”
哥，会有这种情况吗？ @CarGuo

**Comment by Average77** [comment]
@CarGuo  有的不用加header的播放的时候加载的时间特别长，长达一两分钟

**Comment by Average77** [comment]
这种有办法解决吗？ @CarGuo

**Comment by Average77** [comment]
我已经用了你发的那个
  VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "max-buffer-size", 1024);
        VideoOptionModel videoOptionModel2 =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "min-frames", 3);
        VideoOptionModel videoOptionModel3 =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probsize", "4096");
        VideoOptionModel videoOptionModel4 =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "analyzeduration", "2000000");
        VideoOptionModel videoOptionModel5 =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 50);
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        list.add(videoOptionModel2);
        list.add(videoOptionModel3);
        list.add(videoOptionModel4);
        list.add(videoOptionModel5);
        GSYVideoManager.instance().setOptionModelList(list);

确实别的快了点，但是那种加载时间特别长的还是很长时间QAQ

**Comment by CarGuo** [comment]
目前来说没什么办法了

**Comment by Average77** [comment]
好的，谢谢大神
