### ISSUE TITLE
视频缓存

### ISSUE THREAD

**Issue by xiaoxiaohang** [CarGuo/GSYVideoPlayer#945]
我看的是DetailPlayer，视频缓存完事了，断网点击播放 提示没有网络

**Comment by CarGuo** [comment]
demo中，DetailPlayer 没有开启缓缓存

**Comment by xiaoxiaohang** [comment]
那个是开启视频缓存的  是哪个DetailListPlayer  吗

**Comment by CarGuo** [comment]
.setCacheWithPlay(false)修改为true

**Comment by xiaoxiaohang** [comment]
我把DetailPlayer  您说的修改成true    运行点击播放  播放不了 一直转圈

**Comment by xiaoxiaohang** [comment]
因为 我运行不起来github上下载的版本  我只是把demo  模块 复制出来放到我能运行的项目里，我把CacheWithPlay   改成true  就播放不了了

**Comment by CarGuo** [comment]
你调整下demo就可以跑起来了的

**Comment by xiaoxiaohang** [comment]
我发现listview视频列表  在列表里播放  是没有声音的   点击全屏播放有声音   这个要怎么解决一下

**Comment by CarGuo** [comment]
因为设置了列表静音。你看demo源码就知道

**Comment by xiaoxiaohang** [comment]
谢谢  还有一个问题   我做了一个列表   列表上 能播放视频  缓存完事后    点击item进入详情页   这个视频已经缓存了 我应该怎么调这个缓存

**Comment by xiaoxiaohang** [comment]
还有 我发现只要退出这个app  缓存好的视频  在断网的情况下 也播放不了了

**Comment by CarGuo** [comment]
demo如果缓存成功了，你到本地是可以看到那个视频的，缓存的原理是本地服务代理下载，同时分发流给app

**Comment by xiaoxiaohang** [comment]
那默认的存储路径是什么

**Comment by xiaoxiaohang** [comment]
播放视频    holder.gsyVideoPlayer.setUp(list.get(position), true, new File(FileUtils.getTestPath()), "");
清除缓存的时候调GSYVideoManager.clearAllDefaultCache(this);     缓存还是没清掉

**Comment by CarGuo** [comment]
自定义了位置的，要用带url参数的到达，这个是清默认位置的
