### ISSUE TITLE
fragment下的recyleview里全屏播放，直接返回桌面了，却存在声音在播

### ISSUE THREAD

**Issue by Anayuta** [CarGuo/GSYVideoPlayer#947]
03-22 14:44:03.110 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.110 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.110 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.110 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.110 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.113 9044-9166/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.150 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.150 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.150 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.150 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.150 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.153 9044-9167/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.190 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.191 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.191 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.191 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.191 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.195 9044-9168/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.230 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.230 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.230 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.230 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.230 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.233 9044-9160/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.270 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.270 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.270 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.270 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.270 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.274 9044-9161/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.310 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.310 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.310 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.310 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.310 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.313 9044-9162/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.350 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.351 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.351 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.351 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.351 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.354 9044-9163/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.390 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.390 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.390 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.390 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.390 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.392 9044-9164/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.430 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.430 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.430 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.430 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.430 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.433 9044-9165/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.470 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.470 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.470 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.470 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.470 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.474 9044-9166/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2
03-22 14:44:03.510 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.510 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] query: BufferQueue has been abandoned
03-22 14:44:03.510 9044-9146/net.heishi.video E/BufferQueueProducer: [SurfaceTexture-0-9044-1] dequeueBuffer: BufferQueue has been abandoned
03-22 14:44:03.510 9044-9146/net.heishi.video E/Surface: dequeueBuffer failed (No such device)
03-22 14:44:03.510 9044-9146/net.heishi.video E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-22 14:44:03.514 9044-9167/net.heishi.video D/IJKMEDIA: nal_unit_type: 1, nal_ref_idc: 2

**Comment by CarGuo** [comment]
看看demo里有没有设置退到后台暂停

**Comment by Kevin1ee** [comment]
@CarGuo ，我也遇到这个问题了，看了你的demo，根据isPlay来进行Player的回收，但是isPlay是在onPrepare总置为true，如果没走到那一步，isPlay为false，此时没将player进行回收，它会继续在后台进行缓存然后播放，所以声音还是存在。试了下，直接回收还是存在这个问题。。。。。

**Comment by Anayuta** [comment]
我的是在fragment中的列表由列表播放，切换到全屏播放的时候，出现的。点击切换到全屏应用自己退到桌面了，然后声音还在，并没有进入全屏。

**Comment by CarGuo** [comment]
demo中怎么复现？

**Comment by Anayuta** [comment]
@CarGuo  demo目前没遇到，关于这情况一般属于哪个配置的问题呢？

**Comment by CarGuo** [comment]
manifest文件配置了没
