### ISSUE TITLE
smallVideoHelper和gsySmallVideoHelperBuilder有点问题

### ISSUE THREAD

**Issue by MirrorFlower** [CarGuo/GSYVideoPlayer#951]
我用的这个  视频列表是在ListView里 ，外层我用了个ScrollView嵌套了一下，然后用的smallVideoHelper和gsySmallVideoHelperBuilder，点击视频播放的时候，视频有播放声音，但是画面是白色的。

**Comment by CarGuo** [comment]
你嵌套的话，需要看看高度和内部渲染层是否创建成功

**Comment by darkrevier** [comment]
@MirrorFlower 朋友你这个问题怎么解决的
