### ISSUE TITLE
Duplicate files copied in APK lib/armeabi-v7a/libijkplayer.so

### ISSUE THREAD

**Issue by xiaoxnn** [CarGuo/GSYVideoPlayer#952]
依赖的库：
    compile 'com.shuyu:GSYVideoPlayer:4.1.0'
    compile 'com.shuyu:gsyVideoPlayer-java:4.1.0'
    compile 'com.shuyu:gsyVideoPlayer-ex_so:4.1.0'

报错：
com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libijkplayer.so
	File1: D:\androidStudioWorkSpace\MyAllDemo\app\build\intermediates\exploded-aar\com.shuyu\gsyVideoPlayer-armv7a\4.1.0\jni
	File2: D:\androidStudioWorkSpace\MyAllDemo\app\build\intermediates\exploded-aar\com.shuyu\gsyVideoPlayer-ex_so\4.1.0\jni

**Comment by CarGuo** [comment]
去掉第一个依赖

**Comment by xiaoxnn** [comment]
好了，谢谢了
