### ISSUE TITLE
rtsp流  mov  sdp 格式  不支持吗

### ISSUE THREAD

**Issue by zhouwenhao** [CarGuo/GSYVideoPlayer#954]
rtsp流  mov  sdp 格式  不支持吗

**Comment by CarGuo** [comment]
mov协议支持，试试这个
```

```
VideoOptionModel videoOptionModel = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtsp_transport", "tcp");
List<VideoOptionModel> list = new ArrayList<>();
list.add(videoOphtionModel);
GSYVideoManager.instance().setOptionModelList(list);
```
```

**Comment by IT-Talon** [comment]
还是不行呀，测试视频地址: rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov

**Comment by CarGuo** [comment]
如果不行说明协议不支持
