### ISSUE TITLE
视频一直处于加载中 日志如下  AVIndex stream 1, sample 259816, offset 447d7524, dts 266051584, size 249, distance 0, keyframe 1

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#956]
视频一直处于加载中，2分钟左右后就正常了， 日志如下 ，视频是百度云里面的 
播放搜狐的视频也是这样加载很慢，一直是下面的日志。
https://pan.baidu.com/s/1iNa1Dj5PV9nzxIJemGXHjg 密码: idmu 请问是哪的问题？是否百度云的问题

V/IJKMEDIA: AVIndex stream 1, sample 259816, offset 447d7524, dts 266051584, size 249, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259817, offset 447d761d, dts 266052608, size 236, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259818, offset 447d7709, dts 266053632, size 242, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259819, offset 447d77fb, dts 266054656, size 248, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259820, offset 447d78f3, dts 266055680, size 256, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259821, offset 447d79f3, dts 266056704, size 263, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259822, offset 447d7afa, dts 266057728, size 256, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259823, offset 447d7bfa, dts 266058752, size 260, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259824, offset 447d7cfe, dts 266059776, size 257, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259825, offset 447d7dff, dts 266060800, size 263, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259826, offset 447d7f06, dts 266061824, size 255, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259827, offset 447d8005, dts 266062848, size 264, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259828, offset 447d810d, dts 266063872, size 265, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259829, offset 447d8216, dts 266064896, size 251, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259830, offset 447d8311, dts 266065920, size 248, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259831, offset 447d8409, dts 266066944, size 265, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259832, offset 447d8512, dts 266067968, size 261, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259833, offset 447d8617, dts 266068992, size 243, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259834, offset 447d870a, dts 266070016, size 250, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259835, offset 447d8804, dts 266071040, size 249, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259836, offset 447d88fd, dts 266072064, size 263, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259837, offset 447e7bef, dts 266073088, size 258, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259838, offset 447e7cf1, dts 266074112, size 261, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259839, offset 447e7df6, dts 266075136, size 251, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259840, offset 447e7ef1, dts 266076160, size 262, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259841, offset 447e7ff7, dts 266077184, size 256, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259842, offset 447e80f7, dts 266078208, size 253, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259843, offset 447e81f4, dts 266079232, size 255, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259844, offset 447e82f3, dts 266080256, size 248, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259845, offset 447e83eb, dts 266081280, size 252, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259846, offset 447e84e7, dts 266082304, size 255, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259847, offset 447e85e6, dts 266083328, size 254, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259848, offset 447e86e4, dts 266084352, size 286, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259849, offset 447e8802, dts 266085376, size 282, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259850, offset 447e891c, dts 266086400, size 245, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259851, offset 447e8a11, dts 266087424, size 264, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259852, offset 447e8b19, dts 266088448, size 257, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259853, offset 447e8c1a, dts 266089472, size 253, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259854, offset 447e8d17, dts 266090496, size 257, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259855, offset 447e8e18, dts 266091520, size 261, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259856, offset 447e8f1d, dts 266092544, size 257, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259857, offset 447e901e, dts 266093568, size 249, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259858, offset 447e9117, dts 266094592, size 249, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259859, offset 447f740a, dts 266095616, size 259, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259860, offset 447f750d, dts 266096640, size 255, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259861, offset 447f760c, dts 266097664, size 250, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259862, offset 447f7706, dts 266098688, size 254, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259863, offset 447f7804, dts 266099712, size 285, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259864, offset 447f7921, dts 266100736, size 293, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259865, offset 447f7a46, dts 266101760, size 289, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259866, offset 447f7b67, dts 266102784, size 279, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259867, offset 447f7c7e, dts 266103808, size 259, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259868, offset 447f7d81, dts 266104832, size 253, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259869, offset 447f7e7e, dts 266105856, size 242, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259870, offset 447f7f70, dts 266106880, size 245, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259871, offset 447f8065, dts 266107904, size 297, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259872, offset 447f818e, dts 266108928, size 274, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259873, offset 447f82a0, dts 266109952, size 252, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259874, offset 447f839c, dts 266110976, size 239, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259875, offset 447f848b, dts 266112000, size 235, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259876, offset 447f8576, dts 266113024, size 241, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259877, offset 447f8667, dts 266114048, size 231, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259878, offset 447f874e, dts 266115072, size 243, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259879, offset 447f8841, dts 266116096, size 246, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259880, offset 448077f3, dts 266117120, size 246, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259881, offset 448078e9, dts 266118144, size 251, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259882, offset 448079e4, dts 266119168, size 257, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259883, offset 44807ae5, dts 266120192, size 296, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259884, offset 44807c0d, dts 266121216, size 294, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259885, offset 44807d33, dts 266122240, size 293, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259886, offset 44807e58, dts 266123264, size 260, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259887, offset 44807f5c, dts 266124288, size 257, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259888, offset 4480805d, dts 266125312, size 262, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259889, offset 44808163, dts 266126336, size 255, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259890, offset 44808262, dts 266127360, size 254, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259891, offset 44808360, dts 266128384, size 234, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259892, offset 4480844a, dts 266129408, size 258, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259893, offset 4480854c, dts 266130432, size 245, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259894, offset 44808641, dts 266131456, size 243, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259895, offset 44808734, dts 266132480, size 246, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259896, offset 4480882a, dts 266133504, size 234, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259897, offset 44808914, dts 266134528, size 243, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259898, offset 44808a07, dts 266135552, size 243, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259899, offset 44808afa, dts 266136576, size 252, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259900, offset 44808bf6, dts 266137600, size 236, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259901, offset 44808ce2, dts 266138624, size 250, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259902, offset 44817596, dts 266139648, size 252, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259903, offset 44817692, dts 266140672, size 259, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259904, offset 44817795, dts 266141696, size 240, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259905, offset 44817885, dts 266142720, size 248, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259906, offset 4481797d, dts 266143744, size 254, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259907, offset 44817a7b, dts 266144768, size 251, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259908, offset 44817b76, dts 266145792, size 253, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259909, offset 44817c73, dts 266146816, size 264, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259910, offset 44817d7b, dts 266147840, size 249, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259911, offset 44817e74, dts 266148864, size 250, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259912, offset 44817f6e, dts 266149888, size 241, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259913, offset 4481805f, dts 266150912, size 259, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259914, offset 44818162, dts 266151936, size 242, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259915, offset 44818254, dts 266152960, size 250, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259916, offset 4481834e, dts 266153984, size 257, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259917, offset 4481844f, dts 266155008, size 260, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259918, offset 44818553, dts 266156032, size 258, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259919, offset 44818655, dts 266157056, size 261, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259920, offset 4481875a, dts 266158080, size 240, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259921, offset 4481884a, dts 266159104, size 260, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259922, offset 4481894e, dts 266160128, size 259, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259923, offset 44826bb7, dts 266161152, size 248, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259924, offset 44826caf, dts 266162176, size 255, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259925, offset 44826dae, dts 266163200, size 246, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259926, offset 44826ea4, dts 266164224, size 252, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259927, offset 44826fa0, dts 266165248, size 258, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259928, offset 448270a2, dts 266166272, size 248, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259929, offset 4482719a, dts 266167296, size 246, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259930, offset 44827290, dts 266168320, size 268, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259931, offset 4482739c, dts 266169344, size 271, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259932, offset 448274ab, dts 266170368, size 267, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259933, offset 448275b6, dts 266171392, size 254, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259934, offset 448276b4, dts 266172416, size 252, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259935, offset 448277b0, dts 266173440, size 262, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259936, offset 448278b6, dts 266174464, size 255, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259937, offset 448279b5, dts 266175488, size 263, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259938, offset 44827abc, dts 266176512, size 237, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259939, offset 44827ba9, dts 266177536, size 242, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259940, offset 44827c9b, dts 266178560, size 256, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259941, offset 44827d9b, dts 266179584, size 262, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259942, offset 44827ea1, dts 266180608, size 251, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259943, offset 44827f9c, dts 266181632, size 252, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259944, offset 44828098, dts 266182656, size 266, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259945, offset 4483620b, dts 266183680, size 261, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259946, offset 44836310, dts 266184704, size 265, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259947, offset 44836419, dts 266185728, size 252, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259948, offset 44836515, dts 266186752, size 264, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259949, offset 4483661d, dts 266187776, size 252, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259950, offset 44836719, dts 266188800, size 259, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259951, offset 4483681c, dts 266189824, size 247, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259952, offset 44836913, dts 266190848, size 255, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259953, offset 44836a12, dts 266191872, size 253, distance 0, keyframe 1
V/IJKMEDIA: AVIndex stream 1, sample 259954, offset 44836b0f, dts 266192896, size 249, distance 0, keyframe 1

**Comment by CarGuo** [comment]
看起来源问题
