### ISSUE TITLE
mp3播放不了吗？

### ISSUE THREAD

**Issue by youyoubt** [CarGuo/GSYVideoPlayer#960]
mp3播放不了吗？部分日志如下：
W/IJKMEDIA: No codec could be found with id 86016
 A/IJKMEDIA: Failed to open file '/sdcard/1111.mp3' or configure filtergraph

**Comment by CarGuo** [comment]
可以播放

**Comment by youyoubt** [comment]
准确的说是mp2，后面我自己编译了一份so，加入了这个解码就可以播放了。谢谢你。
不过还有个问题，播放音频，有时会出现专辑图片，有时不出现（同一个mp3），这个是啥原因？

**Comment by CarGuo** [comment]
封面出现与否，和播放状态有关。

**Comment by youyoubt** [comment]
不是封面，是专辑图片，播放mp3的时候，ijk会显示一张专辑图片，这个图片是渲染在textureView中的。。而不是我们给播放器设置的封面。

**Comment by youyoubt** [comment]
@CarGuo 感觉是已经开始播放了，但是还没有surface的问题。。是不是要先有surface，然后再进行播放？提早addTexture？

**Comment by CarGuo** [comment]
你可以继承后调整顺序，毕竟你看demo Manager Player 都可以自定义
