### ISSUE TITLE
列表中视频播放位置

### ISSUE THREAD

**Issue by DavaLc** [CarGuo/GSYVideoPlayer#961]
大佬。
列表中，视频A播放，
滑动后，视频A暂停。
再次播放视频A，
能从上次A视频暂停的位置开始播放吗？而不是从头开始播放

**Comment by DavaLc** [comment]
用的listview，我应该在哪里用getCurrentPositionWhenPlaying（）比较好

**Comment by DavaLc** [comment]
已解决。

**Comment by yangfeng1994** [comment]
大佬是怎么解决的？
