### ISSUE TITLE
我播放视频 需要默认静音，但是每次释放资源的时候，静音有打开了，有没有方法可以直接静音

### ISSUE THREAD

**Issue by luhui2014** [CarGuo/GSYVideoPlayer#962]
我播放视频 需要默认静音，但是每次释放资源的时候，静音有打开了，有没有方法可以直接静音.

我在list 列表中播放视频，是静音的，然后列表移除屏幕的时候，会把视频资源释放掉，这时候，静音有打开了，下次出现该 item 的时候，会出现 声音，类似嘀一下的声音。

求解！

**Comment by DavaLc** [comment]
自己写个单例，判断是不是静音。不仅可以默认让你静音，还可以让你控制列表中、详情里，静音的开关。

**Comment by luhui2014** [comment]
boolean isNeedMute = GSYVideoManager.instance().isNeedMute();
这个方法返回都是true 了，但是 播放还是有声音

**Comment by DavaLc** [comment]
你应该把这个加载adapter里面，如果你加载activity  或者fragment是没有用的。
你 在setVideoAllCallBack（）回调中这几个方法，
onClickStartIcon（），onPrepared，onQuitFullscreen，onEnterFullscreen
分别加上     GSYVideoManager.instance().setNeedMute(true);;这句话。

**Comment by luhui2014** [comment]
好的，已经加上去了。我发现在onStarPrepared ,和 onPrepared 这2个方法里面 分别 调用，boolean isNeedMute = GSYVideoManager.instance().isNeedMute();，返回结果还是不一样的，现在我都加上去了，好像是可以了，待进一步测试。

**Comment by luhui2014** [comment]
试了，还是有点问题，在 list item 滑动出屏幕的时候，调用 GSYVideoManager.releaseAllVideos();
在进入屏幕的自动播放，期间还是会 有嘟的一声，声音 由开到关。

在adapter 里面写的关闭声音
``

`Log.d("AAAA","homeAdapter --- ---- 未播放的状态");
                        holder.bannerImage.setVisibility(View.VISIBLE);
                        holder.controlVideo.setPlayTag(TAG);
                        holder.controlVideo.setJumpUrl(jumpUrl);
                        holder.controlVideo.setLooping(true);//循环播放
                        holder.controlVideo.setPlayPosition(position+1); //存在2个头部
                        holder.controlVideo.setReleaseWhenLossAudio(false);
                        holder.controlVideo.setVideoAllCallBack(new GSYSampleCallBack(){
                            @Override
                            public void onStartPrepared(String url, Object... objects) {
                                Log.d("AAAA","homeAdapter --- ---- onStartPrepared");
                                GSYVideoManager.instance().setNeedMute(true);
                                super.onStartPrepared(url, objects);
                            }

                            @Override
                            public void onPrepared(String url, Object... objects) {
                                boolean isNeedMute = GSYVideoManager.instance().isNeedMute();
                                if(!isNeedMute){
                                    GSYVideoManager.instance().setNeedMute(true);
                                }
                                Log.d("AAAA","homeAdapter --- ---- onPrepared isNeedMute="+isNeedMute);

                                Message message = Message.obtain();
                                message.what = MESSAGE_BANNER_IMAGE;
                                message.obj = holder.bannerImage;
                                mHandler.sendMessageDelayed(message,300);

                                super.onPrepared(url, objects);
                            }


                            @Override
                            public void onPlayError(String url, Object... objects) {
                                Log.d("AAAA","homeAdapter --- ---- onPlayError");
                                holder.bannerImage.setVisibility(View.VISIBLE);
                                super.onPlayError(url, objects);
                            }
                        });

                        String sdCardPath = CommonUtils.getDiskCacheDir(context);
                        final File file = new File(sdCardPath + "/" + Constants.ROLL_BANNER_VIDEO_FILENAME);
                        holder.controlVideo.setUpLazy(videoUrl, true, file, null, "");`

**Comment by luhui2014** [comment]
建议 默认 改成 静音状态 ，在用户角度上 静音 变成 有声音 感知不到有问题 ，但是 从有声音 变成 静音 ，可能由于各种原因（类似不同的机型，华为 是无感知的，小米 三星 小概率出现 呲的声音，即有声音变成静音的过程，锤子，oppo 之类的 大概率出现 呲 的声音，存在一个有声音到静音的过程 ）；

因为我们需求是 需要一个静音的视频广告，加上声音控制开关，所以会出现这个问题，因为在 onPrepared 的方法中设置静音，在部分手机上出现呲的声音，。

至于 默认 视频 是打开声音的，默认是静音 会不会造成影响 ，个人感觉 没有太大影响，在视频准备好直接开声音就好了，延迟个 100-200 毫秒，是无感知的！

**Comment by CarGuo** [comment]
你可以参考demo，创建自己的自定义Manager
