### ISSUE TITLE
需要更换大的播放暂停按钮，但是那个是自定义view

### ISSUE THREAD

**Issue by Average77** [CarGuo/GSYVideoPlayer#963]
如题，有办法改吗？

**Comment by CarGuo** [comment]
看demo，你继承后返回自己的布局就可以了，如果是普通imageview，就继承NormalGSYVideoPlayer。

**Comment by Average77** [comment]
不是那个小的，是ENPlayView这个，猫大人~这个是你用自定义view画出来的，我要怎么改成我想要的图标呢？ @CarGuo

**Comment by Average77** [comment]
晓得了，把那个换掉不用，直接用imageview。谢谢猫大人~
