### ISSUE TITLE
关于视频全屏bug

### ISSUE THREAD

**Issue by millerzhu** [CarGuo/GSYVideoPlayer#964]
机型  大部分机型都可以重现 项目里概率大概1/10~1/20

**Comment by millerzhu** [comment]
`.setLockLand(true)
 .setShowFullAnimation(false)`  recyclerviewactivity的那个demo设置锁定横屏不要动画 后点播放视频 后立马点全屏播放  全屏后有时会黑屏 demo里是暂停 我的项目里是黑屏 但是报的是同样的错误 `03-28 17:52:23.791 27647-1767/com.yr.mmpic E/Surface: dequeueBuffer failed (No such device)
03-28 17:52:23.791 27647-1767/com.yr.mmpic E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-28 17:52:23.804 27647-27647/com.yr.mmpic E/SensorManager: RegisterListener ACCELEROMETER type:1 delay:200000us by android.view.OrientationEventListener$SensorEventListenerImpl
03-28 17:52:23.856 27647-1767/com.yr.mmpic E/Surface: dequeueBuffer failed (No such device)
03-28 17:52:23.856 27647-1767/com.yr.mmpic E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-28 17:52:23.925 27647-1767/com.yr.mmpic E/Surface: dequeueBuffer failed (No such device)
03-28 17:52:23.925 27647-1767/com.yr.mmpic E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
03-28 17:52:24.208 27647-27812/com.yr.mmpic E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd2beb640)
03-28 17:52:24.209 27647-27812/com.yr.mmpic E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd2beb680)
03-28 17:52:24.210 27647-27812/com.yr.mmpic E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xd803b800)
03-28 17:52:25.710 27647-27647/com.yr.mmpic E/SensorManager: unRegisterListener by android.view.OrientationEventListener$SensorEventListenerImpl` 求大佬指点下

**Comment by millerzhu** [comment]
我试了 只要不锁定横屏 或者.setShowFullAnimation(true)时 就不会有以上问题

**Comment by millerzhu** [comment]
已解决 需在adapter里的enterFullScreen的回调里 设置activity或者fragment里mFull为true recyclerview的scroll监听就是依据此boolean只来releaseAllVideo的。

**Comment by CarGuo** [comment]
已补充到demo
