### ISSUE TITLE
android 4.4 全屏顶部状态栏不隐藏，已配置startWindowFullscreen(PlayActivity.this, false, true);

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#967]
android 4.4 全屏顶部状态栏不隐藏，已配置startWindowFullscreen(PlayActivity.this, false, true);
在demo中 没问题，
android 大于4.4高版本的全屏也没问题。
我还需要在哪设置什么吗

**Comment by CarGuo** [comment]
demo中没问题？

**Comment by yang0000meng** [comment]
这么快就回答了，哈哈 
demo中没问题，
我也不知道我这哪有问题

**Comment by yang0000meng** [comment]
http://s5.sinaimg.cn/middle/001knM4rzy7jidyKoVm54&690  图片 顶部状态栏不隐藏

**Comment by CarGuo** [comment]
demo不复现···我也很懵逼啊= =
