### ISSUE TITLE
本地mov格式视频

### ISSUE THREAD

**Issue by YellowXiong** [CarGuo/GSYVideoPlayer#969]
## 问题描述：

播放本地mov格式视频出现只有画面没有声音的情况
用Demo的PlayActivity测试也是一样
请问楼主是要自己重新编译so支持吗

## 问题机型/系统：

小米6 Android7.0

编码方式
General
Format                                   : MPEG-4
Format profile                           : QuickTime
Codec ID                                 : qt   2005.03 (qt  )
Encoded date                             : UTC 2018-03-16 06:37:17
Tagged date                              : UTC 2018-03-16 06:47:30
Writing library                          : Apple QuickTime

Video
Format                                   : AVC

Audio
Format                                   : PCM

**Comment by CarGuo** [comment]
如果是正常的pcm音频，应该不会没声音

**Comment by YellowXiong** [comment]
但是用其他播放器 比如说jiaozi那个开源的就有声音
电脑播放也有声音
用我们这个就没有声音了  
用大神你的Demo直接测试也没有声音
就觉得可能是不是so库的问题

**Comment by CarGuo** [comment]
就是so对这类型的pcm支持问题

**Comment by YellowXiong** [comment]
好的 谢谢哦

**Comment by CarGuo** [comment]
你可以切换项目中的explayer加surface 模式试试

**Comment by YellowXiong** [comment]
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
        GSYVideoManager.instance().setVideoType(this,2);
切换explayer之后播放不了
用系统的可以播放但是也还是没有声音
