### ISSUE TITLE
部分m3u8文件快进不了

### ISSUE THREAD

**Issue by EvlinLee** [CarGuo/GSYVideoPlayer#97]
测试地址：http://120.24.82.57:8080/cloudAnalysis/test/getM3u8PlayAddress.m3u8

**Comment by CarGuo** [comment]
快进不了应该和视频的源有关，比如一些视频压缩或者关键帧太少，恰巧ffmpeg的快进是找附近的关键帧，很不幸如果遇到这样的视频，目前ijk给我的答复是ffmpeg的问题，但是一直没修复。

**Comment by EvlinLee** [comment]
@CarGuo 切换成EXOPlayer就可以，ijk的不行

**Comment by CarGuo** [comment]
因为exo和ijk不一样～
