### ISSUE TITLE
横竖屏切换

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#974]
横竖屏如何保存数据？

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyVideoPlayer-java/src/main/java/com/shuyu/gsyvideoplayer/video/base/GSYBaseVideoPlayer.java   

protected void cloneParams(GSYBaseVideoPlayer from, GSYBaseVideoPlayer to)
