### ISSUE TITLE
跳转到另外一个界面，再回来，一直在缓冲

### ISSUE THREAD

**Issue by Demidong** [CarGuo/GSYVideoPlayer#975]
在播放直播流时，如果跳转到其他界面，或者按home按键，再切回到该界面，就会一直在缓冲，缓冲dialog会一直转，无法回到播放状态，只有finish后，重新进入才行。不知道是什么原因。 例子 ： http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8

**Comment by CarGuo** [comment]
试试 
```

/**
  * 恢复暂停状态
  *
  * @param seek 是否产生seek动作,直播设置为false
  */
 public static void onResume(String key, boolean seek)
```

**Comment by Demidong** [comment]
我还在使用2.0版本，升级版本后，使用这个方法完全解决我的问题，谢谢。
