### ISSUE TITLE
React Native中使用时，有时播放时黑屏，只有声音。

### ISSUE THREAD

**Issue by hnyaoqingping** [CarGuo/GSYVideoPlayer#981]
（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

真机 魅蓝 note

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```
我在React Native中封装GSYVideoPlayer，有时播放时黑屏，只有声音。这种现象随机出现。用“Layout Inspector”察看，黑屏时“PhoneWindow$DecorView->LinearLayout->content(FrameLayout)->0xB(ReactRootView)->0x8(GPlayerView)->StandardGSYVideoPlayer->RelativeLayout->surface_container(RelativeLayout)->GSYTextureView”的高和宽为0
另外，在React Native下，CommonUtil.java的函数showSupportActionBar、hideSupportActionBar函数要修改，不然点击全屏时，闪退。

**Comment by CarGuo** [comment]
目前该项目暂无支持react native的计划，所以并没有针对react native适配。高宽为0，一般都是父控件问题导致。至于showSupportActionBar、hideSupportActionBar崩溃的问题问题点是？

**Comment by hnyaoqingping** [comment]
在React Native中，ReactActivity继承于Activity。CommonUtil.getAppCompActivity(context)返回null，所以会闪退。如果不打算支持react native，这就不是问题。
黑屏的问题，我修改了GSYRenderView.java的addToParent函数，手动调用measure和layout函数，试了好多次，暂时没发现黑屏了。
我目前的问题是解决了，还有个小问题是播放视频的准备时间有点久。
再次感谢您的视频库。

**Comment by CarGuo** [comment]
好的，多谢提醒，我看后面增加下处理。

**Comment by poison8** [comment]
> 在React Native中，ReactActivity继承于Activity。CommonUtil.getAppCompActivity(context)返回null，所以会闪退。如果不打算支持react native，这就不是问题。
> 黑屏的问题，我修改了GSYRenderView.java的addToParent函数，手动调用measure和layout函数，试了好多次，暂时没发现黑屏了。
> 我目前的问题是解决了，还有个小问题是播放视频的准备时间有点久。
> 再次感谢您的视频库。
大佬怎么联系你 我付费给我集成一下这个播放器可以吗 我集成的 全屏按钮不管用

**Comment by yubaokang** [comment]
> 在React Native中，ReactActivity继承于Activity。CommonUtil.getAppCompActivity(context)返回null，所以会闪退。如果不打算支持react native，这就不是问题。
> 黑屏的问题，我修改了GSYRenderView.java的addToParent函数，手动调用measure和layout函数，试了好多次，暂时没发现黑屏了。
> 我目前的问题是解决了，还有个小问题是播放视频的准备时间有点久。
> 再次感谢您的视频库。

代码能否贴一下？
