### ISSUE TITLE
android.resource:// 怎么能识别这样的路径

### ISSUE THREAD

**Issue by Biswangluo** [CarGuo/GSYVideoPlayer#983]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
把视频放到了raw 里面 
然后路径 "android.resource://" +getPackageName() + "/" + R.raw.video3
不能识别这样的路径 

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

04-03 10:57:11.787 21635-21967/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
04-03 10:57:11.796 21635-22396/com.example.gsyvideoplayer E/IJKMEDIA: android.resource://com.example.gsyvideoplayer/2131558403: Protocol not found
04-03 10:57:11.796 21635-21967/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
04-03 10:57:11.802 21635-21635/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
04-03 10:57:11.802 21635-21635/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Again android.resource://com.example.gsyvideoplayer/2131558403
04-03 10:57:11.808 21635-21967/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

xxxxxxx

```

**Comment by CarGuo** [comment]
ijk模式不支持raw等播放

**Comment by Biswangluo** [comment]
https://www.jianshu.com/p/9f4379e14ab6

在网上查 要这么改才能支持 但封装之后 不知道改那里了

**Comment by Biswangluo** [comment]
https://github.com/Bilibili/ijkplayer/issues/2043 ijk 那边提的问题

**Comment by CarGuo** [comment]
如果你想用这类型自定义soure的，那么你需要先参考源码和demo自定义Manager和Player就可以了

**Comment by Biswangluo** [comment]
@CarGuo 谢谢老哥 已解决 ijk不支持 我切换到系统播放器就可以了
