### ISSUE TITLE
哥，demo中能不能加个一进来就是全屏播放的例子啊，没有状态栏和导航栏

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#984]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
如果你的意思是一打开就横屏的话，那你直接配置activity不就可以了吗，然后activity设置全屏
