### ISSUE TITLE
与slidableactivity配合实现滑动返回时 activity卡顿

### ISSUE THREAD

**Issue by kidc1412** [CarGuo/GSYVideoPlayer#985]
与slidableactivity配合实现滑动返回时 activity会有卡顿闪屏的问题

**Comment by CarGuo** [comment]
播放时 slide动画效果会卡顿很正常，因为你播放中和滑动中的帧渲染都是占据资源的。滑动过程中最好暂停播放

**Comment by kidc1412** [comment]
暂停也会卡 会是那种拉扯的感觉 你往右滑 整个activity就会往左边拉

**Comment by CarGuo** [comment]
你释放播放看看

**Comment by kidc1412** [comment]
是用GSYVideoManager.instance().releaseMediaPlayer()吗?
问题情况应该是出在了播放的时候
播放之前是滑动activity是正常且流畅 只要开始播放你再滑动
你会看到一个鬼畜的activity

**Comment by CarGuo** [comment]
这种场景，只弄说怎么取舍
