### ISSUE TITLE
请教可否实现透明背景的视频功能?

### ISSUE THREAD

**Issue by ruidge** [CarGuo/GSYVideoPlayer#986]
对实现透明背景的视频有什么思路或者说有什么难点?效果如链接:
https://zhuanlan.zhihu.com/p/34608752
试了用 ijk 原生的播放有透明的通道的 mov 格式的 背景是黑色,不知大神有什么思路?

**Comment by CarGuo** [comment]
因为渲染层无论是textureview还是surfaceview甚至glsurfaceview，都是无法设置透明背景的。类似你这种需要，短一些的时候适合用svg 类似这类吧 https://github.com/yyued/SVGAPlayer-Android

**Comment by ruidge** [comment]
GLSurfaceView 可以实现透明的效果之前在别的需求试过需要设置
setZOrderOnTop(true);
并且onDrawFrame里面绘制前GLES20.glClearColor(0.f, 0.f, 0.f, 0.f);就可以

**Comment by CarGuo** [comment]
那你可以试试修改demo的GL演示尝试下
