### ISSUE TITLE
请教关于列表播放，滑动切换到悬浮小窗口播放的问题

### ISSUE THREAD

**Issue by jlertele** [CarGuo/GSYVideoPlayer#987]
请问demo是如何做到平滑切换到悬浮窗播放且没有任何暂停黑屏缓冲的情况？是直接将列表中的videoview从布局删除后，直接add到悬浮窗布局中吗？

**Comment by CarGuo** [comment]
不是，是新new了一个渲染布局，设置给播放内核

**Comment by jlertele** [comment]
那有个需求，我在A页面播放视频，关闭A页面进入B页面，想把A页面的播放画面和状态set到B页面某个布局中，请问有什么比较好的处理方式么？

**Comment by CarGuo** [comment]
在A的时候不release，然后到b的时候，把直接构建播放器，然后添加渲染层给播放内核，不调用播放
