### ISSUE TITLE
GSYTextureView   相关的疑问

### ISSUE THREAD

**Issue by XXiaoQing** [CarGuo/GSYVideoPlayer#99]
GSYTextureView   是继承  TextureView 的，在官方介绍中有这句话“TextureView can only be used in a hardware accelerated window. When rendered in software, TextureView will draw nothing.”，使用TextureView  必须开启硬解码，但是在项目中我看没有开启硬解码也能播放视频，请问是怎么回事呢

**Comment by CarGuo** [comment]
这个view是由ffmpeg绘制的，不经过java
