### ISSUE TITLE
如何向播放器内部传递数据

### ISSUE THREAD

**Issue by KafukaChen** [CarGuo/GSYVideoPlayer#990]
标题可能有些模糊。是这样的，全屏播放的时候有分享需求，需要拼接一些参数，有些参数是需要从外面传递进来的。我用如下方法构建的播放器 
gsyVideoOptionBuilder
                .setIsTouchWiget(false)
                .setThumbImageView(mThumb)
                .setUrl(url)
                .setCacheWithPlay(true)
                .setRotateViewAuto(false)
                .setLockLand(false)
                .setPlayTag(TAG)
                .setShowFullAnimation(false)
                .setNeedLockFull(false)
                .setThumbPlay(true)
                .setLooping(true)
                .setIsTouchWigetFull(false)
                .setNeedShowWifiTip(false)
                .setMapHeadData(map)
                .setDismissControlTime(1500)
                .build(mVideo);
请问如何传递基本类型的参数进来

**Comment by CarGuo** [comment]
不是很理解你需要传递什么，如果需要自定义，你可以继承后，添加你需要的参数，记得在充值cloneParmas方法中，切换全屏和非全屏时保存同步就好

**Comment by KafukaChen** [comment]
比如我要获取当前url，直接有 mOriginUrl 可以用，但是我的需求里还需要一些其他的参数需要创建播放器对象或者构造播放器的时候传进来，找不到方法
