### ISSUE TITLE
surface_container为RelativeLayout时旋转视频被压扁

### ISSUE THREAD

**Issue by g19980115** [CarGuo/GSYVideoPlayer#993]
## 问题描述：

`surface_container`为`RelativeLayout`时旋转视频被压扁

## 问题机型/系统：

OnePlus5，Android8.0.1

## Demo中的复现步骤

将`sample_video.xml`的`surface_container`从`FrameLayout`改为`RelativeLayout`，然后运行demo，播放视频后点击旋转画面

视频链接: [http://qiniu.carmmi.com/image/FoZsf-QasOOEAsW-1hLop2mKRFfN.mp4](http://qiniu.carmmi.com/image/FoZsf-QasOOEAsW-1hLop2mKRFfN.mp4)

问题截图：[图片链接](https://user-images.githubusercontent.com/25760230/38476269-649dff58-3bdf-11e8-8e13-ccb6713c0e9b.jpg)

用`FrameLayout`是没有问题的，但是demo中的RecyclerView部分用的是`RelativeLayout`

**Comment by CarGuo** [comment]
我记得是有写着注释，需要在某些情况使用FrameLayout
