### ISSUE TITLE
播放器播放后，跳转activity后还在播放？

### ISSUE THREAD

**Issue by i2863CookieZJ** [CarGuo/GSYVideoPlayer#994]
protected void onPause() {
        getCurPlay().onVideoPause();
        super.onPause();
   
        GSYVideoManager.onPause();
        isPause = true;
    }

**Comment by CarGuo** [comment]
demo哪里复现

**Comment by i2863CookieZJ** [comment]
detailplayer

**Comment by yanchengdeng** [comment]
同样遇到这个问题 ，视频还未播放时候，快速返回到上一页  ，视频还会播放！

**Comment by CarGuo** [comment]
detailplayer没有复现问题。release是否了应该不会播放，你可以直接调用Manager的释放
