### ISSUE TITLE
压缩过的视频播放没有进度

### ISSUE THREAD

**Issue by MuseYkh** [CarGuo/GSYVideoPlayer#995]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

压缩过的视频播放没有进度，有总时长，系统自带播放器可以正常显示，压缩前进度也是有的。

## 问题机型/系统：

真机 努比亚Z11minis Android6.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后也会出现这个问题。

问题代码：(如果有)

**Comment by CarGuo** [comment]
如果这样那是因为ffmepg解析问题，没什么办法

**Comment by MuseYkh** [comment]
我看了下我用的那个压缩的用的  Hardware decoding and encoding API(MediaCodec)，据维护的人说是这个库只做了图像的处理，没有改变meta数据

**Comment by CarGuo** [comment]
按照ijk的FFmpeg，应该是音频问题导致的

**Comment by MuseYkh** [comment]
那没有解决的方案吗？

**Comment by CarGuo** [comment]
通过GSYVideoType切换到surface配合exo模式试试
