### ISSUE TITLE
横屏状态播放问题！

### ISSUE THREAD

**Issue by Born-alone** [CarGuo/GSYVideoPlayer#998]
项目中需要实现一个功能  一个视频列表 播放完一个以后要自动播放下一个视频 
在竖屏状态下没有问题  但是在横屏状态下切换到下一个视频时就有问题了: 全屏的播放界面卡住了（只有一个返回阿牛 还有一个点击锁屏按钮）、视频没有画面 有声音、再切换回竖屏还是没有视频画面 情况相同； 

这个是我每次播放一个新视频的代码，自动播放下一个视频资源就是调用的这个方法播放！
private void playVideo(String videoUrl) {
        customizeControlVideo.clearThumbImageView();
        customizeControlVideo.getSubscribe_course_ll().setVisibility(View.GONE);
        customizeControlVideo.getPlay_audio_tv().setVisibility(View.GONE);
        customizeControlVideo.release();
        customizeVideoOptionBuilder.setUrl(videoUrl).
                setCacheWithPlay(true).setCachePath(new File(FileUtils.getPath())).build(customizeControlVideo);
        customizeControlVideo.postDelayed(new Runnable() {
            @Override
            public void run() {
                customizeControlVideo.playSeekOnStartPosition(DbVideoID);
                customizeControlVideo.startPlayLogic();
            }
        }, 1000);
    }

**Comment by CarGuo** [comment]
你必须把方法和参数在横屏与竖屏切换的时候同步，参考demo或者源码的cloneParams

**Comment by Born-alone** [comment]
方法和参数同步 ？ 还没有明白！

**Comment by Born-alone** [comment]
我的现象的横屏状态下自动播放下一个视频时 视频有声音没画面 界面只有返回按钮与锁屏按钮  底下进度条及控制那一块没有

**Comment by Born-alone** [comment]
一直在横屏状态切换下自动切换下一视频就会有问题

**Comment by Born-alone** [comment]
cloneParams 方法不是只有横屏切换的时候才会调用嘛  我已经就是横屏状态了
